### DISCUSSION TITLE
allow action_name to use non capitals

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#10171] [Dashboard] [answered]
when using
```
action_name: 'Turn off'
```
in an entities card on button or entity, 
```
      - entity: script.audio_system_off
        action_name: 'Turn off'
        tap_action:
          confirmation:
            text: Are you sure?
      - type: button
        name: Audio system off
        action_name: 'Turn off'
        icon: mdi:audio-video-off
        tap_action:
          action: call-service
          confirmation:
            text: Are you sure?
          service: script.audio_system_off
```

this gets capitalized to:

<img width="476" alt="Schermafbeelding 2021-10-06 om 17 03 30" src="https://user-images.githubusercontent.com/33354141/136230491-ae4e8297-24e2-4d5e-958b-e31b58d23e2b.png">

which isnt what the user sets in the card config.

Please consider using the exact text set on the `action_name:` option
thanks.
