### DISCUSSION TITLE
add require_admin:  to individual view and cards options

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#10349] [Dashboard]
aware we can set full dashboards using the `require_admin: true` option, it would still be very flexible and easy to configure if we could set this on a single view too. Even more so on individual cards.

That way, we can organize the views in a coherent way, and still safe a couple of those for the admin only. All other view could be seen by all.

We can reach the same end goal probably, but that would require the opposite workflow: add all users to all other views. besides that we would need the explicit user id, instead of the better `require_admin: true`

```
views:
  - title: Admin
    require_admin: true
    cards:
      ...
```
```
  - type: entities
    title: Only for admins
    require_admin: true
    entities:
      - sensor.secret1
      - sensor.seecret2
```
please consider?
thanks 

https://next.home-assistant.io/lovelace/views/#visible
https://next.home-assistant.io/lovelace/dashboards/
