### DISCUSSION TITLE
Modify values when shown on a Lovelace card

### DISCUSSION THREAD

**Discussion by matphillips** [home-assistant/frontend#10365] [Dashboard]
I noticed the "sensor.total_daily_energy_cost" and thought it may be nice to add it to my 'power' card dashboard. It does work, but the value of that sensor is (currently) 68.2198 which is a little more precise than I really need. (Especially as I am using Japanese Yen for the currency, and fractions of a yen are not actually a thing)

I want to be able to modify the value when shown in the card. Simply rounding the number will be fine. A value of 68 here is plenty informative.

```
- type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.amps1
      - type: entity
        entity: sensor.amps2
      - type: entity
        entity: sensor.total_daily_energy_cost
```

Any way to add a filter or something here?
Thanks.
