### DISCUSSION TITLE
[Feature Request] advanced Logbook card settings

### DISCUSSION THREAD

**Discussion by scheusal333** [home-assistant/frontend#10463] [Other feature requests]
I would like the logbook card to be more customizable with the following simple features:

**1. in addition to "hours to show" it would be nice to set a "trigger" like "since status of entitie x is y"**
**2. a filter of states that should be logged,** (eg. only motion sensor state "motion detected" should be loged/shown but "calm/no motion" will not.)

Here is an example how this two options can improve the logbook:

This is currently possible with the logbook card as an overview of events when i am not at home:

> since last 1 hour:
> - Front door changed to "open"
> - Fron door changed to "close"
> - Phone changed to "away"
> - back door changed to "open"
> - motion sensor livingroom was triggered
> - motion sensor livingroom changed to "calm"
> - back door changed to "close"

With the two new requested options it is possible to set a trigger event and filter for relevant events to show up in the logbook card:

> since status of Phone is "away":
> - Back door  changed to "opened"
> - motion sensor livingroom was triggered

**Comment by ildar170975** [comment]
I need at least a `name` option:
```
          - type: logbook
            hours_to_show: ...
            entities:
              - entity: ...
                name: XXXX
              - entity: ...
                name: YYYY
```
Now I have to specify a `friendly_name` for these entities.
But sometimes it is required to use another names in a logbook.
