### DISCUSSION TITLE
add top level option secondary_info:

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#10599] [Dashboard]
for the sake of convenience and prevent huge amounts of repeating yaml lines in cards, it would be a huge step if we could use a top_level card config option like

```
    type: entities
    secondary_info: last-triggered
    entities:
      - automation.sense_family_home_change
      - automation.sense_critical_devices_change
      - automation.sense_hubs_change
      - automation.sense_lights_change
      - automation.sense_doors_change
```
in stead of:

```
    type: entities
    entities:
      - entity: automation.sense_family_home_change
        secondary_info: last-triggered
      - entity: automation.sense_critical_devices_change
        secondary_info: last-triggered
      - entity: automation.sense_hubs_change
        secondary_info: last-triggered
      - entity: automation.sense_lights_change
        secondary_info: last-triggered
      - entity: automation.sense_doors_change
        secondary_info: last-triggered
```

ofc, last_changed will be among the other much used options set if made possible, on entities like lights, switches or booleans.

Hope you can have a look
thanks!
