### DISCUSSION TITLE
Option to expand group objects everywhere

### DISCUSSION THREAD

**Discussion by l-mb** [home-assistant/frontend#11044] [Dashboard]
Unfortunately, the YAML mode for Lovelace doesn't support templates.

One of the features I miss the most is the ability to refer to all members of a group objects; that'd allow me to maintain a consistent set of entities between my frontend and automations etc. This, alas, does not even work in places that are prepared to accept lists of entities.

Consider this simplistic (abbreviated) example:

```
      - type: entity-filter
        show_empty: false
        entities:
          - entity: binary_sensor.opening_window_1_state
            secondary_info: last-changed
          - entity: binary_sensor.opening_window_2_state
            secondary_info: last-changed
...
```

I have to list every single sensor separately and specify further options, even if I have a `group.all_windows`; I don't want the UI to show whether any window is open, but the details.

If children of `entities` supported not just `entity`, but `group_entity:`, which then expanded and repeated the block they're in for each member of the `group`, this block could then look like this:

```
      - type: entity-filter
        show_empty: false
        entities:
          - group_entity: group.all_windows
            secondary_info: last-changed
```

Since this is not dynamic scripting nor templating but "trivial" expansion, it'd only have to be expanded once by the YAML parser when the configuration is loaded.

Would this be a possible feature to consider?
