### DISCUSSION TITLE
Persistent Notification Card

### DISCUSSION THREAD

**Discussion by JustinDwy** [home-assistant/frontend#11189] [Other feature requests]
I suggested this card in a forum thread, and it was suggested it would be a great idea for core.
Thread: https://community.home-assistant.io/t/custom-lovelace-card-ideas/88883/10

Anyways, some type of Persistent Notification card would be cool. Currently I'm using a combination of the conditional and the custom useful markdown cards to display a persistent notification but this doesn't give me the ability to dismiss the notification. 

Maybe an option to always display the card, so it could be like a permanent notification window ( people could create an automation that if there's no current notification then display a random fact or something ). Or hide the card if no notifications are present. 

Being able to style the text colour or border or something of the notification would be cool too. So that a notification that is more important could be displayed more prominently.

**Comment by victorcerutti** [comment]
Hi, I had the exact same idea and opened an issue to discuss it on the architecture repo.
Let's continue the discussion here,
This was my proposal for such notifications, adding parameters `visible`, `severity` and `icon`
![capture d ecran 2019-02-25 a 14 22 47](https://user-images.githubusercontent.com/3236171/53340304-f7b70880-3908-11e9-8f9c-5c7ba34c9f1a.jpg)
```yaml
action:
  service: persistent_notification.create
  data:
    message: "Strong wind expected tonight between 8pm and 11pm."
    title: "Emergency alert"
    visible: true
    icon: mdi:weather-windy
    severity: emergency

```
