### DISCUSSION TITLE
automatically generated views by area and/or domain

### DISCUSSION THREAD

**Discussion by iantrich** [home-assistant/frontend#11199] [Other feature requests]
Option to set a view as a generated view that is either determined by a particular `area` and/or `domain`
```yaml
views:
  - title: Kitchen
    area: kitchen
  - title: Lights
    domain: light
```
