### DISCUSSION TITLE
Customize Layout of Lovelace View

### DISCUSSION THREAD

**Discussion by jjpeet** [home-assistant/frontend#11191] [Other feature requests]
I've spent a few hours with Lovelace today and generally I'm finding it pretty flexible, and extremely fast.

One thing I have struggled with is defining where cards go. They tend to have a mind of their own. At least I would like to define the order of display from top left over to bottom right.

I'd like a little more control over layout in general.
Thx
JP

**Comment by zsarnett** [comment]
You can currently do this using Horizontal and Vertical stacks. But leaving this Request open as I believe a better solution is needed. I just have to figure out how to do that

**Comment by balloob** [comment]
This comment still really holds up: https://github.com/home-assistant/ui-schema/issues/123#issuecomment-406976025

**Comment by zsarnett** [comment]
https://github.com/thomasloven/lovelace-layout-card

@thomasloven has created a custom card for this. Using it to test different ways to do this

**Comment by zsarnett** [comment]
My points:

 * Ability to specify Number of Columns in a view: Very helpful and will extend use of vertical stacks
 * Making the panel variable a string or better yet just make the option extend the columns to the full width of the page instead of choosing the first card and extending it... If they want that just use one card 🤔 
 * As Balloob mentioned in Discord, default should be what it is now for new/less advanced users but giving more advanced users more options (not all the options 😄 ) to customize the layout

**Comment by emlove** [comment]
IMO it would be interesting to explore some client-side control of the layout, since this is pretty specific to the screen that it's being viewed on. As a rough idea, the users could enter "edit" mode for a view, and drag/drop rearrange the cards how they make sense on this device.

**Comment by iantrich** [comment]
for the UI editor, I envision a user being able to select "new row" and dragging/dropping whatever cards they want in there and selecting a card size of small/med/large. how that would translate to implementation or even populating in a configuration I'm not sure of, though

**Comment by Webserve** [comment]
At the moment I’m  testing with the new lovelace layout and missing this feature.

"Ability to specify Number of Columns in a view: Very helpful and will extend use of vertical stacks" <-

**Comment by zsarnett** [comment]
| hui-view.js
```javascript
    const columnCount = config.columns || this.columns;

    for (let i = 0; i < columnCount; i++) {
      columns.push([]);
      columnEntityCount.push(0);
    }
    elementsToAppend = elements.filter((el, index) => {
      const column = config.cards[index].column;

      if (column && column <= columns.length) {
        columns[column - 1].push(el);
        columnEntityCount[column - 1] += computeCardSize(el);
        return false;
      }
      return true;
    });

    elementsToAppend.forEach((el) => {
      const cardSize = computeCardSize(el);
      // Element to append might be the wrapped card when we're editing.
      columns[getColumnIndex(cardSize)].push(el);
    });
```
This adds `columns` to view config. 
```yaml
views:
  - id: '1' # Automatically created id
    title: Testing Grounds
    columns: 3
    cards: {...}
```

And `column` to card config. Position within the column is based on order in YAML file.
```yaml
- id: '1234'
  type: entities
  show_header_toggle: true
  column: 1
  entities: {...}
```


I think this could be implemented easily with our new editor with drag and drop but also with a Position and Column field in the UI editor. Position would move the index within the view config cards and Column would change the column variable in the card Config.

@balloob @bramkragten

**Comment by bramkragten** [comment]
You would also need to take into account that it has to work on different kinds of screens. It is hard to make this responsive...

Not technically, but from a UX point.

**Comment by zsarnett** [comment]
Columns would stack one after the other for mobile. And we could show an outline of the column for editing the layout easier in a mobile stand point

**Comment by zsarnett** [comment]
```javascript
const columnCount =
      this.columns <= 1 || !config.columns ? this.columns : config.columns;
```
This allows for for the cards to stack in the order they are in (index with in view.cards) if width is for 1 column  and also accounts for no columns.

**Comment by zsarnett** [comment]
This also doesn't remove the current capabilities that we offer for auto sorting. If you only add `column` to some cards the rest will be sorted as they are today. Into the shortest/smallest column

I think this could be the first step into making a better system for users to customize their layout. If using the editor it would be easy to sort them by column then by index so that when its on mobile its still the same layout. We could even just build that straight into the mobile viewing. Sort ElemetsToappend by column then index

**Comment by zsarnett** [comment]
I would also like to propose making `panel: true` mean making the columns full width of the screen. AKA if there are 3 columns that means each column is 33% in width.

If you only want 1 card to show. Only supply one card to the view and it will still be a 100% width card

From this:
![image](https://user-images.githubusercontent.com/18730868/49758285-90d06e80-fc8c-11e8-86af-6322053446c9.png)

To this:
![image](https://user-images.githubusercontent.com/18730868/49758292-9463f580-fc8c-11e8-966e-c9887189671b.png)

**Comment by marc-gist** [comment]
just curious how work is going on this before I look to custom cards to solve my similar issues?

Thanks!!

**Comment by Smiggel** [comment]
Is there any progress? I have the same kind of issue where my cards seem to go all over the place when I want to sort them. I love the UI editor, but not able to move the cards to the position I want them in, is a shame.

**Comment by vel2000** [comment]
> I have the same kind of issue where my cards seem to go all over the place when I want to sort them

+1 for customizable columns and drag and drop of the cards. ^^

**Comment by mike391** [comment]
I feel like drag and drop is the one thing that HASS needs to become significantly better. Its easy to do a lot of things except its a nightmare to organize card in the UI. Drag and Drop would save a lot of time and reduce headaches for many users.

**Comment by iantrich** [comment]
muuri library is still our best bet on this, I think. I start a POC based of @bramkragten 's work, but have yet to get it working properly: https://github.com/custom-cards/muuri-grid

**Comment by Misiu** [comment]
A drag-and-drop editor would be awesome addition. Right now you only can move cards up and down, but this isn't the best option - it isn't easy to rearrange items.
Specifying number of columns is another great ideal.
Imagine you want to display 5 items, but in 2 columns, so You want to get this view:

![image](https://user-images.githubusercontent.com/1741838/66298206-89501500-e8f1-11e9-93c8-1c4e0a04bbb6.png)

currently, the only option I found is to use `gap-card`:
```

cards:
  - cards:
      - entity: climate.salon
        type: thermostat
      - entity: climate.sypialnia
        type: thermostat
    type: horizontal-stack
  - cards:
      - entity: climate.dzieciecy
        type: thermostat
      - entity: climate.korytarz
        type: thermostat
    type: horizontal-stack
  - cards:
      - entity: climate.lazienka
        type: thermostat
      - type: 'custom:gap-card'
    type: horizontal-stack
type: vertical-stack
```

but with columns support, I could rewrite this to:
```
cards:
  - cards:
      - entity: climate.salon
        type: thermostat
        column: 1
      - entity: climate.sypialnia
        type: thermostat
        column: 1
    type: horizontal-stack
  - cards:
      - entity: climate.dzieciecy
        type: thermostat
        column: 1
      - entity: climate.korytarz
        type: thermostat
        column: 1
    type: horizontal-stack
  - cards:
      - entity: climate.lazienka
        type: thermostat
        column: 1
    type: horizontal-stack
type: vertical-stack
```
 There is one issue I find very annoying and I think many users will agree:
When adding new cards there should be an option to preconfigure them (for example in cards.yaml ?)
I have a grid that shows 6 mini-graph-cards in 2x3 grid. My yaml looks like this:
```
cards:
  - cards:
      - color_thresholds:
          - color: '#f39c12'
            value: 21
          - color: '#d35400'
            value: 22
          - color: '#c0392b'
            value: 22.5
        entities:
          - sensor.temperatura_na_zewnatrz
        hour24: true
        hours_to_show: 24
        name: Na zewnątrz
        points_per_hour: 0.5
        show:
          fill: true
          labels: false
          state: true
        type: 'custom:mini-graph-card'
        update_interval: 10
      - color_thresholds:
          - color: '#f39c12'
            value: 21
          - color: '#d35400'
            value: 22
          - color: '#c0392b'
            value: 22.5
        entities:
          - sensor.temperatura_salon
        hour24: true
        hours_to_show: 24
        name: Salon
        points_per_hour: 0.5
        show:
          fill: true
          labels: false
          state: true
        type: 'custom:mini-graph-card'
        update_interval: 10
    type: horizontal-stack
  - cards:
      - color_thresholds:
          - color: '#f39c12'
            value: 21
          - color: '#d35400'
            value: 22
          - color: '#c0392b'
            value: 22.5
        entities:
          - sensor.temperatura_sypialnia
        hour24: true
        hours_to_show: 24
        name: Sypialnia
        points_per_hour: 0.5
        show:
          fill: true
          labels: false
          state: true
        type: 'custom:mini-graph-card'
        update_interval: 10
      - color_thresholds:
          - color: '#f39c12'
            value: 21
          - color: '#d35400'
            value: 22
          - color: '#c0392b'
            value: 22.5
        entities:
          - sensor.temperatura_dzieciecy
        hour24: true
        hours_to_show: 24
        name: Dziecięcy
        points_per_hour: 0.5
        show:
          fill: true
          labels: false
          state: true
        type: 'custom:mini-graph-card'
        update_interval: 10
    type: horizontal-stack
  - cards:
      - color_thresholds:
          - color: '#f39c12'
            value: 21
          - color: '#d35400'
            value: 22
          - color: '#c0392b'
            value: 22.5
        entities:
          - sensor.temperatura_korytarz
        hour24: true
        hours_to_show: 24
        name: Korytarz
        points_per_hour: 0.5
        show:
          fill: true
          labels: false
          state: true
        type: 'custom:mini-graph-card'
        update_interval: 10
      - color_thresholds:
          - color: '#f39c12'
            value: 21
          - color: '#d35400'
            value: 22
          - color: '#c0392b'
            value: 22.5
        entities:
          - sensor.temperatura_lazienka
        hour24: true
        hours_to_show: 24
        name: Łazienka
        points_per_hour: 0.5
        show:
          fill: true
          labels: false
          state: true
        type: 'custom:mini-graph-card'
        update_interval: 10
    type: horizontal-stack
type: vertical-stack
```

Ideally, I should be able to define that large yaml once (in cards.yaml) and when I click on the plus to add new card there should be a list of preconfigured cards. This will be super useful when you want to create multiple users and give them the ability to easily configure the UI.
With centralized card configuration, there is also one big advantage - when you want to change something you must do that in a single place and all users will get an update.

The above yaml could be then rewritten to:
```
type: card-template
template_name: mini-graph-grid
```
What do you guys think? Is this something that not only I would find super helpful 😉
