### DISCUSSION TITLE
Time alignment between multiple entities in history graph

### DISCUSSION THREAD

**Discussion by rzolau** [home-assistant/frontend#11265] [Other feature requests] [answered]
#5302  The request

Provide additional parameter to set, or enforce by default, alignment of time in History Graph Card. Currently, when two different entities are plotted, that use different units, both plots use different scaling for time axis. As a result, the plots are misaligned (see attached image). This makes visual data analysis challenging, can be misleading and is aesthetically problematic.
In the image below, observe how 3am tic is shifted between the plots (plots have been generated using the following YAML):

```
                - type: history-graph
                  hours_to_show: 24
                  refresh_interval: 30
                  entities:
                    - entity: sensor.some_temperature
                      name: "Temperature"
                    - entity: binary_sensor.some_binary_state
                      name: "State"
```

<img width="509" alt="Screen Shot 2020-05-27 at 21 43 40" src="https://user-images.githubusercontent.com/42065977/83088980-2e775380-a063-11ea-9e77-d2d8c81fe754.png">

## The alternatives

Currently, there is no real alternative. One can play with the 3rd party `mini-graph-card` but this is sub-optimal as styling of the history graph card and mini-graph-card is visibly different.

## Additional information

Potential alternative, which could be more visually interesting (or not), is to overlay categorical plot on top of the numerical plot with added transparency. This way different categorical states become zones over numerical plot (mock card below).

![mock](https://user-images.githubusercontent.com/42065977/83090277-6764f780-a066-11ea-976b-032171711ec5.png)
