### DISCUSSION TITLE
Pass line styling options through to ChartJS

### DISCUSSION THREAD

**Discussion by AAllport** [home-assistant/frontend#11308] [Other feature requests]
## The request
Add a mechanism to pass ChartJs options to cards such as the Line Graph.
Notably `SteppedLine`
This will allow people to choose between displaying a Stepped line graph, and a much more pleasing interpolated graph, without having to add _unnessasary_ integrations (for interpolation on the data-side of things)

Ideally, users should be able to set the default for the `history` component, with the ability to override it on a per sensor basis (via `customize`)

Feels like adding a key to the Lovelace config to house any raw params to pass straight through to ChartJs could work well
Eg:
```yaml
type: history-graph
entities:
  - entity: sensor.foo_temp
hours_to_show: 24
refresh_interval: 0
title: Temperatures
chartjs:
  steppedLine: false
```

## The alternatives
As far as I have seen, this is possible with various custom Lovelace cards, however, that seems overkill.

## Additional information
Ex: https://www.chartjs.org/docs/latest/charts/line.html#line-styling

**Comment by AAllport** [comment]
Nb: I'd love to contribute to this myself if that's possible!

That being said, my server-side python is very Rusty.
Sounds like this would require backend changes to facilitate the config, which is where I believe I'd struggle

**Comment by gb53smith** [comment]
Also test with an entity_id which is an input_number.  
My workaround was to "convert" a sensor to an input_number using this example automation:
```
- alias: Temperature
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.mysensors_bme280_2_2
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.temperature
        value: "{{ states('sensor.mysensors_bme280_2_2')}}"
```
input_number plots with a linear spline.  It also has the side benefit that the last value is stored.  My graphs with a sensor would show a negative spike to zero if I rebooted the Raspberry Pi.
