### DISCUSSION TITLE
Add transition parameter support to light card

### DISCUSSION THREAD

**Discussion by LarsMudde** [home-assistant/frontend#11525] [Dashboard]
Hi everyone,

I have a Qubino Mini Dimmer and it updates very slow because it uses the configured transition time of the button on the wall to transition between states when using HomeAssistant. This means moving the slider from 20 to 80% takes 6 (for the lamp but also for the ui to update). 

I've fixed this (after some help) by using an automation and a helper (numeric).
```
alias: New Automation
description: ''
trigger:
  - platform: state
    entity_id: input_number.qubino_dimmer_brightness_pct
condition: []
action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ states(''input_number.qubino_dimmer_brightness_pct'')|int }}'
      transition: 0
    target:
      entity_id: light.mini_dimmer
mode: restart
```
This works less well than the light card, and I like the light card better. But there's no way for me to (optionally) feed the transition parameter to the light card. Therefore I'm suggesting we add transition as a parameter on the light card so we can set it for dimmers or other devices that require it.

https://github.com/zwave-js/zwavejs2mqtt/issues/2226

This might also require back-end changes, I'm not sure.

Regards,

Lars
