### DISCUSSION TITLE
Revert Button row to previous design - Discussion

### DISCUSSION THREAD

**Discussion by Masterz69** [home-assistant/frontend#11639] [Dashboard]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/15225823/150306820-7679351b-2285-47b9-8b16-31c6f7d2082c.png)
^^ it looks now totally awful & terrible ... it totally not in line with existing design.

Is it possible to have a switch to use legacy/previous design, not this one ?

### Describe the behavior you expected

Same look as in 2021.11.4, as documented:
![image](https://user-images.githubusercontent.com/15225823/150311907-3a2e8ede-95b6-472e-93c0-92dbfee90c52.png)

### Steps to reproduce the issue

no steps. just existing lovelace.

### What version of Home Assistant Core has the issue?

core-2021.12.10

### What was the last working version of Home Assistant Core?

core-2021.11.4

### In which browser are you experiencing the issue with?

Chrome 97.0.4692.71

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
cards:
      - type: vertical-stack
        cards:
          - type: entities
            show_header_toggle: false
            state_color: true
            entities:

              - type: buttons
                entities:
                  - entity: alarm_control_panel.shed

...
```

### Additional information

As well nothing in https://www.home-assistant.io/blog/2021/12/11/release-202112/#release-2021121---december-12 mentioned about changes in entities lovelace card. Can't find any relevant info.

**Comment by Masterz69** [comment]
Found this one: https://github.com/home-assistant/frontend/pull/10770
IMHO this is a BAD idea to change entities buttons row design so dramatically.
Asking to revert to previous entities card buttons row design, as on 2021.11.4.

**Comment by MrLuit** [comment]
+1 on this issue, I have a configuration similar to this:

```
  - type: entities
    entities:
      - type: buttons
        entities:
          - entity: light.A
          - entity: light.B
          - entity: light.C
  ````

Expected behaviour (pre-updating):
![image](https://user-images.githubusercontent.com/12037024/153086668-f80f0412-9226-4879-bccd-3bb488776089.png)

Actual behaviour (post-updating):
![image](https://user-images.githubusercontent.com/12037024/153086758-c94a01bc-abfd-474a-b64c-79b7676e9474.png)

While I can understand the change of putting icons in a chip component, the horizontal container should probably still have the same flex properties, which it does not. The `justify-content: space-evenly;` was removed [here](https://github.com/home-assistant/frontend/pull/10770/files#diff-e9bb038a47e87defc2aa5f13a364b340f490ed5664ec98ebb19a8f7c6d7a404eL67). By adding this property to the `.ha-scrollbar` div manually using DevTools, the spacing is fixed.

![image](https://user-images.githubusercontent.com/12037024/153087990-392e9d7b-879c-40bc-97a2-7de35606e112.png)

The layout is still different, so I'm a bit confused as to why #10770 is marked as `Code quality improvements to existing code or addition of tests`, instead of `Breaking change (fix/feature causing existing functionality to break)`. I do not believe the author of this PR did this with malicious intent, but it might explain why this change wasn't documented properly.
