### DISCUSSION TITLE
Fire event

### DISCUSSION THREAD

**Discussion by antonio1475** [home-assistant/frontend#11773] [Dashboard]
Developer Tools can Fire Event.
A Script/Automation can Fire Event.
iOS app cann Fire Event through Siri Shortcuts.

However, HA Frontend has no way to directly fire an Event through a button/tap action? Which causes overcomplications (additional script, additional trigger, etc) when trying to do so, to trigger (multiple) automations with the same trigger that are already being used (switches, etc).

Something like
```
tap_action:
  action: call-service
  service: fire_event
  event: action
  service_data:
    command: tele
```

or 
```
tap_action:
  action: event
  event: action
  service_data:
    command: tele
```

**Comment by Soukyuu** [comment]
A long search and lack of search results lead me here. There seems to still not me a way to fire an event on a button tap.

**Reply by dhoeben** [reply]
Well... https://www.home-assistant.io/docs/scripts/#fire-an-event

**Reply by antonio1475** [reply]
> Well... https://www.home-assistant.io/docs/scripts/#fire-an-event

Hi. That doesn't change anything? From the original message:

> Developer Tools can Fire Event.
> A Script/Automation can Fire Event.
> iOS app cann Fire Event through Siri Shortcuts.
> 
> **However, HA Frontend has no way to directly fire an Event through a button/tap action**

The request here was to be able to fire events from a front-end button, without passing through a script.

**Reply by dhoeben** [reply]
You said: "There seems to still not me a way to fire an event on a button tap.", but there is.

If you create a script, you can make it as dynamic as you want. I believe this would work.
```
script:
  fire-event:
    alias: "Fire an event"
    mode: single
    sequence:
    - event: "{{ name }}"
      event_data: "{{ event_data }}"
```

and call it like this:
```
tap_action:
  action: perform-action
  perform_action: script.fire-event
  data:
    name: "Event-name"
    event_data:
      state: "on"
      more-relevant: "abc"
```
