### DISCUSSION TITLE
Allow the Time of Day helper to use `sun` and add offsets

### DISCUSSION THREAD

**Discussion by mehuman** [home-assistant/frontend#12237] [Automations / scripts / scenes] [answered]
Excited to have the new Time of Day helper! The current dialog only allows for setting an actual time. I'd love to be able to configure the `sun` sensor and set `offset` from the dialog as well.

Here's an example yaml I'm currently using that I can't set in the new UI.
```
binary_sensor:
  - platform: tod #Time of Day
    name: Evening
    after: sunset
    after_offset: "-00:30"
    before: "23:59"
```
