### DISCUSSION TITLE
Glance card: per-entity option to invert state color

### DISCUSSION THREAD

**Discussion by rigrig** [home-assistant/frontend#12664] [Dashboard]
I expect some of my devices to be active by default, so it would be nice if their icons could be highlighted when the exception occurs.

Example: This card
```yaml
type: glance
entities:
  - entity: binary_sensor.all_windows
  - entity: switch.transmission_switch
  - entity: cover.all_screens
```
Looks like this:
![image](https://user-images.githubusercontent.com/2941436/167924726-42a1a0d4-10d5-471f-9e78-fdd3a7803115.png)

* The window sensor is highlighted, because some windows are open: this is what I want
* The Transmission switch is on, but I leave it on almost all of the time, so it would be nice to highlight it when I turned it off instead.
* The cover sensor is highlighted, because all sunscreens are raised (for covers "open" = "active"), but I would like it to be highlighted when the screens are closed instead.

A per-entity `invert_state_color: true` option would be nice, even nicer would be if you could override `state_color` per entity, and besides `true` and `false`, `'invert'` was also an option:
```yaml
type: glance
entities:
  - entity: binary_sensor.all_windows
  - entity: switch.transmission_switch
    state_color: 'invert'
  - entity: cover.all_screens
    state_color: 'invert'
```
would have the same effect as
```yaml
type: glance
state_color: 'invert'
entities:
  - entity: binary_sensor.all_windows
    state_color: true
  - entity: switch.transmission_switch
  - entity: cover.all_screens
```
