### DISCUSSION TITLE
Action confirmation popup title configuration variable

### DISCUSSION THREAD

**Discussion by GizmoGoody** [home-assistant/frontend#12844] [Other feature requests] [answered]
I would like the ability to customize the title of action confirmation popups (the "xxx" says in this example):
![image](https://user-images.githubusercontent.com/46235745/171503921-5f692171-e014-4fa3-905c-5554b4854420.png)

**Comment by Misiu** [comment]
@GitHubGoody I think this is by design. It always displays the website URL that shows the prompt. Changing the name would be not secure as one could show a prompt that would pretend to be from your bank (anti-phishing)

https://www.w3schools.com/jsref/met_win_confirm.asp

**Reply by GizmoGoody** [reply]
They could also fake "homeassistant.local:8123 says."

Actually, an argument could be made that entering one's own Title is more secure especially for local servers since the user would know what value to expect.

**Reply by Misiu** [reply]
Did you check the link I provided? Problem is that there isn't API for that. You can only specify text, not the title.

**Reply by GizmoGoody** [reply]
Yes, thank you. If we cannot change it in our configuration, can we at least change "homeassistant.local:8123 says" to just "Home Assistant" in the backend for all confirm popups? This popup looks even worse using the external (e.g. Nabu Casa) link:

![image](https://user-images.githubusercontent.com/46235745/172003403-86a5683f-8085-480f-9618-9876d421d31d.png)

**Reply by gonzotek** [reply]
It's not enforced by the backend of Home Assistant, but by the browser. But I'm curious, what browser do you use?  And can you share an example of the code that triggered the window? Because with the one button for which I use an action confirmation, I get an html-based dialog (e.g. it's part of the page, not a separate window).  At least in Chrome on Windows/Mac/Linux, as well as Firefox and Safari on MacOS Monterey, and in the iOS Home Assistant app (a which uses iOS Safari webview).


          - entity: script.bedtime
            type: button
            icon: mdi:sleep
            name: Night Mode
            show_name: true
            tap_action:
              action: call-service
              service: script.bedtime
              confirmation:
                text: Is it bed time already?
<img width="517" alt="Screen Shot 2022-06-04 at 10 14 44 AM" src="https://user-images.githubusercontent.com/253407/172005759-19798112-76e5-4f8c-af2b-c37cdcdc363b.png">

**Reply by GizmoGoody** [reply]
Oooh, this is promising! I use a bunch of different browsers - Edge, iOS app, Fully Kiosk Browser, Tesla browser (Chromium). I'm mostly configuring Mushroom Cards currently. In your example, did you set the "Are you sure?" somewhere else?

```yaml
                    - type: custom:mushroom-entity-card
                      entity: switch.prusa
                      layout: vertical
                      icon_color: green
                      primary_info: none
                      secondary_info: none
                      tap_action:
                        action: toggle
                        confirmation:
                          text: >-
                            Toggle 3D printer power?
                      hold_action:
                        action: more-info
```
