### DISCUSSION TITLE
Ability to specify defaults for UI-created input Helpers

### DISCUSSION THREAD

**Discussion by seraphx2** [home-assistant/frontend#12846] [Configuration]
Pretty much self-explanatory. Dropdowns and Toggles cannot have a default value set. That can be very important to have defined on restart of a HA. Weird this wasn't included in the first place.

**Comment by Mariusthvdb** [comment]
Same goes for `initial` which is really necessary for some toggles (booleans). Unless that’s what you mean ofc

**Reply by seraphx2** [reply]
correct. I meant for that field.

**Reply by Mariusthvdb** [reply]
had written my own discussion here https://github.com/home-assistant/frontend/discussions/12944#discussioncomment-3148201 but it was marked duplicate if yours ;-)

hope it will attract some attention other than administrative....

**Comment by lollo78** [comment]
OMG! 
After more than a year the "initial" option is not added to the UI.
This is essential in some scenarios! 

Please devs, add it for our brain sanity. Thanks

**Reply by Mariusthvdb** [reply]
wonder if we can set that via customize:

```
homeassistant:
  customize:
    input_boolean.just_started:
      initial: on
```
like we did when this was still in yaml:
```
input_boolean:

  just_started:
    name: Just started
    initial: on
```

nope, doesn't work
