### DISCUSSION TITLE
mqtt / binary_sensor / device_class

### DISCUSSION THREAD

**Discussion by kowalczykrafal** [home-assistant/frontend#13657] [Configuration]
I want to set device_class: door in mqtt / binary_sensor but it doesn't recognize device_class and I don't have the door icon:
My connfig:
```
mqtt:
binary_sensor:
   - unique_id: toilet_door
     friendly_name: "Toilet door"
     state_topic: "bridge / tele / RESULT"
     value_template: "{{value_json.RfReceived.Data}}"
     payload_off: "70CC67"
     payload_on: "70CC6E"
     device_class: door
     qos: 1
```
