### DISCUSSION TITLE
Entity Card does support icons in the name, glance doesn't

### DISCUSSION THREAD

**Discussion by ChristophCaina** [home-assistant/frontend#14133] [Dashboard]
During the configuration of my dashboards,
I've noticed, that I can set an icon to the name of an entity card 

![grafik](https://user-images.githubusercontent.com/26391061/196793168-adb8966b-7741-4351-8562-53d75ab0d959.png)

```
type: entities
icon: mdi:power-socket-de
entities:
  - entity: sensor.kuhlschrank_energy
    name: Energy
  - entity: sensor.kuhlschrank_current
    name: Current
  - entity: sensor.kuhlschrank_power
    name: Power
  - entity: sensor.kuhlschrank_voltage
    name: Voltage
  - entity: sensor.kuhlschrank_signal_strength
    name: Signal Strength
  - entity: light.kuhlschrank_dndmode
    name: DND Mode
title: Kühlschrank
```

to get a consistent look and feel, I wanted to do the same with the Glance-Card... but unfortunately, this does not work there:

```
show_name: true
show_icon: true
show_state: true
type: glance
icon: mdi:alert-circle-check-outline
entities:
  - entity: sensor.siemens_ti9578x1de_68a40e8445de_active_program
    name: Aktives Programm
  - entity: sensor.siemens_ti9578x1de_68a40e8445de_selected_program
    name: Ausgewähltes Programm
title: Kaffeemaschiene
```

The editor is just showing a warning that the element "icon" is not expected or supported by the visual editor.
The card can still be configured with yaml - but the icon will not be shown.

The interesting case here is:
Even the entity card does not have an option to set the icon within the visual editor - it can only be done in the yaml editor.
Anyway - it is working and the editor does not show any warning.

I would really appreciate the same option for the glance card...
