### DISCUSSION TITLE
Support Tile Card Features

### DISCUSSION THREAD

**Discussion by bkbilly** [home-assistant/frontend#14524] [Dashboard]
## Lock
Add buttons for lock tile card with options to select:
 - Lock
 - Unlock
 - Open

## Media Player
Add buttons for media player tile card with options to select:
 - Play/Pause
 - Next
 - Previous
 - Volume Up
 - Volume Down

## Gauge
On sensors tile card add the ability to add gauge sensor.
I’ve created an example of what I am thinking of:
![image](https://user-images.githubusercontent.com/518494/205440013-72e3dd20-cb4b-4d25-bfae-14f4ed53b77d.png)

**Comment by tomlut** [comment]
How about severity colours for the sensor tile icon?

**Reply by bkbilly** [reply]
I would prefer the one I recommend because it's easier for people to understand.
I am using a gauge card for the water heater temperature which makes it really simple for my family to have a quick look at the status of the water and decide if it's hot enough.

**Comment by tomlut** [comment]
It's just a bit much for me. I'll open my own request.

**Comment by ddokupil** [comment]
Why not allow to crerate custom tile cards along with predefined ones?
For example I have a throttle in myfireplace. Now I control it with input_number slider and I would like to put it in a tile card to look like light brightness, but I can't.

**Comment by Feedy88** [comment]
I would add support for `climate` entities:
## Climate
* Show current temperature and the set heatpoint
* Add slider to adjust the Heatpoint
* Add on/off toggle

**Comment by Mariusthvdb** [comment]
would love a lock feature on toggle cards, like switch and boolean, (aware we have the current action confirmation) a visual lock would be an extra warning. 

btw, the current confirmation is very clumsy on confirmation. this does not work

```
        - type: tile
          entity: switch.espresso_keuken
          name: Espresso
          tap_action:
            action: toggle
            confirmation:
              text: Are you sure you want to toggle?
```

when clicking the icon, it toggles directly without confirmation. When clicking the name, the confirmation pops up, but clicking ok next results in an error it needs an id.....

so, we need to spell it all out:

```
        - type: tile
          entity: switch.espresso_keuken
          name: Espresso
          tap_action:
            action: toggle
            confirmation:
              text: Are you sure you want to toggle?
            service: switch.toggle
            data:
              entity_id: entity
```

and even then can still click the icon to not show the confirmation..

This might well be called a bug.


__edit__

Lets not forget cover....

**Comment by ChristophCaina** [comment]
please add a "slider" support for number entities, too :)

![image](https://user-images.githubusercontent.com/26391061/217446380-f2faea70-ad29-4b7e-bcb9-7f19ec2e5f47.png)
![image](https://user-images.githubusercontent.com/26391061/217446131-edbcc523-24b7-4154-90cb-baf142b5ae2f.png)

**Reply by ChristophCaina** [reply]
a thing to note here - because I haven't worked much with mushroom before:

I would like to have the same option as mushroom currently has ... slider for number entities and select boxes for select entities
![image](https://user-images.githubusercontent.com/26391061/233072572-c448c6e0-f8c1-4c61-a01f-c2d6a8bf0bde.png)

**Comment by Quentame** [comment]
Some updates from the `2023.9.0` release: https://www.home-assistant.io/blog/2023/09/06/release-20239/#lots-of-new-tile-features

![image](https://www.home-assistant.io/images/blog/2023-09/tile-features.png)

**Comment by Mariusthvdb** [comment]
no such thing as a lock just yet I believe, which for eg garage doors is quite an issue.

would be really nice if core tile card would support:

<img width="525" alt="Scherm­afbeelding 2024-01-24 om 10 06 39" src="https://github.com/home-assistant/frontend/assets/33354141/8b1e946f-73a5-4e9b-8f8e-8d82169f92db">

which we now can do with the (abandoned?) `custom:restriction-card`

**Reply by ChristophCaina** [reply]
There's no specific "lock" symbol... you're right...
But the tile itself does support locks... or what do you mean?

![grafik](https://github.com/home-assistant/frontend/assets/26391061/2fc3cafe-e7fd-4028-ad5a-260e16712ede)
![grafik](https://github.com/home-assistant/frontend/assets/26391061/15003c94-2b9d-42fb-8c54-3b7a01300dae)

It's basically just like any other "switch" card...

![grafik](https://github.com/home-assistant/frontend/assets/26391061/df0ae467-625c-4850-bd8b-0885f8449fb3)
![grafik](https://github.com/home-assistant/frontend/assets/26391061/9fa5778e-0af8-40b3-a545-2c903b08ea30)
![grafik](https://github.com/home-assistant/frontend/assets/26391061/41ebcea9-0f16-4ec3-92b0-0f515d6981bc)

**Reply by ChristophCaina** [reply]
Ah... you mean, that you need a way to "lock" the ability to change the state?

**Reply by Mariusthvdb** [reply]
yes, guard it from accidentally opening, or, even more importantly, require a code for unauthorized control

**Reply by Mariusthvdb** [reply]
we can set a conditional card on it:
```
          type: conditional
          conditions:
            - condition: user
              users:
                - !secret admin
```
as a core feature, but that isnt enough really. I was looking for this type of control:

```
          <<: &restrict
            condition:
              entity: cover.garage_deur
              value: closed
            restrictions:
              confirm:
                text: 'Garagedeur openen?'
              pin:
                text: 'Voer Pincode in:'
                code: !secret tahoma_secret
                max_retries: 3
                max_retries_delay: 30
```
