### DISCUSSION TITLE
improvement for state colors (enhancements)

### DISCUSSION THREAD

**Discussion by ChristophCaina** [home-assistant/frontend#14685] [Theming]
I think, it would be positive for the community, if the user could define the color of an entity state (binary_sensors first?)

Meaning:
Within the card editor, the user could just select the colors for "off" and "on" state directly per entity.
This could be implemented as yaml option first - and then, maybe implemented as a selector like it is done for the tile card?

maybe, something like the following:

```
type: entities
entities:
  - entity: lock.t***5_door_locked
    name: Lock the Car Doors (lock)
  - entity: binary_sensor.t***5_doors_locked
    state_color: true
      on_state_color: '#4CAF50' # Green
      off_state_color: '#F44336' # Red
    name: Car Doors (binary sensor / lock)
  - entity: binary_sensor.fossil_gen_6_0578_is_charging
     state_color: true
      on_state_color: '#4CAF50' # Green
      off_state_color: '#F44336' # Red
    name: Battery 1 charging (binary sensor / plug)
  - entity: binary_sensor.pixel_6_simone_is_charging
     state_color: true
      on_state_color: '#4CAF50' # Green
      off_state_color: '#F44336' # Red
    name: Battery 2 charging (binary sensor / plug)
state_color: true
```

At the moment, I've reduced the color palette on my system by using green as the default "state-binary-sensor-color" color - which will reduce the amount of different colors by a lot and is still looking good to me.
![grafik](https://user-images.githubusercontent.com/26391061/206848498-987414d3-97ef-4b40-bfc7-ebd272dfb58e.png)
![grafik](https://user-images.githubusercontent.com/26391061/206848980-b58e7a72-2134-47a6-a1af-3c5f10178b20.png)

if no color options will be defined from the user in the above situation, the default colors could be used.
