### DISCUSSION TITLE
Tile Card in grid card dead zoon and ability to create duplicate features

### DISCUSSION THREAD

**Discussion by laithalsunni** [home-assistant/frontend#14746] [Dashboard]
There is a bug where if you put two tile cards in a grid card the active zoon does not go all the way down when the card is extended in its height. moreover, for some reason, you can add the same feature more than one time on the same card.

Example
video https://youtu.be/uvItdJbWbyw

```
square: true
columns: 3
type: grid
cards:
  - type: tile
    entity: light.neon_flex
  - type: tile
    entity: light.display_tv
    features:
      - type: light-brightness
  - type: tile
    entity: light.display_tv
    features:
      - type: light-brightness
      - type: light-brightness
      - type: light-brightness
```
