### DISCUSSION TITLE
Add "step size" support for sliders? (brightness, kelvin, volume)

### DISCUSSION THREAD

**Discussion by chadbaldwin** [home-assistant/frontend#15062] [Other feature requests]
I often find the various sliders in the UI too granual. Especially when using them on a phone where the screen is much smaller. I like when I can easily set a value to a nice round number.

For example, I have quite a few tunable white bulbs...however, I don't exactly need a slider that can support every integer from 1500 to 9000k...It's pretty rare I need to set a bulb to 3824k. I would rather see something similar to what LIFX does in their app. When you have the LIFX app set to normal mode, you are given a wheel with preset values.

Example of LIFX app:
![image](https://user-images.githubusercontent.com/16479446/211378411-3c0829c1-c509-48be-bbd9-e77d86d19938.png)

Similar for setting brightness and volume...99.9% of the time, I want to set it to a multiple of 5. Call me OCD, but that's just what I like.

I've built scripts in Home Assistant for automations so that when I press a button to adjust the volume of the TV, it rounds the current value to the nearest 5 (up or down depending on action), and then increments by 5 from there.

----

I'm sure there's a bunch of ways this could be implemented...When starting this post, my original thought was to put it on the actual card configuration. Something like...

```yaml
type: light
entity: light.living_room_lights
icon: mdi:floor-lamp-dual
step_size: 5
```

But then I started thinking about other parts of the UI, like the entity page for a light. How would you make it so that the Kelvin step_size is also configurable? For that I was thinking maybe a configuration item. Maybe it would go into `customize.yaml`, or `frontend:`...something like:

```yaml
light:
  step_size:
    color_temp_kelvin: 500
    brightness: 5 # not sure how this would work since it's based on 255 and not percentage, so this is just an example
```

Another option would be to just not make it configurable and make it a generic on/off switch. Which is also how LIFX handles it...you either have regular mode, or advanced mode, which allows more granular settings.
