### DISCUSSION TITLE
Group: inconsistency in more-info

### DISCUSSION THREAD

**Discussion by ildar170975** [home-assistant/frontend#15460] [Dashboard]
Consider these groups:
```
group:

  testing_group_1:
    entities:
      - sun.sun
      - sensor.processor_load

  testing_group_2:
    entities:
      - sensor.memory_use
      - sensor.processor_load

  testing_group_3:
    entities:
      - binary_sensor.service_on_value
      - binary_sensor.service_off_value

  testing_group_4:
    entities:
      - sensor.battery_iphone_5s
      - sensor.battery_iphone_5s_32
```

Compare `more-info` for these groups:

![изображение](https://user-images.githubusercontent.com/71872483/219050392-42264a4b-cf33-4c58-90ec-7faac7bf18cc.png)
Here 2 entities of different domains are present.
Data are displayed for `sun.sun` only.

![изображение](https://user-images.githubusercontent.com/71872483/219050527-c347ad11-4e4f-4f82-9557-6c54dfb90192.png)
Here 2 entities are of the same `sensor` domain.
Data are displayed for 1 entity only.

![изображение](https://user-images.githubusercontent.com/71872483/219050640-34e35568-7723-49e3-a837-d7479d691c73.png)
Data are displayed for both entities.

![изображение](https://user-images.githubusercontent.com/71872483/219050713-3a530b70-e477-46a7-96c5-f688551ca319.png)
Data are displayed for both entities.

What I find inconsistent:
1. Why data for only 1 entity displayed?
2. What is a purpose of displaying attributes?
