### DISCUSSION TITLE
Statistics graph: Allow entry of startdate

### DISCUSSION THREAD

**Discussion by seanomat** [home-assistant/frontend#15727] [Dashboard]
It would be great if we cold also explore or compare different periods of statistics, like in the energy-dashboard.
Right now you always start with "today", and look back a defined amount of days.

It is not possible to compare the statistics of this month to the same month last year or to just check statistics for 60 days ago, without displaying ALL datapoints going back 60 days which might be hard to read, if the interval is to big.

Defining a startdate per entity (default=today) would allow for exploring without affecting existing functionality.

**Comment by ildar170975** [comment]
Will be happy to get a similar feature for a history-graph.

**Comment by karwosts** [comment]
This should now be possible via https://www.home-assistant.io/dashboards/statistics-graph/#energy_date_selection

**Reply by ildar170975** [reply]
It has some limitations.
```
type: vertical-stack
cards:
  - &ref_card
    type: statistics-graph
    entities:
      - sensor.xiaomi_cg_1_temperature
  - <<: *ref_card
    energy_date_selection: true
  - type: energy-date-selection
```
![изображение](https://github.com/user-attachments/assets/74a6ced8-f8b9-4fe8-b0c6-b7e817c0514f)

Here the 2nd card "follows" the `energy-date-selection` card.
You can see a difference between 2 graphs - the 2nd graph shows daily readings.

If you select a bigger interval - you may get monthly readings.
Cannot consider this as a good way to select a start date since it changes a "granularity".

**Reply by karwosts** [reply]
The granularity is selectable. 

> `period` string (Optional)
> The period of the rendered graph. 5minute, hour, day, week or month. If energy_date_selection is true, and period is not defined, the chart period will auto-select between month/day/hour based on the selected date range.

**Reply by ildar170975** [reply]
I see, I need to specify the `period` explicitly:
```
type: vertical-stack
cards:
  - &ref_card
    type: statistics-graph
    period: hour
    entities:
      - sensor.xiaomi_cg_1_temperature
  - <<: *ref_card
    energy_date_selection: true
  - type: energy-date-selection
```
But in my example for same time periods different default values for `period` were chosen.
