### DISCUSSION TITLE
Persistent HA settings that work every time you login in the Browser.

### DISCUSSION THREAD

**Discussion by Solarunit** [home-assistant/frontend#15878] [Other feature requests]
Some HA settings (like Dark theme, or Always hide sidebar) only applied for a browser session. If you clean site's cookies/data or open another browser, they are gone and you have to apply them again which is annoying.

It would be nice to have these (and all other) settings persistent.

![](https://i.imgur.com/VE4yJxk.png)

![](https://i.imgur.com/Y7efdPh.png)

____

Edit: I was created this issue in the Issue section but it was redirected to Discussions.. :shrug:

**Comment by ildar170975** [comment]
In my experience these settings (theme, sidebar) are reset to defaults even w/o manual cleaning cache - just after user's logout.

Copy/pasted from [here](https://community.home-assistant.io/t/change-user-defaults-for-theme-and-sidebar/422700/7?u=ildar_gabdullin):

> I have never logged out explicitly from HA - so my settings (theme, sidebar) were persistent.
Surely when I cleared a browser’s cache - I had to login again, set a theme, a sidebar etc.
I thought that I have to re-login & re-set settings since cookies are deleted.

> Now I realized that if I logout - then after re-login all my settings are “purged”.
Seems that these “local settings” are “purged” after logout - even when I do not clear a cache manually and I do not know anything about settings for “automatically clear settings after logout”.
I find this really inconvenient when several users are using HA.

**Comment by nicelight** [comment]
guys, I use ha as a service for many users and I want all of them to first log in into my theme. Can you work on this quastion?

**Reply by dougiteixeira** [reply]
Changing the default theme for everyone can be done with an automation (as long as user theme setting is selected `Use backend preferred theme`):

```
alias: "Home Assistant Started: Change Theme"
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: frontend.set_theme
    data:
      name: enter-the-theme-name-here
mode: single
```
