### DISCUSSION TITLE
Read only view of helpers

### DISCUSSION THREAD

**Discussion by itsadamslife** [home-assistant/frontend#16508] [Dashboard] [answered]
I use several helpers as part of my automations. I want to view their state on a dashboard without having the ability to accidentally change the helper's state, as this would alter the functionality of the automation that uses the helper. I am currently using template sensors to achieve this, but building additional sensors for this seems redundant. Adding a 'read_only: true' option to the entities and entity cards would be nice. This can help clean up some extra sensors only used for UI purposes.

**Comment by karwosts** [comment, marked as answer]
I believe in an entity card they are always read only. 

In an entities card, you can change the type to `simple-entity` to render it as read only instead of a control.

```
type: entities
entities:
  - entity: input_datetime.test_datetime
  - entity: input_datetime.test_datetime
    type: simple-entity
  - entity: input_boolean.boolean1
  - entity: input_boolean.boolean1
    type: simple-entity
```

![image](https://github.com/home-assistant/frontend/assets/32912880/67b83126-26c6-4f1d-9e70-c41a63adf3e0)
