### DISCUSSION TITLE
Generic Temperature setting point

### DISCUSSION THREAD

**Discussion by penguin-fr** [home-assistant/frontend#17028] [Other feature requests]
Hi all,

I started to use Generic Thermostat (https://www.home-assistant.io/integrations/generic_thermostat/#full-configuration-example). However it looks like that it doesn't fit to my needs.
Now I have 2 choices:
- Either I go deep into the Generic Thermostat code and start to build my own custom component
- Either I write down my needs and see if it could be implemented into Home Assistant for the best of everyone

So here below my needs:

I need same nice and look as "Generic Thermostat":
![image](https://github.com/home-assistant/frontend/assets/63901338/6eced76b-5b23-449d-82d8-d32b518f3e09)

However I no need a thermostat. I need a setting point fo my temperature with a manual ON/OFF setting.
I don't need any switch to put on/off the heater system around my temperature setting point because my heater system is able to do the regulation itself (geothermal system / heat pump / ...). It just needs:
- temperature sensor visualization
- temperature setting point
- ON/OFF manual setting (not linked to temperature measurement and setpoint discrepancy)

This request could be really simple to setup as such Generic Thermostat exists and just need to remove and clean a large part of the code to make my need a reality.

This is what I guess about my needs in the configuration file:

climate:
  - platform: generic_temp_control
    name: whatever_you_like
    heater: NO SWITCH
    hvac_mode: this is the info I need to put on or off my heating system in Node RED
    target_sensor: sensor.temperature_whatever_you_like
    min_temp: 15
    max_temp: 25
    ac_mode: false
    target_temp: 20 (this is the value refreshed in real time I need to access in Node RED to send to my heater system)
    cold_tolerance: useless
    hot_tolerance: useless
    initial_hvac_mode: "heat"
    precision: 0.1

Linked to my initial post in the community:
https://community.home-assistant.io/t/thermostat-which-is-not-a-thermostat-with-node-red/584976

You'll see that I'm really not good at coding anything!

Then the additional option:
Access to temperature setting point and the on/off switch with any sort of scheduler (can adjust the temperature or turn on/off the witch in case we leave for a week-end or a week of holiday ...)
Example:
- For a week-end decrease a little the temperature to make energy economy without need a big warm up at the end of the week-end
- For a week or more: I can put off the switch which will lead to 15°C as frozen protection of the home

A global remark for the Generic Thermostat component which is also valuable for my needs: 
The real time value of the temperature setpoint and the hvac mode are not persistent!
Which means that after a Home Assistant restart, we lost those settings and Generic Thermostat sets the values to the ones the configuration file!
That behaviour should be changed in my opinion.

**Comment by Xitee1** [comment]
I have a similar problem and would probably also need something like that.
However I've successful developed a workaround for it using a dummy input boolean and a automation.

I've modified it a bit to fit your use-case:
Create a generic thermostat and a input boolean (input_boolean.dummy).
You set the input boolean as switch for the thermostat. The input boolean is only used as dummy switch and nowhere actually used.
Then create an automation that triggers on any value change of the generic thermostat:
```yaml
alias: "Generic thermostat workaround"
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.your_generic_thermostat
    attribute: temperature
  - platform: state
    entity_id:
      - climate.your_generic_thermostat
    attribute: hvac_action
action:
  - if:
      - condition: template
        value_template: "{{ states(gen_thermostat) == 'heat' }}"
    then:
      - service: switch.turn_on
        target:
          entity_id: switch.heater_on_off_switch
      # Since I don't know what entity type it is that holds your thermostat  temperature,
      # use any service you like here. To get the temperature you can use the variable 'target_temp' in any template.
      # How exactly you can use a template in the service, check the HA docs.
      # Example:
      - service: climate.set_temperature
        data:
          hvac_mode: heat
        data_template:
          temperature: "{{ target_temp }}"
        target:
          entity_id: "climate.your_heater_target_temp_entity"
    else:
      - service: switch.turn_off
        target:
          entity_id: switch.heater_on_off_switch
variables:
  gen_thermostat: climate.your_generic_thermostat
  target_temp: "{{ state_attr(gen_thermostat, 'temperature') }}"
```

Make sure to adjust all entities to your needs and the example service which sets the temperature of your actual heater.
You can also set up preset temperatures (home, away,..) if you like for the generic thermostat.
The generic thermostat should now be linked to your actual heater.
