### DISCUSSION TITLE
Ability to Display a Different Entity in “more-info” for “button card”

### DISCUSSION THREAD

**Discussion by dusan-ivanco** [home-assistant/frontend#17391] [Other feature requests] [answered]
Description:
I would like to propose a new feature for the “button card” component in Home Assistant that allows displaying “more-info” for a different entity than the button itself. This functionality would be useful in cases where different devices are used for control "one" endpoint.

Reason for the request:
In my home, I use the Shelly 2.5 switch to control the lights and a Zigbee RGBW bulbs. I would like to use the “button card” to control the Shelly switch but display “more-info” for the Zigbee RGBW bulb. 

I suggest adding a new attribute to the “button card” configuration called “more_info_entity,” which allows defining the ID of the entity for which “more-info” should be displayed when tapping the button. If this attribute is defined, the “button card” will control one entity, but “more-info” will show information for the entity defined in “more_info_entity.”

Example usage in the configuration:

type: button
entity: light.shelly_room_1
more_info_entity: light.zigbee_room_1

Such a new feature would allow customizing the “more-info” display as needed, increasing the flexibility and usefulness of the “button card.”

Thank you for considering this request, and I believe it would be very beneficial for many Home Assistant users.

**Comment by fsedarkalex** [comment]
This is an old issue but I wanted to share a solution I found.

Using browser mod, this is possible:

```yaml
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.more_info
                data:
                  entity: light.my_light_group
```

**Reply by karwosts** [reply, marked as answer]
Funny you bumped this now, I just put in a native fix for this yesterday 😄 

https://github.com/home-assistant/frontend/pull/22147

**Reply by fsedarkalex** [reply]
lol

**Reply by Windyo** [reply]
@karwosts does this work ?
I tried it and I feel it doesn't work as expected

```yaml 
- entity: sensor.washing_machine_time_formatted
    state_color: false
    shadow: false
    tap_action:
      action: none
    hold_action:
      action: more-info
      entity: sensor.lave_linge_current_status
```
