### DISCUSSION TITLE
Dashboard badge icons should be templateable

### DISCUSSION THREAD

**Discussion by sebastianrasor** [home-assistant/frontend#17639] [Dashboard]
The title says it all. Currently my badges look like this:
![image](https://github.com/home-assistant/frontend/assets/92653912/35573c0f-b2f3-4fd2-9080-9ff29416ee69)
This is only because there is no way to make the icon of a badge follow the state of an entity.

**Comment by ildar170975** [comment]
Post a code you are testing.

**Reply by sebastianrasor** [reply]
Here is the code seen in the screenshot provided:
```
badges:
  - type: state-label
    entity: cover.garage_door
    show_name: false
    tap_action:
      action: toggle
  - type: state-label
    entity: light.inside
    show_name: false
    tap_action:
      action: toggle
```
Here is the code which does not work (but should):
```
badges:
  - type: state-label
    entity: cover.garage_door
    icon: "{{ 'mdi:garage' if is_state('cover.garage_door', 'closed') else 'mdi:garage-open' }}"
    show_name: false
    tap_action:
      action: toggle
  - type: state-label
    entity: light.inside
    icon: "{{ 'mdi:lightbulb-group' if is_state('light.inside', 'on') else 'mdi:lightbulb-group-off' }}"
    show_name: false
    tap_action:
      action: toggle
```
