### DISCUSSION TITLE
Allow empty or custom confirmation text (and not show twice)

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#17686] [Dashboard]
```
  - type: button
    name: Audio system off
    action_name: Turn off
    icon: mdi:audio-video-off
    tap_action:
      action: call-service
      confirmation:
        text: Weet je het zeker?
      service: script.audio_system_off
```

shows:
<img width="392" alt="Scherm­afbeelding 2023-08-23 om 16 11 39" src="https://github.com/home-assistant/frontend/assets/33354141/298a54d7-0edd-4c73-90f6-9d351f017581">

which is silly...

leaving out the `text:` line does not popup anything, which might in fact constitute a Bug..

we need to list ```text: ' ' ``` to get:

<img width="405" alt="Scherm­afbeelding 2023-08-23 om 16 13 21" src="https://github.com/home-assistant/frontend/assets/33354141/fb7d97cc-a344-459a-8918-9ebbb35a59ba">

which at least prevents twice the text. Ive always considered using the ```' '``` a hack but if that is what it takes, so be it.

Yet, we should be able to change the default text on that confirmation, without getting the double lines of text..

please consider allowing using our own confirmation dialog text, and not show the default at the same time

**Comment by Mariusthvdb** [comment]
btw, using that same confirmation on an entity like:
```
  - entity: script.audio_system_off
    action_name: Schakel uit
    secondary_info: last-triggered
    tap_action:
      confirmation:
        text: Weet je het zeker?
```

<img width="497" alt="Scherm­afbeelding 2023-08-23 om 16 19 08" src="https://github.com/home-assistant/frontend/assets/33354141/a06c88d9-9572-4ec7-bbbd-6c1ad3a46378">

only returns the confirmation when clicking on the entity name, while clicking the action_name immediately executes the action. This too would be a bug imho, as the user could be rightly expected to see a confirmation....
