### DISCUSSION TITLE
Ability to create multiple entities in tile type

### DISCUSSION THREAD

**Discussion by eosho** [home-assistant/frontend#17763] [Dashboard]
Today, you can create type `entities` and add n number of entities to a card.

eg: 
```type: entities
entities:
  - type: section
    label: Climate
  - entity: climate.hallway_thermostat
    type: custom:mushroom-climate-card
    fill_container: true
    icon: ''
    show_temperature_control: true
    collapsible_controls: true
    hvac_modes:
      - heat_cool
      - heat
      - cool
      - auto
    tap_action:
      action: more-info
  - type: custom:mushroom-climate-card
    fill_container: false
    show_temperature_control: false
    hvac_modes:
      - heat
      - cool
      - 'off'
    tap_action:
      action: more-info
    entity: climate.dyson_living_room
```

I am looking to create type `tile` and also add multiple entities to it:

eg:
```
type: tile
entities:
  - entity: climate.dyson_living_room
    vertical: false
    features:
      - type: climate-hvac-modes
        hvac_modes:
          - 'off'
          - heat_cool
          - cool
          - heat
      - type: target-temperature
  - entity: climate.dyson_master_bedroom
    vertical: false
    features:
      - type: climate-hvac-modes
        hvac_modes:
          - 'off'
          - heat_cool
          - cool
          - heat
      - type: target-temperature
```

It provides a clean look on the dashboard and the ability to manage/edit as a group.
