### DISCUSSION TITLE
Map card: add an ability to show a state of an entity instead of showing a name

### DISCUSSION THREAD

**Discussion by ildar170975** [home-assistant/frontend#17930] [Dashboard] [answered]
Currently the Map card shows a string composed of up to 3 letters based on an entity name:
```
sensor:
  - platform: template
    sensors:
      testing_map_markers_with_values_4:
        friendly_name: "testing marker xyz"
        value_template: ok
        attribute_templates:
          latitude: 5.100481554029
          longitude: 9.37401816254
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/c19becde-daa2-416f-b88f-df033ad970ac)

Imagine that this entity has a state with some value - could be a weather parameter etc.
Suggest to add an option to show a state inside a composed name:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/cbba8672-bbb3-4832-83ee-7a83047a324e)
