### DISCUSSION TITLE
add empty grid spot option

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#17991] [Dashboard]
please consider adding a core option to allow an empty spot in a grid. Currently we have to resort to custom cards, and eg do:

https://www.home-assistant.io/dashboards/grid

```
      type: grid
      columns: 4
      cards:

          - type: entity

          - <<: &empty
              type: custom:gap-card

          - <<: *empty

          - type: entity
 ```

or
```
  - type: custom:button-card
    color_type: blank-card
```

to skip a spot in the grid.

Please consider adding a core option for this

**Comment by karwosts** [comment]
A stock h-stack or v-stack card with nothing in it seems to do a decent job. 

![image](https://github.com/home-assistant/frontend/assets/32912880/8f677d61-8390-4823-a347-cd6771ba8c4b)

```
type: grid
cards:
  - type: entity
    entity: sensor.time
  - type: horizontal-stack
    cards: []
  - type: entity
    entity: sensor.time
  - type: horizontal-stack
    cards: []
  - type: entity
    entity: sensor.time
```
