### DISCUSSION TITLE
Wrong vertical axis values when displaying a filtered sensor in history graph

### DISCUSSION THREAD

**Discussion by balintkozma** [home-assistant/frontend#18630] [Dashboard]
Hi,

I see wrong vertical axis values when displaying a filtered sensor in history graph.
It looks like this:

![image](https://github.com/home-assistant/frontend/assets/15109984/1f649d1c-6541-44c0-a73f-fed40c051f1c)

There should be temperature values on the vertical axis instead of time values.

The filter:

```
sensor:
  - platform: filter
    name: Filtered Bedroom Temperature
    unique_id: xxxx
    entity_id: sensor.th_sensor_bedroom_temperature
    filters:
      - filter: outlier
        window_size: 10
        radius: 1.5
```
