### DISCUSSION TITLE
add UI configurable entity_picture to entity options

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#18838] [Dashboard]
just like we can set an icon in the UI interface, please allow setting an entity_picture.

currently we have to do that in yaml customize, and at least in my config, makes for 90% of that customize...
```
homeassistant:

  customize_glob:

    scene.*arctische_dageraad:
      entity_picture: /local/hue_scenes/arctische_dageraad.png

    scene.*chinatown:
      entity_picture: /local/hue_scenes/chinatown.png

    scene.*concentreren:
      entity_picture: /local/hue_scenes/concentreren.png

    scene.*_disturbia:
      entity_picture: /local/hue_scenes/disturbia.png

```
or
```
homeassistant:

  customize:

    device_tracker.ha_main:
      entity_picture: /local/home-assistant/picture.png

    device_tracker.hvb_macbook_pro:
      entity_picture: /local/home-assistant/picture.png

    device_tracker.plugwise_smile:
      entity_picture: /local/devices/anna.png
```

would be very nice if we could simple add an entity_picture  picker, and set it directly inside the UI.

<img width="564" alt="Scherm­afbeelding 2023-11-30 om 15 47 01" src="https://github.com/home-assistant/frontend/assets/33354141/3a997d79-b48d-4552-be5c-5561a722680d">

and yet:

<img width="566" alt="Scherm­afbeelding 2023-11-30 om 15 47 08" src="https://github.com/home-assistant/frontend/assets/33354141/9b3e2d36-7104-4ea2-85d6-d59dc93d0f6f">

no entity_picture option.

hope you will consider
