### DISCUSSION TITLE
add 'copy' button on developer tools/service response field

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#18831] [Dashboard] [answered]
with the new service
```
service: weather.get_forecasts
target:
  entity_id: weather.buienradar
data:
  type: daily
response_variable: buienradar_forecast
```

we need to template the output to something like

```
        state: >
          {{buienradar_forecast['weather.buienradar'].forecast[0].temperature}}
```

to be able to test that, we need to copy the output of the service into a yaml to json converter. That process would be helped enormously by adding a 'Copy' button to the Response (Antwoord) field:

<img width="1261" alt="Scherm­afbeelding 2023-11-30 om 11 33 36" src="https://github.com/home-assistant/frontend/assets/33354141/71cd9776-d8e6-4c07-8b47-3b0b08392637">

please consider, thanks
