### DISCUSSION TITLE
Dynamic entity title update on Lovelace floorplan

### DISCUSSION THREAD

**Discussion by QuAzI** [home-assistant/frontend#18874] [Dashboard]
I have simple entity with icon and by hint I want to see some value. As example temperature for teapot.
 ``` - type: state-icon
    entity: water_heater.skykettle_rk_m216s
    title: {{ states('water_heater.skykettle_rk_m216s') }}
    style:
      top: 14%
      left: 82%
```
Currently it shows `[object Object]` on hover

**Comment by ildar170975** [comment]
The picture-element card does not support templates.
You need to use some custom card supporting it.
For instance - config-template-card:
```
type: picture-elements
...
elements:
  - type: custom:config-template-card
    entities:
      - water_heater.skykettle_rk_m216s
    element:
      entity: water_heater.skykettle_rk_m216s
      title: >-
        ${ states['water_heater.skykettle_rk_m216s'].state }
      style:
        top: 14%
        left: 82%
```
