### DISCUSSION TITLE
Relative date parameters for the entity history view

### DISCUSSION THREAD

**Discussion by phipolis** [home-assistant/frontend#18900] [Dashboard]
Selecting multiple entities in the history view is a very useful tool for understanding interactions and testing automations. For clusters of entities I want to be able to check easily, I started adding entities card weblinks that jump directly to the history view.

For example, comparing inside and outside temperature with whether a door was opened:
```
type: entities
title: Stats
entities:
  - type: weblink
    url: /history?entity_id=binary_sensor.door_contact%2Csensor.greenhouse_temperature%2Csensor.outside_temperature
    name: greenhouse temperature gradient
```

This is much more convenient than clicking into the first entity's history and adding the others each time I want to see a particular comparison. The one thing you can't do is set a dynamic time window. If no date is provided, the view defaults to a small number of hours on the current day, which is usually too small. The "Show more" entity history links are generated with a `start_date` value corresponding to midnight UTC the day before, which gives a longer duration that is usually a more useful starting point.

With that in mind:
* My ideal, probably unrealistic, would be if `/history` accepted Grafana-style `from=now-3d&to=now` relative dates.
* Alternatively, if the weblink `url` field supported templates, one could do `/history?entity_id=&start_date={{(utcnow() - timedelta(days=3)).isoformat()}}`. That's clumsy, and the idea has been rejected in the past though. (#4397)
* The least flexible but simplest solution would be for the default time window when `start_date` and `end_date` aren't provided to be identical to the one used in "Show more" history links.
