### DISCUSSION TITLE
Add ‘or’ condition to conditional card

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#18991] [Dashboard] [answered]
As title, please add the ‘or’ condition. We now have to create helpers for those while it could be handled by the Frontend and save some backend entities

**Comment by karwosts** [comment, marked as answer]
It's already there? (I guess its new in 2023.12)

![image](https://github.com/home-assistant/frontend/assets/32912880/0057cd4e-afd7-4419-ab9c-d444027aa320)

**Reply by Mariusthvdb** [reply]
well, so it seems yes! how odd... I never realized, as I am a yaml user and this is the explicit text in the [documentation](https://www.home-assistant.io/dashboards/conditional/)

> Note: if there are multiple conditions there will be treated as an ‘and’ condition. This means that for the card to show, all conditions must be met.

**Reply by Mariusthvdb** [reply]
can confirm:
```
  - type: conditional
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity: binary_sensor.co_alert
            state: 'on'
          - condition: state
            entity: binary_sensor.rookmelder
            state: 'on'
    card:
      type: grid
      columns: 4
      cards:

        - type: conditional
          conditions:
            - entity: binary_sensor.co_alert
              state: 'on'
          card: !include /config/dashboard/includes/button/include_button_co_alert.yaml

        - type: conditional
          conditions:
            - entity: binary_sensor.rookmelder
              state: 'on'
          card: !include /config/dashboard/includes/button/include_button_rook_alert.yaml
```

works as I had hoped for, so discussion closed, thank you very much.

**Now someone need to really update that documentation** 
as it is rather a fundamental lack, and very important functionality
