### DISCUSSION TITLE
FR: add show_when_empty option to Grid card

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#18995] [Dashboard]
consider:
```
  - type: conditional
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity: binary_sensor.co_alert
            state: 'on'
          - condition: state
            entity: binary_sensor.rookmelder
            state: 'on'
    card:
      type: grid
      columns: 4
      cards:

        - type: conditional
          conditions:
            - entity: binary_sensor.co_alert
              state: 'on'
          card: !include /config/dashboard/includes/button/include_button_co_alert.yaml

        - type: conditional
          conditions:
            - entity: binary_sensor.rookmelder
              state: 'on'
          card: !include /config/dashboard/includes/button/include_button_rook_alert.yaml
```

where the conditions test if either states is active, and then a grid is shown with either/both of the cards in the grid, depending on their state.

adding a simple [option like auto-entities offers](https://github.com/thomasloven/lovelace-auto-entities#options) would make for a much shorter card config

```
      type: grid
      columns: 4
      show_when_empty: false
      cards:

        - type: conditional
          conditions:
            - entity: binary_sensor.co_alert
              state: 'on'
          card: !include /config/dashboard/includes/button/include_button_co_alert.yaml

        - type: conditional
          conditions:
            - entity: binary_sensor.rookmelder
              state: 'on'
          card: !include /config/dashboard/includes/button/include_button_rook_alert.yaml
```
 and not require the full setup of nested conditions

_Originally posted by @Mariusthvdb in https://github.com/home-assistant/frontend/discussions/18991#discussioncomment-7810790_
```
