### DISCUSSION TITLE
input_datetime: add an option to enable seconds

### DISCUSSION THREAD

**Discussion by ildar170975** [home-assistant/frontend#19690] [Dashboard]
The `input_datetime` has an internal support to have seconds.
But the seconds are not displayed in UI:

![image](https://github.com/home-assistant/frontend/assets/71872483/be1020dc-77d6-4498-97cf-725dbbd267c3)

Please add an option to enable displaying seconds.

[Related FR in Community](https://community.home-assistant.io/t/input-datetime-show-seconds/407799)

**Comment by karwosts** [comment]
Maybe feels like the entity itself should have `enableSeconds` as a configurable option/attribute? Then the UI could show seconds when it was requested, but not add seconds to all input_datetimes, where seconds may not be desired.

**Reply by ildar170975** [reply]
Someone should tell is it a core or a frontend issue.

**Comment by RFDarter** [comment]
> Maybe feels like the entity itself should have `enableSeconds` as a configurable option/attribute? Then the UI could show seconds when it was requested, but not add seconds to all input_datetimes, where seconds may not be desired.

I dont think that ist needed. You can simply not provide a second value or if the second value is 0 the seconds should not be displayed. That is how all Browsers handle the datetime.

**Comment by 3ative** [comment]
I think it should be a Feature/Shown by defualt. 
For example, you can set ``datetime:`` on an ESPHome device:
```yaml
datetime:
  - platform: template
    id: timer1
    name: The Timer
    type: time
    optimistic: yes
    update_interval: 1s
    initial_value:
      hour: 0
      minute: 0
      second: 1
```
And it still won't show "Seconds" in the GUI in HA
