### DISCUSSION TITLE
use round picture for HA update entities

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#19798] [Dashboard]
so we can see this in the dashboard, and has a better fit with many of the other entity_pictures in the dashboards:

<img width="533" alt="Scherm­afbeelding 2024-02-14 om 13 24 27" src="https://github.com/home-assistant/frontend/assets/33354141/61d81ca0-8a9b-4f76-aa17-d912cc76ad07">

and their more-info:

<img width="579" alt="Scherm­afbeelding 2024-02-14 om 13 25 46" src="https://github.com/home-assistant/frontend/assets/33354141/ad067776-fb91-402a-a3ea-3d031edaf385">

its the official picture provided in the logo set

ive now set it via:
```
homeassistant:

  customize_glob:

    update.home_assistant_*_update:
      entity_picture: /local/home-assistant/picture.png
```

but believe it would be much better if set as default by the Frontend

compare with eg:

<img width="595" alt="Scherm­afbeelding 2024-02-14 om 13 31 17" src="https://github.com/home-assistant/frontend/assets/33354141/29f95327-5177-472f-8ae3-aeb7497213a8">

and ofc current default:

<img width="503" alt="Scherm­afbeelding 2024-02-14 om 13 33 35" src="https://github.com/home-assistant/frontend/assets/33354141/9ec17932-f6da-4a2f-b82b-3ef0a69327d3">
