### DISCUSSION TITLE
Tile card not updating the "remaining" (time) when using timers

### DISCUSSION THREAD

**Discussion by moonwhaler** [home-assistant/frontend#20138] [Other feature requests] [answered]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After setting up a tile card for a "timer" in the dashboard, the "state content" attribute "remaining" never gets updated in the tile card. Clicking the tile card brings up a dialogue which displays the remaining just fine - and also updates it as time moves along.

### Describe the behavior you expected

The remaining time should be updated in the tile card until the timer is up.

### Steps to reproduce the issue

1. Add a tile card to a dashboard
2. Use a timer as the entity
3. Select "remaining" in the "state content"
4. Save
5. Start the timer
...

### What version of Home Assistant Core has the issue?

2023.11.2

### What was the last working version of Home Assistant Core?

2023.11.2

### In which browser are you experiencing the issue with?

Firefox 119.01

### Which operating system are you using to run this browser?

macOS Sonoma 14.0

### State of relevant entities

```txt
entity: timer.kuche_kochmodus
duration: 0:30:00
editable: true
restore: true
icon: mdi:timer
friendly_name: Küche: Kochmodus
```

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - features:
      - type: light-brightness
      - type: light-color-temp
    type: tile
    entity: light.hangelampe_kuche
    icon: mdi:ceiling-light
    name: Hängelampe
    tap_action:
      action: more-info
    hide_state: true
  - features:
      - type: light-brightness
    type: tile
    show_entity_picture: false
    vertical: false
    entity: light.zigbee_tradfri_driver_03
    icon: mdi:faucet
    name: Küchenzeile
    hide_state: true
  - type: horizontal-stack
    cards:
      - type: tile
        entity: sensor.zigbee_aqara_motion_03_device_temperature
        name: Temperatur
        color: accent
      - type: tile
        entity: timer.kuche_kochmodus
        name: Kochmodus
        state_content: remaining
  - type: media-control
    entity: media_player.wohnzimmer
```

### Additional information

<img width="620" alt="Bildschirmfoto 2023-11-11 um 22 13 52" src="https://github.com/home-assistant/frontend/assets/1736467/f19fac7c-a896-4cb4-8101-ad67878596b2">
