### DISCUSSION TITLE
add condition for hide_if_unavailable for Cast devices on views and cards

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#20771] [Dashboard]
so we can show a card (so not an individual row which we can set the hide_if_unavailable to) only when on a Castable device.

Currently we need to use custom cards like state-switch to be able to do this:

```
  - type: custom:state-switch
    entity: deviceID
    states:
      '31ebf03e-2a10d248':
         type: entities
         title: Cast
```
checking for the actual device_id of the browser. (so not even a Chrome check, but the actual deviceID which is set by yet another Custom card...)

Would be a great enhancement if we would have that selector inside core HA Frontend tools.

since we can do:
```
entities:

  - type: cast
    name: Home
    dashboard: ui-overzicht
    view: home
    icon: mdi:home
    hide_if_unavailable: true
```

the check already is available in  HA Frontend. 
Please add it to View, and Cards, and consider the condition for Conditional

so we could do:
```
  - type: vertical-stack
    cards:
      - type: entities
        hide_if_unavailable: true
        title: Cast entities
```

and

```
  - title: Cast on Chrome
    visible: admin
    hide_if_unavailable: true
    cards:
```
