### DISCUSSION TITLE
Enhance Blueprint input sections with conditions

### DISCUSSION THREAD

**Discussion by chrismanivong** [home-assistant/frontend#21003] [Other feature requests]
It would be nice to have sections either collapsing or even hiding, if a specific condition - mainly by other inputs - is met.

For e.g.:
So there could be an input for a "working" mode. Based on the user's decision to use mode "abc" or "xyz", some sections may appear or being hidden, or collapsed or uncollapsed.

This would be very helpful on top of @karwosts contributions, to make the usage of blueprints more convienent.

**Comment by mmoulton** [comment]
For me, this basically comes down to allowing the `input:` section to support templates as values. Though I'm sure this is much more complex than it might seem.

If this was possible, you could collapse a nested input with something like: `collapse: "{{ input.some_input_id == 'some value' }}"`

Beyond that, it would enable highly dynamic blueprint interfaces to be created. I have several advanced lighting / area automation blueprints that work great if you configure them precisely. With dynamic values in blueprint inputs, I could do something like this:

```
  input:

    area:
      name: Select Area
      selector:
        area: {}

    light_entity:
      name: Select Light
      default: ""
      selector:
        entity:
          include_entities: "{{ GET LIST OF LIGHT ENTITIES WITHIN SELECTED input.area }}"
          domain: light

    scene_entity:
      name: Scene Selector Entity
      default: ""
      selector:
        entity:
          include_entities: "{{ GET LIST OF INPUT SELECT ENTITIES WITHIN SELECTED input.area }}"
          domain: input_select

    selected_scene:
      name: Scene
      default: ""
      selector:
        attribute:
          entity_id: "{{ input.scene_entity }}"
```

As HA is looking to really cleanup the overall UX, I think a feature like this would really make it  far easier for Blueprint developers to make complex interfaces that are very user friendly, and robust.
