### DISCUSSION TITLE
Scene UI editor: Add option to only set light state to on/off.

### DISCUSSION THREAD

**Discussion by 2spiritpenguin** [home-assistant/frontend#21434] [Automations / scripts / scenes]
[A copy from here](https://community.home-assistant.io/t/scene-ui-editor-add-option-to-only-set-light-state-on-off/751294).

Some Hue lights, connected via Z2M ecosystem, support gradient scenes, that can be applied to the light during HA scene activation. One of these lights would be Philips Hue Signe with up to 5 colors gradient.

Such lights expose the `light.x` and `select.x` entities to the HA, where `select.x` entity allows you to select and apply the gradient scenes. When applying the `select.x` scene to the light, light won't be turned on automatically, so if we only add this entity to the HA scene, light won't go on. But if the light was on while scene was applied, indeed the correct colors will appear (according to the gradient scene selected in the `select.x` entity)

To have full functionality, we also need to add the `light.x` entity for the same light to the scene, that will turn the light on, but when we do that, HA scenes editor will popup ALL the light options to the scene config. When we apply the scene later, Hue won't take `select.x` gradient scene into consideration, but rather single color from `light.x` config, which was picked up by HA during scene creation in the UI.

A request is to allow HA scene editor, to only set the `on/off` state for the `light.x` entity, without adding all the color configs to the yaml file.

Currently we must exclusively use YAML editor to manually remove all other options from the `light.x` and only keep the `state: on` there. If we later want to update some colors for other lights in the scene UI, all the entities are populated again with the full configs, destroying our yaml manual work.

This is what I want (see `light.hue_light_office_gradient_left` part):
```yaml
  name: 'Office: Test'
  entities:
    select.hue_light_office_gradient_left_gradient_scene:
      options:
      - blossom
      - .... list of all entires can be here, I don't mind
      - crystalline
      assumed_state: true
      friendly_name: Hue Light - office gradient left Gradient scene
      state: midwinter
    light.hue_light_office_gradient_left:
      state: 'on'
  metadata:
    select.hue_light_office_gradient_left_gradient_scene:
      entity_only: true
    light.hue_light_office_gradient_left:
      entity_only: true
```

This is what I get from UI editor:

```yaml
  name: 'Office: Test'
  entities:
    select.hue_light_office_gradient_left_gradient_scene:
      options:
      - blossom
      - crocus
      - precious
      - narcissa
      - beginnings
      - first_light
      - horizon
      - valley_dawn
      - sunflare
      - emerald_flutter
      - memento
      - resplendent
      - scarlet_dream
      - lovebirds
      - smitten
      - glitz_and_glam
      - promise
      - ruby_romance
      - city_of_love
      - honolulu
      - savanna_sunset
      - golden_pond
      - runy_glow
      - tropical_twilight
      - miami
      - cancun
      - rio
      - chinatown
      - ibiza
      - osaka
      - tokyo
      - motown
      - fairfax
      - galaxy
      - starlight
      - blood moon
      - artic_aurora
      - moonlight
      - nebula
      - sundown
      - blue_lagoon
      - palm_beach
      - lake_placid
      - mountain_breeze
      - lake_mist
      - ocean_dawn
      - frosty_dawn
      - sunday_morning
      - emerald_isle
      - spring_blossom
      - midsummer_sun
      - autumn_gold
      - spring_lake
      - winter_mountain
      - midwinter
      - amber_bloom
      - lily
      - painted_sky
      - winter_beauty
      - orange_fields
      - forest_adventure
      - blue_planet
      - soho
      - vapor_wave
      - magneto
      - tyrell
      - disturbia
      - hal
      - golden_star
      - under_the_tree
      - silent_night
      - rosy_sparkle
      - festive_fun
      - colour_burst
      - crystalline
      assumed_state: true
      friendly_name: Hue Light - office gradient left Gradient scene
      state: midwinter
    light.hue_light_office_gradient_left:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - candle
      - fireplace
      - colorloop
      - sunrise
      - finish_effect
      - stop_effect
      - stop_hue_effect
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode: xy
      brightness: 179
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 172.821
      - 45.882
      rgb_color:
      - 138
      - 255
      - 241
      xy_color:
      - 0.2129
      - 0.3577
      friendly_name: Hue Light - office gradient left
      supported_features: 44
      state: 'on'
  metadata:
    select.hue_light_office_gradient_left_gradient_scene:
      entity_only: true
    light.hue_light_office_gradient_left:
      entity_only: true
```
