### DISCUSSION TITLE
Show "old" info for automation when device is removed

### DISCUSSION THREAD

**Discussion by mvdwetering** [home-assistant/frontend#21817] [Automations / scripts / scenes]
I had to replace a faulty device. So after deleting the old one some automations didn't work (as expected) and got some repairs for those. 

When I tried fixing them the UI is not really helpful since it only shows and empty device box.
This is the trigger section of one of my automations (Wanneer = When,  Apparaat = Device)
![image](https://github.com/user-attachments/assets/20ce9afa-d1d2-475a-832b-0d4938be1d19)

I would now have to remember how I configured this condition many years ago 😞. So I tried looking around a bit and in the `automations.yaml` I found the "old" version of the condition like below. This helped me restore the trigger with the original values.

```
  trigger:
  - type: illuminance
    platform: device
    device_id: e43eeef989778763126a7308472668b7
    entity_id: sensor.tuin_sensor_light_level
    domain: sensor
    below: 25
    for:
      hours: 0
      minutes: 30
      seconds: 0
```

It would have helped a lot if the UI would have shown the old values and indicated that the device is invalid. Ideally I could then just choose the new (compatible) device and it would be a lot easier to fix.

![image](https://github.com/user-attachments/assets/ea2757d6-830c-4747-a669-0ace9650ce1d)

Even without selecting a new device just _showing_ the old values would help a lot. Then it could be used as a reference to create a new trigger based on the old one.
