### DISCUSSION TITLE
Add visual editor support for numeric values in state trigger/condition

### DISCUSSION THREAD

**Discussion by Cyberbeni** [home-assistant/frontend#21946] [Automations / scripts / scenes]
For example I want to check whether a cover is completely open. If I use the visual editor, this is the yaml that gets generated:
```yaml
condition: state
entity_id: cover.emelet
attribute: current_position
state: "100"
```

This condition will never be true since "100" string will never equal any number. If I manually remove the "s then it works as expected.
It would be nice if conditions like this worked out of the box with the visual editor.
Same for triggers based on numeric values. Triggering on equals 0 is way more intuitive than triggering on below 0.0001.
