### DISCUSSION TITLE
allow secondary entity for action more-info

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#22020] [Dashboard] [answered]
please consider adding
```
      - type: tile
        entity: binary_sensor.ram_too_high
        name: Ram High
        tap_action:
          action: more-info # on tile this defaults to the card entity
          entity: sensor.memory_use_percent # this would allow a great deal of configuration options
```

and allow us to delete a boat load of `custom: button-cards` by moving all of them to core Tile.
