### DISCUSSION TITLE
How to change border color of picture-elements / state-badge?

### DISCUSSION THREAD

**Discussion by bugarovic** [home-assistant/frontend#22188] [Dashboard] [answered]
I don't understand why all picture-elements / state-badges are red? I want to change the color of border, but it does not work with variable --ha-label-badge-color, because is overwritten with default red color. Is there any possibility to change it? Or is this bug?

Dashboard yaml:
```
type: picture-elements
image: /local/resources/1NP/background/intensity/100.png
view_layout:
  position: main
elements:
  - type: state-badge
    entity: sensor.qwe001_hvac_papouch_temp_1_h_tank_upper
    style:
      '--ha-label-badge-color': green ##does not work
      left: 80%
      top: 80%
  - type: state-badge
    entity: sensor.qwe001_hvac_papouch_temp_1_h_tank_upper
    style:
      '--label-badge-red': green ##this changes color
      left: 85%
      top: 80%
```

https://github.com/home-assistant/frontend/blob/c8930cec870d963b4d2f2a9381052a75d22fc67a/src/components/entity/ha-state-label-badge.ts#L279-L281
