### DISCUSSION TITLE
Sync or allow customize icons on tile features for climate and alarm panel

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#22480] [Dashboard]
Aware we can change the order of the mode buttons on Tile cards, I had hoped we could also change the icons, but seems there is no UI option for that? nor in yaml for that matter.

looks really silly to have the 'same' modes on those Tiles, but different icons, and every time I see it I get confused.... no, not really, but it would be nice to streamline the icons for Away, Night, Vacation:

```
features:
  - type: alarm-modes
    modes:
      - armed_home
      - armed_night
      - armed_away
      - armed_vacation
      - disarmed
 ```

<img width="525" alt="Scherm­afbeelding 2024-10-21 om 13 45 29" src="https://github.com/user-attachments/assets/ca06a8aa-ad22-48c3-86db-2e9985949a8d">

and 

```
            - type: climate-preset-modes
              style: icons
              preset_modes:
                - home
                - asleep
                - away
                - vacation
                - no_frost
```

<img width="554" alt="Scherm­afbeelding 2024-10-21 om 13 45 51" src="https://github.com/user-attachments/assets/4a6c9a2a-c618-481c-aaf7-b497ab2af9d8">

Please consider using the same icons there, or, maybe even better, allow an icon to be set by the user.

Ive tried to PR the https://github.com/home-assistant/core/edit/dev/homeassistant/components/alarm_control_panel/icons.json but those icons are not used in the tile card.
Makes it even more difficult to see what is going on.
