### DISCUSSION TITLE
Hide Date & Time entities from Logbook by default, add UI for setting

### DISCUSSION THREAD

**Discussion by NoRi2909** [home-assistant/frontend#22981] [Other feature requests] [answered]
Currently every minute the Logbook is flooded with 7 Date & Time sensor updates which are probably the vast majority of entries for a beginner's setup.

As it is expected that these seven sensors to update consistently it does not make much sense to monitor them in Logbook. So they should be hidden by default to keep the Logbook clear for all real events to monitor.

And Logbook events all come with their own timestamp anyhow. Therefore having those Time & Date updates in between does not add any useful information either.

This can be fixed manually by adding the exceptions to configuration.yaml like

```
# Reduce clutter in Logbook
recorder:
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
      - sensor.date_time_iso
```

but that is contrary to the continued effort of making HA as UI-driven for all features.

An UI solution to all this should be a toggle in every Entity setting where the user can flip logging on or off for the individual entity.
For example you might have a time pattern automation that triggers every 30 seconds (MQTT keep alive, e.g.) that also should be hidden from Logbook unless you really, really want to track this for debugging.
