### DISCUSSION TITLE
FR capitalize states in Heading badges / use theme variable for badge icon-size

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#23651] [Dashboard]
As can be seen below, the state of the first badge is not translated in the Frontend, opposed to the second one.
the second is a timestamp

<img width="1067" alt="Scherm­afbeelding 2025-01-08 om 22 32 55" src="https://github.com/user-attachments/assets/e612dd7b-afcc-4d1c-bace-35ab23343f1d" />

and Frontend shows I as relative.

the first badge has a simple string as state:

<img width="1053" alt="Scherm­afbeelding 2025-01-08 om 22 33 51" src="https://github.com/user-attachments/assets/72872e22-3f68-4d0b-b42b-a6592ccc82eb" />

and it would be really consistent if the Frontend also 'translates' to use Capitalization.

<img width="529" alt="Scherm­afbeelding 2025-01-08 om 22 36 19" src="https://github.com/user-attachments/assets/b74eaa43-11c8-4ee6-8fa4-2f45a3cf7369" />

config:
```
  - type: heading
    heading: Ophaaldata
    heading_style: title
    card_mod:
      class: class-section-heading
    tap_action:
      action: navigate
      navigation_path: /calendar
    badges:
      - type: entity
        show_state: true
        show_icon: true
        entity: sensor.afvalwijzer_next_type
      - type: entity
        show_state: true
        show_icon: false
        entity: sensor.afvalwijzer_next_date
```

Next to capitalization, it would be really very nice to have a dedicated `ha-heading-badge-icon-size` variable, so we can set that to eg 24px in the theme, and be done with it. Currently it is way too small for older eyes (like mine)...

hope you can consider

fwiw, I managed to set some [serious card_mod customization](https://community.home-assistant.io/t/is-it-possible-to-change-header-card-icon-based-on-entity-state/797326/7?u=mariusthvdb) to get what it could be, but only link, so this is not used as alternative too easily
