### DISCUSSION TITLE
FR: Allow horizontal mode on type: button

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#23750] [Dashboard]
as title, it would be very nice if we could show icon and name horizontally on a `type: button`.

we can fake a button with an entity in an entities card like that, but that does now give the nice hover/click effect

having the horizontal mode ion the button would also save some space in the card, and take out one extra layer of cards.

keep it as simple as possible.

```
  - type: button
    entity: script.say_next_alarm_greet
#     name: Spreek groet
    icon: mdi:account-voice
    icon_height: 24px
    tap_action:
      action: toggle

  - type: entities
    entities:
      - entity: script.say_next_alarm_greet
        action_name: Groet
```

<img width="563" alt="Scherm­afbeelding 2025-01-15 om 09 29 57" src="https://github.com/user-attachments/assets/657e86a6-cd72-4930-bf54-002c5820bc48" />

difference in action, as you can see the button has way more style

![Jan-15-2025 09-36-52](https://github.com/user-attachments/assets/04b438b4-8ff7-4566-b8cd-88c30b8ad498)

it just lacks some orientation settings ;-)
