### DISCUSSION TITLE
TileCard Features for "Counter" entities

### DISCUSSION THREAD

**Discussion by ChristophCaina** [home-assistant/frontend#24196] [Dashboard] [answered]
I've just noticed, that there are no tile-card features available for a counter entity (counter helper)

Right now, you have to increase / decrease / reset the counter either in the "more info" dialog, via automation - or by calling the action for the counter, which means - if you want to do it within the UI:

Add the TileCard + configure a "primary action" - or place button cards next by. ...
So, having a feature like the below, would be great

```
features:
    - type: counter-action-modes
    action_modes:
      - increase
      - decrease
      - reset
 ```
