### DISCUSSION TITLE
Add navigation to glance card's title

### DISCUSSION THREAD

**Discussion by juergen-weber** [home-assistant/frontend#24334] [Dashboard]
The glance card configuration doesn't support navigating to a different lovelace-page via tap_action on title, like it is supported for entities. Please add navigation to the glance card's title like this:

```
  type: glance
  title: PV
  tap_action:
    action: navigate
    navigation_path: /lovelace/...
  entities: ....
```
