### DISCUSSION TITLE
Add templates into cards

### DISCUSSION THREAD

**Discussion by mainmind83** [home-assistant/frontend#24350] [Other feature requests]
This function would allow, for example, to [use helpers as the source of the dates of the statistics cards](https://community.home-assistant.io/t/statistic-card-helpers/832821)

```
type: statistic
entity: sensor.consumo_casa_kwh
stat_type: change
name: Casa
period:
  fixed_period:
    start: "2024-12-16"
    end: "2025-01-16"
```

with something like:

`start: states('input_datetime.start_date')
`

I have [not found a previous request](https://github.com/home-assistant/frontend/discussions/categories/other-feature-requests?discussions_q=is%3Aopen+category%3A%22Other+feature+requests%22+template+cards)...
