### DISCUSSION TITLE
What's wrong with history-graph card?

### DISCUSSION THREAD

**Discussion by ajbathe** [home-assistant/frontend#24584] [Dashboard]
I have this yaml code:

```
title: 24h-Verlauf aller Lumis
type: history-graph
entities:
  - entity: sensor.lumi_1_temperature
  - entity: sensor.lumi_2_temperature
  - entity: sensor.lumi_3_temperature
logarithmic_scale: false
hours_to_show: 24

```

The diagramm looks like this:

![Bildschirmfoto vom 2025-03-10 17-18-04](https://github.com/user-attachments/assets/7a332e8a-0b9b-492b-871e-674aa6893cfe)

When I click at one Temperature legend string, all three graphs get disabled:

![Bildschirmfoto vom 2025-03-10 17-18-16](https://github.com/user-attachments/assets/4224b843-433e-4270-8772-de8ac0516b57)

also the legend is wrong, all three entities are blue and might be the same

Andreas
