### DISCUSSION TITLE
Support additional actions for Entity Heading Badges

### DISCUSSION THREAD

**Discussion by ClayBenson94** [home-assistant/frontend#24705] [Dashboard] [answered]
# Summary
Right now it seems as if entity heading badges only support `tap_action`, while regular entity badges support tap, double tap, and hold. Would it be possible to have them support those actions as well?

I have a dashboard that uses headings which contain badges for a few light entities, and while the `tap_action` works great, it'd be awesome if I could configure them to have a `hold_action` as well!

Here's an example of my current configuration, with the suggested improvement
```yaml
type: heading
icon: mdi:sofa
heading: Living Room
heading_style: title
badges:
  - type: entity
    show_state: false
    show_icon: true
    entity: light.hallway_light
    color: state
    tap_action:
      action: toggle
    hold_action: # This is what I would like to be able to do!
      action: more-info
```

# Investigations
I've contributed a bit to [home-assistant/core](https://github.com/home-assistant/core) before, but never to the frontend, so I unfortunately don't have a great understanding of the complexity of a change like this, but I did do some digging to try and identify what might need to change to support something like this, so I'd love a gut-check if there's anything else I'm missing!

From what I can tell, the `hui-entity-badge` component _already_ supports this (along with `hasDoubleClick`), so it just seems like the `hui-entity-heading-badge` doesn't -- perhaps some of the approach used in the former component could be ported to the latter?
https://github.com/home-assistant/frontend/blob/ef7f4993647fafad43c5e85d3acb7a99dce74a38/src/panels/lovelace/badges/hui-entity-badge.ts#L207-L218
