### DISCUSSION TITLE
Add locked/unlocked state toggle to the available features in tile cards

### DISCUSSION THREAD

**Discussion by stezak77** [home-assistant/frontend#24959] [Dashboard]
Hi,

in tile cards, it would be useful to have the state of a lock entity listed in the available features.
Currently only lock commands are available as features.

Displaying the locked/unlocked state would be really more intuitive and provide a more consistent user experience with other entity types (switch, light, alarm, climate…) where you expect to 'toggle' the entity state, instead of sending commands.

Here is a drawing of what I mean:
![image](https://github.com/user-attachments/assets/62b3f3cf-a3b5-46a5-9e79-ffd7a8e5645d)

**Comment by ildar170975** [comment]
> lock entity listed in the available features.
Currently only lock commands are available as features.

what is a difference?

**Reply by stezak77** [reply]
The difference is a much better experience. 2 buttons against 1 toggle. The benefit of the toggle is you immediately understand the current boolean state (on/off, locked/unlocked, true/false...) and clicking on it will toggle it. Exactely like a light switch. Exactly like when you open the lock more-info panel and you see... a toggle :)

![image](https://github.com/user-attachments/assets/d7980bb6-3647-45cd-808f-46a49eddf2a2)

**Comment by ildar170975** [comment]
I am still not getting what is a difference between your drawing and an already supported look (except a color):
![image](https://github.com/user-attachments/assets/e2042192-aa8c-4654-b1ee-44a75a71854c)

**Reply by checkiecheck** [reply]
This is all you need indeed. Can anybody explain what would be missing here. Ther is state, only the button to unlock is active. If your lock supports it, there is a feature to 'opendoor' without need for lock/unlock

![image](https://github.com/user-attachments/assets/f441b606-6d3e-4ef6-8e45-3f9592d93185)

`features:
  - type: lock-commands
  - type: lock-open-door
`

**Comment by stezak77** [comment]
It's a toggle. Configure a tile card with a switch entity for example to see how a toggle works

**Reply by ildar170975** [reply]
A switch can be on/off, a lock can have several states which may not look nice with a binary toggle.

**Comment by Leons77** [comment]
Tuya opening will allow. HA cannot


ne 13. 4. 2025 v 11:41 odesílatel SanderB ***@***.***> napsal:

**Reply by checkiecheck** [reply]
that sounds more like an integration issue

**Comment by Leons77** [comment]
The integration is fine on the main panel. The problem is in more-info.


ne 13. 4. 2025 v 11:57 odesílatel SanderB ***@***.***> napsal:

**Comment by checkiecheck** [comment]
more-info is not related to  tile card, but entity data delivered by the integration. More info on nuki lock also shows open door button seperately, not just the lock/unlock
![image](https://github.com/user-attachments/assets/410bbaf9-78fd-46cf-a193-eb5d873164d4)

**Comment by Leons77** [comment]
banned entity. everything is working now. thank you for your time.
(Otevřít dveře = Open door)

ne 13. 4. 2025 v 12:23 odesílatel SanderB ***@***.***> napsal:

**Comment by stezak77** [comment]
I've been able to use a toggle inside a tile card to interact with my lock using a custom tile feature.
It works great, I hope Home Assistant will support it one day.

![image](https://github.com/user-attachments/assets/340029fa-d14e-48ba-bede-7cd149abe374)

**Reply by JoRouss** [reply]
Can you share the yaml for this?

**Reply by stezak77** [reply]
Sure

```
features:
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: lock.lock
        options:
          - entity_id: lock.lock
            option: unlocked
            tap_action:
              action: perform-action
              perform_action: lock.unlock
              target:
                entity_id:
                  - lock.lock
              data: {}
              confirmation:
                text: Vuoi sbloccare la porta?
            icon: mdi:lock-open-variant
            haptics: true
            styles: |-
              :host {          
                {% if is_state(config.entity, "unlocked") %}
                  --icon-color: white;
                  --color: var(--state-alarm_control_panel-disarmed-color);
                {% else %}
                  --icon-color: initial
                {% endif %}
              }
          - entity_id: lock.lock
            option: locked
            tap_action:
              action: perform-action
              perform_action: lock.lock
              target:
                entity_id:
                  - lock.lock
              data: {}
              confirmation:
                text: Vuoi bloccare la porta?
            icon: mdi:lock
            haptics: true
            styles: |-
              :host {          
                {% if is_state(config.entity, "locked") %}
                  --icon-color: white;
                  --color: var(--state-alarm_control_panel-armed_away-color);
                {% else %}
                  --icon-color: initial;
                {% endif %}
              }
        styles: ""
type: tile
entity: lock.lock
features_position: inline
vertical: false
grid_options:
  columns: full
name: Porta
hide_state: false
show_entity_picture: false
state_content: last_updated
tap_action:
  action: more-info
icon_tap_action:
  action: more-info
color: disabled
card_mod:
  style:
    ha-tile-info$: |
      .secondary:after {
        visibility: visible;
        content: '- {{ states('sensor.lock_battery') }}%'
      }

```

**Reply by stezak77** [reply]
Another one which I like better as you need to swipe the cursor to lock/unlock

```
features:
  - type: custom:service-call
    entries:
      - type: toggle
        entity_id: lock.lock
        tap_action:
          action: toggle
          target:
            entity_id: lock.lock
          data: {}
        check_numeric: false
        allow_list: true
        swipe_only: true
        full_swipe: true
        checked_values:
          - locked
          - locking
        autofill_entity_id: true
        thumb: default
        icon: "{{ iif(checked, \"mdi:lock\", \"mdi:lock-open-variant\") }}"
        unchecked_icon: mdi:lock
        checked_icon: mdi:lock-open-variant
        styles: |-
          .thumb > .icon {
            --icon-color: white;
          }

          .thumb {
             {{ "background: var(--state-alarm_control_panel-armed_away-color);" if is_state(config.entity, "locked") else "" }}
          }
type: tile
entity: lock.lock
features_position: bottom
vertical: false
grid_options:
  columns: full
name: Porta
hide_state: false
show_entity_picture: false
state_content:
  - state
  - last_updated
  - changed_by
tap_action:
  action: more-info
icon_tap_action:
  action: more-info
color: disabled
card_mod:
  style:
    ha-tile-info$: |
      .secondary:after {
        visibility: visible;
        content: '- {{ states('sensor.lock_battery') }}%'
      }

```
