### DISCUSSION TITLE
Map card: prevent adding several SAME items

### DISCUSSION THREAD

**Discussion by ildar170975** [home-assistant/frontend#25016] [Dashboard]
It is possible to add same item several times:
![изображение](https://github.com/user-attachments/assets/e7628f35-dce8-4dd2-af3b-d7ae0733b8c3)
```
  - type: map
    entities:
      - entity: device_tracker.demo_paulus
      - entity: device_tracker.demo_paulus
      - entity: device_tracker.demo_paulus
```
Suggestion: prevent adding SAME item.

"SAME" means "with same label_mode".
Imho these scenarios should be allowed:
```
  - type: map
    entities:
      - entity: device_tracker.demo_paulus
      - entity: device_tracker.demo_paulus
        label_mode: state
      - entity: device_tracker.demo_paulus
        label_mode: attribute
        attribute: battery
```
![изображение](https://github.com/user-attachments/assets/0b0b0d34-bd11-4d51-9c89-561354c58eb6)
