### DISCUSSION TITLE
FR allow core graph cards in footer

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#25152] [Dashboard]
we can use https://www.home-assistant.io/dashboards/header-footer/#graph-header--footer to add a `type: graph`. however, none of the core (energy) graph cards can be added in the footer.

We can use the `custom:mini-graph-card` to do this

```
footer:
  type: custom:mini-graph-card
  entities:
    - entity: sensor.netto_verbruik
```

or, hack the system by using the  hui-element custom plugin (note we can Not hack it by using the `type: custom:hui-statistics-grap-card` trick)

```
footer
   type: custom:hui-element
   entities:
     - entity: sensor.netto_verbruik
   card_type: statistics-graph
   days_to_show: 1
```

and show the statistics card after all.

we can even show the energy graph in an entities card footer like that:

```
footer:
  type: custom:hui-element
  card_type: energy-usage-graph

```

<img width="534" alt="Scherm­afbeelding 2025-04-24 om 08 45 37" src="https://github.com/user-attachments/assets/c05ff958-c15a-4f61-b6b4-5be88a65bf11" />

This fr is to ask for core Frontend to support the core (energy) graph cards without anything custom.

related community post:https://community.home-assistant.io/t/why-cant-we-use-any-core-graph-card-but-type-graph-in-a-footer/881407
