### DISCUSSION TITLE
Allow changing visibility of individual tile card features

### DISCUSSION THREAD

**Discussion by mukaschultze** [home-assistant/frontend#25757] [Dashboard]
Currently, tiles, thermostats, and humidifiers have no built-in way to hide individual features. The usual workaround is to duplicate the card, assign different feature sets to each copy, and toggle the card’s visibility instead.

Such configuration can be helpful when certain features are not always available and would otherwise waste dashboard space, for example:
- Hiding the target temperature when an AC is in fan-only mode
- Hiding a lock’s “open door” action while the lock is engaged
- Hiding color-temperature and brightness controls when a light is off
- Hiding volume controls on media players that are idle

![hass-feature-visibility](https://github.com/user-attachments/assets/595c7a50-be1d-4518-9e80-54131b4750d0)

![hass-lock](https://github.com/user-attachments/assets/926eee23-01f2-4c2b-9bbc-68eef1c233a5)

I made a proof-of-concept by adding an "eye" icon to the features list. Clicking it opens a submenu with a list of visibility conditions to meet. If the team agrees this would be useful, I can submit a PR.

### Screenshots

![image](https://github.com/user-attachments/assets/d9b97334-586b-47e0-bdb5-fd1a1ffd3168)

![image](https://github.com/user-attachments/assets/e54eb46b-f09d-42a6-b7ef-8d89eefad21d)

Example resulting configuration:

```yaml
type: tile
entity: climate.hvac
features_position: bottom
vertical: false
features:
  - type: climate-hvac-modes
  - type: target-temperature
    visibility:
      - condition: state
        entity: climate.hvac
        state_not: "off"
      - condition: state
        entity: climate.hvac
        state_not: fan_only
  - type: climate-fan-modes
    style: dropdown
    visibility:
      - condition: state
        entity: climate.hvac
        state_not: "off"
  - type: climate-swing-modes
    style: dropdown
    visibility:
      - condition: state
        entity: climate.hvac
        state_not: "off"
  - type: climate-swing-horizontal-modes
    style: dropdown
    visibility:
      - condition: state
        entity: climate.hvac
        state_not: "off"
```

Related feature request (not mine): https://community.home-assistant.io/t/tile-card-hide-features-when-off/753246
