### DISCUSSION TITLE
Icon colors of device_tracker entities

### DISCUSSION THREAD

**Discussion by Youpimatin** [home-assistant/frontend#7391] [Dashboard]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Icon color changing with state doesn't work for device_tracker entities.

![Lovelace1](https://user-images.githubusercontent.com/55438591/96440876-db1bc280-1208-11eb-8edb-544a2fa835b3.png)
('Present' is 'Home', 'Absent' is 'Not home')

## Expected behavior

I expected the same result as with switches, icon yellow when the device is online and blue when it isn't.

![Lovelace3](https://user-images.githubusercontent.com/55438591/96441092-35b51e80-1209-11eb-8107-3d7b57c54593.png)

## Steps to reproduce

- configure nmap tracker in 'configuration.yaml'
- configure devices in 'known_devices.yaml'
- Add a card 'Entities' or 'Glance' to a panel
- Add a device 'device_tracker.xxx'
- Check 'Color icons based on state ?'

![Lovelace2](https://user-images.githubusercontent.com/55438591/96441138-4b2a4880-1209-11eb-9e5a-cbf7225ebe1b.png)

## Environment

- Home Assistant release with the issue: 0.116.4
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 81.0.2 (64 bits)
- Operating system: Windows 7 Pro x64 SP1

## State of relevant entities

Entity:
device_tracker.cellphone1

State:
Home

```yaml
source_type: router
latitude: x.x
longitude: x.x
gps_accuracy: 0
scanner: NmapDeviceScanner
ip: 192.168.1.25
friendly_name: Someone's phone
icon: 'mdi:cellphone-android'

```

## Problem-relevant configuration

```yaml
'configuration.yaml' :

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.1 # Router
      - 192.168.1.20-50 # DHCP
    interval_seconds: 50
    consider_home: 150
    home_interval: 2

'known_devices.yaml' :

Someone's phone:
  icon: mdi:cellphone-android
  mac: xx:xx:xx:xx:xx:xx
  name: Someone's phone
  picture:
  track: true

```

## Javascript errors shown in your browser console/inspector

```txt

```
