### DISCUSSION TITLE
Native Remote Card

### DISCUSSION THREAD

**Discussion by iantrich** [home-assistant/frontend#7558] [Dashboard]
Thinking about writing a native remote card as it is a fairly common request from users. I wrote a custom one for [Roku](https://github.com/iantrich/roku-card) a long time ago which I no longer use, just have buttons in stacks now which works great. The problem with that is that it is a huge config, making it a massive chore for users to configure, especially with the UI editor. Was thinking that given a remote entity and a list of commands, we could just render it for the user. I don't think I would want to get into custom icons/images as the config would be close to already what I have, but instead just throw button cards into the grid card or stacks based on their command list and perhaps give the option to define rows.
For reference, this is currently my config for a single basic Roku remote, 214 lines https://hastebin.com/hofasiwiku.yaml
The remote tap_action commands are what are most tedious about it
So instead what if we just had something like
```yaml
type: remote
entity: remote.roku
commands:
  - power
  - back
  - info
  - home
  - up
  - left
  - select
  - right
  - down
  - reverse
  - forward
  - volume_mute
  - volume_down
  - volume_up
```
And maybe go as far as:
```yaml
type: remote
entity: remote.roku
rows:
  - commands:
      - power
  - commands:
      - back
      - info
      - home
  - commands:
      - up
  - commands:
      - left
      - select
      - right
  - commands:
      - down
  - commands:
      - reverse
      - forward
  - commands:
      - volume_mute
      - volume_down
      - volume_up
```
