### DISCUSSION TITLE
Allow statistics sensor or other sensor for gauge to use max/min

### DISCUSSION THREAD

**Discussion by maweki** [home-assistant/frontend#7630] [Dashboard]
I have several petrol stations near me and I show their current gas prices in a gauge. Currently I have to enter what I consider low and high prices manually as min and max. But this changes monthly as prices are not very stable.

Now I have a statistics sensor that calculates min and max over the last two weeks and I wanted to do something like this:

```YAML
                type: gauge
                entity: sensor.tankerkoenig_supermarkt_leipzig_e10
                name: Kaufland
                min: {{ state_attr("sensor.benzin_statistics", "min_value") }}
                max: {{ state_attr("sensor.benzin_statistics", "max_value") }}
```

And I understand this doesn't work as lovelace does not allow templating in these attributes. But it would be really useful to also allow sensors/entities as min/max or a single statistics sensor (or other sensor that provides `min_value` and `max_value`).

Being able to customize this would also be helpful otherwise as well, like for a temperature sensor that would have different ranges depending on the season.
