### DISCUSSION TITLE
add core scrollable text card (or extend Log card to also accept text files)

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#7796] [Dashboard]
Please consider the following addition to the core cards, to be able to show scrollable text files.

This would in fact be a grand substitute for the state machine 'abusive' variable Custom integrations. Imagine this use case: being able to show in the front end the chronological state changes of a sensor now created with this variable:

```
  set_daylight_variables:
    alias: Set Daylight variables
    mode: restart
    sequence:
      service: variable.set_variable
      data:
        variable: daylight_variables
        attributes:
          history_1: "{{states('variable.daylight_variables')}}"
          history_2: "{{state_attr('variable.daylight_variables','history_1')}}"
          history_3: "{{state_attr('variable.daylight_variables','history_2')}}"
          history_4: "{{state_attr('variable.daylight_variables','history_3')}}"
          history_5: "{{state_attr('variable.daylight_variables','history_4')}}"
          history_6: "{{state_attr('variable.daylight_variables','history_5')}}"
          history_7: "{{state_attr('variable.daylight_variables','history_6')}}"
          history_8: "{{state_attr('variable.daylight_variables','history_7')}}"
          history_9: "{{state_attr('variable.daylight_variables','history_8')}}"
          history_10: "{{state_attr('variable.daylight_variables','history_9')}}"
        value: >-
          {{as_timestamp(now())|timestamp_custom('%X')}}: {{states('binary_sensor.outside_daylight_sensor')}} : {{states('sensor.sun_elevation')}} :
          {% if states.sensor.driveway_buiten_sensor_light_level is not none %}
          {{states('sensor.driveway_buiten_sensor_light_level')}}
          {% else %} Not yet available
          {% endif %}
```

showing in the frontend like:

<img width="394" alt="Schermafbeelding 2020-11-24 om 11 16 29" src="https://user-images.githubusercontent.com/33354141/100080788-87734900-2e46-11eb-994e-a7125bf2f43f.png">

now consider adding a card, that can scroll a text file, create by the notify: file platform:

```
  - platform: file
    file_path: /config/logging/filed_daylight_settings.txt
    name: Filed daylight settings
```
and script:
```
  file_daylight_variables:
    alias: File Daylight variables
    mode: restart
    sequence:
      service: notify.filed_daylight_settings
      data:
        message: >
          {{as_timestamp(now())|timestamp_custom('%X')}}: Daylight: {{states('binary_sensor.outside_daylight_sensor')}} - Elevation: {{states('sensor.sun_elevation')}} -
          Light level:
          {% if states.sensor.driveway_buiten_sensor_light_level is not none %}
          {{states('sensor.driveway_buiten_sensor_light_level')}}
          {% else %} Not yet available
          {% endif %}
```

resulting in a text file `filed_daylight_settings.txt` (now experimentally filled for this purpose):

```
Home Assistant notifications (Log started: 2020-11-24T10:18:35.536308+00:00)
--------------------------------------------------------------------------------

11:31:14: Daylight: on - Elevation: 16.61 - Light level:  1976.97
11:31:37: Daylight: on - Elevation: 16.61 - Light level:  1976.97
11:31:37: Daylight: on - Elevation: 16.61 - Light level:  1976.97
11:31:38: Daylight: on - Elevation: 16.61 - Light level:  1976.97
11:31:39: Daylight: on - Elevation: 16.61 - Light level:  1976.97
11:31:39: Daylight: on - Elevation: 16.61 - Light level:  1976.97
11:31:40: Daylight: on - Elevation: 16.61 - Light level:  1976.97
11:31:40: Daylight: on - Elevation: 16.61 - Light level:  1976.97
```

would be awesome if we could scroll that text (and not have to resort to the markdown card, showing a [sensor file](https://www.home-assistant.io/integrations/file#sensor) entry which only shows the last line, and would come closest to a core solution for this purpose?)

or, maybe the new core log card can be developed to also show these text files created by the core platform  file notification

thanks for considering
