### DISCUSSION TITLE
Use a dedicated icon for YAML automations that cannot be edited in UI

### DISCUSSION THREAD

**Discussion by Mincka** [home-assistant/frontend#7912] [Dashboard]
Would it be possible to use the "Read-only" icon used the non-editable entities for Automations that are defined in YAML?

When you have YAML and UI automations, you are unable to tell which ones can be edited from the UI. There is a pen for all the automations and when you click on it, the pop-up tells you you cannot edit them.

By the way, it seems the tooltip is incorrect since it says the same thing than the one of the info button "Sow info about automation".

**Comment by spacegaier** [comment]
I fixed the edit tooltip a few days ago.

In my list I do have automations that cannot be edited and they get a crossed out edit pen icon plus have a matching tooltip:
![image](https://user-images.githubusercontent.com/114137/101260308-437a2100-372f-11eb-8b59-ba989a274474.png)

Do you have an example of a non editable automation that cannot be handled by the editor? If I create some in the YAML directly I can display and edit them through the UI just fine.

**Reply by Mincka** [reply]
Maybe I misunderstood the issue. Is it because my automations are loaded using `include_dir_list`? So indeed, they are not in `automations.yaml`.
```
automation: !include automations.yaml
automation split: !include_dir_list automation
```

Here is one example for which the pen is enabled and I get the error on click:

Stored in 
`/config/automation/area/buanderie/lave_linge_termine.yaml`
Loaded by `automation split: !include_dir_list automation`

```
id: '1575195793357'
alias: Buanderie - Lave-linge terminé
description: ''
trigger:
- entity_id: binary_sensor.buanderie_lavelinge_running
  from: 'on'
  platform: state
  to: 'off'
condition: []
action:
- data_template:
    entity_id: media_player.mini_salon
    volume_level: 0.15
  service: media_player.volume_set
- service: notify.mini_salon
  data:
    message: Lavage du linge terminé.
```
