### DISCUSSION TITLE
Allow globbing in entity_id on entities for card

### DISCUSSION THREAD

**Discussion by Zocker1999NET** [home-assistant/frontend#8019] [Configuration]
If a card supports showing multiple entities like `glance` or `entities`, enabling support of globbing (`*`) would enable a more abstract UI definition without explicit listing of all entities wanted to show.

This would make things possible like: I want to show all alerts currently not idle so I know about and can disable the alerts or re-enable them if required:
```yaml
- type: entity-filter
  entities:
    - "alert.*"
  state_filter:
    - operator: "!="
      value: idle
  show_empty: no
  card:
    type: entities
    title: Active Alerts
```
This would allow to write this once, forget about it, add an additional alert later on and the UI will do what I expected it to do, showing the new alert if it will go active.

Or another good example:
```yaml
- type: glance
  entities: "device_tracker.max_*"
```
If used together with the FRITZ!Box integration and if I name all my personal devices (a.k.a. their hostnames) `max_*` or `max-*`, then new devices will automatically show up in the UI without changing my lovelace configuration.
