### DISCUSSION TITLE
Simplify turning on scenes using header & footer buttons

### DISCUSSION THREAD

**Discussion by mfschumann** [home-assistant/frontend#8147] [Dashboard]
I like the concept of [header/footer buttons](https://www.home-assistant.io/lovelace/header-footer/) in lovelace cards, especially for quickly turning on scenes. 

Unfortunately, header/footer buttons don't support turning on scenes that are listed as entities, but you need to use a work-around, e.g. setting up scripts for each scene that turn it on and list those scripts as entities, or overriding tap_action with a call-service block.

I suggest to allow configurations like this to get rid of the overhead:

```
footer:
  type: buttons
  entities:
    - scene.living_room_dim_light
    - scene.living_room_bright_light
```

I think what would have to be done to add this feature is introducing a discrimination between entity types and triggering the turn_on action for scenes instead of the default toggle action.
