### DISCUSSION TITLE
add confirmation option for script in entities card

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#8249] [Dashboard]
would love to be able to use a confirmation on a script in an entities card directly, like:

```
      - entity: script.audio_system_off
        action_name: 'Off'
        tap_action:
          confirmation:
            text: Are you sure?
```
or even better:
```
      - entity: script.audio_system_off
        action_name: 'Off'
        confirmation:
          text: Are you sure?
```

in the above config, there is no confirmation at all, and I believe we can only do that by first defining the script to be the action  service of a button?

```
      - type: button
        name: Audio system off
        icon: mdi:audio-video-off
        tap_action:
          action: call-service
          confirmation:
            text: Are you sure?
          service: script.audio_system_off
```

this of course is way more complex, and, rather importantly, loses the option of the action name, which now is defaulted to 'Run', and the other script configurations, like name and icon.

below a screenshot of both entities in a card:

<img width="410" alt="Schermafbeelding 2021-01-27 om 11 45 56" src="https://user-images.githubusercontent.com/33354141/105981180-15adba80-6096-11eb-92b4-47cd969095f3.png">

Please consider adding the confirmation to the script directly in the entities card. It would be even better, if adding a confirmation could also cause a visual indication, like the locks above. Maybe like

```
      - entity: script.audio_system_off
        action_name: 'Off'
        confirmation:
          text: Are you sure?
          indicator: true
```
or
```
      - entity: script.audio_system_off
        action_name: 'Off'
        confirmation:
          text: Are you sure?
          indicator:
            icon: mdi:lock
```
secondary consideration: would it be feasible to change the default script action_name from 'Execute' to 'Run', like on the button. 'Execute' has some serious negative connotations, especially for non  native English speakers..

See community: https://community.home-assistant.io/t/how-to-set-a-confirmation-on-a-script-in-an-entities-card/273492

**Comment by spacegaier** [comment]
> 
> this of course is way more complex, and, rather importantly, loses the option of the action name, which now is defaulted to 'Run', and the other script configurations, like name and icon.
> 

I did some work on the Entities card in the last days and starting with the beta that was released today, the following is now possible (see beta docs https://next.home-assistant.io/lovelace/entities):
```
type: entities
entities:
  - type: button
    entity: script.start_netflix
    action_name: 'Off'
    icon: mdi:home
    tap_action:
      confirmation:
        text: Are you sure?  
```
That covers your use case.

Reg. "Execute": That is the same wording that is used throughout HA. Changing it here would be inconsistent plus you can override it anyway. For non-native speakers, it should be translated and I can only see "Execute" being used in English (and for some reason Portugese).

**Reply by Mariusthvdb** [reply]
Thanks, looking forward to trying that, though reading what you say, that only 'covers' my use case, if you are willing to overcomplicate things, using an intermediary button card, and having to re-state the config options already made in the script itself...

though an improvement to the current situation, I think it is really too bad we have to go all that way, simply for having a confirmation in a directly used script in an entities card, the most basic of all cards I Lovelace. Thats why I feel the confirmation option should really be added here:
https://next.home-assistant.io/lovelace/entities#options-for-entities

> Reg. "Execute": That is the same wording that is used throughout HA

not true ;-) as I found out yesterday and you can see in the screenshot above, it says 'Run' when the button is used. Which is way better.

**Reply by spacegaier** [reply]
> 
> Thanks, looking forward to trying that, though reading what you say, that only 'covers' my use case, if you are willing to overcomplicate things, using an intermediary button card, and having to re-state the config options already made in the script itself...

Like what? The icon from the script entity is taken over, so is the name. What is ignored?

> 
> > Reg. "Execute": That is the same wording that is used throughout HA
> 
> not true ;-) as I found out yesterday and you can see in the screenshot above, it says 'Run' when the button is used. Which is way better.

I meant that the automation and script editor both label it "Execute". The same strings / translation keys are used in this card as well. "Run" is used as default for a button, but in normal entity display scripts and scenes get the "Execute" button.

**Reply by Mariusthvdb** [reply]
> Like what? The icon from the script entity is taken over, so is the name. What is ignored?

not true, at least not  in my experience, see below:

using:
```
      - type: button
#        name: Audio system off
#        icon: mdi:audio-video-off
        tap_action:
          action: call-service
          confirmation:
            text: Are you sure?
          service: script.audio_system_off
```

results in:

<img width="416" alt="Schermafbeelding 2021-01-28 om 09 39 50" src="https://user-images.githubusercontent.com/33354141/106111808-cc6c7200-614c-11eb-8ad1-0108e3b59cba.png">

uncommenting the name to:

```
      - type: button
        name: Audio system off
#        icon: mdi:audio-video-off
        tap_action:
          action: call-service
          confirmation:
            text: Are you sure?
          service: script.audio_system_off
```
then makes it appear, but no icon is displayed:

<img width="417" alt="Schermafbeelding 2021-01-28 om 09 41 34" src="https://user-images.githubusercontent.com/33354141/106112027-1190a400-614d-11eb-8dd8-059b2e9e4227.png">


even though they are configured for the script:
<img width="939" alt="Schermafbeelding 2021-01-28 om 09 42 34" src="https://user-images.githubusercontent.com/33354141/106112182-384eda80-614d-11eb-9744-8d9bf048878b.png">


> "Run" is used as default for a button, but in normal entity display scripts and scenes get the "Execute" button.

well, you've got to admit, that's all not very intuitive..... in this case that, in that case this. Why nit here the same as on the entity, simply because it is a button? Some confusing logic is being used imho.

**Reply by spacegaier** [reply]
As I mentioned in the beginning, that is part of the current beta / next release, see the beta documentation I also linked above.

**Reply by Mariusthvdb** [reply]
o, sorry, I thought that was only referring to the confirmation/action_name

So, am I right then that for doing as I would have wanted on my entity script, I need to package it into a button:

```
type: entities
entities:
  - entity: script.audio_system_off
    action_name: 'Off'
    tap_action:
      confirmation:
        text: Are you sure?
```

needs to configured as a button:
```
type: entities
entities:
  - type: button
    entity: script.audio_system_off
    action_name: 'Off'
    tap_action:
      confirmation:
        text: Are you sure?
```

makes me wonder if we couldnt just bring back the action_name to the script config, like it was before and have the Lovelace frontend inherit that like name and icon

**Comment by Mariusthvdb** [comment]
getting back to this, now we're on 2021.2.1, I see an issue when clicking the Ok after the popup confirmation. The Cancel, which appears on a regular 'script execution' 

<img width="482" alt="Schermafbeelding 2021-02-07 om 15 29 54" src="https://user-images.githubusercontent.com/33354141/107149541-699f8580-6959-11eb-9c14-295b45892556.png">

doesn't show, nor does the script run.

```
      - type: button
        entity: script.reload_themes
        action_name: Reload themes
        tap_action:
          confirmation:
            text: Are you sure?
```
showing fine 
<img width="479" alt="Schermafbeelding 2021-02-07 om 15 26 17" src="https://user-images.githubusercontent.com/33354141/107149433-d9614080-6958-11eb-9fc0-62294649e4a6.png">

the pop up show Are you sure twice which is not as expected I guess:
<img width="574" alt="Schermafbeelding 2021-02-07 om 15 26 46" src="https://user-images.githubusercontent.com/33354141/107149458-f990ff80-6958-11eb-9fcb-096d203b1746.png">

and clicking ok does nothing.

btw, when we leave out the `type: button` as in my suggested config/FR I do get a popup, when clicking on the name of the entity, but again, clicking OK does nothing.
