### DISCUSSION TITLE
allow require_admin: for individual cards

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#8412] [Dashboard]
would be a very nice asset to be able to set `require_admin:` on an individual card. 

As it is now, we can do this for views/dashboards only. Already having a multiple view/dashboard organized Lovelace frontend, there are still several 'shared' views for both admin and non-admin, containing 1 or 2 cards that have sensitive info. With a `require_admin: `option for a single card, we would not have to create yet another view/dashboard. We could suffice with the shared setup, with the exception of this single card, only to e revealed when an admin watches the view.

with the growing set of sensors with sensitive info (geocoded_location, said, etc etc ) on the Mobile app, this 'need' is all the more pronounced.

thanks for considering

```
  - type: custom:auto-entities
    card:
      title: Geocoded
      type: entities
    filter:
      include:
        - entity_id: '*_geocoded_location'
    options:
      require_admin: true
```

I know this is an auto-entities card, but the idea should be clear: allow `require_admin: true` on the type: entities core card. Maybe even all core cards.
