### DISCUSSION TITLE
allow 'no icon' on button in footer

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#8781] [Dashboard]
using:
```
    footer:
      type: buttons
      entities:
      - entity: script.garage_lamellen_open
        icon: mdi:arrow-up
#        name: Open
      - entity: script.garage_lamellen_my
        name: My
        icon: '' # <-- trying to override the default script icon
      - entity: script.garage_lamellen_close
        icon: mdi:arrow-down
#        name: Close
```
to have the middle button only show the name 'My' doesnt work, it still shows the script icon:

<img width="439" alt="Schermafbeelding 2021-04-01 om 09 11 58" src="https://user-images.githubusercontent.com/33354141/113257055-55796400-92ca-11eb-8f75-8aecfae06e35.png">

please consider adding the option to not show the icon? 
thanks!
___edit___

comparing the footer with the regular buttons row in an entities card https://www.home-assistant.io/lovelace/entities/#show_icon I tried that, and it works miraculously ;-) Guess we already have an undocumented option. 

```
    footer:
      type: buttons
      entities:
      - entity: script.garage_lamellen_open
        icon: mdi:arrow-up
      - entity: script.garage_lamellen_my
        name: My
        show_icon: false         # <-----
      - entity: script.garage_lamellen_close
        icon: mdi:arrow-down
```
This then is rephrased as a FR too add it to [the documentation of the header/footer ](https://www.home-assistant.io/lovelace/header-footer/)
