### DISCUSSION TITLE
Add ip_ban_whitelist for HTTP Integration

### DISCUSSION THREAD

**Discussion by Veldkornet** [home-assistant/frontend#8955] [Other feature requests]
Currently in the [HTTP integration](https://www.home-assistant.io/integrations/http), you are able to set `ip_ban_enabled`, this is great... except the iOS Companion app seems to occasionaly fail to authenicate for some reason, and this causes my devices (phones / tablets) to stop working until I realise, after which I need to login via a device which has hopefully not been banned and clear the IP's listed in the ip_ban.yaml.

Ideally, I'd like to whitelist my local subnet to ensure that my local devices are never locked out, even if they for some reason do an authentication failure (thanks iOS companion app). The whitelist whould allow you to add individual IP's or IP subnets, much in the same way as you can with the trusted proxies.

An example configuration is below with the (to be added) `ip_ban_whitelist`:

```
# Example configuration.yaml entry
http:
  server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.32.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ip_ban_whitelist:
    - 192.168.1.0/24
```
