### DISCUSSION TITLE
(can no longer) add variables to default theme

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [home-assistant/frontend#9415] [Dashboard]
somehow an 'undocumented feature' has recently stopped working:
https://community.home-assistant.io/t/can-we-change-add-variables-to-default-theme/214507/2?u=mariusthvdb

we could do things like:

```
default:
  background-color-on: var(--card-background-color)
  background-color-off: var(--primary-color)

  text-color-on: var(--primary-color)
  text-color-off: var(--card-background-color)

  icon-color-on: var(--accent-color)
  icon-color-off: var(--card-background-color)

  active-color: var(--accent-color)

  accent_color: var(--state-icon-active-color)

  ha-card-border-radius: '0px'
  ha-card-box-shadow: '0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)'
  restriction-lock-row-margin-left: 95%
```
which worked wonders, and made it very easy to use these variables throughout the frontend configuration.

Ludeeus suggested this might have to do with the recent themes change 'to allow for dark/light modes to allways inherit default' on [Discord](https://discord.com/channels/330944238910963714/460846676358332417/853917109147140096).

Please have a look if we can get this back, and if so, make it a documented feature ;-)
(purposely writing this as a FR, and not a bug.... since it was undocumented and maybe considered a lucky hack)

thanks for considering

EDIT
since the big change was dark and light modes, I thought that could be the issue in the extra variables, so I also tried
```
default:
  modes:
    dark: &extra_options
      background-color-on: var(--primary-color)
      background-color-off: var(--card-background-color)

      background-opacity-on: rgba(var(--primary),0.8)
      background-opacity-off: rgba(var(--card-background),0.8)

      text-color-on: var(--card-background-color)
      text-color-off: var(--primary-color)

      icon-color-on: var(--accent-color)
      icon-color-off: var(--primary-color)

      active-color: var(--accent-color)

      accent_color: var(--state-icon-active-color)

      ha-card-border-radius: 0px
      ha-card-box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19)
      restriction-lock-row-margin-left: calc(100% - 25px) #95%

      primary: 3,168,243
      card-background: 255,255,255

    light: *extra_options
```

but that doesnt bring anything back from what was used before the move to dark/light mode. 

So, FR stands ;-)
