### DISCUSSION TITLE
Input_text password code for alarm control

### DISCUSSION THREAD

**Discussion by lzinga** [home-assistant/frontend#9877] [Configuration]
Currently the `alarm_control_panel` code gets set through the configuration.yaml. I believe it would be a decent enough feature to be able to set the code from an `input_text` field.

You can already configure an input_text to be a password, however it doesn't exactly secure the code. For example, being able to see it in the entities information.
![image](https://user-images.githubusercontent.com/9082450/130694190-8267882f-a171-4cc4-968c-38afaf2dbc51.png)

As an idea the `alarm_control_panel` configuration could look more like this.
```
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code:
        input_text:
            name: 'Alarm Control Code'
            pattern: '^\\d+$'
            initial: 1234
            mode: password
    arming_time: 30
    delay_time: 20
    trigger_time: 4
```
and then it will create a helper input to go along with the alarm control panel. As well as in general the `password` mode really should hide what the input is everywhere.

This way when calling the service to disarm or trigger the alarm with the code directly in the automation. We can instead use the value of said `secure` input in automations as needed.
