### DISCUSSION TITLE
More gauge colors

### DISCUSSION THREAD

**Discussion by dansrogers** [home-assistant/frontend#9920] [Dashboard]
Can we have more gauge colors?  Seems arbitrary to limit it to three.  I'd really like to recreate the colors for airnow.gov.

**Comment by dansrogers** [comment]
Example config
```
type: gauge
entity: sensor.airnow_aqi
min: 0
needle: true
severity:
  green: 0
  yellow: 50
  orange: 100
  red: 150
  purple: 200
max: 350
name: AirNow AirQuality

```
