### DISCUSSION TITLE
Customizable gauge coloring and allow repetition

### DISCUSSION THREAD

**Discussion by nivbromberg** [home-assistant/frontend#9998] [Dashboard]
When defining a gauge card, allow multiple colors (by name, RGB, hex code, or some other identifier).
Example syntax:
```yaml
severity:
      green: 0
      blue: 20
      yellow: 34
      red: 62
      black: 80
```
Or with hex codes:
```yaml
severity:
      33FF48: 0
      335AFF: 20
      FCFF33: 34
      FF4233: 62
      000000: 80
```
(Or some other encoding YAML allows)

This is useful for non-trinary states (e.g. plant fertilization or traffic status).
I believe that this feature can also be used/applied to allow repetition of colors (in a way YAML allows).
In my case, my plant moisture gauge is defined as:
```yaml
- type: gauge
  entity: sensor.flora2_moisture
  min: 0
  max: 100
  severity:
    yellow: 0
    green: 40
    red: 65
  needle: true
  name: Sweet Potato Moisture
```
![image](https://user-images.githubusercontent.com/17897330/132710049-06d8c410-a1c1-4ecc-964a-29b99978cc25.png)

And I'd like both ends of the gauge (0-40 and 65-100) to be the same color.
A generalization of my case: too-low and too-high both represent the same meaning (=bad=red).
So I believe this feature will be useful.

Theme selecting, as available today, still limits it to 3-states and is much more complex to define than simple support in the YAML definition.
