### ISSUE TITLE
Gauge card theme not working?

### ISSUE THREAD

**Issue by avehome** [home-assistant/frontend#10010]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Theme colors gauge not adjust:

![image](https://user-images.githubusercontent.com/50752001/132902843-ef9fca2a-1e92-4069-bfb3-6ea3d5ad19f5.png)

### Describe the behavior you expected

Gauge color should be the same like color (gold) in graph card below the gauge

### Steps to reproduce the issue

1. Update Home Assistant to latest version

### What version of Home Assistant Core has the issue?

core-2021.9.5

### What was the last working version of Home Assistant Core?

core-2021.8.8 maybe also core-2021.9.1

### In which browser are you experiencing the issue with?

Firefox, Safari

### Which operating system are you using to run this browser?

macOS Big Sur and Windows 10 (both latest version)

### Problem-relevant frontend configuration

```yaml
ui-lovelace info:

      - title: Elektra
        type: entities
        entities:
          - type: custom:hui-element
            card_type: horizontal-stack
            cards:
              - type: gauge
                title: Stroomverbruik
                entity: sensor.power_consumption_kwh_to_watt
                theme: gauge_card
                min: 0
                max: 4000
                severity:
                  green: 0
                  yellow: 0
                  red: 2000
                style: |
                  ha-card {
                    --ha-card-box-shadow: none;
                    margin: 2px -8px -20px -8px;
                  }
              - type: gauge
                title: Stroomopbrengst
                entity: sensor.power_production_kwh_to_watt
                theme: gauge_card
                min: 0
                max: 1800
                severity:
                  green: 0
                  yellow: 2500
                  red: 3000
                style: |
                  ha-card {
                    --ha-card-box-shadow: none;
                    margin: 2px -8px -20px -8px;
                  }

themes info:

daytime:
  # Main colors
  primary-color: '#00a1ff' # light blue
  accent-color: '#ffb300' # orange
  dark-primary-color: '#00a1ff' # light blue
  light-primary-color: '#00a1ff' # light blue

nighttime:
  # Main colors
  primary-color: '#2980b9' # blue
  accent-color: '#b58e31' # gold
  dark-primary-color: '#2980b9' # blue
  light-primary-color: '#2980b9' # blue

# Gauge Cards colors
gauge_card:
  label-badge-green: '#0e962e' # green
  label-badge-yellow: 'var(--accent-color)' # orange (daytime) or gold (nighttime)
  label-badge-red: '#cd1100' # red
```

### Additional information

Could this have happened after this fix:
Use correct vars for gauge colors #9727
