### ISSUE TITLE
Statistics Graph Card displays raw values instead of calibrated values from adc sensor

### ISSUE THREAD

**Issue by VitolsJun** [home-assistant/frontend#10033]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have 2 sensors among others configured in ESPhome.
One is "calibrated" using lambda expression and other using calibration filter.
Both show ppm values in entities card. (Home assistant receives calibrated values)
Graph card does show pulse sensor line correctly (the one with lambda expression)

**Graph card does not show calibrated value from adc sensor.
Instead it shows raw voltage (close to 0 down at the bottom of graph)**
```
  - platform: adc
    pin: 34 #<----------------pin
    name: "CO2_analog"
    unit_of_measurement: ppm
    update_interval: 5s
    filters:
      - calibrate_linear:
          # Point 1 -> 0.4V (from sensor) to 0.0    ppm (true value)
          # Point 2 -> 2.0V (from sensor) to 5000.0 ppm (true value)
          - 0.4 -> 0.0
          - 2.0 -> 5000
          
  - platform: pulse_width
    pin: 18 #<----------------pin
    name: "co2_pulse"
    unit_of_measurement: ppm
    update_interval: 5s
    filters:
      - lambda: return x*5000-10;
```
![image](https://user-images.githubusercontent.com/46457274/133200107-0d6961ea-88d7-4855-ab18-1ba563474420.png)

### Describe the behavior you expected

I expected these values to be represented in graph card.

![image](https://user-images.githubusercontent.com/46457274/133200201-e3231f01-9edc-4c2a-bb7d-780943f4d3a3.png)

### Steps to reproduce the issue

1. configure 2 sensors in ESPhome like I have posted
2. check if entities card shows real values
3. check if graph card shows raw values
...

### What version of Home Assistant Core has the issue?

core-2021.9.4

### What was the last working version of Home Assistant Core?

core-2021.9.4

### In which browser are you experiencing the issue with?

Google chrome Version 93.0.4577.63 , Mozilla also

### Which operating system are you using to run this browser?

Windows 7

### State of relevant entities

```txt
co2 analog state = 478.40
state_class: measurement
unit_of_measurement: ppm
friendly_name: CO2_analog
device_class: voltage

co2 pulse state = 461.565
state_class: measurement
unit_of_measurement: ppm
friendly_name: co2_pulse
icon: mdi:timer-outline
```

### Problem-relevant frontend configuration

```yaml
type: statistics-graph
entities:
  - sensor.co2_pulse
  - sensor.co2_analog
days_to_show: 1
stat_types:
  - mean

type: entities
entities:
  - entity: sensor.co2_analog
  - entity: sensor.co2_pulse
title: Sensor
card_mod:
  style: |
    ha-card {
      color: SeaGreen;
    }
```
