### ISSUE TITLE
Scrip Trace action horizontal alignment wrong

### ISSUE THREAD

**Issue by edenhaus** [home-assistant/frontend#10047]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The symbol of the action (red circle below) inside the default sequence of choose it not aligned correctly.
Maybe this error is related to the point that the action is in the choose action and the next action is also another choose action.

![grafik](https://user-images.githubusercontent.com/26537646/133649295-7b87b57e-381f-477b-948d-b501d9c4f07a.png)

### Describe the behavior you expected

A correct aligned symbol.
![grafik](https://user-images.githubusercontent.com/26537646/133649532-62cd92d2-1cd4-46d4-bfef-b1f02d482254.png)

### Steps to reproduce the issue

You the following test script:
```yaml
alias: Test
sequence:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ True }}'
        sequence:
          - delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
    default:
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - choose:
          - conditions:
              - condition: template
                value_template: '{{ True }}'
            sequence:
              - delay:
                  hours: 0
                  minutes: 1
                  seconds: 0
                  milliseconds: 0
        default:
          - delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
mode: single
```

### What version of Home Assistant Core has the issue?

2021.9.6

### In which browser are you experiencing the issue with?

Firefox 90.0, Chrome 93.0.4577.82 and also Android/iOS App

### Which operating system are you using to run this browser?

Ubuntu 20.10

### Additional information

Trace json:
[trace script.1631809332304 2021-09-16T16 22 21.995096+00 00.json.zip](https://github.com/home-assistant/frontend/files/7179476/trace.script.1631809332304.2021-09-16T16.22.21.995096%2B00.00.json.zip)

Maybe this issue is related to #9536
