### ISSUE TITLE
Numbering for automation trace does not match choose option numbering

### ISSUE THREAD

**Issue by blhoward2** [home-assistant/frontend#10058]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When setting up an automation using the Choose action type, options are numbered 1, 2, 3 in the UI. However, the corresponding automation trace timeline says that choice 0, 1, 2 were executed. While this is obviously a start counting at 0 or 1 issue, the different approaches could be confusing to users.

### Describe the behavior you expected

I'd expect the trace to say Choice 1 was executed, to mean that Option 1 was executed. Actually, I'd expect the language Choice vs Option to match as well, but the numbering is more important if there is a reason for that distinction.

### Steps to reproduce the issue

1. Create automation with multiple choices
2. Run automation
3. View Trace Timeline
...

### What version of Home Assistant Core has the issue?

2021.9.7

### State of relevant entities

```txt
State: 64.0
```

### Additional information

**Automation:**

```yaml
alias: Humidity - Upstairs Bath
description: ''
trigger:
  - platform: state
    id: switch
    entity_id: switch.upstairs_bathroom_fan
  - platform: numeric_state
    entity_id: sensor.upstairs_bath_humidity
    above: '70'
    id: high_limit
  - platform: numeric_state
    entity_id: sensor.upstairs_bath_humidity
    below: '65'
    id: low_limit
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: switch
          - condition: numeric_state
            entity_id: sensor.upstairs_bath_humidity
            below: '65'
        sequence:
          - delay:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
          - service: switch.turn_off
            target:
              entity_id: switch.upstairs_bathroom_fan
      - conditions:
          - condition: trigger
            id: switch
          - condition: numeric_state
            entity_id: sensor.upstairs_bath_humidity
            above: '70'
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.upstairs_bathroom_fan
      - conditions:
          - condition: trigger
            id: high_limit
          - condition: state
            entity_id: switch.upstairs_bathroom_fan
            state: 'off'
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.upstairs_bathroom_fan
      - conditions:
          - condition: trigger
            id: low_limit
          - condition: state
            entity_id: switch.upstairs_bathroom_fan
            state: 'on'
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.upstairs_bathroom_fan
    default: []
mode: restart

```

**As displayed in the Automation UI:**
<img width="1048" alt="Screen Shot 2021-09-19 at 11 51 07 PM" src="https://user-images.githubusercontent.com/33612110/133955444-7637a59c-a72e-47c4-bb5e-f474a5bf4717.png">

**Corresponding trace timeline for the first choice being executed:**

<img width="959" alt="Screen Shot 2021-09-19 at 11 50 21 PM" src="https://user-images.githubusercontent.com/33612110/133955418-0db7e4e1-3792-4800-af19-55729bca34f2.png">
