### ISSUE TITLE
Automation Last Triggered Does Not Update When Automation Stops as Condition Fails

### ISSUE THREAD

**Issue by new-kirte** [home-assistant/frontend#10050]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Last Triggered date and time is not updated for all automations:
![image](https://user-images.githubusercontent.com/10042655/133779707-e47ed915-5449-433d-82c9-28f11859a78b.png)
Both scripts have been triggered:
![image](https://user-images.githubusercontent.com/10042655/133779805-ac4b79ac-f31b-4e94-a6db-2d7f616ded08.png)
![image](https://user-images.githubusercontent.com/10042655/133779907-cb35422e-ba03-4345-9538-81858cbfc178.png)
The only difference is automation Alex is Up v1.0 fails due to condition, but Alex is Up v2.0 completes the execution

### Describe the behavior you expected

Last Trigerred shows the time when an automation has been trigerred regardless of the automation execution state

### Steps to reproduce the issue

1. Create an automation 1 with failing condition and automation 2 without condition
2. Wait for both automations to be triggered
3. Lat Trigerred is updated only for automation 2
...

### What version of Home Assistant Core has the issue?

Home Assistant 2021.9.6

### In which browser are you experiencing the issue with?

Microsoft Edge version 93.0.961.47

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
alias: Alex is up v1.0
description: ''
trigger:
  - platform: state
    attribute: motion_video_time
    entity_id: camera.chuangmi_ipc019_7398_camera_control
condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: '0'
  - condition: template
    value_template: >-
      '{{ as_timestamp(trigger.to_state.attributes.motion_video_time) -
      as_timestamp(trigger.from_state.attributes.motion_video_time) <= 420 }}'
action:
  - service: notify.mobile_app_z_flip
    data:
      message: >-
        Alex is up
        '{{as_timestamp(trigger.to_state.attributes.motion_video_time)}}',
        '{{as_timestamp(trigger.from_state.attributes.motion_video_time)}}'; '{{
        trigger.to_state.attributes.motion_video_time
        }}','{{trigger.from_state.attributes.motion_video_time}}'
      title: Alex is up
mode: single

alias: Alex is up v2.0
description: ''
trigger:
  - platform: state
    attribute: motion_video_time
    entity_id: camera.chuangmi_ipc019_7398_camera_control
condition: []
action:
  - service: notify.mobile_app_z_flip
    data:
      message: >-
        Alex is up '{{ trigger.from_state.attributes.motion_video_time }}', '{{
        trigger.to_state.attributes.motion_video_time }} {{
        as_timestamp(trigger.from_state.attributes.motion_video_time)-as_timestamp(trigger.to_state.attributes.motion_video_time)
        }}'
      title: Alex is up
mode: single
```
