### ISSUE TITLE
‘Backend-selected’ theme no longer applies light/dark mode on Supervisor panel

### ISSUE THREAD

**Issue by gvssr** [home-assistant/frontend#10178]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using XX Theme with both a light and dark mode, setting the user theme to ‘Backend—selected’ no longer applies the dark mode on the Supervisor panel (and HACS panel). Theming **is** properly applied when setting the theme manually and switching device modes, just no longer with backend-selected. First reported at: https://github.com/home-assistant/core/issues/57206

### Describe the behavior you expected

When switching to the device dark-mode, the dark mode theme should be applied to the Supervisor panel.

### Steps to reproduce the issue

1. Set user theme to backend-selected
2. Switch device mode to dark (iOS, Windows)
3. Open Supervisor panel

### What version of Home Assistant Core has the issue?

2021.10

### What was the last working version of Home Assistant Core?

2021.9

### In which browser are you experiencing the issue with?

Safari, Chrome, Edge

### Which operating system are you using to run this browser?

iOS 15, Windows 11

### Problem-relevant frontend configuration

```yaml
Snippet of .yaml theme:

homeOS Theme:
  modes:
    light:
      # Custom: Alert
      alert-card-background: rgb(255, 253, 231)
      alert-primary-text-color: rgb(66, 66, 6
    dark:
      # Custom: Alert
      alert-card-background: rgb(47, 47, 152)
      alert-primary-text-color: rgb(242, 242, 242)
```

### Additional information

Setting theme to backend-selected:
![05F3DF48-976E-4557-BF92-4080D679701B](https://user-images.githubusercontent.com/61377476/136337255-1cef227f-813c-41cf-ba64-ab0416188d05.jpeg)

Viewing Supervisor in dark-mode:
![4C67634D-6D4E-415C-BBB6-7C597AA83FB5](https://user-images.githubusercontent.com/61377476/136337262-416f250d-4ef4-440e-8318-b5a225b820ca.png)

Setting theme manually:
![CC041634-F7DC-4AC6-A62C-E32DCD213747](https://user-images.githubusercontent.com/61377476/136337605-6e6fa335-ac32-4992-b249-d5b3f86227e6.jpeg)

Viewing Supervisor in dark-mode (expected & proper behavior):
![EAB564AD-D370-4D15-BF7D-A1881D314C5F](https://user-images.githubusercontent.com/61377476/136337615-a37f7a02-6116-455b-9b79-7e64105deb5e.png)
