### ISSUE TITLE
History-graph: 'name' not shown for switch domain entity

### ISSUE THREAD

**Issue by Masterz69** [home-assistant/frontend#10233]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As per https://www.home-assistant.io/lovelace/history-graph/ - entity name shown before graph for switches: https://www.home-assistant.io/images/lovelace/lovelace_history_graph.png

But it now works. Have:
```
          - type: history-graph
            entities:
              - entity: switch.hw_pump_plg
                name: Hot Water Pump
```
but no name shown:
![image](https://user-images.githubusercontent.com/15225823/136761484-fdad8d87-a530-4075-98ce-f7717fbf0a5a.png)

Nor entity name not shown, not 'name' defined override.

### Describe the behavior you expected

Entity name to be shown preceed to graph.

### Steps to reproduce the issue

Create history-graph card for switch entity.

### What version of Home Assistant Core has the issue?

core-2021.10.2

### What was the last working version of Home Assistant Core?

do not know

### In which browser are you experiencing the issue with?

Google Chrome	93.0.4577.82 (Official Build) (64-bit) (cohort: 93_Win_82) Revision	e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}

### Which operating system are you using to run this browser?

OS	Windows 10 OS Version 2009 (Build 19042.1237)

**Comment by Masterz69** [comment]
More details see below. IMHO it depends not on entity domain, but on number of entities (switch & binary_sensor checked) in graph.

```yaml
          - type: history-graph
            entities:
              - entity: binary_sensor.hw_pump_on
                name: HW1
              - entity: binary_sensor.hw_pump_power
                name: HW2
```
results in:
![image](https://user-images.githubusercontent.com/15225823/147694335-d400a119-fc4b-49a4-bf65-45cc0226ee83.png)

As soon only one entity is used to graph:
```yaml
          - type: history-graph
            entities:
              - entity: binary_sensor.hw_pump_on
                name: HW1
```
name is not displayed anymore:
![image](https://user-images.githubusercontent.com/15225823/147694427-7e8fbfe0-c141-4bdd-a007-e7887303f85e.png)
