### ISSUE TITLE
history-graph to match X-axis for sensors with & w/out units

### ISSUE THREAD

**Issue by Masterz69** [home-assistant/frontend#10234]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/15225823/136783334-07b8d1d6-0731-4eb4-afe9-238f1447d909.png)

As seen on picture X-Axis not same places for different sensors inside same card. It make harder to match events with values.

### Describe the behavior you expected

Match X-axis placement - see red arrow.

### Steps to reproduce the issue

Just create history-graph card with entities with & w/out units.

### What version of Home Assistant Core has the issue?

core-2021.10.2

### In which browser are you experiencing the issue with?

93.0.4577.82 (Official Build) (64-bit) (cohort: 93_Win_82)

### Which operating system are you using to run this browser?

Windows 10 OS Version 2009 (Build 19042.1237)

### Problem-relevant frontend configuration

```yaml
- type: history-graph
            entities:
              - entity: switch.hw_pump_plg
                name: Hot Water Pump
              - entity: sensor.boiler_sns_h_hw
                name: Hot Water
              - entity: sensor.boiler_sns_h_hw_ret
                name: Return
              - entity: sensor.boiler_sns_h_cw
                name: Cold Water
            hours_to_show: 9
            refresh_interval: 60
```
