### ISSUE TITLE
Device_class: battery - icon stopped changing

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#10332]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since 2020.10 my battery level sensors have static icon.
Earlier the icon depended on state, now it is always same:
![image](https://user-images.githubusercontent.com/71872483/137968537-046bc34e-bd1c-4293-913a-954c90291fd4.png)

### Describe the behavior you expected

The icon should depend on a state:
...
mdi-battery-90
...
mdi-battery-50
...
etc

### Steps to reproduce the issue

1. Create s template sensor for battery level with "device_class: battery":
```
sensor:
  - platform: template
    sensors:
      test_battery_level:
        unit_of_measurement: '%'
        device_class: battery
        value_template: "{{ states('input_number.test_level_1') }}"
```

2. Check if the sensor's icon is changing dependingly on a battery level.

### What version of Home Assistant Core has the issue?

core-2021.10.6

### What was the last working version of Home Assistant Core?

core-2021.9.x

### In which browser are you experiencing the issue with?

Chrome 94.0.4606.81, Firefox 93

### Which operating system are you using to run this browser?

Win10x64
