### ISSUE TITLE
visible: option on view does not hide for non set users

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#10366]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

using the [visible ](https://www.home-assistant.io/lovelace/views/#visible) option on a view does not hide the view from non listed users.
Any page used in a dashboard with a specific user set for visible is displayed for all users.

### Describe the behavior you expected

only show the view to a listed user

### Steps to reproduce the issue

1. make a view with the `visible:` option
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.11dev20211022

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

Safari, Chrome, FF

### Which operating system are you using to run this browser?

Big sur 11.6

### Problem-relevant frontend configuration

```yaml
title: Settings motion
path: settings_motion
visible: 3a8redacted356b63
icon: mdi:run-fast
cards:

title: Light settings
path: light_settings
icon: mdi:home-lightbulb
visible:
  - user: 3a8redacted356b63
cards:
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

nothing much really, other than a discussion I started earlier for allowing 'require_admin: true' also on views.

btw, I also tested the above configs with a secret (dont want the user_id in the frontend lovelace files)

```
title: Settings motion
path: settings_motion
visible: !secret admin
#background: radial-gradient(crimson, skyblue)
icon: mdi:run-fast
cards:

title: Light settings
path: light_settings
icon: mdi:home-lightbulb
visible:
  - user: !secret admin
cards:
```

with the secret setup in secrets.yaml as:

```
admin: 3a8redacted356b63
```
