### ISSUE TITLE
Lists of entities in script condition

### ISSUE THREAD

**Issue by starkillerOG** [home-assistant/frontend#10473]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider the following 2 supported YAML formats for scripts that match a input_select to multiple posible states:

```
alias: Example list 
mode: single
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.example
            state: [state1,state2,state3,state4]
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.example_light
```

```
alias: Example list 
mode: single
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.example
            state:
            - state1
            - state2
            - state3
            - state4
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.example_light
```

If eather one of the formats is put in a script in the UI in "Edit as YAML" mode and then saved they will work just fine.
However oppon saving the frontend will automatically "parse" both versions and convert them to the following fomat:

```
alias: Example list 
mode: single
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.example
            state: state1,state2,state3,state4
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.example_light
```

Note that the [] have been removed automatically by HomeAssistant.
Now when you make some insignificant change (lets say change the alias) the formatter will go to work again and actually reformat this again now making it this:

```
alias: Example list 
mode: single
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.example
            state: "state1,state2,state3,state4"
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.example_light
```

Note the extra "" that have been put around the state, this breaks the script as now the input_select is no longer matching to state1, state2, state3 or state4 but only matches to the not even possible single state "state1,state2,state3,state4".

### Describe the behavior you expected

In the frontend of HomeAssistant in the script editor put in a list of states to match to like:
[state1,state2,state3,state4]
When you hit save, actually save this as [state1,state2,state3,state4] and do not remove the [] from the YAML.
Such that opon each subsequent save it will keep working and not break the script.

### Steps to reproduce the issue

1) Make the following script with the fronted and save:

```
alias: Example list 
mode: single
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.example
            state: [state1,state2,state3,state4]
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.example_light
```

2) Now test the script and see that it works
3) Go back to the script editor and make an insignificant change (like changing the alias or something irrelevant)
4) Save the script again.
5) Try to test the script again and see that it is now broken due to the diffrent formatting of the YAML

### What version of Home Assistant Core has the issue?

2021.10.6

### In which browser are you experiencing the issue with?

FireFox 93.0 (64-bits)

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
alias: Example list 
mode: single
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.example
            state: [state1,state2,state3,state4]
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.example_light
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Note that this is most likely not restricted to script conditions but probably also for automation conditions and most likely way brother in HomeAssistant in multiple places where lists can be used in YAML.
