### ISSUE TITLE
Sidebar - removing items and rearranging does not work

### ISSUE THREAD

**Issue by hklages** [home-assistant/frontend#10488]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As user "henning" I edited the sidebar but after logging out/in, the old one shows up again (with Media Browser, Map, ...)

![custom panel](https://user-images.githubusercontent.com/17273119/139651778-367dc487-a800-4c64-8ca5-e14cb84bb2f2.png)

### Describe the behavior you expected

I would expect, that my customized sidebar is stored and after logging in again shows up 

### Steps to reproduce the issue

1. profile user, Change the order and hide items from the sidebar
2. delete some, rearranged others and pushed the Done button
3. result: sidebar as expected
4. log out
5. log in as same user
6. "old" sidebar shows up agin
...

### What version of Home Assistant Core has the issue?

core-2021.10.6

### In which browser are you experiencing the issue with?

Edge Version 95.0.1020.40 (Official build) (64-bit)

### Which operating system are you using to run this browser?

windows 10

### Problem-relevant frontend configuration

```yaml
panel_custom:
  - name: ha_server_con
    sidebar_title: ServerControl
    sidebar_icon: mdi:cog-transfer
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/server_control"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
  - name: ha_auto
    sidebar_title: Automations
    sidebar_icon: mdi:cog-outline
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/automation"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

panel_iframe:
  homepilot:
    title: "HomePilot"
    url: "http://192.168.178.27"
    icon: mdi:window-shutter
```

### Javascript errors shown in your browser console/inspector

```txt
none
```
