### ISSUE TITLE
History graph: bad position for on and off graph datapoints.

### ISSUE THREAD

**Issue by mdeweerd** [home-assistant/frontend#10489]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

History graph: bad position for on and off graph datapoints.

Straight graph line for shown values, not as steep as initial line while consumption is increasing.

I discovered this on the next top graph.  My daily consumption is higher than the day before, but the incoming line is steeper than the line between the points in view. (the bottom graph shows the amount of increase which is added to the total at a fixed time each day).

![image](https://user-images.githubusercontent.com/1504752/139652184-e8e4da1b-e0a1-499a-80a6-46b4c151505b.png)

Increasing the number of hours shown on the history graph, revealed that the line shown in the graph is straight even with a different consumption each day.

The expectation is that the graph shows multiple segments with different steepness.

The graph for multiple days:
![image](https://user-images.githubusercontent.com/1504752/139652744-18b0be71-ecf3-448d-b41b-19b0e2b91b20.png)

Context

I get the daily gas consumption from the suppliers API once per day.
I add this to a counter so that I get a total increasing sum.

The next table shows the summation values for the last few days and the increase for each day. 

|Sum|Increase
|-|-
1758|  +71
1829|  +74
1903|  +81
1984|  +84
2068| N/A

The next graph is supposed to show the incoming line from 1903kWh, shows the data points at 1984kWh and 2068kWh and ends flat as the next increase is pending.
The previous increase was 81 and the one fully in the graph is 84, so the incoming line should be flatter than the one shown.

I then increased the number of hours shown to check that this was just an issue for the incoming line.
However, it appears that despite the unequal daily consumptions, the line shown is flat.
To demonstrate that there are indeed different datapoints equal to the table provided above, here are different screenshots with the popups at the datapoints:

![image](https://user-images.githubusercontent.com/1504752/139652416-8d0b63bc-1881-4dfb-88a0-3a1cab1c8969.png)

![image](https://user-images.githubusercontent.com/1504752/139652475-090d76d4-8bf8-467e-acf5-7957f0c95213.png)

![image](https://user-images.githubusercontent.com/1504752/139652522-cd5bb62f-ccc3-4dc0-aae0-955e9e676b6f.png)

![image](https://user-images.githubusercontent.com/1504752/139652903-580c9a1e-4a42-4455-a54c-12a75bc10e35.png)

![image](https://user-images.githubusercontent.com/1504752/139652600-2f8ff631-8429-4c0a-9f26-0b373ba01f97.png)

### Describe the behavior you expected

- I expected to see a line coming from the datapoint outside the graph with a lower steepness to be inline with the steepness of the next line segment which has a higher increase;
- I expected to see multiple segments on the graph with different steepness when showing data for multiple days.

### Steps to reproduce the issue

I am not sure how to reproduce this, I suppose with similar datapoints.

### What version of Home Assistant Core has the issue?

2010

### What was the last working version of Home Assistant Core?

core-2021.10.6

### In which browser are you experiencing the issue with?

Version 95.0.4638.69 (Build officiel) (64 bits) & Firefox 93.0 (64 bits)

### Which operating system are you using to run this browser?

Windows 10 20H2 Build 19042.1288

### State of relevant entities

![image](https://user-images.githubusercontent.com/1504752/139655374-a40ea537-e81d-41db-88ab-3cd87dd95abb.png)

### Problem-relevant frontend configuration

```yaml
The datapoints are provided in the report.
For completeness, this is the yaml for the history graph (the duration for the first graph was 48):

  - title: Conso
    path: conso
    type: panel
    badges: []
    cards:
      - type: history-graph
        entities:
          - entity: sensor.current_summation_derived
          - entity: sensor.current_summation
          - entity: sensor.current_demand_log
          - entity: counter.gas_consumption
          - entity: sensor.gas_consumption_kwh
          - entity: sensor.gas_consumption_m3
          - entity: sensor.compteur_gazpar
        refresh_interval: 4
        hours_to_show: 120
```

Definition of the counter shown (with the issue):
```yaml
counter:
  gas_consumption:
    initial: 0
    restore: true
```

Automation increasing it:
```yaml
- id: '1633280482973'
  alias: Accumuler consommation Gazpar
  description: Ajoute la consommation du jour pr..c..dent au compteur global
  trigger:
  - platform: time
    at: '23:30:00'
  condition: []
  action:
  - service: counter.configure
    target:
      entity_id: counter.gas_consumption
    data:
      value: '{{ states(''counter.gas_consumption'') | float + states(''sensor.compteur_gazpar'')
        | float }}'
  mode: single
```

### Javascript errors shown in your browser console/inspector

![image](https://user-images.githubusercontent.com/1504752/139655374-a40ea537-e81d-41db-88ab-3cd87dd95abb.png)
### Additional information

![image](https://user-images.githubusercontent.com/1504752/139654020-18028f68-d3a8-47a8-8f5f-055ea46f7e2f.png)
