### ISSUE TITLE
Dark mode theme switch colors no longer being applied

### ISSUE THREAD

**Issue by gvssr** [home-assistant/frontend#10514]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Looks like switch-checked-button-color and switch-unchecked-button-color are no longer themeable, and grab their color values from other parts of the system.

### Describe the behavior you expected

It used to be you could define discrete color values for switches in dark mode. This still works for switches in light mode.

### Steps to reproduce the issue

1. Apply theme with defined switch colors

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What was the last working version of Home Assistant Core?

core-2021.10.7

### In which browser are you experiencing the issue with?

Safari, Google Chrome, Edge

### Which operating system are you using to run this browser?

iOS 15, Windows 11

### Problem-relevant frontend configuration

```yaml
switch-checked-button-color: rgb(255, 255, 255)
switch-checked-track-color: rgb(48, 208, 88)
switch-unchecked-button-color: var(--switch-checked-button-color)
switch-unchecked-track-color: rgb(154, 160, 166)
```

**Comment by ManCaveMedia** [comment]
I don't know if this is the same thing, but when selecting a theme on a markdown card, it's not being applied on the dashboard. I'm hesitant to open a new bug if it's the same as this one.

**Comment by spacegaier** [comment]
> 
> 
> I don't know if this is the same thing, but when selecting a theme on a markdown card, it's not being applied on the dashboard. I'm hesitant to open a new bug if it's the same as this one.

Please open a new bug report, because I cannot reproduce it. Perhaps there is something specific in your example, but just adding a markdown card and setting a theme for it, works fine.

**Comment by spacegaier** [comment]
@gvssr I cannot reproduce the issue. This theme works fine:

``` 
switch_button:
  switch-checked-button-color: "green"
  switch-checked-track-color: "yellow"
  switch-unchecked-button-color: "red"
  switch-unchecked-track-color: "yellow"
```

![image](https://user-images.githubusercontent.com/114137/140625060-ef22b40d-374f-4124-8d29-b053bbbcea6b.png)

**Comment by gvssr** [comment]
@spacegaier that'a because the bug only occurs when there are zeerste light and dark modes defined in the same theme. This worked correctly in 2021.10.x and before. I used your code as an example:

In light mode:
![image](https://user-images.githubusercontent.com/61377476/140625370-cbab17f1-4abd-4f17-8acf-ce871d715a8d.jpeg)

In dark mode:
![image](https://user-images.githubusercontent.com/61377476/140625379-1626b01b-7f76-47d8-9635-fea3dfe3a212.jpeg)

Exact theme code I used based on your example:

```
test theme:
  modes:
    light:
      switch-checked-button-color: "green"
      switch-checked-track-color: "yellow"
      switch-unchecked-button-color: "red"
      switch-unchecked-track-color: "yellow"
    dark:
      switch-checked-button-color: "green"
      switch-checked-track-color: "yellow"
      switch-unchecked-button-color: "red"
      switch-unchecked-track-color: "yellow"
```
