### ISSUE TITLE
Logbook Card does not group entries correctly

### ISSUE THREAD

**Issue by orandasoft** [home-assistant/frontend#10519]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have configured the Logbook Card to show log entries for 48 hours. The entries for the current day are all grouped under one header (today's date). Each entry of the previous day have their own header (same previous date).

### Describe the behavior you expected

Previous date's log entries are also grouped under one header.

### Steps to reproduce the issue

1. configure logbook card to display 48 hours
2. show 48 hours of entries in the logbook card
3.
...

### What version of Home Assistant Core has the issue?

core-2011.11.0

### In which browser are you experiencing the issue with?

Latest version of Edge and Chrome

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
type: logbook
entities:
  - binary_sensor.psm02_hallway_multi_sensor_motion
  - sensor.psm02_hallway_multi_sensor_air_temperature
  - binary_sensor.psm02_hallway_multi_sensor_low_battery_level
  - sensor.psm02_hallway_multi_sensor_illuminance
  - sensor.psm02_hallway_multi_sensor_battery_level
  - binary_sensor.abode_keypad_motion_sensor
  - binary_sensor.abode_motion_sensor
  - sensor.aarlo_last_hallway_camera
  - sensor.aarlo_recent_activity_hallway_camera
  - binary_sensor.aarlo_motion_hallway_camera
  - binary_sensor.aarlo_motion_light_hallway
  - binary_sensor.recessed_door_sensor_7_access_control_window_door_is_open
  - binary_sensor.tapo_c200_2_motion
hours_to_show: 48
```
