### ISSUE TITLE
CSS variables incorrect in <hui-view> in the "dark" color mode

### ISSUE THREAD

**Issue by andornaut** [home-assistant/frontend#10529]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Theme: [IBM1970 theme](https://github.com/andornaut/homeassistant-ibm1970-theme), which supports dark and light modes. (I am the author of this theme)

Since upgrading to 2021.11.0, the` --primary-background-color`,  `--card-background-color` and possibly other CSS variable values are not propagated to the main content area of the overview page when in dark mode. These same values are propagated correctly when in light mode. In fact, simply renaming "dark" to "light" in the [theme's YAML](https://github.com/andornaut/homeassistant-ibm1970-theme/blob/main/themes/ibm1970.yaml#L20) and then selecting the light mode in the user profile works-around this issue (though, this is not ideal, because the bug continues to be in effect if the dark mode is selected). Note that this appears to only affect the "Overview" page, but I haven't checked all possible pages.

In the example below, the expected `--primary-background-color` is "#464333", but is "#111111" present instead.

```
<ha-app-layout> /* has expected --primary-background-color */
    <hui-view> /* does NOT have expected --primary-background-color */
```
### Expected
Highlighting the custom element - `<ha-app-layout>` with the correct CSS variable value: #464333
![1 expected](https://user-images.githubusercontent.com/737842/140325168-8235a6ae-9eca-4477-8f53-2035187635e4.png)

### Wrong
Highlighting the custom element - `<hui-view>` with the **incorrect** CSS variable value: #111111
![2 wrong](https://user-images.githubusercontent.com/737842/140325182-4d0aca29-4d1f-4ef1-9804-c93511ffc2d7.png)

### Expected after renaming "dark" to "light"

After swapping "light" and "dark" in the [theme's YAML](https://github.com/andornaut/homeassistant-ibm1970-theme/blob/main/themes/ibm1970.yaml#L20), and then selecting "light" (but since the names were swapped this actually uses the "dark" configuration as in the examples above), the bug is no longer present. The bug is present when selecting the dark mode (but now using the configuration that was formerly the "light" mode, since the names were swapped). This shows that this bug is only present when the dark mode is selected regardless of theme configuration.

![3 expected](https://user-images.githubusercontent.com/737842/140325183-82a5e4ad-2721-42ce-8c1f-14c08ae289ea.png)

### Describe the behavior you expected

The color set in the theme applies to the main content area of the overview page.

### Steps to reproduce the issue

1. Install a theme that customizes the --primary-background-color CSS variable.
2. Select "dark" mode
3. Navigate to the Overview page
4. Note that the background color is not the one set by the theme.

### What version of Home Assistant Core has the issue?

core-2021.11.0

(The bug was also present in core-2021.11.0b0)

### What was the last working version of Home Assistant Core?

core-2021.10.7

### In which browser are you experiencing the issue with?

Firefox 90.0 and Chrome 95.0

### Which operating system are you using to run this browser?

Ubuntu 20.10

#### themes/ibm1970.yaml

```yaml
ibm1970:
  accent-color: '#33a999'
  app-header-background-color: 'var(--sidebar-background-color)'
  app-header-edit-background-color: 'var(--accent-color)'
  app-header-text-color: 'var(--sidebar-text-color)'
  disabled-text-color: '#999'
  label-badge-green: 'var(--accent-color)'
  light-primary-color: '#eeeccc'
  scrollbar-thumb-color: 'var(--sidebar-background-color)'
  sidebar-icon-color: 'var(--sidebar-text-color)'
  sidebar-selected-icon-color: 'var(--primary-text-color)'
  sidebar-selected-text-color: 'var(--primary-text-color)'
  state-icon-active-color: '#d0b550'
  switch-unchecked-button-color: 'var(--scrollbar-thumb-color)'
  switch-unchecked-track-color: 'var(--scrollbar-thumb-color)'
  text-primary-color: 'var(--card-background-color)'
  modes:
    dark:
      card-background-color: '#646050'
      divider-color: '#24201a'
      error-color: '#d55'
      mdc-theme-on-secondary: 'var(--card-background-color)'
      primary-background-color: '#464333'
      primary-color: '#ccc8b0'
      primary-text-color: '#eeeccc'
      secondary-background-color: '#9c9977'
      secondary-text-color: '#9c9977'
      sidebar-background-color: '#7c7755'
      sidebar-text-color: '#24201a'
      state-icon-color: 'var(--primary-background-color)'
    light:
      card-background-color: '#dddccc'
      divider-color: 'var(--primary-color)'
      error-color: '#b11'
      primary-background-color: '#eed'
      primary-color: '#646050'
      primary-text-color: '#24201a'
      secondary-background-color: 'var(--card-background-color)'
      secondary-text-color: '#646050'
      sidebar-background-color: '#ccc8b0'
      sidebar-text-color: 'var(--primary-color)'
      state-icon-color: 'var(--primary-color)'
```

### Additional information

This is what the dark mode color theme should look like:
![dark-colors-small](https://user-images.githubusercontent.com/737842/140327274-77bdbf1d-d80a-47bc-ba7c-48765e9a636a.png)
