### ISSUE TITLE
Scene Buttons Fail to call service scene.turn_on

### ISSUE THREAD

**Issue by nullpanda** [home-assistant/frontend#10550]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Expect to click button and it activates scene.

### Describe the behavior you expected

Click button and it gives toast error:
`Failed to call service scene/turn_on. must contain at least one of entity_id, device_id, area_id.
`

### Steps to reproduce the issue

1. Create a button on a lovelace dashboard, configure as such replacing names where necessary:
  - type: button
    tap_action:
      action: call-service
      service: scene.turn_on
      target:
        entity_id: scene.lr_off
      service_data: {}
    entity: scene.lr_off
    name: Living Room Off
    icon: mdi:lightbulb-group-off
2. Tap button
3. ???
4.  Toast error
...

### What version of Home Assistant Core has the issue?

core-2021.11.1

### What was the last working version of Home Assistant Core?

core-2021.10.7

### In which browser are you experiencing the issue with?

Chrome 95.0.4638.69 | Firefox 94.0.1

### Which operating system are you using to run this browser?

Windows 10 21H1 build 19043.1288

### State of relevant entities

```txt
All effected scenes are in state 'scening'.
```

### Problem-relevant frontend configuration

```yaml
type: grid
cards:
  - type: button
    tap_action:
      action: call-service
      service: scene.turn_on
      target:
        entity_id: scene.lr_off
      service_data: {}
    entity: scene.lr_off
    name: Living Room Off
    icon: mdi:lightbulb-group-off
  - type: button
    tap_action:
      action: call-service
      service: scene.turn_on
      target:
        entity_id: scene.lr_dim
      service_data: {}
    entity: scene.lr_dim
    name: Living Room Dim
    show_state: false
    icon: mdi:lightbulb-group-outline
  - type: button
    tap_action:
      action: call-service
      service: scene.turn_on
      target:
        entity_id: scene.lr_on
      service_data: {}
    entity: scene.lr_on
    icon: mdi:lightbulb-group
    name: Living Room On
columns: 3
square: false
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

No logs populate in home-assistant.log for these toast errors.

https://imgur.com/a/BDBLnQT
