### ISSUE TITLE
"entity" and "entities" show value of input_datetime differently

### ISSUE THREAD

**Issue by rbiez** [home-assistant/frontend#10579]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using 24 hour time format the card "entity" and "entities" show the state of input_datetime differently. "Entity" shows 0 hours as 24. Problem does not occur if using 12 hour AM/PM setting

![Untitled](https://user-images.githubusercontent.com/26358715/140818266-acf58e30-3c8f-4a91-970d-677fce58535d.png)
.

### Describe the behavior you expected

should be consistent, both preferably showing 0 hours, not 24

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.11.1

### In which browser are you experiencing the issue with?

Google Chrome 95.0.4638.69

### Which operating system are you using to run this browser?

Windows 10 Pro 21H1 - 19043.1288

### State of relevant entities

```txt
Entity: input_datetime.dishwasher_running_time
 State: 00:22:00
Attributes:
  has_date: false
  has_time: true
  editable: true
  hour: 0
  minute: 22
  second: 0
  timestamp: 1320
  friendly_name: Dishwasher running time
  icon: mdi:dishwasher
```

### Problem-relevant frontend configuration

```yaml
To get them side by side, i use the type grid:

type: grid
cards:
  - type: entity
    entity: input_datetime.dishwasher_running_time
  - type: entities
    entities:
      - entity: input_datetime.dishwasher_running_time
```
