### ISSUE TITLE
Can't set cover position for Tuya cover programatically (Cover Service in Automation blows away scripting)

### ISSUE THREAD

**Issue by tensiondriven** [home-assistant/frontend#10584]
### The problem

When creating an automation using a cover provided by the Tuya app template code is deleted when the automation is saved.

For context, my goal is to write a sequence that will open a cover gradually by setting the position explicitly and using delays in a loop.

```
repeat:
  count: '2'
  sequence:
    - service: cover.set_cover_position
      target:
        entity_id:
          - cover.bedroom_blinds_south_curtain
          - cover.bedroom_shade_west_curtain
      data:
        position: {{ 1 }}
```

After clicking save and refreshing, the data value is lost:

```
service: cover.set_cover_position
target:
  entity_id:
    - cover.bedroom_blinds_south_curtain
    - cover.bedroom_shade_west_curtain
data: {}
```

If I use fixed value instead of a template value, the value is preserved, as in:

```
repeat:
  count: '2'
  sequence:
    - service: cover.set_cover_position
      target:
        entity_id:
          - cover.bedroom_blinds_south_curtain
          - cover.bedroom_shade_west_curtain
      data:
        position: 3
```

Is this a problem with the tuya cover implementation, or a known issue with something else?

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Tuya

### Example YAML snippet

```yaml
repeat:
  count: '2'
  sequence:
    - service: cover.set_cover_position
      target:
        entity_id:
          - cover.bedroom_blinds_south_curtain
          - cover.bedroom_shade_west_curtain
      data:
        position: {{ 1 }}
```
```


### Anything in the logs that might be useful for us?

```txt
No error appears in`/config/logs`
```

### Additional information

This was not possible for me to test prior to 2021.11 since the `cover` device class was not supported by Tuya.  I don't have any other covers with which to test to try to isolate if this is specific to Tuya, so it may be an issue in a different part of the system.
