### ISSUE TITLE
state_color not working for Switches inside Conditional in Entity Card

### ISSUE THREAD

**Issue by RussellAult** [home-assistant/frontend#10580]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In an Entity Card, the icons for Switch entities do not respond to the `state_color` option when they are placed in the `row:` section of a `type: conditional`. (For comparison, the icons for Light entities _do_ respond to `state_color` when inside a `type: conditional`.)

### Describe the behavior you expected

The icons of Switch entities inside a `type: conditional` should be coloured based on state.

### Steps to reproduce the issue

1. Create a Lovelace Entity Card with the same Switch both inside and outside a `type: conditional`
2. Turn on the switch

### What version of Home Assistant Core has the issue?

core-2021.11.1

### In which browser are you experiencing the issue with?

Firefox 78.15.0esr, Chromium 90.0.4430.212 (Developer Build)

### Which operating system are you using to run this browser?

Debian 11.1

### State of relevant entities

```txt
Entity: switch.foo
  state: on
```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - type: conditional
    conditions: []
    row:
      entity: switch.foo
  - entity: switch.foo
  - type: conditional
    conditions: []
    row:
      entity: light.bar
  - entity: light.bar
title: Hello World!
show_header_toggle: false
state_color: true
# Note that the second icon for switch.foo (and both icons for light.bar) change colour with state, but the first icon for switch.foo does not
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

![image](https://user-images.githubusercontent.com/6781011/140825932-45c651f2-7fcf-4098-89ff-162b15799247.png)
