### ISSUE TITLE
Panel mode, picture elements card displays elements incorrectly and does not resize them

### ISSUE THREAD

**Issue by user897943** [home-assistant/frontend#10609]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is how my card looks like on normal mode (masonry):
![image](https://user-images.githubusercontent.com/5891221/141469022-63a000e4-73ab-4d70-bda6-e3f2e0d8ee5e.png)

And this is how the same card looks like on panel mode:
<img width="2103" alt="home assistant card on panel mode" src="https://user-images.githubusercontent.com/5891221/141469119-253625e7-4f08-4b0e-8ac3-550e8573c549.png">

This is simply terrible. It's been like this ever since the picture elements card was made available. It's really time to fix this problem, because HA is made on the premise that it can be used on all sorts of different screen sizes, this is evidenced by the interface being responsive. If so, it must conform to ideals of a responsive interface which is to adapt the elements to fit by resizing and repositioning correctly.

### Describe the behavior you expected

I expect the icons to be in the correct position and to be of the correct size when Panel mode is enabled. If I use my ctrl+wheel to zoom in, it resizes correctly, like this:
![image](https://user-images.githubusercontent.com/5891221/141469436-a4b740d3-0be6-4432-b99d-387440eb18ef.png)

### Steps to reproduce the issue

1. create a dummy binary sensor with icon (to represent stuff like warning light), and a dummy sensor with text (to represent stuff like tire pressure)
2. Add to the below code and test panel mode and masonry mode. On masonry mode, hold ctrl and scroll the wheel to zoom, the card resizes correctly with the elements staying in place, but after enabling panel mode on zoom 100% the elements do not resize and do not stay where they should.

code for card replace with your dummy sensors to test)
```
type: picture-elements
title: Mercedes-Benz C250d AMG Line Premium
image: /local/w205.png
elements:
  - type: conditional
    conditions:
      - entity: sensor.car_lockfrontdoorright
        state: Unlocked
    elements:
      - type: image
        entity: sensor.car_lockfrontdoorright
        image: /local/car-door-lock.svg
        style:
          top: 30%
          left: 43.2%
          width: 3%
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_lockfrontdoorright
        state: Locked
    elements:
      - type: image
        entity: sensor.car_lockfrontdoorright
        image: /local/car-door-lock.svg
        style:
          top: 30%
          left: 43.2%
          width: 3%
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_frontrightwindow
        state: Open
    elements:
      - type: image
        entity: sensor.car_frontrightwindow
        image: /local/car-windshield-outline.svg
        style:
          top: 30%
          left: 49%
          width: 3%
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_frontrightwindow
        state: Closed
    elements:
      - type: image
        entity: sensor.car_frontrightwindow
        image: /local/car-windshield-outline.svg
        style:
          top: 30%
          left: 49%
          width: 3%
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_lockreardoorright
        state: Unlocked
    elements:
      - type: image
        entity: sensor.car_lockreardoorright
        image: /local/car-door-lock.svg
        style:
          top: 30%
          left: 59%
          width: 3%
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_lockreardoorright
        state: Locked
    elements:
      - type: image
        entity: sensor.car_lockreardoorright
        image: /local/car-door-lock.svg
        style:
          top: 30%
          left: 59%
          width: 3%
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_rearrightwindow
        state: Open
    elements:
      - type: image
        entity: sensor.car_rearrightwindow
        image: /local/car-windshield-outline.svg
        style:
          top: 30%
          left: 65%
          width: 3%
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_rearrightwindow
        state: Closed
    elements:
      - type: image
        entity: sensor.car_rearrightwindow
        image: /local/car-windshield-outline.svg
        style:
          top: 30%
          left: 65%
          width: 3%
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_lockfrontdoorleft
        state: Unlocked
    elements:
      - type: image
        entity: sensor.car_lockfrontdoorleft
        image: /local/car-door-lock.svg
        style:
          top: 89.5%
          left: 43.2%
          width: 3%
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_lockfrontdoorleft
        state: Locked
    elements:
      - type: image
        entity: sensor.car_lockfrontdoorleft
        image: /local/car-door-lock.svg
        style:
          top: 89.5%
          left: 43.2%
          width: 3%
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_frontleftwindow
        state: Open
    elements:
      - type: image
        entity: sensor.car_frontleftwindow
        image: /local/car-windshield-outline.svg
        style:
          top: 89.5%
          left: 49%
          width: 3%
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_frontleftwindow
        state: Closed
    elements:
      - type: image
        entity: sensor.car_frontleftwindow
        image: /local/car-windshield-outline.svg
        style:
          top: 89.5%
          left: 49%
          width: 3%
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_lockreardoorleft
        state: Unlocked
    elements:
      - type: image
        entity: sensor.car_lockreardoorleft
        image: /local/car-door-lock.svg
        style:
          top: 89.5%
          left: 59%
          width: 3%
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_lockreardoorleft
        state: Locked
    elements:
      - type: image
        entity: sensor.car_lockreardoorleft
        image: /local/car-door-lock.svg
        style:
          top: 89.5%
          left: 59%
          width: 3%
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_rearleftwindow
        state: Open
    elements:
      - type: image
        entity: sensor.car_rearleftwindow
        image: /local/car-windshield-outline.svg
        style:
          top: 89.5%
          left: 65%
          width: 3%
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_rearleftwindow
        state: Closed
    elements:
      - type: image
        entity: sensor.car_rearleftwindow
        image: /local/car-windshield-outline.svg
        style:
          top: 89.5%
          left: 65%
          width: 3%
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_sunroof
        state: Open
    elements:
      - type: image
        entity: sensor.car_sunroof
        image: /local/cards-variant.svg
        style:
          top: 49%
          left: 50.5%
          width: 3%
          transform: rotate(270deg)
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_sunroof
        state: Closed
    elements:
      - type: image
        entity: sensor.car_sunroof
        image: /local/cards-variant.svg
        style:
          top: 49%
          left: 50.5%
          width: 3%
          transform: rotate(270deg)
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: conditional
    conditions:
      - entity: sensor.car_trunk
        state: Open
    elements:
      - type: image
        entity: sensor.car_trunk
        image: /local/tray.svg
        style:
          top: 49%
          left: 85%
          width: 3%
          transform: rotate(270deg)
          filter: >-
            invert(31%) sepia(83%) saturate(7045%) hue-rotate(353deg)
            brightness(101%) contrast(127%)
  - type: conditional
    conditions:
      - entity: sensor.car_trunk
        state: Closed
    elements:
      - type: image
        entity: sensor.car_trunk
        image: /local/tray.svg
        style:
          top: 49%
          left: 85%
          width: 3%
          transform: rotate(270deg)
          filter: >-
            invert(71%) sepia(75%) saturate(5248%) hue-rotate(85deg)
            brightness(126%) contrast(120%)
  - type: state-label
    entity: sensor.car_frontrighttire
    style:
      top: 23%
      left: 16%
      transform: scale(0.7)
  - type: state-label
    entity: sensor.car_frontlefttire
    style:
      top: 83%
      left: 16%
      transform: scale(0.7)
  - type: state-label
    entity: sensor.car_rearlefttire
    style:
      top: 83%
      left: 66%
      transform: scale(0.7)
  - type: state-label
    entity: sensor.car_rearrighttire
    style:
      top: 23%
      left: 66%
      transform: scale(0.7)
  - type: state-label
    entity: sensor.car_odometer
    style:
      top: 0%
      left: '0'
      transform: scale(0.7)
  - type: state-label
    entity: sensor.car_nextservice
    style:
      top: 0%
      left: 83.5%
      transform: scale(0.7)
  - type: state-label
    entity: sensor.car_range
    style:
      top: 87%
      left: 0%
      transform: scale(0.7)
  - type: state-label
    entity: sensor.car_fuellevel
    style:
      top: 87%
      left: 86.5%
      transform: scale(0.7)
  - type: state-icon
    entity: binary_sensor.car_park_brake_status
    style:
      top: 6.5%
      left: 32%
      transform: scale(0.7)
  - type: state-icon
    entity: binary_sensor.car_low_brake_fluid_warning
    style:
      top: 6.5%
      left: 37%
      transform: scale(0.7)
  - type: state-icon
    entity: binary_sensor.car_engine_light_warning
    style:
      top: 6.5%
      left: 42%
      transform: scale(0.7)
  - type: state-icon
    entity: binary_sensor.car_low_coolant_level_warning
    style:
      top: 6.5%
      left: 47%
      transform: scale(0.7)
  - type: state-icon
    entity: sensor.car_12vbattery
    style:
      top: 6.5%
      left: 52%
      transform: scale(0.7)
  - type: state-icon
    entity: binary_sensor.car_low_wash_water_warning
    style:
      top: 6.5%
      left: 57%
      transform: scale(0.7)
  - type: state-icon
    entity: binary_sensor.car_tire_warning
    style:
      top: 6.5%
      left: 62%
      transform: scale(0.7)
  - type: state-label
    entity: sensor.car_ignitionstatusshort
    style:
      top: 14%
      left: 1%
      transform: scale(0.7)
```
background image:
![w205](https://user-images.githubusercontent.com/5891221/141469887-5e99d271-c067-4a0c-a1d8-ad84dbaa3a22.png)
![w205](https://user-images.githubusercontent.com/5891221/141469888-1016e03b-5146-4ba5-8048-9bd70d9b84e6.png)

### What version of Home Assistant Core has the issue?

core-2021.11.3

### What was the last working version of Home Assistant Core?

Never worked

### In which browser are you experiencing the issue with?

Edge Win, Edge Linux - both chromium-based, Edge Android, Chrome Android, Firefox Win.

### Which operating system are you using to run this browser?

Android 12 (Pixel 6 Pro), Win 11, Win 10, Debian Bullseye
