### ISSUE TITLE
Jumping UI

### ISSUE THREAD

**Issue by ukrolelo** [home-assistant/frontend#10606]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Jumping UI i am not able to see the first history graph alt text
Video self explanatory:
https://www.youtube.com/watch?v=01jZMm2SMRQ

### Describe the behavior you expected

show the alt text so it will not jump the UI

### Steps to reproduce the issue

1.Third row history graph in UI (FULL HD res)
2.move the mouse on the history graph

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What was the last working version of Home Assistant Core?

-

### In which browser are you experiencing the issue with?

Chrome Version 95.0.4638.69 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Win8.1

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: switch.obeh_cerpadlo
  - entity: switch.hdo_tc_stop
  - entity: switch.elektro_kotel
hours_to_show: 24
refresh_interval: 0
title: Obehove, HDO, Elektrokotel
```

### Javascript errors shown in your browser console/inspector

```txt
-
```

### Additional information

Didn't test any other browser (don't have any other installed and IE can't login)
