### ISSUE TITLE
Temperature conversion via templates not correct

### ISSUE THREAD

**Issue by mfratto** [home-assistant/frontend#10629]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Temperatures are set to Imperial by default. I have the Octoprint integration installed. I had created the following template in "customize.yaml" to  display printer temps in Celsius. It worked fine. At some point (sorry, I don't print as often as I update Home Assistant!), an update to Home Assistant broke the conversion process.

```
sensor.octoprint_actual_bed_temp:
  unit_of_measurement: °C
```
The resulting output is captured below:
![FireShot Pro Screen Capture #029 - '3D Printer - Home Assistant' - 192_168_1_241_8123_3d-printer-_0](https://user-images.githubusercontent.com/651614/141869867-16eb2d11-82f3-4fe7-ba34-75d3d9b23e80.png)

The line that reads "Actual Bed Temp" should be in Celsius and labeled C.
Another thing to note is that the 4th from the bottom and second from the bottom entries should be the same. The only difference is that the line "Actual Bed Temp" has the sensor template above applied while the 194 is the actual temp reported in farenheit.

### Describe the behavior you expected

Expected a display conversion to Celsius.

### Steps to reproduce the issue

1. HA core-2021.11.3
2. Set default temp to Farenheit
3. Have a temperature reported in Farenheit
4. Use a template to convert to Celsius in customize.yaml
5. Reload core to set the change.

### What version of Home Assistant Core has the issue?

core-2021.11.3

### In which browser are you experiencing the issue with?

Firefox 94.0.1, Chrome 96.0.4664.45 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro, 21H2, 19043.1237

### State of relevant entities

```txt
state_class: measurement
unit_of_measurement: °F
friendly_name: OctoPrint actual bed temp
device_class: temperature
```

### Problem-relevant frontend configuration

```yaml
customize.yaml
sensor.octoprint_actual_bed_temp:
  unit_of_measurement: °C

Card yaml
type: entities
entities:
  - entity: sensor.octoprint_current_state
    name: Current State
  - entity: sensor.octoprint_estimated_finish_time
    name: Estimated Finish Time
  - entity: sensor.octoprint_job_percentage
    name: Job Percentage
  - entity: binary_sensor.octoprint_printing_2
    name: Printing
  - entity: binary_sensor.octoprint_printing_error
    name: Printing Error
  - entity: sensor.octoprint_start_time
    name: Start Time
  - entity: sensor.octoprint_actual_bed_temp
    name: Actual bed temp
  - entity: sensor.octoprint_actual_tool0_temp
    name: Actual tool0 temp
  - entity: sensor.octoprint_target_bed_temp
    name: Target bed temp
  - entity: sensor.octoprint_target_tool0_temp
    name: Target tool0 temp
title: OctoPrint
footer:
  type: graph
  entity: sensor.plug_1_current_consumption
  hours_to_show: 24
  detail: 2
```
