### ISSUE TITLE
Calender month view empty

### ISSUE THREAD

**Issue by GHeiner** [home-assistant/frontend#10634]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a kalander synced through CALDAV to my Synology calendar. before u[grading to the latest version of HA the month view was populated with appointments.

Now the day view and week view is working, after I click turn off and on of the calendar at the calendars list on the left site of the screen.

When I selected the week view and then the month view that week is also visible in the month view. 

The calendar state is showing the correct appointment

### Describe the behavior you expected

The calendar views are correct populated and I don't have to turn the off and on again.

### Steps to reproduce the issue

1. Add an caldav calendar to home assistant
2. populated the calendar
3. slik in the menu on the left on the calendar symbol
4. choose different lay-outs
5. turn off and on the calendar
...

### What version of Home Assistant Core has the issue?

core-2021.11.4

### What was the last working version of Home Assistant Core?

2021.10.7

### In which browser are you experiencing the issue with?

Safari 15.1, chrome Versie 95.0.4638.69 (Officiële build) (x86_64)

### Which operating system are you using to run this browser?

Mac OS 12.0.1 Monterey

### Problem-relevant frontend configuration

```yaml
#CALDAV Integration
calendar:
  - platform: caldav
    username: !secret cal_user_id
    password: !secret cal_user_secret
    url: https://FQDN/caldav.php/HACalendar
    custom_calendars:
      - name: 'Familie'
        calendar: 'Familie'
        search: '.*'
    days: 7
```

### Javascript errors shown in your browser console/inspector

```txt
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
```
