### ISSUE TITLE
Not able to select "Wait for a trigger" ID in automation actions

### ISSUE THREAD

**Issue by ZuluWhiskey** [home-assistant/frontend#10701]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the automation GUI, one of the 'Action types' is "Wait for a trigger". These triggers can be assigned a 'Trigger ID' (as can be done with the initial trigger of an automation), however I am then unable to select one of these trigger IDs when writing a 'Choose' action type. I am still able to select a trigger ID from the IDs available from the triggers, but not from the "Wait for trigger" triggers.

Also, I am unsure if this is relevant or not, when I switch to YAML mode in the UI and manually add the trigger into the YAML of the choose condition - The automation does not match that trigger when it actually runs, the default is used instead.

### Describe the behavior you expected

I would expect the GUI to provide me with the trigger IDs defined in both the automation triggers and the triggers in the 'wait for' action type.

### Steps to reproduce the issue

1. Create a new automation
2. Define a trigger and give it a trigger ID
3. Define a "wait for trigger" action and give that trigger an ID
4. Add a 'Choose' action and make the condition type 'Trigger'
5. Attempt to select the trigger ID for the "wait for trigger" trigger

### What version of Home Assistant Core has the issue?

core-2021.11.5

### In which browser are you experiencing the issue with?

Google Chrome Version 92.0.4515.107, Safari (iOS 15.1)

### Which operating system are you using to run this browser?

Windows 10 (Chrome) / iOS 15 (Safari)

### Problem-relevant frontend configuration

```yaml
Example automation YAML. In this example, sunrise can be set as a trigger in the choose condition but sunset cannot.

alias: Trigger ID Test
description: ''
mode: single
trigger:
  - platform: state
    entity_id: sun.sun
    to: above_horizon
    from: below_horizon
    id: sunrise
condition: []
action:
  - wait_for_trigger:
      - platform: state
        entity_id: sun.sun
        from: above_horizon
        to: below_horizon
        id: sunset
  - choose:
      - conditions:
          - condition: trigger
            id: ''
        sequence: []
    default: []
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_
