### ISSUE TITLE
Map card showing tiny entities/no images

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#10725]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

a type: map card is showing tiny pins currently, where before we saw larger circles on the map. Map is zoomed out much further too

### Describe the behavior you expected

show bigger circles, zoom out less

### Steps to reproduce the issue

1. create card config like below
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.12.0.dev20211129

### What was the last working version of Home Assistant Core?

2021.11 ?

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS Monterey 12.0.1 

### State of relevant entities

```txt
not home, obviously, but that doesn't really matter, other map card configs show the same tiny entities
```

### Problem-relevant frontend configuration

```yaml
- type: custom:auto-entities
    card:
      type: map
      title: Map on the road

    show_empty: false
    filter:
      include:
        - domain: person
          not:
            state: home
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

<img width="501" alt="Schermafbeelding 2021-11-29 om 13 46 31" src="https://user-images.githubusercontent.com/33354141/143870638-6c0a6e81-5c59-45a5-a4f0-13be59bc08fa.png">

**Comment by Mariusthvdb** [comment]
without custom:
```
  - type: map
    title: No picture & tiny pin
    entities:
      - device_tracker.life360_person
```

<img width="510" alt="Schermafbeelding 2021-11-29 om 13 56 32" src="https://user-images.githubusercontent.com/33354141/143872048-1133b872-cee8-4e34-9452-f40240c2ec71.png">

**Comment by spacegaier** [comment]
Works fine for me on Win 10, so maybe once again a Safari issue 😬?

Do the tracked devices have a name (just thinking what could potentially cause smaller circles).

**Comment by Mariusthvdb** [comment]
HI, no its not only Safari, also on Chrome and Firefox.
Also, this is showing with auto-entities, and listed entities. 
```
    - type: custom:auto-entities
      card:
        type: entities
      show_empty: false
      filter:
        include:
          - entity_id: 'geo_location.*'
        exclude:
          - attributes:
              source: wwlln
```

does still show as before:
<img width="494" alt="Schermafbeelding 2021-11-29 om 14 19 09" src="https://user-images.githubusercontent.com/33354141/143875164-c5b655dc-9a06-415e-ae8b-45c04c6a7cbd.png">
