### ISSUE TITLE
Logbook 'show trace' link includes action script name rather than automation name

### ISSUE THREAD

**Issue by jarrah31** [home-assistant/frontend#10768]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I run an automation that actions scripts, the 'show trace' link within the Logbook entry for that automation has the wrong URL.

For example, when I hover my mouse over the show trace link, the screenshot below shows the link as being:
`http://192.168.1.10:8123/config/automation/trace/opple_kitchen_2_single?run_id=2cd3eb532a0d6c48d3ac51c4a8516af3`

Note that the URL includes "opple_kitchen_2_single" rather than the automation id name "aqara_opple_kitchen_room"

<img width="880" alt="image" src="https://user-images.githubusercontent.com/3072303/144438323-ee738416-ee6e-4f67-9b13-cd8872a9e24a.png">

When you click the link, it results in a “Chosen trace is no longer available” error message.

This doesn't appear to happen all the time as sometimes the show trace link is valid. I haven't been able to pin down when the error occurs.

I'm reporting this bug based on the following HA Forum discussion:
https://community.home-assistant.io/t/automation-and-script-debugging/361630 

### Describe the behavior you expected

The 'show trace' link within Logbook should have the automation name in the URL and not the script name that was actioned

### Steps to reproduce the issue

The following are just two automation examples where the link hasn't worked. It has done this with many other automations as well.
```
  - alias: Bed3 Bedside Night Light Button
    id: bed3_bedside_nightlight_button
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.xiaomi_switch_sw10_action
    action:
      - choose:
          - conditions: "{{ trigger.to_state.attributes.action == 'single' }}"
            sequence:
              - service: script.opple_bed3_2_hold
          - conditions: "{{ trigger.to_state.attributes.action == 'double' }}"
            sequence:
              - service: script.opple_bed3_1_double
          - conditions: "{{ trigger.to_state.attributes.action == 'hold' }}"
            sequence:
              - service: script.opple_bed3_1_hold
```
```
  - alias: "Aqara Opple kitchen Room"
    id: aqara_opple_kitchen_room
    initial_state: 'on'
    trigger:
    - platform: mqtt
      topic: 'zigbee2mqttcc1352/switch_opple_kitchen'
    variables:
      config:
        button_1:
        - single
        - hold
        button_2:
        - single
        - hold
        button_3:
        - single
        - double
        - triple
        button_4:
        - single
        - double
        - triple
        - hold
        button_5:
        - single
        - double
        - triple
        - hold
        button_6:
        - single
        - double
        - triple
        - hold
      event: >
        {{ trigger.payload_json.action | default('button_0_invalid') }}
      items: >
        {{ event.split('_') }}
      button: >
        {{ items[-2] }}
      action: >
        {{ items[-1] }}
      continue: >
        {{ action in config.get('button_' ~ button, []) }}
      service: >
        script.opple_kitchen_{{ button }}_{{ action }}
    condition:
    - condition: template
      value_template: "{{ continue }}"
    action:
    - service: "{{ service }}"
```

### What version of Home Assistant Core has the issue?

core-2021.11.5

### In which browser are you experiencing the issue with?

Chrome 95.0.4638.69, Safari 15.1

### Which operating system are you using to run this browser?

macOS Monterey

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```
