### ISSUE TITLE
input_select s no longer follow card width

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#10776]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

after updating to 2021.12.0.dev20211203
<img width="514" alt="Schermafbeelding 2021-12-03 om 11 11 11" src="https://user-images.githubusercontent.com/33354141/144585892-b24244ce-4cb6-4bcc-85db-9c3f672d6748.png">

### Describe the behavior you expected

regular width, like before:

<img width="509" alt="Schermafbeelding 2021-12-03 om 11 10 57" src="https://user-images.githubusercontent.com/33354141/144585481-56adf77d-4c33-4aa3-9588-20a1a1d3c963.png">

### Steps to reproduce the issue

1. simple card config like below
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.12.0.dev20211203

### What was the last working version of Home Assistant Core?

previous

### In which browser are you experiencing the issue with?

Safari/Chrome/Firefox on Mac

### Which operating system are you using to run this browser?

macOS Monterey 12.0.1 

### Problem-relevant frontend configuration

```yaml
type: entities
title: Themes dashboard
card_mod:
  style: |
    .card-header {
      background-color: var(--background-color-off);
      color: var(--text-color-off);
      padding-top: 0px;
      padding-bottom: 0px;
      margin: 0px 0px 16px 0px;
    }
entities:
  - input_select.theme
  - input_select.set_kiosk_theme
  - input_select.set_full_house_theme
  - input_select.set_dev_theme
  - input_select.set_alarm_theme
  - input_select.set_sunrise_theme
  - input_select.set_sunset_theme
```
