### ISSUE TITLE
Duplicate trigger id for trigger condition in automation view

### ISSUE THREAD

**Issue by royto** [home-assistant/frontend#10793]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If an automation declares multiple times the trigger id, in the choose condition, trigger id are duplicated

![image](https://user-images.githubusercontent.com/6990995/144711150-62c5000c-755d-4261-bf4a-83ad1bb679e4.png)

### Describe the behavior you expected

Trigger id only contains unique values.
Sorting could be also a good thing

### Steps to reproduce the issue

1. Create an automation using multiple trigger with same id

```yaml
alias: Test Notification
description: ''
trigger:
  - platform: time
    id: 'on'
    at: '08:00'
  - platform: time
    id: 'off'
    at: '10:00:00'
  - platform: time
    id: 'on'
    at: '19:00:00'
  - platform: time
    id: 'off'
    at: '21:00:00'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: 'on'
        sequence:
          - service: notify.persistent_notification
            data:
              message: 'on'
    default:
      - service: notify.persistent_notification
        data:
          message: 'off'
mode: single

```
2. Use UI with `choose` action  and `trigger` condition  

### What version of Home Assistant Core has the issue?

core-2021.11.4
