### ISSUE TITLE
Entities Card Buttons Row: Buttons no longer centered in card row or automatically resized to fill card row

### ISSUE THREAD

**Issue by krazos** [home-assistant/frontend#10800]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to core-2021.12.0b0, the buttons in a multiple-buttons row in an entities card are no longer automatically resized based on the number of buttons, and are left-aligned rather than centered horizontally within the row (see screenshot below).

### Describe the behavior you expected

Prior to core-2021.12.0b0, the buttons automatically resized based on the number of buttons, and were centered horizontally within the row.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.0b0

### What was the last working version of Home Assistant Core?

core-2021.11.5

### In which browser are you experiencing the issue with?

Google Chrome 97.0.4692.36; Home Assistant iOS Companion App 2021.11.1

### Which operating system are you using to run this browser?

Various

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - type: buttons
    entities:
      - entity: script.good_morning
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.good_morning
      - entity: script.good_night
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.good_night
      - entity: script.goodbye
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.goodbye
      - entity: script.i_m_back
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.i_m_back
      - entity: script.nursery_gentle_wake_up
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.nursery_gentle_wake_up
      - entity: script.nursery_lullaby_radio
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.nursery_lullaby_radio
```

### Additional information

![Screenshot 2021-12-05 8 49 29 AM](https://user-images.githubusercontent.com/18428022/144749207-d9572584-7e00-4bf9-b13a-233550711009.png)
