### ISSUE TITLE
"Keep me logged in" no longer working with trusted_networks auth provider

### ISSUE THREAD

**Issue by casperklein** [home-assistant/frontend#10803]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

`configuration.yaml`:
```yml
    auth_providers:
      - type: trusted_networks
        trusted_networks:
            - 192.168.0.111/32
        # You can bypass login page if you have only one user available for selection.
        allow_bypass_login: true
```

There is no longer a popup, to keep logged in, when using the above configuration:

![129948295-b5c807e4-bb91-4293-9f78-a1a93d6655a4 1](https://user-images.githubusercontent.com/590174/144777872-85260b6e-5f5e-46cb-b062-b496979964f0.png)

I think, this is a regression of https://github.com/home-assistant/frontend/pull/10226 which removes the popup and moves it to the login page. However, with `allow_bypass_login: yes`, the login page is bypassed. In this scenario, a permanent login is no longer possible.

Workaround: `allow_bypass_login: false`

### Describe the behavior you expected

It should still be possible to permanently login, when using trusted network configuration `allow_bypass_login: true`.

### Steps to reproduce the issue

See issue description above.

### What version of Home Assistant Core has the issue?

core-2021.11.5

### What was the last working version of Home Assistant Core?

core-2021.9.x; maybe core-2021.10.x (not sure)

### In which browser are you experiencing the issue with?

Firefox 94.0.2
