### ISSUE TITLE
The provided value for 'for' is not supported by the visual editor.

### ISSUE THREAD

**Issue by jcbshw** [home-assistant/frontend#10824]
### The problem

Creating an automation in the UI that uses the 'for' option kicks you into yaml editor

### What version of Home Assistant Core has the issue?

core-2021.12.0b2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Example YAML snippet

```yaml
platform: state
entity_id: group.all_people
to: home
from: not_home
for:
  hours: 0
  minutes: 1
  seconds: 0
  milliseconds: 0
```
