### ISSUE TITLE
Key 'id' is not expected or not supported by the visual editor.

### ISSUE THREAD

**Issue by ridderr** [home-assistant/frontend#10825]
### The problem

In automation defining a trigger on a State, the Trigger ID which can be defined to be used in a Choice, is not accepted anymore. An error "Key 'id' is not expected or not supported by the visual editor." is given.
Editing in YAML is possible but this was working in Visual mode.

When a new trigger is defined and something is entered in the Trigger ID field, the editor switches over to YAML editing.

### What version of Home Assistant Core has the issue?

core-2021.12.0b2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Example YAML snippet

```yaml
platform: state
entity_id: binary_sensor.keukenraam_access_control_window_door_is_open
id: door_sensor
```
