### ISSUE TITLE
Blueprint > Time Selector > 22:00:00 = Invalid format

### ISSUE THREAD

**Issue by pticon91** [home-assistant/frontend#10822]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While writing a Blueprint and using Time Selector, default value 22:00:00 is being considered as incorrect, however value 022:00:00 passes.

### Describe the behavior you expected

Value 22:00:00 should be correct and 022:00:00 incorrect

### Steps to reproduce the issue

1. Use the YAML below
```
blueprint:
  name: Time Selector Defect
  domain: automation
  input:
    correct_time:
      name: Correct Time
      description: This will not pass
      default: 22:00:00
      selector:
        time:
    incorrect_time:
      name: Incorrect Time
      description: This will pass
      default: 022:00:00
      selector:
        time:
trigger:
  - platform: time
    at: !input incorrect_time
action:
  - service: notify.persistent_notification
    data:
      message: Hello World
```

### What version of Home Assistant Core has the issue?

core-2021.11.5
