### ISSUE TITLE
Trigger ID not supported in Visual Editor when using 'state' as trigger

### ISSUE THREAD

**Issue by Kertz1954** [home-assistant/frontend#10847]
### The problem

When using the Visual Editor to create an Automation (trigger - state - id) one gets the following message.

Visual editor is not supported for this configuration
Key 'id' is not expected or not supported by the visual editor.
You can still edit your config in YAML.

### What version of Home Assistant Core has the issue?

core-2021.12.0b5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automations

### Example YAML snippet

```yaml
alias: Test new state change
description: ''
trigger:
  - platform: state
    entity_id: sensor.de_bilt_now
    attribute: weatherdescription
    id: debilt
```

### Anything in the logs that might be useful for us?

```txt
None
```

### Additional information

![auto_trigger_state](https://user-images.githubusercontent.com/67558244/145464553-2c2439c0-2c42-46b2-8227-c0d353bf533a.png)

Automation's still work, even with 2 triggers and id's, plus actions choice based on id's.
