### ISSUE TITLE
The yaml view of the automation card does not stick to the card but with its index

### ISSUE THREAD

**Issue by sisimomo** [home-assistant/frontend#10900]
### The problem

![Home Assistant Bug](https://user-images.githubusercontent.com/27745204/145735927-a6221feb-ce12-4349-b8b3-11cea2a6cbdf.gif)

In editing or creating an automation, when moving any (Triggers, Conditions or Actions) card in yaml mode, the yaml view stick to the index of the card and not the card it self. You can see how this is problematic in the animated gif.

### What version of Home Assistant Core has the issue?

core-2021.12.0

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Link to integration documentation on our website

https://www.home-assistant.io/docs/automation/

### Example YAML snippet

```yaml
alias: Test Automation
description: ''
mode: single
trigger:
  - platform: device
    type: turned_on
    device_id: fe16552dbc2d6adc02613a59f20a28f7
    entity_id: switch.couch
    domain: switch
condition: []
action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: fe16552dbc2d6adc02613a59f20a28f7
    entity_id: switch.couch
    domain: switch
```
