### ISSUE TITLE
Dark Mode not working for some cards with non-default themes

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#10923]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The dark mode filter doesn't work when a non-default theme is chosen as dark theme. Map cards are also affected.

### Describe the behavior you expected

Map colors are inverted when dark mode is active. Even when a non-default theme is selected as dark mode.

### Steps to reproduce the issue

1. Install a theme (e.g. midnight)
2. Select the freshly installed theme as backend selected theme for dark mode
![Screenshot_20211214-224533](https://user-images.githubusercontent.com/15657682/146084398-d771aa43-d88e-48fb-8c48-c8783dd94701.png)
3. Configure a map card or use the `dark_mode_filter` property
4. Enable dark theme in mobile app settings
5. Enjoy :tad

### What version of Home Assistant Core has the issue?

2021.12.1

### What was the last working version of Home Assistant Core?

2021.9

### In which browser are you experiencing the issue with?

Chrome and Firefox

### Which operating system are you using to run this browser?

Android and Linux

### Problem-relevant frontend configuration

Map card:
```yaml
entities:
  - entity: person.a
  - entity: person.b
hours_to_show: 48
type: map
```

Picture elements

```yaml
elements:
  - entity: sensor.openweathermap_temperature
    style:
      left: 0.4in
      top: 0.4in
    type: state-label
  - entity: sensor.openweathermap_humidity
    style:
      left: 0.4in
      top: 0.6in
    type: state-label
...
image: /local/pictures/grundriss_farbe.png
entity: binary_sensor.anwesenheit
state_filter:
  'off': grayscale(100%)
dark_mode_filter: invert(100%)
type: picture-elements
```

### Additional information

Issue #10178 describes a similar issue. Both issues appeared with the same update.
