### ISSUE TITLE
Certain cards not displayed correctly using the view theme

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/frontend#10936]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since upgrading to 2021.12.x, I have noticed that if a view is set with a different theme, certain cards like `entities` is being displayed incorrectly where the text is using the color from the theme set for the user profile.

I have set the theme for a view to a dark theme, where the card background is a dark color and the text color is a light one. The theme for the rest of the views is set depending on the state of the sun. The issue occurs when the user profile theme is a light one where the text is dark. So hence the card background as well as the text colors are both dark and the text becomes unreadable.

![image](https://user-images.githubusercontent.com/54566217/146283828-cf9f8f2e-2c63-4a16-a985-e6915a91737b.png)

If I remove the theme for the view, the background color now uses the color from the user theme.

![image](https://user-images.githubusercontent.com/54566217/146283948-130abbec-36da-472d-a22d-880081959126.png)

### Describe the behavior you expected

All cards should reflect the theme defined in the view that it is defined.

### Steps to reproduce the issue

1. Create a view and set it to a dark theme
2. Add an `entities` or `glance` card
3. The text and icons in the card ignores the colors from the theme set in the view and uses the theme from the profile.
...

### What version of Home Assistant Core has the issue?

2021.12.2

### What was the last working version of Home Assistant Core?

2021.11.4

### In which browser are you experiencing the issue with?

Chrome Version 96.0.4664.93 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Enterprise 20H2

**Comment by idoaflalo** [comment]
This problem happens to me too

**Comment by idoaflalo** [comment]
Please help!

**Comment by Sian-Lee-SA** [comment]
This is a serious outstanding issue that I can't understand how the bug found it's way into the source code to begin with... The issue is simply a matter of the cards are now rendering the base theme in their own style attribute's giving it precedence over the view theme! Simply put, this now makes view themes completely irrelevant and redundant. The cards that don't have a theme set to them should not be rendering a style attribute in the element with the core themes variables. This is also a waste of resource's as it renders the document with many irrelevant style attributes causing a larger download and unneeded processing.

**Comment by bramkragten** [comment]
Please share the themes used

**Comment by Sian-Lee-SA** [comment]
Core Theme:-
```yaml
clear:
  # Background / Header !! Use header layout here as love assign theme within the lovelace tag
  lovelace-cc-header-background: 'linear-gradient(45deg, #62c6e042, #ffffff00)'
  lovelace-cc-elements: '#84a3ca'
  lovelace-cc-tab-indicator: '#68cccc'
  lovelace-cc-active-tab: var(--lovelace-cc-tab-indicator)
  
  # Colors
  text-color: '#636B75'                                                           # Grey text
  text-medium-color: '#8c96a5'                                                    # Medium grey text
  text-light-color: '#BAC0C6'                                                     # Light grey text
  accent-color: '#00a1ff'                                                         # Blue
  background-color: '#F7F8F9'                                                     # Light grey background
  background-color-2: '#F4F5F6'                                                   # Light grey background
  background-card-color: 'rgba(255,255,255,0.65)'                                  # White background
  border-color: '#EAEAEA'                                                         # Light grey border

  # Header
  primary-color: 'var(--text-color)'                                              # Background
  text-primary-color: '#FFF'                                                      # Text

  # Left Menu
  paper-listbox-background-color: 'var(--background-color)'                       # Background

  # UI
  paper-card-header-color: 'var(--text-color)'                                    # Title in settings
  primary-background-color: 'var(--background-color)'                             # Background (also title background in left menu)

  # Card
  paper-card-background-color: 'var(--background-card-color)'                     # Background
  dark-primary-color: 'var(--text-color)'
  primary-text-color: 'var(--text-color)'
  paper-listbox-color: 'var(--text-color)'
  light-primary-color: 'var(--text-light-color)'
  secondary-text-color: 'var(--text-medium-color)'
  disabled-text-color: 'var(--text-light-color)'
  paper-dialog-button-color: 'var(--text-color)'
  secondary-background-color: 'var(--background-color-2)'                         # Background more info title

  # Icons
  paper-item-icon-color: 'var(--text-light-color)'                                # Off
  paper-item-icon-active-color: 'var(--accent-color)'                             # On

  # Switches
  paper-toggle-button-checked-button-color: '#FFF'                                # Knob On
  paper-toggle-button-checked-bar-color: '#0077FF'                                # Background On
  paper-toggle-button-unchecked-button-color: '#FFF'                              # Knob Off
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'           # Background Off

  # Shadows
  shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 1px var(--border-color)'
  shadow-elevation-4dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-6dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-8dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-10dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-12dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-14dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-16dp_-_box-shadow: '0px 0px 0px 3px var(--light-color)'

  # Others
  ha-card-box-shadow: '0 1px 1px 0 rgba(0,0,0,.1)'
  dark-secondary-opacity: '.7'
```

Lovelace View Theme:-
```yaml
lovelace-blue-blur:
  theme-color: '#62c6e042'
  primary-color: '#0000005c'
  accent-color: '#68ebf3'

  # BACKGROUND & HEADER

  lovelace-background: top right no-repeat url(/local/images/background-blue-blur.jpg) fixed
  lovelace-cc-header-background: 'linear-gradient(45deg, #62c6e042, #ffffff00)'
  lovelace-cc-elements: '#84a3ca'
  lovelace-cc-tab-indicator: '#68cccc'
  lovelace-cc-active-tab: var(--lovelace-cc-tab-indicator)

  secondary-background-color: 'transparent'
  primary-background-color: '#1f6275'

  # TEXT
  primary-text-color: '#FFFFFF'
  secondary-text-color: '#acd1eccf'
  ha-card-header-color: '#b9ecec'

  # CARD
  paper-card-background-color: '#75889042'
  paper-card-active-background-color: '#3baad696'
  paper-card-header-color: '#97d3ff'
  card-background-color: '#ffffff29'

  # HONEYCOMB
  honeycomb-menu-icon-color: '#29343c'
  honeycomb-menu-icon-active-color: '#3e6e8c'
  honeycomb-menu-background-color: 'linear-gradient(45deg, #98a6c5, #67899e9c)'
  honeycomb-menu-active-background-color: 'linear-gradient(45deg, #8eafd2, #d0e9fd)'
  honeycomb-name-background: rgba(52, 98, 132, 0.58)

  # BUTTONS & TOGGLES
  paper-toggle-button-checked-bar-color: '#739bc3'
  paper-toggle-button-checked-button-color: '#000'
  paper-toggle-button-unchecked-button-color: '#000'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'

  switch-checked-color: '#1b485f'
  switch-checked-button-color: 'var(--switch-checked-color)'
  switch-checked-track-color: 'var(--switch-checked-color)'

  paper-slider-active-color: '#d092c8'
  paper-slider-knob-color: '#d092c8'

  # ICONS
  state-icon-color: '#d7dada'
  state-icon-active-color: '#6ddada'
  paper-item-icon-active-color: 'var(--state-icon-active-color)'
  tiles-card-padding: 0

  # CUSTOM
  grid-card-gap: 2px
```
![view config - Screenshot 2022-02-04 041242](https://user-images.githubusercontent.com/11685433/152399251-d4bff8e7-51f0-4150-9d2e-a516aab43bfe.png)


**The Results**

The html tag is assigned the correct core theme:-
![html - Screenshot 2022-02-04 040446](https://user-images.githubusercontent.com/11685433/152399498-5880bf05-9750-4f3f-a5cb-e84cdffc7fec.png)

Then the lovelace view container is set to the correct view theme (hui-view):-
![Screenshot 2022-02-04 040337](https://user-images.githubusercontent.com/11685433/152399682-7b067a1c-0f88-4e74-85a2-ae20160db321.png)

The problem comes when the following cards start injecting the core themes styles all over again:-
![elements 1 - Screenshot 2022-02-04 040609](https://user-images.githubusercontent.com/11685433/152399933-0a8234d7-a07a-4916-a487-51f850361920.png)
![Elements - Screenshot 2022-02-04 041010](https://user-images.githubusercontent.com/11685433/152399964-cdb6b9ad-9a6a-49f1-b19b-a2e8b4d56846.png)


As you can see in their tags and the styles assigned, it seems to put the base theme into them which was not present prior to the 2021.12 release. I have not used the theme property in anything else other than in the view settings
