### ISSUE TITLE
history-graph : no display of native measurement unit (pb found on statistic integration)

### ISSUE THREAD

**Issue by jugla** [home-assistant/frontend#10968]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When implementating statistic with Watt, the history graph does not display unit.
Furthermore, it considers that the unit is valid but blank.

Nb1 : in entity units is displayed
Nb2 : the statistic on temperature works.

Here after the displayed graphic 
![image](https://user-images.githubusercontent.com/59493499/146656843-ca569bc1-25cd-4743-b9bf-b8e439660de2.png)

And the entity
![image](https://user-images.githubusercontent.com/59493499/146656856-89514823-e0a1-4003-8abc-753f6b4acf51.png)

### Describe the behavior you expected

Take the right native measurement

### Steps to reproduce the issue

1. use atome (to get state in Watt)
2. declare statistics
```yaml
  - platform: statistics
    entity_id: sensor.atome_live_power
    name : stat_atome_live_power_min
    state_characteristic: value_min
    max_age:
       minutes: 20
    sampling_size : 20

  - platform: statistics
    entity_id: sensor.atome_live_power
    name : stat_atome_live_power_max
    state_characteristic: value_max
    max_age:
       minutes: 20
    sampling_size : 20


  - platform: statistics
    entity_id: sensor.atome_live_power
    name : stat_long_atome_live_power_max
    state_characteristic: value_max
    max_age:
       hours: 24
    sampling_size : 3000

  - platform: statistics
    entity_id: sensor.atome_live_power
    name : stat_long_atome_live_power_min
    state_characteristic: value_min
    max_age:
       hours: 24
    sampling_size : 3000

```
3. create history graphic
...

### What version of Home Assistant Core has the issue?

2021.12.2

### In which browser are you experiencing the issue with?

Chrome Version 96.0.4664.110 (Build officiel) (64 bits)

### Which operating system are you using to run this browser?

OS windows 10

### State of relevant entities

```txt
state_class: measurement
age_coverage_ratio: 1
buffer_usage_ratio: 0.47
source_value_valid: true
unit_of_measurement: W
icon: mdi:calculator
friendly_name: stat_long_atome_live_power_max
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.atome_live_power
  - entity: sensor.stat_long_atome_live_power_min
  - entity: sensor.stat_long_atome_live_power_max
title: Puisssance Instantannée et max fenetre glissante 24h
hours_to_show: 24
refresh_interval: 0
```

### Additional information

Woirk around. Declare a sensor template where you force the unit_measurement
```yaml
  - sensor:
      - name : stat_long_atome_live_power_max_unit
        unit_of_measurement: 'W'
        state: "{{ states('sensor.stat_long_atome_live_power_max') | float * 1.0 }}"

```
