### ISSUE TITLE
device_class timestamp shows incorrect day countdown

### ISSUE THREAD

**Issue by ZackaryH8** [home-assistant/frontend#10996]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using a timestamp in a template with `device_class: timestamp`, the incorrect thing is displayed. If the timestamp is set to `2021-12-23T06:00:00` and the current day is the 21st December 2021 the template will return `Tomorrow` instead of the expected `In 2 days`

### Describe the behavior you expected

`In 2 days` instead of `Tomorrow`

### Steps to reproduce the issue

Sensor: 
```yaml

# Get the data - {"next_date": "2021-12-23T06:00:00", "next_type": "Garden"}
- platform: command_line
  name: BinCollection
  json_attributes:
      - next_date
      - next_type
  command: 'py C:/Users/Zack/Documents/HA/scripts/bins.py'
  scan_interval: 43200

- platform: template
  sensors:
      next_bin_date:
          friendly_name: Next Bin Collection Date
          value_template: '{{ (states("sensor.BinCollection")|from_json())["next_date"] }}'
          device_class: timestamp
```

### What version of Home Assistant Core has the issue?

core-2021.12.4

### In which browser are you experiencing the issue with?

Version 96.0.4664.110

### Which operating system are you using to run this browser?

Windows 11 22000.376

### State of relevant entities

```txt
BinCollection
state - `{"next_date": "2021-12-23T06:00:00", "next_type": "Garden"}`

next_date: '2021-12-23T06:00:00'
next_type: Garden
friendly_name: BinCollection

next_bin_date
state - `2021-12-23 06:00:00+00:00`

friendly_name: Next Bin Collection Date
device_class: timestamp
```
