### ISSUE TITLE
Can't fix broken automation via UI

### ISSUE THREAD

**Issue by atmurray** [home-assistant/frontend#11010]
### The problem

When a device_id referenced by an automation is not longer valid, this generates an error but it is not possible to use the automation UI to edit the automation and fix the issue.
In my case I think the latest update to the Philips Hue integration caused a device id to change.
In the Automation configuration screen the automations are disabled and greyed out such that they are not editable.
This forces a user to either delete and re-create the automation or to have to manually fix the error in YAML.

### What version of Home Assistant Core has the issue?

2021.12.3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Link to integration documentation on our website

https://www.home-assistant.io/docs/automation/

### Example YAML snippet

```yaml
- id: '1588513412951'
  alias: Tap 1 - Leave home
  description: Leave home
  trigger:
  - device_id: 09b2d95dde7345edb047f77c3f85f43a
    domain: hue
    platform: device
    subtype: button_1
    type: remote_button_short_press
  condition: []
  action:
  - type: turn_off
    device_id: 4b811bccf0f44d308b744d6d5ba490d0
    entity_id: remote.harmony_hub
    domain: remote
  mode: single
```

### Anything in the logs that might be useful for us?

```txt
Invalid config for [automation]: Device ID 09b2d95dde7345edb047f77c3f85f43a is not valid. Got OrderedDict([('default_config', {}), ('debugpy', OrderedDict([('start', False)])), ('logger', OrderedDict([('default', 'warning'), ('logs', OrderedDict([('custom_components.bluetooth_tracker.device_tracker', 'fatal'), ('homeassistant.components.websocket_api.http.connection', 'fatal')]))])), ('system_health', {}), ('group', {}), ('automation', [OrderedDict([('id', '1588513412951'), ('alias', 'Tap 1 - Leave home'), ('description', 'Leave home'), ('trigger', [OrderedDict([('device_id', '09b2d95.... (See /config/configuration.yaml, line 38).
5:18:13 PM – (ERROR) config.py - message first occurred at 2:07:12 PM and shows up 72 times
```

### Additional information

I'm not sure if this is unique to only when a device id used as a trigger is invalid or more generally when an automation contains an error.
Perhaps this requires a more general fix to ensure that when an automation is invalid it is still possible to edit it via the UI.
