### ISSUE TITLE
`sensor` and `binary_sensor` entities do not align in `history-graph`

### ISSUE THREAD

**Issue by zocker-160** [home-assistant/frontend#11011]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The time on the x-axis is not aligned.
![grafik](https://user-images.githubusercontent.com/36563538/147240640-e66eb627-c077-4f2e-a2cd-484eb25384b4.png)

![grafik](https://user-images.githubusercontent.com/36563538/147240647-a0afa0ff-b9e4-423b-af7a-0f435a93f884.png)

### Describe the behavior you expected

The x-axis should be aligned, at least when inside the same `history-graph` card

### Steps to reproduce the issue

1. go to overview
2. add new view
3. set type to `Panel (1 view)`
4. add vertical stack card
5. add history graph to vertical stack card
6. add at least one `sensor` and one `binary_sensor` to history view (see yml config below)

### What version of Home Assistant Core has the issue?

core-2021.12.4

### What was the last working version of Home Assistant Core?

none that I am aware of

### In which browser are you experiencing the issue with?

Firefox 95.0.1 && Chromium 95

### Which operating system are you using to run this browser?

Ubuntu 20.04

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.boost_value
  - entity: sensor.batt_state
  - entity: sensor.batt_target
  - entity: binary_sensor.batt_phase
  - entity: binary_sensor.mode_ladung
hours_to_show: 24
refresh_interval: 0
```
