### ISSUE TITLE
The gauge card doesn't render correctly on iOS 15.2 / macOS 12.1 in the companion apps

### ISSUE THREAD

**Issue by raducotescu** [home-assistant/frontend#11041]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is the same issue as #10766 for which a partial fix was submitted via #10992. A potential fix was suggested in [this comment](https://github.com/home-assistant/frontend/pull/10992#issuecomment-1002134042).

### Describe the behavior you expected

The gauge card should correctly render also in the Home Assistant companion apps on both iOS/macOS.

### Steps to reproduce the issue

Have a gauge card configured like:
```
- type: gauge
   entity: sensor.temperature
   min: 0
   max: 100
   severity:
     green: 20
     yellow: 22
     red: 25
   name: ' '
```

### What version of Home Assistant Core has the issue?

core-2021.12.6 (and earlier)

### In which browser are you experiencing the issue with?

Safari 15.2 +

### Which operating system are you using to run this browser?

macOS 12.1, iOS 15.2
