### ISSUE TITLE
Poor choice of Y axis for climate history chart; can't see the heating shaded area

### ISSUE THREAD

**Issue by karwosts** [home-assistant/frontend#11050]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a generic thermostat, for which I plot the climate entity in a lovelace history chart. 

The Y axis min-max for this chart tracks strictly to the min and max value of my current temperature, so if the heating turns on when the current temperature is at the min value, the shaded area under the current temperature to signify heating is invisible because the current temperature is exactly 0 pixels from the bottom of the graph, so the shaded area signifying the heating is on is 0 pixels tall and invisible. 

![image](https://user-images.githubusercontent.com/32912880/147779360-68d0ef9d-f9a7-440a-98f9-09eb67999613.png)

### Describe the behavior you expected

Graph Y axis should be padded under the minimum value so that the shaded area representing heating is guaranteed to be visible. 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.7

### In which browser are you experiencing the issue with?

Firefox 95.0.1 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
My climate entity being graphed:

climate:
  - platform: generic_thermostat
    name: Gym Thermostat
    heater: switch.gym_heat
    target_sensor: sensor.gym_temperature
    min_temp: 40
    max_temp: 80
    ac_mode: false
    target_temp: 50
    cold_tolerance: 1
    hot_tolerance: 1
    min_cycle_duration:
      seconds: 60
    initial_hvac_mode: "off"
    away_temp: 40
    precision: 1
```
