### ISSUE TITLE
Scene editor writes invalid settings for Roku Streaming Stick

### ISSUE THREAD

**Issue by josh-m-sharpe** [home-assistant/frontend#11071]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Goal:
As part of a scene automation, I want to turn off my Roku Streaming stick.

The Scene UI does not allow me to save a valid config that turns off the Roku streaming stick.  But I can manually edit the yaml.  Subsequent uses of the UI override my manual edit.  So, the UI is broken in this regard.

### Describe the behavior you expected

The Scene UI should be able to add a Roku Streaming stick and set `state: 'off'` but it cannot.

### Steps to reproduce the issue

1) Edit my Scene
Add Roku Streaming Stick:
![Configuration_-_Home_Assistant](https://user-images.githubusercontent.com/39473/147865930-1ab11467-8034-48ac-baa2-cf408ca31acb.jpg)

2) It is added toggled On:
![Configuration_-_Home_Assistant](https://user-images.githubusercontent.com/39473/147865944-862255bc-6a56-4bc5-a3b7-ff6af6521725.jpg)

3) I toggle it off (The roku itself turns off)
![Configuration_-_Home_Assistant](https://user-images.githubusercontent.com/39473/147865960-d114bcc4-b9af-48d1-beb0-29de693e675e.jpg)

4) I then click the 'Back' Arrow (in the UI, not the browse back)
The roku turns back on (as does everything else in the scene that was off - this is expected)

5) I click the "Play" button
The roku does **not** turn off.  It's expected that it would.

6) I then check the raw yaml:

```
    media_player.roku_living_room:
      source_list:
      - Home
      - ABC
      - AMC
      - Apple TV
      - CBS
      - CBS News
      - CBS Sports Stream & Watch Live
      - Comedy Central
      - Disney Plus
      - ESPN
      - FOX NOW
      - FOX Sports
      - Food Network GO
      - HBO Max
      - HGTV GO
      - Hulu
      - MASN Everywhere
      - NBC
      - NBC News
      - National parks
      - Netflix
      - PBS
      - Pandora
      - Paramount Network
      - Paramount Plus
      - Peacock TV
      - PhotoView for Google Photos
      - Plex - Free Movies & TV
      - Prime Video
      - Screensavers 247 - Nature HD
      - VICE
      - VUDU
      - Vudu Movie & TV Store
      - YouTube
      - YouTube TV
      app_name: Roku
      source: Roku
      device_class: receiver
      friendly_name: Roku Streaming Stick+
      supported_features: 151481
      state: home
```

Lots of stuff here, but notably `state: home` is incorrect.

If I manually change this to 
`state: 'off'`
then the scene works as expected.  However, any subsequent changes to the scene in the UI will override my manual `state: 'off'` with something else - which breaks things.

No amount of noodling in the UI produces a yaml that matches `state: 'off'`

### What version of Home Assistant Core has the issue?

2021.12.7

### What was the last working version of Home Assistant Core?

this hadn't worked all year. I recently updated from some 2021.4 or 2021.6 - not sure.

### In which browser are you experiencing the issue with?

brave/chrome/safari

### Which operating system are you using to run this browser?

OSX 11.6.1
