### ISSUE TITLE
frontend.set_theme changes every card except entitylist

### ISSUE THREAD

**Issue by BCsabaEngine** [home-assistant/frontend#11086]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I use frontend.set_theme at sunset/sunrise to change to light and dark mode. M yphone and tablet on wall changes the skin automatically without interaction.
Two weeks ago the behavior changed: all cards work but entitylist (the most common card type) stay in old mode. When use browser refresh (F5, CTRL+R or navigation) the entitylist goes to perfect skin. But not automatically. All other cards works.

### Describe the behavior you expected

EntityList card (entities) should be skinned automatically when run frontend.set_theme without click.

### Steps to reproduce the issue

1. Setup two skin (light and dark mode)
2. Setup yout user to use system skin mode 
3. Add an empty entitities card and any other card to lovelace.
4. run frontend.set_theme to change between skins form another machine to see changes without click

### What version of Home Assistant Core has the issue?

core-2021.12.7

### In which browser are you experiencing the issue with?

Chrome 96.0.4664.110 

### Which operating system are you using to run this browser?

Linux Elementary 6.1

### Problem-relevant frontend configuration

```yaml
title: Iroda
views:
  - path: default_view
    title: Home
    cards:
      - type: entities
        entities:
          - entity: script.sound_on_off
          - entity: switch.allolampa
            icon: mdi:floor-lamp
          - entity: script.kilepo_feny
          - entity: sensor.0x00124b002228e690_temperature
            name: Hőmérséklet
          - entity: sensor.0x00124b002228e690_humidity
            name: Páratartalom
          - entity: script.futes_45_min
            name: Kazán 15 perc
          - entity: switch.heating
            icon: mdi:radiator
            secondary_info: last-changed
            name: Kazán
          - entity: climate.office
            icon: mdi:radiator
            secondary_info: last-changed
            name: Fűtés
        state_color: false
        title: Iroda
        show_header_toggle: false
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.office
            name: ' '
          - type: entities
            entities:
              - entity: sensor.heat_time_last_7_days
              - entity: sensor.heat_ratio_last_7_days
              - entity: sensor.heat_count_last_7_days
      - type: entities
        entities:
          - entity: binary_sensor.updater
          - entity: sensor.backup_state
            icon: mdi:cloud-upload
            secondary_info: last-changed
          - entity: binary_sensor.backups_stale
          - entity: device_tracker.csaba_huawei
          - entity: device_tracker.csaba_vostro
          - entity: sensor.home_assistant_v2_db
            name: Database size
          - entity: sensor.db_size_per_hour
          - entity: binary_sensor.workday_sensor
            icon: mdi:calendar
          - entity: binary_sensor.0x00158d00049fc3ed_occupancy
            name: Mozgás
            secondary_info: last-changed
        title: Bináris érzékelő
      - type: media-control
        entity: media_player.spotify_balazs_csaba
```

### Javascript errors shown in your browser console/inspector

```txt
No error and other info.
```

### Additional information

![Képernyőkép erről: 2022-01-04 09-40-59](https://user-images.githubusercontent.com/20396372/148032160-f5dc62c0-2d7a-45ce-a6c3-89e894fe7580.png)
![Képernyőkép erről: 2022-01-04 09-41-27](https://user-images.githubusercontent.com/20396372/148032170-1d0b434c-547d-409a-806e-c52d33ed79d6.png)

I have tried it in different browser and mobile apps.
