### ISSUE TITLE
Automation > Trigger > Delete

### ISSUE THREAD

**Issue by pticon91** [home-assistant/frontend#11090]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While having multiple triggers set and want to remove one, always the last trigger is being removed, not the actual one where Delete was fired.

### Describe the behavior you expected

When I click on delete I expect to remove the current trigger

### Steps to reproduce the issue

1. Create Automation
2. Add 2 triggers
3. On 1st trigger choose Delete
4. Last trigger will be deleted instead of 1st one

### What version of Home Assistant Core has the issue?

core-2021.12.7

### In which browser are you experiencing the issue with?

Chrome 96.0.4664.110 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Win 10

**Comment by spacegaier** [comment]
I cannot reproduce the issue. In my tests in the dev version, the correct trigger gets deleted.

Can you please share your concrete automation YAML just in case there is something weird and special going on with your example.

**Comment by pticon91** [comment]
@spacegaier Am sorry, am already running v2021.12.9 and I can confirm I can't reproduce the issue anymore

**Comment by pticon91** [comment]
@spacegaier I was able to replicate this issue again in v2021.12.9. I would slightly change the replication steps in point 2 = **add 2 triggers and turn them in to YAML mode**

The automation below is working properly so I assume formatting is correct. When the triggers are in UI mode, I can remove the trigger I want. If 1st or both triggers are in YAML mode the remove action removes always the last trigger.

```
alias: UTR | Central Heating
description: ''
trigger:
  - platform: template
    value_template: >-
      {{ (as_timestamp(now()) / 60 - as_timestamp(this.last_changed) / 60) |
      round == 1 }}
    id: default
  - platform: state
    entity_id: input_text.glb_last_heat_demand
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: default
        sequence:
          - service: input_text.set_value
            target:
              entity_id: input_text.glb_last_heat_demand
            data:
              value: ''
          - service: switch.turn_off
            target:
              entity_id: switch.utr_central_heating_switch
    default:
      - service: >-
          {{ 'switch.turn_off' if states('input_text.glb_last_heat_demand') ==
          '' else 'switch.turn_on' }}
        target:
          entity_id: switch.utr_central_heating_switch
mode: single
```
