### ISSUE TITLE
When multiple tabs are open, some go out of sync

### ISSUE THREAD

**Issue by mortenmoulder** [home-assistant/frontend#11111]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I have Home Assistant open in multiple tabs, sometimes (sometimes 5 minutes, sometimes an hour, sometimes more), some of the tabs go "out of sync". When they go out of sync, I can turn on the lights, but the card doesn't show it's on. On the "stale" tabs, some of my entities stop updating.

I'm using two custom cards, that are both doing this, but I don't expect those are the issue (would be weird if both had a bug): `custom:mini-graph-card` and `custom:slider-button-card`.

Here are some videos showing they're stale: [Video 1](https://i.imgur.com/Yh6AnkA.mp4) and [video 2](https://i.imgur.com/DlMghsJ.mp4). I solve the issue by refreshing the tab in the last video.

### Describe the behavior you expected

I expect all tabs to show the exact same all the time no matter what. I understand that sometimes things get out of sync, but they should sync back up again after a few seconds. These tabs never sync up again, until I refresh the page (which is annoying for a wall mounted tablet).

### Steps to reproduce the issue

I believe the issue is the socket connection, but the yaml is posted under the config part.

### What version of Home Assistant Core has the issue?

core-2021.12.6

### In which browser are you experiencing the issue with?

Latest Chrome and latest Edge

### Which operating system are you using to run this browser?

Windows 10 and Windows 11

### Problem-relevant frontend configuration

```yaml
- type: custom:slider-button-card
  entity: light.filament
  compact: true
  name: Filament
  style: |
    :host {
      --label-color-on: black !important;
      --state-color-on: black !important;
      --state-color-off: transparent !important;
    }
  slider:
    direction: left-right
    background: solid
  action_button:
    mode: custom
    show: true
    tap_action:
      action: toggle
- type: custom:mini-graph-card
  name: Forbrug 1 time
  entities:
    - sensor.kamstrup_power
  line_color: lightblue
  hours_to_show: 1
  points_per_hour: 60
  update_interval: 60
  aggregate_func: max
  show:
    icon: false
    graph: bar
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_
