### ISSUE TITLE
Hue icons not shown on first service: cast.show_lovelace_view

### ISSUE THREAD

**Issue by pascalwinters** [home-assistant/frontend#11122]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I cast a lovelace dashboard with the first service call `cast.show_lovelace_view` the hue icons missing from the dashboard.
I'm using the: https://github.com/arallsopp/hass-hue-icons

### Describe the behavior you expected

The hue icons are shown the same as the default mdi icons

### Experienced issue:
1.
```
service: cast.show_lovelace_view
data:
  entity_id: media_player.nest_keuken
  view_path: hue-test
  dashboard_path: lovelace-cast
```
With dashboard (light.keuken_dimmer has icon: hue:centura):
```
- title: hue-test
    path: hue-test
    badges: []
    cards:
      - type: button
        name: Aan
        show_name: true
        entity: light.keuken_dimmer
```
2. The button is shown without icon

### Working scenario:
1.
```
service: cast.show_lovelace_view
data:
  entity_id: media_player.nest_keuken
  view_path: <a_path_without_hue_icons>
  dashboard_path: lovelace-cast
```
2.
```
service: cast.show_lovelace_view
data:
  entity_id: media_player.nest_keuken
  view_path: hue-test
  dashboard_path: lovelace-cast
```
With dashboard (light.keuken_dimmer has icon: hue:centura):
```
- title: hue-test
    path: hue-test
    badges: []
    cards:
      - type: button
        name: Aan
        show_name: true
        entity: light.keuken_dimmer
```
3. The button is shown with the hue icon

### What version of Home Assistant Core has the issue?

core-2021.12.8

### In which browser are you experiencing the issue with?

Nest Hub v2
