### ISSUE TITLE
Blueprint default values not saved to automation when using slider.

### ISSUE THREAD

**Issue by m0wlheld** [home-assistant/frontend#11127]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The situation is similar the the closed issue #8011: (Numeric) default values defined in a blueprint do not make it into automation configuration when using a slider, unless changed in UI. 

Example blueprint and automation outcome attached. 

### Describe the behavior you expected

Default values for inputs defined in a blueprint should be saved in the automation, even if unchanged by UI. 

### Steps to reproduce the issue

1. Write a blueprint that supports a (numeric) input using a default value and value-change by slider
2. Create a new automation from that blueprint, do not adjust the value using the slider
3. Save the automation
4. Check the automation YaML to see, that input A was not stored as a parameter in the automation (see below)

Sample blueprint:
```
blueprint:
  name: Test blueprint
  domain: automation
  input:
# another input is required to make the "Save" button appear on create automation UI    
    sample_entity:
      name: Sample entity
      selector:
        entity:
          domain: binary_sensor
          device_class: window  
# the input below will not make it into the automation, unless you modify it in the UI          
    sample_value:
      name: Sample value
      default: 20
      selector:
        number:
          min: 10
          max: 50
          step: 10
          mode: slider

trigger: []
action: []

mode: queued
max: 10
```

Created automation:
```
alias: Neue Automatisierung
description: ''
use_blueprint:
  path: m0wlheld/test-blueprint.yaml
  input:
    sample_entity: binary_sensor.neq1650855_state
```

Input `sample_value: 20` is missing. It does however work, when you remove the selector.

### What version of Home Assistant Core has the issue?

core-2021.12.8

### In which browser are you experiencing the issue with?

Firefox 95.0.2 (64-Bit)

### Which operating system are you using to run this browser?

Windows 11 

### Javascript errors shown in your browser console/inspector

```txt
none related
```
