### ISSUE TITLE
Timestamp sensor shows "last year" while only 10 days ago

### ISSUE THREAD

**Issue by mvdwetering** [home-assistant/frontend#11130]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Timestamp sensors like "last boot" from the systemmonitor integration or "Up time" from Brother Printer integration now show the text "last year" which is not very helpful.
The timestamp has only been like 10 days ago (2021-12-29T15:45:18+00:00)

### Describe the behavior you expected

Display a text representing a shorter duration. 
It showed texts like "last week" before.

### Steps to reproduce the issue

1. Get a timestamp sensor entity with timestamp in last year
2. Look at entity in an entities card or in the device screen and see "last year"

### What version of Home Assistant Core has the issue?

core-2021.12.8

### In which browser are you experiencing the issue with?

Version 96.0.4664.110 (Official Build) (64-bit) and 95.0.2 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
entity:
sensor.last_boot
Last boot

state:
2021-12-29T15:45:18+00:00	

attributes:
device_class: timestamp
friendly_name: Last boot

and

entity:
sensor.hl_3140cw_uptime
HL-3140CW Uptime

state:
2021-12-05T14:46:53+00:00

attributes:
device_class: timestamp
friendly_name: HL-3140CW Uptime
```

### Problem-relevant frontend configuration

```yaml
entities:
  - entity: sensor.processor_use
  - entity: sensor.load_1m
  - entity: sensor.load_5m
  - entity: sensor.load_15m
  - entity: sensor.network_throughput_out_eth0
  - entity: sensor.network_throughput_in_eth0
  - entity: sensor.disk_free
  - entity: sensor.last_boot
show_header_toggle: false
title: Home Assistant status
type: entities
```

### Javascript errors shown in your browser console/inspector

```txt
no errors in console
```

### Additional information

![image](https://user-images.githubusercontent.com/732514/148683291-45d654d8-ffa6-4b3e-aebf-71bf50bd7eb1.png)

Since it just started happening recently I guess it is due to the timestamp being in the previous year.
