### ISSUE TITLE
Need to active scene first via more-info, before being able to active in card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11143]
### The problem

before updating to 20220108, we could directly click ACTIVATE button, new behavior is we need to click the scene for more-info and there we see the exact same scene with an actionable ACTIVATE

getting back to the frontend shows the scene now with an other color, and we can click it directly.

this seems regression, for extra clicks and forcing to use more-info is not very user friendly

### What version of Home Assistant Core has the issue?

2022.2.0.dev20220108

### What was the last working version of Home Assistant Core?

2022.2.0.dev20220107

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

scene Hue

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/hue/

### Example YAML snippet

```yaml
- type: entities
    entities:
      - scene.master_bedroom_arctische_dageraad
      - scene.master_bedroom_chinatown
      - scene.master_bedroom_concentreren
      - scene.master_bedroom_energie
      - scene.master_bedroom_feestelijk_plezier
      - scene.master_bedroom_gedimd
      - scene.master_bedroom_helder
etcetc
```

### Anything in the logs that might be useful for us?

```txt
nope
```

### Additional information

top scene not selectable and not yet activated color grey
<img width="479" alt="Schermafbeelding 2022-01-09 om 01 35 29" src="https://user-images.githubusercontent.com/33354141/148664626-0609585b-b436-4e74-833d-721f041a9494.png">

click it for more info, note it being colored blue

<img width="394" alt="Schermafbeelding 2022-01-09 om 01 35 41" src="https://user-images.githubusercontent.com/33354141/148664630-29386202-bdc3-44b2-a973-8da13e83f879.png">

after clicking there frontend:

<img width="492" alt="Schermafbeelding 2022-01-09 om 01 35 53" src="https://user-images.githubusercontent.com/33354141/148664659-b09cc720-7c53-4d6d-8157-f431407721e2.png">

not sure if this is related, but dev states shows HA sees a dynamic scene, which eg the arctische dageraad isnt at all:

<img width="427" alt="Schermafbeelding 2022-01-09 om 01 43 23" src="https://user-images.githubusercontent.com/33354141/148664759-94a6eaf4-9cb8-474a-9249-d1bdd7c03da3.png">

no matter how many times we activate/swithc to another scene/turn off: these details dont change at all

<img width="630" alt="Schermafbeelding 2022-01-09 om 01 47 44" src="https://user-images.githubusercontent.com/33354141/148664833-19319102-207a-47ad-9167-79d84999f373.png">

while using
```
      - entity: scene.master_bedroom_arctische_dageraad
        secondary_info: last-changed
```
does change when clicking activate correctly

Related to https://github.com/home-assistant/core/pull/62673 ?
