### ISSUE TITLE
hold action animation messes with view width

### ISSUE THREAD

**Issue by matt8707** [home-assistant/frontend#11320]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On iOS when performing a hold_action near the scrollbar the animation messes with view width

https://user-images.githubusercontent.com/36163594/149363413-1e27e0db-9da5-4ce0-b462-fca893533b1b.mp4

### Describe the behavior you expected

I'm assuming the hold_action effect is [mwc-ripple unbounded](https://www.npmjs.com/package/@material/mwc-ripple).  The animation should go outside the view and not mess with page width.

### Steps to reproduce the issue

1. add grid
2. add buttons
3. press and hold on far right button

### What version of Home Assistant Core has the issue?

core-2021.12.9

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

iOS 15.2.1

### Problem-relevant frontend configuration

```yaml
- type: grid
  square: true
  cards:
    - type: button
      entity: light.test
    - type: button
      entity: light.test
    - type: button
      entity: person.test
      hold_action:
        action: more-info
```

### Additional information

test container - no custom cards
