### ISSUE TITLE
Automation - Device Trigger sub selection for Value is not recalled on page load

### ISSUE THREAD

**Issue by Brice-Itec** [home-assistant/frontend#11339]
### The problem

When using a device that allows a Value as a sub-selection to a trigger, the Value field remains empty when the automation is edited in the browser.  This was found using a Zooz Scene Controller.

The graphical interface also clashes with the selected value after the field loses focus:
![image](https://user-images.githubusercontent.com/88401500/147421916-9c46781b-fc39-421d-b51a-571e4c2dee26.png)

Any time the automation is edited, this field must be set again before saving the changes.

### What version of Home Assistant Core has the issue?

core-2021.12.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Z-wave JS

### Example YAML snippet

```yaml
alias: Kitchen - Scene Button 1 - Toggle On
description: ''
trigger:
  - platform: device
    device_id: 56476fd9852bdb47b5afc23f7defff73
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: '001'
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 0
condition:
  - condition: state
    entity_id: input_boolean.kitchen_cabinet_scene_active
    state: 'off'
action:
  - scene: scene.kitchen_cabinets_warm_white
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kitchen_cabinet_scene_active
mode: single
```

### Additional information

This is more of a nuisance with the HA UI when editing the automation.  Actually functionality of the automation does work correctly.
