### ISSUE TITLE
Y-Axis unit is not shown in history for statistics sensors

### ISSUE THREAD

**Issue by DeniTCH** [home-assistant/frontend#11341]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have created a statistics sensor for some of my more noisy sensors. The sensors seem to be working fine but the statistics sensor unit is not shown in the history y-axis:

![missing_history_value](https://user-images.githubusercontent.com/9782597/149679487-6eb08ae8-104f-46db-bf71-a83491481dbc.png)

Even though the unit is set and displayed correctly in the original 'raw' sensor plots:

![co2_sensor](https://user-images.githubusercontent.com/9782597/149679540-e67eb960-df5e-434a-81ae-d9446d7dc5d1.png)

I can verify on the Developer Tools > Statistics page that the units seem to be there:

![average_sensors](https://user-images.githubusercontent.com/9782597/149679612-c48ec9be-08f2-42ec-b63e-6a35b17c8c87.png)

I can also verify this in the database:

```
sqlite> select * from statistics_meta;
...
40|sensor.co2_average|recorder|ppm|1|0|
41|sensor.pm2_5_average|recorder|ug/m3|1|0|
```

### Describe the behavior you expected

The units for the statistics sensor should be the same as for the original sensor and be shown correctly in the history.

### Steps to reproduce the issue

1. Create a statistics sensor in the configuration.yaml.
2. Observe the missing value in the history.

### What version of Home Assistant Core has the issue?

core-2021.12.9

### In which browser are you experiencing the issue with?

Brave v.1.33.106 (Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit))

### Which operating system are you using to run this browser?

Ubuntu 20.04.3 LTS

### State of relevant entities

```txt
state_class: measurement
age_coverage_ratio: 0.95
buffer_usage_ratio: 0.74
source_value_valid: true
unit_of_measurement: ppm
icon: mdi:calculator
friendly_name: CO2 Average

state_class: measurement
age_coverage_ratio: 0.98
buffer_usage_ratio: 0.78
source_value_valid: true
unit_of_measurement: ug/m3
icon: mdi:calculator
friendly_name: PM2.5 Average
```

### Problem-relevant frontend configuration

```yaml
- platform: statistics
  name: "CO2 Average"
  entity_id: sensor.co2
  state_characteristic: mean
  max_age:
    minutes: 5
  sampling_size: 50
  precision: 1

- platform: statistics
  name: "PM2.5 Average"
  entity_id: sensor.pm2_5
  state_characteristic: mean
  max_age:
    minutes: 5
  sampling_size: 50
  precision: 1
```
