### ISSUE TITLE
Scenes: Unknwown/unavailable states should not be recorded in scenes created from UI

### ISSUE THREAD

**Issue by koying** [home-assistant/frontend#11354]
### The problem

Whencreating a scene per device via the UI, all entities are recorded in the scene, including ones with unknown/unavailable state.
Those cannot be applied ofc.

Generally speaking, it makes no sense to record anything that cannot be applied, like read-only attributes (`options` in the example below).
~~I don't know about, e.g., `friendly_name`, `icon`. Are the values saved in a scene actually override the attributes when the scene is applied? If so, might definitely be undesirable, and if not, they are superfluous in the scene as well.~~
EDIT: They are not applied, so superfluous as well.

### What version of Home Assistant Core has the issue?

2021.12.7

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

scene

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/scene/

### Example YAML snippet

```yaml
Snippet of a scene created for WLED via UI


    select.wled_preset:
      options:
      - Default
      - Segmented
      icon: mdi:playlist-play
      friendly_name: WLED TV Preset
      state: unknown
```

### Anything in the logs that might be useful for us?

```
2022-01-06 15:56:19 WARNING (MainThread) [homeassistant.components.select.reproduce_state] Invalid state specified for select.wled_preset: unknown
```
