### ISSUE TITLE
Service UI not sending default value

### ISSUE THREAD

**Issue by bachya** [home-assistant/frontend#11368]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While creating https://github.com/home-assistant/core/pull/64219, it was noted that even though my `services.yaml` includes a default for the `duration` field, that value is not explicitly sent to the service call; instead, the value has to be explicitly entered.

### Describe the behavior you expected

Service field defaults should get sent by the UI to the service call.

### Steps to reproduce the issue

1. Create a service that has a required field with a default
2. Call the service via the UI without altering the field from step 1
3. See error

### What version of Home Assistant Core has the issue?

core-2021-12.9

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Safari 15.2 (17612.3.6.1.6)

### Which operating system are you using to run this browser?

macOS Monterey 12.1

### Problem-relevant frontend configuration

Here's the service call field in question:

```yaml
restrict_watering:
  name: Restrict All Watering
  description: Restrict all watering activities from starting for a time period
  fields:
    device_id:
      name: Controller
      description: The controller whose watering activities should be restricted
      required: true
      selector:
        device:
          integration: rainmachine
    duration:
      name: Duration
      description: The time period to restrict watering activities from starting
      required: true
      default: "01:00:00"
      selector:
        text:
```

### Javascript errors shown in your browser console/inspector

The HASS Core logs show this:

```txt
2022-01-19 11:56:55 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: required key not provided @ data['duration']
2022-01-19 11:56:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [4684009376] Error handling message: required key not provided @ data['duration']. Got None
```

Nothing is showing in the browser console.
