### ISSUE TITLE
coloured gauge indicators are misaligned or flipped and rotated slightly when viewed on Apple iOS

### ISSUE THREAD

**Issue by del13r** [home-assistant/frontend#11421]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I noticed recently that the coloured gauge indicators are misaligned or flipped and rotated slightly when viewed on Apple iOS in both the iOS Home Assistant App as well as Chrome for iOS.

iOS Home Assistant App - Portrait
![IMG-6924](https://user-images.githubusercontent.com/86141523/150891602-d28fb462-a187-463a-a68c-11003148c27d.jpg)

iOS Home Assistant App - Landscape
![IMG-6925](https://user-images.githubusercontent.com/86141523/150891645-353ddd68-fbb7-47ae-ae7b-95e7f3d21e29.jpg)

### Describe the behavior you expected

When I go into chrome on my desktop, the gauges display fine.
Chrome - Windows
![image](https://user-images.githubusercontent.com/86141523/150891749-1da5c15a-8d56-4201-8895-6bc2a8cf5c99.png)

### Steps to reproduce the issue

tested using different devices and narrowed it down to an issue with iOS device.

### What version of Home Assistant Core has the issue?

core-2021.12.10

### In which browser are you experiencing the issue with?

Google Chrome 97.0.4692.84

### Which operating system are you using to run this browser?

Apple iOS 15.2.1

### Problem-relevant frontend configuration

```yaml
title: ''
views:
  - path: default_view
    title: Power
    type: sidebar
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.mqtt_consumption
            min: 0
            max: 7500
            severity:
              green: 0
              yellow: 0
              red: 0
          - type: gauge
            min: 0
            max: 7500
            severity:
              green: 1
              yellow: 0
              red: 0
            entity: sensor.mqtt_production
          - type: gauge
            entity: sensor.today_energy_total_cost
            min: -1
            max: 5
            severity:
              green: 0
              yellow: 2
              red: 4
      - type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.mqtt_import_power
            min: 0
            max: 7500
            severity:
              green: 0
              yellow: 0
              red: 0
          - type: gauge
            entity: sensor.mqtt_export_power
            min: 0
            max: 7500
            severity:
              green: 1
              yellow: 0
              red: 0
          - type: gauge
            entity: sensor.mqtt_instant_cost_per_hour
            min: -1.1
            max: 0.83
            severity:
              green: 0.04
              yellow: 0.2
              red: 0.4
```
