### ISSUE TITLE
Views with spaces are not reachable.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/frontend#11489]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Create a view with a space in the path.  Make the view visible

```
- title: Living Room
  path: living room
  visible: true
  ...
```

Now, in lovelace, try to access the page.  It's impossible.   This was working before and it no longer works now.

### Describe the behavior you expected

Pages that contain paths should be reachable when spaces are %20, e.g. 
```
http://ip:8123/lovelace/living%20room
```
This worked before, now it does not.

### Steps to reproduce the issue

1. Create a view with a space in the path.  Make the view visible

```
title: Home
views:
- title: Garage
  path: garage
  visible: true
  cards:
  - type: entities
    entities:
    - sun.sun
- title: Living Room
  path: living room
  visible: true
  cards:
  - type: entities
    entities:
    - type: section
      label: Section example
```

2. Click on the living room view, it will never load and always display the garage view.  This is because it's defaulting to the main view which is the garage view.

### What version of Home Assistant Core has the issue?

2022.3.0.dev20220130

### What was the last working version of Home Assistant Core?

A dev version from around 2 weeks ago (I dont remember the exact version)

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

All
