### ISSUE TITLE
input_number shows impossible value in hover

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11544]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="331" alt="Schermafbeelding 2022-02-04 om 15 53 04" src="https://user-images.githubusercontent.com/33354141/152550081-145809a8-6f98-4124-bcc3-c315eea4ae1f.png">

### Describe the behavior you expected

show 255

### Steps to reproduce the issue

1. create below input_number and slide to the max
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.3.0.dev20220204

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS  Monterey 12.1 

### State of relevant entities

```txt
input_number:
  hue_dynamic_scene_brightness:
    name: Hue scene brightness
    min: 0
    max: 255
    step: 10
```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - input_select.hue_dynamic_scene
  - input_number.hue_dynamic_scene_speed
  - input_number.hue_dynamic_scene_brightness
```
