### ISSUE TITLE
WebRTC camera entities do not display when navigating away from the page and returning

### ISSUE THREAD

**Issue by ronaldheft** [home-assistant/frontend#11540]
### The problem

If I load up a page that has a camera entity using WebRTC, I click on another lovelace page, and then navigate back to the original page, the camera entity does not load when returning to the page and remains a black box.

If I start on a lovelace page that does not have a camera entity and then navigate to the page with a camera entity, it displays fine the first time.

The issue appears when returning to pages that have already displayed WebRTC camera entities. I have been able to reproduce this in both Safari and Chrome on Mac.

### What version of Home Assistant Core has the issue?

core-2022.2.0

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

rtsp_to_webrtc

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/rtsp_to_webrtc

### Anything in the logs that might be useful for us?

```txt
Nothing shows for the WebRTC component.
```

**Comment by ronaldheft** [comment]
@allenporter 

Sure, here is my card configuration. I'm using just a standard `picture-glance` card.

```yaml
type: picture-glance
title: Driveway
camera_image: camera.driveway_rtsp
camera_view: live
aspect_ratio: "16:9"
entities:
  - entity: binary_sensor.camera_static_last_snapshot
    attribute: last_changed
    show_state: true
tap_action:
  action: url
  url_path: "synocam://"
```

The card is a descendent of a `grid` card, which is a descendent of a `vertical-stack`, if that ends up mattering.
