### ISSUE TITLE
Two View Card into ONE CARD VIEW

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#11549]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

merged two view card into one, same on the phone.

### Describe the behavior you expected

.

### Steps to reproduce the issue

idk

### What version of Home Assistant Core has the issue?

2022.2.1

### What was the last working version of Home Assistant Core?

2021.12.10

### Problem-relevant frontend configuration

```yaml
This code is for view card i dont see.

                    "title": "Dzuri\u0161 Home Server",
                    "path": "Dzuri\u0161HomeServer",
                    "icon": "ios:server-rack",
                    "type": "custom:vertical-layout",
                    "badges": [],
                    "cards": [
                        {
                            "type": "vertical-stack",
                            "cards": [
                                {
                                    "type": "entities",
                                    "entities": [
                                        {
                                            "entity": "sensor.dzuris_home_server_uptime"
                                        },
                                        {
                                            "entity": "binary_sensor.dzuris_server_power_status"
                                        }
                                    ]
                                },
                                {
                                    "type": "entities",
                                    "entities": [
                                        {
                                            "entity": "sensor.disk_use_percent"
                                        },
                                        {
                                            "entity": "sensor.disk_use"
                                        },
                                        {
                                            "entity": "sensor.disk_free"
                                        }
                                    ],
                                    "footer": {
                                        "type": "graph",
                                        "entity": "sensor.disk_free",
                                        "hours_to_show": 24,
                                        "detail": 2
                                    }
                                },
                                {
                                    "type": "entities",
                                    "entities": [
                                        {
                                            "entity": "sensor.memory_use_percent"
                                        },
                                        {
                                            "entity": "sensor.memory_use"
                                        },
                                        {
                                            "entity": "sensor.memory_free"
                                        }
                                    ]
                                },
                                {
                                    "type": "entities",
                                    "entities": [
                                        {
                                            "entity": "sensor.processor_use_percent"
                                        },
                                        {
                                            "entity": "sensor.processor_temperature"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "type": "vertical-stack",
                            "cards": [
                                {
                                    "type": "entities",
                                    "entities": [
                                        {
                                            "entity": "switch.dzuris_dns_server"
                                        },
                                        {
                                            "entity": "script.dzuris_dns_server_restart"
                                        },
                                        {
                                            "entity": "input_boolean.dzuris_home_server"
                                        },
                                        {
                                            "entity": "script.dzuris_home_server_restart"
                                        },
                                        {
                                            "entity": "script.dzuris_home_server_core_restart"
                                        },
                                        {
                                            "entity": "script.dzuris_node_red_server_global"
                                        }
                                    ]
                                },
                                {
                                    "type": "entities",
                                    "entities": [
                                        {
                                            "entity": "automation.dzuris_home_server_start_reload_local_tuya_cfg"
                                        },
                                        {
                                            "entity": "automation.dzuris_home_server_start_reload_reolink_cfg"
                                        },
                                        {
                                            "entity": "automation.dzuris_home_server_start_reload_pi_hole_cfg"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "type": "custom:uptime-card",
                            "bar": {
                                "spacing": 5,
                                "height": 20,
                                "round": 8,
                                "amount": 24
                            },
                            "color": {
                                "ok": "#4BFF59",
                                "ko": "#FF0000",
                                "half": "#EA3900",
                                "title": "Black"
                            },
                            "show": {
                                "header": true,
                                "icon": true,
                                "status": true,
                                "timeline": true,
                                "footer": true,
                                "average": false,
                                "title": true
                            },
                            "alias": {
                                "ok": "100%",
                                "ko": "BAD"
                            },
                            "hours_to_show": 24,
                            "entity": "binary_sensor.dzuris_server_power_status",
                            "name": "Dzuri\u0161 Home Server Power Status",
                            "icon": "ios:server-rack",
                            "update_interval": 30,
                            "ko_icon": "mdi:flash-alert-outline",
                            "severity": 1,
                            "title_adaptive_color": false,
                            "status_adaptive_color": true,
                            "icon_adaptive_color": true,
                            "tooltip_adaptive_color": false,
                            "tooltip": {
                                "animation": true,
                                "hour24": false
                            },
                            "tap_action": {
                                "action": "more-info"
                            },
                            "alignment": {
                                "tooltip_first": false,
                                "icon_first": false,
                                "status": "center",
                                "header": "center"
                            },
                            "blink": {
                                "effect": "fade",
                                "target": "status"
                            },
                            "ok": "off",
                            "ko": "on"
                        },
                        {
                            "type": "horizontal-stack",
                            "cards": [
                                {
                                    "type": "custom:button-card",
                                    "entity": "binary_sensor.updater",
                                    "layout": "icon_name",
                                    "show_state": true,
                                    "show_name": true,
                                    "show_label": true,
                                    "styles": {
                                        "card": [
                                            {
                                                "max-width": "250px"
                                            },
                                            {
                                                "max-height": "80px"
                                            },
                                            {
                                                "margin": "auto"
                                            }
                                        ],
                                        "icon": [
                                            {
                                                "color": "black"
                                            },
                                            {
                                                "margin-left": "15%"
                                            }
                                        ],
                                        "name": [
                                            {
                                                "color": "black"
                                            },
                                            {
                                                "font-size": "15px"
                                            },
                                            {
                                                "padding-right": "50px"
                                            },
                                            {
                                                "max-width": "116%"
                                            }
                                        ],
                                        "state": [
                                            {
                                                "color": "black"
                                            },
                                            {
                                                "font-size": "15px"
                                            }
                                        ]
                                    },
                                    "double_tap_action": {
                                        "action": "url",
                                        "url_path": "http://dzurishome:8123/hassio/dashboard"
                                    }
                                },
                                {
                                    "type": "custom:button-card",
                                    "entity": "sensor.hacs",
                                    "layout": "icon_name",
                                    "show_state": true,
                                    "show_name": true,
                                    "show_label": true,
                                    "styles": {
                                        "card": [
                                            {
                                                "max-width": "250px"
                                            },
                                            {
                                                "max-height": "80px"
                                            },
                                            {
                                                "margin": "auto"
                                            }
                                        ],
                                        "icon": [
                                            {
                                                "color": "black"
                                            },
                                            {
                                                "margin-left": "15%"
                                            }
                                        ],
                                        "name": [
                                            {
                                                "color": "black"
                                            },
                                            {
                                                "font-size": "15px"
                                            },
                                            {
                                                "padding-right": "75px"
                                            }
                                        ],
                                        "state": [
                                            {
                                                "color": "black"
                                            },
                                            {
                                                "font-size": "15px"
                                            },
                                            {
                                                "label": "1",
                                                "value": "TEST"
                                            },
                                            {
                                                "label": "2",
                                                "value": "TEST"
                                            },
                                            {
                                                "label": "3",
                                                "value": "TEST"
                                            },
                                            {
                                                "label": "0",
                                                "value": "TEST"
                                            }
                                        ]
                                    },
                                    "double_tap_action": {
                                        "action": "url",
                                        "url_path": "http://dzurishome:8123/hacs/entry"
                                    }
                                }
                            ]
                        },
                        {
                            "type": "custom:mini-graph-card",
                            "entities": [
                                "sensor.processor_temperature"
                            ],
                            "hours_to_show": 24,
                            "align_state": "center",
                            "points_per_hour": 10,
                            "show": {
                                "labels": false,
                                "extrema": true,
                                "icon_adaptive_color": true
                            },
                            "color_thresholds": [
                                {
                                    "value": 15,
                                    "color": "#009BFF"
                                },
                                {
                                    "value": 20,
                                    "color": "#009BFF"
                                },
                                {
                                    "value": 25,
                                    "color": "#009BFF"
                                },
                                {
                                    "value": 30,
                                    "color": "#009BFF"
                                },
                                {
                                    "value": 35,
                                    "color": "#009BFF"
                                },
                                {
                                    "value": 40,
                                    "color": "#00D1FF"
                                },
                                {
                                    "value": 45,
                                    "color": "#FFAA00"
                                },
                                {
                                    "value": 50,
                                    "color": "#FF4D00"
                                },
                                {
                                    "value": 55,
                                    "color": "#FF4D00"
                                },
                                {
                                    "value": 60,
                                    "color": "#FF0000"
                                },
                                {
                                    "value": 65,
                                    "color": "#FF0000"
                                }
                            ]
                        },
                        {
                            "type": "custom:mini-graph-card",
                            "entities": [
                                "sensor.rack_temperature"
                            ],
                            "align_state": "center",
                            "hours_to_show": 24,
                            "points_per_hour": 3,
                            "show": {
                                "labels": false,
                                "extrema": true,
                                "icon_adaptive_color": true
                            },
                            "color_thresholds": [
                                {
                                    "value": 30,
                                    "color": "#FF0000"
                                },
                                {
                                    "value": 25,
                                    "color": "#FF5815"
                                },
                                {
                                    "value": 22,
                                    "color": "#FFD815"
                                },
                                {
                                    "value": 20,
                                    "color": "#15FF95"
                                },
                                {
                                    "value": 15,
                                    "color": "#00A6FF"
                                }
                            ]
                        }
                    ]
                },
```

### Additional information

https://user-images.githubusercontent.com/42905545/152562437-0769ffe7-1e85-4e3d-a610-aae799beb48d.mp4
