### ISSUE TITLE
cast.show_lovelace_view ignoring background: set on view

### ISSUE THREAD

**Issue by filipwpalm** [home-assistant/frontend#11606]
### The problem

When using cast.show_lovelace_view on a script or via https://cast.home-assistant.io/ the view is casted with correct cards and data. 

But if a background: image is set it will not be casted aswell.

Examplecode for the lovelace view tv:

  - title: TV
    path: tv
    icon: mdi:television
    background: >-
      center / cover no-repeat fixed
      url('https://****.ui.nabu.casa/local/****.jpg')

The above code is correctly showing the background image via a normal browser. But if casted via cast.show_lovelace_view a white background is showed instead.

### What version of Home Assistant Core has the issue?

core-2022.2.2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Google Cast

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/cast

### Example YAML snippet

```yaml
Script:
  me_cast_dashboard:
    alias: "Cast Dashboard"
    sequence:
        - service: cast.show_lovelace_view
          data:
            entity_id: media_player.chromecast
            view_path: tv

Lovelace:
  - title: TV
    path: tv
    icon: mdi:television
    background: >-
      center / cover no-repeat fixed
      url('https://******.ui.nabu.casa/local/****.jpg')
    cards:
      - type: entity
        entity: sensor.time_date
        state_color: false
      - type: entities
        entities:
          - entity: person.person1
```
