### ISSUE TITLE
binary_sensor displays 'on' icon for 'unknown' state

### ISSUE THREAD

**Issue by Renegade605** [home-assistant/frontend#11720]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since 2022.2 update binary sensors can report unknown state. But, badge and entity icons communicate on when unknown.
![image](https://user-images.githubusercontent.com/5857062/154596752-8bd8854e-3d48-4688-843d-75a01c8a8cae.png)

### Describe the behavior you expected

State icons should show off variant when value is unknown, or this behaviour should be configurable.
![image](https://user-images.githubusercontent.com/5857062/154596843-b0dd9495-76d2-4604-9080-7f204ea6932e.png)

### Steps to reproduce the issue

```yaml
binary_sensor:
  - platform: mqtt
    name: "Garage Motion"
    unique_id: garage_motion
    state_topic: blueiris/garage/motion
    payload_on: 1
    device_class: motion
    off_delay: 30
```

### What version of Home Assistant Core has the issue?

2022.2.0-8

### What was the last working version of Home Assistant Core?

2021.12.10

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
device_class: motion
friendly_name: Garage Motion
```

### Problem-relevant frontend configuration

```yaml
views:
  - title: ''
    badges:
      - entity: binary_sensor.garage_door
      - entity: binary_sensor.garage_motion

```
