### ISSUE TITLE
new input_select dropdown drops behind other cards.

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11738]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="509" alt="Schermafbeelding 2022-02-19 om 22 32 21" src="https://user-images.githubusercontent.com/33354141/154819829-2493bca2-7ba9-4e76-86f3-db1cdfb4924d.png">

### Describe the behavior you expected

regular dropdown....

### Steps to reproduce the issue

1. dont know really, it just happens
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.3.0.dev20220219

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

all! 

### Which operating system are you using to run this browser?

MacOS  Monterey 12.2.1

### Problem-relevant frontend configuration

```yaml
- type: custom:auto-entities
    card:
      type: entities
      title: Mini Media Players auto
      card_mod: *header
      show_header_toggle: false
    show_empty: false
    filter:
      include:
        - domain: media_player
          options:
            type: custom:mini-media-player
            artwork: cover
            group: true
            hide:
              power_state: false
      exclude:
        - state: unavailable
        - state: idle
        - state: 'off'
```

### Additional information

aware this is a custom card config, but that hasn't changed since forever. It probably is caused by the new select element?

really strange is that when I open this view in another browser, it is displayed the same. Without even having touched the select element.

ill refer to this at mini-media-player too, if its a thing for that card. please have a look?
