### ISSUE TITLE
2022.3.0b0: Frontend won't load unless a certain sensor (in this case MariaDB size) is removed

### ISSUE THREAD

**Issue by Skeletorjus** [home-assistant/frontend#11824]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Frontend version 20220223.0,

After upgrading to 2022.3.0b0 the frontend was stucked at "Loading data" with the following error in the log:
```
2022-02-23 23:54:29 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.result[242](State: sensor.mariadb_size).attributes.value=2190.33(<class 'decimal.Decimal'>
2022-02-23 23:54:30 ERROR (MainThread) [frontend.js.latest.202202230] http://192.168.1.150:8123/lovelace-mobil?external_auth=1:0:0 Uncaught
```

Automations still worked in the background, so my best guess is that this is a frontend issue.

After removing sensor.mariadb_size from my config and restarting Home Assistant, the frontend loaded as usual.

I do not know if this is related to the platform (SQL) or if this could happen with any sensor. I have not tested with a desktop browser.

### Describe the behavior you expected

The frontend loading.

### Steps to reproduce the issue

1. Have the offending sensor active
2. Start Home Assistant

### What version of Home Assistant Core has the issue?

core-2022.3.0b0

### What was the last working version of Home Assistant Core?

core-2022.2.9

### In which browser are you experiencing the issue with?

Android companion app, Chrome 98.0.4758.101 (mobile)

### Which operating system are you using to run this browser?

Android 10

### Problem-relevant frontend configuration

```yaml
sensor:
  - platform: sql
    db_url: !secret sql_url
    queries:
      - name: MariaDB size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB
```
