### ISSUE TITLE
Sidebar view loading incorrectly.

### ISSUE THREAD

**Issue by jazzyisj** [home-assistant/frontend#11834]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sidebars views load correctly on initial view.  When browser is refreshed all cards stack in the main view and the sidebar is empty.  A reload of lovelace corrects the issue until the browser is refreshed again.

Confirmed on Chrome, Edge on Windows and Fire Tablet using Fully Kiosk.

### Describe the behavior you expected

Cards loading in correct area of sidebar view after browser refresh.

### Steps to reproduce the issue

1. Load a sidebar view.
2. Refresh browser for incorrect render.
3. Reload lovelace for correct render.

### What version of Home Assistant Core has the issue?

2022.3.0b1

### What was the last working version of Home Assistant Core?

2022.2.9

### In which browser are you experiencing the issue with?

Chrome Version 98.0.4758.102 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10.0.19043

### Problem-relevant frontend configuration

```yaml
title: 'Test'
icon: mdi:ab-testing
path: test
type: sidebar
cards:
  - type: entities
    entities:
      - sensor.outdoor_temperature
    view_layout:
      position: sidebar

  - type: entities
    entities:
      - sensor.outdoor_temperature
```

### Javascript errors shown in your browser console/inspector

```txt
None.
```

### Additional information

![sidebar good](https://user-images.githubusercontent.com/44064559/155578284-be921966-560a-4c40-b027-ab13db682258.png)
Correct Render

![sidebar error](https://user-images.githubusercontent.com/44064559/155578368-dfb3de14-c984-4af4-8e2e-e804d6321b3f.png)
Incorrect Render
