### ISSUE TITLE
beta: automation: Timebased triggers get extra lines in yaml and cause errors on safe

### ISSUE THREAD

**Issue by bafplus** [home-assistant/frontend#11840]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

BETA!

When creating a new automation and by using timebased triggers there are extra lines of "mode: value" added in the yaml causing "Message malformed: extra keys not allowed @ data['mode']" errors on saving.
The result in yaml :

```yaml
alias: Nieuwe automatisering
description: ''
trigger:
  - mode: value
    platform: time
    at: '18:00:00'
    id: aan
  - mode: value
    platform: time
    at: '23:00:00'
    id: Uit
condition: []
action:
  - type: turn_off
    device_id: 4858e0aeaa0622910c2010d0fb993171
    entity_id: switch.lt_led_kast
    domain: switch
mode: single
```

### Describe the behavior you expected

ehm...save without errors :-)

### Steps to reproduce the issue

1. create new automation in UI mode
2. Create a time based trigger
3. Try to save the automation
...

### What version of Home Assistant Core has the issue?

core-2022.3.0b1

### What was the last working version of Home Assistant Core?

--

### In which browser are you experiencing the issue with?

--

### Which operating system are you using to run this browser?

HA-OS

### Problem-relevant frontend configuration

```yaml
alias: Nieuwe automatisering
description: ''
trigger:
  - mode: value
    platform: time
    at: '18:00:00'
    id: aan
  - mode: value
    platform: time
    at: '23:00:00'
    id: Uit
condition: []
action:
  - type: turn_off
    device_id: 4858e0aeaa0622910c2010d0fb993171
    entity_id: switch.lt_led_kast
    domain: switch
mode: single
```
