### ISSUE TITLE
Bad "input_*" rendering in a horizontal-stack card

### ISSUE THREAD

**Issue by Herbs851** [home-assistant/frontend#11963]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you set 2 inputs in a horizontal card, the rendering is bad.

The input field goes beyond the card.

See the screenshot below :

![image](https://user-images.githubusercontent.com/51154851/157001485-c4406971-689f-4372-a35a-d941f677557e.png)

### Describe the behavior you expected

Correct rendering : 

![image](https://user-images.githubusercontent.com/51154851/157001722-ce2db143-e926-4627-b0a4-48f87a1aee3d.png)

### Steps to reproduce the issue

1. Create horizontal-stack with this kind of code : 

```
type: horizontal-stack
cards:
  - type: entities
    entities:
      - entity: input_select.cover_cha_delay
  - type: entities
    entities:
      - entity: input_select.cover_par_delay
```

### What version of Home Assistant Core has the issue?

2022.3.2

### What was the last working version of Home Assistant Core?

2022.2.9

### In which browser are you experiencing the issue with?

Firefox 97.0.2 / Brave Version 1.36.109 Chromium: 99.0.4844.51

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

None

### Javascript errors shown in your browser console/inspector

None
