### ISSUE TITLE
error	/config/ui-lovelace.yaml not found

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11981]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

an error is displayed in the System Health panel for the Lovelace config.

<img width="602" alt="Schermafbeelding 2022-03-08 om 13 50 05" src="https://user-images.githubusercontent.com/33354141/157242385-1b846254-f471-4205-ae44-257c24b77472.png">

I dont use the default ui-lovelace view and have set my dashboards in a yaml file

<img width="1425" alt="Schermafbeelding 2022-03-08 om 13 50 27" src="https://user-images.githubusercontent.com/33354141/157241865-fcc21a65-e175-4751-8b30-91906b659f76.png">

### Describe the behavior you expected

show no error. Maybe indicate a 'manual yaml configuration' is used?

### Steps to reproduce the issue

1. check config/info
2.
3.
...

### What version of Home Assistant Core has the issue?

 2022.4.0.dev20220308

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS Monterey 12.2.1

### Problem-relevant frontend configuration

```yaml
lovelace:
  mode: yaml
  resources: !include /config/lovelace/resources.yaml
  dashboards:

    ui-overview:
      mode: yaml
      filename: lovelace/dashboards/ui-overview.yaml
      title: Overview
      icon: mdi:view-dashboard

    ui-settings:
      mode: yaml
      filename: lovelace/dashboards/ui-settings.yaml
      title: Change settings
      icon: mdi:tools

    ui-data:
      mode: yaml
      filename: lovelace/dashboards/ui-data.yaml
      title: Home data
      icon: mdi:home-analytics
      require_admin: true

    ui-develop:
      mode: yaml
      filename: lovelace/dashboards/ui-develop.yaml
      title: Develop
      icon: mdi:remote-desktop
      require_admin: true

    ui-test:
      mode: yaml
      filename: lovelace/dashboards/ui-test.yaml
      title: Test
      icon: mdi:test-tube
      require_admin: true
```

**Comment by Mariusthvdb** [comment]
just to feed back this is still happening:

<img width="605" alt="Schermafbeelding 2022-04-21 om 14 29 26" src="https://user-images.githubusercontent.com/33354141/164458337-76c0e02c-fbc4-485c-833e-db6a386eaf76.png">

in frontend 20220420.0 - latest

**Comment by Mariusthvdb** [comment]
keeping alive

2022.8 still showing this as error, while it most certainly is Not.

**Comment by Mariusthvdb** [comment]
Since this remains unsolved I decided to fix another nuisance (the auto created all entities view upon re-login) by adding a ui-lovelace.yaml with the following content:

```

  - type: markdown
    content: >
      Hi {{user}}, you need to reset the auto-selected 'Overview (default)' View upon login.
      Go to your profile picture in the left side menu and select 'Overview'.
      Or click the image below 😉

  - type: picture
    image: /local/various/select_dashboard.png
    tap_action:
      action: navigate
      navigation_path: /profile
```

this not only removes the silly Error in System Health, but also guides the user to re-set the default View to something useful
