### ISSUE TITLE
Map card does not show up in main view of the sidebar view type

### ISSUE THREAD

**Issue by Mincka** [home-assistant/frontend#12023]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I use a panel (**not** the `default_view`) with the "Side bar" view type. If I add a **map card** in the **main** (left) area, it will not appear on browser refresh. 
I need to go on another dashboard first, then go back to the panel with the map card and then it appears.
I thought it was fixed in #11834 but it's not. As leave this reference in case that could be somehow related.

If a map card is present in the `default_view`  panel of the dashboard, it will work for it and other panels, configured as side bar view or not. Thanks [oalbaf](https://github.com/oalbaf) for this clarification.

### Workaround

See this temporary [workaround](https://github.com/home-assistant/frontend/issues/12023#issuecomment-1075035982).

### Describe the behavior you expected

The map card shows up on browser reload like other cards.

### Steps to reproduce the issue

1. Create a new panel
2. Set it to `Side bar` `View Type` 
3. Add a map card in the main area
4. Click done
5.  CTRL+R
6. The map card does not appear
7. Switch to another **Dashboard**
8. Go back to the panel with the map card
9. The map card appears as expected
```
  - theme: Backend-selected
    title: Test Panel
    path: p
    type: sidebar
    badges: []
    cards:
      - type: map
        entities:
          - device_tracker.telephone_julien
          - device_tracker.telephone_morgane
```

### What version of Home Assistant Core has the issue?

2022.3

### What was the last working version of Home Assistant Core?

2022.2

### In which browser are you experiencing the issue with?

Edge Version 99.0.1150.36 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 19043.1586

### Javascript errors shown in your browser console/inspector

```txt
None
```
