### ISSUE TITLE
Automation visual editor breaks the time formatted text

### ISSUE THREAD

**Issue by Frans1960** [home-assistant/frontend#12058]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Automation visual editor breaks the time formatted text by removing ' from the text, but not with all the text. 

### Describe the behavior you expected

The Automation visual editor breaks the time formatted text by removing ' from the text, but not with all the text. 

### Steps to reproduce the issue

1. Create or Edit by the Automation visual editor. 
2. Show it in the Automation YAML editor
3. check the code with the File editor
...

### What version of Home Assistant Core has the issue?

2022.3.4

### What was the last working version of Home Assistant Core?

2021.???

### In which browser are you experiencing the issue with?

Microsoft Edge

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
Correct shown in the  Automation YAML editor

alias: Slaapkamerthermostaat
description: Temperatuur instellingen
trigger:
  - platform: time
    at: '06:00'
  - platform: time
    at: '07:00'
  - platform: time
    at: '08:00'
  - platform: time
    at: '13:20'
  - platform: time
    at: '13:30'
  - platform: state
    entity_id: climate.slaapkamer
    attribute: preset_mode
condition:
  - condition: state
    entity_id: climate.slaapkamer
    state: none
    attribute: preset_mode
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: '06:00'
                weekday:
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
                before: '07:00'
              - condition: time
                after: '07:00'
                weekday:
                  - sat
                  - sun
                before: '08:00'
              - condition: time
                after: '22:00'
                before: '23:00'
        sequence:
          - service: climate.set_temperature
            data:
              temperature: 15
            entity_id: climate.slaapkamer
    default:
      - service: climate.set_temperature
        data:
          temperature: 5
        target:
          entity_id: climate.slaapkamer
mode: ''
```

### Problem-relevant frontend configuration

```yaml
Logger: homeassistant.config
Source: config.py:454
First occurred: 14 maart 2022 19:45:59 (68 occurrences)
Last logged: 14 maart 2022 21:19:54

Invalid config for [automation]: Expected HH:MM, HH:MM:SS or Entity ID with domain 'input_datetime' or 'sensor' @ data['at'][0]. Got None. (See /config/configuration.yaml, line 17).
Invalid config for [automation]: Invalid time specified: 79200 for dictionary value @ data['condition'][0]['conditions'][1]['conditions'][0]['after']. Got None Invalid time specified: 86340 for dictionary value @ data['condition'][0]['conditions'][1]['conditions'][0]['before']. Got None. (See /config/configuration.yaml, line 17).
Invalid config for [automation]: expected a dictionary for dictionary value @ data['action'][0]['default'][0]['target']. Got None. (See /config/configuration.yaml, line 17).
```

### Additional information

Show in the File editor without the ' on the times in the code, e.g.:   at: 06:00 that should be   at: '06:00'

  alias: Slaapkamerthermostaat
  description: Temperatuur instellingen
  trigger:
  - platform: time
    at: 06:00
  - platform: time
    at: 07:00
  - platform: time
    at: 08:00
  - platform: time
    at: '13:20'
  - platform: time
    at: '13:30'
  - platform: state
    entity_id: climate.slaapkamer
    attribute: preset_mode
  condition:
  - condition: state
    entity_id: climate.slaapkamer
    state: none
    attribute: preset_mode
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: time
          after: 06:00
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          before: 07:00
        - condition: time
          after: 07:00
          weekday:
          - sat
          - sun
          before: 08:00
        - condition: time
          after: '22:00'
          before: '23:00'
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 15
        entity_id: climate.slaapkamer
    default:
    - service: climate.set_temperature
      data:
        temperature: 5
      target:
        entity_id: climate.slaapkamer
  mode: single
