### ISSUE TITLE
Entity icon color inversed based on state

### ISSUE THREAD

**Issue by CZonin** [home-assistant/frontend#12057]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Within the past couple released I have noticed that icons in lovelace have their colors inversed based on their state.  In the past for example, when a light was on the icon would be blue, and grey when off. Now it's the opposite and it's like that for every entity. When I go into an entities details the colors are correct though. Here's a screenshot of one of my cards:
![cUH99le](https://user-images.githubusercontent.com/67965669/158587900-6a128cb1-9b27-4264-8ea8-00735e9bb85d.png)

### Describe the behavior you expected

Entity icon colors in lovelace will match those in the entity details.

### Steps to reproduce the issue

1. Have entity with state based colors in lovelace
2. Open details of one of those entities
3. Icon colors will be different based on current state in lovelace and in the details screen.

### What version of Home Assistant Core has the issue?

2022.3.5

### What was the last working version of Home Assistant Core?

Not sure

### In which browser are you experiencing the issue with?

Chrome  99.0.4844.74 / Home Assistant Android App

### Which operating system are you using to run this browser?

Windows 11 / Android 12

### State of relevant entities

```txt
On / Off or Open / Closed
```

### Problem-relevant frontend configuration

```yaml
type: entities
title: Master Bedroom
entities:
  - type: divider
    style:
      width: 107%
      height: 2px
      margin-left: '-16px'
      margin-right: auto
      opacity: 0%
  - type: custom:slider-entity-row
    entity: light.master_bedroom_ceiling_fan_light
    name: Light
    toggle: false
    hide_state: true
    tap_action:
      action: toggle
  - type: custom:slider-entity-row
    entity: light.corey_bedroom_lamp
    toggle: false
    hide_state: true
    tap_action:
      action: toggle
  - type: custom:slider-entity-row
    entity: light.lauren_bedroom_lamp
    toggle: false
    hide_state: true
    tap_action:
      action: toggle
```

**Comment by zsarnett** [comment]
Seems fine with non custom... It's possible its the slider entity row?

**Comment by cturra** [comment]
i was seeing it across all entity cards. i reverted back to 2022.3.5 and all returned to normal. it was present with both a custom and core theme and didn't go away when i "reset frontend cache." 

here is a short snippet from one of my dashboards (feel free to check out my github repo noted above for more of the config):

```
anchors:
  entities-style: &entities-style
    card_mod:
      style: |
        :host .card-content {
          padding: 0px 10px 5px;
        }
        ha-card {
          box-shadow: none;
        }
[..]
            - type: entities
              show_header_toggle: false
              <<: *entities-style
              entities:
                # display cabinet
                - entity: switch.plg_familyroom_cabinetlight
                  name: Cabinet
                  icon: 'mdi:light-recessed'
                  state_color: true
                # display corner
                - entity: switch.sw_familyroom_cornerlight
                  name: Corner
                  icon: 'mdi:light-recessed'
                  state_color: true
                # wall sconce
                - entity: light.sw_familyroom_walllights
                  name: 'Wall Sconce'
                  icon: 'mdi:wall-sconce-round-variant'
```

**Comment by zsarnett** [comment]
Can you try something non custom?

**Comment by cturra** [comment]
i can confirm, that after upgrading back to 2022.3.5 (from 2022.3.3) with the following "test" dashboard using nothing custom and entity state colors **are working as expected**.

```yaml
 - title: Test
    cards:
      - type: entities
        entities:
        # air purifier
        - entity: switch.plg_office_airpurifier
          name: 'Air Purifier'
          state_color: true
        # ceiling light
        - entity: switch.sw_office_ceilinglight
          name: 'Ceiling'
          state_color: true
```

@CZonin we can probably close this issue here... but let's track down the custom frontend component that's causing this. here is a list of what i have installed, which do you use?

 * battery-state-card
 * button-card
 * lovelace-auto-entities
 * lovelace-card-mod
 * lovelace-slider-entity-row
 * mini-graph-card
 * mini-media-player
 * rgb-light-card
 * simple-thermostat
 * simple-weather-card
 * vertical-stack-in-card
 
@zsarnett thanks for joining in on the conversation.

**Comment by CZonin** [comment]
I'm seeing the issue even with built in cards (ie. button, entity, etc).

@cturra in my current setup, I'm using:

- button-card
- lovelace-sider-entity-row
- vertical-stack-in-card

**Comment by cturra** [comment]
@CZonin do you by chance have `theme: ...` at the top of your dashboads? something like this...

```yaml
  - title: Climate
    path: climate
    icon: 'mdi:home-thermometer-outline'
    theme: google_theme
    badges: []
    cards:
    [...]
```

i did and removing that line resolved my issue!
