### ISSUE TITLE
trigger based template sensor doesnt auto update (needs a view reload)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12053]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

as title

### Describe the behavior you expected

show last-triggered, and auto update

### Steps to reproduce the issue

1. use trigger based sensor in card
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.4.0.dev20220315

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS  Monterey 12.2.1

### State of relevant entities

```txt
entity_id: binary_sensor.library_sensor_motion
icon: mdi:sofa
friendly_name: Last motion seen in area
```

### Problem-relevant frontend configuration

```yaml
entities:

      - entity: sensor.last_motion_sensor_triggered
        secondary_info: last-triggered
      - entity: sensor.last_motion_seen_in_area
        secondary_info: last-triggered
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

<strike>Seems there is no attribute last_triggered at all? Is this a backend (Core bug in that case?)</strike>

even though the state changes correctly, the last-triggered always shows :

<img width="495" alt="Schermafbeelding 2022-03-15 om 10 46 58" src="https://user-images.githubusercontent.com/33354141/158356922-d39f4c98-6aca-498f-b0ba-4d4b77ccb9ea.png">

and remains like that, needing a reload of the view to reveal the correct relative time:

<img width="490" alt="Schermafbeelding 2022-03-15 om 10 46 48" src="https://user-images.githubusercontent.com/33354141/158357003-5bd3387a-9365-48a1-bb2b-cbc4aeeeb20f.png">

yaml config of the sensors is correct:
```
template:

  - trigger:

      - platform: state
        entity_id:
          - binary_sensor.laundry_sensor_motion
          - binary_sensor.dining_table_sensor_motion
          - binary_sensor.auditorium_sensor_motion
          - binary_sensor.frontdoor_sensor_motion
          - binary_sensor.library_sensor_motion

        to: 'on'
    sensor:

      - unique_id: last_motion_sensor_triggered
        name: Last motion sensor triggered
        icon: mdi:motion-sensor
        state: >
          {{trigger.to_state.name.split(' sensor Motion')[0]}}
        attributes:
          entity_id: >
            {{trigger.entity_id}}
          last_triggered: >
            {{trigger.to_state.last_changed.isoformat()}}

      - unique_id: last_motion_seen_in_area
        name: Last motion seen in area
        icon: mdi:sofa
        state: >
          {{area_name(trigger.entity_id)}}
        attributes:
          entity_id: >
            {{trigger.entity_id}}
          last_triggered: >
            {{trigger.to_state.last_changed.isoformat()}}
```
