### ISSUE TITLE
Multiple-day events show as single day in Homeassistant calendar

### ISSUE THREAD

**Issue by meichthys** [home-assistant/frontend#12080]
### The problem

Events that span multiple days only show as a single day in the HA calendar:

Nextcloud (Source calendar):
<img width="1384" alt="Screen Shot 2022-03-18 at 11 03 34 PM" src="https://user-images.githubusercontent.com/10717998/159105163-fdf5d9db-dccc-4051-99c3-50858fc56d33.png">

HA Calendar:
<img width="1193" alt="Screen Shot 2022-03-18 at 11 35 44 PM" src="https://user-images.githubusercontent.com/10717998/159105170-1bd0eb29-b5d2-4470-b68c-13e09f704298.png">

### What version of Home Assistant Core has the issue?

2022.3.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Calendar, ical

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/calendar

### Example YAML snippet

```yaml
# https://www.home-assistant.io/integrations/caldav/
platform: caldav
url: https://nextcloud.mydomain.com/remote.php/dav/calendars/username/
username: !secret nextcloud_username
password: !secret nextcloud_password
calendars:
  - General
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
