### ISSUE TITLE
Frontend not updating entities on state change | state_color: true no longer functions 

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12115]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

noticed since Frontend updated to 20220322.0 it doesnt update the entities rendering  per state change. I really noticed it because custom-ui templates like
```
    input_select.select_flash_color:
      templates:
        icon_color: >
          return state.toLowerCase();
```

or
```
        icon_color: >
          if (state > 500) return 'firebrick';
          if (state > 0) return 'gold';
          return 'steelblue';
```
no longer work on state change. Right now, the view needs to be reloaded for the colors kick in. Same goes for plain icon_templates like:

```
          icon: >
            return (state === 'on') ? 'mdi:music' : 'mdi:music-off';
```
working perfectly in 2022.3.6, where Frontend is still on 20220301.2

I do know that above examples are for [custom-ui](https://github.com/Mariusthvdb/custom-ui), and not supported by HA. I wouldn't have posted if the Lovelace cards option for `state_color: true` would still be working....
It doesnt.
either on an individual entity, or as card option, see below:

please have a look what could have changed in the way the Frontend handles this?
as per Discord [#dev_frontend](https://discord.com/channels/330944238910963714/351047592588869643/956156202767773696), Zack suggested to have a look at the new websocket Changes.

### Describe the behavior you expected

Frontend changing colors and icons on state change

### Steps to reproduce the issue

1. See above
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.4.0.dev20220323

### What was the last working version of Home Assistant Core?

2022.3.6/7

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS  Monterey 12.2.1

### Problem-relevant frontend configuration

```yaml
type: entities
title: Hue motion sensor switches
state_color: true
show_header_toggle: true
entities:
  - entity: switch.dining_table_sensor_motion
    name: Dining table
    secondary_info: last-changed
  - entity: switch.auditorium_sensor_motion
    name: Auditorium
    secondary_info: last-changed
  - entity: switch.front_room_sensor_motion
    name: Front room
```
