### ISSUE TITLE
The list in input_select is not accessible

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#12114]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I don't know if it's correct to post it here ...

From converting input_select to material/mwc-button I encounter this bug: the list in an input_select placed in a PopUp generated by the BrowserMod integration is no longer accessible

![PopUp](https://user-images.githubusercontent.com/74879713/159773977-f1c19b0b-056c-4561-b83b-9a0f5e6ed2bf.png)

### Describe the behavior you expected

The list should be on top

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.3.6

### In which browser are you experiencing the issue with?

Firefox 98.0.1 - Chrome 99.0.4844.82

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
< Picture element >

  - type: state-label
    entity: sensor.roborock_s5_conversione_modalita_aspirante
    title: Modifica la potenza aspirante
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: Modalità aspirante
        card:
          type: entities
          entities:
            - entity: input_select.roborock_s5_modalita_aspirante
          deviceID:
            - this
            - dashboard
    style:
      transform: translate(0%, 0%)
      top: 2.5%
      right: 6.2%
      color: rgb(0, 0, 0)
```
