### ISSUE TITLE
Statistics card misses data for current month

### ISSUE THREAD

**Issue by djwlindenaar** [home-assistant/frontend#12196]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've added a statistics card to my frontend. Intention is to show for each month the maximum power produced by each of my solar panel strings in a bar chart. So 3 entities, one statistic: max. I've set the period to 90 days and monthly scale. The result is that the currently running month is not shown fully, but clipped in the middle of the middle bar. Also tried with different entities, same result. See pictures.
Basically I've found that whenever a bar chart is created, it is cropped in the middle of the current period, where it should include all of the current period.

![Screenshot from 2022-04-02 10-55-49](https://user-images.githubusercontent.com/32413299/161375837-6fbc4f03-2108-4b75-916c-076da6b699cc.png)

![Screenshot from 2022-04-02 10-53-56](https://user-images.githubusercontent.com/32413299/161375841-e57f0ed8-460b-4ca1-8692-919d7af33e16.png)

### Describe the behavior you expected

All bars for the running month/period are shown

### Steps to reproduce the issue

1. Create statistics bar card with the above-mentioned settings
2. look at the current period (good to create the chart with only a few bars, so you can actually see what happens to the current period)
3.
...

### What version of Home Assistant Core has the issue?

core-2022.3.8

### In which browser are you experiencing the issue with?

Firefox 94.0

### Which operating system are you using to run this browser?

Ubuntu Linux 21.10

### Problem-relevant frontend configuration

```yaml
chart_type: bar
period: month
days_to_show: 90
type: statistics-graph
entities:
  - sensor.carport_power_output
  - sensor.growatt_2_grid_active_power
  - sensor.growatt_grid_active_power
stat_types:
  - max
```
