### ISSUE TITLE
History graph rendering binary sensors that have object ids beginning with a number incorrectly

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#12225]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The history graph card is displaying a "de-slugified" object_id instead of the friendly name:

![friendly](https://user-images.githubusercontent.com/10679300/161710326-b02ddd7a-067c-402e-ab68-1e052cb8da89.png)

### Describe the behavior you expected

Friendly name to be displayed, when available.

### Steps to reproduce the issue

1. Add some binary sensors to a history graph card. EDIT: with an object id beginning with a number.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.4.0b4

### In which browser are you experiencing the issue with?

Firefox 98.0.2, Chrome 100.0.4896.75 

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: binary_sensor.00000_motion_alarm
  - entity: binary_sensor.00100_motion_alarm
  - entity: binary_sensor.00200_motion_alarm
  - entity: binary_sensor.00300_motion_alarm
  - entity: binary_sensor.00400_motion_alarm
  - entity: binary_sensor.00500_motion_alarm
  - entity: binary_sensor.00600_motion_alarm
  - entity: binary_sensor.pir_entry
  - entity: binary_sensor.pir_master_bedroom
```
