### ISSUE TITLE
Automation with delay, before sunrise / sunset not triggering – not clear why!

### ISSUE THREAD

**Issue by microfx** [home-assistant/frontend#12245]
This is not working still for me... it's never activated. 
<img width="916" alt="Bildschirmfoto 2022-04-07 um 13 37 18" src="https://user-images.githubusercontent.com/37987212/162190266-cb213979-3205-464d-acdf-f40e062e5843.png">

This node was not executed and so no further trace information is available.

<img width="575" alt="Bildschirmfoto 2022-04-07 um 13 38 09" src="https://user-images.githubusercontent.com/37987212/162190470-6f18804f-7087-4f11-b5b2-37ea979a316e.png">

```
alias: Kueche eMotion
description: ''
trigger:
  - type: motion
    platform: device
    device_id: b684927f214e572da70a26d1f0a0a862
    entity_id: binary_sensor.presence_3
    domain: binary_sensor
condition:
  - condition: sun
    before: sunset
    after: sunrise
action:
  - service: scene.turn_on
    target:
      entity_id: scene.kuche_nachtlicht
    metadata: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - wait_for_trigger:
      - type: no_motion
        platform: device
        device_id: b684927f214e572da70a26d1f0a0a862
        entity_id: binary_sensor.presence_3
        domain: binary_sensor
  - type: turn_off
    device_id: feafb8a064074c1ba73a816fa52ce7c9
    entity_id: light.eins
    domain: light
mode: single

```

The script is kinda broken … although it looked so straight forward. It's confusing for me! The tools to debug getting better. The conditions confuse me still.

_Originally posted by @microfx in https://github.com/home-assistant/frontend/issues/6587#issuecomment-1091632381_
