### ISSUE TITLE
Editing Automations via the GUI breaks if the yaml file is not named exactly "automations.yaml"

### ISSUE THREAD

**Issue by paulhaddon** [home-assistant/frontend#12257]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Editing Automations via the UI

(Configuration => Automations => [Pencil])

Brings up a modal error of 

**Only automations in automations.yaml are editable.** 

if the configuration file for Automations is not "automations.yaml"

### Describe the behavior you expected

Editing Automations via the UI

(Configuration => Automations => [Pencil])

should bring up the GUI editor, regardless of the name of the YAML file,
as long as the line in the configuration.yaml is correctly formatted and points
to a valid file.

### Steps to reproduce the issue

1.  create a separate file for Automations, call it anything but automations.yaml
2.  add a line in configuration.yaml to point to that file  (eg    automation: !include auto.yaml  )
3.  ensure the auto.yaml has valid Automation routines
4. Configuration => [Check Configuration]
5. verify "Configuration Valid!"
6. test one of the Automations via Configuration => Automations => [RUN ACTIONS]
7. Action runs as expected
8. Now click on [Pencil] next to that Automation, to bring up the GUI editor
9. Warning " Only automations in automations.yaml are editable. " is displayed.
10. Rename the existing Automations YAML file to exactly "automations.yaml"   (ie: auto.yaml =>  automations.yaml)
11. in configuration.yaml update the Automations line to be automations.yaml
12. Configuration => [Check Configuration]
13. verify "Configuration Valid!"
14. click [Automations] in the "YAML configuration reloading" section
15. go to Configuration => Automations
16. click on [Pencil] next to the previously failing Automation, to bring up the GUI editor
17. GUI editor is displayed, fields are editable, save works, edits are saved to automations.yaml
...

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Firefox v96.0.1 (64 Bit), Brave	1.29.76 Chromium

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
configuration.yaml entries:

- Working (allows GUI edits)

automation: !include automations.yaml

- Failing (GUI editor returns "Only automations in automations.yaml are editable" );

#note: singular, not plural
automation: !include automations.yaml

#also
automation: !include auto.yaml
```
