### ISSUE TITLE
`*` Showing on optional inputs in a blueprint

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/frontend#12268]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My blueprint has two optional inputs defined like this:
```yaml
blueprint:
  input:
    mobile_app_device:
      name: Mobile app device
      description: (Optional) Android, iphone, mac. Anything with the companion app
      default: ''
      selector:
        device:
          integration: mobile_app
    mobile_app_device_2:
      name: Mobile app device 2
      description: (Optional) Android, iphone, mac. Anything with the companion app.
      default: ''
      selector:
        device:
          integration: mobile_app
```
They still appear with a `*` in the UI as if they are required:
![Screen Shot 2022-04-08 at 12 04 01 PM](https://user-images.githubusercontent.com/2037026/162480300-a2db28e3-7253-4b06-a439-6da9594b1123.png)

### Describe the behavior you expected

There should not be a star.

### Steps to reproduce the issue

1. Make a blueprint
2. Add an input to it with a device selector
3. Give that input a default to make it optional
4. Try to make an automation out of it, notice there is still a `*` like it is required
...

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Firefox 98.02

### Which operating system are you using to run this browser?

macOS Monterey (12.2)
