### ISSUE TITLE
Light/Dark Theme mode not working as expected

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/frontend#12260]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have got `Backend-selected` on my profile page.

![image](https://user-images.githubusercontent.com/54566217/162336121-65c1dc9f-f215-46ef-a91d-be5a51249465.png)

Calling the service from Developer Tools does not do anything.

```
service: frontend.set_theme
data:
  mode: dark
  name: Github Dark Theme
```

Also, the theme stays either on Light or Dark mode. It does not seem to switch between the modes or themes. I have an automation that sets the theme but it does not seem to switch.

```
automation:

  - alias: Set Day/Night Theme
    id: set_daynight_theme
    initial_state: true
    trigger:
      - platform: state
        entity_id: sun.sun
        to: above_horizon
      - platform: state
        entity_id: sun.sun
        to: below_horizon
      - event: start
        platform: homeassistant
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sun.sun
                state: above_horizon
            sequence:
              - service: frontend.set_theme
                data:
                  name: oxfordblue
          - conditions:
              - condition: state
                entity_id: sun.sun
                state: below_horizon
            sequence:
              - service: frontend.set_theme
                data:
                  mode: dark
                  name: Github Dark Theme
        default: []
```

### Describe the behavior you expected

I expect the themes to switch based on the automation. 

### Steps to reproduce the issue

1. Set theme to `Backend-selected` in profile page
2. Call `frontend.set_theme` service for a theme with dark mode. Before doing so, use a light theme.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.4.1

### What was the last working version of Home Assistant Core?

core-2022.3.5

### In which browser are you experiencing the issue with?

Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Enterprise 20H2
