### ISSUE TITLE
Hysteresis field for new threshold sensor does not allow decimal values

### ISSUE THREAD

**Issue by lostcontrol** [home-assistant/frontend#12270]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new threshold sensor form in the UI does not allow decimal values, only integers (positive or negative). I have a working threshold sensor in YAML with a decimal value for hysteresis that I want to migrate to the new UI based helper.

```yaml
- platform: threshold
  entity_id: sensor.rez_repas_temperature
  name: "Ombrage limite température"
  upper: 23.0
  hysteresis: 0.49
```

I cannot enter any decimal value in the hysteresis field:

![image](https://user-images.githubusercontent.com/983305/162482774-1ab48e16-288e-4ffc-9e75-eeebd91beb48.png)

### Describe the behavior you expected

Hysteresis should accept decimal value (e.g. 0.5, or 0.33333333).

### Steps to reproduce the issue

1. Create a new threshold sensor
2. Set a decimal value for hysteresis (like 0.49)

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Firefox 99

### Which operating system are you using to run this browser?

Ubuntu 22.04
