### ISSUE TITLE
Boolean selector in blueprint cannot be updated after creating automation

### ISSUE THREAD

**Issue by gregrob** [home-assistant/frontend#12281]
### Checklist
 
- [x] I have updated to the latest available Home Assistant version.
- [x]  I have cleared the cache of my browser.
- [x]  I have tried a different browser to see if it is related to my browser.

### The problem

- Create an automation based on a blueprint with a boolean selector and select save.
- Go back into the automation and change the state of the boolean selector.  No option for save appears.
- Change an additional selector so an option for save appears.  The old value of the boolean selector is preserved.

I have simplified my blueprint yaml to the minimum and attached below.  This minimised yaml also causes the behaviour that I am observing.

### What version of Home Assistant Core has the issue?

2022.4.1 (first observed the problem), still exists with 2022.7.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Blueprint, Automation

### Link to integration documentation on our website

https://www.home-assistant.io/docs/blueprint/selectors/

### Example YAML snippet

```yaml
blueprint:
  name: Boolean Selector Test
  description: Boolean Selector Test
  domain: automation

  input:
    active_only_at_night:
      name: Active at night
      description: The automation only works at night.
      default: false
      selector:
        boolean:

mode: single
max_exceeded: silent

trigger: []
condition: []
action: []
```

**Comment by erkr** [comment]
I ran into the same issue. But it's even worse:

- It already fails during the creation of an automation! 

My example is:
```
    my_boolean:
      name: my example boolean
      description: my example boolean 
      default: true
      selector:
        boolean: {}
```
When I create a new automation, and change this boolean to false, the safe button pops up (so far so good).  
Then I press the safe button and look in the yaml. It is saved as true (the default), not false !!!
