### ISSUE TITLE
Can't navigate to dashboard views with non-standard characters in the path

### ISSUE THREAD

**Issue by joshwisely** [home-assistant/frontend#12290]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Dashboards have issues non-standard characters in the path such as `é`. When you try to navigate to a view that has such a character you are instead taken to a different view. Same goes for it you try to edit the view. Awkwardly if you do edit something, you end up editing the wrong view and overwriting changes in the wrong place.

### Describe the behavior you expected

The dashboard should have navigated to the proper page.

### Steps to reproduce the issue

1. Create a new dashboard named `Test`.
2. Set the dashboard code to this:
```
views:
  - title: Working
    path: working
    cards:
      - type: markdown
        content: This is the **Working** view.
  - title: Broken
    path: brokén
    cards:
      - type: markdown
        content: This is the **Broken** view.
```
3. Try to navigate to the view named `Broken` and note that you are instead sent to the view named `Working`.
4. Edit the dashboard code to this (all that's changing is the `é` is being replaced with an `e` in the path:
views:
  - title: Working
    path: working
    cards:
      - type: markdown
        content: This is the **Working** view.
  - title: Broken
    path: broken
    cards:
      - type: markdown
        content: This is the **Broken** view.
5. Try to navigate to the view named `Broken` and note that it now works.

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.75

### Which operating system are you using to run this browser?

Linux Mint (20.3)
