### ISSUE TITLE
Can't pick entities from non-config entries filtered by integration

### ISSUE THREAD

**Issue by emontnemery** [home-assistant/frontend#12315]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It's not possible to pick entities from non-config entries filtered by integration 

Step-by-step reproduction:
1. Setup a super cool utility_meter in configuration.yaml:
```yaml
utility_meter:                 
  super_cool:                  
    source: sensor.today_energy
    tariffs:                   
      - peak                   
      - offpeak                
```

2. Try to pick the super cool utility meter in the developer tool for utility meter's calibrate service:
![image](https://user-images.githubusercontent.com/14281572/162980124-b2f0fd9a-f377-4c97-9393-c3f4d59e57f5.png)

### Describe the behavior you expected

It should be possible to select `select.super_cool` according to the step-by-step instruction below

### Steps to reproduce the issue

1. Setup a super cool utility_meter in configuration.yaml:
```yaml
utility_meter:                 
  super_cool:                  
    source: sensor.today_energy
    tariffs:                   
      - peak                   
      - offpeak                
```

2. Try to pick the super cool utility meter in the developer tool for utility meter's calibrate service:
![image](https://user-images.githubusercontent.com/14281572/162980124-b2f0fd9a-f377-4c97-9393-c3f4d59e57f5.png)

3. 😢 

### What version of Home Assistant Core has the issue?

2022.4
