### ISSUE TITLE
Missing part of history-graph after restart HA

### ISSUE THREAD

**Issue by mamo-nick** [home-assistant/frontend#12321]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I heve newest version (2002.4.3). After restar history-graph shows only part of graph.

### Describe the behavior you expected

Graph shows graph of asked time (24 h).

### Steps to reproduce the issue

1. Setup history graph 24 h
2. After e.g. 26 h restart HA
3.
...

### What version of Home Assistant Core has the issue?

core-2022.4.3

### What was the last working version of Home Assistant Core?

core-2022.3

### In which browser are you experiencing the issue with?

Google chrome 100.0.4896.60

### Which operating system are you using to run this browser?

Win 10, Android 

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: switch.podlahovka_lenka_loznice
    name: Lenka
  - entity: switch.podlahovka_martin_pracovna
    name: Martin
  - entity: switch.podlahovka_satna
    name: Šatna
  - entity: switch.podlahovka_koupelna
    name: Koupelna
  - entity: switch.sonoff_th10_prepinac
    name: Čerpadlo
hours_to_show: 24
refresh_interval: 0
```

### Additional information

I have 2 similar history-graphs, they have same issue
![2022-04-13_12-12-44](https://user-images.githubusercontent.com/65286339/163175120-5ec78c7e-ea91-4dc8-bcad-7ba9ac2df58a.png)
