### ISSUE TITLE
Exceptional (!) shown when it's (a sunny) day

### ISSUE THREAD

**Issue by thomaskilian** [home-assistant/frontend#12349]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have connected a Somfy Weather station and added it to my config as

```
  weather:                         
    - name: "Home sensor"
      address_temperature: "6/1/11"
      address_brightness_south: "6/1/8"
      address_brightness_west: "6/1/9"
      address_brightness_east: "6/1/7"
      address_wind_speed: "6/1/10"    
      address_rain_alarm: "6/1/2"
      address_frost_alarm: "6/1/14"   
                      
      address_day_night: "6/2/1"            
      #address_day_night: "6/1/3"
      # day night is reversed ?!              
      sync_state: true
```
                                    
That partially works but there is an issue during daytime. First I thought that the day/night switch is required, but that seems to be related to a rendering issue. Second I noticed that none of the other parameters are shown, only wind and temperature (don't care too much). 
<img width="401" alt="pic20220418203622" src="https://user-images.githubusercontent.com/69296/163857276-83ebbd95-59e4-4821-bdb4-835e8c58c00e.png">

Right now it's evening (and I was wating for that) the rendering is fine:

<img width="399" alt="pic20220418203236" src="https://user-images.githubusercontent.com/69296/163856727-28c36685-7334-4318-9da0-dd77009485fe.png">

But during daytime it shows

![BxkkpyzixXuzQh2b](https://user-images.githubusercontent.com/69296/163856963-788b03d8-0da1-4feb-b487-31937b1cc82b.png)

(the temperature to the right is shown correctly, but I have only this screenshot; a new one only tomorrow).

### Describe the behavior you expected

I would of course except that it shows Daytime and not Exceptional.

### Steps to reproduce the issue

I would guess you just need to poll a binary for the night/day property that is not zero and it will show that Exceptional (at least that's what I did for testing).

### What version of Home Assistant Core has the issue?

2022.4.5

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

any
