### ISSUE TITLE
Map is updated to frequently and zoom level reset

### ISSUE THREAD

**Issue by bratanon** [home-assistant/frontend#12357]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Its almost impossible for me to zoom in on the map, as it now seems to update super frequently, and when its updated, the zoom is reset to default again. 

### Describe the behavior you expected

When the map is updated, the current zoom level should not be changed.

### Steps to reproduce the issue

1. Track an entity on the move, so its long/lat are updated frequently.
2. Navigate to the map
3. zoom in, or out, and wait for the map to update. The zoom level will change to some default one again on update.

### What version of Home Assistant Core has the issue?

core-2022.4.5

### In which browser are you experiencing the issue with?

Google chome 100.0.4896.88, Firefox 99.0.1

### Which operating system are you using to run this browser?

ubuntu 21.10

**Comment by ildar170975** [comment]
What entity is displayed on the map?
Is it a `person` entity?
Do you use Custom UI for the `person` entity?

**Comment by bratanon** [comment]
2 persons, and 2 sensors from the android app showing geocoded locations

**Comment by ildar170975** [comment]
So, no Custom UI is used?
Try to exclude that "2 sensors" from the map and see what happens.

**Comment by bratanon** [comment]
There is no way to exlude them. All states which has either long/lat is displayed.

**Comment by Mariusthvdb** [comment]
not using the Map as default integration myself (so no left side menu Map), but you could also use a Map as panel, and set any entity you desire:
```
- title: Map
  icon: mdi:map
  type: panel
  cards:
    - type: map
      entities:
        - person.1
        - person.2
        - person.3
        - person.4
        - sensor.m_location
      hours_to_show: 48
```
