### ISSUE TITLE
Energy cards don't show titles

### ISSUE THREAD

**Issue by jherby2k** [home-assistant/frontend#12364]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created a custom energy view using the built-in energy cards. This works well enough except for some reason the titles on each card aren't showing

### Describe the behavior you expected

Should look like the screenshots at https://www.home-assistant.io/dashboards/energy/

### Steps to reproduce the issue

1. Create a new dashboard using the provided yaml

### What version of Home Assistant Core has the issue?

core-2022.4.5

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Chrome, Edge, Fully Kiosk

### Which operating system are you using to run this browser?

Windows 11, Android, FireOS

### Problem-relevant frontend configuration

```yaml
- type: sidebar
    title: Energy
    path: energy
    badges: []
    cards:
      - type: energy-date-selection
        view_layout:
          position: sidebar
      - type: energy-usage-graph
      - type: energy-solar-graph
      - type: energy-gas-graph
      - type: energy-devices-graph
      - type: energy-distribution
        view_layout:
          position: sidebar
      - type: energy-grid-neutrality-gauge
        view_layout:
          position: sidebar
      - type: energy-solar-consumed-gauge
        view_layout:
          position: sidebar
      - type: energy-carbon-consumed-gauge
        view_layout:
          position: sidebar
```

### Additional information

![image](https://user-images.githubusercontent.com/9419251/164291934-f4b782e0-b8e7-405f-afb9-c63bc672b090.png)
