### ISSUE TITLE
Gap in stack cards, when using conditional card and condition is false

### ISSUE THREAD

**Issue by emufan** [home-assistant/frontend#12374]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you are using a conditional card in side a vertical-stack or horizontal-stack card and if it placed at first or last position, the stack cards adds/shows nevertheless the space before/after the first/last visible card if the condition is false.

This picture shows two cards. First, a 3-card-stack without any conditions. Second, a 3-card-stack with first cards is condition-true. Every gap is of course equal.

![image](https://user-images.githubusercontent.com/22775515/164463087-945e7ddf-04b5-4c0e-b499-4d686ca1dafe.png)

This picture shows two cards. First, a 3-card-stack without any conditions. Second, a 3-card-stack with first cards is condition-false. There is still the gap, as the card would be condition true.

![image](https://user-images.githubusercontent.com/22775515/164462790-5765fcc7-532c-4091-b36b-6be59350b1cf.png)

If placed between cards, there is no additional gap in these cases.

Same is happening 1:1 with horizontal-stack.

### Describe the behavior you expected

There should not be a displayed space if there is a condition false card in placem it has to be handled as there would be no card.

### Steps to reproduce the issue

```
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: sensor.thermometer_aussen_minimum
          - type: entities
            entities:
              - entity: sensor.thermometer_aussen_minimum
          - type: entities
            entities:
              - entity: sensor.thermometer_aussen_minimum
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: sensor.abfallkalender_gelbetonne_date
                state: '1'
            card:
              type: entities
              entities:
                - entity: sensor.thermometer_aussen_maximum
          - type: entities
            entities:
              - entity: sensor.thermometer_aussen_minimum
          - type: entities
            entities:
              - entity: sensor.thermometer_aussen_minimum
```

### What version of Home Assistant Core has the issue?

core-2022.4.6

### In which browser are you experiencing the issue with?

Chrome, Vivaldi, etc.

### Which operating system are you using to run this browser?

all
