### ISSUE TITLE
first tab in a Dashboard has incorrect path

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12373]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

and only uses the dashboard path, not using the path name in the view

though revealed in a custom:button-card, this is in fact a frontend issue, as can be seen in the inspector console

somehow this is slowing down the frontend tremendously too.  turning the `input_boolean.show_browser_path` off to not show the path immediately fixes it

using yaml mode

### Describe the behavior you expected

always respect the full path, as is set in the dashboard config:

```
title: Home
icon: mdi:home
path: home
```

and dashboard setting:

```
views:
  - !include ui-overview/view_overview_Home.yaml            #0
  - !include ui-overview/view_overview_Lights.yaml          #1
  - !include ui-overview/view_overview_Covers.yaml          #2
  - !include ui-overview/view_overview_Home_summary.yaml    #3
  - !include ui-overview/view_overview_Intercom.yaml        #4
etc etc
```
or 
```
views:
  - !include ui-data/view_data_Energy.yaml              #0
  - !include ui-data/view_data_Solar.yaml               #1
  - !include ui-data/view_data_Water.yaml               #2
  - !include ui-data/view_data_Climate.yaml             #3
etcetc

```
<img width="1089" alt="Schermafbeelding 2022-04-21 om 14 24 31" src="https://user-images.githubusercontent.com/33354141/164457439-044ebc8f-682f-4064-ae48-fb79cbcf084c.png">

### Steps to reproduce the issue

1. openinspectior in Chrome and enter window.location.pathname 
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.5.0.dev20220421

### In which browser are you experiencing the issue with?

Chrome Versie 100.0.4896.127 (Officiële build) (x86_64)
Safari

### Which operating system are you using to run this browser?

macOs  Monterey 12.3.1

### Problem-relevant frontend configuration

discovered because this conditional button suddenly throws an error:
```yaml

type: custom:state-switch
entity: input_boolean.show_browser_path
states:
  'on':
    type: custom:button-card
    template: button_header
    variables:
      view: >
        [[[ return window.location.pathname.split('/')[2]; ]]]
    name: >
      [[[ function capitalizeFirstLetter(string) {
            return string.charAt(0).toUpperCase() + string.slice(1);
          }
          return capitalizeFirstLetter(variables.view.replace('_',' ')); ]]]
```

### Additional information

function of button is to show the path:
<img width="908" alt="Schermafbeelding 2022-04-21 om 14 07 13" src="https://user-images.githubusercontent.com/33354141/164455133-9b064769-021a-4501-8ce2-73be88742eb1.png">

but on first tab shows:

<img width="893" alt="Schermafbeelding 2022-04-21 om 14 07 28" src="https://user-images.githubusercontent.com/33354141/164455195-7ba14eb6-ed10-41cb-ac61-305b52109d2b.png">

because:

<img width="311" alt="Schermafbeelding 2022-04-21 om 13 54 05" src="https://user-images.githubusercontent.com/33354141/164455317-8e548645-a38c-43f3-9351-68e8e588d2c6.png">

or:

<img width="264" alt="Schermafbeelding 2022-04-21 om 14 11 51" src="https://user-images.githubusercontent.com/33354141/164455441-6bb9e351-f099-43eb-9f8e-bb3a585cbc79.png">

while that has set path:

```
title: Develop
path: develop
icon: mdi:remote-desktop
```

could this be related to: https://github.com/home-assistant/frontend/pull/12310, since its the only frontend PR concerning Path, and before this wasnt happening?
