### ISSUE TITLE
conditional card still being evaluated when condition is not true

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12395]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Thie https://github.com/home-assistant/frontend/issues/12373 made me discover that even when a (custom) card is not displayed, because of a conditional, (either core conditional or eg custom state-switch), the logic in that card is still evaluated, and can cause errors.

guess the issue is, it shouldn't evaluate but it does.

### Describe the behavior you expected

no evaluation of a card when the condition in the conditional isnt evaluated to true

### Steps to reproduce the issue

1. create conditional
2.  condition = off
3. card with logic the doesnt apply throws error in Inspector console
...

### What version of Home Assistant Core has the issue?

2022.5.0.dev20220423

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOs  Monterey 12.3.1

### Problem-relevant frontend configuration

```yaml
#type: custom:state-switch
#entity: input_boolean.show_browser_path
#states:
#  'on':
type: conditional
conditions:
  - entity: input_boolean.show_browser_path
    state: 'on'
card:
    type: custom:button-card
    template: button_header
    variables:
      view: >
        [[[ return window.location.pathname.split('/')[2].replace('_',' '); ]]]
    name: >
      [[[ function capitalizeFirstLetter(string) {
            return string.charAt(0).toUpperCase() + string.slice(1);
          }
          return capitalizeFirstLetter(variables.view); ]]]
```

### Additional information

this was noticed because of the error in the Dashboard paths, which now will be repaired. However, that doesnt take away the underlying reason, of a card still being evaluated, even when it shouldn't.
