### ISSUE TITLE
Relative positioning is not being applied correctly causing device specific and hence messed up display

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/frontend#12404]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I noticed that the layout looks quite different in my browser compared to the companion app. So it seems that the layout is not being applied correclty even though I am specifying everything in relative values (%) rather than absolute (px).

Browser Editor Preview:
![c9f8f04d7d3214c7323e370305b577bd8ec67bed](https://user-images.githubusercontent.com/57034871/165096905-988fe5da-2fa2-4718-b94b-e5636adc0438.png)

Browser dashboard after saving:
![38403e9538f934f1ed9d9b6c246e7a3802b1dd61](https://user-images.githubusercontent.com/57034871/165096927-aabfda10-4ba8-4e39-be33-730b4f86353a.png)

Companion app:
![110628ca140f0fef811edf2a2b243fad37d9cf6b_2_690x95](https://user-images.githubusercontent.com/57034871/165096949-45823605-9638-4646-b7d5-f10712830dd9.jpeg)

Code:
```
type: picture-elements
elements:
  - type: image
    image: /local/images/black_50.png
    style:
      bottom: 0%
      left: 0%
      width: 100%
      height: 15%
      transform: none
      background-color: rgba(0, 0, 0, 0.0)
    tap_action:
      action: navigate
      navigation_path: /lovelace-home/persons
    hold_action:
      action: none
  - type: state-icon
    entity: light.ambient_light_lr
    icon: mdi:ceiling-light-outline
    tap_action:
      action: toggle
    style:
      bottom: 0%
      right: 5%
      transform: none
      '--paper-item-icon-color': white
      border-radius: 5px
  - type: state-icon
    entity: light.main_light_lr
    icon: mdi:ceiling-light
    style:
      bottom: 0%
      right: 20%
      transform: none
      '--paper-item-icon-color': white
      border-radius: 5px
    tap_action:
      action: toggle
  - type: custom:slider-entity-row
    entity: climate.eq_3_living_room
    name: Living Room
    full_row: true
    min: 4.5
    max: 23
    step: 0.5
    hide_state: false
    style:
      bottom: 0%
      left: 10%
      transform: none
      '--paper-item-icon-color': white
      border-radius: 5px
  - type: state-label
    entity: sensor.eq_3_battery_living_room
    prefix: (
    suffix: )
    style:
      bottom: 0%
      left: 44%
      transform: none
      color: black
      font-weight: bold
      text-transform: lowercase
      text-shadow: 1px 1px 1px white
      opacity: 50%
      border-radius: 5px
image: /local/images/living_room_16_9.jpg
```

### Describe the behavior you expected

If all positions are defined relatively, i.e. in percent rather than pixels, the position of each element should be the same on every device (i.e. independent of device resolution).

### Steps to reproduce the issue

Create picture elements card and create something similar to code example above. Then view the card on e.g. Windows 10 PC, Android phone and iPhone companion apps.

### What version of Home Assistant Core has the issue?

2022.4.7

### In which browser are you experiencing the issue with?

Chrome, Android companion app, Edge

### Which operating system are you using to run this browser?

Windows 10 & Android
