### ISSUE TITLE
Statistics: can not edit unit in UI, even though unique id is set

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12411]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

we can set an icon, and edit name etc in the UI

<img width="402" alt="Schermafbeelding 2022-04-25 om 17 48 48" src="https://user-images.githubusercontent.com/33354141/165125756-f164c66a-c53f-4aa3-9d2a-401b2a3d92b3.png">

but can not change/set the unit and have to use customize:

```
    sensor.temp_living_statistics:
      unit_of_measurement: °C
# via UI
#      icon: mdi:homethermometer

    sensor.humid_living_statistics:
      unit_of_measurement: '%'
# via UI
#      icon: mdi:water-percent

    sensor.co2_living_statistics:
      unit_of_measurement: 'ppm'
# via UI
#      icon: mdi:molecule-co2

```

### Describe the behavior you expected

allow UI setting of unit

### Steps to reproduce the issue

1. create statistics entity
2. edit
...

### What version of Home Assistant Core has the issue?

 2022.5.0.dev20220425

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOs  Monterey 12.3.1

### State of relevant entities

```txt
state_class: measurement
buffer_usage_ratio: 1
source_value_valid: true
unit_of_measurement: ppm
icon: mdi:molecule-co2
friendly_name: CO2 living statistics
```

### Additional information

```
sensor:

  - platform: statistics
    unique_id: temp_living_statistics
    entity_id: sensor.temperatuur_living
    name: Temp living statistics
    state_characteristic: mean

  - platform: statistics
    unique_id: humid_living_statistics
    entity_id: sensor.luchtvochtigheid_living
    name: Humid living statistics
    state_characteristic: mean

  - platform: statistics
    unique_id: co2_living_statistics
    entity_id: sensor.co2_living
    name: CO2 living statistics
    state_characteristic: mean
```

<img width="613" alt="Schermafbeelding 2022-04-25 om 17 53 43" src="https://user-images.githubusercontent.com/33354141/165126658-37aab136-98ac-4e73-a842-1469173da63f.png">
