### ISSUE TITLE
Problem with the position/alignment for the icons and pictures in Lovelace Picture-Elements

### ISSUE THREAD

**Issue by Photelegy** [home-assistant/frontend#12434]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi everyone,
I’m pretty new to HomeAssistant.
I wanted to make a little homeplan with my lights and the map of my vacuum-cleaner via Lovelace Picture-Elements.
My Problem is, that the icons and picture changes it’s size or position depending on the size of the used display.
On the Computer (in the Browser) it looks different than on my smartphone. And even in the card-configuration-editor it looks a bit different then when I close the editor.
How can I correct this problem? Is there a way with “transform” or so to correct this?

(I also tried with width: 116% except of transform: scale(0.8) but it didn't really help.)

Thank you very much for your ideas!

```
type: picture-elements
elements:
  - type: state-label
    entity: sensor.openweathermap_temperature
    title: test
    style:
      top: 4%
      left: 1%
      color: blue
      transform: scale(0.8)
  - type: state-label
    entity: sensor.gersau_temperature
    title: test
    style:
      top: 9%
      left: 1%
      color: green
      transform: scale(0.8)
  - type: state-icon
    entity: light.eingang
    style:
      top: 13%
      left: 36.3%
      transform: scale(1,-1)
  - type: state-icon
    entity: sensor.sensor_motion_eingang_temperature
    style:
      top: 25.5%
      left: 36.3%
      transform: scale(0.6,0.7)
  - type: state-label
    entity: sensor.sensor_motion_eingang_temperature
    style:
      top: 22%
      left: 31%
      color: red
      transform: scale(0.6)
  - type: state-label
    entity: sensor.sensor_motion_eingang_light_level
    style:
      top: 18%
      right: 51.3%
      color: blue
      transform: scale(0.4)
  - type: state-icon
    entity: light.light_kuche_oben
    style:
      top: 49%
      left: 24.3%
      transform: scale(1.2,-1.2)
  - type: state-icon
    entity: vacuum.xiaomi_vacuum_cleaner_2
    style:
      top: 57.6%
      left: 15.8%
      transform: scale(0.6)
  - type: state-icon
    entity: light.esstisch
    icon: mdi:square
    style:
      top: 49%
      left: 42.2%
      transform: scale(0.8,2)
  - type: state-icon
    entity: light.stube_oben
    style:
      top: 46%
      left: 63.0%
      transform: scale(1,1)
  - type: state-icon
    entity: light.schlafzimmer_marcel
    style:
      top: 75%
      left: 24.2%
      transform: scale(1,-1)
  - type: state-icon
    entity: light.schlafzimmer_barbara
    style:
      top: 75%
      left: 60.2%
      transform: scale(1,-1)
  - type: state-icon
    entity: media_player.mini_marcel
    style:
      top: 86.9%
      left: 26.9%
      transform: scale(0.5,0.5)
  - type: state-icon
    entity: media_player.mini_barbara
    style:
      top: 66%
      left: 69%
      transform: scale(0.5,0.5)
  - type: state-icon
    entity: media_player.wohnzimmerpaar
    style:
      top: 59%
      left: 46%
      transform: scale(0.5,0.5)
  - type: icon
    icon: mdi:home-roof
    hold_action:
      action: navigate
      navigation_path: /lovelace-zimmer/galerie/
    style:
      top: 15%
      left: 61%
      transform: scale(4)
      color: grey
  - type: custom:xiaomi-vacuum-map-card
    entity: vacuum.xiaomi_vacuum_cleaner_2
    calibration_points: null
    camera_calibration: true
    map_camera: camera.xiaomi_cloud_map_extractor
    hold_action:
      action: vacuum.xiaomi_vacuum_cleaner_2
    style:
      left: 14.9%
      top: 23.8%
      transform: scale(1.76)
      opacity: 30%
image: /local/homeplan/HomePlan3OG_Wohnung.png
```
![Screenshot_alignmentError](https://user-images.githubusercontent.com/61714583/165292892-fe64e3b3-f456-4ccb-8338-65694929171d.jpeg)

### Describe the behavior you expected

The expected behavior would be that the alignment of the different elements (text, symbols, pictures) should be equally placed no matter if it's in a browser, bigger/smaller display or Companion App.

### Steps to reproduce the issue

1. Make a lovelace-card with `type: picture-elements`
2. Make multiple elements with different scale and try to align them.
3. Show how it looks on different displays, browser sizes, smartphones, ...

### What version of Home Assistant Core has the issue?

core-2022.4.7

### In which browser are you experiencing the issue with?

Google Chrome, Companion App, Edge

### Which operating system are you using to run this browser?

Windows 10 (for Browser), Android 12 (for Companion App)
