### ISSUE TITLE
Button Visual Editor Creating wrong yaml code

### ISSUE THREAD

**Issue by TheIlluminate92** [home-assistant/frontend#12526]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the visual editor to create a service call button it creates the following:
```type: button
tap_action:
  action: call-service
  service: climate.set_temperature
  service_data:
    temperature: 72
  target:
    device_id: climate.upstairs_thermostat
show_icon: false
name: '72'
```

The correct format should: 
```type: button
tap_action:
  action: call-service
  service: climate.set_temperature
  service_data:
    temperature: 72
    entity_id: climate.upstairs_thermostat
show_icon: false
name: '72'
```

Is basically not using the correct format for the entity ID.  Which causes a "Failed to call service climate/set_temperature. must contain at least one of entity_id, device_id, area_id." Error. 

### Describe the behavior you expected

Click button, calls the service and performs the action. 

### Steps to reproduce the issue

1. Use visual editor to create a service call button
2. Try and use button
3. Get error 
...

### What version of Home Assistant Core has the issue?

2022.4.7

### What was the last working version of Home Assistant Core?

2022.4.6

**Comment by spacegaier** [comment]
I cannot reproduce the issue in the current dev version. This is what I get (which works perfectly fine):
```
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: climate.set_temperature
  service_data:
    temperature: 22
  target:
    entity_id: climate.bedroom
name: Climate Test
icon: mdi:ab-testing
```

However, your reproduction steps are a bit vague. I assume you are talking about a "Button" card, but you might also mean a button row in an "Entities" card, so not really sure...
