### ISSUE TITLE
Automations > Actions > Choose > Duplicate Feature Overwrites Data

### ISSUE THREAD

**Issue by SergeantPup** [home-assistant/frontend#12573]
### The problem

I've been witnessing the behavior for weeks but I assumed it was something I was doing wrong.  I finally dug into it and I'm pretty sure this is a defect.

Create an automation using the choose action and fill out all the fields.
Duplicate the entire chose action (to create a completely new choose (not a 2nd choice)
It copies correctly and all the fields are the same as you'd expect
Edit the fields of the copy as you would if you were duplicating/editing any other automation and save along the way
Scroll back up to the choose that you originally copied and all the fields will have the new edits from the copy
You're left with two identical copies after you've changed one because when you change the copy, it overwrites the original

### What version of Home Assistant Core has the issue?

core-2022.5.0b7

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automations

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/device_automation/

### Example YAML snippet

```yaml
I copied the entire yaml of the automation before I copied the choose:
alias: West Facing Blinds Auto-Close
description: ''
trigger:
  - type: illuminance
    platform: device
    device_id: fe3751edd36d0f0d41e14934a9467070
    entity_id: sensor.garage_door_trisensor_illuminance
    domain: sensor
    above: 3000
    for:
      hours: 0
      minutes: 20
      seconds: 0
  - type: illuminance
    platform: device
    device_id: fe3751edd36d0f0d41e14934a9467070
    entity_id: sensor.garage_door_trisensor_illuminance
    domain: sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
    below: 1000
condition: []
action:
  - choose:
      - conditions:
          - type: is_illuminance
            condition: device
            device_id: fe3751edd36d0f0d41e14934a9467070
            entity_id: sensor.garage_door_trisensor_illuminance
            domain: sensor
            above: 3000
          - condition: numeric_state
            entity_id: cover.media_window_1
            attribute: current_tilt_position
            above: '25'
        sequence:
          - service: cover.set_cover_tilt_position
            data:
              tilt_position: 25
            target:
              entity_id: cover.media_window_1
          - service: notify.alexa_media
            data:
              data:
                type: announce
              message: Adjusting media room blinds
              target: media_player.media_room_sonos
    default: []
mode: single


Then after the copy, you can see where everything's been jumbled and there's some ref_0/ref_1 in there:
alias: West Facing Blinds Auto-Close
description: ''
trigger:
  - type: illuminance
    platform: device
    device_id: fe3751edd36d0f0d41e14934a9467070
    entity_id: sensor.garage_door_trisensor_illuminance
    domain: sensor
    above: 3000
    for:
      hours: 0
      minutes: 20
      seconds: 0
  - type: illuminance
    platform: device
    device_id: fe3751edd36d0f0d41e14934a9467070
    entity_id: sensor.garage_door_trisensor_illuminance
    domain: sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
    below: 1000
condition: []
action:
  - choose:
      - &ref_0
        conditions:
          - type: is_illuminance
            condition: device
            device_id: fe3751edd36d0f0d41e14934a9467070
            entity_id: sensor.garage_door_trisensor_illuminance
            domain: sensor
            below: 1000
          - condition: numeric_state
            entity_id: cover.media_window_1
            attribute: current_tilt_position
            below: '50'
          - condition: time
            before: '20:00:00'
            after: '08:00:00'
        sequence:
          - service: cover.open_cover
            data: {}
            target:
              entity_id: cover.media_window_1
          - service: notify.alexa_media
            data:
              data:
                type: announce
              message: Adjusting media room blinds
              target: media_player.media_room_sonos
    default: &ref_1 []
  - choose:
      - *ref_0
    default: *ref_1
mode: single
```

### Additional information

It's repeatable on the choose function in automations, not sure if it's been doing it on others but it's possible.  I know that I got frustrated multiple times because it seemed like my settings were getting overwritten but there's no telling what all automations this was happening in, I just know that I'm able to reproduce it with proof in the Choose function.
