### ISSUE TITLE
Calendar Card initial_view: listWeek loads w/ Sunday first instead of the current day

### ISSUE THREAD

**Issue by GitHubGoody** [home-assistant/frontend#12598]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have initial_view set to listWeek. When I open the view, listWeek loads, but it always defaults to Sunday as the first day instead of the current day. Clicking the List View icon reloads the same view with the current day as the first day. A browser reload and refresh reverts the view back to Sunday first. This behavior is consistent on desktop (Edge) and mobile (iOS HA app).

### Describe the behavior you expected

When I open a view containing a calendar with initial_view set to listWeek, the first day should be the current day.

### Steps to reproduce the issue

1. Create a calendar with initial_view set to listWeek
2. Wait until the current day is NOT Sunday to test
3. Load the view containing the calendar from (1)

### What version of Home Assistant Core has the issue?

2022.5.0

### In which browser are you experiencing the issue with?

Edge and HA iOS app

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
cards:
      - type: calendar
        title: Family Calendar
        entities:
          - calendar.calendar1
          - calendar.calendar2
        initial_view: listWeek
```
