### ISSUE TITLE
Automation visual editor for "Time" condition forces both Before and After conditions and silently adds them

### ISSUE THREAD

**Issue by FalconFour** [home-assistant/frontend#12607]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing or creating an automation using the "Time" condition -- for example, "Condition: Time, After: Value of a date/time helper named TierTime" -- the editor also has options for "After" time. The problem is, the UI for these options does not have a way to select one, the other, or both "After" and "Before" options -- and if you edited the YAML to produce the desired (valid) condition of only "after", the editor will silently and automatically add the "before" value of 00:00:00.

![image](https://user-images.githubusercontent.com/2126952/167084277-d4162b8d-b1c4-4768-b4f6-e170b22ad0dc.png)
![image](https://user-images.githubusercontent.com/2126952/167084311-2a65499b-6834-4a34-985a-1abfa9a4486f.png)
![image](https://user-images.githubusercontent.com/2126952/167084361-49bcbf7c-82bf-4922-bbce-f9e9ac69295e.png)

### Describe the behavior you expected

The "before" and "after" settings should be selectable - for example, a checkbox that I'd like to enable the "before" or "after" condition, and then it will add that line to the script.

Alternatively, at bare minimum, don't perform changes to the script unless I actually interacted with that function block in some way.

### Steps to reproduce the issue

1. Create an automation that uses the "Time" condition, but only one of "before" or "after"; go into YAML and delete the unwanted line, and save.
2. Exit the editor and go back to editing the automation - defaults to visual editor which silently adds the line; go to YAML again.
3. Observe that the unwanted condition line (either "before" or "after") was added back with a default value of 00:00:00

### What version of Home Assistant Core has the issue?

2022.5.1

### In which browser are you experiencing the issue with?

Edge 101.0.1210.32 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 21H2

### State of relevant entities

```txt
input_datetime.tiertime
Value: 00:20:07
has_date: false
has_time: true
editable: true
hour: 0
minute: 20
second: 7
timestamp: 1207
icon: mdi:battery-clock-outline
friendly_name: TierTime
```

### Problem-relevant frontend configuration

```yaml
alias: Inverter Down Tier 2
description: ''
trigger:
  - platform: event
    event_type: INV_DOWN_TIER_2
condition:
  - condition: and
    conditions:
      - condition: device
        type: is_on
        device_id: 12bf71c48991ce9af8d997974dd376c4
        entity_id: switch.inverter_1000w_84f3eb64446c_switch_relay_1
        domain: switch
        for:
          hours: 0
          minutes: 2
          seconds: 0
      - type: is_power
        condition: device
        device_id: 7e74f026a240df048bfb4773e2d34650
        entity_id: sensor.none_123_1min
        domain: sensor
        below: 0
      - condition: time
        after: input_datetime.tiertime
action:
  - parallel:
      - service: automation.trigger
        data: {}
        target:
          entity_id:
            - automation.holdtier
            - automation.inverter_1000w_cooldown
      - type: turn_on
        device_id: 0ffabc49770391117fc5979069aa222a
        entity_id: switch.inverter_600w_84f3eb64475d_switch_relay_1
        domain: switch
mode: parallel
```
