### ISSUE TITLE
Blueprint entity and open text screens are formatted bad in script build screens.

### ISSUE THREAD

**Issue by SirGoodenough** [home-assistant/frontend#12627]
### The problem

There does not seem to be a set column width for the description of Entities and open text, possibly others on the script builder for blueprints.

If the description is long, the entity field is not usable leaving only 2 characters visible.  The open text input field leaves NO visible characters so you have to type the value in blind.

The values pick and the field is functioning, however you cannot see what you are entering.

I have verified if I remove the description, the field looks normal and is usable.

### What version of Home Assistant Core has the issue?

Home Assistant Core 2022.5.2

### What was the last working version of Home Assistant Core?

Home Assistant Core 2022.4.0 I think worked.

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

blueprint forscripts, possibly the script ui editor.

### Link to integration documentation on our website

https://www.home-assistant.io/docs/blueprint/schema/

### Diagnostics information

No Log Entries,error is visual interface problem.
Here is my systen information:
## System Health

version | core-2022.5.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.0-13-amd64
arch | x86_64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4502
Installed Version | 1.24.5
Stage | running
Available Repositories | 1059
Downloaded Repositories | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 22, 2023, 6:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.0
docker_version | 20.10.14
disk_total | 211.2 GB
disk_used | 89.1 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.6.1), Check Home Assistant configuration (3.10.0), SSH & Web Terminal (10.1.3), TasmoBackup (1.04.26), Duck DNS (1.14.0), Mosquitto broker (6.1.1), Remote Backup (2022.1.1), Home Assistant Google Drive Backup (0.107.1), Plex Media Server (2.8.0), Studio Code Server (5.0.2), Zigbee2mqtt (1.25.1-1), Z-Wave JS to MQTT (0.39.0), Tasmota Device Manager (2022.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 9
views | 17
mode | storage

</details>

<details><summary>Sonoff</summary>

version | 3.0.3
-- | --
cloud_online | 1 / 3
local_online | 1 / 1

</details>

### Example YAML snippet

```yaml
Can be seen when importing these 2 blueprints:
[![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2FSirGoodenough%2FHA_Blueprints%2Fblob%2Fmaster%2FScripts%2FTasmota_EZ-Buttons.yaml)

Look at  Cloud Voice Code in this one:
[![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2FSirGoodenough%2FHA_Blueprints%2Fblob%2Fmaster%2FScripts%2Ftts_All_Message_Script_Blueprint.yaml)
```

### Anything in the logs that might be useful for us?

```txt
No log errors.  Visual problem in UI only.
```

### Additional information

![Screenshot_2022-05-07_23-32-09](https://user-images.githubusercontent.com/47349533/167281964-6fbe8b75-8beb-4f45-b886-7d4b8ad7705b.png)
![Screenshot_2022-05-07_23-32-57](https://user-images.githubusercontent.com/47349533/167281965-798fae3a-f8df-442b-b7a4-58a12b5859cd.png)
![Screenshot_2022-05-07_23-34-56](https://user-images.githubusercontent.com/47349533/167281966-aeaf8822-9279-4312-8608-d7b0b9a6e24c.png)
