### ISSUE TITLE
entities in picture-glance are not centered and aligned with the title

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12731]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="497" alt="Schermafbeelding 2022-05-19 om 10 23 54" src="https://user-images.githubusercontent.com/33354141/169280997-c537d1c3-f643-486a-b59c-fb174827554c.png">

### Describe the behavior you expected

<img width="470" alt="Schermafbeelding 2022-05-19 om 13 16 15" src="https://user-images.githubusercontent.com/33354141/169281101-c10bf0c8-aee5-46b3-b29b-831eb9fa14bf.png">

### Steps to reproduce the issue

1. creatie a picture-glance with several entities
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.6.0.dev20220519

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

macOS  Monterey 12.3.1

### Problem-relevant frontend configuration

```yaml
type: picture-glance
title: Vijverpompen
image: /local/images/areas/vijver.png
state_filter:
  'off': grayscale(72%)
entity: binary_sensor.vijverpompen
entities:
  - switch.vijverpomp_links
  - switch.vijverpomp_rechts
#  - input_boolean.vijverpompen_alterneren
  - sensor.pond_buiten_sensor_temperature
  - binary_sensor.vijverpompen
```

### Additional information

using a 
```
card_mod:
  style:
    .: |
      .box ha-state-icon {
        line-height: 0px;
      }
```

fixes the vertical alignment issue. had a very intense discussion on this in https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/3176

which was resolved with the final mod above, by Arganto
