### ISSUE TITLE
History-graph broken in frontend 20220523.0 

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12767]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

after updating to dev 2022.6.0.dev20220524 all history-graph cards are broken.

### Describe the behavior you expected

show history data

### Steps to reproduce the issue

1. type: history-graph
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.6.0.dev20220524

### What was the last working version of Home Assistant Core?

2022.6.0.dev20220523

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS  Monterey 12.3.1

### Problem-relevant frontend configuration

```yaml
- type: custom:hui-element
        card_type: history-graph
        entities:
          - entity: sensor.co2_living_statistics
            name: Co2
          - entity: sensor.temp_living_statistics
            name: Temp Living
          - entity: sensor.humid_living_statistics
            name: Vocht
          - entity: sensor.schimmel_sensor
            name: Schimmel
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

<img width="488" alt="Schermafbeelding 2022-05-24 om 22 53 46" src="https://user-images.githubusercontent.com/33354141/170130378-565373fb-3cfe-49d8-a46f-aa6fc310b4e0.png">

all entities do have their history logged, as can be seen by clicking on the individual entity, or, by adding them in a logbook card

<img width="397" alt="Schermafbeelding 2022-05-24 om 22 57 16" src="https://user-images.githubusercontent.com/33354141/170130957-8db59574-de9a-47c2-9674-4139d2128cbe.png">

or the statistics-graph card for the exact same entities:

<img width="503" alt="Schermafbeelding 2022-05-24 om 22 58 21" src="https://user-images.githubusercontent.com/33354141/170131284-37f38683-9281-4d7c-ab4b-c8d0edc661a1.png">
