### ISSUE TITLE
input_number decimal separator not localized in Firefox

### ISSUE THREAD

**Issue by breti** [home-assistant/frontend#12803]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the German language, the comma "," is used as a decimal separator. When displaying Sensor entities, this works correctly in all browsers, but for input_number entities, Firefox displays the dot "." as the decimal separator, while Chrome correctly displays the comma ",".

![grafik](https://user-images.githubusercontent.com/3628895/170548695-fbccef9f-d7fc-4ce5-a010-83e73fa79ba7.png)
Firefox

![grafik](https://user-images.githubusercontent.com/3628895/170548996-bde37793-8a3f-46af-9c43-a45aaf0b13ac.png)
Chrome

### Describe the behavior you expected

I'd expect to see the comma "," used as a decimal separator in all browsers.

### Steps to reproduce the issue

Just add a input_number entity to an entities card.

### What version of Home Assistant Core has the issue?

core-2022.5.5

### In which browser are you experiencing the issue with?

Firefox 100.0.2 (64-Bit)

### Which operating system are you using to run this browser?

Windows 10, Windows 11, Android 11

### State of relevant entities

```txt
input_number.te_gaswaage_fullmenge: 8.0
sensor.te_gaswaage_batteriespannung: 3.25
sensor.te_gaswaage_gewicht: 10786
```

### Problem-relevant frontend configuration

```yaml
views:
  - title: Home
    cards:
      - type: entities
        entities:
          - entity: sensor.te_gaswaage_batteriespannung
          - entity: sensor.te_gaswaage_gewicht
          - entity: input_number.te_gaswaage_fullmenge
        title: Decimal separator Test
        show_header_toggle: false
```
