### ISSUE TITLE
history-graph - mess with sensors with & w/out units

### ISSUE THREAD

**Issue by Masterz69** [home-assistant/frontend#12848]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Continued from #10234.

![image](https://user-images.githubusercontent.com/15225823/171601768-0fd43a12-703a-4d17-93f5-914c8700df29.png)

After upgrade to 2022.6.0 history-graph become even worse looking.
Sensors w/out units graph boundaries even more disrespect sensors with units in same card.

### Describe the behavior you expected

![image](https://user-images.githubusercontent.com/15225823/171603174-6b6efd21-a1c9-4faf-883e-bda1fa295e2f.png)

X-axis boundaries must match, IMHO - arrows on picture.

### Steps to reproduce the issue

No actual steps, just HA Core upgrade happens.

### What version of Home Assistant Core has the issue?

core-2022.6.0

### What was the last working version of Home Assistant Core?

core-2002.5.4

### In which browser are you experiencing the issue with?

Chrome, Edge

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
- type: history-graph
            entities:
              - entity: binary_sensor.boiler_ht_pump_on
                name: Heat
              - entity: binary_sensor.boiler_hw_pump_on
                name: HWater
              - entity: sensor.sns_boiler_out
                name: Out
              - entity: sensor.sns_boiler_heating
                name: Heat
              - entity: sensor.sns_boiler_ret
                name: Ret
```
