### ISSUE TITLE
statistics-graph card ignores the days_to_show parameter

### ISSUE THREAD

**Issue by lmagyar** [home-assistant/frontend#12847]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The time horizon displayed got independent from the `days_to_show` parameter.

![image](https://user-images.githubusercontent.com/5061219/171565892-b7649432-b62c-49b4-add1-795fc6d07bd0.png)

### Describe the behavior you expected

Display only the specified time, as it worked previously.

### Steps to reproduce the issue

Set `days_to_show ` to any value, it is ignored.

### What version of Home Assistant Core has the issue?

2022.6.0

### What was the last working version of Home Assistant Core?

2022.5.x

### In which browser are you experiencing the issue with?

any (IE, FF, Chrome Win and Android)

### Which operating system are you using to run this browser?

Android 8.0.0, Win 7

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: statistics-graph
    title: 30 days
    chart_type: line
    period: hour
    days_to_show: 30
    entities:
      - entity: sensor.living_room_temperature_average_for_heater
        name: Temperature
      - entity: sensor.living_room_humidity_average_for_dehumidifier
        name: Humidity
      - entity: sensor.terrace_temperature_average
        name: Temperature›
      - entity: sensor.terrace_humidity_average
        name: Humidity›
    stat_types:
      - mean
  - type: statistics-graph
    title: 180 days
    chart_type: line
    period: day
    days_to_show: 180
    entities:
      - entity: sensor.living_room_temperature_average_for_heater
        name: °C
      - entity: sensor.living_room_humidity_average_for_dehumidifier
        name: '%'
      - entity: sensor.terrace_temperature_average
        name: °C›
      - entity: sensor.terrace_humidity_average
        name: '%›'
    stat_types:
      - min
      - max
      - mean
```

**Comment by bdraco** [comment]
Can you see the api call that is being sent down the websocket in the network panel when you open the inspector and force reload?

**Comment by lmagyar** [comment]
I hope this is what you asked for.

If `start_time` is calculated from `days_to_show`, this seems to be valid.

```
{
  "type": "history/statistics_during_period",
  "start_time": "2022-05-03T11:16:05.950Z",
  "statistic_ids": [
    "sensor.living_room_temperature_average_for_heater",
    "sensor.living_room_humidity_average_for_dehumidifier",
    "sensor.terrace_temperature_average",
    "sensor.terrace_humidity_average"
  ],
  "period": "hour",
  "id": 23
}
```

```
{
  "type": "history/statistics_during_period",
  "start_time": "2021-12-04T11:16:05.955Z",
  "statistic_ids": [
    "sensor.living_room_temperature_average_for_heater",
    "sensor.living_room_humidity_average_for_dehumidifier",
    "sensor.terrace_temperature_average",
    "sensor.terrace_humidity_average"
  ],
  "period": "day",
  "id": 24
}
```

**Comment by bdraco** [comment]
It looks like the datetimes are being cached incorrectly somewhere

**Comment by bdraco** [comment]
Unfortunately, I've not been able to replicate this happening.
<img width="519" alt="Screen Shot 2022-06-02 at 16 50 26" src="https://user-images.githubusercontent.com/663432/171777149-682c2410-75c0-45e7-ad2f-c451ebaf3b62.png">

**Comment by bdraco** [comment]
Can you try turning on debug logging for `sqlalchemy` and see if the query is correct on the backend?

**Comment by lmagyar** [comment]
OK, you wont believe me, but when debug is turned on, everything is OK, when turned off, it fails again!!! My assumption: one of the queries gets the other query's result from the cache!

Previously the 30 day query has got the 180 day query's result, now the 180 day query gets the 30 day's result!

My proof:

```
logger:
  default: warning
  logs:
    sqlalchemy: debug
```

ha core restart

It is perfect:

![image](https://user-images.githubusercontent.com/5061219/171835225-52aed668-b47a-440b-9f10-0e1e73d88b57.png)

Queries are OK:

```
2022-06-03 11:55:00 INFO (DbWorker_0) [sqlalchemy.engine.Engine] SELECT statistics.metadata_id, statistics.start, statistics.mean, statistics.min, statistics.max, statistics.last_reset, statistics.state, statistics.sum 
FROM statistics 
WHERE statistics.start >= %s AND statistics.metadata_id IN (%s, %s, %s, %s) ORDER BY statistics.metadata_id, statistics.start
2022-06-03 11:55:00 INFO (DbWorker_0) [sqlalchemy.engine.Engine] [cached since 91.23s ago] (datetime.datetime(2022, 5, 4, 8, 55, 3, 989000, tzinfo=datetime.timezone.utc), 5, 1, 11, 10)


2022-06-03 11:55:00 INFO (DbWorker_2) [sqlalchemy.engine.Engine] SELECT statistics.metadata_id, statistics.start, statistics.mean, statistics.min, statistics.max, statistics.last_reset, statistics.state, statistics.sum 
FROM statistics 
WHERE statistics.start >= %s AND statistics.metadata_id IN (%s, %s, %s, %s) ORDER BY statistics.metadata_id, statistics.start
2022-06-03 11:55:00 INFO (DbWorker_2) [sqlalchemy.engine.Engine] [cached since 91.23s ago] (datetime.datetime(2021, 12, 5, 8, 55, 3, 991000, tzinfo=datetime.timezone.utc), 5, 1, 11, 10)
```

I've turned off debug log, restart, and then:

![image](https://user-images.githubusercontent.com/5061219/171835429-c5e37a17-387d-4dd2-9364-58c5b0f73715.png)

And certainly there is no debug log.
