### ISSUE TITLE
history-graph: regression: wrong rendering (only half width) when more than one binary sensor is shown

### ISSUE THREAD

**Issue by prof7bit** [home-assistant/frontend#12854]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have for the purpose of testing put these 3 cards onto a dashboard:

````
      - type: history-graph
        title: Test
        hours_to_show: 12
        entities:
          - entity: binary_sensor.garage_door

      - type: history-graph
        title: Test
        hours_to_show: 12
        entities:
          - entity: binary_sensor.speisekammer
          
      - type: history-graph
        title: Test
        hours_to_show: 12
        entities:
          - entity: binary_sensor.garage_door
          - entity: binary_sensor.speisekammer
````

The first two only contain one binary sensor, the last one both of the two sensors in one card. Before the version Update to  Core 2022.6.0 I did today everything was fine. But now they render as seen in the screenshot below.

If more than one sensor is shown it will add a label on the left. This label has always been there but in previous versions it was only as wide as needed, now it is taking up half of the entire width.

Another inconsistency I just noticed: When two entities are shown it shows the state with words according to the type of sensor, in this example these are doors and it writes "Open"/"Closed" but if only one of them is visible it writes the generic "On"/"Off".

![history-graph-render-wrong](https://user-images.githubusercontent.com/1401589/171642326-f8a0eacb-79ae-44d8-ba8b-2b336f9a48ba.png)

### Describe the behavior you expected

Would have expected the label to only take as much space as needed. As it was in previous versions. This is a regression.

### Steps to reproduce the issue

1. Put cards with code like shown above on a dashboard, using binary sensors.
2. Observe the different rendering for one and multiple sensor cards, the space used for labels.

### What version of Home Assistant Core has the issue?

core-2022.6.0

### What was the last working version of Home Assistant Core?

core-2022.5.x

### In which browser are you experiencing the issue with?

Firefox, Android-App

### Which operating system are you using to run this browser?

Ubuntu, Android
