### ISSUE TITLE
Selecting template entities also adds the entity they depend on when using blueprints with selector/target

### ISSUE THREAD

**Issue by johannes-z** [home-assistant/frontend#12871]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating an automation from a blueprint, there is a bug in how the UI handles inputs with the selector type `target`. 

For example, I have two entities called: `select.office_vent` and `fan.e05_vent`. When I add `select.office_vent`, only that entity is added. If I add `fan.e05_vent` both entities are added. I also cannot remove `select.office_vent` in this case.

*`fan.e05_vent` is a template entity based on `select.office_vent`.

#### This is the blueprint I use

```yaml
blueprint:
  name: Toggle (Fan) Entity with Binary Sensor
  description: Turns an entity off or on, depending on the binary sensor state.
  domain: automation
  input:
    binary_sensor:
      name: Binary Sensor
      description: The binary sensor used to toggle the state.
      selector:
        entity:
          domain: binary_sensor
    target_entity:
      name: Target Entity
      description: The entity to be toggled by the binary sensor state.
      selector:
        target:

trigger:
  - platform: state
    entity_id: !input binary_sensor

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_off
      {% else %}
        homeassistant.turn_on
      {% endif %}
    target: !input target_entity
```

#### Automation

This the automation created, when I select `fan.office_vent` from the UI:

```yaml
- id: '1654338543958'
  alias: Test
  description: ''
  use_blueprint:
    path: _custom/vent_toggle.yaml
    input:
      target_entity:
        entity_id:
        - fan.office_vent
        - select.office_vent
      binary_sensor: binary_sensor.e05_wds_contact
```

I would then have to go into the yaml and remove the wrong entity `select.office_vent`, as I cannot remove it via the UI.

### Describe the behavior you expected

Only the entity I select should be added. I should also be able to remove the wrong entity `select.office_vent` in case both are added.

### Steps to reproduce the issue

1. Create a blueprint with my yaml.
2. Create a template entity based on another entity
3. Create an automation from the blueprint
4. Add the template entity to the target entities input.

### What version of Home Assistant Core has the issue?

2022.6.1

### In which browser are you experiencing the issue with?

Google Chrome

### Additional information

*I'm uncertain if this is a UI bug, or if it's a bug in the backend.*
