### ISSUE TITLE
Selector gets confused when different entities have the same friendly name

### ISSUE THREAD

**Issue by calisro** [home-assistant/frontend#12889]
### The problem

When searching through the logbook for debugging, if I filter on a particular entity and that entity has a group with the same name, the filtering shifts as soon as focus is moved away from the screen.  Makes for clumbsy debugging.  

For example:

I have a group of media players called:
group.all_speakers

```
  all_speakers:
    name: All Speakers
    entities:
      - media_player.front_office_speaker
      - media_player.kitchen_display
      - media_player.living_room_speaker
      - media_player.back_office_speaker
      - media_player.master_speaker
      - media_player.loft_speaker
```

and I also have an entity called:
media_player.all_speakers 
which is really a google group of speakers

If I filter on 'group.all_speakers' in the logbook, I correctly see the group.  Then I shift focus of the window, it will immediately change to the entity 'media_play.all_speakers'.

https://user-images.githubusercontent.com/5018276/172055047-68710e63-8881-42fd-9c4b-2679b9e217ec.mp4

Hope this screen capture helps recreate the issue.  I would expect the entity_id to be sticky to the filter rather than trying to swap the filter based on the friendly-name.

This happens with any domains that have the same friendly_name or the same name of hte entity after the domain.

**THis happens even in the history tab AND the developers tab (state state dialog).  It isn't JUST the logbook..  But I assume they both use the same filtering mechanism.**

### What version of Home Assistant Core has the issue?

core-2022.6.2

### What was the last working version of Home Assistant Core?

2022.5.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

logbook
