### ISSUE TITLE
history-graph: wrong graph, wrong current value

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#12896]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The cards  below contain cards for 2 binary sensors - which are supposed to be ON:
- binary_sensor.rpi_1_ping_availability_status
- binary_sensor.rpi_1_integration_availability_status

Their values are:
![image](https://user-images.githubusercontent.com/71872483/172272018-bb82a0f7-9520-461a-b11b-ead908172c22.png)
Note: last-changed = 22:11

![image](https://user-images.githubusercontent.com/71872483/172272088-93b2aab2-9385-42b3-bb1a-7afffb70fb34.png)
Note: last-changed = 18:57

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - binary_sensor.rpi_1_ping_availability_status
      - binary_sensor.rpi_1_integration_availability_status
  - type: history-graph
    entities:
      - binary_sensor.rpi_1_ping_availability_status
      - binary_sensor.rpi_1_integration_availability_status
```

Current states are ON (which is correct).
But graphs are WRONG:
![image](https://user-images.githubusercontent.com/71872483/172272309-17d21b9b-e6bd-47f1-8d11-d512119e84ef.png)

Same is in more-info:
![image](https://user-images.githubusercontent.com/71872483/172272420-9dd85470-750a-4cd4-9914-f3781c5586c4.png)

### Describe the behavior you expected

Graphs are correct.

### Steps to reproduce the issue

1.Create a card
2.See what is displayed.

### What version of Home Assistant Core has the issue?

2022.6.2

### In which browser are you experiencing the issue with?

Chrome 102.0.5005.63 

### Which operating system are you using to run this browser?

Win10x64
