### ISSUE TITLE
Automation: Choosing wrong entity_id using the UI

### ISSUE THREAD

**Issue by RaxCore** [home-assistant/frontend#12893]
### The problem

I wanted to choose an entity for my automation. I had entities with the same name/friendly_name, but different entity_ids.

When I chose the entity_id "device_tracker.iandreas_avm", the automation writes the wrong entity_id in the automation.yaml. 
It takes the first entry of the list, in my case "person.andreas". It doesn´t seem to be a difference between choosing that entry via mouse or via keyboard. 
Unfortunately the UI shows the friendly_name only, so you always have to check the YAML to get sure, that HA uses the right entity_id.
It would be better to show additionally the entity_id in the UI, maybe via tooltip.

<img width="1280" alt="2022-06-06 21_03_40-automation_list_of_entities" src="https://user-images.githubusercontent.com/96478711/172230742-94268682-27f8-4f43-838f-50e99da70f78.png">
<img width="1280" alt="2022-06-06 21_04_08-automation_wrong_entity_id_choosen" src="https://user-images.githubusercontent.com/96478711/172230758-96899156-29d0-4c04-80f3-dfbe384aa121.png">

### What version of Home Assistant Core has the issue?

2022.6.2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Example YAML snippet

```yaml
alias: 'Andreas: Änderung Anwesenheit'
description: ''
trigger:
  - platform: state
    entity_id:
      - person.andreas
condition: []
action:
  - service: notify.signal
    data:
      message: >-
        Anwesenheit Andreas changed to {{trigger.to_state.state}}, from
        {{trigger.from_state.state}}
mode: single
```
