### ISSUE TITLE
Alarm Panel Card no longer displaying numeric keypad on mobile browsers

### ISSUE THREAD

**Issue by RichardDMartinez** [home-assistant/frontend#12908]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On mobile browsers I used to get a native numeric keypad when I tapped in the entry field of the Alarm Panel Card. This was implemented in PR #8521. I no longer get that behavior and instead a full virtual keyboard displays, which makes it more challenging to tap on numbers given the small buttons.

### Describe the behavior you expected

When the user is using an Android browser, and the Code field is displayed for disarming, and the user clicks on the Code field, have the native browser number pad display. I have found the native mobile browser keypad is a much more reliable way for users to enter the pin than the HTML keypad. 

### Steps to reproduce the issue

1. Define an alarm_control_panel with some code to disarm.
2. Add an Alarm Panel Card to a dashboard and associate it with the alarm_control_panel created in 1.
3. Using an Android browser, log into HASS, access the dashboard view with the card added in 2, then tap the Code entry field -> a full virtual keyboard displays instead of a numeric keypad.
...

### What version of Home Assistant Core has the issue?

2022.6.3

### In which browser are you experiencing the issue with?

Google Chrome version 102.0.5005.99

### Which operating system are you using to run this browser?

Android 9

### Problem-relevant frontend configuration

```yaml
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret home_alarm_passcode
    code_arm_required: false
    arming_time: 30
    # delay_time (optional, default: 60) The time in seconds of the ‘pending’ state before triggering the alarm.
    delay_time: 20
    # trigger_time integer (optional, default: 120) The time in seconds of the ‘triggered’ state in which the alarm is firing.
    # trigger_time: 10
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
```
