### ISSUE TITLE
Styling of cards isn't applied until Edit/Save of dashboard

### ISSUE THREAD

**Issue by mwilky** [home-assistant/frontend#12920]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Card styling no longer seems to be working when you initially view the dashboard. If you edit/save the dashboard it then loads the styling correctly, but if you then navigate to a different dashboard and back the styling is lost again.

Code example below.

### Describe the behavior you expected

Not working:
![Not Working](https://user-images.githubusercontent.com/5043227/172798047-e11651f0-e2d6-46e0-87fe-b0cbf60716c5.PNG)

Working:
![Working](https://user-images.githubusercontent.com/5043227/172797484-894c0cc5-6f80-4ea7-a8a8-adc25e90b6ef.PNG)

### Steps to reproduce the issue

1. Create card with above code
2. Edit dashboard and save and then the styling will apply.
3.Browse to different dashboard and return and the styling will be lost

### What version of Home Assistant Core has the issue?

core-2022.6.4

### Which operating system are you using to run this browser?

Windows/Android

### Problem-relevant frontend configuration

```yaml
content: |
  # Kitchen
style:
  .: |
    ha-card {
      --ha-card-background: none !important;
      box-shadow: none !important;
      margin-top: 50px;
      margin-bottom: -15px;
      margin-left: 15px;

    }
  ha-markdown:
    $: |
      ha-markdown-element {
        letter-spacing: 0;
      }
      h1 {
        font-size: 20px !important;
        font-weight: 400;
      }
type: markdown
```
