### ISSUE TITLE
Show as: Update not available

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12939]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

as title

migrating:
```
binary_sensor:

  - platform: group
    unique_id: binary_group_updates
    name: Ha updates
    device_class: update
    entities:
      - binary_sensor.addon_updates
      - binary_sensor.home_assistant_updates
```
to UI  and need to set the equivalent of the device_class.

<img width="396" alt="Schermafbeelding 2022-06-12 om 20 18 27" src="https://user-images.githubusercontent.com/33354141/173247572-eac40d61-1957-424b-b97a-1ce993b5b48c.png">

### Describe the behavior you expected

have Update in de list of available options for Show as

### Steps to reproduce the issue

1. create binary group
2. set Show as
3.
...

### What version of Home Assistant Core has the issue?

2022.7.0.dev20220612

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

macOS 12.4
