### ISSUE TITLE
`logbook_entry` not shown when entity filter was applied

### ISSUE THREAD

**Issue by sti0** [home-assistant/frontend#12968]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When doing `logbook.log` a new Logbook entry was written to the database (event type `logbook_entry`) and was shown in the logbook when calling without a entity filter. But when I filter the entity the logbook entry is not shown anymore.
![image](https://user-images.githubusercontent.com/18382402/174287147-85924472-0f12-4e2c-88d8-90eabc8f19dc.png)
![image](https://user-images.githubusercontent.com/18382402/174287162-06b50cb7-280d-4a74-b909-5d19a77ceeef.png)
![image](https://user-images.githubusercontent.com/18382402/174287186-230b021a-0b65-4c13-89e1-4f6d8967a2c0.png)

`events` table:
![image](https://user-images.githubusercontent.com/18382402/174287269-f6ac2527-bd3c-4bf4-91ef-5e9bb25a93cd.png)

`event_data` table:
![image](https://user-images.githubusercontent.com/18382402/174287308-de1a074d-ef9d-493d-be5b-ec1b87892100.png)

### Describe the behavior you expected

I expected to see the logbook entry when I filter for the entity as well.

### Steps to reproduce the issue

1. Call `logbook.log` to produce a new logbook entry
```yaml
service: logbook.log
data:
  name: test
  message: blabla
  domain: light
  entity_id: light.kuche
```
2. Look at the logbook without entity filter. The logbook entry should show up
3. Filter for the entity from point 1 -> logbook entry is not shown

### What version of Home Assistant Core has the issue?

core-2022.6.6

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.115, Brave 1.39.122

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
Logbook is not filtered

Recorder:


recorder:
  auto_purge: true
  commit_interval: 60
  purge_keep_days: 3
  db_url: !secret mysql_url
  exclude:
    entity_globs:
      - "*sensor.0x*"
      - sensor.*_voltage
      - sensor.*_update_state
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
      - sensor.date_time
      - sensor.internet_time
      - switch.adaptive_lighting_*
      - binary_sensor.*_update_available
    domains:
      - camera
      - script
      - weather
      - zone
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_
