### ISSUE TITLE
Problem with yaml dashboard view

### ISSUE THREAD

**Issue by ijustlikeit** [home-assistant/frontend#12972]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On initial use the attributes defining the view are not being displayed properly. Here is the screenshot of the result:

![home screen before](https://user-images.githubusercontent.com/58893668/174399438-86e6cdac-b9bb-41a5-a6da-00b6f36a6f4d.png)

### Describe the behavior you expected

Moving away and coming say to another tab and coming back to the "Home" screen it then displays properly.  Here is the proper display.  

![Screenshot proper](https://user-images.githubusercontent.com/58893668/174399602-e6a2a957-8726-4907-b015-39acc934a308.png)

### Steps to reproduce the issue

1. Initial display incorrect
2. Move away to another tab or anything
3. Move back and display is now correct.
4.
5.
...

### What version of Home Assistant Core has the issue?

2022.6.6

### What was the last working version of Home Assistant Core?

2022.5.x

### In which browser are you experiencing the issue with?

Version 102.0.5005.115 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
# Home View

  - badges: []
    cards:
      - cards:
          - cards:

              - content: |
                  # Home Directory<br> <br>
                style: 
                    .: |
                      ha-card {
                        color: rgba(240, 202, 168);
                        --card-background-color: 'rgba(11, 11, 11, 0.00)';
                         box-shadow: 2px 2px rgba(0,0,0,0.0);
                      }
                    ha-markdown:
                         $: |  
                            h1 {
                                font-size: 30px;
                                text-align:center;
                                font-weight: 600;
                                font-family: Georgia;
                                opacity: 0.7;
                                font-style: oblique;
                                letter-spacing: '-0.01em';
                               }
                type: markdown            
            type: vertical-stack
            
          - cards:    
            - cards:
                - cards:
# 1st              
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                            ha-card {
                                     --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                     box-shadow: 2px 2px rgba(0,0,0,0.0);
                                    }
                      styles:
                        card:
                          - width: 1px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:lightbulb-multiple'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                      {% if is_state('sun.sun', 'above_horizon') %}
                                       -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                      {% else %}
                                       -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                      {% endif %}                
                                     }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
#                        - border-radius: 10px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/lights
                      type: 'custom:button-card'
                    - cards:
 
                        - content: >
                            # <i><b>Lights</i></b> <br> <br>
                            {% set lgt_cnt = int(states('sensor.current_lights_on'),default=0) %}
                            {% if lgt_cnt < 1 %}
                            No Lights on
                            {% elif lgt_cnt == 1 %}
                            There is one light on
                            {% else %}
                            There are {{ lgt_cnt }} lights on
                            {% endif %}
                          style: 
                            .: |
                              ha-card {
                                color: rgba(255, 119, 0);
                                --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                   box-shadow: 2px 2px rgba(0,0,0,0.0);
                                   }
                            ha-markdown:  
                              $: |
                                h1 {
                                  font-size: 15px;
                                  font-weight: normal;
                                  font-family: Helvetica;
                                  letter-spacing: '-0.01em';
                                  line-height: 1;
                                }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack
# 2nd                
                - show_icon: false
                  show_name: false
                  style: 
                      .: |
                         ha-card {
                                   --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                   box-shadow: 2px 2px rgba(0,0,0,0.0);
                                 }
                  styles:
                    card:
                      - width: 5px
                      - height: 10px
                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                            ha-card {
                                     --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                     box-shadow: 2px 2px rgba(0,0,0,0.0);
                                    }
                      styles:
                        card:
                          - width: 5px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:cctv'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                        {% if is_state('sun.sun', 'above_horizon') %}
                                           -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                        {% else %}
                                           -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                        {% endif %}   
                                      }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/security
                      type: 'custom:button-card'
                    - cards:
                        
                        - content: >
                            # <i><b>Home security</i></b> <br> <br>
                            Security is {% if is_state('alarm_control_panel.x', 'armed_home') %}  armed
                                        {% elif is_state('alarm_control_panel.x', 'armed_away') %}  armed
                                        {% else %}  disarmed  
                                        {% endif %}
                          style: 
                              .: |
                                 ha-card {
                                          color: rgba(255, 119, 0);
                                          --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                          box-shadow: 2px 2px rgba(0,0,0,0.0);
                                         }
                              ha-markdown:
                                $: |
                                   h1 {
                                       font-size: 15px;
                                       font-weight: normal;
                                       font-family: Helvetica;
                                       letter-spacing: '-0.01em';
                                       line-height: 1;
                                      }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack
# 3 rd button                
                - show_icon: false
                  show_name: false
                  style: 
                      .: |
                         ha-card {
                                  --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                                 }
                  styles:
                    card:
                      - width: 5px
                      - height: 10px
                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                                     }
                      styles:
                        card:
                          - width: 5px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:weather-sunny'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                        {% if is_state('sun.sun', 'above_horizon') %}
                                          -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                        {% else %}
                                          -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                        {% endif %}   
                                      }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/weather/
                      type: 'custom:button-card'
                    - cards:

                        - content: >
                            # <i><b>Edm weather</i></b> <br> <br>
                            It is {{states('weather.edmonton_int_l_aprt') }} and {{states('sensor.edmonton_int_l_aprt_temperature') }}°C
                          style: 
                              .: |
                                 ha-card {
                                          color: rgba(255, 119, 0);
                                          --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                          box-shadow: 2px 2px rgba(0,0,0,0.0);
                                         }
                              ha-markdown:
                                $: |
                                   h1 {
                                       font-size: 15px;
                                       font-weight: normal;
                                       font-family: Helvetica;
                                       letter-spacing: '-0.01em';
                                       line-height: 1;
                                      }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack
#4th button                  
                - show_icon: false
                  show_name: false
                  style: 
                      .: |
                         ha-card {
                                  --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                                 }
                  styles:
                    card:
                      - width: 5px
                      - height: 10px
                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                                     }
                      styles:
                        card:
                          - width: 5px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:battery-charging-40'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                       {% if is_state('sun.sun', 'above_horizon') %}
                                          -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                       {% else %}
                                          -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                       {% endif %}   
                                      }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/battery_levels/
                      type: 'custom:button-card'
                    - cards:
                        
                        - content: >
                            # <i><b>Batteries</i></b> <br> 
                            {% if states('sensor.x') |float(default=0) < 21 or
                                     states('sensor.x') |float(default=0) < 21 or
                                     states('sensor.x') |float(default=0)< 21 or
                                     states('sensor.x')|float(default=0) < 21 or
                                     states('sensor.x') |float(default=0)< 21 or
                                     states('sensor.x') |float(default=0)< 21 or
                                     states('sensor.x')|float(default=0) < 21   %} 
                              # One of the batteries is low 
                            {% else %} 
                              # Batteries all ok 
                            {% endif %} 
                          style: 
                              .: |
                                 ha-card {
                                          color: rgba(255, 119, 0);
                                          --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                          box-shadow: 2px 2px rgba(0,0,0,0.0);
                                         }
                              ha-markdown:
                                $: |
                                   h1 {
                                       font-size: 15px;
                                       font-weight: normal;
                                       font-family: Helvetica;
                                       letter-spacing: '-0.01em';
                                       line-height: 1;
                                      }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack                  

#5th button                  
                - show_icon: false
                  show_name: false
                  style: 
                      .: |
                         ha-card {
                                  --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                                 }
                  styles:
                    card:
                      - width: 5px
                      - height: 10px
                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                                     }
                      styles:
                        card:
                          - width: 5px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:video'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                       {% if is_state('sun.sun', 'above_horizon') %}
                                          -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                       {% else %}
                                          -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                       {% endif %}   
                                      }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/cameras/
                      type: 'custom:button-card'
                    - cards:
                        
                        - content: >
                            # <i><b>Cameras</i></b> <br> 

                          style: 
                              .: |
                                 ha-card {
                                          color: rgba(255, 119, 0);
                                          --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                          box-shadow: 2px 2px rgba(0,0,0,0.0);
                                         }
                              ha-markdown:
                                $: |
                                   h1 {
                                       font-size: 15px;
                                       font-weight: normal;
                                       font-family: Helvetica;
                                       letter-spacing: '-0.01em';
                                       line-height: 1;
                                      }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack                  
              type: vertical-stack              
# 6th button                
            - cards:
#                - show_icon: false
#                  show_name: false
#                  style: |
#                    ha-card {
#                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
#                      box-shadow: 2px 2px rgba(0,0,0,0.0);
#                    }
#                  styles:
#                    card:
#                      - width: 5px
#                      - height: 0px
#                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                                     }
                      styles:
                        card:
                          - width: 5px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:thermostat'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                         {% if is_state('sun.sun', 'above_horizon') %}
                                            -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                         {% else %}
                                            -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                         {% endif %}   
                                       }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/zTemperatureHouse/
                      type: 'custom:button-card'
                    - cards:

                        - content: >
                            # <i><b>Thermostats</i></b> <br> <br> 
                            Mainfloor {{ state_attr('climate.x', 'hvac_action') }}, upstairs {{ state_attr('climate.x', 'hvac_action') }}
                          style: 
                              .: |
                                 ha-card {
                                          color: rgba(255, 119, 0);
                                          --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                          box-shadow: 2px 2px rgba(0,0,0,0.0);
                                         }
                              ha-markdown:
                                $: |
                                   h1 {
                                       font-size: 15px;
                                       font-weight: normal;
                                       font-family: Helvetica;

                                       line-height: 1;
                                      }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack
# 7th button                
                - show_icon: false
                  show_name: false
                  style: 
                      .: |
                         ha-card {
                                  --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                                 }
                  styles:
                    card:
                      - width: 5px
                      - height: 10px
                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                                     }
                      styles:
                        card:
                          - width: 5px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:speaker'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                         {% if is_state('sun.sun', 'above_horizon') %}
                                            -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                         {% else %}
                                            -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                         {% endif %}   
                                      }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/media/
                      type: 'custom:button-card'
                    - cards:
                 
                        - content: >
                             # <i><b>Media Players</i></b> <br> <br> 
                             Smartcast is {{ states('media_player.x') }}, Kitchen TV is {{ states('media_player.x') }} 
                          style: 
                              .: |
                                 ha-card {
                                          color: rgba(255, 119, 0);
                                          --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                          box-shadow: 2px 2px rgba(0,0,0,0.0);
                                         }
                              ha-markdown:
                                $: |
                                   h1 {
                                       font-size: 15px;
                                       font-weight: normal;
                                       font-family: Helvetica;
                                       letter-spacing: '-0.01em';
                                       line-height: 1;
                                      }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack
# 8th button                
                - show_icon: false
                  show_name: false
                  style: 
                      .: |
                         ha-card {
                                  --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                                 }
                  styles:
                    card:
                      - width: 5px
                      - height: 10px
                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                                     }
                      styles:
                        card:
                          - width: 5px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:run-fast'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                         {% if is_state('sun.sun', 'above_horizon') %}
                                            -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                         {% else %}
                                            -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                         {% endif %}   
                                      }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/motion_clips/
                      type: 'custom:button-card'
                    - cards:

                        - content: >
                             # <i><b>Motion clips</i></b> <br> <br> 
                             There are {{ state_attr('sensor.videos', 'number_of_files') }} motion clips
                          style: 
                              .: |
                                 ha-card {
                                          color: rgba(255, 119, 0);
                                          --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                          box-shadow: 2px 2px rgba(0,0,0,0.0);
                                         }
                              ha-markdown:
                                $: |
                                   h1 {
                                       font-size: 15px;
                                       font-weight: normal;
                                       font-family: Helvetica;
                                       line-height: 1;
                                      }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack                
# 9th button 
                - show_icon: false
                  show_name: false
                  style: 
                      .: |
                         ha-card {
                                  --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                                 }
                  styles:
                    card:
                      - width: 5px
                      - height: 10px
                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                                     }
                      styles:
                        card:
                          - width: 5px
                          - height: 80px
                      type: 'custom:button-card'
                    - icon: 'mdi:magnify-scan'
                      show_icon: true
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      box-shadow: 
                                         {% if is_state('sun.sun', 'above_horizon') %}
                                            -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                         {% else %}
                                            -8px -8px 8px 0 rgba(77, 77, 77,.5),8px 8px 8px 0 rgba(0,0,0,.3);
                                         {% endif %}   
                                      }
                      styles:
                        card:
                          - width: 70px
                          - height: 70px
                          - border-radius: 15px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color:  rgba(255, 119, 0)
                      tap_action:
                        action: navigate
                        navigation_path: /lovelace/object_detection/
                      type: 'custom:button-card'
                    - cards:
                        
                        - content: >
                            # <i><b>OBTAIN System</i></b> <br> <br>
                            There are 4 object types
                          style: 
                              .: |
                                 ha-card {
                                          color: rgba(255, 119, 0);
                                          --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                          box-shadow: 2px 2px rgba(0,0,0,0.0);
                                         }
                              ha-markdown:
                                $: |
                                   h1 {
                                       font-size: 15px;
                                       font-weight: normal;
                                       font-family: Helvetica;
                                       line-height: 1;
                                      }
                          type: markdown
                      type: vertical-stack
                  type: horizontal-stack  
# end of buttons                  
                - show_icon: false
                  show_name: false
                  style: 
                      .: |
                         ha-card {
                                  --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                                 }
                  styles:
                    card:
                      - width: 5px
                      - height: 10px
                  type: 'custom:button-card'
                - cards:
                    - show_icon: false
                      show_name: false
                      style: 
                          .: |
                             ha-card {
                                      --card-background-color: 'rgba(11, 11, 11, 0.00)';
                                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                                     }
                      styles:
                        card:
                          - width: 5px
                          - height: 10px
                      type: 'custom:button-card'
                  type: horizontal-stack
              type: vertical-stack
            type: horizontal-stack  
        type: vertical-stack
    icon: 'mdi:home'
    path: home
    title: Home
```
