### ISSUE TITLE
panel_iframe + "Visit Device" + ZigBee2MQTT not working together

### ISSUE THREAD

**Issue by GsakuL** [home-assistant/frontend#12974]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when setting the iFrame-Address in Z2M to report back as its "URL on which the frontend can be reached"; and using Z2M Autodiscovery/`homeassistant: true` and clicking "Visit Device" on a Z2M device page, it opens Z2M in the iFrame, but only the main page. Using Z2M "direct" address works as intended.

### Describe the behavior you expected

The iFrame would open Z2M with the device page

### Steps to reproduce the issue

0. Ports:
  a. 8123 Home Assistant
  b. 8090 ZigBee2MQTT
2. ZigBee2MQTT configuration.yml:
```yml
homeassistant:
  legacy_triggers: false 
# ....
frontend:
  url: http://z83.fritz.box:8123/zigbee2mqtt
```
3. HomeAssistant configuration.yaml:
```yml
panel_iframe:
  zigbee2mqtt:
    title: "zigbee2mqtt"
    url: "http://z83.fritz.box:8090"
    icon: mdi:zigbee
    require_admin: true
```
4. Have ZigBee devices be auto discovered
5. go to any Z2M device in Home Assistant
6. click the "Visit Device" Button/Link in the "Device Info" card
7. link that gets constructed: `http://z83.fritz.box:8123/zigbee2mqtt/#/device/0xcc86ecfffe4c3e52/info`
8. visit it
9. only see the Z2M Dashboard

Double check with "direct address":
1. change Z2M.frontend.url: http://z83.fritz.box:8090/
2. rediscover/reboot
3. "Visit Device" Link now produces `http://z83.fritz.box:8090/#/device/0xcc86ecfffe4c3e52/info`
4. visit it
5. land on the wanted device page

### What version of Home Assistant Core has the issue?

2022.6.6

### In which browser are you experiencing the issue with?

any (Win: Firefox 101.0.1 / Win: Brave 1.39.122 Chromium 102.0.5005.115 / Offical HA Android App 2022.6.0-minimal)

### Which operating system are you using to run this browser?

Windows 11 21H2; Android 12

### Javascript errors shown in your browser console/inspector

```txt
(only from Browser because it's not HTTPS)
```

### Additional information

**Zigbee2MQTT -> Settings -> About**
Zigbee2MQTT version: [1.25.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.25.2) commit: [3c5854f](https://github.com/Koenkk/zigbee2mqtt/commit/3c5854f)
Frontend version: 0.6.97

**Comment by RoboMagus** [comment]
Do you have Z2M set up through HA-Addons? 
I'm using Z2M as well, and I cannot see anything related to "visit device" on the device pages. Just "MQTT info".

**Comment by GsakuL** [comment]
I'm sorry if this isn't clear.
I'm using HA Container, managing my own containers. So no, i don't (/can't) use the HA-Addon.
```yml
version: '3'
services:
  zigbee2mqtt:
    tty: true
    stdin_open: true
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_22_98_A4_3D-if00-port0:/dev/ttyACM0
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Berlin
  mosquitto:
    tty: true
    stdin_open: true
    container_name: mosquitto
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
  homeassistant:
    tty: true
    stdin_open: true
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 2m
    privileged: true
    network_mode: host
```
and this is the Button/Link I'm speaking of:
![Device Page](https://user-images.githubusercontent.com/6844160/174738500-500f8c7f-1300-443d-98a4-34a004f4283d.png)


Yes, i know, that `http://z83.fritz.box:8090` would work. I stated that in my first comment.
But the link opens in the current tab by default (thankfully middle mouse / ctrl click works for new tab), thus it would be "cleaner" to also have the Z2M frontend to open in the iframe.
The iframe only opens the page configured in HAs config, and ignores any further URL parameter/paths.
