### ISSUE TITLE
OR conditions in visual editor not working

### ISSUE THREAD

**Issue by alexfd** [home-assistant/frontend#13018]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Setting up an OR automation using the visual editor does not produce a working result.
**Test1:**
```
Condition type: Device
Device: Alarm
Condition: Alarm is armed home

Condition type: Or
Condition type: device
Device: Alarm
Condition: Alarm is armed away
```

produces this yaml:
```
condition:
  - condition: device
    device_id: ef781bb64ece5f2971b593fd190b6ddd
    domain: alarm_control_panel
    entity_id: alarm_control_panel.newbridge_alarm
    type: is_armed_home
  - condition: or
    conditions:
      - condition: device
        device_id: ef781bb64ece5f2971b593fd190b6ddd
        domain: alarm_control_panel
        entity_id: alarm_control_panel.newbridge_alarm
        type: is_armed_away
```

and does not trigger action.

**Test2:**
```
Condition type: Or
Condition type: Device
Device: Alarm
Condition: Alarm is armed home

Condition type: device
Device: Alarm
Condition: Alarm is armed away
```

produces this yaml:
```
condition:
  - condition: or
    conditions:
      - condition: device
        device_id: ef781bb64ece5f2971b593fd190b6ddd
        domain: alarm_control_panel
        entity_id: alarm_control_panel.newbridge_alarm
        type: is_armed_home
  - condition: device
    device_id: ef781bb64ece5f2971b593fd190b6ddd
    domain: alarm_control_panel
    entity_id: alarm_control_panel.newbridge_alarm
    type: is_armed_away
```

and does not trigger action.

The closest thing to the working one is Test2, but indentation is wrong.
So the only way to have it working is to use yaml mode and TAB the second condition so that it is actually nested under "conditions", like this:
```
condition:
  - condition: or
    conditions:
      - condition: device
        device_id: ef781bb64ece5f2971b593fd190b6ddd
        domain: alarm_control_panel
        entity_id: alarm_control_panel.newbridge_alarm
        type: is_armed_home
      - condition: device
        device_id: ef781bb64ece5f2971b593fd190b6ddd
        domain: alarm_control_panel
        entity_id: alarm_control_panel.newbridge_alarm
        type: is_armed_away
```

### Describe the behavior you expected

The OR selector for conditions should produce a working set of conditions, matching either x or y.

### Steps to reproduce the issue

1. Set up new automation
2. Condition type: Or
3. Condition type: Device
4. Select device and add condition
5. Add new condition, type device
6. Select device and add condition

### What version of Home Assistant Core has the issue?

2021.12.8

### In which browser are you experiencing the issue with?

Firefox Nightly

### Which operating system are you using to run this browser?

Windows 10

### Additional information

No I am not running the latest HA because I need the environment stable, so updating comes only in strict conditions. Thanks for understanding.
