### ISSUE TITLE
Using Disable from the UI when creating a script of automation and then enabling again causes "Key 'enabled' is not expected or not supported by the visual editor."

### ISSUE THREAD

**Issue by mattbruman** [home-assistant/frontend#13036]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using Disable from the UI when creating a script of automation and then enabling again causes 

"Key 'enabled' is not expected or not supported by the visual editor." 
You then have to manually delete the "enabled: true" string to be able to use the visual editor again.

Also while it is in this state if you use the arrows to move a action it will add enabled: true and then give the same error. 

### Describe the behavior you expected

When disabling and enabling actions it should not add enabled: true to the yaml or enabled: true should be a allowable string to keep the visual editor working. Also while moving a action it should not append enabled: true to the action that moves past.

### Steps to reproduce the issue

1. Create a script and add a telegram service
2. Click 3 dots and disable the action
3. Click 3 dots again and enable
4. The action is now in a error state.
5. Add another action like "delay" and move it past or above the error state telegram action

![image](https://user-images.githubusercontent.com/43623584/176521678-fd5c3c6b-1b20-4ac3-b09b-3f461ebc42cc.png)
![image](https://user-images.githubusercontent.com/43623584/176521766-90172748-8972-458c-8558-c4715cab1ef2.png)

...

### What version of Home Assistant Core has the issue?

2022.6.7

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.115

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
alias: Someone At Garage Door
sequence:
  - service: tts.cloud_say
    data:
      entity_id: media_player.office_speaker
      message: Person detected at Garage Door
      cache: true
  - service: tts.cloud_say
    data:
      entity_id: media_player.kitchen_mini
      message: Person detected at Garage Door
      cache: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: camera.snapshot
    data:
      filename: /config/www/snap_garage_door.jpg
    target:
      entity_id: camera.garage_door_alerts
  - service: notify.notify
    data:
      data:
        image: >-
          https://.nabu.casa/local/snap_garage_door.jpg
        actions:
          - action: URI
            title: Open Camera
            uri: /camera-pages/garage-door
          - action: WORKING_OUTSIDE
            title: Working Outside
        clickAction: >-
          https://nabu.casa/local/snap_garage_door.jpg
      title: 🏃 Person Detected 🏃
      message: at Garage Door
  - service: telegram_bot.send_photo
    data:
      file: /config/www/snap_garage_door.jpg
    enabled: true
  - service: camera.record
    data:
      filename: /config/www/snap_garage_door.mp4
      duration: 30
      lookback: 5
    target:
      entity_id: camera.blueiris_garagedoorsd
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: telegram_bot.send_video
    data:
      file: /config/www/snap_garage_door.mp4
      target:
        - 1412047356
        - 1289324914
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
mode: single
icon: hass:motion
```
