### ISSUE TITLE
history-graph: wrong auto-refresh

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13128]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The issue is similar to the closed issue https://github.com/home-assistant/frontend/issues/12859.
~In 2022.7 the initial issue seems to be solved - but only for sensors with UoM.
The current issue is for sensors w/o UoM.~
**Update:** the very same behaviour is with sensors with UoM.

To demonstrate the issue, I am using some `input_boolean` helper.

Let's assume that the helper's value is ON.

Set the helper's value to OFF.
The graph is refreshed, the OFF value is displayed on the graph (thin red line).
![image](https://user-images.githubusercontent.com/71872483/177650561-404d35b8-d10f-479c-9cf4-fe9cafa59ba5.png)

Wait for a few minutes - and the graph is NOT refreshed anymore.

Set the helper's value to ON.
The graph is updated, but the ON value is not displayed on the graph.
![image](https://user-images.githubusercontent.com/71872483/177650560-09a970f7-fc44-4d8c-b333-356c1976c926.png)

Wait for a few minutes - and the graph is NOT refreshed.

Press F5 to reload the page - the graph is refreshed:
![image](https://user-images.githubusercontent.com/71872483/177650576-f3428903-b07b-4935-a98b-a84805b67f1d.png)

### Describe the behavior you expected

A graph is updated after a reasonable delay after state's change.

### Steps to reproduce the issue

1. Create an `input_boolean` helper.
2. Create a card with this `input_boolean` helper:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_boolean.flag
        secondary_info: last-changed
  - type: history-graph
    entities:
      - input_boolean.flag
    hours_to_show: 1
    refresh_interval: 0
  - type: logbook
    entities:
      - input_boolean.flag
    hours_to_show: 1
```
3. Change a value of the `input_boolean` helper.
4. See if the graph is updated.
...

### What version of Home Assistant Core has the issue?

2022.7.0

### What was the last working version of Home Assistant Core?

2022.5

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.114

### Which operating system are you using to run this browser?

Win10x64
