### ISSUE TITLE
Gauge does not show label

### ISSUE THREAD

**Issue by lancer73** [home-assistant/frontend#13139]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The gauge card doesn't show labels when defined using segments. Tried on Safari and Edge on M1 Mac.

### Describe the behavior you expected

When configured like this:
`type: gauge
entity: sensor.uv_index
name: ' '
min: 0
max: 12
segments:
  - from: 0
    color: green
    label: 60 min+
  - from: 3
    color: yellow
    label: 30-45 min
  - from: 6
    color: orange
    label: 15-25 min
  - from: 8
    color: red
    label: <15 min
  - from: 11
    color: purple
    label: <10 min
`

It is expected that the label is shown. Instead the value shows. Tried with text only labels as well.

### Steps to reproduce the issue

1. Create card with given config
2.
3.
...

### What version of Home Assistant Core has the issue?

core-7.0

### In which browser are you experiencing the issue with?

Safari 17613.2.7.1.8 and Edge 103.0.1264.51

### Which operating system are you using to run this browser?

macOS 12.4

### State of relevant entities

```txt
state: 2.77
state_class: measurement
unit_of_measurement: UV index
attribution: Data provided by OpenWeatherMap
friendly_name: UV Index
```

### Problem-relevant frontend configuration

```yaml
type: gauge
entity: sensor.uv_index
name: ' '
min: 0
max: 12
segments:
  - from: 0
    color: green
    label: 60 min+
  - from: 3
    color: yellow
    label: 30-45 min
  - from: 6
    color: orange
    label: 15-25 min
  - from: 8
    color: red
    label: <15 min
  - from: 11
    color: purple
    label: <10 min
```

### Javascript errors shown in your browser console/inspector

```txt
No related errors
```
