### ISSUE TITLE
Logbook card: tight placement for entities with images

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13131]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Suppose some entity has an `entity_picture` attribute specified.
Then this image is displayed when the entity is shown in a Logbook card.

The problem is that a horizontal space between the image & a right part of the logbook's row is too narrow:
![image](https://user-images.githubusercontent.com/71872483/177679373-33392c4a-2ef8-4211-9ba4-0699610eb364.png)

Earlier this gap was bigger.

### Describe the behavior you expected

There is a gap between an image and a text.

### Steps to reproduce the issue

1. Create & customize a helper:
```
homeassistant:
  customize:
    input_boolean.flag_with_image:
      entity_picture: /local/images/blue.jpg

input_boolean:
  flag_with_image:
```

2. Create a card:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_boolean.flag_with_image
  - type: logbook
    entities:
      - input_boolean.flag_with_image
    hours_to_show: 1
```

3. Start changing a helper's value.

### What version of Home Assistant Core has the issue?

2022.7.0

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.114 

### Which operating system are you using to run this browser?

Win10x64
