### ISSUE TITLE
Current option: Alarm - Tyrell no longer valid (possible options: Alarm Tyrell) for input_select on startup

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#13142]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

even though https://github.com/home-assistant/frontend/issues/11991 was closed, and I tried to find a solution in it for my specific usecase, I couldn't so please see this.

Its about an input_select with 1 option in the config (we need that unfortuanely, because without an option I the config, the input_select it's accepted as valid)

this was my original yaml select, now its in the UI (error was also I yaml so that isnt it.)
```
  hue_dynamic_scene:
    name: Hue Dynamic scene
    options:
      - 'Alarm - Tyrell'
```

### Describe the behavior you expected

simply accept the correct option

### Steps to reproduce the issue

1. create the input_select with 1 fixed option
2. 
3.

### What version of Home Assistant Core has the issue?

core-2022.8.0.dev20220707

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

MacOS 12.4

### Javascript errors shown in your browser console/inspector

not console, but homeassistant.log
```txt

Logger: homeassistant.components.input_select
Source: components/input_select/__init__.py:367 
Integration: Input select (documentation, issues) 
First occurred: 22:20:18 (1 occurrences) 
Last logged: 22:20:18

Current option: Alarm - Tyrell no longer valid (possible options: Alarm Tyrell)
```

### Additional information

I have an automation to auto-populate the rest of the options for this select:

```
  - alias: Auto populate Hue dynamic scene input select
    id: auto_populate_hue_dynamic_scene_input_select
    mode: restart
    trigger:
      #      - platform: event
      #        event_type: delayed_homeassistant_start
      - platform: state
        entity_id: input_select.hue_group
    action:
      service: input_select.set_options
      target:
        entity_id: input_select.hue_dynamic_scene
      data:
        options: >
          {% set hue_group = states('input_select.hue_group') %}
          {{states.scene
            |selectattr('attributes.group_name','eq',hue_group)
            |selectattr('attributes.is_dynamic','eq',true)
            |map(attribute='name')|list}}
```

but as you can see here, that hasn't triggered at startup yet so its a bit of a miracle why the given option is logged as not being a valid option...even though it is the only one yet available:

<img width="1127" alt="Schermafbeelding 2022-07-07 om 22 35 23" src="https://user-images.githubusercontent.com/33354141/177866895-235be9ac-80a7-4227-8940-8371ab4339cb.png">

## System Health

version | core-2022.8.0.dev20220707
-- | --
installation_type | Home Assistant OS
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.45
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4697
Installed Version | 1.25.5
Stage | running
Available Repositories | 1081
Downloaded Repositories | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 31, 2022, 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | dev
supervisor_version | supervisor-2022.07.dev0703
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 112.7 GB
disk_used | 13.3 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.9.0), Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.108.2), Log Viewer (0.14.0), MariaDB (2.5.0), Matter Server (0.2.2), Samba share (10.0.0), Studio Code Server (5.1.2), Terminal & SSH (9.6.0), phpMyAdmin (0.8.0), Mosquitto broker (6.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 39
error | /config/ui-lovelace.yaml not found
views | 86
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 30, 2022, 05:30
-- | --
current_recorder_run | July 7, 2022, 22:18
estimated_db_size | 982.39 MiB
database_engine | mysql
database_version | 10.6.8

</details>

**Comment by Mariusthvdb** [comment]
a practically identical:
```
input_select:

  hue_group:
    name: Select Hue group
    options:
      - Alarm
#    initial: Alarm
```

doesnt error, even though there is this automation

```
  - alias: Auto populate Hue group input select
    id: auto_populate_hue_group_input_select
    mode: restart
    trigger:
      platform: event
      event_type: delayed_homeassistant_start
    action:
      service: input_select.set_options
      target:
        entity_id: input_select.hue_group
      data:
        options: >
          {{expand(integration_entities('Philips Hue 1'))
            |selectattr('attributes.is_hue_group','defined')
            |selectattr('attributes.is_hue_group','eq',true)
            |map(attribute='name')|list}}
```

right after startup.
