### ISSUE TITLE
Friendly_name not working i the new history section

### ISSUE THREAD

**Issue by thbe51** [home-assistant/frontend#13155]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Friendly names does not show up in the new  history screen  UNLESS you enter a false (not existing) entity in the filter.

### Describe the behavior you expected

Friendly names showing (as in 2022.6.7)

### Steps to reproduce the issue

1. customize: under home_assistant: in configuration.yaml 
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.7

### What was the last working version of Home Assistant Core?

2022.6.7

### In which browser are you experiencing the issue with?

Google Chrome  103.0.5060.114

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: "Europe/Stockholm"
  currency: SEK
  external_url: !secret external_url
  internal_url: !secret internal_url
  customize:
    binary_sensor.dorrsensor_bad_access_control_window_door_is_open:
      friendly_name: "DÖRR BADRUM "
    binary_sensor.dorrsensor_forrad_access_control_window_door_is_open:
      friendly_name: "DÖRR FÖRRÅD "
    binary_sensor.dorrsensor_kok_access_control_window_door_is_open:
      friendly_name: "DÖRR KÖK "
    binary_sensor.vadring_access_control_window_door_is_open:
      friendly_name: "FÖNSTER KÖK "
    binary_sensor.dorrsensor_vardagsrum_access_control_window_door_is_open:
      friendly_name: "DÖRR VARDAGSRUM "
    binary_sensor.vadring2_access_control_window_door_is_open:
      friendly_name: "FÖNSTER VARDAGSRUM "
    binary_sensor.dorrsensor_sovrum_access_control_window_door_is_open:
      friendly_name: "DÖRR SOVRUM "
    sun.sun:
      friendly_name: "SOLEN "
    device_tracker.samsung_s20_ultra_5g:
      friendly_name: "MOBILTELEFON "
  customize_domain:
    automation:
      initial_state: on
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.66.0/24
      allow_bypass_login: true
```
