### ISSUE TITLE
Dropdown - missing selected option when dropdown list updates at the same time (select entity)

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#13189]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When `select` entity changes both state and `options` attribute at once the dropdown may not display current state.
This happens when new state is valid with new options list but was not valid with old one.

### Describe the behavior you expected

The options list is updated as well as new state properly selected.

### Steps to reproduce the issue

1. Create `select` entity with dynamically changing options list. Make sure the state is valid whenever options list change.
2. Place it in UI  as entity row (or whenever it renders as dropdown)

### What version of Home Assistant Core has the issue?

2022.7.3

### In which browser are you experiencing the issue with?

Chrome, Firefox, Mobile app

### Which operating system are you using to run this browser?

Windows 10 21H2, Android 11

### State of relevant entities

I used template integration to build select entity around "last app" sensor state from mobile app installed on my android TV and phone.
Select holds a static list of important/most used apps. Whenever any other app is used it's appended at the bottom of the list - to make the select always in a valid state.

Main entity (relevant to the issue)

```yaml
event_type: state_changed
data:
  entity_id: select.living_room_tv_last_used_app
  old_state:
    entity_id: select.living_room_tv_last_used_app
    state: Netflix
    attributes:
      options:
        - FLauncher # <- static list of important/most used apps
        - Netflix
        - HBO Max
        - Disney+
        - SmartTube
        - VLC
        - Kodi
        - Player.pl
        - Spotify
        - RadioDroid
        - MiXplorer
        - Fennec
      icon: 'mdi:android'
      friendly_name: Living Room TV Last Used App
  new_state:
    entity_id: select.living_room_tv_last_used_app
    state: Settings
    attributes:
      options:
        - FLauncher
        - Netflix
        - HBO Max
        - Disney+
        - SmartTube
        - VLC
        - Kodi
        - Player.pl
        - Spotify
        - RadioDroid
        - MiXplorer
        - Fennec
        - Settings # <- appended last whenever other app is used
      icon: 'mdi:android'
      friendly_name: Living Room TV Last Used App
```

Relevant entity triggering the change (not important, but for context)
 ```yaml
event_type: state_changed
data:
  entity_id: sensor.living_room_tv_last_used_app
  old_state:
    entity_id: sensor.living_room_tv_last_used_app
    state: com.netflix.ninja
    attributes:
      Label: Netflix
      icon: 'mdi:android'
      friendly_name: Living Room TV Last Used App
  new_state:
    entity_id: sensor.living_room_tv_last_used_app
    state: com.android.tv.settings
    attributes:
      Label: Settings
      icon: 'mdi:android'
      friendly_name: Living Room TV Last Used App
```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
   # dropdown entity that has the issue
  - entity: select.living_room_tv_last_used_app
  # no problem just to verify
  - entity: sensor.living_room_tv_last_used_app
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

```txt
Reloading the frontend renders dropdown with correctly selected option.
```
