### ISSUE TITLE
history-graph: wrong graph, wrong current value

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13195]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Absolutely same as described here:
https://github.com/home-assistant/core/issues/73154

history-graph stopped displaying valid data.
On some moment of time graph becomes a constant line.

![изображение](https://user-images.githubusercontent.com/71872483/178974800-e88a19a5-39d8-4250-86cc-2ddf1c6e9525.png)
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - binary_sensor.net_is_available_internet
  - type: history-graph
    entities:
      - binary_sensor.net_is_available_internet
    hours_to_show: 4
    refresh_interval: 0
```

Only after restart of HA graphs again work.

![изображение](https://user-images.githubusercontent.com/71872483/178974587-8012ebb9-f164-429c-be03-09e342eac215.png)
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - sensor.mijia_300_1_co2
  - type: history-graph
    entities:
      - sensor.mijia_300_1_co2
    hours_to_show: 4
    refresh_interval: 0
```

I noticed that sometimes it happened right after connection to Internet is lost.
Today connection lost at about 11:30 .. 11:45.
Then the connection was fixed at about 13:30.
Now it is 14:55.
Graphs stopped working about at the same time as connection was lost.

I wonder why connection to Internet is so important since all monitored sensors are for local devices only.

Here is an example for HA uptime from sysmonitor integration, it shows the same bug:
![Uploading изображение.png…]()

### Describe the behavior you expected

Graphs should be updated.

### Steps to reproduce the issue

1. Start monitoring if graphs are updated.

### What version of Home Assistant Core has the issue?

2022.7.3

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.114

### Which operating system are you using to run this browser?

Win10x64
