### ISSUE TITLE
Lovelace entities card buttons are too big

### ISSUE THREAD

**Issue by yaranzo** [home-assistant/frontend#13201]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As of 2022.6.0, the buttons on the entities card are enlarged on the right side, which cause the icon to be off-center. Happens no matter what theme is in use,
![image](https://user-images.githubusercontent.com/16183895/179145449-27853349-5374-44fe-b27f-7f076c7c9b1c.png)

### Describe the behavior you expected

The icons to be centered in the button, and for said buttons to be circular, as they were in the past.

### Steps to reproduce the issue

1. Adding any button to an entities card.

### What version of Home Assistant Core has the issue?

2022.6.0 to 2022.7.4

### What was the last working version of Home Assistant Core?

2022.5.5

### In which browser are you experiencing the issue with?

Mozilla Firefox 102.0.1, Microsoft Edge 103.0.1264.49 and iOS companion app

### Which operating system are you using to run this browser?

Windows 10 Pro 21H1, build 19043.928 and iOS 15.5

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - type: buttons
    entities:
      - entity: light.living_room_dimmer
      - entity: light.gundam
      - entity: light.living_room_bookcase
      - entity: switch.media_console_outlet
      - entity: switch.television_plug_outlet
      - entity: remote.43_tcl_roku_tv
      - entity: switch.living_room_humidifier
  - type: divider
  - entity: binary_sensor.living_room_motion_sensor_occupancy
    name: Motion
  - entity: sensor.living_room_motion_light_level
    name: Light level
  - entity: sensor.living_room_thermostat_temperature
    name: Temperature
  - entity: sensor.living_room_air_quality_2
    name: Air quality
title: Living room
theme: ios-dark-mode-blue-red
state_color: true
show_header_toggle: false
```
