### ISSUE TITLE
Blueprint boolean selectors not prompting to save and also not saving in blueprint editor

### ISSUE THREAD

**Issue by aderusha** [home-assistant/frontend#13206]
### The problem

There are two issues I've noticed with boolean selectors in blueprints:

1) If you edit a blueprint with one or more booleans, toggling the state of the boolean does not bring up the "save" button.  You have to edit some other selector in order for the "save" button to be presented.
2) If you save a blueprint after toggling the state of a boolean selector, the updated selector state is not persisted to disk.

Here is an example, dummy blueprint that offers a text selector and two booleans: https://gist.github.com/aderusha/e4348da4790af6d0875d2b3baa1762ac

## Process to replicate
1. Import and deploy blueprint: [![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgist.github.com%2Faderusha%2Fe4348da4790af6d0875d2b3baa1762ac)
2. Create automation from blueprint
3. Toggle one of the booleans, observe that the "save" button appears.
4. Press "save" and exit out of automation editor
5. Go back to the new automation in the automation editor
6. Toggle one of the booleans, observe that the "save" button does **not** appear.
7. Change the text field
8. Observe that the "save" button now appears
9. Press save and exit out of automation editor.
10. Go back to the automation in the automation editor and observe that the new value for the boolean you changed has not been saved, while the value for the text selector has been saved.
11. Open `automations.yaml` and observe that the updated boolean has not been saved, while the value for the text selector has been saved.

### What version of Home Assistant Core has the issue?

Home Assistant 2022.7.5

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
blueprint:
  name: "Test blueprint toggle saving"

  domain: automation
  input:
    text:
      name: "Text 01"
      default: "Text to save"
      selector:
        text:
    toggle1:
      name: "Toggle 01"
      default: false
      selector:
        boolean:
    toggle2:
      name: "Toggle 02"
      default: false
      selector:
        boolean:

variables:
  text: !input text
  toggle1: !input toggle1
  toggle2: !input toggle2

trigger: []

action: []
```
