### ISSUE TITLE
Picture Glance card doesn't show buttons with "toggle actions"

### ISSUE THREAD

**Issue by Sirs0ri** [home-assistant/frontend#13219]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The docs about the Picture Glance Card state "The entities on the right side allow toggle actions, others show the more information dialog."

In my opinion, buttons should fall into the group of "toggle actions", however they are shown on the left and open a "more info" dialog when tapped. To make a button inside a Picture Glance Card pressable the tap_action has to be set to `action: toggle`.

### Describe the behavior you expected

If adding a button entity to a Picture Glance Card, it should show up with all the other actionable items on the right, and I shouldn't have to manually set the "tap_action" attribute to make it pressable.

### Steps to reproduce the issue

1. Create a new Picture Glance Card
2. Under "entities", add a button entity
3. Tap the button entity. HA will open its "more info" dialog instead of pressing the button.
...

### What version of Home Assistant Core has the issue?

2022.7.5

### In which browser are you experiencing the issue with?

Chrome Version 104.0.5112.48 beta (64-Bit)

### Which operating system are you using to run this browser?

Win10 21H2

### Problem-relevant frontend configuration

```yaml
camera_view: auto
type: picture-glance
image: https://demo.home-assistant.io/stub_config/kitchen.png
entities:
  - entity: button.fanspeed_down
    # this should not be necessary to make the button actionable in my opinion:
    tap_action:
      action: toggle
```
