### ISSUE TITLE
Scripting: Comments put in YAML get removed once editing in visual editor

### ISSUE THREAD

**Issue by ant-ds** [home-assistant/frontend#13213]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When making a script and switching to YAML, you can add comments by using `#` in the beginning of a line.
When going back to visual editor, and later switching to YAML again, the comments are gone.

### Describe the behavior you expected

When going back to YAML after visual editor, comments should still be there.

### Steps to reproduce the issue

1. Create new script (for example: to turn on light)
2. Open in YAML
3. Add comment using `#`
4. Go back to visual editor
5. Save script
6. Open script again
7. Open in YAML
=> No comments anymore

### What version of Home Assistant Core has the issue?

2022.7.4

### In which browser are you experiencing the issue with?

Microsoft Edge 103.0.1264.62

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
Script
```

### Problem-relevant frontend configuration

```yaml
alias: Example
sequence:
  ## This comment will disappear once we reopen in YAML later
  - type: turn_off
    device_id: 123
    entity_id: light.light1
    domain: light
mode: single
```
