### ISSUE TITLE
Moving between lovelace pages rearranges pages instead

### ISSUE THREAD

**Issue by mariawarnes** [home-assistant/frontend#13229]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Tapping between mobile lovelace pages seems to be actioned as if the rearrange arrows were being pressed instead.

### Describe the behavior you expected

To move to the tapped page, rather than staying on the same one and rearranging it.

### Steps to reproduce the issue

1. Create multiple lovelace pages
2. On the mobile app on a mobile browser tap the three dots in the top-right
3. Tap 'Edit Dashboard'
4. Tap a lovelace page that you are not already on

### What version of Home Assistant Core has the issue?

2022.7.5

### In which browser are you experiencing the issue with?

Android Companion App 2022.6.0-full, Opera Browser (mobile) 70.3.3653.66287

### Which operating system are you using to run this browser?

Android 12

### Problem-relevant frontend configuration

```yaml
Simplified from my setup in the video but the issue still occurs for me with this raw configuration:

title: Home
views:
  - theme: Backend-selected
    icon: mdi:home
    visible:
      - user: 5d593a1778fd44e6a0e0520904d11765
      - user: 6746154764a94b6897c3f4b0bd30d777
    title: Home
    badges: []
    cards:
      - type: custom:mushroom-title-card
        title: |-
          {%- if now().hour < 12 -%}
            Morning
          {%- elif now().hour < 18 -%}
            Afternoon
          {%- else -%}
            Evening
          {%- endif %} {{user}}
      - type: conditional
        conditions:
          - entity: update.home_assistant_core_update
            state: 'on'
        card:
          type: custom:mushroom-template-card
          layout: horizontal
          tap_action:
            action: navigate
            navigation_path: /config/updates
          hold_action:
            action: none
          double_tap_action:
            action: none
          icon: mdi:download
          primary: 'Update '
          secondary: |
            Available
          multiline_secondary: false
          entity: calendar.maria_ewa_s_calendar
          fill_container: false
          icon_color: '#4caf50'
  - theme: Backend-selected
    icon: mdi:doorbell-video
    path: doorbell
    type: panel
    visible: []
    title: Doorbell
    badges:
      - entity: camera.doorbell
    cards:
      - type: grid
        square: false
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.doorbell_streaming_sensor
                state: 'False'
            card:
              type: picture-entity
              entity: camera.doorbell
              hold_action:
                action: none
              tap_action:
                action: call-service
                service: camera.turn_on
                target:
                  entity_id: camera.doorbell
          - type: conditional
            conditions:
              - entity: binary_sensor.doorbell_streaming_sensor
                state_not: 'off'
            card:
              type: custom:webrtc-camera
              entity: camera.doorbell
              ui: true
              shortcuts:
                services:
                  - name: Power Off
                    icon: mdi:power
                    service: camera.turn_off
                    service_data:
                      entity_id: camera.doorbell
        columns: 1
  - theme: Backend-selected
    icon: mdi:map-marker-radius
    path: map
    type: panel
    visible: []
    badges: []
    cards:
      - type: map
        entities:
          - entity: person.ewa
          - entity: person.maria
          - entity: zone.home
          - entity: zone.work_2
          - entity: zone.work
        hours_to_show: 24
```

### Javascript errors shown in your browser console/inspector

```txt
No errors are logged in the console when the issue occurs
```

### Additional information

Changing the pages I have not visible to visible does not seem to make any difference, neither does and adding names to the pages, the issue persists.

This issue does not happen when viewing on desktop browser (Opera 89.0.4447.48) at desktop width. If I emulate a mobile device on my browser or shrink my desktop browser to a mobile width I have (seemingly) inconsistent results - sometimes working perfectly; or changing the right icon to be selected, but not changing the page view; or changing to the right page view and icon and then quickly changing the page view back again without any user input; or just ignoring the click to change page completely.

https://user-images.githubusercontent.com/36001658/179790925-3b96e2c2-8d06-4200-9d54-26e20783a562.mp4
