### ISSUE TITLE
"Unknown error" after moving to 2022.7.6 from 2022.6.7

### ISSUE THREAD

**Issue by woody4165** [home-assistant/frontend#13251]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading from 2022.6.7 to 2022.7.6 I get an "Unknown Error" in my main YAML dashboard
I have other dashboards, not created with a YAML file, and they works fine.

This is the error detailed

Logger: homeassistant.components.websocket_api.http.connection
Source: util/yaml/loader.py:244
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:44:49 (10 occurrences)
Last logged: 11:03:17

[140099096153584] Error handling message: Unknown error (unknown_error)
[140099097172512] Error handling message: Unknown error (unknown_error)
[140099053092480] Error handling message: Unknown error (unknown_error)
[140099092935728] Error handling message: Unknown error (unknown_error)
[140098980824688] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 30, in send_with_error_handling
    result = await func(hass, connection, msg, config)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/websocket.py", line 72, in websocket_lovelace_config
    return await config.async_load(msg["force"])
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 186, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 205, in _load_config
    config = load_yaml(self.path, Secrets(Path(self.hass.config.config_dir)))
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 155, in load_yaml
    return parse_yaml(conf_file, secrets)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 168, in parse_yaml
    return _parse_yaml(SafeLoader, content, secrets)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 198, in _parse_yaml
    yaml.load(content, Loader=lambda stream: loader(stream, secrets))
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 325, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 356, in _construct_seq
    (obj,) = loader.construct_yaml_seq(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 325, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 356, in _construct_seq
    (obj,) = loader.construct_yaml_seq(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 325, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 356, in _construct_seq
    (obj,) = loader.construct_yaml_seq(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 246, in _include_yaml
    return _add_reference(load_yaml(fname, loader.secrets), loader, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 155, in load_yaml
    return parse_yaml(conf_file, secrets)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 168, in parse_yaml
    return _parse_yaml(SafeLoader, content, secrets)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 198, in _parse_yaml
    yaml.load(content, Loader=lambda stream: loader(stream, secrets))
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 325, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 356, in _construct_seq
    (obj,) = loader.construct_yaml_seq(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 325, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 246, in _include_yaml
    return _add_reference(load_yaml(fname, loader.secrets), loader, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 155, in load_yaml
    return parse_yaml(conf_file, secrets)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 168, in parse_yaml
    return _parse_yaml(SafeLoader, content, secrets)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 198, in _parse_yaml
    yaml.load(content, Loader=lambda stream: loader(stream, secrets))
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 325, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 356, in _construct_seq
    (obj,) = loader.construct_yaml_seq(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 325, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 244, in _include_yaml
    fname = os.path.join(os.path.dirname(loader.get_name()), node.value)
  File "/usr/local/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'

### Describe the behavior you expected

After upgrading from 2022.6.7 to 2022.7.6 I get an "Unknown Error" in my main YAML dashboard
I have other dashboards, not created with a YAML file, and they works fine.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.7.6

### What was the last working version of Home Assistant Core?

core-2022.6.7

### In which browser are you experiencing the issue with?

Opera and Chrome both last version

### Which operating system are you using to run this browser?

 Mac Big Sur and Windows 10

### Problem-relevant frontend configuration

```yaml
This is my configuration.yaml






homeassistant:
  # external_url: !secret conf_base_url
  # internal_url: !secret intern_url

  # allowlist_external_dirs:
    # - /tmp
    # - /share
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.1.0/24
    # - type: legacy_api_password
    - type: homeassistant

  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret conf_latitude
  longitude: !secret conf_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 21
  # metric fcor Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: on

  customize_glob:
    "sensor.*_battery":
      templates:
        icon_color: >
          if (state < 20) return 'rgb(255, 0, 0)';
          return 'rgb(0, 171, 0)';

  packages: !include_dir_named packages

lovelace:
  mode: yaml
  resources: !include includes/lovelace_resources.yaml

  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
    lovelace-irrigazione: # Needs to contain a hyphen (-)
      mode: yaml
      filename: lovelace-irrigazione.yaml
      title: Irrigazione
      icon: mdi:sprinkler
      show_in_sidebar: true
      require_admin: true

simpleicons:

influxdb:
  host: !secret influxdb_addr
  port: !secret influxdb_port
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_pwd
  ssl: false
  verify_ssl: false
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - sensor.sonoff_ch4pro_temperature
      - sensor.netatmo_estesa_temperature
      - sensor.netatmo_estesa_gust_strength
      - sensor.temp_letto_xiaomi
      - sensor.temp_giulia_xiaomi
      - sensor.temp_studio_xiaomi
      - sensor.temp_corridoio_su
      - sensor.temperatura_netatmo
      - sensor.shelly_em_channel_1_power
      - sensor.shelly_em_channel_1_voltage
      - sensor.apc_a_ups_load
      - sensor.bme280_temperatura
      - sensor.rpi_adguard_cpu_percent
      - sensor.rpi_adguard_disk_used
      - sensor.rpi_adguard_memory_used
      - sensor.rpi_adguard_temperature
  # component_config_glob:
  #   sensor.*temp*:
  #     override_measurement: temperatura
  component_config:
    sensor.shelly_em_channel_1_power:
      override_measurement: corrente
    sensor.shelly_em_channel_1_voltage:
      override_measurement: voltaggio
    sensor.apc_a_ups_load:
      override_measurement: carico ups



webhook:

system_log:
  fire_event: true

ffmpeg:

recorder:
  purge_keep_days: 7
  auto_purge: false
  commit_interval: 1
  #  db_url: !secret mariadb_url
  include:
    domains:
#      - switch
#      - light
      - climate
      # - person
    entities:
      - device_tracker.google_maps_113671458934018013614
      - binary_sensor.vittorio_presence
      - binary_sensor.giulia_presence
      - sensor.temp_giulia_xiaomi
      - sensor.temp_giulia_xiaomi_2
      - sensor.temp_giulia_xiaomi_3
      - sensor.temp_letto_xiaomi_2
      - sensor.temp_letto_xiaomi
      - sensor.temp_letto_xiaomi_3
      - sensor.temp_sala_xiaomi_2
      - sensor.temp_sala_xiaomi_3
      - sensor.temp_sala_xiaomi
      - sensor.temp_studio_xiaomi
      - sensor.temp_studio_xiaomi_2
      - sensor.temp_studio_xiaomi_3
      - sensor.temp_corridoio_su
      - sensor.temp_corridoio_su_2
      - sensor.temp_corridoio_su_3
      - sensor.temp_esterno_soggiorno
      - sensor.temp_esterno_soggiorno_2
      - sensor.temp_esterno_soggiorno_3
      - sensor.patio_umidita
      - sensor.patio_temp
      - sensor.illumination_286c0785abb8
      - binary_sensor.sensore_ingresso
      - binary_sensor.sensore_finestra_sala
      - binary_sensor.sensore_finestra_bagno
      - binary_sensor.sensore_finestra_cucina
      - binary_sensor.sensore_lucernario
      - sensor.caldaia
      - sensor.caldaia_accesa
      - sensor.mcc_power
      - sensor.comodino_power
      - sensor.lavatrice_power
      - sensor.lavastoviglie_power
      - sensor.caldaia_hr
      - sensor.temperatura_netatmo
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.temp_shelly_2_5_finestra_sala
      - sensor.hass_db_size
      - sensor.cpu_load
      - sensor.cpu_temp
      - sensor.available_memory
      - sensor.disk_use_percent_home
      - sensor.memory_free
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.nuc_cpu1
      - sensor.nuc_cpu_temp
      - sensor.nodered_available_memory
      - sensor.nodered_cpu_load
      - sensor.qnapb3c_cpu_usage
      - sensor.qnapb3c_memory_usage
      - sensor.qnapb3c_status
      - sensor.qnapb3c_system_temperature
      - sensor.qnapb3c_temperature_drive_1
      - sensor.qnapb3c_temperature_drive_2
      - sensor.temp_cupola
      - sensor.shelly_em_channel_1_energy
      - sensor.shelly_em_channel_1_power
      - sensor.lavastoviglie_energy_total
      - sensor.presa_frigo_energy
      - sensor.teckin1_lavatrice_energy_total
      - sensor.shelly_em_channel_1_voltage
      - sensor.shelly_em_online
      - sensor.frigo_power
      - sensor.shelly_shplg_s_041662_current_consumption
      - sensor.temp_soggiorno
      - sensor.temp_soggiorno_2
      - sensor.temp_soggiorno_3
      - sensor.shelly_shem_b9e0a1_1_current_consumption
      - sensor.frigo_daily_kwh
      - sensor.frigo_monthly_kwh
      - sensor.frigo_consumo
      - sensor.portante_download_agganciata
      - sensor.portante_upload_agganciata
      - sensor.shelly_plug_s_frigo_power
      - sensor.shelly_plug_s_frigo_energy
      - sensor.shelly_plug_s_frigo_temp

      - sensor.shelly_shem_b9e0a1_1_current_consumption
      - sensor.shelly_em_channel_1_energy_cost
      - sensor.shelly_em_rssi
      - sensor.esphome_irrigation_controller_wifi_signal
      - sensor.sonoff_ch4pro_temperature
      - sensor.sonoff_ch4pro_humidity

      - sensor.netatmo_estesa_wind_strength
      - sensor.netatmo_estesa_gust_strength
      - sensor.netatmo_estesa_pioggia_ora
      - sensor.netatmo_estesa_pioggia_1h
      - sensor.netatmo_estesa_pioggia_oggi
      - sensor.netatmo_estesa_temperature
      - sensor.netatmo_estesa_humidity
      - sensor.netatmo_estesa_pressure

      - sensor.bme280_pressione
      - sensor.bme280_temperatura
      - sensor.bme280_umidita

  exclude:
    domains:
      - sensor
      - binary_sensor
      - automation
      - weblink
      - updater
      - media_player
      - switch
      - light
    entities:
      - sun.sun
      - camera.meteoeu
      - camera.meteoit
      - camera.patio
      - camera.porta
      - camera.vialetto
      - sensor.last_boot
      - switch.smart_surge_protector_main_switch
      - switch.smart_surge_protector_powerline
      - switch.smart_surge_protector_router_cam
      - switch.smart_surge_protector_usb
      - switch.smart_surge_protector_wii

    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - feedreader
      - service_registered
      - call_service
      - component_loaded

smartir:



# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

panel_iframe:
  traffic_g:
    title: Traffico google_maps
    icon: mdi:car
    url: /local/traffic.html

  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin_url


hassio:

system_health:

websocket_api:

mobile_app:


http:
  ip_ban_enabled: false
  login_attempts_threshold: 5
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

  # base_url: !secret conf_base_url

  # server_host: 127.0.0.1
  # use_x_forwarded_for: true
  # trusted_proxies: 127.0.0.1

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

input_select: !include includes/input_select.yaml
input_text: !include includes/input_text.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_datetime: !include includes/input_datetime.yaml

device_tracker: !include includes/device_tracker.yaml

cover: !include includes/cover.yaml



discovery:

conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
#      - switch
#      - light
      - climate
#      - person
    entities:
      - device_tracker.google_maps_113671458934018013614
      - binary_sensor.vittorio_presence
      - binary_sensor.giulia_presence
      - sensor.temp_giulia_xiaomi
      - sensor.temp_giulia_xiaomi_2
      - sensor.temp_giulia_xiaomi_3
      - sensor.temp_letto_xiaomi_2
      - sensor.temp_letto_xiaomi
      - sensor.temp_letto_xiaomi_3
      - sensor.temp_sala_xiaomi_2
      - sensor.temp_sala_xiaomi_3
      - sensor.temp_sala_xiaomi
      - sensor.temp_studio_xiaomi
      - sensor.temp_studio_xiaomi_2
      - sensor.temp_studio_xiaomi_3
      - sensor.temp_corridoio_su
      - sensor.temp_corridoio_su_2
      - sensor.temp_corridoio_su_3
      - sensor.temp_esterno_soggiorno
      - sensor.temp_esterno_soggiorno_2
      - sensor.temp_esterno_soggiorno_3
      - sensor.patio_umidita
      - sensor.patio_temp
      - sensor.illumination_286c0785abb8
      - binary_sensor.sensore_ingresso
      - binary_sensor.sensore_finestra_sala
      - binary_sensor.sensore_finestra_bagno
      - binary_sensor.sensore_finestra_cucina
      - binary_sensor.sensore_lucernario
      - sensor.caldaia
      - sensor.caldaia_accesa
      - sensor.mcc_power
      - sensor.comodino_power
      - sensor.lavatrice_power
      - sensor.lavastoviglie_power
      - sensor.caldaia_hr
      - sensor.temperatura_netatmo
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.temp_shelly_2_5_finestra_sala
      - sensor.hass_db_size
      - sensor.cpu_load
      - sensor.cpu_temp
      - sensor.available_memory
      - sensor.disk_use_percent_home
      - sensor.memory_free
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.nuc_cpu1
      - sensor.nuc_cpu_temp
      - sensor.nodered_available_memory
      - sensor.nodered_cpu_load
      - sensor.qnapb3c_cpu_usage
      - sensor.qnapb3c_memory_usage
      - sensor.qnapb3c_status
      - sensor.qnapb3c_system_temperature
      - sensor.qnapb3c_temperature_drive_1
      - sensor.qnapb3c_temperature_drive_2
      - sensor.temp_cupola
      - sensor.shelly_em_channel_1_energy
      - sensor.shelly_em_channel_1_power
      - sensor.lavastoviglie_energy_total
      - sensor.presa_frigo_energy
      - sensor.teckin1_lavatrice_energy_total
      - sensor.shelly_em_channel_1_voltage
      - sensor.shelly_em_online
      - sensor.frigo_power
      - sensor.shelly_shplg_s_041662_current_consumption
      - sensor.temp_soggiorno
      - sensor.temp_soggiorno_2
      - sensor.temp_soggiorno_3
      - sensor.shelly_shem_b9e0a1_1_current_consumption
      - sensor.frigo_daily_kwh
      - sensor.frigo_monthly_kwh
      - sensor.frigo_consumo
      - sensor.portante_download_agganciata
      - sensor.portante_upload_agganciata
      - sensor.shelly_plug_s_frigo_power
      - sensor.shelly_plug_s_frigo_energy
      - sensor.shelly_plug_s_frigo_temp

      - sensor.shelly_shem_b9e0a1_1_current_consumption
      - sensor.shelly_em_channel_1_energy_cost
      - sensor.shelly_em_rssi
      - sensor.esphome_irrigation_controller_wifi_signal
      - sensor.sonoff_ch4pro_temperature
      - sensor.sonoff_ch4pro_humidity

      - sensor.netatmo_estesa_wind_strength
      - sensor.netatmo_estesa_gust_strength
      - sensor.netatmo_estesa_pioggia_ora
      - sensor.netatmo_estesa_pioggia_1h
      - sensor.netatmo_estesa_pioggia_oggi
      - sensor.netatmo_estesa_temperature
      - sensor.netatmo_estesa_humidity
      - sensor.netatmo_estesa_pressure

      - sensor.bme280_pressione
      - sensor.bme280_temperatura
      - sensor.bme280_umidita

  exclude:
    domains:
      - sensor
      - binary_sensor
      - automation
      - weblink
      - updater
      - media_player
      - switch
      - light
    entities:
      - sun.sun
      - camera.meteoeu
      - camera.meteoit
      - camera.patio
      - camera.porta
      - camera.vialetto
      - sensor.last_boot
      - switch.smart_surge_protector_main_switch
      - switch.smart_surge_protector_powerline
      - switch.smart_surge_protector_router_cam
      - switch.smart_surge_protector_usb
      - switch.smart_surge_protector_wii

# View all events in a logbook
logbook:

default_config:

logger:
  # default: error

  default: warn
  logs:
    homeassistant.bootstrap: info
    pydaikin: critical
    custom_components.device_tracker: debug


map:

rflink:
  host: !secret rflink_addr
  port: 1234
  ignore_devices:
    - lobeco_*
    - bft_*
    - aster_*
    - bosch_*
    - drayton_*

    - auriol_*
    - globaltronics_*
    - alectov1_*
    - renkforcee_ta_*
    - fineoffset_*
    - bl999_*
    - owl_cm180_*
    - deltronic_*
    - ningbo64_*
    - friedland_*
    - v2phoenix_*
    - digitech_*
    - firstline_*

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_allowed_chat_ids

notify:
  # - platform: alexa_media
  #   name: alexa_media
  - name: Telegram
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_allowed_chat_ids
  - platform: file
    name: filenotify
    filename: /share/daily_power.csv
    #timestamp: true
  - platform: file
    name: log_irrigation
    filename: my-log-irrigation.log

# Track the sun
sun:

mqtt: !include mqtt.yaml


sensor: !include sensors.yaml

light: !include lights.yaml



xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key
      host: !secret xiaomi_host

fan:
  - platform: smartir
    name: Ventilatore
    unique_id: ventilatore
    device_code: 1180
    controller_data: remote.broadlink_soggiorno
  - platform: template
    fans:
      ventilatore_sala:
        friendly_name: "Ventilatore Sala"
        value_template: "{{ states('switch.ventilatore') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.ventilatore_on_off
        turn_off:
          service: switch.turn_off
          entity_id: switch.ventilatore_on_off
        set_percentage:
          service: switch.toggle
          entity_id: switch.ventilatore_speed
        set_oscillating:
          service: switch.toggle
          entity_id: switch.ventilatore_oscilla


#    power_sensor: binary_sensor.fan_power

climate:
  - platform: smartir
    name: "AC Studio"
    unique_id: ac_studio
    device_code: 1400
    controller_data: remote.broadlink_mini_studio
    temperature_sensor: sensor.temp_studio_xiaomi
    humidity_sensor: sensor.temp_studio_xiaomi_2

  - platform: smartir
    name: "AC Giulia"
    unique_id: ac_giulia
    device_code: 1400
    controller_data: remote.broadlink_mini_giulia
    temperature_sensor: sensor.temp_giulia_xiaomi
    humidity_sensor: sensor.temp_giulia_xiaomi_2

  - platform: smartir
    name: "AC Letto"
    unique_id: ac_letto
    device_code: 1761
    controller_data: remote.broadlink_letto
    temperature_sensor: sensor.temp_letto_xiaomi
    humidity_sensor: sensor.temp_letto_xiaomi_2

  - platform: smartir
    name: "AC Sala"
    unique_id: ac_sala
    device_code: 1400
    controller_data: remote.broadlink_soggiorno
    temperature_sensor: sensor.temp_sala_xiaomi
    humidity_sensor: sensor.temp_sala_xiaomi_3



stream:


rest_command:
  google_backup:
    url: "http://localhost:8055/gb/doBackup"
    timeout: "300"

media_player: !include includes/media_player.yaml



switch: !include switches.yaml

camera: !include includes/camera.yaml

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: true

####################################################

google_assistant:
  project_id: !secret ga_project_id
  service_account: !include HassioB3C_service_account_Token_GiuMaps-85068c8fb24c.json
  exposed_domains:
    - climate
    - switch
    - light

####################################################

# Text to speech
tts:
  - platform: google_translate
    language: "it"

person: !include persons.yaml



#utility_meter: !include utility_meter.yaml
utility_meter:
  energy_daily:
    source: sensor.energy_spent
    cycle: daily
    tariffs:
      - peak
      - offpeak
  energy_monthly:
    source: sensor.energy_spent
    cycle: monthly
    tariffs:
      - peak
      - offpeak

  frigo_energy_daily:
    source: sensor.frigo_energy_spent
    cycle: daily
    tariffs:
      - peak
      - offpeak
  frigo_energy_monthly:
    source: sensor.frigo_energy_spent
    cycle: monthly
    tariffs:
      - peak
      - offpeak

binary_sensor: !include binary_sensors.yaml

# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

browser_mod:
  devices:
    191bc56a-5ecd9354:
      name: Mac_Chrome

lovelace_gen:



garbage_collection:
  sensors:
    - name: "Umido" # No collection on Christmas, added extra collection on the 27th
      frequency: "weekly"
      collection_days:
        - tue
        - thu
        - sat
    - name: "Indifferenziato" # No collection on Christmas, added extra collection on the 27th
      frequency: "weekly"
      collection_days:
        - tue
    - name: "Carta" # No collection on Christmas, added extra collection on the 27th
      frequency: "weekly"
      collection_days:
        - thu
    - name: "Plastica" # No collection on Christmas, added extra collection on the 27th
      frequency: "weekly"
      collection_days:
        - sat
    - name: "Sfalci" # No collection on Christmas, added extra collection on the 27th
      frequency: "weekly"
      collection_days:
        - wed

alarm_control_panel:
  - platform: mqtt
    name: "Alarm-Part1"
    command_topic: "paradox/control/partitions/Area_1"
    state_topic: "paradox/states/partitions/Area_1/current_state"
    payload_arm_away: "arm"
    payload_arm_home: "arm_stay"
    payload_arm_night: "arm_sleep"
    payload_disarm: "disarm"



saver:
#
```
