### ISSUE TITLE
Illuminance - Automation condition configuration doesn't work properly 

### ISSUE THREAD

**Issue by rotilho** [home-assistant/frontend#13314]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to create a condition that check illuminance the UI don't display the fields above below.

### Describe the behavior you expected

I expected to be able to use those fields

### Steps to reproduce the issue

1. Pair a sensor that expose illuminance
2. Create an automation
3. In the conditions section try to add a condition that is just triggered when illuminance below some level

### What version of Home Assistant Core has the issue?

2022.7.6

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Google Chrome 103.0.5060.134

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
State: 14800

Properties:
 - state_class: measurement
- device_class: illuminance
- friendly_name: Felipe's Room Motion Sensor illuminance
```

### Problem-relevant frontend configuration

```yaml
type: is_illuminance
condition: device
device_id: 020eb89be1bcf7128769bae7d4f1b471
entity_id: sensor.felipe_s_room_motion_sensor_illuminance
domain: sensor
below: 5000
```

### Javascript errors shown in your browser console/inspector

```txt
No error
```

### Additional information

![image](https://user-images.githubusercontent.com/950510/182086709-dc0075c4-7c3f-4a5e-999d-ef6f6f95be36.png)
