### ISSUE TITLE
entity-filter operators don't work as intended with state as a value and == operator

### ISSUE THREAD

**Issue by Quentame** [home-assistant/frontend#13343]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I want to display a list of cheapest gas station.

Once having the price of nearest stations, I created a min/max helper with those sensors, and now I want to display stations with the cheapest price.
So when [min price] == price

The problem is that I can't display filtered stations because the state_filter operator don't seems to work properly.

Now, with `operator: <=` !!

![image](https://user-images.githubusercontent.com/14821482/183105400-5eab6e4f-fa5b-45a4-9e95-9f36c3734479.png)

```
type: entity-filter
entities:
  - sensor.station_auchan_saint_priest_e10
  - sensor.station_carrefour_venissieux_e10
  - sensor.station_leclerc_drive_e10
  - sensor.prix_carburant
state_filter:
  - operator: <=
    value: sensor.prix_carburant
card:
  title: Stations essence les moins chères
  type: entities
```

With `operator: ==` !!

![image](https://user-images.githubusercontent.com/14821482/183108567-de8e8f70-bcff-44cb-8599-cb3cbfb14394.png)

code 
```
type: entity-filter
entities:
  - sensor.station_auchan_saint_priest_e10
  - sensor.station_carrefour_venissieux_e10
  - sensor.station_leclerc_drive_e10
  - sensor.prix_carburant
state_filter:
  - operator: ==
    value: sensor.prix_carburant
card:
  title: Stations essence les moins chères
  type: entities
```

Then one with the red cross should be filtered, and the last line (lined with yellowed) indicate the min price and is here for this demo only.

----

While writing this issue I've noticed that the value of the value attribute is the cause of that

![image](https://user-images.githubusercontent.com/14821482/183114371-6dd395b8-40ec-4055-a182-20502500d3c2.png)

![image](https://user-images.githubusercontent.com/14821482/183114733-2915da3c-eac2-44d8-a5e8-2a55a31069bf.png)

Apparently it's impossible to assigne a state to the value attribute.

Tried with curly, same results

![image](https://user-images.githubusercontent.com/14821482/183115131-d72a301d-65e5-43d0-bf97-e7ea9a2b3ace.png)

----

There is an issue with `==` operator, see

![image](https://user-images.githubusercontent.com/14821482/183115654-62e35a6b-d53d-46b7-9c99-6c63881672b8.png)

![image](https://user-images.githubusercontent.com/14821482/183115858-3258e90c-6010-484f-92d7-c8a49cc93185.png)

![image](https://user-images.githubusercontent.com/14821482/183115737-fd3709bd-a330-4a69-aed1-5a744f36778c.png)

### Describe the behavior you expected

1. state should be a good parameter of state_filter.value
2. `operator: ==` should display equals values

### Steps to reproduce the issue

1. Create 3 helper `input_number` with values 1, 2 & 3
2. Create an entity-filter card like this
```
type: entity-filter
entities:
  - input_number.test1
  - input_number.test2
  - input_number.test3
state_filter:
  - operator: <=
    value: 2
card:
  type: entities
```
It's working
3.  Create an entity-filter card like this
```
type: entity-filter
entities:
  - input_number.test1
  - input_number.test2
  - input_number.test3
state_filter:
  - operator: <=
    value: input_number.test2
card:
  type: entities
```
It's not working
4. same for `operator: ==`

### What version of Home Assistant Core has the issue?

core-2022.8.0

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Microsoft Edge 102.0.1245.50, Safari iOS 15.6

### Which operating system are you using to run this browser?

Windows 10, iOS 15.6

### Javascript errors shown in your browser console/inspector

Exemple with gas station price only, not applicable to test bench
```shell
       RangeError: Invalid currency code : â¬
    at new NumberFormat (<anonymous>)
    at A (86066a2d.js:1:35223)
    at h (95446709.js:1:1244)
    at p (95446709.js:1:922)
    at F.value (hui-sensor-entity-row.ts:72:1)
    at F.update (styles.ts:370:1)
    at F.performUpdate (styles.ts:370:1)
    at F.scheduleUpdate (styles.ts:370:1)
    at F._$EC (styles.ts:370:1)
```

### Additional information

Documentation: https://www.home-assistant.io/dashboards/entity-filter/#operator
