### ISSUE TITLE
Changing entities in the Statistics Graph Card visual editor removes entity friendly names

### ISSUE THREAD

**Issue by cremor** [home-assistant/frontend#13369]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Friendly entity names in the Statistics Graph Card are lost when the card configuration is changed in the visual editor.

### Describe the behavior you expected

Friendly entity names should be preserved when the card configuration is changed in the visual editor.

### Steps to reproduce the issue

1. Create a Statistics Graph Card and configure friendly entity names in the YAML configuration of the card as shown in the example in the [documentation](https://www.home-assistant.io/dashboards/statistics-graph/#example).
2. Save the card.
3. Reopen the configuration of the card.
4. Add an additional entity via the UI.
5. Switch to the YAML configuration of the card - notice that the friendly entity names are gone.
  OR
6. Save the card - notice that the friendly entity names are gone.

### What version of Home Assistant Core has the issue?

core-2022.8.3

### In which browser are you experiencing the issue with?

Firefox 103.0.1, Edge 104.0.1293.47

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: hour
days_to_show: 7
type: statistics-graph
entities:
  - entity: sensor.wohnzimmer_inside_temperature
    name: Wohnzimmer
  - entity: sensor.temperatur_bad
    name: Bad
  - entity: sensor.temp_schlafzimmer_temperature
    name: Schlafzimmer
stat_types:
  - mean
  - max
  - min
```
