### ISSUE TITLE
picture-glance card doesn't open video stream if you add entity for privacy state_filter

### ISSUE THREAD

**Issue by alexruffell** [home-assistant/frontend#13417]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I wanted an easy way to hide camera streams so I can show a dashboard or take screenshots without showing the camera view. This can easily be achieved with a state_filter but I ran into an undesired (IMO) side effect. When I added the state_filter option controlled by an input_boolean used to turn on/off the privacy mode (displayed in the same picture-glance card), I could no longer click on the image to get a larger live feed. When you add entities in the picture glance-card, and click on the image, you now get the history of one of the entities you added (even if it is the camera entity). I fail to see the reason and usefulness for this unexpected behavior so I am hoping it is a bug that can be corrected (and not per design).

<img width="333" alt="image" src="https://user-images.githubusercontent.com/4006944/185688264-10251083-cfb1-430b-a12f-9262d4ae80e9.png">

My work around was to add an additional entity pointing to the same camera so that by clicking that icon, the feed opens but this is less intuitive and not as easy on small screens than clicking the image anywhere.

Below is my YAML:

```
type: picture-glance
title: Driveway - East
entities:
  - entity: input_boolean.driveway_east_camera_privacy
  - entity: camera.driveway_east_camera
camera_image: camera.driveway_east_camera
aspect_ratio: '16:9'
camera_view: live
state_filter:
  'on': brightness(40%) blur(10px) saturate(0.0)
  'off': brightness(100%)
entity: input_boolean.driveway_east_camera_privacy
```

### Describe the behavior you expected

Expected behavior was that clicking the image, the larger live feed will open (default behavior) instead of getting the history of one of the entities. I tried this with just the boolean, or just the camera, and in both cases I got the history which seems pointless.

### Steps to reproduce the issue

1. Add entity to picture-glance card used to show a camera feed
2. Click on camera image
3. History window will open instead of camera feed
...

### What version of Home Assistant Core has the issue?

core-2022.8.5

### In which browser are you experiencing the issue with?

Google Chrome 104.0.5112.81 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11
