### ISSUE TITLE
Thermostat card shows 3 temperatures controls when in Heat/Cool mode

### ISSUE THREAD

**Issue by fenichelar** [home-assistant/frontend#13450]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When in Heat/Cool mode, the Thermostat card is showing 3 temperatures controls instead of 2:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/3437075/186093708-2f1e81e1-3a1a-426a-8ca0-d94d34b87287.png">

Changing either of the two temperatures that shows 67 resulted in both temperatures controls changing.

When in Heat or when in Cool mode, 1 temperature control is shown as expected:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/3437075/186093799-f17b5c1f-b7c0-4cac-be25-4a58cb4fc9b9.png">

### Describe the behavior you expected

2 temperature controls should be shown when in Heat/Cool mode, not 3.

### Steps to reproduce the issue

Clean install with zwavejs2mqtt, Z-Wave JS, Z-Wave thermostat (e.g., Honeywell TH6320ZW). Click triple dot icon on top right of Thermostat card.

### What version of Home Assistant Core has the issue?

2022.8.6

**Comment by spacegaier** [comment]
Can you please post the entity state YAML here for when the entity is in the state that three inputs are shown. Then we can try to reproduce it locally and potentially fix.

**Comment by fenichelar** [comment]
State YAML below:

```yaml
hvac_modes:
  - 'off'
  - heat
  - cool
  - heat_cool
min_temp: 44.6
max_temp: 95
fan_modes:
  - Auto low
  - Low
  - Circulation
preset_modes:
  - none
  - Energy heat
  - Energy cool
current_temperature: 70
temperature: 67
target_temp_high: 70
target_temp_low: 67
current_humidity: 43
fan_mode: Circulation
hvac_action: cooling
preset_mode: none
fan_state: Running / running low
friendly_name: Downstairs Thermostat
supported_features: 27
```

I believe the frontend is showing controls for `temperature`, `target_temp_low`, and `target_temp_high`.
