### ISSUE TITLE
Automation Trigger doesn't allow negative values (e.g. temperature bellow -3)

### ISSUE THREAD

**Issue by gmlupatelli** [home-assistant/frontend#13493]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Front end doesn't allow the inclusion o "-" when setting automation triggers with numeric values.

The picture below shows an example of a trigger for a temperature sensor that doesn't allow the use of "-" sign.
![image](https://user-images.githubusercontent.com/40525606/186733924-afa4cf8e-8ce5-41ec-aa17-3bb3299fb437.png)

### Describe the behavior you expected

The fields Above and Bellow should accept the "-" sign to allow negative values

### Steps to reproduce the issue

1. Create a new automation not based on a blueprint
2. Select a trigger device that requires a numeric value, like temperature or humidity changes
3. Select the Above or Bellow field and type "-"

### What version of Home Assistant Core has the issue?

Home Assistant 2022.8.6

### What was the last working version of Home Assistant Core?

Could not check.

### In which browser are you experiencing the issue with?

Google Chrome 104.0.5112.102 (Official Build) (64-bit) and Microsoft Edge Version 104.0.1293.63 

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
alias: New Automation
description: ""
mode: single
trigger:
  - type: temperature
    platform: device
    device_id: xxxxxxxxxxxxxxxxxxxxxxxxxx
    entity_id: sensor.basement_environment_temperature
    domain: sensor
    above: 3
condition: []
action:
  - device_id: ""
    domain: ""
    entity_id: ""
```

### Additional information

It is possible to work around this issue by directly editing the automation YAML. When you do that, the negative value persists when moving back to the visual editor. Given that the problem lies with the field character input validation.
