### ISSUE TITLE
Automations: shorthand conditions are not supported by (and can "crash") UI editor [2022.9.0b6]

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#13643]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

"Shorthand" template conditions are not supported by updated UI editor and can cause serious issues when placed in the root of actions: or conditions: block

If it's placed in the root of `conditions:` / `actions:` then entire list becomes invisible and uneditable from UI.

If it's placed inside `choose:` | `if:` action nor `and:` | `or:` | `not:` condition it will not display actions/conditions list for that block only and will prevent adding new ones from UI.

They cannot be placed inside `parallel:` (or `parallel: > sequence:` where it makes more sense) action at all - that might be a separate issue.

### Describe the behavior you expected

"Shorthand" template conditions are not supported by UI editor.

### Steps to reproduce the issue

1. Create or edit automation
2. Enter YAML mode
3. Create shorthand template condition

### What version of Home Assistant Core has the issue?

core-2022.9.0b6

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102, Mozilla Firefox 105beta, Android mobile app 2022.8

### Which operating system are you using to run this browser?

Windows 10, android 11

### Problem-relevant frontend configuration

```yaml
alias: 2022.9.beta - shorthand test
description: ""
trigger: []
condition:
  # will affect only "or:" condition block
  - or:
      - "{{ true }}"
      - "{{ true }}"
  - and:
      - "{{ true }}"
      - "{{ true }}"
  - not:
      - "{{ true }}"
      - "{{ true }}"
  # putting one in the root will crash entire conditions list
  - "{{ true }}"
action:
  - if:
      - "{{ true }}"
      - "{{ true }}"
    then: []
  - choose:
      - conditions:
          - "{{ true }}"
          - "{{ true }}"
        sequence: []
  - parallel:
      - sequence:
           # cannot be added inside parallel: at all
         - "{{ true }}"
         - <action>
```

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) TypeError: WeakMap key must be an object, got e
    value https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/3664b061.js:1993
    value https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/3664b061.js:1943
    dt https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/4201eade.js:2
    update https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/4201eade.js:2
    _$AS https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    D https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    _$AI https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    m https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    T https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    _$AI https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    S https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    update https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    performUpdate https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    scheduleUpdate https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
    _$EC https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/app.ef7cfda5.js:1249
6 3664b061.js:1993:697
```
