### ISSUE TITLE
Actions inside choose block cannot be reordered [2022.9.0b6]

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#13642]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Actions inside `choose` block cannot be reordered. 
Conditions are reorder-able just fine.

### Describe the behavior you expected

Actions can be re-orderd inside any block.

### Steps to reproduce the issue

1. Create or edit automation
2. Create choose block with any conditions and at least 2 actions
3. Select "Re-order" option from 3-dots menu

### What version of Home Assistant Core has the issue?

core-2022.9.0b6

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102, Mozilla Firefox 105beta, Android mobile app 2022.8

### Which operating system are you using to run this browser?

Windows 10, android 11

### Problem-relevant frontend configuration

```yaml
action:
  - choose:
      - conditions:
          - <condition>
        sequence:
          - <action>
          - <action>
```

### Javascript errors shown in your browser console/inspector

```txt
none
```
