### ISSUE TITLE
Picture Glance Card Entity buttons aren't right-aligned

### ISSUE THREAD

**Issue by ams3401** [home-assistant/frontend#13654]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![2v](https://user-images.githubusercontent.com/70864968/189023092-e08730ff-189f-4581-ad4d-3b667e191c49.JPG)

The entity buttons on the bottom fo the picture glance card are floating in the second column instead of being on the third.

### Describe the behavior you expected

![1v](https://user-images.githubusercontent.com/70864968/189023180-eb01f082-d0c4-40d9-a2e6-51877fed2c32.JPG)

### Steps to reproduce the issue

1. Installed picture glance card
2. Went on a test dashboard
3. Added picture glance card

### What version of Home Assistant Core has the issue?

Latest

**Comment by ildar170975** [comment]
Post your problem code.

Here my tests:
2022.7:
![image](https://user-images.githubusercontent.com/71872483/189052865-714e09ec-7d20-4e46-8a19-a215224b82e5.png)

2022.9:
![image](https://user-images.githubusercontent.com/71872483/189052815-de1b16a7-9ace-4dce-ab3a-862bb184a5c2.png)

```
type: picture-glance
title: title
image: /local/images/test/blue.jpg
entities:
  - entity: sun.sun
  - entity: sun.sun
  - entity: input_boolean.test_boolean
  - entity: input_boolean.test_boolean
```

Icons on same positions.
And last year (April 2021) they were on same places too - [check this post](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1689?u=ildar_gabdullin).
