### ISSUE TITLE
Core 2022.9.0 redesigned automation editor problem (bug?)

### ISSUE THREAD

**Issue by vaibhav2912** [home-assistant/frontend#13655]
### The problem

I upgraded to HA core 2022.9.0 today.

I noticed that when I create a new automation, save it and then go back in that automation, without even editing anything, I get the save popup and if I try to back out of the automation also without changing anything, I get a popup saying "You have unsaved changes".

The same thing is happening with automations that were disabled when I upgraded to core 2022.9.0. Even if I now enable those automations, same thing happens.

Automations that were already present and enabled when I upgraded to core 2022.9.0 are OK.

Short video to explain the scenario completely.

https://user-images.githubusercontent.com/20019445/189010914-495b14cd-1ea1-4692-a2e2-c8022f4718ef.mp4

### What version of Home Assistant Core has the issue?

2022.9.0

### What was the last working version of Home Assistant Core?

2022.8.7

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Link to integration documentation on our website

https://www.home-assistant.io/docs/automation/

### Anything in the logs that might be useful for us?

```txt
Nothing in logs
```

**Comment by Digita1Boy** [comment]
Found the cause of this bug. It seems to be related to whether you populate the optional state values for the trigger

If you provide the optional values and save the automation, when you open the automation in the UI editor (and do nothing), the save button does not appear, you can exit without being prompted to save changes. Behavior as expected.

If you do NOT provide the optional state values, then when you open the automation in the UI editor (and again do nothing), the save button DOES appear. When you exit after making no changes, you are prompted to either stay or leave. Behavior unexpected.

**Optional Values Provided - no error**
```yaml
alias: New Automation Editor Bug - no error (optional from/to provided)
description: ""
trigger:
  - platform: state
    entity_id:
      - person.digitalboy
    from: home
    to: not_home
condition: []
action: []
mode: single
```

**Optional value not provided - error**
```yaml
alias: New Automation Editor Bug - ERROR (optional from/to not provided)
description: ""
trigger:
  - platform: state
    entity_id:
      - person.digitalboy
condition: []
action: []
mode: single
```
