### ISSUE TITLE
"Unsaved Changes" after leaving automation without any changes

### ISSUE THREAD

**Issue by Xitee1** [home-assistant/frontend#13665]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For some reason, only by one of my automation (I didn't test all, but it didn't happened on any other of my automations) it says that I have unsaved changes without doing anything. I don't know what's different on this one. I also just noticed, that the "Save" button immediatly comes up.

### Describe the behavior you expected

That I can go straight back to the automation dashboard without an popup coming up.

### Steps to reproduce the issue

1. Open the automation
2. Try to leave without making any changes
3. Get that popup

### What version of Home Assistant Core has the issue?

core-2022.9.0

### In which browser are you experiencing the issue with?

Firefox, Chrome

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
alias: "3D Drucker: Auto shutdown"
description: Automatically shutdown & turn off 3D printer when not connected for 18h
trigger:
  - platform: state
    entity_id:
      - sensor.octoprint_current_state
    to: unavailable
    for:
      hours: 18
      minutes: 0
      seconds: 0
condition: []
action:
  - service: script.3d_drucker_shutdown
    data: {}
mode: single
```

### Javascript errors shown in your browser console/inspector

```txt
Die Ressource unter "http://homeassistant.local:8123/static/fonts/roboto/Roboto-Regular.woff2" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind.

(Sorry that this is in german, idk how to change it to english.)
```

### Additional information

![firefox_iHdR3uMSMc](https://user-images.githubusercontent.com/59659167/189198515-7f03f2ec-06ed-4dd2-a7f8-1436e42549ff.gif)
