### ISSUE TITLE
Sunrise offset not shown in condition description

### ISSUE THREAD

**Issue by rinzeb** [home-assistant/frontend#13797]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an automation with two conditions, to check whether the time is between sunrise and sunset, both with an offset of 1 hour. The condition for after sunset shows the amount of offset, whereas the similar condition for before sunrise does not show the offset. I've attached a screenshot for clarity.

![image](https://user-images.githubusercontent.com/11523459/190876905-bed25777-aa9b-425b-838f-b9c9ed5c6afe.png)

### Describe the behavior you expected

I'd expect the summary of the first condition description to be: 
`Confirm sun before sunrise offset by 1:00`.

### Steps to reproduce the issue

1. Create a condition with trigger sun.
2. Select `before sunrise` with an offset of 1:00
![image](https://user-images.githubusercontent.com/11523459/190876973-2099d303-06d9-47e9-b05f-4a0f414f840c.png)

### What version of Home Assistant Core has the issue?

2022.9.4

### In which browser are you experiencing the issue with?

Android app of Home Assistant and Opera

### Which operating system are you using to run this browser?

Android and Windows

### Problem-relevant frontend configuration

```yaml
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.sensor_1_occupancy
    from: "off"
    to: "on"
condition:
  - condition: or
    conditions:
      - condition: sun
        before: sunrise
        before_offset: "1:00"
      - condition: sun
        after: sunset
        after_offset: "-1:00"
```
```


### Javascript errors shown in your browser console/inspector

```txt
None
```
