### ISSUE TITLE
Entity Id Missing Error when ID is listed

### ISSUE THREAD

**Issue by gmcaesar** [home-assistant/frontend#13794]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

ANy button calling a service (all i have right now are input_boolean.toggle and input_select.select_next) returns "needs enttity_id" error when service lists ID - same service in Dev panel fires fine

### Describe the behavior you expected

service to call

### Steps to reproduce the issue

1. any buntton (tried basic and mushroom button) returns same error

`show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: input_select.select_next
  data: {}
  target:
    entity_id: input_select.kori_morning_routine
entity: input_select.kori_morning_routine
`

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.4

### In which browser are you experiencing the issue with?

using firefox and chromium

### Which operating system are you using to run this browser?

windows 11 and pi os lite 64bit

### Problem-relevant frontend configuration

```yaml
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: input_select.select_next
  data: {}
  target:
    entity_id: input_select.kori_morning_routine
entity: input_select.kori_morning_routine
```

### Additional information

 Home Assistant 2022.9.4 Supervisor 2022.08.6 Operating System 9.0 Frontend 20220907.2 - latest
