### ISSUE TITLE
"tap_action" needs differently defined "entity_id"

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13827]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Check these docs (https://www.home-assistant.io/dashboards/actions/#tap-action):

![image](https://user-images.githubusercontent.com/71872483/191329702-ca322d9a-3d92-486a-9092-a2c6c8edd4eb.png)

Means - I must define `entity_id` inside `data` section:
```
    tap_action:
      action: call-service
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.test_boolean
```
But in practice I may use `data`, `service_data`, `target`:
```
type: entities
entities:
  - input_boolean.test_boolean
  - entity: sun.sun
    name: using data
    tap_action:
      action: call-service
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.test_boolean
  - entity: sun.sun
    name: using service_data
    tap_action:
      action: call-service
      service: input_boolean.toggle
      service_data:
        entity_id: input_boolean.test_boolean
  - entity: sun.sun
    name: using target
    tap_action:
      action: call-service
      service: input_boolean.toggle
      target:
        entity_id: input_boolean.test_boolean
```
![image](https://user-images.githubusercontent.com/71872483/191330555-56dd6e48-dab8-482a-b6ae-301425fa7e0d.png)

Seems that using `data`, `service_data`, `target` gives same result.
Probably we should use ONE method and it must be reflected in docs correspondingly.

Now check a picture-entities card:
```
type: picture-elements
elements:
  - type: state-badge
    entity: sun.sun
    tap_action:
      action: call-service
      service: input_boolean.toggle
      target:
        entity_id: input_boolean.test_boolean
    style:
      top: 10%
      left: 10%
  - type: state-badge
    entity: sun.sun
    tap_action:
      action: call-service
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.test_boolean
    style:
      top: 10%
      left: 50%
  - type: state-badge
    entity: sun.sun
    tap_action:
      action: call-service
      service: input_boolean.toggle
      service_data:
        entity_id: input_boolean.test_boolean
    style:
      top: 10%
      left: 30%
  - type: service-button
    title: input_boolean.toggle (target)
    service: input_boolean.toggle
    target:
      entity_id: input_boolean.test_boolean
    style:
      top: 22%
      left: 50%
  - type: service-button
    title: input_boolean.toggle (data)
    service: input_boolean.toggle
    data:
      entity_id: input_boolean.test_boolean
    style:
      top: 27%
      left: 50%
  - type: service-button
    title: input_boolean.toggle (service_data)
    service: input_boolean.toggle
    service_data:
      entity_id: input_boolean.test_boolean
    style:
      top: 32%
      left: 50%
image: /local/images/test/white.jpg
```
![image](https://user-images.githubusercontent.com/71872483/191332139-4a42b7eb-54dc-414d-99e1-9ab609367147.png)

The `state-badge` element works with `data`, `service_data`, `target`, the `service-button` works with `service_data` only ([as it is described in docs](https://www.home-assistant.io/dashboards/picture-elements/#service-call-button)).

Here a similar situation: we should use ONE method which must be documented in docs.

### Describe the behavior you expected

See above

### Steps to reproduce the issue

See above

### What version of Home Assistant Core has the issue?

2022.9.5

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127 

### Which operating system are you using to run this browser?

Win10x64
