### ISSUE TITLE
Google Maps Card broken:  Won't display users' locations after upgrading Home Assistant

### ISSUE THREAD

**Issue by mkanet** [home-assistant/frontend#13864]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to Home Assistant **Version 2022.9.6** from Home Assistant **Version 2022.7.7**, the Google Maps card stopped displaying users' locations; and, produced an error on the card image:
![Screenshot 09-24-2022 at 06 58 02 PM](https://user-images.githubusercontent.com/811008/192126478-5c8cb719-2a6a-4782-a1dd-9b484e3b3212.png)

If I revert back to **Version 2022.7.7**, the Google Maps card starts working again.

Below, is the still_image_url I'm using:

```
camera:
  - platform: generic
    name: 'Google Maps
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?size=800x800&maptype=hybrid&markers=color:red | label:A | {{ state_attr('sensor.sm_g781v_2_geocoded_location', 'location')[0] }}, {{ state_attr('sensor.sm_g781v_2_geocoded_location', 'location')[1] }}&markers=color:purple | label:A | {{ states.sensor.sm_g781v_geocoded_location.attributes.latitude }}, {{ states.sensor.sm_g781v_geocoded_location.attributes.longitude }}&markers=color:yellow | label:M | {{ state_attr('sensor.sm_t500_geocoded_location', 'location')[0] }}, {{ state_attr('sensor.sm_t500_geocoded_location', 'location')[1] }}&markers=color:blue | label:M | {{ state_attr('sensor.sm_n960u_geocoded_location', 'location')[0] }}, {{ state_attr('sensor.sm_n960u_geocoded_location', 'location')[1] }}&key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### Describe the behavior you expected

I expect the Google Maps card to display the users' locations on the Google Card Map

### Steps to reproduce the issue

1.  Upgrade to the latest Home Assistant version

### What version of Home Assistant Core has the issue?

2022.9.6

### What was the last working version of Home Assistant Core?

2022.7.7

### In which browser are you experiencing the issue with?

All Browsers

### Which operating system are you using to run this browser?

Windows 10 fully patched

### State of relevant entities

```txt
All relevant entities states and respective attributes display correctly in Home Assistant template editor

{{ state_attr('sensor.sm_g781v_2_geocoded_location', 'location')[0] }}
{{ state_attr('sensor.sm_g781v_2_geocoded_location', 'location')[1] }}
{{ states.sensor.sm_g781v_geocoded_location.attributes.latitude }}
{{ states.sensor.sm_g781v_geocoded_location.attributes.longitude }}
{{ state_attr('sensor.sm_t500_geocoded_location', 'location')[0] }}
{{ state_attr('sensor.sm_t500_geocoded_location', 'location')[1] }}
{{ state_attr('sensor.sm_n960u_geocoded_location', 'location')[0] }}
{{ state_attr('sensor.sm_n960u_geocoded_location', 'location')[1] }}
```

### Problem-relevant frontend configuration

```yaml
camera:
  - platform: generic
    name: 'Google Maps
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?size=800x800&maptype=hybrid&markers=color:red | label:A | {{ state_attr('sensor.sm_g781v_2_geocoded_location', 'location')[0] }}, {{ state_attr('sensor.sm_g781v_2_geocoded_location', 'location')[1] }}&markers=color:purple | label:A | {{ states.sensor.sm_g781v_geocoded_location.attributes.latitude }}, {{ states.sensor.sm_g781v_geocoded_location.attributes.longitude }}&markers=color:yellow | label:M | {{ state_attr('sensor.sm_t500_geocoded_location', 'location')[0] }}, {{ state_attr('sensor.sm_t500_geocoded_location', 'location')[1] }}&markers=color:blue | label:M | {{ state_attr('sensor.sm_n960u_geocoded_location', 'location')[0] }}, {{ state_attr('sensor.sm_n960u_geocoded_location', 'location')[1] }}&key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### Additional information

In case there's a recent breaking change (or bug) thats causing this issue, could someone please be kind enough to tell me what component (and respective version) to use in the path below in order to get Google Maps card to work correctly under Home Assistant 2022.9.6 and newer?

**/config/custom_components/_______**
