### ISSUE TITLE
bug in ha-selector-number: slider can not handle min: 0

### ISSUE THREAD

**Issue by philippwaller** [home-assistant/frontend#13867]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

the component "ha-selector-number" cannot select the minimum value in slider mode if it is `min: 0`.

![number selector bug](https://user-images.githubusercontent.com/1090452/192143541-950ef08e-c605-4b51-b6ff-b4055686a8b4.gif)

this is the selctor configuration, I am using:

```
blueprint:
  name: Close shutter at sundown
  description: Close shutter at sundown
  domain: automation
  input:
    cover_target_position:
      name: Cover Target Position
      description: This is the position the cover will be set to when the automation is triggered.
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
...
```

### Describe the behavior you expected

The min value should be selectable. ~~In "box" mode, the component works as expected.~~

### Steps to reproduce the issue

1. create a blueprint
2. create a selector with the following configuration:
```
number:
  min: 0
  max: 100
  unit_of_measurement: "%"
  mode: slider
```

### What version of Home Assistant Core has the issue?

2022.9.6 - Frontend 20220907.2

### In which browser are you experiencing the issue with?

Chrome Version 105.0.5195.125

### Which operating system are you using to run this browser?

macOS Monterey 12.4
