### ISSUE TITLE
Entities Card: Conditional row doesn't recognise empty string as valid condition

### ISSUE THREAD

**Issue by Sirs0ri** [home-assistant/frontend#13870]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding a `type: conditional` element to an entities card, it doesn't allow testing for an empty string (`""`) as condition via the state / state_not keys. Instead, the UI preview shows a "Conditions are invalid" warning

### Describe the behavior you expected

I'd have expected to be able to enter an empty state as condition, like it is possible with the `is_state(ID, STATE)` helper inside templates. 

### Steps to reproduce the issue

1. Create a new text_input helper
2. Set its value to an empty state:
  ```yaml
  service: input_text.set_value
  data: 
    value: ""
  target:
    entity_id: input_text.YOUR_HELPER_ID
  ```
3. In the frontend, create a new entities card, and add a "conditional" row that checks if your helper has an empty state:
```yaml
type: entities
title: My test card
entities: 
  - type: conditional
    conditions:
      - entity: input_text.YOUR_HELPER_ID
        state_not: ""
    row:
      entity: input_text.YOUR_HELPER_ID
```

**Expected:**
* Since you set the state of the helper to be empty in 2), an empty entities card should be created. If the state of the helper is changed (e.g. inside a script), its row should become visible.

**What happens instead:**
* The preview shows a warning "Conditions are invalid"

### What version of Home Assistant Core has the issue?

2022.9.6

### What was the last working version of Home Assistant Core?

n.a.

### In which browser are you experiencing the issue with?

Chrome beta 106

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
type: entities
title: My test card
entities: 
  - type: conditional
    conditions:
      - entity: input_text.YOUR_HELPER_ID
        state_not: ""
    row:
      entity: input_text.YOUR_HELPER_ID
```

### Javascript errors shown in your browser console/inspector

[192.168.188.65-1664120876661.log](https://github.com/home-assistant/frontend/files/9641164/192.168.188.65-1664120876661.log)
