### ISSUE TITLE
In masonry the maximum columns is now 3

### ISSUE THREAD

**Issue by Dontknowwhatiswhatwtf** [home-assistant/frontend#13881]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In previous versions 4 cards were sorted next to each other in 4 columns. Since latest version there seems to be a limit of 3 colums. The 4th element is now sorted under the 3rd element while there is enough horizontal space.

![image](https://user-images.githubusercontent.com/111376581/192337332-6b778092-f0a3-46da-93db-f01bc323c860.png)

### Describe the behavior you expected

I expect the 4 cards to be presented/sorted in 4 columns again

### Steps to reproduce the issue

1. create 4 cards (in my case it is a combination of horizontal en vertical stacks of cards)
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.9.6

### What was the last working version of Home Assistant Core?

2022.9.1

### In which browser are you experiencing the issue with?

Firefox 105.0 + Edge  105.0.1343.50

### Which operating system are you using to run this browser?

Windows 11 

### Problem-relevant frontend configuration

```yaml
views:
  - title: CCTV
    path: cctv
    icon: mdi:cctv
    badges: []
    cards:
      - type: conditional
        conditions:
          - entity: binary_sensor.tyzb01_dsjszp0x_ts0205_ias_zone
            state: 'on'
        card:
          type: entity
          entity: binary_sensor.tyzb01_dsjszp0x_ts0205_ias_zone
          name: Smoke Detected in Living!
          theme: Dark-Orange
      - cards:
          - type: horizontal-stack
            cards:
              - content: |-

                  [**Driveway**](http://192.168.3.20/)
                type: markdown
              - type: button
                tap_action:
                  action: call-service
                  service: homeassistant.reload_config_entry
                  service_data: {}
                  target:
                    entity_id: camera.driveway
                name: Reload
                icon: hass:reload
                icon_height: 30px
                theme: Dark-Red
              - card:
                  entity: media_player.kodi_living
                  hold_action:
                    action: more-info
                  icon: mdi:cctv
                  name: TV Living
                  show_icon: true
                  show_name: true
                  tap_action:
                    action: call-service
                    service: script.cam1_kodi_living
                  type: entity-button
                  icon_height: 30px
                conditions: []
                type: conditional
              - type: conditional
                conditions: []
                card:
                  type: button
                  name: TV Veranda
                  tap_action:
                    action: call-service
                    service: kodi.call_method
                    service_data:
                      entity_id: media_player.android
                      method: Player.Open
                      item:
                        file: smb://secret/downloads2/Reolink1.strm
                    target: {}
                  icon: mdi:cctv
                  show_state: true
                  icon_height: 30px
              - card:
                  type: button
                  name: TV Bedroom
                  tap_action:
                    action: call-service
                    service: kodi.call_method
                    service_data:
                      entity_id: media_player.kodi_bedroom
                      method: Player.Open
                      item:
                        file: smb://secret/downloads2/Reolink1_sub.strm
                    target: {}
                  icon: mdi:cctv
                  show_state: true
                  icon_height: 30px
                conditions: []
                type: conditional
          - camera_image: camera.driveway
            entities:
              - entity: binary_sensor.driveway_motion
              - entity: switch.driveway_ir_lights
              - entity: switch.driveway_record_audio
              - entity: switch.driveway_email
              - entity: switch.driveway_recording
              - entity: switch.driveway_ftp
            title: Driveway
            type: picture-glance
            camera_view: live
          - type: entity-filter
            entities:
              - binary_sensor.driveway_motion
              - camera.driveway
              - device_tracker.cam1
            state_filter:
              - 'on'
              - unavailable
              - not_home
              - home
            card:
              type: entities
          - entities:
              - entity: binary_sensor.driveway_motion
                name: Motion
              - entity: binary_sensor.driveway_person_detected
                name: Person
              - entity: switch.driveway_ir_lights
                name: IR lights
              - entity: switch.driveway_ftp
                name: FTP upload
              - entity: switch.driveway_email
                name: Email Alert
              - entity: switch.driveway_record_audio
                name: Record audio
              - entity: switch.driveway_recording
                name: Recording
              - entity: person.jo
                name: Presence Jo
            hours_to_show: 12
            refresh_interval: 1
            type: history-graph
          - type: horizontal-stack
            cards:
              - type: conditional
                conditions:
                  - entity: media_player.sony_android_tv
                    state: 'off'
                  - entity: switch.tz3000_wamqdr3f_ts011f_21894efe_on_off
                    state: 'off'
                card:
                  type: button
                  tap_action:
                    action: toggle
                  entity: switch.tz3000_wamqdr3f_ts011f_21894efe_on_off
                  icon: hass:power
                  show_state: true
                  name: TV Living
                  icon_height: 30px
        type: vertical-stack
      - type: conditional
        conditions:
          - entity: binary_sensor.tyzb01_dsjszp0x_ts0205_bf4304fe_ias_zone
            state: 'on'
        card:
          type: entity
          entity: binary_sensor.tyzb01_dsjszp0x_ts0205_bf4304fe_ias_zone
          name: Smoke Detected in Living!
          theme: Dark-Orange
      - cards:
          - type: horizontal-stack
            cards:
              - content: '[**Front door** ](http://192.168.3.23/)'
                type: markdown
              - type: button
                tap_action:
                  action: call-service
                  service: homeassistant.reload_config_entry
                  service_data: {}
                  target:
                    entity_id: camera.frontdoor
                name: Reload
                icon: hass:reload
                icon_height: 30px
                theme: Dark-Red
              - card:
                  entity: media_player.kodi_living
                  hold_action:
                    action: more-info
                  icon: mdi:cctv
                  name: TV Living
                  show_icon: true
                  show_name: true
                  tap_action:
                    action: call-service
                    service: script.cam4_kodi_living
                  type: entity-button
                  icon_height: 30px
                conditions: []
                type: conditional
              - type: conditional
                conditions: []
                card:
                  type: button
                  name: TV Veranda
                  tap_action:
                    action: call-service
                    service: kodi.call_method
                    service_data:
                      entity_id: media_player.android
                      method: Player.Open
                      item:
                        file: smb://secret/downloads2/Reolink4.strm
                    target: {}
                  icon: mdi:cctv
                  show_state: true
              - type: button
                name: TV Bedroom
                tap_action:
                  action: call-service
                  service: kodi.call_method
                  service_data:
                    entity_id: media_player.kodi_bedroom
                    method: Player.Open
                    item:
                      file: smb://secret/downloads2/Reolink4_sub.strm
                  target: {}
                icon: mdi:cctv
                show_state: true
                icon_height: 30px
          - camera_view: live
            camera_image: camera.frontdoor
            entities:
              - entity: binary_sensor.frontdoor_motion
              - entity: switch.frontdoor_ir_lights
              - entity: switch.frontdoor_record_audio
              - entity: switch.frontdoor_email
              - entity: switch.frontdoor_recording
              - entity: switch.frontdoor_ftp
            title: Frontdoor
            type: picture-glance
          - type: entity-filter
            entities:
              - binary_sensor.front_door_person_detected
              - binary_sensor.front_door_vehicle_detected
              - binary_sensor.front_door_pet_detected
              - binary_sensor.frontdoor_motion
              - camera.frontdoor
              - device_tracker.cam4
            state_filter:
              - 'on'
              - unavailable
              - not_home
              - home
            card:
              type: entities
          - entities:
              - entity: binary_sensor.front_door_person_detected
              - entity: binary_sensor.front_door_vehicle_detected
              - entity: binary_sensor.frontdoor_motion
                name: Motion
              - entity: switch.frontdoor_ir_lights
                name: IR lights
              - entity: switch.frontdoor_record_audio
              - entity: switch.frontdoor_email
                name: Email Alert
              - entity: switch.frontdoor_ftp
                name: FTP upload
              - entity: switch.frontdoor_recording
              - entity: person.jo
                name: Presence Jo
            hours_to_show: 12
            refresh_interval: 1
            type: history-graph
        type: vertical-stack
      - type: conditional
        conditions:
          - entity: binary_sensor.tyzb01_dsjszp0x_ts0205_2e2f04fe_ias_zone
            state: 'on'
        card:
          type: entity
          entity: binary_sensor.tyzb01_dsjszp0x_ts0205_2e2f04fe_ias_zone
          name: Smoke Detected in Garage!
          theme: Dark-Orange
      - cards:
          - type: horizontal-stack
            cards:
              - content: '[**Garden** ](http://192.168.3.21/)'
                type: markdown
              - type: button
                tap_action:
                  action: call-service
                  service: homeassistant.reload_config_entry
                  service_data: {}
                  target:
                    entity_id: camera.garden
                name: Reload
                icon: hass:reload
                icon_height: 30px
                theme: Dark-Red
                show_state: true
              - card:
                  entity: media_player.kodi_living
                  hold_action:
                    action: more-info
                  icon: mdi:cctv
                  name: TV Living
                  show_icon: true
                  show_name: true
                  tap_action:
                    action: call-service
                    service: script.cam2_kodi_living
                  type: entity-button
                  icon_height: 30px
                conditions: []
                type: conditional
              - type: button
                name: TV Veranda
                tap_action:
                  action: call-service
                  service: kodi.call_method
                  service_data:
                    entity_id: media_player.android
                    method: Player.Open
                    item:
                      file: smb://secret/downloads2/Reolink2.strm
                  target: {}
                icon: mdi:cctv
                show_state: true
                icon_height: 30px
              - type: button
                name: TV Bedroom
                tap_action:
                  action: call-service
                  service: kodi.call_method
                  service_data:
                    entity_id: media_player.kodi_bedroom
                    method: Player.Open
                    item:
                      file: smb://secret/downloads2/Reolink2.strm
                  target: {}
                icon: mdi:cctv
                show_state: true
                icon_height: 30px
          - entities:
              - entity: binary_sensor.garden_motion
              - entity: switch.garden_ir_lights
              - entity: switch.garden_record_audio
              - entity: switch.garden_email
              - entity: switch.garden_recording
              - entity: switch.garden_ftp
            title: Garden
            type: picture-glance
            camera_image: camera.garden
          - type: entity-filter
            entities:
              - binary_sensor.garden_motion
              - camera.garden
              - device_tracker.cam2
            state_filter:
              - 'on'
              - unavailable
              - not_home
              - home
            card:
              type: entities
          - entities:
              - entity: binary_sensor.garden_motion
                name: Motion
              - entity: switch.garden_ir_lights
              - entity: switch.garden_record_audio
              - entity: switch.garden_email
                name: Email Alert
              - entity: switch.garden_ftp
                name: FTP upload
              - entity: switch.garden_recording
              - entity: person.jo
                name: Presence Jo
            hours_to_show: 12
            refresh_interval: 1
            type: history-graph
        type: vertical-stack
      - type: horizontal-stack
        cards:
          - type: conditional
            conditions:
              - entity: binary_sensor.tze200_ggev5fsl_ts0601_e457f1fe_ias_zone
                state: 'on'
            card:
              type: entity
              entity: binary_sensor.tze200_ggev5fsl_ts0601_e457f1fe_ias_zone
              name: DANGER! Gasleak detected in garage!
      - cards:
          - type: horizontal-stack
            cards:
              - content: '[**Garden Gate** ](http://192.168.3.22/)'
                type: markdown
              - type: button
                tap_action:
                  action: call-service
                  service: homeassistant.reload_config_entry
                  service_data: {}
                  target:
                    entity_id: camera.side1
                name: Reload
                icon: hass:reload
                icon_height: 30px
                theme: Dark-Red
              - card:
                  entity: media_player.kodi_living
                  hold_action:
                    action: more-info
                  icon: mdi:cctv
                  name: TV Living
                  show_icon: true
                  show_name: true
                  tap_action:
                    action: call-service
                    service: script.cam3_kodi_living
                  type: entity-button
                  icon_height: 30px
                conditions: []
                type: conditional
              - type: conditional
                conditions: []
                card:
                  type: button
                  name: TV Veranda
                  tap_action:
                    action: call-service
                    service: kodi.call_method
                    service_data:
                      entity_id: media_player.android
                      method: Player.Open
                      item:
                        file: smb://secret/downloads2/Reolink3.strm
                    target: {}
                  icon: mdi:cctv
                  show_state: true
              - type: button
                name: TV Bedroom
                tap_action:
                  action: call-service
                  service: kodi.call_method
                  service_data:
                    entity_id: media_player.kodi_bedroom
                    method: Player.Open
                    item:
                      file: smb://secret/downloads2/Reolink3_sub.strm
                  target: {}
                icon: mdi:cctv
                show_state: true
                icon_height: 30px
          - camera_image: camera.side1
            entities:
              - entity: binary_sensor.side1_motion
              - entity: switch.side1_ir_lights
              - entity: switch.side1_record_audio
              - entity: switch.side1_email
              - entity: switch.side1_recording
              - entity: switch.side1_ftp
            type: picture-glance
            title: Side
          - type: entity-filter
            entities:
              - binary_sensor.side1_motion
              - camera.side1
              - device_tracker.cam3
            state_filter:
              - 'on'
              - unavailable
              - not_home
              - home
            card:
              type: entities
          - entities:
              - entity: binary_sensor.side1_motion
                name: Motion
              - entity: switch.side1_ir_lights
                name: IR lights
              - entity: switch.side1_record_audio
              - entity: switch.side1_email
                name: Email Alert
              - entity: switch.side1_ftp
                name: FTP upload
              - entity: switch.side1_recording
              - entity: person.jo
                name: Presence Jo
            hours_to_show: 12
            refresh_interval: 1
            type: history-graph
        type: vertical-stack
  - title: Presense detection sensors
    path: presense-detection-sensors
    icon: mdi:motion-sensor
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# Level 0'
          - type: entities
            entities:
              - entity: binary_sensor.tyzb01_dsjszp0x_ts0205_2e2f04fe_ias_zone
                name: Garage - Smoke alarm
                secondary_info: last-changed
              - entity: binary_sensor.tze200_ggev5fsl_ts0601_e457f1fe_ias_zone
            state_color: true
            theme: Dark-Orange
          - type: entities
            entities:
              - entity: binary_sensor.ewelink_ms01_9912cd22_ias_zone
                secondary_info: last-changed
            title: Driveway
            state_color: true
          - type: entities
            entities:
              - entity: binary_sensor.ewelink_ds01_3795fb22_ias_zone
                icon: hass:garage
                secondary_info: last-changed
              - entity: binary_sensor.ewelink_ms01_fa17cd22_ias_zone
                secondary_info: last-changed
            title: Garage
            state_color: true
          - type: entities
            entities:
              - entity: binary_sensor.ewelink_ms01_9912cd22_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.ewelink_ds01_178ccd22_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.lumi_lumi_vibration_aq1_96bda006_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.ewelink_ms01_8bcee722_ias_zone
                secondary_info: last-updated
            title: Hallway
            state_color: true
          - type: entities
            entities:
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_5fa2abfe_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.ewelink_ds01_fitness_window_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.lumi_lumi_vibration_aq1_92c2d006_ias_zone
                secondary_info: last-changed
            title: Fitness
            state_color: true
          - type: history-graph
            entities:
              - entity: binary_sensor.ewelink_ms01_9912cd22_ias_zone
                name: Outside front
              - entity: binary_sensor.ewelink_ds01_178ccd22_ias_zone
                name: Front door
              - entity: binary_sensor.lumi_lumi_vibration_aq1_96bda006_ias_zone
                name: Front door vibration
              - entity: binary_sensor.ewelink_ms01_8bcee722_ias_zone
                name: Hallway
              - entity: binary_sensor.ewelink_ds01_3795fb22_ias_zone
                name: Garage door
              - entity: binary_sensor.ewelink_ms01_fa17cd22_ias_zone
                name: Garage
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_5fa2abfe_ias_zone
                name: Fitness
              - entity: binary_sensor.ewelink_ds01_fitness_window_ias_zone
                name: Fitness window
              - entity: binary_sensor.lumi_lumi_vibration_aq1_96bda006_ias_zone
                name: Fitness window vibration
              - entity: binary_sensor.lumi_lumi_vibration_aq1_92c2d006_ias_zone
            hours_to_show: 24
            refresh_interval: 0
          - type: logbook
            entities:
              - binary_sensor.lumi_lumi_vibration_aq1_96bda006_ias_zone
              - binary_sensor.ewelink_ms01_9912cd22_ias_zone
              - binary_sensor.ewelink_ds01_178ccd22_ias_zone
              - binary_sensor.ewelink_ms01_8bcee722_ias_zone
              - binary_sensor.ewelink_ds01_3795fb22_ias_zone
              - binary_sensor.ewelink_ms01_fa17cd22_ias_zone
              - binary_sensor.tz1800_fcdjzz3s_ty0202_5fa2abfe_ias_zone
              - binary_sensor.ewelink_ds01_fitness_window_ias_zone
              - binary_sensor.lumi_lumi_vibration_aq1_92c2d006_ias_zone
            hours_to_show: 24
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# Level 1'
          - type: entities
            entities:
              - entity: binary_sensor.tyzb01_dsjszp0x_ts0205_ias_zone
                name: Living - Smoke alarm
                secondary_info: last-changed
            state_color: true
            theme: Dark-Orange
          - type: entities
            entities:
              - entity: binary_sensor.ewelink_ms01_11e5e922_ias_zone
                secondary_info: last-updated
              - entity: >-
                  binary_sensor.ikea_of_sweden_tradfri_motion_sensor_4b9889fe_on_off
                secondary_info: last-updated
              - entity: binary_sensor.ewelink_ds01_8d3a4223_ias_zone
              - entity: binary_sensor.ewelink_ds01_a3444223_ias_zone
              - entity: binary_sensor.ewelink_ds01_f9fb4223_ias_zone
            title: Living
            state_color: true
            show_header_toggle: false
          - type: entities
            entities:
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_6650c8fe_ias_zone
            title: Kitchen
            state_color: true
            show_header_toggle: false
          - type: entities
            entities:
              - entity: >-
                  binary_sensor.ikea_of_sweden_tradfri_motion_sensor_c464a7fe_on_off
                secondary_info: last-updated
              - entity: binary_sensor.ewelink_ds01_4116fd22_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.lumi_lumi_vibration_aq1_ffa7d006_ias_zone
              - entity: binary_sensor.ewelink_ds01_veranda_door_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.lumi_lumi_vibration_aq1_7fcbd006_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_5ffcc406_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_dad1d006_ias_zone
              - entity: binary_sensor.ewelink_ds01_c0444223_ias_zone
              - entity: binary_sensor.ewelink_ds01_e53c4223_ias_zone
            title: Veranda
            state_color: true
            show_header_toggle: false
          - type: entities
            entities:
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_316a09fe_ias_zone
                icon: hass:motion-sensor
                secondary_info: last-changed
            title: Toilet 2
            state_color: true
            show_header_toggle: false
          - type: history-graph
            entities:
              - entity: binary_sensor.ewelink_ms01_11e5e922_ias_zone
                name: Living
              - entity: binary_sensor.ewelink_ds01_4116fd22_ias_zone
                name: Veranda sliding door
              - entity: binary_sensor.ewelink_ds01_veranda_door_ias_zone
                name: Veranda door
              - entity: >-
                  binary_sensor.ikea_of_sweden_tradfri_motion_sensor_4b9889fe_on_off
                name: Upper stairway
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_ias_zone
                name: Kitchen
              - entity: >-
                  binary_sensor.ikea_of_sweden_tradfri_motion_sensor_c464a7fe_on_off
                name: Veranda
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_316a09fe_ias_zone
                name: Toilet 2
              - entity: binary_sensor.lumi_lumi_vibration_aq1_ffa7d006_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_7fcbd006_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_5ffcc406_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_dad1d006_ias_zone
              - entity: binary_sensor.ewelink_ds01_8d3a4223_ias_zone
              - entity: binary_sensor.ewelink_ds01_a3444223_ias_zone
              - entity: binary_sensor.ewelink_ds01_f9fb4223_ias_zone
              - entity: binary_sensor.ewelink_ds01_c0444223_ias_zone
              - entity: binary_sensor.ewelink_ds01_e53c4223_ias_zone
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_6650c8fe_ias_zone
            hours_to_show: 24
            refresh_interval: 0
          - type: logbook
            entities:
              - binary_sensor.ewelink_ms01_11e5e922_ias_zone
              - binary_sensor.ewelink_ds01_4116fd22_ias_zone
              - binary_sensor.ewelink_ds01_veranda_door_ias_zone
              - >-
                binary_sensor.ikea_of_sweden_tradfri_motion_sensor_c464a7fe_on_off
              - >-
                binary_sensor.ikea_of_sweden_tradfri_motion_sensor_4b9889fe_on_off
              - binary_sensor.tz1800_fcdjzz3s_ty0202_ias_zone
              - binary_sensor.tz1800_fcdjzz3s_ty0202_316a09fe_ias_zone
              - binary_sensor.lumi_lumi_vibration_aq1_ffa7d006_ias_zone
              - binary_sensor.lumi_lumi_vibration_aq1_7fcbd006_ias_zone
              - binary_sensor.lumi_lumi_vibration_aq1_5ffcc406_ias_zone
              - binary_sensor.lumi_lumi_vibration_aq1_dad1d006_ias_zone
              - binary_sensor.ewelink_ds01_8d3a4223_ias_zone
              - binary_sensor.ewelink_ds01_a3444223_ias_zone
              - binary_sensor.ewelink_ds01_f9fb4223_ias_zone
              - binary_sensor.ewelink_ds01_c0444223_ias_zone
              - binary_sensor.ewelink_ds01_e53c4223_ias_zone
              - binary_sensor.tz1800_fcdjzz3s_ty0202_6650c8fe_ias_zone
            hours_to_show: 24
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# Level 2'
          - type: entities
            entities:
              - entity: binary_sensor.tyzb01_dsjszp0x_ts0205_bf4304fe_ias_zone
                name: Night hall - Smoke alarm
                secondary_info: last-changed
            state_color: true
            theme: Dark-Orange
          - type: entities
            entities:
              - entity: >-
                  binary_sensor.ikea_of_sweden_tradfri_motion_sensor_4b9889fe_on_off
                secondary_info: last-changed
              - entity: binary_sensor.lumi_lumi_vibration_aq1_96bda006_ias_zone
                secondary_info: last-changed
            state_color: true
            show_header_toggle: false
            title: Night hall / stairway
          - type: entities
            entities:
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_02b5dffe_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.ewelink_ds01_9ec44423_ias_zone
                secondary_info: last-changed
            state_color: true
            show_header_toggle: false
            title: Office
          - type: entities
            entities:
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_647bdffe_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.ewelink_ds01_a2544423_ias_zone
                secondary_info: last-updated
              - entity: binary_sensor.ewelink_ds01_eaf94223_ias_zone
                secondary_info: last-changed
              - entity: binary_sensor.lumi_lumi_vibration_aq1_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_6cbed006_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_3e42d306_ias_zone
            state_color: true
            show_header_toggle: false
            title: Bedroom
          - type: entities
            entities:
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_75bbaefe_ias_zone
                icon: hass:motion-sensor
                secondary_info: last-changed
            state_color: true
            show_header_toggle: false
            title: Toilet 3
          - type: entities
            entities:
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_45a235fe_ias_zone
                icon: hass:motion-sensor
                secondary_info: last-changed
              - entity: binary_sensor.ewelink_ds01_d43c4223_ias_zone
            state_color: true
            show_header_toggle: false
            title: Bathroom
          - type: history-graph
            entities:
              - entity: >-
                  binary_sensor.ikea_of_sweden_tradfri_motion_sensor_4b9889fe_on_off
                name: Upper stairway
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_02b5dffe_ias_zone
                name: Office
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_647bdffe_ias_zone
                name: Bedroom
              - entity: binary_sensor.ewelink_ds01_a2544423_ias_zone
                name: Bedroom window 1
              - entity: binary_sensor.ewelink_ds01_eaf94223_ias_zone
                name: Bedroom window 2
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_75bbaefe_ias_zone
                name: Toilet 3
              - entity: binary_sensor.tz1800_fcdjzz3s_ty0202_45a235fe_ias_zone
                name: Bathroom
              - entity: binary_sensor.lumi_lumi_vibration_aq1_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_6cbed006_ias_zone
              - entity: binary_sensor.lumi_lumi_vibration_aq1_3e42d306_ias_zone
              - entity: binary_sensor.ewelink_ds01_9ec44423_ias_zone
              - entity: binary_sensor.ewelink_ds01_d43c4223_ias_zone
            hours_to_show: 24
            refresh_interval: 0
          - type: logbook
            entities:
              - >-
                binary_sensor.ikea_of_sweden_tradfri_motion_sensor_4b9889fe_on_off
              - binary_sensor.tz1800_fcdjzz3s_ty0202_02b5dffe_ias_zone
              - binary_sensor.tz1800_fcdjzz3s_ty0202_647bdffe_ias_zone
              - binary_sensor.ewelink_ds01_a2544423_ias_zone
              - binary_sensor.ewelink_ds01_eaf94223_ias_zone
              - binary_sensor.tz1800_fcdjzz3s_ty0202_75bbaefe_ias_zone
              - binary_sensor.tz1800_fcdjzz3s_ty0202_45a235fe_ias_zone
              - binary_sensor.lumi_lumi_vibration_aq1_ias_zone
              - binary_sensor.lumi_lumi_vibration_aq1_6cbed006_ias_zone
              - binary_sensor.lumi_lumi_vibration_aq1_3e42d306_ias_zone
              - binary_sensor.ewelink_ds01_9ec44423_ias_zone
              - binary_sensor.ewelink_ds01_d43c4223_ias_zone
            hours_to_show: 24
  - title: Surveillance settings
    path: surveillance-settings
    icon: mdi:eye-settings
    badges: []
    cards:
      - cards:
          - entities:
              - entity: automation.enable_security_recording_at_night
                icon: mdi:power-standby
                name: 'Activate: FTP security recorden at night'
              - entity: input_datetime.turn_on_seccam
                icon: mdi:timer
                name: Start nightly recording (home)
              - entity: automation.disable_security_recording_in_the_morning
                icon: mdi:power-standby
                name: 'Disable: FTP security recorden at night'
              - entity: input_datetime.turn_off_seccam
                icon: mdi:timer-off
                name: Stop nightly recording (home)
              - entity: automation.leaving_turn_on_security_recording_and_mailing
                icon: mdi:power-standby
                name: Leaving - turn on alarm system
              - entity: >-
                  automation.comming_home_turn_off_security_recording_and_mailing
                icon: mdi:power-standby
                name: Arriving home - turn off alarm system
            show_header_toggle: false
            state_color: true
            title: Schedule recordings (all)
            type: entities
        type: horizontal-stack
      - type: entities
        entities:
          - entity: automation.motion_front_door
            name: Announce visitors
            secondary_info: last-triggered
            icon: hass:bell
          - entity: automation.night_alarm
            secondary_info: last-triggered
            icon: hass:security
            name: Alarm - Absence
          - entity: automation.alarm_breach_and_motion_when_away
            name: Alarm - Night
            secondary_info: last-triggered
            icon: hass:security
          - entity: input_boolean.fire_alarm_mode
            name: Fire alarm siren
          - entity: automation.fire_alarm_smoke_detected
            name: Notify fire alarm
            icon: hass:fire-alert
        title: Alarm system
        state_color: true
        show_header_toggle: true
      - type: entities
        entities:
          - entity: device_tracker.cam1
            secondary_info: last-changed
          - entity: device_tracker.cam2
            secondary_info: last-changed
          - entity: device_tracker.cam3
            secondary_info: last-changed
          - entity: device_tracker.cam4
            secondary_info: last-changed
          - entity: automation.report_cameras_going_offline
        title: Monitor camera status
        state_color: true
      - type: button
        tap_action:
          action: toggle
        entity: input_boolean.alarm_mode
        show_state: true
        icon_height: 100px
        name: Alarm Armed
        icon: mdi:alarm-bell
      - type: button
        tap_action:
          action: call-service
          service: homeassistant.reload_core_config
          service_data: {}
          target: {}
        entity: camera.driveway
        name: Reload
        icon: hass:reload
        icon_height: 30px
        theme: Dark-Red
title: Surveillance
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

![image](https://user-images.githubusercontent.com/111376581/192339056-02f1b9de-1348-47e6-bfbb-76c4cf739c87.png)
