### ISSUE TITLE
Using light groups and scenes with different device brands (incompatible effects)

### ISSUE THREAD

**Issue by j-waters** [home-assistant/frontend#13893]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a light group with several devices in in:

```
- platform: group
  name: Bedroom Lights
  entities:
    - light.tall_lamp
    - light.round_lamp
    - light.main_light
```

It happens that all of these lights are different brands (Yeelight, WLED, LIFX). All of them provide effects, which is where the issue lies.

I go to create a scene, select the light group, change the colour, and click save. I get the following error:
`Failed to call service scene/turn_on. Unable to find service lifx.solid`.

It turns out when editing the colour of the group, the 'Solid' effect from WLED was preselected, and it's impossible to select no effect using the UI. This effect is then being passed to the LIFX bulb, which doesn't understand it, and thus doesn't respond.

This can be fixed by manually editing my `scenes.yaml` and removing the `effect: Solid` line from the scene.

Changing the colour of the light group from the dashboard works fine, it just doesn't work in scenes created by the scene editor UI. Also Yeelight seems to work fine, despite also not having a 'Solid' effect. 

### Describe the behavior you expected

I should be able to create a scene with a light group, and when editing the state of the light group either:

* Not have to select an effect
* Be able to select an effect but if that effect can't be applied to a specific light, still change the light colour

### Steps to reproduce the issue

1. Create a light group with a WLED bulb and a LIFX bulb (other combinations will probably have the same issue, like WLED and [the third party integration for cololight](https://github.com/BazaJayGee66/homeassistant_cololight))
2. Create a scene with that light group using the UI
3. Try activating the scene

### What version of Home Assistant Core has the issue?

2022.9.5

### In which browser are you experiencing the issue with?

Google Chrome Version 106.0.5249.61 (Official Build) beta (64-bit)

### Which operating system are you using to run this browser?

Arch Linux

### Problem-relevant frontend configuration

```yaml
The scene that is generated by the UI is as follows:


- id: '1663798539887'
  name: Bright
  entities:
    light.bedroom_lights:
      supported_color_modes:
      - color_temp
      - hs
      - onoff
      - rgb
      icon: mdi:lightbulb-group
      friendly_name: Bedroom Lights
      supported_features: 44
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - 80s Club
      - Alarm
      - Android
      - Aurora
      - Blends
      - Blink
      - Blink Rainbow
      - Bouncing Balls
      - Bpm
      - Breathe
      - Candle
      - Candle Flicker
      - Candle Multi
      - Candy Cane
      - Chase
      - Chase 2
      - Chase 3
      - Chase Flash
      - Chase Flash Rnd
      - Chase Rainbow
      - Chase Random
      - Cherry Blossom
      - Christmas
      - Chunchun
      - Cocktail Parade
      - Colorful
      - Colorloop
      - Colortwinkles
      - Colorwaves
      - Colour loop
      - Dancing Shadows
      - Date Night
      - Disco
      - Dissolve
      - Dissolve Rnd
      - Drip
      - Dynamic
      - Dynamic Smooth
      - Facebook
      - Fade
      - Fairy
      - Fairytwinkle
      - Fast Random Loop
      - Fill Noise
      - Fire 2012
      - Fire Flicker
      - Fireworks
      - Fireworks 1D
      - Fireworks Starburst
      - Flow
      - Glitter
      - Gradient
      - Halloween
      - Halloween Eyes
      - Happy Birthday
      - Heartbeat
      - Home
      - ICU
      - Instagrammer
      - Juggle
      - LSD
      - Lake
      - Lighthouse
      - Lightning
      - Loading
      - Meteor
      - Meteor Smooth
      - Movie
      - Multi Comet
      - Music Mode
      - Night Mode
      - Noise 1
      - Noise 2
      - Noise 3
      - Noise 4
      - Noise Pal
      - Oscillate
      - Pacifica
      - Palette
      - Pensieve
      - Percent
      - Phased
      - Phased Noise
      - Plasma
      - Police
      - Police2
      - Popcorn
      - Pride 2015
      - RGB
      - Railway
      - Rain
      - Rainbow
      - Rainbow Flow
      - Rainbow Runner
      - Random Colors
      - Random Loop
      - Ripple
      - Ripple Rainbow
      - Romance
      - Running
      - Running Dual
      - Savasana
      - Saw
      - Scan
      - Scan Dual
      - Scanner
      - Scanner Dual
      - Sine
      - Sinelon
      - Sinelon Dual
      - Sinelon Rainbow
      - Slow Temp
      - Slowdown
      - Solid
      - Solid Glitter
      - Solid Pattern
      - Solid Pattern Tri
      - Sparkle
      - Sparkle Dark
      - Sparkle+
      - Spots
      - Spots Fade
      - Stop
      - Stream
      - Stream 2
      - Strobe
      - Strobe Mega
      - Strobe Rainbow
      - Strobe color
      - Strobe epilepsy!
      - Sunrise
      - Sunset
      - Sweep
      - Sweep Random
      - TV Simulator
      - Tetrix
      - The Circus
      - Theater
      - Theater Rainbow
      - Traffic Light
      - Tri Fade
      - Tri Wipe
      - Twinkle
      - Twinklecat
      - Twinklefox
      - Twinkleup
      - Twitter
      - Two Dots
      - Unicorns
      - Washing Machine
      - WhatsApp
      - Wipe
      - Wipe Random
      entity_id:
      - light.tall_lamp
      - light.round_lamp
      - light.main_light
      color_mode: rgb
      brightness: 255
      hs_color:
      - 27.059
      - 20
      rgb_color:
      - 255
      - 227
      - 204
      xy_color:
      - 0.374
      - 0.35
      effect: Solid
      state: 'on'
  metadata:
    light.bedroom_lights:
      entity_only: true
  icon: mdi:brightness-7
```

### Additional information

I decided to file this under `frontend` rather than core because the issue only really occurred when using the scene edit UI. However it might be that the frontend is actually working just fine and it's the WLED or LIFX integration that's the issue, or scene activation itself
