### ISSUE TITLE
Entities card: conditional row - rules does not recognize Unicode

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13894]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this example:
```
type: entities
title: My test card
entities:
  - input_text.test_text
  - type: conditional
    conditions:
      - entity: input_text.test_text
        state_not: \u0061\u0062\u0063
    row:
      entity: input_text.test_text
```
where `\u0061\u0062\u0063` = `abc`

And this rule does not work:
![image](https://user-images.githubusercontent.com/71872483/192666668-49e74dd4-02bd-49f6-9fed-e1fe0163c427.png)

This works:
```
        state_not: abc
```

### Describe the behavior you expected

As above

### Steps to reproduce the issue

As above

### What version of Home Assistant Core has the issue?

2022.9.7

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127 

### Which operating system are you using to run this browser?

Win10x64
