### ISSUE TITLE
Logbook shows wrong trigger

### ISSUE THREAD

**Issue by rikardronnkvist** [home-assistant/frontend#13912]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The logbook shows that a light is turned off by "service notify.discord" but it's turned of by an automation where that service is the previous step.

### Describe the behavior you expected

Should say "Turned off by automation.xyz"

### Steps to reproduce the issue

My code
```
automation:
- id: sun_sunrise_above1
  alias: "Sun - Sunrise - Above1"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 1
  action:
    - service: notify.discord
      data:
        message: ":sunrise: Sunrise Above 1 (elevation {{ state_attr('sun.sun', 'elevation') }} ) - Turn off morning lights"
        target: !secret discord_channel_hassio_automations
    - service: homeassistant.turn_off
      data:
        entity_id:
          - light.kok_hoger_fonsterlampa
          - light.kok_vanster_fonsterlampa
          - light.vardagsrum_fonsterlampa
```

And the result in the logbook:
![Skärmbild 2022-09-29 073319](https://user-images.githubusercontent.com/3245006/192946935-0dc05c8a-60fb-40f7-b504-e0aee98c4c00.png)

And in discord...
![discord](https://user-images.githubusercontent.com/3245006/192946998-bc18975c-5d8f-4c27-b7a2-fcfccb028081.png)

### What version of Home Assistant Core has the issue?

2022.9.7

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.127

### Which operating system are you using to run this browser?

Windows 10 20H2
