### ISSUE TITLE
More info dialogue options not selectable 

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#13947]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Selecting entity options (e.g. sources or light effects) is nearly impossible or by change because the list isn’t collapsed properly. For details see the following clips:

https://user-images.githubusercontent.com/71203830/193453807-1790a865-c6e8-495e-90ae-c07a8efd7742.mov

https://user-images.githubusercontent.com/71203830/193453803-ff92dc99-59c2-4027-a28d-a197d844348b.MOV

### Describe the behavior you expected

Flawless selection of options.

### Steps to reproduce the issue

1. Choose an entity with selectable attribute options
2. Create a UI card for it
3. Open the more info view of this card 4. 
4. Try to select an option

### What version of Home Assistant Core has the issue?

core-2022.10.0b2

### In which browser are you experiencing the issue with?

Google Chrome 106.0.5249.75, iPadOS Safari 15.7

### Which operating system are you using to run this browser?

iPadOS 15.7

### Problem-relevant frontend configuration

```yaml
Examples:

type: media-control
entity: media_player.sony_kd_65xf9005


type: button
entity: light.hue_iris
tap_action:
  action: toggle
```
