### ISSUE TITLE
Bug in Energy Dashboard with multiple Powerwalls

### ISSUE THREAD

**Issue by mindspawn** [home-assistant/frontend#13983]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am using the energy dashboard with two separate solar installs in the same home (each with its own inverter, gateway and powerwall batteries). Everything works great except for the second battery's "Powerwall Battery Export" not being shown in the stacked bar graph for Energy usage (4.5 kWh in the screenshot attached). All other parameters appear to be plotted correctly.

<img width="1006" alt="2022-10-03 21_11_37-Energy – Home Assistant" src="https://user-images.githubusercontent.com/5296802/193732958-b732d58c-5a2c-4080-b5a0-bdb887b91ecb.png">

### Describe the behavior you expected

"Powerwall Battery Export" for each of the two batteries show be plotted separately in the energy usage bar graph.

### Steps to reproduce the issue

1. Using the attached energy configuration file (had to add .txt extension to have Github allow the right filetype).
[energy.txt](https://github.com/home-assistant/frontend/files/9702789/energy.txt)

### What version of Home Assistant Core has the issue?

2022.9.7

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
state_class: total
unit_of_measurement: kWh
device_class: energy
friendly_name: Powerwall Battery Export
```

### Problem-relevant frontend configuration

```yaml
energy configuration:


{
  "version": 1,
  "minor_version": 1,
  "key": "energy",
  "data": {
    "energy_sources": [
      {
        "type": "grid",
        "flow_from": [
          {
            "stat_energy_from": "sensor.powerwall_site_import",
            "stat_cost": null,
            "entity_energy_from": "sensor.powerwall_site_import",
            "entity_energy_price": null,
            "number_energy_price": null
          },
          {
            "stat_energy_from": "sensor.powerwall_site_import_2",
            "stat_cost": null,
            "entity_energy_from": "sensor.powerwall_site_import_2",
            "entity_energy_price": null,
            "number_energy_price": null
          }
        ],
        "flow_to": [
          {
            "stat_energy_to": "sensor.powerwall_site_export",
            "stat_compensation": null,
            "entity_energy_to": "sensor.powerwall_site_export",
            "entity_energy_price": null,
            "number_energy_price": null
          },
          {
            "stat_energy_to": "sensor.powerwall_site_export_2",
            "stat_compensation": null,
            "entity_energy_to": "sensor.powerwall_site_export_2",
            "entity_energy_price": null,
            "number_energy_price": null
          }
        ],
        "cost_adjustment_day": 0.0
      },
      {
        "type": "solar",
        "stat_energy_from": "sensor.powerwall_solar_export",
        "config_entry_solar_forecast": null
      },
      {
        "type": "solar",
        "stat_energy_from": "sensor.powerwall_solar_export_2",
        "config_entry_solar_forecast": null
      },
      {
        "type": "battery",
        "stat_energy_from": "sensor.powerwall_battery_export",
        "stat_energy_to": "sensor.powerwall_battery_import"
      },
      {
        "type": "battery",
        "stat_energy_from": "sensor.powerwall_battery_export_2",
        "stat_energy_to": "sensor.powerwall_battery_import_2"
      }
    ],
    "device_consumption": []
  }
}
```
