### ISSUE TITLE
Picture Glance card bug - setting tap action or hold action to none, breaks the visual editor

### ISSUE THREAD

**Issue by user897943** [home-assistant/frontend#13989]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Add a grid card, change columns to 1, add a picture glance card to the grid, change the tap action to none and the visual editor breaks and removes all the card info from the yaml editor. Same happens to the hold action.
Further to this, since update to 2022.8 the picture glance card keeps flickering when the image is a camera entity. This was not happening on 2022.7.x and before. I have 2 picture glance cards in a 1-column grid card, the cards have entities for each area so I can control lights and door locks for example. The whole card flickers (image and icon elements).

### Describe the behavior you expected

For the editor not to break when changing tap and hold actions, and for the card to not flicker html elements.

### Steps to reproduce the issue

See above

### What version of Home Assistant Core has the issue?

core-2022.8.x

### What was the last working version of Home Assistant Core?

core-2022.7.x

### In which browser are you experiencing the issue with?

All Chromium-based browsers for the flickering and all common browsers for the tap and hold issue

### Which operating system are you using to run this browser?

Debian 11, Ubuntu 22, Windows 11, Windows 10

**Comment by user897943** [comment]
yaml for 1st card:
```
camera_image: camera.entrance
camera_view: live
entities:
  - entity: lock.front_door_2
    show_state: true
    tap_action:
      action: toggle
  - entity: switch.arm_alarm
    show_state: true
    tap_action:
      action: toggle
      confirmation:
        text: Set/Unset Burglar Alarm?
  - entity: automation.door_opened
    show_state: true
    tap_action:
      action: toggle
  - entity: automation.pete_auto_unlock
    show_state: true
    tap_action:
      action: toggle
  - entity: light.entrance
    show_state: true
    tap_action:
      action: toggle
hold_action:
  action: none
tap_action:
  action: more-info
title: Entrance
type: picture-glance
```

yaml for 2nd card:
```
camera_image: camera.backyard_rtsp
camera_view: live
entities:
  - entity: lock.back_door
    show_state: true
    tap_action:
      action: toggle
  - entity: automation.door_alert_when_back_door_opened
    show_state: true
    tap_action:
      action: toggle
  - entity: light.string_lights
    show_state: true
    tap_action:
      action: toggle
hold_action:
  action: none
tap_action:
  action: more-info
title: Backyard
type: picture-glance
```
