### ISSUE TITLE
Statistics Graph not resetting at the same time as the utility meter 

### ISSUE THREAD

**Issue by caco3** [home-assistant/frontend#13995]
### Checklist
 - [x] I have updated to the latest available Home Assistant version.
 - [x] I have cleared the cache of my browser.
 - [x] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing
I have a sensor which reports me my gas meter value as a continuously increasing value:
![grafik](https://user-images.githubusercontent.com/1783586/193898112-c782c2f1-262c-4439-8cbb-34b1449157b8.png)
```yaml
sensor:
# Gasmeter
- platform: mqtt
  name: "Gasmeter Value"
  unique_id: gasmeter_value
  state_topic: "gaszaehler/main/value"
  unit_of_measurement: 'm³'
  state_class: total_increasing
  device_class: gas
  icon: 'mdi:fire'
  last_reset_value_template: '1970-01-01T00:00:00+00:00'
```

Also, I have an utility meter which resets the data once a day (its nowhere stated, but I expect it to happen on midnight, 00:00:00):
![grafik](https://user-images.githubusercontent.com/1783586/193898613-210aef60-9bdf-4259-8345-388ba575c287.png)

```yaml
utility_meter:
  utility_meter_gas_per_day:
    source: sensor.gasmeter_value
    cycle: daily
```

I now would like to have a statistics diagram which shows me the usage per day similar to what the Energy dashboard provides.
Since the Statistics Graph requires ` state_class: measurement`, I added a template sensor for this:
```yaml
# The Statistics Graph needs to have the "state_class" set to "measurement", see https://community.home-assistant.io/t/statistics-graph-just-keeps-going-up/335516/5
  - name: "Gasmeter per day"
    state: "{{ states('sensor.utility_meter_gas_per_day') }}"
    unit_of_measurement: 'm³'
    state_class: measurement
```

Then I created a statistics graph with it:
![grafik](https://user-images.githubusercontent.com/1783586/193902092-e00e099b-27d1-4864-a35a-ea49930da27a.png)

I now would expect that the max starts new every day, how ever it keeps the max of the previous day and only goes over it if the consumption is higher than on the previous day (like 2. to 3. Oct.)!

![grafik](https://user-images.githubusercontent.com/1783586/193900054-0589da94-d9f4-4a54-a3b1-6d0867b702f4.png)

It looks like as if the Statistics Graph takes the max the last time on midnight (00:00:00), how ever the Utility meter only resets a bit later (eg. on 00:00:01). This would cause the Statistics graph to take the max value of the previous day as its start value for max.

I tested this on a clean, new instance of HA.
Also I set the timezone correctly (right from the beginning):
```yaml
default_config:

homeassistant:
  unit_system: metric
  time_zone: Europe/Zurich
```

Below 2 other screenshots of the next day showing the issue once more. And the Energy Dashboard, which does it correctly:

![image](https://user-images.githubusercontent.com/1783586/193987658-5b693ed4-d306-4b18-a745-d8540de9c590.png)

![image](https://user-images.githubusercontent.com/1783586/193987672-9246f086-37b7-421a-9caf-a321d99eada9.png)

### What version of Home Assistant Core has the issue?

Home Assistant Core 2022.6.5

### What was the last working version of Home Assistant Core?

-

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Statistics Graph

### Link to integration documentation on our website

https://www.home-assistant.io/dashboards/statistics-graph/
