### ISSUE TITLE
Conditional card no longer working

### ISSUE THREAD

**Issue by gigatexel** [home-assistant/frontend#14033]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've been using the conditional card below for quite a while now.
Since upgrading to 2022.10 beta and now 2022.10.1, it started failing.

```
type: conditional
conditions:
  - entity: sensor.washing_machine_status
    state_not: 'off'
  - entity: sensor.washing_machine_status
    state_not: not_connected
card:
  type: custom:stack-in-card
  mode: vertical
  cards:
// contents
```

The `sensor.washing_machine_status` has the value program_ended.
This is visible in the card-editor and in the dev-tools.
Also, in the card-editor it is clearly seen that the condition evaluates to "true" because the contents is hidden.
However, in the dashboard itself, the card remains visible.

![image](https://user-images.githubusercontent.com/65073191/194557212-1a9c1e39-52d0-420c-8a94-27925b0a9769.png)

![image](https://user-images.githubusercontent.com/65073191/194557488-85db38a3-085f-41e5-b449-74a75fc95158.png)

I have tried multiple browsers and even physically different PC's. It is present on PC and on the iOS app.

### Describe the behavior you expected

Evaluating correctly as it did before.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.10.1

**Comment by karwosts** [comment]
Suspect this might be something related to your custom:stack-in-card?

Does it work properly if you use a different card type?

I tried to reproduce this with just default cards and it works as expected for me.

```
type: conditional
conditions:
  - entity: input_boolean.mybool
    state_not: 'off'
  - entity: input_boolean.mybool
    state_not: otherstate
card:
  show_name: true
  show_icon: true
  type: button
  tap_action:
    action: toggle
  entity: input_boolean.mybool
  ```

**Comment by ildar170975** [comment]
This code works as expected:
```
type: conditional
conditions:
  - entity: input_boolean.test_boolean
    state_not: 'on'
  - entity: input_boolean.test_boolean_2
    state_not: 'on'
card:
  type: custom:stack-in-card
  mode: vertical
  cards:
    - type: entities
      entities:
        - sun.sun
    - type: glance
      entities:
        - sun.sun
```
