### ISSUE TITLE
Counter: Increment service fails from lovelace button

### ISSUE THREAD

**Issue by chherman0** [home-assistant/frontend#14039]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

using the call service counter:increment on a button card results in a failed to call service in the attached screenshot. This happens with all counters and counter services in lovelace. No issues in the dev tools>services.
<img width="742" alt="counter bug" src="https://user-images.githubusercontent.com/37340551/194594904-45bacbcf-7e3f-4f8a-80ed-e11799e73ad7.png">

### Describe the behavior you expected

it should increase/decrease the counter number 

### Steps to reproduce the issue

1.make button card
2.set tap to call service increment:counter
3.results in issue
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.1

### In which browser are you experiencing the issue with?

Google Chrome 106.0.5249.91, MS Edge 106.0.1370.34

### Which operating system are you using to run this browser?

Win 11 Home 22H2

### Problem-relevant frontend configuration

```yaml
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: counter.increment
  data: {}
  target:
    entity_id: counter.old_coop_good_egg
entity: counter.old_coop_good_egg
show_state: true
```

### Additional information

<img width="742" alt="counter bug" src="https://user-images.githubusercontent.com/37340551/194596099-1d862352-6b1b-49ff-913e-a780e38151de.png">

happens with all counters and input numbers, new and old ones
