### ISSUE TITLE
Calendar does not update the day in dayGridDay

### ISSUE THREAD

**Issue by joejulian** [home-assistant/frontend#14235]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With this card:
```
          - type: calendar
            entities:
              - calendar.family
              - calendar.her
              - calendar.him
              - calendar.holidays_in_united_states
            initial_view: dayGridDay
```
each day you have to hit the "today" button to see that day's events.

### Describe the behavior you expected

I expected that if the calendar is already displaying "today" that when the day changes, the card would be refreshed to the new day.

### Steps to reproduce the issue

1. Add the calendar card (see description)
2. Wait for tomorrow
3. See that the card's still showing yesterday
...

### What version of Home Assistant Core has the issue?

core-2023.2.0

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

Android App

### Which operating system are you using to run this browser?

Android

### Additional information

The checkboxes:

- I have cleared the cache of my browser. *
- I have tried a different browser to see if it is related to my browser. * 

I don't believe these are applicable because I'm not using a browser. I only checked them so I could submit the issue. If I'm wrong, please provide guidance.
