### ISSUE TITLE
config-template-card flickering after updating to 2022.11

### ISSUE THREAD

**Issue by Matman37** [home-assistant/frontend#14269]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After Updating to 2022.11.0 (from 2022.10.5) my custom:config-template-card is flickering (graphic shifting for some miliseconds, very annoying. function is ok). I'm using a 3D Floor-Plan overlapped with state-labels and icons.

### Describe the behavior you expected

no flickering

### Steps to reproduce the issue

1. Adding custom:config-template-card 
2. 
3.
...

### What version of Home Assistant Core has the issue?

2022.11.0

### What was the last working version of Home Assistant Core?

2022.10.5

### In which browser are you experiencing the issue with?

Edge, Mozilla Firefox, Companion-App (iOs)

### Which operating system are you using to run this browser?

iOs, Win10

### Problem-relevant frontend configuration

```yaml
type: custom:config-template-card
entities:
  - sensor.temperature
  - sensor.smokesensora1
  - sensor.humidity
  - binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone
  - binary_sensor.motionsensora1
  - binary_sensor.vibrationa1
  - binary_sensor.lumi_lumi_sensor_wleak_aq1_iaszone
  - light.hue_lampe_1
  - light.hue_lampe_2
  - light.hue_lampe_3
  - light.lichter
  - switch.sonoff
  - switch.schalter_1
  - light.wled
  - sun.sun
card:
  type: picture-elements
  image: /local/floor/alles-aus.png
  style: |
    ha-card:first-child {
      background: rgba(42, 46, 48, 1)
    }
  elements:
    - type: image
      action: none
      entity: sun.sun
      state_image:
        above_horizon: /local/floor/alles-aus.png
        below_horizon: /local/floor/alles-aus.png
      tap_action:
        action: none
      hold_action:
        action: none
      style:
        top: 50%
        left: 50%
        width: 100%
        height: 100%
    - type: image
      action: none
      entity: switch.shelly1
      hold_action:
        action: none
      tap_action:
        action: none
      state_image:
        'on': /local/floor/bad-an.png
        'off': /local/floor/transparent.png
        unavailable: null
      style:
        mix-blend-mode: lighten
        top: 50%
        left: 50%
        width: 100%
        height: 100%
    - type: image
      action: none
      entity: light.hue_lampe_2
      hold_action:
        action: none
      tap_action:
        action: none
      state_image:
        'on': /local/floor/schlaf-an.png
        'off': /local/floor/transparent.png
        unavailable: null
      style:
        mix-blend-mode: lighten
        top: 50%
        left: 50%
        width: 100%
        height: 100%
    - type: image
      action: none
      entity: light.hue_lampe_3
      hold_action:
        action: none
      tap_action:
        action: none
      state_image:
        'on': /local/floor/wohnen-an.png
        'off': /local/floor/transparent.png
        unavailable: null
      style:
        mix-blend-mode: lighten
        top: 50%
        left: 50%
        width: 100%
        height: 100%
    - type: image
      action: none
      entity: switch.sonoff_100145f70e
      hold_action:
        action: none
      tap_action:
        action: none
      state_image:
        'on': /local/floor/flur-an.png
        'off': /local/floor/transparent.png
        unavailable: null
      style:
        mix-blend-mode: lighten
        top: 50%
        left: 50%
        width: 100%
        height: 100%
    - type: image
      action: none
      entity: light.hue_lampe_1
      hold_action:
        action: none
      tap_action:
        action: none
      state_image:
        'on': /local/floor/kueche-an.png
        'off': /local/floor/transparent.png
        unavailable: null
      style:
        mix-blend-mode: lighten
        top: 50%
        left: 50%
        width: 100%
        height: 100%
    - type: image
      action: none
      entity: light.wled
      hold_action:
        action: none
      tap_action:
        action: none
      state_image:
        'on': /local/floor/tv-an.png
        'off': /local/floor/transparent.png
        unavailable: null
      style:
        mix-blend-mode: lighten
        top: 50%
        left: 50%
        width: 100%
        height: 100%
    - type: state-icon
      entity: switch.shelly1pm_98cdac2de405
      icon: mdi:lightbulb
      style:
        left: 48.6%
        top: 18.3%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: toggle
    - type: state-icon
      entity: switch.sonoff_100145f70e
      icon: mdi:lightbulb
      style:
        left: 55.6%
        top: 37.5%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: toggle
    - type: state-icon
      entity: light.hue_lampe_1
      icon: mdi:lightbulb
      style:
        left: 37.7%
        top: 29.6%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: toggle
    - type: state-icon
      entity: light.hue_lampe_2
      icon: mdi:lightbulb
      style:
        left: 70.8%
        top: 42.7%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: toggle
    - type: state-icon
      entity: light.hue_lampe_3
      icon: mdi:lightbulb
      style:
        left: 42.5%
        top: 48.4%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: toggle
    - type: state-icon
      entity: binary_sensor.vibrationa1
      icon: null
      style:
        left: 56.6%
        top: 10.8%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: none
    - type: state-icon
      entity: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone
      icon: null
      style:
        left: 60.2%
        top: 27.9%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: none
    - type: state-icon
      entity: binary_sensor.motionsensora1
      icon: null
      style:
        left: 85.8%
        top: 48.1%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: none
    - type: state-icon
      entity: binary_sensor.lumi_lumi_sensor_wleak_aq1_iaszone
      icon: null
      style:
        left: 27.7%
        top: 24.4%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: none
    - type: state-icon
      entity: light.wled
      icon: mdi:led-strip-variant
      style:
        left: 26.6%
        top: 61.9%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: toggle
    - type: state-label
      entity: sensor.temperature
      style:
        left: 61.4%
        top: 64.2%
        color: '#000'
        border-radius: 10%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
        font-size: 11px
        font-weight: bold
    - type: state-icon
      entity: alarm_control_panel.home_alarm
      icon: null
      style:
        left: 71.7%
        top: 10.92%
        '--iron-icon-stroke-color': '#969696'
        border-radius: 20%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
      tap_action:
        action: none
    - type: state-label
      entity: sensor.humidity
      style:
        left: 50.5%
        top: 64.2%
        color: '#000'
        border-radius: 10%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
        font-size: 11px
        font-weight: bold
    - type: state-label
      entity: sensor.smokesensora1
      style:
        left: 87%
        top: 64.2%
        color: '#000'
        border-radius: 50%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
        font-size: 11px
        font-weight: bold
    - type: state-label
      entity: sensor.lumi_lumi_sensor_motion_aq2_illuminance
      style:
        left: 74.1%
        top: 64.2%
        color: '#000'
        border-radius: 10%
        text-align: center
        background-color: rgba(255, 255, 255, 0.3)
        font-size: 11px
        font-weight: bold
```

### Additional information

Tried to remove Labels and icons.
Tried to move to complete new Dashbaord
no success
