### ISSUE TITLE
Bug with last Core update - Multiple line everywere (all borders showed)

### ISSUE THREAD

**Issue by XenoPsyLa** [home-assistant/frontend#14280]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have updating the last core update 2022.11.1 (frome 2022.10.5) and my dashboard is full of lines.
Something have a idea to get invisible and have correct behavior  ?

### Describe the behavior you expected

The line must be invisible.

### Steps to reproduce the issue

1. Upgrade 2022.10.5 to 2022.11.1
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.11.1

### What was the last working version of Home Assistant Core?

2022.10.5

### In which browser are you experiencing the issue with?

Brave, Edge, iOS, all affected

### Which operating system are you using to run this browser?

Windows 10 20H2

### Problem-relevant frontend configuration

```yaml
type: custom:vertical-stack-in-card
cards:
  - type: custom:button-card
    name: Hall d'entrée
  - type: picture-glance
    title: Hall d'entrée
    entities:
      - light.entree
    image: /local/images/400/entree.jpg
  - type: grid
    square: false
    columns: 5
    cards:
      - type: custom:button-card
        color_type: card
        entity: binary_sensor.porte_d_entree
        name: Porte Ouverte
        state:
          - value: 'on'
            color: rgb(200, 60, 60)
            icon: mdi:alert
            styles:
              card:
                - animation: blink 2s ease infinite
          - operator: default
            color: rgb(72, 164, 79)
            icon: mdi:shield-check
            styles:
              card:
                - filter: opacity(0%)
      - type: custom:gap-card
      - type: custom:button-card
        entity: sensor.porte_entree_4
        show_name: false
        color: rgb(255, 0, 0)
        state:
          - value: state 1
            color: rgb(72, 164, 79)
            icon: mdi:door-closed-lock
          - value: state 2
            color: rgb(200, 60, 60)
            icon: mdi:door-open
          - value: state 3
            color: rgb(72, 164, 79)
            icon: mdi:door-closed
          - value: state 4
            color: rgb(200, 60, 60)
            icon: mdi:door-open
      - type: custom:gap-card
      - type: custom:button-card
        entity: switch.verrouillage_porte
        show_name: false
        state:
          - value: 'on'
            color: rgb(72, 164, 79)
            icon: mdi:lock-check
          - operator: default
            color: rgb(72, 114, 164)
            icon: mdi:lock-open-remove
  - type: entities
    entities:
      - entity: light.exterieur_entree_1
        icon: mdi:coach-lamp


Or for TV Remote :

  - type: grid
    square: false
    columns: 5
    cards:
      - type: custom:gap-card
      - type: custom:gap-card
      - type: button
        icon: mdi:remote
        icon_height: 40px
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Télécommande
              content:
                type: vertical-stack
                cards:
                  - type: custom:gap-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        type: custom:button-card
                        icon: mdi:arrow-up
                        tap_action:
                          action: call-service
                          service: rest_command.orange_up
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:arrow-left
                        tap_action:
                          action: call-service
                          service: rest_command.orange_left
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:keyboard-return
                        tap_action:
                          action: call-service
                          service: rest_command.orange_ok
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:arrow-right
                        tap_action:
                          action: call-service
                          service: rest_command.orange_right
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        type: custom:button-card
                        icon: mdi:arrow-down
                        tap_action:
                          action: call-service
                          service: rest_command.orange_down
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        type: custom:button-card
                        icon: mdi:backup-restore
                        tap_action:
                          action: call-service
                          service: rest_command.orange_back
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                        styles:
                          card:
                            - width: 2px
                      - type: custom:button-card
                        color_type: blank-card
                        styles:
                          card:
                            - width: 2px
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:menu
                        tap_action:
                          action: call-service
                          service: rest_command.orange_menu
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: custom:gap-card
                    height: 7
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-1
                        tap_action:
                          action: call-service
                          service: rest_command.orange_1
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-2
                        tap_action:
                          action: call-service
                          service: rest_command.orange_2
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-3
                        tap_action:
                          action: call-service
                          service: rest_command.orange_3
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-4
                        tap_action:
                          action: call-service
                          service: rest_command.orange_4
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-5
                        tap_action:
                          action: call-service
                          service: rest_command.orange_5
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-6
                        tap_action:
                          action: call-service
                          service: rest_command.orange_6
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-7
                        tap_action:
                          action: call-service
                          service: rest_command.orange_7
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-8
                        tap_action:
                          action: call-service
                          service: rest_command.orange_8
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-9
                        tap_action:
                          action: call-service
                          service: rest_command.orange_9
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:minus
                        tap_action:
                          action: call-service
                          service: rest_command.orange_chdown
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:numeric-0
                        tap_action:
                          action: call-service
                          service: rest_command.orange_0
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:plus
                        tap_action:
                          action: call-service
                          service: rest_command.orange_chup
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: custom:gap-card
                    height: 7
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:rewind
                        tap_action:
                          action: call-service
                          service: rest_command.orange_fbwd
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:play-pause
                        tap_action:
                          action: call-service
                          service: rest_command.orange_playpause
                          data: {}
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:fast-forward
                        tap_action:
                          action: call-service
                          service: rest_command.orange_ffwd
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: rgb(200,0,0)
                        type: custom:button-card
                        icon: mdi:record
                        tap_action:
                          action: call-service
                          service: rest_command.orange_rec
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                        styles:
                          card:
                            - width: 2px
                      - type: custom:button-card
                        color_type: blank-card
                        styles:
                          card:
                            - width: 2px
                      - type: custom:button-card
                        show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        icon: mdi:youtube
                        tap_action:
                          action: call-service
                          service: rest_command.orange_vod
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: horizontal-stack
                    cards:
                      - type: custom:button-card
                        color_type: blank-card
                      - show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: rgb(200,0,0)
                        type: custom:button-card
                        icon: mdi:volume-off
                        tap_action:
                          action: call-service
                          service: rest_command.orange_volmute
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                        styles:
                          card:
                            - width: 2px
                      - type: custom:button-card
                        color_type: blank-card
                        styles:
                          card:
                            - width: 2px
                      - show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        type: custom:button-card
                        icon: mdi:volume-minus
                        tap_action:
                          action: call-service
                          service: rest_command.orange_voldown
                          data: {}
                      - show_name: false
                        styles:
                          card:
                            - background: rgba(255,255,255,0.45)
                            - width: 45px
                            - height: 45px
                            - border-radius: 50%
                          icon:
                            - width: 25px
                            - color: '#303741'
                        type: custom:button-card
                        icon: mdi:volume-plus
                        tap_action:
                          action: call-service
                          service: rest_command.orange_volup
                          data: {}
                      - type: custom:button-card
                        color_type: blank-card
                  - type: custom:gap-card
```

### Additional information

![ha_pb1](https://user-images.githubusercontent.com/13435980/199814229-c7a16e64-5eb9-47e9-bf9b-72550a41357a.JPG)
![ha_pb2](https://user-images.githubusercontent.com/13435980/199809558-c8ddf7c3-b0bc-48d8-a0f0-85967cc6c29c.JPG)
![ha_pb3](https://user-images.githubusercontent.com/13435980/199814898-13113788-182e-4677-8f63-7b7da3537ba5.JPG)
