### ISSUE TITLE
Pictute Elements, not showing state_image

### ISSUE THREAD

**Issue by DravenSA** [home-assistant/frontend#14284]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Love the look, but unfortunately  Picture Elements have stopped working with IMAGES EXAMPLE below an extract from https://www.home-assistant.io/dashboards/picture-elements/#image-element

```
type: picture-elements
image: /local/floorplan.png
elements:
  # state_image & state_filter - toggle on click
  - type: image
    entity: light.living_room
    tap_action:
      action: toggle
    image: /local/living_room.png
    state_image:
      "off": /local/living_room_off.png
    filter: saturate(.8)
    state_filter:
      "on": brightness(120%) saturate(1.2)
    style:
      top: 25%
      left: 75%
      width: 15%
```

My simple one was

```
type: picture-elements
image: /local/irrigation/mon-sun1.png
elements:
  - type: image
    entity: input_boolean.water_monday
    tap_action:
      action: toggle
    state_image:
      'off': /local/off.png
      'on': /local/on/png

```
Worked like a charm before update, 2022.11, even updated to 2022.11.1 still not working

But then again the Picture Elements stopped pushing aspect ratio a long time ago too, so now it CROPS instead of CONSTRAINT the image to FIT the aspect Ratio.

Would love both to be fixed, but at least the First one is a little more important

### Describe the behavior you expected

State_image pics to show

### Steps to reproduce the issue

1.Updated to 2022.11.0
2.then updated to 2022.11.1
3.
...

### What version of Home Assistant Core has the issue?

2022.11.0 and 2022.11.1

### What was the last working version of Home Assistant Core?

2022.10. whatever the last one was

### In which browser are you experiencing the issue with?

All of them

### Which operating system are you using to run this browser?

Windows 10
