### ISSUE TITLE
Picture Elements Card - missing overlaying elements

### ISSUE THREAD

**Issue by oopiicaa** [home-assistant/frontend#14297]
### The problem

I have a few Picture Elements cards configured to control my lights, but this is broken after upgrading to 2022.11.0 - images on top of the picture are now gone and nothing happens if I click on the spot where the dots (images) should be. Resources (images) are locally accessible.

Example:
![image](https://user-images.githubusercontent.com/24246157/199667804-a5b3c2c9-04bd-4000-8c77-697c86be07f7.png)

There should be clickable dots on places circled with red:
![image](https://user-images.githubusercontent.com/24246157/199667999-33839f88-7772-4058-afe5-6977b4fc669c.png)

Images are locally accessible:
![image](https://user-images.githubusercontent.com/24246157/199668132-c8885f74-ca43-4721-98e0-3f7b58270cd9.png)
![image](https://user-images.githubusercontent.com/24246157/199668166-b4e54792-0135-4f4f-b99a-7152b37e433b.png)
![image](https://user-images.githubusercontent.com/24246157/199668213-2482a101-fa62-4b60-ac9b-9a5a762c3492.png)
![image](https://user-images.githubusercontent.com/24246157/199668239-1156d1ca-d81c-4a0b-b8c4-83a5164a1406.png)

Nothing in the logs. Restarted HA instance a few time and it does not help.
The same issue is present on my desktop PC (Firefox, Chrome, Edge), on my tablet (via browser and Android app) and mobile (Android app).

Mentioned [here](https://community.home-assistant.io/t/2022-11-a-heck-of-a-release/483295/45?u=c1c3r0).

### What version of Home Assistant Core has the issue?

core-2022.11.0

### What was the last working version of Home Assistant Core?

core-2022.10.5

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
elements:
  - entity: group.kuhinja
    image: /local/lightbulb-group(1).png
    state_image:
      'on': /local/lightbulb-group-outline(1).png
    style:
      left: 5%
      top: 8%
    tap_action:
      action: toggle
    type: image
  - entity: switch.kuhinja_pc
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 23.3%
      top: 53.5%
    tap_action:
      action: toggle
    type: image
  - entity: switch.kuhinja_ikea
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 39%
      top: 18.3%
    tap_action:
      action: toggle
    type: image
  - entity: switch.kuhinja_ikea
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 80%
      top: 10%
    tap_action:
      action: toggle
    type: image
  - entity: switch.kuhinja_glavna
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 62.8%
      top: 20.4%
    tap_action:
      action: toggle
    type: image
  - entity: switch.emillux2
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 14%
      top: 81.5%
    tap_action:
      action: toggle
    type: image
image: /local/kuhinja1.jpg
type: picture-elements
```

**Comment by theone11** [comment]
> Adding width to state images seems to work

Does scale still work when using width?
My x y scaling is different

**Comment by cannondale99** [comment]
Even if you start with a new Picture Elements card, and then change the YAML from "type: state-badge" to "type: image" and then add your specific entity name, image location, the top and left percentages and then add the "state_image" it does not show the image.  The image only appears after adding what others have said "state_image: " 

This happened to me after upgrading to 2022.11.
Running Supervisor 2022.10.2  Operating System 9.3   Frontend 20221102.1

**Comment by theone11** [comment]
> My images are gone too.
> 
> ```yaml
> - type: image
>     state_image:
>       'on': /local/my-icons/garage-open.png
>       'off': /local/my-icons/garage-closed.png
>     entity: binary_sensor.garage_door_sensor
>     style:
>       top: 66%
>       left: 71%
>       transform: scale(0.6)
>     tap_action:
>       action: call-service
>       service: script.garage_remote
>     hold_action:
>       action: more-info
> ```
> 
> Adding
> 
> ```yaml
>     style:
>       width: 30%
> ```
> 
> brings the image back, but I can't set the correct width without reworking the whole UI.
> 
> _Home Assistant 2022.11.1 Supervisor 2022.10.2 Frontend 20221102.1 - latest_

Do you add the "width" and remove "scale" or do you leave them both?

**Comment by mrbaloghakos** [comment]
What I finally did is just added `width: 12%` to all my `image` elements. 
12% worked well for me, the UI now looks almost exactly like before. 
The red and yellow _icons_ were missing after the upgrade. 
Now you can see they are back:
![kSiYE4L - Imgur](https://user-images.githubusercontent.com/83340568/200595284-a285a2ac-c45d-46cb-b893-70fa8f073e21.png)

**Comment by Salvora** [comment]
Is this a bug or adding width requirement now?

**Comment by Smarf1** [comment]
> Is this a bug or adding width requirement now?

I wonder this too?

**Comment by hajo62** [comment]
> reverting to 2022.10

Just reverted with the actual data or have you restored a backup of your database?

**Comment by hajo62** [comment]
@rirofal

    reverting to 2022.10

Just reverted with the actual data or have you restored a backup of your database?

**Comment by rirofal** [comment]
> @rirofal
> 
> > reverting to 2022.10
> 
> Just reverted with the actual data or have you restored a backup of your database?

Kept the same data.

**Comment by hajo62** [comment]
> Just reverted

Did so and my pictures are back ;)
The "width: %" had not worked for me.

I hope that this will be handled as a bug and fixed. 

AND: A hint in the release notes if an _easy just roll_ back is possible would be perfect. Or a hint, if the database will be modified during update, which would result in the same.

**Comment by sinamics** [comment]
same problem. scale does not work even adding width.
reverted to v10.5

**Comment by smonesi** [comment]
I rolled back only the hui-image.ts file (before this https://github.com/home-assistant/frontend/pull/14245) and everything seems to be working fine without any "width" trick. Also the flickering is gone (mentioned here https://github.com/home-assistant/frontend/issues/14310). I don't know the negative side effects of this...

**Comment by honkerst** [comment]
11 days ago, and still no info about this. I'm going to downgrade until we have some confirmation about what to do. 

I don't really want to add width to dozens of missing elements that are all different sizes if this is going to be fixed at some point.

**Comment by otistarda** [comment]
Still no solution? it is not normal

**Comment by exus85** [comment]
same issue, I can't use my UI. 
Maybe @bramkragten can find a solution?

**Comment by otistarda** [comment]
> mismo problema, no puedo usar mi interfaz de usuario. Quizás@bramkragtenpuede encontrar una solución?

added     width: 6% and it worked for me

**Comment by sinamics** [comment]
Updated to version 11.4, and adding width 3% gives me almost the same behavior as version 10.5 without changing the transform properties.

My floorplan usecase:
```yaml
      - entity: light.{{ entity }}
        image: /local/images/floorplan_v2/transparent_square.png
        style:
          border: 1px solid red
          opacity: 1
          left: 80
          top: 80
          width: 3%
          transform: rotate(0deg) scale(2,2)  
```
