### ISSUE TITLE
Map not centering correctly when in a horizontal-stack & grid

### ISSUE THREAD

**Issue by yzaazy** [home-assistant/frontend#14298]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you put a map in a horizontal stack/grid, it does not center correctly, and when you move the map the title disappears.

![image](https://user-images.githubusercontent.com/8656211/200081326-856fc967-5beb-488f-9ed5-da309a67aa66.png)

![image](https://user-images.githubusercontent.com/8656211/200081351-189069a5-0aa0-4762-a3ff-6896d00cbf32.png)

### Describe the behavior you expected

The map should center like it does as a stand alone card or in a vertical-stack, and the title of the card should not disappear.

### Steps to reproduce the issue

1. go to the demo on demo.home-assistant.io
2. add a horizontal-stack or grid card
3. add a map in the horizontal-stack or grid card and add an entity and a title to the map
4. try to center the map with the center button below the zoom buttons

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

107.0.5304.88

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
title: Home Assistant
views:
  - icon: hass:home-assistant
    id: home
    title: Home
    cards:
      - type: map
        entities:
          - entity: person.arsaboo
        title: Map as cards
      - type: horizontal-stack
        cards:
          - type: map
            entities:
              - entity: person.arsaboo
            title: Map in horizontal-stack
            dark_mode: false
      - type: vertical-stack
        cards:
          - type: map
            entities:
              - entity: person.arsaboo
            title: Map in vertical-stack
      - square: true
        columns: 1
        type: grid
        cards:
          - type: map
            entities:
              - entity: person.arsaboo
            title: Map in grid
  - theme: Backend-selected
    title: test
    path: test
    badges: []
    cards: []
  - theme: Backend-selected
    title: test
    path: test
    badges: []
    cards: []
```
