### ISSUE TITLE
Script fields - required parameter with default not set in service yaml call

### ISSUE THREAD

**Issue by mdeweerd** [home-assistant/frontend#14304]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A script with required fields that have defaults can not be called from Developer Tools > Services when keeping the default values shown.

### Describe the behavior you expected

Script is callable from the UI without changing the default parameters.

### Steps to reproduce the issue

Create script:

```yaml
alias: Sample Script
fields:
  my_required_field:
    name: Required field
    default: 8
    required: true
    selector:
      number:
        min: 8
        max: 22
        mode: box
sequence: []
mode: single
```

Select this script in Developer Tools > Services

![image](https://user-images.githubusercontent.com/1504752/200121337-7d3e9ba6-d5ee-4a41-9e25-930f04b72876.png)

Even though all fields are filled, it's impossible to call the service.

When going to Yaml mode, the field is missing:

![image](https://user-images.githubusercontent.com/1504752/200121384-9231575b-40ec-4bea-913c-0e907af51b05.png)

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

Google Chrome Version 107.0.5304.88 (Build officiel) (64 bits)

### Which operating system are you using to run this browser?

Windows 10
