### ISSUE TITLE
Automation UI does not set value of ZWave Config

### ISSUE THREAD

**Issue by chrisjenx** [home-assistant/frontend#14307]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The UI doesn't not set the value when trying to use Z-Wave Devices Config Params as part of a condition:

- Pick Device
- Pick Config Param
- Pick Value you are checkin
- Error

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/1167793/200136016-fa272750-304b-4422-ae69-21de5684dbe3.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/1167793/200136026-d014eb14-4cff-4113-9e70-8a2415664820.png">
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/1167793/200136043-a31d8d3c-1d9e-4bed-904a-fba0fe8d2cd4.png">

### Describe the behavior you expected

Set the value in yaml and retest , works as expected.

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1167793/200136065-6b85e6f3-9950-41a8-9508-e693163075fa.png">

### Steps to reproduce the issue

1. Create automation
2. Create a condition/action/etc 
3. Pick Device Condition
4. Pick Z Wave switch (or any Z-Wave device)
5. Pick the Config param you want to check
6. Select the value 
7. Try to run/save -> Error/Condition fails
8. Set `value: ${value}` manually 
9. Re-test/save, works as expected

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

Brave/Chrome/Safari

### Which operating system are you using to run this browser?

macOSx 12.6

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by XplodingData** [comment]
I believe I'm having the same issue.

When creating an automation using the UI, and attempting to set the value of a Z-Wave parameter via an action, it misses a line of code (same as OP's missing "value" field) but works fine if added manually via YAML.  
It shows up as a **Message malformed: not a valid value for dictionary value @ data['type']** error when trying to save the automation.

![zwave bug 1](https://user-images.githubusercontent.com/91237040/206967674-fc2579fb-3997-4b3b-9db9-0766c93bb916.jpg)
![zwave bug 2](https://user-images.githubusercontent.com/91237040/206967696-db1fffc3-1a2b-4281-b5bf-b98640d6346b.jpg)

switching to "Edit in YAML" mode and changing the code to
```
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - cover.z_wave_garage_door_controller
condition: []
action:
  - device_id: 84171cc322b0521e24aeadfce5639507
    domain: zwave_js
    type: set_config_parameter
    parameter: 21
    bitmask: null
    subtype: 21 (Status LED 1 Color)
    value: 0  #ADD THIS LINE
alias: Testing Bug
```
seems to fix it.
This error only seems to have cropped up so far when setting the color to "off"
However, switching back to "Edit in visual editor" mode, the value field doesn't populate and is blank.

![zwave bug 3](https://user-images.githubusercontent.com/91237040/206968436-45fa3924-61ef-4a2e-9a56-cdd04d45ef9f.jpg)

But the automation will save and function.


#What version of Home Assistant Core has the issue?#
2022.11.1

#What was the last working version of Home Assistant Core?#
No response

#In which browser are you experiencing the issue with?#
Chrome Version 107.0.5304.106 (Official Build) (64-bit)

Which operating system are you using to run this browser?
Windows 7
