### ISSUE TITLE
Area Card Service Calls Fail

### ISSUE THREAD

**Issue by gadgetbazza** [home-assistant/frontend#14313]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking the light icon on area cards an error is displayed and the lights do not operate:

Failed to call service light/turn_off. must contain at least one of entity_id, deviced_id, area_id

### Describe the behavior you expected

I expected the light entities to toggle when clicking the icon on the area card

### Steps to reproduce the issue

1.Add an area card and select an area that has lights
2.Click the light icon to toggle the lights on or off
3.
...

### What version of Home Assistant Core has the issue?

2022.11.1

### What was the last working version of Home Assistant Core?

2022.7.6

### In which browser are you experiencing the issue with?

Google Chrome Version 107.0.5304.87 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Monterey 12.6

### Problem-relevant frontend configuration

```yaml
views:
  - theme: Backend-selected
    title: Home
    path: home
    icon: mdi:home
    subview: false
    badges: []
    cards:
      - type: area
        area: office
      - type: entities
        entities:
          - entity: scene.office_on
          - entity: scene.office_off
```

### Javascript errors shown in your browser console/inspector

```txt
hui-element.js?hacstag=249942054180547:1 HUI-ELEMENT 1.1.2 IS INSTALLED 
collapsable-cards.js?hacstag=364978303052:1 collapsable-cardsVersion: 0.0.1
auto-entities.js?hacstag=1677445841110:172 AUTO-ENTITIES 1.11.0 IS INSTALLED
mushroom.js?hacstag=444350375233:2846 🍄 Mushroom 🍄 - 2.3.3
button-card.js?hacstag=146194325342:425   BUTTON-CARD   Version 3.4.2 
power-distribution-card.js?hacstag=283578257254:917  POWER-DISTRIBUTION-CARD  2.5.4
weather-radar-card.js?hacstag=487680971210:1291   WEATHER-RADAR-CARD   Version 2.1.0    
frigate-hass-card.js?hacstag=394082552400:1155  FRIGATE-HASS-CARD  Version 4.0.0 
styles.ts:371 Uncaught (in promise) {code: 'invalid_format', message: 'must contain at least one of entity_id, device_id, area_id.'}
callService @ styles.ts:371
await in callService (async)
hass.callService @ honeycomb-menu.js:104
value @ hui-area-card.ts:85
handleEvent @ styles.ts:371
```

### Additional information

Initially upgraded to 2022.10.4 then encountered this problem.  Subsequently upgraded to 2022.11.1 to see if it was resolved, but problem remains.

Note the two scenes I created for office on and office off work just fine from the sample card, but the area card light icon does not.
