### ISSUE TITLE
empty stack cards add a margin

### ISSUE THREAD

**Issue by sevorl** [home-assistant/frontend#14329]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you add an empty stack card (horizontal or vertical stack) to a lovelace dashboard, this adds an extra margin between cards.
This is a problem when conditional cards are used within the stack card, so the stack card is not always empty.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/81764300/200501706-1f347024-6046-4640-9458-e968b0c89d8f.png">

### Describe the behavior you expected

Empty cards should not add extra space between other cards.

### Steps to reproduce the issue

1. Add a entity card to a lovelace dashboard (Or use yaml sample below)
2. Add a horizontal stack card without content, or with a conditional card where the condition is false
3. Add two more entity cards
4. Observe that the gap between the visible cards is different. The empty horizontal stack adds an extra gap
...

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

Google Chrome 106.0.5249.119

### Which operating system are you using to run this browser?

Win 10

### Problem-relevant frontend configuration

```yaml
- theme: Backend-selected
    title: conditional card gap test
    path: conditional-card-gab-test
    badges: []
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: sensor.time
      - type: vertical-stack
        cards: []
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: sensor.time
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: sensor.time
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```
