### ISSUE TITLE
picture-entity card in Panel View does not expand to full panel on popup

### ISSUE THREAD

**Issue by mesa72** [home-assistant/frontend#14335]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Apologies if this is not a bug but just a change in UI behavior.

In versions prior to 2022.11.x, when clicking on a picture entity card within a panel view it would popup and encompass the entire panel. Since version 2022.11.x, the popup is small and not useful for camera views.

Thank you,

![Screenshot 2022-11-08 125511](https://user-images.githubusercontent.com/104174713/200673439-caff5432-7e07-4b05-8770-b6aa8f4b846b.jpg)

### Describe the behavior you expected

Ideally the picture-entity card would popup full inside a panel when clicked.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

11.0.0

### In which browser are you experiencing the issue with?

All but this is Chrome Version 107.0.5304.88

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
- theme: Backend-selected
    type: panel
    icon: mdi:cctv
    badges: []
    cards:
      - square: false
        columns: 2
        type: grid
        cards:
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            entity: camera.driveway
            name: Driveway
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            entity: camera.front1
            name: Driveway
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            entity: camera.northwest
            name: Driveway
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            entity: camera.eastpath2
            name: Driveway
```
