### ISSUE TITLE
Initial input_select option (after boot) no longer triggers actions

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/frontend#14362]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you have an input_select and you use it to trigger an action or use it as input for a card (e.g. for `auto-entities`), the initial option does not trigger anything anymore once you switch away from it and back.

See below on how to reproduce.

Here as a gif. It works when I use it in HA companion app. There it also shows that the option selection was never changed, e.g. whilst in browsers I see that I selected the initial option, in HA companion app it still shows the previous selection.

![input_select_issue](https://user-images.githubusercontent.com/57034871/201286530-78f7023c-9d55-4a0d-91c6-7b0744a3fb23.gif)

```
input_select:
  dropdown_wildcards:
    name: Dropdown Wildcards
    options:
      - 'Xiaomi Temperature'
      - 'Xiaomi Humidity'
      - 'Climate'
      - 'eQ-3 Temperature'
      - 'eQ-3 Valve'
      - 'Power'
      - 'Light'
  ```

### Describe the behavior you expected

When you select the initial option again, it should again trigger whatever is reading it.

### Steps to reproduce the issue

1. Create input_select
2. Make input_select source for auto-entities card
3. Restart HA
4. Change input_select option to e.g. option 2  --> card changes
5. Change input_select back to initial option (e.g. option 1)  --> nothing happens.

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Latest Chrome & Firefox. Works with HA companion app

### Which operating system are you using to run this browser?

Win 10
