### ISSUE TITLE
Statistic graph Card and multi series - not all bars fully shown

### ISSUE THREAD

**Issue by wonderiuy** [home-assistant/frontend#14375]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The statistic graph card soes not display multi series correctly, it cuts the first and the last series in the first and last data aggregation, as depicted here:
![Screenshot](https://user-images.githubusercontent.com/53263262/201513838-d7045554-d55d-443a-895e-9e435c4853f6.png)

### Describe the behavior you expected

Correctly show al the series in all the period aggregation

### Steps to reproduce the issue

```
chart_type: bar
period: day
days_to_show: 7
type: statistics-graph
entities:
  - entity: sensor.pro_6000_9e5e_time
    name: Alle
  - entity: sensor.smart_series_7000_be71_time
    name: Flavia
stat_types:
  - state
title: Spazzolino
```

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Win10
