### ISSUE TITLE
Sensor graph shows data from a different sensor after a while (Safari and iOS app)

### ISSUE THREAD

**Issue by stalar** [home-assistant/frontend#14381]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have two sensor graphs on my dashboard. Initially when loading the page, the graphs work well and show the correct data. After a while (10s of seconds or minutes) the graphs start to show the **same** data. 

Here is everything working well:
![Screenshot 2022-11-14 at 15 22 43](https://user-images.githubusercontent.com/3154690/201686395-a3de84d9-3c80-4f25-bbe0-7df9db2072d1.png)

This is what it looks like after a little while:
![Screenshot 2022-11-14 at 15 24 54](https://user-images.githubusercontent.com/3154690/201686479-b57038b4-229b-48c1-a746-10ae715f300a.png)

### Describe the behavior you expected

I expect the graphs to keep showing the data for the sensor they are configured for, not for a different sensor.

### Steps to reproduce the issue

1. Add two graphs for two different sensors
2. Load the dashboard in Safari on macOS or in the iOS app
3. Wait a few minutes

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Safari Version 16.1

### Which operating system are you using to run this browser?

macOS Ventura 13.0

### Problem-relevant frontend configuration

```yaml
hours_to_show: 24
graph: line
type: sensor
entity: sensor.qubino_3_phase_smart_meter_electric_consumption_w
detail: 2

hours_to_show: 24
graph: line
type: sensor
entity: sensor.solaredge_current_power
detail: 2
name: Solpaneler
```

### Additional information

I have not observed this behaviour in Chrome.
