### ISSUE TITLE
New Tile card shows different value for timestamp sensor

### ISSUE THREAD

**Issue by awolkers** [home-assistant/frontend#14380]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The way the timestamp value of an entitie is shown in the new tile card differs from the way it is shown in a normal entities card. The entities card shows the time past or time left until the date value. The tile card just shows the date value.

Entitie card value
![enitites-card](https://user-images.githubusercontent.com/2470050/201613218-6ed4b95c-28df-4c31-ba77-8ff9023917af.png)

Tile card value
![tile-card](https://user-images.githubusercontent.com/2470050/201613319-41feb354-6ecb-4576-ae36-3901749a857c.png)

### Describe the behavior you expected

I expect the value to be the same as the entitie card since this has more value to the user.

### Steps to reproduce the issue

1. Create a dashboard with both an entities card and a tile card
2. Make sure the entitie used is time based
3. Check the difference
...

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Google Chrome Version 107.0.5304.88 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows

### State of relevant entities

```txt
state: 2022-11-14T04:08:01+00:00
device_class: timestamp
```

### Problem-relevant frontend configuration

```yaml
- type: tile
  entity: sensor.vaatwasser_remaining_program_time
  name: Resterende tijd

- type: entities
    title: Vaatwasser
    entities:
      - entity: sensor.vaatwasser_remaining_program_time
        secondary_info: last-changed
        name: Resterende tijd

```

### Additional information

I think is not browser related but just how the value is visualized.
