### ISSUE TITLE
picture-elements card state_image no longer works

### ISSUE THREAD

**Issue by nialfrancis** [home-assistant/frontend#14394]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A picture-elements card with an entiy with state_image items defined no longer displays the state_images

### Describe the behavior you expected

The state_image images should be displayed when the entity matches the state

### Steps to reproduce the issue

1. Create a picture-elements card
2. Add an entity with a state_image

### What version of Home Assistant Core has the issue?

2022.11.2

### What was the last working version of Home Assistant Core?

2022.10.5

### In which browser are you experiencing the issue with?

Microsoft Edge Version 107.0.1418.42 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
elements:
  - entity: group.people
    state_image:
      not_home: /local/dot.png
      home: /local/txpx.png
    type: image
image: /local/background.png
type: picture-elements
```

### Additional information

Another user on discord has reported a similar issue. My configuration worked for more than a year without issue or changes, the other user also said that the configuration was previously working also.
