### ISSUE TITLE
Can not increase icon_height over 30px

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#14433]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

trying to have an icon a core type:button use the full button space, with below config, it appears we can not go beyond 30px. we can make the icon smaller

https://www.home-assistant.io/dashboards/button/#icon_height

https://github.com/home-assistant/frontend/blob/2223ffd7eedd721196f3673958528e5dab1654d0/src/panels/lovelace/cards/hui-button-card.ts#L187

### Describe the behavior you expected

allow the icon to be full size up to 100%

### Steps to reproduce the issue

1. create `type: button`
2. set `icon_height: 50px` of `icon_height: 80%`
3.
...

### What version of Home Assistant Core has the issue?

2022.11.4

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS Ventura 13.0

### Problem-relevant frontend configuration

```yaml
- type: grid
    columns: 8
    cards:

      - type: custom:button-card
        template: subview
        variables:
          tooltip: Hue scenes
          picture: /local/hue_scenes/hue.jpg
          path: /ui-sub-views/hue_scenes

      - type: custom:button-card
        template: subview
        icon: mdi:home-lightbulb
        variables:
          tooltip: Alle lampen
          path: /ui-sub-views/all_lights

      - type: button
        icon: mdi:home-lightbulb
        icon_height: 30px     <----- can get any bigger?
        tap_action:
          action: navigate
          navigation_path: /ui-sub-views/all_lights
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_
