### ISSUE TITLE
Picture Elements Card State Images don't work

### ISSUE THREAD

**Issue by mattinglis** [home-assistant/frontend#14508]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Picture Elements Card State Images no longer work.

Add a picture elements card, and add some state images, the image no longer changes with the state.

State labels and icons work, but the state image doesn't display

### Describe the behavior you expected

State Image should change with the state of the entity

### Steps to reproduce the issue

1. Add Picture Elements Card
2. Add State Images to card
3. Change state of device
...

### What version of Home Assistant Core has the issue?

2022.11 onwards up to and including 2022.12.0b0

### What was the last working version of Home Assistant Core?

2022.10

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.121  & Microsoft Edge 107.0.1418.62

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
State on and off doesn't change image
```

### Problem-relevant frontend configuration

```yaml
type: picture-elements
image: /local/images/BetterCraigsRoad_WallsOnly2Floors3.png
elements:
  - type: image
    entity: light.sitting_room
    image: /local/images/Transparent.png
    style:
      top: 51%
      left: 50%
      width: 100%
      height: 100%
    state-image:
      'on': /local/images/SittingRoom_On.png
      'Off': /local/images/Transparent.png
  - type: state-label
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by ildar170975** [comment]
Any special reason to create a new issue about the same? )))
https://github.com/home-assistant/frontend/issues/14284
https://github.com/home-assistant/frontend/issues/14297
https://github.com/home-assistant/frontend/issues/14308
https://github.com/home-assistant/core/issues/81646
https://github.com/home-assistant/frontend/issues/14394

**Comment by spacegaier** [comment]
Please double check your config. Your second state is listed as "Off" with a capital "o" which is not the usual off state of a light. Should be "off" instead.

@ildar170975 This is a different issue here, since "width" is used, which from my initial quick read of the other issues is a clear distinction.

**Comment by mattinglis** [comment]
I have tried with 'Off', 'off', 'OFF' as well as 'On', 'on', 'ON'

Nothing works.

Even having multiple states with all different permutations doesn't work

`type: picture-elements
image: /local/images/BetterCraigsRoad_WallsOnly2Floors3.png
elements:
  - type: image
    entity: light.sitting_room
    image: /local/images/Transparent.png
    style:
      top: 51%
      left: 50%
      width: 1200%
      height: 1000%
    state-image:
      'off': /local/images/Transparent.png
      'on': /local/images/SittingRoom_On.png
      'On': /local/images/SittingRoom_On.png
      'Off': /local/images/Transparent.png
  - type: state-label
    entity: light.sitting_room
    style:
      top: 51%
      left: 59%
      height: 100%
      width: 100%
      color: white
`

Interesting that you say its not a capital O State Label displays the current state as 'On' and 'Off' with capital O for the state of all my hue lights.

and yes @ildar170975 it is different, i have width present which is the solution to all of those issues you present.

**Comment by ildar170975** [comment]
> it is different

Oh, I see, my bad.
Then check this - it works:
```
type: picture-elements
image: /local/images/test/blue.jpg
elements:
  - type: image
    entity: input_boolean.test_boolean
    image: /local/images/test/lightgreen.jpg
    style:
      top: 51%
      left: 50%
      width: 50px
      height: 50px
    state_image:
      on: /local/images/test/pink.jpg
      off: /local/images/test/orange.jpg
    tap_action:
      action: toggle
```
with `on`/`off` and `"on"`/`"off"`.

![изображение](https://user-images.githubusercontent.com/71872483/205463107-ccc83eb3-1d53-455e-bba7-50e474f2e46a.png)

The initial problem comes from this typo - `"type: state-label"`
