### ISSUE TITLE
2022.12 Button card does not show idle state color for expired time helpers

### ISSUE THREAD

**Issue by fluxsmith** [home-assistant/frontend#14576]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Prior to 2022.12 when a timer helper was in idle state (timer expired), the button card showed it in blue, when the timer was active it was yellow (in the dark theme).  As of the 2022.12 betas it is always yellow.
Card is defined like:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: more-info
            entity: timer.motion_nancy_timer
            name: ' '
            icon: mdi:motion-sensor
            show_state: false
            state_color: true

### Describe the behavior you expected

State to indicate idle timer as inactive

### Steps to reproduce the issue

1. Create timer
2. Add button card to dashboard representing timer
3. Activate timer
4. Timer expires
5. Dashboard state does not change

(Tested in Edge and Chrome)
...

### What version of Home Assistant Core has the issue?

2022.12.0b5

### What was the last working version of Home Assistant Core?

2022.11.x

### In which browser are you experiencing the issue with?

Google Chrome Version 108.0.5359.73

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
State: idle
Attributes:
duration: '0:05:00'
editable: true
icon: mdi:motion-sensor
friendly_name: Motion Nancy Timer
```

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: more-info
            entity: timer.motion_nancy_timer
            name: ' '
            icon: mdi:motion-sensor
            show_state: false
            state_color: true
          - type: button
            tap_action:
              action: more-info
            entity: timer.occupancy_nancy_timer
            name: Nancy
      - type: vertical-stack
        cards:
          - type: button
            tap_action:
              action: more-info
            entity: timer.motion_jon_timer
            name: ' '
          - type: button
            tap_action:
              action: more-info
            entity: timer.occupancy_jon_timer
            name: Jon
      - type: vertical-stack
        cards:
          - type: button
            tap_action:
              action: more-info
            entity: timer.motion_office_timer
            name: ' '
            icon: mdi:motion-sensor
          - type: button
            tap_action:
              action: more-info
            entity: timer.occupancy_office_timer
            name: Office
            show_state: false
      - type: vertical-stack
        cards:
          - type: button
            tap_action:
              action: more-info
            entity: timer.motion_kitchen_timer
            name: ' '
            icon: mdi:motion-sensor
          - type: button
            tap_action:
              action: more-info
            entity: timer.occupancy_kitchen_timer
            name: Kitchen
            show_state: false
      - type: vertical-stack
        cards:
          - type: button
            tap_action:
              action: more-info
            entity: timer.motion_living_timer
            name: ' '
            icon: mdi:motion-sensor
          - type: button
            tap_action:
              action: more-info
            entity: timer.occupancy_living_timer
            name: Living
            show_state: false
  - type: horizontal-stack
    cards:
      - type: button
        tap_action:
          action: more-info
        entity: timer.motion_aggregate
        name: ' '
      - type: button
        tap_action:
          action: more-info
        entity: timer.occupancy_aggregate
        name: ' '
```
