### ISSUE TITLE
Generic thermostat after update to 2022.12 went wonky, displays C should be F

### ISSUE THREAD

**Issue by ssirkakriss** [home-assistant/frontend#14611]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I employ several Generic thermostat’s in Home assistant. After update 2022.12 all display cards now seem to be converting the values to C, when it should be F.

![heatcard](https://user-images.githubusercontent.com/32778627/206321184-182f7d99-e210-4ba1-bd9c-6fb375c44d92.PNG)

The actual sensor’s by there self’s still report and display there value as F,
![heatcard2](https://user-images.githubusercontent.com/32778627/206321362-e8f03882-fda2-4fa6-8b62-0b020493a10b.PNG)

I have HA General settings set to Fahrenheit.

My Generic thermostat yaml:
```
climate:
# --house heat
  - platform: generic_thermostat
    name: House heat
    unique_id: househeat1234
    heater: switch.thermostat_main_2
    target_sensor: sensor.thermostat_main_ds18b20_temperature
    min_temp: 50
    max_temp: 79
    ac_mode: False
    target_temp: 70
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 45
    keep_alive:
      minutes: 3
    #initial_operation_mode: "auto"
    initial_hvac_mode: "heat"
    away_temp: 63
    precision: 0.1
```
Bug or misconfiguration ?

### Describe the behavior you expected

The card to display the correct temperature conversion.  

### Steps to reproduce the issue

Display thermostat card on 2022.12

### What version of Home Assistant Core has the issue?

core-2022.12

### What was the last working version of Home Assistant Core?

core-2022.11

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.99 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Winsows 10
