### ISSUE TITLE
UI showing wrong color for lock state

### ISSUE THREAD

**Issue by lymanepp** [home-assistant/frontend#14615]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

2022.12.1 release changed lock state image color. Previously it had color when unlocked, but now it has color when locked. This image shows what it looks like when locked with 2022.12.1.

![image](https://user-images.githubusercontent.com/4195527/206332211-c07494f2-475b-4787-8417-67192221e964.png)

### Describe the behavior you expected

2022.11 and previous show color when a lock is unlocked. That is consistent with how other entities display color.

### Steps to reproduce the issue

1. I'm using a picture elements card
2. Add a lock to the the card
3. Lock and unlock the lock to view how color changes\

### What version of Home Assistant Core has the issue?

2022.12.1

### What was the last working version of Home Assistant Core?

2022.11.2

### In which browser are you experiencing the issue with?

Firefox 107.0.1

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
state: locked

Attributes

friendly_name: Front Door Lock
supported_features: 0
```

### Problem-relevant frontend configuration

```yaml
type: picture-elements
image: https://www.xxxxxxxx.com/assets/img/floorplan.jpg
elements:
  - type: state-icon
    entity: lock.front_door_lock
    style:
      top: 66.5%
      left: 70%
```
