### ISSUE TITLE
Casting energy card brakes after update to 2022.12

### ISSUE THREAD

**Issue by shrike8t** [home-assistant/frontend#14657]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,

The update brakes the Energy usage graph card when casting to a google nest hub 2 / nvidia shield.
The grid shows but  the bars are no bars...

Reverting back to 2022.11.5 solves the problem.

Regards,

Bart Janssens

### Describe the behavior you expected

 nvt

### Steps to reproduce the issue

1.  casting to google nest hub 2 / nvidia shield 
2. 
3.
...

### What version of Home Assistant Core has the issue?

2022.12

### What was the last working version of Home Assistant Core?

2022.11.5

### Which operating system are you using to run this browser?

google cast

### State of relevant entities

```txt
nvt
```

### Problem-relevant frontend configuration

```yaml
views:
  - theme: Backend-selected
    title: Home
    type: panel
    badges: []
    cards:
      - square: false
        columns: 1
        type: grid
        cards:
          - square: false
            columns: 1
            type: grid
            cards:
              - type: energy-usage-graph
          - type: custom:power-distribution-card
            title: ''
            entities:
              - decimals: 0
                display_abs: true
                name: solar
                invert_value: false
                unit_of_display: W
                icon: mdi:solar-power
                producer: true
                entity: sensor.solar_panel_production
                preset: solar
              - decimals: 0
                display_abs: true
                name: home
                invert_value: true
                unit_of_display: W
                consumer: true
                icon: mdi:home-assistant
                entity: sensor.solar_house_consumption
                preset: home
              - decimals: 0
                display_abs: true
                name: grid
                invert_value: true
                unit_of_display: W
                icon: mdi:transmission-tower
                entity: sensor.solaredge_m1_ac_power_a
                preset: grid
              - decimals: 0
                display_abs: true
                name: battery
                invert_value: true
                unit_of_display: W
                consumer: true
                icon: mdi:battery-outline
                producer: true
                entity: sensor.solaredge_b1_dc_power
                preset: battery
            center:
              type: bars
              content:
                - preset: autarky
                  name: autarky
                - preset: ratio
                  name: ratio
            animation: flash
```

### Javascript errors shown in your browser console/inspector

```txt
nvt
```

### Additional information

nvt
