### ISSUE TITLE
Tile card in entities card not rendering

### ISSUE THREAD

**Issue by CFenner** [home-assistant/frontend#14686]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding the new tile card into an entity card HA is not able to render it. This worked with the mushroom card as one can see in the screenshots. 
Is this intended r a bug? 

![94DF4884-C9C4-419A-9DF7-2601B0B25D26](https://user-images.githubusercontent.com/9592452/206851503-328bb232-a052-4d41-ae98-fd5897583e5f.png)

### Describe the behavior you expected

Tile should display as before with the mushroom card. 

### Steps to reproduce the issue

Use the yaml posted below. 

### What version of Home Assistant Core has the issue?

2022-12

### Problem-relevant frontend configuration

```yaml
type: entities
title: Garten
entities:
  - type: custom:mushroom-chips-card
    chips:
      - type: entity
        entity: sensor.netatmo_garten_temperature
        use_entity_picture: false
      - type: entity
        entity: sensor.netatmo_garten_humidity
        use_entity_picture: false
      - type: entity
        entity: sensor.vicare_outside_temperature
  - type: custom:mushroom-light-card
    entity: light.paulmann_licht_500_45_c2499a07_level_on_off
    name: Gartenbeleuchtung
    use_light_color: false
    show_color_temp_control: false
    show_color_control: false
    show_brightness_control: true
  - type: custom:mushroom-entity-card
    entity: binary_sensor.aqara_garage_opening
    name: Garage
  - type: custom:mushroom-entity-card
    entity: binary_sensor.aqara_kellertur_opening
    name: Kellertür
  - type: custom:mushroom-entity-card
    entity: binary_sensor.aqara_haustur_opening
    name: Haustür
  - type: tile
    entity: binary_sensor.aqara_garage_opening
    name: Garage
```
