### ISSUE TITLE
Automations Visual- and YAML editor not showing the same information

### ISSUE THREAD

**Issue by Diskoteket** [home-assistant/frontend#14695]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I write an automation using the Visual Editor and select the **device trigger**, **a phone**, **phone leaves a zone** and select the zones they do not reflect as selected in the Visual editor, but are there in the yaml editor of the same automation.

### Describe the behavior you expected

For the Visual editor to show the selected zones that the yaml editor does.

### Steps to reproduce the issue

1. Create a new automation
2. Select the **Device trigger**
3. Choose a **phone device**
4. Choose **phone leaves a zone**
5. Save the automation
6. Stop editing the automation
7. Start editing the automation again
8. Look at the Visual editor and discover that no zone is selected
9. Toggle the YAML editor and discover that a zone is actually selected.

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.1

### In which browser are you experiencing the issue with?

Mozilla Firefox 105.0, Chromium Version 105.0.5195.125

### Which operating system are you using to run this browser?

Arch Linux

### What the Visual editor displays
![Screenshot from 2022-12-10 21-03-45](https://user-images.githubusercontent.com/69105072/206873526-eae5ec2b-b215-4e4d-b87e-a670318ab9b7.png)

### What the YAML editor displays
``` yaml
description: New Automation
mode: single
trigger:
  - platform: device
    device_id: some-id-123123123
    domain: device_tracker
    entity_id: device_tracker.my_phone
    type: leaves
    zone: zone.home
  - platform: device
    device_id: some-id-123123123
    domain: device_tracker
    entity_id: device_tracker.wifes_phone
    type: leaves
    zone: zone.home
condition:
  - condition: not
    conditions:
      - condition: zone
        entity_id: device_tracker.wifes_phone
        zone: zone.home
      - condition: zone
        entity_id: device_tracker.wifes_phone
        zone: zone.home
action: []

```
