### ISSUE TITLE
Picture elements: element's position (top/left) if set in "%" is processed in a bad way

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14704]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this card:
```
  - type: picture-elements
    elements:
      - type: icon
        style:
          top: 50%
          left: 50%
        icon: mdi:car
    image: /local/images/test/blue.jpg
```
![image](https://user-images.githubusercontent.com/71872483/206934075-4168b310-6e35-44ed-bebe-e8b3a87561a2.png)

So far it is OK.

If the card's height is changed - then the element's position is calculated with respect to the INITIAL height, not to the actual one.
Means - the element may be NOT displayed at all since it placed outside the card's boundary:
```
  - type: picture-elements
    elements:
      - type: icon
        style:
          top: 50%
          left: 50%
        icon: mdi:car
    image: /local/images/test/blue.jpg
    card_mod:
      style: |
        ha-card {
          height: 100px !important;
        }
```
![image](https://user-images.githubusercontent.com/71872483/206934367-1ce0f2a1-4af6-4cb6-b780-6b275806a3ce.png)

Element's position must be calculated based on the CURRENT size.

### Describe the behavior you expected

Element's position is calculated based on the CURRENT size.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2022.12.2

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.99 

### Which operating system are you using to run this browser?

Win10x64
