### ISSUE TITLE
Picture element card not respecting style active colors for icon elements

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#14730]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The picture elements card no longer respects the `style:` icon active color. 

### Describe the behavior you expected

Icon active colors to be styled.

### Steps to reproduce the issue

1. See example YAML that does not work below.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.12.3

### What was the last working version of Home Assistant Core?

2022.11.5

### In which browser are you experiencing the issue with?

Firefox 107.0.1, Chrome 108.0.5359.99, Edge 108.0.1462.46

### Which operating system are you using to run this browser?

Windows 10 build 22H2

### Problem-relevant frontend configuration

```yaml
### Worked before 2022.12.1

  - type: state-icon
    state_color: true
    entity: input_boolean.hw_boost
    style:
      top: 35%
      left: 40%
      '--paper-item-icon-active-color': '#0da035'
      '--paper-item-icon-color': '#e45e65'
  - type: state-icon
    icon: mdi:air-filter
    state_color: true
    entity: switch.hot_water
    style:
      top: 58%
      left: 85%
      '--paper-item-icon-active-color': '#0da035'
      '--paper-item-icon-color': '#e45e65'

### Tried this without success:

  - type: state-icon
    state_color: true
    entity: input_boolean.hw_boost
    style:
      top: 35%
      left: 40%
      '--state-input-boolean-color': '#0da035'
      '--paper-item-icon-color': '#e45e65'
  - type: state-icon
    icon: mdi:air-filter
    state_color: true
    entity: switch.hot_water
    style:
      top: 58%
      left: 85%
      '--state-switch-color': '#0da035'
      '--paper-item-icon-color': '#e45e65'
```
