### ISSUE TITLE
Tile Card in grid card dead zoon and ability to create duplicate features

### ISSUE THREAD

**Issue by laithalsunni** [home-assistant/frontend#14748]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There is a bug where if you put two tile cards in a grid card the active zoon does not go all the way down when the card is extended in its height. moreover, for some reason, you can add the same feature more than one time on the same card.

Example
video https://youtu.be/uvItdJbWbyw

```
square: true
columns: 3
type: grid
cards:
  - type: tile
    entity: light.neon_flex
  - type: tile
    entity: light.display_tv
    features:
      - type: light-brightness
  - type: tile
    entity: light.display_tv
    features:
      - type: light-brightness
      - type: light-brightness
      - type: light-brightness
```

### Describe the behavior you expected

non of the above

### Steps to reproduce the issue

1. create a grid card
2. add a tile

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.4
