### ISSUE TITLE
History should honor `binary_sensor` device class for human readable states

### ISSUE THREAD

**Issue by felipecrs** [home-assistant/frontend#14846]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Every binary sensor shows states `on` of  `off` in the history.

![image](https://user-images.githubusercontent.com/29582865/208775912-23a1cc8d-2b78-4a0f-95ad-ab4cb7cb5fe9.png)

### Describe the behavior you expected

They should, however, show their states according to their device class. For example, `network_status` ones should show `connected`/`disconnected`.

### Steps to reproduce the issue

Pretty much self-explanatory.

### What version of Home Assistant Core has the issue?

2022.12.4

**Comment by ildar170975** [comment]
Confirm this with every `device_class`.

![image](https://user-images.githubusercontent.com/71872483/208841447-bbbd3a88-151c-423d-8224-394ff06eb5e8.png)

**Comment by felipecrs** [comment]
Weird. In your print, garage door shows as On/Off too. In my HA it shows as Open/Closed.

![Screenshot_20221221-090718_Home Assistant.jpg](https://user-images.githubusercontent.com/29582865/208901780-11b44526-8d56-4197-b2ec-0508ff9428f5.jpg)

**Comment by ildar170975** [comment]
In a `history-graph`, it also depends on how many entities are in the card:
```
type: vertical-stack
cards:
  - type: history-graph
    entities:
      - binary_sensor.iiyama_wifi_ping_availability_status
      - binary_sensor.rb260gs_0_ping_availability_status
  - type: history-graph
    entities:
      - binary_sensor.iiyama_wifi_ping_availability_status
  - type: history-graph
    entities:
      - binary_sensor.rb260gs_0_ping_availability_status
```
![image](https://user-images.githubusercontent.com/71872483/208912448-1f56ee26-0d25-4441-9046-83260033a28d.png)

and this is strange.
