### ISSUE TITLE
Unable to add GJ as source for gas in energy dashboard

### ISSUE THREAD

**Issue by rbuffi** [home-assistant/frontend#14857]
### The problem

Home Assistant 2022.12.8
Frontend 20221213.1 - latest

Unable to add GJ sensor as source for gas in energy dashboard see image:

 <img width="413" alt="image" src="https://user-images.githubusercontent.com/23478700/209016185-2fe2d4a8-046d-43c9-82fc-9e8192c73e0e.png">

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.8

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

energy dashboard

**Comment by CMDR-Sloma** [comment]
Seems to be affecting the latest update as well, and not only GJ but kWh unit.

Home Assistant 2023.1.0

**Comment by CMDR-Sloma** [comment]
Latest update 2023.1.1 fixed this problem partially.
I was able to add a gas kWh sensor to the dashboard, but I get this warning in the dashboard config for gas consumption:

```
Unexpected unit of measurement
The following entities do not have the expected units of measurement 'Wh', 'kWh', 'MWh' or 'GJ' for an energy sensor or 'm³' or 'ft³' for a gas sensor:
sensor.gas_meter_kwh (kWh)
```

Here is my sensor config:

```
  - platform: template
    sensors:
      gas_meter_kwh:
        friendly_name: Gas Meter (kWh)
        unique_id: sensor.gas_meter_kwh
        unit_of_measurement: "kWh"
        icon_template: "mdi:fire"
        device_class: gas
        value_template: "{{ states ('counter.gas_counter') | float * 0.11 }}"
```
![image](https://user-images.githubusercontent.com/46288478/211145024-672f627b-8ac9-4f82-8f1d-3d6a062a5931.png)


Lastly, gas consumption isn't added to a total consumption in the dashboard:

![image](https://user-images.githubusercontent.com/46288478/211144970-fd55dfaf-b824-40bb-ab7c-f1d84c6fd90c.png)
