### ISSUE TITLE
Camera streams do not show when more than 6 cameras in one dashboard

### ISSUE THREAD

**Issue by farhadvaid** [home-assistant/frontend#14858]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have 9 hikvision cameras connected to Home Assistant, and a dashboard that uses Picture element cards for each camera on a dashboard. Only 6 load at a time. 

I think this is the same as https://github.com/home-assistant/frontend/issues/6879. I was able to reproduce the solution using duckdns/nginx but would prefer not to expose home assistant outside of my network.

### Describe the behavior you expected

All picture elements should load without needing to expose home assistant via duckdns/nginx

### Steps to reproduce the issue

1. add more than 6 unique cameras
2. create picture elements to view the cameras

### What version of Home Assistant Core has the issue?

2022.12.7

### In which browser are you experiencing the issue with?

Chrome Version 108.0.5359.124 (Official Build) (x86_64); wallpanel

### Which operating system are you using to run this browser?

macOS monterey 12.5.1, android 12

### Problem-relevant frontend configuration

```yaml
- platform: generic
  still_image_url: <ip address>/ISAPI/Streaming/channels/1/picture
  name: <camera name>
  username: <user>
  password: <pass>
  authentication: digest
```

### Additional information

I see https://github.com/home-assistant/frontend/issues/6879 was closed so not sure if there is a solution. Any guidance would be extremely appreciated on how to achieve viewing all the cameras without exposing HA outside of my network.
