### ISSUE TITLE
Unable to call the input_select.select_option service from a button (next case)

### ISSUE THREAD

**Issue by Krzysztonek** [home-assistant/frontend#14876]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I need to change the `input_select.program_ogrzewania` state by clicking a dedicated button. Similar to the already reported issue #8026, it is impossible to change the ` input_select.select_option ` state from a dedicated button.
Here are my buttons:
![image](https://user-images.githubusercontent.com/87784133/209329281-6a291b66-fbdf-4d08-a0a0-ebbb0d8977cc.png)
They change automatically, depending on the flow from NR. However, sometimes I need to choose the needed option manually.
I set `entity: input_select.program_ogrzewania` for each of them accordingly.

Here is my code for `dzienny` option (The remaining buttons have been coded in the same way as per the expected option):
```
type: custom:button-card
entity: input_select.program_ogrzewania
name: dzienny
icon: mdi:sun-thermometer

tap_action:
  action: call-service
  service: input_select.select_option
  service_data:
    option: dzienny
    entity_id: input_select.program_ogrzewania
```
I see no errors in the log file, so it seems the code is OK, however, it does NOT work as expected.
My `input_select.program_ogrzewania` helper looks as follows:
![image](https://user-images.githubusercontent.com/87784133/209328075-4d7d6100-b2d8-4125-bbf6-da42cd8ceed9.png)

### Describe the behavior you expected

When clicking the button associated with the `input_select.program_ogrzewania`, the option from this button should be checked. 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12.8

### In which browser are you experiencing the issue with?

Firefox 108.0.1.

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
This works as expected for me in a button card:

```
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: input_select.select_option
  service_data:
    option: foo
    entity_id: input_select.test_select
```

I notice you have a custom card, can you check if your service call works with a regular button, and if so maybe check if it is an issue with the custom card, and not the frontend. 

Also that other issue you linked to was closed as ultimately being user error, so I don't think that is really evidence of a problem.
