### ISSUE TITLE
Automation/actions/change preset/preset_mode not displayed

### ISSUE THREAD

**Issue by patriiiiiiiiiick** [home-assistant/frontend#14893]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Considering the companion app version 2022.11.0-full and the following code:

```
alias: Resume heating when J's door is closed
description: ""
trigger:
  - type: not_opened
    platform: device
    device_id: ...
    entity_id: binary_sensor.j_s_door_door
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition: []
action:
  - device_id: ...
    domain: climate
    entity_id: climate.j_s_radiator
    type: set_preset_mode
    preset_mode: Used
mode: single
```
The preset is not displayed in the UI:

![Screenshot_20221225-224500](https://user-images.githubusercontent.com/5151122/209482870-9b26e683-cfb5-45b1-bf9f-c26add7b049e.png)

There is no data loss in case it is then saved from the UI editor.

### Describe the behavior you expected

Preset mode is displayed.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12.8

### In which browser are you experiencing the issue with?

Companion app and brave

### Which operating system are you using to run this browser?

Android 13
