### ISSUE TITLE
Bug: Duration selector not updating 'days' attribute

### ISSUE THREAD

**Issue by philippwaller** [home-assistant/frontend#14906]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The duration selector with the "enable_day" option set, is not working as expected. The "days" field is not updated or set in the underlying YAML.

![duration_selector_issue](https://user-images.githubusercontent.com/1090452/209849839-9f09b6e4-b86a-43c9-8b15-1fc9bdf9b1e4.gif)

Sample Blueprint to test
```
blueprint:
  name: Check if mobile app is running
  description: >-
    This blueprint will update the display status based on the
    illuminance of a sensor.
  domain: automation
  input:
    device:
      name: Mobile Device
      description: The mobile device to check.
      selector:
        device:
          integration: mobile_app
    unexpected_duration_without_update:
      name: Unexpected duration without update
      default: 0:18:00:00
      description: >-
        If this time period is exceeded, Home Assistant sends a silent 
        "request_location_update" notification to the device to initiate 
        an update cycle. This only works if the Home Assistant app is running 
        in the fore- or background and the location can be determined within 
        the time period specified by the device's operating system.
      selector:
        duration:
          enable_day: true
    critical_duration_without_update:
      name: Critical duration without update
      description: >-
        If this time period is exceeded, Home Assistant sends a regular push 
        notification to request the user to restart the Home Assistant app.
      selector:
        duration:
          enable_day: true

trigger:
  - platform: state
    entity_id: []

condition: [ ]

action: []
mode: restart

```

### Describe the behavior you expected

The "days" field should update the underlying YAML.

### Steps to reproduce the issue

see problem description

### What version of Home Assistant Core has the issue?

2022.12.8

### In which browser are you experiencing the issue with?

Google Chrome Version 108.0.5359.124

### Which operating system are you using to run this browser?

macOS 13.1
