### ISSUE TITLE
Picture Elements card does not respect title setting for badges

### ISSUE THREAD

**Issue by brodkin** [home-assistant/frontend#14908]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The docs state that a title attribute can be specified for a badge element. Setting a title on an element is ignored and the friendly name is displayed below the badge instead. Setting title to null or a string has the same result.

### Describe the behavior you expected

The title setting is honored and either displays the string provided or shows nothing when null.

### Steps to reproduce the issue

1. Create a picture element card.
2. Add element with type of badge.
3. Set title to null or a string.
4. Title is not displayed.

### What version of Home Assistant Core has the issue?

2022.12.8

### In which browser are you experiencing the issue with?

Safari 16.2 (18614.3.7.1.5)

### Which operating system are you using to run this browser?

macOS 13.1 (22C65)

### Problem-relevant frontend configuration

```yaml
type: picture-elements
elements:
  - type: state-badge
    entity: sensor.kitchen_temperature
    title: null
    style:
      top: 52%
      left: 82%
  - type: state-badge
    entity: sensor.bedroom_temperature_3
    title: "Something Swanky"
    style:
      top: 52%
      left: 15%
image: /local/floorplan.png
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_
