### ISSUE TITLE
Alias not available for input_boolean

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/frontend#14923]
### The problem

It looks like the alias option is not available for input_* entities, for example: when I open any input_boolean and go to Settings -> Advanced settings, there is no alias field available.
This feels weird, because when you expose entities to Google Assistant it allows you to set aliases for input_booleans.

    input_boolean.bedtime:
      expose: true
      aliases:
        - Bedtijd
        - Bedtime
      room: Slaapkamer

### What version of Home Assistant Core has the issue?

core-2023.1.0b1

### What was the last working version of Home Assistant Core?

never

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
input_boolean.bedtime:
      expose: true
      aliases:
        - Bedtijd
        - Bedtime
      room: Slaapkamer
```
