### ISSUE TITLE
Blank value for script fields is passed if default value is selected or slider is used in automation UI

### ISSUE THREAD

**Issue by Forceu** [home-assistant/frontend#14930]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have written a script to display notifications, which has three field values to be filled in by the user. Two of them are numbers that have a default value set. If I do not change the value or use a slider, a blank value is used instead of the default or selected value. If I manually enter a value in the box the correct value is passed.

I used the following script:

```
send_notification:
  alias: "Send Notification"
  icon: "mdi:bell"
  description: "Sends a notification"
  fields:
    text:
      name: "Text"
      description: "Message to be sent"
      required: true
      selector:
        text:
          autocomplete: "off"
    importance:
      name: "Importance"
      description: "0 small notification, 1 regular silent, 2 regular, 3 warning with vibration" 
      default: 1
      required: true
      selector:
        number:
          min: 0
          max: 3
          mode: box
    id:
      name: "ID"
      description: "0 if notification shall not replace an old one, with any other number the notification replaces the old notification with the same ID"
      default: 0
      required: true
      selector:
        number:
          min: 0
          max: 65000
          mode: box
  mode: single
  sequence:
    - service: mqtt.publish
      data_template:
        topic: 'homelab/notification'
        payload: '{"text":"{{ text }}","importance":{{ importance }},"NotificationId":{{ id }}}'
```

Output received: 

`{"text":"Test","importance":,"NotificationId":}`

Output expected: 

`{"text":"Test","importance":1,"NotificationId":0}`

### Describe the behavior you expected

The (displayed) default value should be used

### Steps to reproduce the issue

1. Create a script with a number field and a default value
2. Create new automation in UI
3. Add action to execute script above
4. Either run action or save and trigger script. Instead of a default number a blank value was passed

### What version of Home Assistant Core has the issue?

2022.12.8 / Frontend 20221213.1

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.124 / Firefox 

### Which operating system are you using to run this browser?

Ubuntu 20.04

### Javascript errors shown in your browser console/inspector

```txt
The specified value "NaN" cannot be parsed, or is out of range. k @ styles.ts:372 (I don't think this is related)
```
