### ISSUE TITLE
The "color icon based on state" is not working on helper schedule...

### ISSUE THREAD

**Issue by jschinke1067** [home-assistant/frontend#14941]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If an item is active, the icon show's an active state. This work's great everywhere except on Helper Schedules. If an schedule get's active (on) the state still show's inactive state visually...
-> as you can see in the pic below (Weekend)

<img width="446" alt="Bildschirm_foto 2022-12-31 um 17 40 57" src="https://user-images.githubusercontent.com/98277176/210150225-1ade1141-c01c-4ff5-82e1-69703859fb21.png">

### Describe the behavior you expected

If a binary sensor is on, it should also be visual activ in the GUI...
Only the helper "Scheduler" does not behave like that... :-)

### Steps to reproduce the issue

1. creat a helper "Scheduler"
2.brig it to active
3. it will show as on but visually it is not active in the GUI...
...

### What version of Home Assistant Core has the issue?

2022.12.8

### What was the last working version of Home Assistant Core?

2022.12.8

### In which browser are you experiencing the issue with?

Google Chrome latest, Safari latest

### Which operating system are you using to run this browser?

macOS Ventura 13.1

### State of relevant entities

```txt
State: 
on

Attributes: 
editable: true
next_event: 2023-01-01T00:00:00+01:00
icon: mdi:balloon
friendly_name: Weekend
```

### Problem-relevant frontend configuration

```yaml
Standard Glance Gard:

show_name: true
show_icon: true
show_state: true
type: glance
entities:
  - entity: input_boolean.wecker_arun_aktiv
    name: A Wecker
  - entity: calendar.katadyn
    name: A Frei?
  - entity: input_boolean.jens_ferien
    name: J Ferien
  - entity: schedule.weekend
  - entity: input_boolean.ft_we_aktiv
  - entity: calendar.barizzi
    name: M Ferien / Kurs
  - entity: calendar.schulferien_winterthur
    name: M Schulferien
  - entity: input_boolean.jens_krank
  - entity: input_boolean.michi_krank
  - entity: input_boolean.arun_krank
columns: 4
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

This is only a minor problem, but it would be great if it could be fixed...
Thank you very much for all your great work!
