### ISSUE TITLE
Condition not shown correctly in UI of automatisation editor

### ISSUE THREAD

**Issue by Bascht74** [home-assistant/frontend#14958]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you have the following condition in an automatisation: 

```
condition:
  - condition: numeric_state
    entity_id: sensor.ofen_temperature
    above: sensor.1og_wohnraum_gruppe_1og_wohnraum_int0000001_actual_temperature
```

it is not shown right in the UI: 
![image](https://user-images.githubusercontent.com/66269310/210243707-265e537a-a7f9-42f2-bc16-e8a7eab9e4a4.png)

The above section is empty...

### Describe the behavior you expected

that the sensor is shown in the above field.

### Steps to reproduce the issue

1. Have an automatisation with that condition 
2. Open the automatisation in the UI
3. value is missing in the UI, the rendered text seems OK.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.0b4

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

Google Chrome Version 108.0.5359.124

### Which operating system are you using to run this browser?

macos 13.1 (22C65) (but on Windows also)
