### ISSUE TITLE
automatisation graph vanishes after click on "step details" in a wait action

### ISSUE THREAD

**Issue by Bascht74** [home-assistant/frontend#14957]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an automatisation with a wait action:

```
wait_for_trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Thermometer_EG_Wohnzimmer
    id: Mqtt_logging
timeout:
  hours: 0
  minutes: 7
  seconds: 0
  milliseconds: 0
alias: Warte, dass eine MQTT-Botschaft von Zigbee2Mqtt gesendet wird
```

If I open the trace and click on the wait action the graph disappears

![image](https://user-images.githubusercontent.com/66269310/210242518-569fd7de-84cd-4edf-8ad7-4909ac254606.png)

If you click on trace timeline it comes back again

### Describe the behavior you expected

That the graph stays even if clicking on the wait_for_trigger action and "step" details is selected. 
Only there the graph vanishes and come back, if you click on a different tab.

### Steps to reproduce the issue

1. Add a wait_for_trigger action to an automatisation
2. Run automatisation and open trace
3. Klick on the wait_for_trigger action and select "step details" --> Graph vanishes
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.0b4

### What was the last working version of Home Assistant Core?

it worked before, but I didn't use traces that often

### In which browser are you experiencing the issue with?

Google Chrome Version 108.0.5359.124

### Which operating system are you using to run this browser?

macos 13.1 (22C65) (but on Windows also)
