### ISSUE TITLE
Dashboard Editor: Wrong Settings Shown for Buttons in Grid Card in Conditional Card in Grid Card

### ISSUE THREAD

**Issue by The00Dustin** [home-assistant/frontend#14988]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to edit buttons in a grid that is behind a conditional card that is in a grid where the action is `Call Service` and the service is `Remote: Send Command` I see the same thing in the `Command` field of the `Tap Action` for all buttons (1-12 in the example I am working off of to fill out this report).  This is in spite of the correct information being stored in the actual configuration.

### Describe the behavior you expected

The command actually assigned to the action of the selected button should be displayed instead of the command assigned to button 1.

### Steps to reproduce the issue

Some of these steps may be extraneous, but I reproduced as follows:
1. Create a custom dashboard
2. Add a grid card with 1 column
3. Add a conditional card with a condition that will make the card display
4. Add a grid card to the conditional card with 3 columns
5. Add a button to the grid card with a `media_player` entity
6. Set the tap action to `Call Service`
7. Set the service to `Remote: Send Command`
8. Enter `1` as the command
9. Repeat steps 5-7 to add a second button
10. Enter `2` as the command
11. Save the configuration
15. Edit the grid card again
16. Select `CARD` under the conditional card
17. Observe `1` in the command field
18. Select the second button
19. Observe `1` in the command field
20. `SHOW CODE EDITOR` for the button
21. Observe `command: 2` in the code

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.9 Supervisor 2022.12.1 Operating System 9.4 Frontend 20221213.1 - latest

### In which browser are you experiencing the issue with?

Safari 16.2 (17614.3.7.1.7, 17614) & iOS app 2022.10.1

### Which operating system are you using to run this browser?

macOS Monterrey 12.6.2 & iOS 15.7.1

### Problem-relevant frontend configuration

```yaml
square: true
columns: 1
type: grid
cards:
  - type: conditional
    conditions:
      - entity: switch.tp_link_led
        state: 'off'
    card:
      type: grid
      cards:
        - show_name: true
          show_icon: true
          type: button
          tap_action:
            action: call-service
            service: remote.send_command
            data:
              command: 1
            target: {}
          entity: media_player.living_room
        - show_name: true
          show_icon: true
          type: button
          tap_action:
            action: call-service
            service: remote.send_command
            data:
              command: 2
            target: {}
          entity: media_player.living_room
```

### Additional information

This behavior can also be reproduced with the `Hold Action` when it is configured in a similar manner.

This behavior has been consistent for multiple versions, but I only just made time to report it.

The code provided in the "Problem-relevant frontend configuration" is from a grid card that was created only to reproduce the issue and doesn't reflect the complexity of the the grid cards in which I originally came across the issue.

**Comment by karwosts** [comment]
Do you observe this with any other type of services, maybe something more common? Or only with remote?

I was going to see if I could reproduce this, but I don't have any "remote" in my environment. I tried light.turn_on service instead and the service data was correctly rendered when flipping between buttons 1 and 2.

**Comment by The00Dustin** [comment]
Actually, I was able to reproduce this with light.turn_on using FireFox on Windows.  I mention FireFox on Windows because it completely eliminates Apple from the equation.  Here is the config that I used to reproduce the behavior this time:

```
square: true
columns: 1
type: grid
cards:
  - type: conditional
    conditions:
      - entity: media_player.basement
        state: 'off'
    card:
      type: grid
      cards:
        - show_name: true
          show_icon: true
          type: button
          tap_action:
            action: call-service
            service: light.turn_on
            data:
              rgbw_color: 1
            target: {}
          entity: switch.tp_link
        - show_name: true
          show_icon: true
          type: button
          tap_action:
            action: call-service
            service: light.turn_on
            data:
              rgbw_color: 2
            target: {}
          entity: switch.tp_link
```

I should point out that I'm not even setting a target to reproduce this (even though it does occur with an entity selected), so not having any "remote" in your environment shouldn't prevent reproduction.  Regardless, the `rbgw_color` field displays the same way as the `command` field, that's why I chose to populate it for the two cards, and sure enough, when I switch to the second card and scroll down, it still shows "1" instead of "2" in that field.

**Comment by karwosts** [comment]
Ah, I did reproduce your error this time in my dev environment when I copied your latest code sample (and replaced with my own entities).

**Comment by karwosts** [comment]
Just taking some notes:

Removing this if-statement here does seem to fix the problem for me, but that looks like a pretty heavy hammer, and I'm sure there's a better way to fix that doesn't involve destroying and recreating the editor every time the card switches. 

https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/editor/hui-element-editor.ts#L315

**Comment by karwosts** [comment]
Ultimately I think this is a problem with src/components/ha-yaml-editor.ts

When toggling between the different cards, the new service data for the selected card is pushed down to each of the selectors of a card. The ha-selector-object selector contains a ha-yaml-editor, such that the value of ha-object-selector is connected to the defaultValue of the yaml-editor.

ha-yaml-editor has a defaultValue and a value, and it only copies defaultValue to value on first updated. So any time after that, if the defaultValue passed to ha-yaml-editor changes (like when a new card is selected), it gets a new defaultValue, but its value remains unchanged, so you always see the same yaml for all the cards. 

Tried playing with a few ways to fix this, like by setting value to defaultValue anytime defaultValue changes and if defaultValue != value, but I'm not sure if that's the "correct" way to do this with lit.

**Comment by The00Dustin** [comment]
> Tried playing with a few ways to fix this, like by setting value to defaultValue anytime defaultValue changes and if defaultValue != value, but I'm not sure if that's the "correct" way to do this with lit.

Without seeing the code, and without being an experience developer, this does sound like the correct way to fix this to me.  That feeling is specifically based on the assumption that the piece of code you are referring to only runs when the page loads, because you want to set the value at that point.  If the same code could run in other scenarios such as while the page is idle or during save, which would wipe out a user's modification, then it would obviously not be the right thing to do.

**Comment by The00Dustin** [comment]
Actually, I'm not sure why the problem would be at the value level of a yaml editor and only affect one type of field under services.  For instance, consider this code for a different type of field where data is entered but the same issue doesn't occur:

```
type: grid
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: counter.configure
      data:
        minimum: 1
      target: {}
    entity: switch.tp_link
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: counter.configure
      data:
        minimum: 2
      target: {}
    entity: switch.tp_link
```

Maybe I'm reading too much into the name "ha-yaml-editor.ts" but both YAML have a named value under `data:` and so does this one with yet another field type where it isn't reproducible:

```
type: grid
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: cover.set_cover_position
      data:
        position: 1
      target: {}
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: cover.set_cover_position
      data:
        position: 2
      target: {}
```

Notice the complete lack of an entity in the second example here.  I realized that might simplify things even further.  Now see this example:

```
type: grid
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: remote.send_command
      data:
        device: '1'
        command: 1
      target: {}
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: remote.send_command
      data:
        command: 2
        device: '2'
      target: {}
```

If you follow the steps I showed you for reproduction, you will notice that `device` updates when you switch cards even though `command` doesn't, again, based on the type of field.
