### ISSUE TITLE
aspect ratio in picture-entity not working as expected

### ISSUE THREAD

**Issue by ZhuDaHai** [home-assistant/frontend#14984]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

setting aspect_ratio in the picture-entity card crops the image rather than actually changing its aspect ratio.
This was reported in issue #9986 which became stale and locked due to inactivity.
I would still like to have this issue resolved, if possible.

### Describe the behavior you expected

Changing the aspect ratio of an image in the picture-entity card should stretch or squish the image in the required direction to make it comply with the set aspect_ratio setting. At this time, it actually crops or pads the image to fake the set aspect ratio

### Steps to reproduce the issue

1. set aspect_ratio in the picture-entity card to something different than the actual aspect ratio of the camera_image
2. watch the UI just crop or pad the image rather than changing (stretch/squeeze) the image to the set ratio
3. pull hair out
...

### What version of Home Assistant Core has the issue?

HA 2022.12.9 / Super: 2022.12.1 / OS 9.4 / Frontend 202211213.1

### In which browser are you experiencing the issue with?

Version 108.0.5359.125 (Official Build) (64-bit) / Brave Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10.0.19045 Build 19045

### Problem-relevant frontend configuration

```yaml
cards:
          - type: picture-entity
            entity: camera.op_frontdoor
            camera_image: op_frontdoor
            name: Front Door
            aspect_ratio: "16:9"
```
