### ISSUE TITLE
Error rendering graph in Automation Trace

### ISSUE THREAD

**Issue by m0m4x** [home-assistant/frontend#15025]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

from /config/automation/trace/auto_luci_cucina
i get
"Error rendering graph. Please download trace and share with the developers."

Hello,
i've update my automations with "choose" actions group.
https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions
The automation works well but can't be rendered in frontend.

automation:
``` yaml
automation:
  - id: auto_luci_cucina
    alias: auto_luci_cucina
    description: ''
    mode: restart
    trigger:
    - platform: state
      entity_id: 
        - group.cucina_pir
        - group.cucina_door
    - platform: state
      entity_id: 
        - group.cucina_pir
        - group.cucina_door
      to: 'off'
      for: "{{states('input_text.cnf_luci_auto_off_time')}}"
    condition:
    action:
      - choose:
          # if ACCENSIONE
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'on' }}"
              # verifica ACCENSIONE LUCI ATTIVO
              - condition: state
                entity_id: input_boolean.cnf_luci_auto_on
                state: 'on'
              # verifica MULTIMEDIA in riproduzione - se in riproduzione non accendi Luce 
              - condition: template
                value_template: "{{ (states('input_boolean.cnf_luci_auto_multimedia_freeze') == 'off') or 
                                    (states('input_boolean.cnf_luci_auto_multimedia_freeze') == 'on' and 
                                     states('group.cucina_multimedia') in ['unknown', 'unavailable', 'standby', 'off', 'idle', 'paused']) }}"
            sequence:
              - service: light.turn_on
                entity_id: light.switch_btccucina03
              - service: input_boolean.turn_on
                target:
                  entity_id: 
                    - input_boolean.cnf_cucina_auto_on
                    - input_boolean.cnf_cucina_presence
          # if SPEGNIMENTO
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'off' and  (as_timestamp(now()) - as_timestamp(trigger.to_state.last_changed|default(0))) > (states('input_number.cnf_luci_auto_off')|float)}}"
              # verifica LUCE AUTOMATICA - Spegni solo se è stata accesa automaticamente
              - condition: state
                entity_id: input_boolean.cnf_cucina_auto_on
                state: 'on'
              # verifica SPEGNIMENTO LUCI ATTIVO
              - condition: state
                entity_id: input_boolean.cnf_luci_auto_off
                state: 'on'
              # verifica PORTE APERTE - Se porta aperta non spengi Luce
              - condition: template
                value_template: "{{ (states('input_boolean.cnf_luci_auto_door_freeze') == 'off') or (states('input_boolean.cnf_luci_auto_door_freeze') == 'on' and states('group.cucina_door') == 'off') }}"
              # verifica MULTIMEDIA in riproduzione - se in riproduzione non spengi Luce 
              - condition: template
                value_template: "{{ (states('input_boolean.cnf_luci_auto_multimedia_freeze') == 'off') or 
                                    (states('input_boolean.cnf_luci_auto_multimedia_freeze') == 'on' and 
                                     states('group.cucina_multimedia') in ['unknown', 'unavailable', 'standby', 'off', 'idle', 'paused']) }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: 
                    - input_boolean.cnf_cucina_auto_on
                    - input_boolean.cnf_cucina_presence
              - service: homeassistant.turn_off
                entity_id: group.cucina_light
```

Uploaded trace. 
[trace automation.auto_luci_cucina 2023-01-07T10_54_27.205767+00_00.json.log](https://github.com/home-assistant/frontend/files/10366076/trace.automation.auto_luci_cucina.2023-01-07T10_54_27.205767%2B00_00.json.log)

Thank you

### Describe the behavior you expected

Graph of actions being rendered correctly.

### Steps to reproduce the issue

1. copy and paste automation
2. execute it
3. refer to trace

### What version of Home Assistant Core has the issue?

2023.1.1

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.125 (Build ufficiale) (a 64 bit)

### Which operating system are you using to run this browser?

Windows 10 Pro

### Javascript errors shown in your browser console/inspector

```txt
no one
```
