### ISSUE TITLE
Select entity in horizontal stack doesn't fit and doesn't alway become a dropdown

### ISSUE THREAD

**Issue by Fonta** [home-assistant/frontend#15041]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding a select entity to an entities card which is in a horizontal stack, the dropdown extend outside of the block.
Also when you use the entity card or tile card, the select doesn't not become a dropdown.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/6190791/211209344-60c32129-fe4d-4200-851d-ead3b95a193a.png">

### Describe the behavior you expected

I would expect the dropdown to fit within the block and I would expect the select entity to become an dropdown also when using it in a entity or tile card and not only in a entities card.

### Steps to reproduce the issue

Edit the dashboard, add a card, chose horizontal stack, add entities card, chose a select entity.
Then on the right side add another random card.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.1

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

MacOS

### State of relevant entities

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/6190791/211209411-d59ba0e9-2a19-4c6b-9caa-e448f702c96d.png">

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: entity
    entity: select.wled_wall_preset # does not become a dropdown
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - entity: select.wled_wall_color_palette # becomes a dropdown but doesn't fit
          - entity: select.wled_wall_preset # becomes a dropdown but doesn't fit
      - type: tile
        entity: select.wled_wall_preset # does not become a dropdown
```

### Javascript errors shown in your browser console/inspector

```txt
None
```
