### ISSUE TITLE
Automation fails to run due to missing custom name element in Logbook Log

### ISSUE THREAD

**Issue by dmascord** [home-assistant/frontend#15076]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an automation linked to a HomeKit Smart Button (stateless), which requires an automation to trigger events.

As you can see in the automation trace, it fails due to a missing name entity in Logbook Log:

![image](https://user-images.githubusercontent.com/1801667/211679223-79c54949-dc9f-490b-ba02-a576fefc64da.png)

Automation config below which exhibits this behaviour:

```
alias: single press auto
description: ""
trigger:
  - platform: device
    device_id: 6d6ccdd3059492649817069e674f718a
    domain: homekit_controller
    type: button1
    subtype: single_press
condition: []
action:
  - service: logbook.log
    data:
      message: single press 20CA
mode: single
```

This can be worked around by adding a name element:

```
alias: single press auto
description: ""
trigger:
  - platform: device
    device_id: 6d6ccdd3059492649817069e674f718a
    domain: homekit_controller
    type: button1
    subtype: single_press
condition: []
action:
  - service: logbook.log
    data:
      message: single press 20CA
      name: single press name
mode: single
```

### Describe the behavior you expected

Expectation is that the automation will run without the optional field name, currently it is failing because it seems that the logic expects the name, but the UI doesn't enforce entering name.

### Steps to reproduce the issue

To replicate the issue
1) create an automation that calls a service Logbook Log, and just enter a message without a custom entity name.
2) Open the trace window on the automation
3) execute the automation manually or via trigger
4) refresh the trace page, and notice an error on the trace output

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.1

### In which browser are you experiencing the issue with?

Brave Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit)
