### ISSUE TITLE
Tile is formatted to large and overlapped by other card

### ISSUE THREAD

**Issue by Jorikay** [home-assistant/frontend#15095]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding tiles in a horizontal-stack, in a vertical-stack, the tiles are formatted to large.
This is adding "white space" under the effective data of the tile.

When adding additional cards, they are overlapping this area.

![2023-01-12 16_07_51-Kiosk2 – Home Assistant](https://user-images.githubusercontent.com/73581843/212103049-e48ef4f1-13e6-44f8-b010-cb5dbaadebbd.png)

### Describe the behavior you expected

to have the tiles scale properly

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.1.2

### In which browser are you experiencing the issue with?

multiple - chrome, firefox and chrome on android

### Which operating system are you using to run this browser?

Windows 11 and Android 6

### Problem-relevant frontend configuration

```yaml
type: horizontal-stack
cards:
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Master Bedroom
            cards:
              - features:
                  - type: light-brightness
                type: tile
                entity: light.masterbedroom_bedlampje_din_zha_group_0x0004
                name: Din
                show_entity_picture: false
              - type: tile
                entity: light.masterbedroom_bedlampje_krul_zha_group_0x0003
                name: Krul
                features:
                  - type: light-brightness
              - type: tile
                entity: light.masterbedroom_spot_zha_group_0x0002
                name: Spot
                features:
                  - type: light-brightness
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: K
            cards:
              - features:
                  - type: light-brightness
                type: tile
                entity: light.lamp_k_slaapkamer_level_light_color_on_off
                name: Spot
          - type: media-control
            entity: media_player.unnamed_room_2
      - type: vertical-stack
        cards:
          - show_state: true
            show_name: true
            camera_view: live
            type: picture-entity
            entity: camera.g4_doorbell_32_high
            camera_image: camera.g4_doorbell_32_high
            name: Voordeur
          - type: custom:simple-thermostat
            entity: climate.woonkamer
            layout:
              step: column
            header: false
            control: true
```

**Comment by LucasHokerberg** [comment]
Same issue here. Although only when using "title: " on the horizontal stack.

**Comment by chasestech** [comment]
I am having a similar issue when using the tile cards in vertical/horizontal stacks, but it only seems to happen if my view type is panel rather than masonry.

#### Panel view with issue
<img width="500" alt="Panel View" src="https://user-images.githubusercontent.com/8998243/228714842-a2e71ce5-d7ce-43c2-a2f0-d517491b9a27.png">

#### Masonry view without issue
<img width="500" alt="Masonry View" src="https://user-images.githubusercontent.com/8998243/228714840-66d9a9bd-4f0c-4241-903c-6c677435cedc.png">

```
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Lights
    alignment: center
  - type: horizontal-stack
    title: Living Room
    cards:
      - type: tile
        entity: light.living_room_lamps
        icon: mdi:lamps
        name: Lamps
      - type: tile
        entity: light.living_room_light_bar_level_light_color_on_off
        name: Light Bar
  - type: tile
    entity: light.living_room_ceiling_fan_light
    icon: mdi:ceiling-fan-light
    name: Ceiling Fan Light
  - type: horizontal-stack
    title: Kitchen
    cards:
      - type: tile
        entity: light.kitchen_ceiling_light
        icon: mdi:light-recessed
        name: Ceiling
      - type: tile
        entity: light.kitchen_island_light
        name: Island
  - type: horizontal-stack
    title: Loft
    cards:
      - type: tile
        entity: light.loft_light_center_on_off
        name: Center
        icon: mdi:light-recessed
      - type: tile
        entity: light.loft_light_bar_level_light_color_on_off
        name: Light Bar
  - type: horizontal-stack
    title: Primary Bedroom
    cards:
      - type: tile
        entity: light.primary_bedroom_lamp_left_level_light_color_on_off
        name: Lamp Left
        icon: mdi:lamp
      - type: tile
        entity: light.primary_bedroom_lamp_right_level_light_color_on_off
        icon: mdi:lamp
        name: Lamp Right
  - type: horizontal-stack
    cards:
      - type: tile
        entity: light.primary_bedroom_ceiling_fan_light
        name: Ceiling Fan Light
  - type: horizontal-stack
    title: Guest Bedroom
    cards:
      - type: tile
        entity: light.guest_bedroom_lamp
        name: Lamp
        icon: mdi:lamp
  - type: horizontal-stack
    title: Exterior
    cards:
      - type: tile
        entity: light.front_lights
        icon: mdi:coach-lamp
        name: Front Lights
      - type: tile
        entity: light.back_porch_light_on_off
        name: Back Porch
        icon: mdi:light-recessed
  - type: horizontal-stack
    title: Garage
    cards:
      - type: tile
        entity: light.garage_lights
        icon: mdi:lightbulb
        name: Garage Lights
```
