### ISSUE TITLE
Secondary info on Entities card not displaying correctly for "None" and "Last updated"

### ISSUE THREAD

**Issue by maximan** [home-assistant/frontend#15092]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Secondary Information for entities in the Entities Card is showing incorectly for "None" and "Last updated".

![image](https://user-images.githubusercontent.com/7470626/212021460-63871dff-f0b1-4535-81f4-efba7ca55f70.png)

The image above shows four entities on the card with each of the four secodary info options enabled. Selecting "None" displays the text "none" instead of hiding secondary info, and "Last updated" shows the text "last-updated" instead of the time the entity was last updated.

Values for "Entity ID" and "Last changed" appear to be working correctly.

### Describe the behavior you expected

- When "None" is selected for Secondary information for an entity on the Entities card, I expect to see no secondary info displayed.
- When "Last updated" is selected for Secondary information for an entity on the Entities card, I expect to see the time elapsed since the entity was alst updated.

### Steps to reproduce the issue

1. Go to a dashboard with an Entities card on it.
2. Edit the dashboard.
3. Edit the Entities card.
4. Select an entity and select "Last updated" in the Secondary information options.

### What version of Home Assistant Core has the issue?

core-2023.1.2

### In which browser are you experiencing the issue with?

Brave (Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit))

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: sensor.esp_plug_07_power
    secondary_info: none
    icon: mdi:heating-coil
    name: FIR Panel Heater
  - entity: sensor.esp_plug_02_power
    secondary_info: entity-id
    icon: mdi:router-network
    name: POE Switch
  - entity: sensor.power_strip_1_socket_5_power
    name: Matt PC
    secondary_info: last-changed
    icon: mdi:desktop-tower
  - entity: sensor.power_strip_1_socket_1_power
    name: Fanless PC
    secondary_info: last-updated
  - entity: sensor.power_strip_1_socket_4_power
    icon: mdi:monitor
    secondary_info: last-changed
    name: Matt PC Monitor
```
