### ISSUE TITLE
Sonos update alarm automation adds a default time if none is given

### ISSUE THREAD

**Issue by anthonyma94** [home-assistant/frontend#15117]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding an automation action using the Sonos update alarm action, a default time is filled in if none is given. For example, if I want to just toggle the alarm, this would be the yaml representation:
```yaml
service: sonos.update_alarm
data:
  alarm_id: 1
  enabled: false
target:
  entity_id: media_player.bedroom
```

After saving and reloading, the automation action will then be changed to this:
```yaml
service: sonos.update_alarm
data:
  alarm_id: 1
  enabled: false
  time: "00:00:00"
target:
  entity_id: media_player.bedroom
```

### Describe the behavior you expected

I expect the time to be disabled when not needed.

### Steps to reproduce the issue

1. Create a new automation
2. Add "Sonos update alarm" as an action
3. Check "Alarm enabled"
4. Save and exit
5. Go back to the automation edit screen
...

### What version of Home Assistant Core has the issue?

2022.12.0
