### ISSUE TITLE
List of entities created in the wrong way when editing an automation

### ISSUE THREAD

**Issue by MathiasThinsz** [home-assistant/frontend#15149]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing an automation that calls a service the entities state and the snapshop entities are added incorrectly in the yaml file. Instead of creating a list like:
```
snapshot_entities:
- climate.ecobee
- light.ceiling_lights
```
the UI editing results in:
`      snapshot_entities: climate.ecobee light.ceiling_lights
`

It is the same problem with **Entities state**

This stops the automation from running since the listing of entities is wrong. The error message when running the automations is:
> Stopped because an error was encountered at January 20, 2023 at 12:45:02 (runtime: 0.03 seconds)
> 
> Entity ID light.mylight1 light.mylight2 is an invalid entity ID for dictionary value @ data['snapshot_entities']

The documentation states the correct YAML formatting under **Creating scenes on the fly**, in the second example:
https://www.home-assistant.io/integrations/scene/#creating-scenes-on-the-fly

https://github.com/home-assistant/core/tree/dev/homeassistant/components/scene

### Describe the behavior you expected

When adding entities the resulting YAML file would be correctly formatted 

### Steps to reproduce the issue

1. Create a new automation
2. Add any trigger, like a specific time
3. Add a new action of type **Call service**
4. Add the service `Scene: Create`
5. Enter a **Scene entity ID** (doesn't matter which)
6. Check the **Snapshop entities** checkbox
7. Enter a entity of your choice, like a light `light.mylight1` and hit enter
8. Enter a second entity of your choice, like a light `light.mylight2` and hit enter
9. Save the automation
10. Change editing mode to **Edit in YAML** using the three dots in the upper right corner

This is the result:
```
alias: Bug report
description: ""
trigger:
  - platform: time
    at: "01:00:00"
condition: []
action:
  - service: scene.create
    data:
      scene_id: thebugscene
      snapshot_entities: light.mylight1 light.mylight2
mode: single
```
but the result should be:
```
alias: Bug report
description: ""
trigger:
  - platform: time
    at: "01:00:00"
condition: []
action:
  - service: scene.create
    data:
      scene_id: thebugscene
      snapshot_entities:
      - light.mylight1
      - light.mylight2
mode: single
```
**NOTE!** Repeat step 6-10 but with the **Entities state** instead. Same issue here.

### What version of Home Assistant Core has the issue?

2023.1.6

### In which browser are you experiencing the issue with?

Google Chrome 109.0.5414.75 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11
