### ISSUE TITLE
Conditional card does work on dashboard in Chrome

### ISSUE THREAD

**Issue by JoostAB** [home-assistant/frontend#15197]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created a conditional card to show some PC information from HASS agent, visible only if the PC is online. The condition works fine in the visual editor, but not on the dashboard, There everything stays visible, even if de condition is false.
I'm using Chrome 109.0.5414.75

For this I use an MQTT sensor defined as:

```
mqtt:
  - sensor:
  - name: "PC Joost status"
    state_topic: "homeassistant/sensor/PC-JOOST/availability"
    unique_id: "pc_joost_status"
```

This sensor works perfectly.
The condition ius defined as follows:

```
type: vertical-stack
cards:
  - type: entities
    title: PC-Joost
    entities:
      - entity: sensor.pc_joost_status
        name: Status
        icon: mdi:power
  - type: conditional
    conditions:
      - entity: sensor.pc_joost_status
        state: online
    card:
      type: vertical-stack
      cards:
        - type: media-control
   ...
```

Posting 'offline' to the MQTT topic `homeassistant/sensor/PC-JOOST/availability` works in the visual editor, but not when the card is on the dashboard. Also refreshing the screen does not hide the cards.

When I try it in the Android companion app or Edge browser everything works fine

### Describe the behavior you expected

I would expect all cards in the conditional card would be hidden if the condition evaluates to 'false'

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core 2023.1.7

### In which browser are you experiencing the issue with?

Chrome 109.0.5414.75

### Which operating system are you using to run this browser?

Windows 11 Pro - 22H2 - 22621.1105
