### ISSUE TITLE
Map card shows path of previous locations without being configured that way (2023.2 beta)

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/frontend#15216]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Map card shows path of previous locations without being configured that way on 2023.2.0b1. This was not the case in 2023.1.7.

### Describe the behavior you expected

No path visible (as was the case up until 2023.1.7)

### Steps to reproduce the issue

Config of map card (note the absence of the [hours_to_show setting](https://www.home-assistant.io/dashboards/map/#hours_to_show)):
```yaml
      - type: map
        entities:
          - person.bob
          - !secret person_mw
          - !secret person_mini
          - !secret person_puber
          - zone.cz
          - zone.home
          - zone.new_home
          - zone.school
          - zone.school_mini
          - zone.scouting
          - zone.work
          - zone.work_ms
```
### What version of Home Assistant Core has the issue?

core-2023.2.0b1

### Additional information

![image](https://user-images.githubusercontent.com/33529490/214841239-9fa60b37-4b29-4796-9482-69155ab46422.png)
This track shouldn't be there
