### ISSUE TITLE
setting all possible actions to none still triggers the pointer handle

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#15317]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

trying to make an entity not show any possible[ action](https://www.home-assistant.io/dashboards/actions/) by setting:
```
            tap_action:
              action: none
            hold_action:
              action: none
            double_tap_action:
              action: none
```
on an entity, in this case in glance card, still makes the handle popup, as if there could be some action

there really should be no pointer change in this case as all are negated

### Describe the behavior you expected

show no pointer change when hovering 

### Steps to reproduce the issue

1. set the above action an entity and hover
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.0

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Ventura 13.2

### Problem-relevant frontend configuration

```yaml
- entity: sun.sun
            name: ' '
            icon: ' '
            show_state: false
            tap_action:
              action: none
            hold_action:
              action: none
            double_tap_action:
              action: none
```
in this case I am trying to create a 'gap' card inside a glance card, but even on a regular card, this should not happen
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

it would be very nice if we could simply set
```
action: none
```

and not have to use the whole mapping for all 3 actions separately
(aware thats a FR, but just mentioning here)

**Comment by ildar170975** [comment]
May be I am getting this issue wrong - but:
1. No popup is displayed.
2. Mouse pointer is not changing while hovering.

```
type: picture-glance
image: /local/images/test/orange.jpg
entities:
  - entity: sun.sun
    name: ' '
    icon: ' '
    show_state: false
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
  - entity: sun.sun
```

Chrome+Win10.
