### ISSUE TITLE
Automation UI adding timer duration of zero when switching from YAML view to UI view

### ISSUE THREAD

**Issue by cbhiii** [home-assistant/frontend#15349]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The UI seems to be adding a timer duration of zero (checking the duration box) when opening an automation with a timer or when switching back to the UI after suing the 'Edit in YAML' view.

If you type this in the Edit in YAML view:
```
- service: timer.start
   entity_id: timer.exercise_room_motion_timer
```
and then switch back to UI view it changes it into this:
```
 - service: timer.start
    data:
      duration: 0
    target:
      entity_id: timer.exercise_room_motion_timer
```

### Describe the behavior you expected

It should either not alter the YAML or if it does then it should end up like this:
```
 - service: timer.start
    data: {}
    target:
      entity_id: timer.exercise_room_motion_timer
```

### Steps to reproduce the issue

1. Open automation and then click Edit in YAML
2. Add/edit timer as shown above using two simple lines.
3. Click save
4. Switch back to the UI view and view the changed timer entry which will show that the duration checkbox is now checked.
...

### What version of Home Assistant Core has the issue?

2023.2.2

### What was the last working version of Home Assistant Core?

2023.1.x

### In which browser are you experiencing the issue with?

Brave, Chrome, Safari

### Which operating system are you using to run this browser?

macOS 13.1

**Comment by karwosts** [comment]
I think this may actually be a problem with the core definition of this service. For some reason it says "default: 0" for the duration field. Seems like maybe should not have a default value?

```
start:
  name: Start
  description: Start a timer
  target:
    entity:
      domain: timer
  fields:
    duration:
      description: Duration the timer requires to finish. [optional]
      default: 0
      example: "00:01:00 or 60"
      selector:
        text:
```
