### ISSUE TITLE
Logbook/logbook card is showing the wrong icon of an input helper

### ISSUE THREAD

**Issue by mstuij** [home-assistant/frontend#15418]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the logbook/logbook card the wrong icon is showed of a helper entity.

In my yaml file:

```
input_button.dummy_covers_log:
  icon: mdi:window-shutter       
```

It is showed correctly in the entity info dialog:

![image](https://user-images.githubusercontent.com/75884924/218118405-ae38a850-015f-44ee-862d-ebd59f862ac7.png)

In the logbook the wrong icon is showed:

![image](https://user-images.githubusercontent.com/75884924/218118529-5762cf42-758e-4b85-8e47-3c17ac65dc0c.png)

Also in the logbook card the wrong icon is showed:

![image](https://user-images.githubusercontent.com/75884924/218118582-4886cd3e-0735-4417-9eda-b863bd597370.png)

I use this dummy sensor to create a custom log for all of my automations. The log record is created by the next service call:

```
service: logbook.log
data:
  name: Some message
  message: Some message about the executed automation.
  domain: cover

```

### Describe the behavior you expected

the window-shutter icon should be showed in the logbook/logbook card

### Steps to reproduce the issue

1. Create this input helper

```
input_button.dummy_covers_log:
  icon: mdi:window-shutter       
```

2. Create a log entry by calling this service

```
service: logbook.log
data:
  name: Some message
  message: Some message about the executed automation.
  domain: cover

```

3. Check the icon in the logbook/logbook card of the input_button.dummy_covers_log entity

### What version of Home Assistant Core has the issue?

2023.2.3

### Additional information

Unfortunately there is no support for a logbook of just your own custom automation messages. The reason that I use an input_button is that the template sensors gives a log record after restarting Home Assistant. The input_button doesn't do this. So only my own automation texts are saved on the entity.
