### ISSUE TITLE
Sensor Group - Edit issue

### ISSUE THREAD

**Issue by Blackshome** [home-assistant/frontend#15419]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created a _sensor group_ for a lux sensor as per [FAQ](https://community.home-assistant.io/t/sensor-light-motion-sensor-door-sensor-sun-elevation-lux-value-scenes-time-light-control-device-tracker-night-lights/481048/188?u=blacky) in my blueprint.

Without editing the _sensor group_ I can add it to my blueprint in the Ambient Light Sensor selection. Just create a _sensor group_ and add it. This is my blueprint [click here](https://community.home-assistant.io/t/sensor-light-motion-sensor-door-sensor-sun-elevation-lux-value-scenes-time-light-control-device-tracker-night-lights/481048?u=blacky)

this is the code in the blueprint

```
ambient_light_sensor:
      name: Ambient Light Sensor
      description: This is used for adding a condition to only work when it is dark or below the Ambient Light LUX Value.
      default: []
      selector:
        entity:
          domain: sensor
          device_class: illuminance
```

All good, working so far.

Now if you edit the _sensor group_ then you can't select it any more in the blueprints, Ambient Light Sensor selection. This is the problem.

This is the entity ID of the _sensor group_: **sensor.lux_group**

### Describe the behavior you expected

You should be able to edit the _sensor group_ and still select it / add it to my blueprint.

Also the icon changes automaticity after you edit it.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.3 - Supervisor 2023.01.1 - Operating System 9.5 - Frontend 20230202.0 - latest

### In which browser are you experiencing the issue with?

Firefox
