### ISSUE TITLE
cors_allowed_origins doesn't work

### ISSUE THREAD

**Issue by jvcsw** [home-assistant/frontend#15427]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,

I am trying to enable cors to allow cross origin calls.

I configured an external server in configuration.yaml with all the possibilities and it always returns the same error:

![imagen](https://user-images.githubusercontent.com/37216513/218276196-61d8b1ff-f261-4167-865d-bc85bfbbcb46.png)

configuration.yaml:

```
http: 
  use_x_forwarded_for: true 
  trusted_proxies: 
  cors_allowed_origins:
    - http://192.168.1.21:8080
    - 192.168.1.21:8080
    - http://192.168.1.21
    - 192.168.1.21
    - http://name.lan
    - name.lan
  ip_ban_enabled: true
  login_attempts_threshold: 5
```

### Describe the behavior you expected

The http call returns status 200

### Steps to reproduce the issue

1. Configure cors_allowed_origins section
2. Restart HA
3. Do calls using for example Homer (https://hub.docker.com/r/b4bz/homer)
4. See the errors in browser console

### What version of Home Assistant Core has the issue?

2023.2.3

### In which browser are you experiencing the issue with?

Firefox, Chrome

### Which operating system are you using to run this browser?

Windows
