### ISSUE TITLE
Subview button required several clicks to respond

### ISSUE THREAD

**Issue by joakimjalden** [home-assistant/frontend#15424]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sometimes the back button from a subview requires several clicks to respond to the command and return the UI to the view from which the subview was entered. See a more elaborate discussion of the issue in my [forum post #532892](https://community.home-assistant.io/t/dashboard-subview-back-button-becomes-unresponsive/532892).

### Describe the behavior you expected

Returning immediately to the previous view when clicking the back button.

### Steps to reproduce the issue

Using the minimal dashboard example below, with the numerical sensor at the end replaced by any suitable numerical sensor that provides a History graph in a popup when clicked

1. Enter the subview by clicking the button
2. Klick on the value to bring up the History graph in the info panel pop-up
3. Close the pop-up window

Now (at least on my system), the subview back button (in the upper left corner) becomes unresponsive for 3 clicks and returns to the main view (with the single button) on the fourth click.

```
title: Example
views:
  - path: view
    title: View
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: navigate
          navigation_path: /dashboard-subview/subview
  - theme: Backend-selected
    title: Subview
    path: subview
    subview: true
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.ficus_benjamina_moisture
  ``` 

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.3

### In which browser are you experiencing the issue with?

Microsoft Edge Version 109.0.1518.78 (Official build) (64-bit) AND iOS companion app

### Which operating system are you using to run this browser?

Windows 10 AND iOS Version 16.1

### Problem-relevant frontend configuration

```yaml
See the steps to recreate the issue above
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

The issue does not seem to appear if the numerical sensor is replaced by a sensor with discrete states ('on', 'off', etc) in the colored history bar. In the minimal example given it needs to be a sensor with a history graph.
