### ISSUE TITLE
Chart card X axis displaying more than configured

### ISSUE THREAD

**Issue by Lectere** [home-assistant/frontend#15438]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Chart card X axis displaying more days than it should. 

![image](https://user-images.githubusercontent.com/4771745/218462093-956d1b09-ba6d-4ab2-84c9-6d3dc089b3aa.png)

I've configured my chart to display 3 days. But on the X axis I see more than 8 days back...

I've had this is several setups/installations, changing the days to 2 or 4 does not solve the problem.

### Describe the behavior you expected

The chart should display only the amount of days configured in it's yaml. 

### Steps to reproduce the issue

1. add a chart card to the dashboard
2. wait a few days
3.  the chart now displays more days than configured
...

### What version of Home Assistant Core has the issue?

2023.1.7

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

both edge / chrome and the app

### Which operating system are you using to run this browser?

android / windows

### State of relevant entities

```txt
occurs with several entities, both temprature and humidty

I suspect it has to things need to happend for the problem to occour; -missing value of one of the graph series -a reboot
```

### Problem-relevant frontend configuration

```yaml
square: false
columns: 1
type: grid
cards:
  - show_name: true
    show_icon: false
    show_state: true
    type: glance
    entities:
      - entity: sensor.openweathermap_humidity
        name: Buiten
      - entity: sensor.multisensor_7_humidity
        name: Woonkamer
      - entity: sensor.lumi_lumi_airmonitor_acn01_humidity
        name: Keuken
      - entity: sensor.lumi_lumi_weather_humidity
        name: Badkamer
    title: Luchtvochtigheid
  - chart_type: line
    period: 5minute
    days_to_show: 3
    type: statistics-graph
    entities:
      - entity: sensor.openweathermap_humidity
        name: Buiten
      - entity: sensor.multisensor_7_humidity
        name: Woonkamer
      - entity: sensor.lumi_lumi_airmonitor_acn01_humidity
        name: Keuken
      - entity: sensor.lumi_lumi_weather_humidity
        name: Badkamer
    stat_types:
      - mean
```
