### ISSUE TITLE
Automation editor surrounds !secret data with quotes

### ISSUE THREAD

**Issue by xcomputerman** [home-assistant/frontend#15463]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created an automation using the UI editor to automatically disarm the home alarm. I used !secret to specify the disarm code; however when the automation ran, it actually triggered the alarm instead of disarming it.

Digging deeper, I opened the YAML of the automation and realized that it had created this:

```
- service: alarm_control_panel.alarm_disarm
  entity_id: alarm_control_panel.home_alarm
  data:
    code: "!secret alarm_code"
```

This caused home assistant to send a bad code to the alarm panel and trigger the alarm. Furthermore, if I fix this in YAML and then switch back to the UI editor, it always surrounds it with quotes again.

### Describe the behavior you expected

For alarm panel data, it should not surround the code with quotes as this is always either a numerical value or a secret.

```
- service: alarm_control_panel.alarm_disarm
  entity_id: alarm_control_panel.home_alarm
  data:
    code: !secret alarm_code
```

### Steps to reproduce the issue

1. Create a new automation in UI
2. Add action to disarm a home alarm entity
3. Specify code using !secret secret_code
...

### What version of Home Assistant Core has the issue?

2023.2.3

### In which browser are you experiencing the issue with?

Firefox 102.7.0esr (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro 19044.2486
