### ISSUE TITLE
Thermostat card not updating correctly

### ISSUE THREAD

**Issue by msp1974** [home-assistant/frontend#15483]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A part of a well established custom component (Wiser integration), we are trying to add a new function for heating control.  This allows the temperature to be a range (min/max).  However, one of the options is to tie the max to the scheduled temperature and therefore not allow it to be changed (but leave the min user selectable) via the thermostat card slider.

When the max temp is changed using the slider, the underlying custom component will not change it and leave at the pre-determined scheduled temp.

Using the thermostat card, it does not update to reflect that the temp range is not what was set by the user but maintains the temp that was set (both the slider and the text temp range).

If doing this using the more-info dialog for the thermostat card, this does work as expected.  The new temp shows red while waiting to update and then reverts to the scheduled temp after a couple of seconds.  The thermostat card never updates without a refresh of browser.

### Describe the behavior you expected

I expect the thermostat card to revert to the actual max temp (slider and text range) as the more-info dialog box does.

### Steps to reproduce the issue

Steps to recreate:

1. Create climate mqtt template device as per below config
2. Set initial temp state as 21C with mqtt message on topic study/ac/temp/state
3. Using the thermostat card, change the temp to 23C (or any other value but 21C)
4. Send mqtt message of temp state to 21C on topic study/ac/temp/state (to recreate a failed/blocked update) - thermostat card will remain at 23C
5. Send mqtt message to set temp to any other value and card will update.

### Climate Device Config Yaml
```yaml
mqtt:
  climate:
    - name: Study
      modes:
        - "off"
        - "heat"
        - "auto"
      mode_command_topic: "study/ac/mode/set"
      mode_state_topic: "study/ac/mode/state"
      mode_state_template: "{{ value_json }}"
      current_temperature_topic: "study/ac/temp/current"
      temperature_state_topic: "study/ac/temp/state"
      temperature_command_topic: "study/ac/temp/set"
```
...

### What version of Home Assistant Core has the issue?

2023.1

### What was the last working version of Home Assistant Core?

NA

### In which browser are you experiencing the issue with?

Firefox 109.0.1, Google Chrome Version 109.0.5414.121 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 20.04 and Windows 11

### Javascript errors shown in your browser console/inspector

```txt
No errors in browser console
```

### Additional information

https://loom.com/share/8f47d748a0d84bfc87e9daa5b4721450

You will see this behaviour in the above video.  The climate card maintains the temp set by the slider (not reverting).  The more info card does revert.  Even when closing the more info card, the thermostat card does not update.
