### ISSUE TITLE
history-graph: wrong auto-refresh (input_boolean)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#15498]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Continuation of this problem: https://github.com/home-assistant/frontend/issues/13128
Currently I observe the problem for non-numerical entities only.

Test card:

![image](https://user-images.githubusercontent.com/71872483/219959541-7b7f24ed-c16a-4555-98e3-3984d4936b21.png)

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_boolean.flag
        secondary_info: last-changed
  - type: history-graph
    entities:
      - input_boolean.flag
    hours_to_show: 1
    refresh_interval: 0
```

Toggle the entity:
![image](https://user-images.githubusercontent.com/71872483/219959562-f39c986f-37a4-49f0-a79c-34e31da565e5.png)

The graph is updated not immediately, after ~1 minute:
![image](https://user-images.githubusercontent.com/71872483/219959580-f000ff95-b66b-4964-aeb4-f4067de52f57.png)

### Describe the behavior you expected

The graph is updated immediately.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.2.5

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.97 

### Which operating system are you using to run this browser?

Win10x64
