### ISSUE TITLE
too dark map issue when using dark theme

### ISSUE THREAD

**Issue by kiki3529-0** [home-assistant/frontend#15587]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Good morning
when I use the dark theme, the map is really too dark to see the streets well, is it possible to make it much lighter?
THANKS

### Describe the behavior you expected

too dark map issue when using dark theme

Good morning
when I use the dark theme, the map is really too dark to see the streets well, is it possible to make it much lighter?
THANKS

### Steps to reproduce the issue

1.companion app
2.dark theme 
3.person
4 map
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.5 Supervisor 2023.01.1 Operating System 9.5 Interface utilisateur : 20230202.0 - latest

### What was the last working version of Home Assistant Core?

Home Assistant 2023.2.5 Supervisor 2023.01.1 Operating System 9.5 Interface utilisateur : 20230202.0 - latest

**Comment by matthiasdebaat** [comment]
What type of device are you using? Is it the same on desktop and mobile? Can you share a screenshot and describe what parts should be improved?

**Comment by kiki3529-0** [comment]
I m using a smart phone (OnePlus 5 android)
Yes it is the same on desktop and mobile.

I like very much the dark theme, and I would like to keep it, is it
possible to keep dark mode with a white map instead of black map?
I share your a screenshot
Thanks 🙏
Mickaël

**Comment by ildar170975** [comment]
There is an inconsistency with maps in a dark mode.
Check this code:
```
  - type: horizontal-stack
    cards:
      - type: map
        entities:
          - person.ildar
      - type: map
        entities:
          - person.ildar
        dark_mode: false
      - type: map
        entities:
          - person.ildar
        dark_mode: true
```

Light default mode:
![изображение](https://user-images.githubusercontent.com/71872483/221350684-32d27ab5-0792-4f70-b8ec-a3f0372f8efe.png)

Dark default mode:
![изображение](https://user-images.githubusercontent.com/71872483/221350697-58b35ec2-844c-4ae1-8fc6-1a08d7cbdd64.png)

The issue was described here: https://github.com/home-assistant/frontend/issues/13333
And no any movement for this issue.

And  see a difference since 2022.8 (described here - https://github.com/home-assistant/frontend/issues/13333#issuecomment-1204757410):
![изображение](https://user-images.githubusercontent.com/71872483/221350784-2b006d8f-47b9-4c76-aa4e-b8679e1a50f0.png)
