### ISSUE TITLE
Horizontal Stack all into one row squeezed

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#15612]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Auto break is missing, see picture below:

![ADC8454A-B0BF-495D-A4DD-AF5333C02682](https://user-images.githubusercontent.com/71203830/221541293-f927c949-579f-40b3-950a-47908e3a9f63.jpeg)

### Describe the behavior you expected

Auto break rows to get a readable result. 

### Steps to reproduce the issue

1. Create a new Horizontal Stack Card
2. Add multiple cards (10+)
3. Save
...

### What version of Home Assistant Core has the issue?

2023.3.0b3

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.114, Safari 16.3.1

### Which operating system are you using to run this browser?

iPadOS 16.3.1

### Problem-relevant frontend configuration

```yaml
type: horizontal-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.dummieswitch
```
