### ISSUE TITLE
Both Overlay and Time Period are activated for Tado service calls when opening an automation

### ISSUE THREAD

**Issue by muffer-nl** [home-assistant/frontend#15634]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open any automation that contains a Tado service call for heating in the HA GUI it always shows both the Overlay and Time Period options as checked. Only one of these options can be active at any one time. If both options are active the automation will fail on the Tado service call.

When I check the automations.yaml before I open the automation it only shows the Overlay as configured. The Time Period is not configured. If I remove the checkbox before the unwanted option and save it is stored correctly.

It is very annoying as this bug breaks the automation if I go in to change something else. When I click save it stores the incorrect configuration. 

This bug also applies in the reverse. Of only the Time Period is set the GUI will check the box for the Overlay (defaulting to Tado default).

Issue applies in both Firefox and Chrome, in regular and Incognito views. Another user on Reddit confirmed the same behaviour.

### Describe the behavior you expected

The GUI to only check the boxes configured in the automations.yaml file when opening an automation.

### Steps to reproduce the issue

1. Create an automation calling the Tado service to set a temperature
2.  Configure it with either an Overlay or Time Period
3.  Save the automation
4.  Open the automation

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

2023.2.4 I believe but not sure

### In which browser are you experiencing the issue with?

Firefox 110.0

### Which operating system are you using to run this browser?

Windows 10 pro Version 10.0.19044 Build 19044

**Comment by karwosts** [comment]
This is actually an issue with the tado integration, not the frontend. Frontend will enable both because the service call has a default value set for both in the tado services definition.

Notice that both time_period and requested_overlay specify a default value:

```
set_climate_timer:
  name: Set climate timer
  description: Turn on climate entities for a set time.
  target:
    entity:
      integration: tado
      domain: climate
  fields:
    temperature:
      name: Temperature
      description: Temperature to set climate entity to
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 0.5
          unit_of_measurement: "°"
    time_period:
      name: Time period
      description: Choose this or Overlay. Set the time period for the change if you want to be specific. Alternatively use Overlay
      required: false
      example: "01:30:00"
      default: "01:00:00"
      selector:
        text:
    requested_overlay:
      name: Overlay
      description: Choose this or Time Period. Allows you to choose an overlay. MANUAL:=Overlay until user removes; NEXT_TIME_BLOCK:=Overlay until next timeblock; TADO_DEFAULT:=Overlay based on tado app setting
      required: false
      example: "MANUAL"
      default: "TADO_DEFAULT"
      selector:
        select:
          options:
            - "NEXT_TIME_BLOCK"
            - "MANUAL"
            - "TADO_DEFAULT"
```

I would suggest open this issue in the core repository tagged with the frontend component, and ask the component owners to review the defaults and possibly remove one or both, depending on which fields they want populated by default.
