### ISSUE TITLE
Dashboard Thermostat Card Broken

### ISSUE THREAD

**Issue by gnvdude** [home-assistant/frontend#15683]
### The problem

both mobile and web dashboard thermostat card post upgrade not able to adjust temp anymore

Home Assistant 2023.3.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230301.0 - latest

![image](https://user-images.githubusercontent.com/9097927/222496048-e95ecbc7-4381-4861-91b2-14befd016fa8.png)

have to click on 3 dots to adjust temp

![image](https://user-images.githubusercontent.com/9097927/222496204-976d559c-3481-46c4-9000-5ab7131b2bc9.png)

### What version of Home Assistant Core has the issue?

2023.3.0

### What was the last working version of Home Assistant Core?

previous version

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

thermostat CARD

### Example YAML snippet

```yaml
title: Home View
views:
  - title: Thermostat
    path: thermostat
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.home
      - type: thermostat
        entity: climate.upstairs_thermostat
      - type: thermostat
        entity: climate.lucas_thermostat_4
        name: Lucas Thermostat
      - type: thermostat
        entity: climate.livingroom_thermostat_3
        name: Livingroom Thermostat
      - type: thermostat
        entity: climate.hallway_thermostat_5
        name: Hallway Thermostat
      - type: thermostat
        entity: climate.master_bedroom_thermostat_2
        name: Master Bedroom
      - type: entities
        entities:
          - sensor.hacs
        title: HACS
  - title: Rooms
    path: bedrooms
    badges: []
    cards:
      - type: entities
        entities:
          - entity: cover.garage_door
          - entity: cover.garage_door_2
        title: Garage Door
      - type: entities
        entities:
          - entity: light.bed_level_on_off
          - entity: light.bonus_room_light
          - entity: light.sengled_e11_g13_af103703_level_on_off
          - entity: light.sengled_e11_g13_c0780d03_level_on_off
          - entity: light.sengled_e11_g13_df630d03_level_on_off
          - entity: light.sengled_e11_g13_8e020c03_level_on_off
          - entity: light.sengled_e11_g13_20621003_level_on_off
          - entity: group.lamp
          - entity: light.bedroom_lights
          - entity: light.100095469d
          - entity: light.100095469d
        title: Bedroom
      - type: entities
        entities:
          - entity: light.lucas_light_level_on_off
          - entity: fan.lucas_fan
          - entity: light.lucas_fan
        title: Lucas Bedroom
      - type: entities
        entities:
          - entity: fan.lucas_playroom
          - entity: light.lucas_playroom
          - entity: switch.sengled_e1c_nb7_6a426203_on_off
        title: Lucas Playroom
      - type: humidifier
        entity: humidifier.dehumidifier
        name: 'Dehumidifier '
      - type: entities
        entities:
          - entity: switch.smart_power_strip_1_socket_1
          - entity: switch.livingroom_switch_2_socket_1
          - entity: switch.innr_sp_224_990665fe_on_off
          - entity: fan.fan_2
        title: 'Livingroom '
      - type: grid
        square: false
        columns: 1
        cards:
          - type: entities
            entities:
              - remote.tv
            title: TV 75"
            state_color: true
          - type: media-control
            entity: media_player.tv
      - type: grid
        square: false
        columns: 1
        cards:
          - type: entities
            entities:
              - remote.55_tcl_roku_tv_lucas
          - type: media-control
            entity: media_player.55_tcl_roku_tv_lucas
  - title: Pool
    path: Home
    theme: dark-mode
    badges: []
    cards:
      - type: thermostat
        entity: climate.pentair_16_51_d0_pool_heat
        name: Pool Heater
      - type: entities
        entities:
          - entity: switch.pentair_16_51_d0_bubbler
          - entity: switch.pentair_16_51_d0_deck_jets
          - entity: switch.pentair_16_51_d0_waterfall
          - entity: switch.pentair_16_51_d0_cleaner
          - entity: light.pool_fan_light
          - entity: sensor.pentair_16_51_d0_pool_pump_current_rpm
      - type: entity
        entity: fan.pool_fan
        attribute: percentage
  - title: Security
    path: security
    badges: []
    cards:
      - type: entities
        entities:
          - binary_sensor.konnected_8cf961_zone_1
          - binary_sensor.konnected_8cf961_zone_2
          - binary_sensor.konnected_8cf961_zone_3
          - binary_sensor.konnected_8cf961_zone_4
          - binary_sensor.konnected_8cf961_zone_5
          - binary_sensor.konnected_8cf961_zone_6
  - title: Mushrooms
    path: mushrooms
    icon: mdi:mushroom
    badges: []
    cards:
      - type: picture-glance
        title: Mushroom Camera 1
        entities:
          - binary_sensor.remote_ui
          - binary_sensor.updater
        camera_image: camera.mushroom_camera_1
      - type: entities
        entities:
          - entity: sensor.mushroom_box_1_temperature_2
          - entity: sensor.mushroom_box_2_temperature
          - entity: sensor.mushroom_box_3_temperature
          - entity: sensor.mushroom_box_4_temperature
          - entity: sensor.mushroom_box_5_temperature
          - entity: sensor.mushroom_box_6_temperature
          - entity: sensor.mushroom_box_7_temperature
          - entity: sensor.mushroom_box_8_temperature
          - entity: sensor.mushroom_box_9_temperature
        title: Mushrooms Temperature
      - type: entities
        entities:
          - entity: sensor.mushroom_box_1_humidity_2
          - entity: sensor.mushroom_box_2_humidity
          - entity: sensor.mushroom_box_3_humidity
          - entity: sensor.mushroom_box_4_humidity
          - entity: sensor.mushroom_box_5_humidity
          - entity: sensor.mushroom_box_6_humidity
          - entity: sensor.mushroom_box_7_humidity
          - entity: sensor.mushroom_box_8_humidity
          - entity: sensor.mushroom_box_9_humidity
        title: Mushroom Humidity
      - type: entities
        entities:
          - entity: sensor.mushroom_box_1_battery_level_2
          - entity: sensor.mushroom_box_2_battery_level
          - entity: sensor.mushroom_box_3_battery_level
          - entity: sensor.mushroom_box_4_battery_level
          - entity: sensor.mushroom_box_5_battery_level
          - entity: sensor.mushroom_box_6_battery_level
          - entity: sensor.mushroom_box_7_battery_level
          - entity: sensor.mushroom_box_8_battery_level
          - entity: sensor.mushroom_box_9_battery_level
        title: Mushroom Sensor Battery Levels
```
