### ISSUE TITLE
Tile card in grid vertical: true won't square

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#15703]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using a grid with tile card in regular (not using `vertical: true`) shows nicely squared cards (because that is default for grid):

<img width="576" alt="Scherm­afbeelding 2023-03-04 om 16 14 09" src="https://user-images.githubusercontent.com/33354141/222914119-850d0dd0-4587-4f1f-a7d8-719a9a7455f1.png">

However, because the info is cut-off and the icon is off center, we need to use `vertical: true`.

the cards then dont square, and show a lot off empty space (taking out the secondary info line with card_mod, actually reducing the info the card has to show)
<img width="555" alt="Scherm­afbeelding 2023-03-04 om 16 14 25" src="https://user-images.githubusercontent.com/33354141/222914191-ee8c65ad-c05f-447f-b7f3-d4e40c39d045.png">

### Describe the behavior you expected

we'd expect the tile cards to square, and auto resize to the given space in the grid

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Ventura 13.2

### Problem-relevant frontend configuration

```yaml
- type: grid
    columns: 5
    square: true
    cards:

      - entity: device_tracker.iungo
        <<: &tile_vertical
          type: tile
          vertical: true
          card_mod:
            style:
              ha-tile-info$: |
                .secondary {
                  display: none;
                }
```
