### ISSUE TITLE
Live camera doesn't work for image elements in Picture Elements Card

### ISSUE THREAD

**Issue by mu3** [home-assistant/frontend#15744]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The flag is ignored

### Describe the behavior you expected

Live stream from camera, not 10s images

### Steps to reproduce the issue

```
type: picture-elements
image: /local/floorplan.png
elements:
  - type: image
    camera_image: camera.my_camera
    camera_view: live
```

### What version of Home Assistant Core has the issue?

2023.3.1
