### ISSUE TITLE
MQTT Lights RGB & Brightness Controls

### ISSUE THREAD

**Issue by cab1861** [home-assistant/frontend#15745]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating HA, I've had issues pulling up RGB and Brightness controls of my MQTT lights. Right now I don't get anything in the dialog:
![image](https://user-images.githubusercontent.com/46981500/223002690-afa1d7a1-88d0-4eda-a90d-2e9f1116c7c9.png)

The dialogs are working for other entities:
![image](https://user-images.githubusercontent.com/46981500/223002754-4fad21dd-3a71-4d73-b806-e4293fcc155c.png)

yaml code:
```
light:
    - name: "Desk Lights"
      state_topic: "desk/state/powerall"
      command_topic: "desk/command/powerall"
      brightness_state_topic: "desk/state/brightness"
      brightness_command_topic: "desk/command/brighness"
      rgb_state_topic: "desk/state/rgb"
      rgb_command_topic: "desk/command/rgb"
      effect_state_topic: "desk/state/effect"
      effect_command_topic: "desk/command/effect"
      optimistic: false
      retain: true
```

### Describe the behavior you expected

I would expect to see the RGB wheel and brightness slider, or at least the ability to open those controls

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

Firefox, Safari

### Which operating system are you using to run this browser?

iOS 16, Windows 10
