### ISSUE TITLE
ha-selector-datetime broken in ha-service-control

### ISSUE THREAD

**Issue by karwosts** [home-assistant/frontend#15755]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

ha-selector-datetime behaves oddly in ha-service-control. Condider `calendar:create_event`, the only service I see that uses this selector type. It has no default values. 

```
    start_date_time:
      name: Start time
      description: The date and time the event should start.
      example: "2022-03-22 20:00:00"
      selector:
        datetime:
    end_date_time:
      name: End time
      description: The date and time the event should end.
      example: "2022-03-22 22:00:00"
      selector:
        datetime:
```

On first load, end time is selected as enabled (it shouldn't be), the time field is turned on but the date field is disabled. 
![image](https://user-images.githubusercontent.com/32912880/223178794-80959564-0940-418c-9ce1-06878c4f3856.png)

Switch to yaml mode yields:
```
service: calendar.create_event
data:
  end_date_time: undefined 00:00:00
```

Switch back to UI editor, it gets even more messed up. Now start time has the same problem, and the date field has completely disappeared from end time:

![image](https://user-images.githubusercontent.com/32912880/223179035-07775efc-dd0d-4427-9242-3256e789f072.png)

Switch back to yaml mode a second time and see:
```
service: calendar.create_event
data:
  end_date_time: undefined 00:00:00
  start_date_time: undefined 00:00:00
```

### Describe the behavior you expected

fields should be disabled by default

### Steps to reproduce the issue

1. Developer Tools -> Services
2. Select Calendar: Create event
3.
...

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

firefox, chrome

### Which operating system are you using to run this browser?

win10
