### ISSUE TITLE
No way to select white LEDs in RGBW light

### ISSUE THREAD

**Issue by Elkropac** [home-assistant/frontend#15756]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When i want to go from color light back to white light on my RGBW bulb i click into central white dot but i get RGB white, not white from dedicated LEDs.

In esphome log, i can see this after click white center
```
[22:45:50][D][light:035]: 'zemismart_bulb_a19_002_light_rgbw' Setting:
[22:45:50][D][light:054]:   Color brightness: 100%
[22:45:50][D][light:057]:   Red: 100%, Green: 100%, Blue: 100%
```

### Describe the behavior you expected

Clicking white center switches from color_mode = rgb to color_mode = white. Or have some other way like in old frontend

### Steps to reproduce the issue

1. click some color on color wheel
2. click white center on color wheel

### What version of Home Assistant Core has the issue?

 2023.3.1

### What was the last working version of Home Assistant Core?

 2023.2.?

### In which browser are you experiencing the issue with?

Chromium Version 110.0.5481.177

### Which operating system are you using to run this browser?

Debian unstable

**Comment by piitaya** [comment]
Hello 🙂
Can you provide the state and the attributes of your light? https://my.home-assistant.io/redirect/developer_states/

**Comment by Elkropac** [comment]
Hi,
it is set in esphome as rgbw light like this
```
light:
  - platform: rgbw
    id: light_01
    name: "${dev_name}_light_rgbw"
    default_transition_length: 0s
    color_interlock: true
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    effects: !include ../../.common/light_effects_01.yaml

my9231:
  data_pin: GPIO13
  clock_pin: GPIO15
  num_channels: 4
  num_chips: 1
#  bit_depth: 14

output:
  - platform: my9231
    id: output_blue
    channel: 1
  - platform: my9231
    id: output_red
    channel: 3
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_white
    channel: 0
```

I have button to turn the light on in white mode, then the state is
```
supported_color_modes:
  - rgb
  - white
color_mode: white
brightness: 242
friendly_name: Lampa u postele
supported_features: 40
```

after selecting some color from wheel
```
supported_color_modes:
  - rgb
  - white
color_mode: rgb
brightness: 242
friendly_name: Lampa u postele
supported_features: 40
hs_color:
  - 0
  - 100
rgb_color:
  - 255
  - 0
  - 0
xy_color:
  - 0.701
  - 0.299
```

after clicking to central white dot
```
supported_color_modes:
  - rgb
  - white
color_mode: rgb
brightness: 242
friendly_name: Lampa u postele
supported_features: 40
hs_color:
  - 0
  - 0
rgb_color:
  - 255
  - 255
  - 255
xy_color:
  - 0.323
  - 0.329
```
