### ISSUE TITLE
history-graph: new "precision" settings is not used

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#15761]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Precision settings are set for some sensor:

![изображение](https://user-images.githubusercontent.com/71872483/223529914-8291bb6e-ee63-493c-89a7-a0e991d2e68a.png)

Test card:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: sensor.memory_free
  - type: entity
    entity: sensor.memory_free
  - type: tile
    entity: sensor.memory_free
  - type: history-graph
    entities:
      - entity: sensor.memory_free
```
All cards use the changed precision - except the `history-graph`:

![изображение](https://user-images.githubusercontent.com/71872483/223530407-94411c9e-c638-4b3a-8175-5cf4d207f3cd.png)

### Describe the behavior you expected

history-graph should use "precision" settings

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.178 

### Which operating system are you using to run this browser?

Win10x64
