### ISSUE TITLE
Date attributes are displayed wrongly based on timezone

### ISSUE THREAD

**Issue by pinkywafer** [home-assistant/frontend#15813]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

any sensor which return a date attribute are being converted to a timezone aware datetime, the result being that an attribute which reports for example `2023-06-21` displays on the frontend attributes as `June 20, 2023` if the browser is in a negative timezone.
datetime.date values are not timezone aware, so should not be converted.

### Describe the behavior you expected

frontend date should match the attribute date

### Steps to reproduce the issue

1. Create the following template sensor:
```yaml
template:
  - sensor:
      - name: "TEMPLATED"
        state: '2023-06-21'
        attributes:
          date: '2023-06-21'
```
2. reload config
3. if browser's (device) timezone is UTC or any + value, attribute will display `June 21, 2023`
4. set browser's (device) timezone to any - value, ie. UTC -5:00 Eastern Time : reload frontend and now the frontend shows `June 20, 2023`

Note the dev states page always shows `date: 2023-06-21` for the attributes.
...

### What version of Home Assistant Core has the issue?

Frontend 20230309.0 - latest

### In which browser are you experiencing the issue with?

tested on chrome and edge

### Which operating system are you using to run this browser?

windows 10

### State of relevant entities

```txt
state: 
2023-06-21

attributes:
date: 2023-06-21
friendly_name: TEMPLATED
```

### Problem-relevant frontend configuration

```yaml
the more-info page always shows the erroneous attribute.


type: entity
entity: sensor.templated
attribute: date

also shows the erroneous attribute
```

### Javascript errors shown in your browser console/inspector

```txt
None
```
