### ISSUE TITLE
Wrong & inconsistent history for "unavailable" value

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#15866]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this template sensor:
```
template:
  - sensor:
      - name: testing_availability
        unit_of_measurement: "unit"
        state: >-
          {{ states("input_number.test_number") }}
        availability: >-
          {{ is_state("input_boolean.test_boolean","on") }} 
```
And these test cards:
```
  - type: entities
    entities:
      - entity: input_boolean.test_boolean
        name: Available
      - entity: input_number.test_number
        name: Value
      - type: divider
      - entity: sensor.testing_availability

  - type: history-graph
    entities:
      - entity: sensor.testing_availability
    hours_to_show: 1
```
![изображение](https://user-images.githubusercontent.com/71872483/226151760-ed8f1fe1-bb29-4b8f-a4b1-2c5717e033b4.png)

Let's play with `availability` of this sensor and see how it is displayed in `history-graph`.

This is a graph when the sensor is available, seems OK:

![изображение](https://user-images.githubusercontent.com/71872483/226151776-c693a8bd-2d5a-438e-a196-1afbed9ec55f.png)

Turn the `availability` off:
![изображение](https://user-images.githubusercontent.com/71872483/226151791-e3c23212-3607-4904-b418-f0e17ffb0c90.png)

Now the sensor is `unavailable`:

![изображение](https://user-images.githubusercontent.com/71872483/226151805-c0d9c331-8334-4659-9087-de67f2456101.png)

Note that this sensor became `unavailable` at 05:52:41:

![изображение](https://user-images.githubusercontent.com/71872483/226151826-707c0225-b1a1-4cc0-86fc-7b10aa3d351b.png)

But History shows this sensor as available (note that the right border is "05:53:40"):

![изображение](https://user-images.githubusercontent.com/71872483/226151843-aea3dad9-b9ef-422d-8afa-7967f45d9f7f.png)

And later the graph still same (note that the right border is ~ "06:00"):

![изображение](https://user-images.githubusercontent.com/71872483/226151881-86518870-f573-44d6-915b-2cd394318450.png)

Then turn `availability` on.
Note `history-graph` now shows a different picture - a gap:

![изображение](https://user-images.githubusercontent.com/71872483/226151907-977e7e38-66b7-4db1-8bb4-8e27e3ab9551.png)

And same is with History - it shows a gap:

![изображение](https://user-images.githubusercontent.com/71872483/226151956-268824ba-70c8-46b8-aa4a-0f615f15e680.png)

So, the sensor was `unavailable` between 05:53:40 & 06:00:48:
![изображение](https://user-images.githubusercontent.com/71872483/226152009-447b0092-a0ad-4f74-b23f-a3d4608ab94d.png)

but the gap started displayed only when the sensor became available again.

### Describe the behavior you expected

When a sensor is `unavailable` - a gap must be displayed in a graph.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.3.4

### In which browser are you experiencing the issue with?

Chrome 111.0.5563.65 

### Which operating system are you using to run this browser?

Win10x64
