### ISSUE TITLE
Developer Tools > Services is inconsistent about prompting for duration selectors

### ISSUE THREAD

**Issue by stanford-scs** [home-assistant/frontend#15939]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm using Home Assistant 2023.3.6 Frontend 20230309.1 with firefox 110.0.1 and chromium 110.0.5481.177, as well as the latest android app from the play store.  I have a script in which one field has a `duration` input selector:

```
alias: Momentary Switch
fields:
  entity:
    name: Target entity
    description: The switch to activate momentarily
    selector:
      entity:
        domain: switch
    required: true
  duration:
    name: Duration
    description: Time for which to activate the switch
    required: false
    default:
      hours: 0
      minutes: 0
      seconds: 0.25
    selector:
      duration: null
sequence:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: "{{entity}}"
  - delay: "{{ duration | default(0.250) }}"
  - service: switch.turn_off
    data: {}
    target:
      entity_id: "{{entity}}"
mode: parallel
icon: mdi:gesture-tap-button
description: Momentarily activate a switch
max: 10
```

If I visit the YAML editor for this script in Settings > Automations & Scenes > Scripts and then navigate to Developer Tools > Services, I will have the ability to input a specific duration in UI mode.  However, if I reload the browser, or attempt to access the developer tools from any other browser, then the ability to edit the duration disappears.  This also happens in private browsing mode, and on multiple clients, so it doesn't appear to be some bad browser state.

### Describe the behavior you expected

I would expect that I always have the ability to enter a duration, just the same as when I first navigate to the Developer Tools > Services tab.

### Steps to reproduce the issue

1. Create a new script under Settings > Automations & Scenes > Scripts
2. Enter YAML mode and cut and paste the automation from above, or write a simpler automation with just a duration input
3. Navigate to Developer Tools > Services and call up the script you just created.  You should see a duration input.
4. Reload your browser or visit the Services page in a different browser tab, and you will no longer be able to input a duration.
...

### What version of Home Assistant Core has the issue?

core-2023.3.6

### In which browser are you experiencing the issue with?

Firefox 110.0.1

### Which operating system are you using to run this browser?

arch Linux

### Additional information

This is what I think the UI should look like always:

![momentaryui-correct](https://user-images.githubusercontent.com/4564109/227739165-dd8040fd-0f89-47ca-b678-36d1be3544b8.png)

But this is what it looks like after reloading the browser or on another machine that didn't just exit the script editor:

![momentaryui](https://user-images.githubusercontent.com/4564109/227739109-1a60d1a0-286f-4359-ae6e-712774af57e7.png)
