### ISSUE TITLE
Incorrect module name for homeassistant.auth.mfa_modules passes config check, but stops home assistant from loading

### ISSUE THREAD

**Issue by jack5mikemotown** [home-assistant/frontend#15963]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When setting up the home assistant mfa modules through yaml, adding an invalid module type will pass the built in "check config" but will stop core from starting up

### Describe the behavior you expected

Check config should see that the module is invalid and warn me

### Steps to reproduce the issue

1. Create a yaml for mfa modules in yaml
2. Create one with a `type` parameter that is invalid
3. Click "check config" in the developer tools. No errors with be found
4. Restart ha. Core will error out upon trying to load up the module.

### What version of Home Assistant Core has the issue?

2023.3.6

### In which browser are you experiencing the issue with?

Google Chrome Version 111.0.5563.111 

### Which operating system are you using to run this browser?

Windows 11 Version 10.0.22621 version 22621

### Javascript errors shown in your browser console/inspector

```txt
2023-03-29 00:19:56.111 ERROR (MainThread) [homeassistant.auth.mfa_modules] Unable to load mfa module notify2: No module named 'homeassistant.auth.mfa_modules.notify2'
2023-03-29 00:19:56.117 ERROR (MainThread) [homeassistant.bootstrap] Home Assistant core failed to initialize. Further initialization aborted
2023-03-29 00:19:56.118 WARNING (MainThread) [homeassistant.bootstrap] Unable to set up core integrations. Activating safe mode
```

### Additional information

Example YAML that caused the issue
```
homeassistant:  
  auth_mfa_modules:
    - type: notify
      message: "2FA Code: {}"
      include:
        - mobile_app_galaxy_s23
    - type: notify2
      message: "2FA Code: {}"
      include:
        - mobile_app_pixel_2
    - type: totp
      name: "Authenticator App"
```
