### ISSUE TITLE
Hold Action is basically unusable and very unreliable with touch input

### ISSUE THREAD

**Issue by iloveicedgreentea** [home-assistant/frontend#15984]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using hold_action for anything is unreliable. 

1. Sometimes holding down will just fail. No reason. It will just act as a tap even though the large white circle appeared to indicate a successful hold
2. Sometimes the white circle will not appear for a correct hold input
3. Sometimes it will appear and then quickly disappear even though finger is held at constant pressure
4. Sometimes the entire hold action will appear to execute correctly but then register as a tap anyway

I have tried this on various devices ranging from an iphone 8 to a 14 pro, android, ipad, tablet, etc. Hold actions with a touch input is just simply unusable.

Sure, you can say you are doing it wrong, but a good interface *does not let you do the wrong thing*. You are doing it wrong is not valid criticism. 

### Describe the behavior you expected

I expect when I hold down the action, it will register as a hold 100% of the time

### Steps to reproduce the issue

1. create any hold_action on a button
2. use a touch input device 
3. try to trigger the hold action reliably, under various conditions, with different people
4. Observe unpredictable failures and frustration with users

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

safari, chrome, ff, all latest

### Which operating system are you using to run this browser?

ios 14-16, android 11

### Problem-relevant frontend configuration

```yaml
- type: custom:button-card
            entity: media_player.source
            name: Music Control
            tap_action: some action here
            hold_action:
              action: call-service
              service: script.scriptname
            template:
              - something
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```
