### ISSUE TITLE
0b3. Left Hand Menu is Transparent.

### ISSUE THREAD

**Issue by Kertz1954** [home-assistant/frontend#16009]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

0b3. Left Hand Menu is Transparent.

Options are still clickable.

Dashboard card base is horizontal-stack.

### Describe the behavior you expected

Expecting Left Hand Menu not to be transparent

### Steps to reproduce the issue

1. Click on top left hand hamburger menu option.
...

### What version of Home Assistant Core has the issue?

2023.4.0b3

### What was the last working version of Home Assistant Core?

2023.3.6

### In which browser are you experiencing the issue with?

Opera & Google Chrome

### Which operating system are you using to run this browser?

Linux Mint

### Problem-relevant frontend configuration

```yaml
type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - type: conditional
        conditions:
          - entity: input_text.display_toggle
            state: home
        card:
          type: horizontal-stack
          cards:
            - type: vertical-stack
              cards:
                - type: markdown
```

### Additional information

![left_hand_menu_is_transparent](https://user-images.githubusercontent.com/67558244/229270902-508c4819-ee3a-44c6-8ec4-525c37ccb7b6.png)
