### ISSUE TITLE
0b3. Left Hand Menu is Chopped.

### ISSUE THREAD

**Issue by Kertz1954** [home-assistant/frontend#16010]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

0b3. Left Hand Menu is Chopped.

Visible menu options are still clickable.

Dashboard card base is horizontal-stack, vertical-stack & webpage (iframe).

### Describe the behavior you expected

Full menu

### Steps to reproduce the issue

1. Click on top left hamburger option.
...

### What version of Home Assistant Core has the issue?

2023.4.0b3

### What was the last working version of Home Assistant Core?

2023.3.6

### In which browser are you experiencing the issue with?

Opera & Google Chrome

### Which operating system are you using to run this browser?

Linux Mint

### Problem-relevant frontend configuration

```yaml
type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - show_state: false
                    show_name: false
                    camera_view: live
                    type: picture-entity
                    entity: camera.buienradar
                    tap_action:
                      action: url
                      url_path: https://www.buienradar.nl/weer/kortenhoef/nl/2752409
                    hold_action:
                      action: url
                      url_path: https://www.buienradar.nl/
                    aspect_ratio: 100%
                    card_mod:
                      style: |
                        ha-card 
                        {
                          border-top: 1px solid #73AD21;
                          border-left: 1px solid #73AD21;
                          border-right: 1px solid #73AD21;
                          border-bottom: 1px solid #73AD21;
                          border-radius: 20px 20px 20px 20px; 
                          margin-top: 9px;
                          margin-left: 10px!important;
                          margin-right: 0px;
                          margin-bottom: 0px;
                          height: 387px!important;
                          padding: 5px;
                          padding-top: 30px;
                          width: 365px!important;
                        }
          - type: vertical-stack
            cards:
              - type: iframe
                url: /local/html/neerslag/neerslag_v2.html
                aspect_ratio: 100%
                card_mod:
                  style: |
                    ha-card 
                    {
                      background-color: black;
                      height: 400px!important;
                      margin-right: 0px;
                      width: 723px!important;
                      margin-left: -120px!important;
                    }
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: markdown
                    content: >-
                      <center><table width="50%"> <tr><td><font
                      color='#008ffb'>{{states("sensor.schiphol_station_naam")
                      }}</font></td><td><img src="{{
                      state_attr("sensor.br_schiphol_symbol","entity_picture")
                      }}" alt="image n/a" width="40"
                      ></td></tr></table></center><br> <table width="100%">
                      <tr><td width="10%"> <font color=white size=4><ha-icon
                      icon="mdi:arrow-down"></ha-icon></font><br></td><td
                      width="70%">Neerslag 1 uur<br>  </td><td width="20%">
                      {{states("sensor.br_schiphol_precipitation")}}mm
                      <br></td></tr> <tr><td> <font color=white size=4><ha-icon
                      icon="mdi:weather-rainy"></ha-icon></font><br></td><td>
                      Regenval afgelopen 24 u<br>  </td><td>
                      {{states("sensor.br_schiphol_rain_last_24h")}}mm
                      <br></td></tr><tr><td>  <font color=white size=4><ha-icon
                      icon="mdi:weather-rainy"></ha-icon></font><br>
                      </td><td>Regenval afgelopen uur<br>  </td><td>
                      {{states("sensor.br_schiphol_rain_last_hour")}}mm
                      </td></tr></table><br>  <center><table width="50%">
                      <tr><td><font
                      color='#feb019'>{{states("sensor.de_bilt_station_naam")
                      }}</font></td><td><img src="{{
                      state_attr("sensor.br_de_bilt_symbol","entity_picture")
                      }}" alt="image n/a" width="40"
                      ></td></tr></table></center><br> <table width="100%">
                      <tr><td width="10%"> <font color=white size=4><ha-icon
                      icon="mdi:arrow-down"></ha-icon></font><br></td><td
                      width="70%">Neerslag 1 uur<br>  </td><td width="20%">
                      {{states("sensor.br_de_bilt_precipitation")}}mm
                      <br></td></tr> <tr><td> <font color=white size=4><ha-icon
                      icon="mdi:weather-rainy"></ha-icon></font><br></td><td>
                      Regenval afgelopen 24 u<br>  </td><td>
                      {{states("sensor.br_de_bilt_rain_last_24h")}}mm
                      <br></td></tr><tr><td>  <font color=white size=4><ha-icon
                      icon="mdi:weather-rainy"></ha-icon></font><br>
                      </td><td>Regenval afgelopen uur<br>  </td><td>
                      {{states("sensor.br_de_bilt_rain_last_hour")}}mm
                      </td></tr></table>  
                    card_mod:
                      style: |
                        ha-card 
                        {
                          background-color: black;
                          box-shadow: 0px 0px;

                          height: 387px!important;

                          border-top: 1px solid #73AD21;
                          border-left: 1px solid #73AD21;
                          border-right: 1px solid #73AD21;
                          border-bottom: 1px solid #73AD21;
                          border-radius: 20px 20px 20px 20px; 

                          margin-top: 9px;
                          margin-left: 109px!important;
                          margin-bottom: 0px;
                          margin-right: 0px;
                          color: white;
                          width: 369px!important;
                        }
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: iframe
                    url: /local/html/neerslag/neerslag_schiphol.html
                    aspect_ratio: 100%
                    card_mod:
                      style: |
                        ha-card 
                        {
                          background-color: transparent;

                          border-top: 1px solid #73AD21;
                          border-left: 1px solid #73AD21;
                          border-right: 1px solid #73AD21;
                          border-bottom: 1px solid #73AD21;
                          border-radius: 20px 20px 20px 20px;

                          text-align: center; 

                          color: white;

                          z-index: 100;

                          margin-top: -10px;
                          margin-left: 10px;
                          margin-right: 0px;
                          padding-bottom: 0px;

                          height: 255px!important;
                        }      
              - type: vertical-stack
                cards:
                  - type: iframe
                    url: /local/html/neerslag/neerslag_kortenhoef.html
                    aspect_ratio: 100%
                    card_mod:
                      style: |
                        ha-card 
                        {
                          background-color: transparent;

                          border-top: 1px solid #73AD21;
                          border-left: 1px solid #73AD21;
                          border-right: 1px solid #73AD21;
                          border-bottom: 1px solid #73AD21;
                          border-radius: 20px 20px 20px 20px;

                          text-align: center; 

                          color: white;

                          z-index: 100;

                          margin-top: -10px;
                          margin-left: 0px;
                          margin-right: 0px;
                          padding-bottom: 0px;

                          height: 255px!important;
                        }      
              - type: vertical-stack
                cards:
                  - type: iframe
                    url: /local/html/neerslag/neerslag_de_bilt.html
                    aspect_ratio: 100%
                    card_mod:
                      style: |
                        ha-card 
                        {
                          background-color: transparent;

                          border-top: 1px solid #73AD21;
                          border-left: 1px solid #73AD21;
                          border-right: 1px solid #73AD21;
                          border-bottom: 1px solid #73AD21;
                          border-radius: 20px 20px 20px 20px;

                          text-align: center; 

                          color: white;

                          z-index: 100;

                          margin-top: -10px;
                          margin-left: 0px;
                          margin-right: 10px;
                          padding-bottom: 0px;

                          height: 255px!important;
                        }
```

### Additional information

![Left_Hand_Menu_Chopped](https://user-images.githubusercontent.com/67558244/229271653-a74162de-b967-44a2-908f-956935b6ae86.png)
