### ISSUE TITLE
"Unable to edit zone" error message should link to relevant documentation

### ISSUE THREAD

**Issue by unikitty37** [home-assistant/frontend#16052]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to edit my location in the Zones screen, I see this:

![image](https://user-images.githubusercontent.com/139183/229756611-3164df65-0dcc-45c2-b574-a8a684e9b220.png)

Clicking the icon produces this error:

![image](https://user-images.githubusercontent.com/139183/229756676-e2f13ec4-0086-4229-a900-4298b91cb74b.png)

### Describe the behavior you expected

The edit icon should not have a line through it, and when I click on the edit icon, the editor should appear, not an error message. Editing the home location should cause it to be saved without complaint.

### Steps to reproduce the issue

* Save the following as `.storage/core.config` (actual home location has been redacted :)

```json
{
  "version": 1,
  "minor_version": 3,
  "key": "core.config",
  "data": {
    "latitude": 41.94791422117861,
    "longitude": -87.65582857470476,
    "elevation": 3,
    "unit_system": "metric",
    "location_name": "Home",
    "time_zone": "Europe/London",
    "external_url": null,
    "internal_url": null,
    "currency": "GBP",
    "unit_system_v2": "metric",
    "language": "en-GB"
  }
}
```

* Start Home Assistant
* Click on Map
* Click on the edit icon

### What version of Home Assistant Core has the issue?

2023.3.6

### In which browser are you experiencing the issue with?

5.7.2921.63 (Stable channel) (arm64) 

### Which operating system are you using to run this browser?

macOS 12.6.3 (21G419)

### Problem-relevant frontend configuration

```yaml
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  external_url: https://REDACTED
  country: GB

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.10.10

# Text to speech
tts:
  - platform: google_translate

# Workdays
binary_sensor:
  - platform: workday
    country: GB
    province: England
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2019-12-23"
      - "2019-12-24"
      - "2019-12-27"
      - "2019-12-30"
      - "2019-12-31"
```

### Javascript errors shown in your browser console/inspector

```txt
None.
```

### Additional information

This HA config has been around for a time — and the zones used to be set in configuration.yaml, as HA is claiming. But they're not there now:

```yaml
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  external_url: https://REDACTED
  country: GB

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.10.10

# Text to speech
tts:
  - platform: google_translate

# Workdays
binary_sensor:
  - platform: workday
    country: GB
    province: England
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2019-12-23"
      - "2019-12-24"
      - "2019-12-27"
      - "2019-12-30"
      - "2019-12-31"
```

…and I have tried restarting HA, rebooting HA — I'm fairly sure the power's even been cycled at some point since I've made the change.

Is there something in the database that might be causing this? When I try to open it in Base, I get a message saying that the file is either encrypted or not a database, so I can't investigate for myself.

Renaming `.storage/core_config` and restarting HA just moves my location to 0,0 but does not make it editable. #4786 implies it should be…
