### ISSUE TITLE
Panel (1 card) layout renders Map and Webpage card collapsed

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#16054]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

 Map and Webpage cards are rendered collapses in views with "Panel (1 card)" layout.

### Describe the behavior you expected

Card is stretched to available screen height and width.

### Steps to reproduce the issue

1. Create view with "Panel (1 card)" layout
2. Add Map or Webpage card
...

### What version of Home Assistant Core has the issue?

core-2023.4.0b6

### What was the last working version of Home Assistant Core?

core-2023.3.6

### In which browser are you experiencing the issue with?

Google Chrome, Mozilla Firefox, Companion App

### Which operating system are you using to run this browser?

Windows 10, Android 11

### State of relevant entities

```txt
---
```

### Problem-relevant frontend configuration

```yaml
views:
  - theme: Backend-selected
    title: map test
    type: panel
    badges: []
    cards:
      - type: map
        entities:
          - zone.home
```

### Javascript errors shown in your browser console/inspector

```txt
---
```

### Additional information

[collapsed_map_card_on_panel_layout.png](https://user-images.githubusercontent.com/570575/229766076-6ecc663f-6c72-4d8e-8079-acbd86fa9d50.png)
