### ISSUE TITLE
Select selector with multiple true clears input every few seconds

### ISSUE THREAD

**Issue by SgtBatten** [home-assistant/frontend#16078]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I maintain a notification blueprint for the community. I have over the past few months expanded the functionality and added many more options and inputs. 

Some of these inputs are select selectors with both multiple and custom value set to true. 
With this configuration, entering valid freetext into the input field in the automation UI is hampered by the input field clearing text every few seconds. You either have to type and hit enter extremely quickly, or edit the automation in yaml mode to be successful. 

I have also noted that select selectors with multiple true but custom value false clear, but save a null entry unexpectedly. 

### Describe the behavior you expected

The user to have unlimited time to enter the text before hitting enter to save it as a list item.

A null entry to not be saved when this occurs and multiple is true and custom value is false. 

### Steps to reproduce the issue

1. create a blueprint with a select selector input
2. configure multiple and custom_value to true
3. reload automations in developer tools 
4. Create a new automation using the blueprint
5. try to type something in the input field and observe it be deleted after a few seconds
...

I have created a simple blueprint to test for you

```
blueprint:
  domain: automation
  name: Faulty Select Selectors
  input:
    faulty_selector:
      name: Faulty Input
      description: Try to type something else here and wait a few seconds to see it disappear
      selector:
        select:
          options:
            - try
            - to
            - type
            - something
            - else
            - here
          multiple: true
          custom_value: true
    faulty_selector_2:
      name: Faulty Input 2
      description: Try to type something else here and wait a few seconds to see it disappear. A null entry will be saved incorrectly though.
      selector:
        select:
          options:
            - try
            - to
            - type
            - something
            - else
            - here
          multiple: true
trigger: []
action: []

```
![image](https://user-images.githubusercontent.com/24822223/230261583-61bb4662-3744-4f7f-9264-b51e6f8d7557.png)

### What version of Home Assistant Core has the issue?

2022.3.x

### What was the last working version of Home Assistant Core?

None tested

### In which browser are you experiencing the issue with?

Chrome, Edge, Brave, multiple devices, multiple networks.

### Which operating system are you using to run this browser?

Windows, Android
