### ISSUE TITLE
Button card not showing in 2023.4.3

### ISSUE THREAD

**Issue by Eupeodes** [home-assistant/frontend#16155]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to 2023.4.3 by button cards are no longer displayed.

### Describe the behavior you expected

Button cards displaying

### Steps to reproduce the issue

- open a dashboard containing buttons, buttons are not displayed
- Also buttons are not displayed in the edit mode

### What version of Home Assistant Core has the issue?

2023.4.3

### What was the last working version of Home Assistant Core?

2023.4.2

### In which browser are you experiencing the issue with?

Microsoft Edge Version 112.0.1722.39 (Official build) (64-bit) / iOS app 2023.4

### Which operating system are you using to run this browser?

Windows 11 Enterprise 22H2 / iOS 16.4.1

### Problem-relevant frontend configuration

```yaml
show_name: true
show_icon: true
show_state: false
type: button
tap_action:
  action: call-service
  service: rest_command.recreate_ha
  target: {}
  confirmation:
    text: Recreate docker container?
icon: mdi:restart
name: Recreate HA
hold_action:
  action: none
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

None of the buttons in my dashboards are working. I am using the docker container from ghcr.io/home-assistant/home-assistant:latest. When I revert to 2023.4.2 the buttons do work.
