### ISSUE TITLE
Entities card borders are not where they should be

### ISSUE THREAD

**Issue by makhlouta** [home-assistant/frontend#16157]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the upgrade to 2023.4.0 (I think), one of my pages is not displaying correctly on any device. I have two entity cards in a horizontal stack. 26 entities in each card, but the border is wrapping the card at the 13th

### Describe the behavior you expected

border to wrap all entities

### Steps to reproduce the issue

please refer to https://community.home-assistant.io/t/entities-card-borders-are-not-where-they-should-be/558913

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.3

### What was the last working version of Home Assistant Core?

Home Assistant 2023.3.x

### In which browser are you experiencing the issue with?

Firefox, Edge, iOS app, Android App

### Which operating system are you using to run this browser?

Windows, iOS, Android

**Comment by makhlouta** [comment]
This is still an issue after updating to 2023.4.4. But now the border ends at the 20th out of 26 instead of 13th out of 26

**Comment by ildar170975** [comment]
Confirm, the bug is still there:
![image](https://user-images.githubusercontent.com/71872483/232132052-ccde7472-4190-4f3a-8683-713a2c396986.png)
```
type: horizontal-stack
cards:
  - type: entities
    entities:
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
  - type: entities
    entities:
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
      - sun.sun
```
