### ISSUE TITLE
Some items in vertical stack missing on frontend after upgrading to 2023.4.3

### ISSUE THREAD

**Issue by oopiicaa** [home-assistant/frontend#16158]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have multiple vertical stacks on my home dashboard on HA frontend. After upgrading to 2023.4.3 from 2023.4.2, three rows are missing in one vertical stack (look at Lights section in attached screenshots). If I delete cache in my browser and login to HA again, I can see missing items, but only until I hit F5 - then the items disappear again. The same behaviour is in Mozilla Firefox, Google Chrome and also on Home Assistant app for Android.
I have a "copy" of these cards in another tab, just that they're not in vertical stack (but one horizontal stack and one button) and they do not disappear from there.
Since it's working in 2023.4.2 and not in 2023.4.3, I'm guessing it has something to do with https://github.com/home-assistant/frontend/releases/tag/20230411.0

### Describe the behavior you expected

No items should disappear.

### Steps to reproduce the issue

1. Upgrade to 2023.4.3
2. Login to your HA instance
3. Hit F5 in your browser > some items are missing after reload
4. Clear the cache of your browser
5. Login again to your HA instance
6. All items are visible
7. Hit F5 in your browser > some items are missing again after reload
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.3

### What was the last working version of Home Assistant Core?

Home Assistant 2023.4.2

### In which browser are you experiencing the issue with?

Mozilla Firefox 111.0.1 (64-bit), Google Chrome version 112.0.5615.86 (64-bit)

### Which operating system are you using to run this browser?

Windows 10 x64

### Problem-relevant frontend configuration

```yaml
title: Lights
cards:
  - entity: group.luci_vse
    hold_action:
      action: more-info
    icon: mdi:home-lightbulb
    icon_height: 50px
    name: all lights
    show_icon: true
    show_name: false
    tap_action:
      action: toggle
    type: entity-button
  - cards:
      - cards:
          - entity: group.dnevna
            hold_action:
              action: more-info
            icon: mdi:sofa
            icon_height: 60px
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            type: entity-button
          - entity: group.kuhinja
            hold_action:
              action: more-info
            icon: mdi:fridge
            icon_height: 60px
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            type: entity-button
          - entity: group.spalnica
            hold_action:
              action: more-info
            icon: mdi:bed
            icon_height: 60px
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            type: entity-button
          - entity: group.shramba
            hold_action:
              action: more-info
            icon: mdi:locker-multiple
            icon_height: 60px
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            type: entity-button
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.bathroom_lights
            icon_height: 60px
            icon: mdi:shower-head
          - entity: group.wc
            hold_action:
              action: more-info
            icon: mdi:toilet
            icon_height: 60px
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            type: entity-button
          - entity: group.hodnik
            hold_action:
              action: more-info
            icon: mdi:door
            icon_height: 60px
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            type: entity-button
          - entity: group.balkon
            hold_action:
              action: more-info
            icon: mdi:outdoor-lamp
            icon_height: 60px
            show_icon: true
            show_name: false
            tap_action:
              action: toggle
            type: entity-button
        type: horizontal-stack
    type: horizontal-stack
  - entity: switch.vacation_mode_toggle
    hold_action:
      action: more-info
    icon: mdi:home-export-outline
    show_icon: true
    show_name: false
    tap_action:
      action: toggle
    type: button
    show_state: false
    icon_height: 30px
  - type: vertical-stack
    title: Vacuum
    cards:
      - type: custom:vacuum-card
        entity: vacuum.dreame_mc1808_121e_robot_cleaner
        image: default
        compact_view: true
  - type: vertical-stack
    title: Presence
    cards:
      - show_name: true
        show_icon: true
        show_state: true
        type: glance
        entities:
          - entity: device_tracker.xiaomi_12_3
          - entity: device_tracker.xiaomi_natasa
          - entity: device_tracker.golf
          - entity: device_tracker.formentor
          - entity: device_tracker.keys
      - type: picture-elements
        elements:
          - type: state-icon
            entity: sensor.redacted_combustion_range
            icon: mdi:gas-station
            style:
              top: 11%
              left: 11%
              width: 10%
          - type: state-label
            entity: sensor.redacted_combustion_range
            style:
              top: 21%
              left: 10%
          - type: state-icon
            entity: sensor.redacted_fuel_level
            style:
              top: 33%
              left: 11%
              width: 10%
          - type: state-label
            entity: sensor.redacted_fuel_level
            style:
              top: 42.7%
              left: 10%
          - type: state-icon
            entity: binary_sensor.redacted_doors_locked
            style:
              top: 55%
              left: 11%
              width: 10%
          - type: state-label
            entity: binary_sensor.redacted_doors_locked
            style:
              top: 64.3%
              left: 10%
          - type: state-icon
            entity: binary_sensor.redacted_windows_closed
            icon: mdi:car-door
            style:
              top: 77%
              left: 11%
              width: 10%
          - type: state-label
            entity: binary_sensor.redacted_windows_closed
            style:
              top: 86%
              left: 10%
          - type: state-icon
            entity: sensor.redacted_odometer
            style:
              top: 11%
              left: 51%
              width: 10%
          - type: state-label
            entity: sensor.redacted_odometer
            style:
              top: 21%
              left: 45.7%
              width: 10%
          - type: state-icon
            entity: sensor.redacted_oil_inspection_days
            style:
              top: 11%
              left: 31%
              width: 10%
          - type: state-label
            entity: sensor.redacted_oil_inspection_days
            style:
              top: 29%
              left: 27.5%
              width: 10%
          - type: state-label
            entity: sensor.redacted_oil_inspection_distance
            style:
              top: 21%
              left: 26.3%
              width: 10%
          - type: state-icon
            entity: device_tracker.formentor
            icon: mdi:map-marker-radius
            state_color: false
            style:
              top: 11%
              left: 71%
              width: 10%
          - type: state-label
            entity: device_tracker.formentor
            style:
              top: 21%
              left: 69.3%
              width: 10%
        image: /local/formentor_medium2.png
type: vertical-stack
```

### Additional information

Lights section shown:
![vertical_stack_shown_1](https://user-images.githubusercontent.com/24246157/231685775-834d5cd7-90a7-4023-b23f-3485b6f1ec0a.PNG)

Lights section missing:
![vertical_stack_missing_1](https://user-images.githubusercontent.com/24246157/231685781-3a6a00f3-9ccd-4727-a4fb-a68ff57c73cd.PNG)
