### ISSUE TITLE
Can't set an empty string when blueprint input has a default

### ISSUE THREAD

**Issue by SgtBatten** [home-assistant/frontend#16195]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a blueprint input has a default text value it is impossible to set the string to empty in the automation UI. It is possible if you change to editing in yaml mode.

When deleting the existing or default text in the input field, as soon as the field becomes empty the default value is placed in the text box once again. 

Even if you don't want an empty string but just to change the text, many people will delete the existing text first before typing something new, but this bug means you can never delete the text. Instead you must highlight the text and type over it, or edit in yaml. 

### Describe the behavior you expected

When the text is deleted, it should stay empty.

### Steps to reproduce the issue

1. Create a blueprint with a simple input which has a default value. 
2. Try to delete the text 
...

I have created a simple blueprint to test for you
```
blueprint:
  domain: automation
  name: Faulty Input demo
  input:
    faulty_input:
      name: Faulty Input
      description: hold down backspace and you will never delete this text
      default: "Delete me if you can"
trigger: []      
action: []
```

### What version of Home Assistant Core has the issue?

2022.4.x

### What was the last working version of Home Assistant Core?

None tested

### In which browser are you experiencing the issue with?

Chrome, Edge, Brave, multiple devices, multiple networks.

### Which operating system are you using to run this browser?

Windows, Android
