### ISSUE TITLE
Subview 'back' arrow incorrectly acts as 'go back one step'

### ISSUE THREAD

**Issue by dexonter** [home-assistant/frontend#16194]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a subview with a single webpage card and if I click 3 links in the webpage - it takes me 4 clicks on the 'back' arrow at the top to go back to the dashboard from which I came. If I click 7 times on the webpage, it takes me 8 times, etc.

In essence, the back arrow in the subview acts as the back arrow in my browser. 

Apparently this happens also with other cards - it's just that on a webpage card is easy to see what changes when you click the arrow.

### Describe the behavior you expected

I expect, that whatever I do in the subview, and however many clicks I perform - when I click the 'back' arrow at the top of the subview I am taken back to the dashboard from which I came. Logically, that's what I would expect from the UX. If I want to go one step back I would simply use the browser back button.

### Steps to reproduce the issue

1. Create a subview where you have click and interact more than just seeing some data; e.g. a webpage card
2. Link the subview to a dashboard
3. Click on the dashboard to take you to the subview
4. Perform multiple clicks, go to different parts, access different links etc. in the subview
5. Notice how it takes a proportinal amount of clicks on the 'back' arrow at the top of the subview to take you back to the dashboard you came from
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.4; Supervisor 2023.04.0; Operating System 9.5; Frontend 20230411.1 - latest

### In which browser are you experiencing the issue with?

Google Chrome 112.0.5615.87; MS Edge 112.0.1722.46

### Which operating system are you using to run this browser?

Windows 11 Pro 22H2

### Problem-relevant frontend configuration

```yaml
Dashboard link to subview:

camera_view: auto
type: picture-glance
title: Recipe Book
image: https://demo.home-assistant.io/stub_config/kitchen.png
entities: []
tap_action:
  action: navigate
  navigation_path: /lovelace/mealie

Subview card (/lovelace/mealie)

type: iframe
url: http://10.0.0.17:3000
aspect_ratio: 100%
```
