### ISSUE TITLE
Issue with dropdowns in blueprint, and some other quirks. 

### ISSUE THREAD

**Issue by SgtBatten** [home-assistant/frontend#16207]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There are several issue with blueprint I out fields. 

In this issue I'm addressing 2 things. 

Firstly, inputs with dropdowns with a default value are added to the automation yaml (one input per time the automation is in edit mode)
(I believe only when custom value and multiple are false)

The example blueprint below will help explain, but if you open the automation, the bottom most input with the relevant configuration will be added to the yaml prompting you to save it despite not having edited anything. If you save it, then exit and return to the automation again, the next lowest input will be added to the yaml prompting you to save again. This keeps happening until all inputs (that have the issue ) are added to he yaml. 

The second issue is also demonstrated in the blueprint below. Some inputs simply are broken and do not provide an input field.

### Describe the behavior you expected

1. The automation yaml is not filled with default inputs one by one. I prefer default inputs stay out of the yaml until edited.
2.  All input fields are rendered and accessible. 

### Steps to reproduce the issue

1. Create blueprint with a dropdown input and a default set. 
2. Create a new automation using the blueprint. 
3. Observe the yaml already contains the lowest input .
4. Save and open again to observe the yaml now contains the second lowest input. 

Here is a test blueprint to demonstrate. 

```
blueprint:
  domain: automation
  description: Open the automation and you will see that a new input is saved to the yaml without you doing anything. This is repeatable for more inputs
  name: Faulty Inputs
  input:
    faulty_input_1:
      name: Faulty Input 1
      description: 4 options
      default: these
      selector:
        select:
          options:
            - these
            - are
            - some
            - options
    faulty_input_1_dropdown:
      name: Faulty Input 1 with dropdown
      description: 4 options, dropdown true
      default: options
      selector:
        select:
          options:
            - these
            - are
            - some
            - options
          mode: dropdown
    faulty_input_2:
      name: Faulty Input 2
      description: 4 options with multiple true
      default: these
      selector:
        select:
          options:
            - these
            - are
            - some
            - options
          multiple: true
    faulty_input_3:
      name: Faulty Input 3
      description: 4 options, custom true
      default: are
      selector:
        select:
          options:
            - these
            - are
            - some
            - options
          custom_value: true
    faulty_input_4:
      name: Faulty Input 4
      description: 4 options, multiple true, custom true. Something is broken > no selector appears
      default: some
      selector:
        select:
          options:
            - these
            - are
            - some
            - options
          multiple: true
          custom_value: true
    faulty_input_5:
      name: Faulty Input 5
      description: 7 options
      default: dropdown
      selector:
        select:
          options:
            - these
            - are
            - some
            - options
            - that
            - force
            - a
            - dropdown
    faulty_input_6:
      name: Faulty Input 6
      description: 7 options, something broken, no selector appears 
      default: options
      selector:
        select:
          options:
            - these
            - are
            - some
            - options
            - that
            - force
            - a
            - dropdown
          multiple: true
    faulty_input_7:
      name: Faulty Input 7
      description: 7 options, custom true
      default: options
      selector:
        select:
          options:
            - these
            - are
            - some
            - options
            - that
            - force
            - a
            - dropdown
          custom_value: true
    faulty_input_8:
      name: Faulty Input 8
      description: 4 options labelled
      default: labels
      selector:
        select:
          options:
            - label: These
              value: these
            - label: Are
              value: are
            - label: Some
              value: some
            - label: Labels
              value: labels
    faulty_input_8_dropdown:
      name: Faulty Input 8 - dropdown
      description: 4 options labelled, dropdown
      default: some
      selector:
        select:
          options:
            - label: These
              value: these
            - label: Are
              value: are
            - label: Some
              value: some
            - label: Labels
              value: labels
          mode: dropdown
    faulty_input_9:
      name: Faulty Input 9
      description: 7 options labelled,  multiple false
      default: force
      selector:
        select:
          options:
            - label: These
              value: these
            - label: Are
              value: are
            - label: Some
              value: some
            - label: Labels
              value: labels
            - label: That
              value: that
            - label: Force
              value: force
            - label: A
              value: a
            - label: Dropdown
              value: dropdown
trigger: []
action: []

```

### What version of Home Assistant Core has the issue?

2022.4.x

### What was the last working version of Home Assistant Core?

None tested

### In which browser are you experiencing the issue with?

Chrome, Edge, Brave, multiple devices, multiple networks.

### Which operating system are you using to run this browser?

Windows, Android
