### ISSUE TITLE
Card borders aren't updated on the dashboard based on entity state change

### ISSUE THREAD

**Issue by boardlord1** [home-assistant/frontend#16205]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've used the Mini Graph Card custom card to displace temps in my rooms. I've also used card-mod to make the borders of these cards red if the heating is on in them. Before 2023.4, these worked beautifully.

Now with 2023.4 if the heating comes on, the red border often doesn't show up. Multiple page refreshes, cache clearings later I could usually make it appear, but not always.

Example:
![image](https://user-images.githubusercontent.com/8179205/232344956-76628595-0582-437c-a503-e0779b0e0cb7.png)

My card-mod css code works for sure, as it used to work, and if I edit the card, the preview shows the red border
Example:
![image](https://user-images.githubusercontent.com/8179205/232344989-3e6717d0-05c3-4852-8e80-093e515612c9.png)

But if I close the preview, nothing changes. If I change the code, save, change it back to how it was and save again, the red border shows up on the dashboard 

The situation is the same with the Android companion, only after multiple force closes can I make the borders appear. After this it works for the next few changes, then I've reload/force close again to make it update the dashboard.

### Describe the behavior you expected

The red border as prescribed by card-mod should show up whenever heating is active in a given room - so update the card on the dashboard whenever there's a change.

### Steps to reproduce the issue

1. Create a card, add card-mod css code to it to draw a border based on another entities condition
2. My code:
```
type: custom:mini-graph-card
name: Foyer
entities:
  - entity: sensor.average_mi_foyer_temperature
line_color: chartreuse
card_mod:
  style: |
    ha-card {
      {% if is_state('input_boolean.foyer_temp_vs_heating_set_point', 'off') %}
        background: ;
      {% else %}
        border: solid 3px red;
      {% endif %}
      }
```
4.
...

### What version of Home Assistant Core has the issue?

2023.4.4

### What was the last working version of Home Assistant Core?

2023.3.6

### In which browser are you experiencing the issue with?

Google Chrome 111.0.5563.149, Firefox 112

### Which operating system are you using to run this browser?

Windows 10 19045.2846

### Problem-relevant frontend configuration

```yaml
type: custom:mini-graph-card
name: Foyer
entities:
  - entity: sensor.average_mi_foyer_temperature
line_color: chartreuse
card_mod:
  style: |
    ha-card {
      {% if is_state('input_boolean.foyer_temp_vs_heating_set_point', 'off') %}
        background: ;
      {% else %}
        border: solid 3px red;
      {% endif %}
      }
```
