### ISSUE TITLE
Blueprints respect markdown in input descriptions for automations, but not scripts

### ISSUE THREAD

**Issue by mdolnik** [home-assistant/frontend#16222]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating blueprint yml files you are able to utilize markdown in the blueprint / input descriptions.

It seems as if markdown doesn't work in input descriptions when the automation is configured as a script:

- ✔Blueprint: Automation: Main Description
- ✔Blueprint: Automation: Input Description
- ✔Blueprint: Script: Main Description
- ❌Blueprint: Script: Input Description

### Describe the behavior you expected

Script Blueprint input descriptions should support markdown the same as Automation Blueprints.

### Steps to reproduce the issue

Take the following Automation Blueprint
```yml
blueprint:
  domain: automation
  name: Test Blueprint Automation
  description: '# Heading 1

    ## Heading 2

    ### Heading 3

    #### Heading 4

    - List 1

    - List 2

    - List 3


    1. Number 1

    1. Number 2

    1. Number 3


    *Some Bold*

    _Some Italic_

    [A link](www.example.com)
  '
  input:
    my_text:
      name: My Textbox
      description: '# Heading 1

        ## Heading 2

        ### Heading 3

        #### Heading 4

        - List 1

        - List 2

        - List 3


        1. Number 1

        1. Number 2

        1. Number 3


        *Some Bold*

        _Some Italic_

        [A link](www.example.com)
      '
      selector:
        text:
```
It will appear like this:
![2023-04-17_20h51_26](https://user-images.githubusercontent.com/22206300/232666731-2f02f6fc-90a0-4519-9051-e4d50b99db96.png)

But if you take the exact same `yml` above and change `domain` to `script` (and place it in `blueprints/scripts`) then the Script Blueprint UI will look like this:
![2023-04-17_20h51_35](https://user-images.githubusercontent.com/22206300/232666891-72b61f76-60d2-4eb3-a481-757733b63ca8.png)

### What version of Home Assistant Core has the issue?

2023.4.5

### In which browser are you experiencing the issue with?

Google Chrome 111.0.5563.147

### Which operating system are you using to run this browser?

Windows 10
