### ISSUE TITLE
custom:button-card intermittently fails to show up on dashboards 

### ISSUE THREAD

**Issue by matthyne** [home-assistant/frontend#16322]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since sometime late in 2023.3.x and early 2023.4.x a problem was introduced that intermittently causes lovelace cards that contain custom:button-card to show as empty.

If you click on "edit dashboard" the cards show as blank however you can click on "edit" to see the YAML and the preview.  

The problem is intermittent and can be resolved by reloading or rebooting however the issue will return at a later time. 

This problem seems to be similar to  ticket #16155 however that was resolved in 2023.4.4 and this problem continues to exist in 2023.4.6

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/17772672/234595956-b42a322c-e09e-4d88-aed3-fafbea869d78.png">
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/17772672/234596096-a6b36e90-7f76-4485-b199-3e3c83caedf3.png">

### Describe the behavior you expected

Cards comtaining button-card should be rendered on every presentation of the dashboard.

### Steps to reproduce the issue

1.  Home Assistant 2023.4.x (I am using 2023.4.6) 
2. Install custom button card from HACS
3. Create a button-card card
4. repeatedly reload the dashboard until the problem occurs.
...

### What version of Home Assistant Core has the issue?

2023.4.6

### In which browser are you experiencing the issue with?

Chrome 112.0.5615.137

### Which operating system are you using to run this browser?

MacOS Ventura 13.3.1

### Problem-relevant frontend configuration

```yaml
type: custom:button-card
template: container
color: '#00E730'
name: Television Power
custom_fields:
  buttons:
    card:
      type: horizontal-stack
      cards:
        - type: button
          tap_action:
            action: toggle
          entity: switch.family_tv_pwr
          icon: mdi:television
          name: Family/Living TV
          show_state: false
        - type: button
          tap_action:
            action: toggle
          entity: switch.kitchen_tv_pwr
          icon: mdi:television
          name: Kitchen TV
        - type: button
          tap_action:
            action: toggle
          entity: switch.media_tv_pwr
          name: Media TV
          icon: mdi:television
```
