### ISSUE TITLE
Nest Camera not working with Picture Elements Card

### ISSUE THREAD

**Issue by Waggers58** [home-assistant/frontend#16332]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I find my new Nest Cam (Battery) doesn't display the live view with the Picture Elements Card; this is very annoying because that card is core to my HA Dashboard which is based on a floorplan. 

### Describe the behavior you expected

Like my other cameras, I expected the card to show the live view from the camera;  no image appears on the card.  I assume this is because my Nest Cam uses WebRTC rather than RTSP.

This is the image of my test dashboard:

![Nest Cam error](https://user-images.githubusercontent.com/93612342/234810676-e156df44-95fa-4065-9c5a-570ec3e0f886.jpg)

Incidently, when I click on the blank image a new pop-up opens with the actual display.

### Steps to reproduce the issue

Create a new dashboard with only the Picture Elements Card and configure it to display the Nest Cam.  

### What version of Home Assistant Core has the issue?

2023.4.6

### In which browser are you experiencing the issue with?

Google Chrome Version 112.0.5615.138, also Edge Version 112.0.1722.58

### Which operating system are you using to run this browser?

Windows 11 Build 22621.1555

### State of relevant entities

```txt
camera.front_drive_camera
Front Drive camera
streaming	access_token: 323f1cc640a7b9adb8ec033ca7dd5a471f765b94275759e0d8ecf631c5998d6
model_name: Camera
brand: Google Nest
frontend_stream_type: web_rtc
entity_picture: /api/camera_proxy/camera.front_drive_camera?token=323f1cc640a7b9adb8ec033ca7dd5a471f765b94275759e0d8ecf631c5998d6
friendly_name: Front Drive camera
supported_features: 2
```

### Problem-relevant frontend configuration

```yaml
YAML from test dashboard:

views:
  - title: Home
    cards:
      - type: picture-elements
        elements:
          - type: image
            entity: camera.front_drive_camera
            camera_image: camera.front_drive_camera
            camera_view: live
            style:
              top: 32%
              left: 50%
              width: 40%
        image: https://demo.home-assistant.io/stub_config/floorplan.png
```
