### ISSUE TITLE
Automation Graph unable to render while-true loops

### ISSUE THREAD

**Issue by aph3rson** [home-assistant/frontend#16340]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an automation which contains a while-true loop - in essence, I stop the automation within the loop based on when one of two events occurs. Here's a copy of my automation as it stands:

<details>
  <summary>Automation YAML (click)</summary>

  ```yaml
  alias: Patio Rain Protector
  description: "Sends a notification if rain is forecasted soon to cover up the patio furniture."
  trigger:
    - platform: time
      at: "08:00:00"
  condition: null
  action:
    - alias: Set up variables for the actions
      variables:
        action_toggle: "{{ context.id ~ '_toggle' }}"
        notify_tag: "{{ this.attributes.id ~ '_notify' }}"
        forecast_days: 1
    - alias: Check the lookahead window for possible precipitation
      condition: template
      value_template: >-
        {{ state_attr('weather.apartment', 'forecast')[:forecast_days + 1] |
        selectattr('precipitation') | list | length | bool | default(False) }}
    - alias: Send notification to mobile device
      service: notify.mobile_app_sm_n960u
      data:
        title: Patio rain reminder
        message: |-
          Rain forecasted in the next {{ 24 * (forecast_days + 1) }} hours.
          Remember to cover up the patio furniture!
        data:
          tag: "{{ notify_tag }}"
          sticky: true
          actions:
            - action: "{{ action_toggle }}"
              title: Toggle patio lights
    - repeat:
        while:
          - condition: template
            value_template: "True"
        sequence:
          - alias: Wait for an event from the notification
            wait_for_trigger:
              - platform: event
                event_type: mobile_app_notification_action
                event_data:
                  action: "{{ action_toggle }}"
              - platform: event
                event_type: mobile_app_notification_cleared
                event_data:
                  tag: "{{ notify_tag }}"
          - alias: Perform the desired action
            choose:
              - conditions: >-
                  {{ wait.trigger.event.event_type ==
                  "mobile_app_notification_action" }}
                sequence:
                  - service: light.toggle
                    data: {}
                    target:
                      area_id: 324ffd3c1f6f49b28d487cb6caf00d16
              - conditions: >-
                  {{ wait.trigger.event.event_type ==
                  "mobile_app_notification_cleared" }}
                sequence:
                  - stop: ""
  mode: single
  ```
</details>

However, when I run this automation, I'm unable to view traces in the Automation UI, with the following error:
`Error rendering graph. Please download trace and share with the developers.`

<details>
  <summary>JSON trace (click)</summary>
  
  ```json
  {
    "trace": {
      "last_step": "action/1",
      "run_id": "fbfc95711e90fd9ace35a82553fb0569",
      "state": "stopped",
      "script_execution": "aborted",
      "timestamp": {
        "start": "2023-04-28T04:44:59.704350+00:00",
        "finish": "2023-04-28T04:44:59.768216+00:00"
      },
      "domain": "automation",
      "item_id": "1682655354864",
      "trigger": null,
      "trace": {
        "trigger": [
          {
            "path": "trigger",
            "timestamp": "2023-04-28T04:44:59.705095+00:00",
            "changed_variables": {
              "this": {
                "entity_id": "automation.patio_rain_protector",
                "state": "on",
                "attributes": {
                  "last_triggered": "2023-04-28T04:43:53.017124+00:00",
                  "mode": "single",
                  "current": 0,
                  "id": "1682655354864",
                  "icon": "mdi:weather-rainy",
                  "friendly_name": "Patio Rain Protector"
                },
                "last_changed": "2023-04-28T04:44:51.796569+00:00",
                "last_updated": "2023-04-28T04:44:51.796569+00:00",
                "context": {
                  "id": "01GZ32V86M80MXSVS4AWA694XW",
                  "parent_id": null,
                  "user_id": null
                }
              },
              "trigger": {
                "platform": null
              }
            }
          }
        ],
        "action/0": [
          {
            "path": "action/0",
            "timestamp": "2023-04-28T04:44:59.717766+00:00",
            "changed_variables": {
              "context": {
                "id": "01GZ32VFXRT02DJZ7K6SQWRDXM",
                "parent_id": "01GZ32VFXHWJE9YW8875QF3K50",
                "user_id": null
              }
            }
          }
        ],
        "action/1": [
          {
            "path": "action/1",
            "timestamp": "2023-04-28T04:44:59.721042+00:00",
            "changed_variables": {
              "action_toggle": "01GZ32VFXRT02DJZ7K6SQWRDXM_toggle",
              "notify_tag": "1682655354864_notify",
              "forecast_days": 1
            },
            "result": {
              "result": false,
              "entities": [
                "weather.apartment"
              ]
            }
          }
        ]
      },
      "config": {
        "id": "1682655354864",
        "alias": "Patio Rain Protector",
        "description": "",
        "trigger": [
          {
            "platform": "time",
            "at": "08:00:00"
          }
        ],
        "condition": null,
        "action": [
          {
            "alias": "Set up variables for the actions",
            "variables": {
              "action_toggle": "{{ context.id ~ '_toggle' }}",
              "notify_tag": "{{ this.attributes.id ~ '_notify' }}",
              "forecast_days": 1
            }
          },
          {
            "alias": "Check the lookahead window for possible precipitation",
            "condition": "template",
            "value_template": "{{ state_attr('weather.apartment', 'forecast')[:forecast_days + 1] | selectattr('precipitation') | list | length | bool | default(False) }}"
          },
          {
            "alias": "Send notification to mobile device",
            "service": "notify.mobile_app_sm_n960u",
            "data": {
              "title": "Patio rain reminder",
              "message": "Rain forecasted in the next {{ 24 * (forecast_days + 1) }} hours.\nRemember to cover up the patio furniture!",
              "data": {
                "tag": "{{ notify_tag }}",
                "sticky": true,
                "actions": [
                  {
                    "action": "{{ action_toggle }}",
                    "title": "Toggle patio lights"
                  }
                ]
              }
            }
          },
          {
            "repeat": {
              "while": [
                {
                  "condition": "template",
                  "value_template": "True"
                }
              ],
              "sequence": [
                {
                  "alias": "Wait for an event from the notification",
                  "wait_for_trigger": [
                    {
                      "platform": "event",
                      "event_type": "mobile_app_notification_action",
                      "event_data": {
                        "action": "{{ action_toggle }}"
                      }
                    },
                    {
                      "platform": "event",
                      "event_type": "mobile_app_notification_cleared",
                      "event_data": {
                        "tag": "{{ notify_tag }}"
                      }
                    }
                  ]
                },
                {
                  "alias": "Perform the desired action",
                  "choose": [
                    {
                      "conditions": "{{ wait.trigger.event.event_type == \"mobile_app_notification_action\" }}",
                      "sequence": [
                        {
                          "service": "light.toggle",
                          "data": {},
                          "target": {
                            "area_id": "324ffd3c1f6f49b28d487cb6caf00d16"
                          }
                        }
                      ]
                    },
                    {
                      "conditions": "{{ wait.trigger.event.event_type == \"mobile_app_notification_cleared\" }}",
                      "sequence": [
                        {
                          "stop": ""
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          }
        ],
        "mode": "single"
      },
      "blueprint_inputs": null,
      "context": {
        "id": "01GZ32VFXRT02DJZ7K6SQWRDXM",
        "parent_id": "01GZ32VFXHWJE9YW8875QF3K50",
        "user_id": null
      }
    },
    "logbookEntries": []
  }
  ```
</details>

Instead, all tabs of the Trace view are empty:
![image](https://user-images.githubusercontent.com/838916/235057675-cf0146f4-e861-4fa4-a8a5-c4fd725bf2ef.png)

My best guess is that this is related to the components of the automation (the while loop) rather than events that occur during the automation execution - even if the automation stops prior to the while loop, the trace cannot be rendered.

### Describe the behavior you expected

I expected something in the trace step details, timeline, logbook entries, or config tabs of the Automation Trace view to display debugging content.

### Steps to reproduce the issue

1. Copy the above automation into a HA environment
2. Run the automation (you may need to replace area IDs accordingly, the automation uses one)
3. View the Trace page for the automation

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.5 // Supervisor 2023.04.1 // Operating System 10.0 // Frontend 20230411.1 - latest
_n.b.: I'm updating these as we speak, but I don't think this will be fixed by a core and/or OS update, frontend seems latest._

### What was the last working version of Home Assistant Core?

Unknown, this is a new automation I've written.

### In which browser are you experiencing the issue with?

112.0.5615.121 (Official Build) (64-bit) (cohort: Stable) 
Android app beta-9948-32a79333-full

### Which operating system are you using to run this browser?

Windows 10 // Android

### State of relevant entities

Looks to be captured in trace file.

### Problem-relevant frontend configuration

See above YAML for automation.

### Javascript errors shown in your browser console/inspector

No errors observed.
