### ISSUE TITLE
The more-info page for a climate entity doesn't show the right values when being casted

### ISSUE THREAD

**Issue by chiahsing** [home-assistant/frontend#16410]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In a casted dashboard, he swing mode, fan mode, and temperature of a climate entity in more-info page don't reflect the attributes of the climate entity. When it is changed by touching the screen, the dropdown box would jump back to the previous value after a couple of seconds, even though the attribute is changed. When the attribute is changed by something else, the dashboard also doesn't show the latest value.

The desktop and mobile version works fine. Only the casted version has the issue.

### Describe the behavior you expected

The values (temperature, etc.) should reflect the latest status of the entity

### Steps to reproduce the issue

1. Add a climate card
2. Cast the dashboard to Nest Hub
3. Click three dots of the climate card to bring up the more-info page. Alternatively, an entity card also works.
4. Change the fan mode, swing mode, or temperature in the more-info page.

### What version of Home Assistant Core has the issue?

2023.5.0

### In which browser are you experiencing the issue with?

Google Nest Hub (2nd generation)

### State of relevant entities

```txt
hvac_modes: off, cool, dry, fan_only
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: Auto, Low, Medium, High
swing_modes: Auto, 1, 2, 3, 4, 5
current_temperature: 28
temperature: 27
current_humidity: 52.22
fan_mode: Auto
swing_mode: Auto
friendly_name: HVAC Study
supported_features: 41
```

### Problem-relevant frontend configuration

```yaml
Dashboard:
          - type: thermostat
            entity: climate.hvac_study
            name: ' '

Configuration: (using a third-praty template climate from https://github.com/jcwillox/hass-template-climate)
    - platform: climate_template
      name: HVAC Study
      modes: ["off", "cool", "dry", "fan_only"]
      fan_modes: ["Auto", "Low", "Medium", "High"]
      swing_modes: ["Auto", "1", "2", "3", "4", "5"]
      min_temp: 16
      max_temp: 30
      precision: 1.0
      current_temperature_template: "{{ states('sensor.htm_1_study_temperature') }}"
      current_humidity_template: "{{ states('sensor.htm_1_study_humidity') }}"
      set_temperature:
        - service: python_script.hvac_sync
          data:
            room: study
      set_hvac_mode:
        - service: python_script.hvac_sync
          data:
            room: study
      set_fan_mode:
        - service: python_script.hvac_sync
          data:
            room: study
      set_swing_mode:
        - service: python_script.hvac_sync
          data:
            room: study
```
