### ISSUE TITLE
Config Check no longer reports some invalid configurations

### ISSUE THREAD

**Issue by finity69x2** [home-assistant/frontend#16536]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When making yaml configuration changes the config checker fails to report some errors in the config.

It's happened a few times now but the latest occurrence was with the following action:

```
action:
  - repeat:
      - service: notify.alexa_media
        data:
          target: 
            - media_player.livingroom_dot
          data:
            type: tts 
          message: "It's time to turn off the water in the front yard"
        - delay: "00:02:00"
    until:
      - condition: state
        entity_id: input_boolean.irr_time_to_water_front
        state: 'off'
```

Note there is a missing "sequence:"

Instead of reporting an error in the config check window or even just reporting a persistent notification to inform of the error the automation just silently failed to load. I didn't notice it until I went to the traces to figure out why the automation didn't run and found that the automation didn't exist in the system.

There was a note in the log about it that I found later but there was nothing to tell me that I even needed to look there to find the issue.

At one point in the not too recent past the config check would pass but if there was an error it would at least display a persistent notification indicating there was a problem.

### Describe the behavior you expected

There should at a minimum be a persistent notification with either the same info that is placed in the logs or the link to the logs as it has been in the past.

### Steps to reproduce the issue

```
action:
  - repeat:
      - service: notify.alexa_media
        data:
          target: 
            - media_player.livingroom_dot
          data:
            type: tts 
          message: "It's time to turn off the water in the front yard"
        - delay: "00:02:00"
    until:
      - condition: state
        entity_id: input_boolean.irr_time_to_water_front
        state: 'off'
```
Note there is a missing "sequence:"

### What version of Home Assistant Core has the issue?

223.5.0

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows all versions
