### ISSUE TITLE
Service Button on Picture Elements Card does not correctly center text

### ISSUE THREAD

**Issue by ghost** [home-assistant/frontend#16546]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I create a Service Button on a Picture Elements Card and apply a background under the Styles section, the text/title of the Service Button will not correctly center on the background. It seems to be adding a small amount of additional space on the right-hand side.

### Describe the behavior you expected

When using the **text-align: center** parameter under Styles, I would expect the text to perfectly center in the middle of the objects background.

### Steps to reproduce the issue

1. Create an example picture elements card with the following yaml:

type: picture-elements
elements:
  - type: service-button
    title: Turn lights off
    style:
      top: 50%
      left: 50%
      background-color: red
      text-align: center
    service: homeassistant.turn_off
    service_data:
      entity_id: group.all_lights
image: https://demo.home-assistant.io/stub_config/floorplan.png

2. 
![service-button](https://github.com/home-assistant/frontend/assets/86042175/e0f35aaf-2a8f-4b85-aff9-7f18b106e628

You will notice extra pixels/space on the right-hand side. This example is only 1px wide, but this space seems to increase on the iOS mobile app to a noticeable amount.

Perhaps there is something wrong in the css style for the service-button that is causing additional white-space after the last character? I have also tried setting the **background-position: center**  parameter which does not seem to help.

### What version of Home Assistant Core has the issue?

core-2023.5.3

### In which browser are you experiencing the issue with?

MS Edge 113.0.1774.42 (Official build) (64-bit) & iOS Mobile App

### Which operating system are you using to run this browser?

Microsoft Windows 11

### Problem-relevant frontend configuration

```yaml
type: picture-elements
elements:
  - type: service-button
    title: Turn lights off
    style:
      top: 50%
      left: 50%
      background-color: red
      text-align: center
    service: homeassistant.turn_off
    service_data:
      entity_id: group.all_lights
image: https://demo.home-assistant.io/stub_config/floorplan.png
```

### Additional information

![service-button2](https://github.com/home-assistant/frontend/assets/86042175/60d656f8-ef1d-4d47-8056-c0f05dd85ba0)

A second example.

yaml used:

        style:
          left: 50%
          top: 75%
          background-color: '#F2612C'
          border-radius: 16px
          text-align: center
          '--mdc-theme-primary': var(--primary-text-color)
