### ISSUE TITLE
Wrong X axis scale on statistics graph

### ISSUE THREAD

**Issue by bigboban** [home-assistant/frontend#16575]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have 30 days history set in configuration. But graph shows 6 months. And i know why. It is because data gap. I started sensor 19 days ago. When i set 18 days in "days to show" X axis has 18 days. When i set 19 and more days X axis is broken and has 6 months.

18 days setting:
<img width="547" alt="image" src="https://github.com/home-assistant/frontend/assets/7159224/d991286a-a106-4b24-9805-4f7f5df6ea63">

19 days setting:
<img width="551" alt="image" src="https://github.com/home-assistant/frontend/assets/7159224/dae002fa-4e7a-4e2e-bfb9-edf002b63951">

### Describe the behavior you expected

X axis has always length according to configuration also in case of missing sensor data.

### Steps to reproduce the issue

Described above.

### What version of Home Assistant Core has the issue?

2023.5.3

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: day
type: statistics-graph
entities:
  - sensor.teplota_vody_v_bazenu
days_to_show: 19
title: Statistika teplot za měsíc
stat_types:
  - mean
hide_legend: false
```
