### ISSUE TITLE
Vert. or horiz. scrollbar + history-graph tooltip: dashboard blinking

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16622]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this card:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
  - type: history-graph
    entities:
      - sun.sun
```
Required number of `entity: sun.sun` lines may vary dependingly of your monitor's resolution.

Create ONE card and place it on an empty view.
In my case the bottommost `history-graph` card is not fully visible:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/125910f9-5cfe-4cbc-a172-b9f6672bf435)

Need to scroll down a bit to see it fully:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/0984de5a-2164-4e07-b351-521ce7a602e5)

Now place a mouse on a `history-graph` card.
A tooltip is displayed, a vertical scrollbar is trying to adapt, the whole dashboard may start blinking:

![bl1](https://github.com/home-assistant/frontend/assets/71872483/1f4c2fa7-1e9a-4dbb-b09e-9a9270286bdd)

Another example:

![bl2](https://github.com/home-assistant/frontend/assets/71872483/38db187a-aa56-4a4e-852a-d8d638911ffb)

### Describe the behavior you expected

No blinking

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.5.4

### In which browser are you experiencing the issue with?

Chrome 113.0.5672.127 

### Which operating system are you using to run this browser?

Win10
