### ISSUE TITLE
Picture Glance Card: missing possibility to change color of a group of light entities

### ISSUE THREAD

**Issue by Jojo-A** [home-assistant/frontend#16630]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When having a picture glance card the holds the controls for multiple identical light entities and opening the "More Info" menu, there is no option to set the color of all entities at once. But on the other hand the option for setting effects for all at once works perfectly.
![Bildschirmfoto vom 2023-05-26 10-47-02](https://github.com/home-assistant/frontend/assets/33325587/0ed5b7fa-add5-43b5-bcd3-488a3d7c5aae)

### Describe the behavior you expected

The opening the More Info menu the color wheel should come up when clicking the corresponding button.
![Bildschirmfoto vom 2023-05-26 10-48-17](https://github.com/home-assistant/frontend/assets/33325587/3aa87723-03cf-4f70-bb92-c637f9d8b996)

### Steps to reproduce the issue

1. Create two identical light entities (in my case two esphome light with the same configuration regarding the entire light)
2. Create a Picture Glance card
3. Add the identical lights to that Picture Glance card
4. Open the "More Info" dialog (in my case by holding the card clicked)
5. Click on the "Change color" button

### What version of Home Assistant Core has the issue?

Version: 2023.5.4

### Which operating system are you using to run this browser?

Linux Mint 21.1

### State of relevant entities

```txt
light.construction_site_1
State: on
Attributes:
effect_list: Random, Full Color Rainbow, Construction Site Y, Construction Site R, Construction Site C, Strobe, Flicker, None
supported_color_modes: rgbw
color_mode: rgbw
brightness: 133
hs_color: 23.509, 67.059
rgb_color: 255, 151, 84
rgbw_color: 255, 100, 0, 125
xy_color: 0.546, 0.372
effect: None
friendly_name: Construction Site 1
supported_features: 44

light.construction_site_2
State: on
Attributes: same as above, except the name
```

### Problem-relevant frontend configuration

```yaml
camera_view: auto
type: picture-glance
entities:
  - entity: light.construction_site_1
  - entity: light.construction_site_2
title: Baustellen
image: /local/images/lights/construction_site.jpg
aspect_ratio: '4:3'
tap_action:
  action: toggle
hold_action:
  action: more-info
entity: group.constructionsites

The group:
constructionsites:
  name: Baustellen
  entities:
    - light.construction_site_1
    - light.construction_site_2
```

### Additional information

Here is the card, hold it for "More Info":
![Bildschirmfoto vom 2023-05-26 10-50-02](https://github.com/home-assistant/frontend/assets/33325587/07459840-c66d-4b95-bf94-7c1080e76b2c)

The dialog comes up.
![Bildschirmfoto vom 2023-05-26 10-49-06](https://github.com/home-assistant/frontend/assets/33325587/a8743442-cca2-4cb5-90e1-dfe960799d7b)

 Click the "Change color" button:
![Bildschirmfoto vom 2023-05-26 10-47-02](https://github.com/home-assistant/frontend/assets/33325587/4d941d3b-fe51-4018-a58c-115c520a5b9f)

Applying this procedure **to the single card entities** (the light bulb icons on the bottom right) brings up the color wheel:
![Bildschirmfoto vom 2023-05-26 10-48-17](https://github.com/home-assistant/frontend/assets/33325587/8bb3e38a-918d-4c99-bb67-68b99bf71291)
