### ISSUE TITLE
Shutter button down inaccessible when UI too narrow

### ISSUE THREAD

**Issue by madduck** [home-assistant/frontend#16764]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I put two shutter controls (entity cards) in a horizontal stack, then on a mobile device, the controls overflow and become unusable:
![image](https://github.com/home-assistant/frontend/assets/195073/b3f92025-b76b-4679-b829-53731a7cbb4b)
This also happens in landscape mode, since then two columns are actually displayed side-by-side.

### Describe the behavior you expected

In this setting, I'd expect the responsive UI to hide the icon on the left, or for the spacing to be drastically reduced.

### Steps to reproduce the issue

Create a card with the following horizontal stack for two shutter entities:
```
- type: horizontal-stack
  cards:
  - type: entities
    entities:
      - entity: cover.tas_shutters_south_cover_1
        show_header_toggle: false
  - type: entities
    entities:
      - entity: cover.tas_shutters_west_cover_1
        show_header_toggle: false
```
and view it on a mobile device.

Observe how the "down" button is inaccessible.

### What version of Home Assistant Core has the issue?

2023.5.4

### In which browser are you experiencing the issue with?

Firefox 113.0.2

### Which operating system are you using to run this browser?

Debian unstable
