### ISSUE TITLE
Calendar card loses it's styling

### ISSUE THREAD

**Issue by envy** [home-assistant/frontend#16848]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a dashbboard with multiple views and a calendar card on the first main view, it looks like this:

![grafik](https://github.com/home-assistant/frontend/assets/241552/b87f8894-7d79-4310-b9db-87502610e8af)

When I click on a different view and then come back to the previous view, it looks like this:

![grafik](https://github.com/home-assistant/frontend/assets/241552/f6622db5-9f7e-418f-80d4-7806bdff8039)

The same happens when trying to edit the dashboard, the card just loses its styling.

### Describe the behavior you expected

The calendar card should keep its styling

### Steps to reproduce the issue

1. Put a calender card on the first view on the default dashboard, make sure it has entries.
2. Refresh site
3. Calendar card should look ok
4. Switch to edit mode
5. Calendar card shoul look wrong.
...

### What version of Home Assistant Core has the issue?

2023.06.1

### What was the last working version of Home Assistant Core?

2023.05.x

### In which browser are you experiencing the issue with?

Firefox 113.0.1 (also tested Edge 114)

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
type: calendar
entities:
  - calendar.alw
initial_view: listWeek
title: Mülltonnen
```

**Comment by illascanbe** [comment]
I'm also experiencing this behaviour since the update to 2023.06.x

![image](https://github.com/home-assistant/frontend/assets/121318283/b4defcc9-921d-4700-a0a3-ec9c4d383f74)

**Comment by eeFLis** [comment]
same here.

Can also be reproduced in my case by minimising the siedbar and enlarging it again.
If you then switch between the calendar views, the calendar loses its style.

**Comment by Canonfodda** [comment]
Also seeing this issue with Calendar card. Have tested it on Firefox, Google, Safari web browsers. 
Running RPI 3B+ 
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest
also was seen on 2023.6.1 
Can also reproduce styling fubar using the above examples, and also moving between Lovelace tabs. 
No errors being seen in ha su log, or other logs. 
Have remove, cleared cache and re-installed card, but same issue.

**Comment by matthias1189** [comment]
Same here for me

**Comment by Manticore-007** [comment]
I also have this issue, I was playing around with card-mod and thought there was an issue with that, later I found out it also gives this issue without card-mod. Issue restores with a refresh, but reappears after clicking another page and going back.

**Comment by Smokey01966** [comment]
Same issue

When dashboard loads the first time everything is fine but putting the calendar card in a conditional card and then hiding and showing the cards causes everything to break. When in month view it breaks so bad the page freezes.

Base code for testing (need a calendar called test and an input boolean called test)

```
views:
  - type: panel
    title: Calendar Display
    path: calendar-display
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entity
            entity: input_boolean.test
          - type: conditional
            conditions:
              - entity: input_boolean.test
                state: 'on'
            card:
              initial_view: listWeek
              type: calendar
              entities:
                - calendar.test 
```
