### ISSUE TITLE
history-graph: stops updating if sensor is not changing

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16895]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider a history graph with some sensor:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/1e27f610-7c68-409b-a31d-8679e6fb751b)
Assume this sensor is really changing every 1 minute.
We can see this change on the graph.
The right bound is the CURRENT time.

**But if the sensor is NOT changing - then the graph "freezes" & not updating, so the right bound becomes not the current time.**
To update the graph a user needs to refresh a page.

-----------------

Here is a test to demonstrate this behaviour:
Sensors:
```
template:
  - sensor:
      - name: testing_every_minute
        unit_of_measurement: !secret glob__unit_of_measurement__minutes
        state: >-
          {{ now().minute }}

  - trigger:
      - platform: state
        entity_id:
          - sensor.testing_every_minute
          - input_boolean.testing_every_minute_controlled
    sensor:
      - name: testing_every_minute_controlled
        unit_of_measurement: !secret glob__unit_of_measurement__minutes
        state: >
          {% if is_state('input_boolean.testing_every_minute_controlled','on') -%}
            {{ states('sensor.testing_every_minute') }}
          {%- else -%}
            {{ states(this.entity_id) }}
          {%- endif %}

input_boolean:
  testing_every_minute_controlled:
```
Test card:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_boolean.testing_every_minute_controlled
        secondary_info: last-changed
      - entity: sensor.testing_every_minute
        secondary_info: last-changed
      - entity: sensor.testing_every_minute_controlled
        secondary_info: last-changed
  - type: history-graph
    hours_to_show: 0.0833
    entities:
      - entity: input_boolean.testing_every_minute_controlled
        name: bool
      - entity: sensor.testing_every_minute
        name: every_minute
      - entity: sensor.testing_every_minute_controlled
        name: controlled
  - type: history-graph
    hours_to_show: 0.0833
    entities:
      - entity: sensor.testing_every_minute_controlled
        name: controlled
```
Here 2 sensors:
-- 1st - is updated every 1 minute;
-- 2nd - is equal to the 1st if an `input_boolean` = ON (otherwise keeps same value).

When both sensors are changing, both graphs are updating and have same right border:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/91146097-bc39-4239-8d7b-eda802582e82)

When the 2nd sensor "freezes" - the 2nd graph "freezes" too:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/377ed131-5788-41b4-8ba8-deb8a3f2d69e)

### Describe the behavior you expected

Even if a sensor is having same value - update a graph.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.6.0

### In which browser are you experiencing the issue with?

Chrome 114.0.5735.110 

### Which operating system are you using to run this browser?

Win10
