### ISSUE TITLE
Script blueprints do not respect the `mode` parameter.

### ISSUE THREAD

**Issue by samuelthng** [home-assistant/frontend#16916]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Upon creating a script from a blueprint where `mode: restart`, the script is always created with `mode: single`.

### Describe the behavior you expected

This issue may cause unwanted bugs that may not be obvious to troubleshoot, especially when sharing blueprints to less technical users.

It should behave like in automations. 
If the blueprint has defined the `mode` parameter, the automation created will simply inherit the parameter from the blueprint.

### Steps to reproduce the issue

1. Create a simple script blueprint with `mode: restart`
2. Reload scripts in Home Assistant
3. Create a script from the newly created blueprint.
4. `Edit in YAML`
5. Notice that `mode: single` is always being appended at the end of the script.

### What version of Home Assistant Core has the issue?

2023.6.1

### In which browser are you experiencing the issue with?

Google Chrome Version 114.0.5735.133 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Ventura 13.4

### Additional information

Example script:
https://github.com/samuelthng/t-house-blueprints/blob/main/notifications.yaml

**Comment by samuelthng** [comment]
Apologies if this is the incorrect place for this issue, I was recommended to post this here, but it feels more like a /core issue instead.

**Comment by karwosts** [comment]
I actually don't see what you're seeing. I imported your blueprint and made a script from it, and I do not see any mode in the generated script yaml:

```
alias: 🔔 Notification with Confirm, Dismiss and Timeout
use_blueprint:
  path: samuelthng/notifications.yaml
  input:
    notify_device: dac2df065c584a3c053b3454ddb91c6b
    title: x
    message: x
    tag: x
    timeout:
      hours: 0
      minutes: 0
      seconds: 10
```

**Comment by samuelthng** [comment]
That's weird. I've imported a few times and this is always what I get:
```yaml
alias: 🔔 Notification with Confirm, Dismiss and Timeout Test
use_blueprint:
  path: samuelthng/notifications.yaml
  input:
    notify_device: a92204bcbd5a328a4d3f0e8006d04975
    title: Test
    tag: test
    message: test
    timeout:
      hours: 0
      minutes: 0
      seconds: 1
mode: single
```
