### ISSUE TITLE
Goup more-info toggle does net repeat group all: true setting

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#16977]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

core entities card
<img width="498" alt="Scherm­afbeelding 2023-06-19 om 21 22 42" src="https://github.com/home-assistant/frontend/assets/33354141/ef2793b4-dd8e-4279-8283-e53b38bd8bb5">

top is the group, below the entities of the group. group shows off, which is correct.

Now check the more-info on that group:

<img width="578" alt="Scherm­afbeelding 2023-06-19 om 21 22 52" src="https://github.com/home-assistant/frontend/assets/33354141/0edf1953-2e8f-4748-94cd-cc5c4862f294">

it does not respect the all: true in the group configuration, which is a huge issue.

### Describe the behavior you expected

have the group more-info toggle respect the state of the group

### Steps to reproduce the issue

1. create group
2. toggle individual entities
3.
...

### What version of Home Assistant Core has the issue?

2023.6.2

### In which browser are you experiencing the issue with?

any

### Problem-relevant frontend configuration

```yaml
- type: entities
    title: Hide dialog header
    show_header_toggle: false
    entities:
      - group.kiosk_mode_hide_dialog_header
      - input_boolean.hide_dialog_header_history
      - input_boolean.hide_dialog_header_settings
      - input_boolean.hide_dialog_header_overflow
```
