### ISSUE TITLE
Picture-glance doesn't refresh URL pictures properly

### ISSUE THREAD

**Issue by HAuser2019** [home-assistant/frontend#16995]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi, This is an very old issue which really starts to be annoying. If I use a webURL for Picture-Glance, but also the other Picture-entity or Picture. It works for a while, but it does not refresh properly (it's a gif that get's updated a few times a day, see url). When switching dasboards it keeps displaying the old picture. I really have to quit the Android/iOS companion app and restart to get the picture on the dashboard refreshed. Here is my code so you can test it out:

```
type: horizontal-stack
cards:
  - type: picture
    image: >-
      https://cdn.knmi.nl/knmi/map/current/weather/forecast/kaart_verwachtingen_Vandaag_dag.gif
    tap_action:
      action: none
    hold_action:
      action: none
  - type: picture-glance
    camera_view: auto
    title: Example
    image: >-
      https://cdn.knmi.nl/knmi/map/current/weather/warning/waarschuwing_land_0_new.gif
    entities:
      - entity: sensor.weer
```

### Describe the behavior you expected

I expect the picture to be refreshed once in a while. Or at least when I switch dashboards pages.

### Steps to reproduce the issue

1. Add url to picture-glance, picture or picture-entity
2. Keep it as minimal as possible, only want to see picture.
3. Watch the dasboard.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.2

### What was the last working version of Home Assistant Core?

It has never worked as expected.

### In which browser are you experiencing the issue with?

All dashboard displaying possabilities, but mainly Android companion app
Does not happen when viewing in webrowser. It probably updates more often.

### Which operating system are you using to run this browser?

macOS Ventura 13.4

**Comment by HAuser2019** [comment]
Does not happen when viewing in webrowser by the way. It probably updates more often than the HA native companion app displaying the Dashboard on the wall in the house (companion i have the latest version always).

**Comment by HAuser2019** [comment]
Is there any news on this issue pictures from URL not actively refreshing properly?

**Comment by frenck** [comment]
> I expect the picture to be refreshed once in a while.

For that we have a new `image` entity, which will be available in Home Assistant 2023.7.

**Comment by HAuser2019** [comment]
> > I expect the picture to be refreshed once in a while.
> 
> For that we have a new `image` entity, which will be available in Home Assistant 2023.7.

Hmm "new entity type that is like a camera, but specifically for images." NICE!

But the page how to do this is empty: https://www.home-assistant.io/integrations/image
:-(
Not being able to try this out in in 2023.7 yet...

**Comment by ildar170975** [comment]
@HAuser2019 
Try to create a template image entity:
```
template:
  - image:
      - name: test_image
        url: your url
```
