### ISSUE TITLE
history-graph: a "left boundary" in a tooltip may be confusing

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#17003]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this card:
```
type: vertical-stack
cards:
  - type: history-graph
    entities:
      - sun.sun
    hours_to_show: 12
  - type: history-graph
    entities:
      - sun.sun
    hours_to_show: 24
```
![image](https://github.com/home-assistant/frontend/assets/71872483/0185cb5c-0ec3-4903-a7b9-24f7238661fc)

Do not bother that the sun became "above_horizon" by a noon - it happened because I switched off test HA setup at night and switched on it at about a noon.

Check a tooltip for the 1st card:

![image](https://github.com/home-assistant/frontend/assets/71872483/7551f6a3-eafe-4636-9f9d-944a705f8750)

It is said that the `below_horizon` state was between 08:38 and 11:39.
But in fact 08:38 = current time `20:38` - `hours_to_show`, so this is **not a real left boundary of this state**.

### Describe the behavior you expected

The left boundary must be a REAL left boundary.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.6.2

### In which browser are you experiencing the issue with?

Chrome 114.0.5735.134
