### ISSUE TITLE
UPB Integration offers incorrect choice for 'Deactivate Link'

### ISSUE THREAD

**Issue by jc508** [home-assistant/frontend#17006]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In an Automation I am using 'Universal Powerline Bus (UPB): Deactivate link'
The 'choose entity' button shows a list of switches and Dimmers but no Links (scenes)
If the automation.yaml file is manually edited and the correct name inserted eg 'scene.link007_entry' then it works as expected.

### Describe the behavior you expected

Seeing the service is 'deactivate link' I expected a list of links (scenes)

### Steps to reproduce the issue

1.
2.
3.
...
![image](https://github.com/home-assistant/frontend/assets/33336084/eae109e7-00ef-4e5b-bca6-72f59680624d)

### What version of Home Assistant Core has the issue?

2023.6.2

### In which browser are you experiencing the issue with?

Firefox 114.0.2

### Which operating system are you using to run this browser?

Windows 10 Pro

### Problem-relevant frontend configuration

```yaml
-- manually edited to insert correct entity
- id: '1687425730146'
  alias: Entry Light Auto Off
  description: de-activate entry light
  trigger:
  - platform: state
    entity_id:
    - timer.entry_light_timer
    from: active
  condition:
  - condition: state
    entity_id: light.entry_light
    state: 'on'
  action:
  - service: upb.link_deactivate
    data: {}
    target:
      entity_id: scene.link007_entry
  mode: single
```

**Comment by karwosts** [comment]
The authors of this component have defined this service as applying as only to lights:

```
link_deactivate:
  name: Deactivate link
  description: Deactivate a UPB scene.
  target:
    entity:
      integration: upb
      domain: light
```

If scenes should be in this list, then this service call needs to be updated in core repository for scenes as well. So this is not a frontend issue.
