### ISSUE TITLE
Trace error from automation

### ISSUE THREAD

**Issue by martijn1247812** [home-assistant/frontend#17009]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I look for the trace of the last automation run, the last trace is shown with the follwing message: "Error rendering graph. Please download trace and share with the developers."

### Describe the behavior you expected

nice map of the steps in the automation

### Steps to reproduce the issue

none, like the message showed I'm sending you this error

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.1 Frontend 20230608.0 - latest

### Problem-relevant frontend configuration

```yaml
Automation:

alias: Buiten plantjes water geven
description: ""
trigger:
  - platform: time
    at: "03:00:00"
condition: null
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.buienradar_rain_last_24h
        below: 1
      - condition: numeric_state
        entity_id: sensor.buienradar_rain_1d
        below: 5
      - condition: numeric_state
        entity_id: input_number.previous_rain_24h
        below: 5
    then:
      - type: turn_off
        device_id: 1c5979f9379f18653f93c846b5f22cd4
        entity_id: switch.hombli_smart_socket_8_socket_1
        domain: switch
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - repeat:
          count: 2
          sequence:
            - type: turn_on
              device_id: 1c5979f9379f18653f93c846b5f22cd4
              entity_id: switch.hombli_smart_socket_8_socket_1
              domain: switch
            - delay:
                hours: 0
                minutes: 1
                seconds: 2
                milliseconds: 0
            - type: turn_off
              device_id: 1c5979f9379f18653f93c846b5f22cd4
              entity_id: switch.hombli_smart_socket_8_socket_1
              domain: switch
            - delay:
                hours: 0
                minutes: 0
                seconds: 4
                milliseconds: 0
  - service: input_number.set_value
    data:
      value: "{{ states('sensor.buienradar_rain_last_24h') }}"
    target:
      entity_id: input_number.previous_rain_24h
mode: single
```

### Additional information

trace:

{
  "trace": {
    "last_step": "action/1",
    "run_id": "1ceef6b2b6f63a8745eb5dba3fe12f71",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2023-06-23T01:00:00.334863+00:00",
      "finish": "2023-06-23T01:00:00.349559+00:00"
    },
    "domain": "automation",
    "item_id": "1686675670280",
    "trigger": "time",
    "trace": {
      "trigger/0": [
        {
          "path": "trigger/0",
          "timestamp": "2023-06-23T01:00:00.335206+00:00",
          "changed_variables": {
            "this": {
              "entity_id": "automation.buiten_plantjes_water_geven",
              "state": "on",
              "attributes": {
                "last_triggered": "2023-06-21T21:06:57.963173+00:00",
                "mode": "single",
                "current": 0,
                "id": "1686675670280",
                "friendly_name": "Buiten plantjes water geven"
              },
              "last_changed": "2023-06-22T06:53:41.036632+00:00",
              "last_updated": "2023-06-22T06:53:41.036632+00:00",
              "context": {
                "id": "01H3GY2N9CWJXNDVWFJ47ZER9X",
                "parent_id": null,
                "user_id": null
              }
            },
            "trigger": {
              "id": "0",
              "idx": "0",
              "alias": null,
              "platform": "time",
              "now": "2023-06-23T03:00:00.333902+02:00",
              "description": "time",
              "entity_id": null
            }
          }
        }
      ],
      "action/0": [
        {
          "path": "action/0",
          "timestamp": "2023-06-23T01:00:00.336707+00:00",
          "changed_variables": {
            "context": {
              "id": "01H3JW7RYEWQGM69BN5ARZGN8V",
              "parent_id": null,
              "user_id": null
            }
          }
        }
      ],
      "action/0/if": [
        {
          "path": "action/0/if",
          "timestamp": "2023-06-23T01:00:00.338086+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "action/0/if/condition/0": [
        {
          "path": "action/0/if/condition/0",
          "timestamp": "2023-06-23T01:00:00.338255+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "action/0/if/condition/0/entity_id/0": [
        {
          "path": "action/0/if/condition/0/entity_id/0",
          "timestamp": "2023-06-23T01:00:00.338383+00:00",
          "result": {
            "result": false,
            "state": 3.8,
            "wanted_state_below": 1
          }
        }
      ],
      "action/1": [
        {
          "path": "action/1",
          "timestamp": "2023-06-23T01:00:00.338834+00:00",
          "result": {
            "params": {
              "domain": "input_number",
              "service": "set_value",
              "service_data": {
                "value": 3.8,
                "entity_id": [
                  "input_number.previous_rain_24h"
                ]
              },
              "target": {
                "entity_id": [
                  "input_number.previous_rain_24h"
                ]
              }
            },
            "running_script": false,
            "limit": 10
          }
        }
      ]
    },
    "config": {
      "id": "1686675670280",
      "alias": "Buiten plantjes water geven",
      "description": "",
      "trigger": [
        {
          "platform": "time",
          "at": "03:00:00"
        }
      ],
      "condition": null,
      "action": [
        {
          "if": [
            {
              "condition": "numeric_state",
              "entity_id": "sensor.buienradar_rain_last_24h",
              "below": 1
            },
            {
              "condition": "numeric_state",
              "entity_id": "sensor.buienradar_rain_1d",
              "below": 5
            },
            {
              "condition": "numeric_state",
              "entity_id": "input_number.previous_rain_24h",
              "below": 5
            }
          ],
          "then": [
            {
              "type": "turn_off",
              "device_id": "1c5979f9379f18653f93c846b5f22cd4",
              "entity_id": "switch.hombli_smart_socket_8_socket_1",
              "domain": "switch"
            },
            {
              "delay": {
                "hours": 0,
                "minutes": 0,
                "seconds": 5,
                "milliseconds": 0
              }
            },
            {
              "repeat": {
                "count": 2,
                "sequence": [
                  {
                    "type": "turn_on",
                    "device_id": "1c5979f9379f18653f93c846b5f22cd4",
                    "entity_id": "switch.hombli_smart_socket_8_socket_1",
                    "domain": "switch"
                  },
                  {
                    "delay": {
                      "hours": 0,
                      "minutes": 1,
                      "seconds": 2,
                      "milliseconds": 0
                    }
                  },
                  {
                    "type": "turn_off",
                    "device_id": "1c5979f9379f18653f93c846b5f22cd4",
                    "entity_id": "switch.hombli_smart_socket_8_socket_1",
                    "domain": "switch"
                  },
                  {
                    "delay": {
                      "hours": 0,
                      "minutes": 0,
                      "seconds": 4,
                      "milliseconds": 0
                    }
                  }
                ]
              }
            }
          ]
        },
        {
          "service": "input_number.set_value",
          "data": {
            "value": "{{ states('sensor.buienradar_rain_last_24h') }}"
          },
          "target": {
            "entity_id": "input_number.previous_rain_24h"
          }
        }
      ],
      "mode": "single"
    },
    "blueprint_inputs": null,
    "context": {
      "id": "01H3JW7RYEWQGM69BN5ARZGN8V",
      "parent_id": null,
      "user_id": null
    }
  },
  "logbookEntries": [
    {
      "name": "Buiten plantjes water geven",
      "message": "triggered by time",
      "source": "time",
      "entity_id": "automation.buiten_plantjes_water_geven",
      "context_id": "01H3JW7RYEWQGM69BN5ARZGN8V",
      "when": 1687482000.335557,
      "domain": "automation"
    },
    {
      "when": 1687482000.347513,
      "state": "3.8",
      "entity_id": "input_number.previous_rain_24h",
      "icon": "mdi:weather-rainy",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Buiten plantjes water geven",
      "context_message": "triggered by time",
      "context_source": "time",
      "context_entity_id": "automation.buiten_plantjes_water_geven"
    }
  ]
}
