### ISSUE TITLE
Picture-elements card not working on iOS with camera entity 

### ISSUE THREAD

**Issue by MStapelfeldt** [home-assistant/frontend#17211]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a camera set up by frigate and picture-element card to show image on dashboard with some buttons. This is working great on Android and PC, but not on iOS on iphone and iPad.

### Describe the behavior you expected

I expect the card showing a picture/camera stream also on iPad/iPhone

### Steps to reproduce the issue

1. Setup camera in frigate
2. add entity to picture-element card
3. view on iOS

### What version of Home Assistant Core has the issue?

2023.7.1

### What was the last working version of Home Assistant Core?

2023.7.1

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

iPadOS 16.5.1

### Problem-relevant frontend configuration

```yaml
- type: picture-elements
            camera_view: live
            camera_image: camera.terasse_mainstream
            elements: []
          - type: picture-elements
            camera_view: live
            camera_image: camera.fri_terasse_cam
            elements: []
          - type: picture-entity
            entity: camera.fri_terasse_cam
```

### Additional information

The picture-elements with onvif entity is working, picture-entity with frigate is also working. picture-elements with frigate is not working on iOS.
Also posted on [Frigate Github](https://github.com/blakeblackshear/frigate/issues/7085) , but they say it's an issue of HA card, not Frigate (which could be, because it's only on iOS)
Above code produces the following image:

![IMG_0022](https://github.com/blakeblackshear/frigate/assets/6480145/42dc984f-adf3-46e4-983c-8ad5420f9117)
