### ISSUE TITLE
Automation Conditions - value_template not removed after cleared

### ISSUE THREAD

**Issue by itn3rd77** [home-assistant/frontend#17245]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have changed an automation condition (numeric_state) which previously required a value_template to evaluate. I changed the entity to an input_number and deleted the value_template via visual mode.

In the next step I clicked Test from the menu to check the altered condition but that failed with the following error:

```
In 'numeric_state': In 'numeric_state' condition: entity input_number.outside_temperature_threshold_duration state '' cannot be processed as a number
```

After switching to YAML mode I realized that the value_template  was not removed but set to an empty string ```value_template: ""```

After remving the line ```value_template: ""``` in YAML mode the test succeeded.

### Describe the behavior you expected

Clearing the field "Value template" field in visual mode should remove the value_template from YAML.

### Steps to reproduce the issue

1. Create an automation condition with numeric_state and choose an  input_number helper as entity with e.g. above 10
2. Enter something in Value template field (doesn't matter what) and click "Save"
3. Clear the Value template field and click "Save"
4. Now click on "Test" for this automation condition  and you get an error message
5. In YAML mode you can see the line ```value_template: ""```
6. Delete that line an click "Test" again. Now the test succeedes
...

### What version of Home Assistant Core has the issue?

2023.7.1

### In which browser are you experiencing the issue with?

Firefox 115.0.1 (64-Bit)

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
alias: Nachtrückkühlung
description: ""
trigger:
  - platform: time
    at: "03:00:00"
condition:
  - condition: numeric_state
    entity_id: input_number.outside_temperature_threshold_duration
    above: 5
    value_template: ""
action:
  - service: cover.set_cover_position
    data:
      position: 20
    target:
      device_id:
        - 7aef95a7803ec8145e25198f98effe64
        - 5977318b4c0e5eb4c5a3580f68876efe
        - 0c4c66791f926ea59f7595022b57bfc4
    alias: Open covers for recooling
  - service: input_number.set_value
    data:
      value: 0
    target:
      entity_id: input_number.outside_temperature_threshold_duration
    alias: Reset input_number.outside_temperature_threshold_duration
mode: single
```
