### ISSUE TITLE
history-graph inside "Grid" card: page becomes irresponsive

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#17242]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I add this card, my page become irresponsive:
```
        type: grid
        cards:
          - type: history-graph
            hours_to_show: 12
            entities:
              - entity: zone.home
```
![image](https://github.com/home-assistant/frontend/assets/71872483/c3cfcb9c-bfd5-4205-b5fb-eb61f1e427ea)

Cannot save a card.
Have to close a tab.

If this card is added in yaml mode - then after opening a view the page also becomes irresponsive.

Tested with Chrome & FF (Win10).
No errors in Log.

Rebooting HA does not help.
Clearing browser's cache does not help.

### Describe the behavior you expected

The card is added, page is responsive.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.7

### In which browser are you experiencing the issue with?

Chrome
