### ISSUE TITLE
Energy self sufficiency not showing in Android companion app

### ISSUE THREAD

**Issue by WebSpider** [home-assistant/frontend#17314]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since 2023.07 HA has a new energy self sufficiency card. This card for me only shows when accessing the energy dashboard via a webbrowser. It is missing from the Android companion ap

### Describe the behavior you expected

I expect the card to show up, since I measure my solar, energy consumption and energy return

### Steps to reproduce the issue

1. Upgrade HA from 2023.06 to 2023.07.2
2. Wait 2h for statistics to settle
3. Access stock energy dashboard in companion app
4. Notice the new gauge is missing

### What version of Home Assistant Core has the issue?

core.2023.7.2

### What was the last working version of Home Assistant Core?

None, new feature in 2023.7

### In which browser are you experiencing the issue with?

Android companion apps embedded browser

### Which operating system are you using to run this browser?

Android 13

### Problem-relevant frontend configuration

```yaml
View from companion app:

![IMG_20230715_083128](https://github.com/home-assistant/frontend/assets/437323/26272d76-474d-4451-8249-e7e023a8e449)

View from browser:

![Screenshot_2023-07-15-08-20-59-42_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/home-assistant/frontend/assets/437323/1fe5a8b3-aedd-41c7-a86c-f8732cc9c4fd)
```

### Javascript errors shown in your browser console/inspector

```txt
Unaccessible
```
