### ISSUE TITLE
Assist (external bus) payload missing details / using implied defaults

### ISSUE THREAD

**Issue by jpelgrom** [home-assistant/frontend#17322]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The (external bus) payload that is used for the Assist button in the top app bar and the 'Assist' tap action on a card does not always contain enough details for the app to respond correctly and uses implied defaults which may not match with the app.

Specifically I'm seeing:
- It is implied that if `start_listening` isn't set, Assist shouldn't start listening, while for the app experience it should.
This also translates to the tap action, where if "start listening?" is off it isn't sent on the external bus. There is no way for the app to distinguish this from the Assist action in the top app bar.
- If no specific `pipeline_id` is supplied, it is implied that the last used pipeline _or_ the preferred pipeline is used, depending on where it is triggered - top app bar: last used, action: preferred.
This also applies to the frontend, see #17301. The lack of details here means the frontend always uses the last used pipeline while in the app it always uses the preferred pipeline.

### Describe the behavior you expected

More details, see above

### Steps to reproduce the issue

n/a

### What version of Home Assistant Core has the issue?

core-2023.7.1

### In which browser are you experiencing the issue with?

Google Chrome 114.0.5735.199 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11, version 22H2

### Problem-relevant frontend configuration

```yaml
Payload for top app bar and a button with Assist action as configured below is empty ({}), while they should produce different behavior between frontend/app and top app bar/button.

Button card configuration:
show_name: true
show_icon: true
type: button
tap_action:
  action: assist
name: Assist me
```
