### ISSUE TITLE
Energy cards not showing data (however the general Energy dashboard is displaying the data)

### ISSUE THREAD

**Issue by timvdsm** [home-assistant/frontend#17462]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My general HA energy dashboard is working perfectly without any issue. All data is nicely visualized. 
However when I use the custom energy cards (https://www.home-assistant.io/dashboards/energy/) it mentions that the data is not available.
There is no problem with the data itself, as at the same time it is shown on the general HA energy dashboard.  
After refreshing the page a couple of times, the data becomes visible. 

### Describe the behavior you expected

Energy cards show the data as in the general HA energy dashboard instantly. 

### Steps to reproduce the issue

1. Open custom dashboard with energy cards
2. Data is not visible
3. Refreshing a couple of times
4. Data becomes visible

**This is a dashboard using the custom energy cards, data is not available:**
<img width="1025" alt="Scherm­afbeelding 2023-08-02 om 16 25 30" src="https://github.com/home-assistant/frontend/assets/14946020/dcd4913a-c241-4902-8088-319934aea0f3">

**At the same time this is the general HA energy dashboard, which shows all data:**
<img width="1156" alt="Scherm­afbeelding 2023-08-02 om 16 25 17" src="https://github.com/home-assistant/frontend/assets/14946020/cc4a5750-a393-4b1c-a938-c32b8bb1ed26">

**After refreshing the page a couple of times, the data becomes available:**
<img width="1026" alt="Scherm­afbeelding 2023-08-02 om 16 49 36" src="https://github.com/home-assistant/frontend/assets/14946020/c19e82fb-ff01-4058-a2c6-fedb89d17ba1">

### What version of Home Assistant Core has the issue?

Home Assistant 2023.7.3

### In which browser are you experiencing the issue with?

Safari (macbook), Chrome (Macbook & Windows), IOS companion app (iphone) & android app

### Problem-relevant frontend configuration

```yaml
Example of the config of one of the cards:

type: energy-usage-graph
title: Energieverbruik
```

**Comment by karwosts** [comment]
I would suggest share the full yaml of your manual dashboard. 

Instead of refreshing the page, if you switch to a different dashboard/panel and navigate back, does that help with the loading?

**Comment by timvdsm** [comment]
Hi @

> I would suggest share the full yaml of your manual dashboard.
> 
> Instead of refreshing the page, if you switch to a different dashboard/panel and navigate back, does that help with the loading?

Hi, switching to a different dashboard/panel doesn't solve it. 

**Here is the full yaml of the custom dashboard:**
```
views:
  - title: Historiek
    path: energie_overzicht_historiek
    type: sidebar
    badges: []
    cards:
      - type: custom:energy-period-selector-plus
        card_background: false
        today_button: true
        prev_next_buttons: true
        compare_button_type: icon
        today_button_type: text
        period_buttons:
          - day
          - week
          - month
          - year
          - custom
        custom_period_label: Selectie
        compare_button_label: Vergelijk
      - type: energy-distribution
        title: Energiedistributie
        link_dashboard: false
        view_layout:
          position: sidebar
      - type: energy-usage-graph
        title: Energieverbruik
      - type: energy-solar-graph
        title: Zonne-energie productie
      - type: energy-gas-graph
        title: Gasverbruik
      - type: energy-sources-table
        title: Bronnen
      - type: energy-grid-neutrality-gauge
        view_layout:
          position: sidebar
      - type: energy-solar-consumed-gauge
        view_layout:
          position: sidebar
      - type: energy-self-sufficiency-gauge
        view_layout:
          position: sidebar
      - type: energy-devices-graph
title: Energiebeheer
```
