### ISSUE TITLE
Gauges not displaying since 2023.08.1 update

### ISSUE THREAD

**Issue by N3oTraX** [home-assistant/frontend#17497]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,

I've made the laste upgrade of homeassistant Core 2023.08.1 these past days.
Since this upgrade no gauges are displayed.
I cleared my browser cache and cookies and try with 3 different browsers but nothing change. I restarted my virtual machine many times but still not displayed.
Even on the companion app they are not displayed and no errors related to this in the log.

I joined a screenshot and here is the code snippet :

```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: light.cuisine
        name: Cuisine
        icon: mdi:lightbulb-group
        hold_action:
          action: more-info
        theme: Mushroom Shadow
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: light.salon
        name: Salon
        icon: mdi:lightbulb-group
        hold_action:
          action: more-info
        theme: Mushroom Shadow
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.sonoff_couloir_switch
        name: Couloir
        icon: mdi:lightbulb-group
        hold_action:
          action: more-info
        theme: Mushroom Shadow
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: light.terrasse
        name: Terrasse
        icon: mdi:lightbulb-group
        hold_action:
          action: more-info
        theme: Mushroom Shadow
  - type: horizontal-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.prisepiscine
        icon: mdi:pool
        name: Filtration Piscine
        hold_action:
          action: more-info
        theme: Mushroom Shadow
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.prise_clim_socket_1
        icon: mdi:air-conditioner
        name: Prise Clim
        hold_action:
          action: more-info
        theme: Mushroom Shadow
  - type: horizontal-stack
    cards:
      - show_name: true
        show_icon: false
        type: gauge
        tap_action:
          action: toggle
        entity: sensor.prisepiscine_energy_power
        name: Piscine
        hold_action:
          action: more-info
        min: 0
        max: 2000
        severity:
          red: 1800
          yellow: 500
          green: 0
        theme: Mushroom Shadow
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.prise_box_socket_1
        icon: mdi:set-top-box
        name: Prise Box
        hold_action:
          action: more-info
        theme: Mushroom Shadow
      - show_name: true
        show_icon: false
        type: gauge
        tap_action:
          action: toggle
        entity: sensor.prise_clim_power
        name: Prise Clim
        hold_action:
          action: more-info
        min: 0
        max: 2000
        severity:
          red: 1800
          yellow: 500
          green: 0
        theme: Mushroom Shadow
```
![gauges](https://github.com/home-assistant/frontend/assets/7289904/00585e1d-2eb9-49d1-ac98-2880606c2898)

### Describe the behavior you expected

Must display the gauge like before the upgrade 2023.8.1.

### Steps to reproduce the issue

1. Upgrade Core to 2023.8.1
2. Restart HomeAssistant and navigate on my custom dashboard
3. All cards are nice displayed but gauges are not.
...

### What version of Home Assistant Core has the issue?

core-2023.8.1

### What was the last working version of Home Assistant Core?

core-2023.8.0 and before

### In which browser are you experiencing the issue with?

Brave, Chrome and Firefox

### Which operating system are you using to run this browser?

Windows 10 22H2 19045.3208

Best regards
