### ISSUE TITLE
input_select with theme only shows selected option

### ISSUE THREAD

**Issue by dy-nz** [home-assistant/frontend#17503]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I configure lovelace to use a theme for a card that uses an input_select entity, then only the selected option shows in a input_select drop-down list. The full drop-down list still shows - it is just that the text for all the non-selected items is invisible.

### Describe the behavior you expected

That the drop-down list would display when I use a Theme, just like when I don't use a theme for that card.

### Steps to reproduce the issue

1. Go to any lovelace standard (non-custom) card with an input_select entity.
2. Edit that dashboard and Set the theme to something other than "No Thee"
3. Save the dashboard.
4. Try the input_select drop-down list.
...

### What version of Home Assistant Core has the issue?

Supervisor 2023.07.1 ; Operating System 10.4 ; Frontend 20230802.0

### What was the last working version of Home Assistant Core?

Didn't try previously

### In which browser are you experiencing the issue with?

Version 115.0.5790.170 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 23H1

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
title: Screens and Sound
cards:
  - type: entities
    entities:
      - entity: input_select.zm_media_source
        icon: mdi:television-speaker
      - entity: input_select.zk_media_source
        icon: mdi:television-speaker
    state_color: false
```
