### ISSUE TITLE
Badges do not respect the "show_name" configuration variable.

### ISSUE THREAD

**Issue by sebastianrasor** [home-assistant/frontend#17589]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The `show_name` configuration variable for dashboard badges has no effect at all.
![image](https://github.com/home-assistant/frontend/assets/92653912/ce874f28-fbae-4ca9-bcb8-6b6461c1567b)

### Describe the behavior you expected

When `show_name` is set to false, I expect the names to not be shown.

### Steps to reproduce the issue

1. Add a badge to your dashboard and set the `show_names` configuration variable to `false`.

### What version of Home Assistant Core has the issue?

2023.8.2

### In which browser are you experiencing the issue with?

Firefox 115.0.2

### Which operating system are you using to run this browser?

Ubuntu 22.04.2 LTS

### Problem-relevant frontend configuration

```yaml
badges:
  - type: state-label
    entity: binary_sensor.garage_door
    show_name: false
    tap_action:
      action: call-service
      service: button.press
      data:
        entity_id: button.garage_door
  - type: state-label
    entity: light.inside
    show_name: false
    icon: mdi:home-lightbulb
    tap_action:
      action: toggle
```
