### ISSUE TITLE
Automations/scripts UI: lack of the item, in "repeat type" combobox, linked to for_each loop (and parameters)

### ISSUE THREAD

**Issue by Extreme79** [home-assistant/frontend#17679]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I wrote a script using that need to loop through an input_select elements.
I done that directly in yaml using repeat >> for_each.
```
repeat:
  for_each: "{{state_attr('input_select.chiamate_allarme','options')}}"
  sequence:
  .......
```
Directly in yaml because the UI do not have any correspondent value in the combobox.
As you can see switching to UI do not throw any message, and any lock happen when using the "unsupported" loop in the UI
![image](https://github.com/home-assistant/frontend/assets/33934444/9e865ee6-d844-4670-b815-a815a248145b)
![image](https://github.com/home-assistant/frontend/assets/33934444/ffd3b9a1-aa90-4a24-b49b-27680472c9b3)

Sorry, screenshots in italian
- Conteggio = Count 
- Mentre=While
- Fino a = Until

Also no parameters are available in the UI using for_each (blank combo selected value + no params)

I opened as a bug and not a feature request because appear to me as an oversight (all the others loop types are supported)

### Describe the behavior you expected

1. Having the 4th item in the combobox, representing the for_each statement.
2. Be able to configure for_each in the UI.

### Steps to reproduce the issue

1. Create a script
2. Place a loop in it than switch to yaml and modify in a for_each repeat (or create the script directly in yaml 😁)
3. Switch back to the UI and you will see the ui with empty combo box and no parameters

### What version of Home Assistant Core has the issue?

2023.8.3

### In which browser are you experiencing the issue with?

Google Chrome 116.0.5845.96 (Official Build) (a 64 bit)

### Which operating system are you using to run this browser?

Windows 10 - 22H2 (build SO 19045.3324)

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
repeat:
  for_each: "{{state_attr('input_select.chiamate_allarme','options')}}"
  sequence:
    - service: hassio.addon_stdin
      data_template:
        addon: c7744bff_ha-sip
        input:
          command: dial
          number: sip:{{repeat.item}}@fritz.box
          webhook_to_call:
            call_established: "mysecret_webhook1"
            call_disconnected: "mysecret_webhook2"
          ring_timeout: 20
          sip_account: 1
          menu:
            message: "{{messaggio}}"
      alias: Chiama Numero in lista
    - wait_for_trigger:
        - platform: webhook
          allowed_methods:
            - POST
            - PUT
          local_only: true
          webhook_id: "mysecret_webhook1"
          alias: Chiamata agganciata (o rifiutata)
        - platform: webhook
          allowed_methods:
            - POST
            - PUT
          local_only: true
          webhook_id: "mysecret_webhook2"
          alias: Chiamata Risposta
      timeout:
        hours: 0
        minutes: 0
        seconds: 25
        milliseconds: 0
    - choose:
        - conditions:
            - condition: template
              value_template: |
                {{ wait.trigger.webhook_id == "mysecret_webhook2" }}
              alias: Se il trigger è la risposta
          sequence:
            - service: notify.mobile_app_extreme1
              data:
                message: Debug Trigged! Chiamata risposta da..
            - service: script.turn_off
              data: {}
              target:
                entity_id: script.allarme_chiamate_sip
        - conditions:
            - condition: template
              value_template: "{{ wait.trigger.webhook_id == \"mysecret_webhook1\" }}"
              alias: Se il trigger è il rifiuto
          sequence: []
        - conditions:
            - condition: template
              value_template: "{{wait.trigger==null}}"
              alias: Timeout
          sequence: []
      default: []
alias: Scorre la lista dei numeri
```
