### ISSUE TITLE
Android companion app, Android Chrome window freezes when retrieving state history/logbook

### ISSUE THREAD

**Issue by windsurferwill** [home-assistant/frontend#17712]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Not sure at what version this started but it seems like since the last few updates.  Click entity status on HA dashboard.  Sometimes it will freeze.  I'll get the entity status just fine, History will show 'Loading state history...' continuously, The Logbook is blank but shows a spinning circle.  At that point the only thing I can do is close the Android app or the Chrome window on the Android that is running HA.  IF I CLOSE THE APP then restart the App and go back to the same entity it works fine - no hang.  But if I close the App and restart and go back to a different entity it locks up again.   The card in question is the 'Entities Card' in the Dashboard. Windows 10 Desktop Chrome window works fine.
I've noticed I can get to happen consistently with entities declared in YAML for 'envisalink' (maybe others too?).  Retrieving current state of the particular entity in Developer Tools, no problem.  There are other entities declared in YAML but those work (not Envisalink).

 I just upgraded to the latest everything and problem still exists:
Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

I am using the Entities Card in the dashboard.
Any ideas?

### Describe the behavior you expected

Not lock up :)

### Steps to reproduce the issue

1.  Goto to Android app or HA running in Chrome window on the Android
2. Goto dashboard
3. Click on entity within the Entities Card
4. Shows Loading state history and spinning wheel for Logbook.  Locks up.
5. close app
6. restart app
7. go back to same entity - now works fine
8. back to dashboard and click different entity - locks up.
...

### What version of Home Assistant Core has the issue?

2023.8.4

### In which browser are you experiencing the issue with?

Android companion app and Android Chrome 116.0.5845.114,

### Which operating system are you using to run this browser?

Android 13 build /TP1A.220624.014

### Problem-relevant frontend configuration

```yaml
YAML excerpt:
envisalink:
  host: 192.168.xx.xxx
  panel_type: xxx
  user_name: xxxx
  password: xxxx
  evl_version: 4
  zonedump_interval: 0
  partitions:
    1:
      name: 'Home Alarm'
  zones:
    01:
      name: 'Fire - Study'
      type: 'smoke'
    02:
      name: 'Fire-Master Bedroom'
      type: 'smoke'
    03:
      name: 'Fire-Gail workroom'
      type: 'smoke'
    04:
      name: 'Fire-Hallway outside Gail workroom'
      type: 'smoke'
    05:
      name: 'Fire-Pajama lounge'
      type: 'smoke'
    06:
      name: 'Fire-Green (side) Bedroom'
      type: 'smoke'
    07:
      name: 'Fire-Guest Bedroom'
      type: 'smoke'
    08:
      name: 'Fire-Hallway outside Guest Bedroom'
      type: 'smoke'
    09:
      name: 'Back Door'
      type: 'door'
    10:
      name: 'Front Door'
      type: 'door'
    11:
      name: 'Back door to deck'
      type: 'door'
    12:
      name: 'Glass break - Kitchen'
      type: 'sound'
    13:
      name: 'Glass break - Den'
      type: 'sound'
    14:
      name: 'Foyer motion'
      type: 'motion'
    35:
      name: 'Fire- Crawlspace'
      type: 'smoke'
    37:
      name: 'Carbon Monoxide - Hallway'
      type: 'smoke'
    39:
      name: 'Carbon Monoxide - Kitchen'
      type: 'smoke'
weather:
  - platform: wral_weather
    name: "WRAL Weather"
    zipcode: 'xxxxx'
frontend:
  themes: !include_dir_merge_named themes
```

### Javascript errors shown in your browser console/inspector

```txt
not seeing any
```

### Additional information

![Screenshot_20230826_114911_Home Assistant](https://github.com/home-assistant/frontend/assets/49887431/024c0389-461c-4d95-9d9f-d1069c34a9ee)
