### ISSUE TITLE
2023.9.0b0: Weather "more info" card shows erroneous forecast data

### ISSUE THREAD

**Issue by tjhorner** [home-assistant/frontend#17746]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The weather entity's "more info" card appears to show the current temperature instead of the day's high and low, as expected.

### Describe the behavior you expected

The forecast should display the high and low for each day, like so:

<img width="573" alt="image" src="https://github.com/home-assistant/frontend/assets/2646487/5164fe88-2feb-4c04-a857-e993834e9d05">

### Steps to reproduce the issue

1. Create demo weather entity
2. View the entity's "more info" card
3. Compare the current temperature to what the forecast shows

A good way to verify that this issue is not with the entity itself is by creating a weather dashboard card with the forecast; this will show the correct forecast.

More info card:

<img width="594" alt="image" src="https://github.com/home-assistant/frontend/assets/2646487/1b702ff6-53b3-452f-83c8-c1bc38a40b1c">

Dashboard weather card:

<img width="514" alt="image" src="https://github.com/home-assistant/frontend/assets/2646487/db26a6d4-cbfa-49f7-a768-a683ce4f59db">

### What version of Home Assistant Core has the issue?

2023.9.0b0

### In which browser are you experiencing the issue with?

Google Chrome 116.0.5845.110

### Which operating system are you using to run this browser?

macOS Ventura 13.4.1 (22F82)

### Additional information

Result of `weather.get_forecast`:

```yaml
forecast:
  - datetime: "2023-08-30T16:00:43.823155-07:00"
    condition: rainy
    precipitation: 1
    temperature: 72
    templow: 59
    precipitation_probability: 60
  - datetime: "2023-08-31T16:00:43.823155-07:00"
    condition: rainy
    precipitation: 5
    temperature: 66
    templow: 46
    precipitation_probability: 30
  - datetime: "2023-09-01T16:00:43.823155-07:00"
    condition: cloudy
    precipitation: 0
    temperature: 59
    templow: 48
    precipitation_probability: 10
  - datetime: "2023-09-02T16:00:43.823155-07:00"
    condition: sunny
    precipitation: 0
    temperature: 54
    templow: 43
    precipitation_probability: 0
  - datetime: "2023-09-03T16:00:43.823155-07:00"
    condition: partlycloudy
    precipitation: 2
    temperature: 57
    templow: 45
    precipitation_probability: 20
  - datetime: "2023-09-04T16:00:43.823155-07:00"
    condition: rainy
    precipitation: 15
    temperature: 64
    templow: 45
    precipitation_probability: 0
  - datetime: "2023-09-05T16:00:43.823155-07:00"
    condition: fog
    precipitation: 0.2
    temperature: 70
    templow: 54
    precipitation_probability: 100
```
