### ISSUE TITLE
Selection stays stuck after clicking on certain cards

### ISSUE THREAD

**Issue by TheJulianJES** [home-assistant/frontend#17768]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking on entities in a `glance` card, a selection briefly appears during the opening of the more info dialog.
As soon as the dialog is opened, the selection disappears. However, when the more info dialog is closed again, the entity in the `glance` card is selected again.
This did not happen in previous Home Assistant Core versions.

Here's a video showing the behavior:

https://github.com/home-assistant/frontend/assets/6409465/37aa4fd4-b5f8-4901-883c-fc3d1612a9cb

The same thing now also happens when clicking the entity icon in an `entities` card. As expected, however, no selection is made when clicking on the text of an `entities` card.

This doesn't happen on mobile/iOS. Since I'm also not using a keyboard on my PC to navigate through the UI, I see no reason that these selections should appear (and stay) **after** closing the dialog.

This behavior also looks somewhat *ugly*, as you have to click away on some non-interactable place to remove the selection again (which I'm doing in the video after some time).

### Describe the behavior you expected

I'd expect that the selection doesn't appear at all, as long as I'm using a mouse/touch. It should only appear if I'm using the TAB key on my keyboard to navigate through the UI.

Otherwise, it's also reasonable to expect that the "selection" briefly shows when clicking on the entity and/or as long as the "more info" dialog is open. It should disappear as soon as the dialog is closed though.

### Steps to reproduce the issue

1. Create a `glance` card (YAML provided below)
2. Click on an entity in the `glance` card
3. See selection briefly appear
4. See selection disappear when dialog opens
5. Close dialog
6. See selection re-appear

### What version of Home Assistant Core has the issue?

core-2023.9.0b1

### What was the last working version of Home Assistant Core?

core-2023.8.4

### In which browser are you experiencing the issue with?

Google Chrome 116.0.5845.140

### Which operating system are you using to run this browser?

macOS Sonoma (14.0) Dev Beta 7

### Problem-relevant frontend configuration

```yaml
- show_name: true
  show_icon: true
  show_state: true
  type: glance
  entities:
    - entity: sun.sun
    - entity: sensor.sun_next_dusk
  title: Glance card
- type: entities
  entities:
    - entity: sun.sun
    - entity: sensor.sun_next_dusk
  title: Entities card
```
