### ISSUE TITLE
Glance Cards sometimes don't display state on reload

### ISSUE THREAD

**Issue by MrMDavidson** [home-assistant/frontend#17846]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Glance cards do not reliably render the state of their items after a reload (Intermittently, ~10% of the time)

Rendered without State showing
![image](https://github.com/home-assistant/frontend/assets/1366249/7abbf14a-e7ea-42b5-acd5-4e06595d32a5)

Editing the card to show that "Show state" is selected and in the background you can see the state is not being rendered
![image](https://github.com/home-assistant/frontend/assets/1366249/be2eb10b-5671-4704-842f-794c6322e827)

### Describe the behavior you expected

Glance cards reliably draw the state of their items between reloads

### Steps to reproduce the issue

1. Set up some `input_datetime` helpers configured for date and time (Note: These aren't changing during the test)
2. Configure a Glance card with "Show state" containing the helpers
```yaml
show_name: true
show_icon: true
show_state: true
type: glance
entities:
  - entity: input_datetime.blind_last_done
  - entity: input_datetime.blind_reminder
title: Blinds

```
3. Refresh the browser (Ctrl-F5 or Ctrl-R works). May need to try several times, ~10% of the time this happens on my setup
4. Observe the Glance Cards aren't drawing state

Once in this state they will not draw correctly until either another reload (navigating throughout the UI will not correct them) or you toggle their settings;

1. Edit Dashboard
2. Edit (card) (Note: The preview will be correct here)
![image](https://github.com/home-assistant/frontend/assets/1366249/44b87057-6745-49cd-9ffa-2bf4b5ebd270)
3. Flip "Show state?" Off and back On
4. Hit Save (Note: If you cancel, it will not resolve)

### What version of Home Assistant Core has the issue?

2023.9.0

### In which browser are you experiencing the issue with?

Google Chrome 116.0.5845.179 (Official Build) (64-bit) (cohort: M116 Ramp Up) and 116.0.1938.69 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 22H2 (OS Build 19045.3324)

### State of relevant entities

```txt
input_datetime.blind_last_done
State: 2023-09-06 18:23:23	
has_date: true
has_time: true
editable: true
year: 2023
month: 9
day: 6
hour: 18
minute: 23
second: 23
timestamp: 1693988603
icon: mdi:blinds-horizontal-closed
friendly_name: Blind Last Done


input_datetime.blind_reminder
State: 2023-09-07 18:23:23
	has_date: true
has_time: true
editable: true
year: 2023
month: 9
day: 7
hour: 18
minute: 23
second: 23
timestamp: 1694075003
icon: mdi:blinds-horizontal-closed
friendly_name: Blind Reminder
```

### Problem-relevant frontend configuration

```yaml
show_name: true
show_icon: true
show_state: true
type: glance
entities:
  - entity: input_datetime.blind_last_done
  - entity: input_datetime.blind_reminder
title: Blinds
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

N/A
