### ISSUE TITLE
TypeError: i.setConfig is not a function (In 'i.setConfig(t)', 'i.setConfig'is undefined)

### ISSUE THREAD

**Issue by AmoebeLabs** [home-assistant/frontend#17864]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As of HA versions > 2023.6 users of my custom card (Swiss Army Knife) report this error:

![image](https://github.com/home-assistant/frontend/assets/7996307/fb37168b-03e2-414f-ab20-0700a606085b)

Some report this error is persistent, some say after F5 the error is gone. However, it keeps coming back!

See: https://community.home-assistant.io/t/lovelace-versatile-swiss-army-knife-custom-card/432419/244?u=amoebelabs for instance.

I myself can't reproduce the problem.

The crash is as you can see on line 97 where the custom card is created, and the 'setConfig' is called while the element is undefined!

![image](https://github.com/home-assistant/frontend/assets/7996307/407d6f8f-2328-4e40-85ae-3186e1eb83ab)

### Describe the behavior you expected

No error at all. If the custom card is known on other cards/dashboards, it should be known to HA.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

> 2023.6

### What was the last working version of Home Assistant Core?

2023.6

### In which browser are you experiencing the issue with?

Chrome, Edge, Safari and Firefox show these problems

### Problem-relevant frontend configuration

```yaml
Some users use storage mode, others YAML.

As an example: even very simple cards show this behaviour like:


    - type: grid
      columns: 2
      square: false
      cards:
        # ================================================================
        - type: 'custom:swiss-army-knife-card'
          entities:
            - entity: sensor.dsmr_reading_electricity_currently_delivered
              name: 'Electricity'
          layout:
            toolsets:
              - toolset: just-a-name
                position:
                  cx: 50
                  cy: 50
                tools: 
                  - type: circle
                    position:
                      cx: 50
                      cy: 50
                      radius: 45
                    styles:
                      circle:
                        stroke-width: 2em
                        stroke: red 
                        stroke-opacity: 0.5
                        fill: bisque
                        fill-opacity: 0.5
                  - type: state 
                    position: 
                      cx: 50
                      cy: 70
                    entity_index: 0
                    styles:
                      state: 
                        font-size: 15em
```
