### ISSUE TITLE
Lights' color-temperature slider indicates brightness rather than color temperature when idle

### ISSUE THREAD

**Issue by hivehand** [home-assistant/frontend#17870]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I select a light entity that supports different color temperatures, and select the color-temperature control from the appearing popup, I am presented with a slider that allows me to control the color temperature. However, the value displayed above the slider itself is the brightness percentage rather than the current color temperature, i.e. "50%" rather than "4,003 K" . (Please see the attached image for an example.) The color temperature is displayed while I click/tap and hold the slider, but that display reverts to brightness percentage the moment I release the control.

I see this behavior on Mac Safari, Mac Chrome, and the Home Assistant iOS app.

![image](https://github.com/home-assistant/frontend/assets/1063575/7d96b638-c7d9-4db9-8b2d-48052b78f3c1)

### Describe the behavior you expected

I expect to be shown the current color temperature when in color-temperature control mode.

### Steps to reproduce the issue

1. Select, from the UI Overview, a lighting entity that supports variable color temperature.
2. From the ensuing pop-up, click/tap the rightmost member of the upper row of buttons to select color-temperature control.
3. Observe that the text field near the top of the pop-up shows a brightness percentage rather than the color temperature.

### What version of Home Assistant Core has the issue?

2023.9.0

### What was the last working version of Home Assistant Core?

2023.8

### In which browser are you experiencing the issue with?

Apple Safari Version 16.6 (18615.3.12.11.2), Google Chrome Version 116.0.5845.179 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Ventura Version 13.5.2 (22G91)

### State of relevant entities

```txt
State:
on

Attributes:
min_color_temp_kelvin: 2202
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 454
supported_color_modes: color_temp
color_mode: color_temp
brightness: 128
color_temp_kelvin: 4016
color_temp: 249
hs_color: 26.805, 34.581
rgb_color: 255, 206, 166
xy_color: 0.42, 0.365
mode: normal
dynamics: none
icon: mdi:dome-light
friendly_name: Center
supported_features: 40
```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: light.office_led_strips
  - entity: light.desktop_led_strip
  - entity: light.workbench_led_strip
  - entity: light.office_center
  - entity: light.hexagoon
title: Office
footer:
  type: buttons
  entities:
    - entity: scene.office_morning
      show_icon: true
      show_name: true
      name: Morning
    - entity: scene.office_daylight
      show_icon: true
      show_name: true
      name: Daylight
    - entity: scene.office_evening
      show_icon: true
      show_name: true
      name: Evening
    - entity: scene.office_chillout
      show_icon: true
      show_name: true
      name: Chillout
state_color: true
show_header_toggle: true
```
