### ISSUE TITLE
Map card: entity with "friendly_name_template" cannot be displayed

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#17925]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this template sensor of a LEGACY format:
```
sensor:
  - platform: template
    sensors:
      testing_iss:
        friendly_name: abc
        value_template: ok
        attribute_templates:
          latitude: -25.100481554029
          longitude: -129.37401816254
```
and this card:
```
  - type: map
    entities:
      - entity: sensor.testing_iss
    hours_to_show: 1
```
The card displays this entity:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/927ffe80-d53e-4e03-9543-fcf86f0e0dfa)

And same with this - the entity is displayed:
```
        friendly_name_template: 123
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/6c7905d3-1a2d-47d8-a04d-88a5cab278fc)

But with this it does NOT display the entity:
```
        friendly_name_template: >-
          {{123 + 123}}
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/0eb387bb-4848-4359-8642-2e9a9fe599f2)

i.e. entities with templated `friendly_name` are not displayed.

### Describe the behavior you expected

All entities with `latitude` & `longitude` may be displayed on the Map card.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Chrome 116.0.5845.188 

### Which operating system are you using to run this browser?

Win10x64
