### ISSUE TITLE
Energy dashboards frequently display no data unless loaded directly

### ISSUE THREAD

**Issue by MattJeanes** [home-assistant/frontend#17974]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Very often when I navigate to my tab containing the built in energy cards they display no data, but loading into this tab directly always works.

### Describe the behavior you expected

Navigating to the energy tab of my dashboard should always show data and not require me to load directly into it

### Steps to reproduce the issue

1. Load Home Assistant on home page
2. Navigate to Energy tab
3. All built-in energy cards do not load

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Google Chrome 117.0.5938.88

### Which operating system are you using to run this browser?

Windows 11 23H2

### State of relevant entities

`sensor.growatt_import_from_grid_total_cost`

```yaml
state_class: total
last_reset: '2023-09-17T13:39:29.780287+00:00'
unit_of_measurement: GBP
device_class: monetary
friendly_name: sensor Cost
value: 16.0836000000001
```

`sensor.growatt_battery_discharged_total`

```yaml
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
icon: mdi:battery-arrow-down-outline
friendly_name: Growatt - Battery discharged (total)
value: 2761.7
```

`sensor.growatt_generated_solar_energy_epv_today`

```yaml
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
icon: mdi:solar-power
friendly_name: Growatt - Generated solar energy (epv) (Today)
value: 0.0
```

`sensor.growatt_export_to_grid_total`

```yaml
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
icon: mdi:transmission-tower-import
friendly_name: Growatt - Export to grid (total)
value: 412.8
```

`sensor.growatt_export_to_grid_total_compensation`

```yaml
state_class: total
last_reset: '2023-09-17T13:36:40.650363+00:00'
unit_of_measurement: GBP
device_class: monetary
friendly_name: sensor Compensation
value: 0.540000000000003
```

`sensor.growatt_battery_charged_total`

```yaml
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
icon: mdi:battery-arrow-up
friendly_name: Growatt - Battery charged (total)
value: 2810.7
```

`sensor.growatt_import_from_grid_total`

```yaml
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
icon: mdi:battery-arrow-up
friendly_name: Growatt - Battery charged (total)
value: 2810.7
```

### Problem-relevant frontend configuration

```yaml
type: energy-usage-graph
title: Energy usage
```

### Javascript errors shown in your browser console/inspector

```txt
No errors are present in the browser console
```

### Additional information

After debugging through the `hui-energy-usage-graph-card` I believe I have found partially what is causing the issue. the `energyData.stats` appears to differ in format when it is working to when it is not working.

When the dashboard is working as expected:
```json
{
    "sensor.growatt_import_from_grid_total_cost": [
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "change": 0.9000000357627869
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "change": 0.42000001668930054
        }
    ],
    "sensor.growatt_battery_discharged_total": [
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "change": 0
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "change": 0
        }
    ],
    "sensor.growatt_generated_solar_energy_epv_today": [
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "change": 0
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "change": 0
        }
    ],
    "sensor.growatt_export_to_grid_total": [
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "change": 0
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "change": 0
        }
    ],
    "sensor.growatt_export_to_grid_total_compensation": [
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "change": 0
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "change": 0
        }
    ],
    "sensor.growatt_battery_charged_total": [
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "change": 3
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "change": 3
        }
    ],
    "sensor.growatt_import_from_grid_total": [
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "change": 12
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "change": 5.600000000000364
        }
    ]
}
```

And when it is not working:
```json
{
    "sensor.growatt_import_from_grid_total_cost": [
        {
            "start": 1695247200000,
            "end": 1695250800000,
            "sum": 67004699.78361248
        },
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "sum": 67004700.68361252
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "sum": 67004701.103612535
        }
    ],
    "sensor.growatt_battery_discharged_total": [
        {
            "start": 1695247200000,
            "end": 1695250800000,
            "sum": 2759.1000000476774
        },
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "sum": 2759.1000000476774
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "sum": 2759.1000000476774
        }
    ],
    "sensor.growatt_generated_solar_energy_epv_today": [
        {
            "start": 1695247200000,
            "end": 1695250800000,
            "sum": 186.2999999999984
        },
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "sum": 186.2999999999984
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "sum": 186.2999999999984
        }
    ],
    "sensor.growatt_export_to_grid_total": [
        {
            "start": 1695247200000,
            "end": 1695250800000,
            "sum": 412.69999998807947
        },
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "sum": 412.69999998807947
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "sum": 412.69999998807947
        }
    ],
    "sensor.growatt_export_to_grid_total_compensation": [
        {
            "start": 1695247200000,
            "end": 1695250800000,
            "sum": 48.24539999999972
        },
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "sum": 48.24539999999972
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "sum": 48.24539999999972
        }
    ],
    "sensor.growatt_battery_charged_total": [
        {
            "start": 1695247200000,
            "end": 1695250800000,
            "sum": 2802.3999999761545
        },
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "sum": 2805.3999999761545
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "sum": 2808.3999999761545
        }
    ],
    "sensor.growatt_import_from_grid_total": [
        {
            "start": 1695247200000,
            "end": 1695250800000,
            "sum": 6266.200000250351
        },
        {
            "start": 1695250800000,
            "end": 1695254400000,
            "sum": 6278.200000250351
        },
        {
            "start": 1695254400000,
            "end": 1695258000000,
            "sum": 6283.800000250351
        }
    ]
}
```

I don't know a lot about HA's internals but it seems like something else is loading first when loading my home tab which when switching to the energy tab stays in this different format and breaks the graphs. There are cards on the home page which load up these same sensors, but of course that shouldn't break a different component on a different tab.

I can replicate this 100% of the time, and on mobile it is essentially impossible to view my energy dashboard as I cannot reload while on a specific tab, I have to go to the energy tab and then reload the page, which then shows the data. The same cards that show these same sensors are also present on the energy tab too so it's more of a timing / load order issue it seems, as when I load the energy tab directly everything loads correctly.

Please let me know if you'd like me to share any more information that might be useful, but hopefully that bit of debugging I did tells you something useful. If anyone wants to go through an interactive debugging session on my HA instance I am happy to do this as well.

This issue has not always happened but has been happening for at least a few months and started after a HA upgrade, but unfortunately I do not remember which version it started on.
