### ISSUE TITLE
Missing in Lokalise: automations related strings

### ISSUE THREAD

**Issue by tbertels** [home-assistant/frontend#18013]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing words and phrases in Lokalise for translation

URL: /config/automation/edit/

![Screenshot 2023-09-25 at 11-02-10 Paramètres – Home Assistant](https://github.com/home-assistant/frontend/assets/3265870/e69f676a-aeb2-429e-ad3e-9870c50ab82b)

![Screenshot 2023-09-25 at 11-03-51 Paramètres – Home Assistant](https://github.com/home-assistant/frontend/assets/3265870/e6b390af-1e5a-4299-b649-7158ae1b72e0)

![Screenshot 2023-09-25 at 11-10-02 Paramètres – Home Assistant](https://github.com/home-assistant/frontend/assets/3265870/91f8fe09-55b1-4c06-b93c-9476ea15d0e3)

![Screenshot 2023-09-25 at 11-12-35 Paramètres – Home Assistant](https://github.com/home-assistant/frontend/assets/3265870/847d2243-5490-4d3f-949e-4f429b8d8771)

### Describe the behavior you expected

Missing words and phrases should be in Lokalise.

### Steps to reproduce the issue

1. Switch to an other language than English
2. Go to Automations

YAML:
```
platform: numeric_state
entity_id: sensor.open_air_mini_rpm
for:
  hours: 0
  minutes: 1
  seconds: 0
below: 5
above: 10
```

```
condition: numeric_state
entity_id: weather.forecast_maison
attribute: temperature
above: 23
```

```
delay:
  hours: 0
  minutes: 0
  seconds: 10
  milliseconds: 0
```

```
delay:
  hours: 0
  minutes: 0
  seconds: 0
  milliseconds: 5
```

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.2 Interface utilisateur : 20230911.0 - latest
