### ISSUE TITLE
Can't Select Multiple Entities for Numeric State Trigger

### ISSUE THREAD

**Issue by The00Dustin** [home-assistant/frontend#18062]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When setting up triggers in automations, it is possible to choose multiple entities for a `State` trigger using a separate dropdown for each.  The same functionality is not presented when setting up a `Numeric State` trigger even though multiple entities are supported per examples in [the docs](https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger).  One can use YAML to choose multiple entities for the `Numeric State` trigger, and one can even switch back to `visual editor` afterwards, but the entities will all be listed by id on one line, comma separated (they will also be saved as comma separated in the YAML regardless of how they are entered).  If enough entities are chosen to exceed the width of the display, the expansion arrow for the trigger will not be displayed, but it can still be expanded/collapsed by clicking anywhere in the trigger description.

### Describe the behavior you expected

I expect multiple entities to be selectable individually in the `Numeric State` trigger UI the same way they are in the `State` trigger UI.

### Steps to reproduce the issue

1. Create a new automation.
2. Edit in YAML.
3. Use the example YAML from this ticket, substituting your own entities, choose enough entities for the `Numeric State` trigger to exceed the width of your browser/display if the disappearing expansion arrow is also unexpected.
4. Save the automation.
5. Back out of the automation and re-open it.
6. Witness any described behavior(s) that are unexpected by expanding the display of the two triggers and switching to YAML
7. Test the trigger, it still works.
8. Try to add entities to the `Numeric State` trigger using the drop-down, witness that choosing one wipes the others, and that placing the cursor at the end removes the ability to choose.

### What version of Home Assistant Core has the issue?

2023.9.3

### In which browser are you experiencing the issue with?

Safari 16.6, iOS Companion App

### Which operating system are you using to run this browser?

macOS Ventura 13.15.1, iOS 16.7

### Problem-relevant frontend configuration

```yaml
alias: Bug?
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.office_low_battery_level
      - binary_sensor.sun_room_low_battery_level
    to: "on"
  - platform: numeric_state
    entity_id:
      - sensor.office_battery_level
      - sensor.sun_room_battery_level
    above: 0
    below: 25
condition: []
action: []
mode: single
```

### Additional information

![Screenshot 2023-09-29 at 6 35 38 AM](https://github.com/home-assistant/frontend/assets/91274634/6b8a5965-373e-4cf6-a1ff-ae0666342423)
![Screenshot 2023-09-29 at 6 37 51 AM](https://github.com/home-assistant/frontend/assets/91274634/b88ea1dd-151d-4908-b812-7e1b2a52ee93)
