### ISSUE TITLE
No icons for the water heater on the tile card

### ISSUE THREAD

**Issue by Marc1200** [home-assistant/frontend#18073]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There are no icons for the water heater operating modes on the tile card.
![image](https://github.com/home-assistant/frontend/assets/68737063/e79e0b61-8fa2-44db-9692-c83a89071250)

### Describe the behavior you expected

//

### Steps to reproduce the issue

1. //
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2023.9.3

### Problem-relevant frontend configuration

```yaml
- features:
      - type: target-temperature
      - type: water-heater-operation-modes
        operation_modes:
          - auto
          - force_hot_water
    type: tile
    entity: water_heater.technischeruimte
    name: Boilertank
```
