### ISSUE TITLE
Display Precision editor not visible when a MQTT sensor has empty unit_of_measurement

### ISSUE THREAD

**Issue by Axeman72** [home-assistant/frontend#18080]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a MQTT sensor has an empty unit of measurement, in the UI editor there is no way to change its display precision. In this example yaml there are two sensors with the same configuration, except for unit_of_measurement. The first one (with unit "x") allows to set a display precision, the second one does not. 
```
  - sensor:
      unique_id: "Axe72/Home/Energy/AEM1/Stat/PowerFactor"
      name: "Power Factor"
      state_topic: "Axe72/Home/Energy/AEM1/Stat"
      unit_of_measurement: "x"
      value_template: "{{ value_json.PF }}"
      expire_after: 10
  - sensor:
      unique_id: "Axe72/Home/Energy/AEM1/Stat/PowerFactor_NoUnit"
      name: "Power Factor NoUnit"
      state_topic: "Axe72/Home/Energy/AEM1/Stat"
      unit_of_measurement: ""
      value_template: "{{ value_json.PF }}"
      expire_after: 10
```
![image](https://github.com/home-assistant/frontend/assets/26881628/bb1fda66-eae6-49f3-96fc-59dcd2ac14ac)
![image](https://github.com/home-assistant/frontend/assets/26881628/527342ff-712d-43e7-b992-1fffab1d0ba3)

### Describe the behavior you expected

The display precision should be editable in both sensors

### Steps to reproduce the issue

1. Load a yaml like the one pasted in the problem description
2. From the entities list open the entity details and click on the "settings" gear button. 

### What version of Home Assistant Core has the issue?

2023.09.3

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

Windows 10 22H2
