### ISSUE TITLE
Some automations slow to load/edit in visual editor

### ISSUE THREAD

**Issue by kylepyke** [home-assistant/frontend#18104]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

HA interface is slow to load the visual editor for some automations, and editing these automations is painfully slow/causes the interface to hang. This happens regardless of browser, and can prevent navigating away from the affected automation. YAML editing is unaffected.

### Describe the behavior you expected

I expect using the visual editor to be responsive.

### Steps to reproduce the issue

1. Go to settings/automations
2. Open an automations

### What version of Home Assistant Core has the issue?

Operating System 10.5

### In which browser are you experiencing the issue with?

Safari, Firefox, HA macOS app

### Which operating system are you using to run this browser?

macOS Big Sur

### Problem-relevant frontend configuration

```yaml
alias: >-
  Notifications - Front Door Lock Autiomation with Actionable Notifications
  (self-contained variables)
description: ""
trigger:
  - platform: time
    at: "22:00:00"
    id: night
  - platform: state
    entity_id:
      - device_tracker.smeph_iphone
      - device_tracker.the_emissary
    from: home
    to: not_home
    id: away
  - platform: time
    at: "22:18:50"
    id: changetotest
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: lock.front_door_lock
        state: locked
action:
  - choose:
      - conditions:
          - condition: trigger
            id: night
        sequence:
          - service: lock.lock
            data: {}
            target:
              entity_id: lock.front_door_lock
      - conditions:
          - condition: trigger
            id: away
        sequence:
          - delay:
              hours: 0
              minutes: 1
              seconds: 30
              milliseconds: 0
          - choose:
              - conditions:
                  - condition: and
                    conditions:
                      - condition: state
                        entity_id: device_tracker.smeph_iphone
                        state: not_home
                      - condition: state
                        entity_id: device_tracker.the_emissary
                        state: not_home
                sequence:
                  - service: lock.lock
                    data: {}
                    target:
                      entity_id: lock.front_door_lock
                  - if:
                      - condition: state
                        entity_id: lock.front_door_lock
                        state: locked
                    then:
                      - service: notify.allphones
                        data:
                          message: >-
                            The front door was left unlocked, but it is locked
                            now.
                          title: Front Door
                    else:
                      - repeat:
                          until:
                            - condition: template
                              value_template: >-
                                {{ is_state('lock.front_door_lock', 'locked') or
                                repeat.index == 10 }}
                          sequence:
                            - delay:
                                hours: 0
                                minutes: 1
                                seconds: 30
                                milliseconds: 0
                            - service: lock.lock
                              data: {}
                              target:
                                entity_id: lock.front_door_lock
                      - if:
                          - condition: state
                            entity_id: lock.front_door_lock
                            state: locked
                        then:
                          - service: notify.allphones
                            data:
                              message: >-
                                The front door was left unlocked, but it is
                                locked now.
                              title: Front Door
                        else:
                          - service: notify.allphones
                            data:
                              message: >-
                                The front door was left unlocked, and there was
                                an issue locking it. The device could be offline
                                or not responding.
                              title: Front Door
                              data:
                                push:
                                  sound:
                                    name: LOCK ERROR
                                    critical: 1
                                    volume: 0.5
                        alias: >-
                          FAIL SAFE - Ther is an 'until' loop in YAML not shown
                          here
              - conditions:
                  - condition: state
                    entity_id: device_tracker.smeph_iphone
                    state: not_home
                sequence:
                  - alias: Set up variables for the actions
                    variables:
                      action_lock: "{{ 'LOCK_' ~ context.id }}"
                      action_leave: "{{ 'LEAVE_' ~ context.id }}"
                  - alias: Notify
                    service: notify.mobile_app_the_emissary
                    data:
                      message: >-
                        The front door was left unlocked. Do you want to lock
                        it?
                      data:
                        actions:
                          - action: "{{ action_lock }}"
                            title: Lock
                            icon: sfsymbols:lock.fill
                          - action: "{{ action_leave }}"
                            title: Leave Unlocked
                            icon: sfsymbols:lock.open.fill
                  - alias: Wait for a response
                    wait_for_trigger:
                      - platform: event
                        event_type: mobile_app_notification_action
                        event_data:
                          action: "{{ action_lock }}"
                      - platform: event
                        event_type: mobile_app_notification_action
                        event_data:
                          action: "{{ action_leave }}"
                    timeout:
                      hours: 0
                      minutes: 10
                      seconds: 0
                      milliseconds: 0
                  - if:
                      - condition: template
                        value_template: "{{ wait.completed }}"
                    then:
                      - service: lock.lock
                        data: {}
                        target:
                          entity_id: lock.front_door_lock
                      - stop: ""
                  - alias: Perform the action
                    choose:
                      - conditions: "{{ wait.trigger.event.data.action == action_lock }}"
                        sequence:
                          - service: lock.lock
                            data: {}
                            target:
                              entity_id: lock.front_door_lock
                      - conditions: "{{ wait.trigger.event.data.action == action_leave }}"
                        sequence:
                          - stop: ""
              - conditions:
                  - condition: state
                    entity_id: device_tracker.the_emissary
                    state: not_home
                sequence:
                  - alias: Set up variables for the actions
                    variables:
                      action_lock: "{{ 'LOCK_' ~ context.id }}"
                      action_leave: "{{ 'LEAVE_' ~ context.id }}"
                  - alias: Notify
                    service: notify.mobile_app_iphone
                    data:
                      message: >-
                        The front door was left unlocked. Do you want to lock
                        it?
                      data:
                        actions:
                          - action: "{{ action_lock }}"
                            title: Lock
                            icon: sfsymbols:lock.fill
                          - action: "{{ action_leave }}"
                            title: Leave Unlocked
                            icon: sfsymbols:lock.open.fill
                  - alias: Wait for a response
                    wait_for_trigger:
                      - platform: event
                        event_type: mobile_app_notification_action
                        event_data:
                          action: "{{ action_lock }}"
                      - platform: event
                        event_type: mobile_app_notification_action
                        event_data:
                          action: "{{ action_leave }}"
                    timeout:
                      hours: 0
                      minutes: 10
                      seconds: 0
                      milliseconds: 0
                  - if:
                      - condition: template
                        value_template: "{{ wait.completed }}"
                    then:
                      - service: lock.lock
                        data: {}
                        target:
                          entity_id: lock.front_door_lock
                      - stop: ""
                  - alias: Perform the action
                    choose:
                      - conditions: "{{ wait.trigger.event.data.action == action_lock }}"
                        sequence:
                          - service: lock.lock
                            data: {}
                            target:
                              entity_id: lock.front_door_lock
                      - conditions: "{{ wait.trigger.event.data.action == action_leave }}"
                        sequence:
                          - stop: ""
      - conditions:
          - condition: trigger
            id: test
        sequence:
          - alias: Set up variables for the actions
            variables:
              action_lock: "{{ 'LOCK_' ~ context.id }}"
              action_leave: "{{ 'LEAVE_' ~ context.id }}"
          - alias: Notify
            service: notify.mobile_app_iphone
            data:
              message: The front door was left unlocked. Do you want to lock it?
              data:
                actions:
                  - action: "{{ action_lock }}"
                    title: Lock
                    icon: sfsymbols:lock.fill
                  - action: "{{ action_leave }}"
                    title: Leave Unlocked
                    icon: sfsymbols:lock.open.fill
          - alias: Wait for a response
            wait_for_trigger:
              - platform: event
                event_type: mobile_app_notification_action
                event_data:
                  action: "{{ action_lock }}"
              - platform: event
                event_type: mobile_app_notification_action
                event_data:
                  action: "{{ action_leave }}"
            timeout:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
          - if:
              - condition: template
                value_template: "{{ wait.completed }}"
            then:
              - service: lock.lock
                data: {}
                target:
                  entity_id: lock.front_door_lock
              - stop: ""
          - alias: Perform the action
            choose:
              - conditions: "{{ wait.trigger.event.data.action == action_lock }}"
                sequence:
                  - service: lock.lock
                    data: {}
                    target:
                      entity_id: lock.front_door_lock
              - conditions: "{{ wait.trigger.event.data.action == action_leave }}"
                sequence:
                  - stop: ""
mode: single
```
