### ISSUE TITLE
tado climate unit incorrect 

### ISSUE THREAD

**Issue by mmibe** [home-assistant/frontend#18100]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Tado climate card dislaying farenheit when set to celcius in settings 

### Describe the behavior you expected

To display temperature and target temp in celcius when entities and settings all set to celcius 

### Steps to reproduce the issue

1.go to dashboard 
2. add card 
3. by entity 
4. select any tado climate entity 
5. save 
6.
...

### What version of Home Assistant Core has the issue?

2023-9-3

### What was the last working version of Home Assistant Core?

2023-9-3

### In which browser are you experiencing the issue with?

Firefox, chrome, ios

### Which operating system are you using to run this browser?

Windows 10 home

### State of relevant entities

```txt
hvac_modes:
  - 'off'
  - auto
  - heat
min_temp: 41
max_temp: 77
target_temp_step: 0.5
preset_modes:
  - away
  - home
current_temperature: 68
temperature: 61
current_humidity: 75
hvac_action: idle
preset_mode: home
offset_celsius: 0.1
offset_fahrenheit: 0.18
default_overlay_type: TADO_MODE
default_overlay_seconds: null
friendly_name: Aaron
supported_features: 17
```

### Problem-relevant frontend configuration

```yaml
type: custom:simple-thermostat
entity: climate.living_room
step_size: 1
control:
  hvac:
    heat: false
    'off':
      name: 'Off'
      icon: mdi:fan
    'on':
      name: Heat
      icon: mdi:fire
layout:
  mode:
    headings: false
    icons: true
    names: true
```

### Additional information

![image](https://github.com/home-assistant/frontend/assets/144707679/407c7238-dcab-48bf-89cc-71acbcec2176)
![image](https://github.com/home-assistant/frontend/assets/144707679/c373ad83-6815-4fee-a5ca-3d18b4715af7)

```[tasklist]
### Tasks
```
