### ISSUE TITLE
Custom Dashboard with Energy cards don't display data when viewed from the companion app

### ISSUE THREAD

**Issue by chuanguyen** [home-assistant/frontend#18141]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an energy bridge that is feeding live usage from my smart meter. This integration works and displays in the built-in energy tab fine on my phone and on my other devices.

However, I am trying to create a custom dashboard using the energy cards (As mentioned here https://www.home-assistant.io/dashboards/energy/).

The problem I'm running into is that the custom dashboard displays fine on my computer and on the browser on the phone. However, when viewed from the companion app, the cards fail to display any data.

A YAML snippet of my dashboard for the custom energy page is shown in the subsequent feilds. 

### Describe the behavior you expected

I expect that the custom dashboard using the energy cards displays the same information as the built-in energy dashboard when viewed from the companion app. 

### Steps to reproduce the issue

1. Create a new custom dashboard using the energy cards 
2. View the dashboard from the Home Assistant companion app
3. Energy cards show no data is present

### What version of Home Assistant Core has the issue?

2023.9.3

### In which browser are you experiencing the issue with?

Companion App (2023.9.2-full)

### Which operating system are you using to run this browser?

Android

### Problem-relevant frontend configuration

```yaml
- title: Energy
    path: home-energy
    icon: mdi:home-lightning-bolt
    subview: true
    badges: []
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: back
      - type: custom:energy-period-selector-plus
        card_background: false
        today_button: true
        prev_next_buttons: true
        compare_button_type: text
        today_button_type: text
        period_buttons:
          - day
          - week
          - month
          - year
          - custom
        compare_button_label: Compare
      - type: energy-usage-graph
      - type: custom:apexcharts-card
        header:
          show: true
          title: Outside Temperature
          show_states: true
          colorize_states: true
        graph_span: 24h
        span:
          start: day
        series:
          - entity: sensor.openweathermap_temperature
            color: orange
            stroke_width: 3
            type: line
            extend_to: now
      - type: energy-distribution
        link_dashboard: true
      - type: energy-sources-table
      - type: energy-carbon-consumed-gauge
      - type: gauge
        entity: sensor.house_power_demand_per_minute
        name: Current Power Draw
        min: 0
        max: 7500
        needle: false
```

### Additional information

I have encountered this bug on both the IOS and Andriod companion app. However, the browsers of each displayed my custom energy dashboard with proper data. 

**View of dashboard from the companion app (Bug present with the cards having no data):** 

![compansion_app_1_signal-2023-10-04-162430_005](https://github.com/home-assistant/frontend/assets/5003747/15557515-55f5-4e96-8a47-d28b67ced81a)

![compansion_app_2_signal-2023-10-04-162430_004](https://github.com/home-assistant/frontend/assets/5003747/d24ebaff-e122-4804-9913-d0cf1941fbe5)

**View of dashboard from a web browser on the same phone:** 

![browser_1_signal-2023-10-04-162430_003](https://github.com/home-assistant/frontend/assets/5003747/4aa75d0c-0851-4ed2-82d8-053f48a8b023)

![browser_2_signal-2023-10-04-162430_002](https://github.com/home-assistant/frontend/assets/5003747/fa92297c-dc21-4bef-b4cf-d2881c46688d)

**Comment by karwosts** [comment]
Can you try a view with only stock cards (remove the custom ones), so we can rule out any interference from those? 

I made a view of just this and it works fine in my android mobile app:

```
  - title: test
    path: test
    badges: []
    cards:
      - type: energy-usage-graph
      - type: energy-distribution
        link_dashboard: true
      - type: energy-sources-table
      - type: energy-carbon-consumed-gauge
 ```

**Comment by chuanguyen** [comment]
So I copied the view and removed the custom ones, and still can't view the energy data from the companion app. 

One other thing is I recently switched to the MariaDB add-in for Home Assistant. I can't see this being the problem, since the built-in energy dashboard and viewing from the browser displays properly. 

```
  - title: Energy-Test
    path: home-energy-test
    icon: mdi:home-lightning-bolt
    subview: false
    badges: []
    cards:
      - type: energy-date-selection
      - type: energy-usage-graph
      - type: energy-distribution
        link_dashboard: true
      - type: energy-sources-table
      - type: energy-carbon-consumed-gauge
```
