### ISSUE TITLE
Area card has improper button alignment when text wraps.

### ISSUE THREAD

**Issue by sebastianrasor** [home-assistant/frontend#18147]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/92653912/54b4a2f2-0794-475e-ab7a-fa1c65d2eacd)

### Describe the behavior you expected

I expected the area card buttons to not break visually. 

### Steps to reproduce the issue

1. Create an area card for an area with a long name.
2. Reduce the zoom of the home assistant page.

### What version of Home Assistant Core has the issue?

2023.10.1

### In which browser are you experiencing the issue with?

Chromium Version 112.0.5615.165 (Official Build, ungoogled-chromium)

### Which operating system are you using to run this browser?

Ubuntu 22.04.3 LTS

### Problem-relevant frontend configuration

```yaml
cards:
      - type: area
        area: master_bedroom
        navigation_path: /lovelace/master-bedroom
      - type: area
        area: master_bathroom
        navigation_path: /lovelace/master-bathroom
      - type: area
        area: living_room
        navigation_path: /lovelace/living-room
      - type: area
        area: office
        navigation_path: /lovelace/office
      - type: area
        area: hallway
        navigation_path: /lovelace/hallway
      - type: area
        area: kitchen
        navigation_path: /lovelace/kitchen
      - type: area
        area: dining_room
        navigation_path: /lovelace/dining-room
      - type: area
        area: guest_bathroom
        navigation_path: /lovelace/guest-bathroom
      - type: area
        area: guest_bedroom
        navigation_path: /lovelace/guest-bedroom
      - type: area
        area: utility_room
        navigation_path: /lovelace/utility-room
```
