### ISSUE TITLE
Calendar CSS Breaking

### ISSUE THREAD

**Issue by Smokey01966** [home-assistant/frontend#18144]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using a calendar inside of a conditional card calendar displays correctly on first load of the page, but after conditional card is turned off then back on, all CSS for the calendar is broken and if in the month overview can lead to the whole page freezing.

### Describe the behavior you expected

Calendar card to preserve proper formatting at all times.

### Steps to reproduce the issue

1. Create an input boolean named test
2. set up a test calendar (mine for the example code was o365_ian)
3. Build test page with this code
```
views:
  - type: panel
    title: Calendar Display
    path: calendar-display
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entity
            entity: input_boolean.test
          - type: conditional
            conditions:
              - entity: input_boolean.test
                state: 'on'
            card:
              initial_view: listWeek
              type: calendar
              entities:
                - calendar.o365_ian
```
4. Turn the test input boolean off and on

### What version of Home Assistant Core has the issue?

2023.10.1

### In which browser are you experiencing the issue with?

Microsoft Edge Version 117.0.2045.47 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11
