### ISSUE TITLE
pdf files are not opened when clicking a link

### ISSUE THREAD

**Issue by maweki** [home-assistant/frontend#18179]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I wanted to create a collection of manuals for the devices in our home and get rid of all the paper manuals. I've created a dashboard with links to the pdf files (stored in the local www folder).

When I click the link to the pdf, I am redirected to the home dashboard. But when opening the link in a new tab, the pdf is opened correctly.

[Bildschirmaufzeichnung vom 2023-10-10, 09-44-57.webm](https://github.com/home-assistant/frontend/assets/613272/41069be2-7749-452a-b16c-746fa9274127)

### Describe the behavior you expected

* click link
* pdf is either opened in the browser window

### Steps to reproduce the issue

1. create markdown or entities card with weblink to a pdf file
2. click the link

### What version of Home Assistant Core has the issue?

2023.10.

### In which browser are you experiencing the issue with?

Firefox 112.0.1, Chrome 112.0.5615.165

### Which operating system are you using to run this browser?

Fedora 38

### Problem-relevant frontend configuration

```yaml
cards:
      - type: markdown
        content: >-
          * [OKP K2 Robot Vacuum
          Cleaner](http://192.168.1.4:8123/local/manuals/OKP_K2.pdf)
        title: Kleingeräte
      - type: entities
        entities:
          - type: weblink
            url: /local/manuals/OKP_K2.pdf
            name: OKP K2 Robot Vacuum Cleaner
```
