### ISSUE TITLE
history-graph: inconsistency with font-weight

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#18262]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Add a new view with this card:
```
type: history-graph
show_names: false
hours_to_show: 24
entities:
  - entity: sun.sun
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/644af94d-f24e-45b4-b2cc-4ceb400da8af)
Note that `font-width` for the values "Above horizon", "Below horizon" is NOT bold.

Then select a Panel mode for the view.
Now the `font-width` is bold:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/d37f6546-a528-4df9-b56c-6972e69a9044)

Check a History page - it is not bold:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/660d0233-fd5a-476f-8692-bce4249087b9)

Then check with a `vertical-stack`:
```
      - type: vertical-stack
        cards:
          - type: history-graph
            show_names: false
            hours_to_show: 24
            entities:
              - entity: sun.sun
          - type: history-graph
            show_names: false
            hours_to_show: 24
            entities:
              - entity: sun.sun
```
Again not bold:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/c3b24add-1adc-47ad-8c18-9b5b8aa70c85)

And again bold in Panel mode:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/4aebfe23-eb79-45a0-b132-9f719a636718)

Then check with a `horizontal-stack`:
```
      - type: horizontal-stack
        cards:
          - type: history-graph
            show_names: false
            hours_to_show: 24
            entities:
              - entity: sun.sun
          - type: history-graph
            show_names: false
            hours_to_show: 24
            entities:
              - entity: sun.sun
```
It is bold:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/7fb1750a-5cdd-4151-b3e3-bff03932e52e)

And not bold in Panel mode:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/18f6a587-d46e-4530-8ff4-d8d522fd6b1b)

Is there any logic in this behaviour?

### Describe the behavior you expected

font-width should be same for all history-graph cards.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.10.2

### In which browser are you experiencing the issue with?

Chrome 118.0.5993.71 

### Which operating system are you using to run this browser?

Win10x64
