### ISSUE TITLE
history-graph: Tooltip: a long name may overflow

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#18261]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this code:
```
  - type: history-graph
    entities:
      - entity: sun.sun
        name: some very long long long long long long long long long name
```
A long name is nicely shown in a tooltip:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/a915eab1-f30b-4530-861e-1995bcf6a30f)

But if an entity does not have a friendly name containing spaces - then it looks like this (better to show with a dark theme):
![изображение](https://github.com/home-assistant/frontend/assets/71872483/43e294a3-28d9-4059-895b-51315e81832f)
A code to reproduce:
```
  - type: history-graph
    entities:
      - entity: sun.sun
        name: some_very_long_long_long_long_long_long_long_long_long_name
```

Here is a modded look:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/55753169-cbc4-45fa-83cf-e3639ee23be5)
To make it, I needed to apply this card-mod style:
```
              .chartTooltip .title {
                overflow-wrap: break-word;
              }
```
I think this may be implemented in "ha-chart-base.ts":
https://github.com/home-assistant/frontend/blob/d88831b7192de728351e31433bfa5cdc6775b8ce/src/components/chart/ha-chart-base.ts#L434
```
      .chartTooltip .title {
        text-align: center;
        font-weight: 500;
        direction: ltr;
        overflow-wrap: break-word;
      }
```

### Describe the behavior you expected

A long name w/o spaces is wrapped.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.10.2

### In which browser are you experiencing the issue with?

Chrome 118.0.5993.71 

### Which operating system are you using to run this browser?

Win10x64
