### ISSUE TITLE
List with dicts attribute not displayed correctly in devtools > states on nightly

### ISSUE THREAD

**Issue by TheFes** [home-assistant/frontend#18343]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If an attribute of an entity is a list with dicts (like for the weather forecasts) it is not correctly displayed in devtools > states
![image](https://github.com/home-assistant/frontend/assets/28803438/779c59af-0716-47b9-ba37-f557a7127bbd)

It displays `[object Object]` for each list item

### Describe the behavior you expected

Like this on 2023.10.5
![image](https://github.com/home-assistant/frontend/assets/28803438/4a131421-f3ee-44e0-80d6-5a6f93b6e0e3)

### Steps to reproduce the issue

1. Open devtools > states and search for a `weather` entity which still has a forecast attribute
2. If not available, create a test template sensor like this
```yaml
template:
    - sensor:
        - unique_id: 27d4477a-cd06-4198-b7ef-6c297841a9c9
          name: Test list dict
          state: TEST
          attributes:
            test_list_dict: >
              {{ [ dict(test='test' , test2='test2'), dict(test='test' , test2='test2')] }}
```
3. Open devtools > states and look for the template entity 

### What version of Home Assistant Core has the issue?

2023.11.0.dev20231023

### What was the last working version of Home Assistant Core?

2023.10.5

### In which browser are you experiencing the issue with?

Google Chrome 118.0.5993.89

### Which operating system are you using to run this browser?

Windows 10
