### ISSUE TITLE
"AQI" & "pH" device classes: cannot specify "" uom

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#18439]
### The problem

Consider this template sensor:
```
template:
  - sensor:
      - name: testing_device_class_aqi
        device_class: aqi
        state: >-
          {% set INPUT_NAME = "input_number.testing_device_class_aqi" -%}
          {{ states(INPUT_NAME) }}
```
and then this history-graph:
![image](https://github.com/home-assistant/core/assets/71872483/c2ca8a8f-bf56-4c85-a81a-d3586429fe49)

If uom is added:
```
      - name: testing_device_class_aqi
        device_class: aqi
        unit_of_measurement: ""
        state: >-
          {% set INPUT_NAME = "input_number.testing_device_class_aqi" -%}
          {{ states(INPUT_NAME) }}
```
then the graph is correct:
![image](https://github.com/home-assistant/core/assets/71872483/d7989707-ff84-45d0-9606-944f344a23b1)
But there is an error in Log:
2023-09-29 19:14:30.179 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.testing_device_class_aqi (<class 'homeassistant.components.template.sensor.SensorTemplate'>) is using native unit of measurement '' which is not a valid unit for the device class ('aqi') it is using; expected one of ['no unit of measurement']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

The same is for the `pH` device_class.

### What version of Home Assistant Core has the issue?

2023.9.3

### What type of installation are you running?

Home Assistant Container
