### ISSUE TITLE
wrong displaying of overlay images in a picture elements card in companion app and chrome browser

### ISSUE THREAD

**Issue by bewenne** [home-assistant/frontend#18452]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am using a picture elements card to display my floor plan and control all my lights, climate and shutters. For the lights I am using image elements with mixed-blend-mode: lighten which are then overlayed over the basic picture. It worked very well until the October update. All images are the same size and positioning and the code has not changed. I am now seeing a weird cut-off overlay in the upper half of the picture elements card. The expected "light on" image is not being fully displayed. It is observed in chrome browser (edge and firefox I could not reproduce this behavior) but also in the companion app (android, s23ultra and tab8). The behavior also seems to change bei zooming into the image/dashboard. With a certain zoom suddenly the image changes to the correct overlay and everything is fine. But in the standard zoom in which the dashboard starts there will always be a broken overlay image. I also tried to go back to the September version of HA but behavior did not change.

### Describe the behavior you expected

The image should overlay the basic image to the full extend with the correct positioning.

### Steps to reproduce the issue

1. create picture elements card
2. "dark" floorplan as basic image
3. overlay of "light on" floorplan state-image with "mixed-blend-mode: lighten"
4. if light is "off" a "fully transparent" image is overlayed

If the light is turned on via state-icon the overlay image is displayed incorrectly (seemingly as a new "card" with round edges but not placed fully over the basic image; but positioning by yaml is exactly the same)
With different zooming factors this behavior seems to change:
The "new card" is moving to a different position if zooming is changed
At certain zoom stages behavior also can suddenly jump back to normal

Interesting also:
I use the same cards in a vertical stack for all my floors and the issue is only being seen on the very top one!
If I change the view to one of the lower cards as a single card in a seperate dashboard then the issue will be the same, so no code issue only on the very top one.

I hope this can help to resolve this issue. This is quite a premium feature of HA which cost some effort to get working and I was very happy how good it was running for more than half a year now. But with this issue it does not look so premium any more unfortunately. At least state-icon buttons etc. for house control ist still ok.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.10.5

### In which browser are you experiencing the issue with?

chrome 118.0.5993.118

### Which operating system are you using to run this browser?

win11

### State of relevant entities

```txt
light is switched on
overlay image should be shown but is only shown partially
```

### Problem-relevant frontend configuration

```yaml
views:
  - theme: Backend-selected
    title: home
    subview: false
    badges: []
    cards:
      - type: picture-elements
        image: /local/haus-interaktiv/eg/format169/klein/eg169nacht.jpg #night image
        style:
          top: 50%
          left: 50%
          height: 100%
          width: 100%
        elements:
          - type: image
            action: none
            entity: sun.sun
            state_image:
              above_horizon: /local/haus-interaktiv/eg/format169/klein/eg169tagv2.jpg #day image
              below_horizon: /local/haus-interaktiv/eg/format169/klein/eg169nacht.jpg #night image
            style:
              top: 50%
              left: 50%
              height: 100%
              width: 100%
          - type: image
            entities:
              - light.dimmbares_licht_gaste_wc
            tap_action:
              action: none
            hold_action:
              action: none
            entity: light.dimmbares_licht_gaste_wc
            state_image:
              'on': /local/haus-interaktiv/eg/format169/klein/eg169gaestewcan.jpg #overlay light on image
              'off': /local/haus-interaktiv/eg/format169/klein/transparent.jpg #transparent overlay to show day or night image
            style:
              mix-blend-mode: lighten
              top: 50%
              left: 50%
              height: 100%
              width: 100%
          - type: state-icon
            entity: light.dimmbares_licht_gaste_wc
            icon: mdi:lightbulb
            style:
              left: 31%
              top: 29.4%
              border-radius: 50%
              text-align: center
              background-color: rgba(255, 255, 255, 0.3)
              transform: translate(-50%,-50%) scale(0.7,0.7)
            tap_action:
              action: toggle
            hold_action:
              action: more-info
```
