### ISSUE TITLE
Tile Card Fan Speed clicks random speed.

### ISSUE THREAD

**Issue by NonaSuomy** [home-assistant/frontend#18475]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I click on speed 1 it clicks 3 randomly. Then after that, it seems to operate fine. Click speed 1 again it obliges and goes to 1 instead of jumping to 3.

I first thought it was just fat finger clicks but I tested it in the browser with the mouse and it jumped to 3 instead of 1.

```yaml
type: custom:mod-card
card_mod:
  style:
    hui-vertical-stack-card $: |
      div#root > * {
        --ha-card-border-width: 0px;
      }
    .: |
      hui-vertical-stack-card {
        --vertical-stack-card-margin: 3px;
      }
      ha-card {
        background-color: rgba(50,50,50,0.4);
        box-shadow: var(--ha-card-box-shadow);
        border: var(--ha-card-border-color,var(--divider-color,#e0e0e0)) solid var(--ha-card-border-width,1px);
        --ha-card-header-color: white;
        --ha-card-background: rgba(50,50,50,0.4);
      }
card:
  type: vertical-stack
  title: Primary Bedroom
  cards:
    - type: custom:mod-card
      card_mod:
        style:
          hui-horizontal-stack-card$: |
            hui-tile-card {
              margin-left: 0px !important;
              margin-right: 0px !important;
              margin-bottom: 0px !important;
              width: 150%;
              flex: auto !important;
            }
            hui-button-card {
              margin-left: 10px !important;
              margin-right: 10px !important;
              margin-top: 63px !important;
              margin-bottom: 0px !important;
              height: 43px;
              width: 115px;
              flex: auto !important;
            }
          .: |
            ha-card {

            }
      card:
        type: horizontal-stack
        cards:
          - type: tile
            entity: fan.ifan04_bedroom_fan
            name: Ceiling Fan & Light
            features:
              - type: fan-speed
          - type: button
            entity: light.ifan04_bedroom_light
            name: Ceiling Fan Light
            show_state: false
            show_name: false
    - type: tile
      entity: light.sengled_e11_n1ea_light
      name: Bed Lamp
```

![image](https://github.com/home-assistant/frontend/assets/1906575/27d7b1b0-d803-4faf-8e3f-3049ffb90b79)

Would be great if there was a 5th optional button where you could tack the fan light entity onto the end of the speed buttons as well.

### Describe the behavior you expected

It to select the right option on clicking.

### Steps to reproduce the issue

1. Add the YAML Code
2. At a random time click one of the buttons
3. Button clicks not the right button you pushed.
...

### What version of Home Assistant Core has the issue?

2023.11.0b2

### What was the last working version of Home Assistant Core?

Been like this since I started using it. Multiple versions ago first release of the feature.

### In which browser are you experiencing the issue with?

Chrome is up to date Version 118.0.5993.118 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by ildar170975** [comment]
Is it the ONLY part of a code related to the issue?
```
          - type: tile
            entity: fan.ifan04_bedroom_fan
            name: Ceiling Fan & Light
            features:
              - type: fan-speed
```
If yes, then probably there is no need to post rest of it.
