### ISSUE TITLE
hide_state in tile not working

### ISSUE THREAD

**Issue by EvertJob** [home-assistant/frontend#18551]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I would like to hide the state inside a tile card. There for I use the `hide_state: true` option. That is not hiding the state, nothing visible at all.

### Describe the behavior you expected

I would expect that the state is hidden

### Steps to reproduce the issue

1. Create tile card
2. set `hide_state` to true
3. Nothing happens

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Safari Version 17.1 (19616.2.9.11.6)

### Which operating system are you using to run this browser?

MacOS Sonoma 14.1

### State of relevant entities

```
sensor.012030387009003220_bsh_common_setting_powerstate
BSH.Common.EnumType.PowerState.Off

device_class: home_connect_alt__settings
icon: mdi:tune
friendly_name: Siemens Dishwasher - Power State

```

### Problem-relevant frontend configuration

```yaml
service: browser_mod.popup
data:
  browser_id: "{{ browser_id }}"
  dismissable: true
  content:
    type: custom:tabbed-card
    options: {}
    tabs:
      - card:
          type: tile
          entity: select.383020390101000527_001_bsh_common_setting_powerstate
          hide_state: true
          vertical: true
          name: Oven aanzetten op 200° voor 20 minuten
          tap_action:
            action: call-service
            service: script.oven_20_minuten
          card_mod:
            style: |
              ha-card {
                border: none;
              }
        attributes:
          label: Oven
          icon: mdi:toaster-oven
      - card:
          type: vertical-stack
          cards:
            - type: tile
              entity: sensor.012030387009003220_bsh_common_setting_powerstate
              name: Eco programma 50°
              tap_action:
                action: call-service
                service: script.vaatwasser_automatisch_starten
              card_mod:
                style: |
                  ha-card {
                    border: none;
                  }
            - type: tile
              entity: sensor.012030387009003220_bsh_common_setting_powerstate
              name: Kort programma 45°
              tap_action:
                action: call-service
                service: script.vaatwasser_kort_programma
              card_mod:
                style: |
                  ha-card {
                    border: none;
                  }
        attributes:
          label: Vaatwasser
          icon: mdi:dishwasher
  right_button: Sluiten
  timeout: 30000000
  card_mod:
    style:
      ha-dialog$: |
        div.mdc-dialog div.mdc-dialog__scrim {
          backdrop-filter: blur(3px);
        }
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_
