### ISSUE TITLE
Cannot open dashboard view with space in URL

### ISSUE THREAD

**Issue by jessemcdowell** [home-assistant/frontend#18554]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you create a view with a space in the url, you can't open the view from the dashboard.

Why would you create a view with a space in the url you ask? I didn't intend to, but it happened automatically because I modified a dashboard on my phone.

### Describe the behavior you expected

I think any of these options would be an improvement:

- make it impossible to create a view with a space in the url
- give some kind of visual feedback if you create a view with a space in the url
- encode the url so that you can select a view with a space in the url

### Steps to reproduce the issue

1. Add a new view to an existing / working dashboard
2. Give the view the url "bad " (without quotes, notice the trailing space)
4. Save the dashboard
5. click the new tab

Behavior: the tab gets highlighted and the url changes, but the view doesn't change

Note: you can still select the view in edit mode, but the behavior in the normal (saved) mode is very confusing.

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Google Chrome 119.0.6045.105, FireFox 119.0, Fully Kiosk Browser

### Which operating system are you using to run this browser?

Windows 11, Android

### Problem-relevant frontend configuration

```yaml
views:
  - title: Good
    icon: mdi:emoticon-happy-outline
    badges: []
    cards:
      - type: markdown
        content: This view works :)
  - title: Bad
    path: 'bad '
    icon: mdi:emoticon-devil-outline
    badges: []
    cards:
      - type: markdown
        content: This view doesn't work :(
```
```


### Javascript errors shown in your browser console/inspector

```txt
Nothing is emitted to the developer console when clicking the "bad" view
```
