### ISSUE TITLE
High CPU / RAM in browser Tab when Editing Automations in Visual Editor

### ISSUE THREAD

**Issue by RobusX** [home-assistant/frontend#18557]
### The problem

When a more comprehensive automation (for ex. with Jinja2 template conditions/triggers) is opened for editing in the Visual Editor, it causes high CPU usage (15-20% only in this tab !) in Windows 10 browsers such as Firefox and Chrome.
Similar behaviour was noticed when Via Android Companion app. 

This can lead to the browser becoming unresponsive and requiring the tab to be killed. 
If you manage to switch to editing in YAML mode very quickly, you can avoid the problem. 
However, the issue is particularly annoying because you can only switch to YAML mode via the Visual Editor window first. 

Therefore, please resolve this bug, as it's affecting more and more automations with highest HA versions and causing high CPU usage when editing in the Visual Editor.
Automation sample below.

### What version of Home Assistant Core has the issue?

core-2023.10.5

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

Automation Editor

### Link to integration documentation on our website

(https://www.home-assistant.io/docs/automation/editor/)

### Example YAML snippet

```yaml
alias: Heating -> Klima Mitsu All Day Heating ON/OFF
description: Control climate settings based on time of day
trigger:
  - platform: state
    entity_id: input_boolean.turn_on_off_klima_mitsu
    to: "on"
    id: "on"
  - platform: time
    at: "22:00:00"
    id: "22"
  - platform: time
    at: "06:00:00"
    id: "6"
  - platform: time
    at: "14:00:00"
    id: "14"
  - platform: time
    at: "16:00:00"
    id: "16"
  - platform: time
    at: "20:00:00"
    id: "20"
  - platform: state
    entity_id: climate.klima_mitsu
    to: heat
    id: heat
    for: "00:00:04"
  - platform: state
    entity_id: climate.klima_mitsu
    to: cool
    id: cool
    for: "00:00:04"
  - platform: state
    entity_id: climate.klima_mitsu
    to: fan_only
    id: fan_only
    for: "00:00:04"
  - platform: time_pattern
    minutes: /20
    id: time
  - platform: numeric_state
    entity_id: sensor.out1meter_temperature
    above: 16
    for: "01:00:00"
    id: above_16C
  - platform: template
    value_template: >
      {% set temperature = states('sensor.out1meter_temperature') | float %} {{
      temperature < 16 and (as_timestamp(now()) -
      as_timestamp(states.sensor.out1meter_temperature.last_changed)) > 1800 }}
    id: time
  - platform: template
    value_template: "{{ state_attr('climate.klima_mitsu', 'current_temperature') > 0 }}"
    id: curr
condition: []
action:
  - choose:
      - conditions:
          - "{{ trigger.id == 'on' }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ is_state('switch.shelly_klima', 'on') }}"
          - condition: template
            value_template: "{{ states('sensor.shelly_klima_power') | float(0) < 10.0 }}"
        sequence:
          - service: climate.turn_on
            target:
              entity_id: climate.klima_mitsu
            data: {}
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              hvac_mode: fan_only
          - service: climate.set_fan_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              fan_mode: "4"
          - service: input_boolean.turn_on
            entity_id: input_boolean.last_fan_only_mode_change
          - delay: "00:03:00"
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              hvac_mode: heat
          - service: climate.set_swing_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              swing_mode: swing
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.set_hvac_fan_mode_based_on_temperature
            data_template:
              current_temp: "{{ states('sensor.in2meter_temperature') }}"
              target_temp: "{{ state_attr('climate.klima_mitsu', 'temperature') }}"
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
      - conditions:
          - "{{ trigger.id == 'on' }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('switch.shelly_klima', 'on') }}"
        sequence:
          - condition: template
            value_template: |
              {{ is_state('climate.klima_mitsu', 'fan_only') }} 
          - condition: template
            value_template: >
              {{
              (as_timestamp(states.input_boolean.last_fan_only_mode_change.last_changed)
              -
              as_timestamp(states.input_boolean.klima_heat_trigger_executed.last_changed))
              > 0 and
                 (as_timestamp(states.input_boolean.last_fan_only_mode_change.last_changed) -
                  as_timestamp(states.input_boolean.klima_heat_trigger_executed.last_changed)) > 600 }}              
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              hvac_mode: fan_only
          - service: climate.set_fan_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              fan_mode: "4"
          - service: input_boolean.turn_on
            entity_id: input_boolean.last_fan_only_mode_change
          - delay: "00:03:00"
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              hvac_mode: heat
          - service: climate.set_swing_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              swing_mode: swing
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.set_hvac_fan_mode_based_on_temperature
            data_template:
              current_temp: "{{ states('sensor.in2meter_temperature') }}"
              target_temp: "{{ state_attr('climate.klima_mitsu', 'temperature') }}"
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
          - condition: template
            value_template: |
              - "{{ is_state('climate.klima_mitsu', 'heat') }}"
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              hvac_mode: heat
          - service: climate.set_swing_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              swing_mode: swing
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.set_hvac_fan_mode_based_on_temperature
            data_template:
              current_temp: "{{ states('sensor.in2meter_temperature') }}"
              target_temp: "{{ state_attr('climate.klima_mitsu', 'temperature') }}"
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
      - conditions:
          - "{{ trigger.id == 'on' }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('switch.shelly_klima', 'off') }}"
        sequence:
          - service: switch.turn_on
            data:
              entity_id: switch.shelly_klima
      - conditions:
          - condition: trigger
            id: curr
        sequence:
          - service: climate.set_temperature
            data_template:
              temperature: "{{ trigger.to_state.attributes.current_temperature }}"
              entity_id: climate.klima_mitsu
      - conditions:
          - "{{ now().hour >= 22 and now().hour < 6 }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ states('climate.klima_mitsu') == 'heat' }}"
          - condition: template
            value_template: "{{ states('sensor.shelly_klima_power') | float(0) > 10.0 }}"
          - condition: template
            value_template: >-
              {{ not is_state_attr('climate.klima_mitsu', 'hvac_mode',
              'fan_only') }}
        sequence:
          - service: climate.set_fan_mode
            target:
              entity_id: climate.klima_mitsu
            data:
              fan_mode: "4"
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.adjust_ac_target_temperature
            data: {}
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
      - conditions:
          - "{{ now().hour >= 6 and now().hour < 7 }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ states('climate.klima_mitsu') == 'heat' }}"
          - condition: template
            value_template: "{{ states('sensor.shelly_klima_power') | float(0) > 10.0 }}"
          - condition: template
            value_template: >-
              {{ not is_state_attr('climate.klima_mitsu', 'hvac_mode',
              'fan_only') }}
        sequence:
          - service: script.set_hvac_fan_mode_based_on_temperature
            data_template:
              current_temp: "{{ states('sensor.in2meter_temperature') }}"
              target_temp: "{{ state_attr('climate.klima_mitsu', 'temperature') }}"
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.adjust_ac_target_temperature
            data: {}
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
      - conditions:
          - "{{ now().hour >= 7 and now().hour < 14 }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ states('climate.klima_mitsu') == 'heat' }}"
          - condition: template
            value_template: "{{ states('sensor.shelly_klima_power') | float(0) > 10.0 }}"
          - condition: template
            value_template: >-
              {{ not is_state_attr('climate.klima_mitsu', 'hvac_mode',
              'fan_only') }}
        sequence:
          - service: script.set_hvac_fan_mode_based_on_temperature
            data_template:
              current_temp: "{{ states('sensor.in2meter_temperature') }}"
              target_temp: "{{ state_attr('climate.klima_mitsu', 'temperature') }}"
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.adjust_ac_target_temperature
            data: {}
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
      - conditions:
          - "{{ now().hour >= 14 and now().hour < 16 }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ states('climate.klima_mitsu') == 'heat' }}"
          - condition: template
            value_template: "{{ states('sensor.shelly_klima_power') | float(0) > 10.0 }}"
          - condition: template
            value_template: >-
              {{ not is_state_attr('climate.klima_mitsu', 'hvac_mode',
              'fan_only') }}
        sequence:
          - service: script.set_hvac_fan_mode_based_on_temperature
            data_template:
              current_temp: "{{ states('sensor.in2meter_temperature') }}"
              target_temp: "{{ state_attr('climate.klima_mitsu', 'temperature') }}"
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.adjust_ac_target_temperature
            data: {}
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
      - conditions:
          - "{{ now().hour >= 16 and now().hour < 20 }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ states('climate.klima_mitsu') == 'heat' }}"
          - condition: template
            value_template: "{{ states('sensor.shelly_klima_power') | float(0) > 10.0 }}"
          - condition: template
            value_template: >-
              {{ not is_state_attr('climate.klima_mitsu', 'hvac_mode',
              'fan_only') }}
        sequence:
          - service: script.set_hvac_fan_mode_based_on_temperature
            data_template:
              current_temp: "{{ states('sensor.in2meter_temperature') }}"
              target_temp: "{{ state_attr('climate.klima_mitsu', 'temperature') }}"
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.adjust_ac_target_temperature
            data: {}
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
      - conditions:
          - "{{ now().hour >= 20 and now().hour < 22 }}"
          - condition: template
            value_template: "{{ states('sensor.out1meter_temperature') | float(0) <= 16 }}"
          - condition: template
            value_template: "{{ is_state('input_boolean.turn_on_off_klima_mitsu', 'on') }}"
          - condition: template
            value_template: "{{ states('climate.klima_mitsu') == 'heat' }}"
          - condition: template
            value_template: "{{ states('sensor.shelly_klima_power') | float(0) > 10.0 }}"
          - condition: template
            value_template: >-
              {{ not is_state_attr('climate.klima_mitsu', 'hvac_mode',
              'fan_only') }}
        sequence:
          - service: script.set_hvac_fan_mode_based_on_temperature
            data_template:
              current_temp: "{{ states('sensor.in2meter_temperature') }}"
              target_temp: "{{ state_attr('climate.klima_mitsu', 'temperature') }}"
          - service: script.set_climate_temperature_heat
            data: {}
          - service: script.adjust_ac_target_temperature
            data: {}
          - service: input_boolean.turn_on
            entity_id: input_boolean.klima_heat_trigger_executed
      - conditions:
          - condition: template
            value_template: |
              {{ (is_state('switch.shelly_klima', 'unavailable')) or
                 (is_state('climate.klima_mitsu', 'unavailable'))
                 }}
        sequence:
          - service: media_player.volume_set
            data:
              volume_level: >-
                {{ 0.11 if (now().hour >= 21 and now().minute >= 30) or
                now().hour < 6 else 0.16 }}
            target:
              entity_id:
                - media_player.echo_kitchen_l
                - media_player.echo_cellar_l
          - service: notify.alexa_media
            data:
              target:
                - media_player.echo_kitchen_l
                - media_player.echo_cellar_l
              message: >-
                Klima Heating Attention! Some switches are in unavailable state!
                Check situation !
              data:
                type: tts
                method: all
trace:
  stored_traces: 20
mode: queued
```

### Additional information

![image](https://github.com/home-assistant/core/assets/122005348/4e26f7ce-e5d6-4234-9db3-7d7e93840dc4)
![image](https://github.com/home-assistant/core/assets/122005348/893e37d5-c789-4f74-8cd8-01973e2b63bd)
