### ISSUE TITLE
Inconsistent treatment of duration sensor

### ISSUE THREAD

**Issue by jamesonuk** [home-assistant/frontend#18561]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have setup the speedtest integration and adding the ping sensor to various cards results in different displays.   Only the entity and sensor card seem to pick up the unit of measure where as the others (tile, entities, glance) don't and end up showing the value in seconds.

Clicking through on the cards that do so the right value also shows this raw value

![image](https://github.com/home-assistant/frontend/assets/1040621/ef52b199-1b69-4703-9124-e0681f08eb3a)

### Describe the behavior you expected

I would expect all cards to display the same and pick up unit of measure.  In this case I would expect them all to say 8ms not 0.008

### Steps to reproduce the issue

1. Install and configure speedtest integration (although I suspect this will be the same for any duration sensor)
2. Add ping sensor to different cards

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Google Chrome 119.0.6045.106

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
State is 8
Attributes are
state_class: measurement
server_name: London
server_country: United Kingdom
server_id: "40788"
unit_of_measurement: ms
attribution: Data retrieved from Speedtest.net by Ookla
device_class: duration
icon: mdi:speedometer
friendly_name: SpeedTest Ping
```

### Problem-relevant frontend configuration

```yaml
title: Testing
views:
  - title: ping
    path: ping
    badges: []
    cards:
      - type: entity
        entity: sensor.speedtest_ping
      - type: tile
        entity: sensor.speedtest_ping
      - type: entities
        entities:
          - entity: sensor.speedtest_ping
      - type: glance
        entities:
          - entity: sensor.speedtest_ping
      - graph: line
        type: sensor
        detail: 1
        entity: sensor.speedtest_ping
```
