### ISSUE TITLE
Double click with mouse intermittent compared to double tap

### ISSUE THREAD

**Issue by a-nicholls** [home-assistant/frontend#18585]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

having an entities card with a double tap action e.g.

```
double_tap_action:
  action: call-service
  confirmation:
    text: Are you sure you want to restart?
  service: script.restart
```

when you use the mouse to double click on the item instead of coming up with the confirmation dialog you get the entity information dialog like you've single clicked/tapped. very occassionally it works but if i have a touch screen the double tap works consistently. The operating system has typical double click response rate and tested in control panel item and works in there.

Tested on Edge 119.0.2151.44 and Firefox 119.0.1 (x64) on WIndows 11 Surface Pro 8

### Describe the behavior you expected

I expect the double click with mouse to be run the double_tap action as the double tap option with the touch screen on the same entity.

### Steps to reproduce the issue

1.Create entity with double tap action
```
double_tap_action:
  action: call-service
  confirmation:
    text: Are you sure you want to restart?
  service: script.restart
```

2. Try double clicking on new entity - it should come up with confirmation dialog box. Compare this with double tapping

### What version of Home Assistant Core has the issue?

core-2023.11.1

### In which browser are you experiencing the issue with?

Microsoft Edge 119.0.2151.44 and Mozilla Firefox 119.0.1 (x64) 

### Which operating system are you using to run this browser?

Windows 11 23H2
