### ISSUE TITLE
What entity type should I use for radiation?

### ISSUE THREAD

**Issue by buteomont** [home-assistant/frontend#18641]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I built a radiation detector to keep track of the background radiation. When integrating it into HA, the closest device class I could find was "Illuminance".  However, I get a lot of warnings in the log that say "**_Entity sensor.radioactivity_per_second (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'Clks/Sec' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx']_**".

What device class should I use for background radiation, and why does HA care what I use for units?  If I have to use a pre-defined unit, that seems very restrictive.

### Describe the behavior you expected

No warning message.

### Steps to reproduce the issue

1. Add an entity of device_class "Illuminance" and use a unit_of_measurement of "clicks/sec".
2. Check the HA log.
3. That's it.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.10.5 Supervisor 2023.10.1 Operating System 11.0 Frontend 20231005.0 - latest

### In which browser are you experiencing the issue with?

Doesn't matter

### Which operating system are you using to run this browser?

Doesn't matter

### Problem-relevant frontend configuration

```yaml
- sensor:
      unique_id: "radioact-per-second"
      state_topic: "buteomont/house/geigercounter/cps"
      name: "Radioactivity Per Second"
      device_class: "illuminance"
      qos: 0
      unit_of_measurement: "Clks/Sec"
```
