### ISSUE TITLE
Order, quantity and type of cards in dashboard may affect behavior of apexcharts-card with brush

### ISSUE THREAD

**Issue by jvanoosterhout** [home-assistant/frontend#18676]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With some layouts of a dashboard, the a-axis of the main chart of an apexcharts-card with brush gets broken. Strangely, having multiple and exactly the same apexcharts-card with brush on the same dashboard, some may work correctly, others may not. 

broken x-axis:
![image](https://github.com/home-assistant/frontend/assets/18647330/4765c74a-6b29-4acd-8099-7be4e5bfd073)

My own dashboard:
![image](https://github.com/home-assistant/frontend/assets/18647330/1a603252-2e96-45a5-8aae-f732adbece4a)

### Describe the behavior you expected

the a-axis of the main chart of an apexcharts-card with brush remains as-is:

Normal x-axis:
![image](https://github.com/home-assistant/frontend/assets/18647330/3f644216-06dc-43a6-b0fc-5d176f14f229)

for my own dashboard:
![image](https://github.com/home-assistant/frontend/assets/18647330/639ae710-5bd4-4ecf-a85d-7eba7089923d)

### Steps to reproduce the issue

To trigger the x-axis issue: 
1. Make a new dashboard with the mini example of the configuration
2. Refreshing the page when viewing this new default_view dashboard and observe the broken x-axis (with this example is may take a few refreshes, with my own dashboard it occurs directly)

To resolve the x-axis issue:
4. Go to the "test2" view dashboard
5. Refreshing this page 
6. Go back to the default view dashboard and observe a normal x-axis 

### What version of Home Assistant Core has the issue?

2023.11.2

### In which browser are you experiencing the issue with?

 Microsoft Edge for Business Version 119.0.2151.58; Google Chrome Version 119.0.6045.159; App versie 2023.7 (not for the mini example of the configuration, but for mij own dashboard); Chromium Versie 113.0.5672.95

### Which operating system are you using to run this browser?

Windows 10 Enterprise 19045.3570; IOS 16.6; Raspbian GNU/Linux 11 (bullseye)

### State of relevant entities

```txt
irrelevant
```

### Problem-relevant frontend configuration

```yaml
title: test
views:
  - path: default_view
    icon: mdi:test-tube
    badges: []
    cards:
      - type: custom:apexcharts-card
        graph_span: 10d
        header:
          show: true
          title: test
          show_states: true
          colorize_states: true
        experimental:
          brush: true
        brush:
          selection_span: 2d
        series:
          - entity: sensor.sun_next_rising
            curve: stepline
            name: test
            stroke_width: 2
            show:
              legend_value: false
              in_header: true
              in_chart: true
              extremas: true
              in_brush: true
            color: DarkCyan
      - type: history-graph
        entities:
          - entity: sensor.sun_next_rising
          - entity: sun.sun
          - entity: sensor.sun_next_dawn
          - entity: sensor.sun_next_noon
      - type: history-graph
        entities:
          - entity: sensor.sun_next_rising
          - entity: sun.sun
          - entity: sensor.sun_next_dawn
          - entity: sensor.sun_next_noon
      - type: custom:apexcharts-card
        graph_span: 10d
        header:
          show: true
          title: test
          show_states: true
          colorize_states: true
        experimental:
          brush: true
        brush:
          selection_span: 2d
        series:
          - entity: sensor.sun_next_rising
            curve: stepline
            name: test
            stroke_width: 2
            show:
              legend_value: false
              in_header: true
              in_chart: true
              extremas: true
              in_brush: true
            color: DarkCyan
      - type: custom:apexcharts-card
        graph_span: 10d
        header:
          show: true
          title: test
          show_states: true
          colorize_states: true
        experimental:
          brush: true
        brush:
          selection_span: 2d
        series:
          - entity: sensor.sun_next_rising
            curve: stepline
            name: test
            stroke_width: 2
            show:
              legend_value: false
              in_header: true
              in_chart: true
              extremas: true
              in_brush: true
            color: DarkCyan
  - title: test2
    path: test2
    badges: []
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: light.kiki_water
```

### Javascript errors shown in your browser console/inspector

```txt
not applicable
```

### Additional information

I first thought it was an apexcharts-card issue that had to be reported with that integration, though the issue does not occur consistently with one apexcharts-card on different locations within the dashboard, or with more or less other cards. Even with multiple, identical apexcharts-cards on one dashboard, some may show the issue, others may not. I found no consistency yet in the effect of shuffling, adding, deleting cards. After having this issue for months, I just identified this week how to trigger and isolate the issue, I hope more experience people can isolate it further to tackle the issue and fix the bug.
