### ISSUE TITLE
Gradient attributes on the Trend binary sensor entity dialog should be decimal

### ISSUE THREAD

**Issue by keithr59** [home-assistant/frontend#18701]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The gradient attributes of the Trend binary sensor entity are stored in decimal

![Entity](https://github.com/home-assistant/frontend/assets/93706044/bfc1969b-c0df-4602-9bc1-fef453b3644e)

But on the Trend binary sensor entity dialog they are displayed as integers.

![Dialog](https://github.com/home-assistant/frontend/assets/93706044/2f92e9e2-dcf5-44a7-a0ca-c0889f9cea7d)

### Describe the behavior you expected

I expect the gradient attributes on the Trend binary sensor entity dialog to be displayed in decimal

### Steps to reproduce the issue

1. Configure a Trend binary sensor

```
- platform: trend
  sensors:
    heating_temperature_falling:
      entity_id: sensor.heating_current_temperature
      sample_duration: 7200
      max_samples: 60
      min_gradient: -0.00007
      device_class: cold
      friendly_name: Heating Temperature Falling
```

2. Click on binary sensor entity to display dialog

### What version of Home Assistant Core has the issue?

2023.11.0

### In which browser are you experiencing the issue with?

Edge, Opera

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

![Entity](https://github.com/home-assistant/frontend/assets/93706044/ad102c90-bd2c-4cb0-8b57-56ce915b1cb3)

### Problem-relevant frontend configuration

Frontend 20231030.1
