### ISSUE TITLE
Cannot get past server address window on Android companion app - only shows blank white screen

### ISSUE THREAD

**Issue by Traxtar928** [home-assistant/frontend#18754]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Cannot get to login screen using the android companion app.

App opens normally and finds local server IP address. When the address is selected, the app shows a white screen.

Home Assistant server can be accessed without any issues from Chrome browser on the same device... Firefox is also working.

Device is a Beelink GT King Android TV box running Android 9.

### Describe the behavior you expected

After selecting the IP address of the Home Assistant server, the login screen is expected to display.

### Steps to reproduce the issue

1. Install app
2. Open app
3. Enter network address (local or nabu casa)
4. Blank white screen is presented indefinitely with no error messages.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

None - all browsers work fine accessing Home Assistant

### Which operating system are you using to run this browser?

Android 9

### State of relevant entities

```txt
No relevant entities. Mobile App integration does not show an added device for the Android TV box.
```

### Problem-relevant frontend configuration

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
history:
mobile_app:
cloud:
ios:
my:
#media_source:
homeassistant:
  auth_providers:
    - type: homeassistant
#  media_dirs:
#    local: /media/Music
#  name: Home
#  latitude: 
#  longitude: 
#  unit_system: 
#  time_zone: 
#  external_url: nabucasa.link
#  internal_url: localip.link

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: null
#    ssl_certificate: null
#    ssl_key: null

# Configuration
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
   themes: !include_dir_merge_named themes
   extra_module_url:
     - /hacsfiles/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate
  
#CPU Temperature Sensor
command_line:
  - sensor:
      name: CPU Temperature
      command: "cat /sys/class/thermal/thermal_zone0/temp"
      # If errors occur, make sure configuration file is encoded as UTF-8
      unit_of_measurement: "°C"
      value_template: "{{ value | multiply(0.001) | round(1) }}"

#Raspberry Pi Monitoring
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use

#Time/Date Sensor
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time_iso'

#House Thermostat Mode Sensor
  - platform: statistics
    name: Outside Temp Avg
    entity_id: sensor.openweathermap_temp
    state_characteristic: average_linear
    max_age:
      minutes: 20

# Google Assistant Integration
google_assistant: !include google_assistant_integration.yaml

#Media Players
media_player:
  - platform: onkyo
    host: IP address
    name: Media Room AVR
    max_volume: 70
    receiver_max_volume: 200
    sources:
      cd: "Chromecast Audio"
      strm-box: "Nvidia Shield"
      game: "Nintendo"
      
  - platform: universal
    name: Living Room AVR
    attributes:
      state: remote.living_room_hub
      source_list: input_select.living_room_stereo_source|activity_list
      source: remote.living_room_hub|current_activity
    commands:
      turn_on:
        service: remote.send_command
        target:
          entity_id: remote.living_room_hub
        data:
          device: Living Room Stereo
          command: PowerToggle
      turn_off:
        service: remote.send_command
        target:
          entity_id: remote.living_room_hub
        data:
          device: Living Room Stereo
          command: PowerToggle
      volume_up:
        service: remote.send_command
        target:
          entity_id: remote.living_room_hub
        data:
          device: Living Room Stereo
          command: VolumeUp
      volume_down:
        service: remote.send_command
        target:
          entity_id: remote.living_room_hub
        data:
          device: Living Room Stereo
          command: VolumeDown
      volume_mute:
        service: remote.send_command
        target:
          entity_id: remote.living_room_hub
        data:
          device: Living Room Stereo
          command: Mute
      select_source:
        service: remote.turn_on
        target:
          entity_id: remote.living_room_hub
        data:
          activity: "{{ source }}"
    device_class: speaker
    unique_id: living_room_avr

#Hot Tub Thermostat
climate:
  - platform: generic_thermostat
    name: Hot Tub Thermostat
    heater: switch.pool_heater
    target_sensor: sensor.pool_heater_temp
    min_temp: 80
    max_temp: 105
    target_temp: 98
    cold_tolerance: 0.5
    hot_tolerance: 0.5
```

### Additional information

Attempts to fix this issue include looking into the solutions presented in the following links. I acknowledge that this is happening on an Android device and not iOS... But assume the fix would be identical.

https://github.com/home-assistant/iOS/issues/1071

https://github.com/home-assistant/iOS/issues/2259

https://community.home-assistant.io/t/home-assistant-app-showing-a-blank-screen-chrome-safari-on-ios-crash/469565

Setting a default dashboard for a profile doesn't work, because I can't even get to the login screen where the user profile dashboard would have any effect.
