### ISSUE TITLE
picture-elements will occasionally not display custom card elements

### ISSUE THREAD

**Issue by vangorra** [home-assistant/frontend#18764]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Occasionally `custom:` cards used in `picture-elements` does no appear.

Video reproduction:
[before.webm](https://github.com/home-assistant/frontend/assets/1752370/60e1b048-4531-4c20-83d1-ae1e37aa476c)

### Describe the behavior you expected

All `custom:` cards used in `picture-elements` should appear.

### Steps to reproduce the issue

This tends to occur in chrome most often.

1. Add `custom:` card to dashboard. Preferably a complex card.
2. Add `picture-elements` card on dashboard
3. Add a `custom:` card to the `picture-elements` card.
4. Refresh the page a bunch of times. 
5. The `custom:` cards in the `picture-elements` is not visible.

See configuration example below.

When the custom cards do not appear, they are replaced with these error cards (which are also not visible). 
![285662715-ab20155f-c0e1-4dc0-b916-76421115ad46](https://github.com/home-assistant/frontend/assets/1752370/b559aece-b332-409c-96ec-d3ca6876e807)

### What version of Home Assistant Core has the issue?

2023.12.0.dev0

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

Chrome, all versions.

### Which operating system are you using to run this browser?

Ubuntu 23.10

### Problem-relevant frontend configuration

```yaml
title: House
views:
  - icon: mdi:home
    panel: false
    path: default_view
    title: Home
    badges: []
    cards:
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1.0em'
              width: 100%
            title: Always Visible 1
      - type: custom:auto-entities
        card:
          type: entities
          show_empty: false
          state_color: true
        filter:
          include:
            - attributes:
                device_class: door
              state: 'on'
        show_empty: false
        sort:
          method: name
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Always Visible 2
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1.0em'
              width: 100%
            title: Occasionally Visible 1
```

### Additional information

Originally reported and investigated here: https://github.com/piitaya/lovelace-mushroom/issues/1161
