### ISSUE TITLE
cast.home-assistant.io won't connect to self-hosted HTTPS (Error: Unable to Connect)

### ISSUE THREAD

**Issue by F1zzyD** [home-assistant/frontend#18766]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am setting up Google Cast to my Google Home Hub to display dashboards. I am able to connect to my Home Assistant instance through local ip and external ip (https://servernamehere.duckdns.org) both on home network and cellular. When using cast.home-assistant.io, I can successfully log in and use my authenticator, however the website returns the error "Unable to Connect".

### Describe the behavior you expected

Use website to connect to my Google Home Hub.

### Steps to reproduce the issue

1. Open website
2. Log in to my instance
3. Use authenticator code
4. Error "Unable to connect"

### What version of Home Assistant Core has the issue?

2023.11.2

### What was the last working version of Home Assistant Core?

2023.11.2

### In which browser are you experiencing the issue with?

Google Chrome 119.0.6045.160

### Which operating system are you using to run this browser?

Windows 10 Pro 19045.3693

### Problem-relevant frontend configuration

```yaml
Here is my config.yaml with relevent info:

homeassistant:
  name: Home
  external_url: "https://servernamehere.duckdns.org"
  internal_url: "http://homeassistant.local:8123"
  allowlist_external_urls:
    - "https://cast.home-assistant.io"
  legacy_templates: false
```

### Javascript errors shown in your browser console/inspector

```txt
None
```
