### ISSUE TITLE
gauge colors overlap

### ISSUE THREAD

**Issue by gilcu3** [home-assistant/frontend#18805]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The colors in the gauge seem slightly overlapping.
![Screenshot_2023-11-29_10-10-31](https://github.com/home-assistant/frontend/assets/828241/ea2c2078-9739-4829-bec9-a5983706f9d9)

### Describe the behavior you expected

Show colors without overlap

### Steps to reproduce the issue

1. Create a dashboard with the following card:
```
type: gauge
entity: sensor.temperature
needle: true
segments:
  - from: 33
    color: red
  - from: 31
    color: orange
  - from: 25
    color: yellow
  - from: 18
    color: green
  - from: 11
    color: yellow
  - from: 9
    color: orange
  - from: 0
    color: red
min: 7
max: 35
name: Temperature
```

### What version of Home Assistant Core has the issue?

core-2023.11

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Linux

### Additional information

I can see the same glitch in the android app as well.
