### ISSUE TITLE
Copy of thermostat card does not reconfigure

### ISSUE THREAD

**Issue by Twanne** [home-assistant/frontend#18946]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I configured a thermostat card for 1 climate entity that has only 1 HVAC mode: 'heating'.
After this configuration, I copied the card in order to recreate the same configuration for my other climate entities (which all have a 'heating' and 'off' mode).
When I pasted the configuration and changed the climate entity to one with 2 modes, only the 1 'heating' mode stayed visible instead of it showing the 'heating' and 'off' mode that this new entity has.

The issue was resolved by deleting the 'Climate HVAC modes' feature and adding it again.

Picture of the bug:
![HVAC modes bug](https://github.com/home-assistant/frontend/assets/16245507/60eca8a8-defc-4a88-b966-f000b70e5c0b)

### Describe the behavior you expected

When changing the climate entity on the thermostat card, I expected it to look at the entity's available modes and reflect those on the card.

### Steps to reproduce the issue

1. Create Thermostat card with a climate entity that has only 1 mode.
2. Copy this original card and paste it to create a new one, or duplicate the card (same issue persists).
3. Change the climate entity of this new card to one that has multiple HVAC modes.

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

Not applicable

### In which browser are you experiencing the issue with?

Google Chrome and Firefox

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
square: true
type: grid
cards:
  - type: thermostat
    entity: climate.vloerverwarming
    features:
      - type: climate-hvac-modes
        hvac_modes:
          - heat
  - type: thermostat
    entity: climate.badkamer
    features:
      - type: climate-hvac-modes
        hvac_modes:
          - heat
  - type: thermostat
    entity: climate.living
    features:
      - type: climate-hvac-modes
        hvac_modes:
          - heat
columns: 3
```
