### ISSUE TITLE
Thermostat Card - dual mode broken

### ISSUE THREAD

**Issue by cociweb** [home-assistant/frontend#18959]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Updating to 2023.12.0 the dual mode functionality is break for the thermostat card. My thermostat uses MQTT HVAC with [low](https://www.home-assistant.io/integrations/climate.mqtt/#temperature_low_state_topic) / [high](https://www.home-assistant.io/integrations/climate.mqtt/#temperature_high_state_topic) values. After the upgrade, the new card works only in single mode and uses only the low value. the situation is the same for the entity dialog too.

the new behavior:
![image](https://github.com/home-assistant/frontend/assets/1935413/7c14d0ea-096c-4c63-9019-d248f9dd951b)

the old (example, illustration from the www) behavior:
![image](https://github.com/home-assistant/frontend/assets/1935413/62014e7f-151a-4a54-80bf-4405aa41627f)

### Describe the behavior you expected

restore the dual mode functionality for MQTT HVAC as a drop in replacement of the old thermostat card:
Show and set both Low & High temp value on the same card.

### Steps to reproduce the issue

1. upgrade from 2023.11.3 to 2023.12.0
2. Clear cache
3.
...
As an observation: there are no html elements where the class=".dual"  attribute.

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

2023.11.3

### In which browser are you experiencing the issue with?

edge, companion app, firefox

### Which operating system are you using to run this browser?

Ubuntu 22.04, Android 13

### Additional information

appropriate yaml:
```
mqtt:
  climate:
    - name: "Fűtés"
      unique_id: "climate.futes"
      max_temp: 30
      min_temp: 10
      precision: 0.1
      temp_step: 0.5
      retain: false
      temperature_unit: "C"
      modes:
       - auto
       - heat
       - cool
       - 'off'
      mode_state_template: >-
        {% set value = value_json.opmode.value %}
        {% set values = { 'auto':'auto', 'day':'heat', 'night':'cool', 'off':'off'} %}
        {{ values[value] if value in values.keys() else 'auto' }}
      mode_state_topic:  "ebusd/700/z1OpMode"
      mode_command_template: >-
        {% set values = { 'auto':'auto', 'heat':'day',  'cool':'night', 'off':'off'} %}
        {{ values[value] if value in values.keys() else 'auto' }} 
      mode_command_topic: "ebusd/700/z1OpMode/set"
  
      temperature_state_template: "{{ value_json.tempv.value }}"
      temperature_state_topic: "ebusd/700/z1ActualRoomTempDesired"
      temperature_command_topic: "ebusd/700/z1ActualRoomTempDesired/set"
  
      temperature_low_state_template: "{{ value_json.tempv.value }}"
      temperature_low_state_topic: "ebusd/700/z1NightTemp"
      temperature_low_command_topic: "ebusd/700/z1NightTemp/set"
      
      temperature_high_state_template: "{{ value_json.tempv.value }}"
      temperature_high_state_topic: "ebusd/700/z1DayTemp"
      temperature_high_command_topic: "ebusd/700/z1DayTemp/set"
      
      current_temperature_template: "{{ value_json.tempv.value }}"
      current_temperature_topic: "ebusd/700/z1RoomTemp"
```

**Comment by cociweb** [comment]
This is the corresponding service call:
```
service: climate.set_temperature
data:
  target_temp_high: 24
  target_temp_low: 24
  hvac_mode: auto
target:
  entity_id: climate.futes
```
