### ISSUE TITLE
Horizontal stack with 2 horizontal stacks: a height glitch

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#18972]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this card:
```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: horizontal-stack
        title: title
        cards:
          - show_name: true
            show_icon: true
            type: button
          - type: button
      - type: horizontal-stack
        title: title
        cards:
          - type: button
          - type: button
  - type: horizontal-stack
    title: stack title
    cards:
      - type: button
      - type: button
  - type: horizontal-stack
    title: stack title
    cards:
      - type: button
      - type: button
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/55fcfd38-d3a4-4d13-aacb-e31ec76cbb6f)

The upper horiz stack contains two horiz stacks.
Seems that inner stacks make buttons of wrong height.
As a result - the `stack title` text came under the upper stack:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/ec4c1d98-705c-423e-bf02-663cc5e97ae2)

A correct look:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/2d5def30-08c4-4f24-afec-1c3e1322c105)

### Describe the behavior you expected

Using horiz stacks inside a horz stack does not cause glitches.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.12.0

### In which browser are you experiencing the issue with?

Chrome 119.0.6045.200 

### Which operating system are you using to run this browser?

Win10x64

**Comment by vwtuner** [comment]
![ IMG_5414](https://github.com/home-assistant/frontend/assets/121826531/6573c841-e10f-45e2-abbd-87efc5c931d3)

Ich habe ein ähnliches Problem

**Comment by ildar170975** [comment]
Default icons are not shown in 2024.4.3, so the test code is:
```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: horizontal-stack
        title: title
        cards:
          - show_name: true
            show_icon: true
            type: button
            icon: mdi:car
          - type: button
            icon: mdi:car
      - type: horizontal-stack
        title: title
        cards:
          - type: button
            icon: mdi:car
          - type: button
            icon: mdi:car
  - type: horizontal-stack
    title: stack title
    cards:
      - type: button
        icon: mdi:car
      - type: button
        icon: mdi:car
  - type: horizontal-stack
    title: stack title
    cards:
      - type: button
        icon: mdi:car
      - type: button
        icon: mdi:car
```
Editor:
![image](https://github.com/home-assistant/frontend/assets/71872483/b9dd21b8-3cf1-4cd8-92d3-f5ebfc30dbaa)

Edit mode:
![image](https://github.com/home-assistant/frontend/assets/71872483/ad9575b9-0cd7-4958-96ea-d5d3eb7ece4f)

Non-edit mode:
![image](https://github.com/home-assistant/frontend/assets/71872483/de9fc369-4443-4d01-bcf1-9d7f81fe5b55)

**Comment by ildar170975** [comment]
Up

**Comment by ildar170975** [comment]
Up

**Comment by SnowyJaguar1034** [comment]
I'm having a similar issue where the card titles on some of my horizontal cards are overlapping with the card above. I'm not sure if I have a misconfiguration, if this is a bug or if there's a blank card I should be putting between my cards here.
![image](https://github.com/user-attachments/assets/2de2e66e-ab48-4171-981f-37d2a7c25450)

This is the full YML of the view this issue is happening on, at the moment what's seen in the screen shot is all that's in this view.
```yml
    type: sections
    max_columns: 4
    title: Summary
    path: summary
    dense_section_placement: false
    sections:
      - type: grid
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: light.hallway_upstairs_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - brightness
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.hallway_downstairs_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - brightness
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
            grid_options:
              columns: full
            title: Hallway Lights
          - type: horizontal-stack
            cards:
              - type: tile
                entity: light.snug_lamp_light
                vertical: false
                hide_state: false
                show_entity_picture: false
                state_content:
                  - state
                  - brightness
                  - effect
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.flower_lamp
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
            grid_options:
              columns: full
            title: Kitchen Lights
          - type: horizontal-stack
            cards:
              - type: tile
                entity: light.teagans_office_main_light
                vertical: false
                hide_state: false
                show_entity_picture: false
                state_content:
                  - state
                  - brightness
                  - effect
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.desk_corner_lamp_switch_1
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.desk_lamp_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
            grid_options:
              columns: full
            title: Teagan's Office
          - type: horizontal-stack
            cards:
              - type: tile
                entity: light.teagans_room_main_light
                vertical: false
                hide_state: false
                show_entity_picture: false
                state_content:
                  - state
                  - brightness
                  - effect
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.clothes_rail_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.bedside_lamp_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
            grid_options:
              columns: full
            title: Teagan's Bedroom
        column_span: 4
```
