### ISSUE TITLE
Counter increment events do not show up in Logbook

### ISSUE THREAD

**Issue by masman69** [home-assistant/frontend#19039]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After creating a new counter helper entity, when incremented, increment does not show up in logbook.

### Describe the behavior you expected

Increment of counter entity would show up in logbook.  I confirmed that if I click on the entity on dashboard that it's more details does show last increment..

### Steps to reproduce the issue

1. Create counter element
2.Optional configure a logbook card to show that counter
3. Increment counter
4. Confirm that counter increment is not logged in either logbook or shown in logbook card.
...

### What version of Home Assistant Core has the issue?

2023.12.2

### In which browser are you experiencing the issue with?

Google Chrome Version 119.0.6045.200

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
editable: true
initial: 0
step: 1
minimum: 0
maximum: 1000
icon: mdi:dog-side
friendly_name: Hershey Pee Outside

Last changed:
December 13, 2023 at 6:41:15 PM

Last updated:
December 13, 2023 at 6:41:15 PM
```

### Problem-relevant frontend configuration

```yaml
type: logbook
entities:
  - script.hershey_pee_outside
  - counter.hershey_pee_outside
  - counter.hershey_poop_outside
  - counter.hershey_pee_accident
  - counter.hershey_walk
  - counter.hershey_eat
  - input_text.hershey_comment
  - counter.hershey_false_alarm
hours_to_show: 12


Note that script does show in logbook



From logbook.yaml:
exclude:
  entities:
    # - binary_sensor.smartthings_motion1_ias_zone
    - input_boolean.ha_uptime
    - sensor.date
    - sensor.time
    # - binary_sensor.fibaro_multisensor_1_sensor
    - sensor.smartthings_motion1_sensor
  domains:
    - device_tracker
  entity_globs:
    # - sensor.*motion*
```

### Javascript errors shown in your browser console/inspector

```txt
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

### Additional information

When I started writing this, I had only looked at logbook card.  Given that the increment event does not show in logbook either, this might belong as a backend entry?  Note that script element call and text element update from config above do show in logbook.
