### ISSUE TITLE
Trigger selector: cannot add  one from selector if one already exists in the blueprint

### ISSUE THREAD

**Issue by SirGoodenough** [home-assistant/frontend#19050]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I create a blueprint that only has a trigger from an !input, it work fine....
When you try to create a blueprint that has one or more triggers already, there does not seem to be a way to add the selected trigger !input to the yaml.

### Describe the behavior you expected

A blueprint that contains some number of hardcoded triggers to have the ability for the blueprint 'customer' to add another trigger using this selector.

IE, a light that has a hardcoded trigger based on time, and the blueprint 'customer' wants to add a sun trigger to make sure the light goes on at sunset as well. Would like to give the 'customer' that ability in some blueprints.

### Steps to reproduce the issue

This functions:
```yaml
blueprint:
  name: Motion Light Control with Illuminance
  domain: automation
  input:
    ttest:
      name: dttest
      selector:
        trigger:
    light_switch:
      name: Light to Control
      selector:
        entity:
          filter:
            domain: light
trigger: 
  !input ttest
  # - platform: sun
  #   event: sunset
  #   offset: 0
action:
- service: light.turn_{{ trigger.to_state.state }}
  entity_id: !input light_switch
mode: single
```
With automation call:
```yaml
- id: '1702550432838'
  alias: aaMotion Light Control with Illuminance
  description: ''
  use_blueprint:
    path: test/custest.yaml
    input:
      ttest:
      - platform: state
        entity_id:
        - binary_sensor.back_door_pir
        to: 'on'
      light_switch: light.b_porch_relay
```

If you try to put that input into a list yaml breaks because the !input is already a list, and there are no keys to make a sublist work.
There for no way to remove the comment marks and keep the !input statement and have yaml work.

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

new feature with 2023.12.0

### In which browser are you experiencing the issue with?

firefox

### Which operating system are you using to run this browser?

ubuntu

### State of relevant entities

A suggestion was made as a possible solution.
Add a trigger type to use these selector entries.
Then it could work similar to the list produced by the condition selector.

Quote from Discord:
TheFes — Today at 8:53 AM
I think so as well, there is no YAML syntax which allows triggers to be added in a sub list
I think we need something which will be like this:
```yaml
trigger:
  # default blueprint triggers
  - platform: time
    at: "20:00"
  - platform: state
    entity_id: binary_sensor.foo
    to: "on"
  - platform: selector
    triggers:
      # triggers from selector
      - platform: state
        entity_id: binary_sensor.bar
        to: "off"
```

### Additional information

Originally discussed on thread:
https://community.home-assistant.io/t/merge-trigger-selector-with-other-triggers/655399

Edited to fix formatting issues, no content change

**Comment by TH-Braemer** [comment]
If possible, I would like the ability to add triggers of different domain to the same trigger list in order to make the BP usage easier, and the code behind too.

As an example, I would like to add different kind of Zigbee devices to trigger the same action, but the devices are rather different...:

```
trigger:
  - platform: device
    domain: mqtt
    device_id: 5ada79e48bbb945bef9685851c90be91
    type: action
    subtype: emergency
    discovery_id: 0x5c0272fffee9311f action_emergency
    id: trigger_command_pulse
  - platform: device
    domain: mqtt
    device_id: fd51d413950e692568e54ad567cc0100
    type: action
    subtype: press_1
    discovery_id: 0x0000000001719d54 action_press_1
    id: trigger_command_pulse
```

but it could perhaps also be a binary_sensor or whatever - the point is the ability to mix triggers of various kind into a single trigger action

**Comment by SirGoodenough** [comment]
> If possible, I would like the ability to add triggers of different domain to the same trigger list in order to make the BP usage easier, and the code behind too.

You can do that now, but if you want to discuss this, it would be best done in a forum frature request.
https://community.home-assistant.io/c/feature-requests/13.

I am addressing something here that I feel is broken preventing the selector from being used in a meaningful way.

**Comment by Twanne** [comment]
It can be done by adding the triggers in a default field when creating the trigger selector.
I agree it's not obvious because it's not documented anywhere that this can be done, but it works.

`blueprint:
  name: default triggers example
  domain: automation
  input:
    #Triggers
    triggers:
      name: Triggers
      description: Triggers your automation
      default:
        - platform: sun
          event: sunrise
          offset: "00:00:00"
      selector:
        trigger:
...
mode: single

trigger: !input triggers

condition:

action:
`

**Comment by zpriddy** [comment]
@Twanne 

i will have to give that a shot.. I tried to do something like that but it came out super weird.. 

Would that approach just pre-populate the triggers? So that all my f the triggers would be visible in the blueprint edit screen? That would also allow users to delete the default triggers , no?   

I would see that as a point of confusion and and very easy way to make a mistake and make the blueprint nonfunctional

**Comment by TH-Braemer** [comment]
@Twanne

Thank you, I finally figured it out thanks to you 👍 
Do you know, if there is a way to create more than one input entry list for triggers?
I have a BP, where I have 6 different actions triggered by different triggers.
I would like to differentiate them into separate trigger instances (groups) on the UI, in order to make it more obvious for the user, which triggers correspond to which actions...
Right now, I have all triggers in the same "list", and that's a bit confusing on a complicated automation (BP)
```
blueprint:
  name: Test-BP
  description: Test Automation
  domain: automation

  input:
    gate_open_triggers:
      name: Triggers for opening the gate
      ...
    gate_close_triggers:
      name: Triggers for closing the gate
      ...
    gate_state_triggers:
      name: Gate position changed triggers
      ...

trigger:
  - ??: !input gate_open_triggers
  - ??: !input gate_close_triggers
  - ??: !input gate_state_triggers

condition:

action:

```

Do you know what I mean?
