### ISSUE TITLE
legacy group: entity not found error in inspector

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19056]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="1444" alt="Scherm­afbeelding 2023-12-15 om 16 48 08" src="https://github.com/home-assistant/frontend/assets/33354141/b76688c7-a93e-4bd6-8cb3-0713687b4f12">

### Describe the behavior you expected

no error

### Steps to reproduce the issue

1. simply click on the more-info of a group in dev tools state with inspector open
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### In which browser are you experiencing the issue with?

Safari Mac

### Which operating system are you using to run this browser?

Sonoma 14.1.2

### Problem-relevant frontend configuration

no particular Frontend config, just this yaml for the group

```yaml
group:
  hub_device_trackers:
    name: Hub device trackers
    all: true
    entities:
      - device_tracker.ha_main
      - device_tracker.synology_diskstation
      - device_tracker.iungo
      - device_tracker.solaredge
      - device_tracker.ikea_tradfri
      - device_tracker.philips_hue_1
      - device_tracker.philips_hue_2
      - device_tracker.philips_hue_3
      - device_tracker.plugwise_smile
      - device_tracker.somfy_tahoma
```

all trackers are available.
I have 7 legacy groups, and clicking any of these throws the error, and, as far as I have tested now, no where else.

### Javascript errors shown in your browser console/inspector

<img width="1444" alt="Scherm­afbeelding 2023-12-15 om 16 48 08" src="https://github.com/home-assistant/frontend/assets/33354141/b76688c7-a93e-4bd6-8cb3-0713687b4f12">

error itself does not show a lot of info

<img width="671" alt="Scherm­afbeelding 2023-12-15 om 16 55 06" src="https://github.com/home-assistant/frontend/assets/33354141/3bc91e6b-6d84-41cd-9995-222719546476">

### Additional information

error seems to only show when debug tools is turned on in dev tools. still, it would be nice trace why, and fix
