### ISSUE TITLE
ADB integration - entity_picture is empty (black background in media player)

### ISSUE THREAD

**Issue by ar30v8** [home-assistant/frontend#19115]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello, I started using ADB integration with my Android TVs and I'm having an issue. The object entity_picture is empty - a black image is displayed as the background of the media player, although all other functionality is working properly. Two MI TVs.
![IMG_20231222_003454](https://github.com/home-assistant/frontend/assets/122174371/b98015f3-3a29-4339-b073-cb0f711ffa53)
![Screenshot_2023-12-22-00-35-14-520_io homeassistant companion android-edit](https://github.com/home-assistant/frontend/assets/122174371/522d7dcc-44ff-4794-8f24-b7096a567a7f)

### Describe the behavior you expected

The TV screenshot was expected to be displayed, but this problem persists for any application enabled.

### Steps to reproduce the issue

Reboot everything, rechange everything, change TV

### State of relevant entities

```yaml
source_list:
  - dialserver
  - com.android.systemui
  - com.mediatek.tv.agent
  - com.google.android.ext.services
  - com.google.android.tv.remote.service
  - com.google.android.gms.persistent
  - com.google.android.inputmethod.latin
  - com.mediatek.network
  - com.android.providers.media.module
  - com.mediatek.tvinput
  - com.google.process.gservices
  - com.android.providers.tv
  - ru.yourok.torrserve
  - Android TV Launcher
  - com.google.android.tvrecommendations
  - sh
  - torrserver
  - Google Cast
  - com.dolby.android.audio.service
  - Play Store
  - ag.tv.a24h
  - com.google.android.gms
  - com.google.android.katniss:interactor
  - com.google.android.katniss:search
  - com.google.process.gapps
  - com.google.android.packageinstaller
  - com.google.android.permissioncontroller
  - com.rma.speedtesttv
  - com.android.vending:background
volume_level: 0.01
is_volume_muted: false
app_id: com.google.android.tvlauncher
app_name: Android TV Launcher
source: Android TV Launcher
adb_response: null
hdmi_input: null
device_class: tv
entity_picture: >-
  /api/media_player_proxy/media_player.mini_tarata_adb?token=24bd076c1e1dfce4a4f036006eaf02ff15814dcef84e06d892aebe0e577c027f&cache=3c952aee3d482675
friendly_name: Mini-Tarata ADB
supported_features: 23997
```

### Problem-relevant frontend configuration

```yaml
#First:
type: custom:mini-media-player
entity: media_player.mini_tarata_adb
artwork: full-cover

#Second:
type: media-control
entity: media_player.mini_tarata_adb
```

### Additional information

I'm using Orange Pi Zero 3
