### ISSUE TITLE
Animations on picture element card stopped working after update to 2023.12.4

### ISSUE THREAD

**Issue by vaibhav2912** [home-assistant/frontend#19222]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have animated picture (spinning reload icon) on my picture elements card when dishwasher is running. This was working OK until 2023.12.3 but stopped working after update to 2023.12.4. I restored backup to go back to 2023.12.3 and I can see it starts working again.

Here is a screen capture to explain it better. Has anyone else seen this issue ?

2023.12.3 (working OK. Dishwasher spinning icon in the kitchen)

https://github.com/home-assistant/core/assets/20019445/7b0729d6-1e76-4e16-9c24-15d75a2f41a3

2023.12.4 (not working. Just icon position changed)

https://github.com/home-assistant/core/assets/20019445/37cef4b2-a8fc-4997-8eeb-e8652a0d0c7d

### Describe the behavior you expected

Animations on picture-elements card work correctly.

### Steps to reproduce the issue

1. Add picture element card
2. Add conditional image with following,
```yaml
style:
    animation: 1s linear 0s infinite normal forwards running rotate-center
```

For keyframe of rotate-center, use following,
```yaml
style: |
  @keyframes rotate-center {
    0% {
              transform: rotate(0);
    }
    100% {
              transform: rotate(360deg);
    }
  }
```

My yaml code is below in **Problem-relevant frontend configuration** section

...

### What version of Home Assistant Core has the issue?

core-2023.12.4

### What was the last working version of Home Assistant Core?

core-2023.12.3

### In which browser are you experiencing the issue with?

Tried Chrome and Firefox

### Which operating system are you using to run this browser?

Windows 10 Pro

### State of relevant entities

```txt
sensor.dishwasher_state = Running
```

### Problem-relevant frontend configuration

```yaml
- type: conditional
  conditions:
    - entity: sensor.dishwasher_state
      state: Idle
  elements:
    - type: image
      title: Dishwasher state OFF
      entity: sensor.dishwasher_state
      tap_action:
        action: navigate
        navigation_path: /lovelace/dishwasher-info
      image: /local/spin.png
      style:
        top: 66.6%
        left: 51%
        width: 6%
        transform: scale(1,1)
- type: conditional
  conditions:
    - entity: sensor.dishwasher_state
      state: Running
  elements:
    - type: image
      title: Dishwasher state ON
      entity: sensor.dishwasher_state
      tap_action:
        action: navigate
        navigation_path: /lovelace/dishwasher-info
      image: /local/spin.png
      style:
        top: 66.6%
        left: 51%
        width: 6%
        animation: 1s linear 0s infinite normal forwards running rotate-center
```

Keyframe used:
```yaml
style: |
  @keyframes rotate-center {
    0% {
              transform: rotate(0);
    }
    100% {
              transform: rotate(360deg);
    }
  }
```

### Javascript errors shown in your browser console/inspector

```txt
None
```
