### ISSUE TITLE
Tile card doesn't render attributes when value is 'false'

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#19306]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Tile card doesn't render value of attribute when it equals `false` or `null`. 
Renders state instead.

### Describe the behavior you expected

If attribute exists render chosen attribute regardless of value.

### Steps to reproduce the issue

1. Create Tile card
2. In `Appearance` > `state content` select attribute with value `false` or `null`. 
...

### What version of Home Assistant Core has the issue?

core-2024.1.2

### In which browser are you experiencing the issue with?

Firefox, Chrome, Mobile App

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
e.g. Mobile app's wifi connection sensor naturally produces false attribute.
(thou any attribute value can be spawned using Dev Tools > State tab)
```

```yaml
entity_id: sensor.my_phone_wifi_connection
state: my_ssid
attributes:
  is_hidden: false
  icon: mdi:wifi
  friendly_name: My Phone WiFi connection
last_changed: "2024-01-06T14:02:08.216044+00:00"
last_updated: "2024-01-06T15:31:04.746477+00:00"
context:
  id: 01HKFPCBDAX1H1S0BCVBJYTQDC
  parent_id: null
  user_id: 075dd48a6c4f48bfb3eedd69a9a57cb4
```

### Problem-relevant frontend configuration

```yaml
type: tile
entity: sensor.my_phone_wifi_connection
state_content: is_hidden
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

-
