### ISSUE TITLE
wait for trigger optional timeout issue

### ISSUE THREAD

**Issue by a-nicholls** [home-assistant/frontend#19360]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm having problems with wait for trigger in automation where it fails to run as expected or wait for the trigger to actually be called.

When having a wait for trigger in an automation action
![image](https://github.com/home-assistant/frontend/assets/51675087/7f6d41f1-2a23-47fe-b274-3cd5922b5d62)

If you don’t touch the timeout (optional) I think you are ok, but if you change it and even change it back to the default value of all 0’s and click on show in Edit in YAML

```
wait_for_trigger:
  - platform: state
    entity_id:
      - binary_sensor.lg_h850_interactive
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
continue_on_timeout: false
timeout:
  hours: 0
  minutes: 0
  seconds: 0
  milliseconds: 0
```
it shows the timeout section, so this has the effect of not waiting for the trigger. You may as well have a if condition for that.

If I edit out the timeout in the YAML and save the automation it does wait for the trigger as expected.
e.g.

```
wait_for_trigger:
  - platform: state
    entity_id:
      - binary_sensor.lg_h850_interactive
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
continue_on_timeout: false
```

You can’t revert back the value in the visual editor and it isn’t obvious whether it has a value set other than going into the YAML editor. Shouldn’t it be set so that if the value is 0 (or no value) for all those it should clear out the timeout section?

Clearing out the values in the visual editor doesn't remove it either.

### Describe the behavior you expected

Without having to revert to viewing the YAML, having a way to indicate that the timeout is not set or clearing the value. Is a value of all 0's valid for a wait for trigger?

### Steps to reproduce the issue

1. Create Automation with Wait for Trigger
2. Change value of time out and save
3. Go back in and try and revert value back so that it is optional (clear out or zero)
4. Notice YAML view still shows hours minutes and seconds timer of 0
...

### What version of Home Assistant Core has the issue?

core-2024.1.2

### In which browser are you experiencing the issue with?

120.0.2210.121 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 23H2
