### ISSUE TITLE
Automation editor autocap status does it wrong with climate presets

### ISSUE THREAD

**Issue by Kedryn** [home-assistant/frontend#19372]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When making a new automation that switch my thermostat to "auto" at midnight if i left it in manual, i noticed that the UI automation editor always switches my "auto" to "Auto"

When executing the automation, i get the error:
"The preset_mode Auto is not a valid preset_mode: custom, comfort, sleep, away, auto"

If i edit the automation in yaml, and change the "Auto" to "auto", it works

It's a Meross thermostat, so i'm not sure if the auto capitalization is to be considered a lovelace issue, or if not accepting the capitalized "Auto" is an Integration issue.

### Describe the behavior you expected

to work with both "Auto" and "auto"

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.2

### What was the last working version of Home Assistant Core?

don't know

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

win 11

### Problem-relevant frontend configuration

```yaml
alias: ECO Preset Auto per termostato appartamento
description: >-
  Passaggio a schedulazione a mezzanotte per termostato appartamento se
  dimenticato in manuale
trigger:
  - platform: time
    at: "23:59:00"
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: climate.smart_thermostat_2207127891531960120148e1e99a4fda
        attribute: preset_mode
        state: auto
action:
  - service: climate.set_preset_mode
    metadata: {}
    data:
      preset_mode: Auto
    target:
      device_id: 31782d62a7feeaddd8b7f67b86780dac
  - service: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.googlehome3534
      message: Passaggio termostato appartamento in automatico
      language: it
mode: single
```
