### ISSUE TITLE
Integration dashboard is not loading when no integrations are installed

### ISSUE THREAD

**Issue by ReneNulschDE** [home-assistant/frontend#19436]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The integration/dashboard-page does not load and shows the spinning wheel when no integration is added, no integrations are ignored and no integrations are disabled after a fresh install of HA. (default_config: disabled in HA-config file, see below)  

### Describe the behavior you expected

The frontend shows the integration/dashboard page if no integrations are added/disabled/ignored to HA.

### Steps to reproduce the issue

1. Install a fresh HA-core version (new venv, no backup, change the config: port, minimal list of components to prevent discovery, ...) - See details for the current config (all included files are empty)
2. Follow the onboarding process
3. Delete the default integrations Web-Radio, Shopping List,...
4. Restart HA (as requested by the shopping list integration)
5. Try to open the integration/dashboard page
6. Spinning wheel is spinning and spinning and ... ;-)

Potential problem code area: [ha-config-integrations-dashboard.ts - L266](https://github.com/home-assistant/frontend/blob/4046534fa8f3309842ac06637968cdb71e50b661/src/panels/config/integrations/ha-config-integrations-dashboard.ts#L266)

### What version of Home Assistant Core has the issue?

2024.1.3

### In which browser are you experiencing the issue with?

Chromium (120.0.6099.216), Firefox (121.0)

### Which operating system are you using to run this browser?

Ubuntu 23.10

### State of relevant entities

```txt
State list has the person.xxx entity only. All integrations are removed.
```

### Additional information

Default-config is removed. HA config:
```
http:
  server_port: 8126

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
automation: !include automations.yaml
script: !include scripts.yaml
logger:
  default: info
logbook:
history:
config:
network:
```
