### ISSUE TITLE
Cast dashboard to Nest Hub is showing old HA logo

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/frontend#19442]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I cast a dashboard to my Google Nest Hub, it shows the old Home Assistant logo when the dashboard is loading
![huiorhrkshruoeiwj](https://github.com/home-assistant/frontend/assets/80623729/e699b541-239c-44df-934d-369a531e2b0c)

### Describe the behavior you expected

I did expect to see the new logo, [launched in September 2023](https://www.home-assistant.io/blog/2023/09/17/a-refreshed-logo-for-home-assistant/)

### Steps to reproduce the issue

Cast a dashboard, with the cast.show_lovelace_view service
```
service: cast.show_lovelace_view
data:
  entity_id: media_player.nest_hub
  dashboard_path: nest-hub-dashboard
  view_path: default
```

### What version of Home Assistant Core has the issue?

core-2024.1.3
