### ISSUE TITLE
Cards are not translated

### ISSUE THREAD

**Issue by Gnarflord** [home-assistant/frontend#19455]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After setting my profile language to german most of the interface is translated but none of the cards are. In fact I can see the correct translation of entity states in the logbook but for example the history graph picks up the english default:

![image](https://github.com/home-assistant/frontend/assets/19466442/f2295b1b-e176-496f-805c-743b8c9c930b)

When editing the dashboard all interface elements are translated ("bearbeiten" instead of "edit") but again, the cards themselves are stuck in english:
![image](https://github.com/home-assistant/frontend/assets/19466442/e3b68678-20a6-4ab1-a171-9c49aad99444)

### Describe the behavior you expected

I would have expected the entity state to be translated everywhere.

### Steps to reproduce the issue

1. Install latest home assistant
2. Switch profile language from english to german

### What version of Home Assistant Core has the issue?

core-2024.1.0

### In which browser are you experiencing the issue with?

Chromium 121.0.6167.71, Firefox 121.0.1, Android App 2023.12.4-full

### Which operating system are you using to run this browser?

Arch Linux 6.6.10, Android 14

**Comment by karwosts** [comment]
Have you changed the server language in Settings->System->General?

AFAIK state translations are handled by the server language, and frontend elements are by the frontend language, but I'm not 100% positive.

**Comment by Gnarflord** [comment]
![image](https://github.com/home-assistant/frontend/assets/19466442/9b716f6c-4259-4b10-8e01-a9f0726e9300)

Yes, the server language is set to german as well. I'm quite confused about this

**Comment by karwosts** [comment]
Hmm, ok did a little more looking and these are controlled by the frontend/profile language. If you look at any other entities, e.g. `sun.sun`, do any of them get translated?

![image](https://github.com/home-assistant/frontend/assets/32912880/fc83f221-961f-4586-826e-04bf29e9e93f)

**Comment by Gnarflord** [comment]
Thanks for looking into my issue :)

![image](https://github.com/home-assistant/frontend/assets/19466442/e14af236-5e71-4a92-b23c-53b4d8b0fb11)

Nope, it's the same: The logbook has the translated entry while the graphical representation is stuck in english. I can also not find nothing related to that in the systemd log or the native HA log even with verbosity set to INFO.

My configuration.yaml also isn't that special:
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
recorder:
  db_url: !secret recorder_mariadb_url

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1 # Add the IP address of the proxy server
#
#logger:
#  default: info
```
