### ISSUE TITLE
Thermostat card does not display correct temperature (or current temperature)

### ISSUE THREAD

**Issue by mbroadst** [home-assistant/frontend#19498]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm trying to automate a mitsubishi heat pump by representing it to Home Assistant through the `climate.mqtt` integration. Using the UI I can select a mode and a target temperature, and can confirm that the values are being sent to the correct topics and resulting in the desired changes on the heat pump. When in "optimistic" mode the values I choose are represented correctly in the UI, however, if I happen to restart Home Assistant it will arbitrarily reset the state to "heat" mode and 70 degrees no matter what is being published on the state topic. Relatedly, the device is publishing both `temperature` and `current_temperature`, but the UI isn't displaying both values. 

This might be a misunderstanding on my part about how the core+frontend are receiving data from the device. Does Home Assistant make proactive calls to the device to read this state? I was hoping that if I had the device periodically publish the state (say ~60s), then those updates would be reflected in the HA UI. 

Here is the configuration published by the device for auto-discovery:
```
name:
unique_id: 6AE2F403F784
optimistic: true
modes:
- heat_cool
- cool
- dry
- heat
- fan_only
- 'off'
mode_command_topic: heatpump/HVAC_MATT_OFFICE/mode/set
mode_state_topic: heatpump/HVAC_MATT_OFFICE/state
mode_state_template: "{{value_json.mode if (value_json is defined and value_json.mode
  is defined and value_json.mode|length) else 'fan_only'}}"
temperature_unit: F
min_temp: 61
max_temp: 88
temp_step: '1'
temperature_command_topic: heatpump/HVAC_MATT_OFFICE/temp/set
temperature_state_topic: heatpump/HVAC_MATT_OFFICE/state
temperature_state_template: "{{value_json.temperature|int if (value_json is defined
  and value_json.temperature is defined and value_json.temperature|length) else 'N/A'}}"
current_temperature_topic: heatpump/HVAC_MATT_OFFICE/state
current_temperature_template: "{{value_json.roomTemperature|int if (value_json is
  defined and value_json.roomTemperature is defined and value_json.roomTemperature|length)
  else 'N/A'}}"
device:
  ids: HVAC_MATT_OFFICE
  name: HVAC_MATT_OFFICE
  sw: HVAC_WIFI v0.1
  mdl: HVAC MITSUBISHI
  mf: MITSUBISHI ELECTRIC
  cu: http://192.168.0.189
```

and here is an example value published to the state topic:
```
{
  "roomTemperature": 71,
  "temperature": 74,
  "fan": "auto",
  "vane": "SWING",
  "wideVane": "|",
  "mode": "heat",
  "action": "heating",
  "compressorFrequency": 0
}
```

I copied in the current "state" of the entity in the form field below. I notice in Dev Tools that the last update was from yesterday at 5:30pm, but I can confirm that the device is currently publishing its state every 60 seconds.

### Describe the behavior you expected

The thermostat card should show up-to-date temperature (and current temperature) for the device, based on information it publishes every 60s. 

### Steps to reproduce the issue

1. Add climate entity to Home Assistant
2. Observe that the displayed temperature is incorrect
3. Change the temperature and observe it is correct (in "optimistic" mode)
4. Restart Home Assistant and observe the temperature resets to default of 70, in "heat" mode

### What version of Home Assistant Core has the issue?

2024.1.4

### In which browser are you experiencing the issue with?

Google Chrome 120.0.6099.234

### Which operating system are you using to run this browser?

macOS Sonoma 14.2.1

### State of relevant entities

```txt
hvac_modes:
  - heat_cool
  - cool
  - dry
  - heat
  - fan_only
  - "off"
min_temp: 61
max_temp: 88
target_temp_step: 1
current_temperature: null
temperature: 70
friendly_name: HVAC_MATT_OFFICE
supported_features: 1
```
