### ISSUE TITLE
No confirmation with toggle switch on Entities card

### ISSUE THREAD

**Issue by wgstarks** [home-assistant/frontend#19509]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have confirmations enabled on my entities card but when I tap the toggle switch I don't get the expected confirmation dialog. The entity just turns on/off immediately.

![Screenshot 2024-01-22 at 9 35 34 AM](https://github.com/home-assistant/frontend/assets/5657833/24c13246-a6c6-4b88-9006-0a0e061213d7)

`type: entities
entities:
  - entity: sensor.greenhouse_temperature_humidity_greenhouse_temperature
  - entity: sensor.greenhouse_temperature_humidity_greenhouse_humidity
  - entity: switch.greenhouse_lights
  - entity: switch.greenhouse_heater_greenhouse_heater
    tap_action:
      confirmation:
        text: Are You Sure?
      action: toggle
  - entity: binary_sensor.front_door_1_front_door_1
  - entity: binary_sensor.front_door_2_front_door_2
`

### Describe the behavior you expected

Toggling the switch should open the confirmation dialog box rather than immediately performing the action.

### Steps to reproduce the issue

1.Create entities card.
2.Add confirmation yaml code.
3.Toggle associated switch.
...

### What version of Home Assistant Core has the issue?

2024.1.5

### In which browser are you experiencing the issue with?

Safari, Chrome, Firefox

### Which operating system are you using to run this browser?

macOS 14.2.1

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: sensor.greenhouse_temperature_humidity_greenhouse_temperature
  - entity: sensor.greenhouse_temperature_humidity_greenhouse_humidity
  - entity: switch.greenhouse_lights
  - entity: switch.greenhouse_heater_greenhouse_heater
    tap_action:
      confirmation:
        text: Are You Sure?
      action: toggle
  - entity: binary_sensor.front_door_1_front_door_1
  - entity: binary_sensor.front_door_2_front_door_2
```
