### ISSUE TITLE
Fan Only font doesn't scale with new thermostat card

### ISSUE THREAD

**Issue by stormshaker** [home-assistant/frontend#19520]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When a Thermostat is set to Fan Only mode, the text 'Fan Only' doesn't scale with the UI.

### Describe the behavior you expected

As per the other text such as current temperature, set temperature, the words 'Fan Only' should also scale.

### Steps to reproduce the issue

1. Set a Thermostat to Fan Only
2. Create a Grid card, and add the Thermostat card
3. Change the Grid columns up and down, to scale the card
...

### What version of Home Assistant Core has the issue?

core-2024.1.5

### In which browser are you experiencing the issue with?

Safari Version 17.2.1 (19617.1.17.11.12)

### Which operating system are you using to run this browser?

macOS Sonoma 14.2.1 (23C71)

### State of relevant entities

```txt
Current state: fan_only
Attributes:
hvac_modes: off, fan_only, heat_cool
min_temp: 15
max_temp: 30
target_temp_step: 0.5
current_temperature: 21.8
airflow_max: 75
airflow_min: 0
zone_index: 0
friendly_name: Kitchen Thermostat
supported_features: 0
```

### Problem-relevant frontend configuration

```yaml
square: true
type: grid
columns: 3
cards:
  - type: thermostat
    entity: climate.kitchen
    name: Kitchen
    features:
      - type: climate-hvac-modes
        hvac_modes:
          - 'off'
          - fan_only
          - heat_cool
    show_current_as_primary: false
```

### Additional information

<img width="992" alt="4-column - not scaled" src="https://github.com/home-assistant/frontend/assets/2807460/91804450-b999-451e-b1ab-2f4389b7f38a">
<img width="992" alt="3-column - not scaled" src="https://github.com/home-assistant/frontend/assets/2807460/8dee75ce-5350-498d-926c-2daf62aa2262">
<img width="992" alt="2-column - good" src="https://github.com/home-assistant/frontend/assets/2807460/0d128d0b-975a-4675-b1c8-548559c3d78c">
