### ISSUE TITLE
climate preset icons in randon order

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19576]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

as title, the buttons (not talking about the icons, as I am aware the frontend does not yet use/see the icons of this integrations presets) seem in random order, no matter what is set in the yaml config

also, not sure if this is a bug or a FR, if not setting any preset_modes, but do set the feature type, one would have expected the presets to auto populate with all available. currently, and empty dropdown is presented when using the yaml below

### Describe the behavior you expected

have the order of the Dashboard be configured by the order in Yaml

### Steps to reproduce the issue

1. create card
2. check dashboard 
3.
...

### What version of Home Assistant Core has the issue?

2024.1.5

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Sonoma 14.2.1

### State of relevant entities

```txt
hvac_modes:
  - auto
  - heat
min_temp: 4
max_temp: 30
target_temp_step: 0.5
preset_modes:
  - no_frost
  - vacation
  - away
  - asleep
  - home
current_temperature: 10.5
temperature: 10.5
hvac_action: idle
preset_mode: home
friendly_name: Voorkamer
supported_features: 17
```

### Problem-relevant frontend configuration

```yaml
- entity: climate.voorkamer
    type: tile
    features:
      - type: target-temperature
      - type: climate-preset-modes
        style: icons
        preset_modes:
          - home
          - away
          - asleep
          - vacation
          - no_frost
    state_content:
      - current_temperature
      - temperature
      - preset_mode
      - state


no presets at all the using, expected auto populate all available presets
```
    features:
      - type: target-temperature
      - type: climate-preset-modes
        style: icons #dropdown either of these
```
```

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

### Additional information

as you can see 'Away' or Afwezig in Dutch is the center button, while the second in the yaml

<img width="531" alt="Scherm­afbeelding 2024-01-30 om 14 01 18" src="https://github.com/home-assistant/frontend/assets/33354141/d8607a3e-c583-4eb8-8730-d68290dbfb0d">
