### ISSUE TITLE
Horizontal margins in horizontal stack broken in 20240131.0

### ISSUE THREAD

**Issue by jeremynoesen** [home-assistant/frontend#19611]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Setting a horizontal margin within a theme for a horizontal stack results in inconsistent margins.

### Describe the behavior you expected

Setting the horizontal margin for a horizontal stack card within a theme should result in the margin between cards being uniform to the value set.

### Steps to reproduce the issue

Create a dashboard with this card in it:
```yaml
type: horizontal-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    name: Test
    icon: mdi:test-tube
  - show_name: true
    show_icon: true
    type: button
    name: Test
    icon: mdi:test-tube
  - show_name: true
    show_icon: true
    type: button
    name: Test
    icon: mdi:test-tube
```

Then set the dashboard theme to this:
```yaml
test:
  horizontal-stack-card-margin: 0 24px 0 0
```

There will be no 24px margin between the first two buttons, and a larger than 24px margin between the last two.

### What version of Home Assistant Core has the issue?

core-2024.2.0b1

### What was the last working version of Home Assistant Core?

core-2024.1.6

### In which browser are you experiencing the issue with?

Firefox 122.0, Nest Hub 2 Chromecast

### Which operating system are you using to run this browser?

macOS 14.3, Fuchsia 14.20230831.4.72

**Comment by ildar170975** [comment]
This commit could be a reason.
https://github.com/home-assistant/frontend/commit/7e933673943497d7e5836d3c33c914dd1ef4f2e8

**Comment by jeremynoesen** [comment]
Here is what it looks like, and what each button margin is shown as:
![Screenshot 2024-02-01 at 10 13 53 AM](https://github.com/thomasloven/lovelace-card-mod/assets/46114593/1977d34b-1040-4bdc-bcf4-dcd52e3757a4)

Button 1: 
![Screenshot 2024-02-01 at 10 16 23 AM](https://github.com/thomasloven/lovelace-card-mod/assets/46114593/b64f2f44-01a1-40bd-8e60-285e7a89184c)

Button 2: 
![Screenshot 2024-02-01 at 10 16 53 AM](https://github.com/thomasloven/lovelace-card-mod/assets/46114593/522d4a8c-824e-4d49-b587-0aa4bb330fc1)

Button 3: 
![Screenshot 2024-02-01 at 10 17 12 AM](https://github.com/thomasloven/lovelace-card-mod/assets/46114593/c5f6b511-7ac5-4922-822d-892fc68e6fc0)

The button 1 and 3 respectively have extra CSS that seem to override the inner margins.
![Screenshot 2024-02-01 at 10 20 25 AM](https://github.com/thomasloven/lovelace-card-mod/assets/46114593/d37f6cad-5591-4e25-9cab-35974624d385)
![Screenshot 2024-02-01 at 10 20 41 AM](https://github.com/thomasloven/lovelace-card-mod/assets/46114593/9f2b926b-50e9-4303-a54c-95de13d511d2)

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/commit/7e933673943497d7e5836d3c33c914dd1ef4f2e8#diff-6b53863fed3bd098f454367d1830b6084eebc43bdb1fb43b94400e8c2f3ac961

**Comment by jeremynoesen** [comment]
Looks like horizontal stack isn't the only card with issues regarding these new margins. Almost every card now has an additional 4px margin around them as part of the RTL fixes. I tried setting a margin on buttons not inside a stack, and the ha-card margins are surrounded by another margin on the hui-button-card element. This may break some themes.

**Comment by ildar170975** [comment]
Could you post a code & screenshot for this "not-stack" case?

**Comment by jeremynoesen** [comment]
Certainly. Here is the YAML to create a dashboard with three of these test buttons on it. I used card-mod to make it easier to show whats going on, but this would still apply to theming:
```yaml
views:
  - title: Test
    theme: test_minimal
    badges: []
    cards:
      - show_name: true
        show_icon: true
        type: button
        name: Test
        icon: mdi:test-tube
        card_mod:
          style: |
            ha-card {
              margin: 0 24px 0 0 !important;
            }
      - show_name: true
        show_icon: true
        type: button
        name: Test
        icon: mdi:test-tube
        card_mod:
          style: |
            ha-card {
              margin: 0 24px 0 0 !important;
            }
      - show_name: true
        show_icon: true
        type: button
        name: Test
        icon: mdi:test-tube
```

That looks like this:
![Screenshot 2024-02-01 at 9 20 23 PM](https://github.com/home-assistant/frontend/assets/46114593/06ba5366-6609-4c19-8ccc-4febf56961b9)

The last card being taller is normal due to how the card height scales based on its width.

There is the 24px right margin as expected on the first two cards, but there is also an extra margin around the entire card:
![Screenshot 2024-02-01 at 9 22 10 PM](https://github.com/home-assistant/frontend/assets/46114593/2a70e0b1-50a2-4500-80a9-697f43d1c6be)

The last card also has the extra margin, but no modifications to the CSS to show behavior without card mod. 
![Screenshot 2024-02-01 at 9 23 37 PM](https://github.com/home-assistant/frontend/assets/46114593/0a058deb-815e-4fb8-b31c-757742313ab8)
