### ISSUE TITLE
climate presets dont respect config order on Tile card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19686]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

setting an order for the preset modes in the yaml for tile is not respected. Somehow the order seems fixed.
to me, in a seemingly random, but more importantly, counter intuitive way.

usecase: Ive set the l-r order depending on frequency...

Ive issued his as a bug, given we can re-order practically antything on Tile.

If you dont think this is a bug, please consider as  FR.

### Describe the behavior you expected

being able to re-order order of preset modes

### Steps to reproduce the issue

1. create Tile card for climate entity
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.2 beta

### In which browser are you experiencing the issue with?

any

### Problem-relevant frontend configuration

```yaml
type: tile
      features:
        - type: target-temperature
        - type: climate-preset-modes
          style: icons
          preset_modes:
            - home
            - asleep
            - away
            - no_frost
            - vacation
      state_content:
        - current_temperature
        - temperature
        - preset_mode
        - state
```

### Additional information

fwiw, Iv e added a stack of buttons below the Tile card so you can see what I am trying to do

<img width="524" alt="Scherm­afbeelding 2024-02-05 om 11 07 31" src="https://github.com/home-assistant/frontend/assets/33354141/7211e634-7fcc-438a-a9a2-1e597efc5d54">
