### ISSUE TITLE
When device is deleted, automation UI fails to handle references to that device cleanly

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/frontend#19694]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Deleting a device causes the Automation Editor's Device Action values to become empty. When this happens (usually without you noticing) and you try to save your automation in the editor, you receive an error message "Message malformed: Integration '' not found".

![image](https://github.com/home-assistant/frontend/assets/50791984/8dda766c-23a9-41df-8df6-20131c66fe91)

# UI
![image](https://github.com/home-assistant/frontend/assets/50791984/c6ea9191-4372-4b18-b838-dbeae8a392fe)

# YAML
![image](https://github.com/home-assistant/frontend/assets/50791984/a720e0b2-661f-40b4-8071-c02b31858df5)

# Browser Console
![image](https://github.com/home-assistant/frontend/assets/50791984/f06ff3ef-a088-4cca-98b3-e523596faf72)

# API Response
![image](https://github.com/home-assistant/frontend/assets/50791984/61d6143a-a354-4f87-af48-7a9cd9c0dfa7)

### Describe the behavior you expected

I vaguely recall that the toast used to say the actual error, such as "Unknown device 'e9eee6046b80aabf468dc51c90a26297'" or "Device not found" but that does not happen anymore (despite that both of those show in the browser console).

If we can avoid sending malformed data to HA Core that would always be better.

### Steps to reproduce the issue

1. Create automation with device action and save
2. Delete that device itself (not the automation entry)
3. View the automation device action

### What version of Home Assistant Core has the issue?

core-2024.2.0b7

### What was the last working version of Home Assistant Core?

Prior to 2020

### State of relevant entities

```txt
Before the device was deleted, device_id, domain and entity_id were all populated.
```

### Problem-relevant frontend configuration

```yaml
alias: Garage - EV Schedule
description: ""
trigger:
  - platform: time
    at: "21:01:00"
    id: time_start
    alias: Begin Off Peak (TOD)
  - platform: time
    at: "06:59:00"
    id: time_stop
    alias: End Off-Peak (TOD)
  - alias: Begin solar (producing more than 1.8 kW)
    platform: numeric_state
    entity_id:
      - sensor.garage_solar_inverter_pv_power
    for:
      hours: 0
      minutes: 5
      seconds: 0
    id: solar_start
    above: 1.8
  - alias: End solar (producing less 1.8 kW)
    platform: numeric_state
    entity_id:
      - sensor.garage_solar_inverter_pv_power
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: 1.8
    id: solar_stop_fixed
  - alias: End solar (producing less than EV is consuming)
    platform: numeric_state
    entity_id:
      - sensor.garage_solar_inverter_pv_power
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: sensor.garage_ev_current_power
    id: solar_stop_dynamic
condition:
  - condition: numeric_state
    entity_id: zone.home
    above: 0
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - solar_start
              - time_start
        sequence:
          - device_id: ""
            domain: ""
            entity_id: ""
          - device_id: ""
            domain: ""
            entity_id: ""
      - conditions:
          - condition: trigger
            id:
              - solar_stop_fixed
              - solar_stop_dynamic
        sequence:
          - device_id: ""
            domain: ""
            entity_id: ""
          - device_id: ""
            domain: ""
            entity_id: ""
      - conditions:
          - condition: trigger
            id:
              - time_stop
        sequence:
          - device_id: ""
            domain: ""
            entity_id: ""
          - device_id: ""
            domain: ""
            entity_id: ""
mode: parallel
max: 10
```

### Javascript errors shown in your browser console/inspector

```txt
ha-automation-editor.ts:494  Uncaught (in promise) Objectcode: "home_assistant_error"message: "Unknown device 'e9eee6046b80aabf468dc51c90a26297'"[[Prototype]]: Object
ha-device-automation-picker.ts:160  Uncaught (in promise) Objectcode: "not_found"message: "Device not found"[[Prototype]]: Object
ha-device-automation-picker.ts:160  Uncaught (in promise) Objectcode: "not_found"message: "Device not found"[[Prototype]]: Object
ha-device-automation-picker.ts:160  Uncaught (in promise) Objectcode: "not_found"message: "Device not found"[[Prototype]]: Object
ha-device-automation-picker.ts:160  Uncaught (in promise) Objectcode: "not_found"message: "Device not found"[[Prototype]]: Object
ha-device-automation-picker.ts:160  Uncaught (in promise) Objectcode: "not_found"message: "Device not found"[[Prototype]]: Object
ha-device-automation-picker.ts:160  Uncaught (in promise) Objectcode: "not_found"message: "Device not found"[[Prototype]]: Object
90[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Forced reflow while executing JavaScript took 35ms
fetch-with-auth.ts:20 
        
        
        POST https://xxx/api/config/automation/config/1697489596989 400 (Bad Request)
U @ fetch-with-auth.ts:20
await in U (async)
(anonymous) @ hass-call-api.ts:71
callApi @ connection-mixin.ts:155
h @ automation.ts:353
value @ ha-automation-editor.ts:723
handleEvent @ lit-html.ts:2018
ha-automation-editor.ts:737  Uncaught (in promise) {error: 'Response error: 400', status_code: 400, body: {…}}
value @ ha-automation-editor.ts:737
await in value (async)
handleEvent @ lit-html.ts:2018
fetch-with-auth.ts:20 
        
        
        POST https://xxx/api/config/automation/config/1697489596989 400 (Bad Request)
U @ fetch-with-auth.ts:20
(anonymous) @ hass-call-api.ts:71
callApi @ connection-mixin.ts:155
h @ automation.ts:353
value @ ha-automation-editor.ts:723
handleEvent @ lit-html.ts:2018
ha-automation-editor.ts:737  Uncaught (in promise) {error: 'Response error: 400', status_code: 400, body: {…}}
value @ ha-automation-editor.ts:737
await in value (async)
handleEvent @ lit-html.ts:2018

fetch-with-auth.ts:20 
        
        
        POST https://xxx/api/config/automation/config/1697489596989 400 (Bad Request)
U @ fetch-with-auth.ts:20
(anonymous) @ hass-call-api.ts:71
callApi @ connection-mixin.ts:155
h @ automation.ts:353
value @ ha-automation-editor.ts:723
handleEvent @ lit-html.ts:2018
ha-automation-editor.ts:737  Uncaught (in promise) {error: 'Response error: 400', status_code: 400, body: {…}}
```

### Additional information

https://community.home-assistant.io/t/message-malformed-integration-not-found-what-have-i-done/178480
