### ISSUE TITLE
To Do List in Browser Mod Popup - Issues

### ISSUE THREAD

**Issue by smartqasa** [home-assistant/frontend#19705]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Displaying a To Do List card as content in a browser_mod.popup prevents editing of items, reordering of items, and removing of completed items.

Here is a video...

https://github.com/home-assistant/frontend/assets/54689141/a1a205b8-e192-4af1-87b4-7b23a2be0ce7

### Describe the behavior you expected

Launching from a dashboard using the following code:

```
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Shopping
      timeout:  600000
      content:
        type: todo-list
        entity: todo.shopping_list
```

### What version of Home Assistant Core has the issue?

core-2024.1.6

### In which browser are you experiencing the issue with?

Fully Kiosk Version , Google Chrome Version 121.0.6167.140 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Android 11, Windows 11
