### ISSUE TITLE
using attribute option in entities card does not show the attribute name (but defaults to the main entity)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19840]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

using a simple Dashboard like:

```
    entities:
      - type: attribute
        entity: sun.sun
        attribute: next_rising
        # name: Volgende Zonsopkomst
        icon: mdi:weather-sunset-up
        format: time
      - type: attribute
        entity: sun.sun
        attribute: next_setting
        # name: Volgende Zonsondergang
        icon: mdi:weather-sunset-down
        format: relative
```

shows like

<img width="997" alt="Scherm­afbeelding 2024-02-20 om 14 07 33" src="https://github.com/home-assistant/frontend/assets/33354141/083de5fb-0138-4d3d-8284-0dba41d22a01">

where one would expect the name or preferably the translated name of that attribute:

<img width="581" alt="Scherm­afbeelding 2024-02-20 om 14 01 18" src="https://github.com/home-assistant/frontend/assets/33354141/b4cb4ed5-0add-4326-acd9-cd87ba1b585d">

we have to explicitly set the `name:` option as commented in above example, to result in something like

<img width="998" alt="Scherm­afbeelding 2024-02-20 om 14 07 59" src="https://github.com/home-assistant/frontend/assets/33354141/eb6794c3-d0a4-4fd7-a86e-91c8bd078c0f">

this feels like an issue which should have been reported long time ago, but that never happened as far as I could find.

### Describe the behavior you expected

use (translated) name of configured attribute , just like the state of that attribute is used.

### Steps to reproduce the issue

1. use config above
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.3.0.dev20240220 (but also in any version below)

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Sonoma 14.2.1

### State of relevant entities

```txt
frontend 20240220.0.dev
```

### Problem-relevant frontend configuration

```yaml
entities:
      - type: attribute
        entity: sun.sun
        attribute: next_rising
        # name: Volgende Zonsopkomst
        icon: mdi:weather-sunset-up
        format: time
      - type: attribute
        entity: sun.sun
        attribute: next_setting
        # name: Volgende Zonsondergang
        icon: mdi:weather-sunset-down
        format: relative
```
