### ISSUE TITLE
Automation trace (graph) rendering issue

### ISSUE THREAD

**Issue by Chaos02** [home-assistant/frontend#19860]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

for *some* reason the automation trace (of seemingly only this automation?) is not displayed correctly. I suspect some issue while parsing the json of the [tracefile](https://pastebin.com/UKY5kg9Y)... it seems to cut off the first letter of the "action" list after the first couple entries and it continues for the rest of the trace.
Given that the automation affected does not seem *that* complex it kinda surprises me.
![image](https://github.com/home-assistant/frontend/assets/20928702/dd4d400a-6949-4a57-bf0e-ebf79e5ce035)

### Describe the behavior you expected

correct rendering of the trace graph and timeline

### Steps to reproduce the issue

Afaik this issue has existed since I created the automation ~December 2023
### Automation in Question:
```yaml
alias: Light Control
description: >-
  Turns on Lights at Sundown and emulates someone being home if no one is with
  Random Turn on/off times.
trigger:
  - platform: sun
    event: sunset
    offset: 0
condition: null
action:
  - type: turn_on
    device_id: a606eaf04e10a7767b1352ba4a3ee9f1
    entity_id: 6cd4f2733e2e132e1cd4177c3963c29b
    domain: light
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: zone.home
            below: 1
        sequence:
          - variables:
              bedTime: >-
                {{ now() + timedelta(hours=(range(5, 8) | random),
                minutes=(range(0, 59) | random), seconds=(range(0, 59) |
                random)) }}
          - delay:
              hours: 4
              minutes: 0
              seconds: 0
              milliseconds: 0
          - service: media_player.turn_on
            target:
              entity_id: []
              device_id: []
              area_id:
                - 0_wohnzimmer
            data: {}
            enabled: false
          - delay:
              hours: 1
              minutes: 0
              seconds: 0
              milliseconds: 0
          - wait_template: "{{ now() > as_datetime(bedTime) }}"
            continue_on_timeout: true
            timeout: "06:00:00"
          - service: media_player.turn_off
            target:
              area_id: 0_wohnzimmer
            data: {}
          - delay:
              hours: 0
              minutes: 16
              seconds: 17
              milliseconds: 0
          - type: turn_off
            device_id: a606eaf04e10a7767b1352ba4a3ee9f1
            entity_id: c46e5dcbceac7fbbb8409a65b3ee5552
            domain: switch
    default:
      - delay:
          hours: 4
          minutes: 0
          seconds: 0
          milliseconds: 0
      - wait_for_trigger:
          - platform: state
            entity_id:
              - media_player.samsung_q8_series_55_2
              - device_tracker.wintop
            from: "on"
            to: "off"
            for:
              hours: 0
              minutes: 20
              seconds: 0
        timeout:
          hours: 6
          minutes: 0
          seconds: 0
          milliseconds: 0
      - type: turn_off
        device_id: a606eaf04e10a7767b1352ba4a3ee9f1
        entity_id: 6cd4f2733e2e132e1cd4177c3963c29b
        domain: light
mode: restart
```

### What version of Home Assistant Core has the issue?

core-2024.2.2

### In which browser are you experiencing the issue with?

Google Chrome 123.0.6312.5

### Which operating system are you using to run this browser?

Windows 11 (22631.3155)

### Javascript errors shown in your browser console/inspector

```txt
/
```
