### ISSUE TITLE
Automation Issue with !secret tag

### ISSUE THREAD

**Issue by meluvalli** [home-assistant/frontend#19871]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If you use the tag "!secret" to reference secrets.yaml in automations.yaml, you receive an error in FE saying "This automation cannot be edited from the UI, because it is not stored in the automations.yaml file, or doesn't have an ID."

### Describe the behavior you expected

This error shouldn't be there and the automation does have ID's associated with them.  If you remove all references from !secret, this problem goes away.

### Steps to reproduce the issue

1. Create automation in YAML.
2. Reference !secret yaml in automation.
3. Save automation and reload.
4. Go to FE Settings/Automations.
5. Select any automation and it'll show the error.
...

### What version of Home Assistant Core has the issue?

2024.2.3

### In which browser are you experiencing the issue with?

All (N/A)

### Which operating system are you using to run this browser?

N/A

### Problem-relevant frontend configuration

```yaml
- alias: Security Arm Stay Switch
  id: 958c51c9d9104e5294da50a083645bd7
  trigger:
    - platform: state
      entity_id: input_boolean.security_arm_stay
      to: "on"
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.home_alarm_system
        code: !secret alarm_code
    - service: lock.lock
      entity_id: lock.b051mxjg_lock_mechanism
```

### Additional information

FYI: This was also reported in the community forum.  
https://community.home-assistant.io/t/this-automation-cannot-be-edited-from-the-ui/557254/3
