### ISSUE TITLE
cards missing Edit mode after Core update 2024.2.5 - Restored 2024.2.4

### ISSUE THREAD

**Issue by beralios** [home-assistant/frontend#19923]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After update to Core 2024.2.5, the "Edit Dashboard" function works only for New Views. The cards inside all view missing the EDIT function.

### Describe the behavior you expected

The cards inside different Views should have the EDIT function, when the "Edit Dashboard" is activated.

### Steps to reproduce the issue

1. update to Core 2024.2.5
2. wait until the end, reboot included
3. Try to edit cards with the "Edit Dashboard" function activated
...

### What version of Home Assistant Core has the issue?

Core 2024.2.5

### What was the last working version of Home Assistant Core?

Core 2024.2.4

### In which browser are you experiencing the issue with?

Chrome Version 121.0.6167.162

### Which operating system are you using to run this browser?

Home Assistant OS 12.0

### State of relevant entities

```txt
no problems on single entities
```

### Problem-relevant frontend configuration

```yaml
YAML of my Dashboard
title: TANA
style:
  background-color: yellow
views:
  - path: default_view
    title: Home
    cards:
      - type: entities
        entities:
          - entity: person.tana
          - entity: weather.forecast_home
        view_layout:
          column: 2
        show_header_toggle: true
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.tana
        secondary_info_attribute: forecast
      - type: vertical-stack
        cards:
          - type: entity
            entity: sensor.sun_next_dawn
            icon: mdi:sun-clock
          - type: entity
            entity: sensor.sun_next_dusk
            icon: mdi:sun-clock-outline
      - type: map
        entities:
          - entity: device_tracker.c_hr_parking_location
          - entity: device_tracker.tb132fu
          - entity: device_tracker.oppolone
        aspect_ratio: '16:9'
        default_zoom: 16
        dark_mode: true
        title: Devices Location
  - theme: Backend-selected
    title: Toyota
    path: toyota
    icon: mdi:car
    columns: 4
    square: false
    subview: false
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: picture-elements
            name: CHR
            elements:
              - type: state-badge
                entity: sensor.c_hr_fuel_level
                style:
                  top: 92%
                  left: 10%
              - type: state-badge
                entity: sensor.c_hr_odometer
                style:
                  top: 92%
                  left: 90%
            image: >-
              https://dj3z27z47basa.cloudfront.net/b4f9e388-0a03-47ab-bfdd-39b63d577171
            card_mod:
              style: |
                ha-card {
                  --ha-card-background: #00394d;
                  color: var(--primary-color);
                  border: 2px solid #e68a00;
                }
          - type: gauge
            entity: sensor.c_hr_fuel_level
            needle: true
            severity:
              green: 35
              yellow: 12
              red: 0
            name: Benza
            unit: '%'
            card_mod:
              view:
                - 80
              style: |
                ha-card {
                  --ha-card-background: #00394d;
                  color: var(--primary-color);
                  border: 2px solid #e68a00;
                }
          - type: gauge
            entity: sensor.c_hr_odometer
            severity:
              green: 0
              yellow: 150000
              red: 180000
            needle: true
            name: ODOmeter
            max: 200000
            min: 0
            unit: Km
            card_mod:
              view:
                - 80
              style: |
                ha-card {
                  --ha-card-background: #00394d;
                  color: var(--primary-color);
                  border: 2px solid #e68a00;
                }
      - type: entities
        entities:
          - entity: sensor.c_hr_vehicle_identify_number
            name: Numberplate
            icon: mdi:lock
          - entity: device_tracker.c_hr_parking_location
            name: Parking location
          - entity: sensor.c_hr_odometer
            secondary_info: last-changed
            icon: mdi:car
          - entity: sensor.c_hr_fuel_level
        title: C-HR
      - type: vertical-stack
        title: Statistiche Giornaliere
        cards:
          - type: entities
            entities:
              - entity: sensor.c_hr_current_day_statistics
                icon: mdi:update
                secondary_info: last-updated
                name: Km in Giornata
            show_header_toggle: false
            state_color: true
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: sensor.c_hr_ev_driving_dist_d
                    name: In EV
                    secondary_info: none
                    icon: mdi:car-electric-outline
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: entities
                entities:
                  - entity: sensor.c_hr_trips_d
                    name: Viaggi
                    icon: mdi:jellyfish
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
          - type: entities
            entities:
              - entity: sensor.c_hr_driving_time_d
                name: Tempo Totale
                icon: mdi:update
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: entities
            entities:
              - entity: sensor.c_hr_ev_driving_time_d
                name: Tempo in EV
                icon: mdi:update
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.c_hr_av_drive_score_d
                name: Total Score
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: gauge
                entity: sensor.c_hr_av_drive_score_acc_d
                name: Acceleration
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: gauge
                entity: sensor.c_hr_av_drive_score_brak_d
                name: Brake
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
          - type: gauge
            entity: sensor.c_hr_ev_dur_perc_d
            name: Percentage in EV
            unit: '%'
            severity:
              green: 50
              yellow: 30
              red: 0
            needle: true
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
      - type: map
        entities:
          - device_tracker.c_hr_parking_location
        title: Parcheggio
        card_mod:
          style: |
            ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
            }
      - type: vertical-stack
        title: Statistiche Settimana
        cards:
          - type: entities
            entities:
              - entity: sensor.c_hr_current_week_statistics
                icon: mdi:update
                secondary_info: last-updated
                name: Km in Settimana
            show_header_toggle: false
            state_color: true
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: sensor.c_hr_ev_driving_dist_w
                    name: In EV
                    secondary_info: none
                    icon: mdi:car-electric-outline
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: entities
                entities:
                  - entity: sensor.c_hr_trips_w
                    name: Viaggi
                    icon: mdi:jellyfish
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
          - type: entities
            entities:
              - entity: sensor.c_hr_driving_time_w
                name: Tempo Totale
                icon: mdi:update
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: entities
            entities:
              - entity: sensor.c_hr_ev_driving_time_w
                name: Tempo in EV
                icon: mdi:update
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.c_hr_av_drive_score_w
                name: Total Score
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: gauge
                entity: sensor.c_hr_av_drive_score_acc_w
                name: Acceleration
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: gauge
                entity: sensor.c_hr_av_drive_score_brak_w
                name: Brake
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
          - type: gauge
            entity: sensor.c_hr_ev_dur_perc_w
            name: Percentage in EV
            unit: '%'
            severity:
              green: 50
              yellow: 30
              red: 0
            needle: true
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
      - type: vertical-stack
        title: Statistiche Mese
        cards:
          - type: entities
            entities:
              - entity: sensor.c_hr_current_month_statistics
                icon: mdi:update
                secondary_info: last-updated
                name: Km nel Mese
            show_header_toggle: false
            state_color: true
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: sensor.c_hr_ev_driving_dist_m
                    name: Km in EV
                    secondary_info: none
                    icon: mdi:car-electric-outline
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: entities
                entities:
                  - entity: sensor.c_hr_trips_m
                    name: Viaggi
                    icon: mdi:jellyfish
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
          - type: entities
            entities:
              - entity: sensor.c_hr_driving_time_m
                name: Tempo Totale
                icon: mdi:update
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: entities
            entities:
              - entity: sensor.c_hr_ev_driving_time_m
                name: Tempo in EV
                icon: mdi:update
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.c_hr_av_drive_score_m
                name: Total Score
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: gauge
                entity: sensor.c_hr_av_drive_score_acc_m
                name: Acceleration
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: gauge
                entity: sensor.c_hr_av_drive_score_brak_m
                name: Brake
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
          - type: gauge
            entity: sensor.c_hr_ev_dur_perc_m
            name: Percentage in EV
            unit: '%'
            severity:
              green: 50
              yellow: 30
              red: 0
            needle: true
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
      - type: vertical-stack
        title: Statistiche Anno
        cards:
          - type: entities
            entities:
              - entity: sensor.c_hr_current_year_statistics
                icon: mdi:update
                secondary_info: last-updated
                name: Km Ultimo Anno
            show_header_toggle: false
            state_color: true
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: sensor.c_hr_ev_driving_dist_y
                    name: In EV
                    secondary_info: none
                    icon: mdi:car-electric-outline
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: entities
                entities:
                  - entity: sensor.c_hr_trips_y
                    name: Viaggi
                    icon: mdi:jellyfish
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
          - type: entities
            entities:
              - entity: sensor.c_hr_driving_time_y
                name: Tempo Totale
                icon: mdi:update
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: entities
            entities:
              - entity: sensor.c_hr_ev_driving_time_y
                name: Tempo in EV
                icon: mdi:update
            card_mod: null
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.c_hr_av_drive_score_y
                name: Total Score
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: gauge
                entity: sensor.c_hr_av_drive_score_acc_y
                name: Acceleration
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
              - type: gauge
                entity: sensor.c_hr_av_drive_score_brak_y
                name: Brake
                unit: '%'
                min: 0
                max: 100
                needle: true
                severity:
                  green: 70
                  yellow: 40
                  red: 0
                card_mod: null
                style: |
                  ha-card {
                  --ha-card-background: #00394d;
                  color: #e68a00;
                  border: 2px solid #e68a00;
                  }
          - type: gauge
            entity: sensor.c_hr_ev_dur_perc_y
            name: Percentage in EV
            unit: '%'
            severity:
              green: 50
              yellow: 30
              red: 0
            needle: true
            style: |
              ha-card {
              --ha-card-background: #00394d;
              color: #e68a00;
              border: 2px solid #e68a00;
              }
      - type: vertical-stack
        title: Fuel Consumption
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.c_hr_av_fuel_cons_d
                name: for 100km Daily
                unit: Lit
                needle: true
                severity:
                  green: 0
                  yellow: 6
                  red: 9
                max: 18
                min: 1
              - type: gauge
                entity: sensor.c_hr_av_fuel_cons_w
                name: for 100km Weekly
                unit: Lit
                needle: true
                severity:
                  green: 0
                  yellow: 6
                  red: 9
                max: 18
                min: 1
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.c_hr_av_fuel_cons_m
                name: for 100km Monthly
                unit: Lit
                needle: true
                severity:
                  green: 0
                  yellow: 6
                  red: 9
                max: 18
                min: 1
              - type: gauge
                entity: sensor.c_hr_av_fuel_cons_y
                name: for 100km Yearly
                unit: Lit
                needle: true
                severity:
                  green: 0
                  yellow: 6
                  red: 9
                max: 18
                min: 1
      - type: vertical-stack
        title: Kilomteri Totali
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.c_hr_current_day_statistics
                name: Daily
                unit: Km
                needle: true
                severity:
                  green: 0
                  yellow: 30
                  red: 60
                max: 90
                min: 1
              - type: gauge
                entity: sensor.c_hr_current_week_statistics
                name: Weekly
                unit: Km
                needle: true
                severity:
                  green: 0
                  yellow: 130
                  red: 180
                max: 209
                min: 0
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.c_hr_current_month_statistics
                name: Monthly
                unit: Km
                needle: true
                severity:
                  green: 0
                  yellow: 500
                  red: 700
                max: 834
                min: 0
              - type: gauge
                entity: sensor.c_hr_current_year_statistics
                name: Yearly
                unit: Lit
                needle: true
                severity:
                  green: 0
                  yellow: 6000
                  red: 8000
                max: 10000
                min: 0
      - type: entities
        entities:
          - entity: sensor.c_hr_current_day_statistics
            name: Current day statistics
          - entity: sensor.c_hr_current_week_statistics
            name: Current week statistics
          - entity: sensor.c_hr_current_month_statistics
            name: Current month statistics
          - entity: sensor.c_hr_current_year_statistics
            name: Current year statistics
          - entity: sensor.c_hr_fuel_level
            name: Fuel tank
          - entity: sensor.c_hr_odometer
            name: Odometer
        title: C-HR
      - type: vertical-stack
        title: Tempo in Auto
        cards:
          - type: entity
            entity: sensor.c_hr_driving_time_d
            icon: mdi:car
            state_color: true
            name: Time Last Day
          - type: entity
            entity: sensor.c_hr_driving_time_w
            icon: mdi:car
            state_color: true
            name: Time Last Week
          - type: entity
            entity: sensor.c_hr_driving_time_m
            icon: mdi:car
            state_color: true
            name: Time Last Month
          - type: entity
            entity: sensor.c_hr_driving_time_y
            icon: mdi:car
            state_color: true
            name: Time Last Year
      - type: vertical-stack
        title: Tempo in EV
        cards:
          - type: entity
            entity: sensor.c_hr_ev_driving_time_d
            name: EV Last Day
          - type: entity
            entity: sensor.c_hr_ev_driving_time_w
            icon: mdi:car
            state_color: true
            name: EV Last Week
          - type: entity
            entity: sensor.c_hr_ev_driving_time_m
            icon: mdi:car
            state_color: true
            name: EV Last Month
          - type: entity
            entity: sensor.c_hr_ev_driving_time_y
            icon: mdi:car
            state_color: true
            name: EV Last Year
      - type: vertical-stack
        title: Viaggi Notturni
        cards:
          - type: entity
            entity: sensor.c_hr_night_trips_d
            icon: mdi:car
            state_color: true
            name: Last Day
          - type: entity
            entity: sensor.c_hr_night_trips_w
            icon: mdi:car
            state_color: true
            name: Last Week
          - type: entity
            entity: sensor.c_hr_night_trips_m
            icon: mdi:car
            state_color: true
            name: Last Month
          - type: entity
            entity: sensor.c_hr_night_trips_y
            icon: mdi:car
            state_color: true
            name: Last Year
      - type: vertical-stack
        title: Viaggi fatti
        cards:
          - type: entity
            entity: sensor.c_hr_trips_d
            icon: mdi:car
            state_color: true
            name: Last Day
          - type: entity
            entity: sensor.c_hr_trips_w
            icon: mdi:car
            state_color: true
            name: Last Week
          - type: entity
            entity: sensor.c_hr_trips_m
            icon: mdi:car
            state_color: true
            name: Last Month
          - type: entity
            entity: sensor.c_hr_trips_y
            icon: mdi:car
            state_color: true
            name: Last Year
      - type: vertical-stack
        title: Kilometri in Autostrada
        cards:
          - type: entity
            entity: sensor.c_hr_max_highw_km_daily
            icon: mdi:car
            state_color: true
            name: Last Day
            unit: Km
          - type: entity
            entity: sensor.c_hr_max_highw_km_weekly
            icon: mdi:car
            state_color: true
            name: Last Week
            unit: Km
          - type: entity
            entity: sensor.c_hr_max_highw_km_monthly
            icon: mdi:car
            state_color: true
            name: Last Month
            unit: Km
          - type: entity
            entity: sensor.c_hr_max_highw_km_year
            icon: mdi:car
            state_color: true
            name: Last Year
            unit: Km
      - type: vertical-stack
        title: Percentuale Autostrada
        cards:
          - type: entity
            entity: sensor.c_hr_max_highw_perc_daily
            icon: mdi:car
            state_color: true
            name: Last Day
            unit: '%'
          - type: entity
            entity: sensor.c_hr_max_highw_perc_weekly
            icon: mdi:car
            state_color: true
            name: Last Week
            unit: '%'
          - type: entity
            entity: sensor.c_hr_max_highw_perc_monthly
            icon: mdi:car
            state_color: true
            name: Last Month
            unit: '%'
          - type: entity
            entity: sensor.c_hr_max_highw_perc_year
            icon: mdi:car
            state_color: true
            name: Last Year
            unit: '%'
      - type: vertical-stack
        title: Last Trip
        cards:
          - type: entity
            entity: sensor.c_hr_current_day_statistics
            name: Kilometri Totali
          - type: entity
            entity: sensor.c_hr_driving_time_d
          - type: tile
            entity: sensor.c_hr_max_highw_km_daily
          - type: tile
            entity: sensor.c_hr_max_highw_perc_daily
          - type: tile
            entity: sensor.c_hr_av_fuel_cons_d
          - type: tile
            entity: sensor.c_hr_max_speed_daily
          - type: tile
            entity: sensor.c_hr_ev_driving_perc_d
  - title: Surveillance
    path: surveillance
    icon: mdi:camera-enhance-outline
    badges: []
    cards:
      - type: entity
        entity: sensor.sun_next_midnight
        icon: fas:heartbeat
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.10_10_10_38_torch
            icon: mdi:white-balance-sunny
            name: Corridor Torch
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.10_10_10_35_torch
            icon: mdi:white-balance-sunny
            name: Salotto Torch
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: call-service
              service: camera.snapshot
              target:
                entity_id: camera.10_10_10_38
              data:
                filename: >-
                  /media/Streaming/snap.corridoio.{{
                  now().strftime("%Y%m%d-%H%M%S") }}.jpg
            entity: camera.10_10_10_38
            icon: mdi:panorama-variant-outline
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: call-service
              service: camera.snapshot
              target:
                entity_id: camera.10_10_10_35
              data:
                filename: >-
                  /media/Streaming/snap.salotto.{{
                  now().strftime("%Y%m%d-%H%M%S") }}.jpg
            entity: camera.10_10_10_35
            icon: mdi:panorama-variant-outline
      - camera_view: live
        type: picture-glance
        title: Corridoio
        entities:
          - entity: sensor.10_10_10_38_motion
          - entity: switch.10_10_10_38_motion_detection
          - entity: switch.10_10_10_38_night_vision
          - entity: switch.10_10_10_38_torch
        camera_image: camera.10_10_10_38
        entity: camera.10_10_10_38
      - camera_view: live
        type: picture-glance
        title: Salotto
        entities:
          - entity: switch.10_10_10_35_night_vision
          - entity: sensor.10_10_10_35_motion
          - entity: switch.10_10_10_35_motion_detection
          - entity: binary_sensor.10_10_10_35_motion_active
        camera_image: camera.10_10_10_35
  - title: ASUS
    path: asus
    icon: mdi:router-wireless
    badges: []
    cards:
      - type: gauge
        entity: sensor.rt_ax88u_86c8_kib_s_sent
        name: Kappa Sent
        unit: Kb
        needle: true
      - type: entities
        entities:
          - entity: update.rt_ax88u_firmware_update
            name: Firmware update
        title: RT-AX88U
      - type: gauge
        entity: sensor.rt_ax88u_wan_download
        name: AsusWAN Download
        unit: Mb
        needle: true
      - type: entities
        entities:
          - entity: sensor.rt_ax88u_86c8_kib_s_received
            name: KiB/s received
          - entity: sensor.rt_ax88u_86c8_kib_s_sent
            name: KiB/s sent
        title: RT-AX88U-86C8
      - type: gauge
        entity: sensor.rt_ax88u_wan_download_speed
        severity:
          green: 100
          yellow: 50
          red: 0
        needle: true
        unit: Mbit/s
        name: WAN Down Speed
        max: 250
      - type: gauge
        entity: sensor.rt_ax88u_wired_download_speed
        severity:
          green: 100
          yellow: 50
          red: 0
        needle: true
        unit: Mbit/s
        name: Wired Down Speed
        max: 250
      - type: gauge
        entity: sensor.rt_ax88u_wan_download_speed
        name: WAN Down
        needle: true
        unit: Mb
  - title: TANANASSO
    path: tananasso
    icon: mdi:nas
    subview: false
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.tananasso_cpu_usage
            name: CPU Usage
          - entity: sensor.tananasso_memory_usage
            name: Memory Usage
          - entity: sensor.tananasso_network_link_eth0
            name: Network Link (eth0)
          - entity: sensor.tananasso_network_link_eth1
            name: Network Link (eth1)
          - entity: sensor.tananasso_network_link_eth2
            name: Network Link (eth2)
          - entity: sensor.tananasso_network_link_eth3
            name: Network Link (eth3)
          - entity: sensor.tananasso_status
            name: Status
          - entity: sensor.tananasso_system_temperature
            name: System Temperature
          - entity: sensor.tananasso_volume_used_datavol1
            name: Volume Used (DataVol1)
        title: TANANASSO
      - type: gauge
        entity: sensor.tananasso_cpu_usage
        name: CPU
        needle: true
        severity:
          green: 0
          yellow: 50
          red: 80
      - type: gauge
        entity: sensor.tananasso_memory_usage
        needle: true
        severity:
          green: 0
          yellow: 50
          red: 80
        name: Memory
      - type: gauge
        entity: sensor.tananasso_volume_used_datavol1
        name: Occupied
        severity:
          green: 0
          yellow: 60
          red: 80
        needle: true
  - title: Garmin Swim2
    path: garmin-swim2
    icon: mdi:clock
    badges:
      - entity: sensor.body_battery_most_recent
      - entity: sensor.active_time
    cards:
      - chart_type: line
        period: day
        type: statistics-graph
        entities:
          - sensor.max_heart_rate
          - sensor.min_heart_rate
          - sensor.resting_heart_rate
        stat_types:
          - sum
          - state
          - change
        days_to_show: 10
        title: Heart Rate
      - type: statistic
        entity: sensor.total_steps
        period:
          calendar:
            period: day
        stat_type: change
      - chart_type: line
        period: day
        type: statistics-graph
        entities:
          - sensor.sleep_duration
          - sensor.sleeping_time
        stat_types:
          - sum
          - state
          - change
        days_to_show: 20
        title: Sleep Info
      - chart_type: line
        period: day
        type: statistics-graph
        entities:
          - sensor.high_stress_duration
          - sensor.low_stress_duration
          - sensor.total_stress_duration
        stat_types:
          - sum
          - state
          - change
        title: Stress
      - chart_type: line
        period: day
        type: statistics-graph
        entities:
          - sensor.body_battery_charged
          - sensor.body_battery_drained
          - sensor.body_battery_most_recent
        stat_types:
          - sum
          - state
          - change
        title: Body Battery
        days_to_show: 10
      - type: entities
        entities:
          - sensor.bmr_kilocalories
          - sensor.burned_kilocalories
          - sensor.sleep_duration
          - sensor.sleep_score
          - sensor.sleeping_time
          - sensor.total_distance_mtr
  - title: Lenovo
    path: lenovo
    icon: mdi:tablet
    width: 300
    max_cols: 10
    subview: false
    visible:
      - user: a31690d887484f9c9d2b9b52a5b07708
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.tb132fu_battery_state
            name: Battery State
          - entity: sensor.tb132fu_charger_type
            name: Charger Type
          - entity: device_tracker.tb132fu
          - entity: sensor.tb132fu_battery_level
        title: TB132FU
      - type: entity
        entity: sensor.tb132fu_wifi_connection
        state_color: true
      - type: entity
        entity: sensor.tb132fu_wifi_ip_address
        name: Tablet IP Address
        state_color: false
        view_layout:
          column: 2
        icon: fas:heart
      - type: entities
        entities:
          - entity: device_tracker.tb132fu
          - entity: sensor.tb132fu_battery_level
          - entity: sensor.tb132fu_battery_state
          - entity: sensor.tb132fu_internal_storage
          - entity: sensor.tb132fu_wifi_ip_address
          - entity: sensor.tb132fu_wifi_connection
          - entity: binary_sensor.tb132fu_wifi_state
        title: Tablet
        state_color: true
      - type: map
        entities:
          - entity: device_tracker.tb132fu
        title: Tablet position
        hours_to_show: 48
      - type: gauge
        entity: sensor.tb132fu_battery_level
        severity:
          green: 40
          yellow: 20
          red: 0
        name: Battery Lvl
        needle: true
  - title: Oppolone
    path: oppolone
    icon: mdi:cellphone
    badges: []
    cards:
      - type: entities
        entities:
          - entity: device_tracker.oppolone
          - entity: binary_sensor.oppolone_android_auto
          - entity: sensor.oppolone_battery_level
          - entity: sensor.oppolone_battery_state
          - entity: binary_sensor.oppolone_bluetooth_state
          - entity: sensor.oppolone_charger_type
          - entity: sensor.oppolone_current_version
          - entity: sensor.oppolone_geocoded_location
          - entity: sensor.oppolone_wifi_ip_address
          - entity: sensor.oppolone_wifi_connection
        state_color: true
      - type: entities
        entities:
          - entity: binary_sensor.oppolone_android_auto
            name: Android Auto
          - entity: sensor.oppolone_geocoded_location
            name: Geocoded location
        title: Oppolone
      - type: map
        entities:
          - entity: device_tracker.oppolone
        title: Oppo Position
      - type: gauge
        entity: sensor.oppolone_battery_level
        needle: true
        severity:
          green: 40
          yellow: 20
          red: 0
      - type: entity
        entity: sensor.oppolone_wifi_connection
        state_color: true
      - type: entity
        entity: sensor.oppolone_wifi_ip_address
        name: Oppo IP Address
        state_color: false
        view_layout:
          column: 2
        icon: fas:heart
      - type: map
        entities:
          - entity: device_tracker.oppolone
        title: Oppo Position 24h
        hours_to_show: 24
        dark_mode: true
        geo_location_sources: []
        card_mod:
          style:
            ha-map$:
              .leaflet-pane: |
                path {
                  fill: blue;
                  stroke: red;
                  stroke-width: 3;
                }
              .leaflet-overlay-pane: |
                path {
                  fill: red;
                  stroke: red;
                  stroke-width: 3;
                }
      - type: map
        entities:
          - entity: device_tracker.oppolone
        title: Oppo Position 48h
        dark_mode: true
        hours_to_show: 48
        geo_location_sources: []
        card_mod:
          style:
            ha-map$:
              .leaflet-pane: |
                path {
                  fill: blue;
                  stroke: blue;
                  stroke-width: 3;
                }
              .leaflet-overlay-pane: |
                path {
                  fill: red;
                  stroke: blue;
                  stroke-width: 3;
                }
      - type: map
        entities:
          - entity: device_tracker.oppolone
        title: Oppo Position 72h
        dark_mode: true
        hours_to_show: 72
        geo_location_sources: []
        card_mod:
          style:
            ha-map$:
              .leaflet-pane: |
                path {
                  fill: blue;
                  stroke: yellow;
                  stroke-width: 3;
                }
              .leaflet-overlay-pane: |
                path {
                  fill: red;
                  stroke: yellow;
                  stroke-width: 3;
                }
  - title: Oppo Movement
    path: oppo-movement
    icon: mdi:cellphone-link
    subview: false
    type: panel
    badges: []
    cards:
      - type: map
        entities:
          - entity: device_tracker.oppolone
        title: Oppo Last 72h
        dark_mode: true
        geo_location_sources: []
        hours_to_show: 96
        card_mod:
          style:
            ha-map$:
              .leaflet-pane: |
                path {
                  fill: blue;
                  stroke: yellow;
                  stroke-width: 3;
                }
              .leaflet-overlay-pane: |
                path {
                  fill: red;
                  stroke: yellow;
                  stroke-width: 3;
                }
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

I simply restore the previous Backup for Core 2024.2.4 and everything was there (Edit Cards available)
