### ISSUE TITLE
Move Card from Masonry View to Sections View deletes card

### ISSUE THREAD

**Issue by sugnaangus** [home-assistant/frontend#20011]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I attempt to move a card from an existing Masonry View Configuration to a new Sections View Configuration on the same dashboard, the card is deleted without warning.

### Describe the behavior you expected

I expected either a warning message, for this feature to be disabled until implemented, or for the card to be moved to the new View Configuration

### Steps to reproduce the issue

1. Open a dashboard which already has cards 
2. Click Edit Dashboard
3. Click Add View
4. Give the new view a title
5. Change View Type to Sections (experimental)
6. Click save
7. Go back to the original view
8. Choose a card and click the 3 dots for that card
9. Click move to view
10. Select the new view
11. Click move - Card is gone from original view
12. Go to the new view - card is not in new view

### What version of Home Assistant Core has the issue?

core-2024.3.0

**Comment by silamon** [comment]
It's not attached to a section but added as a card like in a masonry view: 

```
  - type: sections
    title: sections
    path: sections
    sections:
      - type: grid
        cards: []
      - type: grid
        cards: []
    cards:
      - type: alarm-panel
        states:
          - arm_home
          - arm_away
        entity: alarm_control_panel.security
 ```
