### ISSUE TITLE
Thermostat card: hvac_action does not update to idle on UI and Developer Tools->States

### ISSUE THREAD

**Issue by amaximus** [home-assistant/frontend#20017]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Thermostat card doesn't update hvac_action to idle even if REST API call shows that the generic thermostat is in idle hvac_action.
The Developer Tools->States also shows the wrong hvac_action information.

### Describe the behavior you expected

When hvac_action is set to 
The heat control works fine though (the switch turns off when current_temp>target_temp+hot_tolerance

### Steps to reproduce the issue

```
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf $grep -v "#" climate.yaml
- platform: generic_thermostat
  name: B3_heat
  heater: switch.shelly1_b3_heat
  target_sensor: sensor.main_temp_template
  min_temp: 18
  max_temp: 23
  precision: 0.1
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf $curl -H @hass_header.txt http://localhost:8123/api/states/switch.shelly1_b3_heat
{"entity_id":"switch.shelly1_b3_heat","state":"off","attributes":{"friendly_name":"shelly1-349454724E19"},"last_changed":"2024-03-07T13:33:38.578557+00:00","last_updated":"2024-03-07T13:33:38.578557+00:00","context":{"id":"01HRCHX5CJ9FGEJASDYDCEJ0M7","parent_id":null,"user_id":null}}(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf $
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf $curl -H @hass_header.txt http://localhost:8123/api/states/climate.b3_heat
{"entity_id":"climate.b3_heat","state":"heat","attributes":{"hvac_modes":["heat","off"],"min_temp":18.0,"max_temp":23.0,"target_temp_step":0.1,"current_temperature":22.3,"temperature":21.5,"hvac_action":"idle","friendly_name":"B3_heat","supported_features":385},"last_changed":"2024-03-07T13:37:00.043704+00:00","last_updated":"2024-03-07T13:37:00.043704+00:00","context":{"id":"01HRCJ3A49EYS9MWFQNVE3YBMT","parent_id":null,"user_id":"c554239d69374adb9ff0e3d31a9de214"}}(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf $
```
![b3_heat](https://github.com/home-assistant/frontend/assets/2511168/34ffe5ae-8d1d-4b45-b7b5-9479cfb9e600)

### What version of Home Assistant Core has the issue?

2024.2.5, 2024.3.0

### What was the last working version of Home Assistant Core?

was working before, I have no version information though

### In which browser are you experiencing the issue with?

Google Chrome 122.0.6261.96

### Which operating system are you using to run this browser?

Windows 10 64 bit

### State of relevant entities

```txt
See the 'Steps to reproduce' section
```

### Problem-relevant frontend configuration

```yaml
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf/lovelace/dashboard_elements $cat heat_b3_heat.yaml
type: thermostat
entity: climate.b3_heat
name: ""
show_current_as_primary: true
features:
  - type: "climate-hvac-modes"
    hvac_modes:
      - heat
      - 'off'
  - type: climate-preset-modes
    style: "icons"
    preset_modes:
      - home
      - sleep
card_mod:
  style: |
    ha-card .title {
      display: none;
    }
(ha_venv3_12) pi@raspberrypi:~/homeassistant_conf/lovelace/dashboard_elements $
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Others have the same issue as reported in:
https://github.com/home-assistant/core/issues/110656
where I originally reported this, but it turned out that it's not the generic_thermostat.
