### ISSUE TITLE
Footer Buttons in Entities Card (state color not changing)

### ISSUE THREAD

**Issue by Great-Chart** [home-assistant/frontend#20022]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating core to 2024.3.0 (frontend = 20240306.0) I noticed (once frontend had refreshed) that footer buttons used within an entities card no longer changed colour when activated.
These buttons are switching boolean entities to hide / un-hide conditional cards.
Adding a new button for an entity such as a light will result in that entity highlighting when operated - shown below.
Adding a new button for a newly created boolean entity will result in that NOT highlighting when activated.
This is shown via the final button below); with the tick indicating it as "on".
![image](https://github.com/home-assistant/frontend/assets/101117351/599b8eef-ea07-4ec1-b4c4-298e6cddff65)

### Describe the behavior you expected

Buttons in footers in cards (this one is an entity card) to change colour when activated

### Steps to reproduce the issue

1. Add buttons into footers on entities card; including input booleans
2. Test behaviour for entities such as light
3. Test behaviour for input boolean (toggle) 

### What version of Home Assistant Core has the issue?

2024.3.0

### What was the last working version of Home Assistant Core?

2024.2.5

### In which browser are you experiencing the issue with?

Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro 19045.4046

### Problem-relevant frontend configuration

```yaml
footer:
  type: buttons
  entities:
    - entity: input_boolean.office
      name: Office
    - entity: input_boolean.bin_day
      name: Bin Day
    - entity: input_boolean.hive
      name: Heating
    - entity: input_boolean.map
      name: Map
    - entity: input_boolean.mode
      name: Mode
    - entity: input_boolean.xmas
      name: XMAS Lights
    - entity: light.bathroom_light
    - entity: input_boolean.testfooter
```

**Comment by chadbaum** [comment]
Adding that this is also impacting my "buttons" rows of the "entities" card.  All buttons as of latest update no longer show state by color.

**Comment by webwude** [comment]
In my entity card the same.

`type: entities
entities:
  - type: section
    label: Dachzimmer
  - type: buttons
    entities:
      - entity: switch.schreibtisch_dach
        name: Schreibtisch & Drucker
      - entity: switch.dach_medien
        name: TV & Medien
  - type: section
    label: Wohnzimmer
  - type: buttons
    entities:
      - entity: switch.medien_wohnzimmer
        name: TV & Medien
  - type: section
    label: Medienzimmer
  - type: buttons
    entities:
      - entity: switch.medienzimmer
        name: TV & Medien
      - entity: switch.meross_steckdosenleiste_outlet_5
        name: USB
  - type: section
    label: Keller
  - type: buttons
    entities:
      - entity: switch.waschmaschine
        name: Waschmaschine
      - entity: switch.trockner
        name: Trockner
title: Steckdosen
state_color: true
`

No state color on activation.
Even a rollback to 2024.2.5 did not help.

**Comment by blubbel42** [comment]
same problem  here with header-buttons in entities-cards, the buttons still change the icon regarding to state, but the color is gone. this is slightly inconvenient

**Comment by silamon** [comment]
This bug is introduced in #19776. 
As far as I understand, this is just for the entities card footer and header row?

Minimal reproduction with a input_boolean helper: 

```
views:
  - title: Home
    cards:
      - type: entities
        entities:
          - entity: input_boolean.test
        footer:
          type: buttons
          entities:
            - entity: input_boolean.test
```

**Comment by webwude** [comment]
> This bug is introduced in #19776. As far as I understand, this is just for the entities card footer and header row?
> 
> Minimal reproduction with a input_boolean helper:
> 
> ```
> views:
>   - title: Home
>     cards:
>       - type: entities
>         entities:
>           - entity: input_boolean.test
>         footer:
>           type: buttons
>           entities:
>             - entity: input_boolean.test
> ```

I have this issue in a normal entity card as well.

**Comment by Pipo31416** [comment]
Same for me with **buttons** in entities card since 2024.3 (that was ok with 2023.2.5):

![image](https://github.com/home-assistant/frontend/assets/158268990/3bb765c3-d1e4-4f9b-8b0e-acf46a6f6bab)

```
type: entities
entities:
  - type: buttons
    entities:
      - entity: binary_sensor.moi
      - entity: input_boolean.appliques
      - entity: light.radiateur
      - entity: input_boolean.alpatec_ion
      - entity: input_boolean.alpatec
      - entity: switch.rasoir_socket_1
      - entity: input_button.prise
        tap_action:
          action: navigate
          navigation_path: prises-ma-chambre
        hold_action:
          action: none
show_header_toggle: false
state_color: true
``` 

If I replace the above with a card of several **button** (not "buttons") that works:

![image](https://github.com/home-assistant/frontend/assets/158268990/da5ae764-6ed2-4c44-ac0f-260239d72007)
```
type: horizontal-stack
cards:
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: none
    entity: binary_sensor.moi
    icon_height: 30px
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: input_boolean.appliques
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: light.radiateur
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: input_boolean.alpatec_ion
    hold_action:
      action: call-service
      service: automation.trigger
      target:
        entity_id: automation.alpatec_ion
      data:
        skip_condition: true
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: binary_sensor.alpatec
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.rasoir_socket_1
  - show_name: false
    show_icon: false
    type: button
    tap_action:
      action: none
    icon: hass:radiobox-blank
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: navigate
      navigation_path: /dashboard-test/prises-ma-chambre
    entity: input_button.prise
    hold_action:
      action: none
```
