### ISSUE TITLE
History Graph Card doesn't honour entity Name option in pop out window

### ISSUE THREAD

**Issue by bleakcomb** [home-assistant/frontend#20047]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have an instance of the History Graph Card on a dashboard. It has 4 temperature sensor entities configured. In YAML I have specified optional, shorter names for each of the entities. The first view of the card on the dashboard honours these names. The pop out view with more data on it, does not honour the specified names for the entities, probably reverting to displaying the entity friendly name.

![image](https://github.com/home-assistant/frontend/assets/82914440/c94409e9-949a-41d0-b79e-03db13345486)

![image](https://github.com/home-assistant/frontend/assets/82914440/a57ec790-571e-41e8-afdc-3829be995ae2)

### Describe the behavior you expected

I would imagine that the pop out should also use the optional name variables, if specified.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.3.0

### In which browser are you experiencing the issue with?

Firefox 123.0.1

### Which operating system are you using to run this browser?

Win 10 Pro 19045.4046

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.study_temp_temperature
    name: Study
  - entity: sensor.kitchen_temperature
    name: Kitchen
  - entity: sensor.bathroom_temperature
    name: Bath
  - entity: sensor.bedroom_temperature
    name: Bed
title: Room Temp History
show_names: true
```
