### ISSUE TITLE
Visibility

### ISSUE THREAD

**Issue by freddiemare** [home-assistant/frontend#20043]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The issue is you can change a user's visibility when the Sections (experimental) view type is selected.

### Describe the behavior you expected

When you edit a view that is created under Sections (experimental) view type and you want to change to option to be visible for a specific user the the switch refuses to set the visibility option but when you edit it in yaml it works perfectly.

### Steps to reproduce the issue

1. Edit a view configured for Sections (experimental) 
2. Select the Visibility Tab
3. try to change the visibility for any user, you will note that you can't change the visibility. But you can edit the visibility in yaml.
...
visibility

### What version of Home Assistant Core has the issue?

2024.3.0

### In which browser are you experiencing the issue with?

Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 UpToDate

### Problem-relevant frontend configuration

```yaml
title: 3D Printer
path: 3d-printer
icon: mdi:printer-3d
type: sections
visible:
  - user: 1b511d7194e64bc091bbd8d4c4fd5752
  - user: aefa2a0fcd2545b28e4911819729d6af
  - user: 1e579eacdebb48f7a239f14ea8e017f2
```
