### ISSUE TITLE
built-in Light card does not send RGBW values over MQTT correctly

### ISSUE THREAD

**Issue by catdotgif** [home-assistant/frontend#20109]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Light card does not send white value correctly in RGBW mode.  Selecting a color mixed with white on the color wheel sends "white" as a mixed RGB value and does not affect the white channel at all.

### Describe the behavior you expected

When using the built-in Light card to control an RGBW light over MQTT:
When I select colors via the Hue/Saturation color disc I would expect the more saturated colors to the outside of the disc to have less white channel mixed in, with more white channel towards the center of the disk, like this:
![Screenshot 2024-03-13 103016](https://github.com/home-assistant/frontend/assets/38963449/325ec8b7-1e53-405e-b194-f8a0cd010cf0)
So pure white would be represented by `"color":{"r":0,"g":0,"b":0,"w":255}`  rather than `"color":{"r":255,"g":255,"b":255,"w":0}`

### Steps to reproduce the issue

1.  Select any color on the Light card color wheel that should have white mixed in
2.  Note in MQTT explorer or similar that Home Assistant does not change the white channel, whatever it is set to.  Instead, "white" is sent as an R+G+B value
3.
...

### What version of Home Assistant Core has the issue?

core: 2024.3.1 / frontend: 20240307.0

### In which browser are you experiencing the issue with?

Version 122.0.6261.112 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
#RGBW light configuration in configuration.yaml:
mqtt:
  - light:
      name: wally
      unique_id: wally_ID
      schema: json
      state_topic: "home/wally"
      command_topic: "home/wally/set"
      brightness: true
      color_mode: true
      supported_color_modes: ["rgbw"]
      optimistic: false
      qos: 0

#card yaml configuration:
```
