### ISSUE TITLE
Markdown card: CSS color variables are misinterpreted

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#20146]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Consider these cards:
```
type: vertical-stack
cards:
  - type: entity
    entity: sun.sun
    card_mod:
      style: |
        ha-card {background: var(--red-color)}

  - type: markdown
    content: <font color=red>xxxx</font>

  - type: markdown
    content: <font color=var(--red-color)>xxxx</font>
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/d8cc1861-9485-423a-9d9d-1abb8f7da785)

![изображение](https://github.com/home-assistant/frontend/assets/71872483/353ed5c9-4f3e-4c06-8a62-675aeff88cee)

Note that CSS variable `--red-color` is misinterpreted as "greenish".

### Describe the behavior you expected

CSS color variables are properly interpreted.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.4.1

### In which browser are you experiencing the issue with?

Chrome 122.0.6261.129

### Which operating system are you using to run this browser?

Win10x64
