### ISSUE TITLE
Footer button in vertical stack don't show state

### ISSUE THREAD

**Issue by vguttmann** [home-assistant/frontend#20147]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using buttons in the footer of a horizontal stack, the buttons don't indicate the state of the resource they are switching any more.
![Screenshot from 2024-03-21 10-56-16](https://github.com/home-assistant/frontend/assets/61903989/c11cddf3-bdd5-4281-afc1-7859424c9c69)

### Describe the behavior you expected

Buttons showing the state of the resource they are switching

### Steps to reproduce the issue

1. Create vertical stack with footer buttons
2. Observe footer buttons not showing state

### What version of Home Assistant Core has the issue?

2024.3.1

### In which browser are you experiencing the issue with?

Firefox 123.01/App 2024.1.5-full

### Which operating system are you using to run this browser?

Ubuntu 20.04/Android 14

### State of relevant entities

```txt
Entity: switch.fritz_box_7530_wi_fi_fritz_box_gastzugang
State: off
Attributes: 
  icon: mdi:wifi
  friendly_name: FRITZ!Box 7530 Wi-Fi FRITZ!Box Gastzugang
  bssid: DE:15:C8:CF:24:A9
  mac_address_control: false

Entity: switch.fritz_box_7530_wi_fi_wlan_app_149_2_4ghz
State: on
Attributes:
  icon: mdi:wifi
  friendly_name: FRITZ!Box 7530 Wi-Fi WLAN_APP 149 (2.4Ghz)
  standard: n
  bssid: DC:15:C8:CF:24:A9
  mac_address_control: false

Entity: switch.fritz_box_7530_wi_fi_wlan_app_149_5ghz
State: on
Attributes:
  icon: mdi:wifi
  friendly_name: FRITZ!Box 7530 Wi-Fi WLAN_APP 149 (5Ghz)
  standard: ac
  bssid: DC:15:C8:CF:24:AA
  mac_address_control: false
```

### Problem-relevant frontend configuration

```yaml
- type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: sensor.fritz_box_7530_upload_speed
              - entity: sensor.fritz_box_7530_download_speed
            footer:
              type: buttons
              entities:
                - entity: switch.fritz_box_7530_wi_fi_wlan_app_149_2_4ghz
                  name: 2,4 GHz
                  action: toggle
                - entity: switch.fritz_box_7530_wi_fi_wlan_app_149_5ghz
                  name: 5 GHz
                  action: toggle
                - entity: switch.fritz_box_7530_wi_fi_fritz_box_gastzugang
                  name: Gastzugang
                  action: toggle
```
