### ISSUE TITLE
IOS App: App locks up if device on last viewed page deleted.

### ISSUE THREAD

**Issue by RobSmyth** [home-assistant/frontend#20144]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If a device is deleted and the IOS app's last viewed page is a page that is now showing unknown device errors, the app cannot be used to view any pages other than the setup pages. When the app is started it shows a message that service not found (from my memory) with no content or navigation. Rebooting phone has no impact. Fixed when device is restored.

### Describe the behavior you expected

The IOS app should display unknown device errors on the Lovelace page the same as I see on my PC. Navigation should be available as normal.

### Steps to reproduce the issue

1. Using the IOS app - view a lovelace page that shows entities from an MQTT device.
2. Close the app.
3. On a PC delete the device (mine was an MQTT device using Zigbee2MQTT, deleted in Z2M with forced HA delete option)
4. Open the IOS app - blank screen with error message (BAD)
...

### What version of Home Assistant Core has the issue?

2024.3.0

### In which browser are you experiencing the issue with?

None - IOS app

### Which operating system are you using to run this browser?

IOS app

### State of relevant entities

```txt
Home Assistant Companion 2024.2 (2024.561)
```

### Problem-relevant frontend configuration

```yaml
The page impacted showed irrigation solenoid states. It was the irrigation relay board device that was deleted.

Lovelace:

title: Watering
views:

  - theme: Backend-selected
    title: Watering
    path: default_view
    icon: mdi:home
    badges: !include /config/lovelace/badges.yaml
    cards:
      - type: vertical-stack
        square: false
        columns: 1
        cards:
          - !include /config/lovelace/cards/garden-watering-card.yaml
          - type: history-graph
            hours_to_show: 12
            entities:
              - entity: switch.irrigation_zone_1_valve
                name: Beds
              - entity: switch.irrigation_zone_2_valve
                name: Pots
              - entity: switch.irrigation_master_valve
                name: Master

/config/lovelace/cards/garden-watering-card.yaml:

type: horizontal-stack
title: Watering
path: watering
cards:
    - type: button
      entity: input_boolean.water_pots
      name: Water Pots
      tap_action:
        action: toggle

    - type: button
      entity: input_boolean.water_garden_beds
      name: Water Beds
      tap_action:
        action: toggle

    - type: button
      name: Master
      show_name: true
      show_icon: true
      entity: switch.irrigation_master_valve
      tap_action:
        action: toggle

    - type: button
      name: Garden
      show_name: true
      show_icon: true
      entity: switch.irrigation_zone_1_valve
      tap_action:
        action: toggle

    - type: button
      name: Pots
      show_name: true
      show_icon: true
      entity: switch.irrigation_zone_2_valve
      tap_action:
        action: toggle
```

### Javascript errors shown in your browser console/inspector

```txt
I do not know how to obtain companion app logs.
```
