### ISSUE TITLE
Some entity names get device added making them too long

### ISSUE THREAD

**Issue by mvdwetering** [home-assistant/frontend#20164]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am trying to build a dashboard for my server with the new sections. When adding some cards to it, some of the entities get the device name (I think) added in front making them too long. Now most of my cards show "MICHEL-SERVER" (which is the name of the machine) which makes it a bit of a guessing game of what is what. When clicking a card with a long name it shows "MICHEL-SERVER <entityname>" like "MICHEL-SERVER Boot time"

Strangely enough this happens for most, but not all entities. The ones for individual CPU load are fine. Also the names of all entities show correct on the device page. Since it is correct in some place, but not the other I assume it is frontend related.
All entities are from the [System Bridge integration](https://www.home-assistant.io/integrations/system_bridge/).

My WIP dashboard. Note that almost all cards show "MICHEL-SERVER" and not the entityname.
![image](https://github.com/home-assistant/frontend/assets/732514/6c7d462b-8209-4937-beda-e6705d31897b)

Names are shown correctly on device page
![image](https://github.com/home-assistant/frontend/assets/732514/74e5eba4-71be-46dd-838a-058837118d0a)

### Describe the behavior you expected

Names like shown on the device page

### Steps to reproduce the issue

1. Create a section
2. Add cards
3. Look at names

### What version of Home Assistant Core has the issue?

core-2024.3.2

### In which browser are you experiencing the issue with?

Google Chrome 122.0.6261.112

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
I added one with correct name and one with long name. I can grab more, but I am not sure if this is the format that is needed.

entity: sensor.load_cpu_3
state: 49.2
state_class: measurement
unit_of_measurement: %
icon: mdi:percent
friendly_name: Load CPU 3

entity: sensor.michel_server_load
state: 28.9
state_class: measurement
unit_of_measurement: %
icon: mdi:percent
friendly_name: MICHEL-SERVER Load
```

### Problem-relevant frontend configuration

```yaml
- title: Server
    path: server
    icon: mdi:server
    type: sections
    sections:
      - type: grid
        cards:
          - type: tile
            entity: sensor.michel_server_cpu_speed
          - type: tile
            entity: sensor.michel_server_load
          - type: tile
            entity: sensor.load_cpu_0
          - type: tile
            entity: sensor.load_cpu_1
          - type: tile
            entity: sensor.load_cpu_2
          - type: tile
            entity: sensor.load_cpu_3
        title: CPU
      - type: grid
        cards:
          - type: tile
            entity: sensor.michel_server_boot_time
          - type: tile
            entity: sensor.michel_server_version
          - type: tile
            entity: sensor.michel_server_operating_system
          - type: tile
            entity: sensor.michel_server_latest_version
          - type: tile
            entity: sensor.michel_server_memory_used
          - type: tile
            entity: sensor.michel_server_memory_free
        title: Misc.
```

### Javascript errors shown in your browser console/inspector

```txt
No errors
```
