### ISSUE TITLE
Tile Card: Option to switch between button input or slider is not available for climate entities

### ISSUE THREAD

**Issue by aschieweck** [home-assistant/frontend#20175]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

While configuring a tile card for numeric inputs, e.g. a number helper, the user can change the style of the input. It can either be +/- buttons or a slider.
However, when configuring a tile card for other entities, which also have numeric values, this style choice is missing. E.g. selecting the target temperature as a feature for climate entities is always +/- buttons input. Or the target humidity of a humidifier is always a slider.
Those fixed input styles lead to inconsistent looking dashboards.

### Describe the behavior you expected

I would like to have the option to choose between +/- buttons or slider for any numeric value feature.

### Steps to reproduce the issue

1. Add a climate entity to your Home Assistant instance.
2. Go to a dashboard and enter edit mode.
3. Add a new Tile.
4. Select your climate entity as entity for the tile.
5. Under 'Features' select 'Target temperature'
6. Note how you can only remove this feature, not change its appearance.

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Firefox 124.0 & Companion App

### Which operating system are you using to run this browser?

ArchLinux (rolling) & Android 13

### Problem-relevant frontend configuration

```yaml
type: tile
entity: input_number.my_number
features:
  - type: numeric-input
    style: slider                   # This changes the input style

type: tile
entity: climate.my_climate_entity
features:
  - type: target-temperature
    style: slider                   # This does nothing
```
