### ISSUE TITLE
Bad "Horizontal/Vertical stack cards" after 2024.3.0 update

### ISSUE THREAD

**Issue by pickonedev** [home-assistant/frontend#20192]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On some devices/computers, everything works well, but on my older huawei tablets with android 10, the vertical and horizontal stack are doing something strange, are cutting the padding around elements, or something similar.

This is how the page should look and it is looking on some newer tablets (Android 12)
![316887081-51d8bbf1-3513-4800-8832-4ba41b39c14b](https://github.com/home-assistant/frontend/assets/34201387/efc2babd-72ac-4800-b760-c1774061dad1)

And this is how the vertical and even horizontal stack, it is acting on older Android 10 tablets
![316887124-56686225-5dec-43f8-a19e-c6b56bd3470d](https://github.com/home-assistant/frontend/assets/34201387/25cfe89f-bc13-4f75-b890-c9306126c6c9)

I waited new updates but nothing repaired the problem, I deleted browser cache and all, still nothing.
I am using Fully Kiosk Browser on my all devices.

Any solution?

### Describe the behavior you expected

It should look exactly like in the first image, on all the devices

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.3.x

### What was the last working version of Home Assistant Core?

core-2024.2.5

### In which browser are you experiencing the issue with?

Fully Kiosk Browser 1.55

### Which operating system are you using to run this browser?

Android 10

**Comment by ildar170975** [comment]
What kind of cards are you using? Are they custom cards?
Probably you should post a code for the view.

**Comment by pickonedev** [comment]
Does not matter what cards I use, original or custom...
It is because of the stack cards...

**Comment by ildar170975** [comment]
Have you tried purging a frontend cache on devices?

**Comment by pickonedev** [comment]
Yes, I done everything, I have even restarted from factory, the tables

**Comment by karwosts** [comment]
Please use safe mode for your screenshots to reproduce. Your frontend looks heavily themed/custom and we don't triage those issues.

**Comment by karwosts** [comment]
That is not a safe mode screenshot. It doesn't matter that you don't use a custom card, the mere existence of any custom card in resources can break an infinite number of things.

**Comment by pickonedev** [comment]
Alright.

Look, this screenshot it is from computer's browser, cards have a gap/padding between, which is ok, this is how it should look...
![WhatsApp Image 2024-03-26 at 19 11 48_d79127b5](https://github.com/home-assistant/frontend/assets/34201387/5f2ec23e-8bb3-42a9-ad7d-1776432e22ed)


And this is from the huawei tablets with android 10
![WhatsApp Image 2024-03-26 at 19 11 48_82ba826d](https://github.com/home-assistant/frontend/assets/34201387/100a1f66-417a-434e-bff3-cbcee4db2d07)


This is the code

```
type: vertical-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.mpower_gaming_headsets_charger
  - type: entity
    entity: >-
      sensor.windows_asus_rog_strix_z790_e_gaming_wifi_ii_nuvoton_nct6798d_voltages_vcore
  - type: light
    entity: light.xiaomi_gateway_light
  - type: markdown
    content: >-
      The **Markdown** card allows you to write any text. You can style it
      **bold**, *italicized*, ~strikethrough~ etc. You can do images, links, and
      more.


      For more information see the [Markdown
      Cheatsheet](https://commonmark.org/help).

```
