### ISSUE TITLE
History graph tooltip ignores standard precision setting

### ISSUE THREAD

**Issue by ste-fle** [home-assistant/frontend#20301]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm using a water meter sensor which reports its current value in m^3 to match the water meter. Therefore 3 decimals are necessary to display the value down to a liter - this seems to be incorporated into the standard precision setting for m^3 (3 decimals).
Despite this being the correct/necessary precision, 
<img width="463" alt="Bildschirmfoto 2024-03-31 um 23 41 29" src="https://github.com/home-assistant/frontend/assets/78681069/a3251ce7-901c-46a6-a488-8156ce77ae84">
the history graph only shows a maximum of 2 decimals within the tooltip with rounding up/down:
<img width="472" alt="Bildschirmfoto 2024-04-01 um 00 08 06" src="https://github.com/home-assistant/frontend/assets/78681069/4b9c5429-b134-4b1e-b1ad-ac862d9211dd">

If I manually change the precision setting to a fixed value of 3, 
<img width="463" alt="Bildschirmfoto 2024-03-31 um 23 47 18" src="https://github.com/home-assistant/frontend/assets/78681069/2c410c96-8117-43a2-bd1f-d2100f27c1c0">

it then works correctly: 
<img width="472" alt="Bildschirmfoto 2024-03-31 um 23 47 13" src="https://github.com/home-assistant/frontend/assets/78681069/027d210b-3b16-44d8-ae91-50f750aefb3a">

### Describe the behavior you expected

Display data in tooltip according to given (standard) precision. The fixes from https://github.com/home-assistant/frontend/pull/18334 (if applicable) don't seem to work.

### Steps to reproduce the issue

1. Show graph of m^3 value with standard precision (3 decimals), only two decimals are shown in tooltip (wrong)
3. Switch to manual precision of 3, 3 decimals are shown in tooltip (correct)

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Safari 17.4.1 (19618.1.15.11.14)

### Which operating system are you using to run this browser?

macOS 14.4.1

### State of relevant entities

```txt
sensor.wasserzaehler_value 
282.806	
state_class: total_increasing
unit_of_measurement: m³
device_class: water
icon: mdi:gauge
friendly_name: wasserzaehler Value
```

**Comment by ildar170975** [comment]
Confirm.
2024.4.3
```
input_number:
  test_accuracy_in_tooltip:
    min: 0
    max: 1000
    step: 0.001
    mode: box

template:
  - sensor:
      - name: testing_accuracy_in_tooltip
        unit_of_measurement: uom
        state: >-
          {{ states('input_number.test_accuracy_in_tooltip') }}
```
![image](https://github.com/home-assistant/frontend/assets/71872483/7f7d7ba8-dc30-435e-af65-e713bd097d8e)
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_number.test_accuracy_in_tooltip
      - entity: sensor.testing_accuracy_in_tooltip
  - type: history-graph
    entities:
      - entity: sensor.testing_accuracy_in_tooltip
```
