### ISSUE TITLE
Update entity service call does not accept any target other than an entity

### ISSUE THREAD

**Issue by Chaoscontrol** [home-assistant/frontend#20443]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Title. Other service calls accept any kind of target, like areas, devices, or the new labels. But this specific service call returns an error
Failed to call service homeassistant.update_entity. extra keys not allowed @ data['label_id']. Got None
when trying to use other targets, even when they include several entities, and they exist.

I do this via UI, so label_id is correct etc.

### Describe the behavior you expected

UI shouldn't show the targets that are not accepted. 

### Steps to reproduce the issue

1. Go to Dev Tools > Services
2. Find the update_entity service call.
3. Add a label, device, or area as the target.
4. Try to run it.

### What version of Home Assistant Core has the issue?

core-2024.4.1

### In which browser are you experiencing the issue with?

Google Chrome 123.0.6312.106

### Which operating system are you using to run this browser?

Windows 11

### Additional information

[Core issue related](https://github.com/home-assistant/core/issues/115008)
[Feature request related](https://community.home-assistant.io/t/make-update-entity-service-call-to-accept-labels-devices-and-areas-just-like-other-service-calls/713705/4)

**Comment by joostlek** [comment]
For the context, this is the service definition
```yaml
update_entity:
  target:
    entity: {}
```

**Comment by karwosts** [comment]
This should be a core issue I think, it shouldn't use the target selector if it doesn't support target selection, but just use a regular entity/entities selector.

**Comment by joostlek** [comment]
```py
SCHEMA_UPDATE_ENTITY = vol.Schema({ATTR_ENTITY_ID: cv.entity_ids})
```
It doesn't use any special kind of selector afaict

**Comment by joostlek** [comment]
Oooh, bnever mind, I see the `target:` in the services.yaml I sent

**Comment by karwosts** [comment]
I think a lot of core services have this wrong TBH ☹️

**Comment by ildar170975** [comment]
I wonder if this related? https://github.com/home-assistant/frontend/issues/13827

**Comment by joostlek** [comment]
Hmm so one difference I see is that other services have a selector in the data field instead of the target:

Google Assistant SDK as example:
```yaml
send_text_command:
  fields:
    command:
      example: turn off kitchen TV
      selector:
        text:
    media_player:
      example: media_player.living_room_speaker
      selector:
        entity:
          domain: media_player
```

Which shows as 
<img width="1242" alt="image" src="https://github.com/home-assistant/frontend/assets/7083755/cba5ab94-89f0-48b0-a651-1085856afea6">

I think there's a bit of inconsistency between how different integration handle this. I would expect everyone to use the same way to scope the integration to certain entities/devices/whatever

**Comment by Chaoscontrol** [comment]
I'd say that's a good approach for single choice elements. But for multiple selection, I'm not sure I've seen another one other than the "target" (which honestly is good, if it worked).

**Comment by karwosts** [comment]
entity selector can set `multiple: true` to select multiple entities, not just a single one.

**Comment by joostlek** [comment]
In the [documentation of core](https://developers.home-assistant.io/docs/dev_101_services) there is something about services:

```yaml
set_speed:
  # If the service accepts entity IDs, target allows the user to specify entities by
  # entity, device, or area. If `target` is specified, `entity_id` should not be
  # defined in the `fields` map. By default it shows only targets matching entities
  # from the same domain as the service, but if further customization is required,
  # target supports the entity, device, and area selectors
  # (https://www.home-assistant.io/docs/blueprint/selectors/). Entity selector
  # parameters will automatically be applied to device and area, and device selector
  # parameters will automatically be applied to area. 
  target:
    entity:
      domain: fan
```

But I honestly have no clue what that last part means
