### ISSUE TITLE
Naming Section a large length name cause the add card window to go off screen

### ISSUE THREAD

**Issue by AwesomeAlec** [home-assistant/frontend#20449]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When making a section in the section dashboard, the section can be named at the top of the section.

The section name appears to not have a character limit allowing for a large name.

After naming a section with a long length name, when you press the add card button the add card window scales with the length of the name longer than my browser window with a standard 16:9 aspect ratio.

This causes the window to go off screen.

### Describe the behavior you expected

When opening the window, the name of the card should be truncated with ellipses or the window should be capped or scale with your browser.

The close window X button should remain visible on the screen.

### Steps to reproduce the issue

1.Open or create a sections dashboard
2.Name new section with a long length name
3.Open the add card window of the section with the long name
...

### What version of Home Assistant Core has the issue?

2024.4.1

### In which browser are you experiencing the issue with?

Firefox 124.0.2

### Which operating system are you using to run this browser?

Windows 10 Pro 22H2

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
title: OverviewNew
    path: overviewnew
    icon: mdi:view-grid
    theme: Mushroom Shadow
    type: sections
    max_columns: 3
    sections:
      - type: grid
        cards: []
        title: >-
          LongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongStringLongString
      - type: grid
        cards: []
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

16:9 aspect ratio 100% zoom when opening the add card window
![Capture1](https://github.com/home-assistant/frontend/assets/14119889/58fb0338-a4b4-4b14-a997-a8742a081e84)
30% zoom window is still off the screen
![Capture2](https://github.com/home-assistant/frontend/assets/14119889/be9933c1-d0b1-4df0-a830-23dfbb74b093)
