### ISSUE TITLE
Calling script after saving fails with Invalid data for call_service but works if one selects Information before running

### ISSUE THREAD

**Issue by arpitgupta** [home-assistant/frontend#20466]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Running into a weird issue where running the script fails unless a specific set of steps are done.

Here is the script in question
```
alias: thermostat
mode: single
icon: mdi:air-conditioner
fields:
  type:
    selector:
      select:
        options:
          - home
          - away
    name: type
    default: home
sequence:
  - service: climate.set_temperature
    data_template:
      hvac_mode: heat_cool
      target_temp_low: >
        {% set t = { 'home': 69, 'away': 68 } %} {{ t[type] if s in t.keys()
        else 68 }}
      target_temp_high: >
        {% set t = {'winter': { 'home': 76, 'away': 78 }, 'autumn': { 'home':
        76, 'away': 78 }, 'spring': { 'home': 75, 'away': 77 }, 'summer': {
        'home': 78, 'away': 79 }} %} {% set s = states('sensor.season') %} {{
        t[s][type] if s in t.keys() else 78 }}
    target:
      device_id: 67eeadf97249bedd287d7438965b0c9a
```

### Describe the behavior you expected

Script should run without an error when selecting run script

### Steps to reproduce the issue

1. Make any valid change to the script
2. Select "Run Script" option for the script.
3. Note one is not prompted to select the input field "type" and the script fails with an error. Error: `2024-04-07 16:35:17.147 ERROR (MainThread) [homeassistant.components.script.thermostat] thermostat: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['target_temp_high']`
4. Now select "Information" option from the 3 dots and close it.
5. Now select "Run Script" option. Note one is now prompted to select the value of "type" field. Select any value and the script runs successfully.

### What version of Home Assistant Core has the issue?

core-2024.4.1
