### ISSUE TITLE
Dashboard with Sections - empty space when conditional cards are being used

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#20479]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm creating a new dashboard for my plants - due to the huge amount of plant sensors, I want to hide all plant-cards when there's no problem.
When all measurements are within the expected range, the card should be hidden.

This is working - but the dashboard shows an empty area where the conditional cards are placed...

![grafik](https://github.com/home-assistant/frontend/assets/26391061/2532a480-05c2-4e1e-91f7-969e19d4d238)

![grafik](https://github.com/home-assistant/frontend/assets/26391061/a7021e15-20a1-482c-9047-7baf63d34647)

### Describe the behavior you expected

like for the other dashboard types, the place where a conditional card is placed should not be "blocked" by an empty area

### Steps to reproduce the issue

1. Create a section dashboard
2. Create a conditional card with conditions not met
3. Save the dashboard & leave the editor
...

### What version of Home Assistant Core has the issue?

core 2024.4.1

### Problem-relevant frontend configuration

```yaml
title: pflanzen
path: pflanzen
icon: mdi:flower
cards: []
type: sections
sections:
  - type: grid
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - condition: state
                entity: plant.benjamin
                state: problem
            card:
              type: vertical-stack
              cards:
                - type: custom:flower-card
                  entity: plant.benjamin
                  battery_sensor: sensor.benjamin_battery
                  show_bars:
                    - moisture
                    - conductivity
                    - temperature
                    - illuminance
                    - dli
                    - humidity
                  display_type: full
                - type: horizontal-stack
                  cards:
                    - type: tile
                      entity: sensor.benjamin_signal_strength
                      name: Signalstärke
                    - type: tile
                      entity: button.benjamin_batterie_ersetzt
                      name: Batterie ersetzt
                      hide_state: true
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - condition: state
                entity: plant.ficus_benjamina_bonsai
                state: problem
            card:
              type: vertical-stack
              cards:
                - type: custom:flower-card
                  entity: plant.ficus_benjamina_bonsai
                  battery_sensor: sensor.ficus_benjamina_1_battery
                  show_bars:
                    - moisture
                    - conductivity
                    - temperature
                    - illuminance
                    - dli
                    - humidity
                  display_type: full
                - type: horizontal-stack
                  cards:
                    - type: tile
                      entity: sensor.ficus_benjamina_1_signal_strength
                      name: Signalstärke
                    - type: tile
                      entity: button.ficus_benjamina_1_batterie_ersetzt
                      hide_state: true
                      name: Batterie ersetzt
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - condition: state
                entity: plant.ficus_microcarpa_bonsai
                state: problem
            card:
              type: vertical-stack
              cards:
                - type: custom:flower-card
                  entity: plant.ficus_microcarpa_bonsai
                  battery_sensor: sensor.ficus_microarpa_bonsai_battery
                  show_bars:
                    - moisture
                    - conductivity
                    - temperature
                    - illuminance
                    - dli
                    - humidity
                  display_type: full
                - type: horizontal-stack
                  cards:
                    - type: tile
                      entity: sensor.ficus_microarpa_bonsai_signal_strength
                      name: Signalstärke
                    - type: tile
                      entity: button.ficus_microarpa_bonsai_batterie_ersetzt
                      name: Batterie ersetzt
                      hide_state: true
      - type: vertical-stack
        cards:
          - type: custom:flower-card
            entity: plant.gummibaum
            battery_sensor: sensor.ficus_elastica_battery
            show_bars:
              - moisture
              - conductivity
              - temperature
              - illuminance
              - dli
              - humidity
            display_type: full
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.ficus_elastica_signal_strength
                name: Signalstärke
              - type: tile
                entity: button.ficus_elastica_battery_replaced
                name: Batterie ersetzt
                hide_state: true
```
