### ISSUE TITLE
Incomplete/Superfluous Description on 'Z-Wave: Refresh values' Service

### ISSUE THREAD

**Issue by The00Dustin** [home-assistant/frontend#20496]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When including the 'Z-Wave: Refresh values' service in an automation or script with z-wave devices selected via entity, the description of the action is incomplete as compared to other service calls.  The following screenshot exemplifies this nicely:
![Screenshot 2024-04-11 at 10 48 33](https://github.com/home-assistant/frontend/assets/91274634/2a9027bf-067b-4d39-8140-0011505c3345)
Here you can see that the entity name is included in the action description for turning on the lights, but not for refreshing the Z-Wave values even though the preposition "on" is included as if it should.

### Describe the behavior you expected

I expect the selected entity/entities to be reflected after the word "on" or for the word "on" to not be used here at all if selected entities won't be shown.

### Steps to reproduce the issue

1. Create a script or automation
2. Add a service call to 'Z-Wave: Refresh values'
3. Assign one or more entities
4. Witness the panel does not indicate the selected entities

### What version of Home Assistant Core has the issue?

2024.4.2

### In which browser are you experiencing the issue with?

Safari 17.4.1, iOS Home Assistant 2024.4

### Which operating system are you using to run this browser?

macOS Sonoma (14.4.1), iOS 17 (17.4.1)

### Problem-relevant frontend configuration

```yaml
alias: New Script
sequence:
  - service: zwave_js.refresh_value
    metadata: {}
    data:
      refresh_all_values: false
      entity_id:
        - light.basement_stairwell_lights
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.basement_stairwell_lights
```
