### ISSUE TITLE
Developer tools / Statistics "Fix Issue" for "This entity is no longer being recorded" doesn't provide option to fix the entity

### ISSUE THREAD

**Issue by bakerkj** [home-assistant/frontend#20506]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the Developer Tools -> Statistics screen the "Fix Issue" button for "This entity is no longer being recorded" doesn't actually provide an option to fix the issue
![statistics_fix_issue](https://github.com/home-assistant/frontend/assets/5491232/ba1254be-5452-41f6-91e3-7fc0bfe85400)

### Describe the behavior you expected

An option to "Delete" all of the statistics associated with the entity.

### Steps to reproduce the issue

1. Install Home Assistant
2. Add an entity that will be recorded in statistics
3. Exclude that entity from being recorded in the recorder
4. Restart Home Assistant
5. Open the developer tools -> statistics screen
6. Find the entity; note when you select "Fix Issue" the only option is "OK

### What version of Home Assistant Core has the issue?

2024.4.3

### In which browser are you experiencing the issue with?

Google Crhome 123.0.6312.105

### Which operating system are you using to run this browser?

Ubuntu 22.04

### Problem-relevant frontend configuration

```yaml
Here is an excerpt from the configuration I am using for the recorder:

recorder:
  db_url: !secret mysql_recorder_database
  exclude:
    entities:
      - sensor.pro_check_83ed_signal_strength
```
