### ISSUE TITLE
Visual mode no longer works as it used to when adding/editing entitities to cover service calls in automations/scripts

### ISSUE THREAD

**Issue by danielbrunt57** [home-assistant/frontend#20595]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using visual mode to edit automations/scripts, the cover service calls no longer present the same way as light/switch/lock/etc. service calls and there is now no way to pick target entities.
New entry:
![image](https://github.com/home-assistant/frontend/assets/49846893/7a1a6c1c-86f9-479b-bb99-65d7af84dedf)
Pre-existing entry:
![image](https://github.com/home-assistant/frontend/assets/49846893/8752819e-ea8c-4af1-8b1f-d0253447cf76)

### Describe the behavior you expected

![image](https://github.com/home-assistant/frontend/assets/49846893/30113da6-6048-43ec-8846-33639c8bef11)

### Steps to reproduce the issue

New action:
1.  
![image](https://github.com/home-assistant/frontend/assets/49846893/ebe8c1ef-1233-49f4-8e79-f15e864b813c)
2.
![image](https://github.com/home-assistant/frontend/assets/49846893/6ef87e0d-56f4-4ec6-ad40-f279414c4413)
3.
![image](https://github.com/home-assistant/frontend/assets/49846893/8d318f85-a488-4c76-9108-981a1ed0e4c2)
4.
![image](https://github.com/home-assistant/frontend/assets/49846893/101d25e7-5bc1-49e0-ad92-22ecfc731f89)

Existing action:
1.  ![image](https://github.com/home-assistant/frontend/assets/49846893/edeeeef4-7c54-42bd-b25a-a4761003073d)

### What version of Home Assistant Core has the issue?

2024.4.3

### What was the last working version of Home Assistant Core?

2024.3?

### In which browser are you experiencing the issue with?

Microsoft Edge for Business 123.0.2420.81 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 Pro

### Problem-relevant frontend configuration

```yaml
alias: Good Night
sequence:
  - parallel:
      - service: input_boolean.turn_on
        continue_on_error: true
        data: {}
        target:
          entity_id:
            - input_boolean.sleep_mode
            - input_boolean.daniel_sleeping
      - service: input_number.set_value
        continue_on_error: true
        data:
          value: 0
        target:
          entity_id: input_number.bathroom_delay_off
      - service: input_select.select_option
        continue_on_error: true
        data:
          option: Sleeping
        target:
          entity_id: input_select.sleep_status
      - service: light.turn_off
        continue_on_error: true
        data: {}
        target:
          area_id:
            - living_room
            - patio
      - service: media_player.turn_off
        continue_on_error: true
        target:
          entity_id:
            - media_player.bedroom_tv
            - media_player.living_room_tv
        data: {}
      - service: lock.lock
        target:
          entity_id: lock.patio_door_lock
        data: {}
      - sequence:
          - service: script.update_last_alexa_and_wait
            data: {}
            enabled: true
            continue_on_error: true
          - if:
              - condition: state
                entity_id: input_boolean.coffee_prepared
                state: "off"
            then:
              - service: script.activate_alexa_actionable_notification
                continue_on_error: true
                data:
                  text: Did you prepare your coffee?
                  event_id: actionable_notification_coffee_prepared
                  alexa_device: "{{ states('sensor.last_alexa') }}"
          - if:
              - condition: numeric_state
                entity_id: sensor.garbage
                below: 2
              - condition: state
                entity_id: input_boolean.garbage_is_out
                state: "off"
              - condition: or
                conditions:
                  - condition: and
                    conditions:
                      - condition: state
                        entity_id: sensor.garbage
                        state: "0"
                      - condition: time
                        before: "09:00:00"
                        after: "00:00:00"
                  - condition: and
                    conditions:
                      - condition: state
                        entity_id: sensor.garbage
                        state: "1"
                      - condition: time
                        after: "12:00:00"
                        before: "00:00:00"
            then:
              - service: script.activate_alexa_actionable_notification
                continue_on_error: true
                data:
                  text: Did you put the garbage out?
                  event_id: actionable_notification_garbage_pickup
                  alexa_device: "{{ states('sensor.last_alexa') }}"
          - if:
              - condition: numeric_state
                entity_id: sensor.recycling
                below: 2
              - condition: state
                entity_id: input_boolean.recycling_is_out
                state: "off"
              - condition: or
                conditions:
                  - condition: and
                    conditions:
                      - condition: state
                        entity_id: sensor.recycling
                        state: "0"
                      - condition: time
                        before: "09:00:00"
                        after: "00:00:00"
                  - condition: and
                    conditions:
                      - condition: state
                        entity_id: sensor.recycling
                        state: "1"
                      - condition: time
                        after: "12:00:00"
                        before: "00:00:00"
            then:
              - service: script.activate_alexa_actionable_notification
                continue_on_error: true
                data:
                  text: Did you put the recycling out?
                  event_id: actionable_notification_recycling_pickup
                  alexa_device: "{{ states('sensor.last_alexa') }}"
  - parallel:
      - if:
          - condition: not
            conditions:
              - condition: state
                entity_id: climate.living_room
                attribute: preset_mode
                state: eco
                alias: Preset of Furnace
            alias: If Preset of Furnace is NOT  'eco'
          - condition: numeric_state
            entity_id: climate.living_room
            attribute: temperature
            above: 17
            alias: Furnace temperature is above 17
        then:
          - service: climate.set_temperature
            continue_on_error: true
            data:
              temperature: 17
            target:
              entity_id: climate.living_room
          - service: script.notify_alexa_media
            continue_on_error: true
            data:
              message: Heat is now set to 17
      - if:
          - condition: state
            entity_id: lock.front_door_lock
            state: unlocked
        then:
          - service: lock.lock
            continue_on_error: true
            data: {}
            target:
              entity_id: lock.front_door_lock
          - service: script.notify_alexa_media
            continue_on_error: true
            data:
              message: The front door was unlocked but I locked it for you.
      - if:
          - condition: state
            entity_id: cover.garage_door
            state: open
        then:
          - if:
              - condition: state
                entity_id: sensor.season
                state: summer
            then:
              - service: script.notify_alexa_media
                continue_on_error: true
                data:
                  message: Hey. Did you know the garage door is open?
                  milliseconds: 0
            else:
              - service: cover.close_cover
                continue_on_error: true
                data:
                  entity_id: cover.garage_door
              - service: script.notify_alexa_media
                continue_on_error: true
                data:
                  message: I closed the garage door for you
                  milliseconds: 0
      - if:
          - condition: numeric_state
            entity_id: sensor.fordpass_elveh
            below: 100
          - condition: state
            entity_id: sensor.ev_charger
            state: "off"
        then:
          - service: script.notify_alexa_media
            continue_on_error: true
            data:
              message: >-
                Your Mach E battery range is only {{
                states("sensor.fordpass_elveh")|int(0) }} kilometers
      - if:
          - condition: state
            entity_id: cover.bedroom_blind
            state: open
        then:
          - service: cover.close_cover
            data:
              entity_id: cover.bedroom_blind
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - alias: "Media Player: Say Goodnight"
    service: media_player.play_media
    continue_on_error: true
    data:
      media_content_id: Alexa.GoodNight.Play
      media_content_type: sequence
    target:
      entity_id: "{{ states('sensor.last_alexa') }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: retry.actions
    data:
      sequence:
        - service: light.turn_off
          continue_on_error: true
          data: {}
          target:
            entity_id:
              - light.nightstand_lamps
              - light.headboard_indirect
      expected_state:
        - "off"
  - if:
      - condition: state
        entity_id: binary_sensor.bathroom_occupancy
        state: "on"
    then:
      - wait_for_trigger:
          - platform: state
            entity_id:
              - binary_sensor.bathroom_occupancy
            to: "off"
        timeout:
          hours: 0
          minutes: 1
          seconds: 30
          milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bathroom_light
mode: single
icon: hass:weather-night
```
```


### Javascript errors shown in your browser console/inspector

```txt
n/a
```

**Comment by karwosts** [comment]
I've tried 2024.4.2 and 2024.4.4 and it looks totally normal to me in both 🤷 

![image](https://github.com/home-assistant/frontend/assets/32912880/8c6abc1b-7d37-4b8d-8089-32c2cecf1cdc)

**Comment by danielbrunt57** [comment]
Well that was bizarre!  I cleared MS Edge cache again plus restarted PC just to be sure and now it's fine.  What's truly bizarre is it was only the cover services...

**Comment by danielbrunt57** [comment]
The problem has resumed.  It occurs in MS Edge, Google Chrome _and_ HA Companion App in Scripts, Automations _and_ DevTools.

Tested and not working:
cover.open, cover.close, cover.set_cover_position
light.turn_xx, light.toggle

Working:
camera.turn_xx
input_boolean, input_button, input_datetime, input_number, input_select, input_text
fan.set_speed
lock.lock, lock.unlock
switch.turn_xx, switch.toggle

If you're not seeing an issue with the above in DevTools in Edge, Chrome & HA App then I'm truly puzzled as to what has broken on my system...

**Comment by danielbrunt57** [comment]
![image](https://github.com/home-assistant/frontend/assets/49846893/64dc9e77-d7a6-44a1-ad23-6e12a05f4268)
![image](https://github.com/home-assistant/frontend/assets/49846893/f641daec-aa63-4266-81c3-f43039247159)
![image](https://github.com/home-assistant/frontend/assets/49846893/66e1e643-2bf5-405b-9955-92fb4f4cddf3)
![image](https://github.com/home-assistant/frontend/assets/49846893/dd08779a-7fcb-4a8c-8e68-bdd18937c0bc)

**Comment by karwosts** [comment]
If you have any custom plugins installed, would be good to try the safe mode as well.

**Comment by danielbrunt57** [comment]
Just tried safe mode and cover and light are fine.  Hmmm...

**Comment by danielbrunt57** [comment]
Possibly one of these?
![image](https://github.com/home-assistant/frontend/assets/49846893/2995d868-fe58-4f38-9c17-ffc780a55463)

**Comment by karwosts** [comment]
I would guess it's probably something installed on the frontend, like a custom card or theme or something, but couldn't say for sure.

**Comment by danielbrunt57** [comment]
Thought about it for a bit and recalled I have cover and light yaml templated entitiies.
So I commented them out...
![image](https://github.com/home-assistant/frontend/assets/49846893/1e311a95-cab5-4838-be94-854e1866f6ea)
and now cover and light work in DevTools.

![image](https://github.com/home-assistant/frontend/assets/49846893/7c6ca15b-df10-40f8-9a31-a7f852ad80c0)
![image](https://github.com/home-assistant/frontend/assets/49846893/4a89fb4b-f163-4d0d-9d0f-5e6938ac2696)
`cover/yaml`
```
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage Door"
        unique_id: zwave-garage-door
        device_class: 'garage'
        value_template: >-
         {{ is_state('binary_sensor.garage_door','on') }}
        open_cover:
          service: switch.turn_on
          target:
            entity_id: switch.garage_door_opener
        close_cover:
          service: switch.turn_on
          target:
            entity_id: switch.garage_door_opener
        stop_cover:
          service: switch.turn_on
          target:
            entity_id: switch.garage_door_opener
        icon_template: >-
          {%- if states('binary_sensor.garage_door') == "on" -%}
             {%- if states('input_boolean.car_in_garage') == "on" -%}kuf:fts_garage
             {%- else -%}mdi:garage-open-variant
             {%- endif -%}
          {%- else -%}
             {%- if states('input_boolean.car_in_garage') == "on" -%}kuf:fts_garage_door_100
             {%- else -%}mdi:garage-variant
             {%- endif -%}
          {%- endif -%}
           
      living_room_blind_v2:
        friendly_name: Living Room
        unique_id: living-room-blind-template
        value_template: '{{ iif (1 < state_attr("cover.living_room_blind_hidden","current_position")|int(0) < 99 , "open", "closed") }}'
        tilt_template: '{{100 - (state_attr("cover.living_room_blind_hidden","current_position")|int(default=0)) }}'
        set_cover_tilt_position:
          service: cover.set_cover_position
          data_template:
            entity_id: cover.living_room_blind_hidden
            position: '{{100 - tilt}}'
        open_cover:
          service: cover.set_cover_position
          data_template:
            entity_id: cover.living_room_blind_hidden
            position: '{{100.0 - states("input_number.living_room_blind")|float(0)}}'
        close_cover:
          service: cover.set_cover_position
          data_template:
            entity_id: cover.living_room_blind_hidden
            position: 100
        icon_template: >-
          {{ iif(this.state =='open','phu:blind-tilt-open','phu:blind-tilt-closed') }}
```

`switch.yaml`
```
#      my_pc_monitor:
#        friendly_name: My PC Monitor
#        unique_id: my_pc_monitor
#        icon_template: >-
#          {% if is_state('sensor.my_pc_is_active', 'on') %}
#           mdi:monitor-star
#          {% else %}
#           mdi:monitor-off
#          {% endif %}
#        turn_on:
#          service: mqtt.publish
#          data:
#            topic: iotlink/brunt/windows-11/commands/displays/on
#        turn_off:
#          service: mqtt.publish
#          data:
#            topic: iotlink/brunt/windows-11/commands/displays/off
  - platform: wake_on_lan
    mac: "08-D2-3E-81-AF-15"
    name: "My PC"
    host: "192.168.1.100"
    
  - platform: wake_on_lan
    mac: 38-8C-50-B4-1F-30
    name: LG TV
    host: 192.168.1.90
```
