### ISSUE TITLE
Statistics graph may show weird accuracy for recently added sensor (probably if a state has not changed since creation)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#20678]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

(instead of a closed https://github.com/home-assistant/frontend/issues/18982)

Consider a card:
```
        type: statistics-graph
        chart_type: line
        period: hour
        entities:
          - sensor.some_sensor
        stat_types:
          - mean
          - min
          - max
        days_to_show: 180
```
Which may be shown with a weird accuracy as
![image](https://github.com/home-assistant/frontend/assets/71872483/a65b237b-87a7-4b6b-aebc-72ea2609a43d)

These sensors have not been changed for a long period - more than 180 days.

How to reproduce:
create a template sensor:
```
template:
  - sensor:
      - name: testing_lts_not_changing_value
        state: 95
        unit_of_measurement: "%"
        state_class: measurement
```
and then add this card:
```
chart_type: line
period: 5minute
type: statistics-graph
entities:
  - sensor.testing_lts_not_changing_value
stat_types:
  - mean
  - min
  - max
days_to_show: 180
```
![image](https://github.com/home-assistant/frontend/assets/71872483/2ead549d-64f1-4a1d-8d88-bf24b0a53111)
![image](https://github.com/home-assistant/frontend/assets/71872483/79062766-04cd-4268-93a0-12ab2347c04c)

Note that here I defined `period: 5minute` since did not want to wait for an hour.

### Describe the behavior you expected

Do not use a weird accuracy

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.4.3

### In which browser are you experiencing the issue with?

Chrome 124.0.6367.91 

### Which operating system are you using to run this browser?

Win10x64
