### ISSUE TITLE
Template time_since is not translated

### ISSUE THREAD

**Issue by stefankoehne** [home-assistant/frontend#20859]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am using a conditional card with a markdown card in it, that shows the last change of an entity with "time_since". 
The Problem is that it is not translating into my language (german) and is shown up in english.

![Screenshot_8](https://github.com/home-assistant/frontend/assets/69876166/e7c5dcd1-0648-491d-bede-9ba425c4f9fb)

I can't find any issues in localise, as it maybe is a hard coded thing?

### Describe the behavior you expected

Translating the time like it does in the entity-popup 
![Screenshot_9](https://github.com/home-assistant/frontend/assets/69876166/a920bfd4-1267-487e-9a14-4db67c09b572)

### Steps to reproduce the issue

1. Use another default-language in HA instead of english
2. Create a boolean switch helper (or use existing one)
3. Go to Developer tools > template and type in "{{ time_since(states.input_boolean.##ENTITY##.last_changed, 2) }}
4. Tadaa, no translating. Time of last change shows up in english.

### What version of Home Assistant Core has the issue?

2024.5.4

### In which browser are you experiencing the issue with?

Google Chrome 125.0.6422.76

### Which operating system are you using to run this browser?

Windows 10 22H2

### Problem-relevant frontend configuration

```yaml
- type: conditional
    conditions:
      - condition: state
        entity: input_boolean.dummy_switch
        state: 'on'
    card:
      type: markdown
      content: >-
        <ha-alert alert-type="info">Der Test läuft seit {{
        time_since(states.input_boolean.dummy_switch.last_changed, 2)
        }}</ha-alert>
```
