### ISSUE TITLE
hui-root doesn't update scrolled attribute after visibility change

### ISSUE THREAD

**Issue by alex3305** [home-assistant/frontend#20854]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I re-focus my window after tabbing out of it, the `hui-root` element sometimes doesn't update the `scrolled`-attribute anymore. Therefore I'm unable to detect (with CSS) if the app has been scrolled. 

### Describe the behavior you expected

That the `scrolled`-attribute always gets updated on scroll events.

### Steps to reproduce the issue

1. Use Home Assistant, scroll and see it has been scrolled
2. Tab out of the application, but leave it running
3. After a while and the app resumes, `scrolled` doesn't get updated anymore

### What version of Home Assistant Core has the issue?

core-2024.5.3

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Brave 1.66.113 Chromium: 125.0.6422.76, Android Home Assistant Companion app

### Which operating system are you using to run this browser?

Windows, Android 14

### Additional information

It seems that the relevant event listener is removed, but isn't added back again when the window regains focus.
https://github.com/home-assistant/frontend/blob/a500b582e348304509bc2d165807c6d66c974973/src/panels/lovelace/hui-root.ts#L502-L505

I suspect that adding a `connectedCallback` can fix this issue:

```typescript
 public connectedCallback(): void { 
   super.connectedCallback(); 
   window.addEventListener("scroll", this._handleWindowScroll); 
 } 
```
However I'm not 100% sure, because of my lack of experience with LitElement.

**Comment by alex3305** [comment]
I found a way to reliably reproduce this. I have created two dashboards:

## Main dashboard

```yaml
views:
  - title: Home
    cards:
      - type: tile
        entity: sensor.sun_next_dawn
        tap_action:
          action: navigate
          navigation_path: /dashboard-test/sub
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
title: Main
```

## Test dashboard

```yaml
views:
  - title: Home
  - title: Sub
    path: sub
    subview: true
    cards: []
title: Test
```

Navigating between those dashboards causes the `scrolled` attribute not being updated anymore. This is apparent because of the missing box shadow in the header even if the window is scrolled:

![image](https://github.com/home-assistant/frontend/assets/5155694/abdadb9e-efba-40c6-812a-5bda4e250526)

I have just submitted my PR, which adds the missing callback, and now the scrolled attribute gets updated correctly:

![image](https://github.com/home-assistant/frontend/assets/5155694/0fe36b6a-0f66-441e-b767-65b9adee30db)
