### ISSUE TITLE
Sections view: Size issue with gauge in horizontal stack + tile cards

### ISSUE THREAD

**Issue by mbo18** [home-assistant/frontend#20905]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding a gauge card inside an horizontal stack with 2 tile cards in a vertical stack there is an issue with sizing but only when the section's size is wide :
<img width="465" alt="Capture d’écran 2024-05-29 à 21 46 26" src="https://github.com/home-assistant/frontend/assets/12999535/fa2c9649-a682-47b9-ada8-ad4cd0c7d36d">

When on mobile or when the section size is small:
<img width="351" alt="Capture d’écran 2024-05-29 à 21 47 36" src="https://github.com/home-assistant/frontend/assets/12999535/f3a611b4-6a0b-43ad-bb18-74a9661aa6f3">

### Describe the behavior you expected

Size of card should not change

### Steps to reproduce the issue

1. Add a section
2. Add an horizontal stack with a gauge card and a vertical stack with 2 tile cards
3. Resize the browser window and tadaaa
...

### What version of Home Assistant Core has the issue?

core-2024.5.5

### In which browser are you experiencing the issue with?

Safari and Firefox latest version

### Which operating system are you using to run this browser?

macOS

### Problem-relevant frontend configuration

```yaml
- title: Air quality
    path: air-quality
    icon: mdi:air-filter
    type: sections
    sections:
      - type: grid
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.awair_element_74608_score
                needle: true
                min: 0
                max: 100
                view_layout:
                  position: sidebar
                name: Score
                severity:
                  green: 80
                  yellow: 50
                  red: 0
              - type: vertical-stack
                cards:
                  - type: tile
                    entity: sensor.awair_element_74608_temperature
                    name: Température
                  - type: tile
                    entity: sensor.awair_element_74608_humidity
                    name: Humidité
```
