### ISSUE TITLE
Automation Editor - missing summary for entity_id: all target

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20963]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

You can use `entity_id: all` as target in service calls, for example to turn off all lights when leaving home. It's documented in "the basics" section of [service calls docs](https://www.home-assistant.io/docs/scripts/service-calls/#the-basics), but isn't supported in the automation editor summary at the moment. Summary refers to it as an "unknown entity" 

<img width="830" alt="Screen Shot 2024-06-03 at 2 26 37 AM" src="https://github.com/home-assistant/frontend/assets/9065557/da1a3685-9bc2-4217-b2bb-a0e39511d255">

### Describe the behavior you expected

Should be summarized as ` Call a service 'Light: Turn on' on all lights` or something like that

### Steps to reproduce the issue

Below is an example automation to reproduce

```
alias: Test - Missing Automation Summary
trigger:
  - platform: sun
    event: sunset
    offset: 0
action:
  - service: light.turn_on
    target:
      entity_id: all
    data: {}
mode: single
```

### What version of Home Assistant Core has the issue?

2024.6.0b5
