### ISSUE TITLE
Entity Filter card not staying hidden

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#20979]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating to the latest beta, 2024.6.0b6 all my entity filter cards that are set to `show_empty: false` are becoming visible  whenever an entity in the card updates, even if the entity state does not match the condition. i.e. the card is empty but visible. 

### Describe the behavior you expected

The cards to stay hidden when empty. 

### Steps to reproduce the issue

1. Create an entity filter card with `show_empty: false`
2. Add it to a dashboard
3. Wait for the entity to update and observe the card not staying hidden
...

### What version of Home Assistant Core has the issue?

 core-2024.6.0b6

### What was the last working version of Home Assistant Core?

 core-2024.6.0b5

### In which browser are you experiencing the issue with?

Firefox 126.0.1, Chrome 125.0.6422.142

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
type: entity-filter
show_empty: false
entities:
  - entity: sensor.memory_use_percent
    state_filter:
      - operator: '>'
        value: 25
  - entity: sensor.home_assistant_supervisor_memory_percent
    state_filter:
      - operator: '>'
        value: 30
  - entity: sensor.database_size
    state_filter:
      - operator: '>'
        value: 3000
  - entity: sensor.processor_temperature
    state_filter:
      - operator: '>'
        value: 60
  - entity: sensor.processor_use
    state_filter:
      - operator: '>'
        value: 30
  - entity: sensor.home_assistant_core_cpu_percent
    state_filter:
      - operator: '>'
        value: 30
  - entity: sensor.home_assistant_supervisor_cpu_percent
    state_filter:
      - operator: '>'
        value: 30
card:
  type: glance
  title: System Issue
```

### Javascript errors shown in your browser console/inspector

```txt
Unexpected value NaN parsing height attribute.
```

**Comment by tomlut** [comment]
Confirmed reverting to 2024.6.0b5 fixes this issue.

**Comment by piitaya** [comment]
Hi 👋 Can you provide some screenshot or video recording? I can not reproduce it 🙁

I tested with this config

```yaml
type: entity-filter
entities:
  - input_number.distance
state_filter:
  - operator: '>'
    value: 30
card:
  type: glance
  title: System Issue
show_empty: false
```

https://github.com/home-assistant/frontend/assets/5878303/766f4b63-f435-4182-b182-596c0f03f088

F

**Comment by tomlut** [comment]
Sure thing. The following is recorded in safe mode (hidden card appears at around the 15s mark):

https://youtu.be/pgfs9ibftLU

Here are the two card configs you are looking at:
```
type: entity-filter
show_empty: false
card:
  show_header_toggle: false
  title: System
  type: glance
entities:
  - entity: sensor.memory_use_percent
    state_filter:
      - operator: '>'
        value: 25
  - entity: sensor.home_assistant_supervisor_memory_percent
    state_filter:
      - operator: '>'
        value: 30
  - entity: sensor.database_size
    state_filter:
      - operator: '>'
        value: 3000
  - entity: sensor.processor_temperature
    state_filter:
      - operator: '>'
        value: 60
  - entity: sensor.processor_use
    state_filter:
      - operator: '>'
        value: 30
  - entity: sensor.home_assistant_core_cpu_percent
    state_filter:
      - operator: '>'
        value: 30
  - entity: sensor.home_assistant_supervisor_cpu_percent
    state_filter:
      - operator: '>'
        value: 30

```
```
type: entities
entities:
  - entity: sensor.memory_use_percent
    secondary_info: last-changed
  - entity: sensor.home_assistant_supervisor_memory_percent
    secondary_info: last-changed
  - entity: sensor.database_size
    secondary_info: last-changed
  - entity: sensor.processor_temperature
    secondary_info: last-changed
  - entity: sensor.processor_use
    secondary_info: last-changed
  - entity: sensor.home_assistant_core_cpu_percent
    secondary_info: last-changed
  - entity: sensor.home_assistant_supervisor_cpu_percent
    secondary_info: last-changed
```


I did not notice any of the sensors last changed secondary info update. So I'm completely unsure as to what is causing it now.

**Comment by tomlut** [comment]
I just tried with your example. It is the updates that trigger the appearance and disappearance (again in safe mode):

https://youtu.be/IG979ApUHn4?si=F-KE4maW94i0D6_s

```
type: entity-filter
show_empty: false
card:
  show_header_toggle: false
  title: System
  type: glance
entities:
  - entity: input_number.anova_run_time
    state_filter:
      - operator: '>'
        value: 100
```

```
type: entities
entities:
  - entity: input_number.anova_run_time
 ```
