### ISSUE TITLE
Visibility option only functional on top level card, not on nested card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21009]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

as title, the new (2024.6) visibility option for cards does not work when doing below snippet

the card with the visibility option set is visible always.

using that exact configuration as separate cards works as expected

### Describe the behavior you expected

have the visibility option work on nested card

### Steps to reproduce the issue

1. see yaml
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.0

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

sonoma 14.5

### Problem-relevant frontend configuration

```yaml
    - type: vertical-stack
      cards:
        - type: entities
          entities:
            - input_boolean.test_2

        - type: conditional
          conditions:
            - condition: state
              entity: input_boolean.test_2
              state: 'on'
          card:
            type: entities
            title: Type Conditional
            entities:
              - light.zitkamer

        - type: entities
          title: Visibility
          visibility:
            - condition: state
              entity: input_boolean.test_2
              state: 'off'
          entities:
            - light.zitkamer
```
