### ISSUE TITLE
Weather-forecast card does not show correct icons and units for some secondary_info_attributes

### ISSUE THREAD

**Issue by Jpsy** [home-assistant/frontend#21026]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Problem when using weather-forecast card with secondary_info_attribute option:
Not all attributes are shown with their icon and their correct unit.

### Describe the behavior you expected

The secondary_info_attribute should be shown with the same icon and unit that their respective entities show.

### Steps to reproduce the issue

1. Use the following YAML code to create three dashboard cards:
```
type: vertical-stack
cards:
  - type: weather-forecast
    entity: weather.openweathermap
    forecast_type: daily
    # humidity works fine
    secondary_info_attribute: humidity
  - type: weather-forecast
    entity: weather.openweathermap
    forecast_type: daily
    # THIS ONE SHOWS THE PROBLEM: dew_point shows no icon and no unit
    secondary_info_attribute: dew_point
  - type: entities
    entities:
      # This is dew_point in an entities card for comparision, icon and unit are shown correctly
      - entity: sensor.openweathermap_dew_point
```
2. Compare the icons and the units in all three cards.

    Notice that the first weather card shows an icon and a unit, while the second card does not.
The third card is an entities card that shows that the icon and the unit is well defined for the dew point entitity used in the second card.
![image](https://github.com/home-assistant/frontend/assets/1806058/2da0c86a-01b5-48ce-876d-162016ef20bd)

### What version of Home Assistant Core has the issue?

2024.6.0

### In which browser are you experiencing the issue with?

Google Chrome 125.0.6422.113 

### Which operating system are you using to run this browser?

macOS Sonoma 14.5
