### ISSUE TITLE
Tile Card not supporting features for Device Type water_heater.

### ISSUE THREAD

**Issue by cloudbr34k84** [home-assistant/frontend#21070]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a pool heater entity using  water_heater.pool_heater_pool_heater. 
when i set this up on the tile card, its not display the text or icons for the features section. See image below
It was set up using Tuya Local as per the below image as well
![image](https://github.com/home-assistant/frontend/assets/58960644/ff11d40d-b94d-43e9-b111-f69da0e54649)
![image](https://github.com/home-assistant/frontend/assets/58960644/681303c4-e7f1-4d9b-b8b2-159222989817)

![image](https://github.com/home-assistant/frontend/assets/58960644/1a434409-cdbf-477f-9e68-fd894059f9de)

### Describe the behavior you expected

I expected the features to show the icon or text

### Steps to reproduce the issue

1. Add tile card
2. add entity
3. enable features
...

### What version of Home Assistant Core has the issue?

2024.6.2

### In which browser are you experiencing the issue with?

Version 125.0.6422.142 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
water_heater.pool_heater_pool_heater
Pool Heater Pool Heater
Power Heating	min_temp: 5
max_temp: 60
operation_list: Smart Heating, Power Heating, Silent Heating, Smart Cooling, Powerful Cooling, Silent Cooling, Off
icon: 
friendly_name: Pool Heater Pool Heater
supported_features: 11
current_temperature: 27
temperature: 30
operation_mode: Power Heating
raw_state: true
```

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: tile
    entity: water_heater.pool_heater_pool_heater
    name: Pool Heater
    icon: mdi:pool-thermometer
    color: primary
    features:
      - type: target-temperature
      - type: water-heater-operation-modes
        operation_modes:
          - Smart Heating
          - Power Heating
          - Silent Heating
          - 'Off'
```
