### ISSUE TITLE
% suffix on a type: attribute not connected like regular unit

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21080]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

top fold: regular entities in a type entities card

bottom fold: type attribute in a [type entities card with suffix set](https://www.home-assistant.io/dashboards/entities/#suffix)

<img width="510" alt="Scherm­afbeelding 2024-06-13 om 14 14 31" src="https://github.com/home-assistant/frontend/assets/33354141/2eb356c0-22b0-444c-87d3-6b18852b1906">

### Describe the behavior you expected

have the suffixes behave like units on regular entities

### Steps to reproduce the issue

1. see yaml
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.2

### In which browser are you experiencing the issue with?

any

### Problem-relevant frontend configuration

```yaml
entities:
      - type: attribute
        entity: binary_sensor.knmi_zon
        name: Vandaag
        attribute: sun_chance0
        suffix: '%'

# compared to

    entities:
      - entity: sensor.buienradar_sunchance_1d
        name: Morgen
      - entity: sensor.buienradar_sunchance_2d
        name: Overmogen
        <<: *style
      - entity: sensor.buienradar_sunchance_3d
        name: 3 dagen
```

### Javascript errors shown in your browser console/inspector

No error
### Additional information

see https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/6621?u=mariusthvdb where I was exploring the card_mod styling options, which made me discover the dispositioned Unit symbol for %
