### ISSUE TITLE
Section Visibility: Invisible section when condition is false

### ISSUE THREAD

**Issue by lionking102** [home-assistant/frontend#21110]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![Screenshot Section Visibility](https://github.com/home-assistant/frontend/assets/92639795/aefacb4c-7ee9-4757-863b-3bb3ef9bd87b)

I use the Drag&Drop Dashboard and wanted to use a dropdown list that only shows the selected remote.
As seen in the screenshot the section that doesn`t match the condition goes only invisible, but still exists.
That makes this feature a lot less useful, would be nice, if there was at least an option/toggle.
It is also not consistent with other cards, like stacks, where the card vanishes when the condition is false.

It is of course posible to use a grid/stack inside the section, but that eliminates the sense of the drag&drop dashboard, as there is no drag&drop then anymore.

Despite that: The new visibility feature is just awesome, thanks again for all the great work! :)

### Describe the behavior you expected

The section where the visibility-condition is false should vanish completely, not just go invisible.

### Steps to reproduce the issue

1. Set a condition for a drag&drop section.
2. The condition needs to be false.
3. The sections goes invisible, but is still prominent on the dashboard.

### What version of Home Assistant Core has the issue?

2024.6.3

### In which browser are you experiencing the issue with?

Firefox 127

### Which operating system are you using to run this browser?

Linux Fedora

**Comment by ChristophCaina** [comment]
can you share your yaml for the section / cards here?
On my current dashboard, the section will be completely "removed" if the condition to show it is not met.

**Comment by lionking102** [comment]
Sorry for the late replay, was gone for a few days.

Here is the code. You will most likely only need the bottom part for the visibility.

```
type: grid
cards:
  - type: vertical-stack
    cards:
      - square: true
        type: grid
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_power_toggle
            icon: mdi:power
            hold_action:
              action: none
            show_state: false
            name: Power
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_soundmode_movie
            icon: mdi:music
            hold_action:
              action: none
            show_state: false
            name: Movie
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_soundmode_music
            icon: mdi:music
            hold_action:
              action: none
            show_state: false
            name: Music
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_soundmode_game
            icon: mdi:music
            hold_action:
              action: none
            show_state: false
            name: Game
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_soundmode_pure
            icon: mdi:music
            hold_action:
              action: none
            show_state: false
            name: Pure
        columns: 5
      - square: false
        type: grid
        cards:
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_aux1
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Aux1
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_aux2
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Aux2
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_mediaplayer
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Media P
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_tvaudio
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: TV Audio
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_tuner
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Tuner
        columns: 5
      - square: false
        type: grid
        cards:
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_ipod_usb
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Ipod/USB
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_mxport
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: MX Port
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_cd
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: CD
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_network
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Network
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_phono
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Phono
        columns: 5
      - square: false
        type: grid
        cards:
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_game
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Game
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_bluray
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: Bluray
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_dvd
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: DVD
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_cbl_sat
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: CBL/Sat
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_source_internet_radio
            icon: mdi:source-branch
            hold_action:
              action: none
            show_state: false
            name: I-Radio
        columns: 5
      - square: true
        type: grid
        cards:
          - show_name: false
            show_icon: false
            type: button
            tap_action:
              action: none
            icon: ""
            hold_action:
              action: none
            show_state: false
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_volume_info
            icon: mdi:information-box-outline
            hold_action:
              action: none
            show_state: false
            name: Info
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_arrow_up
            icon: mdi:arrow-up
            hold_action:
              action: none
            show_state: false
            name: Arrow Up
            theme: ios-light-mode-orange
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_option
            icon: mdi:power
            hold_action:
              action: none
            show_state: false
            name: Option
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_volume_up
            icon: mdi:volume-plus
            show_state: false
            name: Volume Up
            hold_action:
              action: none
        columns: 5
      - square: true
        type: grid
        cards:
          - show_name: false
            show_icon: false
            type: button
            tap_action:
              action: none
            icon: ""
            hold_action:
              action: none
            show_state: false
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_arrow_left
            icon: mdi:arrow-left
            hold_action:
              action: none
            show_state: false
            name: Arrow Left
            theme: ios-light-mode-orange
          - show_name: true
            show_icon: false
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_ok
            icon: ""
            hold_action:
              action: none
            show_state: false
            name: OK
            theme: ios-light-mode-orange
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_arrow_right
            icon: mdi:arrow-right
            hold_action:
              action: none
            show_state: false
            name: Arrow Right
            theme: ios-light-mode-orange
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_volume_down
            icon: mdi:volume-minus
            hold_action:
              action: none
            show_state: false
            name: Volume Down
        columns: 5
      - square: true
        type: grid
        cards:
          - show_name: false
            show_icon: false
            type: button
            tap_action:
              action: none
            icon: ""
            hold_action:
              action: none
            show_state: false
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_back
            icon: mdi:keyboard-return
            hold_action:
              action: none
            show_state: false
            name: Back
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_arrow_down
            icon: mdi:arrow-down
            hold_action:
              action: none
            show_state: false
            name: Arrow Down
            theme: ios-light-mode-orange
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_setup
            icon: mdi:application-cog-outline
            hold_action:
              action: none
            show_state: false
            name: Setup
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: script.remote_av_receiver_mute
            icon: mdi:volume-mute
            hold_action:
              action: none
            show_state: false
            name: Mute
        columns: 5
visibility:
  - condition: state
    entity: input_select.dropdown_remotes
    state: AV Receiver
```
