### ISSUE TITLE
Bug with camera image display: the image's bottom part is missing

### ISSUE THREAD

**Issue by almirus** [home-assistant/frontend#21155]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When displaying the camera image, the bottom part is "cut off." The image is not vertically centered.

### Describe the behavior you expected

The image must be centered

### Steps to reproduce the issue

1. Add a camera entity.
2. Ensure that the bottom part is cut off and not displayed.

### What version of Home Assistant Core has the issue?

2024.6.4

### In which browser are you experiencing the issue with?

Chrome 126.0.6478.63

### Which operating system are you using to run this browser?

win 11

### Problem-relevant frontend configuration

```yaml
square: false
type: grid
cards:
  - type: entity
    entity: sensor.time
  - show_state: false
    show_name: false
    camera_view: live
    type: picture-entity
    entity: camera.camera_hub_g2h_e718_camera_stream_management0
    camera_image: camera.doorbell_repeater_b8b7
columns: 2

show_state: false
show_name: false
camera_view: live
type: picture-entity
entity: camera.doorbell_repeater_b8b7
camera_image: camera.doorbell_repeater_b8b7
```

### Additional information

![image](https://github.com/home-assistant/frontend/assets/16898685/9380e8a1-2f72-4de8-8f84-0ca9f3258463)

original image (camera stream)
![image](https://github.com/home-assistant/frontend/assets/16898685/2e7f7373-ba1f-4493-8b2f-c97b62c65301)

![image](https://github.com/home-assistant/frontend/assets/16898685/ea1b2ddf-aca0-4455-afe1-1c8cab9fe021)
original image
![image](https://github.com/home-assistant/frontend/assets/16898685/61aaf6fb-cfcf-49ab-8206-c255714b3882)
