### ISSUE TITLE
HA Alarm: Validation error: Arming requires a code but none was given for alarm_control_panel.ha_alarm

### ISSUE THREAD

**Issue by maartenroos** [home-assistant/frontend#21167]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Even after reinstall, I get the following error: Kan service alarm_control_panel/alarm_arm_away niet aanroepen. Validation error: Arming requires a code but none was given for alarm_control_panel.ha_alarm". 

It has worked just fine before. Bug since one of the latest updates? 

Please help, thank you.

### Describe the behavior you expected

For HA Alarm to be activated.

### Steps to reproduce the issue

1. Press any activation key on HA Alarm
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.4

### In which browser are you experiencing the issue with?

Chrome 126.0.6478.126

### Which operating system are you using to run this browser?

W11

### Problem-relevant frontend configuration

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Alarm panel
alarm_control_panel:
  - platform: manual

# Remote GPIO
switch:
  - platform: remote_rpi_gpio
    host: 192.168.2.103
    ports:
      18: LED4
      16: LED5
      23: LED6

# Media Player
media_player:
  - platform: vlc
```
