### ISSUE TITLE
Vertical stack breaks cards

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/frontend#21176]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since upgrading to 2024.7.0b0, I am having issues with cards in vertical stack: my (default) map card is broken inside the stack, works fine outside

![image](https://github.com/home-assistant/frontend/assets/33529490/e99380b2-d03e-442b-a61a-4062214a86d3)

![image](https://github.com/home-assistant/frontend/assets/33529490/b4dc5488-e05b-4d77-8d35-66b609fc9480)

### Describe the behavior you expected

A working map card in vertical-stack. This worked fine in 2024.6.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.7.0b0

### What was the last working version of Home Assistant Core?

core-2024.6.4

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Win11

### Problem-relevant frontend configuration

```yaml
####################
# Locations        #
####################
path: locations
title: Locatie
icon: mdi:crosshairs-gps
cards:
  - type: vertical-stack
    cards:
      - type: markdown ## Location header
        content: |
          # Location
      - type: custom:mushroom-chips-card
        alignment: justify
        chips:
          - type: entity
            entity: person.bob
            use_entity_picture: true
          - type: entity
            entity: !secret person_mw
            use_entity_picture: true
          - type: entity
            entity: !secret person_puber
            use_entity_picture: true
          - type: entity
            entity: !secret person_mini
            use_entity_picture: true

      - type: map
        entities:
          - person.bob
          - !secret person_mw
          - !secret person_mini
          - !secret person_puber
          - zone.breda
          - zone.cz
          - zone.home
          - zone.mc
          - zone.ploeterklas
          - zone.school
          - zone.school_mini
          - zone.scouting
          - zone.work
          - zone.work_ms
```

### Additional information

Also a [custom-card is broken](https://github.com/Olen/lovelace-flower-card/issues/125) inside the stack, works partially outside the stack:

![image](https://github.com/home-assistant/frontend/assets/33529490/c75cfcb4-2bab-42b7-b402-c70a3d2120ee)

```
create-element-base.ts:190 card vertical-stack TypeError: Cannot read properties of undefined (reading 'states')
    at set hass (flower-card.js?2:100:22626)
    at i.value (hui-card.ts:95:13)
    at i.value (hui-card.ts:125:26)
    at i.value (hui-card.ts:35:12)
    at n.value (hui-stack-card.ts:71:13)
    at hui-stack-card.ts:45:28
    at Array.map (<anonymous>)
    at n.value (hui-stack-card.ts:44:32)
    at o (create-element-base.ts:104:11)
    at create-element-base.ts:147:12
```

**Comment by karwosts** [comment]
Please try removing custom cards and/or safe mode. 

Map card in a vertical stack working fine for me :shrug:

**Comment by hmmbob** [comment]
fwiw, with default HA theme and the below YAML, it still does not load properly with the same errors

```yaml
####################
# Locations        #
####################
path: locations
title: Locatie
icon: mdi:crosshairs-gps
cards:
  - type: vertical-stack
    cards:
      - type: map
        entities:
          - person.bob
          - !secret person_mw
          - !secret person_mini
          - !secret person_puber
          - zone.breda
          - zone.cz
          - zone.home
          - zone.mc
          - zone.ploeterklas
          - zone.school
          - zone.school_mini
          - zone.scouting
          - zone.work
          - zone.work_ms
```
