### ISSUE TITLE
service-button css styles not applying

### ISSUE THREAD

**Issue by ukmgranger** [home-assistant/frontend#2118]
**Home Assistant release with the issue:**
0.82.1

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Chrome & firefox

**Description of problem:**
The styles CSS information isn't being applied for the font color or text-transform. 

Here is part of my code:
```
          - type: service-button
            title: Security
            style:
              top: 8.5%
              left: 57%
              font-size: 2.1vw
              color: white
              font-weight: lighter
              text-transform: none
            service: homeassistant.turn_off
            service_data:
            entity_id: group.all
```
A screenshot can be seen here:
https://community.home-assistant.io/t/state-label-hide-state/80481/12?u=martin_granger

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
