### ISSUE TITLE
2024.7.0bx broke all my views - issue with sizing of cards

### ISSUE THREAD

**Issue by alexruffell** [home-assistant/frontend#21182]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I use `vertical-stack` , `horizontal-stack`, and `custom:button-card` a lot in all my views. Something in the last beta cycle broke them all.

The snapshot below has a horizontal stack divided into 3 sections. The first one includes a vertical stack of 3 buttons. The issue is with the two buttons to the right. Height is specified as 100% which prior to the latest update made the buttons fill the entire space available. To fix the issue I now need to replace 100% with 133px.

<img width="353" alt="image" src="https://github.com/home-assistant/frontend/assets/4006944/dd099d6a-f3f3-4a55-859e-6ec9413c3f69">

```
type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:button-card
        styles:
          card: null
          name:
            - text-transform: uppercase
            - font-size: 10px
            - font-weight: normal
            - justify-self: center
            - margin-left: '-25px'
            - letter-spacing: 2px
          icon:
            - color: var(--paper-item-icon-color)
            - height: 25px
            - width: 25x
            - padding: 0px 20px 0px 0px
        tap_action:
          action: navigate
          navigation_path: /lovelace/entrance
        name: Entrance
        show_icon: true
        icon: mdi:door-open
        layout: icon_name
      - type: custom:button-card
        styles:
          card: null
          name:
            - text-transform: uppercase
            - font-size: 10px
            - font-weight: normal
            - justify-self: center
            - margin-left: '-25px'
            - letter-spacing: 2px
          icon:
            - color: var(--paper-item-icon-color)
            - height: 25px
            - width: 25x
            - padding: 0px 20px 0px 0px
        tap_action:
          action: navigate
          navigation_path: /lovelace/kitchen
        name: Kitchen
        show_icon: true
        icon: mdi:stove
        layout: icon_name
      - type: custom:button-card
        styles:
          card: null
          name:
            - text-transform: uppercase
            - font-size: 10px
            - font-weight: normal
            - justify-self: center
            - margin-left: '-25px'
            - letter-spacing: 2px
          icon:
            - color: var(--paper-item-icon-color)
            - height: 25px
            - width: 25x
            - padding: 0px 20px 0px 0px
        tap_action:
          action: navigate
          navigation_path: /lovelace/living-room
        name: Living<br/>Room
        show_icon: true
        icon: mdi:sofa-outline
        layout: icon_name
  - type: custom:button-card
    entity: binary_sensor.front_door
    name: Front<br/>Door
    styles:
      card:
        - height: 100%
      name:
        - text-transform: uppercase
        - font-size: 10px
        - font-weight: normal
        - justify-self: center
        - letter-spacing: 1px
        - padding-bottom: 5px
    icon: |
      [[[
        if (states["lock.front_door_lock"].state == "unavailable") return "mdi:alert-circle-outline";
        else if (states["binary_sensor.front_door"].state == "on") return "mdi:door-open";
        else if (states["lock.front_door_lock"].state == "locked") return "mdi:door-closed-lock";
        else return "mdi:door-closed";
      ]]] 
    state:
      - value: 'on'
        styles:
          icon:
            - color: red
            - animation:
                - blink 2s linear infinite
      - value: 'off'
        styles:
          icon:
            - color: |
                [[[
                  if (states["lock.front_door_lock"].state == "unlocked") return "red";
                  if (states["lock.front_door_lock"].state == "unavailable") return "gray";
                  else return "var(--paper-item-icon-color)";
                ]]] 
    tap_action:
      action: call-service
      service: lock.lock
      service_data:
        entity_id: lock.front_door_lock
    hold_action:
      action: call-service
      service: lock.unlock
      service_data:
        entity_id: lock.front_door_lock
    show_icon: true
    show_state: false
  - type: custom:button-card
    entity: binary_sensor.patio_door
    name: Patio<br/>Door
    styles:
      card:
        - height: 100%
      name:
        - text-transform: uppercase
        - font-size: 10px
        - font-weight: normal
        - justify-self: center
        - letter-spacing: 1px
        - padding-bottom: 5px
    icon: |
      [[[
        if (states["lock.patio_door_lock"].state == "unavailable") return "mdi:alert-circle-outline";
        else if (states["binary_sensor.patio_door"].state == "on") return "mdi:door-open";
        else if (states["lock.patio_door_lock"].state == "locked") return "mdi:door-closed-lock";
        else return "mdi:door-closed";
      ]]] 
    state:
      - value: 'on'
        styles:
          icon:
            - color: red
            - animation:
                - blink 2s linear infinite
      - value: 'off'
        styles:
          icon:
            - color: |
                [[[
                  if (states["lock.patio_door_lock"].state == "unlocked") return "red";
                  if (states["lock.patio_door_lock"].state == "unavailable") return "gray";
                  else return "var(--paper-item-icon-color)";
                ]]]
    tap_action:
      action: call-service
      service: lock.lock
      service_data:
        entity_id: lock.patio_door_lock
    hold_action:
      action: call-service
      service: lock.unlock
      service_data:
        entity_id: lock.patio_door_lock
    show_icon: true
    show_state: false
```

In this example, I show a small row I put at the top of my first vertical stack, of all my views. It includes a link to the main dashboard, a link to a menu where I can navigate to another view without returning to the main one, room temperature and humidity, motion, and the name of the room (mostly useful on phone). All the cards are `custom:button-card`.

<img width="388" alt="image" src="https://github.com/home-assistant/frontend/assets/4006944/fe22c97d-5526-4d22-be8a-4e73e602665d">

This is what it should look like:

![image](https://github.com/home-assistant/frontend/assets/4006944/6cfd2984-fe84-4dff-9e8c-a9247bc12e0d)

```
type: horizontal-stack
cards:
  - type: custom:button-card
    styles:
      card:
        - padding: 5px 7px
        - width: 38px
      icon:
        - color: var(--paper-item-icon-color)
        - height: 22px
        - width: 22px
    tap_action:
      action: navigate
      navigation_path: /lovelace/home
    name: ''
    show_icon: true
    icon: mdi:home-outline
    layout: icon
  - type: custom:button-card
    styles:
      card:
        - padding: 5px 7px
        - width: 38px
      icon:
        - color: var(--paper-item-icon-color)
        - height: 22px
        - width: 22px
    tap_action:
      action: navigate
      navigation_path: /lovelace/main-menu/
    name: ''
    show_icon: true
    icon: mdi:cellphone
    layout: icon
  - type: custom:button-card
    entity: sensor.office_multi_sensor_temperature
    styles:
      card:
        - height: 100%
        - width: 58px
        - padding: 0px 0px 0px 2px
      name:
        - text-transform: uppercase
        - font-size: 12px
        - font-weight: normal
        - justify-self: center
        - letter-spacing: 2px
        - padding: 0%
    tap_action:
      action: none
    show_icon: false
    show_name: false
    show_state: true
    layout: name_state
  - type: custom:button-card
    entity: sensor.office_multi_sensor_humidity
    styles:
      card:
        - height: 100%
        - width: 42px
        - padding: 0px 0px 0px 2px
      name:
        - text-transform: uppercase
        - font-size: 12px
        - font-weight: normal
        - justify-self: center
        - letter-spacing: 2px
        - padding: 0%
    tap_action:
      action: none
    show_icon: false
    show_name: false
    show_state: true
    layout: name_state
  - type: custom:button-card
    entity: binary_sensor.office_motion_sensors_group
    styles:
      card:
        - height: 100%
        - width: 38px
        - padding: 0px 0px 0px 14px
      icon:
        - height: 22px
        - width: 22px
      img_cell:
        - padding: 0px 5px 0px 5px
      grid:
        - grid-template-areas: '"i"'
    state:
      - value: 'on'
        icon: mdi:motion-sensor
        color: red
      - value: 'off'
        icon: mdi:motion-sensor-off
    tap_action:
      action: none
    show_icon: true
    show_name: false
    show_state: false
    layout: icon_state
  - type: custom:button-card
    styles:
      card:
        - height: 100%
        - padding: 5px 5px
      name:
        - text-transform: uppercase
        - font-size: 10px
        - font-weight: normal
        - padding: 5px 5px
        - letter-spacing: 2px
    tap_action:
      action: none
    hold_action:
      action: none
    name: Office
    show_icon: false

```

### Describe the behavior you expected

The sizing should be respected as it was prior to 2024.7.bx beta cycle.

### Steps to reproduce the issue

n/a

### What version of Home Assistant Core has the issue?

core-2023.7.0b0

### What was the last working version of Home Assistant Core?

core-2023.7.0b2

### In which browser are you experiencing the issue with?

Chrome, Brave, FF

### Which operating system are you using to run this browser?

Windows 11
