### ISSUE TITLE
Entity Filter card broken in 2024.7.0b3

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#21196]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating to 2024.7.0b3 all my entity filter cards are broke. It doesn't display the nested card at first.

- Initial load of page, it shows as empty cards, despite not actually being empty. 
- Upon a state change they will then appear. For example on my "doors and windows open" entity filter card, if I open a door it'll then appear. This works until a refresh of page.

Screenshot from safe mode, this is what it looks like on initial page load. Appears as empty despite not being empty.

<img width="691" alt="Screen Shot 2024-06-27 at 6 56 52 PM" src="https://github.com/home-assistant/frontend/assets/9065557/bd1568be-0b46-4fc5-b586-d4de228f0bb0">

### Describe the behavior you expected

Work as before

### Steps to reproduce the issue

Just have an entity filter card.

```
type: entity-filter
show_empty: false
entities:
  - person.sean
  - person.two
  - person.three
  - person.four
state_filter:
  - home
card:
  type: glance
  title: People Home
  show_state: false
```

Minimal version of other card config. It will show as empty card at first but if you open a door, it will then show as expected.
```
type: entity-filter
entities:
  - binary_sensor.back_door
  - binary_sensor.front_door
state_filter:
  - 'on'
card:
  type: glance
  title: Doors and Windows Open
show_empty: false
```

### What version of Home Assistant Core has the issue?

2024.7.0b3

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

macOS
