### ISSUE TITLE
Cards inside horizontal stack don't spread evenly

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/frontend#21206]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since beta3, cards inside a horizontal stack do not spread evenly anymore. This is a bunch of mushroom light cards inside  a horizontal stack for each line inside a vertical stack. These light cards used to fill out nicely into two equal columns, now they look like this non-OCD-compatible bunch of clutter. 

![image](https://github.com/home-assistant/frontend/assets/33529490/5ec96285-1222-48fa-ac52-8add28b7b9cf)

As [reported on discord](https://discord.com/channels/330944238910963714/427516175237382144/1256140855715168287)

### Describe the behavior you expected

Two equal columns of cards

### Steps to reproduce the issue

.

### What version of Home Assistant Core has the issue?

core-2024.7.0b3

### What was the last working version of Home Assistant Core?

core-2024.7.0b2

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Win11

### Problem-relevant frontend configuration

```yaml
path: start
title: Start
icon: mdi:home-assistant
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 0px 0px 14px;
                }
            entity: light.spots_vaas
            icon: mdi:lightbulb-spot
            fill_container: true
            show_brightness_control: true
            collapsible_controls: true
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 14px 0px 0px;
                }
            entity: light.spots_woonkamer
            icon: mdi:sofa
            fill_container: true
            show_brightness_control: true
            collapsible_controls: true

      - type: horizontal-stack
        cards:
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 0px 0px 14px;
                }
            entity: light.spots_eetkamer
            icon: mdi:table-chair
            show_brightness_control: true
            collapsible_controls: true
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 14px 0px 0px;
                }
            entity: light.eetkamer_tafel
            icon: mdi:globe-light-outline
            show_brightness_control: true
            collapsible_controls: true

      - type: horizontal-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.spots_keuken
            icon: mdi:countertop
            fill_container: false
            show_brightness_control: true
            collapsible_controls: true
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 0px 0px 14px;
                }
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 14px 0px 0px;
                }
            entity: light.badkamer
            show_brightness_control: true
            collapsible_controls: true

      - type: horizontal-stack
        cards:
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 0px 0px 14px;
                }
            entity: light.sonoff_l1
            name: "Ledstrip pubercave"
            icon: mdi:led-strip-variant
            show_brightness_control: true
            collapsible_controls: true
            show_color_control: true
            use_light_color: true
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 14px 0px 0px;
                }
            entity: light.battletron_ball_light_m
            name: "Ball light pubercave"
            icon: mdi:globe-light-outline
            show_brightness_control: true
            collapsible_controls: true
            show_color_control: true
            use_light_color: true

      - type: horizontal-stack
        cards:
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 0px 0px 14px;
                }
            entity: light.ledstrip_mini
            name: "Bureau minicave"
            icon: mdi:desk
            show_brightness_control: true
            collapsible_controls: true
            show_color_control: true
            use_light_color: true
          - type: custom:mushroom-light-card
            card_mod:
              style: |
                ha-card {
                  box-shadow: var(--card-box-shadow);
                  margin: 0px 14px 0px 0px;
                }
            entity: light.ledstrip_bed_mini
            name: "Bed minicave"
            icon: mdi:bed
            show_brightness_control: true
            collapsible_controls: true
            show_color_control: true
            use_light_color: true

      - type: custom:mushroom-light-card
        card_mod:
          style: |
            ha-card {
              box-shadow: var(--card-box-shadow);
              margin: 0px 14px 0px 14px;
            }
        entity: switch.tuinverlichting
        icon: mdi:coach-lamp
        show_brightness_control: true
        collapsible_controls: true
        show_color_control: true
        use_light_color: true
```
