### ISSUE TITLE
2024.7.0b3 breaks custom:grid-layout when using horizontal-stack or vertical-stack

### ISSUE THREAD

**Issue by EDelsman** [home-assistant/frontend#21211]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

when using https://github.com/thomasloven/lovelace-layout-card the custom:grid-layout is completely broken. b02 is working fine

### Describe the behavior you expected

Header should have three lights, sidebar too, area's should be where expected. The code is in the "steps to reproduce"

### Steps to reproduce the issue

Use sample code below in b3, looks fine in b2

### What version of Home Assistant Core has the issue?

2024.7.0b3

### What was the last working version of Home Assistant Core?

2024.7.0b2

### In which browser are you experiencing the issue with?

Google Chrome 126.0.6478.127

### Which operating system are you using to run this browser?

Windows 11, ipad os, android, ...

### Problem-relevant frontend configuration

```yaml
views:
  - title: Home
    type: custom:grid-layout
    layout:
      grid-template-columns: auto 30px 25%
      grid-template-rows: auto
      grid-template-areas: |
        "header header header"
        "main . sidebar"
        "footer footer footer"
      mediaquery:
        '(max-width: 600px)':
          grid-template-columns: 100%
          grid-template-areas: |
            "header"
            "sidebar"
            "main"
            "footer"
        '(max-width: 800px)':
          grid-template-columns: 50% 50%
          grid-template-areas: |
            "header sidebar"
            "main main"
            "footer footer"
    cards:
      - type: horizontal-stack
        view_layout:
          grid-area: header
        cards:
          - type: entities
            entities:
              - entity: light.woonkamer
            title: '1'
            show_header_toggle: false
          - type: entities
            entities:
              - entity: light.woonkamer
            title: '1'
            show_header_toggle: false
          - type: entities
            entities:
              - entity: light.woonkamer
            title: '1'
            show_header_toggle: false
      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: entities
            entities:
              - entity: light.woonkamer
            title: '2'
            show_header_toggle: false
          - type: entities
            entities:
              - entity: light.woonkamer
            title: '2'
            show_header_toggle: false
          - type: entities
            entities:
              - entity: light.woonkamer
            title: '2'
            show_header_toggle: false
      - type: entities
        entities:
          - entity: light.woonkamer
        title: '3'
        show_header_toggle: false
        view_layout:
          grid-area: footer
      - type: entities
        entities:
          - light.woonkamer
          - light.woonkamer
          - light.woonkamer
        title: '4'
        show_header_toggle: false
        view_layout:
          grid-area: main
```
