### ISSUE TITLE
Dev tools -> Services: cannot use "input_datetime.set_datetime" to set a 0 value

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21220]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This code seems to be considered as wrong:
```
service: input_datetime.set_datetime
target:
  entity_id: input_datetime.test_datetime
data:
  timestamp: 0
```
![image](https://github.com/home-assistant/frontend/assets/71872483/ac9799f3-959c-4bf7-a103-25a5f7fd3108)

This code is accepted:
```
service: input_datetime.set_datetime
target:
  entity_id: input_datetime.test_datetime
data:
  timestamp: 0.001
```
![image](https://github.com/home-assistant/frontend/assets/71872483/8a63b1c1-c18c-464f-a00c-1f63ce2233a5)

### Describe the behavior you expected

Setting a 0 value is supported.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.6.4

### In which browser are you experiencing the issue with?

Chrome 126.0.6478.62

### Which operating system are you using to run this browser?

Win10x64
