### ISSUE TITLE
grid card (with custom:button-card) wont scroll anymore 

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21237]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

running the 2024.7 beta cycle introduced this issue in my long standing configs, consisting of a core vertical-stack, with inside that stack a button-card for title and a modded grid card containing custom-button cards.

the issue is that the scrolling mod, and he max-height no longer were applied, see below yaml

b3 fixed his, as reported in the Discord channel

however, b5 re-introduced the issue 

( I am aware this is realized by card_mod, but, since the has not changed, it must be something that changed in the HA frontend.

### Describe the behavior you expected

respect the card_mod

(ofc, if the particular mod would no longer be vid, because of changed elements in the do path, Id be very happy to aplly another. Would appreciate a hint as to that new element in that case)

### Steps to reproduce the issue

1. create low card config
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.7.0b0, 2024.7.0b5

### What was the last working version of Home Assistant Core?

2024.7.0b3/4

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Sonoma 14.5

### Problem-relevant frontend configuration

```yaml
- type: custom:mod-card
    card_mod:
      style: |
        :host {
          max-height: 500px;
          overflow-y: scroll;
        }
    card:
      type: grid
      columns: 4
      cards:
```

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

**Comment by piitaya** [comment]
Can you provide a minimal config to reproduce the issue? Your config example is partial. 
Also, it was fixed in b3 but it the fix we used broke others thing so we reverted it. Since you’re using custom card, maybe you will need to adapt the code a little. It will check with a full config example.

**Comment by Mariusthvdb** [comment]
well, even though my buttons are in a vertical-stack, the minimal config is what I added above (ofc we need to add buttons there.....) 

As Ive tested, it is the grid card no longer getting modded, either inside a container card, or as standalone.

that is why I posted the minimal config above.

filled with some default buttons:
```
type: custom:mod-card
card_mod:
  style: |
    :host {
      max-height: 500px;
      overflow-y: scroll;
    }
card:

  type: grid
  columns: 4
  cards:

      - <<: &button
          type: custom:button-card
          entity: sensor.time
          aspect_ratio: 1
      - <<: *button
      - <<: *button
      - <<: *button

      - <<: *button
      - <<: *button
      - <<: *button
      - <<: *button

      - <<: *button
      - <<: *button
      - <<: *button
      - <<: *button

      - <<: *button
      - <<: *button
      - <<: *button
      - <<: *button

      - <<: *button
      - <<: *button
      - <<: *button
      - <<: *button

      - <<: *button
      - <<: *button
      - <<: *button
      - <<: *button

      - <<: *button
      - <<: *button
      - <<: *button
      - <<: *button

      - <<: *button
      - <<: *button
      - <<: *button
      - <<: *button

      - <<: *button
      - <<: *button
      - <<: *button
      - <<: *button
```

**Comment by piitaya** [comment]
```yaml
style: |
  :host {
    max-height: 500px;
    overflow-y: scroll;
    display: block;
  }
```
Adding `display: block;` should fix your issue.

**Comment by Mariusthvdb** [comment]
it does!
beautiful! thank you very much.

Can you explain why this now is required? what changed it from previous behavior?

**Comment by piitaya** [comment]
Before, the section, the view end the stack cards were responsible he load card (and custom card). It was many duplicate code. Now, we wrap all this logic into a `hui-card` component responsible of the load of the card to remove duplicated code. 
It breaks some custom cards because we added a new component in the DOM and some adjustment need to be done (mostly cards that inject custom css like custom button card or card mod).

**Comment by Mariusthvdb** [comment]
thanks , Ive pasted your explanation in the community topic for card-mod, as it is very important information. Ill close, as the issue is perfectly fixed.

**Comment by Mariusthvdb** [comment]
Paul, one followup question after all: is there any way at all we can unset the horizontal limit of a card?

asking because id love to be able to do a single line of button-cards, and then scroll horizontally.
cant find a way now, because both grid and horizontal-stack are limited by the max width of a column, and will compress anything wider..

hoping to do this
```
type: custom:mod-card
card_mod:
  style: |
    :host {
      overflow-x: scroll;    }
card:

  type: grid
  columns: 4
  row: 1
  cards:
```
