### ISSUE TITLE
Logbook card display/reloading issues in 2024.7b

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#21236]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

edit: updated issue with more findings after originally posting this, first three comments summarized here:

**Logbook card has several issues with reloading**:
1. If an unrelated Entity Filter card on the same view gets updated, it will cause Logbook card to reload
2. When entering dashboard Edit mode, it will cause Logbook card to reload. Pressing "Done" button to leave edit mode also causes a reload.
3. If browser width is changed to be more narrow, it will cause Logbook card to reload

--- 

The issue I reported with entity filter card before was fixed via https://github.com/home-assistant/frontend/pull/21218 but there appears to be another one. Anytime the Entity Filter card gets updated it messes with an unrelated Logbook card. Screen recording below, it shows the Logbook card displaying fine. As soon as Entity Filter card gets updated it causes hte Logbook card to reload and show progress indicator for excessively long time. Posted code below to reproduce.

https://github.com/home-assistant/frontend/assets/9065557/29d801cd-2057-4d3b-9f24-b4ad494d2b1d

### Describe the behavior you expected

Logbook card shouldn't change when an unrelated Entity Filter card changes

### Steps to reproduce the issue

1. Have a view with Entity Filter card and Logbook card
4. Make a change that causes Entity Filter card to update, it will then "break" the Logbook card

Here is code to easily reproduce, just change entity ID to a light of yours. And btw I put these two cards are inside a stack for bug reporting purposes only, the issue still occurs even if they're not in the same stack. 

```
type: vertical-stack
cards:
  - type: entity-filter
    entities:
      - light.office_main_lights
    state_filter:
      - 'on'
    card:
      type: glance
      title: Lights On
    show_empty: false
  - type: logbook
    entities:
      - light.office_main_lights
    hours_to_show: 24
    title: Light Activity
```

### What version of Home Assistant Core has the issue?

2024.7.0b5
