### ISSUE TITLE
Controls appear to connect to the wrong section

### ISSUE THREAD

**Issue by slungs** [home-assistant/frontend#21266]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In one column layout, the controlls for the card beneth seems to relate to the card above. Confusing!

![image](https://github.com/home-assistant/frontend/assets/58640347/9d7a822b-c8dd-48d0-b65f-78e976256e9c)

### What version of Home Assistant Core has the issue?

2024.7.0b4

### In which browser are you experiencing the issue with?

Chrome 122.0.6261.112

### Which operating system are you using to run this browser?

Win 10

### Problem-relevant frontend configuration

```yaml
views:
  - type: sections
    max_columns: 1
    title: Överblick
    path: overview
    sections:
      - type: grid
        cards:
          - type: map
            entities:
              - entity: person.
              - entity: person.
            default_zoom: 12
            theme_mode: dark
            layout_options:
              grid_columns: 4
              grid_rows: 3
          - type: tile
            entity: person.
            hide_state: false
            show_entity_picture: true
            vertical: false
            state_content:
              - state
              - last-changed
          - type: tile
            entity: person.
            show_entity_picture: true
            state_content:
              - state
              - last-changed
        title: Position
      - type: grid
        cards:
          - type: tile
            entity: light.kontor_group
            name: Kontor
          - type: tile
            entity: light.kontor_grupp
            name: kontor
          - type: tile
            entity: light.sovrum_golvlampa
            name: Sovrum
          - type: tile
            entity: light.vardagsrum_group
            name: Vardagsrum
          - type: tile
            entity: light.hall_group
            name: Hall
          - type: tile
            entity: light.kok_z2m_group
            name: Kök
          - type: tile
            entity: switch.uterum_ikea_ljusslinga
            name: Uterum
          - type: tile
            entity: light.innergard_vagglampa
            name: Entré
        title: Rum
      - type: grid
        cards:
          - type: tile
            entity: binary_sensor.vardagsrum_hue_motion_occupancy
            state_content: last-changed
            name: Kök
          - type: tile
            entity: binary_sensor.vardagsrum_hue_motion_occupancy
            state_content: last-changed
            icon: mdi:motion-sensor-off
            name: Vardagsrum
          - type: tile
            entity: binary_sensor.trapphus_ikea_motion_occupancy
            name: Övervåning
            state_content: last-changed
          - type: tile
            entity: binary_sensor.trapphus_hue_motion_occupancy
            state_content: last-changed
            icon: mdi:motion-sensor-off
            name: Trapphus
          - type: tile
            entity: binary_sensor.kontor_hue_motion_occupancy
            state_content: last-changed
            icon: mdi:motion-sensor-off
            name: Antons kontor
          - type: tile
            entity: binary_sensor.innergard_hue_motion_occupancy
            state_content: last-changed
            name: Innergård
        title: Rörelse
      - type: grid
        cards:
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: camera.entrance_frigate
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            name: Entre
            layout_options:
              grid_columns: 2
              grid_rows: 2
          - show_state: false
            show_name: false
            camera_view: auto
            type: picture-entity
            entity: camera.garden_frigate
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            name: Garden
            aspect_ratio: '16:9'
            layout_options:
              grid_columns: 2
              grid_rows: 2
        title: Kameror
      - type: grid
        cards: []
        title: '     '
      - type: grid
        cards:
          - type: custom:mushroom-vacuum-card
            entity: vacuum.roborock_s6_pure
            icon_animation: true
            fill_container: false
            commands:
              - start_pause
              - return_home
            layout: horizontal
            layout_options:
              grid_columns: 4
              grid_rows: 1
          - type: tile
            entity: vacuum.roborock_s6_pure
          - type: tile
            entity: script.clean_kitchen
            hide_state: true
            name: Städa köket
        title: Dammsugare
      - type: grid
        cards:
          - type: tile
            entity: sensor.temperatur_hus_average
            name: Hus Genomsnitt
            icon: fas:temperature-quarter
            color: accent
          - type: tile
            entity: sensor.utetemperatur
            icon: mdi:sun-thermometer
          - type: tile
            entity: sensor.uterum_termometer_temperature
            name: Uterum
            layout_options:
              grid_columns: 2
              grid_rows: 1
            vertical: false
          - type: tile
            entity: sensor.sovrum_rullgardin_device_temperature
            name: Sovrum
          - type: tile
            entity: sensor.kontor_hue_motion_temperature
            name:  kontor
          - type: tile
            entity: sensor.vardagsrum_hue_motion_temperature
            name: Vardagsrum
    cards: []
    background:
      image: >-
        https://images.unsplash.com/photo-1644286625023-446a2347e6ae?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
```
