### ISSUE TITLE
Sections view: Inconsistent tile card sizes in Cloud vs. Local

### ISSUE THREAD

**Issue by PascalHaury** [home-assistant/frontend#21276]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When accessing the dashbord via Nabucasa the tile card in the sections view has different minimal sizes then in the local version. 

At home with local access i can set the tile card to 1x1 and it is shown as 1x1
In the Nabucasa Cloud dashboard the cards are set to minimal 2x1 (Screenshot 3) or 2x2 (Screenshot 1) if vertical is enabled, even though the configuration still is set to 1x1

When i try to edit the card via the cloud dashboard, i cant even set the size below the above minimum size values. (See Screenshot 2)

### Describe the behavior you expected

Both Dashboards should have the same minimal size for cards.
On cloud ui I should be able to also resize the tile cards to 1x1.
On cloud ui the cards should be the same size as when i access ha locally.

### Steps to reproduce the issue

1. Create local dashboard using Direct Access with the IP
2. Enable Sections dashboard style 
3. Add a Section and add a tile card in it
4. Set the size of the tile card to 1x1
5. (optional) set mode to vertical
6. Access the dashboard via nabu casa cloud 
7. The card is now displayed via cloud with a size of 2x1 or 2x2 if vertical was enabled

Note: Due to current restrictions by my ISP i cannot test if the bug also occurs if i access my instance via reverse Proxy and my domain

### What version of Home Assistant Core has the issue?

2024.7.0

### What was the last working version of Home Assistant Core?

2024.7.0b6

### In which browser are you experiencing the issue with?

Google Chrome 126.0.6478.127, Microsoft Edge 126.0.2592.81, Firefox 127.0.2

### Which operating system are you using to run this browser?

Windows 10, Windows 11

### State of relevant entities

```txt
----
```

### Problem-relevant frontend configuration

```yaml
#Complete section with only 1x1 Cards:
type: grid
cards:
  - type: tile
    entity: switch.computer
    vertical: true
    layout_options:
      grid_columns: 1
      grid_rows: 1
    name: " "
    icon: mdi:desktop-tower-monitor
    hide_state: true
  - type: tile
    entity: switch.monitore
    visibility:
      - condition: state
        entity: switch.computer
        state: "on"
    layout_options:
      grid_columns: 1
      grid_rows: 1
    vertical: true
    hide_state: true
    name: " "
  - type: tile
    entity: switch.schreibtisch_licht
    layout_options:
      grid_columns: 1
      grid_rows: 1
    vertical: true
    icon: phu:desk-sit-alt
    name: " "
    hide_state: true
  - type: tile
    entity: light.computer_licht
    vertical: true
    layout_options:
      grid_columns: 1
      grid_rows: 1
    hide_state: true
    show_entity_picture: false
    name: " "
  - type: tile
    entity: switch.sim_rig
    vertical: true
    visibility:
      - condition: state
        entity: switch.computer
        state: "on"
    layout_options:
      grid_columns: 1
      grid_rows: 1
    name: " "
    icon: mdi:steering
    hide_state: true
  - type: tile
    entity: switch.computer_lautsprecher
    visibility:
      - condition: state
        entity: switch.computer
        state: "on"
    layout_options:
      grid_columns: 1
      grid_rows: 1
    vertical: true
    icon: mdi:fan
    name: " "
    hide_state: true
  - type: tile
    entity: switch.sim_rig_monitore_2
    visibility:
      - condition: state
        entity: switch.sim_rig
        state: "on"
    layout_options:
      grid_columns: 1
      grid_rows: 1
    vertical: true
    name: " "
    hide_state: true
  - type: tile
    entity: switch.simrig_fernseher
    name: " "
    visibility:
      - condition: state
        entity: switch.sim_rig
        state: "on"
    vertical: true
    layout_options:
      grid_columns: 1
      grid_rows: 1
    hide_state: true
title: Computer
```

### Javascript errors shown in your browser console/inspector

```txt
----
```

### Additional information

Screenshot 1
![image](https://github.com/home-assistant/frontend/assets/32424321/24bb8b38-2692-48cb-816d-97c46e137976)

Screenshot 2
![image](https://github.com/home-assistant/frontend/assets/32424321/d2b2ec98-6093-4094-b786-149f96fd2c8b)

Screenshot 3
![image](https://github.com/home-assistant/frontend/assets/32424321/91c4bc13-71df-4c38-b003-aa4d014e7090)
![image](https://github.com/home-assistant/frontend/assets/32424321/12b11840-d04b-4592-a92d-aa0aa3995698)
