### ISSUE TITLE
Card visibility breaks with template condition

### ISSUE THREAD

**Issue by johanneswuerbach** [home-assistant/frontend#21287]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm trying to conditionally display a card when the last input date time has surpassed a certain age and while the dashboard is occasionally working, a lot of the times the entire dashboard remains empty and a js error is logged in the console.

### Describe the behavior you expected

Card rendering depending on the input condition.

### Steps to reproduce the issue

Use a template inside a visibility condition.

### What version of Home Assistant Core has the issue?

2024.7.0

### In which browser are you experiencing the issue with?

Chrome 126.0.6478.127

### Which operating system are you using to run this browser?

macOS Sonoma 14.5

### State of relevant entities

```txt
# input_datetime.bad_hinten_luftung_reinigung
has_date: true
has_time: false
editable: true
year: 2024
month: 7
day: 4
timestamp: 1720044000
icon: mdi:vacuum-outline
friendly_name: Bad hinten Lüftung Reinigung
```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: input_datetime.bad_hinten_luftung_reinigung
title: Letzte Badlüfter Reinigung
visibility:
  - condition: template
    value_template: >
      {% set dt = states('input_datetime.bad_hinten_luftung_reinigung')
        | as_datetime | as_local %}
      {{ (dt.date() - now().date()).days | abs < 60 }}
```

### Javascript errors shown in your browser console/inspector

`Cannot read properties of undefined (reading 'includes')`

<img width="919" alt="image" src="https://github.com/home-assistant/frontend/assets/864578/c7bfdf3a-c4dc-4277-a8fa-1923fd071c3a">

<img width="481" alt="image" src="https://github.com/home-assistant/frontend/assets/864578/4d42961d-c4ff-4106-aa73-6a1a0d3713a2">
