### ISSUE TITLE
Difference row height with and without horizontal-stack

### ISSUE THREAD

**Issue by Revilo91** [home-assistant/frontend#21283]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the update 20240702.0 (#21244), the entities cards are displayed larger than in a horizontal stack. In the source code you can find the following:
```
public getLayoutOptions(): LovelaceLayoutOptions {
    return {
      grid_columns: 2,
      grid_rows: 2,
      grid_min_columns: 2,
      grid_min_rows: 2,
    };
  }
```
Does this grid_min_rows: 2 have an important meaning or could you set it back to 1? Because you can see that it looks good even at a reduced height.

![image](https://github.com/home-assistant/frontend/assets/39066472/81b2459b-a325-482f-a816-8f4671fa9b1c)

### Describe the behavior you expected

Should looks like the left side of this image:

![image](https://github.com/home-assistant/frontend/assets/39066472/81b2459b-a325-482f-a816-8f4671fa9b1c)

### Steps to reproduce the issue

Code to check:

```
type: sections
max_columns: 4
title: Test2
path: test2
sections:
  - cards:
      - type: horizontal-stack
        cards:
          - type: entity
            entity: sensor.ebusd_pms_yieldcurrentday_energy
            state_color: true
          - type: entity
            entity: sensor.ebusd_pms_yieldtotal_energy4
            state_color: true
    title: Solarthermie
  - cards:
      - type: entity
        entity: sensor.ebusd_pms_yieldcurrentday_energy
        state_color: true
      - type: entity
        entity: sensor.ebusd_pms_yieldtotal_energy4
        state_color: true
    title: Solarthermie
cards: []

```

### What version of Home Assistant Core has the issue?

core-2024.7.0b9

### What was the last working version of Home Assistant Core?

core-2024.7.0b8

### In which browser are you experiencing the issue with?

Google Chrome Version 126.0.6478.127 (64-Bit)

### Which operating system are you using to run this browser?

Windows 10 / 11
