### ISSUE TITLE
Allow us to use css variables to specify card size (again)

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#21309]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After 2024.7.0 both `grid_rows:` and `grid_columns:` card config properties (on any card) only accepts numeric values.
It would be nice to use a (string) css variable instead.

### Describe the behavior you expected

Specifying `grid_rows:` or `grid_columns:` as string is a valid possibility.

### Steps to reproduce the issue

1. Add any card
2. define `layout_options > grid_rows` and `grid_columns` as string

### What version of Home Assistant Core has the issue?

core-2024.7.0

### What was the last working version of Home Assistant Core?

core-2024.6.4

### In which browser are you experiencing the issue with?

any (Firefox 127.0.2, Companion App 2024.6.5)

### Which operating system are you using to run this browser?

any (teseted on Windows 10, Android 11)

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
type: area
area: living_room
navigation_path: /by-area/living_room
layout_options:
  grid_columns: var(--area-card-column-size,4)
  grid_rows: var(--area-card-row-size,3)
```

### Additional information

Useful e.g. for dynamic layouts where size is shrinked on mobile screens
