### ISSUE TITLE
Sensor card is squashed

### ISSUE THREAD

**Issue by bbs2web** [home-assistant/frontend#21317]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Sensor cards are now half the height they were before, don't like the text superimposed the way it is now.

https://www.home-assistant.io/dashboards/sensor/

What it looks like now:
![image](https://github.com/home-assistant/frontend/assets/1456100/22da1051-b7c4-4080-8b65-3a767cf375c7)

in safe mode:
![image](https://github.com/home-assistant/frontend/assets/1456100/81b2d561-74d7-46a6-8066-6c76933cf88d)

### Describe the behavior you expected

Restore original size of sensor cards in dashboards

### Steps to reproduce the issue

Upgrade to 2024.07.1, then force refresh the UI

### What version of Home Assistant Core has the issue?

2024.7.1

### What was the last working version of Home Assistant Core?

2024.7.0

### In which browser are you experiencing the issue with?

Google Chrome 126.0.6478.127

### Which operating system are you using to run this browser?

Microsoft Windows 11 Enterprise 23H2 (build 22631.3810)

### Problem-relevant frontend configuration

```yaml
Dashboard:
type: vertical-stack
cards:
  - graph: line
    type: sensor
    detail: 2
    entity: sensor.pv_power
    name: Solar
    hours_to_show: 48
```

**Comment by a1ex-ak** [comment]
![Снимок экрана от 2024-07-06 12-09-21](https://github.com/home-assistant/frontend/assets/121604147/7906fbb5-af7f-411f-a050-6b4d00e09257)

**Comment by Blacksli** [comment]
2024.7.0

![IMG_20240706_141510_996](https://github.com/home-assistant/frontend/assets/74769766/43e0b7d8-c76b-4862-b1d6-1225da3e1f29)

2024.7.1
![IMG_20240706_141501_630](https://github.com/home-assistant/frontend/assets/74769766/fb5cb5f4-80c6-40b4-b387-e693e9c87dbc)

**Comment by bbs2web** [comment]
I'm using a vertical-stack card, the following doesn't appear to have any affect:
```
    layout_options:
      grid_columns: 1
      grid_rows: 4
```

Couldn't get a 'before' image, the post by Blacksli demonstrates the problem though:
[[Blacksli](https://github.com/Blacksli)](https://github.com/home-assistant/frontend/issues/21317#issuecomment-2211716549)

**Comment by piitaya** [comment]
Fixed with https://github.com/home-assistant/frontend/issues/21313. It will be fixed in 2024.7.2 release.

**Comment by bbs2web** [comment]
Thank you https://github.com/piitaya. Got it tweaked to my linking using a sections view, where I could then specify the columns and rows:
```
  - icon: mdi:home-lightning-bolt
    title: Garage
    path: garage
    type: sections
    max_columns: 1
    sections:
      - type: grid
        cards:
          - graph: line
            type: sensor
            detail: 2
            entity: sensor.inverter_pv_power
            name: Solar
            hours_to_show: 48
            layout_options:
              grid_columns: 4
              grid_rows: 3
```
