### ISSUE TITLE
Thermostat card `top` fan speed is missing icon

### ISSUE THREAD

**Issue by danoc** [home-assistant/frontend#21329]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello! HA Core supports four fan speeds: `LOW`, `MEDIUM`, `HIGH`, and `TOP`, a newer speed added in https://github.com/home-assistant/core/pull/51969.

The thermostat card seems to not support a `TOP` icon.

<img width="274" alt="Screenshot showing `Top` speed without an icon" src="https://github.com/home-assistant/frontend/assets/916038/f5c2b17e-124f-45a7-8257-009d1737ff46">

This is my YAML config for the card:

```yaml
type: thermostat
entity: climate.<removed>
features:
  - type: climate-hvac-modes
    hvac_modes:
      - 'off'
      - cool
      - fan_only
  - style: dropdown
    type: climate-fan-modes
show_current_as_primary: true
name: A/C
```

Is the issue that this code only supports 3 speeds?

https://github.com/home-assistant/frontend/blob/aa49d6ef6b94853ccc49de6b52333cc9fa3f508b/src/data/fan.ts#L81-L94

### Describe the behavior you expected

I'd expect all of the icons to appear.

### Steps to reproduce the issue

1. Create a climate custom component that supports `FAN_TOP` from `homeassistant.components.climate.const`
2. Create a thermostat card in the dashboard
3. Notice that the icon doesn't appear for `FAN_TOP` but it does for the others.

### What version of Home Assistant Core has the issue?

core-2024.7.0

### In which browser are you experiencing the issue with?

Safari 17.5

### Which operating system are you using to run this browser?

macOS 14.5
