### ISSUE TITLE
Conditional card: if an entity is "unknown" - it is treated as "unavailable" (same about visibility)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21381]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

A non-existing entity has `unknown` state:
![image](https://github.com/user-attachments/assets/d7f70de4-7160-4984-b95c-0867981beda4)

Consider this code:
```
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - condition: state
        entity: sun.su
        state: unavailable
    card:
      type: entity
      entity: sun.sun
  - type: conditional
    conditions:
      - condition: state
        entity: sun.su
        state_not: unavailable
    card:
      type: entity
      entity: zone.home
```
which shows this card:
![image](https://github.com/user-attachments/assets/9483610e-ddf1-4e81-96e8-2b6f55b7d951)

But the state is not `unavailable` - it is `unknown`.
Then why the 1st condition is `true`?

### Describe the behavior you expected

`unknown` should not be treated as `unavailable`

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.7.1

### In which browser are you experiencing the issue with?

Chrome 126.0.6478.127

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
And compare with visibility options where `unavailable` & `unknown` are different cases:
```
type: entity
entity: sun.sun
visibility:
  - condition: state
    entity: sun.su
    state: unavailable
```
![image](https://github.com/user-attachments/assets/4262af46-0fef-45b3-9658-8996b9465e95)
