### ISSUE TITLE
Conditional Card only visible card in dashboard

### ISSUE THREAD

**Issue by akuehner** [home-assistant/frontend#21402]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I've only experienced since the update that allows for conditional cards to be visible only to certain users. 
I have a card in my primary dashboard that is only visible to myself. When I login to the mobile Android app on my Pixel 8 Pro (up to date) oftentimes I see ONLY that conditional card. If I navigate elsewhere in Home Assistant, like settings, when I then go back to my dashboard the full dashboard will again be visible.

### Describe the behavior you expected

I except all the "regular" cards to show up in the dashboard view.

### Steps to reproduce the issue

1. Setup a dashboard, with mostly always visible card
2. Add a single conditionally visible card that is only visible to 1 user
3. Set that dashboard as default so it's the first thing that opens
4. Open Home Assistant on mobile Android device
5. Only the conditional dashboard is visible, navigate to settings or a different HA screen
6. Navigate back to the dashboard, now all the cards show
...

### What version of Home Assistant Core has the issue?

2024.7.2

### In which browser are you experiencing the issue with?

io.homeassistant.companion.android 2024.6.1-full

### Which operating system are you using to run this browser?

Android 14

### Problem-relevant frontend configuration

```yaml
type: conditional
conditions:
  - condition: user
    users:
      - [uid]
card:
  type: vertical-stack
  title: R1T
  cards:
    - type: conditional
      conditions:
        - entity: input_boolean.rivian_drawer
          state: 'off'
```

### Additional information

I have not yet dug deeper, I do also have a condition on the cards in the vertical stack, controlled by the user visibility conditonal card.
