### ISSUE TITLE
navigate works only if user has admin rights

### ISSUE THREAD

**Issue by phg2020** [home-assistant/frontend#21445]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The navigation works only if user has admin rights 
Example:
type: tile
entity: input_button.taste_kuche
icon: mdi:countertop-outline
color: lime
tap_action:
  action: navigate
  navigation_path: /dashboard-test/kueche
show_entity_picture: false
vertical: false
layout_options:
  grid_columns: 2
  grid_rows: 1
hide_state: true
name: Küche

### Describe the behavior you expected

when user push the button it should switch to another page For non Admins it do not work.

### Steps to reproduce the issue

1.push the button with admin user, it works
2.push the button with non admin it do not work

### What version of Home Assistant Core has the issue?

Core 2024.7.3

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

OS 15.4

### State of relevant entities

```txt
I test the OS App and Safari browser
```

### Problem-relevant frontend configuration

```yaml
type: tile
entity: input_button.taste_kuche
icon: mdi:countertop-outline
color: lime
tap_action:
  action: navigate
  navigation_path: /dashboard-test/kueche
show_entity_picture: false
vertical: false
layout_options:
  grid_columns: 2
  grid_rows: 1
hide_state: true
name: Küche
```
