### ISSUE TITLE
Logbook: "triggered by" changes after F5 to a wrong reason

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21464]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Consider a template binary sensor:
```
template:
  - binary_sensor:
      - name: testing_sensor
        state: >-
          {{ states('input_boolean.test_boolean') }}
```
Open Logbook for this sensor in some browser's tab.
In another tab open Settings -> Entities, find a source `input_boolean.test_boolean` entity & open a more-onfo window:

![изображение](https://github.com/user-attachments/assets/3b06995f-439c-44e7-a310-8bef1af1614c)

Then start turning the helper ON/OFF.
Switch to the Logbook tab - it shows a correct reason "triggered by service input_boolean.turn_on/off":

![изображение](https://github.com/user-attachments/assets/8b4c0783-f2f2-49e3-9925-a0abaed8f4aa)

Press F5 / reload the page.
Now the reason becomes "triggered by state of testing_switch turned on/off":

![изображение](https://github.com/user-attachments/assets/40fc44f5-e1e5-4280-9fba-5748bef1b7a2)

This `switch.testing_switch` is just another test entity which was not directly involved:
```
switch:
  - platform: template
    switches:

      testing_switch:
        icon_template: >-
          {% if is_state(this.entity_id,'on') -%}
            mdi:radiobox-marked
          {%- else -%}
            mdi:radiobox-blank
          {%- endif %}

        value_template: >-
          {{ is_state('input_boolean.test_boolean', 'on') }}

        turn_on:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.test_boolean

        turn_off:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.test_boolean
```

### Describe the behavior you expected

A reason should be correct ("triggered by service input_boolean.turn_on/off") even after F5.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2024.7.1

### In which browser are you experiencing the issue with?

Chrome 126.0.6478.127 

### Which operating system are you using to run this browser?

Win10x64
