### ISSUE TITLE
"duration" sensors may be shown differently on the same Entities card

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21478]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Sensor 1 - `history_stats`:
```
sensor:
  - platform: history_stats
    name: "day vs night (ratio)"
    entity_id: sun.sun
    state:
      - "above_horizon"
      - "below_horizon"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
```
Sensors 2, 3 - `template`:
```
template:
  - sensor:
      - name: testing_device_class_duration_seconds
        device_class: duration
        unit_of_measurement: "s"
        state: >-
          {% set INPUT_NAME = "input_number.testing_device_class_duration_seconds" -%}
          {{ states(INPUT_NAME) }}

      - name: testing_device_class_duration_hours
        device_class: duration
        unit_of_measurement: "h"
        state: >-
          {% set INPUT_NAME = "input_number.testing_device_class_duration_seconds" -%}
          {{ states(INPUT_NAME)|int(default=0)/60/60 }}
```
All sensors have `device_class: duration`:
![изображение](https://github.com/user-attachments/assets/f6721ed7-bb49-4acb-8977-6e5d1a5fd2bd)

And these sensors are displayed on Entities card differently:
UoM for `history_stats` sensor = hour:
![изображение](https://github.com/user-attachments/assets/6e72ccd7-ee74-44ba-8dd1-76ea0d19002f)
UoM for `history_stats` sensor = sec:
![изображение](https://github.com/user-attachments/assets/830aa3df-7752-4098-8c19-283e21fbdc33)

### Describe the behavior you expected

Duration sensor should be as a duration....

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2024.7.3

### In which browser are you experiencing the issue with?

Chrome 126.0.6478.127

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
Can you fix your sensor 1 to the actual sensor in question. I think you copy/pasted a ratio sensor instead of a time sensor. 

When I make a time sensor history stats, it displays appropriately as hh:mm:ss duration.

The only way I know to make an entity display as not hh:mm:ss is to assign a display precision, but that requires a unique_id and the entity registry, which doesn't seem to be a factor here.

**Comment by ildar170975** [comment]
> Can you fix your sensor 1 to the actual sensor in question. I think you copy/pasted a ratio sensor instead of a time sensor.

Thanks a lot! Wrong copy-paste.

**Comment by ildar170975** [comment]
@karwosts 

Here is my test.
Create in yaml 2 sensors:
```
sensor:
  - platform: history_stats
    name: "day vs night (time) (test)"
    <<: &ref_settings
      entity_id: sun.sun
      state:
        - "above_horizon"
        - "below_horizon"
      type: time
      start: "{{ now().replace(hour=0, minute=0, second=0) }}"
      end: "{{ now() }}"

  - platform: history_stats
    name: "day vs night (time) (test with uuid)"
    unique_id: 987cb65a-09f3-424c-947a-0080f5cde30f
    <<: *ref_settings
```
Here we defined 2 similar sensors - but the 2ns one has a ` unique_id`.

The 1st sensor (w/o `unique_id`) is shown as
![image](https://github.com/user-attachments/assets/f37bfd78-b8ad-489b-8339-0064e06c50be)

The 2nd sensor (with `unique_id`) is shown as
![image](https://github.com/user-attachments/assets/59e55476-10d7-4baf-8ba0-f674aa8113c1)
and this is a default presentation (I did not touch settings in more-info).
