### ISSUE TITLE
Tile Card contents are misaligned with each other

### ISSUE THREAD

**Issue by andrewfluck** [home-assistant/frontend#21516]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

As of Home Assistant 2024.8b0, the tile card contents are visually misaligned with each other. The new grid also looks like it messes with some of the tile cards cards, too.

<img width="943" alt="Screenshot 2024-07-31 at 21 08 56" src="https://github.com/user-attachments/assets/5998ffe2-78c1-49a6-aab5-a60aeaa78601">

### Describe the behavior you expected

The tile card primary contents should be lined up with each other, and not centered within the the card itself, or at least, the primary contents containing title, state, and icon should be constrained to 1 grid unit of height.

### Steps to reproduce the issue

1. Place a 2 tile cards on the dashboard
2. Resize one of them to use 2 grid units

Also:
1. Place two tile cards on the dashboardd
2. With one of the tile cards, assuming it supports multiple feature sections, add two features, and compare it to the title card using 1 grid unit of height.
...

### What version of Home Assistant Core has the issue?

2024.8.0b0

### What was the last working version of Home Assistant Core?

2024.7.4

### Problem-relevant frontend configuration

```yaml
views:
  - icon: mdi:sofa
    title: Living Room
    path: living-room
    type: sections
    sections:
      - type: grid
        cards:
          - type: tile
            entity: switch.living_room_tv
        title: Active Devices
        visibility:
          - condition: state
            entity: switch.living_room_tv
            state: 'on'
      - type: grid
        cards:
          - type: thermostat
            entity: climate.hallway_thermostat
            name: Thermostat
            show_current_as_primary: false
            features:
              - type: climate-hvac-modes
            layout_options:
              grid_columns: 2
              grid_rows: 4
          - graph: line
            type: sensor
            entity: sensor.hallway_thermostat_temperature
            detail: 1
            name: Temperature
          - graph: line
            type: sensor
            entity: sensor.hallway_thermostat_humidity
            detail: 1
            name: Humidity
          - type: tile
            entity: fan.smart_heater
            name: Smart Heater Flow
            icon: mdi:air-filter
            layout_options:
              grid_columns: 2
              grid_rows: 2
          - features:
              - type: climate-hvac-modes
            type: tile
            entity: climate.smart_heater
            icon: mdi:heat-wave
        title: Climate
      - type: grid
        cards:
          - type: tile
            entity: light.living_room_ceiling_fan_lights_zigbee_groups
            name: Ceiling Fan Light
            layout_options:
              grid_columns: 2
              grid_rows: 2
            features:
              - type: light-brightness
          - type: tile
            entity: fan.living_room_ceiling_fan_speed
            name: Ceiling Fan Speed
            features:
              - type: fan-speed
          - features:
              - type: cover-position
              - type: cover-open-close
            type: tile
            entity: cover.living_room_blinds
            name: Shades
        title: Lighting
      - type: grid
        cards:
          - type: tile
            entity: switch.living_room_tv
            layout_options:
              grid_columns: 2
              grid_rows: 1
          - type: media-control
            entity: media_player.living_room_display
            layout_options:
              grid_columns: 2
              grid_rows: auto
        title: Media
    badges:
      - type: entity
        entity: switch.living_room_tv
        visibility:
          - condition: state
            entity: switch.living_room_tv
            state: 'on'
```
