### ISSUE TITLE
Entity Badge configuration perform action doesn't save settings

### ISSUE THREAD

**Issue by casakampa** [home-assistant/frontend#21534]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When setting the tap behaviour of an entity badge in core-2024.8.0b0, in the UI the settings can be configured. Then, after switching to the code-editor, the settings from the UI are not visible in the YAML. When switching back to the UI, the settings are shown. When saving the entity badge configuration, no settings are saved.

### Describe the behavior you expected

When selecting _Perform Action_ as tap behaviour on an entity badge, the expectation is that I can select the action with the right UI appearing, so that it's possible to select the correct entity.

### Steps to reproduce the issue

1. Select an entity, for example _timer.zha_join_60s_
![image](https://github.com/user-attachments/assets/510bf85a-cf63-47b4-8b2b-a6b37856d8fd)

2. Set the tap behaviour action to _timer.start_
![image](https://github.com/user-attachments/assets/3bdf65f0-0de6-4a9f-9b8e-f7a17be89a8e)

3. Switch to the code editor:
```yaml
type: entity
tap_action:
  action: perform-action
  perform_action: ''
  target: {}
entity: timer.zha_join_60s
```
4. Switch back to the visual editor
![image](https://github.com/user-attachments/assets/bf110fa4-740b-4894-b9b7-1ed0afb2e722)

5. Save the entity badge
6. Click on the entity badge to perform the action previously configured:
![image](https://github.com/user-attachments/assets/be5f15d8-1847-4127-924b-ff527ddbacca)
7. Edit the entity badge and open the Interactions section:
![image](https://github.com/user-attachments/assets/2784c540-e4b5-4ff9-ae36-d1d2c1326d14)
and
```yaml
type: entity
tap_action:
  action: perform-action
  perform_action: ''
  target: {}
entity: timer.zha_join_60s
```
8. When changing _perform_action: ''_ to _perform_action: timer.start_ in the code-editor, the UI changes and an entity can be selected:
![image](https://github.com/user-attachments/assets/29073985-e5e3-4add-a4e7-9536ec8c1cbc)
9. When selecting the same entity again, the interactions is emptied again:
![image](https://github.com/user-attachments/assets/2dee262b-80a2-4c34-b985-36705e797a34)
and
```yaml
type: entity
tap_action:
  action: perform-action
  perform_action: ''
  target:
    entity_id: timer.zha_join_60s
  data: {}
entity: timer.zha_join_60s
```
10. When changing _perform_action: ''_ again to _perform_action: timer.start_ and then saving the entity badge, the timer can be started.
![image](https://github.com/user-attachments/assets/2acdcf49-0e04-47eb-accc-720d9c2119e6)
11. When editing the entity badge, all settings are present:
![image](https://github.com/user-attachments/assets/a35253fa-d65f-4795-a42a-436d727c7452)
and
```yaml
type: entity
tap_action:
  action: perform-action
  perform_action: timer.start
  target:
    entity_id: timer.zha_join_60s
  data: {}
entity: timer.zha_join_60s
```

### What version of Home Assistant Core has the issue?

core-2024.8.0b0

### In which browser are you experiencing the issue with?

Microsoft Edge 127.0.2651.74

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

This was also tested in Mozilla Firefox 128.0.3 x64
