### ISSUE TITLE
Times of the Day integration not visible in the UI

### ISSUE THREAD

**Issue by philipp-frank** [home-assistant/frontend#21578]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The Times of the Day integration does not show up on the integration page in the UI. The integraion is set up manually via YAML.

### Describe the behavior you expected

The Times of the Day integration, regardless of how it is set up, should be visible in the integrations page in the UI.

### Steps to reproduce the issue

1. Setup the Times of the Day integration via YAML (see below)
2. Go to the integrations page in the UI

### What version of Home Assistant Core has the issue?

2024.8.0b1

### Problem-relevant frontend configuration

```yaml
binary_sensor:
  - platform: tod
    name: tod
    after: sunrise
    after_offset: "01:30:00"
    before: sunset
    before_offset: "-00:30:00"
```
