### ISSUE TITLE
Sometimes First (Left) Section missing

### ISSUE THREAD

**Issue by MickLesk** [home-assistant/frontend#21605]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Sometimes it happens when I call up my Home Assistant via the URL and get to the standard dashboard that the first section (left) is not displayed. F5 (Refresh) is not enough. I have to reload the page with CTRL Shift R or refresh with the pen (edit) from the dashboard. (Here it is sufficient to just click on the pencil, then the dashboard is displayed correctly).

The error has been around since 2024.5 or 2024.6, but I have not been able to identify why it occurs.

Here yaml of left section:

```yaml
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Personen
    title_tap_action:
      action: none
  - type: entities
    entities:
      - entity: person.*****
        name: *****
      - entity: person.*****
        name: *****
    state_color: true
  - type: custom:mushroom-title-card
    title: Stromverbrauch
    title_tap_action:
      action: none
  - type: custom:power-flow-card-plus
    entities:
      battery:
        state_of_charge_unit_white_space: true
        entity:
          '0': '['
          '1': o
          '2': b
          '3': j
          '4': e
          '5': c
          '6': t
          '7': ' '
          '8': O
          '9': b
          '10': j
          '11': e
          '12': c
          '13': t
          '14': ']'
          consumption: sensor.senec_battery_discharge_power
          production: sensor.senec_battery_charge_power
        icon: mdi:home-battery
        name: Stromspeicher
        color_icon: true
        color_circle: true
        display_zero_tolerance: 0
        state_of_charge: sensor.senec_battery_charge_percent
      grid:
        entity: sensor.stromzahler
        color_value: false
        color_icon: true
        color_circle: true
      solar:
        entity: sensor.senec_solar_generated_power
        display_zero_state: true
        color_value: true
        color_icon: true
        icon: mdi:solar-power-variant
        color:
          - 241
          - 233
          - 9
      home:
        entity: sensor.stromzahler
        icon: mdi:home-analytics
        subtract_individual: false
    clickable_entities: true
    display_zero_lines:
      mode: show
      transparency: 50
      grey_color:
        - 189
        - 189
        - 189
    use_new_flow_rate_model: true
    w_decimals: 0
    kw_decimals: 1
    min_flow_rate: 0.75
    max_flow_rate: 6
    max_expected_power: 2000
    min_expected_power: 0.01
    watt_threshold: 1000
    transparency_zero_lines: 0
  - type: gauge
    entity: sensor.stromzahler
    needle: true
    max: 3500
    min: 1
    unit: W
    name: Sromverbrauch
```

Here - Missing Left Section:
<img width="1510" alt="2024-08-06_15-41" src="https://github.com/user-attachments/assets/1ea3529a-0b9f-4e09-b3d1-64e4040ed00f">

Here - After STRG(CTRL) Shift R: 

<img width="1297" alt="2024-08-06_15-59" src="https://github.com/user-attachments/assets/ff116d07-9469-41e9-beb4-f1fec1f4d8dd">

### Describe the behavior you expected

The dashboard should be displayed completely. 

### Steps to reproduce the issue

1. Open URL of HomeAssistant
2. First Dashboard Loading, Left Section Missing

### What version of Home Assistant Core has the issue?

2024.8.0b4

### What was the last working version of Home Assistant Core?

2024.5

### In which browser are you experiencing the issue with?

127.0.6533.89 

### Which operating system are you using to run this browser?

Windows 11 / Ubuntu 24.04

### Problem-relevant frontend configuration

```yaml
card-mod.js?hacstag=190927524343:1 CARD-MOD 3.4.3 IS INSTALLED
browser_mod.js:385 BROWSER_MOD 2.3.1 IS INSTALLED    BrowserID: f063a085-87c2efbc
purifier-card.js?hacstag=274738925262:4  PURIFIER-CARD  2.6.1 
rain-gauge-card.js?hacstag=609593305140:77   RAIN-GAUGE-CARD   Version 1.4.0    
landroid-card.js?hacstag=510045489111:1  LANDROID-CARD  1.1.1
expander-card.js?hacstag=677140532164:1   Expander-Card  Version 1.6.4
hass-hue-icons.js?hacstag=3844345221253:2074  HASS-HUE-ICONS  Version 1.2.53 
config-template-card.js?hacstag=172177543136:329 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ config-template-card.js?hacstag=172177543136:329
config-template-card.js?hacstag=172177543136:735   CONFIG-TEMPLATE-CARD    Version 1.3.6         
mushroom.js?hacstag=444350375363:3400 🍄 Mushroom 🍄 - 4.0.1
bar-card.js?hacstag=163363577320:4855   BAR-CARD   Version 3.1.7    
swipe-navigation.js?hacstag=5017254791140:1 ↔️ Swipe navigation ↔️ - v1.14.0
mini-graph-card-bundle.js?hacstag=1512800620121:1  MINI-GRAPH-CARD  0.12.1 
hourly-weather.js?hacstag=499270202602:283   HOURLY-WEATHER-CARD   Version 6.0.2    
weather-radar-card.js?hacstag=487680971210:1291   WEATHER-RADAR-CARD   Version 2.1.0    
vertical-stack-in-card.js?hacstag=142051833044:1 vertical-stack-in-cardVersion: 0.4.4
slider-entity-row.js?hacstag=1448997001741:1 SLIDER-ENTITY-ROW 17.4.1 IS INSTALLED 
layout-card.js?hacstag=156434866245:228 LAYOUT-CARD 2.4.5 IS INSTALLED
multiple-entity-row.js?hacstag=178921037451:1  MULTIPLE-ENTITY-ROW  4.5.1 
apexcharts-card.js?hacstag=331701152204:835  APEXCHARTS-CARD  v2.1.2 
utils.ts:1  BATTERY-STATE-CARD  3.2.1
card.js?hacstag=2153271951110:295 
  RGB Light Card  v1.11.0  
banner-card.js?hacstag=1867657040130:162 banner-card: 0.12.0
lg-remote-control.js?hacstag=257005990203:272   LG WebOS Remote Control Card    version: v2.0.3  
card-tools.js?hacstag=16140332811:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: 2c79fc98-dccf9c7b
uptime-card.js?hacstag=3505098670160:448  uptime-card    0.16.0    
rpi-monitor-card.js?hacstag=281214271142:174   RPI-MONITOR-CARD   Version 1.4.2    
custom-icons.js?hacstag=491465538037:309   Custom-icons    Version 0.3.7 20221004
kiosk-mode.js?hacstag=497319128601:1 ≡ kiosk-mode             ⋮
version 6.1.0            ⋮
entities.js:28   SPOTIFY-CARD   Version 2.4.0    
clock-weather-card.js?hacstag=522634019280:180   CLOCK-WEATHER-CARD  Version: 2.8.3
swiss-army-knife-card.js?hacstag=214786112251:702   SWISS-ARMY-KNIFE-CARD        Version 2.5.1      
slider-button-card.js?hacstag=4987940331130:1043   SLIDER-BUTTON-CARD  v1.13.0 
mushroom-strategy.js?hacstag=619284862210:1  Mushroom Strategy  v2.1.0 
flex-table-card.js?hacstag=156292058077:735  FLEX-TABLE-CARD  Version 0.7.7 
big-slider-card.js?hacstag=332589148115:179   BIG-SLIDER-CARD   Version 1.1.5    
trashcard.js?hacstag=678764124221:665 🗑️ TrashCard 2.2.3
wallpanel.js?hacstag=3095064164254:296 🖼️ Wallpanel version 4.25.5
wallpanel.js?hacstag=3095064164254:296 Location changed from panel 'null/null' to 'lovelace/default_view'
bubble-card.js?hacstag=680112919204:1201  Bubble Card  v2.1.1 
power-flow-card-plus.js?hacstag=618081815022:1 ⚡ Power Flow Card Plus v0.2.2 is installed
givtcp-battery-card.js?hacstag=649637656024:1256  GIVTCP-BATTERY-CARD  v0.2.4 
auto-entities.js?hacstag=1677445841130:172 AUTO-ENTITIES 1.13.0 IS INSTALLED
button-card.js?hacstag=146194325412:426   BUTTON-CARD   Version 4.1.2 
my-cards.js?hacstag=399108901105:186   ---- MY-SLIDER ----   Version 3.0.6    
my-cards.js?hacstag=399108901105:356   ---- MY-SLIDER-V2 ----   Version 3.0.6    
my-cards.js?hacstag=399108901105:388   ---- MY-BUTTON ----   Version 1.0.2    
my-cards.js?hacstag=399108901105:495   ---- MY-CARDS ----   Version 2.0.4    
air-visual-card.js?hacstag=157674859203:4   AIR-VISUAL-CARD    Version 2.0.3
sunsynk-power-flow-card.js?hacstag=6135885354432:52  ⚡ SUNSYNK-POWER-FLOW-CARD  Version: 4.44.0 
platinum-weather-card-df6d26e2.js:73   PLATINUM-WEATHER-CARD    Version 1.0.5          
cast_receiver_framework.js:77  [  0.000s] [cast.receiver.IpcChannel] Opening net websocket 
cast_receiver_framework.js:532 CAST SDK CAF Version: 3.0.0125
astroweather-card.js?hacstag=4546707420504:9   ASTROWEATHER-CARD   Version v0.50.4
```

### Javascript errors shown in your browser console/inspector

```txt
Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
```
