### ISSUE TITLE
Single card (Panel) with vertical and horisontal stack will broke card view

### ISSUE THREAD

**Issue by almost-online** [home-assistant/frontend#21643]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Home assistant 2024.8.0
I have a panel with a single card view + horizontal and vertical stacs liike this one
```yaml
title: Test card
path: test-card
icon: mdi:battery-clock-outline
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        title: Title1
        cards:
          - type: tile
            entity: sensor.in_out_electricity_diff
            vertical: true
          - type: tile
            entity: sensor.in_out_electricity_diff
            vertical: true
          - type: tile
            entity: sensor.in_out_electricity_percent
            vertical: true
            show_entity_picture: false
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.in_out_electricity_percent
              - type: tile
                entity: sensor.in_out_electricity_percent
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.in_out_electricity_percent
              - type: tile
                entity: sensor.in_out_electricity_percent
type: panel

```

on the editor this cards view as expected
![image](https://github.com/user-attachments/assets/39404a5b-870a-4b74-847b-3ae71c899912)

But on the panel view I have some overlaping like this one

![image](https://github.com/user-attachments/assets/b311b3cf-c76c-4a42-8ae1-5a379748be8f)

Also the same problem on the mobile app (Android)
![image](https://github.com/user-attachments/assets/0a1655b8-d2af-4814-a3c3-0a3078d849cd)

P.S. Home assistant 2024.7.x had a similar prooblem but not criticall. Overlaping was by few pixels

### Describe the behavior you expected

Expected the card should display like this one

![image](https://github.com/user-attachments/assets/b18a3a64-f5b3-4f3c-87cd-c0e9fe9769e6)

### Steps to reproduce the issue

Usee the YAML above (with correct entities) with default themes

### What version of Home Assistant Core has the issue?

2024.8.0, 2024.7.х

### What was the last working version of Home Assistant Core?

No idea

### In which browser are you experiencing the issue with?

Chrome
Version 127.0.6533.100 (Official Build) (arm64)

### Which operating system are you using to run this browser?

mac OS sonoma 1.16, Android modile app

### State of relevant entities

```txt
any entities
```

### Problem-relevant frontend configuration

```yaml
title: Test card
path: test-card
icon: mdi:battery-clock-outline
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        title: Title1
        cards:
          - type: tile
            entity: <any entity>
            vertical: true
          - type: tile
            entity: <any entity>
            vertical: true
          - type: tile
            entity: <any entity>
            vertical: true
            show_entity_picture: false
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: <any entity>
              - type: tile
                entity: <any entity>
          - type: horizontal-stack
            cards:
              - type: tile
                entity: <any entity>
              - type: tile
                entity: <any entity>
type: panel
```

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

**Comment by ildar170975** [comment]
seems to be a duplicate of https://github.com/home-assistant/frontend/issues/18972

**Comment by ildar170975** [comment]
> But not for Panel (1 card) view type

What a difference?
In [my issue](https://github.com/home-assistant/frontend/issues/18972) it was not said about a particular view.
The glitch occurs on any view.

**Comment by ildar170975** [comment]
> at least for the Masonry (default) view type the issue had fixed

The issue could be still there - we just do not see it in this particular case.

BTW, here is a simplified MWE for your issue:
```
type: vertical-stack
cards:
  - type: horizontal-stack
    title: Title1
    cards:
      - type: tile
        entity: sun.sun
      - type: tile
        entity: sun.sun
      - type: tile
        entity: sun.sun
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: tile
            entity: sun.sun
          - type: tile
            entity: sun.sun
      - type: horizontal-stack
        cards:
          - type: tile
            entity: sun.sun
          - type: tile
            entity: sun.sun
```
