### ISSUE TITLE
Badge: hold_action doesn't work

### ISSUE THREAD

**Issue by JSoko** [home-assistant/frontend#21644]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In documentation for the new badges hold_action is mentioned:
https://www.home-assistant.io/dashboards/badges/#hold_action

But if i use it, it doesn't work and the tap_action is triggered

### Describe the behavior you expected

The hold action should be triggerd if I hold the badge

### Steps to reproduce the issue

Create a badge and use hold_action:

```
type: entity
entity: input_boolean.ap_joachim_warm
color: accent
name: JS
state_content: name
visibility:
  - condition: state
    entity: switch.apjss
    state: 'on'
tap_action:
  action: toggle
hold-action:
  action: more-info
```

### What version of Home Assistant Core has the issue?

core-2024.8.0

### In which browser are you experiencing the issue with?

Firefox and chrome

### Which operating system are you using to run this browser?

Windows 11
