### ISSUE TITLE
Missing data and target when converting buttons from call-service to perform-action

### ISSUE THREAD

**Issue by tronikos** [home-assistant/frontend#21659]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Existing buttons with `call-service` get converted to `perform-action` but lose the data and target.

For example this:
```yaml
show_name: true
show_icon: true
type: button
icon: mdi:circle
tap_action:
  action: call-service
  service: remote.send_command
  data:
    command: DPAD_CENTER
  target:
    entity_id: remote.kitchen_tv
```

When edited becomes:
```yaml
show_name: true
show_icon: true
type: button
icon: mdi:circle
tap_action:
  action: perform-action
  perform_action: remote.send_command
  data:
    command: {}
  target: {}
```

### Describe the behavior you expected

Don't lose data and target.

### Steps to reproduce the issue

1. Create a new button card with the above code and save
2. Edit the card and observe the action doesn't have data and target.

### What version of Home Assistant Core has the issue?

2024.8.0
