### ISSUE TITLE
Wake on LAN integration doesn't show up in the Integrations tab

### ISSUE THREAD

**Issue by Dawidooox** [home-assistant/frontend#21653]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

With 2024.8 release, integrations set up via YAML should be now visible in the UI.
In the Integrations tab I can now find pretty much every YAML integration running on my instance, except Wake on LAN integration.

The WOL integration works perfectly fine and is visible in UI while using filters in Devices and Entities tabs. However Integrations tab doesn't list it.

![filters](https://github.com/user-attachments/assets/bdb5054f-7579-48e3-9444-d0209dbeb86e)
Integration visible in filters in Devices and Entities tabs.

![integrationsTab](https://github.com/user-attachments/assets/d0998831-7c42-40b6-8d34-8ac45f93dcbb)
Integration not visible in Integrations tab.

```
switch:
  - platform: wake_on_lan
    name: "my-pc"
    mac: !secret wol_mac
    host: !secret wol_host
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: my-pc
```
My YAML config.

### Describe the behavior you expected

Wake on LAN integration should be visible in the Integrations tab when it's set up in YAML.

### Steps to reproduce the issue

1. Set up Wake on LAN integration in YAML ([the switch version](https://www.home-assistant.io/integrations/wake_on_lan#switch))
2. Make sure the integration is working
3. Go to Settings > Devices & services > Integrations tab
4. Wake on LAN shouldn't be listed here

### What version of Home Assistant Core has the issue?

2024.8.0

### In which browser are you experiencing the issue with?

Mozilla Firefox 129.0
Google Chrome 127.0.6533.100

### Which operating system are you using to run this browser?

Windows 10
