### ISSUE TITLE
Vertical Stack with Conditional Card - Creating White Space

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/frontend#2167]
**Home Assistant release with the issue:**
0.83.2

**Last working Home Assistant release (if known):**
Unsure

**Browser and Operating System:**
Chrome & Safari (macOS)

**Description of problem:**
When using a conditional card in a vertical-stack, when the first card is hidden, there is white-space created in its place, bumping the next card down slightly by a few pixels.

Ignore my messy test page, but the below screenshots show when the first item in my vertical stack is shown (on the right half), the top of the right panel is level with the items on the left. When I go to any other item in this vertical stack being the first displayed, the top edge sits a few pixels lower. Switching between the second and third items doesn't add to the gap, the space only seems to appear when the first item is hidden.

![image](https://user-images.githubusercontent.com/24840952/49334669-1324b700-f62b-11e8-93a3-3a6fd49f3753.png)

![image](https://user-images.githubusercontent.com/24840952/49334681-6e56a980-f62b-11e8-8f14-e5826a37c2f1.png)

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
`

      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: input_select.tablet_panel_detail
                state: "Lights"
            card:
              (LIGHT CARD)

          - type: conditional
            conditions:
              - entity: input_select.tablet_panel_detail
                state: "Lights Advanced"
            card:
              (ADVANCED LIGHT CARD)

          - type: conditional
            conditions:
              - entity: input_select.tablet_panel_detail
                state: "Media"
            card:
              (MEDIA CARD)

`

**Comment by iantrich** [comment]
related: https://github.com/home-assistant/home-assistant-polymer/issues/2395

**Comment by barrymossel** [comment]
This should have been fixed regarding https://github.com/home-assistant/home-assistant-polymer/pull/1999 but for me it still exists. Hidden conditional cards leave whitespace:

![2019-12-13 14_34_38-Home Assistant](https://user-images.githubusercontent.com/10389401/70804055-c931ed80-1db5-11ea-928e-b827da91486c.png)

**Comment by dfritsch86** [comment]
I have the same issue too, i have an empty column where a conditional card would show up if the conditions were met.

**Comment by s-hutter** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> Please make sure to update to the latest Home Assistant version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

Problem still persists in latest version.

**Comment by alexwohlbruck** [comment]
Is there any solution for this? Messing with the CSS in my browser tools but I even after deleting the cards from the layout, they still leave gaps. I'm assuming there is some kind of javascript code that calculates the positions of the cards (ie. [Masonry.js](https://masonry.desandro.com/)), is there any way we can access that API?

**Comment by bramkragten** [comment]
There is not js involved, we don't use Masonary. Removed the elements should remove the spacing.

**Comment by barrymossel** [comment]
Though the problem still persists.

**Comment by diamant-x** [comment]
Facing the same issue, although is important to disitnguish between vertical spaces (Such as the issue author setup), and horizontal spaces. Critical Scenario 2 next:

1. Scenario 1: Vertical spaces appearing.
- Hypothesis: An empty vertical stack still populates as a card for layout purposes.
- Test: 3 cards whatsoever, but second card to be a vertical/horizontal stack card. Include a single card in the stack, to be a conditional card. Set a condition so that it dissapears. Ensure the lovelace viewport is narrow enough so that all cards appear vertically.
- Issue: When disappearing the middle card conditional card, the other 2 cards won't be right next to each other.
- WORKAROUND: Encapsulate your vertical/horizontal card inside a conditional card, with condition with some sort of group collection of the subconditions.
- Expected solution: An empty card shouldn't be rendered at all.

2. Scenario 2: Horizontal spaces appearing.
- Hypothesis: The view controller program that calculates how many columns to generate in a wide viewport, takes into account total # of cards, not visible only.
- Test: 3 cards whatsoever, but second card to be a conditional card. Set a condition so that it dissapears. Ensure the lovelace viewport is wide enough so that all cards appear horizontally (3 columns).
- Issue: When disappearing the middle card conditional card, the other 2 cards won't be right next to each other; a big empty column is left in the middle.
- WORKAROUND: **NONE**.
- Expected solution: An empty card shouldn't be rendered at all; only 2 columns should appear.


Any help and/or fixes for this would be appreciated! Thanks.

**Comment by barrymossel** [comment]
This is still a relevant issue.

**Comment by barrymossel** [comment]
And still this issue is relevant. If someone needs more information, I will be happy to provide it!

**Comment by bangcrash** [comment]
I still have this issue and can demonstrate/supply config etc. if needed.

**Comment by JDunnio** [comment]
Same here. Please fix this annoying bug.
There is a workaround of using a grid card with 1 column. Is there something to be learned for the vertical stack card?

**Comment by bangcrash** [comment]
This is still a problem as of version 2021.6.5

**Comment by bangcrash** [comment]
This is still a problem as of version 2021.9.6 and I can reproduce/demonstrate if necessary

**Comment by Glennesink** [comment]
Still a problem in 2021.10

**Comment by bangcrash** [comment]
Still happening in 2021.12.9

**Comment by krazos** [comment]
This is still an issue in 2022.2.0b4.  The empty space above the Seasonal Decorations entities card in the screenshot corresponds to a vertical stack card containing two hidden conditional cards. 

![Screenshot from 2022-01-31 07-55-10](https://user-images.githubusercontent.com/18428022/151798069-98e35e86-3f65-4744-ab39-56c1775aba1a.png)
 
```yaml
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - entity: media_player.sonos_beam
        state: playing
      - entity: sensor.sonos_beam_source
        state_not: TV
    card:
      type: media-control
      entity: media_player.sonos_beam
  - type: conditional
    conditions:
      - entity: media_player.sonos_move
        state: playing
    card:
      type: media-control
      entity: media_player.sonos_move
```

**Comment by krazos** [comment]
Still an issue in 2022.6.1

**Comment by krazos** [comment]
This is still an issue as of 2022.9.5.

**Comment by s-hutter** [comment]
Since this issue never got the attention it deserves in my opinion, I decided to mention it in a post for the current "What the heck?" month of October 2022: https://community.home-assistant.io/t/471426
Votes are very much welcome to finally give this way too old bug more visibility. 🙂

**Comment by ildar170975** [comment]
This PR seems to solve this issue:
https://github.com/home-assistant/frontend/pull/13955

**Comment by ildar170975** [comment]
@TheTimmaeh 
Could you share a test code? 
Will check it again.

**Comment by TheTimmaeh** [comment]
@ildar170975 

This is a basic example of my setup.

Card #1 
```
type: vertical-stack
title: Weather
cards:
  - type: weather-forecast
    entity: weather.home
```

Card #2
```
type: vertical-stack
title: Media
cards:
  - type: conditional
    conditions:
      - entity: media_player.spotify
        state_not: unavailable
    card:
      type: media-control
      entity: media_player.spotify
  - type: conditional
    conditions:
      - entity: media_player.plex
        state_not: unavailable
    card:
      type: media-control
      entity: media_player.plex
  - type: entities
    entities:
      - entity: switch.guest_wi_fi
        name: Guest Wi-Fi
```

I tested a few things, like whether removing the title of the vertical stacks or changing the type of card inside the conditional card changes anything (not that I'd expect it to), but nothing changed.

**Comment by ildar170975** [comment]
@TheTimmaeh 
Sorry for a delay. Tested your [case ](https://github.com/home-assistant/frontend/issues/2167#issuecomment-1411046752), have to confirm:

1. Bot conditional cards are shown:

![изображение](https://user-images.githubusercontent.com/71872483/221649037-480e6a26-8ba5-440d-9f55-964e7dbe4497.png)

2. The 1st conditional card is shown the 2nd is not:

![изображение](https://user-images.githubusercontent.com/71872483/221649165-6c324158-39ff-41b1-81e4-78877f97ead5.png)

3. The 1st conditional card is not shown the 2nd is shown - there is a GAP:
![изображение](https://user-images.githubusercontent.com/71872483/221649204-7cfa0c4b-a335-4f61-bc7e-2564473fbaaa.png)

4. Both conditional cards are not shown - there is a GAP:

![изображение](https://user-images.githubusercontent.com/71872483/221649453-a04b7be4-3ad3-4a5f-b541-33da6b253f9b.png)

**Comment by rkoptev** [comment]
I'm experiencing the same issue while using conditional card in a stack

**Comment by ildar170975** [comment]
Do not observe this issue in 2024.4.3

**Comment by dhoeben** [comment]
Still observe the issue in 2024.5.4

**Comment by ildar170975** [comment]
@dhoeben 
Could you post a MINIMAL code to reproduce the issue?
Meanwhile I will re-check mine (https://github.com/home-assistant/frontend/issues/2167#issuecomment-1446829031)

**Comment by dhoeben** [comment]
@ildar170975 ofcourse!

Like described above, it seems to only happen when the first card is a hidden conditional card in a vertical stack.

`- type: vertical-stack 
  title: "Issue"
  cards:
  - type: conditional
    conditions:
    - condition: state
      entity: sun.sun
      state: "below_horizon" #I assume you are looking at this during the day
    card:
      type: vertical-stack 
      cards:
      - type: entity
        entity: light.living_room
      - type: entity
        entity: sun.sun

- type: vertical-stack 
  title: "Correct"
  cards:
  - type: vertical-stack 
    cards:
    - type: entity
      entity: light.living_room
    - type: entity
      entity: sun.sun`

**Comment by ildar170975** [comment]
@dhoeben 
Just managed to test your case, sorry for a delay.

1. Check this - place these cards on an empty view:
```
  - type: vertical-stack
    cards:
      - &ref_conditional_card
        type: conditional
        conditions:
          - entity: input_boolean.test_boolean
            state: 'on'
        card:
          type: entities
          entities:
            - entity: sun.sun
      - &ref_entity_card
        type: entity
        entity: sun.sun

  - &ref_picture_card
    type: picture
    image: /local/images/test/blue.jpg

  - type: vertical-stack
    cards:
      - *ref_conditional_card
      - *ref_entity_card

  - *ref_picture_card

  - type: entities
    entities:
      - entity: input_boolean.test_boolean
```
There are 2 stacks which have same cards:
-- the 1st stack has a conditional card as the 2nd card,
-- the 2nd stack has a conditional card as the 1st card.

when shown:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/213f41f4-a245-4ac8-9d22-8310eabbdc9c)

when hidden:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/5562f045-5989-4a9d-ad97-8c6494671e89)

No gaps here.
Note - the stacks included other card along with ф conditional card.

------------

2. Next - a case when a stack only contains a conditional card:
```
  - type: vertical-stack
    cards:
      - &ref_conditional_card
        type: conditional
        conditions:
          - entity: input_boolean.test_boolean
            state: 'on'
        card:
          type: entities
          entities:
            - entity: sun.sun
      # - &ref_entity_card
      #   type: entity
      #   entity: sun.sun

  - &ref_picture_card
    type: picture
    image: /local/images/test/blue.jpg

  # - type: vertical-stack
  #   cards:
  #     - *ref_conditional_card
  #     # - *ref_entity_card

  # - *ref_picture_card

  - type: entities
    entities:
      - entity: input_boolean.test_boolean
```
when shown:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/53004a2f-da56-44be-80f5-ebebb4bb4aae)

when hidden:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/891cddf8-1ca5-497e-bc05-4182cd70c4bd)

The gap is here.

3. When a title is defined:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/a3cd5643-97d4-4e59-a42c-d8bd970dc079)

Technically there is no gap here - a stack card is shown with a header w/o inner cards.
I do not think we should prevent showing a title for an empty stack.

As a conclusion:
stack card w/o a title still occupies a space if the only card is a conditional & it is hidden.
Worth re-creating an issue.

**Comment by dhoeben** [comment]
Thanks for the explanation! I think we should definitely re-open

**Comment by dhoeben** [comment]
@ildar170975, I have a vertical stack with lots of conditional cards in it, as suggested actions throughout the day. Unfortunately, this causes it to behave like this. Thanks for the information.

**Comment by ildar170975** [comment]
So, all cards inside a stack are conditional?
Then yes, there will be a gap probably.

**Comment by nocin** [comment]
In case anyone ends up here looking for a workaround. I replaced the default vertical-stack card with the [layout-card](https://github.com/thomasloven/lovelace-layout-card) from HACS. Using this card, I get no white space when having a conditional card inside.
```yaml
type: custom:layout-card
layout_type: custom:vertical-layout
layout: {}
cards:
  - type: conditional
    conditions:
      - condition: state
        entity: schedule.display_sleep_toggle
        state: 'on'
    card:
      type: tile
      entity: input_boolean.sleep_status
      icon: mdi:sleep
      state_content: state
```
