### ISSUE TITLE
Miss-Scaling input_datetime.xxxx within horizontal stack

### ISSUE THREAD

**Issue by Swimmer71** [home-assistant/frontend#21687]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since Core 2024.08 my input_datetime.xxx does not fit anymore into the horizontal stack on my mobile device. It is too far right.
Also 2024.08.1 didn't help. 
![Screenshot_2024-08-11-13-04-13-74_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/0bc90fe3-5088-4c2e-b869-c0aa35780b93)

![Screenshot_2024-08-11-13-04-52-69_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/f3a2de79-9424-4d72-96ab-b2b675d7e633)

```
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - entity: input_datetime.poolcycle1start
            name: Start 1
          - entity: input_datetime.poolcycle1end
            name: Ende 1
        state_color: true
      - type: entities
        entities:
          - entity: input_datetime.poolcycle2start
            name: Start 2
          - entity: input_datetime.poolcycle2end
            name: Ende 2
        state_color: true

```

### Describe the behavior you expected

Before 2024.08 it was nice within the borders of the stack

### Steps to reproduce the issue

1. use my code in post to test
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.08, but also 2024.08.1

### What was the last working version of Home Assistant Core?

latest before 2024.08

### In which browser are you experiencing the issue with?

Android App at mobile device
