### ISSUE TITLE
Key 'service' is not expected for blueprint automations

### ISSUE THREAD

**Issue by EnochPrime** [home-assistant/frontend#21692]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Same issue as #21555, but with blueprint controlled automations.

### Describe the behavior you expected

Blueprint controlled automations should migrate from service to action.

### Steps to reproduce the issue

1. Run core-2024.7.4 or earlier
2. Create blueprint with service selector
3. Create automation from blueprint and add a call service service
4. Update to core-2024.8.0 or newer

### What version of Home Assistant Core has the issue?

core-2024.8.1

### What was the last working version of Home Assistant Core?

core-2024.7.4

**Comment by karwosts** [comment]
Can you share an example blueprint which has a problem, and share your resulting automation instance yaml which has a problem. 

I don't believe there has ever existed something called a `service selector`, so just want to clarify exactly what you're referring to.

**Comment by EnochPrime** [comment]
> Can you share an example blueprint which has a problem, and share your resulting automation instance yaml which has a problem.
> 
> I don't believe there has ever existed something called a "service selector", so just want to clarify exactly what you're referring to.

Blueprint
``` yaml
blueprint:
  name: Scene Control
  description: Configures scene actions for Inovelli Red Series Dimmers.
  domain: automation
  input:
    target_device:
      name: Target Device
      description: Device which will trigger the scene.
      selector:
        device:
          filter:
            - manufacturer: Inovelli
              model: LZW31-SN
            - manufacturer: Inovelli
              model: VZW31-SN
    config_action:
      name: Config Button Action
      description: Actions to perform when the config button is pressed.
      default: []
      selector:
        action:
    up2x_action:
      name: Double Tap Up Action
      description: Actions to perform when the up button is double tapped.
      default: []
      selector:
        action:
    down2x_action:
      name: Double Tap Down Action
      description: Actions to perform when the down button is double tapped.
      default: []
      selector:
        action:
trigger:
  - platform: device
    device_id: !input target_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "003"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 003
    id: config
  - platform: device
    device_id: !input target_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "002"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 3
    id: up2x
  - platform: device
    device_id: !input target_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 3
    id: down2x
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: config
        sequence: !input config_action
      - conditions:
          - condition: trigger
            id: up2x
        sequence: !input up2x_action
      - conditions:
          - condition: trigger
            id: down2x
        sequence: !input down2x_action
    default: []
```

Automation
``` yaml
alias: "Scene Control: Dining Room"
description: ""
use_blueprint:
  path: scene_control.yaml
  input:
    config_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.blue_lamp
    up2x_action:
      - service: light.turn_on
        target:
          entity_id:
            - light.chandelier
        data:
          brightness_pct: 100
    down2x_action: []
    target_device: 18a107a04aa0814d1cffcdf608b8942f
```
