### ISSUE TITLE
gauge font size is unstable

### ISSUE THREAD

**Issue by 0ki** [home-assistant/frontend#21735]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

gauge card text size is jumping around

### Describe the behavior you expected

text should not change after a page has loaded (unless maybe the number of digits changes)

### Steps to reproduce the issue

1. Add a gauge card to a sensor that fluctuates between 220-250

### What version of Home Assistant Core has the issue?

core-2024.8.2

### In which browser are you experiencing the issue with?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: gauge
        .....
      - type: gauge
        entity: sensor.power_total_power
        name: Current load
        severity:
          green: 0
          yellow: 350
          red: 1500
        min: 0
        needle: false
        max: 6000
  - type: history-graph
    .....
```

### Additional information

![bug](https://github.com/user-attachments/assets/35301842-edf0-4f7b-9131-867525687862)

**Comment by ildar170975** [comment]
Confirmed.
MWE:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_number.test_level_1
  - type: horizontal-stack
    cards:
      - type: glance
        entities:
          - input_number.test_level_1
      - type: gauge
        entity: input_number.test_level_1
```
Suggest to reflect in the issue's title that this happens when the Gauge card is placed inside a Horizontal stack.
