### ISSUE TITLE
Image variable in picture-entity card overridden by `person` image

### ISSUE THREAD

**Issue by damiano75** [home-assistant/frontend#21738]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I want to change the entity image with a local one, but I still have the entity default image. 

### Describe the behavior you expected

Before 2024.8 it worked fine

### Steps to reproduce the issue

n/a

### What version of Home Assistant Core has the issue?

core-2024.8.x

### What was the last working version of Home Assistant Core?

core-2024.7.x

### In which browser are you experiencing the issue with?

Many

### Problem-relevant frontend configuration

```yaml
show_state: true
show_name: false
camera_view: auto
type: picture-entity
entity: person.damiano
image: /local/io_round.png
```
