### ISSUE TITLE
Keyboard stops working when setting Light brightness

### ISSUE THREAD

**Issue by nikduvall** [home-assistant/frontend#21752]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When modifying an automation and attempting to type in a brightness, the keyboard stops responding until the webpage is reloaded.

### Describe the behavior you expected

Be able to type in a value for the brightness percentage

### Steps to reproduce the issue

1.  Navigate to Settings --> Automation
2.  Create a new automation targeting a light
3.  Set an Action of Light: Turn On
4. Check the checkbox for Brightness
5. Click inside the edit box for the value (do not touch the slider)
6. Attempt to type in a numeric value
7. No value is displayed in the edit box
8. The keyboard inputs are now ignored on every screen you navigate to
9. Click the browser Reload button
10. Keyboard inputs are back to normal
...

### What version of Home Assistant Core has the issue?

2024.8.2

### What was the last working version of Home Assistant Core?

2024.7.4

### Problem-relevant frontend configuration

```yaml
alias: Master Bedroom Switch Toggle
description: ""
trigger:
  - platform: device
    type: changed_states
    device_id: 4d824368de158122d15c18e6525d0d77
    entity_id: b1ff47da42c14b669f2986b2f8b49206
    domain: switch
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: switch.master_bedroom_light_switch_switch_1
            state: "on"
        sequence:
          - action: light.turn_on
            data:
              kelvin: 3067
              brightness_pct: 100
            target:
              entity_id: light.floor_corner_light
      - conditions:
          - condition: state
            entity_id: switch.master_bedroom_light_switch_switch_1
            state: "off"
        sequence:
          - action: light.turn_off
            target:
              entity_id:
                - light.floor_corner_light
            data: {}
mode: single
```
