### ISSUE TITLE
Alarm_panel Tile changes mode even though code is not entered/dismissed

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21775]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

when selecting a mode for the alarm_panel  in the Tile card, the code panel pops up correctly. However, clicking it away, still changes the mode to the selected mode, while it should not and remain on the original mode.
Maybe even show a warning no acid code was entered.

### Describe the behavior you expected

upon no code, clicking the X, the mode should Not change

<img width="281" alt="Scherm­afbeelding 2024-08-24 om 10 52 13" src="https://github.com/user-attachments/assets/c913f77f-6ee6-40e1-958a-dc46e65b926a">

### Steps to reproduce the issue

1. see procedure above
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Sonoma 14.6.1

### Problem-relevant frontend configuration

```yaml
type: tile
entity: alarm_control_panel.ha_main_alarm
features:
  - type: alarm-modes
    modes:
      - armed_home
      - armed_away
      - armed_night
      - armed_vacation
      - disarmed
```

### Additional information

<img width="547" alt="Scherm­afbeelding 2024-08-24 om 10 54 57" src="https://github.com/user-attachments/assets/f4cbdd94-fed7-4318-9e3a-8df46e60510d">
