### ISSUE TITLE
Automation that is disabled becomes enabled after a HA restart

### ISSUE THREAD

**Issue by bouwew** [home-assistant/frontend#21780]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have one Automation that is disabled as the default, via `initial_state: false`.

Every time I restart HA for some reason, this Automation becomes enabled. It happens just before the HA restart finished message is shown on screen.

### Describe the behavior you expected

The Automation should stay disabled.

### Steps to reproduce the issue

1. Disable the automation manually via the UI.
2. Restart HA.
3. Watch the status of the automation, it becomes enabled during HA restarting.
...

### What version of Home Assistant Core has the issue?

core-2024.8.2

### What was the last working version of Home Assistant Core?

Unknown

### In which browser are you experiencing the issue with?

Firefox for Linux Mint v129.0

### Which operating system are you using to run this browser?

Linux Mint 22.0

### Problem-relevant frontend configuration

```yaml
alias: DHW Solar heating
  description: Heat DHW via surplus solar energy
  trigger:
    - platform: time_pattern
      seconds: /20
  condition:
    - condition: numeric_state
      entity_id: water_heater.thermex_water_heater
      attribute: current_temperature
      below: 69
  action:
    - choose:
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: water_heater.thermex_water_heater
                  attribute: operation_mode
                  state: "off"
                - condition: and
                  conditions:
                    - condition: state
                      entity_id: water_heater.thermex_water_heater
                      attribute: operation_mode
                      state: eco
                    - condition: numeric_state
                      entity_id: water_heater.thermex_water_heater
                      above: 29
                      below: 31
                      attribute: temperature
          sequence:
            - if:
                - condition: numeric_state
                  entity_id: sensor.aurum_net_energy
                  above: -1350
                  below: -725
              then:
                - action: water_heater.set_temperature
                  metadata: {}
                  data:
                    operation_mode: eco
                    temperature: 69
                  target:
                    entity_id: water_heater.thermex_water_heater
              else:
                - if:
                    - condition: numeric_state
                      entity_id: sensor.aurum_net_energy
                      above: -2050
                      below: -1350
                  then:
                    - action: water_heater.set_temperature
                      metadata: {}
                      data:
                        temperature: 70
                        operation_mode: electric
                      target:
                        entity_id: water_heater.thermex_water_heater
                  else:
                    - if:
                        - condition: numeric_state
                          entity_id: sensor.aurum_net_energy
                          below: -2050
                      then:
                        - action: water_heater.set_temperature
                          metadata: {}
                          data:
                            temperature: 71
                            operation_mode: performance
                          target:
                            entity_id: water_heater.thermex_water_heater
        - conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: water_heater.thermex_water_heater
                  attribute: operation_mode
                  state: eco
                - condition: numeric_state
                  entity_id: water_heater.thermex_water_heater
                  attribute: temperature
                  above: 31
          sequence:
            - if:
                - condition: numeric_state
                  entity_id: sensor.aurum_net_energy
                  above: -1325
                  below: -625
              then:
                - action: water_heater.set_temperature
                  metadata: {}
                  data:
                    temperature: 70
                    operation_mode: electric
                  target:
                    entity_id: water_heater.thermex_water_heater
              else:
                - if:
                    - condition: numeric_state
                      entity_id: sensor.aurum_net_energy
                      below: -1325
                  then:
                    - action: water_heater.set_temperature
                      metadata: {}
                      data:
                        temperature: 71
                        operation_mode: performance
                      target:
                        entity_id: water_heater.thermex_water_heater
                  else:
                    - if:
                        - condition: numeric_state
                          entity_id: sensor.aurum_net_energy
                          above: 0
                      then:
                        - action: water_heater.set_temperature
                          metadata: {}
                          data:
                            operation_mode: eco
                            temperature: 30
                          target:
                            entity_id: water_heater.thermex_water_heater
        - conditions:
            - condition: state
              entity_id: water_heater.thermex_water_heater
              attribute: operation_mode
              state: electric
          sequence:
            - if:
                - condition: numeric_state
                  entity_id: sensor.aurum_net_energy
                  below: -700
              then:
                - action: water_heater.set_temperature
                  metadata: {}
                  data:
                    temperature: 71
                    operation_mode: performance
                  target:
                    entity_id: water_heater.thermex_water_heater
              else:
                - if:
                    - condition: numeric_state
                      entity_id: sensor.aurum_net_energy
                      above: 0
                      below: 625
                  then:
                    - action: water_heater.set_temperature
                      metadata: {}
                      data:
                        temperature: 69
                        operation_mode: eco
                      target:
                        entity_id: water_heater.thermex_water_heater
                  else:
                    - if:
                        - condition: numeric_state
                          entity_id: sensor.aurum_net_energy
                          above: 625
                      then:
                        - action: water_heater.set_temperature
                          metadata: {}
                          data:
                            operation_mode: eco
                            temperature: 30
                          target:
                            entity_id: water_heater.thermex_water_heater
        - conditions:
            - condition: state
              entity_id: water_heater.thermex_water_heater
              attribute: operation_mode
              state: performance
          sequence:
            - if:
                - condition: numeric_state
                  entity_id: sensor.aurum_net_energy
                  above: 0
                  below: 700
              then:
                - action: water_heater.set_temperature
                  metadata: {}
                  data:
                    temperature: 70
                    operation_mode: electric
                  target:
                    entity_id: water_heater.thermex_water_heater
              else:
                - if:
                    - condition: numeric_state
                      entity_id: sensor.aurum_net_energy
                      above: 700
                      below: 1325
                  then:
                    - action: water_heater.set_temperature
                      metadata: {}
                      data:
                        temperature: 69
                        operation_mode: eco
                      target:
                        entity_id: water_heater.thermex_water_heater
                  else:
                    - if:
                        - condition: numeric_state
                          entity_id: sensor.aurum_net_energy
                          above: 1325
                      then:
                        - action: water_heater.set_temperature
                          metadata: {}
                          data:
                            operation_mode: eco
                            temperature: 30
                          target:
                            entity_id: water_heater.thermex_water_heater
  initial_state: false
  mode: single
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

**Comment by karwosts** [comment]
I have plenty of automations disabled that stay disabled after a restart. 

If it's just this particular automation, maybe you have some automation that is turning it on. 

But anyway this isn't a frontend issue, the states of entities are controlled by the backend.

**Comment by ildar170975** [comment]
@bouwew 
For the record:
this automation is still disabled after HA reboot:
```
alias: test_initial_state
description: ""
trigger: []
action:
  - action: notify.persistent_notification
    data:
      message: test
initial_state: false
mode: single
```
