### ISSUE TITLE
Editing a todo list item due date and saving causes date to be out by one day.  Google Tasks Integration.

### ISSUE THREAD

**Issue by markusg1234** [home-assistant/frontend#21803]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding a todo item for google tasks and then saving a date.
What will save is the day before the date selected..

### Describe the behavior you expected

Should save the date selected.

### Steps to reproduce the issue

1.  Create a new todo list item. Integration is google tasks.
2.  Edit and add a date.
3.  Save the date.
4.  Now the date will be the day before the one that was selected.

### What version of Home Assistant Core has the issue?

core-2024.8.3

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Google Chrome 128.0.6613.84

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
I'll guess this is probably not a frontend issue. What you can do for debug is open a separate tab on developer-tools/event and add a listener for `call_service`. Then when you save the event, you should see this:

> Event 0 fired 5:20 AM:
```
event_type: call_service
data:
  domain: todo
  service: update_item
  service_data:
    item: 7e465a18-646e-11ef-bb38-f7eaa6c2412a
    rename: Test
    status: needs_action
    description: null
    due_date: "2024-09-30"
    entity_id:
      - todo.todo
origin: LOCAL
time_fired: "2024-08-27T12:20:51.612719+00:00"
context:
  id: 01J69WG7RWA9W8CKMGXVK2FPYE
  parent_id: null
  user_id: f4e7321cdf6145c9a7a2e615a5487d10
```


If the values in the service_data are as expected, you would need to follow this up as a core issue with the google tasks integration.
