### ISSUE TITLE
Badges - not possible to edit after creation - Auto-entities

### ISSUE THREAD

**Issue by dajomu1** [home-assistant/frontend#21823]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Added a card using the Auto-entities plugin in the badges section which should be hidden until battery level goes under x-percentage. When going out of edit mode, the card is hidden but when entering edit mode again I am not able to see the card for further editing. It will only appear, even in edit mode, when battery level goes below defined threshold.

### Describe the behavior you expected

The card should be visible in edit mode and hidden only when not in edit mode.

### Steps to reproduce the issue

1. Add a badge
2. go to code editor
3. replace code (see code under "Problem-relevant frontend configuration")
4. go out of code editor (now the GUI has changed)
5. go to Card
6. Remove tick "show if empty"
7. save

### What version of Home Assistant Core has the issue?

2024.8.3

### In which browser are you experiencing the issue with?

Firefox 129.02, Brave Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Kubuntu 24.04, Win10, IOS

### Problem-relevant frontend configuration

```yaml
type: custom:auto-entities
card:
  show_header_toggle: false
  type: entities
filter:
  include:
    - attributes:
        device_class: battery
      state: <= 10
  exclude:
    - name: /[Ll]ow/
    - name: /[Ss]tate/
    - entity_id: '*phone*'
    - entity_id: '*ipad*'
sort:
  method: state
  numeric: true
show_empty: true
```
