### ISSUE TITLE
Badges Visibility is not working as expected

### ISSUE THREAD

**Issue by martindybal** [home-assistant/frontend#21849]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the Issue You Are Experiencing

The badge in my UI is not respecting the visibility condition that I’ve set. Despite configuring the badge to only be visible when a specific entity (`binary_sensor.reedcontact_103_window`) is in the 'on' state, the badge remains visible at all times, regardless of the entity's state.

This issue is causing the UI to display the badge even when the condition is not met, which disrupts the intended user experience. The visibility condition seems to be ignored entirely, leading to a badge that is always shown.

### Describe the behavior you expected

I expected the badge to only be visible when the specified visibility condition is met. Specifically, when the `binary_sensor.reedcontact_103_window` entity is in the 'on' state, the badge should be displayed. If the entity is in any other state (e.g., 'off'), the badge should not be visible.

### Steps to reproduce the issue

1. Create a badge with a visibility condition in the UI.
1. Set the visibility condition based on the state of an entity.
1. Observe that the badge remains visible even when the condition is not met.

```
title: Test
views:
  - title: Visibility
    path: visibility
    cards: []
    badges:
      - type: custom:mushroom-template-badge
        content: Hello
        icon: mdi:mushroom
        color: red
        entity: binary_sensor.reedcontact_103_window
        visibility:
          - condition: state
            entity: binary_sensor.reedcontact_103_window
            state: 'on'
      - type: entity
        entity: binary_sensor.reedcontact_103_window
        visibility:
          - condition: state
            entity: binary_sensor.reedcontact_103_window
            state: 'on'
```

### What version of Home Assistant Core has the issue?

2024.8.3

### In which browser are you experiencing the issue with?

https://www.whatsmybrowser.org/b/JNNLL

### State of relevant entities

```txt
Frontend 20240809.0
```
