### ISSUE TITLE
history-graph's scaling not consistent, flickering and cutting off data

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#21846]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The history graph's scaling doesn't work right and is flickering on updates, which cuts off data.

Left side is Chromium, right side is Firefox:

[Screencast_20240901_100802.webm](https://github.com/user-attachments/assets/a6970321-98cc-4224-8ed4-109f47cc6a32)

### Describe the behavior you expected

Scaling should work correct

### Steps to reproduce the issue

1. Use history graph.

### What version of Home Assistant Core has the issue?

2024.9.0b2

### In which browser are you experiencing the issue with?

Firefox 130.0b9 / Chromium 128.0.6613.84 

### Which operating system are you using to run this browser?

KDE 6.1.4 7 / Wayland / Linux

### Problem-relevant frontend configuration

```yaml
- type: vertical-stack
        cards:
          - type: history-graph
            entities:
              - entity: sensor.lamp_left_room_ceiling_spot_power
              - entity: sensor.ambient_light_sensor_illuminance
              - entity: sensor.target_brightness_left_room
              - entity: sensor.lamp_left_room_ceiling_2_power_2
            hours_to_show: 0.2
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_
