### ISSUE TITLE
YAML dump appears not consistent to core

### ISSUE THREAD

**Issue by akloeckner** [home-assistant/frontend#21860]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I acknowledge that YAML will most likely never match entirely between UI and configuration files. However, simple harmonizations could be done. Consider this script example: 

In UI:
```yaml
alias: Test Unicode
sequence:
  - variables:
      abort: "{{ \"\\uE12C\" }}"
mode: single
```

In scripts.yaml:
```yaml
test_unicode:
  alias: Test Unicode
  sequence:
  - variables:
      abort: '{{ "\uE12C" }}'
  mode: single
```

The difference in quotes seems to be a choice. 

For the UI double quotes are set:
https://github.com/home-assistant/frontend/blob/a09f44dcd2b887b3a40116caa4705045dae005ab/src/components/ha-yaml-editor.ts#L62

While core seems to default to single quotes:
https://github.com/home-assistant/core/blob/671aaa7e957ffd9603d0c5beb39b10d00d223da6/homeassistant/util/yaml/dumper.py#L21

Probably more options could be harmonized: https://github.com/nodeca/js-yaml/tree/master?tab=readme-ov-file#dump-object---options-

### Describe the behavior you expected

YAML in UI and in configuration files should be more alike.

### Steps to reproduce the issue

1. Copy above script into the code editor
2. Save and compare scripts.yaml

### What version of Home Assistant Core has the issue?

2024-8-3
