### ISSUE TITLE
Calendar Card overflowing Layout

### ISSUE THREAD

**Issue by cloudbr34k84** [home-assistant/frontend#21873]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using the calendar card the fc-list-table  overflows the the calendar card as see in the image below, 
![image](https://github.com/user-attachments/assets/25d30a73-9016-470d-9651-ef3f92444b3a)
![image](https://github.com/user-attachments/assets/620f4d54-0b45-42cd-ad64-fff78fecd8ac)

### Describe the behavior you expected

I would expect the this card to be like all the other HA cards when using the layout function

### Steps to reproduce the issue

1. Add Calendar Card
2. add calendar entity
3.
...
![image](https://github.com/user-attachments/assets/78c31a91-f92a-4afb-a42f-79f7afbbe57f)

### What version of Home Assistant Core has the issue?

2024.9.0b4

### What was the last working version of Home Assistant Core?

2024.7.. Before layout control was added

### In which browser are you experiencing the issue with?

Version 128.0.6613.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
initial_view: listWeek
type: calendar
entities:
  - calendar.rainbow_beach_tide_times_heights
layout_options:
  grid_columns: full
  grid_rows: 8
theme: My Theme
title: Rainbow Beach Tides
```
