### ISSUE TITLE
Error in describing action when target is a template in blueprint input defaults

### ISSUE THREAD

**Issue by seblu** [home-assistant/frontend#21884]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Let's imagine the following blueprint:

```yaml
blueprint:
  name: Cover Daily
  domain: automation
  input:
    covers:
      name: Cover(s)
      selector:
        target:
          entity:
            domain: cover
    open_action:
      name: Open action(s)
      description: Actions to open the cover(s).
      default:
      - service: cover.open_cover
        target: "{{ covers }}"
      selector:
        action:
```

The automation edition interface display the following error message : `Error in describing action: cannot use 'in' operator to search for "area_id" in "{{ covers }}"`.

Here is a screenshot of how it's displayed.
![screenshot_gram_20240904_235030](https://github.com/user-attachments/assets/7bdd8f72-586e-4d35-bd11-1e38c065a972)

The automation works as expected, so it's mainly an UI errors because a code is expecting a map and not a string for targets.

### Describe the behavior you expected

To not display errors and propose YAML edition.

### Steps to reproduce the issue

1. Create a blueprint with an input with a default with a target template
2. Create an automation based on this blueprint

### What version of Home Assistant Core has the issue?

2024.9.0

### In which browser are you experiencing the issue with?

firefox,chrome

### Which operating system are you using to run this browser?

Arch Linux, Android

### Javascript errors shown in your browser console/inspector

```txt
TypeError: cannot use 'in' operator to search for "area_id" in "{{ covers }}"
    y script_i18n.ts:102
    f script_i18n.ts:53
    value ha-automation-action-row.ts:230
    update lit-element.ts:160
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    p directive-helpers.ts:195
    update repeat.ts:342
    _$AS directive.ts:134
    N lit-html.ts:1085
    _$AI lit-html.ts:1362
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    B lit-html.ts:2183
    update lit-element.ts:165
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    B lit-html.ts:2183
    update lit-element.ts:165
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    update dynamic-element-directive.ts:28
    update dynamic-element-directive.ts:27
    _$AS directive.ts:134
    N lit-html.ts:1085
    _$AI lit-html.ts:1362
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    B lit-html.ts:2183
    update lit-element.ts:165
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    T lit-html.ts:1618
    _$AI lit-html.ts:1403
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    B lit-html.ts:2183
    update lit-element.ts:165
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
script_i18n.ts:64:12
```
```


### Additional information

_No response_

**Comment by ildar170975** [comment]
I do not think you can use this:
```
      - service: cover.open_cover
        target: "{{ covers }}"
```
1st, `covers` is not a variable - it is an "input" and is supposed to be used along with `!input` when addressed.
2nd, do not think that it is allowed to use other inputs/variables for `default`.

**Comment by seblu** [comment]
1. The template is rendered when automation is fired. `cover` is a variable in the context of where `open_action` is substituted. I removed the end of the blueprint to simplify the report. Here is what is look like.

```yaml
action:
- variables:
    covers: !input covers
- choose:
  - alias: Open cover(s)
    conditions:
    - condition: trigger
      id: sunrise
    sequence: !input open_action
```
This is an elegant way to create default actions. IIRC, sequence cannot use templates.

2. [It's documented](https://www.home-assistant.io/docs/scripts/perform-actions/#use-templates-to-determine-the-attributes) :
> `You can use a template returning a native dictionary as well, which is useful if the attributes to be set depend on the situation`.

Not a perfect argument but let me remind you that the blueprint/automation works (and for months), so the core is accepting it.

**Comment by ildar170975** [comment]
> 1. `cover` is a variable in the context of where `open_action` is substituted

This is an important info.
Tried to reproduce your case, it seems to work OK, no errors in Log:
```
blueprint:
  name: test_input
  domain: automation
  input:
    input_INPUT_BOOLEAN:
    input_ACTION:
      default:
        - service: input_boolean.toggle
          target:
            entity_id: >-
              {{ INPUT_BOOLEAN }}
      selector:
        action:
trigger: []
action:
  - variables:
      INPUT_BOOLEAN: !input input_INPUT_BOOLEAN
  - sequence: !input input_ACTION
```
```
automation:
  - alias: test_input_1
    id: test_input_1
    use_blueprint:
      path: test/test_input.yaml
      input:
        input_INPUT_BOOLEAN: input_boolean.test_boolean_2
```
