### ISSUE TITLE
NFC Tags are not working. No delete. No edit. No update is possible.

### ISSUE THREAD

**Issue by Lutier2017** [home-assistant/frontend#21918]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

NFC tag are not working.
1) It is not possible to delete a script.
2) It is not possible to edit a script. After saving, no change is recorded.
3) Most of the pop-up menu items are disabled.

# I enter this:
```
alias: Tag AC-On-MasterBedroom is scanned
description: NFC Tag AC On Master Bedroom
trigger:
  - platform: tag
    tag_id: 04938d00-1412-456c-a720-dad9e57097c0
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.sac_2_mb
mode: queued
```

# This is what always remain:
```
description: ""
mode: single
trigger:
  - platform: tag
    tag_id: 04938d00-1412-456c-a720-dad9e57097c0
condition: []
action: []
alias: Tag AC-On-MasterBedroom is scanned
```

### Describe the behavior you expected

If I I update a Tag (NDC) logic, after I click SAVE the changes should remain, BUT they are lost.

### Steps to reproduce the issue

1. Open an existing Tag (NFC) logic.
2. Do changes.
3. Save changes. No error message.
4. Changes are not saved.
...

### What version of Home Assistant Core has the issue?

2024.8.3

### What was the last working version of Home Assistant Core?

2023.8.1

### In which browser are you experiencing the issue with?

Google Chrome Version 128.0.6613.120 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Additional information

![image](https://github.com/user-attachments/assets/4c5aa051-bfc5-4e16-8c04-ebdea40394da)
