### ISSUE TITLE
Sections failing when adding Layout_options to Sankey-Chart

### ISSUE THREAD

**Issue by viper539** [home-assistant/frontend#21922]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I wanted to extend the Layout Options of a existing working Sankey Chart (1 row, full width, to 2 rows) and it was then obverlaped by lower sections

### Describe the behavior you expected

I expected the Sankey Chart would be shown in full width and 2 rows

### Steps to reproduce the issue

1. have a Sankey Chart with one row, full width
2. extend it to 2 rows

### What version of Home Assistant Core has the issue?

2024.9.1

### In which browser are you experiencing the issue with?

Firefox 130.0 64-bit

### Which operating system are you using to run this browser?

Win10

### Problem-relevant frontend configuration

```yaml
i think it's this at the end of the chart-config:
layout_options:
  grid_columns: full

When it fails (reproduceable) it's this:
layout_options:
  grid_columns: full
  grid_rows: 2
```
