### ISSUE TITLE
"Trace Timeline" throws exceptions for `repeat` action

### ISSUE THREAD

**Issue by Guyohms** [home-assistant/frontend#21938]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On several of my automations, when I need to troubleshoot it, I find myself with an empty "Trace Timeline". I can see the steps details, download the trace in json format but the "Trace Timeline" tab is empty.

![image](https://github.com/user-attachments/assets/b020cf4d-ce39-4214-b8cb-0a2b0062d035)

It seems to happen more frequently when using a `repeat, while`.
Here's the most basic automation I've been able to write that causes this issue.

``` yaml
alias: New automation
description: ''
trigger: []
condition: []
action:
  - repeat:
      sequence:
        - stop: test
      while:
        - condition: state
          entity_id: input_boolean.test
          state: 'on'
mode: single
```

It seems to happen more frequently when using a `repeat, while`.
Maybe it's backend related, but I'll report it here since the automation works and the trace is generated for download.

### Describe the behavior you expected

See the trace timeline as with any other automations

### Steps to reproduce the issue

1. Write a new automation using the UI with a Reapeat/While
2. Add a stop action
3. Run
4. Check the "Trace Timeline". It should be empty

### What version of Home Assistant Core has the issue?

2024.9.1

### In which browser are you experiencing the issue with?

Google Chrome 128.0.6613.120

### Which operating system are you using to run this browser?

Windows 10
