### ISSUE TITLE
Thermostat Card: +/- Buttons Removed Upon Resizing

### ISSUE THREAD

**Issue by anandv85** [home-assistant/frontend#21943]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When the thermostat cards are placed side-by-side in a vertical stack card, the set temperature buttons "+" and "-" are removed automatically.
![Capture](https://github.com/user-attachments/assets/5e0ed4d5-ba98-4701-bbf2-7631a68ab55d)

### Describe the behavior you expected

The "+" and "-" buttons to be displayed as the thermostat card has enough space to show these 2 buttons.

### Steps to reproduce the issue

1. Create vertical stack card
2. Add horizontal stack card inside the vertical stack card
3. Add 2 thermostat cards inside the horizontal stack card
4. Observe the + and - buttons on the thermostat card not displayed

```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: thermostat
        entity: climate.thermostat_downstairs_thermostat
      - type: thermostat
        entity: climate.thermostat_upstairs_thermostat
```

### What version of Home Assistant Core has the issue?

2024.9.1
