### ISSUE TITLE
Issue with multiple Selector types when using "Add Field" in Script Editor.

### ISSUE THREAD

**Issue by Didgeridrew** [home-assistant/frontend#21997]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding Fields using the Visual Editor for Script, an `{}` is inserted after the selector type key instead of `null`. 

Example:

![image](https://github.com/user-attachments/assets/ec2439e4-6ad8-4ad7-9fa2-418d06ba3fa0)

This causes the script to error and become unavailable.  Many Selector types require further configuration using the YAML editor, but some do not require it and a few do not have any options beyond their key, so switching the the YAML editor to delete the `{}` should not be required.

### Describe the behavior you expected

If additional configuration is not required by the Selector, just choosing the selector type should be sufficient to have a working field variable.

### Steps to reproduce the issue

1. Start a new script in the script editor.
2. Add a Field using the "Add Field" button or Menu item
3. Pick a selector from the Selector drop down menu.  Most will work... but the 12 key-only types, like Template, Action, or Date definitely will.
4. Add any action in the sequence.
5. Save the script.

### What version of Home Assistant Core has the issue?

2024.9.1

### In which browser are you experiencing the issue with?

Firefox 130.0, Google Chrome 128.0.6613.137

### Which operating system are you using to run this browser?

Pop!_OS 22.04 LTS

**Comment by karwosts** [comment]
What exactly is the script error you are seeing?

I'm trying this but I don't see any errors, don't see any problem with having empty brackets there. 

```
alias: Entity Selector
sequence:
  - action: logbook.log
    metadata: {}
    data:
      message: Test Message
      name: test
fields:
  example:
    selector:
      entity: {}
    name: Example
    description: Example Description
description: ""
```

**Comment by AdarshPandey-07** [comment]
@Didgeridrew check again is the issue still persisting, if yes I would like to contribute.

**Comment by Didgeridrew** [comment]
> What exactly is the script error you are seeing?

The script setup fails with the following:

```
The script "zTest data field" (script.ztest_data_field) is not active because the configuration has errors.

Error:Only one type can be specified. Found for dictionary value @ data['fields']['testent']['selector']. Got OrderedDict().

To fix this error, [edit the script](https://johnsontolarha.duckdns.org/config/script/edit/ztest_data_field) to correct it, then save and reload the script configuration.
```

**Comment by karwosts** [comment]
Can you post the entire complete script that has this error (yaml not screenshot?)

**Comment by Didgeridrew** [comment]
```
alias: zTest data field
sequence:
  - action: persistent_notification.create
    metadata: {}
    data:
      message: "{{testent}}"
      title: This is a Test
fields:
  testent:
    selector:
      entity: {}
    name: TestEnt
description: ""
```
