### ISSUE TITLE
script fields: default values are different -> script unusable

### ISSUE THREAD

**Issue by Gifford47** [home-assistant/frontend#22005]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

i have a script that turns on a poolpump, waits a defined time of hours and then turns off the pump. the time has to be defined by the user but a default time should be defined. For my example is the default time 3 hours.
The problem:
If I execute the script via ui, the preselected time (the selectable blue bubble) is 4 hours but the number behind it is 3 hours. If I execute the script, it is not executed as expected (with 3 hours).
**Note: I don`t know if the issue exists also on the other field options.**
![image](https://github.com/user-attachments/assets/223af5b9-bb2b-416f-9c13-5d893368b05c)

### Describe the behavior you expected

Both the time on the selectable blue bubble and the time behind it are the default values from the script (f.e. 3 hours). If I change nothing and click "execute", the script will run with 3 hours as default value.
![image](https://github.com/user-attachments/assets/8b527168-c11c-484a-9eac-9d03d9f448cd)

### Steps to reproduce the issue

1. Create the following script:
```
alias: Pool Pump timer
sequence:
  - metadata: {}
    data: {}
    target:
      entity_id: switch.esp32_rail_switch12
    action: switch.turn_on
  - delay:
      hours: "{{timer}}"
      minutes: 0
      seconds: 0
      milliseconds: 0
  - metadata: {}
    data: {}
    target:
      entity_id: switch.esp32_rail_switch12
    action: switch.turn_off
fields:
  timer:
    selector:
      number:
        min: 0
        max: 8
        step: 1
    name: Pumpenlaufzeit
    default: 3
    description: Wir lange soll die Pumpe laufen?
    required: true
description: ""
mode: restart

```
2. Execute the script via UI
3. Only click Execute
4. The script shouldn`t be executed.

### What version of Home Assistant Core has the issue?

2024.9.2

### In which browser are you experiencing the issue with?

Google Chrome 128.0.6613.138

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
- type: entity
  entity: script.pool_pump
  name: Timer Poolpumpe
```
