### ISSUE TITLE
tap_action with service call broken

### ISSUE THREAD

**Issue by swifty99** [home-assistant/frontend#22046]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I created a multimode switch, described [here](https://community.home-assistant.io/t/best-solution-for-on-auto-off-switch/323121/9), and used by many people.
It worked perfectly since around 2 months. Since then taps are ignored. Other taps without service call in the same frontend have no issues.

the problematic code:
```
  - entity: sensor.kwl_mode_icon
    name: Belüftung
    tap_action:
      action: call-service
      service: input_select.select_next
      data:
        cycle: true
      target:
        entity_id: input_select.kwl_mode
```

this is a trick to change the icon of a select entity by showing a template and changing the select.

A restart of HA fixes the issue temporarily. I will measure the time how long it will take.

### Describe the behavior you expected

service call should be executed.

### Steps to reproduce the issue

See [here](https://community.home-assistant.io/t/best-solution-for-on-auto-off-switch/323121/9)

### What version of Home Assistant Core has the issue?

2024-09

### What was the last working version of Home Assistant Core?

2024-06

### In which browser are you experiencing the issue with?

companion, firefox, chrome, safari

### Which operating system are you using to run this browser?

macOS 15, iPadOS, Android 8
