### ISSUE TITLE
Not possible to delete selected attribute (Heading Card) (Beta 2024.10.0b0)

### ISSUE THREAD

**Issue by vwccvr6** [home-assistant/frontend#22088]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

It's not possible to delete selected attribute from an entity which is added to the new header card. 
When pressing an the small x nothing happens. 

I only have the Issue on Android Phone (APP and Chrome Browser on Android)

![image0](https://github.com/user-attachments/assets/fa4b86ce-aa2c-46af-a26b-dafd9ae88c34)

### Describe the behavior you expected

deleting the attribute

### Steps to reproduce the issue

1. create header card
2. add entity
3. select an attribute from the list
4. try to delete that attribute

### What version of Home Assistant Core has the issue?

2024.10.0b0

### Problem-relevant frontend configuration

```yaml
type: heading
icon: mdi:fridge
heading: Küche
heading_style: title
entities:
  - show_state: true
    show_icon: false
    entity: climate.wandthermostat_badezimmer
    state_content: current_temperature
```
