### ISSUE TITLE
The nested trigger `triggers` is breaking the automation editor

### ISSUE THREAD

**Issue by jlpouffier** [home-assistant/frontend#22101]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

2024.10 introduced a way for (advanced) users to nest triggers like that:

```yaml
description: ""
triggers:
  - triggers:
      - trigger: state
        entity_id:
          - light.salon_buffet_droit
        id: child_1
      - trigger: state
        entity_id:
          - light.salon_buffet_gauche
        id: child_2
```

Today this is not handled well by the UI, as show here:

![CleanShot 2024-09-26 at 16 17 20](https://github.com/user-attachments/assets/ecae2b93-4d39-4041-acd7-5b5665ca5d4a)

![CleanShot 2024-09-26 at 16 17 33](https://github.com/user-attachments/assets/d8e44f4a-48b9-4146-a59e-7da2e44c4349)

Even if this is a pretty advanced use case mostly built for blueprint creators, we should not break the UI especially knowing that users can take control of blueprints 

### Describe the behavior you expected

I would expected a nested block as similar to what we built for the `sequence` building block
Just a list, displaying the individual child triggers.

Similar to that
![CleanShot 2024-09-26 at 16 20 41](https://github.com/user-attachments/assets/f8fe5bbf-a868-4a74-aaea-2e76e6f3d106)

### Steps to reproduce the issue

1. Open Automation editor
2. Go into YAML mode
3. Coyp this:
```yaml
alias: "TEST NESTED TRIGGERS "
description: ""
triggers:
  - triggers:
      - trigger: homeassistant
        event: start
      - trigger: homeassistant
        event: shutdown
conditions: []
actions: []
mode: single
```
4. Back to visual mode

### What version of Home Assistant Core has the issue?

core-2024.10.0b0

### What was the last working version of Home Assistant Core?

core-2024.9.3

### In which browser are you experiencing the issue with?

Version 1.61.1 (54104) Chromium Engine Version 129.0.6668.59

### Which operating system are you using to run this browser?

macOS 14.6.1 (23G93)
