### ISSUE TITLE
No list with TriggerIDs in the "Triggered by" selection when creating automations.

### ISSUE THREAD

**Issue by vwccvr6** [home-assistant/frontend#22120]
### The problem

I set a trigger ID for an trigger. Normally these TriggerIDs are shown in an dropdownlist to select as "triggered by" condition. Since 2024.10.b0 these are not shown anymore. 

In the Code example the triggerID is set to "test" for an Trigger. But that is not visible in the GUI under condition.

![image](https://github.com/user-attachments/assets/749eaf94-9166-4ce5-9fad-fc5b62baf841)
![image](https://github.com/user-attachments/assets/720cebb2-1273-4ec2-acfb-b0b76765e765)

### What version of Home Assistant Core has the issue?

core-2024.10.0b1

### What was the last working version of Home Assistant Core?

core-2024.09.x

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
alias: Neue Automatisierung
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_boolean.test
    id: test
conditions:
  - condition: trigger
    id: test
```
