### ISSUE TITLE
Heading and tile in a vertical stack (Beta 2024.10.0b3)

### ISSUE THREAD

**Issue by DirkMu** [home-assistant/frontend#22141]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I put a heading and a tile in a vertical stack which is placed in a section, then the add card (+) appears behind the vertical stack. The stack overlies the section border. A new element would overlie the stack again.

![image](https://github.com/user-attachments/assets/fd2b27b1-4b4d-4900-b441-76addadb38f3)

### Describe the behavior you expected

The stack is considered

### Steps to reproduce the issue

1. Create a vertical stack
2. add a heading to the stack
3. add a tile to the stack
...

### What version of Home Assistant Core has the issue?

core-2024.10.0b3

### In which browser are you experiencing the issue with?

Google Chrome 128.0.6613.138

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: heading
    icon: mdi:door-closed
    heading: Haustür
    heading_style: title
    badges:
      - show_state: false
        show_icon: true
        entity: light.haustuer
      - show_state: false
        show_icon: true
        entity: binary_sensor.haustuer_pm_fb5_sensor_motion
  - features:
      - type: lock-commands
    type: tile
    entity: lock.haustur
    vertical: false
    hide_state: false
    state_content: last-changed
layout_options:
  grid_columns: 2
  grid_rows: 1
```
