### ISSUE TITLE
Light toggle does not respect brightness by turning light on from tile card

### ISSUE THREAD

**Issue by pascalwinters** [home-assistant/frontend#22152]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

With the tile card below the light is not enabled (when it's off) with given brightness but with the previous value for the brightness.
```
- type: tile
  entity: light.eettafel
  hide_state: true
  name: '‎ '
  tap_action:
    action: perform-action
    perform_action: light.toggle
    target:
      entity_id:
        - light.eettafel
    data:
      brightness_pct: 100
      transition: 3
```

When I do exactly the same in the Developer tools it works as expected with the following code:
```
action: light.toggle
target:
  entity_id: light.eettafel
data:
  transition: 3
  brightness_pct: 100
```

### Describe the behavior you expected

When the light is off, I expect that the light in on with the given brightness values.

### Steps to reproduce the issue

1. Turn light off from an 50% percentage value
2. Click on tile card
3. Light should be turned on with a brightness of 100%

### What version of Home Assistant Core has the issue?

2024.9.3

### In which browser are you experiencing the issue with?

Google Chrome 129.0.6668.70

### Which operating system are you using to run this browser?

Windows 11
