### ISSUE TITLE
Entities in Heading are only updated every 10s

### ISSUE THREAD

**Issue by envy** [home-assistant/frontend#22229]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a power sensor that updates multiple times per second. I used to have it in a tile card which was fine, the card updated mutliple times per seconds.

I now put that same sensor into a heading card as an entity. But there the sensor value is only updated every 10s or so (timed badly with a stopwatch).

### Describe the behavior you expected

Value in heading card updates as fast as the underlying entity changes its value.

If update frequency is a performance issue, I would propose to make it at least configurable down to 1s.

### Steps to reproduce the issue

1. Have sensor that updates more often that once per 10s,
2. Put that sensor into a heading as an entity.
3. (optional) put it also in a tile card to observe the difference.
...

### What version of Home Assistant Core has the issue?

2024.10.0

### In which browser are you experiencing the issue with?

Firefox 128.0, Edge

### Which operating system are you using to run this browser?

Windows 11 23H2

**Comment by piitaya** [comment]
Can you share your dashboard config? Do you also notice the same issue in safe mode?

I can not reproduce it on my side, entities are like regular cards or badge so the update is instant.

https://github.com/user-attachments/assets/51e4dba5-81e9-4580-a480-8771e37ac42e

**Comment by envy** [comment]
Sure:

```yaml
views:
  - type: sections
    max_columns: 3
    icon: mdi:flash
    path: leistung
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Erzeugung
          - type: custom:power-flow-card
            entities:
              solar: sensor.gesamt_solar_wirkleistung
              grid: sensor.cerbo_gx_victron_netz_gesamtwirkleistung
              battery:
                consumption: sensor.batterie_entladung_wirkleistung
                production: sensor.batterie_ladung_wirkleistung
              battery_charge: sensor.cerbo_gx_victron_batterie_soc
            watt_threshold: 900
          - type: tile
            entity: sensor.kueche_sued_power
          - type: tile
            entity: sensor.terasse_power
      - type: grid
        cards:
          - type: heading
            heading: Fluss
            heading_style: title
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.victron_grid_l1_power_30
                icon: ''
                state_content:
                  - name
                  - state
                name: L1
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.victron_grid_l2_power_30
                name: L2
                state_content:
                  - name
                  - state
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.victron_grid_l3_power_30
                name: L3
                state_content:
                  - name
                  - state
          - layout: horizontal
            height: 300
            unit_prefix: ''
            round: 0
            convert_units_to: ''
            co2_intensity_entity: sensor.co2_signal_co2_intensity
            gas_co2_intensity: 2351.6459999999997
            min_box_size: 3
            min_box_distance: 5
            show_states: true
            show_units: true
            sections:
              - entities:
                  - type: entity
                    children:
                      - sensor.gesamt_wirkleistung
                      - sensor.victron_netz_export_wirkleistung
                      - sensor.batterie_ladung_wirkleistung
                    entity_id: sensor.gesamt_solar_wirkleistung
                    name: Solar
                    color: var(--energy-solar-color)
                  - type: entity
                    children:
                      - sensor.gesamt_wirkleistung
                      - sensor.victron_netz_export_wirkleistung
                    entity_id: sensor.batterie_entladung_wirkleistung
                    name: Entladung
                    color: var(--energy-battery-out-color)
                  - type: entity
                    children:
                      - sensor.gesamt_wirkleistung
                      - sensor.batterie_ladung_wirkleistung
                    entity_id: sensor.victron_netz_import_wirkleistung
                    name: Netz
                    color: var(--energy-grid-consumption-color)
              - entities:
                  - type: entity
                    children:
                      - sensor.buro_pc_wirkleistung
                      - sensor.serverraum_rack_l1_wirkleistung
                      - sensor.serverraum_wand_l1_wirkleistung
                      - sensor.waschmaschine_wirkleistung
                      - sensor.trockner_wirkleistung
                      - sensor.gefrierschrank_wirkleistung
                      - sensor.prusa_mk4_wirkleistung
                      - fake.others
                    entity_id: sensor.gesamt_wirkleistung
                    name: ' '
                  - type: entity
                    children:
                      - sensor.victron_batterie_ladung_wirkleistung
                      - fake.victron_others
                    entity_id: sensor.batterie_ladung_wirkleistung
                    name: Victron
                    color: var(--energy-battery-in-color)
                  - type: entity
                    children: []
                    entity_id: sensor.victron_netz_export_wirkleistung
                    name: Export
                    color: var(--energy-grid-return-color)
              - entities:
                  - type: entity
                    children: []
                    entity_id: sensor.buro_pc_wirkleistung
                    name: Büro PC
                  - type: entity
                    children: []
                    entity_id: sensor.serverraum_rack_l1_wirkleistung
                    name: Rack
                  - type: entity
                    children: []
                    entity_id: sensor.serverraum_wand_l1_wirkleistung
                    name: Wand
                  - type: entity
                    children: []
                    entity_id: sensor.waschmaschine_wirkleistung
                    name: Waschmaschine
                  - type: entity
                    children: []
                    entity_id: sensor.trockner_wirkleistung
                    name: Trockner
                  - type: entity
                    children: []
                    entity_id: sensor.gefrierschrank_wirkleistung
                    name: Gefrierschrank
                  - type: entity
                    children: []
                    entity_id: sensor.prusa_mk4_wirkleistung
                    name: Prusa
                  - type: remaining_parent_state
                    children: []
                    entity_id: fake.others
                    name: Andere
                  - type: entity
                    children: []
                    entity_id: sensor.victron_batterie_ladung_wirkleistung
                    name: Ladung
                    color: var(--energy-battery-in-color)
                  - type: remaining_parent_state
                    children: []
                    entity_id: fake.victron_others
                    name: Verlust?
                    color: red
            type: custom:sankey-chart
            min_state: 0
            show_names: true
            min_box_height: 3
            wide: false
            layout_options:
              grid_columns: full
            throttle: 1000
            show_icons: false
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.cerbo_gx_victron_netz_l1_wirkleistung
                name: L1
                hide_state: false
                show_entity_picture: false
                vertical: false
              - type: tile
                entity: sensor.cerbo_gx_victron_netz_l2_wirkleistung
                name: L2
              - type: tile
                entity: sensor.cerbo_gx_victron_netz_l3_wirkleistung
                name: L3
            layout_options:
              grid_columns: full
              grid_rows: auto
        column_span: 2
      - type: grid
        cards:
          - type: heading
            heading: Speicher
            heading_style: title
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.cerbo_gx_victron_batterie_soc
                color: state
                tap_action:
                  action: more-info
              - type: entity
                entity: sensor.cerbo_gx_victron_system_status
          - type: tile
            entity: sensor.cerbo_gx_victron_batterie_spannung
            name: Spannung
          - type: tile
            entity: sensor.cerbo_gx_victron_batterie_strom
            icon: ''
            name: Strom
          - type: tile
            entity: sensor.victron_battery_system_maxcellvoltage
          - type: tile
            entity: sensor.victron_battery_system_mincellvoltage
          - type: tile
            entity: sensor.victron_battery_system_maxcelltemperature
          - type: tile
            entity: sensor.victron_battery_system_mincelltemperature
          - type: tile
            entity: sensor.victron_battery_soh
      - type: grid
        cards:
          - type: heading
            heading: Ersparnisse
          - type: tile
            entity: sensor.solar_ersparnis
            name: Aktuell
          - type: tile
            entity: sensor.solar_ersparnis_tag
            name: Heute
          - type: tile
            entity: sensor.solar_ersparnis_monat
            name: Monat
          - type: tile
            entity: sensor.solar_ersparnis_gesamt
            name: Gesamt
          - type: tile
            entity: sensor.solar_investition
    cards: []
    subview: false
```



https://github.com/user-attachments/assets/4d06672e-2cb0-4d15-a6c6-e87e1dd8a458
