### ISSUE TITLE
Relative Time for calendar start and end times in tile card

### ISSUE THREAD

**Issue by JosephAbbey** [home-assistant/frontend#22245]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The start and end times in tile cards are displayed as full date times, not as relative times like last changed and last triggered, etc.

### Describe the behavior you expected

The times should be in the format "X mins ago".

### Steps to reproduce the issue

Create a tile card for a calendar and add state content for the start time.

### What version of Home Assistant Core has the issue?

core-2024.10.1

### Problem-relevant frontend configuration

```yaml
type: tile
entity: calendar.slow_cooker
icon: mdi:calendar
color: orange
layout_options:
  grid_columns: 4
  grid_rows: 1
state_content:
  - message
  - end_time
```

### Additional information

Should be a simple fix, reuse the logic for last changed for start and end.
