### ISSUE TITLE
Dashboard graph incorrectly displaying unavailable data as extreamly large values rather than gaps

### ISSUE THREAD

**Issue by IWR69** [home-assistant/frontend#22246]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a dashboard chart that is displaying invalid humidity values for one of my sensors.

![HA Graph](https://github.com/user-attachments/assets/2dec00b5-8bf9-4ad2-931d-22236f27b60a)

This is the yaml for the graph...

```
chart_type: line
period: 5minute
type: statistics-graph
entities:
  - entity: sensor.bedroom_humidity
    name: Bedroom
  - entity: sensor.living_room_humidity
    name: Lounge
  - entity: sensor.office_humidity
    name: Office
days_to_show: 2
hide_legend: false
```

The Living Room Humidity (Lounge) sensor is actually a Group Helper that calculates the arithmetic mean from two humidity sensors ignoring non numeric data. One of these sensors has been unavailable for some time and the other has recorded at least tree unavailable readings resulting in the group helper also recording unavailable readings. These tie up with the last two spikes but I cannot find any unavailable data around the time of the first spike. Downloaded data can be found below.

When I click on the spike I get the graph below that clearly shows the 2nd and 3rd spikes...

![HA History 1](https://github.com/user-attachments/assets/124925dd-f2c2-4e20-b50a-e47de8b0a6c3)

But when I drill into this I cannot see any spikes. Maybe this is just a function of these graphs but I've added them just in case they are helpful. 

![HA History Show More](https://github.com/user-attachments/assets/256beeaf-dc95-4c13-9a87-28d299b5334b)

And here is the downloaded data from this chart...
```
entity_id,state,last_changed
sensor.living_room_humidity,59.0,2024-10-03T23:00:00.000Z
sensor.living_room_humidity,57.0,2024-10-04T00:46:05.931Z
sensor.living_room_humidity,55.0,2024-10-04T04:05:35.507Z
sensor.living_room_humidity,57.0,2024-10-04T13:08:39.252Z
sensor.living_room_humidity,55.0,2024-10-05T05:03:43.598Z
sensor.living_room_humidity,53.0,2024-10-05T05:58:41.337Z
sensor.living_room_humidity,55.0,2024-10-05T07:25:26.626Z
sensor.living_room_humidity,unavailable,2024-10-05T08:00:15.339Z
sensor.living_room_humidity,55.0,2024-10-05T08:00:33.437Z
sensor.living_room_humidity,53.0,2024-10-05T08:48:46.812Z
sensor.living_room_humidity,unavailable,2024-10-05T11:07:21.904Z
sensor.living_room_humidity,53.0,2024-10-05T11:07:37.045Z
sensor.living_room_humidity,unavailable,2024-10-05T11:08:30.815Z
sensor.living_room_humidity,53.0,2024-10-05T11:08:46.441Z
```

I've also checked Developer Tools, Statistics and the Living Room Humidity shows as "No Issue" so I can't remove this invalid data.

### Describe the behavior you expected

I would expect any unavailable data to appear as a gap in the chart. Displaying extremely large values rather than gaps has resulted in a graph that obscures the valid data while highlighting invalid and inaccurate data.

### Steps to reproduce the issue

I guess simply adding an entity to a dashboard graph that contains some unavailable data would produce the same results.

### What version of Home Assistant Core has the issue?

2024.10.1

### In which browser are you experiencing the issue with?

Firefox 131.0 (also tested on Chrome 129.0.6668.90)

### Which operating system are you using to run this browser?

Windows 11 23H2 22631.4169

### State of relevant entities

```txt
Living Room Hunidity (current state 53.0)
state_class: measurement
entity_id: sensor.dyson_humidity, sensor.nest_thermostat_humidity
unit_of_measurement: %
device_class: humidity
icon: mdi:water-percent
friendly_name: Living Room Humidity

Dyson Humidity (current state 'unavailable')
restored: true
state_class: measurement
device_class: humidity
friendly_name: Dyson Humidity
supported_features: 0
unit_of_measurement: %

Nest Thermostat Humidity (current state 53)
state_class: measurement
unit_of_measurement: %
device_class: humidity
friendly_name: Nest Thermostat Humidity
```

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: 5minute
type: statistics-graph
entities:
  - entity: sensor.bedroom_humidity
    name: Bedroom
  - entity: sensor.living_room_humidity
    name: Lounge
  - entity: sensor.office_humidity
    name: Office
days_to_show: 2
hide_legend: false
```
