### ISSUE TITLE
Dynamic URL in tap_action redirects to localhost

### ISSUE THREAD

**Issue by jrhessels** [home-assistant/frontend#22256]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm encountering an issue where using a dynamic URL in the tap_action results in the URL redirecting to localhost instead of the correct external URL. The same dynamic URL works correctly in a markdown card, but not within the other dashboard card.

Clicking the chip redirects the browser to localhost instead of the expected external URL.

### Describe the behavior you expected

The card should redirect to the dynamic URL specified by the release_url attribute from the state_attr function.

### Steps to reproduce the issue

1. Add the following YAML configuration to a Lovelace dashboard:
2. Ensure the entity has a valid release_url attribute.
3. Click on the chip and observe that it redirects to localhost instead of the expected URL.
...

### What version of Home Assistant Core has the issue?

v2024.9.3

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

google chrome

### Which operating system are you using to run this browser?

windows

### State of relevant entities

```txt
The dynamic URL works correctly in a markdown card, as shown below:
******** Yaml ***************
type: markdown
content: >
[Click here]({{ state_attr('update.zigbee2mqtt_firmware_update', 'release_url') }})

Please let me know if there’s any additional information or logs I can provide.
```

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Zigbee2MQTT Updates
    subtitle: |+

  - type: custom:mushroom-chips-card
    chips:
      - type: template
        icon: mdi:web
        icon_color: blue
        content: Release Changelog
        tap_action:
          action: url
          url_path: >
            {{ state_attr('update.zigbee2mqtt_firmware_update', 'release_url')
            }}
      - type: template
        entity: update.hacsa_update
        content: >-
          Installed v{{ state_attr('update.zigbee2mqtt_firmware_update',
          'installed_version') }}
        icon_color: green
        icon: mdi:package-variant-closed
        tap_action:
          action: none
      - type: template
        entity: update.hacs_update
        content: >-
          Latest v{{ state_attr('update.zigbee2mqtt_firmware_update',
          'latest_version') }}
        icon_color: orange
        icon: mdi:package-variant-closed
        tap_action:
          action: none
  - type: custom:mushroom-update-card
    entity: update.bathroom_extractor
    layout: horizontal
    show_buttons_control: true
  - type: custom:mushroom-update-card
    entity: update.bedroom_1
    layout: horizontal
    show_buttons_control: true
  - type: custom:mushroom-update-card
    entity: update.dishwasher
    layout: horizontal
    show_buttons_control: true
  - type: custom:mushroom-update-card
    entity: update.livingroom_dimmer
    layout: horizontal
    show_buttons_control: true
  - type: custom:mushroom-update-card
    entity: update.livingroom_motion
    layout: horizontal
    show_buttons_control: true
  - type: custom:mushroom-update-card
    entity: update.tumble_dryer
    layout: horizontal
    show_buttons_control: true
  - type: custom:mushroom-update-card
    entity: update.office_heater
    layout: horizontal
    show_buttons_control: true
  - type: custom:mushroom-update-card
    entity: update.washingmachine
    layout: horizontal
    show_buttons_control: true
layout_options:
  grid_columns: 4
  grid_rows: 8
```

### Javascript errors shown in your browser console/inspector

```txt
none
```
