### ISSUE TITLE
Automation Action adds deprecated `service` tag on edit through Visual Editor

### ISSUE THREAD

**Issue by Veillax** [home-assistant/frontend#22269]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

While editing an automation action `scene.turn_on` in the visual editor, when changing the scene entity, the yaml is updated to include the deprecated `service` key

Before editing action:
``` yaml
action: scene.turn_on
metadata: {}
target:
  entity_id: scene.3d_printer_status_attention_needed
```
After editing action:
``` yaml
action: scene.turn_on
metadata: {}
target:
  entity_id: scene.3d_printer_status_finished
service: scene.turn_on
```

### Describe the behavior you expected

The visual editor should only update the `entity_id` key and not include the `service` key

### Steps to reproduce the issue

1. Create a new automation
2. Add a new action, select Scene: Activate
3. Change the scene

### What version of Home Assistant Core has the issue?

2024.10.1

### In which browser are you experiencing the issue with?

Google Chrome 129.0.6668.90 
(Also tested using a custom Wall Panel android app, but I don't know where to find the browser version)

### Which operating system are you using to run this browser?

Windows 11 Home 23H2

### Additional information

https://youtu.be/XhG5WRcqgBc
