### ISSUE TITLE
Transition time not honored turning off WLED light

### ISSUE THREAD

**Issue by galets** [home-assistant/frontend#22282]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am running hassio with WLED lights. Firmware versions are 14.3 and 14.4

I am using following automation to dim the lights for 2 hours until they are fully off (xxxxxxx is redacted for privacy):

```
alias: xxxxxxx-lights-off
description: ""
triggers:
  - at: "22:00:00"
    trigger: time
conditions: []
actions:
  - action: light.turn_off
    target:
      device_id:
        - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    data:
      transition: 7200
```

Lights don't dim down, instead turn fully off in several minutes

### Describe the behavior you expected

Lights gradually dim for 2 hours until fully off

### Steps to reproduce the issue

1. create automation (see yaml)
2. turn on WLED
3. wait for 10pm
4. observe that lights don't gradually dim
...

### What version of Home Assistant Core has the issue?

2024.10.1

### In which browser are you experiencing the issue with?

not a browsert issue

### Which operating system are you using to run this browser?

not a browsert issue
