### ISSUE TITLE
Constant selector not working when it is within a section

### ISSUE THREAD

**Issue by tr4nt0r** [home-assistant/frontend#22297]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I defined an action in `services.yaml` and wanted to use a constant selector. I tried it in the developer tools and when checking the box the attribute `clear_date` should be submitted with the value true in the service data but that doesn't happen. When switching to the yaml view i could confirm that the field was not added. 

This is from my `services.yaml` (truncated)
```yaml
update_daily:
  fields:
    duedate_options:
      collapsed: true
      fields:
        date:
          required: false
          selector:
            date:
        clear_date:
          selector:
            constant:
              value: true
              label: Enabled
```

I tried defining the selector outside of a section and then it worked as expected.

Tested with Chrome, Edge and the Home Assistant mobile app on Android

### Describe the behavior you expected

I expect that the value of the constant selector is submitted in the service data if the box is checked

### Steps to reproduce the issue

1. add a constant selector to a section in `services.yaml` (e.g. kitchen sink integration) 
2. go to the action in developer tools
3. check the box of the constant selector
4. Click on perform action. 
5. The kitchen sink action should show an exception no extra fields allowed but that does not happen
6. When switching to the yaml view the field name and value is not listed under date{} 
...

### What version of Home Assistant Core has the issue?

core-2024.11.0.dev0 (HEAD at 00a037c786)

### In which browser are you experiencing the issue with?

Google Chrome 129.0.6668.90 

### Which operating system are you using to run this browser?

Windows 11 Home v. 21H2 build 22000.2538

### Javascript errors shown in your browser console/inspector

```txt
No js errors in the console
```

### Additional information

Example `services.yaml` of kitchen sink integration with added constant selectors
```
test_service_1:
  fields:
    field_1:
      required: true
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds
    field_2:
      required: true
      selector:
        select:
          options:
            - "off"
            - "auto"
            - "cool"
    const1:
      selector:
        constant:
          value: true
          label: Enabled
    advanced_fields:
      collapsed: true
      fields:
        field_3:
          selector:
            number:
              min: 0
              max: 24
              unit_of_measurement: hours
        field_4:
          selector:
            select:
              options:
                - "forward"
                - "reverse"
        const2:
          selector:
            constant:
              value: true
              label: Enabled
```
UI view with both constant selectors checked:
![image](https://github.com/user-attachments/assets/8a1717b3-13f4-4ab8-806e-db89238521e8)

When switching to yaml view, const1 is set but const2 not:
![image](https://github.com/user-attachments/assets/275d764e-f893-460f-a238-f4a8c800894e)
