### ISSUE TITLE
empty 'stack card' in Section nearly impossible to edit

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#22317]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

if you add an empty stack card (horizontal or vertical) and close the dialog without adding another card (maybe by mistake) - it is nearly impossible to open the card again for any modification / correction.

In the red area shown in this screenshot, the stack card is placed, using the code below:
![image](https://github.com/user-attachments/assets/f0933ec6-9eea-4781-86fe-c0d7c2f764a5)

```
type: grid
cards:
  - title: Energieverteilung heute
    type: energy-distribution
    link_dashboard: false
  - type: energy-solar-consumed-gauge
  - type: energy-self-sufficiency-gauge
  - type: energy-grid-neutrality-gauge
  - type: horizontal-stack
    cards: []
column_span: 1
```

Right now, the only way to edit the card - or even delete it is by using the yaml editor of the section itself.

### Describe the behavior you expected

you sould be able to edit the added card by showing the editor icon.

### Steps to reproduce the issue

1. add a vertical or horizontal stac card to the section
2. save the change without adding any other card to the stack
3.
...

### What version of Home Assistant Core has the issue?

2024.10.1
