### ISSUE TITLE
New dashboard row layout issue (mini-graph) 

### ISSUE THREAD

**Issue by jandechent** [home-assistant/frontend#22352]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I know you warned about using rows. In the home Assistant app and in portrait mode this happens. Notice how the mini-graphs do overlap. 
![IMG_1370](https://github.com/user-attachments/assets/3f7b05a7-b3e6-4240-a25e-c5252a97ffec)

In editing mode, the edit field also seems smaller than it should be: 
![20241014T091003-Übersicht – SG10](https://github.com/user-attachments/assets/33ae9163-c3ca-4965-9405-65b243da2c71)

### Describe the behavior you expected

In landscape or on desktop it works as expected: ![IMG_1371](https://github.com/user-attachments/assets/c610b5ee-78af-40b9-b5b3-5d84b4e658cf)

### Steps to reproduce the issue

```
type:grid
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.kamin_temp_object
        color: red
        name: Kamin
    hours_to_show: 48
    points_per_hour: 3
    decimals: 0
    lower_bound: 25
    upper_bound: 80
    show:
      icon: false
      state: true
    height: 300
    line_width: 2
    layout_options:
      grid_columns: 4
      grid_rows: 2
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.heizung_auslastung_heizung_eingangsseite
        show_legend: false
        show_state: false
        name: Heizung
      - entity: sensor.heizung_auslastung_heizung_gartenseite
        show_legend: false
        show_state: false
    hours_to_show: 48
    points_per_hour: 3
    decimals: 0
    lower_bound: 0
    upper_bound: 100
    show:
      icon: false
      state: false
    height: 150
    line_width: 2
    layout_options:
      grid_columns: 4
  - type: gauge
    entity: sensor.gasverbrauch_sum_24h
    name: ""
    max: 30
    min: 0
    height: 100
    needle: true
    segments:
      - from: 0
        color: var(--success-color)
      - from: 5
        color: var(--warning-color)
      - from: 15
        color: var(--error-color)
column_span: 2

```

### What version of Home Assistant Core has the issue?

24.10.2
