### ISSUE TITLE
Error while loading page dashboard config (Home Assistant Green)

### ISSUE THREAD

**Issue by krommetje3108** [home-assistant/frontend#22408]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Unable to enter config in browser instance, the android app works normally. The settings cannot be entered in Safe Mode either.

### Describe the behavior you expected

Expected to be able to enter settings

### Steps to reproduce the issue

1.Click on settings
2."Error while loading page dashboard."
...

### What version of Home Assistant Core has the issue?

2024.10.2

### In which browser are you experiencing the issue with?

Firefox Canonical-002-1.0, Vivaldi 6.9.3447.54, Edge 128.0.2739.54, Brave Versie 1.69.160 Chromium: 128.0.6613.114

### Which operating system are you using to run this browser?

Ubuntu 24.04.1 LTS

### Problem-relevant frontend configuration

```yaml
configuration.yaml:

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
telegram_bot:
  - platform: polling
    api_key: X
    allowed_chat_ids:
      - X
# Example configuration.yaml entry for the notifier
notify:
  - platform: telegram
    name: "habot"
    chat_id: X
  - name: "emailtomarp"
    platform: smtp
    server: "smtp.strato.de"
    sender: "home.assistant@krommetje.nl"
    recipient: "peter@marp.nl"
    port: 465
    timeout: 15
    username: "home.assistant@krommetje.nl"
    password: "X"
    sender_name: "Home Assistant"
    encryption: tls
  - name: "emailtoankie"
    platform: smtp
    server: "smtp.strato.de"
    sender: "home.assistant@krommetje.nl"
    recipient: "X"
    port: 465
    timeout: 15
    username: "home.assistant@krommetje.nl"
    password: "X"
    sender_name: "Home Assistant"
    encryption: tls
#
rest_command:
  voordeurrolluikopen:
    url: "https://maker.ifttt.com/trigger/Voordeur_open/with/key/X"
    method: put
    content_type: "application/x-www-form-urlencoded"
  voordeurrolluikdicht:
    url: "https://maker.ifttt.com/trigger/Voordeur_dicht/with/key/X"
    method: put
    content_type: "application/x-www-form-urlencoded"
  tuindeurrolluikopen:
    url: "https://maker.ifttt.com/trigger/Tuindeur_open/with/key/X"
    method: put
    content_type: "application/x-www-form-urlencoded"
  tuindeurrolluidicht:
    url: "https://maker.ifttt.com/trigger/Tuindeur_dicht/with/key/X"
    method: put
    content_type: "application/x-www-form-urlencoded"
  airquality:
    url: "http://192.168.178.96:8080/json.htm?type=command&param=getdevices&rid=18"
    method: get
    content_type: "application/x-www-form-urlencoded"
#
## Buienalarm instaleren via hacs
#===============================================================================
sensor: # ervoor weg halen als dit je eerste sensor is.
  - platform: buienalarm
    timeframe: 30
    name: buienalarm
    monitored_conditions:
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      - next_rain_forecast
#===============================================================================
  - platform: template
    sensors:
      buienalarm_precipitation_forecast_level:
        friendly_name: Buienalarm Neerslagintensiteit niveau
        value_template: >
          {% set value =
            states('sensor.buienalarm_precipitation_forecast_average')
            |float %}
          {% if value < 0.1 %}
            0
          {% elif value < 1 %}
            1
          {% elif value < 3 %}
            2lucht
          {% elif value < 10 %}
            3
          {% elif value >=10 %}
            4
          {% else %}
            unavailable
          {% endif %}
        icon_template:
          hass:weather-pouring
        attribute_templates:
          label: >
            {% set value =
              states('sensor.buienalarm_precipitation_forecast_average')
              |float %}
            {% if value < 0.1 %}
              Geen neerslag
            {% elif value < 1 %}
              Lichte neerslag
            {% elif value < 3 %}
              Matige neerslag
            {% elif value < 10 %}
              Zware neerslag
            {% elif value >=10 %}
              Zware buien
            {% else %}
              unavailable
            {% endif %}
#
# Example configuration.yaml entry
ifttt:
  key: X
 #
shell_command:
    copy_doorbell_img: cp /config/nest/event_media{{ path }} /config/www/doorbell.mp4
    move_lastmotion_img: mv /config/nest/event_media/32892fdcd41d17ad6820037271a72738/*.* /config/www/
#
wake_on_lan:
scrape:
  - resource: https://www.knmi.nl/nederland-nu/weer/waarschuwingen/noord-baraban
    sensor:
      - select: "div.alert__heading"
        name: "knmi weercode"

  - resource: https://www.knmi.nl/nederland-nu/weer/waarschuwingen/noord-baraban
    sensor:
      - select: "a.alert__description"
        name: "knmi weer waarschuwing"
#
template:
  sensor:
    - name: Gas Verbruik Per Dag
      unique_id: gas-verbruik-per-dag
      unit_of_measurement: m3 
      device_class: gas
      icon: mdi:gauge
      state: >
        {{ states.input_number.gas_verbruik_per_dag.state }}
    - name: Kosten gasverbruik per dag
      unique_id: kosten-gasverbruik-per-dag
      unit_of_measurement: €
      icon: mdi:currency-eur
      state: >
        {{ states.input_number.gas_verbruik_per_dag.state |float * 0.85 /1000 }}
#
```

### Javascript errors shown in your browser console/inspector

```txt
hass-router-page.ts:160 Error loading page dashboard SyntaxError: Unexpected identifier 'start' (at 58222.KZ4Iq0GeOuI.js:1:12697)
(anonymous)	@	hass-router-page.ts:160
Promise.catch		
value	@	hass-router-page.ts:158
performUpdate	@	reactive-element.ts:1329
scheduleUpdate	@	reactive-element.ts:1261
_$Ej	@	reactive-element.ts:1233
await in _$Ej		
requestUpdate	@	reactive-element.ts:1208
_$Eu	@	reactive-element.ts:946
w	@	reactive-element.ts:931
n	@	hass-router-page.ts:48
i	@	subscribe-mixin.ts:13
t	@	ha-panel-config.ts:371
k	@	scoped-custom-element-registry.js:385
t	@	scoped-custom-element-registry.js:236
value	@	hass-router-page.ts:296
value	@	hass-router-page.ts:316
(anonymous)	@	hass-router-page.ts:214
Promise.then		
value	@	hass-router-page.ts:205
performUpdate	@	reactive-element.ts:1329
scheduleUpdate	@	reactive-element.ts:1261
_$Ej	@	reactive-element.ts:1233
await in _$Ej		
requestUpdate	@	reactive-element.ts:1208
set	@	reactive-element.ts:726
value	@	hass-router-page.ts:284
await in value		
value	@	partial-panel-resolver.ts:214
value	@	partial-panel-resolver.ts:85
performUpdate	@	reactive-element.ts:1327
scheduleUpdate	@	reactive-element.ts:1261
_$Ej	@	reactive-element.ts:1233
await in _$Ej		
requestUpdate	@	reactive-element.ts:1208
_$Eu	@	reactive-element.ts:946
w	@	reactive-element.ts:931
n	@	hass-router-page.ts:48
r	@	partial-panel-resolver.ts:41
k	@	scoped-custom-element-registry.js:385
t	@	scoped-custom-element-registry.js:236
u	@	lit-html.ts:1129
g	@	lit-html.ts:1543
_$AI	@	lit-html.ts:1384
q	@	lit-html.ts:2183
update	@	lit-element.ts:165
performUpdate	@	reactive-element.ts:1329
scheduleUpdate	@	reactive-element.ts:1261
_$Ej	@	reactive-element.ts:1233
await in _$Ej		
requestUpdate	@	reactive-element.ts:1208
_$Eu	@	reactive-element.ts:946
w	@	reactive-element.ts:931
C	@	lit-element.ts:115
r	@	home-assistant-main.ts:52
k	@	scoped-custom-element-registry.js:385
t	@	scoped-custom-element-registry.js:236
u	@	lit-html.ts:1129
g	@	lit-html.ts:1543
_$AI	@	lit-html.ts:1384
q	@	lit-html.ts:2183
update	@	lit-element.ts:165
(anonymous)	@	superPropGet.js:6
value	@	home-assistant.ts:95
performUpdate	@	reactive-element.ts:1329
scheduleUpdate	@	reactive-element.ts:1261
_$Ej	@	reactive-element.ts:1233
await in _$Ej		
requestUpdate	@	reactive-element.ts:1208
set	@	reactive-element.ts:726
value	@	hass-base-mixin.ts:56
_updateHass	@	context-mixin.ts:102
_selectNumberFormat	@	translations-mixin.ts:191
(anonymous)	@	translations-mixin.ts:131
Promise.then		
hassConnected	@	translations-mixin.ts:121
hassConnected	@	themes-mixin.ts:58
hassConnected	@	auth-mixin.ts:24
(anonymous)	@	superPropGet.js:6
value	@	home-assistant.ts:166
initializeHass	@	connection-mixin.ts:214
value	@	home-assistant.ts:246
await in value		
value	@	home-assistant.ts:100
_$AE	@	reactive-element.ts:1376
performUpdate	@	reactive-element.ts:1343
scheduleUpdate	@	reactive-element.ts:1261
_$Ej	@	reactive-element.ts:1233
await in _$Ej		
requestUpdate	@	reactive-element.ts:1208
_$Eu	@	reactive-element.ts:946
w	@	reactive-element.ts:931
C	@	lit-element.ts:115
F	@	hass-base-mixin.ts:6
(anonymous)	@	context-mixin.ts:23
(anonymous)	@	logging-mixin.ts:24
(anonymous)	@	panel-title-mixin.ts:12
(anonymous)	@	haptic-mixin.ts:38
(anonymous)	@	url-sync-mixin.ts:29
(anonymous)	@	dialog-manager-mixin.ts:28
(anonymous)	@	notification-mixin.ts:5
(anonymous)	@	connection-mixin.ts:42
(anonymous)	@	disconnect-toast-mixin.ts:18
(anonymous)	@	sidebar-mixin.ts:28
(anonymous)	@	action-mixin.ts:18
(anonymous)	@	more-info-mixin.ts:16
(anonymous)	@	state-display-mixin.ts:7
(anonymous)	@	translations-mixin.ts:71
(anonymous)	@	themes-mixin.ts:24
(anonymous)	@	auth-mixin.ts:14
Pe	@	hass-element.ts:23
(anonymous)	@	quick-bar-mixin.ts:24
r	@	home-assistant.ts:48
k	@	scoped-custom-element-registry.js:385
t	@	scoped-custom-element-registry.js:236
window.CustomElementRegistry.define	@	scoped-custom-element-registry.js:85
finisher	@	custom-element.ts:41
runClassFinishers	@	decorate.js:172
a	@	decorate.js:10
(anonymous)	@	home-assistant.ts:34
Show less
```

### Additional information

system runs on Home Assistant Green
