### ISSUE TITLE
allow_bypass_login Not working as intended

### ISSUE THREAD

**Issue by jonylentzmc** [home-assistant/frontend#22400]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When enabling allow_bypass_login: true in configuration.yaml it is expected to bypass the login screen according to the documentation.

### Describe the behavior you expected

The actual behavior is: the log in screen is still shown, you have to manually click on Trusted Networks in order to log in
This is frustrating as I have a tablet as a dashboard and every 2 days or so it logs out for no reason... sometimes in the middle of the night blasting a white log-in screen into my room

### Steps to reproduce the issue

1.Add allow_bypass_login in configuration.yaml
2.Restart Home Assistant
3.Try to access Home Assistant using a browser from a trusted network
...

### What version of Home Assistant Core has the issue?

2024.10.2

### What was the last working version of Home Assistant Core?

I have seen this issue on Github all the way back to 2019! 

### In which browser are you experiencing the issue with?

WallPanel; tried with chrome and firefox from a pc same behavior

### Which operating system are you using to run this browser?

Android, Windows

### Problem-relevant frontend configuration

```yaml
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.15.92/32
        - 192.168.15.66/32
      trusted_users:
        192.168.15.92: 15[redacted user ID]04
        192.168.15.66: 15[redacted user ID]04
      allow_bypass_login: true
```
