### ISSUE TITLE
Some automations slow to load/edit in visual editor

### ISSUE THREAD

**Issue by mparsche** [home-assistant/frontend#22491]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The home assistant interface is slow when trying to edit some automations in the visual editor. The UI is painfully slow and it appears to hang the browser window. This happens regardless of browser, and can prevent navigating away from the affected automation.

### Describe the behavior you expected

I expect using the visual editor to be responsive.

### Steps to reproduce the issue

1. Go to settings/automations
2. Open an automation

### What version of Home Assistant Core has the issue?

2024.10.3

### Problem-relevant frontend configuration

```yaml
This automation causes the issue:

alias: KLE High Temp (Rest Nest and Furnace)
description: ""
triggers:
  - enabled: true
    minutes: /30
    trigger: time_pattern
conditions:
  - condition: numeric_state
    entity_id: sensor.klenestcurrenttemp
    above: input_number.input_number_kle_nest_alert_high_temp_minus_half
actions:
  - data:
      title: KLE Nest high Temperature RESTART PROCESS
      message: >-
        KLE Nest and Furnace RESET proess started. Current temp is {{
        states("sensor.klenestcurrenttemp") }} 
      target:
        - 19999999999
    action: notify.twilio_sms
  - target:
      entity_id: climate.hallway_2
    data:
      hvac_mode: "off"
    action: climate.set_hvac_mode
    enabled: false
  - delay: "00:00:15"
  - target:
      entity_id: climate.hallway_2
    data:
      hvac_mode: heat_cool
    action: climate.set_hvac_mode
    enabled: false
  - delay: "00:03:00"
  - metadata: {}
    data: {}
    target:
      entity_id: switch.scene_capable_switch_on_off
    action: switch.turn_off
  - delay: "00:00:20"
  - metadata: {}
    data: {}
    target:
      entity_id: switch.scene_capable_switch_on_off
    action: switch.turn_on
  - data:
      title: KLE Nest High Temperature RESTART PROCESS
      message: >-
        KLE Nest and Furnace RESET proess COMPLETED. Current temp is {{
        states("sensor.klenestcurrenttemp") }} 
      target:
        - 19999999999
    action: notify.twilio_sms
mode: single
```
