### ISSUE TITLE
Layout overlap with combination of vertical and horizontal stacks

### ISSUE THREAD

**Issue by GeoffWy** [home-assistant/frontend#22515]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

A combination of vertical and horizontal stack elements does not layout correctly, causing a later element to overlap another in the display. The layout is correct in edit mode.
Problem shows in Chrome and also in the Android mobile app.

### Describe the behavior you expected

Cards should not overlap

### Steps to reproduce the issue

1. Configure a set of cards as in the code below. The code is a complete dashboard view.
2. The second element of the vertical stack overlaps the first element of the first vertical stack.
3. The problem is that the first element (with name "Auto / Manual") is printed too large in the vertical dimension

_edited to show correctly formatted code_

```title: Fault
path: fault
type: panel
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: true
            icon_height: 50px
            type: button
            entity: input_boolean.irig_auto_manual
            name: Auto / Manual
            show_state: false
            tap_action:
              action: more-info
          - type: vertical-stack
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: input_boolean.irig_start_1_enable
                icon_height: 30px
                name: Enable start time
              - show_name: false
                show_icon: false
                show_state: true
                type: glance
                entities:
                  - entity: input_datetime.start_watering
          - type: vertical-stack
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: input_boolean.irig_start_2_enable
                icon_height: 30px
                name: Enable start time
              - show_name: false
                show_icon: false
                show_state: true
                type: glance
                entities:
                  - entity: input_datetime.irig_start_time_2
        title: Automatic timer settings
      - type: tile
        entity: timer.irig_line_1_timer
        vertical: false
        hide_state: false
        state_content:
          - duration
          - remaining_time
        tap_action:
          action: perform-action
          perform_action: timer.start
          target:
            entity_id: timer.irig_line_1_timer
          data: {}
        name: Line 1 timer
```

### What version of Home Assistant Core has the issue?

2024.10.3

### In which browser are you experiencing the issue with?

Google Chrome 130.0.6723.70

### Which operating system are you using to run this browser?

Windows 10

**Comment by GeoffWy** [comment]
Adding some screenshots of the problem.
Dashboard display faulty:
![image](https://github.com/user-attachments/assets/c586913e-54d3-42c2-978b-103faf164b59)

Editor display formatted correctly:
![image](https://github.com/user-attachments/assets/db1fc7c5-d2ee-466d-b266-91372483a386)

**Comment by ildar170975** [comment]
Suggest to post a FORMATTED code and a screenshot. 
Guess this is a duplicate of https://github.com/home-assistant/frontend/issues/18972

**Comment by GeoffWy** [comment]
Yes it does look like the same issue as 18972, though I note that that issue keeps being marked as stale with no progress.

I tried to put formatted code using the code formatting button (<>) and what you saw in my post was the result. How should I add formatted code correctly please?

**Comment by ildar170975** [comment]
To format a code properly, place it between triple quotes, not single ones. 

> Yes it does look like the same issue as 18972, though I note that that issue keeps being marked as stale with no progress.

Does not mean that “the more duplicates exist - the faster the issue is solved”.

**Comment by SnowyJaguar1034** [comment]
I'm think I'm having a similar issue where the card titles on some of my horizontal cards are overlapping with the card above. I'm not sure if I have a misconfiguration, if this is a bug or if there's a blank card I should be putting between my cards here.
![image](https://github.com/user-attachments/assets/2de2e66e-ab48-4171-981f-37d2a7c25450)

This is the full YML of the view this issue is happening on, at the moment what's seen in the screen shot is all that's in this view.
```yml
    type: sections
    max_columns: 4
    title: Summary
    path: summary
    dense_section_placement: false
    sections:
      - type: grid
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: light.hallway_upstairs_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - brightness
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.hallway_downstairs_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - brightness
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
            grid_options:
              columns: full
            title: Hallway Lights
          - type: horizontal-stack
            cards:
              - type: tile
                entity: light.snug_lamp_light
                vertical: false
                hide_state: false
                show_entity_picture: false
                state_content:
                  - state
                  - brightness
                  - effect
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.flower_lamp
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
            grid_options:
              columns: full
            title: Kitchen Lights
          - type: horizontal-stack
            cards:
              - type: tile
                entity: light.teagans_office_main_light
                vertical: false
                hide_state: false
                show_entity_picture: false
                state_content:
                  - state
                  - brightness
                  - effect
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.desk_corner_lamp_switch_1
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.desk_lamp_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
            grid_options:
              columns: full
            title: Teagan's Office
          - type: horizontal-stack
            cards:
              - type: tile
                entity: light.teagans_room_main_light
                vertical: false
                hide_state: false
                show_entity_picture: false
                state_content:
                  - state
                  - brightness
                  - effect
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.clothes_rail_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
              - type: tile
                entity: light.bedside_lamp_light
                vertical: false
                hide_state: false
                state_content:
                  - state
                  - color_mode
                tap_action:
                  action: none
                icon_tap_action:
                  action: none
                hold_action:
                  action: none
            grid_options:
              columns: full
            title: Teagan's Bedroom
        column_span: 4
```
