### ISSUE TITLE
In entities card with conditional row, "or" condition requires unused entity to validate

### ISSUE THREAD

**Issue by mark-harmison** [home-assistant/frontend#22536]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Here's a card using an "or" condition.

```yaml
type: entities
entities:
  - entity: switch.fireplace_fan_test
  - entity: valve.fireplace_vent_valve_test
  - type: conditional
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity: valve.fireplace_vent_valve_test
            state: open
          - condition: state
            entity: switch.fireplace_fan_test
            state: "on"
        # Why is the following unused entity requried?
        # entity: unused
    row:
      entity: input_number.fireplace_off_timer
      name: Delay OFF for
title: Fireplace
show_header_toggle: false
```

In the HA dashboard editor ("Entities Card configuration", yaml view), it displays the following error if I don't have the entity: unused in place:

```
Configuration error
Required key 'entities.2.conditions.0.entity' is missing.
```

If I uncomment the entity then everything is happy. Oddly, even when the editor is showing the error the preview card at the right still works but I can't save.

### Describe the behavior you expected

Either no error displayed when no `entity` is in the `conditions` list or the required entity actually does something.

Having YAML that does not validate but the card works and the entity does nothing seems like a mismatch between what we are validating against and what is actually being run. This may not be the only mismatch.

### Steps to reproduce the issue

1. Create the above card.
2. Observe that you cannot save as long as the commented out `entity` is missing.
...

### What version of Home Assistant Core has the issue?

2024.10.2
