### ISSUE TITLE
Heading Card entities icon colour not always applied

### ISSUE THREAD

**Issue by circa1665** [home-assistant/frontend#22553]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When selecting an icon colour for entities used in the heading card as a heading badge, the icon colour is not always applied:
<img width="473" alt="Screenshot 2024-10-26 at 23 18 40" src="https://github.com/user-attachments/assets/9d5daa5f-6535-49b5-a2f8-9d5b3f057f69">

For example I am able to change the colour of this icon:
<img width="1001" alt="Screenshot 2024-10-26 at 23 20 27" src="https://github.com/user-attachments/assets/35db3681-9061-44ae-bf3d-3afb1ab23b3b">

But for some reason not this one:
<img width="1006" alt="Screenshot 2024-10-26 at 23 21 57" src="https://github.com/user-attachments/assets/6c644677-be04-407a-80a5-f1494ebd0d02">

### Describe the behavior you expected

Selecting an icon colour should apply the colour to the icon.

### Steps to reproduce the issue

1. Attempted to apply the colour red to the icon for a Climate entity using the visual editor.

### What version of Home Assistant Core has the issue?

2024.10.4

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Safari 18.0.1 (20619.1.26.31.7)

### Which operating system are you using to run this browser?

macOS 15.0.1

### Problem-relevant frontend configuration

```yaml
Here's the YAML for the heading card in question:

type: heading
heading: Bedroom
heading_style: subtitle
icon: mdi:bed
badges:
  - type: entity
    show_state: true
    show_icon: true
    entity: sensor.bedroom_air_quality_humidity
    color: blue
  - type: entity
    show_state: true
    show_icon: true
    entity: climate.wiser_bedroom
    state_content: current_temperature
    visibility:
      - condition: state
        entity: binary_sensor.season_temp_threshold
        state: "off"
    icon: mdi:thermometer
    color: red
tap_action:
  action: navigate
  navigation_path: /lovelace/bedroom
```

**Comment by ildar170975** [comment]
Do not confirm for 2024.10.4 + Chrome with `climate` entities provided by Demo integration:
```
type: heading
icon: mdi:fridge
heading: Kitchen
badges:
  - type: entity
    show_state: true
    show_icon: true
    entity: climate.ecobee
    color: accent
  - type: entity
    show_state: true
    show_icon: true
    entity: climate.heatpump
    color: red
  - type: entity
    show_state: true
    show_icon: true
    entity: climate.hvac
    color: green
heading_style: title
```
![image](https://github.com/user-attachments/assets/389d6a68-6827-4e0e-8972-c7a33adacb8a)
