### ISSUE TITLE
Page Often Fails to Completely Load w/ Error "Unhandled promise rejection - Subscription not found"

### ISSUE THREAD

**Issue by thaynes43** [home-assistant/frontend#22581]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Periodically, when I got to a new page in home assistant, the page is not fully loaded. For example, when I go to voice assistants often there will be nothing in the list of voice assistants. Then I reload the page, and everything is there. This happens with other pages as well, like saving the logs. I tried to save the logs, it did not save, and then I reloaded the page, and they saved fine.

### Describe the behavior you expected

Home Assistant would load the page fully when redirected to it.
Note that this is a new instance of Home Assistant with not much configured yet. I installed HACS but have not installed anything from it and I set up a voice assistant. I am moving soon, and I plan to run this instance at my new house. My other instance is fine but hosted on unraid while this is in Kubernetes on Talos Linux.

### Steps to reproduce the issue

1. Click from page to page in the menu, especially the voice assistant page
2. Soon notice that fields are missing or things that would normally have entities have no rows
3. Reload the page
4. Observe that the page now looks normal
...

### What version of Home Assistant Core has the issue?

2024.10.4

### What was the last working version of Home Assistant Core?

N/A

### Which operating system are you using to run this browser?

Windows

### State of relevant entities

```txt
N/A this seems to impact all things equally and doesn't appear to be related to any specific entities.
```

### Problem-relevant frontend configuration

```yaml
N/A my configuration is very barebones as this is a new container I just set up in anticipation of moving.
```

### Javascript errors shown in your browser console/inspector

```txt
2024-10-28 22:54:34.405 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139876245211888] Administrator from 10.244.2.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0): Received {'type': 'call_service', 'domain': 'system_log', 'service': 'write', 'return_response': False, 'service_data': {'logger': 'frontend.js.modern.202410023', 'message': 'Unhandled promise rejection from Edge 130.0.0.0 on Windows 10\n{\n "code": "not_found",\n "message": "Subscription not found."\n}', 'level': 'debug'}, 'id': 44}
2024-10-28 22:54:34.405 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=system_log, service=write, service_data=logger=frontend.js.modern.202410023, message=Unhandled promise rejection from Edge 130.0.0.0 on Windows 10
{
"code": "not_found",
"message": "Subscription not found."
}, level=debug>
2024-10-28 22:54:34.405 DEBUG (MainThread) [frontend.js.modern.202410023] Unhandled promise rejection from Edge 130.0.0.0 on Windows 10
{
"code": "not_found",
"message": "Subscription not found."
}
```

### Additional information

Below are the logs I collected, first when capturing the issue but later as I went through the checklist.

This is a log from after I upgraded from .3 to .4 as the checklist mentioned:
[home-assistant-2024.10.4_2024-10-29T03-16-50.255Z.log](https://github.com/user-attachments/files/17551319/home-assistant-2024.10.4_2024-10-29T03-16-50.255Z.log)

This is a log from when I reproduced the issue with firefox as the checklist mentioned using another browser:
[home-assistant-firefox_2024-10-29T03-28-35.938Z.log](https://github.com/user-attachments/files/17551320/home-assistant-firefox_2024-10-29T03-28-35.938Z.log)

This is safe mode:
[home-assistant-safe-mode_2024-10-29T03-21-03.586Z.log](https://github.com/user-attachments/files/17551321/home-assistant-safe-mode_2024-10-29T03-21-03.586Z.log)

This was the initial logs I collected before reading the checklist:
[home-assistant-2024.10.3_2024-10-29T02-57-22.836Z.log](https://github.com/user-attachments/files/17551322/home-assistant-2024.10.3_2024-10-29T02-57-22.836Z.log)

**Comment by thaynes43** [comment]
I believe using the following Middleware for Traefik has resolved my problem:

```yaml
apiVersion: traefik.io/v1alpha1 # traefik.containo.us/v1alpha1 depreciated in Traefik v3
kind: Middleware
metadata:
  name: default-headers
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    referrerPolicy: no-referrer
    contentSecurityPolicy: "default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https:; frame-src 'self' https:; media-src 'self' https:; object-src 'none'; frame-ancestors 'self'; base-uri 'self'; form-action 'self';"
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
```

I tried no reverse proxy at all and still had the problem so I'm not 100% sure I'm out of the woods but after adding this things seem fine!
