### ISSUE TITLE
Incorrect height of vertical Tile cards in horizontal stack

### ISSUE THREAD

**Issue by bieniu** [home-assistant/frontend#22635]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In a section layout, vertical Tile cards in the horizontal stack have the incorrect height.

![obraz](https://github.com/user-attachments/assets/8687b0b1-87ac-4394-a08d-bdc3516b510a)

### Describe the behavior you expected

Tile cards should be the same height with and without a horizontal stack.

### Steps to reproduce the issue

1. Create section layout
2. Add horizontal stack card
3. Add vertical Tile card to the horizontal stack
...

### What version of Home Assistant Core has the issue?

core-2024.10.x/2024.11.0b2

### In which browser are you experiencing the issue with?

Firefox 132/Safari (iPhone)

### Which operating system are you using to run this browser?

Windows 11/iOS 18.1

### Problem-relevant frontend configuration

```yaml
type: horizontal-stack
cards:
  - type: tile
    entity: sensor.home_temperature
    vertical: true
  - type: tile
    entity: sensor.home_pressure
    vertical: true
```
