### ISSUE TITLE
Entity Card visibility logic not working

### ISSUE THREAD

**Issue by Greeve99** [home-assistant/frontend#22646]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Visibility logic should display Card when entity stare = Ready. the  entry box shows the current state is Ready but the test fails.

![chrome_7iaTpVJZdi](https://github.com/user-attachments/assets/bd6a5408-9ee7-44dd-b69e-4a3374af2d34)

### Describe the behavior you expected

When entity State = "Ready" ( the visual Editor shows the current state: Ready) visibility test should pass and the card should display.

### Steps to reproduce the issue

Edit the Card and enter the code below or configure via visual editor
```
visibility:
  - condition: state
    entity: sensor.013070425748000829_bsh_common_status_operationstate
    state: Ready
```
![chrome_7iaTpVJZdi](https://github.com/user-attachments/assets/6ef257a1-dcbe-4d47-acb6-d8e09d06d471)

### What version of Home Assistant Core has the issue?

2024.10.4

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
BSH.Common.EnumType.OperationState.Ready
```

### Problem-relevant frontend configuration

```yaml
visibility:
  - condition: state
    entity: sensor.013070425748000829_bsh_common_status_operationstate
    state: Ready
```
