### ISSUE TITLE
Section display broken with streamline card after 2024.11 update

### ISSUE THREAD

**Issue by BBE-FR** [home-assistant/frontend#22723]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Issue described here:
https://github.com/brunosabot/streamline-card/issues/30

Display of section is inhibited when streamline card are used with 2024.11
Decluttering cards does not show the same issue.

### Describe the behavior you expected

Section display not empty (was working before the update 2024.11). it should at least display the other cards (the heading card in the example below).

### Steps to reproduce the issue

This dashboard, with a simple streamline card template (only one heading card - no entity):
- one view in section with one heading card and the streamline card
- one view in masonry with the same two cards

<details><summary>Full simple dashboard code</summary>
<p>

```
streamline_templates:
  pop-up-test:
    card:
      type: heading
      heading: test streamline
      heading_style: title
views:
  - title: sections
    path: pop-ups
    type: sections
    sections:
      - type: grid
        cards:
          - type: heading
            heading: This is a streamline card
            heading_style: title
          - type: custom:streamline-card
            template: pop-up-test
            variables: {}
    cards: []
    max_columns: 4
  - type: masonry
    path: ''
    cards:
      - type: heading
        heading: This is a streamline card
        heading_style: title
      - type: custom:streamline-card
        template: pop-up-test
        variables: {}
    title: masonry

``` 

</p>
</details> 

Section display is empty:
![image](https://github.com/user-attachments/assets/4dcb9de2-f1e0-46d4-bee0-bdc65f2ac438)
Masonry display is working:
![image](https://github.com/user-attachments/assets/fc21f8cf-3b57-4bab-9136-fcdb094e8996)
in edit mode, code of the section is still there:
![image](https://github.com/user-attachments/assets/21a26f95-96c0-46d7-8913-066e4f3a44b3)

### What version of Home Assistant Core has the issue?

2024.11

### What was the last working version of Home Assistant Core?

2024.10

### In which browser are you experiencing the issue with?

chrome

### Which operating system are you using to run this browser?

windows

### State of relevant entities

```txt
no entity used in the example given
```

### Javascript errors shown in your browser console/inspector

```txt
Log obtained with F12 on chrome are all of this type:

12compute-card-grid-size.ts:20 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'grid_columns')
    at r (compute-card-grid-size.ts:20:33)
    at i.value (hui-card.ts:94:23)
    at i.value (hui-card.ts:73:33)
    at hui-grid-section.ts:111:40
    at o.ct (repeat.ts:57:23)
    at o.update (repeat.ts:93:53)
    at o._$AS (directive.ts:134:17)
    at I (lit-html.ts:1085:24)
    at N._$AI (lit-html.ts:1362:13)
    at R.v (lit-html.ts:1192:16)
r @ compute-card-grid-size.ts:20
value @ hui-card.ts:94
value @ hui-card.ts:73
(anonymous) @ hui-grid-section.ts:111
ct @ repeat.ts:57
update @ repeat.ts:93
_$AS @ directive.ts:134
I @ lit-html.ts:1085
_$AI @ lit-html.ts:1362
v @ lit-html.ts:1192
g @ lit-html.ts:1553
_$AI @ lit-html.ts:1384
B @ lit-html.ts:2183
update @ lit-element.ts:165

grid_columns never needed to be defined in any of my cards...
```
