### ISSUE TITLE
Camera does not keep stream orientation (rotation)

### ISSUE THREAD

**Issue by TrasteCC** [home-assistant/frontend#22834]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm struggling with this same issue,  which seems to be back after HA 2024.11:

https://github.com/home-assistant/core/issues/81089

"When setting a orientation on the camera, it briefly changes position, but then reverts to the standard, and the value is not saved."

### Describe the behavior you expected

Rotate the camera stream in the front-end in a grid card

### Steps to reproduce the issue

1. Load the dashboard
2. Click the video stream on the card
3. Set upt "camera strem orientation" to "rotate righ"
4. Click "Update"

![image](https://github.com/user-attachments/assets/f90f414a-8fa8-4615-999c-b8b15c8b6e24)

### What version of Home Assistant Core has the issue?

2024.11.1

### In which browser are you experiencing the issue with?

Chrome 130.0.6723.117

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
State: idle
```

### Problem-relevant frontend configuration

```yaml
cards:
      - type: grid
        square: false
        columns: 1
        cards:
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            entity: camera.reolink_rlc_510wa_clear
            camera_image: camera.reolink_rlc_510wa_clear
```

### Javascript errors shown in your browser console/inspector

```txt
http://192.168.1.144:8123/unknown/src/scoped-custom-element-registry.js 404 (Not Found)
```
