### ISSUE TITLE
Script field selectors not disabled when viewing read-only YAML Scripts through UI

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#22976]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Have scripts in YAML with fields and while it displays the correct message on top about it being read-only and not editable, the controls are not disabled like they should be. You can toggle the booleans, use the dropdown to change to a different selector, etc. And then it has the "Save Script" FAB at the bottom even though you cannot save it.

Included script below to reproduce

<img width="1154" alt="Screen Shot 2024-11-24 at 12 03 59 AM" src="https://github.com/user-attachments/assets/29243d0f-472c-46fc-ab0d-e3a76bdf1c6c">

### Describe the behavior you expected

Should be disabled state like the rest of the user interface elements

### Steps to reproduce the issue

Script to reproduce:

```
alias: Announce Downstairs
description: Send an announcement downstairs
icon: mdi:bullhorn
mode: queued
fields:
  message:
    selector:
      text:
        multiline: true
    name: Message
    description: The message to broadcast
    required: true
sequence:
  - alias: Audible notification
    continue_on_error: true
    action: notify.alexa_media
    data:
      data:
        type: tts
      target:
        - media_player.living_room_echo
      message: "{{ message }}"
```

1. Copy above script into a YAML file, then reload scripts and view script through UI
2. Note how message says `This script cannot be edited from the UI` but still allows interacting with UI elements

### What version of Home Assistant Core has the issue?

2024.11.3
