### ISSUE TITLE
Layout Does not work on smeller width displays

### ISSUE THREAD

**Issue by pacmac** [home-assistant/frontend#22970]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

With a 2 Column section design on low width screen (480px) the right hand column does not appear on the right, but below the left column.

### Describe the behavior you expected

Columns would be side by side

### Steps to reproduce the issue

1. Create a new Panel
2. Add a Full Width Top Bar
3. Add a 1/2 width Left Column
4. Add a 1/2 width Right Column
5. in Develope Tools enable Device Toolbar and set width & height to 480px
6. The Right Column will not appear on the right
7. Make screen wider, it is deisplayed correctly

### What version of Home Assistant Core has the issue?

2024.11.3

### What was the last working version of Home Assistant Core?

n/a

### Problem-relevant frontend configuration

```yaml
views:
  - title: Test
    type: sections
    max_columns: 4
    sections:
      - type: grid
        cards:
          - type: markdown
            content: '**TOP**'
            grid_options:
              columns: full
              rows: auto
        column_span: 2
      - type: grid
        column_span: 1
        cards:
          - type: markdown
            content: '**LEFT**'
            grid_options:
              columns: 6
              rows: auto
      - type: grid
        column_span: 1
        cards:
          - type: markdown
            content: '**RIGHT**'
            grid_options:
              columns: 6
              rows: auto
    subview: true
    cards: []
    dense_section_placement: false
    path: nav_
```

### Additional information

See attached screen shot.
<img width="497" alt="Screenshot 2024-11-23 at 9 40 12 PM" src="https://github.com/user-attachments/assets/9f5b3444-b7f5-4720-98fb-b2b6d71729fc">
