### ISSUE TITLE
Markdown cards in grid card are not taking full height

### ISSUE THREAD

**Issue by sairon** [home-assistant/frontend#23119]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Starting with Core 2024.8.0, Markdown cards contained in Grid cards do not take the same height as the neighboring button. It doesn't happen if the cards are in a horizontal stack (bottom):
![image](https://github.com/user-attachments/assets/3f37a0a4-6440-4c11-aa93-648a217b63d5)

### Describe the behavior you expected

Cards will be rendered as in Core < 2024.8.0:
![image](https://github.com/user-attachments/assets/b6fe32c4-2a39-4c70-ac35-a8ad51ab8003)

### Steps to reproduce the issue

Create a Grid card containing Markdown cards:
```
type: grid
cards:
  - type: markdown
    content: ' '
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: zone.home
  - type: markdown
    content: ' '
```

### What version of Home Assistant Core has the issue?

2024.8.0+

### What was the last working version of Home Assistant Core?

2024.7.3

### In which browser are you experiencing the issue with?

Firefox 132.0.2 (64-bit)

### Which operating system are you using to run this browser?

Arch Linux
