### ISSUE TITLE
Area cards sometimes disappear from view when dashboard is loaded

### ISSUE THREAD

**Issue by Venefilyn** [home-assistant/frontend#23158]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Within my HA instance I've setup area cards with similar configurations as this

```yaml
- alert_classes:
      - motion
      - moisture
    sensor_classes:
      - temperature
      - humidity
    type: area
    area: living_room
    navigation_path: /lovelace/living-room
    layout_options:
      grid_columns: 2
      grid_rows: 3
```

However, sometimes some or all of the area cards disappear from view and takes a minute or so before clearing cache makes it loads completely. JS Console spits this out when it happens
`Error: Incorrect argument types for storage.StorageAreaWithUsage.get.`

I do not know how to reproduce the issue or any workarounds.

### Describe the behavior you expected

Area cards never disappear from view

### Steps to reproduce the issue

1. Create area cards in a dashboard
2. Hope it happens

### What version of Home Assistant Core has the issue?

core-2024.11.3

### In which browser are you experiencing the issue with?

Firefox v133.0

### Which operating system are you using to run this browser?

Tested on Linux PC & iPhone

### Javascript errors shown in your browser console/inspector

`Error: Incorrect argument types for storage.StorageAreaWithUsage.get.`
