### ISSUE TITLE
thermostat card shows `n.setConfig is not a function` for new horizontal swing mode

### ISSUE THREAD

**Issue by jwillemsen** [home-assistant/frontend#23162]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

A climate can now provide a horizontal swing mode but when I show this on a thermostat card after some time I get `n.setConfig is not a function` 

![Screenshot_20241205_142205](https://github.com/user-attachments/assets/772e1212-5cce-4c77-86a6-cc5f6bd3e1c7)

### Describe the behavior you expected

Show the horizontal swing mode

### Steps to reproduce the issue

1. Use an integration which exposes swing_horizontal_mode for a climate entity
2. Show the new swing_horizontal_mode on the dashboard

### What version of Home Assistant Core has the issue?

core-2024.12.0

### In which browser are you experiencing the issue with?

firefox/chrome

### Which operating system are you using to run this browser?

OpenSuSE Linux

### Problem-relevant frontend configuration

```yaml
type: thermostat
entity: climate.werkkamer_room_temperature
features:
  - type: climate-hvac-modes
    hvac_modes:
      - "off"
      - fan_only
      - heat
      - cool
      - heat_cool
      - dry
  - style: dropdown
    type: climate-fan-modes
  - style: dropdown
    type: climate-swing-modes
  - type: climate-preset-modes
    style: dropdown
  - type: climate-swing-horizontal-modes
    style: dropdown
show_current_as_primary: false
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_
