### ISSUE TITLE
Energy Dashboard: water consumption is always shown in Liters (L) even when sensor uses m³

### ISSUE THREAD

**Issue by KC-inDomus** [home-assistant/frontend#23318]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Having a `sensor.home_water` entity collecting an increasing float value of water consumption, customized as follow:

```
sensor.home_water:
  friendly_name: Casa - ACQUA
  last_reset: '1970-01-01T00:00:00+00:00'
  device_class: water
  state_class: total_increasing
  unit_of_measurement: m³
  icon: mdi:water

```

seems impossibile to let Enery Dashboard show the correct unit of measurement (m³): the graph always express values in Liters (L) x1000 (if you got 3m³, graph shows 3.000 L).

### Describe the behavior you expected

Graph must show m³ values.

### Steps to reproduce the issue

1. create a sensor
2. customize it
3. populate with a correct value

### What version of Home Assistant Core has the issue?

2024.12.3

### What was the last working version of Home Assistant Core?

n.a.

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
-
```

### Javascript errors shown in your browser console/inspector

```txt
-
```
