### ISSUE TITLE
Card_Mod CSS erases when selecting 'EDIT' for a section of a dashboard

### ISSUE THREAD

**Issue by Todd-Bec-Smart-Home** [home-assistant/frontend#23464]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I know card_mod is a custom function, but it is the visual editor that erases the code. If I open the editor in YAML, it retains the card mod css section, but not in visual editor.

It only erases the code of the selected card though, so when I have a horizontal row of cards with card_mod added and the first card is selected, only that card looses it's card mod YAML, the rest of the row retains the code until they are selected (by selecting card number: 1,2,3,4,etc).

### Describe the behavior you expected

Any additional YAML code should not be errased.

I don't understand why a CSS editor is not just an existing function of the visual editor in the first place, as this seems to be EXTREMELY popular amongst dashboard creators. But why does it have to erase additional code, it didn't in previous versions.

### Steps to reproduce the issue

1. add additional YAML to a card,
2. open the card in visual editor
3. additional code will disapear, as though the visual editor reformats the card each time it is opened?
4.
...

### What version of Home Assistant Core has the issue?

2024.12.5

### In which browser are you experiencing the issue with?

Chrome and HA app

### Which operating system are you using to run this browser?

Windows 10 Pro, iOS on iPhone (always the latest, but not beta)

### Problem-relevant frontend configuration

```yaml
cards:
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-climate-card
                entity: climate.living_room
                icon: mdi:air-conditioner
                name: Living Room
                layout: vertical
                card_mod:
                  style: |
                    :host {
                      --mush-icon-symbol-size: 30px;
                      --mush-icon-size: 50px;
                      --mush-card-primary-font-size: 14px;
                      --mush-card-secondary-font-size: 14px;
                      --mush-card-primary-font-weight: bold;
                      --mush-card-secondary-font-weight: light;
                    }
                    ha-card {
                      {% if states('climate.living_room')=='heat' %}
                      background: rgba(255, 166, 0, 0.2);
                      color: #ffa600;
                      border: 3px solid rgba(255, 166, 0, 0.3);
                      {% elif states('climate.living_room')=='cool' %}
                      background: rgba(0, 115, 255, 0.2);
                      color: #33ceff;
                      border: 3px solid rgba(0, 115, 255, 0.3);
                      {% else %}
                      border: 3px solid rgba(100, 100, 100, 0.3);
                      {% endif %}
                    }
              - type: custom:mushroom-climate-card
                entity: climate.master_bedroom
                icon: mdi:air-conditioner
                name: Master Bedroom
                layout: vertical
                card_mod:
                  style: |
                    :host {
                      --mush-icon-symbol-size: 30px;
                      --mush-icon-size: 50px;
                      --mush-card-primary-font-size: 14px;
                      --mush-card-secondary-font-size: 14px;
                      --mush-card-primary-font-weight: bold;
                      --mush-card-secondary-font-weight: light;
                    }
                    ha-card {
                      {% if states('climate.master_bedroom')=='heat' %}
                      background: rgba(255, 166, 0, 0.2);
                      color: #ffa600;
                      border: 3px solid rgba(255, 166, 0, 0.3);
                      {% elif states('climate.master_bedroom')=='cool' %}
                      background: rgba(0, 115, 255, 0.2);
                      color: #33ceff;
                      border: 3px solid rgba(0, 115, 255, 0.3);
                      {% else %}
                      border: 3px solid rgba(100, 100, 100, 0.3);
                      {% endif %}
                    }
              - type: custom:mushroom-climate-card
                entity: climate.lilys_room
                icon: mdi:air-conditioner
                name: Lily's Room
                layout: vertical
                card_mod:
                  style: |
                    :host {
                      --mush-icon-symbol-size: 30px;
                      --mush-icon-size: 50px;
                      --mush-card-primary-font-size: 14px;
                      --mush-card-secondary-font-size: 14px;
                      --mush-card-primary-font-weight: bold;
                      --mush-card-secondary-font-weight: light;
                    }
                    ha-card {
                      {% if states('climate.lilys_room')=='heat' %}
                      background: rgba(255, 166, 0, 0.2);
                      color: #ffa600;
                      border: 3px solid rgba(255, 166, 0, 0.3);
                      {% elif states('climate.lilys_room')=='cool' %}
                      background: rgba(0, 115, 255, 0.2);
                      color: #33ceff;
                      border: 3px solid rgba(0, 115, 255, 0.3);
                      {% else %}
                      border: 3px solid rgba(100, 100, 100, 0.3);
                      {% endif %}
                    }
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-light-card
                entity: light.toilet_light
                icon: mdi:lightbulb-on-outline
                fill_container: true
                layout: vertical
                show_brightness_control: true
                collapsible_controls: true
                name: Toilet
                icon_color: yellow
                card_mod:
                  style: |
                    :host {
                      --mush-icon-symbol-size: 30px;
                      --mush-icon-size: 40px;
                      --mush-card-primary-font-size: 14px;
                      --mush-card-secondary-font-size: 14px;
                      --mush-card-primary-font-weight: bold;
                      --mush-card-secondary-font-weight: light;
                    }
                    ha-card {
                      {% if states('light.toilet_light')=='on' %}
                      background: rgba(252, 236, 3, 0.2);
                      color: #FCEC03;
                      border: 3px solid rgba(252, 236, 3, 0.3);
                      {% else %}
                      border: 3px solid rgba(100, 100, 100, 0.3);
                      {% endif %}
                    }
              - type: custom:mushroom-light-card
                entity: light.kitchen_light
                icon: mdi:lightbulb-on-outline
                fill_container: true
                layout: vertical
                show_brightness_control: true
                collapsible_controls: true
                name: Kitchen
                icon_color: yellow
                card_mod:
                  style: |
                    :host {
                      --mush-icon-symbol-size: 30px;
                      --mush-icon-size: 40px;
                      --mush-card-primary-font-size: 14px;
                      --mush-card-secondary-font-size: 14px;
                      --mush-card-primary-font-weight: bold;
                      --mush-card-secondary-font-weight: light;
                    }
                    ha-card {
                      {% if states('light.kitchen_light')=='on' %}
                      background: rgba(252, 236, 3, 0.2);
                      color: #FCEC03;
                      border: 3px solid rgba(252, 236, 3, 0.3);
                      {% else %}
                      border: 3px solid rgba(100, 100, 100, 0.3);
                      {% endif %}
                    }
              - type: custom:mushroom-light-card
                entity: light.hall_dimmer_light
                icon: mdi:lightbulb-on-outline
                fill_container: true
                layout: vertical
                show_brightness_control: true
                collapsible_controls: true
                name: Hallway
                icon_color: yellow
                card_mod:
                  style: |
                    :host {
                      --mush-icon-symbol-size: 30px;
                      --mush-icon-size: 40px;
                      --mush-card-primary-font-size: 14px;
                      --mush-card-secondary-font-size: 14px;
                      --mush-card-primary-font-weight: bold;
                      --mush-card-secondary-font-weight: light;
                    }
                    ha-card {
                      {% if states('light.hall_dimmer_light')=='on' %}
                      background: rgba(252, 236, 3, 0.2);
                      color: #FCEC03;
                      border: 3px solid rgba(252, 236, 3, 0.3);
                      {% else %}
                      border: 3px solid rgba(100, 100, 100, 0.3);
                      {% endif %}
                    }
              - type: custom:mushroom-light-card
                entity: light.lounge_light_switch_light_2
                icon: mdi:coach-lamp
                fill_container: true
                layout: vertical
                show_brightness_control: true
                collapsible_controls: true
                name: Porch
                icon_color: yellow
                card_mod:
                  style: |
                    :host {
                      --mush-icon-symbol-size: 30px;
                      --mush-icon-size: 40px;
                      --mush-card-primary-font-size: 14px;
                      --mush-card-secondary-font-size: 14px;
                      --mush-card-primary-font-weight: bold;
                      --mush-card-secondary-font-weight: light;
                    }
                    ha-card {
                      {% if states('light.lounge_light_switch_light_2')=='on' %}
                      background: rgba(252, 236, 3, 0.2);
                      color: #FCEC03;
                      border: 3px solid rgba(252, 236, 3, 0.3);
                      {% else %}
                      border: 3px solid rgba(100, 100, 100, 0.3);
                      {% endif %}
                    }
```
