### ISSUE TITLE
Scripts with fields showing Action selector at all times, even when not specified

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#23495]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

All of my scripts that use fields are showing the Action selector in the script more info dialog even when it's not specified and doesn't belong. 

Not only does it mess with the clean appearance, but it's somewhat of a security issue too because it shows up for standard/non-admin user accounts and allows them to run any action. 

<img width="569" alt="ScriptFields" src="https://github.com/user-attachments/assets/aa12f828-40fb-42a8-91b2-82a72dba1e07" />

### Describe the behavior you expected

Don't show Action selector if not specified in the script

### Steps to reproduce the issue

1. Have any script with fields and open the more info dialog for that script. Here's the YAML for the one in my screenshot:

```
script:

  kitchen_faucet_pour:
    alias: Kitchen Faucet Pour
    description: Pour a custom amount from kitchen faucet
    icon: mdi:faucet-variant
    mode: queued
    fields:

      amount:
        selector:
          number:
            min: 1
            max: 20
            step: 1
        default: 2
        required: true
        name: Dispense Amount
        description: Drag slider to set

      unit:
        selector:
          select:
            options:
              - cups
              - ounces
              - pints
              - quarts
              - gallons
              - liters
              - centiliters
              - deciliters
              - milliliters
            multiple: false
        name: Unit
        required: true
        default: cups
        description: Unit of measurement

    sequence:
      - alias: "Mimic a voice command using Alexa Media Player"
        continue_on_error: true
        action: media_player.play_media
        data:
          entity_id: media_player.kitchen_echo
          media_content_type: custom
          media_content_id: "Ask Delta to dispense {{ amount }} {{ unit }}"
```

### What version of Home Assistant Core has the issue?

2025.1.0b2
