### ISSUE TITLE
Editing UI causes an element to be replaced

### ISSUE THREAD

**Issue by pspeirs** [home-assistant/frontend#23510]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When editing a dashboard, contents of edited column is replaced with another element that exists on the page.  For example, I have 2 horizontal stacks, the first containing a number of images, and the second contains 3 columns.  If I choose column 3 to edit, the entire content is replaced by an element in the first column.

yaml snippet of column 3 prior to selecting the column in UI edit.

     - type: vertical-stack
        cards:
          - type: vertical-stack
            cards:
              - type: custom:garbage-collection-card
                entity: sensor.rubbish_bin
                icon_size: 50px
                icon_color: red
                hide_before: 1
                hide_date: true
                hide_days: true
                hide_on_click: false
              - type: custom:garbage-collection-card
                entity: sensor.recycle_bin
                icon_size: 50px
                icon_color: yellow
                hide_before: 1
                hide_date: true
                hide_days: true
                hide_on_click: false
              - type: custom:garbage-collection-card
                entity: sensor.garden_waste_bin
                icon_size: 50px
                icon_color: green
                hide_before: 1
                hide_date: true
                hide_days: true
                hide_on_click: false

1. Show visual editor
2. Show code again, snippet as shown below.

      - type: vertical-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.lounge
            name: Lounge Room
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: true
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"

The yaml above is replacing the first chunk of yaml simply by clicking the edit in UI button.

### Describe the behavior you expected

I expect that the content will not change when selecting edit in UI

### Steps to reproduce the issue

1. Edit page
2. Select vertical column to edit
3. Now shows something completely different

This has been happening for a number of updates now, probably 6-12 months old, but I don't edit very often.

### What version of Home Assistant Core has the issue?

2024.12.5

### What was the last working version of Home Assistant Core?

Unsure, perhaps 6-12 months ago

### In which browser are you experiencing the issue with?

Chrome 131.0.6778.205 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 v 10.0.19045

### Problem-relevant frontend configuration

```yaml
Entire YAML prior to selecting the column
========================================================

type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - entity_picture: /local/images/img-lounge-1.jpg
        name: Home
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/home
        template: picture_button
        type: custom:button-card
      - entity_picture: /local/images/img-outside.jpg
        name: Outdoors
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/outdoors
        template: picture_button
        type: custom:button-card
      - entity_picture: /local/images/img-sprinkler.jpg
        name: Irrigation
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/irrigation
        template: picture_button
        type: custom:button-card
      - entity_picture: /local/images/img-security-1.jpg
        name: Security
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/security
        template: picture_button
        type: custom:button-card
      - entity_picture: /local/images/img-energy.jpg
        name: Energy
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/energy
        template: picture_button
        type: custom:button-card
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.lounge
            name: Lounge Room
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: true
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
          - type: custom:mushroom-light-card
            entity: light.dining
            name: Dining Room
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: true
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
          - type: custom:mushroom-light-card
            entity: light.kitchen
            name: Kitchen
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: true
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
          - type: custom:mushroom-light-card
            entity: light.kitchen_bench
            name: Kitchen Bench
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: false
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
          - type: custom:mushroom-template-card
            primary: Feature
            icon: |-
              {% if is_state('light.upstairs_feature_light', 'on') %}
                mdi:lightbulb-spot
              {% else %}
                mdi:lightbulb-spot-off
              {% endif %}
            icon_color: |-
              {% if is_state('light.upstairs_feature_light', 'on') %}
                #56A0EE
              {% else %}
                grey
              {% endif %}
            layout: horizontal
            tap_action:
              action: toggle
            fill_container: true
            secondary: ""
            entity: light.upstairs_feature_light
      - type: vertical-stack
        cards:
          - type: custom:mushroom-cover-card
            entity: cover.shutter_front_door
            name: Front Door
            show_buttons_control: true
            tap_action:
              action: toggle
            show_position_control: false
            icon: mdi:window-closed
            card_mod:
              style: |
                ha-state-icon {
                  color: #56A0EE;
                }
          - type: custom:mushroom-cover-card
            entity: cover.shutter_front_window
            name: Front Window
            show_buttons_control: true
            tap_action:
              action: toggle
            icon: mdi:window-closed
            card_mod:
              style: |
                ha-state-icon {
                  color: #56A0EE;
                }
          - type: custom:mushroom-cover-card
            entity: cover.shutter_rear_door
            name: Rear Door
            show_buttons_control: true
            tap_action:
              action: toggle
            icon: mdi:window-closed
            fill_container: false
            card_mod:
              style: |
                ha-state-icon {
                  color: #56A0EE;
                }
          - type: custom:mushroom-cover-card
            entity: cover.shutter_rear_side_door
            name: Rear Side Door
            show_buttons_control: true
            tap_action:
              action: toggle
            icon: mdi:window-closed
            card_mod:
              style: |
                ha-state-icon {
                  color: #56A0EE;
                }
      - type: vertical-stack
        cards:
          - type: vertical-stack
            cards:
              - type: custom:garbage-collection-card
                entity: sensor.rubbish_bin
                icon_size: 50px
                icon_color: red
                hide_before: 1
                hide_date: true
                hide_days: true
                hide_on_click: false
              - type: custom:garbage-collection-card
                entity: sensor.recycle_bin
                icon_size: 50px
                icon_color: yellow
                hide_before: 1
                hide_date: true
                hide_days: true
                hide_on_click: false
              - type: custom:garbage-collection-card
                entity: sensor.garden_waste_bin
                icon_size: 50px
                icon_color: green
                hide_before: 1
                hide_date: true
                hide_days: true
                hide_on_click: false
card_mod:
  style: |
    ha-card {
      height: 100%;
    }

Entire YAML after selecting the 3rd vertical stack on the second horizontal stack
=================================================================================
Note the last section of yaml changes

type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - entity_picture: /local/images/img-lounge-1.jpg
        name: Home
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/home
        template: picture_button
        type: custom:button-card
      - entity_picture: /local/images/img-outside.jpg
        name: Outdoors
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/outdoors
        template: picture_button
        type: custom:button-card
      - entity_picture: /local/images/img-sprinkler.jpg
        name: Irrigation
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/irrigation
        template: picture_button
        type: custom:button-card
      - entity_picture: /local/images/img-security-1.jpg
        name: Security
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/security
        template: picture_button
        type: custom:button-card
      - entity_picture: /local/images/img-energy.jpg
        name: Energy
        tap_action:
          action: navigate
          navigation_path: /lovelace-tablet/energy
        template: picture_button
        type: custom:button-card
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.lounge
            name: Lounge Room
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: true
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
          - type: custom:mushroom-light-card
            entity: light.dining
            name: Dining Room
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: true
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
          - type: custom:mushroom-light-card
            entity: light.kitchen
            name: Kitchen
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: true
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
          - type: custom:mushroom-light-card
            entity: light.kitchen_bench
            name: Kitchen Bench
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: false
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
          - type: custom:mushroom-template-card
            primary: Feature
            icon: |-
              {% if is_state('light.upstairs_feature_light', 'on') %}
                mdi:lightbulb-spot
              {% else %}
                mdi:lightbulb-spot-off
              {% endif %}
            icon_color: |-
              {% if is_state('light.upstairs_feature_light', 'on') %}
                #56A0EE
              {% else %}
                grey
              {% endif %}
            layout: horizontal
            tap_action:
              action: toggle
            fill_container: true
            secondary: ""
            entity: light.upstairs_feature_light
      - type: vertical-stack
        cards:
          - type: custom:mushroom-cover-card
            entity: cover.shutter_front_door
            name: Front Door
            show_buttons_control: true
            tap_action:
              action: toggle
            show_position_control: false
            icon: mdi:window-closed
            card_mod:
              style: |
                ha-state-icon {
                  color: #56A0EE;
                }
          - type: custom:mushroom-cover-card
            entity: cover.shutter_front_window
            name: Front Window
            show_buttons_control: true
            tap_action:
              action: toggle
            icon: mdi:window-closed
            card_mod:
              style: |
                ha-state-icon {
                  color: #56A0EE;
                }
          - type: custom:mushroom-cover-card
            entity: cover.shutter_rear_door
            name: Rear Door
            show_buttons_control: true
            tap_action:
              action: toggle
            icon: mdi:window-closed
            fill_container: false
            card_mod:
              style: |
                ha-state-icon {
                  color: #56A0EE;
                }
          - type: custom:mushroom-cover-card
            entity: cover.shutter_rear_side_door
            name: Rear Side Door
            show_buttons_control: true
            tap_action:
              action: toggle
            icon: mdi:window-closed
            card_mod:
              style: |
                ha-state-icon {
                  color: #56A0EE;
                }
      - type: vertical-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.lounge
            name: Lounge Room
            tap_action:
              action: toggle
            use_light_color: false
            show_brightness_control: true
            secondary_info: none
            icon: mdi:lightbulb
            icon_color: "#56A0EE"
card_mod:
  style: |
    ha-card {
      height: 100%;
    }
```
