### ISSUE TITLE
Tile state_content attributes ignore precision settings for sub-entities

### ISSUE THREAD

**Issue by arcalulu** [home-assistant/frontend#23526]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a SONOFF SNZB02 device that provides two entities through MQTT, one for temperature and the other for humidity.

![1](https://github.com/user-attachments/assets/2f000558-1715-4305-8c6e-d4b6a775cf83)

 I have defined the desired precision for each of these entities.

![2](https://github.com/user-attachments/assets/670d63b1-8d5a-4a98-b69b-47d9e858f835)

![3](https://github.com/user-attachments/assets/924fce94-19f7-42f0-857d-b92bbe2492bb)

Each entity has, in its attributes, the temperature and humidity values from the sensor.

![6](https://github.com/user-attachments/assets/7f231f13-c045-454f-b79b-c2a4b9e7952c)

On a tile, if I only display the state of the entity, the precision format is correctly applied and displayed.

![4](https://github.com/user-attachments/assets/e2923ffe-7e10-4be1-8d2f-bde889147b38)

However, on the same tile, if I want to display both the temperature and humidity attribute values at the same time, the precision format does not apply to the attributes.

![5](https://github.com/user-attachments/assets/199ec3ef-c0a3-422d-b095-6ffb20ace397)

How can I display on a single tile the temperature and humidity values from the same sensor, with distinct precision formats for each value?
Thank you for your help.

By the way, thank you for your splendid work.

### Describe the behavior you expected

I would like to display my tile this way:
![7](https://github.com/user-attachments/assets/3ce9989c-5f5c-484f-81d0-b6bebafd68c6)

Eventually, I would like to have a differentiated "more-info" depending on the attribute I click on (if I click on temperature, I get the temperature graph, and the same for humidity).

### Steps to reproduce the issue

1. Add SNZB02 throught MQTT
2. Add tile
3. Try to add 2 attributes with differentiated precision.
...

### What version of Home Assistant Core has the issue?

2024.12.5

### In which browser are you experiencing the issue with?

Firefox 133.0.3 (64bits)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
entity: sensor.sonde_temp_hygro_04_humidity
state: 54.72

***attributes***
state_class: measurement
battery: 67.5
humidity: 53.64
last_seen: 2024-12-31T16:36:26.625Z
linkquality: 175
temperature: 20.79
voltage: 2900
unit_of_measurement: °C
device_class: temperature
friendly_name: Sonde_Temp_Hygro_04 Température
```

### Problem-relevant frontend configuration

```yaml
type: grid
cards:
  - type: tile
    entity: sensor.sonde_temp_hygro_04_temperature
    grid_options:
      columns: full
  - type: tile
    entity: sensor.sonde_temp_hygro_04_humidity
    grid_options:
      columns: full
  - type: tile
    entity: sensor.sonde_temp_hygro_04_temperature
    state_content:
      - state
      - temperature
      - humidity
    grid_options:
      columns: full
  - type: tile
    entity: sensor.sonde_temp_hygro_04_humidity
    state_content:
      - state
      - temperature
      - humidity
    grid_options:
      columns: full
```
