### ISSUE TITLE
Picture Element Card - Scaling issue between mobile and desktop

### ISSUE THREAD

**Issue by Emeraude998** [home-assistant/frontend#23559]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The position set for the badges in the Picture Element card and the size of the badge do not scale correctly with the picture used when viewed changing the size of the browser window or when viewing it in the mobile app.

<details>
  <summary><h3>"Large" Browser Window</h3></summary>

![large_browser_window](https://github.com/user-attachments/assets/702edf48-c9d7-4170-ba7a-3f81cbfc76a4)
</details>

<details>
  <summary><h3>"Small" Browser Window</h3></summary>

![small_browser_window](https://github.com/user-attachments/assets/88552c63-6f1e-4d57-af31-c4f7bee6243c)
</details>

<details>
  <summary><h3>Mobile App</h3></summary>

![mobile_app](https://github.com/user-attachments/assets/aeceec94-d0eb-49a7-aecb-72879f4cf306)
</details>

### Describe the behavior you expected

The badges should scale and be positionned with the image

### Steps to reproduce the issue

1. Create a new view with a `Panel (single card)` Layout
2. Add a `Picture elements Card`
3. Add a badge and set its position and scale
``` yaml
type: state-badge
entity: sensor.temp_sensor_entree_temperature
title: Entrée
style:
  top: 10%
  left: 40%
  color: red
  transform: scale(50%)
```
4. Change the window size of the browser or switch to mobile and the badge's position and size do not scale with the image.

### What version of Home Assistant Core has the issue?

core-2024.12.5

### What was the last working version of Home Assistant Core?

core-2024.12.5

### In which browser are you experiencing the issue with?

Google Chrome 131.0.6778.205

### Which operating system are you using to run this browser?

Windows (10)

### Problem-relevant frontend configuration

```yaml
type: picture-elements
elements:
  - type: state-badge
    entity: sensor.temp_sensor_entree_temperature
    title: Entrée
    style:
      top: 10%
      left: 40%
      color: red
      transform: scale(50%)
image: https://demo.home-assistant.io/stub_config/floorplan.png
```

### Additional information

The **Title** parameter of the badge doesn't seem to apply to the text underneath the badge icon.

![image](https://github.com/user-attachments/assets/b79027b8-62c0-473f-a8ac-f6663d59b257)

The badge only shows the friendly name of the entity but the tooltip when hovering above the badge shows the correct title.

Don't know if it is the intended behavior but it seems useless for mobile/tactile screen users.
