### ISSUE TITLE
After updating to 2025.1, some card_mod code stopped working

### ISSUE THREAD

**Issue by dnestico** [home-assistant/frontend#23608]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Before 2025.1.0 had scrollable mushroom chips cards using card_mod that worked with no issue, now after updating to 2025.1.0 that stopped working. Did something change behind the scenes that blocks it?

<img width="472" alt="Screenshot 2025-01-06 at 7 11 37 PM" src="https://github.com/user-attachments/assets/0ba9c078-925a-43a2-8f44-22282323a75a" />

The mushroom chips on the right in the picture have card_mod code pasted below that made them scrollable on the dashboard, this no longer works with 2025.1 for some reason.

### Describe the behavior you expected

For the code that worked before 2025.1.0 to work again or a workaround if possible

### Steps to reproduce the issue

1. Update to 2025.1
2. Code breaks

### What version of Home Assistant Core has the issue?

2025.1.0

### What was the last working version of Home Assistant Core?

2024.9.1

### In which browser are you experiencing the issue?

Google Chrome

### Which operating system are you using to run this browser?

macOS Sequioa

### Problem-relevant frontend configuration

```yaml
type: custom:mushroom-chips-card
chips:
  - type: conditional
    conditions:
      - condition: state
        entity: binary_sensor.aurora_visibility_visibility_alert
        state: "on"
    chip:
      type: entity
      entity: binary_sensor.aurora_visibility_visibility_alert
      tap_action:
        action: navigate
        navigation_path: "#weather"
      double_tap_action:
        action: none
      content_info: state
  - type: conditional
    conditions:
      - condition: state
        entity: binary_sensor.aurora_visibility_visibility_alert
        state: "on"
    chip:
      type: entity
      entity: sensor.aurora_visibility_visibility
      tap_action:
        action: navigate
        navigation_path: "#weather"
      double_tap_action:
        action: none
      content_info: state
  - type: weather
    entity: weather.forecast_home
    tap_action:
      action: navigate
      navigation_path: "#weather"
    hold_action:
      action: more-info
    double_tap_action:
      action: none
    show_conditions: true
    show_temperature: true
  - type: conditional
    conditions:
      - condition: state
        entity: sun.sun
        state: below_horizon
    chip:
      type: entity
      entity: sensor.sun_next_rising
      icon: mdi:weather-sunset-up
      icon_color: orange
      use_entity_picture: false
      tap_action:
        action: navigate
        navigation_path: "#weather"
  - type: conditional
    conditions:
      - condition: state
        entity: sun.sun
        state: above_horizon
    chip:
      type: entity
      entity: sensor.sun_next_setting
      icon: mdi:weather-sunset-down
      icon_color: deep-orange
      tap_action:
        action: navigate
        navigation_path: "#weather"
  - type: entity
    entity: sensor.vaughan_humidity
    icon_color: cyan
    icon: mdi:water-opacity
    tap_action:
      action: navigate
      navigation_path: "#weather"
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.vaughan_chance_of_precipitation
        state_not: unknown
    chip:
      type: entity
      entity: sensor.vaughan_chance_of_precipitation
      tap_action:
        action: navigate
        navigation_path: "#weather"
      icon: mdi:weather-rainy
      icon_color: light-blue
  - type: conditional
    conditions:
      - condition: numeric_state
        entity: sensor.vaughan_wind_speed
        above: 0
    chip:
      type: template
      entity: sensor.vaughan_wind_speed
      icon: mdi:weather-windy
      icon_color: grey
      content: "{{ states('sensor.vaughan_wind_speed') }}km/h"
      tap_action:
        action: navigate
        navigation_path: "#weather"
  - type: conditional
    conditions:
      - condition: numeric_state
        entity: sensor.vaughan_aqhi
        above: 4
    chip:
      type: template
      entity: sensor.vaughan_aqhi
      icon: mdi:air-filter
      icon_color: |-
        {% set aqhi = states('sensor.vaughan_aqhi') | int %}
        {% if aqhi >= 8 %}
          red
        {% elif aqhi >= 6 %}
          orange
        {% elif aqhi > 3 %}
          amber
        {% else %}
          green
        {% endif %}
      content: |-
        {% set aqhi = states('sensor.vaughan_aqhi') | int %}
        {% if aqhi >= 8 %}
          AQHI Very High
        {% elif aqhi >= 6 %}
          AQHI High
        {% elif aqhi > 3 %}
          AQHI Moderate
        {% else %}
          AQHI Low 
        {% endif %}

        ({{ states('sensor.vaughan_aqhi') }})
      tap_action:
        action: navigate
        navigation_path: "#weather"
  - type: conditional
    conditions:
      - condition: state
        entity: sun.sun
        state: above_horizon
      - condition: numeric_state
        entity: sensor.vaughan_uv_index
        above: 4
    chip:
      type: template
      entity: sensor.vaughan_uv_index
      icon: mdi:sun-wireless
      tap_action:
        action: navigate
        navigation_path: "#weather"
      icon_color: |-
        {% set uv_index = states('sensor.vaughan_uv_index') | int %}
        {% if uv_index >= 8 %}
          red
        {% elif uv_index > 6 %}
          orange
        {% elif uv_index > 3 %}
          amber
        {% else %}
          green
        {% endif %}
      content: |-
        {% set uv_index = states('sensor.vaughan_uv_index') | int %}
        {% if uv_index >= 8 %}
          UV Very High
        {% elif uv_index > 6 %}
          UV High
        {% elif uv_index > 3 %}
          UV Moderate
        {% else %}
          UV Low
        {% endif %}

        ({{ states('sensor.vaughan_uv_index') }})
alignment: left
view_layout:
  grid-area: 1
card_mod:
  style: |
    ha-card {
        animation: slideInLeft 0.6s ease-out forwards;
        animation-iteration-count: 1 !important;
        -webkit-animation-iteration-count: 1 !important;
        margin: 10px 0px 10px;
        --chip-border-width: 0;
        --chip-box-shadow: 0;
        --chip-background: #9E9E9E20;
      }
      ha-card > .chip-container {
        flex-wrap: nowrap;
        overflow-x: auto; /* Enable horizontal scrolling */
        scroll-behavior: smooth; /* Smooth scrolling */
      }

      ha-card > .chip-container::-webkit-scrollbar {
        height: 1px; /* Customize the scrollbar height */
      }

      ha-card > .chip-container::-webkit-scrollbar-thumb {
        background-color: var(--google-grey); /* Color of the scrollbar thumb */
        border-radius: 10px; /* Round the scrollbar edges */
      }

      ha-card > .chip-container::-webkit-scrollbar-thumb:hover {
        background-color: var(--google-violet); /* Darker on hover */
      }

      ha-card > .chip-container > * {
        flex-shrink: 0;
      }

      @keyframes slideInLeft {
         0% {
            opacity: 0;
            transform: translateX(-100%);
         }
         100% {
            opacity: 1;
            transform: translateX(0);
         }
      }
```
