### ISSUE TITLE
History Graph Bug

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#23607]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

History Graph Bug, i only have this problem on my phone.

https://github.com/user-attachments/assets/49e5045c-a029-4fc6-ac13-85d05f3fda4b

### Describe the behavior you expected

.

### Steps to reproduce the issue

.

### What version of Home Assistant Core has the issue?

2025.1.0

### Problem-relevant frontend configuration

```yaml
- type: history-graph
    entities:
      - entity: sensor.patio_illuminance
        name: Patio
      - entity: sensor.outside_illuminance
        name: Outside
      - entity: sensor.outside_illuminance_cloud
        name: Outside Cloud
```
