### ISSUE TITLE
Header badge entity visibility not working correctly

### ISSUE THREAD

**Issue by Jeroendg** [home-assistant/frontend#23620]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have entities in my card headers for my Unifi AP's that are set to be only visible when their state is not equal to "Connected" so I can see when there's an issue with that AP.
Since 2025.1 they are visible all the time.
![image](https://github.com/user-attachments/assets/c53a5bbb-c304-4646-8ebe-1f5040cda25f)
![image](https://github.com/user-attachments/assets/e358a7d1-4bb5-4885-8f46-a1cd5b42583f)
![image](https://github.com/user-attachments/assets/9d930de1-9b4b-4311-aa3f-3459e5ec3383)

### Describe the behavior you expected

When the AP is in the "Connected" state, as it currently is, the pink wifi icon for that entity should not be visible

### Steps to reproduce the issue

1. Add Unifi AP entity to card header
2. Set visibility to only show when state does not equal "Connected"
3. Entity remains visible when state equals "Connected"

### What version of Home Assistant Core has the issue?

2025.1.1

### In which browser are you experiencing the issue?

Firefox 133.0.3

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
disconnected, connected, pending, firmware_mismatch, upgrading, provisioning, heartbeat_missed, adopting, deleting, inform_error, adoption_failed, isolated
```

### Problem-relevant frontend configuration

```yaml
type: grid
cards:
  - type: heading
    heading: Overloop
    heading_style: title
    icon: mdi:stairs
    badges:
      - type: entity
        show_state: false
        show_icon: true
        entity: sensor.ap_overloop_state
        icon: mdi:wifi-alert
        color: pink
        visibility:
          - condition: state
            entity: sensor.ap_overloop_state
            state_not: Connected
      - type: entity
        show_state: false
        show_icon: true
        entity: binary_sensor.motion_overloop
        color: state
      - type: entity
        show_state: true
        show_icon: false
        entity: sensor.temperatuur_overloop
    tap_action:
      action: navigate
      navigation_path: /lovelace/overloop
  - type: tile
    entity: sensor.pir_motion_sensor_3_battery_level_5
    grid_options:
      columns: full
    visibility:
      - condition: state
        entity: binary_sensor.pir_motion_sensor_3_low_battery_level_5
        state: "on"
    name: Batterij Bewegingsmelder 1
  - type: tile
    entity: sensor.pir_motion_sensor_3_battery_level_6
    grid_options:
      columns: full
    visibility:
      - condition: state
        entity: binary_sensor.pir_motion_sensor_3_low_battery_level_6
        state: "on"
    name: Batterij Bewegingsmelder 2
  - type: tile
    entity: cover.wrap_overloop
    name: Jaloezieën
    icon_tap_action:
      action: toggle
```
