### ISSUE TITLE
Statistic Card with Footer containing Button with Tap Action for More Info not showing correct entity

### ISSUE THREAD

**Issue by sourworm** [home-assistant/frontend#23622]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using a Statistic card for a certain entity (A) and adding a Footer to that card which contains a Button setup to show More Info for a different entity (B) when clicked, that button will instead usually (but not always) open the info pane for the entity (A) from the main statistic card. This issue occurs in multiple browsers on Windows PC but not in the Android Home Assistant app or Firefox mobile app.

In my specific case the button labeled 'Daily Energy' opens the 'kauf_plug_power' info instead of the 'kauf_plug_total_daily_energy' info. See code in "Problem-relevant frontend configuration" section below.

### Describe the behavior you expected

The button in the footer should always open the info pane for the entity specified in the tap_action section under the footer entities.

### Steps to reproduce the issue

1. Create a statistic card
2. Use the code editor to add a footer of type buttons which has a tap_action setup for a different entity than the one used for the statistic part.
`footer:
  type: buttons
  entities:
    - entity: _SomeSecondEntity_
      tap_action:
        entity: _SomeSecondEntity_
        action: more-info`
4. In a browser on a Windows PC click the button in the footer of that statistic card
5. Notice which entity's info card was opened then close the opened info pane
6. Repeat steps 4 to 5 a few times
...

### What version of Home Assistant Core has the issue?

core 2025.1.1

### In which browser are you experiencing the issue?

Firefox 133.0.3, Chrome 131.0.6778.205, Edge 131.0.2903.112

### Which operating system are you using to run this browser?

Windows 10.0.19045

### Problem-relevant frontend configuration

```yaml
type: statistic
entity: sensor.kauf_plug_power
stat_type: mean
name: 24 Hr Avg
period:
  rolling_window:
    duration:
      hours: 24
      minutes: 0
icon: mdi:gauge
footer:
  type: buttons
  entities:
    - entity: sensor.kauf_plug_total_daily_energy
      tap_action:
        entity: sensor.kauf_plug_total_daily_energy
        action: more-info
      name: Daily Energy
```
