### ISSUE TITLE
Toggling `multiple` of the `select` selector in visual editor does not update default value, leading to unexpected behavior

### ISSUE THREAD

**Issue by MrEbbinghaus** [home-assistant/frontend#23645]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Toggling `multiple`  in the UI for a `select` selector with a default value does not update the default value and sends an incorrect default value to the backend. 

When `multiple` is off the default value is a single value and displayed as a radio button:

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/830c032d-31cc-475d-98c4-3c9a33ade631)

The YAML for this:
```yaml
receiver:
  selector:
    select:
      options:
        - label: Björn
          value: notify.bjorn
        - label: Person1
          value: notify.person1
      multiple: false
  name: Receiver
  required: true
  default: notify.bjorn
```

</details>

Toggling _multiple_ turns the radio buttons into checkboxes, but doesn't actually update the `default` value in the yaml. `default` should be a list with a single element. `- notify.bjorn`. 

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/2c9841cb-c175-4c6d-be46-bf9bbeff22b3)

```yaml
receiver:
  selector:
    select:
      options:
        - label: Björn
          value: notify.bjorn
        - label: Person1
          value: notify.person1
      multiple: true
  name: Receiver
  required: true
  default: notify.bjorn  # this is wrong
  
# should be:
  default:
    - notify.bjorn
```
</details>

This looks like the correct default is set, but it is not. This confusion persists when running the script from the UI. Running it with the default value, like shown in the following screenshot, calls the script with `"notify.bjorn"`, possibly breaking code that expects a list. Toggling "Björn" off/on first, calls the script correctly with `["notify.bjorn"]`.

![image](https://github.com/user-attachments/assets/379371a0-8faa-48d2-b7fa-79e5f91acb7a)

---

This also breaks the other way round.
Turning off "multiple" with one or more defaults leads to the UI showing empty radio buttons, while the default is still the old list. (This reads like "no default" is set.)

<details>
<summary>Screenshot</summary>

```yaml
receiver:
  selector:
    select:
      multiple: false 
...
  default:
    - notify.bjorn
    - notify.person1
```

![image](https://github.com/user-attachments/assets/68ff79b9-673a-4dc4-997e-95f2e41160c5)

</details>

### Describe the behavior you expected

When enabling `multiple` from the UI, the default value should be wrapped in a list.

When disabling `multiple` from the UI, take the first item and set it as the new default. 

### Steps to reproduce the issue

1. Create a `select` selector
2. Add some options
3. Choose a default for the selector
4. Enable the `multiple` toggle
-> Switch to "Edit in YAML" to see that the default value is still a single value.

6. Back in the UI: Toggle the selected default value off/on
-> Now the default value is a list as expected.
7. Disable the `multiple` toggle
-> The default value is still a list instead of a single value.

### What version of Home Assistant Core has the issue?

2025.1.1

### In which browser are you experiencing the issue?

Version 1.73.101 Chromium: 131.0.6778.139 x86_64

### Which operating system are you using to run this browser?

macOS 15.2 (24C101)

### Javascript errors shown in your browser console/inspector

```txt
No JS errors.
```
