### ISSUE TITLE
Statistic Card doesn't have unavailable state, shows as blank card

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#23727]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Temperature sensor in my attic died and it's a hassle to get up there, so I disabled the device temporarily. That is when I noticed the Statistic card doesn't have an error / unavailable state. 

See the comparison below to Entity card on the left which correctly says the entity is unavailable, and Statistic card on the right which just shows a blank card. Have posted the code below to reproduce.

<img width="591" alt="Screen Shot 2025-01-13 at 2 19 55 PM" src="https://github.com/user-attachments/assets/681c7f40-c681-4507-854a-9c5e7c7793d8" />

### Describe the behavior you expected

Should display an `Entity not available: <entity_id>" message like the other cards have

### Steps to reproduce the issue

```
  - type: grid
    cards:
      - type: heading
        heading: Entity card (left) and Statistic card (right)
        heading_style: title
      - type: entity
        entity: sensor.this_entity_does_not_exist_and_should_display_error
      - type: statistic
        entity: sensor.this_entity_does_not_exist_and_should_display_error
        period:
          calendar:
            period: month
        stat_type: mean
```

1. Add above to a dashboard and compare how they are displayed

### What version of Home Assistant Core has the issue?

2025.1.2
