### ISSUE TITLE
Missing automations from UI after some time

### ISSUE THREAD

**Issue by marc4s** [home-assistant/frontend#23749]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If i reboot the HA instance all automations are visible in the UI Settings-Automations - see here the UI list after a reboot:

![Image](https://github.com/user-attachments/assets/6b5a7f2c-6371-49a5-85bd-135d9d1156e7)
![Image](https://github.com/user-attachments/assets/0c67fba1-20ea-43d0-bfc0-5487ec6fe3b1)
![Image](https://github.com/user-attachments/assets/55918854-630d-4a08-9409-16f24d9ae164)
![Image](https://github.com/user-attachments/assets/a3f9f819-cc88-4b12-b0b8-705a96681587)
![Image](https://github.com/user-attachments/assets/8c5c28f9-7ae5-420d-944a-f422ee95b372)
![Image](https://github.com/user-attachments/assets/ca770702-74a7-4b4d-8d61-c57c844402da)
![Image](https://github.com/user-attachments/assets/b0f31908-6f07-4e91-a110-6c4c140b0704)
![Image](https://github.com/user-attachments/assets/0fb0a88a-d828-4a24-bd78-5429f11a8813)
![Image](https://github.com/user-attachments/assets/5ce1dd95-6b08-499d-9eb8-a9c94eef3de4)
![Image](https://github.com/user-attachments/assets/face8420-f0af-4d48-b340-6efc7fb045c6)
![Image](https://github.com/user-attachments/assets/470d6b01-e44a-4e20-bd6b-90921165097a)

But after some hours the list is almost the half (and yes, not all the time the same automations are missing.
I except this is a UI bug as the core is running still all automations fine and I cannot find any related log entrys for this

![Image](https://github.com/user-attachments/assets/c9ecf804-1583-4b0f-b93c-64be551bad4b)
![Image](https://github.com/user-attachments/assets/57eb4fa6-f72e-4636-9d19-8865bee14480)
![Image](https://github.com/user-attachments/assets/ae7db1a9-3bd6-4037-a85a-6901318020e8)
![Image](https://github.com/user-attachments/assets/9029d3fd-e6ec-44af-86c8-7638a4212ad8)
![Image](https://github.com/user-attachments/assets/35ab5a23-6502-47ef-8e44-07c0866de6ee)
![Image](https://github.com/user-attachments/assets/f83a26f5-21a0-41e0-8e17-00a59afd5d3c)

an example automation which is missing:

```
 
- id: '1626892309922'
  alias: GefrierschrankTuerTelegram
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hmip_swdm_gefrierschrank_00155d899120ae
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.ha_telegram_hausstatus
    data:
      title: ACHTUNG
      message: Die Gefrierschranktür ist noch offen
  mode: single
```

### Describe the behavior you expected

listing all automations...

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
