### ISSUE TITLE
"Show header toggle" does not work for covers

### ISSUE THREAD

**Issue by mxr** [home-assistant/frontend#23805]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I use the 'entities' card with covers and enable 'show header toggle', a toggle doesn't show up. 

### Describe the behavior you expected

I expect a toggle to show up (for example, it works for lights).

### Steps to reproduce the issue

Create a card as follows.

```yaml
type: entities
entities:
  - entity: cover.living_room_shade
title: Shades
show_header_toggle: true
```

<img width="996" alt="Image" src="https://github.com/user-attachments/assets/b1c589ac-fa51-4974-b2c3-ad0e7e574846" />

### What version of Home Assistant Core has the issue?

core-2025.1.2

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: cover.living_room_shade
title: Shades
show_header_toggle: true
```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

Example configuration for lights that works

```yaml
type: entities
entities:
  - entity: light.living_room_lights
title: Lights
show_header_toggle: true
```

<img width="1008" alt="Image" src="https://github.com/user-attachments/assets/23f75fc7-87a6-4466-9b56-877bc641402b" />
