### ISSUE TITLE
kelvin and turn_on warning in automation

### ISSUE THREAD

**Issue by antamy** [home-assistant/frontend#23801]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In my logs that I am getting the warning 

` Got kelvin argument in turn_on service, which is deprecated and will break in Home Assistant 2026.1, please use color_temp_kelvin argument `

This is from an automation that turns on lights with a color temperature set with the slider in the UI.  

### Describe the behavior you expected

No error messages from an automation created through the UI.

If I go into the YAML for the automation I see, for example:

```
actions:
  - metadata: {}
    data:
      kelvin: 2200
      brightness_pct: 70
```
 

### Steps to reproduce the issue

Configure an automation to turn on a light and set the color temperature in the UI.  Using this automation creates the warning message.

If the generated YAML is changed, for example:

```
actions:
  - metadata: {}
    data:
      color_temp_kelvin: 2200
      brightness_pct: 70
```

then the automation works without throwing a warning, but the automation UI for "Then Do > Light Turn on" breaks (no sliders etc to set the color temperature)

### What version of Home Assistant Core has the issue?

2025.1.2

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
