### ISSUE TITLE
referenceing #17242, issue is back on 2025.1.3 and 2025.1.4

### ISSUE THREAD

**Issue by jouster1974** [home-assistant/frontend#23869]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

this issue seems to be back where grid cards and history graphs are somehow locking up dashboards being displayed on Firefox browsers on Windows 10.

I can open and fully interact with the identical dashboards on Chrome and Edge browsers...but every time it is opened on Fiefox it becomes unresponsive and gives the following warning

![Image](https://github.com/user-attachments/assets/cd0d2eca-aabc-483b-a511-dd6e3a92671d)

there is no way to get this working in any way...restarting HA makes no difference and if you happen to use no other browsers, then you would be without the dashboard altogether

I was able to fix this by removing a grid card with history graphs.....and as a short-term workaround this is fine but ultimately this was working without issue prior to 2025.1.3

### Describe the behavior you expected

dashboard to be fully viewable and interaction to work as expected

### Steps to reproduce the issue

1.open firefox
2.navigate to home assistant dashboard 
3.
...

### What version of Home Assistant Core has the issue?

2025.1.3 2025.1.4

### What was the last working version of Home Assistant Core?

2025.1.2

### In which browser are you experiencing the issue?

Firefox 134.0.2 (64-bit) 

### Which operating system are you using to run this browser?

Windows 10 Version	10.0.19045 Build 19045

### State of relevant entities

```txt
the grid card in question is siuated witin a custom swipe card...the issue goes away if the grid card within it is removed...this grid card in question is not on display as the first card in 'the swipe'
```

### Problem-relevant frontend configuration

```yaml
there is line segregating the yaml...if the code below the line is rempoved, the dashboard loads as expected in Firefox


type: custom:swipe-card
cards:
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.speedtest_download
        name: Download
        color: white
        show_fill: false
        show_state: true
      - entity: sensor.speedtest_upload
        name: Upload
        color: green
        show_fill: false
        show_state: true
        theme: amoled
        detail: 1
        hour24: true
    decimals: 0
    icon: mdi:speedometer
    points_per_hour: 4
    height: 137
    hour24: true
    show:
      extrema: true
      state: last
      name: false
      icon: false
      align_header: center
      align_state: center
      hours_to_show: 96
      header: false
  - type: statistics-graph
    entities:
      - sensor.ps_btc
    name: £ BTC 6M
    title: £ BTC 6M
    color: red
    chart_type: line
    period: hour
    days_to_show: 180
    stat_types:
      - mean
    hide_legend: true
  - type: statistics-graph
    entities:
      - sensor.ps_btc
    name: £ BTC 1M
    title: £ BTC 1M
    color: blue
    chart_type: line
    period: 5minute
    days_to_show: 30
    stat_types:
      - mean
    hide_legend: true
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.ps_btc
        name: £ BTC 7D
        color: green
      - entity: sensor.bitcoingbp
        show_state: true
        show_graph: false
    hours_to_show: 168
    height: 137
    hour24: true
    details: 4
    decimals: 0
    points_per_hour: 0.1
    icon: mdi:bitcoin
    tap_action:
      action: none
    show:
      extrema: true
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.btc
        name: $ BTC 7D
        show_state: true
        y_axis: primary
        color: white
      - entity: sensor.bitcoinusd
        show_state: true
        show_graph: false
    hours_to_show: 168
    height: 137
    hour24: true
    decimals: 0
    details: 4
    points_per_hour: 0.1
    icon: mdi:bitcoin
    tap_action:
      action: none
    show:
      extrema: true


----------------------------------------------------------


  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: tile
            entity: sensor.cryptoinfo_bitcoin
            name: £ Bitcoin
            color: green
            vertical: true
            grid_options:
              columns: 4
              rows: 2
          - type: tile
            entity: input_number.bitcoin_min
            color: red
            icon: mdi:bitcoin
            vertical: true
            grid_options:
              columns: 4
              rows: 2
          - type: tile
            entity: input_number.bitcoin_max
            vertical: true
            color: green
            icon: mdi:bitcoin
            grid_options:
              columns: 4
              rows: 2
      - type: history-graph
        entities:
          - entity: sensor.cryptoinfo_bitcoin
        grid_options:
          columns: full
        hours_to_show: 120
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: tile
            entity: sensor.cryptoinfo_bitcoin_2
            name: £ Bitcoin
            color: green
            vertical: true
            grid_options:
              columns: 4
              rows: 2
          - type: tile
            entity: input_number.bitcoin_2_min
            color: red
            icon: mdi:bitcoin
            vertical: true
            grid_options:
              columns: 4
              rows: 2
          - type: tile
            entity: input_number.bitcoin_2_max
            vertical: true
            color: green
            icon: mdi:bitcoin
            grid_options:
              columns: 4
              rows: 2
      - type: history-graph
        entities:
          - entity: sensor.cryptoinfo_bitcoin_2
        grid_options:
          columns: full
        hours_to_show: 120
```

### Javascript errors shown in your browser console/inspector

```txt
doesnt seem to be possible to even access developer tools within the tab in quesiton as it is totally locked up
```
