### ISSUE TITLE
`hvac_action` of `preheating` not shown

### ISSUE THREAD

**Issue by mnbf9rca** [home-assistant/frontend#23876]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Some thermostats have a feature where they can start heating a room before the time it needs to be at temperature, which is reported with an `hvac_action` of `preheating`, which is defined in [this enum](https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/const.py#L83). The [current climate UI only recognises](https://github.com/home-assistant/frontend/blob/dev/src/components/chart/state-history-chart-line.ts#L345) `heating` or `cooling`, not other equivalent values like `preheating`. This means the charts show the temperature rising, but don't show the reason (`preheating`):

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/1a8bd2fb-088b-4065-998e-f8e2280688e2" />

First raised in MindrustUK/Heatmiser-for-home-assistant#241

### Describe the behavior you expected

I would like the UI to show other `hvac_action` [states](https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/const.py#L83) so that it's easier to understand what is causing temperature changes. This might be the individual actions, or a map (e.g. `defrosting`, `heating` and `preheating` are grouped).

### Steps to reproduce the issue

1. Install a `climate` entity which supports `preheating`
2. Configure a schedule which will trigger preheating

### What version of Home Assistant Core has the issue?

2025.1.4

### State of relevant entities

```txt
hvac_action: preheating
```

### Problem-relevant frontend configuration

```yaml
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: heading
            icon: ''
            heading: Dining
            heading_style: title
            badges: []
          - type: history-graph
            entities:
              - entity: climate.dining_room
            grid_options:
              columns: full
              rows: 5
```

### Javascript errors shown in your browser console/inspector

```txt

```
