### ISSUE TITLE
Cover: Percentage Displayed wrong / inversed

### ISSUE THREAD

**Issue by realdognose** [home-assistant/frontend#23904]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm controlling some blinds (via knx) which have the following operation-constraints for both, `position` and `angle`: 

- opened := 0%
- closed := 100%

Control works as expected, when attempting to close the blinds, 100% is send to knx, however the UI still shows the percentage-tooltip
as 0% for "closed" and 100% for "opened": 

![Image](https://github.com/user-attachments/assets/e5e0a7cb-8d49-4bc4-9c7a-d5975eae252d)

![Image](https://github.com/user-attachments/assets/dcf10027-bfe5-47d3-9d9b-46a93f57c579)

Applies for both sliders, `position` and `angle`.

### Describe the behavior you expected

ToolTip should indicate the value actually beeing "send": 

![Image](https://github.com/user-attachments/assets/56b0652c-6e6b-4426-ae3d-2be0adaa3099)

### Steps to reproduce the issue

View the percentage-tooltip of a blind configured like: 

```
knx:
 cover:
    #UG
    - name: "Jalousien Foyer Klein"
      move_long_address: "2/0/0"
      stop_address: "2/0/1"
      position_address: "2/0/2"
      angle_address: "2/0/3"
      position_state_address: "11/0/2"
      angle_state_address: "11/0/3"
      device_class: "blind"
```

### What version of Home Assistant Core has the issue?

2025.1.2

### In which browser are you experiencing the issue?

Any

### Which operating system are you using to run this browser?

Any

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
