### ISSUE TITLE
ECharts: incorrect bar-chart stacking

### ISSUE THREAD

**Issue by karwosts** [home-assistant/frontend#23919]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Observe this bar chart. It has two entities, with min/mean/max. 

When carbon dioxide is enabled, I only see two bars, not three as expected (min/max seem maybe drawn on top of each other)
When carbon monoxide is enabled, I only see two bars, though now there is a gap between them, like where a third bar should be.

When both entities are enabled, some of the bars incorrectly stack on top of each other (yellow bar is stacked atop the blue bar, they should be side by side).

![Image](https://github.com/user-attachments/assets/805386da-a72d-466c-84a3-856aad5e09b3)

### Describe the behavior you expected

.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.2.dev @ f8d25601046179540976d6c16e513749b519c526

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
chart_type: bar
period: hour
type: statistics-graph
entities:
  - sensor.carbon_dioxide
  - sensor.carbon_monoxide
stat_types:
  - mean
  - min
  - max
days_to_show: 0.1
```

### Javascript errors shown in your browser console/inspector

```txt

```
