### ISSUE TITLE
Selected entities reset on graph zoom or new data

### ISSUE THREAD

**Issue by tjorim** [home-assistant/frontend#23945]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the new charts on HA 2025.2.0b0 you can still deselect entities you want to hide in the legend.
When new data comes in the selections reset and everything is shown,
the same happens when you zoom in or out.

### Describe the behavior you expected

It remembers my selection as long as I stay on the page, allowing me to only view the data I want at that moment.

### Steps to reproduce the issue

1. Add a history graph Card with multiple entities
2. Deselect one on the entities in the legend
3. Wait for new data to come in or zoom in/out
4. All entities in the legend are selected again

### What version of Home Assistant Core has the issue?

core-2025.2.0b0

### What was the last working version of Home Assistant Core?

core-2025.1.x

### In which browser are you experiencing the issue?

Google Chrome Version 132.0.6834.111 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 Version 24H2 (OS Build 26100.2894)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Mariusthvdb** [comment]
seeing  this too, but have some details

it only happens in a view with a seemingly simple card, that appears to grind the view. I have tested several combinations, but final conclusion is it even grinds the view if only this card is used:

```
      - type: history-graph
        title: Zon - Huis - Net 6 uur
        entities:
          - entity: sensor.zp_actuele_opbrengst
            name: Zon
          - entity: sensor.bruto_stroom_verbruik
            name: Huis
          - entity: sensor.netto_verbruik
            name: Net
        hours_to_show: 6
```

I believe on most of the other history-graph cards, I can toggle click the entities in the legend just fine.

somehow I must conclude the lag of the view caused by this card has to do with it, maybe re-rendering it?

OP mentions 

> the same happens when you zoom in or out.

which is not possible at all in my Dashboard, there are not zoom in/out options available anymore, and, as I understood that in #beta on Discord, that is correct, as

> drag to zoom has been removed. It will be replaced by something way cooler but not in this release
