### ISSUE TITLE
History graph with many entities overlaps entities

### ISSUE THREAD

**Issue by Daemo00** [home-assistant/frontend#23950]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When many entities are shown in an history-graph, they overlap with the graph itself:
![Image](https://github.com/user-attachments/assets/bbacc44c-911e-4b8c-b6b0-ced6be92ddcc)

### Describe the behavior you expected

The entities should be listed above the graph

### Steps to reproduce the issue

1. Create a history-graph card
2. Add at least 10 entities to it

### What version of Home Assistant Core has the issue?

2025.2.0b1

### What was the last working version of Home Assistant Core?

2025.1.4

### In which browser are you experiencing the issue?

Chrome 132.0.6834.122

### Which operating system are you using to run this browser?

Android

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.presa_frigo_power
  - entity: sensor.luce_bagno_rosa_power
  - entity: sensor.colonna_switch_0_power
  - entity: sensor.lampadario_studio_power
  - entity: sensor.presa_tv_switch_0_power
  - entity: sensor.tapparella_camera_power
  - entity: sensor.tapparella_sala_sud_est_power
  - entity: sensor.tapparella_cucina_power
  - entity: sensor.ventola_bagno_rosa_power
hours_to_show: 1
```

### Javascript errors shown in your browser console/inspector

```txt

```
