### ISSUE TITLE
Large left padding for history graph

### ISSUE THREAD

**Issue by tetele** [home-assistant/frontend#23980]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In 2025.2.0b2 i get a large left padding for my history graph cards.

![Image](https://github.com/user-attachments/assets/45a6f7c1-0265-49ff-8a7c-06308cbfc9ec)

This was not present in 2025.1 (same code, different entities in the screenshot)

![Image](https://github.com/user-attachments/assets/14c3cdea-383b-4c64-9cf8-6c7ffb60e387)

This is the code for the section in the screenshots

```yaml
type: grid
cards:
  - type: heading
    heading: Tudor
    heading_style: title
    icon: mdi:face-man
  - hours_to_show: 24
    graph: line
    type: sensor
    entity: sensor.tudors_current_speed
    detail: 1
  - hours_to_show: 24
    graph: line
    type: sensor
    entity: sensor.tudor_time_to_home
    detail: 2
  - type: history-graph
    entities:
      - entity: person.tudor
      - entity: binary_sensor.tudor_is_driving
      - entity: sensor.home_tudor_direction_of_travel
      - entity: sensor.home_tudor_distance
    layout_options:
      grid_columns: 6
      grid_rows: auto
column_span: 1

```

### Describe the behavior you expected

Smaller padding for graphs

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.2.0b2

### What was the last working version of Home Assistant Core?

2025.1.4

### In which browser are you experiencing the issue?

all browsers and mobile companion app

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
