### ISSUE TITLE
History graph card does not display chart if legend is hidden

### ISSUE THREAD

**Issue by Yevgenium** [home-assistant/frontend#24008]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If you add two or more entities to the History graph card and hide the legend using the `show_names` variable, the graph disappears completely.

Example configuration:
```
type: history-graph
hours_to_show: 3
show_names: false
entities:
  - entity: sensor.28_ffc6d2a21604_temperature
  - entity: sensor.sonoff_basic_t2
```

### Describe the behavior you expected

Drawing a chart according to its values.

### Steps to reproduce the issue

1. Create a History graph card with two or more entities.
2. Hide the legend using the `show_names` variable.

### What version of Home Assistant Core has the issue?

core-2025.2.0b4

### What was the last working version of Home Assistant Core?

core-2025.2.0b2

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
