### ISSUE TITLE
long wrapping state value taking too much space

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#24009]
as per 2025.2 beta this is happening 

![Image](https://github.com/user-attachments/assets/2f5c60fe-cbce-4e7f-916b-20d04490b866)

```
type: entities
title: Test long state wrap
entities:
  - entity: sensor.last_boot
    format: datetime
```

on smaller screens like an iPhone

Desktop shows:

<img width="981" alt="Image" src="https://github.com/user-attachments/assets/63ec4a64-a6a8-4b36-baa8-4f57751b03c5" />

<img width="441" alt="Image" src="https://github.com/user-attachments/assets/60cfc177-0881-44c6-992a-3f600c9616fe" />

and before, the wrapping would snap in to the secondary_info line height 

__edited__

to make card as core and clear as possible
