### ISSUE TITLE
history-graph showing weird update animations on graphs with gaps

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#24019]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In 2025.2.0b4 I've noticed that the graphs are showing weird update animations if there are gaps in the data (due to a system reboot):

https://github.com/user-attachments/assets/3457dd68-b46c-4e52-9f97-fab7160f2bc9

### Describe the behavior you expected

No weird motion of graphs if the data is updated

### Steps to reproduce the issue

1. Create history graph
2. Graph values with gaps
3. See a weird update animation play on each update for the section with no data updates

### What version of Home Assistant Core has the issue?

2025.2.0b4

### What was the last working version of Home Assistant Core?

2025.1.0

### In which browser are you experiencing the issue?

Chrome 128.0.6613.189 / Firefox 129.0.2

### Which operating system are you using to run this browser?

ArchLinux

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by MindFreeze** [comment]
Is this still present in 2025.2.0b6 ? I can't reproduce it.

**Comment by RubenKelevra** [comment]
I tried like 5 times to update before creating this ticket. After a couple more tries it finally worked now half an hour ago

**Comment by RubenKelevra** [comment]
> Is this still present in 2025.2.0b6 ? I can't reproduce it.

Still present in 2025.20b6, and I can also confirm it for the Android App:

https://github.com/user-attachments/assets/4211ec41-0e20-4521-814b-7fa7f203f00d

**Comment by RubenKelevra** [comment]
Here's my config:

```
type: vertical-stack
cards:
  - type: history-graph
    entities:
      - entity: sensor.lamp_left_room_ceiling_spot_power
      - entity: sensor.target_brightness_left_room
      - entity: sensor.lamp_left_room_ceiling_2_power
      - entity: sensor.brightness_left_room_illuminance
      - entity: sensor.brightness_left_room_desktop_illuminance
      - entity: sensor.illuminance_sensor_left_room_under_desktop
      - entity: sensor.adaptive_lighting_light_temperature_selection
      - entity: sensor.light_sensor_outdoor_light_sensor_outdoor_color_temperature
      - entity: input_boolean.left_room_lights
      - entity: sensor.ambient_light_sensor_illuminance
      - entity: sensor.ambient_light_sensor_color_temperature
      - entity: input_number.light_temperature_delta_left_room
    logarithmic_scale: false
    fit_y_data: false
    hours_to_show: 0.5
```
