### ISSUE TITLE
Dashboard yaml editor is silently mangling my templates

### ISSUE THREAD

**Issue by fallingcats** [home-assistant/frontend#24056]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Manual yaml editor of dashboard - please disable hard line wrapping and template reformating during yaml save, it's really annoying for manual editing.

I'm trying to save the following part of my dashboard's yaml:

```yaml
              - type: custom:mushroom-template-card
                primary: Bedroom
                multiline_secondary: false
                layout: vertical
                secondary: >-
                  {% set valve_name = 'climate.netatmo_local_bedroom' %}
                  {% set current_temperature = state_attr(valve_name, 'current_temperature') | float %}
                  {% set target_temperature = state_attr(valve_name, 'temperature') | float %}

                  {{ current_temperature }} ˚C 
                  {% if current_temperature < target_temperature %}
                    / {{ target_temperature }} ˚C
                  {% endif %}
                badge_icon: >-
                  {% if state_attr('climate.netatmo_local_bedroom', 'hvac_action') == 'heating' %}
                    mdi:thermometer-chevron-up
                  {% endif %}
                badge_color: orange
                icon: mdi:bed
                icon_color: >-
                  {% if (is_state('switch.bedroom_tv_screen_state', 'off') and is_state('light.bedroom_tv_ambilight', 'on')) or (is_state('light.bedroom_bulb', 'on')) %}
                    yellow
                  {% endif %}
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/bedroom
                double_tap_action:
                  action: none
                entity: light.bedroom_tv_ambilight
                hold_action:
                  action: none
```

When I save it, I don't see instantly, that it has beed reformated - the code in editor didn't changed. But after page refresh, my yaml has been changed to this (there are some line wraps in templates and some expressions were moved to previous lines):

```yaml
              - type: custom:mushroom-template-card
                primary: Bedroom
                multiline_secondary: false
                layout: vertical
                secondary: >-
                  {% set valve_name = 'climate.netatmo_local_bedroom' %} {% set
                  current_temperature = state_attr(valve_name,
                  'current_temperature') | float %} {% set target_temperature =
                  state_attr(valve_name, 'temperature') | float %}

                  {{ current_temperature }} ˚C  {% if current_temperature <
                  target_temperature %}
                    / {{ target_temperature }} ˚C
                  {% endif %}
                badge_icon: >-
                  {% if state_attr('climate.netatmo_local_bedroom',
                  'hvac_action') == 'heating' %}
                    mdi:thermometer-chevron-up
                  {% endif %}
                badge_color: orange
                icon: mdi:bed
                icon_color: >-
                  {% if (is_state('switch.bedroom_tv_screen_state', 'off') and
                  is_state('light.bedroom_tv_ambilight', 'on')) or
                  (is_state('light.bedroom_bulb', 'on')) %}
                    yellow
                  {% endif %}
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/bedroom
                double_tap_action:
                  action: none
                entity: light.bedroom_tv_ambilight
                hold_action:
                  action: none
```

### Describe the behavior you expected

yaml editor should keep the content of templates without reformatting/line wrapping.

### Steps to reproduce the issue

1.Open raw yaml editor of dashboard and use templates in it like is mentioned in description.

### What version of Home Assistant Core has the issue?

2025.1.4

### What was the last working version of Home Assistant Core?

not for 2 years at least

### In which browser are you experiencing the issue?

Firefox 134.0.2

### Which operating system are you using to run this browser?

Arch Linux

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

Originally reported as #16718 by @cniry, closed by stale bot
