### ISSUE TITLE
Small Energy Values Not Displayed Properly (0 kWh Instead of Wh)

### ISSUE THREAD

**Issue by Revilo91** [home-assistant/frontend#24115]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Small decimal values ​​that are less than 1kWh are not displayed correctly.

![Image](https://github.com/user-attachments/assets/c6c9394e-6fe6-4ed3-ac8a-ce9ccb1fe83d)

### Describe the behavior you expected

Values ​​should be displayed in Wh if they are less than 1kWh.

### Steps to reproduce the issue

```
chart_type: bar
period: hour
type: statistics-graph
entities:
  - entity: sensor.smartmeter_consumed_energy
    name: Bezogen
  - entity: sensor.smartmeter_provided_energy
    name: Eingespeist
stat_types:
  - change
days_to_show: 1
```

### What version of Home Assistant Core has the issue?

core-2025.2.0

### What was the last working version of Home Assistant Core?

core-2025.1.x

### In which browser are you experiencing the issue?

Google Chrome 133.0.6943.54 (64-Bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
