### ISSUE TITLE
Stats Graph Tooltip does not drop below curser at top of graph with many entities and slides out of window

### ISSUE THREAD

**Issue by Happy-Cadaver** [home-assistant/frontend#24134]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a stats graph at the top of a view with 13 entities (RSSI) and the tooltip stays above the curser at the top of the graph and slides outside ot the viewport. The tooltip drops below the curser on other graphs with less entities.

![Image](https://github.com/user-attachments/assets/2216c6c0-996f-41b7-98d1-e23948808aa2)

### Describe the behavior you expected

I expect the tooltip to drop below the curser at the top of the graph.

### Steps to reproduce the issue

1. Create a statistics graph as the first item in a view with 13 entities.
2. Hover over the top of the graph.
3.
...

### What version of Home Assistant Core has the issue?

2025.2.1

### What was the last working version of Home Assistant Core?

None, new feature.

### In which browser are you experiencing the issue?

Iridium, Edge, and Chrome

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: 5minute
type: statistics-graph
entities:
  - sensor.basement_bedroom_1_ceiling_2_signal_strength
  - sensor.basement_bathroom_1_vanity_1_signal_strength
  - sensor.bedroom_power_signal_strength
  - sensor.fridge_signal_strength
  - sensor.lamp_2_signal_strength
  - sensor.livingarea_central_signal_strength
  - sensor.smart_plug_signal_strength
  - sensor.tt_8l_roomminder_02_rssi
  - sensor.tt_8l_gatekeeper_rssi
  - sensor.main_livingarea_1_lamp_1_signal_strength
  - sensor.basement_bedroom_1_ceiling_1_signal_strength
  - sensor.basement_bedroom_1_ceiling_3_signal_strength
  - sensor.bedside_lamp_signal_strength
stat_types:
  - max
grid_options:
  columns: 24
  rows: 6
days_to_show: 1
```

### Javascript errors shown in your browser console/inspector

```txt
No Errors.
```

### Additional information

I noticed this towards the end of beta and posted it to Discord, waited until 2025.2.1 to see if it persisted.
