### ISSUE TITLE
Weather forecast card configuration not restored on backend restart

### ISSUE THREAD

**Issue by bioxz** [home-assistant/frontend#24133]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have _Weather forecast cards_  with custom settings (i.e. something that is not the default, like showing the forecast). Every time the backend gets restarted (e.g. HA update or restart, HAOS update or restart), the weather forecast cards end up in the default state (but original card size) displaying just the current weather. This can be solved by reloading the page or changing the view.

This example shows to weather forecast cards (config is provided), one with the current weather, one with the forecast.

![Image](https://github.com/user-attachments/assets/95aee3c0-b080-47c4-88cf-8fc6e99810c4)

After restarting HA, both cards reload with showing just the current weather (picture 2). Reloading the view in any way and I end up with the original display (picture 1) as configured.

![Image](https://github.com/user-attachments/assets/90a5b24e-4e40-450d-89d6-426da7689089)

This happens for me some months now (I actually thought this issue would be well known and thus hoped it would go away at one point). It's reproducible in browser (Firefox) and (more annoyingly) on my Android with the official app as my wall mounted dashboard, which requires a manual reload from me each time HA gets restarted.

I recreated this issue with a minimal dashboard and in safe mode.

### Describe the behavior you expected

I expect the weather forecast card to always get displayed as configured, e.g. as shown in the first picture.

### Steps to reproduce the issue

1. Create a dashboard with a weather forecast card using custom settings (e.g. use the dashboard config provided).
2. Keep the dashboard open on any device.
3. Restart HA.
4. Check the still open dashboard. All weather forecast cards are now in their default state without their settings.

### What version of Home Assistant Core has the issue?

2025.2.1

### In which browser are you experiencing the issue?

Firefox (current versions for at least a year), Android App (current versions for at least a year)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - show_current: true
            show_forecast: false
            type: weather-forecast
            entity: weather.home
            secondary_info_attribute: humidity
            forecast_type: daily
          - show_current: false
            show_forecast: true
            type: weather-forecast
            entity: weather.home
            secondary_info_attribute: humidity
            forecast_type: daily
```

### Javascript errors shown in your browser console/inspector

```txt

```
