### ISSUE TITLE
Grid card icon status takes 1 minute to update

### ISSUE THREAD

**Issue by rrediske** [home-assistant/frontend#24157]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a grid card of icons to toggle switches. Since the last update (possibly last two?), when I click on an icon, it doesn't change state for exactly one minute. My grid includes 15 different switches with different underlying hardware (Shelly, Kauf, Tasmota, Koogeek, TP-Link) and they all behave the same way. If it's off and I tap or click the icon, the icon doesn't change to "on" status on any Home Assistant client until exactly 60 seconds later. It has the same behavior on the iOS app, firefox and msedge browsers.

### Describe the behavior you expected

I've only used the grid card for about 18 months, but I never recall waiting more than a second or two for the on/off status to update across all connected clients.

### Steps to reproduce the issue

1. Create icon grid.
2. Login to HA interface,
3. Tap/click icon.
...

### What version of Home Assistant Core has the issue?

core-2025.2.1 - Frontend: 20250205.0

### What was the last working version of Home Assistant Core?

core-2025.1.5

### In which browser are you experiencing the issue?

firefox, msedge, brave, android chrome, samsung internet (android)

### Which operating system are you using to run this browser?

Linux, MacOS, iOS, GrapheneOS

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
square: true
columns: 5
type: grid
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    icon: mdi:monitor
    icon_height: 30px
    show_state: false
    entity: switch.tp_link_power_strip_1b6b_kasa_smart_plug_1b6b_1
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    icon: mdi:floor-lamp
    name: Living
    icon_height: 30px
    show_state: false
    entity: switch.plug_14
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    icon: mdi:floor-lamp
    name: Guest
    icon_height: 30px
    show_state: false
    entity: switch.tp_link_power_strip_1b6b_kasa_smart_plug_1b6b_5
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    icon: mdi:floor-lamp
    name: Desk
    icon_height: 30px
    show_state: false
    entity: switch.kauf_plug_27
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.tp_link_power_strip_2e3a_plug_2
    icon: mdi:floor-lamp
    icon_height: 30px
    name: Bed
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.koogeek_kitchen_outlet2
    icon: mdi:pizza
    icon_height: 30px
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.koogeek_kitchen_outlet3
    icon: mdi:coffee-maker
    icon_height: 30px
    name: Coffee
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.tp_link_power_strip_1b6b_kasa_smart_plug_1b6b_2
    icon: mdi:coffee
    icon_height: 30px
    name: Cup
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.kauf_plug_28
    icon_height: 30px
    name: Shoe
    icon: mdi:shoe-sneaker
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: automation.bed_light_am
    name: Alarm
    icon: mdi:alarm-light
    icon_height: 30px
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.kauf_plug_20
    name: Bath
    icon: mdi:fan
    icon_height: 30px
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.tp_link_power_strip_2e3a_plug_1
    icon_height: 30px
    icon: mdi:fan
    name: Bed
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.kauf_plug_29
    icon_height: 30px
    name: Base
    icon: mdi:fan
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: lock.back_door
    icon_height: 30px
    name: Back
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.garage_door
    icon_height: 30px
    icon: mdi:garage
    name: Garage
```

### Javascript errors shown in your browser console/inspector

```txt
none
```
