### ISSUE TITLE
History-graph: a "state" label may be misplaced

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#24163]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There is a very erratic issue I see sometimes:
1. Create a card:
```
type: vertical-stack
cards:
 - type: history-graph
   show_names: false
   hours_to_show: 24
   entities:
     - entity: sun.sun
 - type: history-graph
   show_names: false
   hours_to_show: 24
   entities:
     - entity: sun.sun
```
2. A view must be in a Panel mode.
3. Open UI editor for the card.
4. Close UI editor.
5. The card is shown with a misplaced "state" label:

![Image](https://github.com/user-attachments/assets/a4292b12-3cfb-4663-b2d4-fb19767dfdef)

6. After a few seconds a look becomes normal.

Same was observed with a horizontal stack.
I could not reproduce it with a single card (i.e. not in a stack card).
Also, could not reproduce it in a masonry layout.
Even in a Panel layout the issue is observed erratically, sometime I have to repeat same "F5 - open UI editor - close UI editor" several time to get the glitch.

IMHO it is a glitch inside Echarts.
Difficult to say since many [issues](https://github.com/apache/echarts/issues) are registered in Japanese...

### Describe the behavior you expected

"State" labels are properly positioned.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2025.2.1

### In which browser are you experiencing the issue?

Chrome 133.0.6943.60 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
