### ISSUE TITLE
2025.2.0: statistics-graph cards no longer update

### ISSUE THREAD

**Issue by wouttom** [home-assistant/frontend#24167]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After upgrading to 2025.2.1 all dashboard-cards with
```
          - chart_type: line
            type: statistics-graph
```
stopped automatically updating with new data.
Even after several hours the graphs never updated. 

I reverted to 2025.1.4, after which all cards were updating themselves as expected.

### Describe the behavior you expected

When a dashboards stays open, the graphs are automatically updated as new data for a metric arrives.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.2.1

### What was the last working version of Home Assistant Core?

2025.1.4

### In which browser are you experiencing the issue?

Firefox 134, and the IOS app

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: 5minute
type: statistics-graph
entities:
  - sensor.envoy_xxxx_current_power_consumption
  - sensor.envoy_xxxx_current_power_production
  - sensor.site_load_connector_1
stat_types:
  - mean
hide_legend: true
days_to_show: 0.5
unit: W
grid_options:
  rows: 4
  columns: full

---
chart_type: line
period: 5minute
type: statistics-graph
entities:
  - sensor.power_usage
stat_types:
  - mean
  - min
  - max
unit: W
hide_legend: true
days_to_show: 0.5
grid_options:
  columns: full
  rows: 4
```

### Javascript errors shown in your browser console/inspector

```txt

```
