### ISSUE TITLE
Statisctics Diagram: Logarithmic scale is not displayed correctly since 2025.2

### ISSUE THREAD

**Issue by christian-schauer** [home-assistant/frontend#24232]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the statistics diagram overhaul in 2025.2, the logarithmic scale is not displayed correctly anymore as the lines for 0 or null values do not drop to 0 anymore: 

![Image](https://github.com/user-attachments/assets/8e40bea1-9418-427e-a7e5-f80c7b499391)

### Describe the behavior you expected

For all 0 or null values of a data series, the line in the chart should drop to 0. This worked perfectly until the recent overhaul of the statistics diagrams. 

### Steps to reproduce the issue

1. Create a dashboard with a statistics diagram. 
2. Use time series data that has 0 values (e.g. like inverter production of a PV).
3. Observe the issue
...

### What version of Home Assistant Core has the issue?

2025.2.3

### What was the last working version of Home Assistant Core?

2025.1.4

### In which browser are you experiencing the issue?

Google Chrome Version 132.0.6834.160 (also verified in latest Firefox version)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: 5minute
type: statistics-graph
entities:
  - entity: sensor.wechselrichter_sud_string_leistung
    name: Süd
  - entity: sensor.wechselrichter_ost_string_leistung
    name: Ost
  - entity: sensor.wechselrichter_west_string_leistung
    name: West
  - entity: sensor.wechselrichter_garten_leistung_von_p1
    name: Garten
stat_types:
  - mean
logarithmic_scale: true
days_to_show: 1
hide_legend: false
card_mod:
  style: |
    ha-card {
      --graph-color-1: red;
      --graph-color-2: blue;
      --graph-color-3: orange;
      --graph-color-4: green;
    }
```

### Javascript errors shown in your browser console/inspector

```txt

```
