### ISSUE TITLE
long area names overlapping with icon on area card with sensors below title

### ISSUE THREAD

**Issue by pax85** [home-assistant/frontend#24246]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I noticed when adding an area card that contains a long name + a row of sensors, that the name is slightly overlapping with the area mdi icon on the card itself.

![Image](https://github.com/user-attachments/assets/0cf3faa4-2bc9-475e-ae0f-f7aa650c75ff)

I've tried to change the aspect_ratio, but entering any ratio in any format listed on the documentation (https://www.home-assistant.io/dashboards/area) doesn't change anything on the area card.
The documentation isn't explicit if this attribute even works with areas that don't have an image, so I tried adding an image to an area and adjust the aspect_ratio again, but that also didn't affect the card.

In the end I was unsure if I should report the title or the aspect_ratio as a bug, and chose the title as I believe there shouldn't be that much overlap in the out-of-the-box card design.

Behaviour is the same on my MacBook and in the iOS/iPadOS Home Assistant app.

### Describe the behavior you expected

Expected the name to not touch the mdi icon on area card.
Expected the aspect ratio to work on the area card, even if it's not using an image.

### Steps to reproduce the issue

1. create empty dashboard
2. add area card with longer title/name
3. have a list one sensor row on the area card

### What version of Home Assistant Core has the issue?

core-2025.2.4

### In which browser are you experiencing the issue?

Version 1.75.175 Chromium: 133.0.6943.54 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

masOS Monterey 12.7.6

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
- type: grid
        cards:
          - alert_classes:
              - motion
              - moisture
            sensor_classes:
              - temperature
              - humidity
            type: area
            area: grosser_kellerraum_regale
          - type: gauge
            entity: sensor.kg_grosser_kellerraum_regale_mold_indicator_helper
            severity:
              green: 40
              yellow: 60
              red: 70
            name: Mold Indicator
            needle: true
            unit: '%'
        column_span: 1
```

### Javascript errors shown in your browser console/inspector

```txt

```
