### ISSUE TITLE
History graph legend no longer shows all entities

### ISSUE THREAD

**Issue by cwitting** [home-assistant/frontend#24263]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After one of the latest updates the history graph legends no longer shows all legends when you plot multiple entities, you have to click an arrow to see more.
This makes it much harder to get an overview of the plots as you cannot see what the colors represents without excessive back and forth clicking. Especially when you have a lot of plots.
I also often share plots using screenshots, which is no longer possible as people cannot see what the graphs represent.

Is there a way to get the old full legend back?

You can see what I mean on this plot here:

![Image](https://github.com/user-attachments/assets/4c9d57b1-df49-4c78-b067-992f5ec05492)

There is no way of knowing what green and red represents from the image alone.

### Describe the behavior you expected

That the history graph legend shows all entity names and colors at the same time.

### Steps to reproduce the issue

1. Create a history card with multiple entities (3+) of the same type in the same plot
2. See that the legend is not fully visible and an arrow has to be clicked to see the rest

### What version of Home Assistant Core has the issue?

2025.2.4

### What was the last working version of Home Assistant Core?

I think before 2025.2.0

### In which browser are you experiencing the issue?

Google Chrome Version 133.0.6943.98 (Official Build) (64-bit), but all browsers really

### Which operating system are you using to run this browser?

Ubuntu 24.04 and Samsung Galaxy S23, etc

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
- type: history-graph
            entities:
              - entity: sensor.living_room_thermo_temperature
              - entity: sensor.bedroom_thermo_temperature
              - entity: sensor.bme280_temperature
              - entity: sensor.stue_temperature
            hours_to_show: 24
            refresh_interval: 0
```

### Javascript errors shown in your browser console/inspector

```txt

```
