### ISSUE TITLE
History graph Card UI issue

### ISSUE THREAD

**Issue by musapinar** [home-assistant/frontend#24356]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### The problem

History graph card, when working normally, shows a legend on top of the graph, with corresponding colors.

Good : 
![Image](https://github.com/user-attachments/assets/ca484c25-68bf-4c1a-b85d-8a5763a814ad)

When overloaded with more entities, the user-interface fails, and the legend's user-interface is bugged (timeline is shown twice and has a padding on top.
Bad : 
![Image](https://github.com/user-attachments/assets/426012b6-aa95-4cc2-acc1-ee26f818807f)

### What version of Home Assistant Core has the issue?

core-2025.2.5

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
type: history-graph
entities:
  - entity: sensor.ct_clamp_current_sensor_2_power_a
    name: Pompe à chaleur
  - entity: sensor.ct_clamp_current_sensor_4_power_b
    name: Chauffe-eau
  - entity: sensor.prise_connectee_lave_linge_power
    name: Lave-linge
  - entity: sensor.ct_clamp_current_sensor_power_a
    name: Plaque de cuisson
  - entity: sensor.prise_connectee_onduleur_power
    name: Onduleur
  - entity: sensor.prise_connectee_lave_vaisselle_power
    name: Lave-vaisselle
  - entity: sensor.prise_connectee_televiseur_atelier_power
    name: Téléviseur atelier
  - entity: sensor.prise_connectee_refrigerateur_power
    name: Réfrigérateur
  - entity: sensor.prise_connectee_cameras_de_surveillance_power
    name: Caméras de surveillance
  - entity: sensor.prise_connectee_buanderie_power
    name: Buanderie
  - entity: sensor.ct_clamp_current_sensor_3_power_b
    name: Éclairages rez-de-chaussée
  - entity: sensor.ct_clamp_current_sensor_3_power_a
    name: Éclairages étage
  - entity: sensor.ct_clamp_current_sensor_power_b
    name: Four
  - entity: sensor.ct_clamp_current_sensor_2_power_b
    name: Climatiseur atelier
  - entity: sensor.ct_clamp_current_sensor_4_power_a
    name: VMC
hours_to_show: 1
logarithmic_scale: false
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

I noticed deleting this node fixes the UI : 

![Image](https://github.com/user-attachments/assets/153df17a-1672-46fe-a279-15bb8153a6b9)

![Image](https://github.com/user-attachments/assets/c1e5ca7c-c6a9-46e1-8858-c195f75c6c7c)

However it might be required in some other use-cases.

### Describe the behavior you expected

no timeline on top, no padding/margin

### Steps to reproduce the issue

1.create a card of type "history-graph"
2.add many entitites
3.
...

### What version of Home Assistant Core has the issue?

core-2025.2.5

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
