### ISSUE TITLE
empty grid in grid of tiles resizes row incorrectly

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#24369]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

using empty grid 
<img width="519" alt="Image" src="https://github.com/user-attachments/assets/782f9f37-e427-4765-b4a6-1fee48b0569d" />

### Describe the behavior you expected

<img width="526" alt="Image" src="https://github.com/user-attachments/assets/abbba785-f495-4884-90f6-9b418f0f37db" />

Now requires fixing with custom:button-card. (or other custom card, `custom:gap-card` comes to mind provided by `custom:layout-card`)

Would be great if we could natively set an empty spot in the grid, and especially one that adapts to the actual card-height as shown here

### Steps to reproduce the issue

1. see yaml below 
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.2.5

### In which browser are you experiencing the issue?

any

### Which operating system are you using to run this browser?

macOS Sequoia 15.3.1

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

resizing caused by empty grid
```yaml
      - type: grid
        columns: 2
        square: false
        cards:

          - type: tile
            entity: light.sportkamer_plafond
          - type: grid
            cards: []

          - type: tile
            entity: light.sportkamer_links
          - type: tile
            entity: light.sportkamer_rechts
```

so need to replace with custom button-card
```yaml
      - type: grid
        columns: 2
        square: false
        cards:

          - type: tile
            entity: light.sportkamer_plafond
          - type: custom:button-card
            color_type: blank-card

          - type: tile
            entity: light.sportkamer_links
          - type: tile
            entity: light.sportkamer_rechts
```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ildar170975** [comment]
Add `square: false` to fix it:

![Image](https://github.com/user-attachments/assets/7e211435-75ad-4c78-93e3-b08804f420f2)

(although could be considered as merely a workaround)

**Comment by Mariusthvdb** [comment]
right that is a nice workaround.
I use this empty grid all over as an empty placeholder in my grids, and this was the first time I encountered the incorrect spacing.

Ill add it now, but believe the main grid's setting `square: false` should be inherited by the nested grid?

**Comment by ildar170975** [comment]
A possible fix could be NOT adding a `:before` pseudoclass if `cards` is empty.

**Comment by MindFreeze** [comment]
Can't you just add `square: false` to the child grid?

**Comment by Mariusthvdb** [comment]
yes we can.
though, as I wrote above, having set that in the main config should set it for all contained cards, even a grid?

**Comment by MindFreeze** [comment]
The space it takes looks like 3 squares in a row, which makes sense as this is the default config. Inheritance in cards is not supported and not a trivial topic.
I do agree we need an empty/placeholder card in core. You shouldn't need weird workarounds like this. But that should be a separate PR and I don't think we should modify the grid card for this workaround.

**Comment by Mariusthvdb** [comment]
ok thanks,
as a follow-up question on that subject: if we would set that like this

```
      - type: grid
        columns: 2
        square: false
        cards:

          - type: tile
            entity: light.sportkamer_plafond
          - type: empty

          - type: tile
            entity: light.sportkamer_links
          - type: tile
            entity: light.sportkamer_rechts
```

would it also take the `square: false` of the main config?
