### ISSUE TITLE
header: options not working in subview

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#24427]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

2025.3 beta introducés the header: option 
```
title: Welkom
icon: mdi:home
path: welkom
header:
  badges_position: bottom
  card:
    type: markdown
    text_only: true
    content: |
     # Hallo {{ user }}
```

which works nicely, and we can even add other cards.

However, this does Not work if the view is a subview, simply nothing is displayed

(my particular usecase is I have many of those markdowns, and especially so on the subviews...)
would be nice if this could be fixed if indeed not per desing

if it would be per design, please see this as a FR to add it to subviews ;-)

### Describe the behavior you expected

header: being functional in subviews

### Steps to reproduce the issue

1. see above
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.3.0b0

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
see above
```

### Javascript errors shown in your browser console/inspector

```txt

```
