### ISSUE TITLE
Weather forecast card overflows in dashboard and edit window

### ISSUE THREAD

**Issue by Rrp13** [home-assistant/frontend#24443]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Weather card overflows when you set the max number of forcast to 12 in edit mode for laptops and tablets and is perfect for mobile but in companion app the the card overflows in the dashboard.

### Describe the behavior you expected

Weather card shouldnot overflow and be bound within the card or be scrollable like in more info.

### Steps to reproduce the issue

1. Goto Section View
2. Add Weather Forecast Card
3. Set the max number of forecast to 12

### What version of Home Assistant Core has the issue?

2025.3.b1

### What was the last working version of Home Assistant Core?

2025.2

### In which browser are you experiencing the issue?

Microsoft Edge Version 133.0.3065.82 and Companion app 2025.1.2-full

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
show_current: true
show_forecast: true
type: weather-forecast
entity: weather.forecast_home
forecast_type: hourly
secondary_info_attribute: temperature
forecast_slots: 12
grid_options:
  columns: full
```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

**Weather Forecast Card Edit Mode in Laptop**
![Image](https://github.com/user-attachments/assets/e1602235-b82f-47e9-9b7d-7d4b51f6d2da)
**Weather Card in Companion App**
![Image](https://github.com/user-attachments/assets/ef6caea1-0a58-4fa6-956d-939c3eeb8525)
_Small nitpick the padding in mobile seems too tight and the C on the far right is cut off and this only happens in mobile._
