### ISSUE TITLE
Layout config of card is forgotten when card config in GUI is opened in 2025.3.0b1

### ISSUE THREAD

**Issue by TheFes** [home-assistant/frontend#24444]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On my dashboard I have cards like this, set up to be shown using 6 columns and 2 rows.

<img width="106" alt="Image" src="https://github.com/user-attachments/assets/5f8d48d4-da5f-4e80-98b2-395f016c72fc" />

As soon as I open the configuration in the GUI, it seems to forget this configuration, and uses 12 x 1

<img width="505" alt="Image" src="https://github.com/user-attachments/assets/149dfdc2-a608-45cd-b005-3a80323844d9" />

Saving without setting the layout correctly results in a changed layout

<img width="187" alt="Image" src="https://github.com/user-attachments/assets/7f8ec073-b86b-4f3f-8f73-4858a445904a" />

This means that every time I want to change a card, I need to correct the layout.

### Describe the behavior you expected

Layout settings to be remembered

### Steps to reproduce the issue

1. Set a custom layout on a card
2. Save the card
3. Open card settings
4. Save the card again
...

### What version of Home Assistant Core has the issue?

core-2025.3.0b1

### What was the last working version of Home Assistant Core?

core-2025.2.5

### In which browser are you experiencing the issue?

Google Chrome 133.0.6943.127

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
type: custom:vertical-stack-in-card
cards:
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.area_data_vliering
        state: red
    card:
      type: tile
      entity: sensor.area_data_vliering
      tap_action:
        action: navigate
        navigation_path: vliering
      state_content: text
      color: red
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.area_data_vliering
        state: yellow
    card:
      type: tile
      entity: sensor.area_data_vliering
      tap_action:
        action: navigate
        navigation_path: vliering
      state_content: text
      color: yellow
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.area_data_vliering
        state: default
    card:
      type: tile
      entity: sensor.area_data_vliering
      tap_action:
        action: navigate
        navigation_path: vliering
      state_content: text
  - type: horizontal-stack
    cards:
      - type: grid
        cards: []
      - type: tile
        entity: light.vliering_led
        hide_state: true
        name: "‎ "
        color: yellow
        tap_action:
          action: toggle
        icon_tap_action:
          action: toggle
      - type: grid
        cards: []
```

### Javascript errors shown in your browser console/inspector

```txt

```
