### ISSUE TITLE
Entities card & more-info pop up shows incorrect state when calling turn_off raises an error

### ISSUE THREAD

**Issue by StaleLoafOfBread** [home-assistant/frontend#24455]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you click on the toggle switch on the entities card or the more-info pop-up to turn off an entity and that entity raises a service error, then the UI will show the toggle as off until you refresh the screen. 

This problem does not exist in the tile card.

![Image](https://github.com/user-attachments/assets/2cc4642f-b576-4eea-9145-ce26122b9532)

Discovered in https://github.com/home-assistant/core/pull/139483#discussion_r1975825115

### Describe the behavior you expected

Ideally the toggle would remain in the `on` position. At the very least, it would flip back to `on` after a short duration.

### Steps to reproduce the issue

1. Use the version of `alert` component from this PR and create an alert with `can_acknowledge` set to `false` https://github.com/home-assistant/core/pull/139483
2. Alternatively you can modify `inputboolean` (and I suspect others but I did not check) to raise an error in their `turn_off` function.
3. Add an entities card to your dashboard like
```yaml
type: entities
entities:
  - alert.test_alert_not_ackable
title: Alert
```
4. Ensure the state of the entity is on
5. Click the toggle to turn it off and observe that it raises an error but the UI shows it as a state of `off` despite the service call failing

### What version of Home Assistant Core has the issue?

2025.2.5

### In which browser are you experiencing the issue?

Google Chrome Version 133.0.6943.142 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
title: Home
cards: []
type: sections
sections:
  - type: grid
    cards:
      - type: heading
        heading: Alert from PR#139483
        heading_style: title
      - type: entity
        entity: alert.test_alert_not_ackable
        state_color: true
      - type: entities
        entities:
          - entity: alert.test_alert_not_ackable
        title: Alert
      - type: tile
        entity: alert.test_alert_not_ackable
        features_position: bottom
        vertical: false
        tap_action:
          action: toggle
  - type: grid
    cards:
      - type: heading
        heading: Modified inputboolean to always raise error on turn_off
        heading_style: title
      - type: entity
        entity: input_boolean.test_alerting
        state_color: true
      - type: entities
        entities:
          - input_boolean.test_alerting
        title: Helpers
      - type: tile
        entity: input_boolean.test_alerting
        features_position: bottom
        vertical: false
        tap_action:
          action: toggle
```

### Javascript errors shown in your browser console/inspector

```txt
From entities card:
ha-entity-toggle.ts:153 Uncaught (in promise) {code: 'service_validation_error', message: 'Validation error: This alert cannot be acknowledged'}code: "service_validation_error"message: "Validation error: This alert cannot be acknowledged"[[Prototype]]: Object
value @ ha-entity-toggle.ts:153
await in value
value @ ha-entity-toggle.ts:95
handleEvent @ lit-html.ts:2018
(anonymous) @ mwc-switch-base.ts:121



From tile card:
connection-mixin.ts:156 Uncaught (in promise) {code: 'service_validation_error', message: 'Validation error: This alert cannot be acknowledged'}
callService @ connection-mixin.ts:156
await in callService
i @ turn-on-off-entity.ts:34
(anonymous) @ toggle-entity.ts:10
h @ handle-action.ts:141
value @ hui-tile-card.ts:140
handleEvent @ lit-html.ts:2018
n @ fire_event.ts:75
t.actionHandler.e.disabled.t.actionHandler.end @ action-handler-directive.ts:185
```

### Additional information

```
Core 2025.2.5
Supervisor 2025.02.4
Operating System 14.2
Frontend 20250221.0
```
