### ISSUE TITLE
Number format not respected in charts

### ISSUE THREAD

**Issue by erikgeurts** [home-assistant/frontend#24461]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I've set my preference for number format as follows:

![Image](https://github.com/user-attachments/assets/f8149f50-67fc-49ba-8503-a722e5976dc8)

Yet, charts insist on using a comma as the thousands separator:

![Image](https://github.com/user-attachments/assets/9f42ef21-db71-47ef-80af-404b9c7f7d62)

### Describe the behavior you expected

I'd expect that UI elements respect the number format the user has indicated in their settings. Even when (obviously) the entity's state internally is represented as 90654.3 in the database.

### Steps to reproduce the issue

n/a

### What version of Home Assistant Core has the issue?

2025.2.5

### In which browser are you experiencing the issue?

Chrome, ChromeOS, Android companion app (it's not a browser thing though)

### Which operating system are you using to run this browser?

Windows, ChromeOS, Android

### State of relevant entities

```txt
sensor.niro_odometer
state: 90654.3

state_class: total_increasing
unit_of_measurement: km
device_class: distance
icon: mdi:speedometer
friendly_name: NIRO Odometer
```

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: week
type: statistics-graph
entities:
  - sensor.niro_odometer
  - sensor.niro_next_service
stat_types:
  - state
days_to_show: 450
hide_legend: true
title: Kilometerstand
```

### Javascript errors shown in your browser console/inspector

```txt

```
