### ISSUE TITLE
beta -  history-graph: Entities in the legend are cut off

### ISSUE THREAD

**Issue by Revilo91** [home-assistant/frontend#24477]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Entities in the legend are cut off

![Image](https://github.com/user-attachments/assets/84be8d0e-7bb6-4fee-9a2b-ae573d6a914b)

### Describe the behavior you expected

If you separate the values ​​because they have different units, then all entities are displayed
![Image](https://github.com/user-attachments/assets/49448789-65d3-467f-9dea-91cac6144b50)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2025.3.0b3

### What was the last working version of Home Assistant Core?

core-2025.2.x

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

**first image:**
```
  - type: history-graph
    entities:
      - entity: sensor.ebusd_pms_ntc1sensor_temp
      - entity: sensor.ebusd_pms_ntc2sensor_temp
      - entity: sensor.ebusd_pms_ntc3sensor_temp
      - entity: sensor.ebusd_pms_ntc4sensor_temp
      - entity: sensor.ebusd_pms_yieldcurrentday_energy
```

**second image:**
```
  - type: history-graph
    entities:
      - entity: sensor.ebusd_pms_ntc1sensor_temp
      - entity: sensor.ebusd_pms_ntc2sensor_temp
      - entity: sensor.ebusd_pms_ntc3sensor_temp
      - entity: sensor.ebusd_pms_ntc4sensor_temp
  - type: history-graph
    entities:
      - entity: sensor.ebusd_pms_yieldcurrentday_energy
```
