### ISSUE TITLE
Overflow text on Badges if person is home (Android)

### ISSUE THREAD

**Issue by yurividal** [home-assistant/frontend#24474]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My badges overflow the text and look weird. 

![Image](https://github.com/user-attachments/assets/281b47e6-4a86-42c7-a197-ebc902630f9b)

````yaml
    badges:
      - type: entity
        show_name: true
        show_state: false
        show_icon: true
        entity: device_tracker.s23
        color: pink
        name: Luly
        icon: mdi:home-account
        show_entity_picture: false
        visibility:
          - condition: state
            entity: device_tracker.s23
            state: home
      - type: entity
        show_name: true
        show_state: false
        show_icon: true
        entity: device_tracker.sm_s931b
        color: blue
        name: Yuri
        icon: mdi:home-account
        show_entity_picture: false
        visibility:
          - condition: state
            entity: device_tracker.sm_s931b
            state: home
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: sensor.laura_thermostat_humidity
        color: ''
        name: Humidity
        tap_action:
          action: more-info
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: switch.adguard
        color: lime
        name: Aguard
        tap_action:
          action: toggle
        icon: mdi:shield-home
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: binary_sensor.dishwasher_no_rinse_aid
        color: red
        visibility:
          - condition: state
            entity: binary_sensor.dishwasher_no_rinse_aid
            state: 'on'
        name: Rinse Aid!
        icon: mdi:dishwasher-alert
        show_entity_picture: false
        state_content: name
        tap_action:
          action: none
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: binary_sensor.dishwasher_no_salt
        color: red
        visibility:
          - condition: state
            entity: binary_sensor.dishwasher_no_salt
            state: 'on'
        name: Salt!
        icon: mdi:dishwasher-alert
        show_entity_picture: false
        state_content: name
        tap_action:
          action: none
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        color: ''
        entity: sensor.dishwasher_state
        name: Dishwasher
        icon: mdi:dishwasher
        state_content: state
      - type: entity
        show_name: true
        show_state: true
        show_icon: false
        color: ''
        entity: sensor.dishwasher_sub_state
        name: Dishwasher
        icon: mdi:dishwasher
        state_content: state
        visibility:
          - condition: state
            entity: select.dishwasher_state
            state_not: device_state_off
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        color: ''
        entity: sensor.dishwasher_time_hh_mm
        name: Dishwasher Remain Time
        icon: mdi:clock-time-eight-outline
        state_content: state
        visibility:
          - condition: state
            entity: select.dishwasher_state
            state_not: device_state_off
        show_entity_picture: false
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: sensor.washing_machine_state
        color: ''
        name: Washing Machine
        icon: mdi:washing-machine
      - type: entity
        show_name: true
        show_state: true
        show_icon: true
        entity: sensor.washing_machine_sub_state
        color: ''
        name: Washing Machine
        icon: mdi:washing-machine
        visibility:
          - condition: state
            entity: select.washing_machine_state
            state_not: device_state_off
          - condition: state
            entity: select.washing_machine_state
            state_not: unavailable
````

### Describe the behavior you expected

Badges should resize to fit text

### Steps to reproduce the issue

Create a few badges, open the android app

### What version of Home Assistant Core has the issue?

2025.2.5

### In which browser are you experiencing the issue?

Android App

### Which operating system are you using to run this browser?

Android 15

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
