### ISSUE TITLE
Some gauge values missing

### ISSUE THREAD

**Issue by raqua** [home-assistant/frontend#24473]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am having following frontend issue:

![Image](https://github.com/user-attachments/assets/c85c0f2e-8fd2-4747-90a1-277f9ba46d21)

As you can see, one of the gauges in the red-marked group does not show the value. I have this quite often, for couple of months already. I believe it started some time in last autumn. 
But it does not show all the time. I would say this happens about 60% of time. Usually, one or few CTRL+F5 makes the value come back, but not always. Sometimes even 10 repeats won't return the value. 
It happens only in the red-marked group, I have never seen it in the non-marked part. 
When this happens, often all the gauges are missing values. Sometimes, the value comes back without any interaction, presumably when there is change of the value. 

I have reproduced this on desktop Firefox (currently 135.0.1), desktop Brave browser  (1.75.181) and Android companion app (2025.1.2-full).

I could not reproduce this in safe mode, but I can not say 100% that it won't happen as it does not happen 100% of the time and I could not leave my HA instance in safe mode for too long. 

### Describe the behavior you expected

See the gauge value.

### Steps to reproduce the issue

1. Open the dashboard .. ? 
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.2.5

### In which browser are you experiencing the issue?

See above.

### Which operating system are you using to run this browser?

Linux

### State of relevant entities

```txt
State: 13
Attributes:
state_class: measurement
unit_of_measurement: µg/m³
device_class: pm25
friendly_name: air-quality1 PMS5003 PM2.5
```

### Problem-relevant frontend configuration

```yaml
square: false
columns: 3
type: grid
cards:
  - type: gauge
    entity: sensor.temp_onkyo_temperature
    name: Teplota Onkyo
    min: 15
    max: 47
    severity:
      green: 1
      yellow: 35
      red: 40
  - type: gauge
    entity: sensor.tasmota_esp_co2_sensor_mhz19b_carbondioxide
    name: CO2 obývačka
    max: 2500
    severity:
      green: 1
      yellow: 900
      red: 1800
    min: 380
  - type: gauge
    entity: sensor.air_quality1_pms5003_pm2_5
    name: PM2.5 kuchyna
    min: 0
    max: 40
    severity:
      green: 0
      yellow: 12.1
      red: 35.5
  - type: gauge
    entity: sensor.air_quality2_pm25
    name: PM2.5 IKEA
    min: 0
    max: 40
    severity:
      green: 0
      yellow: 12.1
      red: 35.5
  - type: button
    show_name: true
    show_icon: true
    tap_action:
      action: none
    entity: input_boolean.posta
    name: Pošta
    hold_action:
      action: none
  - type: sensor
    graph: line
    detail: 2
    entity: sensor.air_quality2_voc_index
    name: VOC IKEA
    min: 0
    max: 40
    needle: false
    severity:
      green: 0
      yellow: 0
      red: 0
```

### Javascript errors shown in your browser console/inspector

```txt

```
