### ISSUE TITLE
History graph: long term data not visible

### ISSUE THREAD

**Issue by polgarc** [home-assistant/frontend#24495]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Long term data is missing from the history graph card on the dashboard.

### Describe the behavior you expected

Long term data is missing when the page is loading the first time. If I change to a different tab and then back, the long term data is suddenly visible.

### Steps to reproduce the issue

1. create a dashboard with 2 tabs:
   - first tab with a `history-graph`
     - entity is a number (like temperature)
     - `hours to show` is big (1000)
   - second tab, content doesn't matter
2. open first tab - long term data is missing:
   ![Image](https://github.com/user-attachments/assets/a75650c4-cb6f-4406-8b60-27cb2781aa87)
3. switch to the second tab
4. switch to the first tab again, long term data is visible:
   ![Image](https://github.com/user-attachments/assets/c6616c7f-4fb0-49ff-b25a-7980e2633bc6)

### What version of Home Assistant Core has the issue?

2025.2.5

### In which browser are you experiencing the issue?

Firefox 135.0.1, Chrome 133.0.6943.141

### Which operating system are you using to run this browser?

Fedora 41

### State of relevant entities

```txt
state_class: measurement
unit_of_measurement: °C
device_class: temperature
friendly_name: Office temperature
```

### Problem-relevant frontend configuration

```yaml
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: history-graph
            entities:
              - entity: sensor.office_temp_temperature
            hours_to_show: 1000
  - type: sections
    max_columns: 4
    title: another tab
    path: another-tab
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
```

### Javascript errors shown in your browser console/inspector

```txt
No errors.
```

### Additional information

Also happens with other type of entities, like battery %.
