### ISSUE TITLE
Such a "Great" bug with the new 2025.3.0 update...

### ISSUE THREAD

**Issue by pickonedev** [home-assistant/frontend#24527]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Editing text in frontend visual not working anymore.
Trying to do this in YAML, will take you back to visual...

Take a look at the video

https://github.com/user-attachments/assets/8d8e0a1c-b013-43f4-b346-0de7520ee43d

### Describe the behavior you expected

It should be ok, not like is right now

### Steps to reproduce the issue

1. Edit card names or other text field

### What version of Home Assistant Core has the issue?

2025.3.0

### What was the last working version of Home Assistant Core?

2025.2.5

### In which browser are you experiencing the issue?

All

### Which operating system are you using to run this browser?

All

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by pickonedev** [comment]
Back to 2025.2.5, everything works flawless

**Comment by pickonedev** [comment]
This is what I used

```
type: grid
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.lights_group_computer
    name: test
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.lights_group_computer
    name: test
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: switch.lights_group_computer
    name: test
```

**Comment by pickonedev** [comment]
> Reproduced in 2025.3.0. button-card, auto-entities, card-mod installed.

Same exactly result with issues?

**Comment by pickonedev** [comment]
Soo... this could be an issue from one of those cards? I have removed auto-entities.

**Comment by piitaya** [comment]
It's caused by card-mod. I pushed a PR that will fix the issue.

**Comment by ildar170975** [comment]
> It's caused by card-mod.

There is a similar glitch reported here - https://github.com/home-assistant/frontend/issues/24410
And I [managed](https://github.com/home-assistant/frontend/issues/24410#issuecomment-2700798486) to reproduce it on a machine w/o card-mod (((

**Comment by piitaya** [comment]
@ildar170975 You may have some other custom that will affect the editor. But that's not a problem anymore, it will be fixed anyway.

**Comment by ildar170975** [comment]
> You may have some other custom card that will affect the editor

Agree, could be a reason. Thanks for the fix!

**Comment by Nerwyn** [comment]
Slightly unrelated, but is there a CLI command to force update the frontend to [20250306.0](https://github.com/home-assistant/frontend/releases/tag/20250306.0)? I was only able to find commands for updating core and OS, my HA OS is saying there are not updates available, and this update may fix some editor issues with my custom cards when they're used within a stack. If this does fix it it saves me the debugging headache.

**Comment by pickonedev** [comment]
Updated to HA 2025.3.1, I thought that everything is ok, till I got the issue again... but only in some cases.
Let's say that I have 3 horizontal cards, each with other 3 vertical cards, If I edit the yaml card from inside the vertical layout, it is ok, but if I edit the vertical layout, the issue is back...
https://github.com/user-attachments/assets/24d32ff7-23f0-4fbb-9acb-acd20d2685dc

More than that, with the new HA update, if I have the same situation with horizontal and veritcal stack cards, when I change to other horizontal card, the tab will jump to the first one, not like in the past, in the past it will keep the position of the tab even if I go to other card. I think this is because of the "workaround" used for the solution applied to the initial issue... Hope that the video will explain more
https://github.com/user-attachments/assets/d586c4fd-2def-4b9d-847d-36754e6aa16c

**Comment by piitaya** [comment]
@pickonedev Can you provide a minimal config to reproduce it? I was not able to reproduce it?

Also, if you access to the [system info](https://my.home-assistant.io/redirect/info/), what version to you have for frontend?

**Comment by SNoof85** [comment]
@piitaya here is the minimal example where I have the issue at editing yaml on the 2 buttons cards : 
```
type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: light.appoint_salon
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: light.appoint_salon
```
