### ISSUE TITLE
Improper spacing between graphs

### ISSUE THREAD

**Issue by Ragingfire105** [home-assistant/frontend#24540]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When a single history graph card is configured with entities having different units of measure the second graph covers a portion of the legend if the legend is multiple rows.

### Describe the behavior you expected

The full legend to be visible when configured this way.

### Steps to reproduce the issue

1.configure a history graph card as described above.
2.view card on screen narrow enough to cause the legend to be in two rows.
3.
...

### What version of Home Assistant Core has the issue?

2025.3.0

### What was the last working version of Home Assistant Core?

2025.2.5

### In which browser are you experiencing the issue?

Native app, edge mobile

### Which operating system are you using to run this browser?

Android 

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
hours_to_show: 12
    refresh_interval: 1
    title: Upstairs
  - type: history-graph
    entities:
      - entity: climate.downstairs
        name: " "
      - entity: sensor.downstairs_temperature
      - entity: sensor.dining_room_temperature
        name: Intake
    hours_to_show: 12
    refresh_interval: 10
    title: Downstairs
  - type: history-graph
    entities:
      - entity: sensor.openweathermap_temperature
        name: Weather
      - entity: sensor.temperature_attic
        name: Attic
      - entity: sensor.upstairs_temperature
        name: Upstairs
      - entity: sensor.upstairs_high
        name: High
      - entity: sensor.upstairs_low
        name: Low
      - entity: sensor.temperature_master_bath
        name: Master Bath
      - entity: sensor.temperature_kids_bath
        name: Kid's Bath
      - entity: sensor.hallway_temperature
        name: Hallway
      - entity: sensor.motion_sensor_master_air_temperature
        name: Master Bedroom
      - entity: sensor.anna_s_room_temperature
        name: Anna
      - entity: sensor.guest_room_temperature
        name: Guest
      - entity: sensor.temperature_kate
        name: Kate
      - entity: sensor.ag_one_temperature
        name: AG One
    hours_to_show: 12
    refresh_interval: 1
    title: Upstairs
  - type: history-graph
    entities:
      - entity: sensor.openweathermap_temperature
        name: Weather
      - entity: sensor.temperature_garage
        name: Garage
      - entity: sensor.downstairs_temperature
        name: Downstairs
      - entity: sensor.downstairs_high
        name: High
      - entity: sensor.downstairs_low
        name: Low
      - entity: sensor.dining_room_temperature
        name: Dining
      - entity: sensor.temperature_foyer
        name: Foyer
      - entity: sensor.pantry_temperature
        name: Pantry
      - entity: sensor.living_room_temperature
        name: Living
    hours_to_show: 12
    refresh_interval: 1
    title: Downstairs
  - type: history-graph
    entities:
      - entity: sensor.openweathermap_humidity
        name: Weather
      - entity: sensor.humidity_attic
        name: Attic
      - entity: sensor.upstairs_humidity
        name: Upstairs
      - entity: sensor.downstairs_humidity
        name: Downstairs
      - entity: sensor.humidity_master_bath
        name: Master Bath
      - entity: sensor.humidity_kids_bath
        name: Kid's Bath
      - entity: sensor.hallway_humidity
        name: Hallway
      - entity: sensor.dining_room_humidity
        name: Dining
      - entity: sensor.motion_sensor_master_humidity
        name: Master Bedroom
      - entity: sensor.anna_s_room_humidity
        name: Anna
      - entity: sensor.guest_room_humidity
        name: Guest
      - entity: sensor.humidity_kate
        name: Kate
      - entity: sensor.humidity_foyer
        name: Foyer
      - entity: sensor.pantry_humidity
        name: Pantry
      - entity: sensor.living_room_humidity
        name: Living
      - entity: sensor.humidity_garage
        name: Garage
      - entity: sensor.ag_one_humidity
        name: AG One
      - entity: sensor.ag_one_co2
    refresh_interval: 1
    hours_to_show: 12
    title: Humidity
  - type: history-graph
    entities:
      - entity: sensor.ag_one_co2
        name: CO2
    refresh_interval: 1
    hours_to_show: 12
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

![Image](https://github.com/user-attachments/assets/fb169799-af50-4945-9d0b-027f470ed9fc)
