### ISSUE TITLE
Convert to Sections drag-and-drop does not work on Firefox

### ISSUE THREAD

**Issue by peter1rhodes** [home-assistant/frontend#24617]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This is certainly browser-related. It works in Edge. I've tried it on a couple of different machines running Firefox, with the same result.

When using the Convert to Sections tool to update masonry dashboards, the convenient drag-and-drop tool for moving parts into the new Sections layout does not work on Firefox. Clicking and dragging on the sections at the bottom simply produces no result — the section does not appear to be dragged, and does not end up in the dropped location.

### Describe the behavior you expected

The drag and drop should work on Firefox as well as it does on Edge. 

### Steps to reproduce the issue

1. Use FIrefox (I have v136.0.1)
2. Go to a Masonry dashboard view
3. Click "Edit" on the view and change the layout from Masonry to Sections (default) Then click Convert and Create
4. Try to drag and drop from the "Imported cards" at the bottom into the new sections above
5. Fail
...

### What version of Home Assistant Core has the issue?

2025.3.2

### In which browser are you experiencing the issue?

Mozilla Firefox v136.0.1

### Which operating system are you using to run this browser?

Windows 10 build 19044

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
title: Living Room
icon: mdi:sofa
subview: true
badges:
  - type: entity
    show_name: false
    show_state: true
    show_icon: true
    entity: sensor.living_room_th_sensor_temperature
    color: orange
  - type: entity
    entity: sensor.living_room_th_sensor_humidity
  - type: custom:mushroom-template-badge
    tap_action:
      action: more-info
    hold_action:
      action: none
    double_tap_action:
      action: none
    entity: binary_sensor.living_room_presence_sensor_occupancy
    icon: >-
      {% if states('binary_sensor.living_room_presence_sensor_occupancy') ==
      'on' %}
        mdi:motion-sensor
      {% elif states('binary_sensor.living_room_presence_sensor_occupancy') ==
      'off' %}
        mdi:motion-sensor-off
      {% endif %}
    content: >-
      {% if states('binary_sensor.living_room_presence_sensor_occupancy') ==
      'on' %}
        Detected
      {% elif states('binary_sensor.living_room_presence_sensor_occupancy') ==
      'off' %}
        Clear
      {% endif %}
    color: >-
      {% if states('binary_sensor.living_room_presence_sensor_occupancy') ==
      'on'

      %}
        blue
      {% elif states('binary_sensor.living_room_presence_sensor_occupancy') ==
      'off' %}
        grey
      {% endif %}
    label: ""
  - type: custom:mushroom-template-badge
    entity: sensor.hall_th_sensor_battery
    icon: >-
      {% set battery_level =
      states('sensor.hall_th_sensor_battery')|default(0)|int %}

      {% set battery_round = (battery_level / 10) |int * 10 %}

      {% if battery_round >= 100 %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-alert
      {% endif %}
    tap_action:
      action: more-info
    hold_action:
      action: none
    double_tap_action:
      action: none
    content: "{{ states('sensor.hall_th_sensor_battery') }} %"
    color: >-
      {% set battery_level =
      states('sensor.hall_th_sensor_battery')|default(0)|int %}

      {% set battery_round = (battery_level / 10) |int * 10 %}


      {% if battery_round >= 40 %}
        green
      {% elif battery_round > 20 %}
        orange
      {% else %}
        red
      {% endif %}
    label: TH Sensor
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-title-card
        title: Living Room
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-light-card
        name: Ceiling
        icon: mdi:ceiling-light
        use_light_color: true
        show_brightness_control: true
        show_color_temp_control: false
        show_color_control: false
        collapsible_controls: false
        tap_action:
          action: toggle
        entity: light.living_room_ceiling_light
      - type: custom:mushroom-light-card
        tap_action:
          action: toggle
        use_light_color: true
        show_brightness_control: true
        collapsible_controls: false
        name: Corner lamp
        icon: mdi:lamp
        entity: light.living_room_corner_lamp
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-light-card
        name: Floor
        icon: mdi:floor-lamp
        use_light_color: true
        show_brightness_control: true
        show_color_temp_control: false
        show_color_control: false
        collapsible_controls: false
        tap_action:
          action: toggle
        entity: light.living_room_standing_lamp
      - type: custom:mushroom-light-card
        tap_action:
          action: toggle
        use_light_color: true
        show_brightness_control: true
        collapsible_controls: false
        entity: light.living_room_door_end_standing_lamp
        name: Dual
        icon: mdi:floor-lamp-dual
      - type: custom:mushroom-light-card
        tap_action:
          action: toggle
        use_light_color: true
        show_brightness_control: true
        collapsible_controls: false
        entity: light.living_room_door_end_standing_lamp_flexi
        icon: mdi:floor-lamp-dual
        name: Flexi
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-light-card
        tap_action:
          action: toggle
        use_light_color: true
        show_brightness_control: false
        collapsible_controls: false
        name: Mantlepiece
        icon: mdi:fireplace
        entity: light.livingroom_mantelpiece_lamp
  - type: vertical-stack
    cards:
      - type: custom:mushroom-media-player-card
        entity: media_player.xbox
        name: Xbox
        use_media_info: true
        media_controls:
          - play_pause_stop
          - on_off
        collapsible_controls: true
        icon: mdi:controller
        layout: horizontal
      - type: custom:mushroom-media-player-card
        entity: media_player.living_room_tv
        name: TV
        icon: mdi:television
        media_controls:
          - on_off
          - play_pause_stop
        fill_container: false
        show_volume_level: false
        use_media_info: false
        layout: horizontal
        collapsible_controls: false
        tap_action:
          action: call-service
          service: media_player.media_play_pause
          target:
            entity_id: media_player.living_room_tv
      - type: custom:mushroom-light-card
        name: TV Backlights
        icon: mdi:television-ambient-light
        use_light_color: true
        show_brightness_control: true
        show_color_temp_control: false
        show_color_control: true
        collapsible_controls: true
        tap_action:
          action: toggle
        entity: light.living_room_tv_backlights
        layout: horizontal
type: sections
sections:
  - type: grid
    cards:
      - type: heading
        heading: New section
```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ildar170975** [comment]
Suggest to reproduce with stock cards & then post a minimal working example.
Currently the code contains custom cards and thus may not get a proper attention.

**Comment by peter1rhodes** [comment]
> Suggest to reproduce with stock cards & then post a minimal working example. Currently the code contains custom cards and thus may not get a proper attention.

Thank you for the suggestion. I created a new dashboard view with a couple of stock cards, the problem is exactly the same. Here is the YAML for that view beforehand (as masonry):

```
type: masonry
path: test-dashboard
title: test-dashboard
cards:
  - type: entities
    entities:
      - sensor.average_house_humidity
      - sensor.average_house_temperature
  - type: map
    entities:
      - entity: device_tracker.pixel_6
    theme_mode: auto
subview: true
```

and when the problem shows (after using "Convert" to Sections):

```
type: sections
title: test-dashboard
cards:
  - type: entities
    entities:
      - sensor.average_house_humidity
      - sensor.average_house_temperature
  - type: map
    entities:
      - entity: device_tracker.pixel_6
    theme_mode: auto
subview: true
sections:
  - type: grid
    cards:
      - type: heading
        heading: New section
```
