### ISSUE TITLE
history-graph flickering and disappearing lines if values stayed the same for longer durations

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#24648]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In Chrome and Firefox graphs which show values which haven't changed for a longer duration will flicker on and off in the horizontal portions of the lines.

Chrome:

https://github.com/user-attachments/assets/d5e04c54-578a-42bc-8c19-6c6b1dd7151d

Firefox:

https://github.com/user-attachments/assets/b197b49c-b5bb-45f0-9172-f9df69d70a2f

### Describe the behavior you expected

No flickering

### Steps to reproduce the issue

1. Create a history graph
2. Have values which do not change over a longer time span
3. See flickering on each update of the graph, with disappearing lines

### What version of Home Assistant Core has the issue?

2025.3.3

### What was the last working version of Home Assistant Core?

2024.x

### In which browser are you experiencing the issue?

Chrome 130.0.6723.174 / Firefox 129.0.2

### Which operating system are you using to run this browser?

Arch Linux

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sun.sun
  - entity: sensor.light_s_temperature_left_room
  - entity: sensor.adaptive_lighting_light_temperature_selection
  - entity: input_number.light_temperature_delta_left_room
  - entity: sensor.presence_left_room_presence_left_room_outdoor_color_temperature
  - entity: sensor.presence_left_room_presence_left_room_left_room_color_temperature
hours_to_show: 12
```

### Javascript errors shown in your browser console/inspector

```txt

```
