### ISSUE TITLE
horizontal-stack card overlaps when using an title in the sections view

### ISSUE THREAD

**Issue by guido1981** [home-assistant/frontend#24699]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

horizontal-stack card overlaps when using an title in the sections view

with title:

![Image](https://github.com/user-attachments/assets/5c2405d0-57b4-4df3-b76f-0bdd1d06284d)

### Describe the behavior you expected

No overlap, just like does without an title

![Image](https://github.com/user-attachments/assets/6fa14c0d-39a2-41ee-aa88-bc1832b02fb6)

### Steps to reproduce the issue

1. Create a new sections page/dashboard
2. Add horizontal stack card with multiple entities and an title
3. Add another card like Thermostat below

### What version of Home Assistant Core has the issue?

2025.3.3

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
views:
  - title: Verwarming
    cards: []
    type: sections
    sections:
      - type: grid
        cards:
          - type: thermostat
            entity: climate.woonkamer
            features:
              - style: icons
                type: climate-hvac-modes
                hvac_modes:
                  - 'off'
                  - auto
                  - heat
            show_current_as_primary: true
      - type: grid
        cards:
          - type: thermostat
            entity: climate.werkkamer
            features:
              - type: climate-hvac-modes
                hvac_modes:
                  - 'off'
                  - auto
                  - heat
            show_current_as_primary: true
      - type: grid
        cards:
          - type: thermostat
            entity: climate.badkamer
            features:
              - type: climate-hvac-modes
                hvac_modes:
                  - 'off'
                  - auto
                  - heat
            show_current_as_primary: true
      - type: grid
        cards:
          - type: thermostat
            entity: climate.karenza
            features:
              - type: climate-hvac-modes
                hvac_modes:
                  - 'off'
                  - auto
                  - heat
            show_current_as_primary: true
      - type: grid
        cards:
          - type: heading
            heading_style: title
            heading: Woonkamer
            badges: []
          - type: heading
            icon: mdi:home-thermometer
            heading_style: subtitle
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.ru0298454528_battery_state
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.ru0298454528_connection_state
            heading: Slimme thermostaat
          - type: heading
            icon: mdi:radiobox-indeterminate-variant
            heading_style: subtitle
            badges:
              - type: entity
                entity: binary_sensor.va1164057088_battery_state
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.va1164057088_connection_state
            heading: Slimme radiatorknop
          - type: heading
            heading_style: title
            heading: Werkkamer
            badges: []
          - type: heading
            icon: mdi:radiobox-indeterminate-variant
            heading_style: subtitle
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.va0727783936_battery_state
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.va0727783936_connection_state
            heading: Slimme radiatorknop
          - type: heading
            icon: mdi:router-network-wireless
            heading_style: subtitle
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.ib1436355840_connection_state
            heading: Internetbridge
          - type: heading
            heading_style: title
            heading: Badkamer
            badges: []
          - type: heading
            icon: mdi:radiobox-indeterminate-variant
            heading_style: subtitle
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.va3831568896_battery_state
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.va3831568896_connection_state
            heading: Slimme radiatorknop
          - type: heading
            heading_style: title
            heading: Karenza
            badges: []
          - type: heading
            icon: mdi:radiobox-indeterminate-variant
            heading_style: subtitle
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.va1080171008_battery_state
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.va1080171008_connection_state
            heading: Slimme radiatorknop
    max_columns: 2
  - type: masonry
    path: woonkamer
    title: Woon
    cards:
      - type: horizontal-stack
        cards:
          - graph: line
            type: sensor
            detail: 1
            entity: sensor.woonkamer_temperature
            name: Temperatuur
            hours_to_show: 24
          - graph: line
            type: sensor
            detail: 1
            entity: sensor.woonkamer_humidity
            name: Luchtvochtigheid
            hours_to_show: 24
        grid_options:
          columns: 12
          rows: 2
        title: Woonkamer
      - type: thermostat
        entity: climate.woonkamer
        features:
          - style: icons
            type: climate-hvac-modes
            hvac_modes:
              - 'off'
              - auto
              - heat
        show_current_as_primary: false
        name: ' '
      - type: heading
        icon: mdi:home-thermometer
        heading_style: subtitle
        badges:
          - type: entity
            show_state: true
            show_icon: true
            entity: binary_sensor.ru0298454528_battery_state
          - type: entity
            show_state: true
            show_icon: true
            entity: binary_sensor.ru0298454528_connection_state
        heading: Slimme thermostaat
      - type: heading
        icon: mdi:radiobox-indeterminate-variant
        heading_style: subtitle
        badges:
          - type: entity
            entity: binary_sensor.va1164057088_battery_state
          - type: entity
            show_state: true
            show_icon: true
            entity: binary_sensor.va1164057088_connection_state
        heading: Slimme radiatorknop
    icon: mdi:sofa
    subview: false
  - type: sections
    title: Woon
    cards: []
    icon: mdi:sofa
    subview: false
    sections:
      - type: grid
        cards:
          - type: horizontal-stack
            cards:
              - graph: line
                type: sensor
                detail: 1
                entity: sensor.woonkamer_temperature
                name: Temperatuur
                hours_to_show: 24
              - graph: line
                type: sensor
                detail: 1
                entity: sensor.woonkamer_humidity
                name: Luchtvochtigheid
                hours_to_show: 24
            grid_options:
              rows: 2
              columns: full
            title: Woonkamer
          - type: thermostat
            entity: climate.woonkamer
            features:
              - style: icons
                type: climate-hvac-modes
                hvac_modes:
                  - 'off'
                  - auto
                  - heat
            show_current_as_primary: false
            name: ' '
          - type: heading
            icon: mdi:home-thermometer
            heading_style: subtitle
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.ru0298454528_battery_state
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.ru0298454528_connection_state
            heading: Slimme thermostaat
          - type: heading
            icon: mdi:radiobox-indeterminate-variant
            heading_style: subtitle
            badges:
              - type: entity
                entity: binary_sensor.va1164057088_battery_state
              - type: entity
                show_state: true
                show_icon: true
                entity: binary_sensor.va1164057088_connection_state
            heading: Slimme radiatorknop
```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ildar170975** [comment]
duplicate of https://github.com/home-assistant/frontend/issues/18972
same reason

**Comment by ildar170975** [comment]
2025.6.2:
```
sections:
  - type: grid
    cards:
      - type: horizontal-stack
        title: title
        cards:
          - type: markdown
            content: xxx
          - type: markdown
            content: xxx
      - type: markdown
        content: xxx
```
![Image](https://github.com/user-attachments/assets/d1909cfa-3e02-435e-8c24-0978b3a64a98)
