### ISSUE TITLE
Tracer UI reports incorrect/misleading Iteration number when you have more than 20 iterations

### ISSUE THREAD

**Issue by ncd7** [home-assistant/frontend#24847]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I understand that the Tracer UI deliberately only preserves the last 20 iterations if a "repeat" loop to keep logs manageable.
However, the current behavior starts off with "Iteration 1" when in reality it should be (max iteration - 20). 
Eg below for a repeat loop with 21 iterations, only the last 20 are preserved but instead of the Tracer UI stating "Iteration 2" it says "Iteration 1" which is very confusing. 

![Image](https://github.com/user-attachments/assets/bca85825-3f0f-4815-ad4f-ea8a91850b7e)

### Describe the behavior you expected

I expect the "Iteration" in the Tracer UI to correctly match the `repeat.index` value since the actual iteration displayed IS the index-th one.

### Steps to reproduce the issue

1.Create a script as below

```
alias: test
sequence:
  - repeat:
      count: 21
      sequence:
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: "{{ repeat.index|int }}"
description: ""

```
2. Run it
3. Look at "Traces"
4. Click on the "delay" node and scroll down to the "Changed Variables" tab.
5. Observe that it starts with "Iteration 1" but it is actually displaying the values of the 2nd iteration, e.g "repeat: first" is false and "repeat: index" is 2. 

### What version of Home Assistant Core has the issue?

2025.3.3

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
