### ISSUE TITLE
Weather Forecast card editor missing ui for customizing actions (2025.4 beta)

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#24858]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The cards supports all 3 (tap, double tap and hold) actions but it's editor does not.

### Describe the behavior you expected

Card editor UI supports defining actions.

### Steps to reproduce the issue

1. Create Weather Forecast card
2. Attempt to add action to it

### What version of Home Assistant Core has the issue?

2025.4.0b9

### What was the last working version of Home Assistant Core?

never worked

### In which browser are you experiencing the issue?

any

### Which operating system are you using to run this browser?

any

### State of relevant entities

```txt
irrelevant
```

### Problem-relevant frontend configuration

```yaml
type: weather-forecast
entity: weather.home
tap_action:
  action: navigate
  navigation_path: /actions-test/tap-action
double_tap_action:
  action: navigate
  navigation_path: /actions-test/double-tap-action
hold_action:
  action: navigate
  navigation_path: /actions-test/hold-action
```

### Javascript errors shown in your browser console/inspector

```txt
-
```

### Additional information

Someones been busy bee lately (#24824), but you missed one.
