### ISSUE TITLE
Vertical axis of graphs doesn't start at zero

### ISSUE THREAD

**Issue by erikgeurts** [home-assistant/frontend#24851]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After the recent changes to graph cards, I've noticed that in several cases the vertical axis doesn't start at zero.

Here is an example:

![Image](https://github.com/user-attachments/assets/f722bca9-99a8-439d-b824-9c54c6308955)

Notice the vertical axis starts at 5, instead of 0.

### Describe the behavior you expected

I expect the vertical axis to always start at zero in relevant cases.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2025.3.4

### What was the last working version of Home Assistant Core?

core-2025.1.x?

### In which browser are you experiencing the issue?

All browsers, also in Android companion app

### Which operating system are you using to run this browser?

Windows 10, Android 15

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
- chart_type: bar
    period: month
    days_to_show: 450
    type: statistics-graph
    entities:
      - sensor.grid_water_total_consumed
    stat_types:
      - change
    title: Watergebruik afgelopen 15 maanden
    hide_legend: true
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

### Additional information

I'm reporting this in Frontend, but if this should have been in Core, just let me know and I'll post it there and cross-reference.
