### ISSUE TITLE
Options with labels in select selector are not being translated as expected

### ISSUE THREAD

**Issue by tr4nt0r** [home-assistant/frontend#24856]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am defining a select selector for an action in `services.yaml` and using labels for the options to give them a more meaningful description. The values are numbers 1-5 and can't be used as translation keys. When defining translations for the option's labels (max,high,default,low,min) in strings.json the translations don't work. when using the values as translation key in strings.json the translation works and the labels are ignored.

### Describe the behavior you expected

I would have expected that when the value can't be used as translation key (because it is a number, starts  with a number, is uppercase or has other characters that are not allowed as translation key), that defining a label as alternative string would then serve as translation key. 

### Steps to reproduce the issue

```yaml
priority:
  required: false
  selector:
    select:
      options:
        - value: "5"
          label: "max"
        - value: "4"
          label: "high"
        - value: "3"
          label: "default"
        - value: "2"
          label: "low"
        - value: "1"
          label: "min"
      mode: dropdown
      translation_key: "priority"
      sort: false
```

```json
"selector": {
    "priority": {
      "options": {
        "1": "Min. priority",
        "low": "Low priority",
        "default": "Default priority",
        "high": "High priority",
        "max": "Max. priority"
      }
    }
  }
```

### What version of Home Assistant Core has the issue?

2025.5.0.dev0

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

Not sure if this is a bug, something that just hasn't been considered or if it is intended behavior and working as expected
