### ISSUE TITLE
statistics-graph card  incorrectly adopts max-values from the previous day

### ISSUE THREAD

**Issue by mzaufl** [home-assistant/frontend#25056]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The consumption counter helper is used to create reset entities on a daily basis. These have been checked and are correct. Using the statistics-graph card to show daily consumtion bars, the statistics-graph card  adopts incorrectly max-values from the previous day.

You can see the issue by comparing the values "Erzeugung" of April 9 and 10 and April 12 and 13. And also for the values "Verbrauch" of April 13 and 14. 

![Image](https://github.com/user-attachments/assets/7704f941-1966-4e41-81f1-72160242cfe8)

In addition, the configured value "Verbrauch" is not displayed at all, although it also contains values.

### Describe the behavior you expected

The graph should show the maximum values of a day as apexcharts-card does using function "last". The daily max value is the same as the daily "last" value.

![Image](https://github.com/user-attachments/assets/7db13992-72ee-4197-94fa-bdd97dc66cfe)

### Steps to reproduce the issue

1. Create an integral sensor
2. Based on this integral sensor, create a consumption counter helper that is reset daily
3. Create a statistics-graph card like this

`chart_type: bar
period: day
type: statistics-graph
entities:
  - entity: sensor.produktion_alle_heute
    name: Erzeugung
  - entity: sensor.eigenverbrauch
    name: Eigenverbrauch
  - entity: sensor.pv_netzbezug_heute
    name: Netzbezug
  - entity: sensor.verbrauch_alle_heute
    name: Verbrauch
days_to_show: 6
stat_types:
  - max
title: " Tag/Maximum"`

![Image](https://github.com/user-attachments/assets/3ab5e9ee-3852-4bad-a149-4efca5f3cc51)

### What version of Home Assistant Core has the issue?

2025.4.1

### In which browser are you experiencing the issue?

Google Chrome Mobile, Microsoft Edge Desktop

### Which operating system are you using to run this browser?

Android 14, Windows 10 and Windows 11

### State of relevant entities

```yaml
state_class: measurement
unit_of_measurement: kWh
icon: mdi:calculator
friendly_name: Produktion alle heute

state_class: measurement
unit_of_measurement: kWh
icon: mdi:calculator
friendly_name: Eigenverbrauch heute

state_class: total_increasing
status: collecting
last_period: "8.132"
last_valid_state: "1239.832"
last_reset: "2025-04-13T22:00:00.011385+00:00"
next_reset: "2025-04-15T00:00:00+02:00"
unit_of_measurement: kWh
device_class: energy
icon: mdi:transmission-tower-export
friendly_name: Netzbezug heute

state_class: measurement
unit_of_measurement: kWh
icon: mdi:calculator
friendly_name: Verbrauch alle heute'
```

### Problem-relevant frontend configuration

```yaml
chart_type: bar
period: day
type: statistics-graph
entities:
  - entity: sensor.produktion_alle_heute
    name: Erzeugung
  - entity: sensor.eigenverbrauch
    name: Eigenverbrauch
  - entity: sensor.pv_netzbezug_heute
    name: Netzbezug
  - entity: sensor.verbrauch_alle_heute
    name: Verbrauch
days_to_show: 6
stat_types:
  - max
title: " Tag/Maximum"
```

### Javascript errors shown in your browser console/inspector

```txt

```
