### ISSUE TITLE
Conditional card showing "Entity not found"

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [home-assistant/frontend#25062]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Until recently the Conditional card would show only available entities when configured with "state_not: unavailable". Recently this card started showing my cards when they are "not found" i.e. don't exist. The ability to not show cards when the entity doesn't exist allows me to standardise my cards and use the configuration in different applications with the card only showing the relevant entities. Could we please have the previous functionality back?

### Describe the behavior you expected

Entities not configured to have the same effect as unavailable entities.

### Steps to reproduce the issue

1. Setup conditional card with state_not: unavailable for a non-existent entity.
2. Observe

### What version of Home Assistant Core has the issue?

2025.4.2

### What was the last working version of Home Assistant Core?

2025.3

### In which browser are you experiencing the issue?

Google Chrome Version 135.0.7049.85 (Official Build) (arm64) & Safari Version 18.3.1 (20620.2.4.11.6)

### Which operating system are you using to run this browser?

macOS 15.3.2 (24D81)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ildar170975** [comment]
Post a yaml code of your card.

**Comment by bigfeetneedbigboots** [comment]
```
- type: grid
  square: false
  columns: 3
  cards:
    - type: conditional
      conditions:
        - condition: state
          entity: switch.la_therm_bed1_actuator_1
          state_not: unavailable
      card:
        type: tile
        card_mod:
          style:
            .: |
              ha-card { border: none; } 
        entity: switch.la_therm_bed1_actuator_1
        name: Actuator 1
    - type: conditional
      conditions:
        - condition: state
          entity: switch.la_therm_bed1_actuator_2
          state_not: unavailable
      card:
        type: tile
        card_mod:
          style:
            .: |
              ha-card { border: none; } 
        entity: switch.la_therm_bed1_actuator_2
        name: Actuator 2

```

Actuator 1 shows as it should (because it exists). Actuator 2 shows an error (question mark icon with red exclamation with text Entity not found) because it does not exist in this case.

I tried as you suggest and "state_not: unknown" seems to address my use case. Thanks.
