### ISSUE TITLE
Automation Editor: device_automation.ts:173 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by weirded** [home-assistant/frontend#25196]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This exception happens in a tight loop when I edit a specific integration. It makes the UI unusable (slow), and when I attempt to save the automation, I get the same exception. 

![Image](https://github.com/user-attachments/assets/ae72ce0e-6497-4f66-a18d-ac05b28286b1)

### Describe the behavior you expected

I expect no exception and ability to edit/save this automation.

### Steps to reproduce the issue

1. Open the automation in editor
2. Try to toggle any of the sections
3. Observe UI is slow and exception happens rapidly

### What version of Home Assistant Core has the issue?

2025.4.4

### In which browser are you experiencing the issue?

Google Chome  135.0.7049.115, Brave Version 1.77.101 Chromium: 135.0.7049.115 (Official Build) (arm64), Home Assistant Companion App  

### Which operating system are you using to run this browser?

macOS Sequoia 15.4.1 (24E263)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
alias: Schedule - Hall Bath Washlet
description: ""
triggers:
  - at: "00:08:00"
    id: morning
    trigger: time
  - at: "20:00:00"
    id: evening
    trigger: time
  - entity_id:
      - input_boolean.extended_absence
    to: "on"
    id: gone
    trigger: state
  - entity_id:
      - input_boolean.extended_absence
    to: "off"
    id: back
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: morning
          - condition: state
            entity_id: input_boolean.extended_absence
            state: "off"
        sequence:
          - type: turn_on
            device_id: 4ef2963c80648c834a44222f39879ec8
            entity_id: switch.halljj_bath_washlet
            domain: switch
      - conditions:
          - condition: trigger
            id: back
        sequence:
          - type: turn_on
            device_id: 4ef2963c80648c834a44222f39879ec8
            entity_id: switch.halljj_bath_washlet
            domain: switch
      - conditions:
          - condition: trigger
            id: gone
        sequence:
          - type: turn_off
            device_id: 4ef2963c80648c834a44222f39879ec8
            entity_id: switch.halljj_bath_washlet
            domain: switch
      - conditions:
          - condition: trigger
            id: evening
        sequence:
          - type: turn_off
            device_id: 4ef2963c80648c834a44222f39879ec8
            entity_id: switch.halljj_bath_washlet
            domain: switch
mode: single
```

### Javascript errors shown in your browser console/inspector

```txt
device_automation.ts:173 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at p (device_automation.ts:173:58)
    at h (device_automation.ts:119:10)
    at ha-device-automation-picker.ts:86:7
    at Array.findIndex (<anonymous>)
    at F.value (ha-device-automation-picker.ts:85:35)
    at F.value (ha-device-automation-picker.ts:100:24)
    at F.update (lit-element.ts:161:15)
    at F.performUpdate (reactive-element.ts:1333:14)
    at F.scheduleUpdate (reactive-element.ts:1262:4)
    at F._$Ej (reactive-element.ts:1237:9)
```
