### ISSUE TITLE
Custom_Panel stays blank regardless of content

### ISSUE THREAD

**Issue by christianslw** [home-assistant/frontend#25214]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

adding a custom_panel to configuration.yaml results in a blank page when navigating to the panel

### Describe the behavior you expected

in this case, the panel should at least show a blue BG and lightblue border.

### Steps to reproduce the issue

1. add custom_panel: with path to step 2 to configuration.yaml
2. add {your_name.js} to www folder
3. del cache, restart HA and navigate to the Custom Panel via Sidebar.
...
``

### What version of Home Assistant Core has the issue?

2025.4.4

### In which browser are you experiencing the issue?

Brave 1.77.101; Microsoft Edge 135.0.3179.98

### Which operating system are you using to run this browser?

Windows 11 Pro 64bit, Windows 11 Pro ARM64

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
configuration.yaml:


`http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.2.0/24

default_config:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

panel_custom:
  - name: automation-tree
    # url_path needs to be unique for each panel_custom config
    url_path: automation-tree
    sidebar_title: Automations
    sidebar_icon: mdi:robot
    module_url: /local/automation-tree.js
    config:
      divider: "//"
      defaultOpenTreeDepth: 999
      automationHeight: 30
      summaryHeight: 52

  - name: test-panel-entry
    sidebar_title: Lutschi # oof
    sidebar_icon: mdi:check
    url_path: testpanel
    module_url: /local/testing.js

python_script:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - name: "Bresser Temperatur"
      state_topic: "rtl_433/raspberry/events"
      value_template: >
        {% if value_json.model == "Bresser-6in1" and value_json.id == 556796163 %}
          {{ value_json.temperature_C }}
        {% else %}
          {{ states('sensor.bresser_temperatur') }}
        {% endif %}
      unit_of_measurement: "°C"
      unique_id: bresser_temp
      expire_after: 300 # Sensor "läuft ab", wenn keine neue Nachricht in 130 Sek.
      force_update: false # verhindert ständiges "update obwohl Wert gleich"

    - name: "Bresser Luftfeuchtigkeit"
      state_topic: "rtl_433/raspberry/events"
      value_template: >
        {% if value_json.model == "Bresser-6in1" and value_json.id == 556796163 %}
          {{ value_json.humidity }}
        {% else %}
          {{ states('sensor.bresser_luftfeuchtigkeit') }}
        {% endif %}
      unit_of_measurement: "%"
      unique_id: bresser_humidity
      expire_after: 400 # Sensor "läuft ab", wenn keine neue Nachricht in 130 Sek.
      force_update: false # verhindert ständiges "update obwohl Wert gleich"

    - name: "Bresser Windrichtung"
      state_topic: "rtl_433/raspberry/events"
      value_template: >
        {% if value_json.model == "Bresser-6in1" and value_json.id == 556796163 %}
          {{ value_json.wind_dir_deg }}
        {% else %}
          {{ states('sensor.bresser_windrichtung') }}
        {% endif %}
      unit_of_measurement: "°"
      unique_id: bresser_wind_dir
      expire_after: 60 # Sensor "läuft ab", wenn keine neue Nachricht in 130 Sek.
      force_update: false # verhindert ständiges "update obwohl Wert gleich"

    - name: "Bresser Windgeschwindigkeit"
      state_topic: "rtl_433/raspberry/events"
      value_template: >
        {% if value_json.model == "Bresser-6in1" and value_json.id == 556796163 %}
          {{ value_json.wind_avg_m_s }}
        {% else %}
          {{ states('sensor.bresser_windgeschwindigkeit') }}
        {% endif %}
      unit_of_measurement: "m/s"
      unique_id: bresser_wind_avg
      expire_after: 60 # Sensor "läuft ab", wenn keine neue Nachricht in 130 Sek.
      force_update: false # verhindert ständiges "update obwohl Wert gleich"

    - name: "Bresser Windböe"
      state_topic: "rtl_433/raspberry/events"
      value_template: >
        {% if value_json.model == "Bresser-6in1" and value_json.id == 556796163 %}
          {{ value_json.wind_max_m_s }}
        {% else %}
          {{ states('sensor.bresser_windboee') }}
        {% endif %}
      unit_of_measurement: "m/s"
      unique_id: bresser_wind_max
      expire_after: 60 # Sensor "läuft ab", wenn keine neue Nachricht in 130 Sek.
      force_update: false # verhindert ständiges "update obwohl Wert gleich"

    - name: "Bresser UV-Index"
      state_topic: "rtl_433/raspberry/events"
      value_template: >
        {% if value_json.model == "Bresser-6in1" and value_json.id == 556796163 %}
          {{ value_json.uv }}
        {% else %}
          {{ states('sensor.bresser_uv') }}
        {% endif %}
      unit_of_measurement: ""
      unique_id: bresser_uv
      expire_after: 400 # Sensor "läuft ab", wenn keine neue Nachricht in 130 Sek.
      force_update: false # verhindert ständiges "update obwohl Wert gleich"

    - name: "Bresser Batteriespannung OK"
      state_topic: "rtl_433/raspberry/events"
      value_template: >
        {% if value_json.model == "Bresser-6in1" and value_json.id == 556796163 %}
          {{ value_json.battery_ok }}
        {% else %}
          {{ states('sensor.bresser_battery') }}
        {% endif %}
      unique_id: bresser_battery_ok
      expire_after: 1000 # Sensor "läuft ab", wenn keine neue Nachricht in 130 Sek.
      force_update: false # verhindert ständiges "update obwohl Wert gleich"`

testing.js:

// config/www/testing.js
console.log('Minimal Module Loaded');

// HTML
const template = document.createElement('template');
template.innerHTML = `
  <style>
    :host {
      display: block;
      padding: 20px;
      border: 3px solid blue;
      background-color: lightblue;
    }
  </style>
  <h2>bitte funktionieerrrereeeeee Test Panel</h2>
  <p>Dieser Inhalt kommt aus dem Template.</p>
`;

class MinimalPanel extends HTMLElement {
  constructor() {
    super(); 
    console.log('Minimal Constructor aufgerufen');
    // Shadow DOM
    this.attachShadow({ mode: 'open' }); // Shadow DOM activation
    this.shadowRoot.appendChild(template.content.cloneNode(true));
    console.log('Minimal Shadow DOM angehängt');
  }
}

console.log('Definiere minimal-panel...');
try {
  customElements.define('minimal-panel', MinimalPanel);
  console.log('Minimal Panel definiert.');
} catch (e) {
  console.error('Fehler bei Definition minimal-panel:', e);
}
```

### Javascript errors shown in your browser console/inspector

```txt

```
