### ISSUE TITLE
history-graph: double graphs for a disabled entity

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#25225]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Consider this card:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - sensor.system_monitor_disk_free
  - type: history-graph
    entities:
      - entity: sensor.system_monitor_disk_free
```
The `sensor.system_monitor_disk_free` was disabled.
Immediately the 2md graph was shown (Chrome 135.0.7049.115):

![Image](https://github.com/user-attachments/assets/3906df5c-19d1-4d33-8bfe-daf56d29cac9)

Browser cache was reloaded.

Similar was observed in FF 137.0.2 in private mode:

![Image](https://github.com/user-attachments/assets/05c64152-3e6a-45e4-aec6-096b86c9d1a9)

No errors in console.

### Describe the behavior you expected

One graph is shown.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

HA 2025.4.1

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
