### ISSUE TITLE
Badge scroll does not recognize hidden badges and fades anyway

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#25343]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The new scroll badge feature is great, and the fade effect very beautiful.
thanks for implementing that

one issue:
when several badges are hidden (when their visibility condition is not met, the remaining visible badges are still faded, even when well within the boundaries of the single column

(I believed to have already written this up, but cant find it anymore... sorry if there is an open issue elsewhere already after all)

### Describe the behavior you expected

dont fade badges that are within the available screen size for the column

### Steps to reproduce the issue

1. just add a few badges with a condition
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.5.0bx

### In which browser are you experiencing the issue?

any

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
  header:
    layout: center
    badges_position: bottom
    badges_wrap: scroll
  badges:
    - entity: sun.sun
    - entity: sun.sun
    - entity: sun.sun
      visibility:
        - condition: state
          entity: sun.sun
          state: below_horizon
```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

yaml config from above:

<img width="531" alt="Image" src="https://github.com/user-attachments/assets/60bc7f1e-055f-4e30-bc82-9c5614a0ddae" />

just 3 badges, nothing further, showing fine inside the available column

<img width="623" alt="Image" src="https://github.com/user-attachments/assets/65d73ece-735f-4c19-a1f7-32cd222d4733" />

same 3 badges, and a few identical 'hidden' badges, that now cause the right most badge to fade, as if more badges would be scrollable.

<img width="671" alt="Image" src="https://github.com/user-attachments/assets/05819c35-5bbd-4fd6-b0f0-ddfc13a368c4" />
