### ISSUE TITLE
Add Action button disappears when switching between YAML and UI in automation

### ISSUE THREAD

**Issue by MaJerle** [home-assistant/frontend#25434]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If one makes the automation in YAML and tries to switch to UI, the *Add action* button disappears for `if` block when `then:` has been written in the UI but not completed with the actions.

### Describe the behavior you expected

*Add action* button shall be available in the UI for user all the time.

### Steps to reproduce the issue

1. Start a new automation
2. Go to YAML
3. Under actions start writing code with `if`:
```yaml
actions:
  - if:
      - condition: numeric_state
        entity_id: sensor.your_sensor_entity
        above: 0
    then:
```
4. Switch to UI - there will be no *Add action* button anymore

![Image](https://github.com/user-attachments/assets/673d7cfc-b1a9-4449-9763-896bf561b396)
5. If you switch back to the YAML, the new YAML code will append the `null` to the `then:` statement
```yaml
actions:
  - if:
      - condition: numeric_state
        entity_id: sensor.your_sensor_entity
        above: 0
    then: null
```
6. If you remove the `then: null` from the YAML and go back to UI, button appears again.

### What version of Home Assistant Core has the issue?

core-2025.5.1

### What was the last working version of Home Assistant Core?

none I am aware

### Which operating system are you using to run this browser?

Windows-11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
