### ISSUE TITLE
Home Assistant not setting cookies / persisting login

### ISSUE THREAD

**Issue by danielrosehill** [home-assistant/frontend#25430]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since last Home Assistant upgrade:

- Authentication is not persisting due to cookies not being provided to the browser 
- Deployment is behind Cloudflare Tunnel attached using Cloudflare add-on 

Representative codeblock from config:

```yaml
http:
  server_port: 8123
  cors_allowed_origins:
    - https://myhomeassistant.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
  use_x_frame_options: true
```

Inspecting in Dev Tools, no cookie is being provided to the user, hence authentication cannot hold:

![Image](https://github.com/user-attachments/assets/48aa3e46-8a5d-4e1b-b75a-f63e48d056a2)

### Describe the behavior you expected

HA should:

- Provide cookie

### Steps to reproduce the issue

- HAOS on VM installation
- Proxy configuration via Cloudflare Tunnel

### What version of Home Assistant Core has the issue?

2025.5.1

### What was the last working version of Home Assistant Core?

2025.5.0

### In which browser are you experiencing the issue?

Version 136.0.7103.92 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 25.04

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
Frontend
20250509.0
```

### Javascript errors shown in your browser console/inspector

```txt

```
