### ISSUE TITLE
Automation Action missing menu when alias has insufficient whitespace

### ISSUE THREAD

**Issue by kerryland** [home-assistant/frontend#25474]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I edit this automation **using the Android app** the "3 dot" menu does not appear for the action. It's fine in a normal browser on my PC.

![Image](https://github.com/user-attachments/assets/dfab6d07-b2db-4c17-8229-310deb0b6245)

It's caused by the name containing a long string of text without any whitespace (e.g. "alexa_media_family_room_sonos_beam"). In the real world this alias was generated automatically by HA, but setting the name explicitly via `alias:` illustrates the same problem.

PS: Ticket originally raised [here](https://github.com/home-assistant/android/issues/5309) but apparently that was the wrong place.

### Describe the behavior you expected

I should be able to use the spill-over "3 dot" menu, regardless of the action's name.

### Steps to reproduce the issue

1. Create an automation with the following yaml

```
alias: test test test
description: ""
triggers:
  - at: "19:30:00"
    trigger: time
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
    alias: 'No Menu: alexa_media_family_room_sonos_beam'
mode: single
```
2. View it via the Android app (or Android Chrome or Android Firefox)
3. See missing menu 

### What version of Home Assistant Core has the issue?

2025.5.1

### In which browser are you experiencing the issue?

HA Android app 2025.4.3-full, Android Chrome 136.0.7103.87, Android Firefox 138.0.2

### Which operating system are you using to run this browser?

Android 10

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

I notice that the [Brave browser](https://play.google.com/store/apps/details?id=com.brave.browser) does not have this problem -- it shows the menu correctly.
