### ISSUE TITLE
input_select does not show all options in UI edit panel

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#25473]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

see options in dropdown

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/bec5fc40-3ba1-4fae-9392-e7273bd89425" />

see edit in UI

<img width="570" alt="Image" src="https://github.com/user-attachments/assets/a29b0188-330e-4545-ba7e-7e526c1207e3" />

not happening to all, in fact, most are correctly displaying all options, 2 however with a larger number of options dont show any options, but the one selected 

### Describe the behavior you expected

show all options in the editor

### Steps to reproduce the issue

1. see above
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.5.1

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

**Comment by karwosts** [comment]
Are you using the set_options service to override the options? 

Options set by that wouldn't be shown there, and on reboot it will revert back to the options from the entity configuration.

**Comment by Mariusthvdb** [comment]
.....

I figured I didnt, because of the options in the registry.

but then you made me remember...

```
      - action: input_select.set_options
        target:
          entity_id:
            - input_select.destination
            - input_select.origin
        data:
          options: >
            {{['zone','familie']|map('label_entities')|sum(start=[])
              |map('state_attr','friendly_name')|list}}
```

thank you!

btw, how come these are then still listed in the registry, and, when that is the case, not in the editor UI, but uneditable?
