### ISSUE TITLE
Error in Español (Latin America) automations visual editor

### ISSUE THREAD

**Issue by igarreta** [home-assistant/frontend#25527]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have the following automation:

```
alias: "Tanque de agua: encender durante el dia"
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.cantidad_de_agua_tanque
    for:
      hours: 0
      minutes: 12
      seconds: 0
    below: 300
conditions:
  - condition: state
    entity_id: input_boolean.activar_bomba_agua
    state: "on"
  - condition: not
    conditions:
      - condition: time
        after: "02:00:00"
        before: "06:00:00"
actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.bomba_tanque_de_agua
mode: single
```

And get the following error with the visual editor in Español (Latin America)

`Translation Error: The intl string context variable "entidad" was not provided to the string "Cuando {attribute, select, undefined {} other {{attribute} de } }{entidad} {numberOfEntities, plural, one {es} other {son} } debajo {below}{duration, select, undefined {} other { durante {duration}} }"`

If I turn the language to English or Español (not Latin America) the error disappears

### Describe the behavior you expected

Show this text in visual editor "Cuando Cantidad de agua tanque está por debajo de 300 durante 12:00"

### Steps to reproduce the issue

1. Swith language to Español (Latin America)
2. Add the inluded automation
3.
...

### What version of Home Assistant Core has the issue?

2025.5.2

### In which browser are you experiencing the issue?

Chrome 136.0.7103.114

### Which operating system are you using to run this browser?

Microsoft Windows 11 Pro / Versión	10.0.26100 compilación 26100

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```
