### ISSUE TITLE
BT Visualization (and other echarts graphs) blur text when primary-background-color is set in theme

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#25617]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

when setting that theme variable the names of the nodes are practically impossible to read, unless zooming in extremely. there seems to be a remnant of a background color to the names, which makes you feel to be seeing 'double'

<img width="941" alt="Image" src="https://github.com/user-attachments/assets/a0dcc13d-c2d2-4a42-8b43-52a1e745df35" />

its also visible in other graphs like this sankey:

<img width="720" alt="Image" src="https://github.com/user-attachments/assets/9d1e61cb-d28f-4124-8aaa-36c5eb2955be" />

and also when a lighter color is used, though that makes less troublesome:

<img width="303" alt="Image" src="https://github.com/user-attachments/assets/41e3fa44-a95b-4e5e-aa12-9cc07d42a60c" />

but you can still clearly see the  background surrounding the names.

**could it be the echarts add some background padding or so to the names that isnt in any theme at all, but only made visible when setting this?**

### Describe the behavior you expected

no background surrounding the names

### Steps to reproduce the issue

1. set primary-background-color in a theme and load that time
```
Dark mode:
  primary-background-color: '#111111'
```
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.6.0b0/1

### In which browser are you experiencing the issue?

any really tested Safdari/Chrome/Firefox/Edge

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

Ive made a special Dark mode theme, copying the exact theme variables of the css variables listed on https://github.com/home-assistant/frontend/blob/master/src/resources/theme/color.globals.ts#L301
or dev https://github.com/home-assistant/frontend/blob/e8fc36026a05e430451d5b56c10381441cdff065/src/resources/theme/color.globals.ts#L301

```yaml


Dark mode:
# https://github.com/home-assistant/frontend/blob/master/src/resources/theme/color.globals.ts#L301
  primary-background-color: '#111111'
  card-background-color: '#1c1c1c'
  secondary-background-color: '#282828'
  clear-background-color: '#111111'
  primary-text-color: '#e1e1e1'
  secondary-text-color: '#9b9b9b'
  disabled-text-color: '#6f6f6f'
  app-header-text-color: '#e1e1e1'
  app-header-background-color: '#101e24'
  switch-unchecked-button-color: '#999999'
  switch-unchecked-track-color: '#9b9b9b'
  divider-color: rgba(225, 225, 225, 0.12)
  outline-color: rgba(225, 225, 225, 0.12)
  outline-hover-color: rgba(225, 225, 225, 0.24)
  mdc-ripple-color: '#aaaaaa'
  mdc-linear-progress-buffer-color: rgba(255, 255, 255, 0.1)

  input-idle-line-color: rgba(255, 255, 255, 0.42)
  input-hover-line-color: rgba(255, 255, 255, 0.87)
  input-disabled-line-color: rgba(255, 255, 255, 0.06)
  input-outlined-idle-border-color: rgba(255, 255, 255, 0.38)
  input-outlined-hover-border-color: rgba(255, 255, 255, 0.87)
  input-outlined-disabled-border-color: rgba(255, 255, 255, 0.06)
  input-fill-color: rgba(255, 255, 255, 0.05)
  input-disabled-fill-color: rgba(255, 255, 255, 0.02)
  input-ink-color: rgba(255, 255, 255, 0.87)
  input-label-ink-color: rgba(255, 255, 255, 0.6)
  input-disabled-ink-color: rgba(255, 255, 255, 0.37)
  input-dropdown-icon-color: rgba(255, 255, 255, 0.54)

  codemirror-keyword: '#c792ea'
  codemirror-operator: '#89ddff'
  codemirror-variable: '#f07178'
  codemirror-variable-2: '#eeffff'
  codemirror-variable-3: '#decb6b'
  codemirror-builtin: '#ffcb6b'
  codemirror-atom: '#f78c6c'
  codemirror-number: '#ff5370'
  codemirror-def: '#82aaff'
  codemirror-string: '#c3e88d'
  codemirror-string-2: '#f07178'
  codemirror-comment: '#545454'
  codemirror-tag: '#ff5370'
  codemirror-meta: '#ffcb6b'
  codemirror-attribute: '#c792ea'
  codemirror-property: '#c792ea'
  codemirror-qualifier: '#decb6b'
  codemirror-type: '#decb6b'
  energy-grid-return-color: '#a280db'
  map-filter: invert(0.9) hue-rotate(170deg) brightness(1.5) contrast(1.2)
    saturate(0.3)
  disabled-color: '#464646'
```
and even this demonstrates the issue.

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

a zoomed out 

<img width="588" alt="Image" src="https://github.com/user-attachments/assets/c3448e61-4f8b-4288-830f-d0af47ebc54b" />

shot in Edge makes it very obvious
