### ISSUE TITLE
Time card doesnt resize to snap in grid

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#25621]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

<img width="598" alt="Image" src="https://github.com/user-attachments/assets/730b320b-389d-4bc4-9d7c-46f9a770eb53" />

### Describe the behavior you expected

auto resize to grid

### Steps to reproduce the issue

1. see yaml below
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.6.0

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
- type: grid
        columns: 4
        cards:

          - type: clock
            clock_size: large
            show_seconds: true
  
          - !include /config/dashboard/includes/button/button_dst.yaml

          - !include /config/dashboard/includes/button/button_seizoen.yaml
```

### Javascript errors shown in your browser console/inspector

```txt

```
