### ISSUE TITLE
Increased spacing on Entity card on 2025.6.0b0

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#25620]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On 2025.6.0b0 the Entity card is rendering with lots of extra spacing compared to before, I have these on a tablet dashboard and it fits less cards on screen now due to all this extra spacing.

Previous / Stable Release: 

![Image](https://github.com/user-attachments/assets/49f65872-b407-4b05-9acd-d2c82e0bf74e)

Beta Release (there's extra spacing between the name and entity value, and also below the entity value I think):

<img width="543" alt="Image" src="https://github.com/user-attachments/assets/2f8a0f46-26ac-4bf3-8a8d-2c1958eae488" />

### Describe the behavior you expected

Same style as 2025.5

### Steps to reproduce the issue

1. Add Entity card on 2025.6.0b0

### What version of Home Assistant Core has the issue?

2025.6.0b0

### What was the last working version of Home Assistant Core?

2025.5

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
- type: grid
        columns: 2
        square: false
        cards:
          - type: entity
            entity: sensor.upstairs_temperature
            name: Upstairs Avg Temp

          - type: entity
            entity: sensor.upstairs_humidity
            name: Upstairs Avg Humid

          - type: entity
            entity: sensor.downstairs_temperature
            name: Downstairs Avg Temp

          - type: entity
            entity: sensor.downstairs_humidity
            name: Downstairs Avg Humid
```

### Javascript errors shown in your browser console/inspector

```txt

```
