### ISSUE TITLE
Statistics graph Card configuration doesn't accept entity name

### ISSUE THREAD

**Issue by Recte** [home-assistant/frontend#25670]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

According to [the docs](https://www.home-assistant.io/dashboards/statistics-graph#options-for-entities), one could name the entities in the yaml. As shown below, the save button grays out once doing so and it shows  below.

![Image](https://github.com/user-attachments/assets/4786f424-7d38-4806-8f4e-7c2c5f935c64)

I tried it on iOS Safari and Linux Firefox, don´t have another browser. It grays out once you hit space after `name:`

### Describe the behavior you expected

I expect it to except the `name:` once entered. 

Never felt the need to do this before, so I don't know when it broke

### Steps to reproduce the issue

1. Go to statistic graph
2. Enter code editor
3. Goto the entities
4. create new line, indent and enter `name: `

### What version of Home Assistant Core has the issue?

2025.5.3

### What was the last working version of Home Assistant Core?

2025.5.3

### In which browser are you experiencing the issue?

Firefox 128.11.0esr (64-bit)

### Which operating system are you using to run this browser?

Debian Linux 12 Plasma 5 KDE 

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: day
type: statistics-graph
entities:
  - sensor.pi_hole_1_ads_percentage_blocked_today
    name: Pi-Hole
  - sensor.pi_hole_2_ads_percentage_blocked_today
stat_types:
  - max
title: "Block percentage "
days_to_show: 30
hide_legend: true
```

### Javascript errors shown in your browser console/inspector

```txt

```
