### ISSUE TITLE
Automation trace"Error in describing condition: e is not an Object (evaluating 'i in e')“

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#25694]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

A shortened template condition in automation conditions causes the following error displayed in the trace:

![Image](https://github.com/user-attachments/assets/a0cee51c-26ab-48c6-9438-884ba6db571a)

I write my automations in YAML. I often use a short version for template conditions. This worked for years.

### Describe the behavior you expected

No error message should appear. 
If this is treated as an error as of version 2025.6, feel free to close this issue.

### Steps to reproduce the issue

1. Use a short version of a template condition, e.g. `- "{{ is_state('sun.sun', 'below_horizon') }}"`
2. Wait until the automation was executed (or trigger it manually)
3. Check trace
...

### What version of Home Assistant Core has the issue?

core-2025.6.0b5

### In which browser are you experiencing the issue?

Safari 18.4

### Which operating system are you using to run this browser?

iPadOS

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
triggers:
      - trigger: state
        entity_id: sun.sun
        from: above_horizon
        to: below_horizon

      - trigger: state
        entity_id: sensor.daylight
        from: solar_noon
        to: golden_hour_2

    conditions:
      - |-
        {%- set last = state_attr(this.entity_id, 'last_triggered') %}
        {{ last is not none and now().date() != last.date() }}

    actions:
     …
```

### Javascript errors shown in your browser console/inspector

```txt

```
