### ISSUE TITLE
Areas dashboard does not show yaml defined entities

### ISSUE THREAD

**Issue by glennpierce** [home-assistant/frontend#25785]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have some yaml defined entities like

```
  sensor:
    - state_topic: "SolarEnergyMeter/export_energy/status"
      name: "Solar generated"
      unique_id: "solar_generated"
      device_class: "energy"
      state_class: "total"
      unit_of_measurement: "kWh"
      value_template: "{{ value[:-4] }}"

    - name: "Import / Export Power"
      unique_id: "power_import"
      device_class: "power"
      unit_of_measurement: "W"
      state_topic: "MainsEnergyMeter/total_active_power/status"
      value_template: "{{ value[:-2] }}"

```

I have assigned areas to these in the ui (Whole house). However, when trying to show these o the Whole House area in the Areas dashboard it does not show the entities.

### Describe the behavior you expected

I would expect the entities to show up in the others category sho I can add them to a area on the Areas dashboard.

### Steps to reproduce the issue

1. Defined an entiity in yaml
2.Assign area to the entitiy in the ui
3. Try to get it to show in the new Areas dashboard
...

### What version of Home Assistant Core has the issue?

core-

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```
