### ISSUE TITLE
shaking popover screen when clicking on attributes in Nutsmeters

### ISSUE THREAD

**Issue by robzgit** [home-assistant/frontend#25824]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I create this issue but it may be FF issue. I'm going to repeat this later in a clean FF install. Maybe someone will experience this too or can reproduce this.

Just updated Home Assistant to latest version and never saw this before.
For P1 meter and some energy sensors I created day/week/month/year totals via nutsmeter helpers. Some are working fine for more than a year, some are 2 weeks or so ago created.

Works fine. Till after upgrade. When clicking on 1 of the totals i see a graph and the energy use. On the bottom is the attributes pull down option. When I click on attributes the complete popover screen starts shaking and stops when i click again on attributes.

This happens in my preferred browser: Firefox 139.0.4 (64-bits). 
Refreshment <CTRL><F5> does not help
In In-private session I see the problem too.
In Home Assistant safe mode in Firefox same problem
When I Zoom the page from 100% out to 90% or 110% or something else it works fine (just found out in Safe mode)
The problem is only there when I use Firefox in Full screen, in a window it works fine too
In M$ Edge it works fine.

It worked fine in: previous: (2025.5.3)

actual: 2025.6.1
Installatiemethode Home Assistant OS
Core 2025.6.1
Supervisor 2025.05.5
Operating System 15.2
Frontend 20250531.3
Full HD screen 1920x1080

If you need more info just ask me.

### Describe the behavior you expected

I like a screen that is not shaking up and down.

### Steps to reproduce the issue

1. Create a sensor and create a helper nutsmeter on it with a resettime of an day, week or month
2. Safe some data
3. Open Home assistant in Firefox
4. Open a helper on the dashboard, graph and stats are shown.
5. Click on "attributes" on the bottom part op the popover.
6. Shaking begins emmediately and stop when closing the attributes part

### What version of Home Assistant Core has the issue?

2025.6.1

### What was the last working version of Home Assistant Core?

2025.5.3

### In which browser are you experiencing the issue?

Firefox 139.0.4 (64-bits)

### Which operating system are you using to run this browser?

Win10 22H2 screen 1920x1080px

### State of relevant entities

```txt
For example this one:
 	state_class: total_increasing
status: collecting
last_period: 77670
last_valid_state: 34585768
last_reset: 2025-06-15T22:00:00.005179+00:00
next_reset: 2025-06-23T00:00:00+02:00
unit_of_measurement: Wh
device_class: energy
friendly_name: Deze Week Stroom
```

### Problem-relevant frontend configuration

```yaml
type: grid
cards:
  - type: heading
    heading: Nieuwe sectie
  - type: vertical-stack
    title: Energie verbruik en opbrengsten
    cards:
      - type: horizontal-stack
        title: Gas
        cards:
          - type: tile
            entity: sensor.vandaag_gas
            name: Vandaag
            features_position: bottom
            vertical: false
          - type: tile
            entity: sensor.gas_deze_week
            name: Week
          - type: tile
            entity: sensor.gas_deze_maand
            name: Maand
            features_position: bottom
            vertical: false
    grid_options:
      rows: 8
```

### JavaScript errors shown in your browser console/inspector

```txt
-
```
