### ISSUE TITLE
Invalid 'X-Frame-Options' header encountered | breaks back button on Subview

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#25831]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

as title see logging below

happening on an iframe with that resource, or as full blown panel view. same error being logged

### Describe the behavior you expected

no loggin in the Inspector console

### Steps to reproduce the issue

1. see Yaml below
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.6.1

### In which browser are you experiencing the issue?

any

### Which operating system are you using to run this browser?

macOS 

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
type: iframe
aspect_ratio: 100%
url: |
  https://waterinfo.rws.nl/#/publiek/waterhoogte

title: Water info
path: water_info
subview: true
panel: true
cards:

  - type: iframe
    url: https://waterinfo.rws.nl/#/publiek/waterhoogte
```

### JavaScript errors shown in your browser console/inspector

```txt
Invalid 'X-Frame-Options' header encountered when loading 'https://waterinfo.rws.nl/#/publiek/waterhoogte': 'ALLOW-FROM *' is not a recognized directive. The header will be ignored.
```

### Additional information

Special note:
the subview in the above yaml **wont return to its origin**, because of this issue, no matter how often we click that, the browser seems not to recognize it at that point

![Image](https://github.com/user-attachments/assets/f72bc2f0-087b-4f9d-af8f-37ec6baa6903)
