### ISSUE TITLE
Automation editor forgets selected entities in action

### ISSUE THREAD

**Issue by DutchessNicole** [home-assistant/frontend#25853]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I add multiple entities in the media_player_entity_id entity selector for say, `tts.speak`, because I want to have it work on multiple media_player entities, the automation can save and it does work on all selected entities.
However, whenever I then edit this same automation again, the extra selected entities are lost from the automation and only the first one remains.

This means that I constantly have to re-add the media players that should be affected. This should not be the case.

If multiple entities are selected or added in YAML, those should always be kept as is.

### Describe the behavior you expected

I manually add the missing entities back into the YAML for the action every edit.

### Anything else?

I don't mind the entity picker not being able to select multiple items, but if a specific selection is saved to an automation section, it should not be altered without the user's input.

I know I can make media_player groups and use those instead, but that would mean I would have to make a specific permutation for each combination of entities, which is a waste of effort. 

### Steps to reproduce the issue

1. Create an automation with at least one action, I use `tts.speak`
2. Add at least two valid entity types for the key. I choose the `media_player_entity_id` and I add a list manually with three valid media_player entities.
```
action: tts.speak
metadata: {}
data:
  cache: true
  media_player_entity_id: 
    - media_player.home_assistant_voice_092047_media_player
    - media_player.home_assistant_voice_092443_media_player
    - media_player.home_assistant_voice_0971ee_media_player
```

3. Save the automation and re-open it.
4. Open the action you created in YAML mode. The list is gone and only the first item remains.
```
action: tts.speak
metadata: {}
data:
  cache: true
  media_player_entity_id: media_player.home_assistant_voice_092047_media_player
```

### What version of Home Assistant Core has the issue?

2025.6.1

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue?

Firefox/Chromium

### Which operating system are you using to run this browser?

Linux Mint 21.3 Virginia

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
n/a
```

### JavaScript errors shown in your browser console/inspector

```txt
None
```
