### ISSUE TITLE
Manual TESTing _identical_ / pass+fail condition for automation returns unplausible results

### ISSUE THREAD

**Issue by Stefan-Linux** [home-assistant/frontend#25873]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have varying / not 100% reproducible results, but finally somehow wrong.

I'm creating an automation and do manual testing of the conditions. And this seems to be broken.
1. On an identical condition (duplicated, checked to be identical in YAML), I got one time "pass" and one time "unclear".
2. After reloading the page, changing the border values to 6 and 16 (entity value is 10), I get "pass" in both cases. While expecting one to fail.

The checked entity is from Zendure HACS Integration.

So my problem is, I cannot interactively test my conditions, as the result is not save.

Picture for 1 (expecting identical results):

![Image](https://github.com/user-attachments/assets/511db987-d1ad-48ae-a6df-7368d25d226d)

Picture for 2 (expecting one to fail):

![Image](https://github.com/user-attachments/assets/b040450f-7c9f-4ffe-b669-c68d2b6fafaf)

Full YAML, check condition 2 and 3, with changed values 6 / 16:

```
alias: Zendure OR10 - Akku MIN 10% (re-set)
description: ""
triggers:
  - type: power
    device_id: 45ae132edef5a95c833bf6e17cb25112
    entity_id: 3fd36eaccc841a5c050a2c3e24889872
    domain: sensor
    trigger: device
    above: 150
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - type: battery_level
    device_id: dab2de9998f46b4784fa7ea766447078
    entity_id: 2cd0369c07bc0e623c95d968a3126d9c
    domain: sensor
    trigger: device
    below: 3
    for:
      hours: 0
      minutes: 0
      seconds: 30
conditions:
  - condition: numeric_state
    entity_id: sensor.or10_hyper2k_batterie
    below: 3
  - condition: numeric_state
    entity_id: number.or10_hyper2k_min_soc
    attribute: min
    below: 16
  - condition: numeric_state
    entity_id: number.or10_hyper2k_min_soc
    attribute: min
    below: 6
actions:
  - action: notify.mobile_app_stefans_iphone_se
    metadata: {}
    data:
      message: Zendure OR10 - Setze Akku Untergrenze zurueck auf 10%
      title: SOC reset to 10%
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - device_id: dab2de9998f46b4784fa7ea766447078
    domain: number
    entity_id: 8de8bd222ba565604c080e9584ad5a9a
    type: set_value
    value: 10
  - delay:
      hours: 24
      minutes: 0
      seconds: 0
      milliseconds: 0
mode: single
```

Entity:

![Image](https://github.com/user-attachments/assets/858683ca-9ff3-4f57-8af8-84f69c645d71)

Value:

![Image](https://github.com/user-attachments/assets/ef0e1f40-532e-4d84-b623-6da369423355)

I know this is not easy to debug / reproduce. But maybe somebody has same experience.

Thanks,  Stefan

Installationsmethode Home Assistant OS
Core 2025.6.1
Supervisor 2025.05.5
Operating System 15.2
Frontend 20250531.3

### Describe the behavior you expected

Correct result values for "Prüfen" (test).
Identical values for same condition on test.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.6.1

### In which browser are you experiencing the issue?

Firefox 139.0.4 (64-Bit) / Chrome Version 137.0.7151.68 (Offizieller Build) snap (64-Bit)

### Which operating system are you using to run this browser?

Ubuntu 24.04.2 LTS

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```
