### ISSUE TITLE
input_number: missing/disappearing current values and units of measurement

### ISSUE THREAD

**Issue by akasma74** [home-assistant/frontend#2905]
**Home Assistant release with the issue:**
Hass 0.89.0

**Last working Home Assistant release (if known):**
not sure

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome 72.0.3626.121 (Official Build) (64-bit)
OS X 10.11.6
and
Chrome 72.0.3626.105
Android 7.0

**Description of problem:**
2 problems here:
1. Despite defining unit_of_measurement in config.yaml I can only see them in slider mode
2. In slider mode current values and units of measurement show up or disappear randomly. I took 3 screenshots when resizing browser's window.
Initial window
![Screen Shot 2019-03-10 at 21 40 39 (2)](https://user-images.githubusercontent.com/13675855/54091990-c87baf00-437e-11e9-9695-b05644b7b1af.png)
Let's shrink it
![Screen Shot 2019-03-10 at 21 41 52 (2)](https://user-images.githubusercontent.com/13675855/54091992-cd406300-437e-11e9-9c24-d78ce16eb2ba.png)
.. and then make bigger
![Screen Shot 2019-03-10 at 21 42 07 (2)](https://user-images.githubusercontent.com/13675855/54091994-d03b5380-437e-11e9-993b-9449568a2d72.png)

Reloading without resizing does not help.
On my smartphone I can see no units of measurement and there is no way to resize window so I can see no units of measurement and current values.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
Only on initial load is the width calculated to determine if the value should be shown or not. We don't follow window resizing.

**Comment by akasma74** [comment]
First of all, that's not true - look at screenshots, they appear and disappear when I resize.
Secondly, do you think it's not a bug and the behaviour is documented for users so they clear they might not see the units?

**Comment by Mariusthvdb** [comment]
I noticed this just recently, and it seems to not be consistent, some of these show, some don't, apparently no matter the screen /column size:

![Schermafbeelding 2019-09-19 om 08 18 16](https://user-images.githubusercontent.com/33354141/65218117-16a00680-dab6-11e9-8c46-ebcdec4dfe32.jpg)

```
input_number:
  outdoors_brightness:
    name: Outdoors brightness
    icon: mdi:spotlight-beam
    min: 0
    max: 255
    step: 10

  perc_outdoors_brightness:
    name: '% Outdoors brightness'
    icon: mdi:spotlight-beam
    min: 0
    max: 100
    step: 5
```
and

![Schermafbeelding 2019-09-19 om 08 18 26](https://user-images.githubusercontent.com/33354141/65218124-1c95e780-dab6-11e9-8c4f-d4a10ca2cdf7.jpg)

```
input_number:
  high_lux:
    name: High Lux
    icon: mdi:gauge
#    initial: 100
    min: 0
    max: 400
    step: 10

  low_lux:
    name: Low Lux
    icon: mdi:gauge
#    initial: 40
    min: 0
    max: 200
    step: 5
```
