### ISSUE TITLE
Automation/Script Editor: Data Template

### ISSUE THREAD

**Issue by timstanley1985** [home-assistant/frontend#3258]
**Home Assistant release with the issue:**
 0.94.1

**Last working Home Assistant release (if known):** unknown

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** android chrome

**Description of problem:**

I am (finally) getting around to moving all my automations and scripts from individual yaml files to the UI editor. So far so good but I use a lot of templates and the editor does not seem to permit editing data_templates.  An extra field in the editor needs to be added to enable the editing of data_templates for service calls

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by timstanley1985** [comment]
Any thoughts on this one?

**Comment by Santobert** [comment]
Example:

```yaml
dummy:
  alias: Dummy
  description: "Dummy script to be executed if no other script matches the conditions."
  fields:
    deviceLocation:
      description: "Location of the given device"
      example: livingroom
  sequence:
    - service: notify.telegram
      data_template:
        title: dummy
        message: "deviceLocation: {{ deviceLocation }}"
```

results in:
![grafik](https://user-images.githubusercontent.com/15657682/68206406-e1e80000-ffcc-11e9-8875-a44e514d8e75.png)

**Comment by Aesculapius** [comment]
Any idea when this will be added? Very much welcomed, since even simple automations like setting light brightness based on time of day, seem not to be possible with the UI editor. Now I prevent using it at all, as it messes up the configuration somehow (strange linebreaks and not complete code).

Using this automation, not visible in UI:
```
  action:
  - data:
      brightness_pct: '{% if now().hour >= 21 %}2.0{% elif now().hour < 8 %}1.0{% else %}70.0{% endif %}'
    entity_id: light.shelly_dimmer_overloop
    service: light.turn_on
```
