### ISSUE TITLE
script status with wait instruction not well displayed in entities card

### ISSUE THREAD

**Issue by oncleben31** [home-assistant/frontend#3276]
**Home Assistant release with the issue:** 0.94.3

**Last working Home Assistant release (if known):** Don't know

**UI (States or Lovelace UI?):**Lovelace

**Browser and Operating System:** Bug viewed on Chrome 74.0.3729.169 and Safari 12.1

**Description of problem:**
State of script with `wait_template` instruction is not well displayed in entities card. For example when I launch the script by clicking the toggle. The toggle first go to `on` and then go back to `off` after 2 or 3 seconds even if the script is not finished.

Example to reproduce:
```yaml
script:
  test_debug:
    sequence: 
     - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.stop_debug
     - wait_template: "{{ is_state('input_boolean.stop_debug', 'on') }}"
```

You can recover the good state by refreshing the page in the web browser

**Javascript errors shown in the web inspector (if applicable):**No message in console

**Additional information:**
