### ISSUE TITLE
Automation Editor Doesn't work with data_template 

### ISSUE THREAD

**Issue by fguidetti** [home-assistant/frontend#3577]
**Home Assistant release with the issue:**

Version 0.98.1
**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Using lovelace

**Browser and Operating System:**

Chrome or Firefox

**Description of problem:**

In Automation.yaml  I have this automation:

```yaml
- id: Incoming call
  alias: call
  trigger:
    platform: state
    entity_id: sensor.phone
    to: ringing
  action:
  - service: tts.google_say
    data_template:
      message: Call From {{ states.sensor.phone.attributes.from_name }}
      entity_id: media_player.mpd 
```

everything work well.
If I edit this automation with 'Automation Editor' it doesn't show correctly and data_template statememt is not available

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
