### ISSUE TITLE
Conditional Card GUI preview filckers constantly

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#3646]
**Home Assistant release with the issue:**

0.98.4

**Last working Home Assistant release (if known):**

0.97.2?

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Firefox v69.0, Chrome v76.0.3809.132, Windows 10.

**Description of problem:**

When constructing a conditional card in the Manual Card GUI editor the preview constantly flickers. Example card config:
```
card:
  content: '![Image](/local/icons/rubbish_and_recycling/recycling.png)'
  title: Garbage and Recycling Tomorrow
  type: markdown
conditions:
  - entity: binary_sensor.recycling_week
    state: 'on'
  - entity: binary_sensor.garbage_tomorrow
    state: 'on'
type: conditional
```
Example of flickering: 

![flicker](https://user-images.githubusercontent.com/10679300/64489053-1328a600-d292-11e9-9499-fa799f9b2cf9.gif)

The state of the conditional entities is not changing.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
