### ISSUE TITLE
Home Assistant cast shows generated view instead of selected

### ISSUE THREAD

**Issue by pszafer** [home-assistant/frontend#3778]
**Home Assistant release with the issue:**
0.99.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
HA Cast
**Browser and Operating System:**
not applicable

**Description of problem:**
My full story:
- I upgraded my HA to 0.99.2 and tested cast to nvidia shield and callled service:
```
cast.show_lovelace_view
{
  "entity_id": "media_player.shield",
  "view_path": "camera"
}
```
It was working.

- Upgraded HA in my parents house and I wanted to test on same shield (we share vpn network with same subnet).
It was working
- Now calling same service from my instance of HA is not working
I get:
```
Unable to find a view with path camera
```

if I call service with `view_path: 0` I can see display with States UI of HA.
I can't find way to revert to see lovelace in cast.

My configuration yaml of http:
```
http:
  server_port: 443
  ssl_certificate: acme.fullchain
  ssl_key: acme.key
  base_url: https://myurl.com
  use_x_forwarded_for: true
  trusted_proxies:
    - HAPROXY IP
```

PS
Is it possible to control UI via remote controller of android tv?
