### ISSUE TITLE
entity filter to support wild cards so can filter by entity names

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#3831]
**Home Assistant release with the issue:**

All

**Last working Home Assistant release (if known):**
Current

**Operating environment (Hass.io/Docker/Windows/etc.):**

Docker

**Component/platform:**

Program itself

**Description of problem:**
Currently you need to specify the individual entities in a entity filter.
This should be changed to support wild as in the example below,
and there should also be a way to exclude certain devices.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
card:
  title: People at home
  type: glance
entities:
  - device_tracker.*
  - NOT device_tracker.*pc*
  - NOT device_tracker.*laptop*
  - NOT device_tracker.*server*
state_filter:
  - home
type: entity-filter
```
