### ISSUE TITLE
Automations condition.weekday missing in Automation GUI

### ISSUE THREAD

**Issue by ghost** [home-assistant/frontend#3833]
The weekday interface in the Automations UI is missing. 
I have the following config:
```yml
- id: '1555796295451'
  alias: Verwarming uit MA DI WO DO
  trigger:
  - at: '11:30'
    platform: time
  condition:   
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
  action:
  - data:
      entity_id: climate.woonkamer,climate.serre
      temperature: 16
    service: climate.set_temperature
  - data:
      entity_id: automation.schuifpui_dicht_zet_verwarming_aan
    service: automation.turn_off
```
But the interface looks like this
![image](https://user-images.githubusercontent.com/8215278/65832633-a6b82a00-e2c6-11e9-98b0-254b2e37512f.png)
It would be nice to have a <select> or something to select the weekday time condition and then a list of checkboxes/switches to add or remove the weekdays that will be added in the condition.
