### ISSUE TITLE
Alarm panel card does not scale well when stacked

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/frontend#3893]
The alarm card does not scale well when they are used in a horizontal stack card. Here's my config:
```yaml
      - type: horizontal-stack
        cards:
          - type: alarm-panel
            entity: alarm_control_panel.abode_alarm
            title: Abode
            states:
              - arm_home
              - arm_away
          - type: alarm-panel
            entity: alarm_control_panel.arlohome
            title: Arlo
            states:
              - arm_away
```
Here's the output

![image](https://user-images.githubusercontent.com/18319734/47518579-5c7a2d80-d859-11e8-89c4-a7bbe3207994.png)

cc: @zsarnett
