### ISSUE TITLE
Allow Entity Filter based on another entity

### ISSUE THREAD

**Issue by Roemer** [home-assistant/frontend#3969]
The entity filter card allows filtering all (or single entities coming with 0.100) on each entitys own state.
Would it be possible to add filtering based on the state of another entity?
I have the following scenario:

* light.livingroom controls if there is any current for the living room light
* light.hue_livingroom controls the hue light of the living room (which of course only works if light.livingroom is on

Now I want to hide the light.hue_liginvroom if light.livingroom is turned off and show it otherwise.
For that, I need to be able to add a filter just to the entity light.hue_livingroom.

The configuration in my case could look like:
```
type: entity-filter
entities:
  - light.livingroom
  - entity: light.hue_livingroom
    state_filter:
      - entity_id: light.livingroom
        value: 'on'
```

So the card would always show `light.livingroom` and `light.hue_livingroom` only if `light.livingroom` is `on`
