### ISSUE TITLE
history-graph with multiple entities loads much slower as all seperate history-graph elements

### ISSUE THREAD

**Issue by tr1plus** [home-assistant/frontend#4155]
**Home Assistant release with the issue:**

0.100.2

**Last working Home Assistant release (if known):**
Has been the case for a rather long time

**Operating environment (Hass.io/Docker/Windows/etc.):**

Docker

**Integration:**

**Description of problem:**
When putting 3 entities in the history graph it loads much, much slower as compared to 3 seperate graphs. See the video below:
https://youtu.be/Ou4hAv4aWFg

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
  - cards:
      - entities:
          - sensor.shrimp1_2
          - sensor.shrimp2_2
          - sensor.shrimp3_2
        refresh_interval: 30
        type: history-graph
    type: horizontal-stack
  - cards:
      - entities:
          - sensor.shrimp1_2
        refresh_interval: 30
        type: history-graph
    type: horizontal-stack
  - cards:
      - entities:
          - sensor.shrimp2_2
        refresh_interval: 30
        type: history-graph
    type: horizontal-stack
  - cards:
      - entities:
          - sensor.shrimp3_2
        refresh_interval: 30
        type: history-graph
    type: horizontal-stack
```

**Traceback (if applicable):**
```

```

**Additional information:**
