### ISSUE TITLE
Confusing (incorrect?) message when customizing entity via GUI

### ISSUE THREAD

**Issue by mrand** [home-assistant/frontend#4304]
**Home Assistant release with the issue:**
0.102.2

**Last working Home Assistant release (if known):**
n/a

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io on Ubuntu 16.04

**Description of problem:**

I decided to try customizing a device_tracker entity via the GUI and when I hit save, I got the following message which doesn't seems accurate.  I do have the include in what I believe to be the correct place, and it works - other device names are customized.

GUI message was as follows:

> It seems that your configuration.yaml doesn't properly include customize.yaml.
> Changes made here are written in it, but will not be applied after a configuration reload unless the include is in place.
> 

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
homeassistant:
  name: Home
  latitude: 32
  longitude: -96
  elevation: 190
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

```
