### ISSUE TITLE
Card Configuration dialog OK and Cancel buttons off screen

### ISSUE THREAD

**Issue by Unthred** [home-assistant/frontend#4320]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser

Home Assistant 0.102.3

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace UI

Frontend version: 20191119.6 - latest

**Browser and Operating System:**
Brave Browser (Chrome also) 
Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

OS: ubuntu 18.04 & Windows 10

**Description of problem:**

Sometimes when I am editing the frontend ui on the Card Configuration dialog the OK and Cancel buttons are completely off the screen. Enter does not autoselect nor does escape cancel. The dialog does not have a scrollbar on it. I have to refresh the page to get control back

**Expected behaviour:**

A scroll bar on the Card Configuration dialog would solve the issue

**Relevant config:**

![image](https://user-images.githubusercontent.com/5455511/70221172-c5f88b00-173f-11ea-9978-cb02354a325c.png)

**Steps to reproduce this problem:**

1) Click Configure UI
2) edit a complex card. This is the one I am editing just now
```
cards:
  - entities:
      - entity: light.lower_main_stripper
        toggle: true
        icon: 'bha:led-strip'
        type: 'custom:slider-entity-row'
      - entity: light.upper_main_stripper
        toggle: true
        icon: 'bha:led-strip'
        type: 'custom:slider-entity-row'
      - entity: light.lower_cooking_stripper
        toggle: true
        icon: 'bha:led-strip'
        type: 'custom:slider-entity-row'
      - entity: light.upper_cooking_stripper
        toggle: true
        icon: 'bha:led-strip'
        type: 'custom:slider-entity-row'
    head:
      entity: light.kitchen_strippers
      label: Kitchen Strippers
      toggle: true
      type: 'custom:slider-entity-row'
    type: 'custom:fold-entity-row'
type: 'custom:hui-vertical-stack-card'
```

**Javascript errors shown in the web inspector (if applicable):**
No errors shown in chromes console
