### ISSUE TITLE
Host is not reachable, rstp streaming camera

### ISSUE THREAD

**Issue by claudiofus** [home-assistant/frontend#4381]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.103.0 and 0.103.4

**Last working Home Assistant release (if known):**
Not known

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Docker on Raspberry Pi 4

**Description of problem:**
I have 3 camera connected as entity image in Home Assistant and sometimes a camera are not ready to stream (maybe network is slow) so I have an error page. The logs shows that the problem is "Host unreachable" for rstp camera.

**Expected behaviour:**
It would be nice to show the working cameras and show an error for the one that is not ready.

**Relevant config:**
```
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: template
    sensors:
      sunrise_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Alba"
        
      sunset_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Tramonto"
        
speedtestdotnet: 
    scan_interval: 
        minutes: 30
    server_id: 10456
    monitored_conditions: 
        - ping
        - download
        - upload        

camera:
  - platform: generic
    name: Cancello
    still_image_url: http://192.168.0.3:8123/local/cancello.png
    stream_source: rtsp://admin:@192.168.0.3:554
    
camera 2:
  - platform: generic
    name: Garage
    still_image_url: http://192.168.0.4:8123/local/garagecasa.png
    stream_source: rtsp://admin:@192.168.0.4:554
    
camera 3:
  - platform: generic
    name: Garage casa
    still_image_url: http://192.168.0.7:8123/local/garage.png
    stream_source: rtsp://admin:@192.168.0.7:554
```

**Steps to reproduce this problem:**
Open lovelace UI overview and reload page until camera is not ready to stream. It happens 3/10 to me (I have cheap camera for surveillance).

**Javascript errors shown in the web inspector (if applicable):**
Not applicable, it's an error page
