### ISSUE TITLE
Zones: radius actually sets diameter or zone is displayed wrongly on map

### ISSUE THREAD

**Issue by sgofferj** [home-assistant/frontend#4427]
**Home Assistant release with the issue:**
0.99.3

**Last working Home Assistant release (if known):**
Unknown

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker

**Component/platform:**
Zones

**Description of problem:**
The radius parameter seems to actually define the diameter of the zone, not the radius. Alternatively, it's possible that the UI map displays it wrongly.
I defined a home zone with a 50m radius but on the map it shows as having a diameter of 50m.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
  - name: Home                                                                                   
    latitude: 61.xxxxxx                                                                          
    longitude: 24.xxxxxx                                                                         
    radius: 50                                                                                   
    icon: mdi:home                                                                               
    passive: false                                                                               
```

**Traceback (if applicable):**
```
not applicable
```

**Additional information:**
none
