### ISSUE TITLE
Add "Hide when unavailable" toggle to Lovelace Media Control card

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4472]
Streaming sticks like Chromecast and Roku are super popular devices. Often these are powered by the USB port on the television, so whenever the TV is turned off, the media player becomes unavailable too.

One of the most common use cases I see for conditional cards is to hide media players that are unavailable. This isn't too user friendly currently - it requires knowledge of conditional cards and YAML.  I think it could be a lot simpler:

![media-control-unavailable](https://i.imgur.com/MfhpMeY.jpg)

A toggle to hide the media control card when the media player is unavailable. Would basically add the necessary conditional card.

```
type: conditional
conditions:
  - entity: media_player.living_room_roku
    state_not: "unavailable"
card:
  type: media-control
  entity: media_player.living_room_roku
```  

I don't know the logistics of this, would it break the preview since it'd be considered a conditional card and there's no UI editor for that? etc. But I think it'd make this common use case a lot easier.
