### ISSUE TITLE
picture-glance card using camera_image seems to "double fetch" the image

### ISSUE THREAD

**Issue by Codelica** [home-assistant/frontend#4554]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**

Home Assistant 0.104.2

**Last working Home Assistant release (if known):**

Unknown

**UI (States or Lovelace UI?):**

Lovelace UI

**Browser and Operating System:**

Chrome 79.0.3945.130 or Safari 13.0.1 on MacOS (Mojave)

**Description of problem:**

For some reason when a picture-glance card is configured to use a camera_image like the following (originally created via HA GUI):

``` yaml
aspect_ratio: 0%
camera_image: camera.main_floor
entities: []
title: "Main Floor"
type: picture-glance
```

The resulting UI card fetches the camera image twice for each update.  At least that's what I seem to be seeing via my NGINX proxy logs and Chrome Devtools.  

![Jade 2020-01-21 17-44-10](https://user-images.githubusercontent.com/386101/72855812-f35cb200-3c75-11ea-8af9-2b675d283c53.jpg)

![Home Assistant 2020-01-21 17-48-13](https://user-images.githubusercontent.com/386101/72855964-6d8d3680-3c76-11ea-88a0-1597adddf9b4.jpg)

**Expected behaviour:**

Camera snapshot proxy would just be called once per update.

**Relevant config:**

``` yaml
aspect_ratio: 0%
camera_image: camera.main_floor
entities: []
title: "Main Floor"
type: picture-glance
```

**Steps to reproduce this problem:**

1. Add Picture Glance card via HA GUI to a blank view
2. Configure to use a camera
3. Monitor requests to `/api/camera_proxy/xxxx` while just on that view in one browser/tab.

**Javascript errors shown in the web inspector (if applicable):**

Nothing noticed
```
```

**Additional information:**
