### ISSUE TITLE
Generic camera, picture-glance cards, DuckDNS(?) - perfect storm?! 

### ISSUE THREAD

**Issue by lancelon** [home-assistant/frontend#4650]
## Checklist

- [yep] I have updated to the latest available Home Assistant version.
- [yep] I have cleared the cache of my browser.
- [yep] I have tried a different browser to see if it is related to my browser.

## The problem
I'm using six generic cameras which load images from the www. They are set to ONLY download a new image if there's a change to the URL. I've tested with Chrome's development tools and they SEEM to be adhering to that rule. They only seem to download the once when the page first loads.
However, the six cameras, despite being supposedly static images once when the page has loaded, soon cause the (websocket?) page to freeze and essentially slowly poison the connection itself, often leading to an IP ban of the viewing browser. Seems to be extremely similar if not the same problem as [here](https://github.com/home-assistant/home-assistant/issues/23055).

## Expected behavior
That the six cameras should sit happily and just be without causing a crash

## Steps to reproduce
1. Create six generic camera sensors pointed at some online images, external to your LAN.
2. Look at them via the Lovelace picture-glance cards
3. Await crash/connection fail/IP ban

## Environment

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/London
version | 0.104.3
virtualenv | false
Frontend version: 20200108.2 - latest

-->

- Home Assistant release with the issue: 0.104.3
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): lovelace
- Browser and browser version: any
- Operating system: all 

## Problem-relevant configuration

```
      - camera_image: camera.radio1
        camera_view: live
        entities:
          - automation.forked_demand
        type: picture-glance
      - entities:
          - entity: sensor.friendly_r1_status
        show_icon: false
        show_name: false
        show_state: true
        type: glance
      - camera_image: camera.radio2
        camera_view: live
        entities:
          - automation.forked_demand
        type: picture-glance
      - entities:
          - entity: sensor.friendly_r2_status
        show_icon: false
        show_name: false
        show_state: true
        type: glance
      - camera_image: camera.radio3
        camera_view: live
        entities:
          - automation.forked_demand
        type: picture-glance
      - entities:
          - entity: sensor.friendly_r3_status
        show_icon: false
        show_name: false
        show_state: true
        type: glance
      - camera_image: camera.radio4
        camera_view: live
        entities:
          - automation.forked_demand
        type: picture-glance
      - entities:
          - entity: sensor.friendly_r4_status
        show_icon: false
        show_name: false
        show_state: true
        type: glance
      - camera_image: camera.radio4extra
        camera_view: live
        entities:
          - automation.forked_demand
        type: picture-glance
      - entities:
          - entity: sensor.friendly_r4extra_status
        show_icon: false
        show_name: false
        show_state: true
        type: glance
      - camera_image: camera.radio6
        camera_view: live
        entities:
          - automation.forked_demand
        tap_action:
          action: call-service
          service: automation.trigger
          service_data:
            entity_id: automation.alert_that_rosetta_is_down
        type: picture-glance

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Not sure if this is a lovelace or a back end error. It seemed more lovelacey because if you don't actually VIEW the cameras everything works swell.
