### ISSUE TITLE
When setting Delay with yaml params, the interface sets the delay to '[object Object]'

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#4733]
## The problem
When setting a delay (as in the eg below) in a script / automation using the yaml interface, then re-editing with the interface, the delay in the yaml becomes '[object Object]' (an invalid delay)...

## Environment

- Home Assistant release with the issue: 0.104.3
- Last working Home Assistant release (if known): 
- Operating environment (Hass.io/Docker/Windows/etc.): Docker
- Integration causing this issue: Script Syntax
- Link to integration documentation on our website: https://www.home-assistant.io/docs/scripts/

## Problem-relevant `configuration.yaml`

```yaml
delay:
  milliseconds: 250
#When re-saving this is changed to:
delay: '[object Object]'
```
