### ISSUE TITLE
Error selecting scene in footer Entities Card

### ISSUE THREAD

**Issue by Rep-Hueman** [home-assistant/frontend#4794]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Error slecting scene in footer Entities Card:
Failed to call service scene/turn_off.Service not found

## Expected behavior

Click on icon must turn scene on!

## Steps to reproduce

footer:
  entities:
    - scene.woonkamer_gedimd

## Environment

- Home Assistant release with the issue: 0.105.1
- Operating system: Win 10

## Problem-relevant configuration

Entities Card Configuration
```yaml
entities:
  entity: light.zolder
  entity: light.woonkamer
footer:
  entities:
    scene.woonkamer_gedimd
    entity: script.1581004556664
    icon: 'mdi:weather-sunset-down'
  type: buttons
show_header_toggle: false
title: Zone
type: entities
```
## Javascript errors shown in your browser console/inspector

Failed to call service scene/turn_off.Service not found

```

## Additional information

**Comment by iantrich** [comment]
please format your configuration using backticks

**Comment by balloob** [comment]
What's happening here is that we call `toggleEntity`, but that's not something that works for scenes.

**Comment by BradyRosino** [comment]
If you don't want to mess with the default toggle behavior, could we make it so each entity button in a header or footer could have it's own tap_action, hold_action, or double_tap_action defined, similar to picture header or footers? That way anybody could override the default behavior as they see fit?

Something like this:

```
entities:
  - entity: fan.downstairs_bradyoffice_ceiling
  - entity: light.downstairs_bradyoffice_ceiling
  - entity: light.downstairs_bradyoffice_desk
  - entity: light.downstairs_bradyoffice_corner
  - entity: light.downstairs_bradyoffice_bookshelf
  - entity: media_player.downstairs_bradyoffice_sonos
footer:
  entities:
    - entity: scene.brady_office_work
      icon: 'mdi:briefcase'
      tap_action:
        action: call-service
        service: scene.turn_on
        service_data:
          entity_id: scene.brady_office_work
    - entity: scene.brady_office_late_night
      icon: 'mdi:weather-night'
      tap_action:
        action: call-service
        service: scene.turn_on
        service_data:
          entity_id: scene.brady_office_late_night
  type: buttons
title: Brady's Office
type: entities
```
