### ISSUE TITLE
Consistency of variables accepted for Home zone; presence of only one Home zone in Zones editor

### ISSUE THREAD

**Issue by grantalewis** [home-assistant/frontend#4801]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

There are several locations where the Home zone can be configured (in configuration.yaml as part of  `homeassistant:`, in zones.yaml, in Configuration | General, and in the Zones editor). There's some inconsistency as to what/where variables can be set. For instance, `radius:` can't be set in configuration.yaml or in Configuration | General; `elevation:` can't be set in zones.yaml or the Zones editor.

In addition, if the Home zone is not defined in configuration.yaml but is defined in the Zones editor, two entries result: the created one, and another that might be hilariously wrong (mine was off the coast of Equatorial Guinea in the Atlantic Ocean).

## Expected behavior

- That the user may enter longitude, latitude, radius, and elevation for the Home zone in configuration.yaml, zones.yaml, Configuration | General, or the Zones editor
- That on boot/reload, settings made in an earlier location override settings that follow later (perhaps in the order listed: configuration.yaml, zones.yaml, Configuration | General, Zones editor) 
- That when the Home zone is defined, it is the only Home zone used

## Steps to reproduce

See above.

## Environment

- Home Assistant release with the issue: Home Assistant Core 0.105.2
- Last working Home Assistant release (if known): (unknown)
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox 72.0.2 (64-bit)
- Operating system:
  arch | x86_64
  dev | false
  docker | true
  hassio | true
  os_name | Linux
  python_version | 3.7.6

## Problem-relevant configuration

configuration.yaml:
```
homeassistant:
  name: Home
  latitude: !secret my_latituide
  longitude: !secret my_longitude
  elevation: 228 #can't be defined in the Zones editor or in zones.yaml
  radius: 60 #can't be defined in configuration.yaml or in Configuration | General
  unit_system: imperial
  time_zone: America/New_York
```

## Javascript errors shown in your browser console/inspector

```
  zone:
    - Invalid config for [zone]: [elevation] is an invalid option for [zone]. Check: zone->zone->0->elevation. (See /config/configuration.yaml, line 64).
```
