### ISSUE TITLE
View Configuration edits wrong view if the URL path begins with a number

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4805]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Discovered this bug while trying to help "osh" troubleshoot something in Discord. 

He had a view titled "3D Printer" with the url path of `3d-printer` 
But when editing the view, it would select an entirely different "Comfort" view.

He shared this screenshot which helped me figure it out:

![bug](https://i.imgur.com/VOvcJ4b.png)

When a view starts with a number in the url path, the UI editor messes up and attempts to edit that view index number. In the above screenshot "Overview" is view 0, "Media" is view 1, "Lighting" is view 2, and "Comfort" is view 3.

One of the issues here is that when you add a new view titled "3D Printer" the url path is automatically generated/pre-filled as `3d-printer` for you. It should either strip that number out, show an error in red text next to the URL field, or warn the user when saving.

## Expected behavior

Always edit the proper view the user clicked the pencil icon next to

## Steps to reproduce

1. Open [Home Assistant demo](https://demo.home-assistant.io/)
2. Enter Configure UI mode
3. Enter Raw Config editor
4. Paste contents of configuration below and save
5. Now attempt to edit the "3D Printer" view or the "2nd Home" view and watch what happens...

## Environment

- Home Assistant release with the issue: 0.105.2
- Last working Home Assistant release (if known):  
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome stable
- Operating system: macOS

## Problem-relevant configuration

```yaml
title: Home Assistant
views:
  - icon: 'mdi:home'
    id: home
    title: Home
    badges: []
    cards:
      - type: 'custom:ha-demo-card'
  - title: Second
    path: second
    badges: []
    cards: []
  - title: Third
    path: third
    badges: []
    cards: []
  - title: Fourth
    path: fourth
    badges: []
    cards: []
  - title: 3D Printer
    path: 3d-printer
    badges: []
    cards: []
  - title: 2nd Home
    path: 2nd-home
    badges: []
    cards: []

```

## Javascript errors shown in your browser console/inspector

```txt

```
