### ISSUE TITLE
Automation editor, changes my automation from working to not working

### ISSUE THREAD

**Issue by etxttul** [home-assistant/frontend#4826]
## The problem
When changing ANY automation with the automation editor, it changes a specific automation from working to not working.

Specifically this.
```yaml
  action:
  - data_template:
      entity_id: input_text.trafik_7
      value: "{{ states.sensor.trafik_p4_stockholm.state.split ('http') [0] }}"
    service: input_text.set_value
```
This is working!!!

If I change ANY automation with the automation editor, the editor changes this automation to as follows.
```yaml
  - data_template:
      entity_id: input_text.trafik_7
      value: '{{ states.sensor.trafik_p4_stockholm.state.split (''http'') [0] }}'
    service: input_text.set_value
  - data_template:
```
This doesn't work. To point out the differences:

1. The quatation marks around the whole temple has changed from " to '.
2. The sitation marks around http has changed from ('http') to double (' 'http' ') (I put a space in between the' not to confuse it with a ").

## Environment
HW= RaspberryPi 4
Hostname | hassio
System | HassOS 3.9
Deployment | production
Version | 199
Latest version | 199

I tested this after upgrading today, I believe it is 0.105.2

The automation is new, I always had this problem. I think I was using 0.104 when I noticed it the first time.

## Problem-relevant `automation.yaml`
Using automation editor for one automation change another automation

## YAML
This is my full automation:
```yaml
- id: '1580301033027'
  alias: Övrigt_trafik_tweet
  description: ''
  trigger:
  - event_data:
      entity_id: sensor.trafik_p4_stockholm
    event_type: state_changed
    platform: event
  condition: []
  action:
  - data_template:
      entity_id: input_text.trafik_6
      value: '{{ states.input_text.trafik_5.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_time_6
      value: '{{ states.input_text.trafik_time_5.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_5
      value: '{{ states.input_text.trafik_4.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_time_5
      value: '{{ states.input_text.trafik_time_4.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_4
      value: '{{ states.input_text.trafik_3.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_time_4
      value: '{{ states.input_text.trafik_time_3.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_3
      value: '{{ states.input_text.trafik_2.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_time_3
      value: '{{ states.input_text.trafik_time_2.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_2
      value: '{{ states.input_text.trafik_1.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_time_2
      value: '{{ states.input_text.trafik_time_1.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_1
      value: '{{ states.input_text.trafik_7.state }}'
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_time_1
      value: '{{ states.input_text.trafik_time_7.state }}'
    service: input_text.set_value
  - delay: 00:02:00
  - data_template:
      entity_id: input_text.trafik_7
      value: "{{ states.sensor.trafik_p4_stockholm.state.split ('http) [0] }}"
    service: input_text.set_value
  - data_template:
      entity_id: input_text.trafik_time_7
      value: '{{ as_timestamp(states.sensor.trafik_p4_stockholm.last_changed)| timestamp_custom("%A
        %X") }}'
    service: input_text.set_value
```

##text
What it do? It takes a scrape sensor that scrapes the latest tweet and stores the 6 latest tweet in FIFO, that is I no longer only have the latest tweet I have the 6 latest tweet.

## Traceback/Error logs
<!--
  If you come across any trace or error logs, please provide them.

## Additional information
Background:
I tried to create the automation with the automation editor at first, but failed (haven't figured this one out so this is not the cause of the trouble report). When I failed I started to edit the automation,yaml I created directly in automation.yaml. This way I got it working. After some time it stopped working and I tried to figure out why. I found that the automation editor is messing up my automation.

Please note, I don't have to change this specific automation for this specific automation to change. It get messed up any time I change ANY automation with the automation editor.

Best Regards
Tobe

**Comment by etxttul** [comment]
Hi,

It seems my end of my trouble report was cut. I will add it the background missing.

I tried to do this automation through the automation editor in yaml mode, but I failed. Having created the automation in the editor, I went in to automation.yaml and made it work. But everytime I go in to the automation editor anything, it change this automation. I use the automation editor for most of my automation. It really has improved over the last months. The problem is not that big, I know the probem, but it is enoying. I might change a simple automation in the editor, then I have to go to automation.yaml to restore this automation.

I assume that the reason the automation didn't work when creating the automation from the editor is the same as why it is changing, but I can not tell. I was not troubleshooting HA at the time only my automation.

BR
Tobe

**Comment by zsarnett** [comment]
```yaml
- data_template:
      entity_id: input_text.trafik_7
      value: '{{ states.sensor.trafik_p4_stockholm.state.split ("http") [0] }}'
    service: input_text.set_value
```

If you change the YAML to this, does the editor change it?
