### ISSUE TITLE
Entities Card header toggle is not working with 'conditional' special rows

### ISSUE THREAD

**Issue by PronkMedia** [home-assistant/frontend#4865]
## Checklist
- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Entities Card header toggle is not working with 'conditional' special rows.
![image](https://user-images.githubusercontent.com/697093/74473034-34c23500-4ea3-11ea-9c7b-504f7d46c3ab.png)

## Expected behavior
The header toggle should also work with conditional rows.

## Steps to reproduce
1. Add an entity.
2. Add a special row with type: conditional.
3. Toggle header switch

## Environment
- Home Assistant release with the issue: 0.105.3
- Last working Home Assistant release (if known): n/a
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Google Chrome Version 80.0.3987.100 (Official Build) (64-bit)
- Operating system: macOS Catalina 10.15.3

## Problem-relevant configuration
```yaml
  - type: entities
    title: Huiskamer
    entities:
      - entity: light.buffetkast
      - type: conditional
        conditions:
          - entity: light.vloerlamp
            state_not: 'unavailable'
        row:
            entity: light.vloerlamp
            icon: mdi:floor-lamp
```

## Javascript errors shown in your browser console/inspector
n/a

## Additional information
n/a
