### ISSUE TITLE
Entities Card slider for number does not show for conditional rows

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#4898]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

If an entity row (slider input) is contained within a conditional row then the value & unit is not shown:
![image](https://user-images.githubusercontent.com/1435262/74628365-4a847280-51a1-11ea-94cc-d7b0b4db8778.png)

## Expected behavior

The value and unit should be shown

## Steps to reproduce

1. Add the following to the configuration.yaml:
```yaml
input_number:
  cleaning_interval:
    name: Cleaning interval
    min: 0
    max: 14
    step: 1
    icon: 'mdi:broom'
    unit_of_measurement: Days
```
2. Restart the HA server
3. Add the following card to lovelace:
```yaml
entities:
  - entity: input_number.cleaning_interval
  - type: divider
  - type: conditional
    conditions:
      - entity: input_number.cleaning_interval
        state_not: '0.0'
    row:
      entity: input_number.cleaning_interval
type: entities
```
4. notice that the numbers do not show next to the second slider

## Environment

- Home Assistant release with the issue: 0.105.4
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Opera & Chrome
- Operating system: Windows 10

## Problem-relevant configuration

```yaml
# listed in Steps to reproduce ... since this is a step to produce the issue
```

## Javascript errors shown in your browser console/inspector

```txt
N/A
```
