### ISSUE TITLE
Consistency in cards when media_player is off

### ISSUE THREAD

**Issue by zappasmart** [home-assistant/frontend#4904]
## The problem
When a media_player entity is off, GLANCE and ENTITIES cards show a state badge with media content, while MEDIA CONTROL card does not show any media content picture.
It's a consistency issue.

![image](https://user-images.githubusercontent.com/53600373/74668242-18750f80-51a5-11ea-8abc-ae06931321b3.png)

## Expected behavior
Expected behaviour needs to be defined and should aim at consistency in the experience.
Should the MEDIA CONTROL card display the media content picture when state is off?
Or should the GLANCE and ENTITIES cards not display the state badge picture when state is off?

## Steps to reproduce
1. Configure a media_player entity (test was made with universal media player)
2. Add a GLANCE card, an ENTITIES card and  MEDIA CONTROL card in the UI, all including the previous media_player entity
3. Play something, the turn it off
4. Observe the different cards and in particular the presence/absence of the media content pictures

## Environment
- Home Assistant release with the issue: 0.105.4
- Last working Home Assistant release (if known): N/A
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome
- Operating system: Windows

## Problem-relevant configuration
```yaml
      - type: glance
        entities:
          - entity: media_player.universal
      - type: entities
        entities:
          - entity: media_player.universal
      - type: media-control
        entity: media_player.universal
```
