### ISSUE TITLE
Time Inputs don't display two digits in FireFox when the value is 9 or less

### ISSUE THREAD

**Issue by andyshilton** [home-assistant/frontend#4921]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

When returning to a tab that has input_datetimes saved, the numbers are not displayed with two numerals as would be expected with time.

1) Enter "09:00"
2) go to a different tab
3) return to the tab with the time entry
4) you will see " 9: 0"

I've tested FireFox and Chrome (latest versions) on Windows 10, and Chrome on my Android Pixel XL3. **This only appears to affect FireFox.**

## Expected behavior

Times should display with 4 digits in Firefox, as they do in other browsers

## Steps to reproduce

1) Create an input_datetime:
```yaml
input_datetime:
  morning_working:
    name: Morning Start Time, Working Days
    has_date: false
    has_time: true
```
and put it on a tab 
2) Then set the time to "09:00"
3) Go to a different tab
4) re-visit the tab, it displays as " 9: 0"

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml
input_datetime:
  morning_working:
    name: Morning Start Time, Working Days
    has_date: false
    has_time: true
```

## Javascript errors shown in your browser console/inspector

```txt
n/a
```
