### ISSUE TITLE
Cannot save config from lovelace UI editor if the content is too big

### ISSUE THREAD

**Issue by nicolasvac** [home-assistant/frontend#4924]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I'm trying to save my layout in the lovelace editor, but because the preview is too big, i cannot scroll and press save.

## Expected behavior

I should be able to scroll and press save.
This happened by changing from horizontal-stack to vertical-stack.

## Environment

- Home Assistant release with the issue: 0.105.5
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version:  Brave Browser (chrome) at latest
- Operating system: MacOS 10.15

## Problem-relevant configuration

```yaml
type: vertical-stack
title: Ambiente
cards:
  - type: entities
    title: Ambiente
    show_header_toggle: false
    entities:
      - entity: sensor.temperatura_camera
        name: Temperatura
        ........
  - type: history-graph
    entities:
      - entity: sensor.temperatura_camera
      ......
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

I can see it has already been reported here: #3215 #4412 (this one less related but still a similar problem with size of the content)

<img width="1477" alt="Schermata 2020-02-19 alle 18 32 03" src="https://user-images.githubusercontent.com/45635090/74859061-9fadb900-5346-11ea-89fb-f68bb719ac58.png">
