### ISSUE TITLE
Alt-drag should prevent click events from being handled.

### ISSUE THREAD

**Issue by hovissimo** [home-assistant/frontend#4970]
## Checklist
- [✔️] I have updated to the latest available Home Assistant version.
- [✔️] I have cleared the cache of my browser.
- [✔️] I have tried a different browser to see if it is related to my browser.

## The problem
When alt-dragging on ui elements, registered click events are processed instead of the text being selected.
(Examples in 'Steps to reproduce`)

## Expected behavior
Alt-dragging on text should always select the text only, even if the text is interactive or a link.

## Steps to reproduce
Logs:
1. Visit the logs in 'Dev Tools' 
2. While holding alt on your keyboard, click and drag to select text on a log entry.
3. Notice that the log opens.

Overview:
1. Visit the Lovelace overview
2. While holding alt on your keyboard, click and drag to select text on a card (not the header, because it doesn't open cards anyway). 
3. Notice that the card opens.

Also, try this on any other link in your browser to see the expected behavior.

Example, by holding alt I can select the text on this page without visiting the linked url.
screenshot-->![image](https://user-images.githubusercontent.com/6434414/75180590-5c11d100-56f1-11ea-9a45-4bc5653288a7.png)

## Environment

- Home Assistant release with the issue: 0.105.3
- Frontend version: 20200130.2
- Last working Home Assistant release (if known): unknown
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 79, Firefox 72
- Operating system: Windows 10, Ubuntu 19

## Problem-relevant configuration

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

```

## Javascript errors shown in your browser console/inspector
None.
```txt

```
