### ISSUE TITLE
Custom element doesn't exist: hui-...

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/frontend#4984]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I'm seeing this since beta 0.106 from time to time, now i found a way to reproduce it.
![Auswahl_293](https://user-images.githubusercontent.com/26381449/75277515-7094bd00-5808-11ea-9117-f7f67f179a3e.png)

## Steps to reproduce

Create a view and add this entities card
```
type: entities
title: First card
show_header_toggle: false
entities:
  - type: 'custom:hui-gauge-card'
    entity: input_number.slider1
  - type: 'custom:hui-gauge-card'
    entity: input_number.slider1
```
The red cards show up for every gauge card.
This could be fixed by: (and that's the reason why i've seen this only from time to time)
- Opening another view that contains a gauge card and going back to the view with the entities card
- Creating a normal gauge card in the view, also if it's not visible
```
type: conditional
conditions:
  - entity: light.bed_light
    state: 'on'
card:
  type: gauge
  min: 0
  max: 100
  theme: default
  entity: input_number.slider1
```

Another example with a markdown and the state-switch by @thomasloven :
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - switch.test_switch
  - type: 'custom:state-switch'
    entity: switch.test_switch
    states:
      'on':
        type: markdown
        content: |
          switch is ON
      'off':
        type: markdown
        content: |
          switch is OFF
```
After reloading the card shows like this
![Auswahl_294](https://user-images.githubusercontent.com/26381449/75278260-d9306980-5809-11ea-90c3-42871e163dab.png)
Going to another tab with a markdown in it and back again, the card shows the expected markdown.
![Auswahl_295](https://user-images.githubusercontent.com/26381449/75278387-11d04300-580a-11ea-9bcf-62f7d5bf1bea.png)

## Environment

- Home Assistant release with the issue: 0.106.0bx
- Last working Home Assistant release (if known): 0.105.4
- UI Type (States or Lovelace): LL
- Browser and browser version: FF and Chrome
- Operating system: Ubuntu

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
Nothing, absolutely clean.
```
