### ISSUE TITLE
Automations with value_template get corrupted by the Automation Editor

### ISSUE THREAD

**Issue by marcelvandongen** [home-assistant/frontend#5038]
## Checklist

- [x] I have updated to the latest available Home Assistant version: 0.107.0dev20200222
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser: Chrome and Edge.

## The problem

I use automations for the Xiaomi Magic Cube, with a condition that uses a value_template. When I use the Automation Editor in the Frontend and save the automation, the value_template get corrupted. From this:
```
- alias: Brightness up with Cube
  id: '1585630664465'
  description: ''
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: magic_cube_woonkamer
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.gesture == 7 }}
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.71448200bcddc29c5799
    service: light.turn_on
```
To this:

```
- alias: Brightness up with Cube
  id: '1585630664465'
  description: ''
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: magic_cube_woonkamer
  condition:
    condition: template
    value_template: '{{ trigger.event.data.gesture == 7 }}

      '
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.71448200bcddc29c5799
    service: light.turn_on
```
If the value_template contains multiple, longer lines (e.g. flip90) it goes from this:
```
  condition:
    condition: template
    value_template: >
      {% set valid_events = [1002, 1003, 1004, 1005, 2001, 2003, 2004, 2006, 3001, 3002, 3005, 3006, 4001, 4002, 4005, 4006, 5001, 5003, 5004, 5006, 6002, 6003, 6004, 6005] %}
      {{ trigger.event.data.event in valid_events }}
```
to this:
```
  condition:
    condition: template
    value_template: '{% set valid_events = [1002, 1003, 1004, 1005, 2001, 2003, 2004,
      2006, 3001, 3002, 3005, 3006, 4001, 4002, 4005, 4006, 5001, 5003, 5004, 5006,
      6002, 6003, 6004, 6005] %} {{ trigger.event.data.event in valid_events }}

      '
```
So it will also break off any lines longer than about 80 characters. Even worse, it corrupts all the automations in my yaml file.

## Expected behavior

The Automation Editor should be aware of value_templates and the '>' sign and not add the extra lines at the end, and also not split up lines longer than about 80 characters.

## Steps to reproduce

1. Add the first automation in the problem description to your automation.yaml file
2. From Server Controls, choose RELOAD AUTOMATIONS
3. Edit an automation using the Automation Editor and be sure to change something and save it
    (just add an 'a' somewhere and delete it)
4. Reopen your automation.yaml file

## Environment

- Home Assistant release with the issue: tested 0.103.6 and 0.107.0
- Last working Home Assistant release (if known): unknown
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 79 and Edge 42
- Operating system: Windows 10 1803

## Problem-relevant configuration

```
automation:
- alias: Brightness up with Cube
  id: '1585630664465'
  description: ''
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: magic_cube_woonkamer
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.gesture == 7 }}
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.71448200bcddc29c5799
    service: light.turn_on
```

## Javascript errors shown in your browser console/inspector

```
No errors.
```

## Additional information

Xiaomi Magic Cube gesture 7 is clockwise rotation (8 is counter clockwise).
