### ISSUE TITLE
When building a scene from the scene's editor, all capabilities are included in the settings

### ISSUE THREAD

**Issue by fribse** [home-assistant/frontend#5049]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When you build a scene by just adding the existing lights and their settings into the scene, all the capabilities of the light is included.
I have built a few scenes for my WLED lights, and ALL the effects it can do, all the capabilities etc. are included in the scene. This makes the scene extremely big when looking at it with an editor.

## Expected behavior

Only the settings that are set should be included, the capabilities of the light is already available in the light itself, and it will not help having them stored in the scene.

## Steps to reproduce

1. Set up lights to your liking
2. Add them to a scene
3. Look in the scene with an editor

## Environment

- Home Assistant release with the issue: 0.106.3
- Last working Home Assistant release (if known): unknown
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox 73.0.1
- Operating system:  Windows 10

## Problem-relevant configuration

```yaml
- id: '1583217876129'
  name: Party - Adrians Birthday
  entities:
    light.adrians_skrivebord:
      brightness: 255
      effect: Scanner
      effect_list:
      - Android
      - Blink
      - Blink Rainbow
      - Bpm
      - Breathe
      - Candle
      - Chase
      - Chase Flash
      - Chase Flash Rnd
      - Chase Rainbow
      - Chase Random
      - Circus
      - Colorful
      - Colorloop
      - Colortwinkles
      - Colorwaves
      - Dissolve
      - Dissolve Rnd
      - Dual Scan
      - Dynamic
      - Fade
      - Fill Noise
      - Fire 2012
      - Fire Flicker
      - Fireworks
      - Glitter
      - Gradient
      - Halloween
      - Halloween Eyes
      - ICU
      - Juggle
      - Lake
      - Lighthouse
      - Lightning
      - Loading
      - Merry Christmas
      - Meteor
      - Meteor Smooth
      - Multi Comet
      - Noise 1
      - Noise 2
      - Noise 3
      - Noise 4
      - Oscillate
      - Palette
      - Police
      - Police All
      - Pride 2015
      - Railway
      - Rain
      - Rainbow
      - Rainbow Runner
      - Random Colors
      - Red & Blue
      - Ripple
      - Running
      - Running 2
      - Saw
      - Scan
      - Scanner
      - 'Scanner Dual '
      - Solid
      - Solid Pattern
      - Solid Pattern Tri
      - Sparkle
      - Sparkle Dark
      - Sparkle+
      - Spots
      - Spots Fade
      - Stream
      - Stream 2
      - Strobe
      - Strobe Mega
      - Strobe Rainbow
      - Sweep
      - Sweep Random
      - Theater
      - Theater Rainbow
      - Traffic Light
      - Tri Chase
      - Tri Fade
      - Tri Wipe
      - Twinkle
      - Twinklecat
      - Twinklefox
      - Two Areas
      - Two Dots
      - Wipe
      - Wipe Random
      friendly_name: Adrians Skrivebord
      hs_color:
      - 120
      - 100
      icon: mdi:led-strip-variant
      intensity: 128
      max_mireds: 500
      min_mireds: 153
      palette: Default
      playlist:
      preset:
      rgb_color:
      - 0
      - 255
      - 0
      speed: 128
      state: 'on'
      supported_features: 183
      white_value: 0
      xy_color:
      - 0.172
      - 0.747
    light.garden:
      brightness: 255
      effect: Scanner
      effect_list:
      - Android
      - Blink
      - Blink Rainbow
      - Bpm
      - Breathe
      - Candle
      - Chase
      - Chase Flash
      - Chase Flash Rnd
      - Chase Rainbow
      - Chase Random
      - Circus
      - Colorful
      - Colorloop
      - Colortwinkles
      - Colorwaves
      - Dissolve
      - Dissolve Rnd
      - Dual Scan
      - Dynamic
      - Fade
      - Fill Noise
      - Fire 2012
      - Fire Flicker
      - Fireworks
      - Glitter
      - Gradient
      - Halloween
      - Halloween Eyes
      - ICU
      - Juggle
      - Lake
      - Lighthouse
      - Lightning
      - Loading
      - Merry Christmas
      - Meteor
      - Meteor Smooth
      - Multi Comet
      - Noise 1
      - Noise 2
      - Noise 3
      - Noise 4
      - Oscillate
      - Palette
      - Police
      - Police All
      - Pride 2015
      - Railway
      - Rain
      - Rainbow
      - Rainbow Runner
      - Random Colors
      - Red & Blue
      - Ripple
      - Running
      - Running 2
      - Saw
      - Scan
      - Scanner
      - 'Scanner Dual '
      - Solid
      - Solid Pattern
      - Solid Pattern Tri
      - Sparkle
      - Sparkle Dark
      - Sparkle+
      - Spots
      - Spots Fade
      - Stream
      - Stream 2
      - Strobe
      - Strobe Mega
      - Strobe Rainbow
      - Sweep
      - Sweep Random
      - Theater
      - Theater Rainbow
      - Traffic Light
      - Tri Chase
      - Tri Fade
      - Tri Wipe
      - Twinkle
      - Twinklecat
      - Twinklefox
      - Two Areas
      - Two Dots
      - Wipe
      - Wipe Random
      friendly_name: Garden
      hs_color:
      - 120
      - 100
      icon: mdi:led-strip-variant
      intensity: 128
      max_mireds: 500
      min_mireds: 153
      palette: Default
      playlist:
      preset:
      rgb_color:
      - 0
      - 255
      - 0
      speed: 128
      state: 'on'
      supported_features: 55
      xy_color:
      - 0.172
      - 0.747
    light.julelys_1stesal:
      brightness: 255
      effect: Scanner
      effect_list:
      - Android
      - Blink
      - Blink Rainbow
      - Bpm
      - Breathe
      - Candle
      - Chase
      - Chase Flash
      - Chase Flash Rnd
      - Chase Rainbow
      - Chase Random
      - Circus
      - Colorful
      - Colorloop
      - Colortwinkles
      - Colorwaves
      - Dissolve
      - Dissolve Rnd
      - Dual Scan
      - Dynamic
      - Fade
      - Fill Noise
      - Fire 2012
      - Fire Flicker
      - Fireworks
      - Glitter
      - Gradient
      - Halloween
      - Halloween Eyes
      - ICU
      - Juggle
      - Lake
      - Lighthouse
      - Lightning
      - Loading
      - Merry Christmas
      - Meteor
      - Meteor Smooth
      - Multi Comet
      - Noise 1
      - Noise 2
      - Noise 3
      - Noise 4
      - Oscillate
      - Palette
      - Police
      - Police All
      - Pride 2015
      - Railway
      - Rain
      - Rainbow
      - Rainbow Runner
      - Random Colors
      - Red & Blue
      - Ripple
      - Running
      - Running 2
      - Saw
      - Scan
      - Scanner
      - 'Scanner Dual '
      - Solid
      - Solid Pattern
      - Solid Pattern Tri
      - Sparkle
      - Sparkle Dark
      - Sparkle+
      - Spots
      - Spots Fade
      - Stream
      - Stream 2
      - Strobe
      - Strobe Mega
      - Strobe Rainbow
      - Sweep
      - Sweep Random
      - Theater
      - Theater Rainbow
      - Traffic Light
      - Tri Chase
      - Tri Fade
      - Tri Wipe
      - Twinkle
      - Twinklecat
      - Twinklefox
      - Two Areas
      - Two Dots
      - Wipe
      - Wipe Random
      friendly_name: Julelys 1stesal
      hs_color:
      - 120
      - 100
      icon: mdi:led-strip-variant
      intensity: 128
      max_mireds: 500
      min_mireds: 153
      palette: Default
      playlist:
      preset:
      rgb_color:
      - 0
      - 255
      - 0
      speed: 128
      state: 'on'
      supported_features: 55
      xy_color:
      - 0.172
      - 0.747
    light.kenneths_skrivebord:
      brightness: 255
      effect: Scanner
      effect_list:
      - Android
      - Blink
      - Blink Rainbow
      - Bouncing Balls
      - Bpm
      - Breathe
      - Candle
      - Chase
      - Chase Flash
      - Chase Flash Rnd
      - Chase Rainbow
      - Chase Random
      - Circus
      - Colorful
      - Colorloop
      - Colortwinkles
      - Colorwaves
      - Dissolve
      - Dissolve Rnd
      - Drip
      - Dynamic
      - Fade
      - Fill Noise
      - Fire 2012
      - Fire Flicker
      - Fireworks
      - Fireworks 1D
      - Fireworks Starburst
      - Glitter
      - Gradient
      - Halloween
      - Halloween Eyes
      - Heartbeat
      - ICU
      - Juggle
      - Lake
      - Lighthouse
      - Lightning
      - Loading
      - Merry Christmas
      - Meteor
      - Meteor Smooth
      - Multi Comet
      - Noise 1
      - Noise 2
      - Noise 3
      - Noise 4
      - Oscillate
      - Palette
      - Percent
      - Plasma
      - Police
      - Police All
      - Popcorn
      - Pride 2015
      - Railway
      - Rain
      - Rainbow
      - Rainbow Runner
      - Random Colors
      - Red & Blue
      - Ripple
      - Ripple Rainbow
      - Running
      - Running 2
      - Saw
      - Scan
      - Scan Dual
      - Scanner
      - Scanner Dual
      - Sinelon
      - Sinelon Dual
      - Sinelon Rainbow
      - Solid
      - Solid Pattern
      - Solid Pattern Tri
      - Sparkle
      - Sparkle Dark
      - Sparkle+
      - Spots
      - Spots Fade
      - Stream
      - Stream 2
      - Strobe
      - Strobe Mega
      - Strobe Rainbow
      - Sweep
      - Sweep Random
      - Theater
      - Theater Rainbow
      - Traffic Light
      - Tri Chase
      - Tri Fade
      - Tri Wipe
      - Twinkle
      - Twinklecat
      - Twinklefox
      - Two Areas
      - Two Dots
      - Wipe
      - Wipe Random
      friendly_name: Skrivebord
      hs_color:
      - 120
      - 100
      icon: mdi:led-strip-variant
      intensity: 128
      max_mireds: 500
      min_mireds: 153
      palette: Default
      playlist:
      preset:
      rgb_color:
      - 0
      - 255
      - 0
      speed: 128
      state: 'on'
      supported_features: 183
      white_value: 0
      xy_color:
      - 0.172
      - 0.747
    light.spisebord_1:
      brightness: 50
      friendly_name: Spisebord 1
      hs_color:
      - 119.533
      - 100
      rgb_color:
      - 1
      - 255
      - 0
      state: 'on'
      supported_features: 49
      xy_color:
      - 0.173
      - 0.747
    light.spisebord_2:
      brightness: 50
      friendly_name: Spisebord 2
      hs_color:
      - 119.533
      - 100
      rgb_color:
      - 1
      - 255
      - 0
      state: 'on'
      supported_features: 49
      xy_color:
      - 0.173
      - 0.747
    light.toilet:
      brightness: 255
      effect: Scanner
      effect_list:
      - Android
      - Blink
      - Blink Rainbow
      - Bouncing Balls
      - Bpm
      - Breathe
      - Candle
      - Chase
      - Chase Flash
      - Chase Flash Rnd
      - Chase Rainbow
      - Chase Random
      - Circus
      - Colorful
      - Colorloop
      - Colortwinkles
      - Colorwaves
      - Dissolve
      - Dissolve Rnd
      - Drip
      - Dynamic
      - Fade
      - Fill Noise
      - Fire 2012
      - Fire Flicker
      - Fireworks
      - Fireworks 1D
      - Fireworks Starburst
      - Glitter
      - Gradient
      - Halloween
      - Halloween Eyes
      - Heartbeat
      - ICU
      - Juggle
      - Lake
      - Lighthouse
      - Lightning
      - Loading
      - Merry Christmas
      - Meteor
      - Meteor Smooth
      - Multi Comet
      - Noise 1
      - Noise 2
      - Noise 3
      - Noise 4
      - Oscillate
      - Palette
      - Percent
      - Plasma
      - Police
      - Police All
      - Popcorn
      - Pride 2015
      - Railway
      - Rain
      - Rainbow
      - Rainbow Runner
      - Random Colors
      - Red & Blue
      - Ripple
      - Ripple Rainbow
      - Running
      - Running 2
      - Saw
      - Scan
      - Scan Dual
      - Scanner
      - Scanner Dual
      - Sinelon
      - Sinelon Dual
      - Sinelon Rainbow
      - Solid
      - Solid Pattern
      - Solid Pattern Tri
      - Sparkle
      - Sparkle Dark
      - Sparkle+
      - Spots
      - Spots Fade
      - Stream
      - Stream 2
      - Strobe
      - Strobe Mega
      - Strobe Rainbow
      - Sweep
      - Sweep Random
      - Theater
      - Theater Rainbow
      - Traffic Light
      - Tri Chase
      - Tri Fade
      - Tri Wipe
      - Twinkle
      - Twinklecat
      - Twinklefox
      - Two Areas
      - Two Dots
      - Wipe
      - Wipe Random
      friendly_name: Toilet
      hs_color:
      - 120
      - 100
      icon: mdi:led-strip-variant
      intensity: 128
      max_mireds: 500
      min_mireds: 153
      palette: Default
      playlist:
      preset:
      rgb_color:
      - 0
      - 255
      - 0
      speed: 128
      state: 'on'
      supported_features: 55
      xy_color:
      - 0.172
      - 0.747
    switch.adrians_skrivebord_nightlight:
      duration: 60
      fade: true
      friendly_name: Adrians Skrivebord Nightlight
      icon: mdi:weather-night
      state: 'off'
      target_brightness: 0
    switch.adrians_skrivebord_sync_receive:
      friendly_name: Adrians Skrivebord Sync Receive
      icon: mdi:download-network-outline
      state: 'on'
      udp_port: 21324
    switch.adrians_skrivebord_sync_send:
      friendly_name: Adrians Skrivebord Sync Send
      icon: mdi:upload-network-outline
      state: 'off'
      udp_port: 21324
    switch.garden_nightlight:
      duration: 60
      fade: true
      friendly_name: Garden Nightlight
      icon: mdi:weather-night
      state: 'off'
      target_brightness: 0
    switch.garden_sync_receive:
      friendly_name: Garden Sync Receive
      icon: mdi:download-network-outline
      state: 'on'
      udp_port: 21324
    switch.garden_sync_send:
      friendly_name: Garden Sync Send
      icon: mdi:upload-network-outline
      state: 'off'
      udp_port: 21324
    switch.julelys_1stesal_nightlight:
      duration: 60
      fade: true
      friendly_name: Julelys 1stesal Nightlight
      icon: mdi:weather-night
      state: 'off'
      target_brightness: 0
    switch.julelys_1stesal_sync_receive:
      friendly_name: Julelys 1stesal Sync Receive
      icon: mdi:download-network-outline
      state: 'on'
      udp_port: 21324
    switch.julelys_1stesal_sync_send:
      friendly_name: Julelys 1stesal Sync Send
      icon: mdi:upload-network-outline
      state: 'on'
      udp_port: 21324
    switch.kenneths_skrivebord_nightlight:
      duration: 60
      fade: true
      friendly_name: Kenneths skrivebord Nightlight
      icon: mdi:weather-night
      state: 'off'
      target_brightness: 0
    switch.kenneths_skrivebord_sync_receive:
      friendly_name: Kenneths skrivebord Sync Receive
      icon: mdi:download-network-outline
      state: 'on'
      udp_port: 21324
    switch.kenneths_skrivebord_sync_send:
      friendly_name: Kenneths skrivebord Sync Send
      icon: mdi:upload-network-outline
      state: 'off'
      udp_port: 21324
    switch.toilet_nightlight:
      duration: 60
      fade: true
      friendly_name: Toilet Nightlight
      icon: mdi:weather-night
      state: 'off'
      target_brightness: 0
    switch.toilet_sync_receive:
      friendly_name: Toilet Sync Receive
      icon: mdi:download-network-outline
      state: 'on'
      udp_port: 21324
    switch.toilet_sync_send:
      friendly_name: Toilet Sync Send
      icon: mdi:upload-network-outline
      state: 'off'
      udp_port: 21324

```

## Javascript errors shown in your browser console/inspector

```txt

```
