### ISSUE TITLE
History Graphs for the same entity but different time ranges will duplicate plots if longer one is first

### ISSUE THREAD

**Issue by linfoxo** [home-assistant/frontend#5061]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When creating two History Graph cards, for the same entity yet different time periods, the two cards will display the same data. Each page load it seems random which of the two it will duplicate, I'm assuming whichever one renders first.

It seems this only happens when the first graph has a longer time period than the second. If the shorter one is first, it appears to work fine.

## Expected behavior

Both History Graph cards display their unique timeframe regardless of page organisation.

## Steps to reproduce

* Create a History Graph card for an entity
* Create a second History Graph card for the same entity, with a shorter time period
* Place that second card below the first in display order

## Environment

- Home Assistant release with the issue: 0.106.4
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Firefox 73.0.1, MS Edge Chromium 80.0.361.62
- Operating system: Win 10

## Problem-relevant configuration

```yaml
type: history-graph
entities:
  - entity: sensor.linzoomy_range_sensor
hours_to_show: 168
refresh_interval: 0
title: Remaining Range (7-day)

type: history-graph
entities:
  - entity: sensor.linzoomy_range_sensor
hours_to_show: 24
refresh_interval: 0
title: Remaining Range (1-day)
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Identical to https://github.com/home-assistant/frontend/issues/2061, which has been closed with no action. Unsure if I can reopen that one.
