### ISSUE TITLE
Chrome 80 alarm_control_panel transition wired while pending state

### ISSUE THREAD

**Issue by Quentame** [home-assistant/frontend#5074]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

On Chrome (80 for me), the pending alarm state is glowing from white to orange at infinite.
Also tested on Firefox and Safari, pending state is always orange (not glowing).

```css
.label-badge {
     transition: border 0.3s ease-in-out 0s;
}
.label-badge .label span {
    transition: background-color 0.3s ease-in-out 0s;
}
```

## Expected behavior

I don't know, one behavior or an other, but coherent.

## Steps to reproduce

   1. Add into your config.yaml : 
```yaml
alarm_control_panel:
  - platform: manual
```
   2. Navigate to Lovelace
   3. Click on arm 

## Environment

- Home Assistant release with the issue: 0.107.0.dev0
- Last working Home Assistant release (if known): 
- Browser and browser version: Safari 13.0 + Chrome 80 + Firefox 74.0b9
- Operating system: macOS 10.15

## Problem-relevant configuration

```yaml
alarm_control_panel:
  - platform: manual
```

## Javascript errors shown in your browser console/inspector

```txt

```
