### ISSUE TITLE
On Android (App and mobile Chrome browser), single-tap action fires when double-tapping

### ISSUE THREAD

**Issue by lightmaster** [home-assistant/frontend#5075]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have a picture elements card set up in panel mode. Within it, I have an image setup that has a tap_action and a double_tap_action defined, both of which with confirmation prompts. The single tap works as expected, however the double tap causes both the double tap confirmation followed by the single tap confirmation to show up. Sort of like the opposite of Issue #4639.

On PC, it works correctly. On Android, in Chrome with Desktop Mode enabled, it works correctly. However, on Android in Chrome with Desktop Mode disabled and within the Android app, I see the double-tap confirmation, followed by the single-tap confirmation. Doesn't happen 100% of double taps, but a little more than half of double-clicks.

## Expected behavior

Only the double tap event should fire on a double tap.

## Steps to reproduce

1. Create an image with a double and single tap action within a picture elements.
2. On mobile site on Android, attempt to double tap on the sensor.

## Environment

- Home Assistant release with the issue: 0.106.5
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Home Assistant Android App & Android Chrome 80.0.3987.132
- Operating system: Android 10

## Problem-relevant configuration

Example config that shows the issue: [https://pastebin.com/7Fet9dh8](https://pastebin.com/7Fet9dh8). The entry that starts with `- entity: binary_sensor.kitchen_motion` is the one setup with a single-tap and double-tap action.

## Javascript errors shown in your browser console/inspector

txt

## Additional information

**Comment by bramkragten** [comment]
Can you just post the smallest possible config that allows us to reproduce this problem?

**Comment by lightmaster** [comment]
Here's a shortened version of the code, consisting of just the background image, the foreground image, some positioning style so it's not off the side of the screen, and a tap and double-tap code.

```

type: picture-elements
image: /local/hassets/layout/Home Assistant Backdrop blank.png
elements:
  - type: image
    entity: binary_sensor.kitchen_motion
    image: /local/hassets/assets/motion.png
    style:
      left: 49.5%
      top: 40%
      width: 1.5%
    tap_action:
      action: call-service
      confirmation:
        text: Enable the Kitchen motion sensor?
      service: input_boolean.turn_on
      service_data:
        entity_id: input_boolean.kitchen_motion_enabled
    double_tap_action:
      action: call-service
      confirmation:
        text: Disable the Kitchen Motion Sensor?
      service: input_boolean.turn_off
      service_data:
        entity_id: input_boolean.kitchen_motion_enabled
```
