### ISSUE TITLE
The Script GUI editor can expose information from secrets.yaml to the scripts.yaml file.

### ISSUE THREAD

**Issue by dfmckay** [home-assistant/frontend#5107]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [n/a ] I have cleared the cache of my browser.
- [n/a ] I have tried a different browser to see if it is related to my browser.

## The problem

When using a "!secret variable" in a script if I edit any script with the gui it will read the data and replace it with the actual variable in the scripts.yaml file. Also when attempting to write code in the gui it will change the "!secret variable" to "NULL"

## Expected behavior

The gui editor shouldn't replace the data.

## Steps to reproduce

1. Write a script in scripts.yaml that includes the use of "!secret"
    2. Go into the scripts editor and edit any script
    3. Save the script
    4. Look at the scripts.yaml file and take note the data that was obscured by the secrets file is now visible in the scripts.yaml file

## Environment

Running Home Assistant core 0.106.5 via docker on a x_86_64 nuc

- Home Assistant release with the issue:
- Last working Home Assistant release (if known): unkown
- Browser and browser version: n/a
- Operating system: n/a

## Problem-relevant configuration

```yaml
'1582914397778':
  alias: Arm Alarm Panel
  sequence:
  - data:
      code: !secret alarm
      entity_id: alarm_control_panel.home_alarm
    entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_away
```

## Javascript errors shown in your browser console/inspector

```txt

```
