### ISSUE TITLE
Media Player does not reset album cover color

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#5137]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

If media player goes from playing to paused, and paused doesn't have an album cover, we still show a square for the album cover.

Sonos playing my Spotify:
![image](https://user-images.githubusercontent.com/1444314/76458615-0a777080-6398-11ea-9f12-5d0f1f7d0d8a.png)

State: `playing`

Attributes:
```yaml
source_list: This Is Creedence Clearwater Revival
volume_level: 0.36
is_volume_muted: false
media_content_id: x-sonos-vli:RINCON_347E5C35DA6C01400:2,spotify:997fb54731b631d951d3cc968f9e8407
media_content_type: music
media_duration: 256
media_position: 179
media_position_updated_at: 2020-03-11T20:00:28.035860+00:00
media_title: O.N.S. Verhaal
media_artist: Rob Dekay
media_album_name: Alles Gaat Voorbij
shuffle: false
sonos_group: media_player.bookshelf
friendly_name: Bookshelf
entity_picture: /api/media_player_proxy/media_player.bookshelf?token=59588bb569c3a4b7aaab2c7a446db8c10d806a3c16583a4d973acaa185c188ae&cache=e6d9c51a4ee49d47
supported_features: 64063
```

In Spotify on my Mac, select Spotify to play on my mac. After:
![image](https://user-images.githubusercontent.com/1444314/76458591-01869f00-6398-11ea-9b44-c629c2c926a5.png)

State: `paused`

Attributes:
```yaml
source_list: This Is Creedence Clearwater Revival
volume_level: 0.36
is_volume_muted: false
media_content_id: x-sonos-vli:RINCON_347E5C35DA6C01400:2,spotify:2a5ab363818186b463068de2d7ac964c
media_content_type: music
media_position_updated_at: 2020-03-11T19:58:56.394009+00:00
media_title: 
media_artist: 
media_album_name: 
shuffle: false
sonos_group: media_player.bookshelf
friendly_name: Bookshelf
supported_features: 64063
```

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
