### ISSUE TITLE
[BUG] Issue with timestamp on iOS

### ISSUE THREAD

**Issue by vistalba** [home-assistant/frontend#5156]
## The problem
I have a sensor with device_class: timestamp
I wan't to display the time of this sensor. (Endtime of a washing machine).

I tried multiple custom formats to get it work proper:
`timestamp_custom('%Y-%m-%dT%H:%M:%S%z', false)`
`timestamp_custom('%Y-%m-%dT%H:%M:%S%z', true)`
`timestamp_custom('%Y-%m-%dT%H:%M:%S', false)`
`timestamp_custom('%Y-%m-%dT%H:%M:%S', true)`
`timestamp_local`

It is still now working in iOS App and Google Chrome on Windows.
Additional, the device I recieve the timestamp from is already using local time and will automatic adjust daylight saving time.
So I wan't just to display the time of the timestamp.

Card config:
```
entities:
  - entity: sensor.any-device-eta
    format: time
    name: Any-Device
show_header_toggle: false
title: Some Title
type: entities
```

## Expected behavior
Show the correct time without any offset.

## Environment

- Home Assistant release with the issue: 0.106.6
- Last working Home Assistant release (if known): -
- Browser and browser version: iOS 13.3.1 / 2.0.0 (69)
- Operating system: HSSIO

## Problem-relevant configuration
```
sensor:
  - platform: rest
    resource: "http://192.168.x.x/status"
    name: "any-device-eta"
    scan_interval: 60
    value_template: >-
      {% set hours, mins = value_json.ProgramEnd.End.split("h") %}
      {{ (now() | as_timestamp() + ((hours | int*60*60) + (mins|int*60))) | timestamp_custom('%Y-%m-%dT%H:%M:%S%z', false) }}
    device_class: timestamp
```

I also tried with `timestamp_local` but I run into the same issue. Chrome on WIndows 10 looks fine while in iOS I get an offset because of the timezone.
