### ISSUE TITLE
Entity Pictures not displayed in Entities panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5169]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I feel like this worked before, but I'm not 100% sure and may be thinking of the Unused Entities screen. But in the "Entities" panel, it is not displaying `entity_picture`, just `icon`.

![image](https://i.imgur.com/exgtEa6.png)

The scripts above have both an icon and entity picture, the entity picture is supposed to get priority I believe. This is how it's displayed in Lovelace (and other areas like dropdown on States dev tools panel and Scenes editor panel etc):
![image](https://i.imgur.com/qGIVEjv.png)

I would expect the pictures to show the same way in Entities panel.

lovelace config below.

## Environment

- Home Assistant release with the issue: 0.107.0b0
- Last working Home Assistant release (if known): ???
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml
homeassistant:

  # Customize entities matching a pattern
  customize_glob:
    "script.channel_*":
      icon: mdi:television-classic

  customize:
    script.channel_abc:
      entity_picture: /local/images/tv_channel_icons/ABC.png
    script.channel_abc_lr:
      entity_picture: /local/images/tv_channel_icons/ABC.png

```

## Javascript errors shown in your browser console/inspector

```txt

```
