### ISSUE TITLE
Truncated text on slider entity row

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#5274]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Text on the slider entity row now is truncated, before 0.107 it would shrink to fit the text ... also there still appears to actually be enough space
![image](https://user-images.githubusercontent.com/1435262/77038532-b73c9800-69ff-11ea-8712-72548527a1e0.png)

## Expected behavior

Should shrink to fit the text

## Steps to reproduce

```yaml
entities:
  - entity: input_number.cleaning_interval
    name: Cleaning Interval
  - entity: input_select.bin_day
type: entities
```

## Environment

- Home Assistant release with the issue: 0.107.0
- Last working Home Assistant release (if known): 0.106.X
- Browser and browser version: Chrome
- Operating system: Docker

## Problem-relevant configuration

```yaml
# as above
```

## Javascript errors shown in your browser console/inspector

**N/A**

```txt

```
