### ISSUE TITLE
Placing cards inside an entity row no longer works

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#5275]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

You used to be able to place built in cards within an entity row by using (for eg): custom:hui-picture-glance-card ...
This no longer works.

## Expected behavior

Cards should be peaceable in entity rows

## Steps to reproduce

```yaml
type: entities
entities:
 - type: 'custom:hui-picture-glance-card'
    title: Kitchen
    image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
    entities: []
    aspect_ratio: 0%
```

## Environment

- Home Assistant release with the issue: 0.107.0
- Last working Home Assistant release (if known): 0.106.X
- Browser and browser version: Chrome
- Operating system: Docker

## Problem-relevant configuration

```yaml
# AS ABOVE
```

## Javascript errors shown in your browser console/inspector

**N/A**

```txt

```

## Additional information
I would suggest allow the placement of any card within an entity row (without having to use the custom: bit for built in cards)
