### ISSUE TITLE
picture-entities within entities work no more

### ISSUE THREAD

**Issue by s3ta** [home-assistant/frontend#5277]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
I'm in lovelace yaml mode and use(d) the config below to get my cameras briefly displayed as shown in [this screenshot](https://snipboard.io/WSs1kp.jpg) ![up-to-104 3](https://user-images.githubusercontent.com/11409228/77046273-eda7f200-69c2-11ea-95b6-ff09cd3b6113.png)
- this was working (or is still working, since I downgraded meanwhile) up to 104.3.

After I upgraded to 107.1 those badge-like icons aren't shown and I get error messages shown in [this screenshot.](https://snipboard.io/pX21QJ.jpg) 
![from-107](https://user-images.githubusercontent.com/11409228/77046310-07493980-69c3-11ea-8a23-62f7baee1a30.png)

## Expected behavior

badge-like icons are shown as before upgrade
## Steps to reproduce

I guess a config like below should trigger the effect
## Environment

- Home Assistant release with the issue: 107.1
- Last working Home Assistant release (if known): 104.3
- Browser and browser version: chrome 
- Operating system: linux/ubuntu

## Problem-relevant configuration

```
cards:
      - type: horizontal-stack
        cards:
         - type: entities
           entities:
           - entity: camera.ipcam1_garten
             type: picture-entity
           - entity: camera.ipcam2_garten
             type: picture-entity
           - entity: camera.ipcam3_garten
             type: picture-entity

```

## Javascript errors shown in your browser console/inspector

none

## Additional information
I really searched for similar issues, but found nothing appropriate or wasn't sure if another (wider) issue contains this behaviour as well - I hope someone w/ more knowledge might merge/mark as dupe this issue, if he is sure.
