### ISSUE TITLE
Divider element no longer showing

### ISSUE THREAD

**Issue by PaulAntonDeen** [home-assistant/frontend#5290]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

![image](https://user-images.githubusercontent.com/25848961/77167565-9125ff00-6ab6-11ea-9255-a4fc98efe4ff.png)

## Expected behavior
 This code used to show a divider element. Can it be the hui should be gui (typo in the source code?)

## Steps to reproduce
Include a 'type: divider' in a card.

## Environment

- Home Assistant release with the issue: 0.107.1
- Last working Home Assistant release (if known): 0.106
- Browser and browser version: Chrome latest
- Operating system: All of them

## Problem-relevant configuration

```
cards:
  - entities:
      - entity: sensor.netherlands_coronavirus_confirmed
        name: Confirmed
      - entity: sensor.netherlands_coronavirus_current
        name: Current
      - entity: sensor.netherlands_coronavirus_deaths
        name: Deaths
      - entity: sensor.netherlands_coronavirus_recovered
        name: Recovered
    show_icon: false
    title: Netherlands
    type: glance
  - type: divider
  - entities:
      - entity: sensor.france_coronavirus_confirmed
        name: Confirmed
      - entity: sensor.france_coronavirus_current
        name: Current
      - entity: sensor.france_coronavirus_deaths
        name: Deaths
      - entity: sensor.france_coronavirus_recovered
        name: Recovered
    show_icon: false
    title: Frankrijk
    type: glance
  - type: divider
  - entities:
      - entity: sensor.italy_coronavirus_confirmed
        name: Confirmed
      - entity: sensor.italy_coronavirus_current
        name: Current
      - entity: sensor.italy_coronavirus_deaths
        name: Deaths
      - entity: sensor.italy_coronavirus_recovered
        name: Recovered
    show_icon: false
    title: Italie
    type: glance
  - type: divider
  - entities:
      - entity: sensor.worldwide_coronavirus_confirmed
        name: Confirmed
      - entity: sensor.worldwide_coronavirus_current
        name: Current
      - entity: sensor.worldwide_coronavirus_deaths
        name: Deaths
      - entity: sensor.worldwide_coronavirus_recovered
        name: Recovered
    show_icon: false
    title: Worldwide
    type: glance
type: 'custom:vertical-stack-in-card'


```

## Javascript errors shown in your browser console/inspector

```txt

```
