### ISSUE TITLE
Dashboard yaml file in a folder not found

### ISSUE THREAD

**Issue by JAAlperin** [home-assistant/frontend#5296]
## Checklist

- [X] I have updated to the latest available Home Assistant version. 0.107.2
- [X] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Cannot put dashboard yaml file in a folder.

Since the dashboard-01.yaml existed within the ui-lovelace_dashboards directory I expected both of the above configurations to display the proper dashboard.  Also, since the configuration.yaml specified mode: yaml and the dashboard block specified mode: yaml, I would have expected an error message, not a GUI generated display.

## Steps to reproduce

  in a dashboard block specify a filename within a directory such as in my example above.

## Environment

0.107.2
Path to configuration.yaml: /config

- Home Assistant release with the issue: 0.107.2
- Last working Home Assistant release (if known): never worked, new feature
- Browser and browser version: Chrome Version 80.0.3987.132 (Official Build) (64-bit)
- Operating system: MacOS 10.14.6

## Problem-relevant configuration

See failing and working dashboard configurations above.

```yaml
lovelace-generated:
  mode: yaml
  filename: dashboard-01.yaml
  title: Dashboard-01
  icon: mdi:tools
  show_in_sidebar: true
  require_admin: false
**The following results in display of a dashboard generated because the .yaml file is not found in the directory:**
lovelace-generated:
  mode: yaml
  filename: ui-lovelace_dashboards/dashboard-01.yaml
  title: Dashboard-01
  icon: mdi:tools
  show_in_sidebar: true
  require_admin: false
```

## Javascript errors shown in your browser console/inspector

```txt

```
