### ISSUE TITLE
0.107.3 Unknown type encountered: media-control

### ISSUE THREAD

**Issue by u8915055** [home-assistant/frontend#5297]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

I have recently upgraded to 0.107.1 and the subsequently to 107.3.  I generally use the custom card called mini-media-player but was trying to change to the new updated media-control card.  For some reason it does not recognize this as a valid card.  I get the message "Unknown type encountered: media-control.'  I do not use the ui-lovelace configurator but rather still use the text-file editing of the ui-lovelace yaml file.  Everything else works fine.  

This is what the section of config looks like that has the media-control element:

#######################
#Kitchen
#######################
```yaml
      - type: entities
        title: Kitchen
        id: kitchen_card
        entities:
          - type: section
            label: Lights       
          - type: 'custom:slider-entity-row'
            name: Main
            entity: light.kitchen_main_lights
            toggle: true
            icon: 'far:ha-recessedlight'
          - type: section
            label: Media Players
          - group: true
            entity: media_player.kitchen_google_hub
            artwork_border: false
            hide:
              power: true
              artwork_border: false
            idle_view:
              when_idle: true
              when_standby: true
              when_paused: true
            artwork: cover
            info: short
            type: 'custom:mini-media-player'
            name: Kitchen Google Hub
            icon: 'far:ha-google-home-hub'
          - entity: media_player.kitchen_sonos
            type: media-control
```
And the message I get in the UI is:

Unknown type encountered: media-control.
entity: media_player.kitchen_sonos
type: media-control

## Expected behavior

I would assume the module would load :)

## Steps to reproduce

I simply changed my ui-lovelace.yaml file to utilize the new control.  I cleared the cache and reloaded.

## Environment

0.107.1 and then upgraded to 0.107.3.  It happened in both.
- Home Assistant release with the issue: 0.107.3 and 0.107.1
- Last working Home Assistant release (if known): unknown, didnt use it before
- Browser and browser version: chrome Version 79.0.3945.130
- Operating system: MAC OSX 10.15.3

#######################
#Kitchen
#######################
```yaml
      - type: entities
        title: Kitchen
        id: kitchen_card
        entities:
          - type: section
            label: Lights       
          - type: 'custom:slider-entity-row'
            name: Main
            entity: light.kitchen_main_lights
            toggle: true
            icon: 'far:ha-recessedlight'
          - type: section
            label: Media Players
          - group: true
            entity: media_player.kitchen_google_hub
            artwork_border: false
            hide:
              power: true
              artwork_border: false
            idle_view:
              when_idle: true
              when_standby: true
              when_paused: true
            artwork: cover
            info: short
            type: 'custom:mini-media-player'
            name: Kitchen Google Hub
            icon: 'far:ha-google-home-hub'
          - entity: media_player.kitchen_sonos
            type: media-control
```
