### ISSUE TITLE
Switch lightning icon not changing color when switch is activated. 

### ISSUE THREAD

**Issue by ristoavila** [home-assistant/frontend#5306]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem
Switch with lightning icon is not changing color when switch is activated. Sliders moves correctly and device is in right state but the lightning icon is not yellow.

For regular bulb icons works correctly and change color based on brightness. 

## Expected behavior

Switch lightning icons are highlighted or not depending the state of the switch.

## Steps to reproduce

Visible after upgrade with any entity with mqtt switch in it.

## Environment
I've tested version 0.1.0.7.x, 0.1.0.6, 1.0.5, and with 0.1.0.4.4 it still works so it got broken when 1.0.5 was updated.
 

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

example ui element
```yaml
entities:
  - entity: light.0x000b57fffe127b7b_light
  - entity: switch.0x7cb03eaa0a025751_switch
  - entity: light.0x7cb03eaa0a05d094_light
  - entity: switch.0x7cb03eaa0a02359f_switch
  - entity: switch.0x00158d000356bbbf_switch
  - entity: light.0x00124b001efe0270_light
show_header_toggle: false
theme: default
title: Sisävalot
type: entities
```

## Javascript errors shown in your browser console/inspector

```txt

```
