### ISSUE TITLE
Custom element doesn't exist: hui-alarm-panel-card.

### ISSUE THREAD

**Issue by RichardUUU** [home-assistant/frontend#5310]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

The alarm control panel has been working fine until the last update.

Now the frontend shows: Custom element doesn't exist: hui-alarm-panel-card.

Here is my YAML:
```
              - type: alarm-panel
                entity: alarm_control_panel.area_001
                states:
                  - arm_away    
                  - arm_home
                  - arm_night

```
The alarm entities are all normal.

## Environment

- Home Assistant release with the issue: 0.107.4
- Last working Home Assistant release (if known): 0.106.x
- Browser and browser version: 80.0.3987.149 (Official Build) (64-bit), also opera, brave
- Operating system: Win 10, android

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
