### ISSUE TITLE
Empty column when using conditional cards

### ISSUE THREAD

**Issue by parkside-codingchallenge** [home-assistant/frontend#5314]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When using conditional cards and/or entity-filter cards and all of them are hidden the first column is empty on desktop browsers. See screenshot. 

![image](https://user-images.githubusercontent.com/62093979/77253958-3a5b2980-6c5e-11ea-8946-f9d360eecf59.png)

![image](https://user-images.githubusercontent.com/62093979/77253945-2d3e3a80-6c5e-11ea-9b1a-d4d4f0e217dd.png)

## Expected behavior
When using conditional cards and/or entity-filter cards the layout should adapt if all cards are hidden - meaning there shouldn't be a big hole in the frontend by having a column not having any content.

## Steps to reproduce

Add conditional cards and entity-filter cards on the top of your view. In my case, I have 1 conditional card, followed by 3 entity-filter cards. Afterward add more cards. If none of the conditional and entity-filter cards are visible the first column is empty. This is only visible on desktop browsers - not on mobile.

## Environment

- Home Assistant release with the issue: 0.107.5
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 80.0.3987.149
- Operating system: MacOS 10.15.3

## Problem-relevant configuration

```yaml
title: Overview
path: overview
icon: mdi:home
badges:
  - entity: person.thomas
    name: Thomas
    image: /local/persons/thomas.jpg
  - entity: person.takwa
    name: Takwa
    image: /local/persons/takwa.jpg

cards:
  - type: conditional
    conditions:
      - entity: calendar.haus
        state: "on"
    card:
      type: markdown
      title: Reminder
      content: |
        {{ states.calendar.haus.attributes.description }}

  - type: entity-filter
    show_empty: false
    entities:
      - light.living_room_couch
      - light.living_room_plants
      - light.kitchen
      - light.kitchen_sink
      - light.kitchen_coffee
      - light.dining_area
      - light.bedroom_main
      - light.bedroom_stripe
      - light.office
      - light.kids_room
      - light.terrace
      - light.cellar_entrance
      - light.cellar_hwr
      - light.cellar_storage
      - light.cellar_fitness
      - light.cellar_werkstatt
    state_filter:
      - "on"
    card:
      title: Active Lights
      show_header_toggle: true

  - type: entity-filter
    show_empty: false
    entities:
      - sensor.entrance_humidity
      - sensor.living_room_humidity
      - sensor.galery_humidity
      - sensor.bathroom_humidity    
      - sensor.bedroom_humidity
    state_filter:
      - operator: ">"
        value: 65
    card:
      title: High Humidity
      show_header_toggle: false

  - type: entity-filter
    show_empty: false
    entities:
      - binary_sensor.entrance_door
      - binary_sensor.bathroom_window
      - binary_sensor.bedroom_window
      - binary_sensor.office_window
      - binary_sensor.eg_restroom_window
      - binary_sensor.dining_room_sliding_door
      - binary_sensor.terrace_door
      - binary_sensor.og_restroom_window
      - binary_sensor.dressing_room_window
      - binary_sensor.kids_room_window
      - binary_sensor.couch_window
      - binary_sensor.kitchen_window
    state_filter:
      - "on"
    card:
      title: Open Windows & Doors
      show_header_toggle: false

  - type: custom:weather-card
    entity: weather.dark_sky

  - type: entities
    show_header_toggle: false
    title: Alarm Clock
    entities: 
      - input_boolean.alarm_clock_status
      - type: custom:fold-entity-row
        head: sensor.alarm_clock_time
        padding: 0
        entities:   
          - input_number.alarm_clock_hour
          - input_number.alarm_clock_minutes
          - input_boolean.alarm_clock_workday

  - type: entities
    title: Most used
    show_header_toggle: false
    entities:
      - entity: light.living_room_couch
        name: Couch Light
      - entity: light.dining_area
        name: Dining Area Light
      - entity: light.kitchen
        name: Kitchen Light
      - entity: cover.living_room_couch
        name: Couch Blinds
      - entity: cover.living_room_plants
        name: Plants Blinds
      - entity: cover.dining_area
        name: Sliding Door Blinds
      - entity: cover.bedroom
        name: Bedroom Blinds

  - type: entities
    title: Information
    show_header_toggle: false
    entities:
      - entity: group.window_sensors
        name: Windows
        icon: mdi:window-closed
      - type: section
      - sensor.living_room_temperature
      - sensor.bedroom_temperature 
      - sensor.average_cellar_temperature 
      - type: custom:auto-entities
        filter:
          include:
            - group: group.temperature_sensors
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Temperatures
      - type: custom:auto-entities
        filter:
          include:
            - group: group.humidity_sensors
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Humidity
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
This seems to have already been reported in earlier versions: https://github.com/home-assistant/frontend/issues/1686
