### ISSUE TITLE
Empty colum when using conditional and entity-filter cards

### ISSUE THREAD

**Issue by friedit** [home-assistant/frontend#5315]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When using conditional cards and/or entity-filter cards and all of them are hidden the first column is empty on desktop browsers. See screenshot. 

![image](https://user-images.githubusercontent.com/1833366/77254037-ca996e80-6c5e-11ea-9258-f42227469ca3.png)
![image](https://user-images.githubusercontent.com/1833366/77254042-d1c07c80-6c5e-11ea-8135-aaf12422b760.png)

## Expected behavior
When using conditional cards and/or entity-filter cards the layout should adapt if all cards are hidden - meaning there shouldn't be a big hole in the frontend by having a column not having any content.

## Steps to reproduce

Add conditional cards and entity-filter cards on the top of your view. In my case, I have 1 conditional card, followed by 3 entity-filter cards. Afterward add more cards. If none of the conditional and entity-filter cards are visible the first column is empty. This is only visible on desktop browsers - not on mobile.

## Environment

- Home Assistant release with the issue: 0.107.5
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 80.0.3987.149
- Operating system: MacOS 10.15.3

## Problem-relevant configuration

```yaml
title: Overview
path: overview
icon: mdi:home
badges:
  - entity: person.thomas
    name: Thomas
    image: /local/persons/thomas.jpg
  - entity: person.takwa
    name: Takwa
    image: /local/persons/takwa.jpg

cards:
  - type: conditional
    conditions:
      - entity: calendar.haus
        state: "on"
    card:
      type: markdown
      title: Reminder
      content: |
        {{ states.calendar.haus.attributes.description }}

  - type: entity-filter
    show_empty: false
    entities:
      - light.living_room_couch
      - light.living_room_plants
      - light.kitchen
      - light.kitchen_sink
      - light.kitchen_coffee
      - light.dining_area
      - light.bedroom_main
      - light.bedroom_stripe
      - light.office
      - light.kids_room
      - light.terrace
      - light.cellar_entrance
      - light.cellar_hwr
      - light.cellar_storage
      - light.cellar_fitness
      - light.cellar_werkstatt
    state_filter:
      - "on"
    card:
      title: Active Lights
      show_header_toggle: true

  - type: entity-filter
    show_empty: false
    entities:
      - sensor.entrance_humidity
      - sensor.living_room_humidity
      - sensor.galery_humidity
      - sensor.bathroom_humidity    
      - sensor.bedroom_humidity
    state_filter:
      - operator: ">"
        value: 65
    card:
      title: High Humidity
      show_header_toggle: false

  - type: entity-filter
    show_empty: false
    entities:
      - binary_sensor.entrance_door
      - binary_sensor.bathroom_window
      - binary_sensor.bedroom_window
      - binary_sensor.office_window
      - binary_sensor.eg_restroom_window
      - binary_sensor.dining_room_sliding_door
      - binary_sensor.terrace_door
      - binary_sensor.og_restroom_window
      - binary_sensor.dressing_room_window
      - binary_sensor.kids_room_window
      - binary_sensor.couch_window
      - binary_sensor.kitchen_window
    state_filter:
      - "on"
    card:
      title: Open Windows & Doors
      show_header_toggle: false

  - type: custom:weather-card
    entity: weather.dark_sky

  - type: entities
    show_header_toggle: false
    title: Alarm Clock
    entities: 
      - input_boolean.alarm_clock_status
      - type: custom:fold-entity-row
        head: sensor.alarm_clock_time
        padding: 0
        entities:   
          - input_number.alarm_clock_hour
          - input_number.alarm_clock_minutes
          - input_boolean.alarm_clock_workday

  - type: entities
    title: Most used
    show_header_toggle: false
    entities:
      - entity: light.living_room_couch
        name: Couch Light
      - entity: light.dining_area
        name: Dining Area Light
      - entity: light.kitchen
        name: Kitchen Light
      - entity: cover.living_room_couch
        name: Couch Blinds
      - entity: cover.living_room_plants
        name: Plants Blinds
      - entity: cover.dining_area
        name: Sliding Door Blinds
      - entity: cover.bedroom
        name: Bedroom Blinds

  - type: entities
    title: Information
    show_header_toggle: false
    entities:
      - entity: group.window_sensors
        name: Windows
        icon: mdi:window-closed
      - type: section
      - sensor.living_room_temperature
      - sensor.bedroom_temperature 
      - sensor.average_cellar_temperature 
      - type: custom:auto-entities
        filter:
          include:
            - group: group.temperature_sensors
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Temperatures
      - type: custom:auto-entities
        filter:
          include:
            - group: group.humidity_sensors
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: Humidity
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
This seems to have already been reported in earlier versions: https://github.com/home-assistant/frontend/issues/1686

**Comment by szimszon** [comment]
Hi,

I have the same issue with conditional and entity filter cards in Frontend version: 20200407.2 - latest .

**Comment by boesing** [comment]
Still an issue with `20200519.4`.
Sometimes it works, sometimes not. 
If you toggle edit-mode on/off, some cards jump around and fill the empty columns but thats not the case on hard-reload or initial request.

**Comment by thehaxxa** [comment]
Still experiencing this on 0.112.2, acts if the card existed in place.

**Comment by s-hutter** [comment]
Issue is still present in 0.115.6.

**Comment by vertex29** [comment]
Issue is still present in 2021.1.0

**Comment by boesing** [comment]
Issue still ignored.

**Comment by gazpachoking** [comment]
This is still an issue with the latest version.

**Comment by guilhermebera** [comment]
This issue persists in the latest version.

**Comment by Olum-hack** [comment]
I think this issue still exists.
I'm using Home Assistant Core 2022.5.2 and have the same.

**Comment by szimszon** [comment]
On 2022.8.4 the issue is still there. ;(

**Comment by jhansche** [comment]
Disclaimer: it's been over ~10+ years since my html/js/css days. In fact, shadow roots and custom dom elements did not exist when I last touched web.

Through some experimentation, I was able to apply a css style that appears to work, in my limited tests (in Chrome):

```js
var colStyles = document.createElement("style");
colStyles.innerHTML = "#columns .column:not(:has(>*:not([hidden]))) { flex-grow: 0; }\n";
document.querySelector('home-assistant').shadowRoot
    .querySelector("home-assistant-main").shadowRoot
    .querySelector("ha-panel-lovelace").shadowRoot
    .querySelector("hui-root").shadowRoot
    .querySelector("hui-masonry-view").shadowRoot
    .appendChild(colStyles);
```

I _think_ we could add a `patch/hui-masonry-view.ts` in [card-mod](https://github.com/thomasloven/lovelace-card-mod/) to accomplish this.

Or I think we can just make the change [here](https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/views/hui-masonry-view.ts#L296), in `static get styles()`:
```css
.column:not(:has(>*:not([hidden]))) {
  flex-grow: 0;
}
```

The breakdown of the selectors:
1. `div.column` - this is the element that makes up each column in the view
2. `>*:not([hidden])` - selects "direct child elements that do not contain a 'hidden' attribute" => in other words "any non-hidden elements, aka any visible element"
3. `.column:not(:has(...))` - "columns that do not contain those^" => in other words: columns that do not contain any non-hidden (aka visible) cards

We can then override the default `.column { flex }` style, by setting `flex-grow: 0`, which causes that column to collapse.

Unfortunately this won't work just by dropping in a Lovelace stylesheet resource, so it really can only be done by patching the custom element as in card-mod, or by fixing the styles in frontend. And another option would be a custom javascript resource that does the DOM traversal like above.

Note that there is _not_ 100% support for these selectors:
* https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility - Firefox does _not_ support the `:has()` selector
* https://developer.mozilla.org/en-US/docs/Web/CSS/:not#browser_compatibility - this looks okay, because opera android only does not support a list selector (and we're not using a list here)

Also note that this only works if the element is explicitly hidden (by setting `element.hidden = true`, or html `<hui-conditional-card hidden>`). In other words, it will not work to test visibility of an element that is hidden by any other means (like a .hidden class or other css rule that hides it).
