### ISSUE TITLE
No current value displayed if input_number (slider) is part of a conditional row

### ISSUE THREAD

**Issue by akasma74** [home-assistant/frontend#5332]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
When `input_number` (with `mode: slider`) is part of a conditional row, it's displayed without value, only a slider.
![Screen Shot 2020-03-24 at 18 42 08 (2)](https://user-images.githubusercontent.com/13675855/77464756-8ee9da80-6dff-11ea-9616-aa9bf2c53fbe.png)

## Expected behavior
It should behave exacly as a normal entity row and display slider *and* current value.

## Environment

- Home Assistant release with the issue: 0.107.5
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Google Chrome 80.0.3987.149 (Official Build) (64-bit)
- Operating system: OS X 10.11.6

## Problem-relevant configuration

```yaml
type: entities
entities:
  - entity: automation.ventilation_1st_floor_bathroom_extractor_fan_turn_on_by_humdity_threshold
    name: humidity value

  - type: conditional
    conditions:
      - entity: automation.ventilation_1st_floor_bathroom_extractor_fan_turn_on_by_humdity_threshold
        state: 'on'
    row:
      entity: input_number.ventilation_1st_floor_bathroom_shower_humidity_threshold
      name: above
```

## Javascript errors shown in your browser console/inspector

```txt

```
