### ISSUE TITLE
Lovelace switches overview and my dashboard icon and url

### ISSUE THREAD

**Issue by klejejs** [home-assistant/frontend#5377]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
I have setup one dashboard in lovelace (see code below) but currently that dashboard has "lovelace" link and auto-generated dashboard icon and my auto-generated overview dashboard has "lovelace-main" url and "mdi:monitor-dashboard" icon (see config below).

## Steps to reproduce
1. Enter config in configuration.yaml
2. Restart home assistant core

## Environment

- Home Assistant release with the issue: 0.107.7
- Last working Home Assistant release (if known): -
- Browser and browser version: Chrome, latest, checked on Firefox too
- Operating system: Windows 10, HA Core running on docker

## Problem-relevant configuration

```yaml
  dashboards:
    lovelace-main:
      mode: yaml
      title: Dashboard
      icon: mdi:monitor-dashboard
      filename: ui-lovalace.yaml
      show_in_sidebar: true
      require_admin: false
```

## Javascript errors shown in your browser console/inspector

```txt

```
