### ISSUE TITLE
Entities page - input helpers no longer showing read only status icons

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5411]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

It seems that all input_* entities (boolean, select, number, datetime, text - basically everything that can be created under Configuration -> Helpers) are no longer displaying the "read only" status icon. 

Most of mine are created in YAML and are non-editable, yet they lack the crossed out pencil icons in 0.108.0b0. So you cannot tell the difference currently between YAML or UI created ones.

## Expected behavior

Show the crossed out pencil icon for YAML to indicate it's read-only / not editable.

## Steps to reproduce

Go to Entities panel, look at column for entities created via YAML.

## Environment

- Home Assistant release with the issue: 0.108.0b0
- Last working Home Assistant release (if known): 0.107.7
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

A few examples of YAML created entities:

```yaml
input_boolean:
  enable_security:
    name: Alarm Enabled
    icon: mdi:security

input_number:
  alarm_siren_volume:
    name: Siren Volume
    icon: mdi:volume-high
    # initial: 0
    min: 0
    max: 1
    step: 0.05
    unit_of_measurement: '%'

input_text:
  car_remote_start_pin_ford_fusion:
    name: Ford Remote Start PIN
    icon: mdi:dialpad
    mode: password


```

## Javascript errors shown in your browser console/inspector

```txt

```
