### ISSUE TITLE
Code editors switch back to visual editor after just one keystroke

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5413]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

While trying to reproduce a different bug, I noticed that the code editors for ~~stack cards~~ ALL cards immediately switch back to visual editor after just one single keystroke.

## Steps to reproduce

1. Configure UI > Add any card
2. Switch from Visual to Code editor
3. Try to edit any code - either type a character or try to delete a character
4. Any keypress will switch you back to the visual editor

## Environment

- Home Assistant release with the issue: 0.108.0b0
- Last working Home Assistant release (if known): 0.107.7
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml
type: horizontal-stack
cards:
  - type: button
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    show_icon: true
    show_name: true 
    entity: light.kitchen_lights
 
```

## Javascript errors shown in your browser console/inspector

```txt

```
