### ISSUE TITLE
state_filter doesn't work.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/frontend#5434]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

State filter does not appear to work.  This was only tried with device_tracker.xxx and person.xxx.  'home', home, 'not_home', and not_home do not work.  I tried applying other CSS filters and pretty much everything failed.  This was tried in both picture-entity and picture-glance cards.

```
state_filter:
  home: greyscale(100%)
  not_home: greyscale(100%)
  'home': greyscale(100%)
  'not_home': greyscale(100%)
```

Aside from the above configuration, I tried the css listed in the docs.  THose also did not work.  The current state of the person and device_tracker at the time of testing was 'home'.

## Expected behavior

I expect the above configuration to make the image 100% greyscale at any of the listed states.  It does not.

## Steps to reproduce

You can try this one on the demo website:
```
type: picture-glance
title: Kitchen
image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
entities:
  - sensor.livingroom_temp_rounded
  - binary_sensor.motion_sensor_158d00016daecc
aspect_ratio: 0%
entity: person.arsaboo
state_filter:
  not_home: grescale(100%)
```

## Environment
doesn't matter, use the demo site.

- Home Assistant release with the issue: 106.5, 107.7, or whatever is on the demo site.
- Last working Home Assistant release (if known): Not known
- Browser and browser version: Chrome
- Operating system: Windows

## Problem-relevant configuration
See above

```yaml

```

## Javascript errors shown in your browser console/inspector
no errors

```txt

```

**Comment by zsarnett** [comment]
```yaml
type: picture-glance
title: Kitchen
image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
entities:
  - sensor.livingroom_temp_rounded
  - binary_sensor.motion_sensor_158d00016daecc
aspect_ratio: 0%
entity: person.arsaboo
state_filter:
  not_home: grayscale(80%)
```

Works fine for me :)

I believe you spelled it wrong. Use the a version of gray
