### ISSUE TITLE
Unable to load dashboards not on root

### ISSUE THREAD

**Issue by nitobuendia** [home-assistant/frontend#5456]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

`filename` within `dashboards` within lovelace is unable to load files not on /config/ folder. Instead, loads dashboard with all entities (storage mode?).

## Expected behavior

`filename` within `dashboards` within lovelace should load files on subfolders.

## Steps to reproduce

1) Create a dashboard.yaml file on `/config/` and `/config/lovelace/`. Any content would do. Example `dashboard.yaml`

```yaml
title: Dashboard
views:
    # View tab title.
  - title: Example
    cards:
        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
```

2) Change your `configuration.yaml` to the one of the following.

This one works:

```yaml
dashboards:
  quantified-self:
    mode: yaml
    title: Quantified Self
    icon: "mdi:home-analytics"
    filename: dashboard.yaml
    show_in_sidebar: true
```

This one does not work:

```yaml
dashboards:
  quantified-self:
    mode: yaml
    title: Quantified Self
    icon: "mdi:home-analytics"
    filename: lovelace/dashboard.yaml
    show_in_sidebar: true
```

I would love to be able to place my configurations in any folder.

## Environment

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.106-v7
python_version | 3.7.7
timezone | Asia/Singapore
version | 0.107.7
virtualenv | false

- Home Assistant release with the issue: 0.107.7
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Not relevant, but Chrome 80.0.3987.149
- Operating system: Not relevant

## Problem-relevant configuration

```yaml
dashboards:
  quantified-self:
    mode: yaml
    title: Quantified Self
    icon: "mdi:home-analytics"
    filename: lovelace/dashboard.yaml
    show_in_sidebar: true
```

`filename` does not load the right file.

## Javascript errors shown in your browser console/inspector

No errors. Instead, it shows the default configuration with all the entities.

**Comment by kaijk** [comment]
Note that in the "Lovelace Dasboards" under "Configuration" the "Filename" you enter as "lovelace/dashboard.yaml" will display as "lovelacedashboard.yaml."  The "/" is stripped out leaving an unknown file-spec.
Here is a workaround until a fix is available:
1. Specify filename: dashboard.yaml in your dashboards list
```
dashboards:
  quantified-self:
    mode: yaml
    title: Quantified Self
    icon: "mdi:home-analytics"
    filename: dashboard.yaml
    show_in_sidebar: true
```
2. Create a dashboard.yaml file in /config with a single line: !include: lovelace/dashboard.yaml
3. Put your real dashboard.yaml file in /config/lovelace directory as you (and I) desire.
4. Your lovelace/dashboard.yaml file will be used.
