### ISSUE TITLE
panel support for home assistant cast

### ISSUE THREAD

**Issue by jtonk** [home-assistant/frontend#5470]
# Checklist 

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

when casting a lovelace url with 
```yaml
panel: true
```

I only see a white screen. In normal browsers it works as expected. I'd like to be able to show one big picture-elements card on the cast.

## Expected behavior

expected to see the first card of the view in panel mode on the cast.

## Steps to reproduce

1. set the panel parameter to true for a view in ui-lovelace.yaml
2. cast view to google nest hub

## Environment

- HA 107.7 (ubuntu/docker)
- frontend 20200318.1 - latest
However never tried it before, so not sure if the feature was supported in previous versions

## Problem-relevant configuration

```yaml
  - title: testing
    path: testing
    panel: true
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.home_alarm
```

## Javascript errors shown in your browser console/inspector

```txt
not sure how to view log of the nest_hub
```
