### ISSUE TITLE
State filter "!=" doesn't work with strings

### ISSUE THREAD

**Issue by inputd** [home-assistant/frontend#5480]
## The problem

When using the state filter and the operator "!=", nothing is filtered.

## Expected behavior

!= should filter out everything except the value

## Steps to reproduce
```yaml
        type: entity-filter
        show_empty: false
        state_filter:
        - value: home
        - operator: "!="
        entities:
          - person.me
          - person.you
          - device_tracker.33_ff_32
        card:
          type: glance
          title: Who's away?
          show_name: false
          show_state: true
```
## Environment

- Home Assistant release with the issue: 0.107.7
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 80.0.3987.149
- Operating system: W10

## Additional information

I've tried home, Home, "home" and "Home" as values with the same result. With the pasted config, if I change != to ==, it will successfully filter for only devices that are home.

**Comment by bramkragten** [comment]
Change your config from:
```yaml
        state_filter:
        - value: home
        - operator: "!="
```
to:
```yaml
        state_filter:
        - value: home
          operator: "!="
```
