### ISSUE TITLE
Scene Editor does not properly show 'Entities' entries on subsequent edits.

### ISSUE THREAD

**Issue by linuxkidd** [home-assistant/frontend#5519]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When attempting to edit a Scene which previously only had 'Entities' entries ( not 'Devices' entries ), the editor now shows the full parent Device with all Entities under it, instead of only the previously selected 'Entities' entries.

## Expected behavior
Scene editor should display the 'Entity' entries only on subsequent edits.

## Steps to reproduce
1. Ensure 'Advanced Mode' is enabled for your profile
2. Create a new Scene
3. Under 'Entities', add a few entities (my use case has 'Entities' entries from one Device, but not all entities offered by the Device)
4. Save the Scene
5. Return to the 'Scenes' list
6. Click the 'Edit' pencil for the Scene
7. Note the 'Devices' section is now populated with the parent device and all entities, but the 'Entities' section is blank.
8. Confirm the 'scenes.xml' shows only the previously populated 'Entities'

## Environment
- Home Assistant release with the issue: 0.108.1 through 0.108.3
- Last working Home Assistant release (if known): 0.107.x
- Browser and browser version: Tested with Chrome 81.x and Firefox 75.0
- Operating system: Tested in browsers on Ubuntu 20.04 and Windows 10

## Problem-relevant configuration
Entities and parent device are using MQTT Auto-Discovery, have not tested with other integrations.

sample scene.xml
```
- id: '1578889588482'
  name: Bedroom Off
  entities:
    light.bedroom_ceiling:
      friendly_name: Bedroom Ceiling
      state: 'off'
      supported_features: 1
    light.bedroom_reading:
      friendly_name: Bedroom Reading
      state: 'off'
      supported_features: 1
    light.bedroom_sconce:
      friendly_name: Bedroom Sconce
      state: 'off'
      supported_features: 1
```

## Javascript errors shown in your browser console/inspector
n/a

## Additional information
May have been present in 0.108.0, but did not test there.
