### ISSUE TITLE
Tibber problem after 108 update: "sensor.real_time_consumption_none non numeric"

### ISSUE THREAD

**Issue by cortado** [home-assistant/frontend#5530]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Tibber real time consumption is not showing in gauge card or on badge after 108 update (108.1-3):

Error message:
"Enitity is non numeric: sensor.real_time_consumption_none"

Cannot get "average power" (the realtime consumption), all other data from Tibber displays as normal in UI.

## Expected behavior

Has been working like a charm since 098.4 (when I began with Hass)

## Steps to reproduce

1. Add Tibber integration
2. Add Sensor remplates
3. Add sensor "sensor.real_time_consumption_none" and "sensor.electricity_price_none" to badge and guage card.
4. observe error message of non numeric for "sensor.real_time_consumption_none"

## Environment

- Home Assistant release with the issue: 108.1-3
- Last working Home Assistant release (if known): 107.7
- Browser and browser version: Safari 13.1/Safari iOS 13.4 and Chrome 80.0.3987.163
- Operating system: MacOS and iOS

## Problem-relevant configuration

```yaml
platform: template
sensors:
  tibber_nett:
    friendly_name: "Nett Eier"
    value_template: "{{ state_attr('sensor.electricity_price_none', 'grid_company') }}"
    icon_template: mdi:fuse
  tibber_max:
    friendly_name: "Max pris"
    unit_of_measurement: "NOK/kWh"
    value_template: "{{ state_attr('sensor.electricity_price_none', 'max_price') }}"
    icon_template: mdi:currency-usd
  tibber_avg:
    friendly_name: "Gjennomsnittspris"
    unit_of_measurement: "NOK/kWh"
    value_template: "{{ state_attr('sensor.electricity_price_none', 'avg_price') }}"
    icon_template: mdi:currency-usd
  tibber_min:
    friendly_name: "Minimumspris"
    unit_of_measurement: "NOK/kWh"
    value_template: "{{ state_attr('sensor.electricity_price_none', 'min_price') }}"
    icon_template: mdi:currency-usd
  tibber_estimert:
    unit_of_measurement: 'kWh'
    friendly_name: "Estimert forbruk"
    value_template: "{{ state_attr('sensor.electricity_price_none', 'estimated_annual_consumption') }}"
    icon_template: mdi:power-plug
  tibber_time:
    friendly_name: "Sist oppdatert"
    value_template: "{{ state_attr('sensor.real_time_consumption_none', 'timestamp') }}"
    icon_template: mdi:clock-outline
  tibber_minpower:
    friendly_name: "Laveste forbruk"
    unit_of_measurement: "W"
    value_template: "{{ state_attr('sensor.real_time_consumption_none', 'minPower') }}"
    icon_template: mdi:power-plug
  tibber_averagepower:
    friendly_name: "Gjennomsnitts forbruk"
    unit_of_measurement: "W"
    value_template: "{{ state_attr('sensor.real_time_consumption_none', 'averagePower') }}"
    icon_template: mdi:power-plug
  tibber_maxpower:
    friendly_name: "Høyeste forbruk"
    unit_of_measurement: "W"
    value_template: "{{ state_attr('sensor.real_time_consumption_none', 'maxPower') }}"
    icon_template: mdi:power-plug
  tibber_accumulatedconsumption:
    friendly_name: "Forbruk i dag"
    unit_of_measurement: 'kWh'
    value_template: "{{ state_attr('sensor.real_time_consumption_none', 'accumulatedConsumption') }}"
    icon_template: mdi:power-plug
  tibber_accumulatedcost:
    friendly_name: "Kostnad i dag"
    unit_of_measurement: 'Kr'
    value_template: "{{ state_attr('sensor.real_time_consumption_none', 'accumulatedCost') }}"
    icon_template: mdi:currency-usd
  tibber_volt:
    friendly_name: "Spenning"
    unit_of_measurement: 'V'
    value_template: "{{ state_attr('sensor.real_time_consumption_none', 'voltagePhase1') }}"
    icon_template: mdi:flash
  tibber_amp:
    friendly_name: "Strøm"
    unit_of_measurement: 'A'
    value_template: "{{ state_attr('sensor.real_time_consumption_none', 'currentPhase1') }}"
    icon_template: mdi:current-ac
```

## Javascript errors shown in your browser console/inspector

```txt

```
