### ISSUE TITLE
markdown card inside stack cards as a part of conditional card generates errors

### ISSUE THREAD

**Issue by akasma74** [home-assistant/frontend#5532]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

When `markdown` card is used inside `vertical-stack` or `horizontal-stack` and that stack card is in `card` section of a `conditional` card, in JS console I can see the following errors:

> ERROR (MainThread) [frontend.js.latest.202003181] http://hassio.local:8123/frontend_latest/chunk.ea4a842548b68b236f48.js:795:320 Uncaught TypeError: Cannot read property 'replaceChild' of null

## Expected behavior
There should be no errors.

## Environment

- Home Assistant release with the issue:0.107.7
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 81.0.4044.92 (Official Build) (64-bit)
- Operating system: OS X 10.11.6

## Problem-relevant configuration

```yaml
# generates ERROR (MainThread) [frontend.js.latest.202003181] http://hassio.local:8123/frontend_latest/chunk.ea4a842548b68b236f48.js:795:320 Uncaught TypeError: Cannot read property 'replaceChild' of null

type: conditional
conditions:
  - entity: input_boolean.alarm_detected_open_sensors
    state: 'on'
card:
  type: vertical-stack
  cards:
    - type: markdown
      content: test

# no errors
type: conditional
conditions:
  - entity: input_boolean.alarm_detected_open_sensors
    state: 'on'
card:
  type: vertical-stack
  cards:
    - type: entities
      entities:
        - entity: input_boolean.alarm_detected_open_sensors

# no error
type: conditional
conditions:
  - entity: input_boolean.alarm_detected_open_sensors
    state: 'on'
card:
  type: markdown
  content: test

# no errors
type: vertical-stack
cards:
  - type: markdown
    content: test
```

## Javascript errors shown in your browser console/inspector

```txt
ERROR (MainThread) [frontend.js.latest.202003181] http://hassio.local:8123/frontend_latest/chunk.ea4a842548b68b236f48.js:795:320 Uncaught TypeError: Cannot read property 'replaceChild' of null

```
