### ISSUE TITLE
Automation Editor not loading data_template correct

### ISSUE THREAD

**Issue by skycryer** [home-assistant/frontend#5541]
Automation Editor is not showing automations with data_template correct. It shows empty action if action uses data_tempalte. Service is visible but not service data.

Home Assistant 0.108.3

- Home Assistant Core release with the issue: 0.108.3
- Last working Home Assistant Core release (if known): Never
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml
- id: 85c27f449d4ac159fb2e97d0f360b85e
  alias: Wenn maxtemp geändert wird heizung Bathroom hoch drehen (Bathroom Temperature
    Control)
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_number.bathroom_temp_max
  condition:
  - condition: template
    value_template: '{{ states.input_number.bathroom_temp_max.state | int > states.sensor.bathroom_multi_sensor_temperature.state
      | int }}'
  - condition: state
    entity_id: sensor.someone_home
    state: 'true'
  - condition: state
    entity_id: input_boolean.sleepmode
    state: 'off'
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.bathroom_heating_heating_1
      temperature: 28

```

## Traceback/Error logs

```txt

```

## Additional information
Seems to be fixed for conditions in home-assistant/core#1601 but here the problem in in Actions.
