### ISSUE TITLE
Automation/Script Editor break delay

### ISSUE THREAD

**Issue by skycryer** [home-assistant/frontend#5542]
## The problem
I moved my scripts into scripts.yaml to use script editor, same for automations. If I now try to edit the script/automation the delay data got loaded as [object Object] so I am not able to edit it. And saving break the script/automation because it also get written into files as [object Object]. 

## Environment
Home Assistant 0.108.3

- Home Assistant Core release with the issue: 0.108.3
- Last working Home Assistant Core release (if known): Never
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `scripts.yaml`

```yaml
bedroom_underground_light_off:
  alias: Schalte Untergrund Bett Beleuchtung nach 30 Sekunden aus
  sequence:
  - delay:
      seconds: 30
  - service: switch.turn_off
    data:
      entity_id: switch.bedroom_bed_light_switch

```

## Traceback/Error logs

```txt

```
