### ISSUE TITLE
Script Editor fail saving if script uses !include 

### ISSUE THREAD

**Issue by skycryer** [home-assistant/frontend#5543]
## The problem
I moved all my scripts to new scripts.yaml to use script editor from Home Assistant. While working on some script i had a problem saving my changes. While testing I found out that script using !include make the problem. After removing the scripts it was fine. But as I am able to use that in yaml I should be able to use that in script editor also,.

## Environment
Home Assistant 0.108.3

- Home Assistant Core release with the issue: 0.108.3
- Last working Home Assistant Core release (if known): Never
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `scripts.yaml`

```yaml
alexa_say_no_in_living:
  sequence:
    - service: notify.alexa_media_wohnzimmer
      data_template:
        message: !include alexa_deny.yaml
        data: {"type": "tts"}

```

## Traceback/Error logs

```txt

```
