### ISSUE TITLE
Script Editor not loading Script names when editing

### ISSUE THREAD

**Issue by skycryer** [home-assistant/frontend#5544]
## The problem
If editing a script the name field is not populated if script has not been created with script editor. Automation Editor loads names even if not created in Automation editor. Script editor should load the name even if not created in editor to prevent problems with names of scripts.

## Environment
Home Assistant 0.108.3

- Home Assistant Core release with the issue: 0.108.3
- Last working Home Assistant Core release (if known): Never
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `scripts.yaml`
```yaml
start_bathroom_occupied_timer:
  alias: Start Bathroom Occupied Timer
  sequence:
  - delay:
      minutes: 15
  - service: input_boolean.turn_off
    entity_id: input_boolean.bathroom_occupied
  - service: switch.turn_off
    entity_id: switch.bathroom_main_light_switch

```

## Traceback/Error logs

```txt

```
