### ISSUE TITLE
Automations UI: Can't select entity in actions

### ISSUE THREAD

**Issue by rgruyters** [home-assistant/frontend#5570]
## The problem

When creating an automation via UI, I can't set the entity in actions. (see short film)

https://robin.grtrs.nl/s/DXVal3oN8w2aVxc

## Environment

```yaml
   -  homeassistant:
          version: 0.108.6
          dev: false
          hassio: true
          virtualenv: false
          python_version: 3.7.7
          docker: true
          arch: armv7l
          timezone: Europe/Amsterdam
          os_name: Linux
          os_version: 4.19.114-v7
      lovelace:
          dashboards: 2
          mode: storage
          views: 7
          resources: 8
```

- Home Assistant Core release with the issue:  0.107.0
- Last working Home Assistant Core release (if known): 
- Operating environment (Home Assistant/Supervised/Docker/venv):  Home Assistant
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml
automation:
```

## Traceback/Error logs
N/A
