### ISSUE TITLE
Translations: required key not provided @ data['category']

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/frontend#5601]
## The problem

Getting an unidentified log error

## Environment

- Home Assistant Core release with the issue: 0.109.0b0
- Last working Home Assistant Core release (if known): 0.108.x
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```
Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.140244295007440
Source: components/websocket_api/connection.py:97
Integration: Home Asssitant WebSocket API (documentation, issues)
First occurred: 9:29:33 AM (1 occurrences)
Last logged: 9:29:33 AM

Error handling message: required key not provided @ data['category']. Got None

```

**Comment by SeanPM5** [comment]
I noticed this yesterday too, log error didn't happen before 0.109. 

I suspect this might come from the iOS Mobile App actionable notifications as it uses a kinda similar format:

```
automation:
  - alias: Notify Mobile app
    trigger:
      ...
    action:
      service: notify.mobile_app_<your_device_id_here>
      data:
        title: "Check this out!"
        message: "Something happened at home!"
        data:
          push:
            category: "alarm"
```
