### ISSUE TITLE
horizontal stack is still misaligned.

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/frontend#5628]
## Environment

- Home Assistant Core release with the issue: 0.108.9
- Last working Home Assistant Core release (if known): never
- Operating environment (Home Assistant/Supervised/Docker/venv): hassio
- Integration causing this issue: ?
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

This is the config:

```yaml
cards:
  - cards:
      - entity: switch.solar_station
        hold_action:
          action: more-info
        icon_height: 36px
        show_icon: true
        show_name: true
        state_color: true
        type: entity-button
      - entities:
          - sensor.solar_station_remaining_seconds
        show_icon: false
        show_name: true
        show_state: true
        type: glance
      - entity: switch.water_pump_power
        hold_action:
          action: more-info
        icon_height: 36px
        show_icon: true
        show_name: true
        state_color: true
        type: entity-button
    type: horizontal-stack
type: vertical-stack

```

## Additional information

![misalignment](https://user-images.githubusercontent.com/4722227/80287793-a506f580-8733-11ea-922b-66d1e5770ed3.JPG)

Isn't this kind of misalignment fixed in the 0.108.x version?
