### ISSUE TITLE
Entity card shows duplicate unit of measurement

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5630]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Using Entity card for first time after Zack's [forum post](https://community.home-assistant.io/t/my-mobile-dashboard-pure-core-lovelace/189671) gave me some ideas/inspiration. It seems that on 0.109 whenever an entity has a unit of measurement the entity card will display that twice (see the "Percentage" card in top right of this pic):

![image](https://i.imgur.com/iAT7AkV.png)

## Expected behavior

The example on the [Entity Card docs](https://www.home-assistant.io/lovelace/entity/) shows how it's expected to look:

![image](https://www.home-assistant.io/images/lovelace/lovelace_entity_card.png)

## Environment

- Home Assistant release with the issue: 0.109.0b0
- Last working Home Assistant release (if known): ??
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml
    - type: horizontal-stack
      cards:
        - entity: sensor.time_driving_today
          name: Drove Today
          type: entity

        - entity: sensor.percentage_driven_today
          name: Percentage
          type: entity

    - type: horizontal-stack
      cards:

        - entity: counter.car_trips
          type: entity
          name: Trips This Week

        - entity: counter.car_hard_brake_events
          type: entity
          name: Hard Brakes

    - type: horizontal-stack
      cards:
        - entity: counter.car_hard_accel_events
          type: entity
          name: Rapid Accels

        - entity: counter.car_speeding_events
          type: entity
          name: Speeding
```

## Javascript errors shown in your browser console/inspector

```txt

```
