### ISSUE TITLE
Broken Image if entity is unavailable - Picture Elements

### ISSUE THREAD

**Issue by coolriku** [home-assistant/frontend#5645]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The problem rises when an image element goes unavailable, than you'll get an broken image icon in the middle of the main image.

## Expected behavior
In my opinion there has to be an state 'unavailable' option in the state config, or process this type as state 'off' so you won't get the broken image, that will block most of the main image(floorplan)

## Steps to reproduce
add an image element with the state_image option

```yaml
- entity: light.philips_hue_color_1
    hold_action: none
    state_image:
      'off': /local/floorplan/transparant_pixel.png
      'on': /local/floorplan/.....png
    style:
      left: 50%
      top: 50%
      width: 100%
    tap_action: none
    type: image

```

![Image of Picture Elements](https://i.imgur.com/rVQaTBL.png)

## Environment

- Home Assistant release with the issue: 0.108.8
- Last working Home Assistant release (if known): 
- Browser and browser version: Latest chrome / Firefox / Chrome mobile (android)
- Operating system: Windows 10 / Android 10

## Problem-relevant configuration

```yaml

elements:
  - entity: light.philips_hue_color_1
    hold_action: none
    state_image:
      'off': /local/floorplan/transparant_pixel.png
      'on': /local/floorplan/......png
    style:
      left: 50%
      top: 50%
      width: 100%
    tap_action: none
    type: image
image: /local/floorplan/....png
type: picture-elements


```

## Javascript errors shown in your browser console/inspector

```txt

```
