### ISSUE TITLE
Weather Card: NWS Integration Weather Forecast not properly displayed

### ISSUE THREAD

**Issue by droans** [home-assistant/frontend#5651]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

NWS reports daytime high/nighttime low as two separate objects. The weather card keeps these separate instead of merging the high and low under a single day.

## Expected behavior

Weather card should show the high and low for each day instead of separating it out. See image below. Top is Darksky, bottom is NWS.

![image](https://user-images.githubusercontent.com/49721649/80508186-b7f11400-8945-11ea-8dd8-1cea04d5f8a0.png)

## Steps to reproduce

Add NWS Weather integration. Add weather card to frontend using the NWS Weather Inegration.

## Environment

- Home Assistant release with the issue: 0.108.9
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Chrome 81 64-bit
- Operating system: Windows 10

## Problem-relevant configuration

```
sensor:
  - platform: nws
    api_key: !secret nws_api_key
    latitude: !secret latitude
    longitude: !secret longitude
    name: NWS Weather

```

## Javascript errors shown in your browser console/inspector

No Javascript errors.

```txt

```
