### ISSUE TITLE
New weather card switches between modes on view change

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/frontend#5656]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The new weather card switches between modes (PC, Mobile, according to the window size, i think?) on changing to another view.
![weather-card-issue](https://user-images.githubusercontent.com/26381449/80572263-3e692c80-89fe-11ea-9945-d4a125286d6f.gif)

## Expected behavior
Mode should be consistent.

## Steps to reproduce
1. Open a view with the weather-card
2. Go to another view and back to the view with the weather-card
3. Card shows only 3 instead of 5 icons in the forecast
4. Wait a minute or so, card shows 5 icons again.

## Environment

- Home Assistant release with the issue: 0.109.0b5
- Last working Home Assistant release (if known):
- Browser and browser version: Latest Firefox and Chrome
- Operating system: Ubuntu 18.04

## Problem-relevant configuration

```yaml
  - title: Wetter
    path: wetter
    icon: mdi:weather-partly-cloudy
    #icon: mdi:numeric-1-circle
    #badges: *view-badges
    cards:

      - type: vertical-stack
        cards:

          - type: weather-forecast
            entity: weather.dark_sky
```

## Javascript errors shown in your browser console/inspector

Seeing this only on views with the weather-card
```txt
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. embed2.html
```
