### ISSUE TITLE
Impossible to use a Tuya cover (smart life) in a card.

### ISSUE THREAD

**Issue by sidwin9** [home-assistant/frontend#5664]
## The request
  My cover Smart Life is no longer usable in a map, the states do not update and the open and close buttons cannot be used since the update to version 0.109.0.
This problem is caused by the fact that when my switch turns off the power a few seconds after an action, the state changes to unknown. Another problem, if I press Stop, I no longer have the 2 possibilities to go up or down, I only have one possibility, up or down.
![image](https://user-images.githubusercontent.com/45182426/80657283-7d8d9100-8a83-11ea-9c0d-fb27a83a514e.png)

## The alternatives

You must reset the functionality as before in version 0.108.x

## Additional information
The cover states in the database are correct and update and the use of the cover.open_cover and cover.close_cover services are working properly.

**Comment by bramkragten** [comment]
Please share the states + a screenshot at the moment you believe the UI is not right.

**Comment by sidwin9** [comment]
Hello,

Unknown state after automatic shutdown of the blind power supply after a few seconds. No action possible
![image](https://user-images.githubusercontent.com/45182426/80753396-791db280-8b2d-11ea-8eec-55b0dcf42107.png)

After pressing stop after partial opening of the blind, only one action possible
![image](https://user-images.githubusercontent.com/45182426/80754040-a1f27780-8b2e-11ea-956e-2ed17c9fcbf2.png)

**Comment by sidwin9** [comment]
I got around the problem with a template cover

`- platform: template`
  `covers:`
      `store_terrasse:`
      `friendly_name: "Store Terrasse"`
      `open_cover:`
          `service: script.1588234357264`
      `close_cover:`
        `service: script.1588234416379`
      `stop_cover:`
        `service: script.1588234488607`
      `value_template: >-`
        `{% if is_state('cover.328214383c71bf312919', 'open') %}open`
        `{% elif is_state('cover.328214383c71bf312919', 'closed') %}closed`
        `{% else %}{{ states('sensor.store_terrasse_state') }}`
        `{% endif %}`

**Comment by bramkragten** [comment]
Please share the states from `/developer-tools/state` especially for the stop case.

**Comment by sidwin9** [comment]
See the same topic
https://github.com/home-assistant/core/issues/34942

**Comment by sidwin9** [comment]
One click on ↓ and one clic stop after 3 seconds
![image](https://user-images.githubusercontent.com/45182426/80800042-bf642780-8ba8-11ea-9b87-dc4426fcd4ca.png)
![image](https://user-images.githubusercontent.com/45182426/80800082-dacf3280-8ba8-11ea-90b6-76fc84e06afc.png)
If back to version 0.108.9 or 0.108.8 there is no longer this problem, we can click on ↓ and ↑

Exactly the same problem for other users. See the same topic
home-assistant/core#34942

**Comment by thimic** [comment]
I’ve got a similar issue with MQTT covers on 0.109. All buttons are greyed out except the stop buttons that do nothing.

Interestingly, I have a few covers grouped and the groups are fine. Once the blinds have been operated via the group, the blinds in that group become available in the card. Similarly, if I operate a cover by calling a service, that blind becomes available. A restart of Home Assistant will deactivate the individual MQTT blinds in the card once more.

Sample from my config:

```yaml
- platform: mqtt
  name: "Dixon Street Left"
  command_topic: "home/cover/set"
  payload_open: "{\"name\": \"dixon_l\", \"command\": \"up\"}"
  payload_close: "{\"name\": \"dixon_l\", \"command\": \"down\"}"
  payload_stop: "{\"name\": \"dixon_l\", \"command\": \"stop\"}"
- platform: mqtt
  name: "Dixon Street Right"
  command_topic: "home/cover/set"
  payload_open: "{\"name\": \"dixon_r\", \"command\": \"up\"}"
  payload_close: "{\"name\": \"dixon_r\", \"command\": \"down\"}"
  payload_stop: "{\"name\": \"dixon_r\", \"command\": \"stop\"}"

- platform: group
  name: "Dixon Street"
  entities:
    - cover.dixon_street_left
    - cover.dixon_street_right
```

What the card looks like when it doesn't let me operate certain blinds:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/9880865/80800233-11cf3380-8bfd-11ea-9687-1f0190bdce37.png">

State:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/9880865/80800401-7ab6ab80-8bfd-11ea-9ef2-774b85729156.png">

State for the group which is working:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/9880865/80800477-afc2fe00-8bfd-11ea-9d17-82c29159a064.png">

Seems this occurs when the current state of the cover is unknown? Trouble is, my covers are dumb and communication with them is one way. They never report a state.
