### ISSUE TITLE
Add ability to change color of icon and the icon itself based on state

### ISSUE THREAD

**Issue by DrJohnT** [home-assistant/frontend#5691]
## The request

Obviously binary_sensors allow the icon to be changed based on state.   

However, switches originating from integrations (e.g. deConz) do not always have the appropriate icon set.  This is especially true of Zigbee devices originating from deConz as it treats most switches as lights!

HA does provide a way to change the static icon associated with an entity using customize, customize_domain and customize_glob as documented here: https://www.home-assistant.io/docs/configuration/customizing-devices/customizing.yaml

However, would be great to have the ability to 
- change color of icon based on the entity's state, and
- change the actual icon itself based on entity's state

## The alternatives

I was using Andrey’s Custom UI (https://github.com/andrey-git/home-assistant-custom-ui) but have removed this now from my HA setup as it depends on are deprecated features.  

Andrey’s Custom UI extended the customize.yaml with a templates section as shown here:

```yaml
switch.s7_upstairs_light:
  icon: mdi:lightbulb-outline  # default icon
  templates:
    icon: >
      if (state === 'on') return 'mdi:lightbulb'; else return 'mdi:lightbulb-outline';
    icon_color: >
      if (state === 'on') return 'red'; else return '#424242';
```
In the above case, the icon is changed to lightbulb if the state is on, and mdi:lightbulb-outline when off.   The icon color is change to red when the state is on.

## Additional information
