### ISSUE TITLE
Error Message if you Toggle Hue Light from UI and iOS Compagnion App

### ISSUE THREAD

**Issue by northpower25** [home-assistant/frontend#5693]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem
on the frondend and iOS App i've got the following error if i toggle hue lights (the function of the light is not affected that meens that the light goes on/off the same in automations)  
Error Message: 

`Fehler beim Aufrufen des Service light/turn_on. unsupported operand type(s) for /: 'NoneType' and 'int' `

## Expected behavior

Toggle without error message

## Steps to reproduce
after HA Version 0.108 toggle hue light in the UI or Comanion iOS App

## Environment
HA 0.109.2

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 5.3.0-46-generic
python_version | 3.7.7
timezone | Europe/Berlin
version | 0.109.2
virtualenv | false

- Home Assistant release with the issue: 0.109.2
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

Example 1:
```
entities:
  - entity: light.garten
  - entity: light.terrasse1
  - entity: light.terrasse2
  - entity: light.terrasse3
show_header_toggle: false
title: Schalter
type: entities
```
Example 2:
```
entity: light.garten
name: Garten
type: light
```

## Javascript errors shown in your browser console/inspector

```txt

```
