### ISSUE TITLE
Prayer Times inconsistent across Mobile & Desktop Web

### ISSUE THREAD

**Issue by iamehkri** [home-assistant/frontend#5699]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem

The lovelace entity card I have setup for prayer times shows the correct time on web, and the incorrect time for mobile (17 hour difference)

## Expected behavior

The times should be the same.

## Steps to reproduce

    1. Configure Islamic Prayer Times Configuration
    2. Navigate to Lovelace
    3. Add Entity Card, put format:time underneath each sensor (fajr, asr maghrib)
    4. Save the card, in the dashboard/web looks fine.
    5. Open HA on iOS and go to Lovelace 
    6. See that Prayer times are wrong, but other sensor times are correct (Bus times, etc)

## Environment

HASS is on a RPi4 both hass and rpi are up to date, iOS is up to date with the latest app.  All browsers have been used on desktop version (Chrome, Safari, etc)

## State of relevant entities

device_class: timestamp

``` yaml
sensor
  - platform: islamic_prayer_times
    calculation_method: isna
    sensors:
      - fajr
      - dhuhr
      - asr
      - maghrib
      - isha
```

## Problem-relevant configuration

From my Lovelace card:

```yaml
entities:
  - entity: sensor.islamic_prayer_time_fajr
    format: time
    icon: 'mdi:weather-sunset-up'
  - entity: sensor.islamic_prayer_time_dhuhr
    format: time
    icon: 'mdi:weather-sunny'
  - entity: sensor.islamic_prayer_time_asr
    format: time
    icon: 'mdi:weather-sunny-alert'
  - entity: sensor.islamic_prayer_time_maghrib
    format: time
    icon: 'mdi:weather-sunset'
  - entity: sensor.islamic_prayer_time_isha
    format: time
    icon: 'mdi:moon-waning-crescent'
show_state: true
title: Prayer Times
type: glance

```

## Javascript errors shown in your browser console/inspector

Non
