### ISSUE TITLE
Underflow displaying allowed range for Z-Wave configuration paramter

### ISSUE THREAD

**Issue by patrickkostjens** [home-assistant/frontend#5739]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When configuring my Aeotec TriSensor connected to my Z-Wave setup in Home Assistant, I can set different node configuration options. The configuration parameter '7: Temperature Alarm Value' says in the description the available range for settings is from -400 to 850, but the label above the textbox says 'A short between 4294934529 and 32767'. It looks like here was an underflow on what seems to be an unsigned number while it should be signed. The same happens for, for example, '30: Temperature Offset Value'.

## Expected behavior

I expect the proper range to be displayed in the label above the field.

## Steps to reproduce

1. Setup zwave integration
2. Add Aeotec TriSensor (may very well happen with other sensors too)
3. Go to the node's configuration options in the Z-Wave configuration panel
4. Select one of the configuration parameters mentioned above

## Environment

- Home Assistant release with the issue: 0.109.3
- Last working Home Assistant release (if known): -
- Browser and browser version: Firefox 75.0, Edge
- Operating system: Windows 10 (Home Assistant Core running on Ubuntu as a Docker image)

## State of relevant entities

```yaml
node_id: 5
node_name: Aeotec Limited ZWA005 TriSensor
manufacturer_name: Aeotec Limited
product_name: ZWA005 TriSensor
query_stage: CacheLoad
is_awake: false
is_ready: false
is_failed: false
is_info_received: true
max_baud_rate: 40000
is_zwave_plus: true
capabilities:
  - routing
  - beaming
  - zwave_plus
sentCnt: 1
sentFailed: 1
retries: 0
receivedCnt: 5
receivedDups: 0
receivedUnsolicited: 5
sentTS: '2020-05-03 10:52:23:696 '
receivedTS: '2020-05-03 10:55:36:179 '
lastRequestRTT: 0
averageRequestRTT: 0
lastResponseRTT: 0
averageResponseRTT: 0
battery_level: 91
wake_up_interval: 28800
application_version: '2.09'
friendly_name: Aeotec Limited ZWA005 TriSensor
```
Note that the problem was already occuring when the query stage was completed, but is now CacheLoad because I upgraded Home Assistant from 0.108.x to 0.109.3 to see if that would fix the problem.

## Problem-relevant configuration

```yaml
zwave:
  usb_path: /dev/zwave
  device_config: !include zwave_device_config.yaml
  network_key: "0x...."
```

```yaml
sensor.aeotec_limited_zwa005_trisensor_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.aeotec_limited_zwa005_trisensor_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.trisensor_living_room_luminance:
  ignored: false
  polling_intensity: 10
sensor.trisensor_living_room_temperature:
  ignored: false
  polling_intensity: 10
```

## Javascript errors shown in your browser console/inspector

No errors in the logs.

## Additional information
Reported as a frontend issue since I see the problem there, but not sure whether these limits are already sent incorrectly from the backend.
