### ISSUE TITLE
incorrect show_header_toggle on Glance-card not noted in yaml parser

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#5749]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Using show_header_toggle: on a glance card is not possible, but when accidentally doing so, it doesnt error out on the refresh of the view

## Expected behavior

show an error an unavailable configuration variable was used

## Environment

- Home Assistant release with the issue: 109.3
- Last working Home Assistant release (if known): never?
- Browser and browser version: Safari. Chrome Mac, Ios app 
- Operating system: Mac

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
      - type: glance
        show_header_toggle: false
        entities:
          - sensor.calculated_totaal_dag_afname
          - sensor.calculated_totaal_dag_afname_t1
          - sensor.calculated_totaal_dag_afname_t2
```

## Javascript errors shown in your browser console/inspector

```txt

```
