### ISSUE TITLE
More Info dialog not scrollable in Firefox

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/frontend#5771]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
To see more attributes in the new weather-card, we are advised to look into the more-info dialog.
This dialog is not scrollable in Firefox.
FF:
![Auswahl_326](https://user-images.githubusercontent.com/26381449/81147724-33247c80-8f7b-11ea-8531-78e984060b36.png)
Chrome:
![Auswahl_327](https://user-images.githubusercontent.com/26381449/81147740-3d467b00-8f7b-11ea-99e1-0b3823487fd0.png)

## Environment

- Home Assistant release with the issue: 0.109.4
- Last working Home Assistant release (if known):
- Browser and browser version: Latest FF, Chrome works
- Operating system: Ubuntu 18.04

## State of relevant entities

```yaml

```

## Problem-relevant configuration

configuration.yaml
```yaml
weather:
  - platform: darksky
    api_key: !secret ds_api_key
    mode: hourly
```
ui-lovelace.yaml
```yaml
      - type: vertical-stack
        cards:

          - type: weather-forecast
            entity: weather.dark_sky
```
## Javascript errors shown in your browser console/inspector

```txt

```
