### ISSUE TITLE
Sensor graphs show bogus data after some time

### ISSUE THREAD

**Issue by dseven** [home-assistant/frontend#5828]
## The problem

Sensor card graphs show bogus data over time. The current value (state) is displayed correctly, but the graph shows something completely unlike reality. Reloading the page makes the graph look correct, but over time, it becomes wrong again. This is happening in different browsers, including Vivaldi (Chromium-based) on Windows, and Fully Kiosk on Android.

## Expected behavior

Graph should show a continually updating representation of past <hours_to_show> hours' worth of values of the sensor.

These graphs are bogus. The random spikes are not realistic. Both graphs should show slow increase over the last several hours:

![graphs-before](https://user-images.githubusercontent.com/3360577/81486686-51a0a700-920b-11ea-8161-873ff5207d91.PNG)

After reloading the page, they look like they're supposed to:

![graphs-after](https://user-images.githubusercontent.com/3360577/81486691-5b2a0f00-920b-11ea-8ab1-9341e68987ad.PNG)

From Android tablet around the same time:

![Screenshot_20200509-150340](https://user-images.githubusercontent.com/3360577/81486696-6b41ee80-920b-11ea-9efe-c727b0aaad03.png)

## Steps to reproduce

Just leave it in the browser for some hours.

## Environment

- Home Assistant release with the issue:

Home Assistant 0.109.6
Frontend version: 20200427.2 - latest

- Last working Home Assistant release (if known):

Not sure if it even worked - this graph feature is fairly new

- Browser and browser version:

Vivaldi | 3.0.1874.33 (Stable channel) (64-bit)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.132 Safari/537.36

Fully Kiosk Browser v1.38

- Operating system:

Windows 10
Android

## State of relevant entities

State values (current temps) shown in the above screenshots are correct - it's just the graphs that are bogus.

## Problem-relevant configuration

```
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.master_br_temperature
            name: 'Master BR'
            graph: 'line'
            detail: 2
            hours_to_show: 12
          - type: sensor
            entity: sensor.weewx_out_temp
            name: 'Outside'
            graph: 'line'
            detail: 2
            hours_to_show: 12
```

## Javascript errors shown in your browser console/inspector

n/a
