### ISSUE TITLE
Addtional blank space in the Entities card

### ISSUE THREAD

**Issue by cofw2005** [home-assistant/frontend#5842]
## The request

I defined three cards with horizontal-stack, the Entities card always extend the height to have the same height with the longest card, and so that there is big blank area in the card. See picture below (the right card is the Entities card with problem):
![image](https://user-images.githubusercontent.com/32097699/81750192-52f0fe80-94ad-11ea-8970-2d7c03e2a7fe.png)

## The alternatives
I only see the Entities card with this issue, if I change the card type to Glance or Histroy-graph, it turns back normal. See picture (Glance card type doesn't have the issue).
![image](https://user-images.githubusercontent.com/32097699/81750303-859af700-94ad-11ea-8c71-5c14d665b981.png)

Further example, I change the left card to Entities, and the right card type to History-graph. Now the height of left card is extended.
![image](https://user-images.githubusercontent.com/32097699/81750538-f9d59a80-94ad-11ea-91c6-c5a25bbfaf8a.png)

## Additional information
Here is the beginning code of the view.
```
title: XXX
views:
  - title: Watering
    icon: mdi:flower
    panel: true
    cards:
      - type: horizontal-stack
        cards:
```
