### ISSUE TITLE
Custom device_class: presence reporting wrong state

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#5844]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I noticed with other presence sensors they started stating home / not_home on entity cards and sometime between 109.0 & 109.3 that was fixed...

However I have some custom presence detectors defined (see yaml); and before 109 this would show Home / Away; but now shows On / Off.

**Same is for weather reporting things like partlyCloudy rather than Partly cloudy and ping sensors that report on rather than "Connected"** 

## Expected behavior

Correct state to be shown

## Steps to reproduce

```yaml
    sensors:
      pet_biscuit_summary:
        value_template: "{{ is_state('binary_sensor.pet_biscuit', 'on') }}"
        device_class: presence
        friendly_name: 'Biscuit'
        icon_template: 'mdi:cat'
```
Add it to an entity card ... prior to 109 it would show Home / Away ... now shows on/off

## Environment

- Home Assistant release with the issue: 0.109.ALL
- Last working Home Assistant release (if known): 0.108.X
- Browser and browser version: Chrome
- Operating system: Tested on Windows / android

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
#detailed in steps to reporduce
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Detailed in https://github.com/home-assistant/core/issues/35102 .. was told it is a frontend issue.
