### ISSUE TITLE
invalid option 'line_color' doesn't error on card type sensor

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#5857]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Using a now deprecated option line_color (hadn't noticed the breaking change some time ago...) doesnt error out in the inspector.

## Expected behavior

Using invalid options for a card should throw an error.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known): 0.84... I know, sorry
- Browser and browser version: Any
- Operating system: Ha 109.6

## State of relevant entities

```yaml
  - type: sensor
    name: Opbrengst Zonnepanelen
    entity: sensor.zp_actuele_opbrengst
    graph: line
    detail: 2
    height: 75
    line_color: '#3498db'
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
