### ISSUE TITLE
Toggle switch for entity holds focus until clicked away

### ISSUE THREAD

**Issue by mwasowski** [home-assistant/frontend#5898]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I noticed recently that when I click an entity in card group (or single entity for that matter), the element keeps focus until anything else is clicked making it loose focus as seen on the example:

## Expected behavior

When the toggle is clicked the entity looses focus.

## Steps to reproduce

1. Add entity card with any type of a switch/input boolean
2. Change it's state.

## Environment

- Home Assistant release with the issue: HA 0.109.6, HassOS 3.13, Supervisor 222
- Last working Home Assistant release (if known): -
- Browser and browser version: Firefox 76.0.1 x64
- Operating system: Windows 10 x64 Build 1909

## State of relevant entities

It's not relevant to specific entity but I noticed it after I added this.
```yaml
entities:
  - entity: sensor.bridge_state
  - entity: input_boolean.zigbee_permit_join
  - entity: timer.zigbee_permit_join
show_header_toggle: false
title: Zigbee
type: entities
```
![JfI0OFu6X2](https://user-images.githubusercontent.com/1921808/82075690-eceabe00-96dc-11ea-8c7f-31866fde9427.gif)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
