### ISSUE TITLE
entity-filter card not appearing in Home Assistant 0.110.0b3

### ISSUE THREAD

**Issue by Hackashaq666** [home-assistant/frontend#5911]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem
An entity filter card is only appearing when initially created and saved. Any page refresh and it no longer appears. This happens in both the ios app and windows 10 with Chrome browser
Here s the code for the card:

```yaml
type: entity-filter
entities:
  - entity: sensor.front_door_lock_battery_level
  - entity: sensor.garage_access_door_lock_battery_level
  - entity: sensor.siren_strobe_battery_level
  - entity: sensor.basement_battery
  - entity: sensor.basement_water_sensor_battery_level
  - entity: sensor.front_door_battery
  - entity: sensor.front_door_sensor_battery_level
  - entity: sensor.garage_access_door_sensor_battery_level
  - entity: sensor.deck_door_sensor_battery_level
  - entity: sensor.patio_door_sensor_battery_level
  - entity: sensor.basement_door_sensor_battery_level
  - entity: sensor.closet_door_sensor_battery_level
  - entity: sensor.foyer_motion_sensor_battery_level
  - entity: sensor.loft_motion_sensor_battery_level
  - entity: sensor.battery_level
  - entity: sensor.battery_level_2
state_filter:
  - operator: <
    value: 90
title: Battery Levels

```

## Expected behavior
Card should appear listing entities with battery level <90.

## Environment
Home Assistant 0.110.0b3 on raspberry pi 4B, hassOS.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
