### ISSUE TITLE
History component somehow controls recorder state history

### ISSUE THREAD

**Issue by sophof** [home-assistant/frontend#5913]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Disabling the history component somehow prevents any state history from being shown in the frontend. This applies to both 'more information' tabs as graphs. I'm not entirely sure it is a frontend issue, but my database appears to be filled fine, so I assume it is not home assistant core.

See also [https://community.home-assistant.io/t/graph-only-available-with-history-integration/193038/4](https://community.home-assistant.io/t/graph-only-available-with-history-integration/193038/4)

## Expected behavior
Disabling the history component only removes the history tab while keeping the possibility to show state history.

## Steps to reproduce
I'm not sure if it is unique to me or not. The following is my configuration for recorder and history. If I disable history, I run into the issue. The backend database is postgresql.

```yaml
# Postgresql database
recorder:
  purge_keep_days: 28 #keep 4 weeks
  db_url: !secret db_connect
  exclude:
    entities:
      - sensor.yr_symbol
      - sensor.time
      - sensor.time_hour
      - sensor.date_time

history:
```

## Environment
Running on a ubuntu 19.10 server, I've tried both Firefox and chrome as browsers. Latest version of home assistant (0.109)

- Home Assistant release with the issue: 0.109
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Chrome (Version 81.0.4044.138), Firefox (69.0.3)
- Operating system: Home assistant running on Ubuntu 19.10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
# Postgresql database
recorder:
  purge_keep_days: 28 #keep 4 weeks
  db_url: !secret db_connect
  exclude:
    entities:
      - sensor.yr_symbol
      - sensor.time
      - sensor.time_hour
      - sensor.date_time

history:
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
The history component is what provides state history, so if you disable that we have no way to get state history.

In other words, this is expected.

**Comment by sophof** [comment]
Not so fast! This is clearly not the case and also not intended.
For instance, I've used the following settings for history up to the point where I started testing this issue:
```yaml
history:
  include:
    domains:
      - light
    entities:
      - binary_sensor.presence_tv
      - binary_sensor.presence_werkkamer
      - binary_sensor.presence_woonkamer
      - binary_sensor.presence_anyone_home
      - binary_sensor.iemand_in_slaap_slaapkamer
      - binary_sensor.beide_in_slaap_slaapkamer
      - binary_sensor.pir_multisesensor
      - binary_sensor.pir_voordeur
      - binary_sensor.pir_werkkamer
      - binary_sensor.pir_woonkamer_deur
      - binary_sensor.time_bed
      - binary_sensor.time_evening
      - binary_sensor.time_workhours
```
Even though this excludes many entities from the history tab, the state history will still be available for those excluded entities in other places. From the forum thread I linked it is also clear that others also don't think this is intended.

Finally, even if it is intended, imo it is a mistake to depend this on a visual panel component. Especially since the opposite behaviour (just a standalone panel) is strongly implied from the integration page itself [https://www.home-assistant.io/integrations/history/](https://www.home-assistant.io/integrations/history/).

It makes sense that not recording an entity with 'recorder' would make the data unavailable, but why would a visual component exactly impact it? You can't tell me you really think that a history panel should be required to show a single graph on a Lovelace panel?
