### ISSUE TITLE
Part of card edit menu hidden behind toolbar

### ISSUE THREAD

**Issue by mariusoei** [home-assistant/frontend#5928]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I tried to move all my cards from one view to another.
Upon clicking the 3-dot-menu for the last card to select "move to another view", part of the menu including that entry was hidden behind the "toolbar" on the top (the view chooser).

![image](https://user-images.githubusercontent.com/23221754/82299847-51946a00-99b6-11ea-85e2-16f8fc31f71b.png)

I know in this case I can manually edit the lovelace configuration, but I think it could be fixed anyway.

## Expected behavior

![image](https://user-images.githubusercontent.com/23221754/82301145-1e52da80-99b8-11ea-8521-d8f1d208273e.png)

The menu should be fully visible as is the case for taller cards or when there is another card above the selected one.

## Steps to reproduce

1. Add a new view in lovelace
2. Open the lovelace edit view
3. Add a single "flat" (i.e. low height) card to that menu (such as an elements card with a single entry and no title)
4. Click the 3-dot-menu on the bottom right of the card where it says "move to view", "duplicate" and "delete"
5. Part of the menu will now be hidden beneath the top bar (view chooser). 

## Environment

- Home Assistant release with the issue: 0.109.6
- Last working Home Assistant release (if known):
- Browser and browser version: Brave Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit), Firefox 76.0.1 (64-Bit)
- Operating system: Homeassistant running in a Docker container on Ubuntu, accessing interface from Windows 10

## State of relevant entities

Independent of entity states.

```yaml

```

## Problem-relevant configuration

Pretty sure this has nothing to do with the configuration, but here is an example anyway.

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
    language: 'de'

discovery:
  ignore:
    - igd
    
# Setup InfluxDB
influxdb:
  host: influxdb
  database: homeassistant

# Include the themes directory
frontend:
  themes: !include_dir_merge_named themes    
   
# MQTT Setup (overridden by UI config)   
mqtt:
  broker: mosquitto
  discovery: true
  discovery_prefix: homeassistant
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

```

## Javascript errors shown in your browser console/inspector

No errors
```txt

```

## Additional information

Note that while I include other themes, this problem appears for the standard theme also (not a bug in the theme I used).
