### ISSUE TITLE
0.110 broke gauges visualization

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/frontend#5943]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Latest 0.110 update broke `type: gauge`
an image speaks better than what I can do.

![1](https://user-images.githubusercontent.com/4722227/82443301-8fba8800-9aa1-11ea-82c0-9ec66f603e5b.JPG)

![2](https://user-images.githubusercontent.com/4722227/82443307-934e0f00-9aa1-11ea-960d-21b81a7814dd.JPG)

![3](https://user-images.githubusercontent.com/4722227/82443310-9517d280-9aa1-11ea-8517-549dc1504e01.JPG)

as you can see gauges are misaligned now, with bigger and smaller gauge in the same horizontal layout.

before it worked better.

![smartostat_dashboard](https://user-images.githubusercontent.com/4722227/82443436-c395ad80-9aa1-11ea-889b-8c64144d35cc.jpg)

## Environment

- Home Assistant release with the issue: 0.110
- Last working Home Assistant release (if known): 0.109
- Browser and browser version: Chrome/Firefox
- Operating system: Windows 10

**Comment by MuppetOwl** [comment]
Can also confirm similar issue. gauges does not look good on desktop and on tablet/phone they take up way to much space now.

![Annotation 2020-05-20 152729](https://user-images.githubusercontent.com/33086105/82457563-db772c80-9ab5-11ea-8c0e-847601d33019.png)

**Comment by bramkragten** [comment]
Please follow the issue template.

**Comment by sblantipodi** [comment]
> Please follow the issue template.
> 
> What is your config?
> 
> Also add a clear before/after image. I see a lot of images but I'm not sure what I'm looking at.

Sincerely I don't know what are the improvements bringed on gauge but I see only regression.

```
cards:
  - cards:
      - entity:
          - sensor.room_humidity
        type: gauge
        unit: '%'
      - entity:
          - sensor.room_pressure
        max: 1050
        min: 950
        type: gauge
        unit: hPa
      - entity:
          - sensor.room_gasresistance
        max: 1400
        min: 0
        type: gauge
        unit: KOhms
    type: horizontal-stack
  - cards:
      - entity:
          - sensor.room_iaq
        max: 500
        min: 0
        type: gauge
        unit: IAQ
      - entity:
          - sensor.cyberpower_watt_load
        max: 1350
        min: 0
        type: gauge
        unit: W
      - entity:
          - sensor.cyberpower_pr1500elcd_battery_charge
        max: 100
        min: 0
        type: gauge
        unit: '%'
    type: horizontal-stack
type: vertical-stack

```

![Screenshot_20200520-191351](https://user-images.githubusercontent.com/4722227/82476708-c0fd7d00-9ace-11ea-9a28-3a2b4bc77381.jpg)

gauses was correctly aligned before, now it is misaligned as you can see from this image,
the gauge bar was fatter, now is so slim why?

it's not difficult to reproduce, simply use my vertical stack
