### ISSUE TITLE
Lovelace, view consisting of multiple picture-elements not displayed properly after 110.0

### ISSUE THREAD

**Issue by plamish** [home-assistant/frontend#5959]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

A view view consisting of multiple picture-elements is shown in vertical layout, one below other, instead of spread out on screen. The issue occurs in YAML and UI edit modes. "Refresh" command from Lovelace top right menu fixes the layout, however same happen on next session. 

## Expected behavior

When view consisting of multiple picture-elements is shown elements are  spread out on screen

## Steps to reproduce

 Using UI mode:
    1. Click Configure UI
    2. Add a new view
    3. Add 3 picture elements 
    4. Close UI mode
    5. Close web browser 
    6. Open web browser and connect to HA, navigate to added view to see the issue

## Environment

Home Assistant 0.110.0
Frontend version: 20200519.0 - latest

Client OSX Catalina and Chrome 81/Firefox 76

Worked well on HA 0.109

## State of relevant entities

N/A

```yaml

```

## Problem-relevant configuration

  An example configuration that caused the problem for you. Fill this out even
  if it seems unimportant to you. Please be sure to remove personal information
  like passwords, private URLs and other credentials.

```yaml
title: TEST
views:
  - badges: []
    panel: false
    title: Test
    icon: mdi:biohazard
    cards:
      - type: picture-elements
        elements:
        - type: state-badge
          entity: binary_sensor.updater
          style:
            top: 32%
            left: 40%
        image: 'https://demo.home-assistant.io/stub_config/floorplan.png'
      - type: picture-elements
        elements:
        - type: state-badge
          entity: binary_sensor.updater
          style:
            top: 32%
            left: 40%
        image: 'https://demo.home-assistant.io/stub_config/floorplan.png'
      - type: picture-elements
        elements:
        - type: state-badge
          entity: binary_sensor.updater
          style:
            top: 32%
            left: 40%
        image: 'https://demo.home-assistant.io/stub_config/floorplan.png'

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

![Screen Shot 2020-05-21 at 09 35 46](https://user-images.githubusercontent.com/52619470/82535402-15dcda00-9b47-11ea-96b9-21ce12a7f27b.png)
![Screen Shot 2020-05-21 at 09 36 04](https://user-images.githubusercontent.com/52619470/82535390-12495300-9b47-11ea-942e-1f07d1dfc61c.png)
![Screen Shot 2020-05-21 at 09 36 12](https://user-images.githubusercontent.com/52619470/82535399-15444380-9b47-11ea-98cb-4a54dc8b388c.png)
