### ISSUE TITLE
Entity details on mobile only using 1/3 screen

### ISSUE THREAD

**Issue by mrnix1001** [home-assistant/frontend#5969]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

When opening the details for an entity, it only occupies 1/3 of the screen.
 
![image](https://user-images.githubusercontent.com/47438671/82486218-8681e900-9aaa-11ea-90e8-b2c8082a45d5.png)

## Expected behavior

Expects that the entity details occupy the entire screen.

## Steps to reproduce

1. Open up local ha instance on mobile device.
2. Open an entity inside a "entities" type card.

## Environment

- Home Assistant release with the issue: 0.110.0
- Last working Home Assistant release (if known): 0.108.x
- Browser and browser version: Chrome 81.0.4044.138
- Operating system: Android 10

## State of relevant entities

From desktop browser:

![image](https://user-images.githubusercontent.com/47438671/82575510-922ae980-9b56-11ea-9f14-1e073d03660d.png)

```yaml

```

## Problem-relevant configuration

```yaml
      - type: entities
        title: Living Room
        show_header_toggle: true
        entities:
          - entity: switch.living_room_flux
          - entity: light.living_room_lamp_1
          - entity: light.living_room_lamp_2
          - entity: light.tall_lamp
          - entity: light.living_room_fan
          - entity: light.entryway_downlights
          - entity: switch.living_room_sconces
          - entity: light.display_case
          - entity: switch.tv
          - entity: switch.living_room_filter
          - entity: binary_sensor.living_room_motion
          - entity: binary_sensor.living_room_motion_2          
          - entity: sensor.living_room_temperature
          - entity: sensor.living_room_lux
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Nabu Casa's rendering shows the exact same thing.
