### ISSUE TITLE
Reopen, still misaligned.

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/frontend#5970]
A reopen of this:
https://github.com/home-assistant/frontend/issues/5943

is still misaligned

![misaligned](https://user-images.githubusercontent.com/4722227/82579759-8d822780-9b8e-11ea-8046-6a5c8865e0c0.JPG)

**Comment by marklister** [comment]
## Checklist

- [X] I have updated to the latest available Home Assistant version. 0.110.1
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem


The gauge card does not resize consistently.  I'll attach screenshots.  Tested on Chrome 81.0.4044.138 (Official Build) (64-bit) (Linux) and on Chrome for Android.

## Expected behavior

I'll attach screenshots of 0.109.x  .  I'd expect the gauge to look the same in the same size view port. 


## Steps to reproduce
Here's my lovelace setup:

```
cards:
  - entity: sensor.bat_percent
    max: 100
    min: 0
    name: Battery
    severity:
      green: 65
      red: 20
      yellow: 35
    theme: default
    type: gauge
    unit: '%'
  - entity: sensor.bat_watts
    max: 2000
    min: -4000
    name: W
    severity:
      green: -300
      red: -5048
      yellow: -1200
    theme: default
    type: gauge
    unit: W
type: horizontal-stack
```
I have 3 rows of these.

To reproduce the problem resize your window.  The gauge bars will jump from thick to thin, the text will spill into the graphic area, then become tiny.  Once its really ugly hit refresh and it'll probably look fine.

On android switch from portrait to landscape and back. 


## Environment



- Home Assistant release with the issue: 0.110.1
- Last working Home Assistant release (if known): 0.109.6
- Browser and browser version: Chrome on Linux 81.0.4044.138 (Official Build) (64-bit)
Chrome on android 81.0.4044.138
- Operating system:
  Linux Debian
  Android
## State of relevant entities



```yaml
cards:
  - entity: sensor.bat_percent
    max: 100
    min: 0
    name: Battery
    severity:
      green: 65
      red: 20
      yellow: 35
    theme: default
    type: gauge
    unit: '%'
  - entity: sensor.bat_watts
    max: 2000
    min: -4000
    name: W
    severity:
      green: -300
      red: -5048
      yellow: -1200
    theme: default
    type: gauge
    unit: W
type: horizontal-stack
```

## Problem-relevant configuration



```yaml

```

## Javascript errors shown in your browser console/inspector



```txt

```

## Additional information
![Screenshot_20200524-091352](https://user-images.githubusercontent.com/1758937/82750038-7cf7ca00-9da5-11ea-8cb5-a58363141fbe.png)
![Screenshot_20200524-091411](https://user-images.githubusercontent.com/1758937/82750040-81bc7e00-9da5-11ea-8164-1b957d40ca66.png)
![Screenshot_20200524-091421](https://user-images.githubusercontent.com/1758937/82750044-841ed800-9da5-11ea-9df5-7eeb473af4a5.png)
![Desktop-0 110](https://user-images.githubusercontent.com/1758937/82750045-884af580-9da5-11ea-818a-b8668f37b2c8.png)
![Desktop-0 110 1-2](https://user-images.githubusercontent.com/1758937/82750048-8aad4f80-9da5-11ea-9ebb-72ec2f9c60fb.png)

It seems to me that PR #5900 might be the cause?  What do you think @zsarnett ?

To follow: screenshots from 0.109.6.  I'm busy downgrading.
