### ISSUE TITLE
Switch control returns to previous state after ~1 second, however physical switch behaves as expected

### ISSUE THREAD

**Issue by dslynko** [home-assistant/frontend#5982]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have enabled MQTT integration. I have several switch controls - Aqara relays, and my custom device based on Wemos D1 board. After latest update I've noticed that switch behavior is broken - if I toggle switch (lets say, switch was OFF and I set in to ON, it acts as expected (state=ON), physical switch toggles, however, switch on the UI returns back to previous state (OFF) in ~1 sec.
If I refresh browser's tab - switch shows correct state (ON).

## Expected behavior
UI switch's state should match physical switch's state

## Steps to reproduce

1. Have some switch integration in Hassio (Aqara) via MQTT
2. Toggle it
3. Physical switch is toggled
4. Check toggle state on the UI

## Environment

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
hassio | true
host_os | Ubuntu 18.04.4 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.15.0-101-generic
python_version | 3.7.7
supervisor | 222
timezone | Europe/Warsaw
version | 0.110.1
virtualenv | false

- Home Assistant release with the issue: 0.110.0/1
- Last working Home Assistant release (if known):0.109
- Browser and browser version: Chrome Version 81.0.4044.138 (Official Build) (64-bit), Safari 
- Operating system: MacOS, iOS

## State of relevant entities

```yaml
payload_off: 'OFF'
payload_on: 'ON'
value_template: '{{ value_json.state_l1 }}'
command_topic: zigbee2mqtt/0x00158d00044b1bef/l1/set
state_topic: zigbee2mqtt/0x00158d00044b1bef
json_attributes_topic: zigbee2mqtt/0x00158d00044b1bef
name: 0x00158d00044b1bef_switch_l1
unique_id: 0x00158d00044b1bef_switch_l1_zigbee2mqtt
device:
  identifiers:
    - zigbee2mqtt_0x00158d00044b1bef
  name: '0x00158d00044b1bef'
  sw_version: Zigbee2mqtt 1.13.0
  model: Aqara wireless relay controller (LLKZMK11LM)
  manufacturer: Xiaomi
availability_topic: zigbee2mqtt/bridge/state
platform: mqtt
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
screen video https://take.ms/hxtJu
