### ISSUE TITLE
Calendars created from search queries show duplicated in "Calendar" panel

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/frontend#6003]
## Checklist
- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Calendar entities created by applying a search query to a 'master' calendar are are shown duplicated in the calendar view.

In the attached screenshot _(fig. 1)_, three calendars pull from a single "Meals" calendar and search for all-day events prefixed with 'Breakfast:', 'Lunch:', or 'Dinner:' for respectively named calendar.  The main "Meals" calendar isn't imported into Home Assistant, opting for the separated ones in it's place. Under the new Calendar panel, the "Breakfast" and "Lunch" calendar are showing "Dinner" events, despite not being actually active in their respective `calendar.` entities _(fig. 2)_.

![Screenshot 2020-05-23 at 1 02 01 pm](https://user-images.githubusercontent.com/16481433/82730203-f46e2080-9cf5-11ea-94d8-223b6f6366d1.png)
_Figure 1_

![Screenshot 2020-05-23 at 1 06 12 pm](https://user-images.githubusercontent.com/16481433/82730234-2f705400-9cf6-11ea-9750-34d9736fbd8a.png)
_Figure 2_

## Expected behavior
Calendars should only show events for that particular `calendar.` entity.

## Steps to reproduce

1. Add searchable event to CalDAV calendar (i.e. iCloud)
2. Create a calendar component from the CalDAV URL
3. Create _child_ calendars using the search query (one positive, one negative)
4. Hide the parent calendar (do not import into Home Assistant)
5. Observe the calendar panel
6. Witness _child_ calendars show all events from parents, and are not filtered.

## Environment

- Home Assistant release with the issue: 0.110.x
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Edge 83.0.478.37
- Operating system: macOS 10.15.4

## State of relevant entities

```yaml
calendar.meals_breakfast
  state: off	
  offset_reached: false
  friendly_name: Breakfast

calendar.meals_dinner
  state: on
  message: Dinner: Fish and Chips
  all_day: true
  start_time: 2020-05-23 00:00:00
  end_time: 2020-05-24 00:00:00
  location: null
  description: null
  offset_reached: false
  friendly_name: Dinner

calendar.meals_lunch
  state: off	
  offset_reached: false
  friendly_name: Lunch
```

## Problem-relevant configuration

```yaml
- name: 'Breakfast'
  calendar: &meal_calendar
      Meals
  search: '^\s*[Bb]reakfast[:]'

- name: 'Lunch'
  calendar: *meal_calendar
  search: '^\s*[Ll]unch[:]'

- name: 'Dinner'
  calendar: *meal_calendar
  search: '^\s*[Dd]inner[:]'
```

## Javascript errors shown in your browser console/inspector

```txt
N/A
```
