### ISSUE TITLE
Automatically signed in users should not be asked wether to save login

### ISSUE THREAD

**Issue by mback2k** [home-assistant/frontend#6022]
## The request

I think automatically signed in users should not be asked wether to save the login for later.

E.g. if a login happens with the following configuration, Lovelace should not show the popup to ask the user about saving the login for later:
```
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - a.b.c.d
      trusted_users:
        a.b.c.d: userid
      allow_bypass_login: true
    - type: homeassistant
```

## The alternatives

At the moment there is no real alternative. Since my use case is a magic mirror display, I always have to get a mouse and click away the question after a device/browser restart.

## Additional information

My original feature request on the forums can be found here:
https://community.home-assistant.io/t/automatically-signed-in-users-should-not-be-asked-wether-to-save-login/180742
