### ISSUE TITLE
Entity-filter badge doesn't work

### ISSUE THREAD

**Issue by ee02217** [home-assistant/frontend#6047]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I just noticed an issue when creating a condition to show a badge.
I use the Raw Configuration Editor to add the following:

```
  - badges:
      - entity: person.sergio_sa
      - entity: person.joana
      - entity: device_tracker.x1_sdrive16d
      - type: entity-filter
        entities:
          - entity: sensor.lixo
          - entity: sensor.plastico
          - entity: sensor.papel
        state_filter:
          - operator: ==
            value: "today"
```

It works perfectly, but when I refresh the page, it stops working because the double quotes are removed and the condition no longer works:

```
  - badges:
      - entity: person.sergio_sa
      - entity: person.joana
      - entity: device_tracker.x1_sdrive16d
      - type: entity-filter
        entities:
          - entity: sensor.lixo
          - entity: sensor.plastico
          - entity: sensor.papel
        state_filter:
          - operator: ==
            value: today
```

## Expected behavior

Quotes or double quotes should not be removed by Lovelace otherwise the entity-filter will not work. 

## Steps to reproduce

As described above with samples. 
Introduce the condition and save. 
Confirm it is working and badge appears as it should. 
Refresh the browser and it no longer works. Badge disappear although the condition was true. 

## Environment

All browsers. 
I have Hass running in docker. 

- Home Assistant release with the issue: latest. 
- Last working Home Assistant release (if known): not known
- Browser and browser version: all
- Operating system: all (server running in docker in Ubuntu)
