### ISSUE TITLE
Conditional card spacing

### ISSUE THREAD

**Issue by flixlix** [home-assistant/frontend#6051]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I noticed, that when I create a conditional card, and the condition is false, so the card doesn´t show, there is is a empty space in the desktop view of lovelace.

## Expected behavior

I would like it, if, when the conditions are false, the card nor the space for the card is shown.

## Steps to reproduce

1. Create a card.
2. Click on "Conditional Card".
3. Create a certain condition (that later can be false) .
4. Use any card (ie.: Entities Card) .
5. Select entities.
6. Exit configuration mode.
7. Make sure the card doesn't appear, so the condition is false.

## Environment

I'm using Home Assistant 0.110.1 in a docker with a Raspberry pi4 model b 2gb RAM. I'm browsing on Chrome (I cleared the cache) on a Windows machine.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

![image](https://user-images.githubusercontent.com/61006057/82895629-60e25d00-9f4c-11ea-9b1d-6cabcea0aa94.png)

```yaml

```

## Problem-relevant configuration

My .yaml config is the following

```yaml
type: conditional
conditions:
  - entity: input_boolean.show_card
    state: 'on'
card:
  type: entities
  title: Lichter
  entities:
    - entity: light.bett
    - entity: light.schreibtisch
    - entity: light.schlafzimmer
    - entity: light.fenster

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by eggman0131** [comment]
It also seems that even when a visible space is not left the layout engine acts as if there was a card there - is card_size not set to 0 when the card isn't displayed?

**Comment by Mariusthvdb** [comment]
can confirm the latter, using conditional (custom) button-cards, leaving spaces when not displayed, yaml code for config:

```
  - type: horizontal-stack
    cards:

      - type: conditional
        conditions:
          - entity: input_boolean.github_repo_update
            state: 'on'
        card: !include /config/lovelace/includes/include_button_github_repo_alert.yaml

      - type: conditional
        conditions:
          - entity: binary_sensor.earthquakes_near_active
            state: 'on'
        card: !include /config/lovelace/includes/include_button_quake_alert.yaml

      - type: conditional
        conditions:
          - entity: binary_sensor.trash_notification
            state: 'on'
        card: !include /config/lovelace/includes/include_button_trash_alert.yaml

      - type: conditional
        conditions:
          - entity: binary_sensor.schimmel_alert
            state: 'on'
        card: !include /config/lovelace/includes/include_button_ventilate.yaml

      - type: conditional
        conditions:
          - entity: binary_sensor.updater_notification
            state: 'on'
        card: !include /config/lovelace/includes/include_button_updater.yaml

      - type: conditional
        conditions:
          - entity: binary_sensor.meteoalarm_brabant
            state: 'on'
        card: !include /config/lovelace/includes/include_button_meteoalarm_alert.yaml

      - type: conditional
        conditions:
          - entity: binary_sensor.hubs_offline
            state: 'on'
        card: !include /config/lovelace/includes/include_button_sensor_hubs.yaml

      - type: conditional
        conditions:
          - entity: binary_sensor.critical_devices_offline
            state: 'on'
        card: !include /config/lovelace/includes/include_button_critical_devices.yaml

      - type: conditional
        conditions:
          - entity: binary_sensor.espresso_needs_refill
            state: 'on'
        card: !include /config/lovelace/includes/include_button_espresso.yaml

      - type: custom:button-card
        color_type: blank-card

      - type: custom:button-card
        color_type: blank-card

      - type: custom:button-card
        color_type: blank-card
```
