### ISSUE TITLE
Spacing Conditional Card bug

### ISSUE THREAD

**Issue by flixlix** [home-assistant/frontend#6064]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I noticed, that when I create a conditional card, and the condition is false, so the card doesn´t show, there is is a empty space in the desktop view of lovelace.

## Expected behavior

I would like it, if, when the conditions are false, the card nor the space for the card is shown.

## Steps to reproduce

1. Create a card.
2. Click on "Conditional Card".
3. Create a certain condition (that later can be false) .
4. Use any card (ie.: Entities Card) .
5. Select entities.
6. Exit configuration mode.
7. Make sure the card doesn't appear, so the condition is false.

## Environment

I'm using Home Assistant 0.110.1 in a docker with a Raspberry pi4 model b 2gb RAM. I'm browsing on Chrome (I cleared the cache) on a Windows machine.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

![image](https://user-images.githubusercontent.com/61006057/82895629-60e25d00-9f4c-11ea-9b1d-6cabcea0aa94.png)

```yaml

```

## Problem-relevant configuration

My .yaml config is the following

```yaml
type: conditional
conditions:
  - entity: input_boolean.show_card
    state: 'on'
card:
  type: entities
  title: Lichter
  entities:
    - entity: light.bett
    - entity: light.schreibtisch
    - entity: light.schlafzimmer
    - entity: light.fenster

```

## Javascript errors shown in your browser console/inspector

```txt

```
