### ISSUE TITLE
support for service_data_template for actions

### ISSUE THREAD

**Issue by travisghansen** [home-assistant/frontend#6078]
## The request

I'm pretty new to the project so forgive my ignorance here if I'm just missing something blatantly obviously or approaching it incorrectly. I've created some `input_number` sensors which I in turn want to use the current value of as a `service_data` attribute when invoking a service on a different entity altogether. I've tried various syntaxes at setting the value as such but it always sort of blows up when I return to edit the definition it has `[object Object]..` as the value of the attribute.

Hypothetical example:

```
tap_action:
  action: call-service
  service: opensprinkler.run
  service_data_template:
    run_seconds: {{ states.input_number.openprinkler_station_run_time.state | int }}
```

## The alternatives

Unsure at this point. Maybe I should be invoking a `script` and then subsequently invoking a `service`? If I do that I'm not sure how I get the proper `entity_id`.

## Additional information

Thanks for the help and consideration!
