### ISSUE TITLE
In Lovelace, add card hangs generating preview list

### ISSUE THREAD

**Issue by seanb-uk** [home-assistant/frontend#6080]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

When I try to add a card to the Lovelace UI, the browser window hangs. The cancel button cannot be clicked - the entire window is unresponsive and the tab has to be killed. The browser is showing high CPU use.  

Tried in Chrome and Firefox and I get the same behaviour.

After a period - at least five minutes - the window sometimes responds. There is a timeout error in the Javascript console at this point (see below)

I have also had instances where the connection to HA is lost completely with the browser then showing the "Connection lost. Reconnecting..." message.

## Expected behavior

I should see the full list of cards and be able to select a card to configure.

## Steps to reproduce

From the front end, select "Configure UI" and press the plus button.

I have fired up a clean install of HassOS in a VM, and the issue does not occur. The fact that it doesn't occur on a clean install suggests that the issue may be with a specific entity that the card list is trying to preview. Ideally this should still lead to a timely error message so that it's possible to track down and fix the offending entity.

## Environment

- Running v0.110.4 core under Docker on an i5 based CentOS host that isn't heavily loaded.
- This has occurred since at least v.109. I don't change the UI often, so hard to be sure when it first occurred.
- Using latest Chrome and Firefox.
- Occurs when browsing via both Windows (fairly high spec machine) and Android.

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) DOMException: Transaction timed out due to inactivity.
```
When the connection breaks completely I get the following error:
```text
hui-image.ts:28 Uncaught (in promise) {type: "result", success: false, error: {…}}
```

**Comment by seanb-uk** [comment]
I've identified the culprit. I have a template sensor to expose the windspeed attribute from weather, defined as:

```
- platform: template
  sensors:
    wind_speed:
      value_template: '{{ (state_attr("weather.home", "wind_speed") | float * 0.62137119) |round}}'
      friendly_name: "Wind speed"
      unit_of_measurement: 'mph'
```

I can add that to the UI successfully. Once it's added, the "Add Card" selector hangs every time I go into it. As soon as I remove the template sensor from the UI, the selector works again.

That sensor isn't important to me now and I don't need it in the UI,, so this isn't an issue now. I think the bug remains - a problem with a single sensor shouldn't stop the selector from working.

**Comment by aderusha** [comment]
Others are reporting the same behavior: https://community.home-assistant.io/t/lovelace-ui-add-card-panel-freeze-unresponsive-for-long-time/195483

I'm also seeing this, in my case it's an SNMP sensor.  This is for sure a bug in the frontend somewhere.

**Comment by bramkragten** [comment]
Is this the history card or the sensor card, or what card in the preview is showing the problematic sensor?

**Comment by aderusha** [comment]
The issue impacts the entire browser, no page controls or scrolling works on the tab at all and this happens in Chrome, FF, and also the new MS Edge.  Chrome and Edge will prompt to kill the stuck page after a bit.  After maybe 2-3 minutes the page becomes responsive again.

Process:

- Three dots > Configure UI
- Hit `+` to add new card
- Page is responsive for maybe a second (if you're scrolling it will scroll for just a flash)
- Everything locks up for several minutes

Result looks like this: https://i.imgur.com/uSLLXZI.png

**Comment by bramkragten** [comment]
Yeah, I understand that, but I'm looking for the cause of it, so if it gets responsive again, is the SNMP sensor that seems to be the issue used in one of the previews? And if so it what card preview?

**Comment by seanb-uk** [comment]
In my case, it was probably because the weather entity wasn't available - I think there must've been an issue with the default weather integration or the met.no API for a while.

I had the template sensor to extract windspeed from the attributes. It must have been that template sensor that was causing the hang, as removing it fixed the issue.

The weather entity is now working again, and I've added the template sensor back with no issues.

So it looks like the triggering cause was the unavailability of a sensor, but only in certain circumstances - I have some obsolete entities that are unavailable and I can't replicate the issue by adding them to the UI.

**Comment by aderusha** [comment]
Digging a little deeper, in my case it appears to be the statistics sensors I have for an SNMP sensor.  Here is the complete definition:

```yaml
  - platform: snmp
    name: 'router01 WAN in'
    host: 10.0.0.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.6.16
    community: !secret snmp_read
    version: '2c'
    scan_interval: 10
  - platform: snmp
    name: 'router01 WAN out'
    host: 10.0.0.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.10.16
    community: !secret snmp_read
    version: '2c'
    scan_interval: 10
  # - platform: statistics
  #   name: 'router01 WAN In Stats'                      
  #   entity_id: sensor.router01_wan_in                  
  #   sampling_size: 4                              
  #   max_age:                                      
  #     hours: 24                                   
  # - platform: statistics                          
  #   name: 'router01 WAN Out Stats'                     
  #   entity_id: sensor.router01_wan_out
  #   sampling_size: 4
  #   max_age:
  #     hours: 24
```

With the stats sensors commented out everything works like normal.  This might be due to the specific sensor that hass is selecting to show in the various cards which show a sensor entity as a demo in the pick list.  When I comment out the SNMP stat sensors it selects my UPS (meaning, some other sensor) and then everything works.
