### ISSUE TITLE
Media Control in a Horizontal Stack no same size

### ISSUE THREAD

**Issue by Xaldimo** [home-assistant/frontend#6086]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

When adding multiple media players in a horizontal stack the heights are not equal.

![image](https://user-images.githubusercontent.com/2435859/83443340-77535180-a441-11ea-8ab5-9c3cb82b51fc.png)

## Expected behavior

The smaller media player to fill up to same height as the longer media player.

## Environment

- Home Assistant release with the issue: 0.110.4
- Last working Home Assistant release (if known):
- Browser and browser version: FireFox 68.8.0esr
- Operating system: Debian 10

## State of relevant entities

```yaml
source_list:
  - HDMI 1
  - HDMI 2
  - HDMI 3/ARC
  - HDMI 4
  - AV 1
  - AV 2/Component
  - Screen mirroring
  - Play Store
  - YouTube
  - Album
  - Music
  - TV
  - Programme Guide
  - Recorded Title List
  - Prime Video
  - Play Music
  - Play Games
  - Play Movies &amp; TV
  - Netflix
  - BRAVIA Tutorials
  - Video
  - Help
  - TV Control Setup with Amazon Alexa
  - Sony Select
  - Timers
  - Internet Browser
  - ES File Explorer
  - Termux
  - Kodi
  - Emby
  - BBC iPlayer
  - ITV Player
  - All 4
  - My5
  - YouView
  - 'Rakuten TV: Your cinema at home'
  - BBC News
  - BBC Sounds
  - BBC Sport
  - Digital Concert Hall
  - Rakuten TV
  - Meteonews TV
  - DW for Smart TV
volume_level: 0
is_volume_muted: false
media_content_id: HDMI 2
media_title: HDMI 2
source: HDMI 2
friendly_name: Sony Bravia TV
supported_features: 23997
device_class: tv

friendly_name: Main Kodi
supported_features: 55231

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
