### ISSUE TITLE
Scene Editor and RGB WW CW switching

### ISSUE THREAD

**Issue by brinzlee** [home-assistant/frontend#6091]
## Checklist

- [yes ] I have updated to the latest available Home Assistant version.
- [ yes] I have cleared the cache of my browser.
- [ yes] I have tried a different browser to see if it is related to my browser.

## The problem

I have an RGB WW CW floodlight made by Novostella. This has then had tasmota firmware v7.0. When I set a scene to make the lights cool white or warm white in the scenes editor and then save it. If I recall the scene the RGB takes priority and and makes the RGB 100% to make white instead of using the WW or CW leds.

## Expected behavior

 I would expect it to remember the last recalled value of the LED staus correctly. Its fine with RGB just the CW and WW it can't recall

## Steps to reproduce

Get a RGB WW CW light and try and save warm white or cool white in the scenes editor. I have seen other people have the issue with some philips hue devices

## Environment

- Home Assistant release with the issue: Home Assistant 0.110.4
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- Operating system: Windows 10 Pro 1909

## State of relevant entities

```yaml

```

## Problem-relevant configuration
```yaml
- id: '1574512957647'
  name: Lounge TV
  entities:
    light.novostella_flood_1:
      brightness: 255
      color_temp: 438
      effect: '0'
      effect_list:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      friendly_name: Novostella Flood 1
      hs_color:
      - 0
      - 0
      max_mireds: 500
      min_mireds: 153
      rgb_color:
      - 255
      - 255
      - 255
      state: 'on'
      supported_features: 23
      xy_color:
      - 0.323
      - 0.329
    light.novostella_flood_2:
      brightness: 209
      color_temp: 435
      effect: '0'
      effect_list:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      friendly_name: Novostella Flood 2
      hs_color:
      - 0
      - 0
      max_mireds: 500
      min_mireds: 153
      rgb_color:
      - 255
      - 255
      - 255
      state: 'on'
      supported_features: 23
      xy_color:
      - 0.323
      - 0.329`
```

## Javascript errors shown in your browser console/inspector

```txt

```
