### ISSUE TITLE
Markdowncard h2 does not accept styling since 0.111

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/frontend#6147]
## Checklist
- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

With the latest update to 0.111, my markdown cards lost the ability to style the h2 headers with card-mod. Cant get any styling applied to the h2 tag.

## Expected behavior

To style the h2 headers with custom css using card-mod.

## Steps to reproduce
I've added a markdown card as listed below, using card-mod. Works in 0.110.4, breaks in 0.111.0

## Environment

- Home Assistant release with the issue: 0.111.0
- Last working Home Assistant release (if known): 0.110.4 (didn't patch higher)
- Browser and browser version: Chrome 83.0 fully patched
- Operating system: Win10
- Using custom plugin [lovelace-card-mod](https://github.com/thomasloven/lovelace-card-mod) (there is an [issue ](https://github.com/thomasloven/lovelace-card-mod/issues/52)listed there as well), but I've got a feeling it might be related to this PR: https://github.com/home-assistant/frontend/pull/5904

Styling is also not applied when loading though the HA Android app.

## State of relevant entities
n/a

## Problem-relevant configuration

```yaml
      - type: markdown 
        content: |
         ## In een oogopslag...
        style: |
         ha-card {
          margin: 0px 14px -5px 14px;
          box-shadow: none;
          --paper-card-background-color: rgba(0, 0, 0, 0.0)
          }
          h2 {
            font-size: 18px;
            font-weight: 400;
            padding-left: 10px;
            border-left: 3px solid rgba(81, 134, 236);
          }
```

## Javascript errors shown in your browser console/inspector
None observed

## Additional information
Rollback to 0.110.4 gave expected result, after browser refresh.
