### ISSUE TITLE
Script delay gets overwritten to [object Object] when using the GUI

### ISSUE THREAD

**Issue by HugoPeters1024** [home-assistant/frontend#6164]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## Expected behavior

The "delay" property of a script is saved correctly and verbatim

## Steps to reproduce

Create a script in the text editor, add a sequence action with a delay, for e.g:

```yaml
delay:
   milliseconds: 200
```

Then open the gui script editor, verify that the gui already shows [object Object] as a delay value, use the save button from the gui, assert that the script has indeed changed in the file editor.

## Environment

Home Assistant 0.111.2
PI 4 2GB

Viewing on Chrome

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml
# After opening and saving from GUI
    entity_id: light.bed
    service: light.turn_on
  - delay: '[object Object]'
  - data:
      rgb_color:
      - 255
      - 0
      - 0
    entity_id: light.bed
    service: light.turn_on
  - delay: '[object Object]'

```
