### ISSUE TITLE
Media player entity picture is disappear for 1-2 seconds during automatic refresh

### ISSUE THREAD

**Issue by nchieffo** [home-assistant/frontend#6196]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When I use a media player card/entity in lovelace, there is a feature that downloads the currently playing image and shows it in the card.
The image is refreshed every 10-15 seconds and every time it gets refreshed it disappears for 1-2 seconds then it loads.
This happens even if the picture does not change (for still images)

## Expected behavior

I don't expect any glitch, so maybe the image data should be pre-fetched before showing it in the browser

## Steps to reproduce

- Add a media player which can show the entity picture (such as a television, I used my lg_netcast)
- add the media player lovelace card
- turn on the TV
- wait 10-15 seconds so that the card picture reloads automatically

## Environment

- Home Assistant release with the issue: 0.111.4
- Last working Home Assistant release (if known):
- Browser and browser version: chrome 83.0.4103.106
- Operating system: windows / android

## State of relevant entities

```yaml
source_list:
  - Rai 1
  - Rai 2
  - Rai 3
volume_level: 0.05
is_volume_muted: false
media_content_type: channel
friendly_name: tv_lg_55lm660s
entity_picture: >-
  /api/media_player_proxy/media_player.tv_lg_55lm660s?token=7ffebafd3325454d997fe7d2c82cc404f648773dea3608c59f56b8fe0e748b1a&cache=9863ac6471d862f2
supported_features: 19769
```

## Problem-relevant configuration

```yaml
media_player:
  - platform: lg_netcast
    name: tv_lg_55lm660s
    host: 192.168.1.15
    access_token: xxx
```

## Javascript errors shown in your browser console/inspector

```txt

```
