### ISSUE TITLE
Automation reordering removes information

### ISSUE THREAD

**Issue by oneseventhree** [home-assistant/frontend#6221]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser - I am using Chome but I can replicate this problem on my HA app on my iphone.

## The problem

a)
When I add a new device in the automations UI at the bottom and try it move it to the top sometimes the new added device will stop moving up when it's under another device:
<img width="610" alt="Screen Shot 2020-06-24 at 7 57 18 am" src="https://user-images.githubusercontent.com/15043282/85468883-5ae5a780-b5f0-11ea-915f-d77ef20bb684.png">
When I try and swap the above around they flash quickly then change back to their previous positions.

b) Also if I move a blank device:
<img width="653" alt="Screen Shot 2020-06-24 at 7 58 30 am" src="https://user-images.githubusercontent.com/15043282/85469031-84063800-b5f0-11ea-973f-dd724e1d246f.png">
Up through the animation all other devices lose their information:
<img width="630" alt="Screen Shot 2020-06-24 at 7 59 28 am" src="https://user-images.githubusercontent.com/15043282/85469138-a6985100-b5f0-11ea-9e8f-82d635a86e44.png">
In the above photo I moved a blank device all the way up the automation and the devices below lost their information and when I try and save it says "Message malformed: Integration '' not found" even when I fill in the information of the first blank device.

## Expected behavior

The ability to reorder automations in UI with a blank device or with a filled in device

## Steps to reproduce

a)
    1. Add 2-3 devices and fill in information
    2. Add a blank device 
This SOMETIMES works but doesn't work for larger automations

b)
    1. Add 2-3 devices and fill in information
    2. Add a blank device and move it to the top
This SOMETIMES works but doesn't work for larger automations

## Environment

- Home Assistant release with the issue: 0.111.4
- Last working Home Assistant release (if known): This has always been an issue
- Browser and browser version: Chrome - Version 83.0.4103.106 (Official Build) (64-bit) 
- Operating system: MAC - Also doesn't work on HA app on iOS or Chrome on Windows

## State of relevant entities
```yaml
N/A
```

## Problem-relevant configuration

```yaml
N/A
```

## Javascript errors shown in your browser console/inspector

```txt
N/A
```

## Additional information
This is the code for the larger automation:
```yaml
- id: '1573025769685'
  alias: Bedroom Tap Switch - 4 - ALEXA "Sleep"
  description: ''
  trigger:
  - device_id: 95f44d17d16441089c82c3e3b08b8f93
    domain: hue
    platform: device
    subtype: button_4
    type: remote_button_short_press
  condition:
  - after: '19:00:00'
    before: 06:30:00
    condition: time
  action:
  - data:
      entity_id: light.every_light_zone
    service: light.turn_off
  - data:
      command: Stop
      device: 67310068
      entity_id: remote.harmonyhub
    service: remote.send_command
  - data:
      command: PowerOff
      device: 67310068
      entity_id: remote.harmonyhub
    entity_id: remote.harmonyhub
    service: remote.send_command
  - data:
      data:
        type: tts
      message: Goodnight
    service: notify.alexa_media_echo_spot
  - data:
      command: PowerToggle
      device: 69709672
      entity_id: remote.harmonyhub
    service: remote.send_command
  - entity_id: lock.front_door_lock
    service: lock.lock
  - device_id: b2afab5d53c24241868da3890587e2e4
    domain: switch
    entity_id: switch.kitchen_leds_smartplug
    type: turn_off
  - device_id: b2afab5d53c24241868da3890587e2e4
    domain: switch
    entity_id: switch.kitchen_leds_smartplug
    type: turn_off
  - device_id: 831da000b8ee4f8e877c278523157614
    domain: switch
    entity_id: switch.office_smartplug
    type: turn_off
  - device_id: 9f449a87ee6e4dd085b5cdd1ec44469f
    domain: switch
    entity_id: switch.tv_leds_smartplug
    type: turn_off
  - data:
      volume_level: 0.4
    entity_id: media_player.alexa_sonos_beam
    service: media_player.volume_set
  - data:
      command: PowerOff
      device: 51933082
    entity_id: remote.harmonyhub
    service: remote.send_command
  - data:
      activity: 31888252
    entity_id: remote.harmonyhub
    service: remote.turn_off
  - delay: 06:30:00
  - device_id: d836cc4d2a5740c784d575cb9600f577
    domain: switch
    entity_id: switch.fan_smartplug
    type: turn_off
```
