### ISSUE TITLE
The visual Editor shows a warning for double_tap_action of type button. But it works.

### ISSUE THREAD

**Issue by ranomier** [home-assistant/frontend#6243]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

If i add double_tap_action for the type button in the visual editor, it shows a warning that it expects undefined. (I think that means not possible. Maybe a better error message would be good)

## Expected behavior

One of two things.
1. Show no warning (proffered)
2. do not allow the double_tap_action to work.

## Steps to reproduce
1. Add a button to lovelace
2. press on show visual editor
3. append
```
double_tap_action:
  action: more-info
```
at the end
4. see warning message.
5. press save
6. double tap and see that it works

## Environment

arch | armv7l
-- | --
chassis |  
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | Debian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.4.45-sunxi
python_version | 3.7.7
supervisor | 228
version | 0.111.4
virtualenv | false

- Home Assistant release with the issue: 0.111.4
- Last working Home Assistant release (if known):
- Browser and browser version: firefox 77.0.1 and chromium  83.0.4103.116
- Operating system: debian 10

## State of relevant entities

```
type: button
entity: light.mi_arbeit
name: Arbeit
double_tap_action:
  action: more-info
hold_action:
  action: more-info
tap_action:
  action: call-service
  service: switch.toggle
  service_data:
    entity_id: switch.so_arbeit_so_arbeit
```
![image](https://user-images.githubusercontent.com/7649949/85891206-01979700-b7ef-11ea-8151-a91aae44bdf7.png)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
