### ISSUE TITLE
Broadlink RM 3 Mini - Failed to send packet: The device storage is full

### ISSUE THREAD

**Issue by j3mu5** [home-assistant/frontend#6295]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When sending a command using "broadlink.send", there is no IR code send but this error occurs in the log:
2020-07-01 20:33:03 ERROR (MainThread) [homeassistant.components.broadlink] Failed to send packet: The device storage is full

This error ouccurs since 0.111 and maybe even before.

## Expected behavior

Usually, IR codes are sent, e.g. turning on my TV screen.

## Steps to reproduce

Broadlink is integrated using a switch, giving the ability to use "broadlink.send"

## Environment

Home Assistant 0.112.0
arch | armv7l
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.118-v7l+
python_version | 3.7.7
timezone | Europe/Berlin
version | 0.112.0
virtualenv | false

- Home Assistant release with the issue: 0.112.0 and 0.111.0
- Last working Home Assistant release (if known): not sure, maybe 0.108.0
- Browser and browser version: Chrome Version 83.0.4103.116 (Offizieller Build) (64-Bit)
- Operating system: Windows 10, (Home Assistant runs on Raspbian Buster in Docker)

## State of relevant entities
Cannot find any entity related to the broadlink rm 3 mini.

```yaml

switch.ir_cmd_advent_wreath | off | friendly_name: Adventskranz assumed_state: true
-- | -- | --



```

## Problem-relevant configuration

```yaml
form: broadlink
host: !secret ir_mini3_ip
mac: !secret ir_mini3_mac
type: rm_mini3_redbean

switches:
  ir_cmd_advent_wreath:
    friendly_name: "Adventskranz"
    command_on: 'JgBQAAABKJQVEBQSFBEUEhQSFBEUEhQRFDYUNhU1FDYUNhQ2FDYUNhQ2FBIUERURFBEUEhUQFREUEhQ1FTUVNRQ2FDYUNhQ2FQAFHQABL0kUAA0FAAAAAAAAAAA=='
    command_off: 'JgBQAAABKJUSFBITEhQSExIUEhMTExIUEjcSOBI4EjgSOBI4EjgSOBI4EhQSExI4EhQSFBITEhQSExI4EzcTExI4EjgSOBI4EgAFIAABK0sSAA0FAAAAAAAAAAA=='
```

## Javascript errors shown in your browser console/inspector

```txt

```
