### ISSUE TITLE
Translation errors for Portuguese on Integrations screen

### ISSUE THREAD

**Issue by jprates** [home-assistant/frontend#6334]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

User profile set to "Portugues" language.
[Integrations page](https://hass.ecowatt.pt/config/integrations) shows all cards with "Translation error" as the exemple below:
![image](https://user-images.githubusercontent.com/20585218/86530249-06bfaa80-beaf-11ea-854f-257a329b9b7c.png)

## Expected behavior

No localized language / translation errors should be displayed.

## Steps to reproduce

Set user language to "Portugues";
Navigate to integrations page.

## Environment

- Home Assistant release with the issue: Home Assistant 0.112.2
- Last working Home Assistant release (if known): Home Assistant 0.111.?
- Browser and browser version: Chrome 83.0.4103.116 (Official Build) (64-bit)
- Operating system: Microsoft Windows [Version 10.0.18363.900] (64-bit)

## Problem-relevant configuration

# Configure a default setup of Home Assistant (frontend, api, etc)
```
default_config:

system_health:

person:

homeassistant:
  name: (removed info)
  latitude: (removed info)
  longitude: (removed info)
  unit_system: metric
  time_zone: Europe/Lisbon
  customize:
    person.(removed info):
      entity_picture: "/local/pics/(removed info).png"
    person.(removed info):
      entity_picture: "/local/pics/(removed info).jpg"
    person.(removed info):
      entity_picture: "/local/pics/(removed info).jpg"
    person.(removed info):
      entity_picture: "/local/pics/(removed info).jpg"

weather:
  - platform: ipma

# Text to speech
tts:
  - platform: google_translate

zwave: !include zwave.yaml
automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
shell_command: !include shell.yaml
zone: !include zone.yaml

google_assistant: 
  project_id: (removed info)
  service_account: !include (removed info)
  report_state: true
  exposed_domains:
    - group
  entity_config:
    group.ventila:
      name: ventilação
    group.ilumina_exterior:
      name: muro

frontend:
  themes: !include themes/ookla/ookla_theme.yaml

http: 
  ssl_certificate: /ssl/fullchain.pem 
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

```
