### ISSUE TITLE
Number in input_number slider pop-up is lower than it used to be

### ISSUE THREAD

**Issue by Tediore** [home-assistant/frontend#6350]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Absolutely terrible explanation in the title, but please see this screenshot:

![Screenshot_20200708-081013_2](https://user-images.githubusercontent.com/49540618/86923171-4ecf0f00-c0f3-11ea-8f77-5cab8ff8c309.png)

## Expected behavior

The number in the icon that appears when you touch the slider used to be higher up (vertically centered with the circular part of the pop-up instead of the entire icon). This made it easier to see the number when using the slider on a mobile device. Currently my thumb covers up most of the number when before it was much more visible. Unfortunately I can't tell when this was changed since I haven't used these sliders in a while. This affects all sliders, not just the specific one shown in the screenshot.

Tested in both the official Android app and Chrome on desktop (on Debian and Windows).

## Steps to reproduce

Add any `input_number` slider to the UI, and move the slider position.

## Environment

- Home Assistant release with the issue: 0.112.0+ (possibly earlier)
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Chrome 83, Android Companion App 1.10.0
- Operating system: Debian 10, Windows 10, Android 10  (hmm... I'm noticing a pattern here)

## State of relevant entities

![Untitled](https://user-images.githubusercontent.com/49540618/86924426-10d2ea80-c0f5-11ea-9343-090786f8c5b8.png)

Attributes:
```yaml
initial: null
editable: false
min: 70
max: 78
step: 1
mode: slider
unit_of_measurement: °F
friendly_name: Home
icon: 'mdi:home-outline'
```

## Problem-relevant configuration

```yaml
input_number:
  cool_home:
    name: Home
    icon: mdi:home-outline
    min: 70
    max: 78
    step: 1
    unit_of_measurement: '°F'
    mode: slider
```

## Javascript errors shown in your browser console/inspector

```txt
N/A
```
