### ISSUE TITLE
Entities used in cards are still listed as unused

### ISSUE THREAD

**Issue by Kernald** [home-assistant/frontend#6375]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

I have a few sensors that I'm aggregating inside a `plant` entity, which I'm displaying using a [`plant-status`](https://www.home-assistant.io/lovelace/plant-status/) card. It's the only place I'm using them, I don't have them displayed directly anywhere else. When visiting `/lovelace/hass-unused-entities`, they're still listed there.

## Expected behavior

They shouldn't be listed in this list, as even if it's indirect, they are indeed used by the `plant` entity.

## Steps to reproduce

    1. Aggregate some sensors in a `plant` entity
    2. Display this `plant` entity in a `plant-status` card

## Environment

- Home Assistant release with the issue: 0.112.4
- Last working Home Assistant release (if known): I don't know, but it's probably never been working any differently - it's definitely not new.
- Browser and browser version: Chrome 83.0.4103.116
- Operating system: happens on both Linux, macOS and Windows

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
plant:                                                                                                                                                                                       
  succulents:                                                                                                                                                                                
    sensors:                                                                                                                                                                                 
      moisture: sensor.succulents_moisture                                                                                                                                                   
      battery: sensor.succulents_battery                                                                                                                                                     
      temperature: sensor.succulents_temperature                                                                                                                                             
      conductivity: sensor.succulents_conductivity                                                                                                                                           
      brightness: sensor.succulents_light                                                                                                                                                    
    min_moisture: 7                                                                                                                                                                          
    max_moisture: 50                                                                                                                                                                         
    min_conductivity: 300                                                                                                                                                                    
    max_conductivity: 1000                                                                                                                                                                   
    min_temperature: 8.0                                                                                                                                                                     
    max_temperature: 35.0    


# Lovelace:

  - path: plants
    title: Plants
    badges: []
    cards:
      - type: plant-status
        entity: plant.succulents
        name: Succulents

```

## Javascript errors shown in your browser console/inspector

```txt

```
