### ISSUE TITLE
Invalid Date for Jewish Calendar in Mobile app and Safari

### ISSUE THREAD

**Issue by lukecarbis** [home-assistant/frontend#6391]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The Jewish Calendar works great in most browsers. However, in Safari the Entities and Glance cards return "Invalid date". This affects the Home Assistant iOS app, as it renders the view using the native Safari engine.

<img width="400" src="https://user-images.githubusercontent.com/1097667/87478935-ef7e7b00-c66d-11ea-8a68-728b89d6e2eb.jpeg">

## Expected behavior

Safari displays the correct formatted date, the same as other browsers.

## Steps to reproduce

1. Enable the Jewish Calendar by updating `configuration.yaml` with the following:
```yaml
jewish_calendar:
```
2. Add a new Entities card
3. Choose an Jewish Calendar entity, such as `sensor.jewish_calendar_upcoming_candle_lighting`
4. View the card in Safari

## Environment

- Home Assistant release with the issue: Home Assistant 0.112.4 / Frontend version: 20200702.1 / Home Assistant 2020.3.1 (mobile app)
- Last working Home Assistant Core release (if known): 
- Browser and browser version: MacOS Safari 13.1.1 / iOS 13 Safari
- Operating system: MacOS 10.15.5 / iOS 13.5.1
- Integration causing this issue:  Jewish Calendar
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/jewish_calendar/

## State of relevant entities

```yaml
entities:
  - entity: sensor.jewish_calendar_upcoming_candle_lighting
    name: Candle Lighting
  - entity: sensor.jewish_calendar_upcoming_havdalah
    name: Havdalah
title: Candle Lighting
type: entities
```

## Problem-relevant configuration

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
jewish_calendar:
  diaspora: true
  candle_lighting_minutes_before_sunset: 18
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
shopping_list:
```

## Javascript errors shown in your browser console/inspector

There are no javascript console errors.

The raw value of the date is a timestamp format. For example:

```txt
2020-07-17 06:54:00+00:00
```

Running `new Date('2020-07-17 06:54:00+00:00')` in the Firefox console returns a valid result.

Running `new Date('2020-07-17 06:54:00+00:00')` in the Safari console returns "Invalid date."

## Additional information

This Stack Overflow answer seems related: https://stackoverflow.com/a/4310986
