### ISSUE TITLE
Setting default dashboard in multi-dashboard config does not persist - yaml mode - docker

### ISSUE THREAD

**Issue by u8915055** [home-assistant/frontend#6414]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have configured multiple dashboards in yaml mode.  Each dashboard has its own yaml file.  The dashboards show up correctly in home assistant.  However, when logged in as admin (only user defined), and try to set a dashboard as default, it does not persist after logging out and back in again.  Ive tried setting this under the user profile and also under the 'Lovelace Dashboards' section.  It seems to take it, the Overview sidebar option disappears immediately (because set another dashboard to default) but if I log out and back in again it goes back to 'Overview' as the default and 'Default' in my user profile.

I am building this in docker but everything else seems to work fine.

## Expected behavior

I expect that if I create additional dashboards and set one of them to default it should persist across logout/login.
## Steps to reproduce

Installed home assistant (in docker alpine image), created dashboard config in configuration.yaml, reloaded, went to both user->profile and Configuration->Lovelace Dashboards to set the default and then logged out and back in .

## Environment

- Home Assistant release with the issue: 0.112.5
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Chrome Version 83.0.4103.116
- Operating system: Mac OSX Catalina 10.15.5

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```
  mode: yaml
  resources:
    - url: https://fonts.googleapis.com/css?family=Comfortaa&display=swap
      type: css
  dashboards:
    na-routines:
      mode: yaml
      filename: na-routines.yaml
      title: Routines
      icon: mdi:clipboard-check-multiple-outline
      show_in_sidebar: true
    na-sensors:
      mode: yaml
      filename: na-sensors.yaml
      title: Sensors
      icon: mdi:antenna
      show_in_sidebar: true
    na-dashboard:
      mode: yaml
      filename: na-dashboard.yaml
      title: Dashboard
      icon: mdi:monitor-dashboard
      show_in_sidebar: true
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Since im in yaml mode, if this were to function correctly, where would that default dashboard info be stored?  since its per device and not per user, woudl it be stored in the database?  or somewhere in the .storage folder?  Thank you.
