### ISSUE TITLE
Warning text makes UI editor unusable

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#6420]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When there is a long list of entities in a card that the Lovelace UI editor does not support the warning text makes the card uneditable. This is with my browser zoomed out to 10%:

![Untitled](https://user-images.githubusercontent.com/10679300/87773154-2dc99500-c83c-11ea-994f-0cdc2b2e03ee.png)

## Expected behavior

Wordwrap the warning, limit it to the width of the code edit box.
## Environment

- Home Assistant release with the issue: Home Assostant OS (NUC) v0.112.4
- Last working Home Assistant release (if known): v0.111
- Browser and browser version: Firefox 78.0.2, also Chrome 84.0.4147.89
- Operating system: Windows 10 Pro

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Please complete the template, how do I reproduce this?

**Comment by tomlut** [comment]
Try this:
```
entities:
  - entities:
      - automation.abb_usage_alert
      - automation.addon_update_available
      - automation.backup_notifications
      - automation.dns_change
      - automation.gpio_bridge_1_disconnection_alert
      - automation.gpio_bridge_1_memory_monitor_alert
      - automation.gpio_bridge_2_disconnection_alert
      - automation.gpio_bridge_2_memory_monitor_alert
      - automation.hacs_update_available
      - automation.hassos_update_available
      - automation.lane_gate_battery_monitor
      - automation.lane_gate_connection_monitor
      - automation.mailbox_battery_monitor
      - automation.mailbox_connection_monitor
      - automation.mains_power_on_alert
      - automation.mains_power_fail_alert
      - automation.memory_monitor_alert
      - automation.processor_use_alert
      - automation.set_light_theme_at_sunrise
      - automation.set_dark_theme_at_sunset
      - automation.shutdown
      - automation.speedtest_alert
      - automation.speedtest_peak_time_check
      - automation.startup
      - automation.supervisor_update_available
      - automation.test_mode_reset
      - automation.update_available
    group_config:
      state_color: true
    head:
      label: Expand
      type: section
    padding: 0
    type: 'custom:fold-entity-row'
show_header_toggle: false
title: Automations - Sysyem
type: entities
```
