### ISSUE TITLE
Entity Card: Attribute with value 0 shown as “unknown”

### ISSUE THREAD

**Issue by sonnstein** [home-assistant/frontend#6483]
## The problem
I am displaying the attribute of a sensor in the frontend with the lovelace card type "entity". If the attribute "min_value" is zero (0), it is shown as "unknown" in the frontend.

## Expected behavior

I would expect it to be shown just as "0"
![Stat_YAML](https://user-images.githubusercontent.com/1300860/88786829-4b2f2500-d193-11ea-8672-305f23dea54e.png)

## Steps to reproduce

see the code example in the first chapter

## Environment

Parameter | Value
-- | --
arch | armv7l
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.3
supervisor | 229
timezone | Europe/Vienna
version | 0.113.1
virtualenv | false

## State of relevant entities

see screenshot in "Expected Behaviour"

## Problem-relevant configuration

```
cards:
  - type: entity
    entity: sensor.poolpump_power_statistics
    attribute: min_value
    icon: mdi:arrow-down-bold-box-outline
    name: "Min."
    unit: W
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

[Link to the community forum](https://community.home-assistant.io/t/attribute-with-value-0-shown-as-unknown/214808)
