### ISSUE TITLE
Camera Snapshot in Automation broken

### ISSUE THREAD

**Issue by sla89** [home-assistant/frontend#6493]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Currently the camera snapshot API says that you have to use `data` to specify everything like this:

```yaml
action:
  service: camera.snapshot
  data:
    entity_id: camera.yourcamera
    filename: '/tmp/yourcamera_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
```

See docs: https://www.home-assistant.io/integrations/camera/

But the truth is that instead of `data` you have to use `data_template`. Otherwise it will not work. So this is also a bug in the documentation.

In my automation I had to use 

```yaml
action:
  service: camera.snapshot
  data_template:
    entity_id: camera.turstation
    filename: /config/www/camera1/snapshots/doorbell_snapshot.jpg
```

When I do this the automation UI gets broken too because the entity id field and the data field are empty then and you have to work with the yaml editor all the time.

## Expected behavior
I want the automation UI work properly with this circumstance.
You can also not use the entity field for entering the camera name - you have to do it in the `data_template` part.

## Steps to reproduce

1. Have a camera entity
1. Configure the folder allow list for the snapshot
1. Create a new automation
1. Add action with calling service `camera.snapshot` and try to configure it properly
1. You will see that you have to use the yaml mode and `data_template` instead of `data`

## Environment
- Home Assistant version:
```
arch | x86_64
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 5.4.0-42-generic
python_version | 3.8.3
timezone | Europe/Vienna
version | 0.113.1
virtualenv | false
```

- Last working Home Assistant release (if known): unknown
- Browser and browser version: Chrome 84.0.4147.105 
- Operating system: Windows 10

## Additional information
Shall I add a ticket in the core repository too for the camera repository to change it using `data` instead of `data_template` or should the documentation be updated? 

Thank you.
Stefan
