### ISSUE TITLE
Secrets in automation.yaml replaced with cleartext value when saved from UI

### ISSUE THREAD

**Issue by fredrikbaberg** [home-assistant/frontend#6496]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I use secrets in `automation.yaml` for e.g. PIN-code for alarm.
Modifying the file by hand, this seem to work. When I used the editor in the frontend (Automations/edit) the secrets are replaced by their value.

I´ve tried this through opening the first automation in my list and press save, without any modifications.

## Expected behavior

Secrets should not be replaced by cleartext value when editing automations using the UI.

## Steps to reproduce

1. Create an automation using a "!secrets" entry,
2. Open editor for automation in UI, press save button,
3. secret has been replaced by cleartext value in file.

## Environment

- Home Assistant release with the issue: Home Assistant 0.113.2
- Last working Home Assistant release (if known):
- Browser and browser version: Microsoft Edge 84.0.522.48 (Officiell version) (64 bitar), also tried with Google Chrome 84.0.4147.105 (Officiell version) (64 bitar)
- Operating system: Windows 10 Pro

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
# In automations.yaml
- id: '<some id>'
  alias: Disable Alarm
  description: ''
  trigger:
  - event_data:
      action: disable_alarm
    event_type: mobile_app_notification_action
    platform: event
  condition: []
  action:
  - data:
      code: !secret some_secret_code
    entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
  mode: single
```

## Javascript errors shown in your browser console/inspector

```txt

```
