### ISSUE TITLE
Edit with YAML in Automation: Trigger Battery Level with Above & Below Configured, Throws Error

### ISSUE THREAD

**Issue by woodmj74** [home-assistant/frontend#6498]
## Checklist

- [ YES ] I have updated to the latest available Home Assistant version.
- [ YES ] I have cleared the cache of my browser.
- [ YES ] I have tried a different browser to see if it is related to my browser.

## The problem

Error thrown when selecting "Edit with YAML" the trigger in an automation based around a sensor battery:
![image](https://user-images.githubusercontent.com/68328701/89023779-07b3f280-d31c-11ea-8c64-e69f2847162a.png)

Quite specific steps to recreate (noted below) and can be rectified by refreshing the page but an error shouldn't be shown

## Expected behavior

Expected behavior is that the YAML representation of the trigger defined in UI is shown without throwing an error

## Steps to reproduce

- Create a new automation
- Within trigger select Device and a valid sensor (with a battery)
- Select the trigger [Device] Battery Level battery level changes
- Enter a below value (value doesn't matter)
- Add an action (any just to allow us to save)
- Hit Save

At this point you can happily select "Edit as YAML" against the trigger (using the top right menu on the trigger).

- Now add an Above value for the trigger through the UI (not in YAML)
- Hit save
- Attempt to edit the trigger again in YAML from within the trigger element of the UI

The error is thrown (screen shot above)

- Refresh the page without having to leave
- Edit as YAML again against the trigger and it loads

![image](https://user-images.githubusercontent.com/68328701/89025379-a5a8bc80-d31e-11ea-9b14-a68bf2dcd071.png)

## Environment

- Home Assistant release with the issue: 0.113
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Chrome 84.0.4147.105 (also tested in Edge)
- Operating system: HassOS 4.11

## State of relevant entities

Also tested this scenario with other entities and reproduced, not specific to a single entity

`event_id: office_switch
unit_of_measurement: '%'
friendly_name: Office Switch Battery Level
device_class: battery`

## Problem-relevant configuration

This is the automation after the page has been refreshed:

```
- id: '1596189405367'
  alias: xxxTest
  description: ''
  trigger:
  - above: 5
    below: 95
    device_id: 82e2b05faaeb41b5ba4e28759e2694fc
    domain: sensor
    entity_id: sensor.dimmer_switch_battery_level
    platform: device
    type: battery_level
  condition: []
  action:
  - device_id: 2b25b411b457443e85bfe0ecba659a63
    domain: light
    entity_id: light.front_room
    type: turn_off
  mode: single
```

## Javascript errors shown in your browser console/inspector

```txt

```
