### ISSUE TITLE
MQTT Light publishes duplicate messages on single brightness change event

### ISSUE THREAD

**Issue by mweber88** [home-assistant/frontend#6516]
## The problem

When I make a single brightness change to the light by, say, tapping the brightness scale for the light in the Android app, Mosquitto sees two published messages when using the JSON template, and four published messages when using the default template. With the JSON template, the messages contain both the state and brightness values. With the default template, since I have the brightness topic separated, I get two state topic messages and two brightness topic messages.

When I turn the light either on or off, effectively initiating only a state change, Mosquitto broker sees one published message, which is perfect.

## Environment

- Home Assistant Core release with the issue: 0.112.4
- Last working Home Assistant Core release (if known): Unknown
- Operating environment (OS/Container/Supervised/Core): Container
- Integration causing this issue: light.mqtt
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/light.mqtt/

## Problem-relevant `configuration.yaml`

```yaml
  - platform: mqtt
    schema: json
    command_topic: "home/x10/ext/K2/set"
    state_topic: "home/x10/state/K2"
    brightness: true
    brightness_scale: 62
    unique_id: "light.K2"
    name: "Kitchen Cans"
    retain: false
  - platform: mqtt
    schema: default
    command_topic: "home/x10/std/L3/set/state"
    state_topic: "home/x10/state/L3/state"
    brightness_command_topic: "home/x10/std/L3/set/brightness"
    brightness_state_topic: "home/x10/state/L3/brightness"
    brightness: true
    brightness_scale: 22
    unique_id: "light.L3"
    name: "Living Room Indirect"
    retain: false
```

## Traceback/Error logs

```txt
NA
```

## Additional information

I switched from the JSON template to the default template because I thought maybe there was something specific with the JSON template causing this behavior, but apparently it’s also baked into the default template… or maybe how MQTT Light deals with brightness changes.
