### ISSUE TITLE
History graphs not refreshing at all

### ISSUE THREAD

**Issue by OrbitingOcelot** [home-assistant/frontend#6520]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

My lovelace UI history graph cards do not get refreshed. Never. The information is shown correctly, but it is never updated, only if I reload the page manually. Once the page is refreshed manually by pressing F5, the timeline is updated and the information shown correctly.

## Expected behavior

UI history graph cards should update periodically while the web page is open.

## Steps to reproduce

1. Download clean hass.io VDI image and install it in virtualbox.
2. Add a history graph card (optionally remove everything else from the UI).
4. Exit UI edit mode. Optionally reload the page.
5. Wait for refresh of the card -> never happens.
6. Hit F5 to reload page - new info appears.

## Environment

- Home Assistant release with the issue: Home Assistant 0.113.3
- Last working Home Assistant release (if known): not known
- Browser and browser version: Chrome 84.0.4147.105, Firefox 79.0. All add-ons disabled. Cache cleared.
- Operating system: Windows 10 Home 64 Bit

## State of relevant entities

sensor.compal_broadband_networks_inc_ch7465lg_packets_s_sent | 2.1 | unit_of_measurement: packets/s friendly_name: Compal Broadband Networks, Inc CH7465LG packets/s sent icon: mdi:server-network
-- | -- | --

## Problem-relevant configuration

Home UI reduced to two graphs to highlight the problem and rule out other issues:

```yaml
title: Home
views:
  - path: default_view
    title: Home
    badges: null
    cards:
      - type: history-graph
        entities:
          - entity: sun.sun
        hours_to_show: 1
        refresh_interval: 5
      - type: history-graph
        entities:
          - entity: sensor.compal_broadband_networks_inc_ch7465lg_packets_s_sent
        hours_to_show: 1
        refresh_interval: 5
```

## Javascript errors shown in your browser console/inspector

```txt
n/a
```

## Additional information

sis | vm
-- | --
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.8.3
supervisor | 229
timezone | UTC
version | 0.113.3
virtualenv | false
