### ISSUE TITLE
Background not working/showing in panel mode

### ISSUE THREAD

**Issue by NinDTendo** [home-assistant/frontend#6573]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have cleared the cache of my browser.

## The problem

Background is not showing/ working in Views with `panel: true`
I can sometimes see the background being loaded, but then "overshadowed" by a plain background color (white for default or dark grey, using google dark mode theme)

## Expected behavior

Expect the background to be shown instead of a plain background color.

## Steps to reproduce

```
Views: 
    - title: Main
      panel: true
      icon: mdi:crown
      path: main
      background: center / cover no-repeat url("/local/pictures/wall10.jpg")
      cards:
          -[...]
```
by setting `panel: false`, background is being shown.

## Environment

- Home Assistant release with the issue: 0.113.3
- Last working Home Assistant release (if known): /
- Browser and browser version: Chrome  84.0.4147.105
- Operating system: Win 10, HASS OS running on rasbperry pi 4

## Problem-relevant configuration

```
Views: 
    - title: Main
      panel: true
      icon: mdi:crown
      path: main
      background: center / cover no-repeat url("/local/pictures/wall10.jpg")
      cards:
          -[...]
```

## Additional information
`panel: true`
![image](https://user-images.githubusercontent.com/3543456/89714484-63771f00-d99f-11ea-8dfa-ec4758576a78.png)

`panel: false`
![image](https://user-images.githubusercontent.com/3543456/89714506-75f15880-d99f-11ea-962d-f5b82623c7aa.png)
