### ISSUE TITLE
0.114 Beta - Script and Automation Editors - Entire Choose section switches to YAML mode when typing data for service call

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#6577]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When adding service data to a **Call service** which has no data, the entire Choose section switches to YAML mode as soon as the first letter of the option name is typed:

![image](https://user-images.githubusercontent.com/2099542/89738523-3c891d80-da71-11ea-9454-6efb0da2a30e.png)

## Expected behavior

Only the action should switch to YAML mode, looking similar to the mockup below:

![image](https://user-images.githubusercontent.com/2099542/89738866-d3ef7000-da73-11ea-8726-debc6c639683.png)

## Steps to reproduce

1. Create a script, like the example below:
```
choose_test:
  alias: Choose Test
  mode: single
  sequence:
  - choose:
    - conditions:
      - after: sunrise
        before: sunset
        condition: sun
      sequence:
      - entity_id: light.bedside_light
        service: light.turn_on
    default: []
```
2. Edit the script in the UI.
3. Add `brightness_pct: 20` to the service data for the **light.turn_on** call.
4. As soon as "b" is typed the entire Choose section will show as the second screenshot, with the error message: `The value of "data" is not supported by the UI editor, we support "Object" but received ""b"".You can still edit your config in yaml.`

## Environment

- Home Assistant release with the issue: 0.114.0b3
- Last working Home Assistant release (if known):
- Browser and browser version: Google Chrome 84.0.4147.105
- Operating system: macOS Mojave 10.14.6

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
