### ISSUE TITLE
Sun condition automation is not consistent before after sunrise sunset

### ISSUE THREAD

**Issue by glmnet** [home-assistant/frontend#6587]
## The problem

Using automation editor,
We do a condition for day time:
Let's pretend a day is 15:00, now this is after sunrise and before sunset, condition is ok, automation triggers.

We do alike, a condition for nigh time:
Now if its 3:00 now this is before sunrise, but it's also before sunset of the same day, and we configured before sunrise and after sunset of course... automation does not trigger. Saying this is a bug or not, is quite a technisism.

Should this instead be a feature request to have sun condition accept a condition "Is night" or "Is day", this is a trap I believe 80% of people fall into, we want simple automatons to just work. E.g. iOS automation ask for Time, then it will offer During day, night, or between specific times, if you choose day or night it will allow you to select some offsets. I know what hass has already is more powerful, this bug report is more aimed at the trap of the Automation Editor UI not behaving as one would naturally expect.

## Environment

- Home Assistant Core release with the issue: 0.113
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): 
- Integration causing this issue: sun
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/sun/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by microfx** [comment]
This is not working still for me... it's never activated. 
<img width="916" alt="Bildschirmfoto 2022-04-07 um 13 37 18" src="https://user-images.githubusercontent.com/37987212/162190266-cb213979-3205-464d-acdf-f40e062e5843.png">

This node was not executed and so no further trace information is available.

<img width="575" alt="Bildschirmfoto 2022-04-07 um 13 38 09" src="https://user-images.githubusercontent.com/37987212/162190470-6f18804f-7087-4f11-b5b2-37ea979a316e.png">

```
alias: Kueche eMotion
description: ''
trigger:
  - type: motion
    platform: device
    device_id: b684927f214e572da70a26d1f0a0a862
    entity_id: binary_sensor.presence_3
    domain: binary_sensor
condition:
  - condition: sun
    before: sunset
    after: sunrise
action:
  - service: scene.turn_on
    target:
      entity_id: scene.kuche_nachtlicht
    metadata: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - wait_for_trigger:
      - type: no_motion
        platform: device
        device_id: b684927f214e572da70a26d1f0a0a862
        entity_id: binary_sensor.presence_3
        domain: binary_sensor
  - type: turn_off
    device_id: feafb8a064074c1ba73a816fa52ce7c9
    entity_id: light.eins
    domain: light
mode: single

```

The script is kinda broken … although it looked so straight forward. It's confusing for me! The tools to debug getting better. The conditions confuse me still.
