### ISSUE TITLE
Allow custom themes to have light and dark variants

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6588]
## The request

0.114 has an "auto" mode for the default theme which lets it show a light or dark variant depending on your OS appearance.  Really nice and useful. Would be cool if support for this was extended to custom themes as well.

Many theme creators already offer different variants of their themes for light and dark mode. For example, here is a collection of 20 [JuanMTech themes](https://www.juanmtech.com/themes-in-home-assistant/). It's really ten themes with light and dark variants, though. 

So the idea here is rather than having "MyCoolCustomTheme - Light" and "MyCoolCustomTheme - Dark", there would instead be a single "MyCoolCustomTheme" with light and dark variants that get intelligently switched based on OS appearance, much like the default theme. Idea of how the YAML could look:

```
MyCoolCustomTheme:
  dark_mode:
    primary-background-color: "black"
    primary-text-color: "white"
  light_mode:
    primary-background-color: "white"
    primary-text-color: "black"
 ```

Some benefits:
* This would make custom themes behave more intelligently
* Makes it easier for users to find and install themes. Less searching, less copy and pasting, etc.
* Also makes it easier for users to update their themes when the author updates them (or they break due to HA update etc)
* Would decrease the "Theme" dropdown in the users profile page in half, making it easier for them to find/switch between their themes.
