### ISSUE TITLE
group with nested groups shows toggle instead of state home/not_home

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#6599]
## The problem

a group containing only other groups shows a toggle (which is useless) instead of home/not_home. All contained groups are of the home/not_home type, since they contain device_trackers of mobile devices/persons etc.

desired solution: have these groups show home/not_home

## Environment

- Home Assistant Core release with the issue:  113.3
- Last working Home Assistant Core release (if known): not sure, but think never
- Operating environment (OS/Container/Supervised/Core):  OS
- Integration causing this issue: group
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/group/

## Problem-relevant `configuration.yaml`

```yaml
# for the group
  family_home:
    name: Familie Home
    icon: mdi:home-heart
    entities:
      - group.daughter_1
      - group.daughter_2
      - group.daughter_3
      - group.daughter_4
      - group.she
      - group.me

# lovelace card:
 - type: entities
    title: At home
    entities:
    #####
      - entity: group.family
        secondary_info: last-changed
      - entity: group.family_home
        secondary_info: last-changed
```

## Traceback/Error logs

NO errors
```txt

```

## Additional information
the first group contains individual entitities, the second contains the groups, 
<img width="385" alt="Schermafbeelding 2020-08-03 om 23 07 09" src="https://user-images.githubusercontent.com/33354141/89227651-5a243600-d5de-11ea-9e7d-51db1bd844a5.png">

which individually do show their correct state in the more-info of the group, as does the group itself:

<img width="392" alt="Schermafbeelding 2020-08-03 om 23 07 29" src="https://user-images.githubusercontent.com/33354141/89227850-b7b88280-d5de-11ea-82df-db7d426c99e2.png">

clicking the toggle is ineffective because an error is displayed it cant find a service device_tracker/turn_on, which is correct of course. and, though the toggle does change position, the entity doesnt change state.
