### ISSUE TITLE
entity_id: all is not supported

### ISSUE THREAD

**Issue by rgruyters** [home-assistant/frontend#6617]
When setting the `entity_id: all` for e.g. lights or media_player services the UI displays the following message and switch to YAML mode:

```
UI editor is not supported for this config:
  The value of "entity_id" is not supported by the UI editor, we support "entity id should be in the format 'domain.entity'" but received ""all"".
You can still edit your config in yaml.
```

Home Assistant info:
```yaml
arch: armv7
audio_input: null
audio_output: null
boot: true
image: homeassistant/raspberrypi3-homeassistant
ip_address: 172.30.32.1
last_version: 0.114.0
machine: raspberrypi3
port: 8123
ssl: false
version: 0.114.0
version_latest: 0.114.0
wait_boot: 600
watchdog: true
```
