### ISSUE TITLE
HA Frontpage does not load on my iPad

### ISSUE THREAD

**Issue by haegar33** [home-assistant/frontend#6618]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

For all browsers on my iPad (Safari, iCab) the HA frontpage at http://192.x.x.x:81234 does not load. You only see the background patter (blue bar on top), no text, no login fields

## Expected behavior

proper login prompt and UI page as before

## Steps to reproduce

1. open HA frontpage on Safari or iCab with http **not** https

## Environment

HA core installation (virtual Python3 env) on my Raspberry 3. At latest version 114
iPad at iOS 11.2 with corresponding Safari version

## Problem-relevant configuration

I was suspecting the trusted network settings to be reasponsible but enable/disable login does not solve the problem

```yaml
  auth_providers:
   - type: trusted_networks
     trusted_networks:
       - 192.168.178.0/24
       - fd00::/8
     trusted_users:
       192.168.178.0/24: bdxxxxxxx.
```
