### ISSUE TITLE
Lovelace creates "empty" column for conditional cards when cards are not shown

### ISSUE THREAD

**Issue by sgofferj** [home-assistant/frontend#6632]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
In its algorithm for organizing the cards, Lovelace also sometimes creates columns which only contain hidden conditional cards which breaks the layout.

![Screenshot_20200816_110057](https://user-images.githubusercontent.com/3258466/90329787-469aa700-dfb0-11ea-8532-897584eb000c.png)

## Expected behavior
Lovelace should not create "empty" columns. One possibility would be to append a hidden conditional card to the previous column.

## Steps to reproduce
Create a Lovelace dashboard with multiple conditional cards which are hidden.

## Environment
- Home Assistant release with the issue: 0.114.1 docker
- Last working Home Assistant release (if known): none
- Browser and browser version: Chrome latest, Firefox latest
- Operating system: Ubuntu 18.04, Windows 10

## State of relevant entities
N.a.

## Problem-relevant configuration
N.a.

## Javascript errors shown in your browser console/inspector
None

## Additional information
None

**Comment by sgofferj** [comment]
That seems to still persist in 117.5

**Comment by iantrich** [comment]
@sgofferj if an issue is open you can assume it still persists. No need to comment as such.

**Comment by sgofferj** [comment]
I am the reporter of the issue. My comment was in reply to the bot.

**Comment by bkupidura** [comment]
It still there.

**Comment by sgofferj** [comment]
Issue is still present in 2021.7.3.

**Comment by wormuths** [comment]
Same here.  I have different conditional cards configured to show for different weather scenarios, and the whole row is eaten by the blank cards that don't currently need to show.

![Conditional](https://user-images.githubusercontent.com/47436307/141602214-8d2a1979-0620-443c-9ba4-5afdd9bbf91b.png)

![Shown](https://user-images.githubusercontent.com/47436307/141602221-a5a9bd9e-30ea-47e9-89c3-6778e75a0c98.png)

**Comment by fikustommy** [comment]
I am also bothered by this very frustrating issue.
It seems the problem is that Lovelace creates a div column and populates it with hui-conditional-cards and applies style="display: none;" to them, but they are still taking up "space" in the column so that no other items can go there.

I tried using [state-switch](https://github.com/thomasloven/lovelace-state-switch) cards. This works great for replacing a card with another based off conditions, but there's no hiding a card completely because of the Lovelace root issue.
![image](https://user-images.githubusercontent.com/33975922/142877903-bbb23ac1-6fef-41a1-a0ff-9a5b8daef673.png)

**Comment by Bradford1138** [comment]
Same with the state-switch card in a grid card. [I have made a reddit post if more details can help](https://www.reddit.com/r/homeassistant/comments/s9dx9i/state_switch_card_not_showing_second_state_in_grid/)

**Comment by pejotigrek** [comment]
I can't believe it, but after all those years [I've found first appearence of this issue in the 2018...] this is still a problem!

no matter what card is used inside [stacks, grids etc.] the whole conditional card still is considered as "I am here, so display me!". this is annoying as hell, especially when the conditional content should "jump" to next column [even without the vertical-stack configured].

the whole right column [highlighted by me in developer's tools in chrome] should be gone, and therefore the left column should be centered
![image](https://user-images.githubusercontent.com/10796588/153865306-8dccb977-aad8-4de8-9b7c-a2b970bfbef4.png)

**Comment by OmgImAlexis** [comment]
I found a "workaround" just trying to find a way I can apply it.

The parent element needs to either not exist or the style that's applied to the child element needs to be removed from the child and applied to the `hui-conditional-card`.

For example in my case I have multiple `button-card` elements here. Each in a conditional to only show if they're set to `on`. If I move the styles from the `button-card` child to the `hui-conditional-card` parent it all works.

![image](https://user-images.githubusercontent.com/6525926/160227897-b10c7c0d-32f7-47aa-b47b-80fffeef60f0.png)


![image](https://user-images.githubusercontent.com/6525926/160227943-b0ff2855-7b8c-4f59-9af8-8aca70c8183f.png)

**Comment by FsxShader2012** [comment]
Issue still present in HA 2022.4.1

**Comment by nicolo-ribaudo** [comment]
@FsxShader2012 I understand that this bug is annoying (I am affected by it too), but it's not necessary to comment that "it's still present". If it was fixed, this issue would have obviously been closed.

**Comment by finder39** [comment]
I have also found a workaround, but its messy, tweaks a bit when the page is first opened, and requires work for each specific case.

Here is a gif with both the working and non-working examples on top of each other:
![Screen Recording 2022-04-16 at 4 01 53 PM](https://user-images.githubusercontent.com/518673/163693843-b53d8db3-1f55-4507-a6c3-f4d5ce0e1b8a.gif)

And here is that 'tweaking' i was talking about as a page opens or is switched to:
![Screen Recording 2022-04-16 at 4 02 10 PM](https://user-images.githubusercontent.com/518673/163693852-f0ea7b8a-4162-4f75-822a-4811d1cf10eb.gif)

Here is my code that makes it work:
```
- type: horizontal-stack
  cards:
    - type: 'custom:button-card'
      template: chip_icon_only
      variables:
        ulm_chip_icon_only: '🔥'

    - type: custom:mod-card
      card_mod:
        style: |
          :host {
            flex: 0 0 auto !important;
            {%- set sensor = states('binary_sensor.refrigerator_contact') %}
            {%- if sensor == 'off' %}display: none !important
            {%- endif %}
          }
      card:
        type: conditional
        conditions:
          - entity: binary_sensor.refrigerator_contact
            state: 'on'
        card:
          type: 'custom:button-card'
          template: chip_icon_only
          variables:
            ulm_chip_icon_only: '🧊'
          card_mod:
            style: |
              :host {
                width: 100% !important;
                max-width: none !important;
              }
    - type: 'custom:button-card'
      template: chip_icon_only
      variables:
        ulm_chip_icon_only: '🪨'
```

and here is the code that we expect to work but doesn't:
```
- type: horizontal-stack
  cards:
    - type: 'custom:button-card'
      template: chip_icon_only
      variables:
        ulm_chip_icon_only: '🔥'

    - type: conditional
      conditions:
        - entity: binary_sensor.refrigerator_contact
          state: 'on'
      card:
        type: 'custom:button-card'
        template: chip_icon_only
        variables:
          ulm_chip_icon_only: '🧊'

    - type: 'custom:button-card'
      template: chip_icon_only
      variables:
        ulm_chip_icon_only: '🪨'
```

I hope this helps someone, but I also hope we can get to the bottom of this so this isn't necessary anymore

**Comment by rigrig** [comment]
Still an issue: 
![image](https://user-images.githubusercontent.com/2941436/192974751-25bae3a5-5e60-4421-b806-d4c4de7ca29b.png)

Home Assistant 2022.9.7  
Supervisor 2022.09.1 
Operating System 9.0 
Frontend 20220907.2 - latest 
Firefox 105.0.1 (64-bit)

**Comment by sgofferj** [comment]
Can somebody please turn off the stale bot? I wouldn't say that's a minor issue and everybody who posted here will be following the issue and happily close it when it has been corrected.
@frenck ?

**Comment by s-hutter** [comment]
Since this issue never got the attention it deserves in my opinion, I decided to create a post on it for the current "What the heck?" month of October 2022: https://community.home-assistant.io/t/471426
Votes are very much welcome to finally give this old bug more visibility. 🙂

**Comment by stalegjelsten** [comment]
Hi all! I have also had this problem, but I have found a workaroud that works for me. I use a Lovelace dashboard that I manage through the user interface (no configuration.yaml).

To avoid the empty column I simply put my conditional cards into a grid card. So the hierarchy becomes Grid card → Conditional card → "Card to be displayed".

**Comment by cammcnab** [comment]
I tried this just now @stalegjelsten and couldn't get it to work… Maybe I'm doing it wrong. The conditional cards still hold a spot (column) even within a grid card. 

Did you wrap the entire dashboard in a grid card with multiple columns, or just that one column with a grid card (1 column grid) and the conditionals within that? Thanks in advance

**Comment by stalegjelsten** [comment]
Hi @cammcnab, I'm sorry but I may have been to quick to celebrate and getting your hopes up. It seems that it works for be because the priority of my newly created grid card is all the way at the bottom. If I "promote" the card by pressing the ↑ arrow while rearranging the cards, the column sometimes goes blank.

I have many different non-conditional cards in my Dashboard. I have grouped all my conditional cards into the grid card with 1 column so that it becomes a vertical stack.

**Comment by cammcnab** [comment]
@stalegjelsten Ahhh gotcha. Yeah that makes sense. No worries, was just excited for a fix to this!

**Comment by sandman98321** [comment]
It's bizarre to me that the WTH thread got so many votes, and this has been open so long, but there has never been any dev assignment or interaction about the issue.  Is there anything that can be done to at least get some attention?

**Comment by mrestorff** [comment]
I've given up on the integrated conditional card and switched to the [auto-entites card](https://github.com/thomasloven/lovelace-auto-entities), e.g.:

```
- type: "custom:auto-entities"
  filter:
    include:
      - entity_id: "sensor.easee_home_status"
        options:
          type: "custom:button-card"
          template: "chip_ev_charger"
    exclude:
      - state: "disconnected"
  card_param: cards
  card:
    type: custom:layout-card
    layout_type: grid
    layout_options:
      grid-template-columns: 1fr
      grid-template-rows: auto
      grid-gap: 0px 4px
      margin: "-4px -4px 0px -4px"
```

**Comment by karwosts** [comment]
This appears fixed after #16351. I create three big cards, they create three columns. I put the middle card in conditional and hide it. 
Now lovelace shows only two columns with no gap. 

Closing as fixed, feel free to comment if you still see issues.

**Comment by sgofferj** [comment]
@karwosts 
Not fixed.

![Screenshot_20230903_131051](https://github.com/home-assistant/frontend/assets/3258466/26925f53-62f5-49e0-b543-4e9da9ef5b17)

- Home Assistant 2023.8.4
- Supervisor 2023.08.1
- Operating System 10.5
- Frontend 20230802.1 - latest

**Comment by sgofferj** [comment]
Also with default HA theme...

![Screenshot_20230903_131846](https://github.com/home-assistant/frontend/assets/3258466/d330757e-5479-4480-8d89-199adc8c8d4a)

**Comment by karwosts** [comment]
@sgofferj - that "default" theme still looks very heavily modded. Have you tried with stock configuration?

**Comment by sgofferj** [comment]
Just forgot to hard reload the page after theme change. What is "stock configuration"? This is the default HA theme, unmodified:

![Screenshot_20230904_095357](https://github.com/home-assistant/frontend/assets/3258466/b932b114-0b97-466b-961e-40569c1bd1d3)

**Comment by karwosts** [comment]
Can you add the full yaml for the minimal dashboard that reproduces this?

Also I still see you have card-mod in the DOM, maybe try removing that as well.

**Comment by sgofferj** [comment]
```yaml
  - icon: mdi:remote-tv
    title: Remote
    path: remote
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# TV'
            card_mod:
              class: header
          - type: media-control
            entity: media_player.living_room_tv
            card_mod:
              class: middle
          - square: false
            columns: 2
            type: grid
            cards:
              - type: button
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    source: YouTube
                  target:
                    entity_id: media_player.living_room_tv
                icon: mdi:youtube
                name: YouTube
                hold_action:
                  action: none
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: webostv.command
                  data:
                    entity_id: media_player.living_room_tv
                    command: system.launcher/open
                    payload:
                      target: <redacted>
                  target: {}
                name: Jellyfin
                icon: mdi:shark-fin
                hold_action:
                  action: more-info
                entity: media_player.jellyfin_stefan_s_tv
                card_mod:
                  class: button-lozenge
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: webostv.command
                  data:
                    entity_id: media_player.living_room_tv
                    command: system.launcher/open
                    payload:
                      target: <redacted>
                  target: {}
                name: Garden
                icon: mdi:cctv
                hold_action:
                  action: none
                card_mod:
                  class: button-bullet
              - type: button
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    source: Photo & Video
                  target:
                    entity_id: media_player.living_room_tv
                name: Media
                icon: mdi:play
                hold_action:
                  action: none
                card_mod:
                  class: button-lozenge
              - type: button
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    source: Web Browser
                  target:
                    entity_id: media_player.living_room_tv
                name: Browser
                icon: mdi:web
                hold_action:
                  action: none
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: false
                type: button
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  target:
                    entity_id: media_player.living_room_tv
                  data:
                    source: Yle Areena
                name: YLE Areena
                icon: mdi:map
                hold_action:
                  action: none
                card_mod:
                  class: button-lozenge
          - type: media-control
            entity: media_player.jellyfin_stefan_s_tv
            card_mod:
              class: middle
          - type: markdown
            content: '## &nbsp;'
            card_mod:
              class: footer
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# Amplifier'
            card_mod:
              class: header
          - square: false
            columns: 2
            type: grid
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: switch.amplifier
                name: Power
                icon: mdi:power
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_vid1
                entity: switch.amp_vid1
                name: VID1
                card_mod:
                  class: button-lozenge
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_vid2
                entity: switch.amp_vid2
                name: VID2
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_vid3
                entity: switch.amp_vid3
                name: VID3
                card_mod:
                  class: button-lozenge
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_cd
                entity: switch.amp_cd
                name: CD
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_dvd
                entity: switch.amp_dvd
                name: DVD
                card_mod:
                  class: button-lozenge
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_vol_dec
                entity: switch.amp_vol_dec
                name: VOL -
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_vol_inc
                entity: switch.amp_vol_inc
                name: VOL +
                card_mod:
                  class: button-lozenge
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_surr
                entity: switch.amp_surr
                name: SURROUND
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_up
                entity: switch.amp_up
                name: Up
                card_mod:
                  class: button-lozenge
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_dn
                entity: switch.amp_dn
                name: Down
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  service_data: {}
                  target:
                    entity_id: switch.amp_night
                entity: switch.amp_night
                name: Night
                card_mod:
                  class: button-lozenge
          - type: markdown
            content: '## &nbsp;'
            card_mod:
              class: footer
      - type: conditional
        conditions:
          - entity: media_player.wohnzimmer
            state_not: unavailable
        card:
          type: vertical-stack
          cards:
            - type: markdown
              content: '# Living room player'
              card_mod:
                class: header
            - type: media-control
              entity: media_player.wohnzimmer
              card_mod:
                class: middle
            - type: markdown
              content: '## &nbsp;'
              card_mod:
                class: footer
      - type: conditional
        conditions:
          - entity: media_player.schlafzimmer
            state_not: unavailable
        card:
          type: vertical-stack
          cards:
            - type: markdown
              content: '# Bedroom player'
              card_mod:
                class: header
            - type: media-control
              entity: media_player.schlafzimmer
              card_mod:
                class: middle
            - type: markdown
              content: '## &nbsp;'
              card_mod:
                class: footer
      - type: conditional
        conditions:
          - entity: media_player.player_2
            state_not: unavailable
        card:
          type: vertical-stack
          cards:
            - type: markdown
              content: '# ESP32 player'
              card_mod:
                class: header
            - type: media-control
              entity: media_player.player_2
              card_mod:
                class: middle
            - square: false
              columns: 2
              type: grid
              cards:
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: call-service
                    service: media_player.play_media
                    data:
                      media_content_id: <redacted>
                      media_content_type: news
                      extra:
                        title: KJFK
                    target:
                      entity_id: media_player.player_2
                  name: KJFK
                  icon: mdi:airport
                  card_mod:
                    class: button-bullet
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: call-service
                    service: media_player.play_media
                    data:
                      media_content_id: <redacted>
                      media_content_type: news
                      extra:
                        title: EFJY
                    target:
                      entity_id: media_player.player_2
                  name: EFJY
                  icon: mdi:airport
                  card_mod:
                    class: button-lozenge
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: call-service
                    service: media_player.play_media
                    data:
                      media_content_id: <redacted>
                      media_content_type: news
                      extra:
                        title: EFJY
                    target:
                      entity_id: media_player.player_2
                  name: SWR3
                  icon: mdi:radio
                  card_mod:
                    class: button-bullet
                - show_name: true
                  show_icon: true
                  type: button
                  tap_action:
                    action: call-service
                    service: media_player.play_media
                    data:
                      media_content_id: <redacted>
                      media_content_type: news
                      extra:
                        title: ESSSG
                    target:
                      entity_id: media_player.player_2
                  name: ESSG
                  icon: mdi:airport
                  card_mod:
                    class: button-lozenge
            - type: markdown
              content: '## &nbsp;'
              card_mod:
                class: footer
```

I'll try removing card mod but it's gonna take a moment. I have a little bit full calendar at the moment.

**Comment by karwosts** [comment]
I put your yaml in my dashboard and it works as expected, no empty columns. 

![conditional](https://github.com/home-assistant/frontend/assets/32912880/1d068e72-ab29-48a2-9729-ee64d1169c30)

**Comment by karwosts** [comment]
> I can reproduce the issue in Firefox 117.0 but not Chrome 116.0.5845.141 - it appears that the CSS added in https://github.com/home-assistant/frontend/pull/16351 does not work in Firefox (the :has selector seems unsupported according to https://caniuse.com/css-has).

Good find, it appears you are correct. 

Note I maybe don't recommend enabling the `has` support in firefox, that creates other problems, see #17182.

I will reopen this as OP requested (though I'm not sure if a new firefox-specific issue makes sense instead).

**Comment by sgofferj** [comment]
@karwosts 

Thank you! I noticed a bunch of other problems I have with HA in Firefox which I just haven't gotten around to document properly yet. It seems, FF isn't tested by the HA devs :disappointed:

**Comment by sgofferj** [comment]
Issue persists

**Comment by s-hutter** [comment]
Under some circumstances, this is also still happening in Chrome.
Demo code for an affected dashboard:
```
views:
  - title: Demo
    cards:
      - type: entities
        entities:
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
      - type: entity-filter
        show_empty: false
        entities:
          - sun.sun
          - sun.sun
          - sun.sun
          - sun.sun
          - sun.sun
          - sun.sun
          - sun.sun
          - sun.sun
          - sun.sun
          - sun.sun
        state_filter:
          - always_hidden
        card:
          type: entities
      - type: conditional
        conditions:
          - entity: sun.sun
            state: always_hidden
        card:
          type: conditional
          conditions:
            - entity: sun.sun
              state: always_hidden
          card:
            type: entities
            entities:
              - entity: sun.sun
              - entity: sun.sun
              - entity: sun.sun
              - entity: sun.sun
              - entity: sun.sun
              - entity: sun.sun
              - entity: sun.sun
              - entity: sun.sun
              - entity: sun.sun
              - entity: sun.sun
      - type: entities
        entities:
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
```
