### ISSUE TITLE
state_color doesn't work with switch template within groups

### ISSUE THREAD

**Issue by xenz698** [home-assistant/frontend#6636]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem

The state_color doesn't work for any switch templates that listed INSIDE any group.
NOTE: not talking about Group icon itself, it's the switch template icon inside the group, not just any switch, only switch template.

## Expected behavior

Any other switches, eg. MQTT, command_line, Broadlink, icon will turn yellow when switch is on, except anything within switch template 

## Environment

- Home Assistant release with the issue: 108.2 all the way to 114.1
- Last working Home Assistant release (if known): 
- Browser and browser version: Chrome 84.0.4147.125 
- Operating system: Windows 10 1903

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```
switch:
- platform: template
  switches:
    fan:
      value_template: '{{ is_state("input_boolean.fan","on") }}'
      turn_on:
      - service: input_boolean.turn_on
        entity_id: input_boolean.fan
      turn_off:
      - service: input_boolean.turn_off
        entity_id: input_boolean.fan

group:
  basement:
    entities:
      - switch.fan

ui-lovelace.yaml
views:
  - titles: main tab
    cards:
    - type: entities
      state_color: true
      entities:
      - group.basement
```
The above will show a group name "basement" on the lovelace UI, when click on the basement group, it will show basement fan, when clicking on the basement fan on/off switch, the icon will not turn yellow.

if I copy everything into light domain, the icon will turn yellow when turn on. Of course will have to customize the icon and call it light.fan instead of switch.fan   eg
```
light:
- platform: template
  lights:
    fan:
      value_template: '{{ is_state("input_boolean.fan","on") }}'
      turn_on:
      - service: input_boolean.turn_on
        entity_id: input_boolean.fan
      turn_off:
      - service: input_boolean.turn_off
        entity_id: input_boolean.fan
```

## Javascript errors shown in your browser console/inspector

```txt

```
