### ISSUE TITLE
Display title on right side of the card

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/frontend#6645]
## The request

Add an option to display the title on the right side. This is useful if the title text is written in an RTL language (like Arabic) but the user doesn't want the whole interface to be RTL.
![Screenshot (58)_LI](https://user-images.githubusercontent.com/5123967/90489949-af1b8c80-e146-11ea-88c0-e0085047fa1a.jpg)

**Comment by spacegaier** [comment]
What would be the use case for having such a mixture of languages?

In your screenshot, what are those dates? Are the Arabic names for those dates coming from the integration in a local language? If the overall UI is English, why wouldn't you then also have the card title in English and just the date labels in Arabic?

**Comment by engrbm87** [comment]
In our country we use both Arabic and English. For me I prefer English for the main UI but there are some entities that I want to show in Arabic (such as the prayer times shown in the image, the names are changed by me in the entity property).
If it is possible to have the option for the title to align-right that would great.

**Comment by balloob** [comment]
This is not a feature that we should add to the frontend. It's too narrow of a use case. It can be achieved with a custom card.

**Comment by thomasloven** [comment]
[Card-mod](https://github.com/thomasloven/lovelace-card-mod) based solution:

![image](https://user-images.githubusercontent.com/1299821/99508038-6c0ac880-2984-11eb-9043-6f1d8b7aed62.png)

```yaml
type: entities
title: testing
entities:
  - light.55515875_66c04789
  - light.bed_light
  - light.ceiling_lights
style: |
  .card-header {
    flex-direction: row-reverse;
  }
```
