### ISSUE TITLE
Weather card precipitation lacks decimal formatting

### ISSUE THREAD

**Issue by thimic** [home-assistant/frontend#6648]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After updating to 0.114.x the weather card layout sometimes goes out of whack if the forecast contains precipitation data and this data has many decimals. I’m not sure if the issue was introduced by the weather integration (Met.no) suddenly reporting precipitation to many decimal places or if there’s been a change to the front end. 

From the forum I don’t seem to be the only one with this issue after updating to 0.114.x.

## Expected behavior

The weather card rounds precipitation values to one or two decimal places. 

The layout displays data as intended: Card name and full current temperature is shown.

## Steps to reproduce

Create a standard weather card and point it at a weather integration. Populate with the sensor data below.

## Environment

- Home Assistant release with the issue: 0.114.0-0.114.2
- Last working Home Assistant release (if known): 0.113.x
- Browser and browser version: Home Assistant iOS app, Chrome for iOS, Safari for iOS
- Operating system: iOS

## State of relevant entities

```yaml
temperature: 11.7
humidity: 76
pressure: 1014.9
wind_bearing: 43.5
wind_speed: 23.4
attribution: >-
  Weather forecast from met.no, delivered by the Norwegian Meteorological
  Institute.
forecast:
  - datetime: '2020-08-19T12:00:00+12:00'
    condition: rainy
    pressure: 1006.5
    humidity: 79.9
    wind_bearing: 19.6
    temperature: 12.8
    templow: 10.9
    precipitation: 74.10000000000001
    wind_speed: 30.2
    wind_gust: null
  - datetime: '2020-08-20T12:00:00+12:00'
    condition: rainy
    pressure: 992
    humidity: 86.4
    wind_bearing: 331.2
    temperature: 13.1
    templow: 10.9
    precipitation: 39.50000000000002
    wind_speed: 45.7
    wind_gust: null
  - datetime: '2020-08-21T12:00:00+12:00'
    condition: partlycloudy
    pressure: 990.6
    humidity: 79.4
    wind_bearing: 323.7
    temperature: 12.8
    templow: 10.5
    precipitation: 0.1
    wind_speed: 28.8
    wind_gust: null
  - datetime: '2020-08-22T12:00:00+12:00'
    condition: sunny
    pressure: 1004.6
    humidity: 69.9
    wind_bearing: 325.1
    temperature: 13
    templow: 9.9
    precipitation: 0.1
    wind_speed: 23.4
    wind_gust: null
  - datetime: '2020-08-23T12:00:00+12:00'
    condition: partlycloudy
    pressure: 1005.9
    humidity: 74.8
    wind_bearing: 92.8
    temperature: 13.4
    templow: 10.6
    precipitation: 5.3
    wind_speed: 18
    wind_gust: null
friendly_name: Home
```

Results in the following card:

![B6CA7D4F-FEFD-41C2-A8CB-DD9C4FB597E9](https://user-images.githubusercontent.com/9880865/90510553-4a484c80-e1af-11ea-9260-415b029ce952.jpeg)

## Problem-relevant configuration

```yaml
entity: weather.home
name: Home
type: weather-forecast
```

## Javascript errors shown in your browser console/inspector

```txt

```
