### ISSUE TITLE
Scene editor not working with Climate entities

### ISSUE THREAD

**Issue by gigatexel** [home-assistant/frontend#6651]
## The problem
I encountered this problem when defining a scene to turn off all A/C units in our house.
I defined a new scene, added al 4 climate entities. I set all states using the popup and saved the scene.
Specifically in this case, I set the operation mode to "off".
This results in the following scenes.yaml:
```
- id: '1597845223608'
  name: New Scene
  entities:
    climate.ouderkamer:
      current_temperature: 27
      fan_mode: Silence
      fan_modes:
      - Auto
      - Silence
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      friendly_name: Ouderkamer
      hvac_modes:
      - fan_only
      - dry
      - cool
      - heat
      - heat_cool
      - 'off'
      max_temp: 35
      min_temp: 7
      preset_mode: none
      preset_modes:
      - away
      - none
      state: 'off'
      supported_features: 57
      swing_mode: 'Off'
      swing_modes:
      - 'Off'
      - Vertical
      - Horizontal
      - 3D
      target_temp_step: 1
      temperature: 25
```
I think the "state": off statement is wrong. I think it should be hvac_mode: off

When activating the scene, the A/C is activated in stead of turned off. Also, when editing the scene, the climate entity defaults back to "cool"

## Environment

- Home Assistant Core release with the issue: 0.114.1
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): Supervised on Raspbian
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt
No errors appeared.

```

## Additional information
Tried to replicate the same behavior using standard automations, and this works.

```
- id: '1590672251117'
  alias: Airco uit in de ochtend
  description: ''
  trigger:
  - at: 07:00:00
    platform: time
  condition: []
  action:
  - data:
      hvac_mode: 'off'
    entity_id: climate.kindkamer_groot,climate.kindkamer_klein,climate.ouderkamer,climate.zolder
    service: climate.set_hvac_mode
```
