### ISSUE TITLE
Onboarding - password manager doesn't popup on iOS (Safari or iOS app)

### ISSUE THREAD

**Issue by devopsleigh** [home-assistant/frontend#6655]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When logging into Home Assistant, the password manager (Bitwarden in my case) pop up doesn’t appear using Safari naively or or the iOS app. This works just fine in Firefox.

## Expected behavior

Tapping the password field should make the password auto-fill prompt appear so I can access my vault.

## Steps to reproduce

1. Open Home Assistant in Safari (not previously authenticated)
2. Tap the password field and note the lack of password auto-fill prompt
3. Repeat the above in Firefox and the password prompt appears

## Environment

- Home Assistant release with the issue: 0.114.2 (Docker)
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Safari (iOS 14b5)
- Operating system: iOS
- FrontEnd:  20200811.0

## State of relevant entities

Not applicable

## Problem-relevant configuration

```yaml
default_config:

homeassistant:
  customize:   !include customize.yaml
  whitelist_external_dirs:
    - /config/www/

http:
  server_port:     !secret port
  ssl_certificate: !secret ssl_cert
  ssl_key:         !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5

frontend:
  themes: !include_dir_merge_named themes

discovery:
shopping_list:
automation:     !include automations.yaml
scene:          !include scenes.yaml
automation:     !include automations.yaml
scene:          !include scenes.yaml
script:         !include scripts.yaml
tts:            !include tts.yaml
mqtt:           !include mqtt.yaml
binary_sensor:  !include binary_sensors.yaml
sensor:         !include sensors.yaml
weather:        !include weather.yaml
camera:         !include cameras.yaml
```

## Javascript errors shown in your browser console/inspector

Not sure how to do this in iOS
