### ISSUE TITLE
Input number box (not slider) is clipped on mobile and more info displays incorrect value

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#6660]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Input number boxes are clipped on mobile:
Mobile:
![mobile](https://user-images.githubusercontent.com/10679300/90766009-51cd3a00-e304-11ea-98b9-52d1bc0d3878.jpeg)

Desktop:
![desktop](https://user-images.githubusercontent.com/10679300/90766021-57c31b00-e304-11ea-8679-e38187202012.png)

Additionally more-info pop-ups do ot display the value correctly (desktop and mobile):
![m-info](https://user-images.githubusercontent.com/10679300/90766080-6c071800-e304-11ea-8824-c9f7fc36a73c.png)

## Expected behavior
The ability to read and edit non-slider input numbers on mobile or in more info pop-ups on desktop and mobile devices.

## Steps to reproduce
Add the following sort of input number:
```
t31_daily_cost:
  name: T31 Daily Cost
  mode: box
  min: 0
  max: 100
  unit_of_measurement: "$/day"
  icon: mdi:currency-usd
```

Add the following card:
```
type: entities
title: Unit Costs
entities:
  - entity: input_number.t31_daily_cost
  - entity: input_number.t31_energy_cost
  - entity: input_number.t41_daily_cost
  - entity: input_number.t31_energy_cost
```
View on mobile and/or click entity to view pop-up.

NOTE: I managed to trick the app into displaying more digits by entering the following input number configuration:
```
t31_daily_cost:
  name: T31 Daily Cost
  mode: box
  min: 0.00000001
  max: 100.00000001
  unit_of_measurement: "$/day"
  icon: mdi:currency-usd
```
However the more info pop up still does not display the number correctly:
![m-info2](https://user-images.githubusercontent.com/10679300/90768071-a0c89e80-e307-11ea-931f-04d1420588c6.png)

I do not know what this is displaying but the value of the input number remained at 0.95193 even after the more-info box was closed.

## Environment

arch | x86_64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.56
python_version | 3.8.3
supervisor | 235
timezone | Australia/Hobart
version | 0.114.2
virtualenv | false

- Home Assistant release with the issue: 0.114.2
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Firefox 79.0 (64bit) , Chrome 84.0.4147.125 (Official Build) (64-bit), iOS app 
- Operating system: Windows 10 v1909

## State of relevant entities

```yaml
input_number.t31_daily_cost = 0.95193
```

## Problem-relevant configuration

```yaml
As above
```

## Javascript errors shown in your browser console/inspector

```txt
Nil.
```
