### ISSUE TITLE
Automation editor clobbers multiple state conditions

### ISSUE THREAD

**Issue by skylyn** [home-assistant/frontend#6664]
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem

Release 0.112 added [multiple state support](https://www.home-assistant.io/docs/scripts/conditions/#state-condition) for conditions in Automations.

This is great, so I have many automations now that trigger if I'm in one of several modes. eg:
```yaml
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state:
      - Night
      - Home
```
However, if I load this automation in the UI, the UI reads it in and displays it as 
![image](https://user-images.githubusercontent.com/4708347/90796889-bff20c80-e2c4-11ea-94d3-2993492f16fd.png)

and if I save any change to any part of this automation in the UI, it clobbers the condtion and becomes:
```yaml
condition: state
entity_id: input_select.home_mode
state: 'Sleep,Night'
```

## Expected behavior

Can open and edit automation in UI with multiple states and have it save in the correct format ie:
```yaml
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state:
      - Night
      - Home
```
instead of 
```yaml
condition: state
entity_id: input_select.home_mode
state: 'Sleep,Night'
```

## Steps to reproduce

1. Edit Automations.yaml manually and create an automation with a condition with multiple states such as:
```yaml
- id: trigger_good_morning
  alias: 'Trigger: Good Morning'
  trigger:
  - entity_id: binary_sensor.master_closet_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state:
      - Sleep
      - Night
  action:
  - data: {}
    service: script.good_morning
  mode: single
```
2. Go to the UI and load the automation "Trigger: Good Morning"
3. Without changing anything, press save.

## Environment

- Home Assistant release with the issue: 0.114.3
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Firefox Version 78.0.2 (64-bit) and Chrome 84.0.4147.89 and mobile app
- Operating system: Windows and Android

## State of relevant entities

n/a

## Problem-relevant configuration

see steps to reproduce

## Javascript errors shown in your browser console/inspector

n/a

**Comment by jasonalsing** [comment]
Wow I think we were writing these at the same time: https://github.com/home-assistant/frontend/issues/6665

**Comment by seblu** [comment]
I was hit by this issue recently. As I'm only looking for a state swap I replaced:
```yaml
      - condition: state
        entity_id: light.bathroom
        state:
        - 'on'
        - 'off'
        for: 2
```
by
```yaml
      - condition: template
        value_template: '{{ (now()-states.light.bathroom.last_changed).total_seconds() >= 120 }}'
```
to prevent any breakage when saving automation.
