### ISSUE TITLE
NWS Forecast has oversized icon for "Hot"

### ISSUE THREAD

**Issue by KennyStier61** [home-assistant/frontend#6680]
## Checklist

- [ x ] I have updated to the latest available Home Assistant version.
- [ x ] I have cleared the cache of my browser.
- [ x ] I have tried a different browser to see if it is related to my browser.

## The problem

Days that are listed as "Hot" in NWS forecast come up with an oversized exclamation mark

![Screenshot from 2020-08-23 12-14-31](https://user-images.githubusercontent.com/4749568/90983357-8414ac80-e53b-11ea-9283-5f56ad7d4f13.png)
![Screenshot from 2020-08-23 12-14-48](https://user-images.githubusercontent.com/4749568/90983358-86770680-e53b-11ea-82e6-826aeb932c7b.png)

## Expected behavior

A more descriptive icon, or at least one of a proper size

## Steps to reproduce

1. Add NWS integration for a location that has "Hot" in the upcoming forecast
2. Add Weather card to Lovelace
3. See the icon

## Environment

- Home Assistant release with the issue: 0.114.2
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Brave 1.12.112 (Chromium 84.0.4147.125)
- Operating system: Pop!_OS 20.04

## State of relevant entities

```yaml
  - detailed_description: >-
      A slight chance of rain showers before 8am. Mostly sunny. High near 93,
      with temperatures falling to around 90 in the afternoon. Southwest wind 5
      to 8 mph. Chance of precipitation is 20%. New rainfall amounts less than a
      tenth of an inch possible.
    temperature: 93
    datetime: '2020-08-24T06:00:00-04:00'
    daytime: true
    condition: exceptional
    precipitation_probability: 20
    wind_bearing: 225
    wind_speed: 6

```

## Problem-relevant configuration

Configured via Lovelace

## Javascript errors shown in your browser console/inspector

```txt
DevTools failed to load SourceMap: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/content_start/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/content/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/vendors/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
roku-card.js:186   ROKU-CARD       Version 1.1.4 

```
