### ISSUE TITLE
Entities Card does not highlight icon when 3 speed fan when on

### ISSUE THREAD

**Issue by ZetaPhoenix** [home-assistant/frontend#6685]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

When a 3 speed fan from ESPHome is exposed in an Entities Card, the slider will turn on but the fan icon is not highlighted showing the device is on.
![image](https://user-images.githubusercontent.com/1578743/91009532-9de2dd80-e595-11ea-8649-96cece13726d.png)

## Expected behavior

I would expect the icon to be the highlighted color like on the glances card:

## Steps to reproduce

Use the iFan02 example from ESPHome: https://esphome.io/cookbook/ifan02.html
Add the device to Home Assistant
Add the new fan in an Entities Card

## Environment

- Home Assistant release with the issue: 0.114.3
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 79.0, Safari (iOS app)
- Operating system: OSX, iOS

## State of relevant entities

```yaml
speed_list:
  - 'off'
  - low
  - medium
  - high
speed: medium
friendly_name: Main Bedroom Ceiling Fan
supported_features: 1
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ZetaPhoenix** [comment]
May be related to #6636 as both are about `fan` devices.

**Comment by bramkragten** [comment]
Have you enabled `state_color` for the entities card?

**Comment by ZetaPhoenix** [comment]
@bramkragten I have not done anything with `state_color` for the card and configured the card though the GUI. All of the other time I have an entities card the icon will highlight, IE lights.

**Comment by zsarnett** [comment]
You will need to turn the state_color option on (https://www.home-assistant.io/lovelace/entities/#state_color) to enable any other icons to show color. Lights state color is shown by default

**Comment by ZetaPhoenix** [comment]
@zsarnett This does and does not resolve the issue. I makes the fan highlight but then changes how the other sensors show up in the card as well. How do you affect just one entry? Why does a fan not get show by default?

**Comment by ZetaPhoenix** [comment]
@zsarnett, Can this be re-opened? The `state_color` option changes the behavior of the entire card and not just fan entity.

**Comment by zsarnett** [comment]
Correct it affects the whole card. This issue is for a bug that doesn't exist. If you want, you can create a feature request for the ability to turn state color on per entity

**Comment by ZetaPhoenix** [comment]
When I had template fans setup for the same devices when running Tasmota I did not need to add `state_color` to get the icons to highlight. After switching to ESPHome I am running to the issue on the frontend for the discovered device.

Is this not a bug?

Old fan template:
```yaml
fan:
  - platform: mqtt
    name: "Living Room Ceiling Fan"
    command_topic: "cmnd/livingroom-fan/FanSpeed"
    speed_command_topic: "cmnd/livingroom-fan/FanSpeed"
    state_topic: "stat/livingroom-fan/RESULT"
    speed_state_topic: "stat/livingroom-fan/RESULT"
    #state_value_template: "{% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.guest_bedroom_fan.state == 'off' -%}0{%- elif states.fan.guest_bedroom_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/livingroom-fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    qos: 1
    retain: false
    speeds:
      - 'off'
      - low
      - medium
      - high
```
