### ISSUE TITLE
More info dialog with Lights - color picker disappears in some cases (0.115.0b0)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6837]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When on the more info Lights dialog, when you toggle off a light and then toggle it back on, the color picker does not reappear. Tested with a Hue light strip. See image below:

![image](https://i.imgur.com/Ac1yb9P.png)

## Steps to reproduce

1. Open more info for a light entity
2. Toggle light off
3. Toggle light back on

The color picker will not re-appear, will just be an empty space where it belongs.

## Environment

- Home Assistant release with the issue: 0.115.0b0
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml
min_mireds: 153
max_mireds: 500
effect_list: colorloop, random
brightness: 24
hs_color: 33.767, 84.314
rgb_color: 255, 160, 39
xy_color: 0.561, 0.404
effect: none
friendly_name: Office Light Strip
supported_features: 63
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
