### ISSUE TITLE
Mjpeg Camera gives error in logs in 0.115.0b0

### ISSUE THREAD

**Issue by luca-angemi** [home-assistant/frontend#6862]
## The problem

Mjpeg Camera gives error in logs, altohugh nothing has changed in the configuration and there are no breaking changes for this platform.

## Environment

- Home Assistant Core release with the issue: 0.115.0b0
- Last working Home Assistant Core release (if known): 0.114.0
- Operating environment (OS/Container/Supervised/Core): Core
- Integration causing this issue: Mjpeg camera
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/mjpeg/

## Problem-relevant `configuration.yaml`

```yaml
camera:
  - platform: mjpeg
    name: Door
    mjpeg_url: http://192.168.1.52/media.live?videocodec=mjpeg
```

## Traceback/Error logs

```txt
2020-09-08 14:57:52 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: camera.door does not support play stream service

```
