### ISSUE TITLE
Graphs not rendering correct on some devices

### ISSUE THREAD

**Issue by Strixx76** [home-assistant/frontend#6875]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

Graphs not rendering correct on some devices some times.

## Expected behavior

Graphs to render correct

## Steps to reproduce

1. Create a couple of sensor cards so that they will show up in either 2, 3 or 4 columns.
2. Show them on a device which is rendering badly.

## Environment

- Home Assistant release with the issue: 0.114.4
- Last working Home Assistant release (if known): ?
- Browser and browser version: Chrome 85.0.4183.81, Home Assistant (companion app) 1.3.3-full
- Operating system: Android 7.1.1 / Android 6.0

## State of relevant entities

No patterns in sensor state found to be relevant for producing this issue, only the layout of the cards on the screen.
Seems as the issue occurs more often if the cards is placed inside an vertical stack

![Screenshot_2020-09-09-10-11-03-216](https://user-images.githubusercontent.com/17635047/92575200-56906880-f288-11ea-8e23-c994f3443785.jpeg)
Sensors card

![Screenshot_2020-09-09-10-10-40-698](https://user-images.githubusercontent.com/17635047/92575744-01088b80-f289-11ea-8b77-22f43dd67029.jpeg)
Custom mini-graph-card

## Problem-relevant configuration

```yaml
 - title: TEST2
    path: test2
    badges: []
    cards:
      - cards:
          - type: sensor
            graph: line
            entity: sensor.weatherstation_temp_out
            name: Ute
          - type: sensor
            graph: line
            entity: sensor.433_uterum_temp
            name: Uterum
          - type: sensor
            entity: sensor.average_downstairs
            graph: line
            name: Nere
          - type: sensor
            entity: sensor.average_upstairs
            graph: line
            name: Uppe
        type: vertical-stack
      - &ref_1
        type: sensor
        entity: sensor.weatherstation_temp_out
        graph: line
        name: Ute
      - type: sensor
        entity: sensor.433_uterum_temp
        graph: line
        name: Uterum
      - type: sensor
        entity: sensor.average_downstairs
        graph: line
        name: Nere
      - type: sensor
        entity: sensor.average_upstairs
        graph: line
        name: Uppe
      - *ref_1
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Never any issues using desktop browser.
Never any issues using a Huawei MediaPad T5 (Android 8.0, screen res.: 1920x1200)

Issues occurs on the following tested devices, both in Chrome and Android app:
Lenovo Tab 3 Plus, YT-X703F (Android 7.1.1, screen res.: 2560x1600)
Lenovo Tab M10 plus, TB-X704L (Android 7.1.1, screen res.: 1920x1200)
Lenovo Tab 2, A10-70F (Android 6.0, screen res.:1920x1200)

The issue is occurring more often on the the two last devises (because of screen resolution?)

Issue is even more visible when using custom card: https://github.com/kalkih/mini-graph-card
Same issue reported for mini-graph-card: https://github.com/kalkih/mini-graph-card/issues/422
