### ISSUE TITLE
Editing entities within cards not working anymore.

### ISSUE THREAD

**Issue by dreimer1986** [home-assistant/frontend#6883]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

After updating to the new beta0 and 1 I did not notice the problem, but now I wanted to add some new sensors from Android app to a existing Glance containing all of them. (1) First thing I see is that the added one is included as expected. (2) Fun starts when I remove one of the entites. The line should vanish, but it doesn't. No, the empty line shows up at the very beginning of the list now. (3) Adding another in there causes the mess you see. (4) The same happens when I create a new card.

## Expected behavior

It should work as before.

## Steps to reproduce

Already in the description.

## Environment

- Home Assistant release with the issue: 0.105.0B2
- Last working Home Assistant release (if known): 0.104.4
- Browser and browser version: Chrome 85.0.4183.102 and Firefox 75.0
- Operating system: Windows 10 2004

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
title: Home
views:
  - badges:
      - sensor.plex_reimi_nuc
      - sun.sun
      - weather.home
      - sensor.tautulli
    cards:
      - entities:
          - input_boolean.zigbee_permit_join
          - timer.zigbee_permit_join
          - sensor.bridge_state
        show_header_toggle: true
        title: Zigbee
        type: entities
      - entities:
          - entity: automation.sonnenaufgang_lampen_aus
          - entity: automation.telefonstatus
          - entity: automation.nacht_modus
          - entity: automation.alarmanlage
          - entity: automation.nachts_lampen_aus_wenn_abwesend
        title: Automatisierung
        type: entities
      - entities:
          - entity: light.esszimmer_light
          - entity: light.heimkino
          - entity: light.kino1_light
          - entity: light.kino2_light
          - entity: light.kommode_light
          - entity: light.schlafen1_light
          - entity: light.schlafen2_light
          - entity: light.schlafen3_light
          - entity: light.schlafzimmer
          - entity: light.schrank_light
          - entity: light.schranke
          - entity: light.wohnen1_light
          - entity: light.wohnen2_light
          - entity: light.wohnen3_light
          - entity: light.wohnen4_light
          - entity: light.wohnzimmer
        title: Licht
        type: entities
      - entity: media_player.samsung_ue55mu8009
        type: media-control
      - entity: media_player.schlafzimmer
        type: media-control
      - entity: media_player.verstarker
        type: media-control
      - entity: media_player.daniels_echo
        type: media-control
      - entity: media_player.daniels_echo_dot
        type: media-control
      - entities:
          - entity: switch.hassio
          - entity: switch.pc
          - entity: switch.server
          - entity: switch.xmas_2
          - entity: sensor.schalter1_click
          - entity: sensor.schalter2_click
          - entity: switch.doorbird_relay
        title: Schalter
        type: entities
      - entity: media_player.spotify_daniel_reimer
        type: media-control
      - type: media-control
        entity: media_player.plex_plex_for_windows_reimi_pc
    path: default_view
    title: Home
  - cards:
      - css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 196, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #dcfaff;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 196, .5);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #1278c4;
            --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 196, 0.7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 100, .7);
          }
        entity: sensor.zigbee2mqtt_networkmap
        font_size: 12
        force: 2000
        height: 498
        link_width: 2
        mqtt_base_topic: zigbee2mqtt
        node_size: 16
        panel: true
        type: 'custom:zigbee2mqtt-networkmap'
      - entities:
          - entity: binary_sensor.schlafen1_update_available
          - entity: binary_sensor.schlafen2_update_available
          - entity: binary_sensor.schlafen3_update_available
          - entity: binary_sensor.esszimmer_update_available
          - entity: binary_sensor.wohnen1_update_available
          - entity: binary_sensor.wohnen2_update_available
          - entity: binary_sensor.wohnen3_update_available
          - entity: binary_sensor.wohnen4_update_available
          - entity: binary_sensor.kino1_update_available
          - entity: binary_sensor.kino2_update_available
          - entity: binary_sensor.schrank_update_available
          - entity: binary_sensor.kommode_update_available
          - entity: binary_sensor.hue_motion_update_available
        type: entities
      - cards:
          - entity: sensor.schlafen1_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
          - entity: sensor.schlafen2_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
        type: horizontal-stack
      - cards:
          - entity: sensor.schlafen3_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
          - entity: sensor.esszimmer_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
        type: horizontal-stack
      - cards:
          - entity: sensor.wohnen1_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
          - entity: sensor.wohnen2_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
        type: horizontal-stack
      - cards:
          - entity: sensor.wohnen3_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
          - entity: sensor.wohnen4_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
        type: horizontal-stack
      - cards:
          - entity: sensor.kino1_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
          - entity: sensor.kino2_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
        type: horizontal-stack
      - cards:
          - entity: sensor.schrank_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
          - entity: sensor.kommode_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
        type: horizontal-stack
      - cards:
          - entity: sensor.motion_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
          - entity: sensor.hue_motion_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
        type: horizontal-stack
      - cards:
          - entity: sensor.schalter1_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
          - entity: sensor.schalter2_linkquality
            max: 150
            min: 0
            severity:
              green: 75
              red: 1
              yellow: 25
            theme: default
            type: gauge
        type: horizontal-stack
    title: Zigbee Netzwerk
  - badges:
      - sensor.cpu_temperatur
      - sensor.synology_temperature_sda
      - sensor.processor_use
      - binary_sensor.hdd_defect
      - binary_sensor.hdd_temp
      - sensor.hue_motion_battery
      - binary_sensor.motion_battery_low
      - binary_sensor.hue_motion_occupancy
      - binary_sensor.motion_occupancy
      - sensor.hue_motion_illuminance
      - sensor.synology_status_volume_1
      - sensor.schalter1_battery
      - sensor.schalter2_battery
      - binary_sensor.iss
    cards:
      - columns: 4
        entities:
          - entity: sensor.synology_temperature_sda
          - entity: sensor.synology_temperature_sdb
          - entity: sensor.synology_temperature_sdc
          - entity: sensor.synology_temperature_sdd
          - entity: sensor.nas3_laufwerk_1_status
          - entity: sensor.nas3_laufwerk_2_status
          - entity: sensor.nas3_laufwerk_3_status
          - entity: sensor.nas3_laufwerk_4_status
          - entity: sensor.synology_status_smart_sda
          - entity: sensor.synology_status_smart_sdb
          - entity: sensor.synology_status_smart_sdc
          - entity: sensor.synology_status_smart_sdd
          - entity: binary_sensor.nas3_laufwerk_1_exceeded_max_bad_sectors
          - entity: binary_sensor.nas3_laufwerk_2_exceeded_max_bad_sectors
          - entity: binary_sensor.nas3_laufwerk_3_exceeded_max_bad_sectors
          - entity: binary_sensor.nas3_laufwerk_4_exceeded_max_bad_sectors
          - entity: binary_sensor.nas3_laufwerk_1_below_min_remaining_life
          - entity: binary_sensor.nas3_laufwerk_2_below_min_remaining_life
          - entity: binary_sensor.nas3_laufwerk_3_below_min_remaining_life
          - entity: binary_sensor.nas3_laufwerk_4_below_min_remaining_life
        show_state: true
        title: NAS Temperatur/Status
        type: glance
      - columns: 3
        entities:
          - entity: sensor.cert_expiry_fb_dreimer_de
          - entity: sensor.cert_expiry_nas_dreimer_de
          - entity: sensor.cert_expiry_ha_dreimer_de
          - entity: sensor.cert_expiry_repeater_dreimer_de
          - entity: sensor.cert_expiry_dreimer1986_spdns_de_32400
          - entity: sensor.cert_expiry_tautulli_dreimer_de
        title: Zertifikate
        type: glance
      - camera_view: live
        entity: camera.camera_mainstream
        type: picture-entity
      - columns: 3
        entities:
          - entity: sensor.hassio_temp
          - entity: sensor.cine_temp
          - entity: sensor.hue_motion_temperature
          - entity: sensor.motion_temperature
          - entity: sensor.living_temp
        title: Temperaturen
        type: glance
      - columns: 3
        entities:
          - entity: sensor.glances_c_used_percent
          - entity: sensor.glances_c_used
          - entity: sensor.glances_c_free
          - entity: sensor.glances_swap_used_percent
          - entity: sensor.glances_total
          - entity: sensor.glances_ram_used_percent
          - entity: sensor.glances_swap_used
          - entity: sensor.glances_thread
          - entity: sensor.glances_ram_used
          - entity: sensor.glances_swap_free
          - entity: sensor.glances_sleeping
          - entity: sensor.glances_ram_free
          - entity: sensor.glances_running
          - entity: sensor.glances_cpu_used
        title: Server
        type: glance
      - dark_mode: false
        default_zoom: 11
        entities:
          - entity: device_tracker.hd1913
        hours_to_show: 24
        type: map
      - entities:
          - binary_sensor.fritzlinked
          - binary_sensor.fritzconnected
          - sensor.fritz_netmonitor
          - sensor.phone
          - sensor.fritzexip
          - sensor.fritzuptime
          - sensor.fritzsentmb
          - sensor.fritzrecmb
          - sensor.fritzcurrup
          - sensor.fritzcurrdown
          - sensor.fritzmaxup
          - sensor.fritzmaxdown
        show_header_toggle: false
        title: Fritz Box
        type: entities
      - cards:
          - cards:
              - entity: sensor.memory_use_percent
                max: 100
                min: 0
                severity:
                  green: 0
                  red: 70
                  yellow: 30
                theme: default
                type: gauge
              - entity: sensor.swap_use_percent
                max: 100
                min: 0
                severity:
                  green: 0
                  red: 70
                  yellow: 30
                theme: default
                type: gauge
            type: horizontal-stack
          - cards:
              - entity: sensor.disk_use_percent_home
                max: 100
                min: 0
                severity:
                  green: 0
                  red: 70
                  yellow: 30
                theme: default
                type: gauge
              - entity: sensor.processor_use
                max: 100
                min: 0
                severity:
                  green: 0
                  red: 70
                  yellow: 30
                theme: default
                type: gauge
            type: horizontal-stack
        type: vertical-stack
      - columns: 2
        entities:
          - entity: sensor.hacs
          - entity: binary_sensor.updater
        title: Updates
        type: glance
      - entities:
          - entity: binary_sensor.hue_motion_occupancy
            name: Hue Motion
          - entity: binary_sensor.motion_occupancy
            name: Motion
        hours_to_show: 24
        refresh_interval: 0
        title: Motion
        type: history-graph
      - cards:
          - entity: sensor.germany_coronavirus_current
            graph: line
            hours_to_show: 168
            name: Corona Current / 7 days
            type: sensor
          - entity: sensor.germany_coronavirus_deaths
            graph: line
            hours_to_show: 168
            name: Corona Deaths / 7 days
            type: sensor
          - entity: sensor.germany_coronavirus_recovered
            graph: line
            hours_to_show: 168
            name: Corona Recovered / 7 days
            type: sensor
        type: vertical-stack
    title: Überwachung
  - badges: []
    cards:
      - columns: 2
        entities:
          - entity: device_tracker.hd1913
          - entity: sensor.hd1913_geocoded_location
        show_icon: true
        show_name: true
        title: Ortung Handy
        type: glance
      - columns: 2
        entities:
          - entity: device_tracker.sm_t819
          - entity: sensor.sm_t819_geocoded_location
        show_icon: true
        show_name: true
        title: Ortung Tablet
        type: glance
    path: mobile
    title: Mobile
  - badges: []
    cards:
      - entity: alarm_control_panel.alarmanlage
        states:
          - arm_home
          - arm_away
        type: alarm-panel
    path: alarmanlage
    title: Alarmanlage

```

## Javascript errors shown in your browser console/inspector

```txt
zigbee2mqtt-networkmap.js:7 [Violation] 'setTimeout' handler took 60ms
[Violation] Forced reflow while executing JavaScript took 30ms
[Violation] 'setInterval' handler took 89ms
[Violation] 'setInterval' handler took 66ms
[Violation] Forced reflow while executing JavaScript took 37ms
[Violation] 'setInterval' handler took 2702ms
[Violation] 'setInterval' handler took 2610ms
chunk.6d296d3fb5b06cb356ab.js:1 Uncaught r {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…end_latest/chunk.aec31b3f7d5bd71fbf0f.js:42:1128)"}mark: undefinedmessage: "unacceptable kind of an object to dump [object Undefined]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object Undefined]"stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]↵    at S (https://REMOVED.local/frontend_latest/chunk.6d296d3fb5b06cb356ab.js:2:61115)↵    at https://REMOVED.local/frontend_latest/chunk.6d296d3fb5b06cb356ab.js:2:60670↵    at S (https://REMOVED.local/frontend_latest/chunk.6d296d3fb5b06cb356ab.js:2:60797)↵    at https://REMOVED.local/frontend_latest/chunk.6d296d3fb5b06cb356ab.js:2:60011↵    at S (https://REMOVED.local/frontend_latest/chunk.6d296d3fb5b06cb356ab.js:2:60116)↵    at _ (https://REMOVED.local/frontend_latest/chunk.6d296d3fb5b06cb356ab.js:2:61705)↵    at https://REMOVED.local/frontend_latest/chunk.6d296d3fb5b06cb356ab.js:2:61792↵    at HTMLElement.value (https://REMOVED.local/frontend_latest/chunk.aec31b3f7d5bd71fbf0f.js:1:34615)↵    at HTMLElement.value (https://REMOVED.local/frontend_latest/chunk.aec31b3f7d5bd71fbf0f.js:42:378)↵    at HTMLElement.<anonymous> (https://REMOVED.local/frontend_latest/chunk.aec31b3f7d5bd71fbf0f.js:42:1128)"__proto__: Errorconstructor: ƒ r(t,e)arguments: (...)caller: (...)length: 2name: "r"prototype: Error {constructor: ƒ, toString: ƒ}constructor: ƒ r(t,e)toString: ƒ (t)__proto__: Object__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[FunctionLocation]]: chunk.6d296d3fb5b06cb356ab.js:1[[Scopes]]: Scopes[1]toString: ƒ (t)arguments: (...)caller: (...)length: 1name: ""prototype: {constructor: ƒ}__proto__: ƒ ()[[FunctionLocation]]: chunk.6d296d3fb5b06cb356ab.js:1[[Scopes]]: Scopes[1]__proto__: constructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()arguments: (...)caller: (...)length: 1name: "isPrototypeOf"__proto__: ƒ ()[[Scopes]]: Scopes[0]propertyIsEnumerable: ƒ propertyIsEnumerable()arguments: (...)caller: (...)length: 1name: "propertyIsEnumerable"__proto__: ƒ ()[[Scopes]]: Scopes[0]toLocaleString: ƒ toLocaleString()arguments: (...)caller: (...)length: 0name: "toLocaleString"__proto__: ƒ ()[[Scopes]]: Scopes[0]toString: ƒ toString()arguments: (...)caller: (...)length: 0name: "toString"__proto__: ƒ ()[[Scopes]]: Scopes[0]valueOf: ƒ valueOf()arguments: (...)caller: (...)length: 0name: "valueOf"__proto__: ƒ ()[[Scopes]]: Scopes[0]__defineGetter__: ƒ __defineGetter__()arguments: (...)caller: (...)length: 2name: "__defineGetter__"__proto__: ƒ ()[[Scopes]]: Scopes[0]__defineSetter__: ƒ __defineSetter__()arguments: (...)caller: (...)length: 2name: "__defineSetter__"__proto__: ƒ ()[[Scopes]]: Scopes[0]__lookupGetter__: ƒ __lookupGetter__()arguments: (...)caller: (...)length: 1name: "__lookupGetter__"__proto__: ƒ ()[[Scopes]]: Scopes[0]__lookupSetter__: ƒ __lookupSetter__()arguments: (...)caller: (...)length: 1name: "__lookupSetter__"__proto__: ƒ ()[[Scopes]]: Scopes[0]get __proto__: ƒ __proto__()arguments: (...)caller: (...)length: 0name: "get __proto__"__proto__: ƒ ()[[Scopes]]: Scopes[0]set __proto__: ƒ __proto__()arguments: (...)caller: (...)length: 1name: "set __proto__"__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]No properties
S @ chunk.6d296d3fb5b06cb356ab.js:1
(anonymous) @ chunk.6d296d3fb5b06cb356ab.js:1
S @ chunk.6d296d3fb5b06cb356ab.js:1
(anonymous) @ chunk.6d296d3fb5b06cb356ab.js:1
S @ chunk.6d296d3fb5b06cb356ab.js:1
_ @ chunk.6d296d3fb5b06cb356ab.js:1
(anonymous) @ chunk.6d296d3fb5b06cb356ab.js:1
value @ chunk.aec31b3f7d5bd71fbf0f.js:1
value @ chunk.aec31b3f7d5bd71fbf0f.js:991
(anonymous) @ chunk.aec31b3f7d5bd71fbf0f.js:991
n @ app.4c0ae78c.js:1
value @ chunk.c448994df52482ddf15d.js:7732
handleEvent @ app.4c0ae78c.js:1
__boundHandleEvent @ app.4c0ae78c.js:1
n @ app.4c0ae78c.js:1
value @ chunk.c448994df52482ddf15d.js:7263
handleEvent @ app.4c0ae78c.js:1
__boundHandleEvent @ app.4c0ae78c.js:1
n @ app.4c0ae78c.js:1
(anonymous) @ chunk.c448994df52482ddf15d.js:2259
setTimeout (async)
value @ chunk.c448994df52482ddf15d.js:2259
value @ chunk.c448994df52482ddf15d.js:2259
handleEvent @ app.4c0ae78c.js:1
__boundHandleEvent @ app.4c0ae78c.js:1
E @ app.4c0ae78c.js:1
P @ app.4c0ae78c.js:1
w @ app.4c0ae78c.js:1
(anonymous) @ app.4c0ae78c.js:1
_propertiesChanged @ app.4c0ae78c.js:1
_flushProperties @ app.4c0ae78c.js:18831
_flushProperties @ app.4c0ae78c.js:1
_invalidateProperties @ app.4c0ae78c.js:1
_setProperty @ app.4c0ae78c.js:1
Object.defineProperty.set @ app.4c0ae78c.js:18831
_selectedItemChanged @ chunk.a26386d87ac964c98d76.js:474
R @ app.4c0ae78c.js:1
w @ app.4c0ae78c.js:1
_ @ app.4c0ae78c.js:1
_propertiesChanged @ app.4c0ae78c.js:1
_flushProperties @ app.4c0ae78c.js:18831
_flushProperties @ app.4c0ae78c.js:1
_invalidateProperties @ app.4c0ae78c.js:1
_setProperty @ app.4c0ae78c.js:1
Object.defineProperty.set @ app.4c0ae78c.js:18831
_onClosed @ chunk.a26386d87ac964c98d76.js:474
_openedChanged @ chunk.a26386d87ac964c98d76.js:474
x @ app.4c0ae78c.js:1
w @ app.4c0ae78c.js:1
_ @ app.4c0ae78c.js:1
_propertiesChanged @ app.4c0ae78c.js:1
_flushProperties @ app.4c0ae78c.js:18831
_flushProperties @ app.4c0ae78c.js:1
_invalidateProperties @ app.4c0ae78c.js:1
_setProperty @ app.4c0ae78c.js:1
Object.defineProperty.set @ app.4c0ae78c.js:18831
close @ chunk.a26386d87ac964c98d76.js:474
_overlaySelectedItemChanged @ chunk.a26386d87ac964c98d76.js:474
_onItemClick @ chunk.a26386d87ac964c98d76.js:4342
(anonymous) @ app.4c0ae78c.js:1
(anonymous) @ app.4c0ae78c.js:1
```

## Additional information

1.
![1](https://user-images.githubusercontent.com/29841368/92604587-f661ec80-f2b0-11ea-8dd8-b8a62fea882f.PNG)

2.
![2](https://user-images.githubusercontent.com/29841368/92604596-f82bb000-f2b0-11ea-9959-e7c3a4a84c83.PNG)

3.
![3](https://user-images.githubusercontent.com/29841368/92604606-fa8e0a00-f2b0-11ea-8b34-f049f87da6d5.PNG)

4.
![4](https://user-images.githubusercontent.com/29841368/92604609-fcf06400-f2b0-11ea-8789-37d355260426.PNG)
