### ISSUE TITLE
Hold_action doesn't work after updating to 0.115b

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/frontend#6905]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After updating to 0.115 beta (started with b0 and still exists on b4) the `hold_action` doesn't work if i long tap.
I tried this on the web browser and android app.
The problem is only fixed by editing the card and changing the `hold_action` option then save. Afterwards the long press starts working for that item.
## Expected behavior

Long pressing on an item should trigger the action defined under `hold_action`
## Environment

- Home Assistant release with the issue: 0.115b4
- Last working Home Assistant release (if known): 0.114
- Browser and browser version: latest firefox browser and android app
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Can't reproduce, what's your config?

**Comment by engrbm87** [comment]
Here is one of the cards i have 
``` yaml
aspect_ratio: 16x9
entities:
  - entity: light.living_room_light1
  - entity: light.living_room_light2
entity: light.living_room_backlight
image: /local/living_room.jpg
tap_action:
  action: toggle
title: Living Room
type: picture-glance
```
![Screenshot (61)](https://user-images.githubusercontent.com/5123967/92717841-97ac7980-f369-11ea-8faf-9cb2310036ae.png)
