### ISSUE TITLE
Device tracker should show away instead of not_home

### ISSUE THREAD

**Issue by tyjtyj** [home-assistant/frontend#6971]
## The request
Device tracker in entity card show not_home while badge shows away. Both should show away

## Additional information
![image](https://user-images.githubusercontent.com/5368474/93011913-ab581a00-f5cd-11ea-8263-54f589a374a5.png)

**Comment by bramkragten** [comment]
This should be translated, and is working here.

Is this a default card? Share your config.

**Comment by tyjtyj** [comment]
Just simple entity card with google maps tracker

Since you think it is a bug i provided more screen shot

```
  - title: Automation
    icon: mdi:cog
    cards:
      - type: entities
        title: 'Person'
        show_header_toggle: false
        state_color: true
        entities:          
          - device_tracker.google_maps_1091574334xxxxxxxxxxxxx
          - device_tracker.google_maps_1021231999xxxxxxxxxxxxx
          - device_tracker.google_maps_1008191652xxxxxxxxxxxxx
```

![image](https://user-images.githubusercontent.com/5368474/93017265-e53f1580-f5f9-11ea-868e-a6ba5331693e.png)
