### ISSUE TITLE
Picture cards playing camera audio

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/frontend#6981]
## Checklist

- [Y ] I have updated to the latest available Home Assistant version.
- [Y ] I have cleared the cache of my browser.
- [Y ] I have tried a different browser to see if it is related to my browser.

## The problem

Camera stream in a picture-entity and picture-glance cards are playing audio in frontend without ability to mute. When opening the more-info box for the camera, I get a second (out of sync) audio stream from the same camera.

This happens in Chrome on desktop, using Fully Kiosk on some wall mounted Android tablets, and in the iOS app.

## Expected behavior

Audio to be muted by default, only to play audio when opened in more-info.

## Steps to reproduce

See below config, my camera is coming in using the UVC integration:
https://www.home-assistant.io/integrations/uvc/

## Environment

- Home Assistant release with the issue: 0.115.0b9
- Last working Home Assistant release (if known): New feature, no audio at all before (not even in more-info card)
- Browser and browser version: Multiple
- Operating system: Multiple

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
  - type: picture-glance
    title: Front Door
    entities:
      - light.outside_front
    camera_image: camera.front_door
    camera_view: live
```

## Javascript errors shown in your browser console/inspector

```txt

```
