### ISSUE TITLE
Weather card forecast exclamation icon 

### ISSUE THREAD

**Issue by mattsheffiel** [home-assistant/frontend#6991]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

My weather forecast card is showing a circular icon with an exclamation mark in place of several of the condition icons. See image below. I am using the National Weather Service as a data source.

![HA Weather Formatting Error](https://user-images.githubusercontent.com/29007028/93101525-fe82a900-f66f-11ea-9d5a-0c031c422bd7.png)

## Expected behavior

Normally weather condition icons would be show here. If this is indicating an unexpected response from the NWS API I could expect the icon to match the sizing of the other icons.

## Steps to reproduce

Unsure. It seems to only happen occasionally. Of note my area is expecting tropical storm/hurricane conditions so perhaps the issue could be related to this.

## Environment

- Home Assistant release with the issue: 0.114.4
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Firefox 80.0.1, Chrome 73.0.3683.75, Home Assistant iOS App 2020.5.2
- Operating system: HassOS 4.12

## State of relevant entities

I have not been able to catch the state data while the card is exhibiting this issue. I will add this information if I am able to grab it while the card is in this state.
```yaml

```

## Problem-relevant configuration

```yaml
entity: weather.khbg_daynight
name: Purvis
type: weather-forecast
secondary_info_attribute: humidity
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
This was fixed in a prior release 
![image](https://user-images.githubusercontent.com/18730868/93107054-b87d1380-f676-11ea-803c-5058a16e39c8.png)

Not sure why you are still seeing this

**Comment by mattsheffiel** [comment]
Is there anything I could do to gather additional information that might be useful? I've been trying to figure out if there is a way to retrieve the historic state data that triggered the strange icons but haven't been able to figure out a way to do so.

**Comment by zsarnett** [comment]
hmm I think the only thing that could be useful is inspecting the page and inspect that Icon `<ha-icon>` and show us what is rendered in the DOM (HTML)

Its interesting that it happens on Chrome which is what I use to test...

**Comment by mattsheffiel** [comment]
I just had it happen again. I double checked and it is indeed happening in Chrome, Firefox, and the iOS App. The attached image is showing one of the exclamation icons I mentioned in the developer tools in Chrome.

![Inspector Screencap](https://user-images.githubusercontent.com/29007028/93114250-fd597800-f67f-11ea-8314-7cd5d51ac6cf.png)

I also managed to get the state data. It looks like the "exceptional" condition is what is causing it to show up.

```
temperature: 82
humidity: 72
pressure: 29.98
wind_bearing: 40
wind_speed: 9
visibility: 10
attribution: Data from National Weather Service/NOAA
forecast:
  - detailed_description: >-
      A chance of showers and thunderstorms between 1pm and 4pm, then showers
      and thunderstorms likely. Mostly cloudy. High near 87, with temperatures
      falling to around 82 in the afternoon. Northeast wind around 15 mph, with
      gusts as high as 25 mph. Chance of precipitation is 70%. New rainfall
      amounts between a tenth and quarter of an inch possible.
    temperature: 87
    datetime: '2020-09-14T11:00:00-05:00'
    daytime: true
    condition: lightning-rainy
    precipitation_probability: 70
    wind_bearing: 45
    wind_speed: 15
  - detailed_description: >-
      Tropical storm conditions possible. Showers and thunderstorms likely.
      Mostly cloudy, with a low around 73. Chance of precipitation is 60%. New
      rainfall amounts between a quarter and half of an inch possible.
    temperature: 73
    datetime: '2020-09-14T18:00:00-05:00'
    daytime: false
    condition: exceptional
    precipitation_probability: 60
    wind_bearing: null
    wind_speed: null
  - detailed_description: >-
      Tropical storm conditions possible. A chance of rain showers before 7am,
      then rain likely between 7am and 1pm, then rain and a slight chance of
      thunderstorms. Cloudy. High near 79, with temperatures falling to around
      75 in the afternoon. Chance of precipitation is 90%. New rainfall amounts
      between a half and three quarters of an inch possible.
    temperature: 79
    datetime: '2020-09-15T06:00:00-05:00'
    daytime: true
    condition: exceptional
    precipitation_probability: 90
    wind_bearing: null
    wind_speed: null
  - detailed_description: >-
      Tropical storm conditions expected. Rain and a slight chance of
      thunderstorms before 7pm, then rain showers between 7pm and 1am, then rain
      and a slight chance of thunderstorms. Some of the storms could produce
      heavy rain. Cloudy, with a low around 72. Chance of precipitation is 90%.
      New rainfall amounts in excess of 4 inches possible.
    temperature: 72
    datetime: '2020-09-15T18:00:00-05:00'
    daytime: false
    condition: exceptional
    precipitation_probability: 90
    wind_bearing: null
    wind_speed: null
  - detailed_description: >-
      Tropical storm conditions possible. Rain and a slight chance of
      thunderstorms before 1pm, then showers and thunderstorms. Some of the
      storms could produce heavy rain. Cloudy, with a high near 79. Chance of
      precipitation is 80%. New rainfall amounts in excess of 4 inches possible.
    temperature: 79
    datetime: '2020-09-16T06:00:00-05:00'
    daytime: true
    condition: exceptional
    precipitation_probability: 80
    wind_bearing: null
    wind_speed: null
  - detailed_description: >-
      Tropical storm conditions possible. Showers and thunderstorms before 7pm,
      then a chance of rain and a slight chance of thunderstorms between 7pm and
      1am, then a chance of rain showers. Mostly cloudy, with a low around 70.
      Chance of precipitation is 80%. New rainfall amounts between a quarter and
      half of an inch possible.
    temperature: 70
    datetime: '2020-09-16T18:00:00-05:00'
    daytime: false
    condition: exceptional
    precipitation_probability: 80
    wind_bearing: null
    wind_speed: null
  - detailed_description: >-
      A chance of rain showers before 7am, then a chance of showers and
      thunderstorms. Mostly cloudy, with a high near 80. Northwest wind around 5
      mph, with gusts as high as 20 mph. Chance of precipitation is 50%.
    temperature: 80
    datetime: '2020-09-17T06:00:00-05:00'
    daytime: true
    condition: lightning-rainy
    precipitation_probability: 50
    wind_bearing: 315
    wind_speed: 5
  - detailed_description: >-
      A chance of showers and thunderstorms before 7pm, then a chance of
      thunderstorms and a chance of rain. Mostly cloudy, with a low around 68.
      North northwest wind 0 to 5 mph. Chance of precipitation is 50%.
    temperature: 68
    datetime: '2020-09-17T18:00:00-05:00'
    daytime: false
    condition: lightning-rainy
    precipitation_probability: 50
    wind_bearing: 337.5
    wind_speed: 2
  - detailed_description: >-
      A chance of thunderstorms and a chance of rain before 7am, then a chance
      of rain and a slight chance of thunderstorms. Mostly cloudy, with a high
      near 79. North wind around 5 mph. Chance of precipitation is 30%.
    temperature: 79
    datetime: '2020-09-18T06:00:00-05:00'
    daytime: true
    condition: lightning-rainy
    precipitation_probability: 30
    wind_bearing: 0
    wind_speed: 5
  - detailed_description: >-
      A chance of rain and a slight chance of thunderstorms before 7pm. Mostly
      cloudy, with a low around 65. Chance of precipitation is 30%.
    temperature: 65
    datetime: '2020-09-18T18:00:00-05:00'
    daytime: false
    condition: lightning-rainy
    precipitation_probability: 30
    wind_bearing: 22.5
    wind_speed: 5
  - detailed_description: >-
      A slight chance of rain showers after 7am. Partly sunny, with a high near
      79. Chance of precipitation is 20%.
    temperature: 79
    datetime: '2020-09-19T06:00:00-05:00'
    daytime: true
    condition: rainy
    precipitation_probability: 20
    wind_bearing: 45
    wind_speed: 8
  - detailed_description: >-
      A slight chance of rain showers before 7pm. Partly cloudy, with a low
      around 63. Chance of precipitation is 20%.
    temperature: 63
    datetime: '2020-09-19T18:00:00-05:00'
    daytime: false
    condition: rainy
    precipitation_probability: 20
    wind_bearing: 45
    wind_speed: 5
  - detailed_description: >-
      A slight chance of rain after 7am. Mostly sunny, with a high near 79.
      Chance of precipitation is 20%.
    temperature: 79
    datetime: '2020-09-20T06:00:00-05:00'
    daytime: true
    condition: rainy
    precipitation_probability: 20
    wind_bearing: 67.5
    wind_speed: 8
  - detailed_description: >-
      A slight chance of rain before 7pm. Partly cloudy, with a low around 62.
      Chance of precipitation is 20%.
    temperature: 62
    datetime: '2020-09-20T18:00:00-05:00'
    daytime: false
    condition: rainy
    precipitation_probability: 20
    wind_bearing: 67.5
    wind_speed: 5
friendly_name: KHBG Daynight
```
