### ISSUE TITLE
Themes without divider color make some cards unreadable

### ISSUE THREAD

**Issue by KTibow** [home-assistant/frontend#7009]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Some themes set `--divider-color` and `--card-background-color` to be the same as `--primary-background-color`, which hides dividers on `outlined` `ha-card`s.
![image](https://user-images.githubusercontent.com/10727862/93156542-2c420f00-f6bd-11ea-9340-c4040cf8e61a.png)

## Expected behavior

That it would either detect that and use box-shadow instead, or just use box-shadow here. Or maybe make a separate variable for theme writers.

## Steps to reproduce

1. Add this theme:
```
test_theme:
  primary-background-color: white
  divider-color: white
  card-background-color: white
```
2. Use that theme
3. Go to Config > Integrations
4. Look

## Environment

- Home Assistant release with the issue: 0.114.4
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Microsoft Edge Version 85.0.564.51 (Official build) (64-bit)
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
frontend:
  themes:
    test_theme:
      primary-background-color: white
      divider-color: white
      card-background-color: white
```

## Javascript errors shown in your browser console/inspector

```txt

```
