### ISSUE TITLE
gauge card, no red color if the theme is not selected

### ISSUE THREAD

**Issue by asystentka-jolka** [home-assistant/frontend#7016]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

if the theme is not selected on the gauge there is no red color
see the example below

```
type: gauge
entity: sensor.ais_wifi_service_current_network_info
min: 0
max: 100
severity:
  green: 70
  yellow: 40
  red: 30
name: Connection speed
```

1. the connection speed is above 70 - all correct - green
![image](https://user-images.githubusercontent.com/43966761/93196654-fe0b1080-f74a-11ea-89f3-2b175ddef111.png)

2. the connection speed is between 40-70 - all correct - yellow
![image](https://user-images.githubusercontent.com/43966761/93196804-2a269180-f74b-11ea-86a7-7ce421f2faa8.png)

3. the connection speed is between 30-40- no red color
![image](https://user-images.githubusercontent.com/43966761/93198407-488d8c80-f74d-11ea-8f90-c2e7cc7a0129.png)

I thought that this is a problem with template but it is not - see the code inspector - the style for .value class is not generated
![image](https://user-images.githubusercontent.com/43966761/93199470-b5eded00-f74e-11ea-9eee-17dd5c65baf0.png)

When we do this in other way:
```
type: gauge
entity: sensor.ais_wifi_service_current_network_info
min: 0
max: 100
severity:
  green: 0
  yellow: 40
  red: 70
name: Connection speed
```

1. the green is green
![image](https://user-images.githubusercontent.com/43966761/93197949-9e156980-f74c-11ea-9565-5a226365341d.png)

2. the yellow is yellow
![image](https://user-images.githubusercontent.com/43966761/93198026-b6858400-f74c-11ea-8834-f9a28b6ae921.png)

3. again the is not red
![image](https://user-images.githubusercontent.com/43966761/93198206-f8162f00-f74c-11ea-9ffd-60b24a231c69.png)

It looks that the .value style is not generated for red
![image](https://user-images.githubusercontent.com/43966761/93199470-b5eded00-f74e-11ea-9eee-17dd5c65baf0.png)

When the theme is selected all works as expected

![image](https://user-images.githubusercontent.com/43966761/93198705-b0dc6e00-f74d-11ea-99f6-4b2598947f8c.png)

## Expected behavior

It will be great if the default colors work even if the theme is not selected.

## Steps to reproduce

as described above

## Environment

- Home Assistant release with the issue: I think this was always like that
- Last working Home Assistant release (if known): no
- Browser and browser version: latest chrome, ff etc..
- Operating system: linux

## State of relevant entities

-

## Problem-relevant configuration

-

## Javascript errors shown in your browser console/inspector

-
