### ISSUE TITLE
Camera Issue - Images not properly refreshed on picture-elements floormap

### ISSUE THREAD

**Issue by StefanoGiu** [home-assistant/frontend#7023]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have configured 12 generic cameras. Below the configuration of one of them:

```
  - platform: generic
    name: Cucina
    authentication: digest
    username: XXX
    password: XXX
    still_image_url: http://192.168.1.13:13000/snapshot.cgi?user=XXX&pwd=XXX
    stream_source: rtsp://192.168.1.13:14000/tcp/av0_0
```

and I included them all on my picture-elements floormap:

```
                              - camera_image: camera.veranda
                                entity: camera.veranda
                                style:
                                  border: 2px solid red
                                  border-radius: 10%
                                  left: 75%
                                  top: 75%
                                  width: 10%
                                type: image


```
Very often, after few minutes the webpage of my floormap on Chrome is open, I see that the camera images is not properly refreshed and they disappear:
[https://imgur.com/B42hDvp](url)

I can also simulate this behaviour if I change the zoon size of Chrome. Then... if I just press F5 to refresh the page, I got the images back:
[https://imgur.com/3gxFqxm](url)

Moreover, when the images from the camera gets a timeout, I have a straight red line for the camera.
[https://imgur.com/LfkR57v](url)
or an empty box with image icon:
[https://imgur.com/0slIbdX](url)
In this case, would it be possible just to show the previous image?

## Expected behavior
problem 1 (images disappear) - Cameras refresh properly
problem 2 (straight red line or empty box) - Show previous image

## Steps to reproduce

problem 1 (images disappear) - e.g. change zoom size on Chrome
problem 2 (straight red line or empty box) - e.g. simulate a timeout on camera image

## Environment

- Home Assistant release with the issue: Home Assistant 0.114.4
- Last working Home Assistant release (if known): it never worked properly
- Browser and browser version: Chrome Version 85.0.4183.102
- Operating system: Windows 10

## State of relevant entities

-

## Problem-relevant configuration

-

## Javascript errors shown in your browser console/inspector

```
Uncaught (in promise) 
Object
error: {code: 3, message: "Connection lost"}
success: false
type: "result"
__proto__: Object
chunk.e4db989….js:683 Uncaught (in promise) 
Object
error: {code: 3, message: "Connection lost"}
success: false
type: "result"
__proto__: Object
```

```
Uncaught (in promise) Object
13core.abb95f18.js:1 WebSocket is already in CLOSING or CLOSED state.
sendMessage @ core.abb95f18.js:1
undefined:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
core.abb95f18.js:1 WebSocket is already in CLOSING or CLOSED state.
sendMessage @ core.abb95f18.js:1

```
## Additional information

-
