### ISSUE TITLE
Power off button missing in media player card

### ISSUE THREAD

**Issue by mvdwetering** [home-assistant/frontend#7068]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

For my mediaplayers (Sonos, Cast, Kodi) I don't see a Power Off button. Pretty sure there used to be one.
![image](https://user-images.githubusercontent.com/732514/93670401-659ec400-fa9b-11ea-938a-29c71de19445.png)

## Expected behavior

Be able to power off a mediaplayer

Actually I just noticed that the power off button _does_ appear when media is playing.
So expected behaviour is that the power button is always visible.
![image](https://user-images.githubusercontent.com/732514/93670547-713eba80-fa9c-11ea-8943-afa43975f4be.png)

## Steps to reproduce

* Take a mediaplayer entity. I see it with Sonos, Cast and Kodi standard integrations and add it to the frontend with the default mediaplayer card.
* Turn mediaplayer on with the button on the card (on button changes into play button)
* Go to the popup menu by pressing the 3 dots menu at top right of the card
* Expected to to see Power Off button

## Environment

- Home Assistant release with the issue: 0.115.1
- Last working Home Assistant release (if known): not sure
- Browser and browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit) on Windows 10
- Operating system: Home Assistant (HassIO)

## State of relevant entities

Screenshot is in the problem section
```yaml
volume_level: 0.4000000059604645
is_volume_muted: false
media_content_id: 'https://www.home-assistant.io/images/cast/splash.png'
media_position: 0
media_position_updated_at: '2020-09-19T15:26:29.442637+00:00'
app_id: CC1AD845
app_name: Default Media Receiver
entity_picture_local: null
friendly_name: Hobbykamer Mini
supported_features: 152463
```

## Problem-relevant configuration

```yaml
All configured through UI
```

## Javascript errors shown in your browser console/inspector

```txt
none
```
