### ISSUE TITLE
Lovelace UI History Graph card not updating on `refresh_interval`

### ISSUE THREAD

**Issue by mfisher87** [home-assistant/frontend#7133]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

History graph card does not update when new data comes in from sensors until the page is refreshed in the browser.

## Expected behavior

History graph card updates every `refresh_interval` (5 seconds as configured), with new data values.

I know in v0.8x or so, this functionality worked and I used it to monitor food temperatures in real-time while cooking. I'm not sure what update broke it, but I thought it would be fixed in v0.115.x by pull request #6647.

## Steps to reproduce

1. Create history graph card from any sensor in Lovelace UI. The current outdoor temperature works well to demonstrate this problem.
2. View the card in the UI
3. Wait for 10 minutes and observe one of two conditions: A) no change; B) the line has flatlined, as if the sensor value has continued to report the same value for the last 10 minutes. Both conditions are described in linked issues, but I experienced condition A.
4. Refresh and see the un-updated chart or flat line has been replaced with all the real values from the last 10 minutes.

## Environment

- Home Assistant release with the issue: v0.115.3
- Last working Home Assistant release (if known): A v0.8x release was the last one _I tried_ that worked.
- Browser and browser version: Firefox v80.0.1
- Operating system: Ubuntu 20.04

## State of relevant entities

```yaml
19.7
```

At 10:00AM, the UI shows latest value is 9:47:00 AM value `18.9`, while developer-tools shows `19.7`.

Before refresh:
![image](https://user-images.githubusercontent.com/3608264/94289113-76c15800-ff15-11ea-8eca-4a7ac3517fee.png)

After refresh:
![image](https://user-images.githubusercontent.com/3608264/94289409-e9323800-ff15-11ea-88c8-a354af575db8.png)

## Problem-relevant configuration

```yaml
          - type: history-graph
            title: 'Temperature'
            refresh_interval: 5
            hours_to_show: 48
            entities:
              - entity: sensor.dark_sky_temperature
                name: Outdoor Temperature
```

## Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations
.
```

Unsure if this is relevant!

## Additional information

Relevant pull request: #6647 
Duplicate closed issues: #6520, #5129 

Please see the discussion in both the original issue and the pull request for additional details. A new issue was specifically requested in the pull request discussion, otherwise I would have requested re-opening the original issues :)

**Comment by zsarnett** [comment]
hmm it seems the new code does not update the state history on an interval. Meaning that if the refresh interval is 5 seconds and the entity updates after 3 seconds and then doesn't update again then the value update wont show. Only until it updates again after the 5 seconds will it update.

**Comment by mfisher87** [comment]
I _think_ I am not seeing updates no matter how long I wait. I'm going to do another test for 30 minutes just to confirm this. This particular sensor updates every 5 minutes, but I'm seeing the same thing from a voltage sensor that updates every 20 seconds. I'll attach more screenshots.

**Comment by mfisher87** [comment]
page loaded at 10:19AM, screenshot taken at 10:22AM. The lower graph has updated several times, while the upper graph has not updated at all yet. both have `refresh_interval: 5`.

![image](https://user-images.githubusercontent.com/3608264/94291582-0c121b80-ff19-11ea-9aae-3c0e9a4fc67d.png)

Full config:
```
        cards:
          # Full-width history graphs
          - type: history-graph
            refresh_interval: 5
            hours_to_show: 2
            entities:
              - entity: sensor.indoor_grow_temp
                name: Indoor Grow Temperature
              - entity: sensor.living_room_temp
                name: Living Room Temperature
              - entity: sensor.dark_sky_temperature
                name: Outdoor Temperature
          - type: history-graph
            refresh_interval: 5
            hours_to_show: 2
            entities:
              - entity: sensor.washing_machine_volts
                name: Washing Machine Volts
              - entity: sensor.led_volts
                name: LED Volts
```
