### ISSUE TITLE
Media player volume slider is not usable with Onkyo

### ISSUE THREAD

**Issue by pszafer** [home-assistant/frontend#7137]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Hi,
This problem is occuring since long time, but I used VOL UP/VOL DOWN before. Now as both buttons are gone and I have to use slider, I can't do it.
When I click on slider it's going crazy.
![onkyo_media](https://user-images.githubusercontent.com/690510/94336301-6d51f180-ffe2-11ea-84d7-76ffce49cfe3.gif)

It's almost always decreasing volume even if I click to higher value in slider.
I don't have any other media players with slider, so can't tell if this is only problem with communication frontend <-> onkyo integration.

What I can tell that using services it's working as expected (all three services volume_up, volume_down, set_volume)
## Expected behavior

Make slider more reliable.
Bring back buttons for vol up/down.

## Steps to reproduce

    1. Add a onkyo integration in configuration.yaml
    2. Navigate to more info of media_player card
    3. Turn on media_player if off.
    3. Set volume and wait.

## Environment

- Home Assistant release with the issue: 0.115.3
- Last working Home Assistant release (if known): don't know
- Browser and browser version: Chromium 85.0.4183.102, Android app.
- Operating system: Linux Alpine | 5.4.44-2-pve

## State of relevant entities

After clicking with slider 
```
source_list: Bluray, Shield, NC+, Radio volume_level: 0.22049999999999997 is_volume_muted: false source: Radio preset: 5 video_out: yes,out friendly_name: onkyoparter supported_features: 20364
--
```
After setting with remote:
```

source_list: Bluray, Shield, NC+, Radio volume_level: 0.3115 is_volume_muted: false source: Radio preset: 5 video_out: yes,out friendly_name: onkyoparter supported_features: 20364
--
```
![image](https://user-images.githubusercontent.com/690510/94336436-9c1c9780-ffe3-11ea-8f2a-249436aa33bc.png)

## Problem-relevant configuration

I tried configuration as:

```yaml
- platform: onkyo
  host: IP
  name: onkyoparter
  receiver_max_volume: 200
  max_volume: 70
  sources:
    bd: 'Bluray'
    video3: 'Shield'
    video2: 'NC+'
    fm: 'Radio'
```

```yaml
- platform: onkyo
  host: IP
  name: onkyoparter
  sources:
    bd: 'Bluray'
    video3: 'Shield'
    video2: 'NC+'
    fm: 'Radio'
```

## Javascript errors shown in your browser console/inspector
None errors.

## Additional information
It might be problem with integration, not the frontend, but I can't tell which one.
