### ISSUE TITLE
Service 'cast.show_lovelace_view' not working as expected (for me)

### ISSUE THREAD

**Issue by NicoSomerwil** [home-assistant/frontend#7155]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This is my first attempt to create an issue so sorry if it is not yet a good/correct one.

I like to use the the service 'cast.show_lovelace_view' to cast a view to my Google Nest Hub. It doesn't work (yet) as expected. It seems that the entries for both 'dashboard_path' and 'view_path' must be entered with single quotes.
I do support Nabu Casa to use this feature (the easy way).

An example of the service data in a script:
```yaml
service: cast.show_lovelace_view
data:
  dashboard_path: 'lovelace'
  view_path: '11'
  entity_id: media_player.huiskamer_midden
```
'11' is the sequence number of the view.
This script works when I execute it directly, but only once, from the scripts editor. It also works (with using single quotes for both entries) from the developer tools.
When the script is saved and executed again or executed from an automation then it won't work anymore. 
Sometimes I do get the 'Connected' screen on my device with the logos from HA and Nabu Casa but isn't the view shown.
I also tried to use the name of the with (kids-room) as suggested in the documentation, but with also no luck.

```yaml
service: cast.show_lovelace_view
data:
  dashboard_path: lovelace
  view_path: kids-room
  entity_id: media_player.huiskamer_midden
``` 
This results in the 'Connected' screen with error message:
**Error: Unable to find a view with path kids-room**

I noticed that after saving the script the **single quotes** from the entry of the dashboard_path **are deleted**!

```yaml
service: cast.show_lovelace_view
data:
  dashboard_path: lovelace
  view_path: '11'
  entity_id: media_player.huiskamer_midden
```
So I guess that could cause this issue?

 
## Steps to reproduce

Make a script with entries **without** single quotes and execute the script. Use name or number of view.
If it won't work, like it does for me, then first use service 'media_player.media_stop' and/or 'media_player.turn_off ' to 'stop' the connected screen. 
Then try it again (within the script editor) with both entries **with** single quotes and execute the script.
If it then works like is does (once) for me then save the script and again first use service 'media_player.media_stop' and/or 'media_player.turn_off ' to 'stop' the connected screen. 
Then try again to run the script and notice the deleted single quotes from the dashboard_path entry. Does it work for you? Is does not for me.

## Environment

I'm using HA 0.115.4. Operating system: HassOS 4.13 (Intel NUC with Proxmox).
I don't know this issue was already there or 'new' with the 0.115.x release.
As browser I use latest Chrome on by Macbook Pro, but also tried Safari

- Home Assistant release with the issue: 0.115.4.
- Last working Home Assistant release (if known): not known
- Browser and browser version: Chrome (latest version: 85.0.4183.121)
- Operating system: HassOS 4.13 (Intel NUC with Proxmox)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Sorry for long story! What could be (done) wrong?
