### ISSUE TITLE
Entity Row Editor scroll issue in mobile Safari 0.116b1

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7212]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In HA iOS app (and thus mobile Safari) on iOS 14.2b when I click the pencil icon to enter the "Entity Row editor" and then scroll down in order to look at the preview, it causes the top part to kind of duplicate.

![image](https://i.imgur.com/rkxN41H.jpg)

## Steps to reproduce

1. Edit an Entities card on iOS
2. Click pencil icon to enter the Entity Row Editor
3. Scroll down a bit (to look at the preview) but you'll notice the text at the top moved

## Environment

- Home Assistant release with the issue: 0.116.0b1
- Last working Home Assistant release (if known): n/a (new feature)
- Browser and browser version: Home Assistant Companion for iOS
- Operating system: iOS 14.2 beta

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Good lord

**Comment by SeanPM5** [comment]
I think it _might_ possibly be related to having a header and/or footer in the card. 

Tried editing a bunch of other cards, some with very few rows and others with tons of rows. And the Entity Row Editor on all of those worked perfectly fine. It's just this one particular card (so far) with issues. The only thing different from those other cards, is this one has a header/footer. Here's the card config:

```
entities:
  - light.ceiling_couch
  - light.ceiling_desk
  - light.desk_lights
footer:
  entities:
    - entity: scene.night_watch
    - entity: scene.bright_white
      icon: 'mdi:track-light'
    - entity: script.lights_flash_sean_desk_blink_long
  type: buttons
header:
  image: 'https://www.pngarts.com/files/1/Header-PNG-Image.png'
  type: picture
title: My Title
type: entities
```

Even on this I'm unable to reproduce it 100% consistently, so this might not be a big deal after all. Will play with it more tomorrow and see if I can reliably reproduce, otherwise I'll close this.
