### ISSUE TITLE
Alexa "Manage Entities" tooltip (title) for the control button reads "Expose to Google Assistant"

### ISSUE THREAD

**Issue by mikebaz** [home-assistant/frontend#7214]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When using the new 0.115 functionality to manage entities exposed to Alexa, the tooltip (title) for the manage button reads "Expose to Google Assistant" instead of "Expose to Alexa" (or something along those lines).
![image](https://user-images.githubusercontent.com/11339500/94994588-84568d80-0566-11eb-9ec7-bf2dfaa4cb2e.png)

## Expected behavior

The tooltip should reference the proper assistant.  This might impact accessibility a small bit as well as a screen reader would read out confusing text when reading the title information.

## Steps to reproduce

1. Configure Home Assistant Cloud integration.
2. Enable Alexa integration.
3. Select `MANAGE ENTITIES` in the Alexa area.
4. Hover over any of the control buttons.

## Environment

- Home Assistant release with the issue: Home Assistant 0.115.6
- Last working Home Assistant release (if known): feature is new to 0.115
- Browser and browser version: Microsoft Edge Version 87.0.658.0 (Official build) canary (64-bit)
- Operating system: Windows 10 20H2 Build 19042.508

## State of relevant entities

n/a

## Problem-relevant configuration

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: microsoft
    api_key: removed
    region: northcentralus

zone:
  - name: Home
    latitude: removed
    longitude: removed
    radius: 50
    icon: mdi:home

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

```

## Javascript errors shown in your browser console/inspector

n/a

## Additional information

I believe the issue is this line in `src/panels/config/cloud/alexa/cloud-alexa.ts`, line 134 as I'm entering this bug, but I don't know the right way to fix it because I don't know how localization, etc. works at the moment.

```typescript
        .title=${this.hass!.localize("ui.panel.config.cloud.google.expose")}
```
