### ISSUE TITLE
Deleting refresh token doesn't show token name when it wants to

### ISSUE THREAD

**Issue by mikebaz** [home-assistant/frontend#7215]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When deleting a refresh token, it seems clear the app is supposed to be showing me some kind of identifier for the token.  However, there is no identifier shown, just blank space:

![image](https://user-images.githubusercontent.com/11339500/94995123-1f049b80-056a-11eb-9a8c-9c1aeef0bec7.png)

## Expected behavior

Some kind of token identifier is present.

## Steps to reproduce

1. Go to a user profile, say by clicking the user icon in the lower-left-hand-side of the UI.
2. Scroll down to the `Refresh Tokens` area.
3. Click the delete button for one of the tokens.
4. Observe the text in the confirmation dialog.

## Environment

Home Assistant release with the issue: Home Assistant 0.115.6
Last working Home Assistant release (if known): unknown, possibly never?
Browser and browser version: Microsoft Edge Version 87.0.658.0 (Official build) canary (64-bit)
Operating system: Windows 10 20H2 Build 19042.508

## State of relevant entities

n/a

## Problem-relevant configuration

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: microsoft
    api_key: removed
    region: northcentralus

zone:
  - name: Home
    latitude: removed
    longitude: removed
    radius: 50
    icon: mdi:home

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

## Javascript errors shown in your browser console/inspector

No relevant entries that I see.

## Additional information

It appears the issue is in `src/panels/profile/ha-refresh-tokens-card.ts`, where this code (starting line 103 as I type this):

```typescript
    const token = (ev.currentTarget as any).token;
    if (
      !(await showConfirmationDialog(this, {
        text: this.hass.localize(
          "ui.panel.profile.refresh_tokens.confirm_delete",
          "name",
          token.client_name
```

references `token.client_name`, which is `null`.  I don't know if the fix is to populate that field somewhere (don't know where it would be coming from or what would be in it), or to change the reference to `token.client_id`, which is populated:

![image](https://user-images.githubusercontent.com/11339500/94995218-e1ecd900-056a-11eb-8698-b2fa230e4d2b.png)

or some other fix.  `token.client_id` seems like the quickest fix but I don't know the underlying intent so it might be the wrong fix.
