### ISSUE TITLE
General Configuration UI disabled

### ISSUE THREAD

**Issue by firstof9** [home-assistant/frontend#7217]
## The problem

General configuration disabled in UI configuration when configuration is not in yaml.

## Environment

- Home Assistant Core release with the issue: 0.116b1
- Last working Home Assistant Core release (if known): 0.115.x
- Operating environment (OS/Container/Supervised/Core): Container
- Integration causing this issue: core
- Link to integration documentation on our website: n/a

## Problem-relevant `configuration.yaml`

```yaml
homeassistant:
  # Name of the location where Home Assistant is running
  # name: Home
  # Location required to calculate the time the sun rises and sets
  # latitude: [redacted]
  # longitude: [redacted]
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: 1068
  # metric for Metric, imperial for Imperial
  # unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: America/Phoenix
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
  media_dirs:
    local: /config/www/
```

## Traceback/Error logs

```txt
n/a
```

## Additional information

![image](https://user-images.githubusercontent.com/1105672/94887184-7c91ce80-042a-11eb-8cae-36e2895c202e.png)
