### ISSUE TITLE
Button w/ service call missing data when loaded in UI editor. Saving causes data loss

### ISSUE THREAD

**Issue by bverkron** [home-assistant/frontend#7221]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have a horizontal-stack of several buttons within a vertical-stack (not sure if that layout matters). Each button it tied to an entity (example a switch). Each button has the `tap_action` set to call a service (in this case a script related to the switch).

After saving the button config via the UI everything works as expected. However, next time I open the editor the first button will be missing it's tap action / service call. If I re-save in that state it wipes out the tap / service call data that was set the first time (which makes sense because the UI editor fields were blank). It appears that the UI editor is not properly loading the data for the first button. It is clearly saving it the first time it's set though because as said the button functions as expected as long as it's not edited / re-saved with the blankly loaded fields.

This does not seem to be tied to a specific entity or service call. If I swap the order of the buttons in the horizontal-stack it will still be the first button with a script each time.

## Expected behavior

UI editor loads what's defined in the lovelace file instead of blank data.

## Steps to reproduce

Not sure if this is an entirely valid test since entities and scripts of these names won't exist in a fresh instance of HA but I pasted this into the card code editor in a fresh install of 0.115.6 in VirtualBox and it exhibited the same issue. The first button with a script assigned (in this case `switch.oliver_lamp`) has an empty tap action when loaded in the UI after the initial save but the rest are fine.

```yaml
cards:
  - cards:
      - entity: switch.livingroom_smartstrip_1_lamp
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
        name: Living Room
      - entity: switch.oliver_lamp
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: call-service
          service: script.blink_oliver_lamp
        type: button
        name: 'Blink Oliver''s '
      - entity: switch.london_smartstrip_1_lamp
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: call-service
          service: script.blink_london_lamp
        type: button
        name: 'Blink London''s'
      - type: button
        tap_action:
          action: call-service
          service: script.blink_basement_lamp
        entity: switch.basement_smartstrip_1_lamp
        name: Blink Basement
    type: horizontal-stack
type: vertical-stack
```

## Environment

- Home Assistant release with the issue: 0.115.6
- Last working Home Assistant release (if known): Only noticed in current version, unsure if it happened previously.
- Browser and browser version: Safari 14.0, Chrome 85.0.4183.121
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Initial save of button config via UI
<img width="1141" alt="Screen Shot 2020-10-03 at 2 33 18 PM" src="https://user-images.githubusercontent.com/19174503/95002122-824ff700-0585-11eb-9633-ffacfee1748f.png">

Re-opening the config in the editor after the initial save. Button works as expected (calls script) even in this state as long as I don't re-save with the screen like this which overwrites the working config with the blank tap action.
<img width="1027" alt="Screen Shot 2020-10-03 at 2 25 14 PM" src="https://user-images.githubusercontent.com/19174503/95002125-89770500-0585-11eb-8f0e-60cf66064cf1.png">
