### ISSUE TITLE
[0.116.0bx] Header toggle of entity card does not show current state

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#7222]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When all my lights are on, the header toggle of the entities card does not show the correct state. In previous version, the header toggle was on, if one or more lights where on. Now it does not change at all:
![Screenshot_2020 10 03_13h38m25s_008_](https://user-images.githubusercontent.com/1368405/94993242-db248d00-058f-11eb-900c-f43f37eaf92e.png)

Additionally when I toggle the header toggle, my lights not change at all:
![Screenshot_2020 10 03_15h48m53s_009_ (1)](https://user-images.githubusercontent.com/1368405/94993305-4a01e600-0590-11eb-961d-757727be6fbb.gif)

There is no error in the logs regarding this issue. 

## Expected behavior

Show current state of the entities in the card and also toggle lights if the toggle element is pressed. 

## Steps to reproduce

1. Create entity card
2. Add lights
3. Enable header toggle

## Environment

- Home Assistant release with the issue: 0.116.0bx
- Last working Home Assistant release (if known): 0.115.x???
- Browser and browser version: Edge Chrome 86
- Operating system: Windows 10

## State of relevant entities

Example state of one of the lights:
```yaml
state: on
min_mireds: 153
max_mireds: 588
effect_list: Strobe color, Police, Christmas, RGB, Random Loop, Fast Random Loop, LSD, Slowdown, Disco, Strobe epilepsy!, Alarm, Police2, WhatsApp, Facebook, Twitter, Slow Temp, Stop
brightness: 23
color_temp: 429
hs_color: 31.381, 93.725
rgb_color: 255, 141, 16
xy_color: 0.592, 0.387
flowing: false
friendly_name: Hintergrund 1
supported_features: 63
```

## Problem-relevant configuration

```yaml
entities:
  - entity: light.hintergrund_1
  - entity: light.hintergrund_2
  - entity: light.hintergrund_3
  - entity: light.hintergrund_4
  - entity: light.hintergrund_5
show_header_toggle: true
title: Hintergrund
type: entities
```

## Javascript errors shown in your browser console/inspector

```txt
None
```
