### ISSUE TITLE
entities card only displays operation mode 'off' for water heater

### ISSUE THREAD

**Issue by perjury** [home-assistant/frontend#7225]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
The entities card for entity water_heater.hot_water displays operation_mode 'off' but displays nothing for operation_mode 'eco' or 'on'

## Expected behavior
The entities card for entity water_heater.hot_water should display all operation modes

## Steps to reproduce
Entities card config:
```yaml
type: entities
entities:
  - entity: water_heater.hot_water
  - entity: climate.downstairs_heat_heating
```

## Environment

- Home Assistant release with the issue: 0115.3
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome
- Operating system: Windows 10

## State of relevant entities

```yaml
min_temp: 43.3
max_temp: 60
operation_list:
  - eco
  - 'on'
  - 'off'
current_temperature: null
temperature: null
target_temp_high: null
target_temp_low: null
operation_mode: 'off'
friendly_name: Hot Water
supported_features: 2

min_temp: 43.3
max_temp: 60
operation_list:
  - eco
  - 'on'
  - 'off'
current_temperature: null
temperature: null
target_temp_high: null
target_temp_low: null
operation_mode: eco
friendly_name: Hot Water
supported_features: 2
```
![Overview-Home-Assistant-water1](https://user-images.githubusercontent.com/11613248/95018799-d5937980-0659-11eb-8a71-53702a0de1f9.png)
![Overview-Home-Assistant-water2](https://user-images.githubusercontent.com/11613248/95018801-d62c1000-0659-11eb-9cb3-aae1972e0643.png)

## Problem-relevant configuration

```yaml
type: entities
entities:
  - entity: water_heater.hot_water
  - entity: climate.downstairs_heat_heating
```

## Javascript errors shown in your browser console/inspector

```txt

```
