### ISSUE TITLE
Add service integration.reload

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#7242]
## The request

to the services.
At startup some integrations fail to initialize properly. Not sure why (might be timing issues due to a large instance).
However, clicking the reload in the UI integrations page is always very helpful

Would be nice if we could write a small script to do so, and click that from the Frontend. Without having to go into settings/integrations/select integration/options/reload…

## The alternatives

go into settings/integrations/select integration/options/reload…
## Additional information
imagining a script:
```
script:
  reload_weatherbit:
    sequence:
       service: integration.reload
        data:
          name: Weatherbit
```
and we can even do that automatically upon

```
    trigger:
      platform: homeassistant
      event: start
```

this is a copy of https://community.home-assistant.io/t/add-service-integration-reload/231940, wasn't sure if this is the better place to put a FR forward.
