### ISSUE TITLE
Calendar card shows 2 events when the event goes over midnight

### ISSUE THREAD

**Issue by gieljnssns** [home-assistant/frontend#7266]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When the event goes over midnight, it splits up in 2. One to midnight and one to the end of the event
## Expected behavior
It should be one event

## Steps to reproduce
Have a calendar card with your work calendar in it when working night shifts

## Environment

- Home Assistant release with the issue: 0.116.0
- Last working Home Assistant release (if known): none
- Browser and browser version: all
- Operating system: Home Assistant Operating System

## State of relevant entities
x

```yaml

```

## Problem-relevant configuration
x

```yaml
  - platform: caldav
    url: !secret icloud_url
    username: !secret icloud_username
    password: !secret icloud_pw
    custom_calendars:
      - calendar: "Mondelez"
        name: "Mondelez"
        search: ".*"
      - calendar: "Monnikenheide"
        name: "Monnikenheide"
        search: ".*"
      - calendar: "De Vuilkar"
        name: "De Vuilkar"
        search: ".*"
      - calendar: "Noor"
        name: "Noor"
        search: ".*"
      - calendar: "Fien"
        name: "Fien"
        search: ".*"
      - calendar: "Martine"
        name: "Martine"
        search: ".*"
      - calendar: "Giel"
        name: "Giel"
        search: ".*"
      - calendar: "Gezin"
        name: "Gezin"
        search: ".*"
      - calendar: "Noor en Fien"
        name: "Noor en Fien"
        search: ".*"
      - calendar: "Festivallekes"
        name: "Festivallekes"
        search: ".*"
      - calendar: "Mondelez"
        name: "De vroege"
        search: "De vroege"
      - calendar: "Mondelez"
        name: "De late"
        search: "De Late"
      - calendar: "Mondelez"
        name: "De nacht"
        search: "De Nacht"
      - calendar: "Mondelez"
        name: "Weekend nacht"
        search: "Weekend Nacht"
      - calendar: "Mondelez"
        name: "Weekend dag"
        search: "Weekend dag"
      - calendar: "RAFC"
        name: "RAFC"
        search: ".*"
      - calendar: "Feestdagen"
        name: "Feestdagen"
        search: ".*"
      - calendar: "Schoolvakanties"
        name: "Schoolvakanties"
        search: ".*"
```

## Javascript errors shown in your browser console/inspector
x

```txt

```

## Additional information
This is a screenshot how it is now
![Schermafbeelding 2020-10-08 om 15 50 35](https://user-images.githubusercontent.com/17234951/95467651-03403180-097e-11eb-924b-afea594f4c14.png)

This is more like it should be
![Schermafbeelding 2020-10-08 om 15 51 07](https://user-images.githubusercontent.com/17234951/95467733-15ba6b00-097e-11eb-805e-e335f6101f38.png)
