### ISSUE TITLE
Entities Card show_header_toggle: true no longer observed when all of the entities are custom types

### ISSUE THREAD

**Issue by Ryan-J** [home-assistant/frontend#7270]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After upgrading from 0.115 to 0.116 I noticed some of my entities cards no longer had a header toggle. Through trial and error I have determined the common symptom is that these are entities cards where every entity is of a custom type. Changing even a single one of them to non-custom makes the toggle appear.

## Expected behavior
The YAML 
`show_header_toggle: true `
should result in a header toggle for the entities card

## Steps to reproduce

Here is as simple of an example of YAML as I could think of to show the issue:

Header toggle shown (works as expected):
```
type: entities
entities:
  - entity: light.garage_overhead_lights
title: All Lights
show_header_toggle: true
```

Header toggle not shown (showed in 0.115 but not in 0.116):
```
type: entities
entities:
  - entity: light.garage_overhead_lights
    type: 'custom:multiple-entity-row'
title: All Lights
show_header_toggle: true
```

## Environment

- Home Assistant release with the issue: 0.116
- Last working Home Assistant release (if known): 0.115
- Browser and browser version: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

Same as mentioned above:
```
type: entities
entities:
  - entity: light.garage_overhead_lights
    type: 'custom:multiple-entity-row'
title: All Lights
show_header_toggle: true
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Looking through the code check-ins it does seem like work was recently done that involves checking the type of entities. I suspect this was an unintended side effect.
