### ISSUE TITLE
Climate entity ignores 'precision' in UI

### ISSUE THREAD

**Issue by andriej** [home-assistant/frontend#7308]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have "generic thermostat" climate.* domain devices with `precision: 0.1`.
When I open those entities in UI view, I can only set the target temperature with step of 0.5, nothing in between.
![image](https://user-images.githubusercontent.com/6303489/95676708-5c97a300-0bc0-11eb-8097-1ad13bff61b3.png)

Click of up or down arrow marked yellow on screenshot would make it either 19.5 or 18.5, not 19.1 and 18.9 as desired.

## Expected behavior

Respect `precision`

## Steps to reproduce

1. Add climate generic thermostat 
2. Set it's precision to 0.1
3. Add the entity to 'entities' UI lovelace card
4. Open the entity
5. Try to set temperature with 0.1*C higher value than shown

## Environment

- Home Assistant release with the issue: 0.116.2
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome latest (no matter browser)
- Operating system: Win 10

## State of relevant entities

```yaml

heat 
hvac_modes: heat, off 
min_temp: 10 
max_temp: 26 
preset_modes: none, away 
current_temperature: 20.7 
temperature: 19 
hvac_action: idle 
preset_mode: none 
friendly_name: Garaż 
supported_features: 17
```

## Problem-relevant configuration

```yaml
- platform: generic_thermostat
  name: Garaż
  heater: group.co_parter_garaz
  target_sensor: sensor.temperature_garaz
  min_temp: 10
  max_temp: 26
  precision: 0.1
  away_temp: 16
  hot_tolerance: 0
  cold_tolerance: 0.3
  min_cycle_duration:
    minutes: 30
```

## Javascript errors shown in your browser console/inspector

```txt

```
