### ISSUE TITLE
Last-Changed not reporting correct value

### ISSUE THREAD

**Issue by murraykessell** [home-assistant/frontend#7372]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
I have an entity to indicate when my dishwasher was last used (binary_sensor.dishwasher_state) and another to indicate when my washing machine was last used (binary_sensor.washing_machine_state). 

![image](https://user-images.githubusercontent.com/51472089/96332386-43966280-1096-11eb-9b54-a5440c7e915f.png)

In the example above the washing machine last-changed was 1 hour ago which is correct. The dishwasher has not been used since 16 Oct 21:03 and yet the last-changed time is also 1 hour, seeming the same time as the washing machine.

## Expected behavior

Correct last-changed time to be displayed for each and every entity. In my example the last-changed for the dishwasher should be 19 hours ago.

## Steps to reproduce

as described

## Environment

- Home Assistant release with the issue: 0.116.4
- Last working Home Assistant release (if known): 0.114 ? I think 
- Browser and browser version: Chrome Version 86.0.4240.75 (Official Build) (64-bit)
- Operating system: HassOS 4.13 on Raspberry PI 4 , Browser in Windows 10 

## State of relevant entities
![image](https://user-images.githubusercontent.com/51472089/96332806-c6b8b800-1098-11eb-911a-160e7539080d.png)

## Problem-relevant configuration

In Lovelace I have a vertical stack card that shows the last change and history for both entities like so.
``` 
cards:
  - entities:
      - entity: binary_sensor.washing_machine_state
        name: Washing Machine Last Changed
        secondary_info: last-changed
        state_color: true
    type: entities
  - entities:
      - binary_sensor.washing_machine_state
    hours_to_show: 24
    refresh_interval: 300
    type: history-graph
  - entities:
      - entity: binary_sensor.dishwasher_state
        name: Dishwasher Last Changed
        secondary_info: last-changed
        state_color: true
    type: entities
  - entities:
      - binary_sensor.dishwasher_state
    hours_to_show: 24
    refresh_interval: 300
    type: history-graph
type: vertical-stack

```

## Javascript errors shown in your browser console/inspector

```txt

```
