### ISSUE TITLE
history-graph: entities with no state change in DB purge period are not shown!

### ISSUE THREAD

**Issue by energywave** [home-assistant/frontend#7398]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have a history-graph card with multiple device_tracker entities (tracked by Fritz integration) so that I can see at a glance the online status of many devices at once. It seems that devices that don't have a state change in the purge period (3 days in my case) are not shown at all!
My configuration of the card is as following:
entities:
```yaml
  - entity: device_tracker.hshome
  - entity: device_tracker.nvr
  - entity: device_tracker.osmc
  - entity: device_tracker.osmc_cameretta
  - entity: device_tracker.asciugatrice
  - entity: device_tracker.cam_front
  - entity: device_tracker.cam_bbq
  - entity: device_tracker.cam_salotto
  - entity: device_tracker.cam_pool
  - entity: device_tracker.echo_dot_pian_terreno
  - entity: device_tracker.echo_dot_mansarda
  - entity: device_tracker.tado_bridge
  - entity: device_tracker.luce_a_terra
  - entity: device_tracker.broadlink_camera
  - entity: device_tracker.broadlink_cameretta
  - entity: device_tracker.pompa_piscina
hours_to_show: 24
refresh_interval: 0
type: history-graph
```
The card shown is this, as HSHOME is the only device with HOME/NOT_HOME updates in last 3 days:
![image](https://user-images.githubusercontent.com/2051567/95093345-f676d000-0728-11eb-9783-3ce55832eb52.png)

## Expected behavior

I expect that if a device has no history events the current state is used to show a full width bar with that state. In my case I expect to see all other devices with a green bar showing "HOME".
I'm nearly sure that in previous versions it was correctly handled as I ever seen the graph for all devices... Maybe an optimization introduced screwed up something.

## Steps to reproduce

Add a card with some entities that have the same state from the whole period of purge of DB and some not. Entities that have at least one state change are shown, entities without state change are not shown.

## Environment

- Home Assistant release with the issue: 0.115.3 (not mention of this in the .6 changelog...)
- Last working Home Assistant release (if known): 1.114, but not sure.
- Browser and browser version: Chrome ver 85.0.4183.121 (64 bit), Firefox ver. 81.0.1 (64 bit)
- Operating system: Windows 10 Pro 1909 build 18363.1082

## State of relevant entities

Following a dump from developer tools of an entity with updates and one without.
```yaml
#device_tracker.hshome
source_type: router
scanner: FritzBoxScanner
ip: 192.168.68.50
mac: 'XX:XX:XX:XX:XX:XX'
friendly_name: HSHOME
icon: 'mdi:desktop-tower'
#state: not_home

#device_tracker.nvr
source_type: router
latitude: xxx
longitude: xxx
gps_accuracy: 0
scanner: FritzBoxScanner
ip: 192.168.68.53
mac: 'XX:XX:XX:XX:XX:XX'
friendly_name: NVR
icon: 'mdi:server-network'
#state: home
```

## Problem-relevant configuration

```yaml
entities:
  - entity: device_tracker.hshome
  - entity: device_tracker.nvr
  - entity: device_tracker.osmc
  - entity: device_tracker.osmc_cameretta
  - entity: device_tracker.asciugatrice
  - entity: device_tracker.cam_front
  - entity: device_tracker.cam_bbq
  - entity: device_tracker.cam_salotto
  - entity: device_tracker.cam_pool
  - entity: device_tracker.echo_dot_pian_terreno
  - entity: device_tracker.echo_dot_mansarda
  - entity: device_tracker.tado_bridge
  - entity: device_tracker.luce_a_terra
  - entity: device_tracker.broadlink_camera
  - entity: device_tracker.broadlink_cameretta
  - entity: device_tracker.pompa_piscina
hours_to_show: 24
refresh_interval: 0
type: history-graph
```

## Javascript errors shown in your browser console/inspector

```txt

```
