### ISSUE TITLE
Missing power button when media_player is on

### ISSUE THREAD

**Issue by sploders101** [home-assistant/frontend#7457]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In previous versions of home assistant, media players always contained a power button in the lovelace entity dialog that could be used to turn the device on *and* off. That button now only shows up when the device is off, forcing me to either add a separate button, or go to the developer tools to turn off my TV.

## Expected behavior

The power button should be visible in all states except "Unavailable", allowing the user to turn their media players on and off.

## Steps to reproduce

1. Add a media_player integration that supports power controls (Android TV is a good example, assuming it supports CEC).
2. Navigate to Lovelace and find the entity for the media player
    1. Since this has to do with the entity *dialog*, you can do this straight from the "entities" configuration page
3. Turn the device on
4. Observe there is no way to turn it off now

## Environment

- Home Assistant release with the issue: 0.116.4
- Last working Home Assistant release (if known): 0.116.2 (not 100% sure on this as I ran two updates fairly close to one another)
- Browser and browser version: Chrome 86.0.4240.111, Firefox 82.0
- Operating system: Windows (client), Docker on CentOS 8 (server)

## State of relevant entities

```yaml
adb_response: null
friendly_name: Living Room TV
entity_picture: >-
  /api/media_player_proxy/media_player.living_room_tv_4?token=39bcbb5c7fb6ecb44b123e52d5ba8bd86808964aab90ef2b6e140d3b5dc16597&cache=1603407881.393676
supported_features: 23997
```
### Anything other than `off` or `unavailable`
![image](https://user-images.githubusercontent.com/26530958/96938853-a322b280-1488-11eb-8fd4-e219572584c1.png)

### `off`
![image](https://user-images.githubusercontent.com/26530958/96938830-9605c380-1488-11eb-80f4-0996abce2458.png)

## Problem-relevant configuration

```yaml
media_player:
  - platform: androidtv
    name: Living Room TV
    host: 10.0.0.142
```

## Javascript errors shown in your browser console/inspector

![image](https://user-images.githubusercontent.com/26530958/96939151-71f6b200-1489-11eb-8c9f-c633efd2fffc.png)

## Additional information
