### ISSUE TITLE
Binary Sensor status reset on reboot (while is still ok in history)

### ISSUE THREAD

**Issue by jokerigno** [home-assistant/frontend#7491]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I made an entity card for my windows binary sensors and I added the feature to show secondary info in lovelace (last changed)
What I noticed is that when I reboot the status is reset.

## Expected behavior

Status is reported correctly as shown in history

![image](https://user-images.githubusercontent.com/23552762/97234370-f1b1b300-17e0-11eb-8968-98683792ac9d.png)

## Environment

- Home Assistant release with the issue: 0.116
- Last working Home Assistant release (if known): NA
- Browser and browser version: Chrome and Edge
- Operating system: WIN 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```
entities:
  - entity: binary_sensor.portafinestrasoggiorno
    name: Porta Finestra Soggiorno
    secondary_info: last-changed
  - entity: binary_sensor.001558a99d4529_state
    secondary_info: last-changed
  - entity: binary_sensor.001558a99d4a8d_state
    secondary_info: last-changed
  - entity: binary_sensor.001558a99ef4be_state
    secondary_info: last-changed
  - entity: binary_sensor.portafinestracameradiadele
    name: Porta Finestra Camera di Adele
    secondary_info: last-changed
  - entity: binary_sensor.portafinestracucina
    name: Porta Finestra Cucina
    secondary_info: last-changed
  - entity: binary_sensor.finestra_cucina
    secondary_info: last-changed
  - entity: binary_sensor.001558a99d4e50_state
    secondary_info: last-changed
  - entity: binary_sensor.001558a99ef07a_state
    secondary_info: last-changed
type: entities
```

## Javascript errors shown in your browser console/inspector

```txt

```
