### ISSUE TITLE
Stack card header has extra padding and lost font style

### ISSUE THREAD

**Issue by dklemm** [home-assistant/frontend#7533]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

Stack card header has extra padding and lost font style introduced with #7373

<img width="507" alt="Screenshot 2020-10-29 at 19 19 35" src="https://user-images.githubusercontent.com/2111972/97626301-873b8580-1a21-11eb-9cd8-41eaf2366902.png">

## Steps to reproduce

1. Add title to stack card

## Environment

- Home Assistant release with the issue: 0.117
- Last working Home Assistant release (if known): 0.116
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
type: horizontal-stack
title: Hello World
cards: []
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by NobleKangaroo** [comment]
@dklemm I wanted to see if you're still experiencing this because - at least for me personally - 0.118 doesn't appear to fix this issue. If you're still having the issue and/or just want to take a peek, as you're the current subject matter expert (joking), I'll defer to you for some help here. I've spent a few hours poking around in Chrome dev tools, to the point of totally emptying a hui-entity-button-card and child ha-card [in 0.108.0](https://i.imgur.com/FRTTXl9.png) and comparing it to one [in 0.106.4](https://i.imgur.com/fspVvKc.png), but even after breaking it down to the bare minimum, I can't seem to pinpoint the exact element and/or CSS rule that's responsible for this issue. If you don't have time to look at this (or don't want to - that's okay too), I can open a new issue and go from there. Thank you!

**0.116.4**
Notice everything is lined up properly and paddings are as they should be
<img src="https://i.imgur.com/2l9TEu6.png">

**0.117.5 and 0.118 (really 0.117+ in general)**
Padding causes the cards to all become taller than they should be
<img src="https://i.imgur.com/l5vpeEg.png">

**0.117.5 and 0.118 (really 0.117+ in general)**
Removing the title and using [card-mod](https://github.com/thomasloven/lovelace-card-mod) to style it is *close*, but it's a lot of work (and it's not really fixing the issue)
<img src="https://i.imgur.com/3uHoLWH.png">

In my layout, I don't have any instances where a vertical-stack is affected; I presume this is because vertical-stack by nature is designed to fill the screen's height from top to bottom, but this may require more testing. I noticed that you can simply wrap a horizontal-stack with a vertical-stack to make it look better, but IMO that shouldn't be necessary; first as it's extra redundant work, and second because it wasn't required back in 0.116 so something broke this.

Here's the YAML I am using to generate this layout. You will probably need to adjust it due to differences in elements and cards you have, but it should give you an idea of what I'm doing:
<details>
<summary>Spoiler - click me</summary>

```yaml
views:
# Broken
  - title: Broken
    path: broken
    icon: 'mdi:alpha-b'
    panel: true
    badges: []
    cards:
      # Main wrapper for everything
      - type: vertical-stack
        cards:
          # Split the screen up into 4 columns
          - type: horizontal-stack
            cards:
              # Column 1: vertical-stack of titled horizontal stack (of entity-buttons) and vacuum card - looks pretty bad as you can see
              - type: vertical-stack
                cards:
                  - type: horizontal-stack
                    title: 118.0 (title in child horizontal-stack)
                    cards:
                      - type: entity-button
                        name: Den Lights
                        entity: light.den_lights
                      - type: entity-button
                        name: Light 1
                        entity: light.den_ceiling_light_1
                      - type: entity-button
                        name: Light 2
                        entity: light.den_ceiling_light_2
                      - type: entity-button
                        name: Light 3
                        entity: light.den_ceiling_light_3
                  - type: custom:xiaomi-vacuum-card
                    name: Robbie
                    entity: vacuum.roborock_s5
                    image: /local/img/vacuum.png
              # Column 2: titled vertical-stack of horizontal stack (of entity-buttons) and vacuum card - looks better, but I'm not convinced we should have to wrap every horizontal-stack with a vertical-stack just to fix this
              - type: vertical-stack
                title: 118.0 (title in parent vertical-stack)
                cards:
                  - type: horizontal-stack
                    cards:
                      - type: entity-button
                        name: Den Lights
                        entity: light.den_lights
                      - type: entity-button
                        name: Light 1
                        entity: light.den_ceiling_light_1
                      - type: entity-button
                        name: Light 2
                        entity: light.den_ceiling_light_2
                      - type: entity-button
                        name: Light 3
                        entity: light.den_ceiling_light_3
                  - type: custom:xiaomi-vacuum-card
                    name: Robbie
                    entity: vacuum.roborock_s5
                    image: /local/img/vacuum.png
              # Column 3: titled horizontal-stack of entity-buttons - looks bad compared to 0.116.4
              - type: horizontal-stack
                title: 118.0 (title in only horizontal-stack)
                cards:
                  - type: entity-button
                    name: Den Lights
                    entity: light.den_lights
                  - type: entity-button
                    name: Light 1
                    entity: light.den_ceiling_light_1
                  - type: entity-button
                    name: Light 2
                    entity: light.den_ceiling_light_2
                  - type: entity-button
                    name: Light 3
                    entity: light.den_ceiling_light_3
              # Column 4: titled vertical-stack of entity-buttons - looks about the same as 0.116.4
              - type: vertical-stack
                title: 118.0 (title in only vertical-stack)
                cards:
                  - type: entity-button
                    name: Den Lights
                    entity: light.den_lights
                  - type: entity-button
                    name: Light 1
                    entity: light.den_ceiling_light_1
                  - type: entity-button
                    name: Light 2
                    entity: light.den_ceiling_light_2
                  - type: entity-button
                    name: Light 3
                    entity: light.den_ceiling_light_3
```
</details>
