### ISSUE TITLE
Alignments not right since 117 update

### ISSUE THREAD

**Issue by jamieparris89** [home-assistant/frontend#7547]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

The alignment of cards is no longer centred correctly since the update to 0.117

As reported here https://community.home-assistant.io/t/alignments-not-right-since-117-update/240374/3

## Expected behavior

Cards to be perfectly aligned as they were in earlier versions

## Steps to reproduce

Install or update to version 0.117 and create a card on your dashboard using the default configuration
Problem is evident on varying browsers and mobile app

## Environment

- Home Assistant release with the issue: 0.117
- Last working Home Assistant release (if known): 0.116.X
- Browser and browser version: Google Chrome 86, Firefox 82.0.2, iOS 14 App, Android App
- Operating system: Windows 10, iOS 14, Android 10/11

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

![image](https://user-images.githubusercontent.com/68253698/97663613-2d44c980-1ace-11eb-95f5-bb519eaee57e.png)

**Comment by iantrich** [comment]
@jamieparris89 please provide your card configuration

**Comment by jamieparris89** [comment]
The one screenshotted is as follows;

cards:
  - card:
      entities:
        - entity: switch.heater
      title: Caution!
      type: glance
    conditions:
      - entity: switch.heater
        state: 'on'
    type: conditional
  - card:
      entities:
        - entity: switch.bathroom_socket
      title: Caution!
      type: glance
    conditions:
      - entity: switch.bathroom_socket
        state: 'on'
    type: conditional
type: horizontal-stack

**Comment by iantrich** [comment]
Can you post text instead? You can format yaml via https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting

**Comment by jamieparris89** [comment]
Don't think it makes a lot of difference, it looks the same but anyway

```

cards:
  - card:
      entities:
        - entity: switch.heater
      title: Caution!
      type: glance
    conditions:
      - entity: switch.heater
        state: 'on'
    type: conditional
  - card:
      entities:
        - entity: switch.bathroom_socket
      title: Caution!
      type: glance
    conditions:
      - entity: switch.bathroom_socket
        state: 'on'
    type: conditional
type: horizontal-stack

```

**Comment by jamieparris89** [comment]
From what I can tell, it only affects type "glance", other formats (buttons, light etc) formats correctly.

**Comment by iantrich** [comment]
> Don't think it makes a lot of difference, it looks the same but anyway

Makes it easier to test

**Comment by spacegaier** [comment]
> 
> Don't think it makes a lot of difference, it looks the same but anyway

I prefer not having to type your configuration character for character into my dev environment when trying to reproduce a reported issue 😄 .

Anyway, I cannot reproduce the issue on my end.
![image](https://user-images.githubusercontent.com/114137/97678335-f0f47780-1a93-11eb-9380-d1bed603d579.png)

**Comment by jamieparris89** [comment]
I'm using a Glance nested inside a Conditional nested inside a Horizontal Stack.

However, I just did a test with Glance on its own - alignment is fine. Then I did a test with Glance nested inside Conditional - alignment is also fine.

So the issue appears to be when Horizontal Stack is used.

If I recreate the card from scratch the issue remains.

**Comment by jamieparris89** [comment]
I just created a Horizontal Stack as follows and still get alignment issues;

```
type: glance
entities:
  - entity: sensor.sw_bathroom_energy_yesterday
  - entity: sensor.sw_bathroom_energy_today
  - entity: sensor.sw_bathroom_energy_total
title: Bathroom Socket
```
