### ISSUE TITLE
Markdown card is broken since 0.117

### ISSUE THREAD

**Issue by ibl129** [home-assistant/frontend#7571]
Since I updated Home Assistant to version 0.117 every Markdown card I use is leading to a non visible view. Other views are still visible, except the ones in which the Markdown is taking place.

**Comment by spacegaier** [comment]
I can't reproduce that. The card and its view work just fine.

What exactly do you mean by "non visible view"? The tab in the header bar is still there, but when going to it, there is no content (so all other cards in the view are gone)?

Also: Please use the issue template and fill it out to provide the required information.

**Comment by ibl129** [comment]
Hi @spacegaier, sorry for the inconvenience that I didn't make mention of the problem the way it should be. I hope I can hereby make the problem clearer.



## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem



When opening a particular view where a markdown card is included, I can not see any card in that specific view. 

I'm experiencing the problem from my webbrowser and from the mobile app. It seems not giving any difference whether I use a different device. 

## Expected behavior



I expected to see the text-content mentioned in the markdown card as in versions before 0.117.

## Steps to reproduce



When I tried to change the UI in raw by deleting the markdown card and saving the particular view; I can see every card (without the deleted markdown card of course). I tried making a new view, adding several entity cards and than adding a markdown card and from the moment I add a markdown card, the other entity cards are not displayed anymore. 

## Environment



- Home Assistant release with the issue: 0.117.1
- Last working Home Assistant release (if known): 0.116.4
- Browser and browser version: Safari 13.1.3 (15609.4.1) 
- Operating system: Mac OS Catalina 10.15.7 (19H2)

## State of relevant entities



```yaml
- content: >-
          Onderstaand kan het schema voor de centrale verwarming worden
          aangepast. 
        title: Centrale verwarming schema
        type: markdown
```

## Problem-relevant configuration



```yaml
- content: >-
          Onderstaand kan het schema voor de centrale verwarming worden
          aangepast. 
        title: Centrale verwarming schema
        type: markdown
```

## Javascript errors shown in your browser console/inspector



```txt
Logger: homeassistant
Source: runner.py:115 
First occurred: 16:15:18 (6 occurrences) 
Last logged: 16:15:48

Error doing job: An open stream object is being garbage collected; call "stream.close()" explicitly.
```

## Additional information
