### ISSUE TITLE
Logbook showing the wrong icon_template

### ISSUE THREAD

**Issue by logicup-dev** [home-assistant/frontend#7585]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
In the logbook, for a binary_sensor, the displayed icon is the one before the state changed. 

![Screenshot from 2020-11-02 20-41-19](https://user-images.githubusercontent.com/63303119/97939839-7fe1e800-1d51-11eb-8698-5a5472cf89a7.png)

## Expected behavior
In other words, for the state "on" it's displaying the icon_template for "off" and for "off" displaying the one for "on"

## Steps to reproduce

Look like it's showing the state before the icon_template is updated

## Environment

- Home Assistant release with the issue:  0.117.1
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 86.0.4240.111 (Official Build) (64-bit)
- Operating system: Debian 10

## State of relevant entities

```yaml
        icon_template: >-
          {% if is_state('binary_sensor.voiture', 'on') -%}
            mdi:car-connected
          {%- else -%}
            mdi:car
          {%- endif %}
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I made a quick test on my side, but could not reproduce. Switched the `updater` binary sensor on and off via dev tools and icon was used correctly.

```YAML
binary_sensor:
  - platform: template
    sensors:
      test_7585:
        friendly_name: Test 7585 Icon
        value_template: "{{ states('binary_sensor.updater') }}"
        icon_template: >-
          {% if is_state('binary_sensor.updater', 'on') -%}
            mdi:car-connected
          {%- else -%}
            mdi:car
          {%- endif %}
```

![image](https://user-images.githubusercontent.com/114137/97963345-3af09c80-1db7-11eb-8dd5-19e83e2d3ae4.png)
