### ISSUE TITLE
Thermostat card has insufficient width for set-values when thermostat allows two setpoints

### ISSUE THREAD

**Issue by ianmcorvidae** [home-assistant/frontend#7598]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

My thermostat (Z-Wave, Remotec ZTS500US) allows an "Auto" mode that allows setting both a heating and a cooling setpoint, and the thermostat decides for itself whether to heat or cool. In the Thermostat card, the set points are both shown with a dash between them, but the `set-values` section in the card has a width that doesn't accommodate that width, so I see only parts of each number plus the dash in-between.

I'm not completely sure if my thermostat is actually remembering my values either, but that's a separate problem.

Current behavior:

![Screen Shot 2020-11-04 at 18 35 45](https://user-images.githubusercontent.com/106004/98186714-9bbdc900-1ecc-11eb-8bfb-58c35d6bb6b1.png)

## Expected behavior

I would expect the display to accommodate the two values rather than cutting off content, or when cutting off content is necessary, show the most useful display it can.

Expected behavior (this is with setting the width to `60` in inspector, but I would expect HA to do some detection rather than a fixed value like this):

![Screen Shot 2020-11-04 at 18 37 01](https://user-images.githubusercontent.com/106004/98186790-bdb74b80-1ecc-11eb-90c2-7ac587f45b68.png)

## Steps to reproduce

1. Add or have a climate component that allows setting two values
2. Set that climate component to any necessary modes to allow two values, and set some values
3. Add or view Thermostat card in Lovelace
4. Observe values are not shown

## Environment

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.6
supervisor | 2020.11.0
timezone | America/Phoenix
version | 0.117.4
virtualenv | false

- Home Assistant release with the issue: 0.117.4
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Firefox 82.0
- Operating system: Linux (Ubuntu)

## State of relevant entities

Current mode is set to: `heat_cool`. The temps aren't updating right, which is why `target_temp_low` is at 0, but I don't think that distinction matters.

```yaml
hvac_modes:
  - heat
  - heat_cool
  - 'off'
  - cool
min_temp: 45
max_temp: 95
fan_modes:
  - Auto Low
  - On Low
preset_modes:
  - Resume
  - none
current_temperature: 74
temperature: null
target_temp_high: 75
target_temp_low: 0
fan_mode: Auto Low
hvac_action: idle
preset_mode: none
node_id: 10
value_index: 0
value_instance: 1
value_id: '72057594210942980'
fan_action: Idle
friendly_name: Thermostat Mode
supported_features: 27
```

## Problem-relevant configuration

No particular custom configuration, this is pretty much as-detected-by-zwave.

## Javascript errors shown in your browser console/inspector

None displayed
