### ISSUE TITLE
Automations: switching from the GUI editor to YAML and back does create invalid yaml for conditions with state lists

### ISSUE THREAD

**Issue by hal2100** [home-assistant/frontend#7600]
## The problem
Editing an automation with a state list in the conditions first in the file editor in pure yaml and opening the same automation in the UI editor changes the yaml of the conditions and makes it invalid.
Same happens if an automation is entered in the new automation YAML editor and one switches to the UI editor and back to the YAML editor.

## Environment
- Home Assistant Core release with the issue: 0.117.4
- Last working Home Assistant Core release (if known): unknown
- Operating environment (OS/Container/Supervised/Core): VM (supervised)
- Integration causing this issue: none?
- Link to integration documentation on our website: none?

## Problem-relevant `automation.yaml`
Example condition with valid yaml
```yaml
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: sensor.easee_home_XXXXX_status
        state:
          - CAR CONNECTED
          - READY TO CHARGE
          - CHARGING
          - PAUSED
```

Result of the same block after opening the automation in the UI editor, auto-generated and invalid (it seems):
```yaml
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: sensor.easee_home_XXXXX_status
        state: 'CAR CONNECTED,READY TO CHARGE,CHARGING,PAUSED'
```
