### ISSUE TITLE
Formating a number in a template sensor is not possible

### ISSUE THREAD

**Issue by logicup-dev** [home-assistant/frontend#7758]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Formating a number in a template sensor is not possible, the frontend is overwritting it to a different format

## Expected behavior

I created this template sensor for this issue, supposed to format a state to 3.30 instead of 3.3

If using this template in Template / Developer Tools it will be displayed as 3.30

If using this template creating a template sensor, the frontend is displaying the state as 3.3, or 3,3 depending where or witch card in lovelace. I'm using French language. 

It looks like the frontend is overwritting it to format the number a different way.

## Steps to reproduce

```
      test_template:
        friendly_name: "test template"
        value_template: >-
          {{ '{:.2f}'.format((float(1.3) * 1) + (float(1) * 1) + 1) }}
```

## Environment

- Home Assistant release with the issue: 0.118.0
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- Operating system: Ubuntu 20.04.1 LTS (client)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
