### ISSUE TITLE
Missing 0(s) after decimal point 

### ISSUE THREAD

**Issue by KNXBroker** [home-assistant/frontend#7787]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

0s are not displayed after decimal points in gauge cards and entities cards, while they are displayed in entity cards. 

Example:  Entities card shows 55, gauge card shows 55, entity card shows 55.0

![Unbenannt](https://user-images.githubusercontent.com/25910703/99969966-78838c80-2d9b-11eb-9b16-6bfa2b0e2c73.png)

This is the same for 'pop-ups';
![a](https://user-images.githubusercontent.com/25910703/99967508-491f5080-2d98-11eb-9a18-6d49231a6478.png)

## Expected behavior

The behaviour of the entity card is correct (56.0). Numbers should be displayed as defined (unless formated by a template or other setting). All other cards (and pop-ups) should display 56.0 as well. 

## Steps to reproduce

1. Create an entity with 55.0 
2. Create gauge and entities card

## Environment

- Home Assistant Core release with the issue:  Home Assistant 0.118.2
- Frontend: Frontend-Version: 20201111.2 - latest
- Operating environment (OS/Container/Supervised/Core): HassOS 4.17
- Browser and browser version: Chrome 86.0.4240.198
- Operating system: Windows 10

## State of relevant entities

In the developer tools you can see that the number is defined as 56.0

![f](https://user-images.githubusercontent.com/25910703/99967506-4886ba00-2d98-11eb-8b75-0e0c14a11f77.png)

```yaml
unit_of_measurement: °C
friendly_name: Processor temperature
icon: 'mdi:cpu-32-bit'
```

## Problem-relevant configuration

```yaml
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: gauge
        entity: sensor.disk_use_percent
        min: 0
        max: 100
        name: Festplatte
        severity:
          green: 0
          yellow: 70
          red: 90
      - type: gauge
        entity: sensor.processor_temperature
        min: 0
        max: 100
        name: Temperatur
        severity:
          green: 0
          yellow: 65
          red: 75
      - type: gauge
        entity: sensor.rpi_prozessorlast
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 75
          red: 90
  - type: entity
    entity: sensor.processor_temperature
  - type: entities
    entities:
      - entity: sensor.processor_temperature

```

## Javascript errors shown in your browser console/inspector

None

## Additional information

None
