### ISSUE TITLE
Reversed/Inverted `- platform: ping` binary_sensor icon color, based on state.

### ISSUE THREAD

**Issue by mitchell-bumgarner** [home-assistant/frontend#7791]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When I create a single entity card, or an `entities` card, which contains the `ping` `binary_sensor`, the state is exactly reversed, *only* on the Lovelace Frontend/GUI. To note, I would expect proper coloring to be GREEN == On/Connected, and then YELLOW == Off/Disconnected.

[*NOTE*: I'm not sure if this is related, is that the state is green on the entity-page when it's ***BOTH*** connected and disconnected, but I am not sure if it just doesn't refresh in time, or if it's even related. I wanted to include as much detail/testing information as possible, though.]

![Screen Shot 2020-11-23 at 11 38 40 AM](https://user-images.githubusercontent.com/55501744/100003326-e2983380-2d93-11eb-8d15-902debf07528.png)
^^ In the image above, you can see it's in the `Connected` state, but the icon is YELLO on the GUI. (Note: I clicked the entity to show it's GREEN in that page.)
![Screen Shot 2020-11-23 at 1 49 55 PM](https://user-images.githubusercontent.com/55501744/100003317-df9d4300-2d93-11eb-91fe-ea1c64748384.png)
^^ In this image above, you can see it's in the `Disconnected` state, but *now* the icon is GREEN on the GUI. (Note: I clicked the entity here to show it's still GREEN with no icon change.)
![Screen Shot 2020-11-23 at 1 54 13 PM](https://user-images.githubusercontent.com/55501744/100003320-e035d980-2d93-11eb-8f53-261e4b66af24.png)
^^ This image is the entity selected while the device is rebooting, AKA "Disconnected".

## Expected behavior

The entity icon color, based on state, for a `ping` `binary_sensor`, should show the icon as GREEN for On/Connected, and YELLOW for Off/Disconnected. (Even RED for disconnected would make more sense than GREEN, IMO.)

## Steps to reproduce

1. Add a binary_sensor, via the `- platform: ping`.
2. Navigate to Lovelace
3. Add either an `Entity` or `Entities` card, and set your binary_sensor.named_ping_device
4. Toggle the `Color icons based on state?` switch in the card settings.
5. Click save.

## Environment

- Home Assistant release with the issue: 0.118.3 (Note: This has been an issue since before 0.118.x releases.)
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Firefox 
- Operating system: Debian GNU/Linux 10 (buster) [4.19.0-12-amd64]
- Frontend version: 20201111.2 - latest

![Screen Shot 2020-11-23 at 2 12 25 PM](https://user-images.githubusercontent.com/55501744/100004778-fe9cd480-2d95-11eb-81e3-249a7f6907a1.png)
^^ Screenshot from the "System Health", under the `General` menu.

## State of relevant entities

![Screen Shot 2020-11-23 at 2 13 53 PM](https://user-images.githubusercontent.com/55501744/100004930-36a41780-2d96-11eb-9155-0a4d7af09ec4.png)

```yaml
round_trip_time_avg: 27.069
round_trip_time_max: 74.802
round_trip_time_mdev: ''
round_trip_time_min: 8.812
friendly_name: Garage Pi
device_class: connectivity
icon: 'mdi:raspberry-pi'
```

## Problem-relevant configuration

These are the entire sections relevant to this binary_sensor / PING.

```yaml
# MQTT binary sensor template testing
binary_sensor:
  - platform: mqtt
    state_topic: "garage/door/switch/input/state"
    name: "Garage Door"
    payload_on: 'off'
    payload_off: 'on'
    device_class: garage_door
    
  - platform: ping
    host: raspi01.my-domain.com
    name: "Garage Pi"
    # ONLY USE scan_interval for testing
    scan_interval: 10
    
homeassistant:
  customize:
    binary_sensor.garage_pi:
      friendly_name: 'Garage Pi'
      icon: mdi:raspberry-pi
```

## Javascript errors shown in your browser console/inspector

```txt
N/A
```
