### ISSUE TITLE
0.119.0.dev20201127: entity-filter does't work with default card entities

### ISSUE THREAD

**Issue by S-Przybylski** [home-assistant/frontend#7835]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After updating from 0.118dev to 0.119.0.dev20201127 the entitiy-filter doesn't work at all! I only see a red line.
Its the same for creating a fresh entity-filter: red line - no content

## Expected behavior

The entity filter should work as before using the default entities card.
If using the glance card, the filter works!
## Steps to reproduce

Create a new entity-filter card by using the  example from: https://www.home-assistant.io/lovelace/entity-filter/

````
type: entity-filter
entities:
  - binary_sensor.window_xyz
state_filter:
  - "on"
````
same for:
````
type: entity-filter
entities:
  - binary_sensor.window_xyz
state_filter:
  - "on"
card: 
  type: entities
  title: TEST
````  
BUT This works:
````
type: entity-filter
entities:
  - binary_sensor.window_xyz
state_filter:
  - "on"
card: 
  type: glance
  title: TEST
````  
## Environment

- Home Assistant release with the issue: Home Assistant 0.119.0.dev20201127
- Last working Home Assistant release (if known): 0.118dev
- Browser and browser version: Firefox and Edge
- Operating system: Windows 10 (browser); RASPI 4 Docker for HA

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
