### ISSUE TITLE
Attributes with a value of zero show up as "-" in an Entities card

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#7841]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

If I create an Entities card and add attribute rows whose value is zero (integer), they show up as a hyphen (-) in the card, rather than the value.

## Expected behavior

I expect all values to be displayed, regardless of whether they're zero.

## Steps to reproduce

1. Add an entities card
2. Add an attribute
3. Observe that the rendered card shows "-" when the value of the attribute is zero

## Environment

- Home Assistant release with the issue: 0.118.3
- Last working Home Assistant release (if known): ??
- Browser and browser version: Chrome 87
- Operating system: Home Assistant OS

## State of relevant entities

<img width="645" alt="Screen Shot 2020-11-27 at 5 11 36 PM" src="https://user-images.githubusercontent.com/860888/100490841-a8040300-30d3-11eb-86eb-baeee9c8423d.png">

## Problem-relevant configuration

```yaml
                - type: entities
                  entities:
                    - switch.la_marzocco
                    - type: attribute
                      entity: switch.la_marzocco
                      attribute: prebrewing_enabled
                      name: Prebrewing Enabled
                    - type: attribute
                      entity:  switch.la_marzocco
                      attribute: standby_timer
                      name: Standby Timer
                    - type: attribute
                      entity:  switch.la_marzocco
                      attribute: prebrewing_ton_k1
                      name: Prebrewing Time On Key 1
                    - type: attribute
                      entity:  switch.la_marzocco
                      attribute: prebrewing_ton_k1
                      name: Prebrewing Time On Key 2
                    - type: attribute
                      entity:  switch.la_marzocco
                      attribute: prebrewing_ton_k1
                      name: Prebrewing Time On Key 3
                    - type: attribute
                      entity:  switch.la_marzocco
                      attribute: prebrewing_ton_k1
                      name: Prebrewing Time On Key 4
```

<img width="400" alt="Screen Shot 2020-11-27 at 5 04 26 PM" src="https://user-images.githubusercontent.com/860888/100490815-5d828680-30d3-11eb-9cd2-548a92b00239.png">
<img width="490" alt="Screen Shot 2020-11-27 at 5 04 44 PM" src="https://user-images.githubusercontent.com/860888/100490820-64a99480-30d3-11eb-8b29-5c2415ce7ff6.png">

## Javascript errors shown in your browser console/inspector

None
