### ISSUE TITLE
Styling badges - Loosing custom color

### ISSUE THREAD

**Issue by medicus07** [home-assistant/frontend#7849]
Hey there!

My Home Assistant version: 0.118.2, problem in newer versions of HA, don't know exactly since when... I think 0.110 was working fine

My lovelace configuration method (GUI or yaml): YAML

What I am doing: 
I style my badges with card mod (https://github.com/thomasloven/lovelace-card-mod) in the following way...

``` 
badges:
  - entity: binary_sensor.garage_status
    name: Garage
      style: |
        :host {
          --label-badge-blue: {% if is_state('binary_sensor.garage_status', 'off') %} green {% else %} red {% endif %};
        }
```

What I expected to happen: 
Changing color of the badge between green and red...

What happened instead: 
When refreshing webpage or app, there is no color in styled batches anymore. After clicking or touching screen, push a button or something else, the color appears again. In older versions of HA it worked just fine without this bug.

Screenshots:
<img width="340" alt="Bildschirmfoto 2020-11-22 um 08 53 56" src="https://user-images.githubusercontent.com/24975901/99898252-4e996f80-2ca0-11eb-8550-64bddce7c691.png">
<img width="344" alt="Bildschirmfoto 2020-11-22 um 08 53 40" src="https://user-images.githubusercontent.com/24975901/99898255-51946000-2ca0-11eb-90e0-91a9eacba9ab.png">

in configuration.yaml I use the following:

```
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/custom-ui/custom-ui.js

lovelace:
  mode: yaml

homeassistant:
  customize:
    binary_sensor.garage_status:
      device_class: garage_door
      unit_of_measurement: 'Status'

binary_sensor:
  - platform: mqtt
    state_topic: "homee.garage"
    name: "Garage Status"
```

in ui-lovelace.yaml I use the following:

```
resources:
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module

views:
  - badges:
      - entity: binary_sensor.garage_status
        name: Garage
        style: |
          :host {
            --label-badge-blue: {% if is_state('binary_sensor.garage_status', 'off') %} green {% else %} red {% endif %};
          }
```

<img width="364" alt="Bildschirmfoto 2020-11-24 um 20 52 24" src="https://user-images.githubusercontent.com/24975901/100144399-07290400-2e97-11eb-96c7-60a35b2f9555.png">

I did some testing around and could localize the problem with Safari and the HA iOS App (also Safari based). In Log-File there are no further hints or information.

Here a video of the behavior:

![HA1](https://user-images.githubusercontent.com/24975901/100551173-57310d80-327f-11eb-9a9c-020727b3dda0.gif)

Thanks a lot.
Michael
