### ISSUE TITLE
Picture Glance cards do not appear in Firefox for Android (works in Chrome)

### ISSUE THREAD

**Issue by synthead** [home-assistant/frontend#7852]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Picture Glance cards don't appear in Firefox for Android.  Here is an example where I would normally be able to see Picture Glance cards for camera feeds:

![image](https://user-images.githubusercontent.com/820984/100655763-93588280-3300-11eb-8d6a-2f3143c3be78.png)

This functionality works correctly on Chrome for Android.

## Expected behavior

Picture Glance cards appear in Firefox for Android.

## Steps to reproduce

1. Install Firefox for Android on an Android device.
2. Log into HA using Firefox for Android.
3. Attempt to view a Picture Glance card in the UI.
4. Observe that the Picture Glance cards are not displayed.

## Environment

- Home Assistant release with the issue: 0.117.5
- Last working Home Assistant release (if known): This used to work 1-2 months ago (sorry for being vague)
- Browser and browser version: Firefox for Android
- Operating system: Arch Linux (server), Android (client)

## State of relevant entities

```yaml
access_token: <removed>
friendly_name: Front door
entity_picture: >-
  /api/camera_proxy/camera.front_door?token=<removed>
supported_features: 0
```

## Problem-relevant configuration

The Picture Glance card in my example was added via the HA UI, so I have not written YAML for it.  I'm using a typical ZoneMinder integration, though:

```yaml
zoneminder:
  host: <removed>
  path: /
  path_zms: /cgi-bin/nph-zms
  ssl: true
  username: <removed>
  password: <removed>
```

## Javascript errors shown in your browser console/inspector

_No errors_
