### ISSUE TITLE
Lots of strings missing in editing mode (1.0.0b0)

### ISSUE THREAD

**Issue by EricReiche** [home-assistant/frontend#7881]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The kebap menu when editing a card doesn't show  any text. Neither are there descriptions in the editing dialog window.
![grafik](https://user-images.githubusercontent.com/894987/100979756-82984e80-3544-11eb-806d-b16d7b70a18a.png)
![grafik](https://user-images.githubusercontent.com/894987/100979799-917f0100-3544-11eb-9f7e-9bfe66f74c52.png)

Maybe related: When cliking on the save button after editing, the card is duplicated with the new settings. So afterwards, you got the "new" and the "old" version of the card on the dashboard.

## Expected behavior

I expected the same strings there as in 0.118.4. I expect cards to be updated after saving, not duplicated.

## Steps to reproduce

* Upgrade to 1.0.0b0
* Edit existing dashboard cards

I tried switching between German and English, between custom and default theme, even uninstalling the custom theme, no difference.

## Environment

- Home Assistant release with the issue: 1.0.0b0
- Last working Home Assistant release (if known): 0.118.4
- Browser and browser version: Firefox 83.0, Chrome 87.0.4280.88
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
views:
  - badges: []
    cards:
      - entities:
          - entity: light.e1_flur_decke
          - entity: light.e1_flur_wand
          - entity: light.o1_treppenlicht_oben
          - entity: light.o1_flur_wand
        title: Flur
        type: entities
        state_color: true
      - entities:
          - entity: light.o2_schlafzimmer_balken
          - entity: light.o2_schlafzimmer_bett_links
          - entity: light.o2_schlafzimmer_bett_rechts
          - entity: light.o2_schlafzimmer_spiegel
          - entity: light.o3_yyy
          - entity: light.o4_zzz_decke
          - entity: light.o5_xxx_decke
          - entity: light.o6_bad
          - entity: light.o7_hobbyraum_decke
        title: OG
        type: entities
        state_color: true
      - entities:
          - entity: light.eingangsbeleuchtung_hausnr
          - entity: light.extended_color_light_1_6
          - entity: light.a3_ddd
          - entity: light.hue_outdoor_wall_1
          - entity: light.a3_ccc
        title: Aussen
        type: entities
        state_color: true
      - entities:
          - entity: light.shelly_shsw_1_xxx
          - entity: light.shelly_shsw_1_zzz
          - entity: switch.xxx
          - entity: switch.zzz
          - entity: light.hue_lightstrip_plus_1
          - entity: light.hue_lightstrip_plus_2
        title: Keller
        type: entities
      - type: entities
        entities:
          - entity: switch.e1_flur_fenster
          - entity: switch.e5_wohnen_fenster_steckdose
          - entity: switch.o4_zzz_fenster
          - entity: switch.o5_xxx_fenster
          - entity: switch.a1_terasse_aussenecke
          - entity: switch.a1_terasse_innenecke
          - entity: switch.e4_kuche_fenster
          - entity: switch.e3_buro_wand_l
          - entity: switch.eg_j
        title: Steckdosen
        state_color: true
      - entities:
          - entity: light.extended_color_light_1
          - entity: light.extended_color_light_1_7
          - entity: light.extended_color_light_1_3
          - entity: light.extended_color_light_1_8
          - entity: light.extended_color_light_1_4
          - entity: light.extended_color_light_1_5
          - entity: light.a3_xxx_spots
        title: Garten
        type: entities
        state_color: true
      - entities:
          - entity: light.e2_wc_decke
          - entity: light.e3_buro_deckenventilator
          - entity: light.e3_buro_vitrine
          - entity: light.kuche_decke_ambiance
          - entity: light.kuche_ecke_hinten_rechts
          - entity: light.kuchenschrank_links
          - entity: light.kuchenschrank_rechts
          - entity: light.esstisch_pendant_up
          - entity: light.esstisch_pendant_down
          - entity: light.e5_wohnen_spots
          - entity: light.e5_wohnen_decke_stripes
          - entity: light.buro_pendant_up
          - entity: light.buro_pendant_down
          - entity: light.twinkly_xxx
        title: EG
        type: entities
        state_color: true
    icon: 'mdi:lamp'
    panel: false
    path: licht
    title: Licht
  - badges: []
    cards:
      - entities:
          - entity: cover.aaa_rollos
          - entity: cover.bbb_rollos
          - entity: cover.ccc_rollo
        type: entities
      - entities:
          - entity: script.tor_auf
          - entity: script.tor_zu
        title: Einfahrt
        type: entities
    icon: 'mdi:blinds'
    path: rollo
    title: Rollo
  - badges: []
    cards:
      - entities:
          - entity: input_number.bbb
          - entity: input_number.ccc
          - entity: input_number.ddd
        type: glance
      - entity: weather.ds2
        type: weather-forecast
      - entities:
          - entity: light.zzz
          - entity: switch.aaa
        type: entities
      - entity: sensor.vicare_outside_temperature
        graph: line
        type: sensor
    icon: 'mdi:water'
    path: outside
    title: outside
  - badges: []
    cards:
      - entities:
          - entity: input_select.trockner_status
          - entity: input_select.waschmaschine_status
        type: glance
      - entity: sensor.abfall
        type: entity
      - entity: sensor.nuki_bridge
        type: entity
      - entities:
          - entity: sensor.inverter_instant_power
          - entity: sun.sun
        type: glance
      - entity: climate.vicare_heating
        type: thermostat
    icon: 'mdi:information'
    path: info
    title: Info
  - badges: []
    cards:
      - entity: switch.xxxx
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
      - entity: switch.yyyy
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
      - entity: light.shelly_shsw_1_xxxx
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
      - entity: light.shelly_shsw_1_xxxx
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
    icon: 'mdi:party-popper'
    path: party
    title: Party

```

## Javascript errors shown in your browser console/inspector

none
