### ISSUE TITLE
Blueprint description lacks padding

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7895]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Small visual thing, but the Blueprint description lacks padding, it is touching the left of the card and looks weird.

![image](https://i.imgur.com/7vDWbPa.png)

## Expected behavior

Should instead be lined up with the text below it imo.
## Steps to reproduce

Add a description to Blueprint (see code below)

## Environment

- Home Assistant release with the issue: 0.1.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
blueprint:
  name: Welcome Home
  description: Plays a welcome home message on a Cast-enabled device
```

## Javascript errors shown in your browser console/inspector

```txt

```
