### ISSUE TITLE
state_color: true not being shown on light card for color lights

### ISSUE THREAD

**Issue by JeeWeetje** [home-assistant/frontend#7904]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The problem is that I have 3 color lights as Light cards in a grid but when I add state_color : true to the Lights in the grid, the state color  (yellow) isn't shown when the lights are on.

## Expected behavior
Adding state_color to the color lights in a grid showing the state color yellow when turned on if the property state_color : true is added to them. Like the behavior is for white only lights.

## Steps to reproduce
Create a light card or a grid with light card for color lights like:
Single color light in light card
```yaml
type: light
entity: light.hornbach_extended_color_light
state_color: true
```
Multiple light cards in grid
```YAML
type: grid
cards:
  - type: light
    entity: light.<color light entity name>
    state_color: true  
  - type: light
    entity: light.<color light entity name>
    state_color: true
  - type: light
    entity: light.<color light entity name>
    state_color: true
```

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known): 0.118.0 & 0.1118.4 (docker container, container deamon: moby, host: RPi3B+, Raspbian Buster)
- Browser and browser version: Microsoft Edge Version 87.0.664.47 (Official build) (64-bit)
- Operating system: Windows 10 20H2 build 19042.662

## State of relevant entities

```yaml

```

## Problem-relevant configuration

![image](https://user-images.githubusercontent.com/693760/101143890-d58f0600-3617-11eb-8643-b492d375b558.png)

```yaml
type: grid
cards:
  - type: light
    entity: light.<light entity name>
    state_color: true  
  - type: light
    entity: light.<light entity name>
    state_color: true
  - type: light
    entity: light.innr_extended_color_light
    state_color: true
```
```yaml
effect_list:
  - colorloop
brightness: 95
hs_color:
  - 197.037
  - 95.294
rgb_color:
  - 12
  - 186
  - 255
xy_color:
  - 0.147
  - 0.23
is_deconz_group: false
friendly_name: Ikea - color
supported_features: 61
```
```yaml
min_mireds: 140
max_mireds: 650
effect_list:
  - colorloop
brightness: 95
hs_color:
  - 197.037
  - 95.294
rgb_color:
  - 12
  - 186
  - 255
xy_color:
  - 0.147
  - 0.23
is_deconz_group: false
friendly_name: Hornbach - color
supported_features: 63
```

```yaml
min_mireds: 140
max_mireds: 650
effect_list:
  - colorloop
brightness: 95
hs_color:
  - 197.037
  - 95.294
rgb_color:
  - 12
  - 186
  - 255
xy_color:
  - 0.147
  - 0.23
is_deconz_group: false
friendly_name: Innr - color
supported_features: 63
```
## Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by spacegaier** [comment]
I cannot reproduce this issue. My light cards in a grid are yellow if they are on, even without `state_color` being set. However, my lights are pure white ones, no color, so perhaps this comes into play here?

**Comment by JeeWeetje** [comment]
I noticed there was a never version of Home Assistant docker container available. Pulled that one, but the issue persists in that version (HA 0.118.4) as well.

**Comment by JeeWeetje** [comment]
@Spacegaier let me check that with a white only light. Good suggestion.

**Comment by JeeWeetje** [comment]
@spacegaier indeed it is color light related.

![image](https://user-images.githubusercontent.com/693760/101157475-7c7c9d80-362a-11eb-8a1c-ab1492300f05.png)

The Dining table light is a Philips Hue Ambient White. The other is a Hornbach color light.

**Comment by JeeWeetje** [comment]
Updated the issue to represent the actual problem (scoped to color lights only).

**Comment by spacegaier** [comment]
And just to double-check. Outside of a grid card, the light card with a color light works fine? How does the icon look there? Does it reflect the selected color of the lamp or also only on/off (yellow/blue)?

**Comment by JeeWeetje** [comment]
@spacegaier the issue need further refinement. It is indeed light related not light in grid. The state of a color light.

![image](https://user-images.githubusercontent.com/693760/101159456-bdc27c80-362d-11eb-94fe-d3601bb009bf.png)
```yaml
type: light
entity: light.hornbach_extended_color_light
state_color: true
```

**Comment by JeeWeetje** [comment]
@spacegaier  ultimate support would be that the on state for color lights represent the set color as well, but that would be a feature request, I guess. ;-)

**Comment by spacegaier** [comment]
Yes, FR and a bit tricky, since then the off color would need to get changed to gray as the current blue off color, would then be misleading.

**Comment by JeeWeetje** [comment]
Turned on it shows this in developer tools:
```yaml
min_mireds: 140
max_mireds: 650
effect_list:
  - colorloop
brightness: 95
hs_color:
  - 197.037
  - 95.294
rgb_color:
  - 12
  - 186
  - 255
xy_color:
  - 0.147
  - 0.23
is_deconz_group: false
friendly_name: Hornbach - color
supported_features: 63
```
![image](https://user-images.githubusercontent.com/693760/101195513-d0ee4000-365f-11eb-8e52-95c53385a0f3.png)

But it isn't limited to any other color light other than Philips Hue it seems. The only showing correctly on/off state is a Philips Hue Ambient Color E14 candle. 

The original yaml from the grid (in the original issue reported), included a IKEA TRÅDFRI bulb E27 CWS opal 600lm, INNR RB 285 C and a HORNBACH VIYU-A60-806-RGBW-10011725. Which all seem not be able to show on/off state in color.
