### ISSUE TITLE
Scene editor adds to much fields for an input_select

### ISSUE THREAD

**Issue by stieler-it** [home-assistant/frontend#7936]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I want to include an input_select in my scenes, so it is set to a specified value. The generated YAML does not only contain the value but also the list of options, which I assume leads to an additional value change to the first value, followed by the correct value.

Generated YAML:
```yaml
    input_select.my_select:
      options:
      - One
      - Two
      - Three
      editable: true
      friendly_name: My Select
      state: Three
```

## Expected behavior

If the scene is activated, the input_select's value is set to the specified value directly.

Expected YAML:
```yaml
    input_select.my_select:
      state: Three
```

## Steps to reproduce

1. Add input_select with some options
2. Create a scene, add the input_select and set it to a value that is not the first one
3. Activate the scene

In the history of the input_select you should see that it was first changed to the first value, then to the specified one.

## Environment

- Home Assistant release with the issue: Home Assistant 0.118.5
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system: HassOS 4.17

## State of relevant entities

-

## Problem-relevant configuration

-

## Javascript errors shown in your browser console/inspector

-
