### ISSUE TITLE
input_datetime detail view cuts off leading zeros

### ISSUE THREAD

**Issue by SeraphimSerapis** [home-assistant/frontend#7957]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The detail view for any input_datetime entity is cutting off leading zeros as exemplified in the screenshot.

<img width="395" alt="Screenshot 2020-12-13 at 11 33 25" src="https://user-images.githubusercontent.com/160543/102009407-7fb50f00-3d37-11eb-854d-3c9e777a5e75.png">

This issue has been referenced in a old comment before, but no separate issue was created: https://github.com/home-assistant/frontend/issues/3920#issuecomment-547349240

## Expected behavior

Instead of 11:7, the time should be displayed as 11:07. The same applies for hours, too:

<img width="384" alt="Screenshot 2020-12-13 at 11 39 00" src="https://user-images.githubusercontent.com/160543/102009458-d6bae400-3d37-11eb-9987-852c4678426d.png">

## Steps to reproduce

1. Set any input_datetime entity to either a time containing hour or minute < 10.
2. Select the entity in the frontend to see the details
3. Time displays incorrectly.

## Environment

- Home Assistant release with the issue: 0.118.5
- Last working Home Assistant release (if known): -
- Browser and browser version: Google Chrome 87.0.4280.88
- Operating system: OSX 10.15.7

## State of relevant entities

```yaml
editable: false
has_date: true
has_time: true
year: 2020
month: 12
day: 13
hour: 11
minute: 7
second: 0
timestamp: 1607854020
friendly_name: Letzte Reinigung Keller
```

## Problem-relevant configuration

```yaml
cat_clean_basement:
  name: Letzte Reinigung Keller
  has_date: true
  has_time: true
```

## Javascript errors shown in your browser console/inspector

```txt

```
