### ISSUE TITLE
Number Selector for Blueprint-based automation returns string instead of integer

### ISSUE THREAD

**Issue by DerFlob** [home-assistant/frontend#7975]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have a blueprint with a 'number' input. When I create an automation from the blueprint and select the number, it is saved as a string, not an integer into the yaml-configuration. This breaks/makes the automation fail.

```yaml
alias: Number input test
description: ''
use_blueprint:
  path: number-input.yaml
  input:
    test_number: '16' # expected this to be a 16 instead.
```

## Expected behavior

The selected number should be saved as an integer instead of a string into the yaml-configuration

## Steps to reproduce

1. Import example blueprint below
2. Create new automation from it
3. Select a number of your choosing
4. Change to 'Edit as YAML'

## Environment

- Home Assistant release with the issue: 2020.12.0
- Last working Home Assistant release (if known): -
- Browser and browser version: Firefox 80
- Operating system: Linux

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
blueprint:
  name: Number input test
  domain: automation
  input:
    test_number:
      name: Test number
      description: Would expect to get an integer, selected through UI.
      selector:
        number:
          min: 0
          max: 42
          mode: box

trigger: []
condition: []
action: []
```

## Javascript errors shown in your browser console/inspector

```txt

```
