### ISSUE TITLE
All other items disappear when removing an item from sidebar

### ISSUE THREAD

**Issue by SmarterHomeLife** [home-assistant/frontend#7977]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When I try to remove an item from the sidebar menu all other items disappear so you can only remove 1 at a time, clicking done and going back into edit mode has no effect, you have to refresh the browser.  When you go back into edit mode and remove another item all other items disappear except the previously removed items remain with a + to add them back.
## Steps to reproduce
![Screenshot](https://user-images.githubusercontent.com/69889375/102175312-6953b280-3ef3-11eb-8049-784625752265.png)

Try to remove a sidebar item.
## Environment

- Home Assistant release with the issue:  2020.12.0 noticed it happening in 1.0.0.b0 also
- Last working Home Assistant release (if known): 0.118
- Browser and browser version: Chrome, Edge and Firefox
- Operating system: Zorin OS (Linux) and Android 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
homeassistant:
  customize: !include smarterhomelife/config/customize.yaml

default_config:

frontend:
  themes: !include_dir_merge_named smarterhomelife/themes/

lovelace:
  mode: yaml
  resources: !include smarterhomelife/resources/resources.yaml
  dashboards:
    brad-ui:
      mode: yaml
      filename: brad-ui.yaml
      title: Brad
      icon: mdi:home-variant-outline
      show_in_sidebar: true
      require_admin: true
    emma-ui:
      mode: yaml
      filename: emma-ui.yaml
      title: Emma
      icon: mdi:home-variant-outline
      show_in_sidebar: false
      require_admin: false
    home-ui:
      mode: yaml
      filename: home-ui.yaml
      title: Home
      icon: mdi:home-variant-outline
      show_in_sidebar: true
      require_admin: false
    tablet-ui:
      mode: yaml
      filename: tablet-ui.yaml
      title: Tablet
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      require_admin: true
    admin-ui:
      mode: yaml
      filename: admin-ui.yaml
      title: Administrator
      icon: mdi:account-cog-outline
      show_in_sidebar: true
      require_admin: true

browser_mod:
  disable:
    - light

cast:

local_ip:

recorder:
  purge_keep_days: 7

notify:
  - name: !secret signal_name
    platform: signal_messenger
    url: http://10.0.1.10:8080
    number: !secret signal_number
    recipients: !secret brad_mobile

  - name: !secret simplepush_name
    platform: simplepush
    device_key: !secret simplepush_device_key
    password: !secret simplepush_password
    salt: !secret simplepush_salt

  - name: !secret twilio_name
    platform: twilio_sms
    from_number: !secret twilio_from

  - platform: html5
    name: !secret html5-name
    vapid_pub_key: !secret html5-pub-key
    vapid_prv_key: !secret html5-pri-key
    vapid_email: !secret html5-email

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

smartir:

climate:
  - platform: smartir
    name: Air Conditioning
    unique_id: air-conditioning
    device_code: 1281
    controller_data: remote.rm_mini_3_remote
    temperature_sensor: sensor.living_room_smartsensor_temperature
    humidity_sensor: sensor.living_room_smartsensor_humidity
    power_sensor: switch.aircon_power

tts:
  - platform: google_translate
    service_name: google_say

alarm_control_panel: !include smarterhomelife/config/alarm.yaml
automation: !include_dir_merge_list smarterhomelife/config/automations/
binary_sensor: !include smarterhomelife/config/binary_sensor.yaml
cover: !include smarterhomelife/config/cover.yaml
device_tracker: !include smarterhomelife/config/device_tracker.yaml
fan: !include smarterhomelife/config/fan.yaml
group: !include smarterhomelife/config/group.yaml
input_boolean: !include smarterhomelife/config/input_boolean.yaml
input_number: !include smarterhomelife/config/input_number.yaml
input_select: !include smarterhomelife/config/input_select.yaml
light: !include smarterhomelife/config/light.yaml
media_player: !include smarterhomelife/config/media_player.yaml
scene: !include smarterhomelife/config/scene.yaml
script: !include smarterhomelife/config/script.yaml
sensor: !include smarterhomelife/config/sensor.yaml
switch: !include smarterhomelife/config/switch.yaml
```

## Javascript errors shown in your browser console/inspector

```txt

```
