### ISSUE TITLE
Cannot save a blueprint with default selector values until values are modified.

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#8011]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

If a blueprint's selectors have default values, the UI initially ignores them and you cannot save the automation until you modify at least one of the inputs.

## Expected behavior

Should be able to save the automation using the default values without first having to edit at least one of them.

## Steps to reproduce

Here's the relevant section from the blueprint:
```
  input:
    first_entity:
      name: First Light
      description: Select a light.
      selector:
        entity:
          domain: light
      default: light.hallway_light
    second_entity:
      name: Second Light
      description: Select a light.
      selector:
        entity:
          domain: light
      default: light.foyer_light
```
Here's its appearance in the UI. Notice the lack of the SAVE button in the bottom-right.

![Screenshot from 2020-12-18 12-12-01](https://user-images.githubusercontent.com/44732909/102642180-49a6cf00-412b-11eb-9b82-bd204a673c0b.png)

If I change at least one of the two inputs, the SAVE button appears.

![Screenshot from 2020-12-18 12-22-17](https://user-images.githubusercontent.com/44732909/102642500-c46fea00-412b-11eb-850f-f9efc176ea7a.png)

If I want to save it using its default input values, I first have to change at least one of the inputs to another value then change it back to its default value.

## Environment

- Home Assistant release with the issue: 2020.12.1
- Last working Home Assistant release (if known): New feature
- Browser and browser version: Firefox 84.0
- Operating system: Ubuntu 20.04.1

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
