### ISSUE TITLE
The logbook card keeps loading when tab is casted on google cast device

### ISSUE THREAD

**Issue by cyberjunky** [home-assistant/frontend#8013]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have a tab with below Lovelace code, the logbook card doesn't display it's content but keeps loading when the tab is cast to a Nest Hub for example.

## Expected behavior

Showing it's contents also when casting.

## Steps to reproduce

Create a tab with below Lovelace code and cast it to a Nest Hub.

## Environment

- Home Assistant release with the issue: 2020.12.1
- Last working Home Assistant release (if known): I think the issue was always there
- Browser and browser version: Nest Hub
- Operating system:  Nest Hub

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
  - title: Brandweer
    path: fireservicerota
    icon: 'mdi:fire-truck'
    badges: []
    cards:
      - type: logbook
        entities:
          - sensor.incidents
        hours_to_show: 24
```

## Javascript errors shown in your browser console/inspector

```txt

```
