### ISSUE TITLE
Custom icons do not show up on iOS 10

### ISSUE THREAD

**Issue by jpirnie** [home-assistant/frontend#8032]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

- On an old iPad 4 which runs iOS 10, when you use any custom icons in customize.yaml, they will not show up on the iPad.  It seems that anything in a template like this does not work.  You can however set an icon outside of templates: and the icon does show up without any trouble, even the icons you're using inside the templates section.  The issue appears to be the templates section on the older iPad 4 devices running iOS 10.

```yaml
switch.xmas_tree_big:
  templates:
    icon: >
      if (state === 'off') return 'mdi:pine-tree';
      if (state === 'on') return 'mdi:pine-tree';
    
    icon_color: >
      if (state === 'on') return 'rgb(255,0,0)';
```

This is the way it looks on a computer:
![8fdf144e6018a8309011664f346cdfc6ddc7c7b6](https://user-images.githubusercontent.com/33987478/102904925-495a4c80-4427-11eb-8aea-1ff204fbd93e.png)

This is the way it looks on the iPad 4:
![c180fa35d0552cb36082a8ed98c5092f48132b25_2_375x500](https://user-images.githubusercontent.com/33987478/102904947-5119f100-4427-11eb-914e-1de68127bc99.jpeg)

## Expected behavior
Since the icons are just images and can show up if you set them outside of the templates area, I would expect all of those modifications to work on iOS 10 devices.

This is the way it should look:
![8fdf144e6018a8309011664f346cdfc6ddc7c7b6](https://user-images.githubusercontent.com/33987478/102904925-495a4c80-4427-11eb-8aea-1ff204fbd93e.png)

## Steps to reproduce

1. Make a customize.yaml file with the code in it that changes the icon of an entity.
2. It shows up as changed on the computer, but doesn't change on iOS 10 devices
 
    1. Make a custom setup to an entity in the customize.yaml like this:

```yaml 
        switch.xmas_tree_big:
              templates:
                   icon: >
                       if (state === 'off') return 'mdi:pine-tree';
                       if (state === 'on') return 'mdi:pine-tree';
    
                 icon_color: >
                      if (state === 'on') return 'rgb(255,0,0)';
```
    2. Check to see it works on the computer to know it is working
    3. Look at it on an iOS 10 device.

## Environment

- Home Assistant release with the issue: 2020.12.1
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Safari in Big Sur
- Operating system: Max OS X Big Sur
- iPad 4 running iOS 10

This is an iPad 4 running iOS 10.  I tried the HA app, Safari, Chrome, and Firefox and they all do the same thing.

## State of relevant entities

The state of the entity doesn't matter.

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
