### ISSUE TITLE
entities card can not support templates with secondary info

### ISSUE THREAD

**Issue by SevenPlusJun** [home-assistant/frontend#8033]
![图片](https://user-images.githubusercontent.com/10571170/102973159-40f13700-4537-11eb-98e3-7f350feb59f2.png)

```
UI editor is not supported for this config:

    The value of "entities.0" is not supported by the UI editor, we support "Object<{entity,name,icon,image,secondary_info,format,state_color,tap_action,hold_action,double_tap_action}> | string | Object<{type,name,action_name,tap_action,hold_action,double_tap_action}> | Object<{type,view,dashboard,name,icon,hide_if_unavailable}> | Object<{type,row,conditions}> | Object<{type,style}> | Object<{type,label}> | Object<{type,url,name,icon}> | Object<{type,entities}> | Object<{type,entity,attribute,prefix,suffix,name}> | Object<{type,name,service,icon,action_name,service_data}>" but received "{"entity":"light.jingqiandeng","secondary_info":[["sensor.jing_qian_deng_shi_jian_chuo"]],"type":"custom:secondaryinfo-entity-row"}".


You can still edit your config in YAML. 
```

configurations:

```
entities:
  - entity: light.jingqiandeng
    secondary_info: [[ sensor.jing_qian_deng_shi_jian_chuo ]]
    type: 'custom:secondaryinfo-entity-row'

```
