### ISSUE TITLE
Possible to create invalid automation that is not listed

### ISSUE THREAD

**Issue by sytem** [home-assistant/frontend#8040]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I tried to create automation, temperature alert for my fridge. I started from sensor and create automation. In the editor there are fields for both above and below, I entered 12 and 2 and then time 10 seconds.
 
![Screen Shot 2020-12-28 at 14 53 39](https://user-images.githubusercontent.com/10594837/103216324-75da0100-491e-11eb-9284-81a446c50259.png)

Then alert action and save, no error message. But also no "execute button" on editor page, and when I get to the automation list, that new automation is not there. Then repeated this few times, no erros, but no new automations on list. Third time, after save, I copied page url and that is working even that automation is not on the list.

Tried to reload automation and then I got error message what is wrong: 

"Failed to call service automation/reload. A value can never be above 12.0 and below 2.0 at the same time. You probably want two different triggers."

Only way I found to remove these is edit yaml manually and then reload

## Expected behavior

There could be description that only either value can be filled.
There should be clear error message when saving automation if there is something wrong with it. 
Invalid automations should be also on list so they can be edited or removed via gui.

## Steps to reproduce

1. create automation
2. enter something invalid, like both above and below values
3. save and navigate away
4. be unable to find invalid automation

## Environment

Frontend version: 20201212.0 - latest

Version | 2020.12.1
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 4.9.0-11-amd64
CPU Architecture | x86_64
Timezone | Europe/Helsinki

Chrome Version 87.0.4280.88 (Official Build) (x86_64), Mac 10.11.6

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
- id: '1609159213005'
  alias: Fridge temp
  description: ''
  trigger:
  - type: temperature
    platform: device
    device_id: 6d2a2e260ac94c5b9c2125a4fa2cb9f6
    entity_id: sensor.ed53f2d2db81_temperature
    domain: sensor
    above: 12
    below: 2
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - device_id: b03b077af239129b77e8457f6308e478
    domain: mobile_app
    type: notify
    message: Jääkaappi
    title: Alarm
  mode: single

```

## Javascript errors shown in your browser console/inspector

```txt

```
