### ISSUE TITLE
Boolean Selector in Blueprint requires toggling on/off to allow saving as off

### ISSUE THREAD

**Issue by trankillity** [home-assistant/frontend#8053]
## The problem

When creating an automation from a blueprint which uses the `boolean:` selector, you cannot leave it in the default "off" position then save the automation. You must first toggle it on then off again in the UI for it to register as off/false.

## Environment

- Home Assistant Core release with the issue: 2020.12.2
- Last working Home Assistant Core release (if known): None
- Operating environment (OS/Container/Supervised/Core): Supervised (2020.12.7)
- Integration causing this issue: blueprint
- Link to integration documentation on our website: https://www.home-assistant.io/docs/blueprint/

## Problem-relevant `configuration.yaml`

```yaml
blueprint:
  name: Light Trigger
  description: Turns lights on/off 
  domain: automation
  input:
    trigger_entity:
      name: Trigger Sensor
      description: Sensor(s) that will trigger the light.
      selector:
        entity:
          domain: binary_sensor
    light_target:
      name: Target Light(s)
      description: Lights that should turn on.
      selector:
        target:
          entity:
            domain: light
    wait_delay:
      name: Wait time
      description: Time before the light should turn off.
      default: 10
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: minutes
    constrain_presence:
      name: Constrain presence
      description: Only trigger when someone is home
      selector:
        boolean:

mode: restart
max_exceeded: silent

variables:
  v_constrain_bool: !input constrain_presence

trigger:
  platform: state
  entity_id: !input trigger_entity
  from: "off"
  to: "on"
condition:
  - condition: template
    value_template: >-
      {% if v_constrain_bool -%}
        {{ states.person | selectattr('state', 'equalto', 'home') | list | count > 0 }}
      {%- else -%}
        True
      {%- endif %}
action:
  - service: light.turn_on
    target: !input light_target
  - wait_for_trigger:
      platform: state
      entity_id: !input trigger_entity
      from: "on"
      to: "off"
  - delay: !input wait_delay
  - service: light.turn_off
    target: !input light_target
```

## Traceback/Error logs

```txt
Message malformed: Missing input constrain_presence
```

**Comment by frenck** [comment]
You can provide a default for those:

```yaml
    constrain_presence:
      name: Constrain presence
      description: Only trigger when someone is home
      default: false
      selector:
        boolean:
```
