### ISSUE TITLE
Template sensor device_class timestamp - Invalid date on mobile browser

### ISSUE THREAD

**Issue by danbayliss** [home-assistant/frontend#8072]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have the following template sensor to store the last_updated timestamp of another sensor so I can show it in the UI
```
gas_electricity_30_days_combined_cost_timestamp:
  friendly_name: Combined Cost Last Updated
  icon_template: mdi:clock-outline
  value_template: '{{ states.sensor.gas_electricity_30_days_combined_cost.last_updated }}'
  device_class: timestamp
```

## Expected behavior

When i open the UI via my laptop browser I see the following
![Screenshot_1](https://user-images.githubusercontent.com/54558493/103470220-98797900-4d67-11eb-92b5-831e6094d4c6.jpg)

When i access via Safari on IOS or the Home Assistant app I see
![IMG_3496](https://user-images.githubusercontent.com/54558493/103470227-afb86680-4d67-11eb-9126-769a8fd973e7.jpg)

## Steps to reproduce

1. Add template sensor
2. Visit UI via desktop browser and compare with mobile browser/IOS app

## Environment

- Home Assistant release with the issue: 2020.12.2
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: IOS Safari browser / Firefox 84.0.1
- Operating system: iPhone IOS 14.3 / Windows 10

## State of relevant entities
![Screenshot_2](https://user-images.githubusercontent.com/54558493/103470253-1d649280-4d68-11eb-90e7-1686b02da4ed.jpg)

```yaml

```

## Problem-relevant configuration

```yaml
As above
```

## Javascript errors shown in your browser console/inspector

```txt
Unknown
```
