### ISSUE TITLE
Bad (NaN) Temp Sensor Value For Climate Integration Stops Lovelace UI From Loading

### ISSUE THREAD

**Issue by aaroncake** [home-assistant/frontend#8075]
## Checklist

- [N] I have updated to the latest available Home Assistant version.
- [Y] I have cleared the cache of my browser.
- [Y] I have tried a different browser to see if it is related to my browser.

## The problem

I bad sensor value for climate.attributes.current_temperature (for example, NaN) causes JSON serialization error  which prevents Lovelace from loading.

My interface yesterday would not load past the HA log and spinning indicator. Nothing about the installation had changed for days. Browser Dev tools reported a JSON serialization error (I'm sorry, at the time I did not take a screenshot as I was more interested in turning my heating back on). 

Discovered the log below via systemd service status that showed the problem was relating to parsing a NaN value from my temp sensor.

Logger: homeassistant.components.websocket_api.messages
Source: components/websocket_api/messages.py:82
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: January 2, 2021, 5:12:35 PM (10 occurrences)
Last logged: January 2, 2021, 5:21:47 PM

Unable to serialize to JSON. Bad data found at $.result[115](state: climate.shop_heating).attributes.current_temperature=nan(<class 'float'>

Confirmed via MQTT explorer checking the output of the sensor. 
Rebooting the sensor corrected the issue and Lovelace loaded.

## Expected behavior

Lovelace should not fail to load with a bad sensor value that cannot be parsed for climate.attributes.current_temprature

## Steps to reproduce

1. Add a generic thermostat
2. Provide it with an invalid temperature sensor data such as NaN
3. Wait for sensor to refresh
4. Attempt to load lovelace

## Environment

- Home Assistant release with the issue: 118.4
- Last working Home Assistant release (if known): unknown
- Browser and browser version: MS Edge Chromium 87.0.664.66
- Operating system: Windows 7 Pro x64

## State of relevant entities

Did not screenshot at time, sorry. sensor.shop_temperature = NaN

```yaml

```

## Problem-relevant configuration

```yaml

###########SHOP HEATING
  - platform: generic_thermostat
    name: Shop Heating
    heater: switch.shop_heater_switch
    target_sensor: sensor.shop_temperature
    min_temp: -10
    max_temp: 30
    ac_mode: False
    target_temp: 18.5
    cold_tolerance: 0.5
    hot_tolerance: 0.75
    min_cycle_duration:
      seconds: 240
    #keep_alive:
    #  minutes: 3
    initial_hvac_mode: 'off'
    away_temp: 4


#############Shop Climate Sensor
 - platform: mqtt
   name: "Shop Temperature"
   unit_of_measurement: 'Â°C'
   state_topic: "/shop/sensor/"
   value_template: "{{value_json.DHT22Temp | float }}"
 - platform: mqtt
   name: "Shop Humidity"
   unit_of_measurement: '%'
   state_topic: "/shop/sensor/"
   value_template: "{{value_json.DHT22Humidity | float }}"


```

## Javascript errors shown in your browser console/inspector

```txt
Sorry, did not screenshot at time.
```
