### ISSUE TITLE
automations.yaml should support !secret when edited via UI

### ISSUE THREAD

**Issue by sujal** [home-assistant/frontend#8083]
## The problem
I have a backup automation that uses a password to encrypt the backups. I'd like to leverage the `!secret` functionality to pull in the secret, but when I do that, I'm noticing inconsistent behavior, and definitely not the behavior I want.

If I add the automation via the `automations.yaml` file, then reload automations and try to edit via the UI, I will see the actual secret value (the actual password from `secrets.yaml`) rather than the secrets declaration.

If I edit the automation via the UI's yaml view for that action section, and use a `!secret` reference in the `data_template` section, the automation will save with a blank password value (literally, the file will say `password: ` in the data template).

I would prefer the UI to allow the use of secrets explicitly for that use case. Or, if there's a better way to do this, I'm open to that. The backup automation in it's entirety is below.

## Environment

- Home Assistant Core release with the issue: 2020.12.7
- Operating environment (OS/Container/Supervised/Core): Home Assistant OS 5.9

## Problem-relevant `configuration.yaml`

```yaml
- id: '1603043657737'            
  alias: Automatically Create Snapshot
  description: Backup automation
  trigger:           
  - platform: time_pattern                   
    hours: '3'   
    minutes: '0'
    seconds: '0'          
  condition: []    
  action:   
  - service: notify.mobile_app_iphone
    data:                                                                            
      message: Backup triggered for server
      title: Backup Started!                                                         
  - service: hassio.snapshot_full
    data_template:
      name: Backup_{{ now().strftime('%YT%m%dT%H%M%S') }}                         
      password: !secret snapshot_backup_pw                                        
  mode: single
```

## Traceback/Error logs

N/A - no errors returned to screen...

## Additional information

I did a quick search of the issues looking for similar reports, didn't see anything that looked relevant.
