### ISSUE TITLE
state_filter attribute == 0 does not work.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/frontend#8087]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

When using the following config on an integer attribute that is equal to 0, the state filter does not work.
```yaml
state_filter:
  - operator: ==
    value: 0
    attribute: current
```

The issue is most likely due to a check on the value itself.  Assuming this is like python an `if value` would return false because 0 is technically a boolean false.  We shouldn't be checking with a simple check like that, should be checking against null/None.

## Expected behavior

Filter attributes based on an integer value of 0.

## Steps to reproduce

make a sensor or device.  I used the air quality demo sensor.  It made the following entity:

air_quality.demo_air_quality_home | 14 | attribution: Powered by Home Assistant nitrogen_oxide: 100 particulate_matter_10: 23 particulate_matter_2_5: 14 unit_of_measurement: µg/m³ friendly_name: Demo Air Quality Home
-- | -- | --

Then I used the following config to verify that it doesn't work:

```yaml
type: entity-filter
entities:
  - automation.keyring_boolean_trigger
state_filter:
  - operator: ==
    value: 0
    attribute: current
```

Then i used the following config to verify that == does work with integers

```yaml
type: entity-filter
entities:
  - automation.keyring_boolean_trigger
state_filter:
  - operator: ==
    value: 10
    attribute: max
```

## Environment
Doesn't matter, its everywhere.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities
air_quality.demo_air_quality_home | 14 | attribution: Powered by Home Assistant nitrogen_oxide: 100 particulate_matter_10: 23 particulate_matter_2_5: 14 unit_of_measurement: µg/m³ friendly_name: Demo Air Quality Home
-- | -- | --

```yaml

```

## Problem-relevant frontend configuration

```yaml
type: entity-filter
entities:
  - automation.keyring_boolean_trigger
state_filter:
  - operator: ==
    value: 0
    attribute: current
```

## Javascript errors shown in your browser console/inspector

None

**Comment by Petro31** [comment]
I just realized that I used 2 different entities.  Either way, the bug still stands.  Just find a entity with an int attribute and the value of 0 and attempt to use the state_filter on it.

**Comment by Petro31** [comment]
If anyone stumbles on this, the current work around is:

```yaml
state_filter:
- operator: in
  value: [ 0 ]
  attribute: whatever_your_attribute_is
```
