### ISSUE TITLE
Scene Editor: Scene created with UI contains unnecessary YAML entries

### ISSUE THREAD

**Issue by pixeldoc2000** [home-assistant/frontend#8091]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When edit an existing Scene or create a new Scene in UI all kinds of unnecessary "garbage" (entitiy properties ?) are added to the scene in YAML (scene.yaml) like:
```
linkquality: 21
update_available: false
effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
...
```

Maybe it does only happen when using **zigbee2mqtt** with lights?

## Expected behavior

Save only Scene relevant Settings (in YAML) like brightness, rgb_color etc.
Filter unrelated stuff like linkquality, update_available, supported_features.

## Steps to reproduce

Edit an existing Scene or create a new Scene in UI.

## Environment

- Home Assistant release with the issue: 2020.12.2
- Last working Home Assistant release (if known): ?
- Browser and browser version: Firefox 84.0.1
- Operating system: Windows
- zigbee2mqtt with zigbee Lights
- Home Assistant Core in Docker on UNRAID

## State of relevant entities

```yaml
-
```

## Problem-relevant frontend configuration

Example (scene.yaml) :

```yaml
- id: '1609853226890'
  name: TEST 1
  entities:
    light.gledopto_rgbw_01_light:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      brightness: 253
      color_temp: 164
      hs_color:
      - 0
      - 0.784
      rgb_color:
      - 255
      - 253
      - 253
      xy_color:
      - 0.325
      - 0.329
      color:
        x: 0.324
        y: 0.329
      linkquality: 18
      state: 'on'
      white_value: 250
      friendly_name: Fensterbank
      supported_features: 63
    light.osram_e27_rgbw_01_light:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      brightness: 253
      color_temp: 320
      hs_color:
      - 45
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      color:
        h: 45
        s: 0
        x: 0.428631269134558
        y: 0.401051093716253
      linkquality: 21
      state: 'on'
      update:
        state: idle
      update_available: false
      friendly_name: Stehlampe
      supported_features: 63
    light.osram_e27_rgbw_04_light:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      brightness: 253
      color_temp: 321
      hs_color:
      - 75
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      color:
        h: 75
        hue: 0
        s: 0
        saturation: 0
        x: 0.3805
        y: 0.3769
      linkquality: 45
      state: 'on'
      update:
        state: idle
      update_available: false
      friendly_name: Decke
      supported_features: 63
```
