### ISSUE TITLE
Climate Card missing colors

### ISSUE THREAD

**Issue by samuelecarpene** [home-assistant/frontend#8159]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I noticed that in a climate card of Lovelace there is this css
```css
ha-card {
    height: 100%;
    position: relative;
    overflow: hidden;
    --name-font-size: 1.2rem;
    --brightness-font-size: 1.2rem;
    --rail-border-color: transparent;
    --auto-color: green;
    --eco-color: springgreen;
    --cool-color: #2b9af9;
    --heat-color: #ff8100;
    --manual-color: #44739e;
    --off-color: #8a8a8a;
    --fan_only-color: #8a8a8a;
    --dry-color: #efbd07;
    --idle-color: #8a8a8a;
    --unknown-color: #bac;
}
```

As you can see the `--off-color`, `--fan_only-color` and `--idle-color` are the same.

## Expected behavior

Differente colors for each mode

## Steps to reproduce

Try to use a climate card (personally i'm using with dark mode)

## Environment

- Home Assistant release with the issue: latest
- Last working Home Assistant release (if known): i think none
- Browser and browser version: Chrome 87.0.4280.141
- Operating system: Windows 10

## State of relevant entities

Nothing relevant

```yaml

```

## Problem-relevant frontend configuration

Nothing relevant

```yaml

```

## Javascript errors shown in your browser console/inspector

No errors

```txt

```
