### ISSUE TITLE
Wrong day names in weather card forecast

### ISSUE THREAD

**Issue by bkupidura** [home-assistant/frontend#8169]
## The problem

`weather-forecast` shows wrong forecast day names. Instead of different week days in forecast i can see just `Monday` with different weather conditions. I believe it can be connected to https://github.com/home-assistant/core/pull/45124

## Expected behavior

Properly rendered forecast.

## Steps to reproduce

Add `weather-forecast` card with entity created by `openweathermap`.

## Environment

- Home Assistant release with the issue: 2021.1.3
- Last working Home Assistant release (if known): 2021.1.1 (afaik)
- Browser and browser version: firefox 84.0.2 (64-bit), safari 14.0.2 (15610.3.7.1.10, 15610)
- Operating system: MacOS Catalina

## State of relevant entities

```yaml
temperature: -2.1
humidity: 86
pressure: 1021
wind_bearing: 300
wind_speed: 14.83
attribution: Data provided by OpenWeatherMap
forecast:
  - datetime: 1610744400
    precipitation: null
    wind_speed: 3.89
    wind_bearing: 317
    condition: cloudy
    temperature: -3.3
  - datetime: 1610755200
    precipitation: null
    wind_speed: 4.47
    wind_bearing: 313
    condition: cloudy
    temperature: -3.6
  - datetime: 1610766000
    precipitation: null
    wind_speed: 4.62
    wind_bearing: 313
    condition: cloudy
    temperature: -4
  - datetime: 1610776800
    precipitation: null
    wind_speed: 4.17
    wind_bearing: 300
    condition: snowy
    temperature: -5.5
  - datetime: 1610787600
    precipitation: null
    wind_speed: 5.19
    wind_bearing: 292
    condition: cloudy
    temperature: -4.7
  - datetime: 1610798400
    precipitation: null
    wind_speed: 6.46
    wind_bearing: 287
    condition: cloudy
    temperature: -3.2
  - datetime: 1610809200
    precipitation: null
    wind_speed: 7.32
    wind_bearing: 295
    condition: snowy
    temperature: -3.3
  - datetime: 1610820000
    precipitation: null
    wind_speed: 6.6
    wind_bearing: 307
    condition: snowy
    temperature: -3.1
  - datetime: 1610830800
    precipitation: null
    wind_speed: 3.18
    wind_bearing: 38
    condition: snowy
    temperature: -4.7
  - datetime: 1610841600
    precipitation: null
    wind_speed: 2.89
    wind_bearing: 83
    condition: cloudy
    temperature: -9.8
  - datetime: 1610852400
    precipitation: null
    wind_speed: 2.35
    wind_bearing: 64
    condition: cloudy
    temperature: -11.6
  - datetime: 1610863200
    precipitation: null
    wind_speed: 2.48
    wind_bearing: 73
    condition: cloudy
    temperature: -13.2
  - datetime: 1610874000
    precipitation: null
    wind_speed: 2.58
    wind_bearing: 91
    condition: sunny
    temperature: -13.1
  - datetime: 1610884800
    precipitation: null
    wind_speed: 2.16
    wind_bearing: 120
    condition: sunny
    temperature: -11.4
  - datetime: 1610895600
    precipitation: null
    wind_speed: 1.94
    wind_bearing: 127
    condition: partlycloudy
    temperature: -13.1
  - datetime: 1610906400
    precipitation: null
    wind_speed: 2.04
    wind_bearing: 129
    condition: partlycloudy
    temperature: -14.2
  - datetime: 1610917200
    precipitation: null
    wind_speed: 1.9
    wind_bearing: 154
    condition: clear-night
    temperature: -14.6
  - datetime: 1610928000
    precipitation: null
    wind_speed: 2.14
    wind_bearing: 155
    condition: clear-night
    temperature: -14.7
  - datetime: 1610938800
    precipitation: null
    wind_speed: 2.31
    wind_bearing: 166
    condition: cloudy
    temperature: -14.4
  - datetime: 1610949600
    precipitation: null
    wind_speed: 2.78
    wind_bearing: 149
    condition: cloudy
    temperature: -14.2
  - datetime: 1610960400
    precipitation: null
    wind_speed: 3.07
    wind_bearing: 161
    condition: sunny
    temperature: -12.2
  - datetime: 1610971200
    precipitation: null
    wind_speed: 3.04
    wind_bearing: 173
    condition: partlycloudy
    temperature: -9.4
  - datetime: 1610982000
    precipitation: null
    wind_speed: 2.69
    wind_bearing: 175
    condition: cloudy
    temperature: -8.6
  - datetime: 1610992800
    precipitation: null
    wind_speed: 2.41
    wind_bearing: 186
    condition: snowy
    temperature: -6.6
  - datetime: 1611003600
    precipitation: null
    wind_speed: 1.86
    wind_bearing: 195
    condition: snowy
    temperature: -3.4
  - datetime: 1611014400
    precipitation: null
    wind_speed: 3.46
    wind_bearing: 261
    condition: snowy
    temperature: 0.6
  - datetime: 1611025200
    precipitation: null
    wind_speed: 4.75
    wind_bearing: 256
    condition: snowy
    temperature: 0.5
  - datetime: 1611036000
    precipitation: null
    wind_speed: 3.96
    wind_bearing: 224
    condition: cloudy
    temperature: -1.9
  - datetime: 1611046800
    precipitation: null
    wind_speed: 3.92
    wind_bearing: 201
    condition: cloudy
    temperature: -1.5
  - datetime: 1611057600
    precipitation: null
    wind_speed: 5.19
    wind_bearing: 176
    condition: cloudy
    temperature: -0.5
  - datetime: 1611068400
    precipitation: null
    wind_speed: 5.11
    wind_bearing: 179
    condition: cloudy
    temperature: -0.5
  - datetime: 1611079200
    precipitation: null
    wind_speed: 6.52
    wind_bearing: 193
    condition: snowy
    temperature: 0.2
  - datetime: 1611090000
    precipitation: null
    wind_speed: 5.55
    wind_bearing: 203
    condition: rainy
    temperature: 1
  - datetime: 1611100800
    precipitation: null
    wind_speed: 5.31
    wind_bearing: 212
    condition: rainy
    temperature: 1.7
  - datetime: 1611111600
    precipitation: null
    wind_speed: 4.99
    wind_bearing: 213
    condition: cloudy
    temperature: 1.8
  - datetime: 1611122400
    precipitation: null
    wind_speed: 4.58
    wind_bearing: 196
    condition: cloudy
    temperature: 1.7
  - datetime: 1611133200
    precipitation: null
    wind_speed: 5.23
    wind_bearing: 200
    condition: cloudy
    temperature: 2.2
  - datetime: 1611144000
    precipitation: null
    wind_speed: 5.78
    wind_bearing: 207
    condition: cloudy
    temperature: 2.9
  - datetime: 1611154800
    precipitation: null
    wind_speed: 4.56
    wind_bearing: 202
    condition: cloudy
    temperature: 2.6
  - datetime: 1611165600
    precipitation: null
    wind_speed: 4.6
    wind_bearing: 194
    condition: cloudy
    temperature: 2.4
friendly_name: OpenWeatherMap
```

## Problem-relevant frontend configuration

```yaml
          - type: weather-forecast
            entity: weather.openweathermap
```

## Javascript errors shown in your browser console/inspector

No errors.
<img width="404" alt="Screenshot 2021-01-15 at 20 18 53" src="https://user-images.githubusercontent.com/4814684/104769149-247b9f80-576f-11eb-8858-b111ef9cda8c.png">
