### ISSUE TITLE
buttons in entities card doesn't support same functions as button card

### ISSUE THREAD

**Issue by scyto** [home-assistant/frontend#8188]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## Steps to reproduce

1. prove out basic functionality via the button card.  Here is example 
```
  - type: horizontal-stack
    cards:
      - type: button
        icon: 'mdi:volume-plus'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            entity_id: remote.basement_harmony
            command: VolumeUp
            device: 49625216
        icon_height: 45px
      - type: button
        icon: 'mdi:volume-off'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            entity_id: remote.basement_harmony
            command: Mute
            device: 49625216
        icon_height: 45px
      - type: button
        icon: 'mdi:volume-minus'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            entity_id: remote.basement_harmony
            command: VolumeDown
            device: 49625216
        icon_height: 45px
```
2 try and reproduce these buttons in the entities card.  I tried two variants:
```
type: entities
entities:
  type: entities
entities:
  - type: divider
  - type: buttons
    entities:
      - type: button
        icon: 'mdi:volume-plus'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            entity_id: remote.basement_harmony
            command: VolumeUp
            device: 9625216
      - type: button
        icon: 'mdi:volume-minus'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            entity_id: remote.basement_harmony
            command: VolumeDown
            device: 9625216
  - type: divider
```
and
```
type: entities
entities:
  - type: divider
  - type: buttons
    entities:
      - type: button
        icon: 'mdi:volume-plus'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: VolumeUp
            entity_id: 9625216
      - type: button
        icon: 'mdi:volume-minus'
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: VolumeDown
            entity_id: 9625216
  - type: divider
```
I am not assuming that these should be supported not am I assuming that my yaml is right.  If there are edits to my code that would make this work that is awesome.  I couldn't figure it out from the docs (i am new).

## Environment

- Home Assistant release with the issue: 2021.1.4
- Last working Home Assistant release (if known): never worked AFAIK
- Browser and browser version: Latest new windows Edge browser.
- Operating system: Windows 10

## State of relevant entities

saved cards look like this
![image](https://user-images.githubusercontent.com/11369180/104856128-a41b8280-58c5-11eb-95be-97456b0f2b4a.png)
and 
![image](https://user-images.githubusercontent.com/11369180/104856138-b09fdb00-58c5-11eb-9ea1-966ccabac005.png)

```
none

```

## Problem-relevant frontend configuration

```
provided in repro above

```

## Javascript errors shown in your browser console/inspector

```
none

```

## System Health

version | 2021.1.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.86
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4994
Installed Version | 1.10.0
Stage | running
Available Repositories | 709
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | stable
supervisor_version | 2021.01.4
docker_version | 19.03.13
disk_total | 30.8 GB
disk_used | 6.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (5.1), Samba share (9.3.0), Visual Studio Code (2.9.1), Log Viewer (0.9.1), SSH & Web Terminal (7.8.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 6
resources | 1

</details>
