### ISSUE TITLE
cover not showing position as secondary info in entities card

### ISSUE THREAD

**Issue by wivaku** [home-assistant/frontend#8199]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

See https://community.home-assistant.io/t/hunter-douglas-cover-position-available-but-not-in-lovelace-entities-card/270333

Related to the functionality added in pull request https://github.com/home-assistant/frontend/pull/5556

I am using an entities card in Lovelace, where I can select “position” as secondary info.
But it literally shows the word **position** instead of e.g. **100%** (just in case, also tried with `current_position`). When using `last-changed` it works as expected. When using (single) entity card it works as expected.

It seems tilt-position also literally shows the text (but my cover does not support tilt, so not sure).

Screenshot:
![image](https://user-images.githubusercontent.com/2084872/105180180-83079b80-5b2a-11eb-8ef0-2ef2a518cf19.png)

## Expected behavior

See above.

## Steps to reproduce

In my case I used Lovelace visual editor, same result when using manual editing.

## Environment

- Home Assistant release with the issue: 2021.1.4
- Last working Home Assistant release (if known): n/a
- Browser and browser version: e.g. Chrome 87-88 and HA app iOS
- Operating system: e.g. macOS

## State of relevant entities

Properties of my cover:
```
current_position: 80
roomName: myroom
friendly_name: blinds 1
supported_features: 15
device_class: shade
```

## Problem-relevant frontend configuration

Yaml of Lovelace **entities** card:
```yaml
type: entities
entities:
  - entity: cover.blinds_1
    secondary_info: position
state_color: true
show_header_toggle: false
```

Yaml of Lovelace (working) **single entity** card:
```yaml
type: entity
entity: cover.blinds_1
attribute: current_position
unit: '%'
```

## Javascript errors shown in your browser console/inspector

Not applicable.
