### ISSUE TITLE
Script editor UI destroys YAML script

### ISSUE THREAD

**Issue by emufan** [home-assistant/frontend#8200]
## The problem

Are there known limitiations with the script editor? I’m used to edit the YAML from automations, ets. and everyting the UI editor is not able to show, it is shown as code sniblets and I have to proceed in YAML. So good so far.

But If I e.g. paste the YAML view of UI editor

```
alias: Neues Skript
sequence:
  - service: light.turn_on
    data:
      entity_id: light.hue_color_lamp_1
      xy_color: [0.67,0.39]
      brightness: 1
  - delay:
      seconds: 1
  - service: light.turn_on
    data:
      entity_id: light.hue_color_lamp_1
      xy_color: [0.65,0.41]
      brightness: 85
      transition: 600
  - delay:
      seconds: 600
  - service: light.turn_on
    data:
      entity_id: light.hue_color_lamp_1
      xy_color: [0.60,0.40]
      brightness: 170
      transition: 600
  - delay:
      seconds: 600
  - service: light.turn_on
    data:
      entity_id: light.hue_color_lamp_1
      xy_color: [0.48,0.40]
      brightness: 255
      transition: 600
mode: single
```

to a new script, save, close and reopen, the third and sometimes second delay is “transformed” to:

```
      brightness: 170
      transition: 600
  - delay: '[object Object]'
  - service: light.turn_on
```

And yes, this is the YAML view and not the UI one. And it is damaged again after save, If I try to correct it. As long this is such style and not a ‘00:10:00’ style the third delay is always destroid.

Update: Perhaps not the third, but always the last existing one (in second/minutes-stylye) is destroyed.

Is this a known limitation or bug? If I paste and save I’m used to have a valid and not damaged code afterwards.

## Environment

Core 2021.1.3 on Docker in QNAP

## Additional information

I asked for this already [here](https://community.home-assistant.io/t/script-editor-ui-vs-yaml-problems-bugs/270257), but not a single answer/idea.
