### ISSUE TITLE
conditional cards causes left and right margin in horizontal stacks

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8204]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Using a horizontal stack of conditional cards reveals a small margin left (see below) and right side of the stack (if the stack is filled with 4 cards)

<img width="162" alt="Schermafbeelding 2021-01-22 om 10 19 53" src="https://user-images.githubusercontent.com/33354141/105471788-69399600-5c9b-11eb-98e3-bf234aa17137.png">

4 'on' cards:

<img width="511" alt="Schermafbeelding 2021-01-22 om 10 44 17" src="https://user-images.githubusercontent.com/33354141/105474742-e1ee2180-5c9e-11eb-9eb3-c058f2360360.png">

## Expected behavior

 no margins (screenshot of horizontal stack with unconditional cards)

<img width="225" alt="Schermafbeelding 2021-01-22 om 10 20 48" src="https://user-images.githubusercontent.com/33354141/105471878-853d3780-5c9b-11eb-9b68-da1fdc955e3e.png">

no margin with 4 unconditional cards:

<img width="516" alt="Schermafbeelding 2021-01-22 om 11 04 31" src="https://user-images.githubusercontent.com/33354141/105477099-b7519800-5ca1-11eb-9c20-2cba8b6266a8.png">

custom card stack-in-card doesnt create the margin either

<img width="204" alt="Schermafbeelding 2021-01-22 om 10 22 21" src="https://user-images.githubusercontent.com/33354141/105472107-d0efe100-5c9b-11eb-8502-81be9f7c35c2.png">

of course this custom card has another issue, but used here only to demonstrate the left margin is caused by the core conditional card
## Environment

- Home Assistant release with the issue: has been there since a very long time
- Last working Home Assistant release (if known): never?
- Browser and browser version: Safari, Chrome, Firefox
- Operating system: Home Assistant OS, device Mac/iPhone

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml
type: horizontal-stack
cards:

  - type: conditional
    conditions:
      - entity: input_boolean.github_repo_update
        state: 'on'
    card: !include /config/lovelace/includes/include_button_github_repo_alert.yaml

  - type: conditional
    conditions:
      - entity: binary_sensor.earthquakes_near_active
        state: 'on'
    card: !include /config/lovelace/includes/include_button_quake_alert.yaml

  - type: conditional
    conditions:
      - entity: binary_sensor.trash_notification
        state: 'on'
    card: !include /config/lovelace/includes/include_button_trash_alert.yaml

  - type: conditional   ##<---- this is the card in the screenshots
    conditions:
      - entity: binary_sensor.schimmel_alert
        state: 'on'
    card: !include /config/lovelace/includes/include_button_ventilate.yaml
```

## Javascript errors shown in your browser console/inspector

no errors
```txt

```

## Additional information

Posted on this before https://github.com/home-assistant/frontend/issues/6051#issuecomment-638920204 but was then told that not to be the correct issue, hence this dedicated issue.

As far as I can analyze this issue, it could have to do with the position of the 'on' card in the order of list of the conditional cards.
If I position an 'on' card to the top of the list, it shows correctly:

<img width="159" alt="Schermafbeelding 2021-01-22 om 10 35 03" src="https://user-images.githubusercontent.com/33354141/105473544-853e3700-5c9d-11eb-9aca-e5b1575128fd.png">

btw, it has nothing to do with the individual cards, it's happening to all of them, and as displayed above, using any of these cards in a non-conditional Lovelace config works perfectly.
