### ISSUE TITLE
[Request] Cover Group - add unique_id or device_class or icon

### ISSUE THREAD

**Issue by TonyBrobston** [home-assistant/frontend#8247]
I have grouped a few covers together:
```
cover:
  - platform: group
    name: 'Basement Curtains'
    entities:
      - cover.basement_west_curtains
      - cover.basement_northeast_curtains
      - cover.basement_southeast_curtains
```
In lovelace I'd like to customize the icon:
![image](https://user-images.githubusercontent.com/4724577/105912963-ce6dee00-5ff1-11eb-83ec-719bf6383173.png)
Lovelace says it requires a `unique_id` in order to do that:
![image](https://user-images.githubusercontent.com/4724577/105913025-e5144500-5ff1-11eb-8381-cddab217c1d5.png)
Cover Group does not support `unique_id`.
https://www.home-assistant.io/integrations/cover.group/
I thought maybe `device_class` or `icon` may be supported, but those are not either.

I would like to propose a feature request to add `unique_id` and/or `device_class` and/or `icon`.
