### ISSUE TITLE
Automation Editor Breaks YAML for Event Type Trigger

### ISSUE THREAD

**Issue by regoras** [home-assistant/frontend#8301]
**The problem**

When creating an automation that triggers on multiple events, it must be edited manually via YAML and saved from in Edit with YAML, otherwise the list of events is compressed into a comma-delimited string, which the event listener does not seem to recognize or listen to. 

Opening the automation to edit it defaults into the UI editor which again requires going into Edit with YAML to correct this so that the event listener can correctly see what events to listen to. 

**What is version of Home Assistant Core has the issue?**

core-2021.1.5

**What was the last working version of Home Assistant Core?**

_No response_

**What type of installation are you running?**

Home Assistant Supervised

**Integration causing the issue**

Automation

**Link to integration documentation on our website**

https://www.home-assistant.io/docs/automation/trigger/

**Example YAML snippet**

```
### working manual YAML for listening to multiple events
trigger:
  - platform: event
    event_type: 
      - esphome.kitchen_cabinet1
      - esphome.kitchen_cabinet2
    event_data: {}


### broken YAML that UI editor converts to
trigger:
  - platform: event
    event_type: 'esphome.kitchen_cabinet1,esphome.kitchen_cabinet2'
    event_data: {}

```

**Anything in the logs that might be useful for us?**

```
# Put your logs below this line

```

The broken YAML results in Event Listener trying to listen to `esphome.kitchen_cabinet1,esphome.kitchen_cabinet2` rather than listening to the events individually and so no events are captured from the devices.
