### ISSUE TITLE
Numbers Showing Too Large in Frontend

### ISSUE THREAD

**Issue by JeffResc** [home-assistant/frontend#8304]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When enlarging an entity (either though an entity card, in the entity list or any other means), the number label on the color temperature slider is not rounded and shows a huge decimal number.
![Image](https://i.imgur.com/dn4ia3G.png)

## Expected behavior

Proabbly a rounded integer to display.

## Steps to reproduce

Open an entity with a color temperature slider using any means and slide the slider, you will notice a huge number will display.

## Environment

- Home Assistant release with the issue: 2021.1.5
- Last working Home Assistant release (if known): Not known
- Browser and browser version: Firefox 85.0 and Edge 88.0.705.56
- Operating system: Windows for the browser, running Ubuntu 20.04.1 LTS (Raspberry Pi 4, arm64) on the server, but it is running in Docker using the official Docker image (homeassistant:2021.1.5).

## State of relevant entities

```yaml
min_mireds: 152.998779296875
max_mireds: 500
brightness: 255
color_temp: 300
hs_color:
  - 0
  - 0
rgb_color:
  - 255
  - 255
  - 255
xy_color:
  - 0.323
  - 0.329
white_value: 255
friendly_name: [redacted]
supported_features: 187
```

## Problem-relevant frontend configuration

```yaml
N/A
```

## Javascript errors shown in your browser console/inspector

```txt
N/A
```

## Additional information
None at this time, if you need any more information or screenshots, feel free to let me know.
