### ISSUE TITLE
Media Control Card: handle missing media image

### ISSUE THREAD

**Issue by patagonaa** [home-assistant/frontend#8317]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Every time you play media that does not have a media image, two errors are thrown in the browser console (see below).
The first one is from directly trying to load the image as a background-image, the second one is from trying to get the image colors for this (non-existing) image.

## Expected behavior

No Javascript errors during normal operation.

## Steps to reproduce

1. Add a Media Control card for an MPD media player entity
2. Play some media that doesn't have an album cover
3. Look at the browser's Javascript console

## Environment

- Home Assistant release with the issue: 2021.1.5
- Last working Home Assistant release (if known): -
- Browser and browser version: Chrome 88.0.4324.104 / Firefox 84.0.2
- Operating system: Windows 10

## State of relevant entities

```yaml
source_list:
  - ABC
volume_level: 1
is_volume_muted: false
media_content_id: >-
  Musik/Albums/ABC/DEF.flac
media_content_type: music
media_duration: '138'
media_position: 35
media_position_updated_at: '2021-02-03T18:02:16.231706+00:00'
media_title: Example Title
media_artist: Example Artist
media_album_name: Example Album
shuffle: true
repeat: 'off'
friendly_name: MPD
entity_picture: >-
  /api/media_player_proxy/media_player.mpd?token=4bb5d...a8582e&cache=db34e8adce03a954
supported_features: 327615
```

## Problem-relevant frontend configuration

```yaml
type: media-control
entity: media_player.mpd
```

## Javascript errors shown in your browser console/inspector

```txt
media_player.mpd:1 GET https://homeassistant.example.org/api/media_player_proxy/media_player.mpd?token=b27cab8c[...]3cab34d&cache=702922c838afb4d7 500
Image (async)
e.load @ chunk.dcb57b9bb2daf791877d.js:1
t.getPalette @ chunk.dcb57b9bb2daf791877d.js:1
(anonymous) @ chunk.9a230f4e1ba6d82a8c78.js:745
value @ chunk.9a230f4e1ba6d82a8c78.js:745
value @ chunk.9a230f4e1ba6d82a8c78.js:745
performUpdate @ app.924deda6.js:10297
[...]
chunk.9a230f4e1ba6d82a8c78.js:745 Error getting Image Colors Error: Fail to load image: /api/media_player_proxy/media_player.mpd?token=b27cab8cdfe[...]8903c163cab34d&cache=702922c838afb4d7
    at HTMLImageElement.e.complete.e.onerror (chunk.dcb57b9bb2daf791877d.js:1)
```

## Additional information

This was revealed while using the MPD integration (https://github.com/home-assistant/core/issues/45235), because the server returns a 500 Error if there is missing album art:
https://github.com/home-assistant/core/blob/467d79c7fdfa44337e9a64776e999fe590ace4b4/homeassistant/components/media_player/__init__.py#L973-L974

This might also be an issue in the backend, the API should probably return something else when there's no image available (maybe throwing a 404 or returning an empty/transparent image would be a better way)
