### ISSUE TITLE
Scenes do not reflect exact state of light bulbs

### ISSUE THREAD

**Issue by DannyGJdeJong** [home-assistant/frontend#8399]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

When creating a new scene for the current states of my lights and then applying it, the lights change color and brightness even though I didn't change any of the parameters in the scene. 

**Describe the behavior you expected**

I expect the color of my light bulbs to stay the same before and after creating a new scene without editing any of the parameters.

**Steps to reproduce the issue**

1. Set light bulb (Yeelight color2) to a color and brightness of choice through your method of choice (e.g. Yeelight app)
2. Create a new scene
3. Add the light bulb to the scene
4. Save the scene without changing anything
5. Watch as the light bulbs change color and brightness from the state they were in before
6. Apply the newly set scene and watch as the bulbs don't change to the desired color/brightness

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Google Chrome 88.0.4324.150

**Which operating system are you using to run this browser?**

Arch Linux

**State of relevant entities**

```yaml
- id: '1613384006191'
  name: test
  entities:
    light.yee_living_room:
      min_mireds: 153
      max_mireds: 588
      effect_list:
      - Strobe color
      - Police
      - Christmas
      - RGB
      - Random Loop
      - Fast Random Loop
      - LSD
      - Slowdown
      - Night Mode
      - Date Night
      - Movie
      - Sunrise
      - Sunset
      - Romance
      - Happy Birthday
      - Disco
      - Strobe epilepsy!
      - Alarm
      - Police2
      - WhatsApp
      - Facebook
      - Twitter
      - Home
      - Candle Flicker
      - Slow Temp
      - Stop
      brightness: 255
      color_temp: 285
      hs_color:
      - 27.165
      - 44.6
      rgb_color:
      - 255
      - 192
      - 141
      xy_color:
      - 0.454
      - 0.373
      flowing: false
      music_mode: false
      friendly_name: yee_living_room
      supported_features: 63
      state: 'on'
```

**Problem-relevant frontend configuration**

_No response_

**Javascript errors shown in your browser console/inspector**

_No response_

It seems that the scene editor takes the entire state of the light bulb and tries to apply it all at once, resulting into many color modes being set at the same time even though they are mutually exclusive. I'm experiencing these issues with my Yeelight color2 bulbs, so I'm not sure whether this is an issue with other bulbs as well. I have been able to make it work by removing a lot of this unnecessary information from the scenes.yaml and creating the scenes through there instead.
