### ISSUE TITLE
Cover group does not allow to use the up button

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#8436]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

I have to single cover entities, which work great on the frontend (see sceenshots in additional information).
Now I created a group containing those two covers. When I use the group within the frontend, the "up" button is disabled (see screenshot)

**Describe the behavior you expected**

Since the position of both covers within this group is set to always 50, I expect the group to also allow the up action.

**Steps to reproduce the issue**

1. Have two cover entities
2. Set both of them to `position_template: "50"`
3. Create a group containing both entities
...

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Microsoft Edge 89.0.774.27

**Which operating system are you using to run this browser?**

Windows 10 20H2

**State of relevant entities**

```yaml
cover.eg_links	
     state: open
     attributes:
          current_position: 50
          friendly_name: EG Jalousie Links
          supported_features: 11
          device_class: shutter
cover.eg_rechts
     state: open
     attributes:
          current_position: 50
          friendly_name: EG Jalousie Rechts
          supported_features: 11
          device_class: shutter
cover.jalousie_erdgeschoss
     state: open
     entity_id: cover.eg_links, cover.eg_rechts
     attributes:
          friendly_name: Jalousie Erdgeschoss
          supported_features: 11
          device_class: shutter
```

**Problem-relevant frontend configuration**

```yaml
type: button
show_name: true
tap_action:
  action: more-info
entity: cover.jalousie_erdgeschoss
name: EG
```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

### Configuration:
```yaml
cover:
  - platform: template
    covers:
      eg_links:
        device_class: shutter
        position_template: "50"
        friendly_name: "EG Jalousie Links"
        open_cover:
          service: switch.turn_off
          data:
            entity_id: switch.jalousie_links
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.jalousie_links
        stop_cover:
          service: switch.turn_on
          data:
            entity_id: switch.jalousie_links
  - platform: template
    covers:
      eg_rechts:
        device_class: shutter
        position_template: "50"
        friendly_name: "EG Jalousie Rechts"
        open_cover:
          service: switch.turn_off
          data:
            entity_id: switch.jalousie_rechts
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.jalousie_rechts
        stop_cover:
          service: switch.turn_on
          data:
            entity_id: switch.jalousie_rechts
  - platform: group
    name: Jalousie Erdgeschoss
    entities:
      - cover.eg_links
      - cover.eg_rechts
```

### Screenshots:
![Screenshot_2021 02 22_23h27m05s_009_](https://user-images.githubusercontent.com/1368405/108838487-fc842500-75d3-11eb-9bfc-0ea7e18855fa.png)
![Screenshot_2021 02 22_23h27m13s_010_](https://user-images.githubusercontent.com/1368405/108838490-fdb55200-75d3-11eb-9823-e6f179a1a725.png)
![Screenshot_2021 02 22_23h27m26s_011_](https://user-images.githubusercontent.com/1368405/108838491-fdb55200-75d3-11eb-9526-2314bf92f5cc.png)

**Comment by spacegaier** [comment]
A cover group works fine for me when using regular covers (not templated ones).  Can you config Lovelace to render the position as the secondary info for your group to see what it has in there at runtime.

**Comment by TheZoker** [comment]
I created a test card with this config:
```yaml
type: entities
entities:
  - entity: cover.eg_rechts
    secondary_info: position
  - entity: cover.jalousie_erdgeschoss
    secondary_info: position
```

And this is the result:
![Screenshot_2021 02 25_12h56m06s_004_](https://user-images.githubusercontent.com/1368405/109150199-d5ab2780-7768-11eb-88bc-8d826ac49ca4.png)

So as seen in the attribute list, it seems that the group does not have a position at all. I think the best way to handle this issue would be, that if there is no position available, both controls are enabled
