### ISSUE TITLE
Request to add a space between the data entry field and the units

### ISSUE THREAD

**Issue by vtb77** [home-assistant/frontend#8449]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

When I use an "input number" on a card, the representation of the field to modify and the units of the "inputnumber" are not separated by a space as if I use a "sensor". I have tested it in Chrome and Firefox and the same thing happens.

**Describe the behavior you expected**

I expected a similar graphical representation with the "input number" and the "sensor" being the same, that is, the data and the units are separated by at least one space to make it visually more pleasant and readable. Thanks.

**Steps to reproduce the issue**

1. Create an "entity" with an "inputnumber".

**What version of Home Assistant Core has the issue?**

all versions

**What was the last working version of Home Assistant Core?**

none

**In which browser are you experiencing the issue with?**

Chrome, Firefox and Edge

**Which operating system are you using to run this browser?**

Windows 10

**State of relevant entities**

```yaml
  - entity: input_number.trafico_datos_acumulados
    name: Acumulados mes anterior
  - entity: sensor.huawei_b535_235_current_month_download_gb
    name: Consumidos mes actual


**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```
