### ISSUE TITLE
Automation editor corrupts template in delay action

### ISSUE THREAD

**Issue by balk77** [home-assistant/frontend#8475]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

I want to implement a random delay in the action of an automation. The docs suggest it is possible like this (https://www.home-assistant.io/docs/scripts/ , search for "random"). When I add this manually to `automations.yaml` it works. When I open the same automation in the UI the template is removed. When I save without touching that segment of the automation the template is also removed.

**Describe the behavior you expected**

To be able to edit the template AND that the template is correctly saved to `automations.yaml`.

**Steps to reproduce the issue**

1. Add this to `automations.yaml` and reload automations:
```yaml
- delay:
      seconds: '{{ range(1, 30)|random }}'
```
2. Open the automation in the editor and make a minor change (description or so). Save. It does not matter if I use `Edit with UI` or `Edit as YAML`. 
3. The following code is written to `automations.yaml`:
```yaml
- delay:
      hours: 0
      minutes: 0
      seconds:
      milliseconds: 0
```
2A. Edit with UI results in:
<img width="629" alt="Screenshot 2021-02-27 at 09 36 32" src="https://user-images.githubusercontent.com/10166350/109382217-6b68c300-78df-11eb-8d37-454e6af819df.png">

2B. Edit as YAML results in:
<img width="607" alt="Screenshot 2021-02-27 at 09 38 32" src="https://user-images.githubusercontent.com/10166350/109382242-9c48f800-78df-11eb-9f9e-5dcb703559f7.png">

...

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Firefox 86.0

**Which operating system are you using to run this browser?**

MacOS 11.2.1 on M1 Macbook air

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
- id: '1614349029131'
  alias: 'Occusim: random off (test)'
  description: x
  trigger:
  - at: '22:20:00'
    platform: time
  condition: []
  action:
  - delay:
      seconds: '{{ range(10, 20)|random }}'
  - service: light.turn_off
    data: {}
    entity_id: all
  - data:
      message: 'Occusim: lichten gaan uit'
    service: notify.telegram
  - data: {}
    entity_id: input_boolean.occupancy_simulation
    service: input_boolean.turn_off
  - delay: 00:00:10
  - service: light.turn_on
    data: {}
    entity_id: light.mbr_plafond_level
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_off
    data: {}
    entity_id: light.mbr_plafond_level
  mode: single
```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```
