### ISSUE TITLE
button confirmation question asking about the service, not the name

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8492]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

when the confirmation pops up, it displays some technical, not very clear question, 'are you sure you want to execute action  call-service?

**Describe the behavior you expected**

It would be a much better experience if the popup state: Do you want to activate the Alarm system, (given the fact the action name and name are provided

**Steps to reproduce the issue**

1.
2.
3.
...

**What version of Home Assistant Core has the issue?**

2021.2.3

**What was the last working version of Home Assistant Core?**

?

**In which browser are you experiencing the issue with?**

_No response_

**Which operating system are you using to run this browser?**

not relevant

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.
      - type: button
        icon: mdi:shield-home
        name: ALARM SYSTEM
        tap_action:
          action: call-service
          service: script.turn_on_alarm_system
          confirmation: true
        action_name: Activate
```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

<img width="409" alt="Schermafbeelding 2021-02-28 om 23 06 51" src="https://user-images.githubusercontent.com/33354141/109435317-344afc80-7a1a-11eb-846e-f5f9671003bf.png">

<img width="501" alt="Schermafbeelding 2021-02-28 om 23 07 00" src="https://user-images.githubusercontent.com/33354141/109435329-4462dc00-7a1a-11eb-8bd6-6fd1ca68ae16.png">

am aware we can:
```
          confirmation:
            text: Are you sure you want to activate the Alarm system?
```

but this still feels like an unnecessary extra effort, where the frontend should be as human friendly as possible by default
