### ISSUE TITLE
Entities Card ha-card element overflow:hidden hides values of dropdown box

### ISSUE THREAD

**Issue by aex351** [home-assistant/frontend#8494]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

The values of a dropdown box when opened within an Entities Card are not fully visible. `overflow:hidden` is being applied to the `ha-card` element. This is causing an additional scrollbar to be applied to the list of values (note: sometimes no scrollbar is shown and then other values simply cannot be selected).

**Describe the behavior you expected**

The values should be fully visible.

**Steps to reproduce the issue**

1. Add an Entities Card to a dashboard and add a helper entity w/ values (dropdown box);
2. As a user open the dropdown box;
3. ha-card element contains 'overflow:hidden`.

**What version of Home Assistant Core has the issue?**

2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Google Chrome 88 (Desktop/Mobile) and mobile HA app

**Which operating system are you using to run this browser?**

_No response_

**State of relevant entities**

```css
ha-card {
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    overflow: hidden;
}
```

**Problem-relevant frontend configuration**

```yaml
type: entities
entities:
  - entity: input_select.my_entity_with_values
show_header_toggle: false
```

**Javascript errors shown in your browser console/inspector**

_No response_

Opened dropdown box:
![entities-card-bug](https://user-images.githubusercontent.com/79757148/109439857-58b1d380-7a30-11eb-8d60-01b41f59a86b.PNG)
Closed dropdown box:
![entities-card-bug-nothing-selected](https://user-images.githubusercontent.com/79757148/109439876-68c9b300-7a30-11eb-8432-549acc67a1f1.PNG)
