### ISSUE TITLE
Lovelace cards which in YAML mode has more than around 75 lines are not displayed correctly

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/frontend#8534]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have several cards in Lovelade. Entity cards with some extras that disabled the normal mode. Ie. they are displayed in YAML by default

I only see the first 72-77 or so lines and then a lot of empty white space followed by a flood of errors related to the YAML not being clean entity only.

If I scroll to the bottom I see the last lines but then the top lines are missing.

If you click on the last lines visible it is like the missing lines get loaded but when you scroll they get hidden again

The content of the cards I have tried with (I have tried many and of other types than entity) and they all behave the same if they are long. I have a two picture elements card that has same behaviour. 

### Describe the behavior you expected

I expect to see all the lines

It makes editing your Lovelace UI almost impossible

### Steps to reproduce the issue

Make an entity card with a lot of content. Like 100 lines. Not 100 entities. 100 lines.

### What version of Home Assistant Core has the issue?

core-2021.3.0

### What was the last working version of Home Assistant Core?

core-2021.2.3

### In which browser are you experiencing the issue with?

Google Chrome 88.0.4324.182 and also tried Firefox and Safary on IOS

### Which operating system are you using to run this browser?

Ubuntu 20.04 and latest IOS

### Problem-relevant frontend configuration

```yaml
entities:
  - closePosition: 0
    customClosedText: 0
    customMidClosedText: 50
    customMidOpenText: 85
    customOpenText: 100
    customSetpoints: true
    customText: true
    entity: cover.both_blinds
    midClosePosition: 50
    midOpenPosition: 85
    name: Both Blinds
    openPosition: 100
    reverseButtons: false
    type: 'custom:cover-position-preset-row'
  - closePosition: 0
    customClosedText: 0
    customMidClosedText: 50
    customMidOpenText: 85
    customOpenText: 100
    customSetpoints: true
    customText: true
    entity: cover.left_blinds
    midClosePosition: 50
    midOpenPosition: 85
    name: Left Blinds
    openPosition: 100
    reverseButtons: false
    type: 'custom:cover-position-preset-row'
  - closePosition: 0
    customClosedText: 0
    customMidClosedText: 50
    customMidOpenText: 85
    customOpenText: 100
    customSetpoints: true
    customText: true
    entity: cover.right_blinds
    midClosePosition: 50
    midOpenPosition: 85
    name: Right Blinds
    openPosition: 100
    reverseButtons: false
    type: 'custom:cover-position-preset-row'
  - closePosition: 0
    customClosedText: 0
    customMidClosedText: 50
    customMidOpenText: 75
    customOpenText: 100
    customSetpoints: true
    customText: true
    entity: cover.office_blinds
    midClosePosition: 50
    midOpenPosition: 75
    name: Office Blinds
    openPosition: 100
    reverseButtons: false
    type: 'custom:cover-position-preset-row'
  - closePosition: 0
    customClosedText: 0
    customMidClosedText: 50
    customMidOpenText: 75
    customOpenText: 100
    customSetpoints: true
    customText: true
    entity: cover.workshop_blinds
    midClosePosition: 50
    midOpenPosition: 75
    name: Workshop Blinds
    openPosition: 100
    reverseButtons: false
    type: 'custom:cover-position-preset-row'
  - entity: cover.kitchen_curtain
  - entity: cover.bedroom_insect
  - entity: cover.bedroom_curtain
  - entity: cover.bedroom_shade
  - entity: cover.small_window
  - entity: cover.living_room_curtain
show_header_toggle: false
title: Covers
type: entities


```

### Javascript errors shown in your browser console/inspector

Do not see any
