### ISSUE TITLE
Card Configuration: YAML View missing data on load

### ISSUE THREAD

**Issue by woodmj74** [home-assistant/frontend#8549]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On a Lovelace dashboard, go into edit mode and select to edit a card (in this case these are no created with the visual editor and all entered in YAML).

Not the entire YAML is loaded and only shown up to the height of the visual display on the right of card configuration. At the end of the list clicking in the YAML editor loads the missing lines at the bottom, however scrolling back up then blanks the upper part of the YAMLs until you click back into it.

### Describe the behavior you expected

The full YAML to be displayed on load (or at least not to disappear when more has been loaded)

### Steps to reproduce the issue

1. Edit a Lovelace dashboard
2. Edit a card (best to select a big beefy one and one where there is no visual editor!)
3. In the card configuration scroll to the bottom of the loaded YAML, this is capped off at the bottom of the visual display on the right hand side (screen shot 1)
4. Clicking in the YAML editor then loads the missing lines (screen shot 2)
5. Scroll back up the editor and the upper lines are then blank (screen shot 3)
6. These reappear when simply clicking in the editor again

### What version of Home Assistant Core has the issue?

2021.3.0

### What was the last working version of Home Assistant Core?

2021.2.3

### In which browser are you experiencing the issue with?

Version 88.0.4324.190 (Official Build) (64-bit) - and Edge

### Which operating system are you using to run this browser?

Win10

### Problem-relevant frontend configuration

```
cards:
  - type: 'custom:gap-card'
    height: 5
  - type: markdown
    content: |
      ## Home Assistant
  - entities:
      - type: 'custom:multiple-entity-row'
        entity: binary_sensor.remote_ui
        state_color: true
      - type: 'custom:multiple-entity-row'
        entity: sensor.ha_uptime
        name: Uptime
        format: total
        state_color: true
        icon: 'mdi:clock-check-outline'
      - type: divider
      - entity: binary_sensor.update_homeassistant
        type: 'custom:multiple-entity-row'
        show_state: false
        state_color: true
        name: Home Assistant Core
        tap_action:
          action: navigate
          navigation_path: /hassio/dashboard/
        entities:
          - entity: sensor.current_version
            name: Current
          - entity: binary_sensor.updater
            attribute: newest_version
            name: Available
      - entity: binary_sensor.update_os
        type: 'custom:multiple-entity-row'
        show_state: false
        state_color: true
        name: Operating System
        tap_action:
          action: navigate
          navigation_path: /hassio/dashboard/
        entities:
          - entity: sensor.os
            attribute: current_version
            name: Current
          - entity: sensor.os
            attribute: newest_version
            name: Available
      - entity: binary_sensor.update_supervisor
        type: 'custom:multiple-entity-row'
        show_state: false
        state_color: true
        name: Supervisor
        tap_action:
          action: navigate
          navigation_path: /hassio/system/
        entities:
          - entity: sensor.supervisor
            attribute: current_version
            name: Current
          - entity: sensor.supervisor
            attribute: newest_version
            name: Available
      - entity: binary_sensor.update_addons
        type: 'custom:multiple-entity-row'
        show_state: false
        state_color: true
        name: Add Ons
        tap_action:
          action: navigate
          navigation_path: /hassio/dashboard/
        entities:
          - entity: sensor.supervisor
            name: Available
      - entity: binary_sensor.update_hacs
        type: 'custom:multiple-entity-row'
        show_state: false
        state_color: true
        name: HACS
        tap_action:
          action: navigate
          navigation_path: /hacs/entry/
        entities:
          - entity: sensor.hacs
            name: Available
    state_color: true
    type: entities
  - type: markdown
    content: |
      ## Backup
  - entities:
      - entity: binary_sensor.backup
        type: 'custom:multiple-entity-row'
        show_state: false
        state_color: true
        tap_action:
          action: navigate
          navigation_path: /hassio/addon/cebe7a76_hassio_google_drive_backup/info/
        entities:
          - entity: binary_sensor.backup
            attribute: status
            name: false
      - entity: sensor.snapshot_backup
        type: 'custom:multiple-entity-row'
        show_state: false
        icon: 'mdi:camera'
        name: Last Snapshot
        entities:
          - entity: sensor.snapshot_backup
            attribute: last_snapshot
            name: false
            format: datetime
      - entity: sensor.snapshot_backup
        type: 'custom:multiple-entity-row'
        show_state: false
        icon: 'mdi:cached'
        name: Number of Snapshots
        entities:
          - entity: sensor.snapshot_backup
            attribute: snapshots_in_home_assistant
            name: HA
          - entity: sensor.snapshot_backup
            attribute: size_in_home_assistant
            name: Size
          - entity: sensor.snapshot_backup
            attribute: snapshots_in_google_drive
            name: Google
          - entity: sensor.snapshot_backup
            attribute: size_in_google_drive
            name: Size
    state_color: true
    type: entities
  - break
  - type: 'custom:gap-card'
    height: 5
  - type: markdown
    content: |
      ## Odriod N2+
  - entities:
      - entity: sensor.processor_use
        entity_row: true
        name: Processor
        type: 'custom:bar-card'
      - entity: sensor.memory_use_percent
        entity_row: true
        name: Memory
        type: 'custom:bar-card'
      - entity: sensor.disk_use_percent
        entity_row: true
        name: Disk
        type: 'custom:bar-card'
      - entity: sensor.processor_temperature
        entity_row: true
        name: Temperature
        type: 'custom:bar-card'
      - entity: sensor.last_boot
        name: Last Reboot
        icon: 'mdi:restart'
    type: entities
  - type: horizontal-stack
    cards:
      - type: 'custom:mini-graph-card'
        hours_to_show: 24
        line_width: 10
        line_color: '#03a9f4'
        name: Processor
        entities:
          - entity: sensor.processor_use
        show:
          average: true
          state: false
      - type: 'custom:mini-graph-card'
        hours_to_show: 24
        line_width: 10
        line_color: '#03a9f4'
        name: Temperature
        entities:
          - entity: sensor.processor_temperature
        show:
          average: true
          state: false
  - type: horizontal-stack
    cards:
      - type: 'custom:mini-graph-card'
        hours_to_show: 24
        line_width: 10
        line_color: '#03a9f4'
        name: Memory
        entities:
          - entity: sensor.memory_use
        show:
          average: true
          state: false
      - type: 'custom:mini-graph-card'
        hours_to_show: 24
        line_width: 10
        line_color: '#03a9f4'
        name: Disk
        entities:
          - entity: sensor.disk_use
        show:
          average: true
          state: false
layout: vertical
type: 'custom:layout-card'


```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

Screen shot 1:
![image](https://user-images.githubusercontent.com/68328701/109986208-710a4280-7cfd-11eb-9eb2-e9b1686d85a5.png)

Screen shot 2:
![image](https://user-images.githubusercontent.com/68328701/109986348-8ed7a780-7cfd-11eb-9376-d8f99d7d5e46.png)

Screen shot 3:
![image](https://user-images.githubusercontent.com/68328701/109986593-cfcfbc00-7cfd-11eb-9f3b-8d95681ae6e1.png)
