### ISSUE TITLE
Impossible to use template for numeric data attributes

### ISSUE THREAD

**Issue by estevez-dev** [home-assistant/frontend#8561]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating HA Core to 2021.3 it is impossible to use templates in numeric service call data attributes. For example, when adding a `media_player.media_seek` service call in the automation actions it is impossible to add template value for `seek_position`.
When switching to YAML editor and adding a template there, it will be removed when saving the automation.

### Describe the behavior you expected

It is possible to use templates for numeric data attributes for service calls.

### Steps to reproduce the issue

1. Create an automation
2. Create a Service Call action calling `media_player.media_seek`
3. Try to use a template in Position field in UI or `seek_position` in YAML editor
...

### What version of Home Assistant Core has the issue?

core-2021.3

### What was the last working version of Home Assistant Core?

core-2021.2

### In which browser are you experiencing the issue with?

Google Chrome 88.0.4324.208

### Which operating system are you using to run this browser?

Chrome OS

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by frenck** [comment]
Could you share the relevant template that doesn't work?

**Comment by estevez-dev** [comment]
Hi @frenck . Sure, but the issue is not in a template itself. It is just removed when added trough UI.
Here is how it was working in HA core 2021.2:
```yaml
  - service: media_player.media_seek
    data:
      entity_id: media_player.chromecast_living_room
      seek_position: '{{state_attr(''media_player.chromecast_living_room'', ''media_position'')
        + now() | as_timestamp - state_attr(''media_player.chromecast_living_room'',
        ''media_position_updated_at'') | as_timestamp - 30}}'
```

**Comment by wigster** [comment]
I have a similar problem. If you create the following templae in the automation UI
```
id: auto_trv_salon_correction2
alias: Correct TRV Salon Temp 2
description: Correct TRV Salon Temperature to that given by room Xiaomi thermometer
trigger:
  - platform: state
    entity_id: sensor.trv_living_room_air_temperature
  - platform: state
    entity_id: sensor.salon_temperature
condition: []
action:
  - service: input_number.set_value
    target:
      entity_id: input_number.salon_temperature_correction
    data:
      value: >
        {## Read room temp from sensor and from TRV. Calculate difference ##}
        {% set sensor_temp = float(states('sensor.salon_temperature'))%}
        {%   set trv_temp = float(states('sensor.trv_living_room_air_temperature')) %}
        {%   set corr = [-5,(sensor_temp - trv_temp) | round(1)]|max %}
        {%   set corr = [5,corr | round(1)]|min %}
        {{ corr }}
  - service: zwave_js.set_config_parameter
    data:
      parameter: "8"
      value: >
        {## This takes the above temp corr, multiplies by 10 and passes ##}
        {## to the config param if positive. If -ve > passes value 256 + corr ##}  
        {% set corr = 10*float(states('input_number.salon_temperature_correction'))  %} 
        {% if corr<0 -%} 
        {% set corr = 256 + corr %}
        {%- endif %}
        {{'%0.0f'|format(corr)}}
    target:
      device_id: 32ab6dc7b858f9a872df75b8d891bef7
mode: restart
```
it becomes garbled when you save it and reopen for editing:
```
alias: Correct TRV Salon Temp 2
description: Correct TRV Salon Temperature to that given by room Xiaomi thermometer
trigger:
  - platform: state
    entity_id: sensor.trv_living_room_air_temperature
  - platform: state
    entity_id: sensor.salon_temperature
condition: []
action:
  - service: input_number.set_value
    target:
      entity_id: input_number.salon_temperature_correction
    data: {}
  - service: zwave_js.set_config_parameter
    data:
      parameter: '8'
      value: >
        {## This takes the above temp corr, multiplies by 10 and passes ##} {##
        to the config param if positive. If -ve > passes value 256 + corr ##}  
        {% set corr =
        10*float(states('input_number.salon_temperature_correction'))  %}  {% if
        corr<0 -%}  {% set corr = 256 + corr %} {%- endif %}
        {{'%0.0f'|format(corr)}}
    target:
      device_id: 32ab6dc7b858f9a872df75b8d891bef7
mode: restart
```
