### ISSUE TITLE
Can't Play Videos on Android Tablet

### ISSUE THREAD

**Issue by mathmaniac43** [home-assistant/frontend#8575]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I cannot play videos from my security cameras on my Android tablet (Samsung Galaxy A7 SM-T500). I have tried to view them via the Home Assistant app and the Chrome browser, and neither work. The video streams still work fine on my Windows computer or the Android app on my cell phone.

I chimed into an existing issue in the Android app repo, but was told that since it appears to be an issue in Chrome as well, it is likely a Frontend issue.
https://github.com/home-assistant/android/issues/1355#issuecomment-791952495

### Describe the behavior you expected

I expect the videos to play, both when in the live camera picture entity mode, as well as when selected and made fullscreen.

### Steps to reproduce the issue

1. View live camera picture entity on Android tablet from Lovelace dashboard.
2. Open specific camera feed on Android tablet.

### What version of Home Assistant Core has the issue?

core-2021.3.2

### In which browser are you experiencing the issue with?

Google Chrome 88.0.4324.181; Home Assistant Companion 2021.3.1-full

### Which operating system are you using to run this browser?

Android 10 QP1A.190711.020.T500XXS2ATL1

### State of relevant entities

```yaml
access_token: REDACTED
daynight_state: AUTO
sensitivity:
  - id: 0
    sensitivity: 28
    begin: '00:00'
    end: '06:00'
  - id: 1
    sensitivity: 28
    begin: '06:00'
    end: '12:00'
  - id: 2
    sensitivity: 28
    begin: '12:00'
    end: '18:00'
  - id: 3
    sensitivity: 28
    begin: '18:00'
    end: '23:59'
friendly_name: Front-Door
entity_picture: >-
  REDACTED
supported_features: 2

```

### Problem-relevant frontend configuration

```yaml
type: picture-entity
entity: camera.front_door
camera_view: live
show_state: false
show_name: false
```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```
