### ISSUE TITLE
[UPDATED INFO] UI Script/Automation Editor: Opening select scripts/automations for editing and the SAVE button immediately activates

### ISSUE THREAD

**Issue by danielbrunt57** [home-assistant/frontend#8576]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have several automations and two scripts that every time you open them via the UI Editor, the SAVE button is immediately activated.

### Describe the behavior you expected

The SAVE button should not be activate as no edits have been done yet.

### Steps to reproduce the issue

1. Open one of my problem scripts/automations
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.3.2

### What was the last working version of Home Assistant Core?

I think core-2021.2.?

### State of relevant entities

n/a

### Problem-relevant frontend configuration

Problem Automations:
```
alias: Actionable - I Bought Coffee Filters
description: ''
trigger:
  - platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_coffee_filters
      event_response_type: ResponseNumeric
condition: []
action:
  - service: input_number.set_value
    target:
      entity_id: input_number.coffee_filter_count
    data_template:
      value: >-
        {{ trigger.event.data.event_response|int +
        states('input_number.coffee_filter_count')|int}}
  - service: notify.alexa_media_last_called
    data:
      message: >
        You now have '{{ states("input_number.coffee_filter_count")|int }}'
        coffee filters.
      data:
        type: tts
  - service: shopping_list.complete_item
    data:
      name: Coffee filters
mode: single
```
```
alias: Actionable Notification - Lock the door?
trigger:
  - platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_lock_left_unlocked
      event_response_type: ResponseYes
action:
  - service: lock.lock
    data: {}
    target:
      entity_id: lock.front_door_lock
mode: single
```
```
alias: Alexa Guard - Home/Away
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.daniel_is_home
    to: 'on'
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.daniel_is_home
            state: 'on'
        sequence:
          - service: alarm_control_panel.alarm_disarm
            data: {}
            target:
              entity_id: alarm_control_panel.alexa_guard_da03a
      - conditions:
          - condition: state
            entity_id: binary_sensor.daniel_is_home
            state: 'off'
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            data: {}
            target:
              entity_id: alarm_control_panel.alexa_guard_da03a
    default: []
mode: single
```
```
alias: Alexa Guard - Home/Away
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.daniel_is_home
    to: 'on'
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.daniel_is_home
            state: 'on'
        sequence:
          - service: alarm_control_panel.alarm_disarm
            data: {}
            target:
              entity_id: alarm_control_panel.alexa_guard_da03a
      - conditions:
          - condition: state
            entity_id: binary_sensor.daniel_is_home
            state: 'off'
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            data: {}
            target:
              entity_id: alarm_control_panel.alexa_guard_da03a
    default: []
mode: single
```
Problem Scripts:
```
alias: Good Morning
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.coffee_prepared
            state: 'on'
        sequence:
          - service: script.activate_alexa_actionable_notification
            data:
              text: Would you like me to start your coffee?
              event_id: actionable_notification_make_coffee
              alexa_device: '{{ states(''sensor.last_alexa'') }}'
          - wait_for_trigger:
              - platform: event
                event_type: alexa_actionable_notification
            timeout: '00:00:10'
    default:
      - service: notify.alexa_media_last_called
        data:
          message: 'I''m sorry, it looks like you''ll have to make your own coffee'
          data:
            type: tts
      - delay: '00:00:02'
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.night_mode
            state: 'off'
        sequence:
          - service: cover.set_cover_position
            data:
              position: 40
            entity_id: cover.bedroom_blind
    default:
      - service: light.turn_on
        data:
          transition: 120
          brightness_pct: 70
        target:
          entity_id: light.bedroom_lights
  - service: notify.alexa_media_last_called
    data:
      message: >-
        The temperature outside is {{
        states("sensor.outside_weather_temperature")|replace('.0','') }} {% if
        states("sensor.lumi_lumi_weather_temperature")|replace('.0','') != "1"
        %}degrees{% else %}degree{% endif %}{% if
        states("sensor.norton_court_realfeel_temperature") != "unknown" and
        states("sensor.norton_court_realfeel_temperature") !=
        states("sensor.lumi_lumi_weather_temperature") %} but it feels like {{
        states("sensor.norton_court_realfeel_temperature") }}{% if
        states("sensor.norton_court_realfeel_temperature")|replace('.0','') !=
        "1" %} degrees. {% else %} degree. {% endif -%}{% else %}. {% endif %} 
        The living room is currently {{
        state_attr("climate.living_room","current_temperature")|round(1,"half")|replace('.0','')
        }} degrees and the heat is {% if is_state("climate.living_room", "off")
        -%} turned off. {% else -%} set to {{
        state_attr("climate.living_room","temperature")|round(1,"half")|replace('.0','')
        }} {% endif %}
      data:
        type: tts
  - delay:
      hours: 0
      minutes: 0
      seconds: 13
      milliseconds: 0
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: sensor.season
                    state: summer
              - condition: numeric_state
                entity_id: climate.living_room
                attribute: temperature
                below: '21'
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: none
            entity_id: climate.living_room
          - service: climate.set_temperature
            data:
              temperature: 21
            entity_id: climate.living_room
          - service: notify.alexa_media_last_called
            data:
              message: I've set the heat to 21
              data:
                type: tts
          - delay: '00:00:01'
    default: []
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.garbage
            state: '0'
          - condition: state
            entity_id: input_boolean.garbage_is_out
            state: 'off'
          - condition: time
            before: '08:00:00'
        sequence:
          - service: notify.alexa_media_last_called
            data:
              message: You might still have time to put the garbage out.
              data:
                type: tts
    default: []
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.recycling
            state: '0'
          - condition: state
            entity_id: input_boolean.recycling_is_out
            state: 'off'
          - condition: time
            before: '07:45:00'
        sequence:
          - service: notify.alexa_media_last_called
            data:
              message: You might still have time to put the recycling out
              data:
                type: tts
    default: []
  - service: input_boolean.turn_off
    entity_id: input_boolean.sleep_mode
    data: {}
mode: single
icon: 'hass:weather-sunset-up'
```
```
alias: Good Night
sequence:
  - service: light.turn_off
    entity_id: light.bedroom_lights
    data:
      transition: 80
  - service: homeassistant.turn_off
    data: {}
    target:
      area_id:
        - bathroom
        - front_door
        - garage
        - cd09dc33605e4919ba81a1208862d911
        - office
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.coffee_prepared
            state: 'off'
        sequence:
          - service: script.activate_alexa_actionable_notification
            data:
              text: Did you prepare your coffee?
              event_id: actionable_notification_coffee_prepared
              alexa_device: '{{ states.sensor.last_alexa.state }}'
          - wait_for_trigger:
              - platform: event
                event_type: alexa_actionable_notification
            timeout: '00:00:10'
    default: []
  - choose:
      - conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: climate.living_room
                attribute: preset_mode
                state: eco
        sequence:
          - service: climate.set_preset_mode
            data:
              preset_mode: eco
            entity_id: climate.living_room
          - service: notify.alexa_media_last_called
            data:
              message: Furnace is now in echo mode
              data:
                type: tts
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
    default: []
  - choose:
      - conditions:
          - condition: state
            entity_id: lock.front_door_lock
            state: unlocked
        sequence:
          - service: lock.lock
            data: {}
            target:
              entity_id: lock.front_door_lock
          - service: notify.alexa_media_last_called
            data:
              message: The front door was unlocked but I locked it for you.
              data:
                type: tts
          - delay: '00:00:01'
  - choose:
      - conditions:
          - condition: state
            entity_id: cover.garage_door
            state: open
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: sensor.season
                    state: summer
                sequence:
                  - service: notify.alexa_media_last_called
                    data:
                      message: psst. the garage door is still open.
                      data:
                        type: tts
                  - delay: '00:00:01'
            default:
              - service: cover.close_cover
                data:
                  entity_id: cover.garage_door
              - service: notify.alexa_media_last_called
                data:
                  message: I closed the garage door for you
                  data:
                    type: tts
              - delay: '00:00:01'
    default: []
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.garbage_is_out
            state: 'off'
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.garbage
                    below: '1'
                  - condition: time
                    before: '09:00:00'
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.garbage
                    below: '2'
                    above: '0'
                  - condition: time
                    after: '09:00:00'
        sequence:
          - service: script.activate_alexa_actionable_notification
            data:
              text: Did you put the garbage out?
              event_id: actionable_notification_garbage_pickup
              alexa_device: '{{ states.sensor.last_alexa.state }}'
          - wait_for_trigger:
              - platform: event
                event_type: alexa_actionable_notification
            timeout: '00:00:10'
    default: []
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.recycling_is_out
            state: 'off'
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.recycling
                    below: '1'
                  - condition: time
                    before: '12:00:00'
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.recycling
                    below: '2'
                    above: '0'
                  - condition: time
                    after: '12:00:00'
        sequence:
          - service: script.activate_alexa_actionable_notification
            data:
              text: Did you put the recycling out?
              event_id: actionable_notification_garbage_pickup
              alexa_device: '{{ states.sensor.last_alexa.state }}'
          - wait_for_trigger:
              - platform: event
                event_type: alexa_actionable_notification
            timeout: '00:00:10'
    default: []
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: input_boolean.turn_on
    entity_id: input_boolean.sleep_mode
mode: single
icon: 'hass:weather-night'
```

### Javascript errors shown in your browser console/inspector

n/a

**Comment by bramkragten** [comment]
Most likely because your mode is missing. The UI adds this for you and therefore changes the script/automation.

**Comment by danielbrunt57** [comment]
I went through the automations.yaml file and found numerous oddities that I cleaned up but all entries had `mode:` listed.  There were a couple of `id:` numbers that were quite long and unquoted.  I deleted those sections entirely and recreated them.  The other oddities were extraneous line breaks in templates and one had a bunch of \n's in it.
After a thorough cleaning and HA restart, the automations in question now load without SAVE triggering
I've only ever used the UI for creating/editing automations so I am not sure when/how the weirdness entered the file!

Now to look at scripts.yaml...

**Comment by danielbrunt57** [comment]
Success!  Good Morning now loads into editor without triggering SAVE after cleaning up the file.  The problems were not in the script but further down like in test_light_on
```
  variables:
    entities:
    - light.office_light_1
    - light.office_light_2
    - light.office_light_3
    color_temp: '{{ state_attr(''switch.adaptive_lighting_office'', ''color_temp_kelvin'')
      }}

      '
  mode: single
```
New scripts.yaml:
```
good_night:
  alias: Good Night
  sequence:
  - service: light.turn_off
    entity_id: light.bedroom_lights
    data:
      transition: 80
  - service: homeassistant.turn_off
    data: {}
    target:
      area_id:
      - bathroom
      - front_door
      - garage
      - cd09dc33605e4919ba81a1208862d911
      - office
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.coffee_prepared
        state: 'off'
      sequence:
      - service: script.activate_alexa_actionable_notification
        data:
          text: Did you prepare your coffee?
          event_id: actionable_notification_coffee_prepared
          alexa_device: '{{ states.sensor.last_alexa.state }}'
      - wait_for_trigger:
        - platform: event
          event_type: alexa_actionable_notification
        timeout: 00:00:10
    default: []
  - choose:
    - conditions:
      - condition: not
        conditions:
        - condition: state
          entity_id: climate.living_room
          attribute: preset_mode
          state: eco
      sequence:
      - service: climate.set_preset_mode
        data:
          preset_mode: eco
        entity_id: climate.living_room
      - service: notify.alexa_media_last_called
        data:
          message: Furnace is now in echo mode
          data:
            type: tts
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: lock.front_door_lock
        state: unlocked
      sequence:
      - service: lock.lock
        data: {}
        target:
          entity_id: lock.front_door_lock
      - service: notify.alexa_media_last_called
        data:
          message: The front door was unlocked but I locked it for you.
          data:
            type: tts
      - delay: 00:00:01
  - choose:
    - conditions:
      - condition: state
        entity_id: cover.garage_door
        state: open
      sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: sensor.season
            state: summer
          sequence:
          - service: notify.alexa_media_last_called
            data:
              message: psst. the garage door is still open.
              data:
                type: tts
          - delay: 00:00:01
        default:
        - service: cover.close_cover
          data:
            entity_id: cover.garage_door
        - service: notify.alexa_media_last_called
          data:
            message: I closed the garage door for you
            data:
              type: tts
        - delay: 00:00:01
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.garbage_is_out
        state: 'off'
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.garbage
            below: '1'
          - condition: time
            before: 09:00:00
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.garbage
            below: '2'
            above: '0'
          - condition: time
            after: 09:00:00
      sequence:
      - service: script.activate_alexa_actionable_notification
        data:
          text: Did you put the garbage out?
          event_id: actionable_notification_garbage_pickup
          alexa_device: '{{ states.sensor.last_alexa.state }}'
      - wait_for_trigger:
        - platform: event
          event_type: alexa_actionable_notification
        timeout: 00:00:10
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.recycling_is_out
        state: 'off'
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.recycling
            below: '1'
          - condition: time
            before: '12:00:00'
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.recycling
            below: '2'
            above: '0'
          - condition: time
            after: '12:00:00'
      sequence:
      - service: script.activate_alexa_actionable_notification
        data:
          text: Did you put the recycling out?
          event_id: actionable_notification_garbage_pickup
          alexa_device: '{{ states.sensor.last_alexa.state }}'
      - wait_for_trigger:
        - platform: event
          event_type: alexa_actionable_notification
        timeout: 00:00:10
    default: []
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: input_boolean.turn_on
    entity_id: input_boolean.sleep_mode
  mode: single
  icon: hass:weather-night
morning:
  alias: Morning
  sequence:
  - service: media_player.alexa_tts
    data_template:
      entity_id: notify.alexa_media_bedroom_echo_left
      message: -> 'Good morning Daniel, it is {{ as_timestamp(now()) | timestamp_custom("%I
        %M %p") }} on {{ as_timestamp(now()) | timestamp_custom("%A") }} the {{ states("sensor.date_human")
        }} of {{ as_timestamp(now()) | timestamp_custom("%B") }}. You {% if states("calendar.work")
        == "on" or states("binary_sensor.workday_sensor") == "off" -%} are not {%-
        else -%} are {%- endif %} due in work today. The temperature outside feels
        like {{ states("sensor.dark_sky_apparent_temperature")}} degrees. Your indoor
        temperature is {{ state_attr("climate.heating", "current_temperature") }}
        degrees. The probability of rain for the hour is {{ states("sensor.dark_sky_precip_probability")
        }} percent. You have {{ states("sensor.annual_leave")}} days of Annual Leave
        remaining and your flexitime balance is {{ states("sensor.flexi_balance")}}
        hours. It looks like it will take you {{ states("sensor.luke_work_to_home_travel_time")
        }} minutes to get to work. {% set curr_date = as_timestamp(now()) | timestamp_custom("%Y-%m-%d")
        %}{% for state in states.calendar if state.name == "Google Family" or state.name
        == "Google Lift Share"  -%}{% set cal_start_date = as_timestamp(state.attributes.start_time)
        | timestamp_custom("%Y-%m-%d") %}{% set cal_start_time = as_timestamp(state.attributes.start_time)
        | timestamp_custom("%I %M %p") %}{% if cal_start_date == curr_date -%}The
        first item on your {{ state.name }} calendar today is {{state.attributes.message
        }} at {{ cal_start_time }}{%- else -%} You have nothing on your {{ state.name
        }} calendar today {% endif -%}{%- endfor %}'
  - delay: 00:00:40
  - service: notify.alexa_media_bedroom_echo_left
    data:
      entity_id: media_player.bedroom_echo_left
  mode: single
set_temperature:
  alias: Set Thermostat Temperature
  sequence:
  - service: climate.set_temperature
    data:
      temperature: '{{ temperature }}'
      hvac_mode: heat
    entity_id: climate.inside_nest_thermostat
  mode: single
  icon: hass:thermostat
sleep_mode:
  alias: Sleep Mode
  sequence:
  - service: input_boolean.toggle
    data: {}
    entity_id: input_boolean.sleep_mode
  mode: single
  icon: hass:sleep
good_morning:
  alias: Good Morning
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.coffee_prepared
        state: 'on'
      sequence:
      - service: script.activate_alexa_actionable_notification
        data:
          text: Would you like me to start your coffee?
          event_id: actionable_notification_make_coffee
          alexa_device: '{{ states(''sensor.last_alexa'') }}'
      - wait_for_trigger:
        - platform: event
          event_type: alexa_actionable_notification
        timeout: 00:00:10
    default:
    - service: notify.alexa_media_last_called
      data:
        message: I'm sorry, it looks like you'll have to make your own coffee
        data:
          type: tts
    - delay: 00:00:02
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_mode
        state: 'off'
      sequence:
      - service: cover.set_cover_position
        data:
          position: 40
        entity_id: cover.bedroom_blind
    default:
    - service: light.turn_on
      data:
        transition: 120
        brightness_pct: 70
      target:
        entity_id: light.bedroom_lights
  - service: notify.alexa_media_last_called
    data:
      message: The temperature outside is {{ states("sensor.outside_weather_temperature")|replace('.0','')
        }} {% if states("sensor.lumi_lumi_weather_temperature")|replace('.0','') !=
        "1" %}degrees{% else %}degree{% endif %}{% if states("sensor.norton_court_realfeel_temperature")
        != "unknown" and states("sensor.norton_court_realfeel_temperature") != states("sensor.lumi_lumi_weather_temperature")
        %} but it feels like {{ states("sensor.norton_court_realfeel_temperature")
        }}{% if states("sensor.norton_court_realfeel_temperature")|replace('.0','')
        != "1" %} degrees. {% else %} degree. {% endif -%}{% else %}. {% endif %}  The
        living room is currently {{ state_attr("climate.living_room","current_temperature")|round(1,"half")|replace('.0','')
        }} degrees and the heat is {% if is_state("climate.living_room", "off") -%}
        turned off. {% else -%} set to {{ state_attr("climate.living_room","temperature")|round(1,"half")|replace('.0','')
        }} {% endif %}
      data:
        type: tts
  - delay:
      hours: 0
      minutes: 0
      seconds: 13
      milliseconds: 0
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: not
          conditions:
          - condition: state
            entity_id: sensor.season
            state: summer
        - condition: numeric_state
          entity_id: climate.living_room
          attribute: temperature
          below: '21'
      sequence:
      - service: climate.set_preset_mode
        data:
          preset_mode: none
        entity_id: climate.living_room
      - service: climate.set_temperature
        data:
          temperature: 21
        entity_id: climate.living_room
      - service: notify.alexa_media_last_called
        data:
          message: I've set the heat to 21
          data:
            type: tts
      - delay: 00:00:01
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.garbage
        state: '0'
      - condition: state
        entity_id: input_boolean.garbage_is_out
        state: 'off'
      - condition: time
        before: 08:00:00
      sequence:
      - service: notify.alexa_media_last_called
        data:
          message: You might still have time to put the garbage out.
          data:
            type: tts
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.recycling
        state: '0'
      - condition: state
        entity_id: input_boolean.recycling_is_out
        state: 'off'
      - condition: time
        before: 07:45:00
      sequence:
      - service: notify.alexa_media_last_called
        data:
          message: You might still have time to put the recycling out
          data:
            type: tts
    default: []
  - service: input_boolean.turn_off
    entity_id: input_boolean.sleep_mode
    data: {}
  mode: single
  icon: hass:weather-sunset-up
activate_alexa_actionable_notification:
  alias: Activate Alexa Actionable Notification
  sequence:
  - service: input_text.set_value
    entity_id: input_text.alexa_actionable_notification
    data:
      value: '{"text": "{{ text }}", "event": "{{ event_id }}" }'
    target:
      entity_id: input_text.alexa_actionable_notification
  - service: media_player.play_media
    target:
      entity_id: '{{ alexa_device }}'
    data:
      media_content_type: skill
      media_content_id: amzn1.ask.skill.6b2071e3-0f30-4fcf-b3d3-65631de50fd2
  mode: single
  description: Activates an actionable notification on a specific echo device
  fields:
    text:
      description: The text you would like alexa to speak.
      example: What would you like the thermostat set to?
    event_id:
      description: Correlation ID for event responses
      example: ask_for_temperature
    alexa_device:
      description: Alexa device you want to trigger
      example: media_player.new_white_echo_dot
make_coffee:
  alias: Make Coffee
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.coffee_prepared
        state: 'off'
      sequence:
      - service: script.activate_alexa_actionable_notification
        data:
          text: Did you prepare the coffee machine?
          event_id: actionable_notification_coffee_prepared
          alexa_device: '{{ states.sensor.last_alexa.state }}'
      - wait_for_trigger:
        - platform: event
          event_type: action_coffee_prepared
        timeout: 00:00:30
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.coffee_prepared
        state: 'on'
      sequence:
      - service: switch.toggle
        data: {}
        entity_id: switch.sonoff_inching
    default:
    - service: notify.alexa_media_last_called
      data:
        message: I can't make coffee if you don't prepare it!
        data:
          type: tts
  mode: single
  icon: hass:coffee-maker
lights_out:
  alias: Lights Out
  sequence:
  - service: light.turn_off
    data: {}
    entity_id: all
  mode: single
  icon: hass:lightbulb-group
feed_fish:
  alias: Feed Fish
  sequence:
  - service: alexa_media.update_last_called
    data: {}
  - service: switch.turn_off
    data: {}
    entity_id: switch.beta_filter
  - service: switch.turn_off
    data: {}
    entity_id: switch.main_filter
  - service: switch.turn_off
    data: {}
    entity_id: switch.uv_filter
  - service: switch.turn_off
    data: {}
    entity_id: switch.air_pump
  mode: single
  icon: hass:fish
log_heating:
  alias: HVAC Log - Heating
  sequence:
  - service: logbook.log
    data:
      name: Nest Thermostat
      message: 'heating {{ state_attr(''climate.living_room'',''current_temperature'') }}'
      entity_id: climate.living_room
  mode: single
log_cooling:
  alias: HVAC Log - Cooling
  sequence:
  - service: logbook.log
    data:
      name: Nest Thermostat
      message: 'cooling {{ state_attr(''climate.living_room'',''current_temperature'') }}'
      entity_id: climate.living_room
  mode: single
log_idle:
  alias: HVAC Log - Idle
  sequence:
  - service: logbook.log
    data:
      name: Nest Thermostat
      message: 'idle {{ state_attr(''climate.living_room'',''current_temperature'') }}'
      entity_id: climate.living_room
  mode: single
test_light_off:
  alias: Test Light Off
  sequence:
  - service: light.turn_off
    data:
      entity_id:
      - light.office_light_1
      - light.office_light_2
      - light.office_light_3
  variables:
    entities:
    - light.office_light_1
    - light.office_light_2
    - light.office_light_3
    color_temp: '{{ state_attr(''switch.adaptive_lighting_office'', ''color_temp_kelvin'') }}'
  mode: single
new_scripttest_lights_flip_flop:
  alias: Test Lights flip-flop
  sequence:
  - service: script.test_light_off
    data: {}
  - delay: 00:00:02
  - service: script.test_light_on
    data: {}
  - delay: 00:00:05
  - service: script.test_light_off
    data: {}
  - delay: 00:00:02
  - service: script.test_light_on
    data: {}
  - delay: 00:00:05
  - service: script.test_light_off
    data: {}
  - delay: 00:00:02
  - service: script.test_light_on
    data: {}
  mode: single
test_light_on:
  alias: Test Light On
  sequence:
  - service: light.turn_on
    data:
      entity_id: '{{ entities }}'
      kelvin: '{{ color_temp }}'
      brightness: 80
  variables:
    entities:
    - light.office_light_1
    - light.office_light_2
    - light.office_light_3
    color_temp: '{{ state_attr(''switch.adaptive_lighting_office'', ''color_temp_kelvin'') }}'
  mode: single
bought_coffee_filters:
  alias: Alexa - I Bought Coffee Filters
  sequence:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: How many coffee filters did you buy?
      event_id: actionable_notification_coffee_filters
      alexa_device: '{{ states.sensor.last_alexa.state }}'
  mode: single
```
I recognize all the oddities being from the same general time frame but when exactly (i.e. what version HA) I've no idea...

**Comment by danielbrunt57** [comment]
New info...
I've spent the last several hours editing each of my automations via UI and saving the problem ones' yaml code into notepad txt files and deleting them from HA.  I then spent more tedious time recreating them slowly and testing what breaks the UI.  At first I thought it was choose: but have narrowed it down to call service entries and _optional_ unselected fields.  One simple one for instance:
```
alias: Daniel leaves home
description: ''
trigger:
  - platform: state
    entity_id: person.daniel_brunt
    from: home
condition: []
action:
  - service: notify.pushover
    data:
      message: Goodbye
      title: Home Assistant
  - choose:
      - conditions:
          - condition: state
            entity_id: lock.front_door_lock
            state: Unlocked
        sequence:
          - service: lock.lock
            data: {}
            target:
              entity_id: lock.front_door_lock
    default: []
  - choose:
      - conditions:
          - condition: state
            entity_id: light.porch_light
            state: 'On'
        sequence:
          - service: light.turn_off
            data:
              entity_id: light.porch_light
    default: []
  - choose:
      - conditions:
          - condition: state
            entity_id: cover.garage_door
            state: Open
        sequence:
          - service: cover.close_cover
            data:
              entity_id: cover.garage_door
          - delay: '00:01:00'
          - choose:
              - conditions:
                  - condition: state
                    entity_id: cover.garage_door
                    state: Open
                sequence:
                  - service: cover.close_cover
                    data:
                      entity_id: cover.garage_door
            default: []
    default: []
    ```
I recreated this one step by step saving and re-opening it.  I cannot add for instance a notify.pushover without being force to tick the _optional_ Title and entering something.  This works:
```
alias: Daniel Leaves Home
description: ''
trigger:
  - platform: state
    entity_id: sensor.vog_l04_wifi_bssid
    from: '78:8a:20:55:6e:cc'
condition: []
action:
  - service: notify.pushover
    data:
      message: Goodbye
      title: Home Assistant
mode: single
```
This one breaks the UI triggering an immediate force to save upon opening it for editing:
```
alias: Daniel Leaves Home
description: ''
trigger:
  - platform: state
    entity_id: sensor.vog_l04_wifi_bssid
    from: '78:8a:20:55:6e:cc'
condition: []
action:
  - service: notify.pushover
    data:
      message: Goodbye
mode: single
```
as does this one:
```
alias: Daniel Leaves Home
description: ''
trigger:
  - platform: state
    entity_id: sensor.vog_l04_wifi_bssid
    from: '78:8a:20:55:6e:cc'
condition: []
action:
  - service: notify.pushover
    data:
      message: Goodbye
      title: Home Assistant
  - service: lock.lock
    data: {}
    target:
      entity_id: lock.front_door_lock
mode: single
```
For that last one I am forced to tick the _optional_ Code: field:
```
alias: Daniel Leaves Home
description: ''
trigger:
  - platform: state
    entity_id: sensor.vog_l04_wifi_bssid
    from: '78:8a:20:55:6e:cc'
condition: []
action:
  - service: notify.pushover
    data:
      message: Goodbye
      title: Home Assistant
  - service: lock.lock
    data:
      code: '123456'
    target:
      entity_id: lock.front_door_lock
mode: single
```
The same holds true for light.[turn_on|turn_off|toggle], notify,alexa_media, etc. , etc.
HA is updated to most recent 2021.3.4...
