### ISSUE TITLE
Badges color - door opening sensor

### ISSUE THREAD

**Issue by ruszok** [home-assistant/frontend#8588]
### The problem

Dark theme, primary color: red, accent color: orange.
All badges have red (primary color) outline. Only one have different (blue) outline - it is door opening sensor badge.

### What is version of Home Assistant Core has the issue?

2021.3.2

### What type of installation are you running?

Home Assistant Supervised

### Example YAML snippet

```yaml
# Put your YAML below this line
badges:
      - entity: alarm_control_panel.xiaomi_centralka_alarmowa_alarm
      - entity: binary_sensor.drzwi_przedpokoj
      - entity: sensor.temperature_podworko
      - entity: sensor.temperature_salon
      - entity: sensor.ocz_sypialnia_aqi
      
State: off
Open since: 0
voltage: 3.04
battery_level: 47
friendly_name: Drzwi wejściowe
device_class: opening

```

### Anything in the logs that might be useful for us?

```txt
# Put your logs below this line

```

![Screenshot_20210308-062636](https://user-images.githubusercontent.com/68990273/110278296-49ee9200-7fd7-11eb-9f1b-7fedbfde027f.jpg)
