### ISSUE TITLE
Non-Numerical and Numerical sensor graphs don't align on a History Graph Card

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#8590]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A History Graph Card should show different sensors over a period of time, but when a user put non-numerical sensors on a card, their label is on the right, moving the x-axis (time) to the left. This means the scales don't align between non-numerical sensors and numerical ones, which makes comparing really hard.

### Describe the behavior you expected

One History Graph Card should have the same scale and position for all x-axis and the labels should be positioned around the graphs in a way that they cannot move the x-axis.

### Steps to reproduce the issue

1. Create a History Graph Card
2. Add a non-numerical sensor
3. Add a numerical sensor

### What version of Home Assistant Core has the issue?

core-2021.3.2

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Chromium: 89.0.4389.72 / Firefox 86.0

### Which operating system are you using to run this browser?

ArchLinux

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sun.sun
  - entity: binary_sensor.window_sensor_kitchen_contact
  - entity: input_boolean.heatsource_present_kitchen
  - entity: switch.kitchen_under_cupboard_lights
  - entity: sensor.temp_sensor_kitchen_temperature
  - entity: sensor.radiator_valve_kitchen_position
  - entity: input_number.target_temp_kitchen
  - entity: sensor.outdoor_temperature_temperature
hours_to_show: 72
refresh_interval: 3600
```

### Screenshot

![Screenshot_20210308_164918-1](https://user-images.githubusercontent.com/614929/110368668-a9858580-8049-11eb-87bf-65e20fae2975.png)
