### ISSUE TITLE
Automations does not show data field

### ISSUE THREAD

**Issue by dannytsang** [home-assistant/frontend#8591]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Calling a script from an automation doesn't show data field like it used to.

### Describe the behavior you expected

When calling a script, I'd expect the data field to be exposed. I use this to pass parameters to scripts.

### Steps to reproduce the issue

1. Open / create an automation
2. In actions, add a "Call service" type.
3. In the "Service" field, select a pre-made script
...

### What version of Home Assistant Core has the issue?

core-2021.3.2

### What was the last working version of Home Assistant Core?

core-2021.2

### In which browser are you experiencing the issue with?

Firefox 86.0 and Microsoft Edge 89.0.774.45

### Which operating system are you using to run this browser?

Windows 10 build 19042.804

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
alias: '3D Printer: Errored'
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.octoprint_printing_error
    from: 'off'
    to: 'on'
condition: []
action:
  - service: script.post_to_home_log
    data:
      title: 3D printer error
      message: ':warning: :printer: 3D printer has encountered an error :x: :warning:'
mode: single

alias: Post To Home Log
icon: 'mdi:slack'
max: 10
mode: queued
sequence:
  - condition: state
    entity_id: input_boolean.enable_slack_notifications
    state: 'on'
  - data:
      message: '{{ message }}'
      title: '{{ title }}'
      target: '#home_log'
      data:
        blocks: []
    service: notify.slack_notify

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

Screenshot of what it looks like in UI:
![image](https://user-images.githubusercontent.com/567982/110362578-5a375900-8039-11eb-8480-c7705f47b8f2.png)

Partial YAML view:
![image](https://user-images.githubusercontent.com/567982/110362616-64f1ee00-8039-11eb-8638-b766416cd8c8.png)

No issues when using an out the box service e.g turn on light:
![image](https://user-images.githubusercontent.com/567982/110362723-88b53400-8039-11eb-8b76-034490e4f43a.png)
