### ISSUE TITLE
Icon override does not works for google calendar entities

### ISSUE THREAD

**Issue by jffz** [home-assistant/frontend#8597]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Overriding google calendar entities using customization or lovelace badges does not work. 

### Describe the behavior you expected

The icon of the related entity shuld be overried with desired one

### Steps to reproduce the issue

1. configure google calendar integration
2.  configure google calendar entity based on calendar event
3. customize the entity by setting a custom icon (optional)
4. add the entity in lovelace badges and override its icon attribute

### What version of Home Assistant Core has the issue?

core-2021.3.3

### In which browser are you experiencing the issue with?

Brave - Version 1.21.73 Chromium: 89.0.4389.72, Chrome Version 88.0.4324.190

### Which operating system are you using to run this browser?

android, windows, linux

### State of relevant entities

```yaml
message: Jacuzzi
all_day: true
start_time: '2021-03-14 00:00:00'
end_time: '2021-03-15 00:00:00'
location: ''
description: ''
offset_reached: false
friendly_name: jacuzzi
```

### Problem-relevant frontend configuration

```yaml

badges:
  - type: entity-filter
    entities:
      - entity: calendar.jacuzzi
        icon: 'mdi:pool'        
    state_filter:
      - "on"
```
