### ISSUE TITLE
Saving script in Frontend breaks long lines which in turn breaks the functionality

### ISSUE THREAD

**Issue by wuede** [home-assistant/frontend#8609]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I save a script in the frontend HA automatically breaks long lines. In my case I am testing for a certain string inside a wait template. Due to the length of the template code HA adds a line break in the middle of this quoted string. With the added line break the test fails.

### Describe the behavior you expected

HA should not break the lines inside of quoted strings.

### Steps to reproduce the issue

1. Add a script using the cmd
```
cat <<EOT >> /config/scripts.yaml
test_script:
  alias: test script
  sequence:
  - wait_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status != ''Segment cleaning'' }}'
    timeout: 00:30:00
  mode: single
EOT
```

2. Edit the script in the HA Frontend
3. Check the contents of the file /config/scripts.yaml

```
cat /config/scripts.yaml
some_script:
  alias: test script
  sequence:
  - wait_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status != ''Segment
      cleaning'' }}'
    timeout: 00:30:00
  mode: single
```

### What version of Home Assistant Core has the issue?

core-2021.3.3

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```
