### ISSUE TITLE
Templates not supported in visual editor

### ISSUE THREAD

**Issue by knallt** [home-assistant/frontend#8624]
### The problem

I have serval automations with conditioned actions containing templates. 
With the new UI for service calls these actions are not supported anymore by the editor and, even they worked perfect before, they don't work anymore. 
The Interface says:

"Visual editor is not supported for this configuration:
Templates not supported in visual editorYou can still edit your config in YAML."

... for an action that was created with the old editor and that worked before. 

### What is version of Home Assistant Core has the issue?

core-2021.3.3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Link to integration documentation on our website

https://www.home-assistant.io/docs/automation

### Example YAML snippet

```yaml
choose:
  - conditions:
      - condition: state
        entity_id: media_player.wohnzimmer
        state: playing
    sequence:
      - service: sonos.join
        data:
          master: media_player.wohnzimmer
        entity_id: media_player.bad
      - service: mqtt.publish
        data:
          topic: epaper-displays/display1/music
          payload: '{{ states.media_player.gastebad.attributes.media_title }}'
  - conditions:
      - condition: state
        entity_id: media_player.wohnzimmer
        state: paused
    sequence:
      - service: sonos.unjoin
        data: {}
        entity_id: media_player.bad
      - service: media_player.select_source
        data:
          source: '{{ states.input_select.radio_station.state }}'
        entity_id: media_player.bad
      - service: mqtt.publish
        data:
          topic: epaper-displays/display1/music
          payload: '{{ states.input_select.radio_station.state }}'
default: []

```

### Anything in the logs that might be useful for us?

```txt
# Put your logs below this line

```

Have the same issue for more complex automations. Any idea?
