### ISSUE TITLE
Thermostat Card Button Spacing Not Dynamic

### ISSUE THREAD

**Issue by EnochPrime** [home-assistant/frontend#8627]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The thermostat card displays buttons for the operations modes (heat, cool, off). No matter the width of the dashboard display the buttons remain a fixed distance apart. This can result in one button moving to a second row when the thermostat card, with all three buttons, is placed in a horizontal stack and viewed from a narrow display.

### Describe the behavior you expected

The spacing between the icons should dynamically adjust based on the display width so that all three button remain on one row.

### Steps to reproduce the issue

1. Add thermostat device with both heat and cool operations modes
2. Add thermostat card to Lovelace dashboard within a horizontal stack
3. Resize browser window to be narrow

### What version of Home Assistant Core has the issue?

core-2021.3.4

### In which browser are you experiencing the issue with?

Brave Version 1.21.74; Chromium: 89.0.4389.72 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux Mint 20.1 Cinnamon

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
cards:
  - entity: climate.honeywell_t6_pro_29174
    name: Upstairs
    type: thermostat
  - entity: climate.honeywell_t6_pro_03986
    name: Downstairs
    type: thermostat
type: horizontal-stack
```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

This was originally discovered using the mobile app, but I was able to reproduce the scenario with the web browser.

![Screenshot from 2021-03-12 23-55-59](https://user-images.githubusercontent.com/1175190/111019627-8aab2a00-838e-11eb-87c9-821999ca7893.png)
