### ISSUE TITLE
Generic camera streaming continues even when stopped

### ISSUE THREAD

**Issue by millallo** [home-assistant/frontend#8630]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a simple generic camera showed with the picture-glance card. When I start streaming, jpeg traffic starts but it doesn't stop when I close the streaming window, traffic continues to go on. Only a refresh of browser stops it.

### Describe the behavior you expected

when I close the camera window, jpeg traffic should stop.

### Steps to reproduce the issue

1. Click on the camera icon at the bottom center of the picture-glance card.
2. See jpeg stream on the new window
2. Close the window
3. Traffic continues

### What version of Home Assistant Core has the issue?

core-2021.3.2

### In which browser are you experiencing the issue with?

Firefox >80, Safari >14

### State of relevant entities

Configuration:
```yaml
camera:
  - platform: generic
    name: Telecamera
    still_image_url: http://192.168.x.y/tmpfs/snap.jpg
    username: xxx
    password: xxx
    framerate: 2
    verify_ssl: false
```

State:
```yaml
state: idle
access_token: c621e2934f23e4390c2eeec9f8eacffa8fa304ebb2cff1045bb73c896ab3cd54
friendly_name: Telecamera
entity_picture: >-
  /api/camera_proxy/camera.telecamera?token=c621e2934f23e4390c2eeec9f8eacffa8fa304ebb2cff1045bb73c896ab3cd54
supported_features: 0
```

### Problem-relevant frontend configuration

```yaml
type: picture-glance
title: Telecamera
entities:
  - entity: camera.telecamera
tap_action:
  action: navigate
camera_image: camera.telecamera
```

### Javascript errors shown in your browser console/inspector

No errors and no logs

This is the network monitor widget that suggests me to open this issue :)
![Screen Shot 2021-03-13 at 15 45 38](https://user-images.githubusercontent.com/1112565/111034770-73fce580-8417-11eb-979d-ae5f8615b64b.png)
