### ISSUE TITLE
Cannot create a valid condition using an input_select and multiple options in the Automation editor

### ISSUE THREAD

**Issue by jeffjumper** [home-assistant/frontend#8666]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The automations editor does not create valid yaml syntax for conditions containing multiple options in an input_select. I wrote the yaml by hand using both methods shown below in the "behavior you expected" (one line and multiple lines) and the automation worked correctly. In both cases when I opened it in the editor and saved it, it put all the options on one line but without the square brackets--like this:

```yaml
- id: '1615916936190'
  alias: Test Automation
  trigger:
  - platform: state
    entity_id: input_boolean.test
  condition:
  - condition: state
    entity_id: input_select.test
    state: option1,option2,option3
  action:
  - service: notify.notify
    data:
      title: Test
      message: It worked!
  mode: single
```

If I attempt to add the brackets myself in the field in the UI, it then saves it as a string which also doesn't work:

```yaml
- id: '1615916936190'
  alias: Test Automation
  trigger:
  - platform: state
    entity_id: input_boolean.test
  condition:
  - condition: state
    entity_id: input_select.test
    state: '[option1,option2,option3]'
  action:
  - service: notify.notify
    data:
      title: Test
      message: It worked!
  mode: single
```

### Describe the behavior you expected

I expect the editor to create one of these valid conditions in the automations.yaml :

```yaml
  - condition: state
    entity_id: input_select.test
    state: 
      - option1
      - option2
      - option3
```

```yaml
  - condition: state
    entity_id: input_select.test
    state: [option1,option2,option3]
```

### Steps to reproduce the issue

Use the automation editor in the UI to create a condition in an automation for an input_select that tests for multiple options as shown in the yaml above.

### What version of Home Assistant Core has the issue?

core-2021.3.4

### In which browser are you experiencing the issue with?

Chrome and Safari

### Which operating system are you using to run this browser?

Windows 10 and Big Sur

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

Originally submitted this bug to core as #48002 but I will close that one.
