### ISSUE TITLE
Source list not showing up in an universal media_player

### ISSUE THREAD

**Issue by jiquem** [home-assistant/frontend#8673]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,

I have some universal media_player used to select some action to perform in Apple HomeKit.
Unfortunatelly since a few time the list of source doesn't show anymore in Home Assistant (and therefore in Homekit)
It's quite strange because it was working fine... and then stopped.
 

### Describe the behavior you expected

Display the list of source

### Steps to reproduce the issue

Here is my configuration

1. Create the media player in configuration.yaml

```
media_player:
  - platform: universal
    name: Chauffage 
    commands:
      turn_on:
        service: input_select.select_option 
        entity_id: input_select.chauffage 
        data:
          option: Normal
      turn_off:
        service: input_select.select_option 
        entity_id: input_select.chauffage 
        data:
          option: Eté
      select_source:
        service: input_select.select_option
        data_template:
          entity_id: input_select.chauffage
          option: >-
            {% if source == 'Normal' %}
              Normal 
            {% elif source == 'Confinement' %}
              Confinement
            {% elif source == 'Visite' %}
              Visite 
            {% elif source == 'Présent' %}
              Présent
            {% elif source == 'Télétravail' %}
              Télétravail
            {% elif source == 'Absence longue' %}
              Absence longue
            {% elif source == 'Absence courte' %}
              Absence courte
            {% elif source == 'Eté' %}
              Eté
            {% else %}
              Normal 
            {% endif %}
    attributes:
      state: input_boolean.homekit_chauffage
      source: input_select.chauffage
```

2. Specify the entry  in input_select.yaml

```
chauffage:
  name: Etats du Chauffage
  icon: mdi:home-minus
  options:
   - Normal
   - Confinement
   - Visite
   - Présent
   - Télétravail
   - Absence courte
   - Absence longue
   - Eté 
```

3. And last in in customize.yaml

```
chauffage:
  name: Etats du Chauffage
  icon: mdi:home-minus
  options:
   - Normal
   - Confinement
   - Visite
   - Présent
   - Télétravail
   - Absence courte
   - Absence longue
   - Eté 
```

4. Restart
5. Add the media player card

result is provided in attached screenshots

### What version of Home Assistant Core has the issue?

core-2021.3.4

### State of relevant entities

```yaml
is_volume_muted: false
source: Confinement
friendly_name: Chauffage
supported_features: 384
source_list:
  - Normal
  - Visite
  - Présent
  - Télétravail
  - Absence courte
  - Absence longue
  - Confinement
  - Eté
device_class: tv

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

<img width="330" alt="Capture d’écran 2021-03-19 à 14 30 42" src="https://user-images.githubusercontent.com/1716813/111787965-df373380-88bf-11eb-9c88-8640bb3c78ec.png">
<img width="425" alt="Capture d’écran 2021-03-19 à 14 30 27" src="https://user-images.githubusercontent.com/1716813/111787969-dfcfca00-88bf-11eb-88d4-eddc84ba8eaa.png">
