### ISSUE TITLE
Lines on graphs are rendered wrong

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#8709]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I use an input_number for an automation to set the desired temperature in a room. I have a graph that renders this value and the actual room temperature.

I just changed the input_number half a degree lower than before, but the graph now shows a negative slope of the desired temperature over the length of the whole graph - which is obviously wrong. 

### Describe the behavior you expected

The line should be horizontal until it's changed, fall 90° for 0.5°C, and be horizontal again afterward.

### Steps to reproduce the issue

1. Create a graph
2. Have a value static for a long period of time
3. Change the value
4. See a sloping graph between both points
...

### What version of Home Assistant Core has the issue?

core-2021.3.4

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Chromium: 89.0.4389.90 / Firefox 86.0

### Which operating system are you using to run this browser?

ArchLinux

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sun.sun
  - entity: binary_sensor.window_sensor_bedroom_contact
  - entity: sensor.temp_sensor_bedroom_temperature
  - entity: sensor.radiator_valve_bedroom_position
  - entity: binary_sensor.door_bedroom_contact
  - entity: input_number.target_temp_bedroom
hours_to_show: 72
refresh_interval: 3600
```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

![Screenshot_20210324_164136-1](https://user-images.githubusercontent.com/614929/112342173-4be86e80-8cc2-11eb-9892-7079c035f226.png)
