### ISSUE TITLE
Generic camera connection lost with grey image and broken image symbol

### ISSUE THREAD

**Issue by str2der** [home-assistant/frontend#8727]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Up until a few weeks ago all my generic cameras have been working flawlessly. Now they work (in overview and Lovelace) after a restart of HA, but after about a day, they all turn grey with a broken image symbol. Changing to FFMPEG works, but some of my cameras doesn't support FFMPEG.

I have checked the logs and can't find anything camera related.

### Describe the behavior you expected

I expect the images to show up both in the overview and in Lovelace.

### Steps to reproduce the issue

1. Add cameras as generic camera to Configuration.yaml
2. Re-start HA
3. Wait 24-48 hours.
...

### What version of Home Assistant Core has the issue?

core-2021.3.4

### In which browser are you experiencing the issue with?

89.0.4389.90 (Official Build) (64-bit), Fully kiosk browser (latest version) and HA app (latest version)

### Which operating system are you using to run this browser?

Windows 10 business 20H2, Android 11, Android 9, Android 8.

### State of relevant entities

```yaml
camera:
  - platform: generic
    still_image_url: http://192.168.1.42:8080/photo.jpg
    username: username
    password: password
    name: Hall kamera

```

### Problem-relevant frontend configuration

```yaml
      - type: picture-glance
        image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
        entities:
          - entity: binary_sensor.hall_rorelsesensor_occupancy
          - entity: light.hall_takspottar_level
        camera_image: camera.hall_kamera

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```
