### ISSUE TITLE
Lack of new lines clutters attributes view

### ISSUE THREAD

**Issue by agneevX** [home-assistant/frontend#8733]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It's very hard to discern between JSON arrays when there is no new line between each object. 

### Describe the behavior you expected

There should be a new line after every JSON array.

Just to be clear, there should not be a new line after each object, just after an array.

### Steps to reproduce the issue

1. Open the entity details menu for any entity that has nested attributes
2. Observe how cluttered it looks, especially when objects in the array have items in common.

### What version of Home Assistant Core has the issue?

2021.3.3

### State of relevant entities

```yaml
status:
  uptime: 0d 5h 59m
backhaul:
  status: online
  speed: 1733M
WAN:
  status: up
  uptime: 0d 5h 59m
  port0: 100M/Full
LAN:
  port1: 1000M/Full
  port2: 1000M/Full
  port3: Link down
friendly_name: Orbi Router
icon: 'mdi:router-wireless'
```

I'd like there to be a new line after `Status`, then again after the last item of `Backhaul`, for example.

<img src="https://user-images.githubusercontent.com/19761269/112717363-29e52b00-8f12-11eb-8885-f570dac84a58.png" width="320">
