### ISSUE TITLE
Automation trace: Incorrect handling of condition errors

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/frontend#8756]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The rendering breaks with the attached trace as the condition raised an error that the frontend does not handle yet.

### Describe the behavior you expected

Trace to render and to show the condition error message in the step details.

### Steps to reproduce the issue

1. Load attached trace

### What version of Home Assistant Core has the issue?

Latest dev / beta

### In which browser are you experiencing the issue with?

FF

### State of relevant entities

```yaml
{
  "trace": {
    "last_step": "condition/0/entity_id/0",
    "run_id": "0",
    "state": "stopped",
    "timestamp": {
      "start": "2021-03-30T08:14:57.117343+00:00",
      "finish": "2021-03-30T08:14:57.121619+00:00"
    },
    "domain": "automation",
    "item_id": "1611779304720",
    "trigger": "Home Assistant starting",
    "trace": {
      "trigger": [
        {
          "path": "trigger",
          "timestamp": "2021-03-30T08:14:57.117621+00:00",
          "changed_variables": {
            "trigger": {
              "platform": "homeassistant",
              "event": "start",
              "description": "Home Assistant starting"
            }
          }
        }
      ],
      "condition/0": [
        {
          "path": "condition/0",
          "timestamp": "2021-03-30T08:14:57.117982+00:00",
          "error": "In 'numeric_state':\n  In 'numeric_state' condition: attribute 'brightness' (of entity light.office_ceiling) does not exist"
        }
      ],
      "condition/0/entity_id/0": [
        {
          "path": "condition/0/entity_id/0",
          "timestamp": "2021-03-30T08:14:57.118596+00:00",
          "error": "In 'numeric_state' condition: attribute 'brightness' (of entity light.office_ceiling) does not exist"
        }
      ]
    },
    "config": {
      "id": "1611779304720",
      "alias": "Issue 8201 (Numeric state condition)",
      "description": "",
      "trigger": [
        {
          "platform": "homeassistant",
          "event": "start"
        }
      ],
      "condition": [
        {
          "condition": "numeric_state",
          "attribute": "brightness",
          "above": "50",
          "value_template": "{{ (state.attributes.brightness / 255 * 100) | round(0) }}",
          "entity_id": "light.office_ceiling"
        }
      ],
      "action": [
        {
          "event": "test.test789",
          "event_data": {}
        }
      ],
      "mode": "single"
    },
    "context": {
      "id": "71342ac419309b676573e6274239d904",
      "parent_id": null,
      "user_id": null
    }
  },
  "logbookEntries": []
}

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
script-to-graph.ts:407
Uncaught (in promise) TypeError: conditionResult[0].result is undefined
    _createConditionNode script-to-graph.ts:407
    _renderTraceHead script-to-graph.ts:145
    _renderTraceHead script-to-graph.ts:145
    ActionHandler script-to-graph.ts:94
    result memoize-one.esm.js:30
    createGraph script-to-graph.ts:105
    value hat-script-graph.ts:139
    result memoize-one.esm.js:30
    getTrackedNodes hat-script-graph.ts:111
    render ha-automation-trace.ts:77
    update lit-element.ts:293
    performUpdate updating-element.ts:774
    _enqueueUpdate updating-element.ts:724
    requestUpdateInternal updating-element.ts:689
    set updating-element.ts:371
    updatePageEl ha-config-automation.ts:72
    update hass-router-page.ts:88
    performUpdate updating-element.ts:774
    _enqueueUpdate updating-element.ts:724
    requestUpdateInternal updating-element.ts:689
    set updating-element.ts:371
    updatePageEl ha-panel-config.ts:387
    update hass-router-page.ts:88
    performUpdate updating-element.ts:774
    _enqueueUpdate updating-element.ts:724
    requestUpdateInternal updating-element.ts:689
    set updating-element.ts:371
    updatePageEl partial-panel-resolver.ts:110
    update hass-router-page.ts:88
    performUpdate updating-element.ts:774
    _enqueueUpdate updating-element.ts:724
    requestUpdateInternal updating-element.ts:689
    set updating-element.ts:371
    commit parts.ts:443
    commit parts.ts:153
    update template-instance.ts:49
    __commitTemplateResult parts.ts:291
    commit parts.ts:241
    render render.ts:51
    render shady-render.ts:276
    update lit-element.ts:297
    performUpdate updating-element.ts:774
    _enqueueUpdate updating-element.ts:724
    requestUpdateInternal updating-element.ts:689
    set updating-element.ts:371
    commit parts.ts:443

```
