### ISSUE TITLE
group more-info shows toggle on group with binary entities only

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8799]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

as title, having a group consisting of only binary_sensors, the more-info show a non functional toggle

### Describe the behavior you expected

no toggle when none of the entities it togglable

### Steps to reproduce the issue

1. click entity
2.
3.
...

### What version of Home Assistant Core has the issue?

up to 2021.4.0b02

### In which browser are you experiencing the issue with?

all

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.
type: entity
entity: group.doors_open
name: Doors open
```

and group:
```
group:
 Doors open:
   - binary_sensor.back_door_is_open
   - binary_sensor.corridor_door_is_open
   - binary_sensor.front_door_is_open
   - etcetc
 ```
or 
```
group:
 doors_open:
   name: Doors open
   entities:
     - binary_sensor.back_door_is_open
     - binary_sensor.corridor_door_is_open
     - binary_sensor.front_door_is_open
```
### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

<img width="507" alt="Schermafbeelding 2021-04-02 om 10 36 31" src="https://user-images.githubusercontent.com/33354141/113398709-516b4600-939f-11eb-8911-3de006c8901a.png">

<img width="395" alt="Schermafbeelding 2021-04-02 om 10 32 21" src="https://user-images.githubusercontent.com/33354141/113398651-3bf61c00-939f-11eb-89ca-3a651f3b6a17.png">
