### ISSUE TITLE
UI Editor does not allow saving with exclamation marks

### ISSUE THREAD

**Issue by echoromeo** [home-assistant/frontend#8805]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding a !secret to an automation or script it does not get saved

### Describe the behavior you expected

The secret should get saved, or I should get a warning explaining why it does not work

### Steps to reproduce the issue

1. Add this service to an automation (in UI or YAML editor) and save it
```
action:
  - service: xiaomi_aqara.play_ringtone
    data:
      ringtone_id: 7
      ringtone_vol: 8
      gw_mac: secret xiaomi_mac
```
2. Now add the exclamation mark before the secret
```
action:
  - service: xiaomi_aqara.play_ringtone
    data:
      ringtone_id: 7
      ringtone_vol: 8
      gw_mac: !secret xiaomi_mac
```
3. Now I get a red line along the edge of the editor and the save button does not appear

### What version of Home Assistant Core has the issue?

core-2021.3.4

### In which browser are you experiencing the issue with?

Google Chrome Version 89.0.4389.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro 1909 build 18363.1441

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

Screenshot of how the Editor looks after adding the exclamation mark to !secrets:
![image](https://user-images.githubusercontent.com/374680/113476953-43d0c180-946e-11eb-84d3-d6fd3ac94fe7.png)
