### ISSUE TITLE
Tooltip on picture-glance entity formatted unevenly

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8818]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

the tooltip on an individual entity in the picture glance card is very uneven, almost as if it is aligned to the right

### Describe the behavior you expected

show a more evenly aligned tooltip

### Steps to reproduce the issue

1. Create card with below yaml
2. Hove mouse on entity in the bottom entities placeholder box
3.
...

### What version of Home Assistant Core has the issue?

2021.4.0b4

### What was the last working version of Home Assistant Core?

??

### In which browser are you experiencing the issue with?

Any browser really

### Which operating system are you using to run this browser?

Mac Big Surr 11.2.2

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.
  - type: picture-glance
    title: Vijverpompen
    image: /local/images/vijver.png
    state_filter:
      'off': grayscale(72%)
    entity: binary_sensor.vijverpompen
    entities:
      - switch.vijverpomp_links
      - switch.vijverpomp_rechts
      - input_boolean.vijverpompen_alterneren
      - sensor.pond_buiten_sensor_calibrated_temperature
      - binary_sensor.vijverpompen
      - sensor.vijverpompen
```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

tooltip on the thermometer icon:

<img width="437" alt="Schermafbeelding 2021-04-06 om 11 23 18" src="https://user-images.githubusercontent.com/33354141/113689716-e9806c80-96ca-11eb-8679-a523d6829819.png">

on the binary:

<img width="436" alt="Schermafbeelding 2021-04-06 om 11 26 42" src="https://user-images.githubusercontent.com/33354141/113689809-ff8e2d00-96ca-11eb-8e2e-1a2b5bb571ec.png">
