### ISSUE TITLE
Can't reorder actions in template-based automations in GUI editor

### ISSUE THREAD

**Issue by dgtal1** [home-assistant/frontend#8825]
## The problem

I am not able to reorder actions in some automations. I guess this only happens to the ones that have actions with jinja templates, not supported by GUI editor. I understand GUI support for editing it may be missing, but such thing as reordering actions should work in my opinion. It does look like a bug now. But not sure, maybe is intended.

## Environment

HA Core 2021.1.5 in docker

- Home Assistant Core release with the issue: 2021.1.5
- Last working Home Assistant Core release (if known): never?
- Operating environment (OS/Container/Supervised/Core): Core/Container
- Integration causing this issue: automation
- Link to integration documentation on our website: https://www.home-assistant.io/docs/automation/

## Problem-relevant `configuration.yaml`

```yaml
- id: '1598295584467'
  alias: 'Zniornik 70% powiadomienie'
  description: ''
  trigger:
  - entity_id: binary_sensor.zbiornik
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      value: '{% set days = (as_timestamp(now()) - states.input_datetime.wypompowane.attributes.timestamp)/60/60/24
        %} {% set p_day = 70 / days %} {% set d_remain = 30 / p_day %} {{d_remain|round(method=''floor'')|int}}

        '
    entity_id: input_number.prognoza_pozostalo_dni
    service: input_number.set_value
  - data_template:
      data:
        channel: Alert
        color: red
        importance: high
        sticky: 'true'
      message: Zbiornik pełny w 70%! Pozostało {{states.input_number.prognoza_pozostalo_dni.state|int}}
        dni
    service: notify.notify
  - data_template:
      message: Zbiornik pełny w 70%! Pozostało {{states.input_number.prognoza_pozostalo_dni.state|int}}
        dni
    service: persistent_notification.create
  mode: single
```

## Traceback/Error logs

```txt

```
