### ISSUE TITLE
incorrect paintig of svg picture in picture card or picture glance card

### ISSUE THREAD

**Issue by Pirol62** [home-assistant/frontend#8828]
## 
I integrated an svg picture from YR.NO via camera integration.
````
camera:
  - platform: generic
    name: Weather
    still_image_url: https://www.yr.no/place/Germany/Nordrhein-Westfalen/Meerbusch/meteogram.svg
    content_type: "image/svg+xml"
````
The problem is, that the temperature graph isn't painted regardless if I set the camera entity in the picture glance card or the link in the picture card.
![image](https://user-images.githubusercontent.com/48820003/104178021-fd893a80-5409-11eb-93b2-2544f90e1a2d.png)

this is the picture when I open the same link via chrome browser:
![image](https://user-images.githubusercontent.com/48820003/104178167-2ad5e880-540a-11eb-8f74-34db12a16f3d.png)

## Environment

- Home Assistant Core release with the issue: 2021.01.1
- Last working Home Assistant Core release (if known): it started around 0.116.x
- Operating environment (OS/Container/Supervised/Core): Hass.io with Hass OS 3.11
- Integration causing this issue: ?
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml picture card config
aspect_ratio: 55%
entities: []
hold_action:
  action: none
image: 'https://www.yr.no/place/Germany/Nordrhein-Westfalen/Meerbusch/meteogram.svg'
tap_action:
  action: none
type: picture-glance

```

## Traceback/Error logs

```txt

```
