### ISSUE TITLE
target templates disappeared from service call to notify.alexa_media

### ISSUE THREAD

**Issue by DLThompson06** [home-assistant/frontend#8835]
### The problem

I have several automations that execute a service call to notify.alexa_media.  I use a template for the target {{states('input_select.which_echo')}}.  Previously this information was stored in the service data field, but after the update, the target information disappeared.  Entering it back in works temporarily (manually executing the automation while it's still on screen) but once I save and close the automation, it reverts the target back to '[object Object]': null, rendering all of these automations useless.  Note:  I created all of my automations using the UI, if that matters. 

### What is version of Home Assistant Core has the issue?

2021.3

### What was the last working version of Home Assistant Core?

2021.2.3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Example YAML snippet

```yaml
      - service: notify.alexa_media
        data:
          message: The washing machine just finished its load.
          data:
            entity_id: {{ states('input_select.which_echo') }}
            type: tts
```

### Anything in the logs that might be useful for us?

```txt
# Put your logs below this line

```
