### ISSUE TITLE
Uncaught TypeError: Cannot read property 'timestamp' of undefined when trying to use traces

### ISSUE THREAD

**Issue by fufs** [home-assistant/frontend#8857]
### The problem

I'm trying to use the new traces feature to debug automations, however, I keep getting 
`http://rpi-server.rye/frontend_latest/chunk.e4629a3bb43aafd111cb.js:849:2274 Uncaught TypeError: Cannot read property 'timestamp' of undefined`

### What is version of Home Assistant Core has the issue?

2021.4.0

### What was the last working version of Home Assistant Core?

-

### What type of installation are you running?

Home Assistant Supervised

### Anything in the logs that might be useful for us?

```txt
http://rpi-server.rye/frontend_latest/chunk.e4629a3bb43aafd111cb.js:849:2274 Uncaught TypeError: Cannot read property 'timestamp' of undefined
```

**Comment by spacegaier** [comment]
Please download and attached the trace to this ticket.

**Comment by fufs** [comment]
That's the thing. When I click download it does nothing (screen remains blank) and I get that error in the logs.

**Comment by spacegaier** [comment]
Then it would be good if those important details were in the issue description 😉.

Without having a trace this will be more tricky to investigate. Can you please add your automation YAML. That might give some ideas where something might go wrong with the trace.

**Comment by bramkragten** [comment]
Are there errors in your ha core log?

**Comment by fufs** [comment]
It happens with every automation. Here is a example automation:
```yaml
alias: Home Assistant - Set theme based on time of day
description: >-
  Set light theme after sunrise and dark theme after sunset. You must set
  "backend-selected" theme in the profile settings for it to work.
trigger:
  - platform: sun
    event: sunrise
  - platform: sun
    event: sunset
  - platform: homeassistant
    event: start
condition: []
action:
  - service: frontend.set_theme
    data:
      name: |-
        {% if is_state('sun.sun','above_horizon') %}
          hassio-light
        {% else %}
          hassio-dark
        {% endif %}
mode: single
```
There are no other errors related in anyway to automations than the one I gave.
