### ISSUE TITLE
batteries device_class are not grouped

### ISSUE THREAD

**Issue by antoweb** [home-assistant/frontend#8858]
### The problem

If I insert a device_class of type battery in a group it is not displayed. If I change the device_class to current for example it is displayed correctly

### What is version of Home Assistant Core has the issue?

core-2021.4.0

### What was the last working version of Home Assistant Core?

Never

### What type of installation are you running?

Home Assistant OS

### Link to integration documentation on our website

https://www.home-assistant.io/docs/configuration/customizing-devices/

### Example YAML snippet

```yaml
camera:
    name: Camera
    entities:
      - sensor.ble_battery_XXXXXXXXXXX
```
