### ISSUE TITLE
Debugging doesn't work: no traces found

### ISSUE THREAD

**Issue by azrael783** [home-assistant/frontend#8862]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Trying to use the new debugging feature but this is not working for me. I only see "no traces found". I have added a unique ID to all of my automation files (I have them separated), but this doesn't help. It is also not working for some automation stored in the `automations.yaml`. I am also seeing one automation several time, but it is only stored once in a file. 

![grafik](https://user-images.githubusercontent.com/44697375/114082687-53a53700-98ae-11eb-94c4-e0d908f835e1.png)

This is the code for this automation stored in a separate file:
```yml
- id: 21f6c6c6-f77a-4d7c-8583-4adbe526d462
  alias: Alarmierung Tür / Fenster noch offen
  trigger:
  - entity_id: person.daniel_2
    from: home
    platform: state
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.anne_2
      state: not_home
    - condition: state
      entity_id: group.contacts
      state: 'on'
  action:
  - service: notify.telegram
    data_template:
      message: Hallo, da ist noch was offen! {{ states | selectattr('entity_id','in',
        state_attr('group.contacts','entity_id')) | selectattr('state','eq','on') | map(attribute='name') | join(', ') }}
      data:
        inline_keyboard:
        - Rollläden steuern:/rollo_steuerung
        - Aus:/removekeyboard
```
This is an automation stored in `automations.yaml` where the debugging is also not working:
```yml
- id: aussenlicht_an
  alias: Außenlicht an, wenn dunkel
  trigger:
  - entity_id: person.daniel_2
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - entity_id: light.garage
    service: homeassistant.turn_on
  mode: single
```

### Describe the behavior you expected

Debugging feature is working.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.4.0

### In which browser are you experiencing the issue with?

Firefox 78.0 and Edge 89.0.774.68

### Which operating system are you using to run this browser?

Windows 10 Pro

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```
