### ISSUE TITLE
Restoring from background gets stuck with 'Connection lost. Reconnecting…' for 10 seconds

### ISSUE THREAD

**Issue by balu79** [home-assistant/frontend#8893]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Whenever I use the HA Companion Anroid app after more than 30 minutes it takes long time to connect (around 10 seconds). When I use the app again within an about 30 minutes time frame, it only takes 1-2 seconds to connect / load. This issue is not observed in Google Chrome on the same phone and neither in the iOS Companion App on an iPad.
At the end of the loading process (so after around 10 seconds) a pop up is displayed and disappears immidiately / in an instant. The error message is: Unable to connect to Home Assistant - There was an error loading Home Assistant, please review the connection settings and try again.

Initially filed an issue in home-assistant / android (https://github.com/home-assistant/android/issues/1498) but was advised that this is not an issue of the Android app itself but rather that the disconnecting message showed up because the frontend was disconnected and that I hence should open a frontend issue for this.

Tried different things by now:
- Clean cache and data of the Android app
- Uninstall and re-install the Android app
- Cleared cache of Chrome Browser
- Deactivated lite / data saver mode in Chrome
- Checked that Android System WebView was up to date
- Restarted phone and Home Assistant
- Enabled and disabled the "Automatically close connection" setting

### Describe the behavior you expected

App loaded immidiately / with max 1-2 seconds delay and no "Unable to connect" error message

### Steps to reproduce the issue

1. Start Home Assistant Andoird app and let it connect
2. Go to other Android apps and / or lock the phone.
3. After more than 30 minutes start Home Assistant app / bring it to foreground

### What version of Home Assistant Core has the issue?

core-2021.4.1

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Issue is not observed in any browser

### Which operating system are you using to run this browser?

Android version 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```
title: Home
views:
  - path: default_view
    title: Home
    icon: 'mdi:home-assistant'
    badges:
      - entity: person.bastian
      - entity: person.vivian
      - entity: group.family
        name: Family
      - entity: sensor.lk_rhein_kreis_neuss_weekincidence
        name: RKI
    cards:
      - entities:
          - entity: switch.pump
            name: Pumpe
            icon: 'mdi:fountain'
            tap_action:
              action: toggle
          - entity: switch.printer
            name: Printer
            icon: 'mdi:printer'
            tap_action:
              action: toggle
          - entity: switch.tv
            name: TV
            icon: 'mdi:television'
            tap_action:
              action: toggle
          - entity: switch.avr
            name: AVR
            icon: 'mdi:audio-video'
            tap_action:
              action: toggle
          - entity: switch.cam_garage
            name: Garage
            icon: 'mdi:cctv'
            tap_action:
              action: toggle
          - entity: switch.socket_portable_1
            name: X-Mas
            icon: 'mdi:ferris-wheel'
            tap_action:
              action: toggle
          - entity: switch.socket_portable_2
            name: PC
            icon: 'mdi:laptop'
            tap_action:
              action: toggle
        show_name: true
        show_state: false
        type: glance
      - entities:
          - entity: light.read_b
            name: Read B
            icon: 'mdi:track-light'
            tap_action:
              action: toggle
          - entity: light.read_v
            name: Read V
            icon: 'mdi:track-light'
            tap_action:
              action: toggle
          - entity: light.lights_sleep
            name: Sleep
            icon: 'mdi:floor-lamp'
            tap_action:
              action: toggle
          - entity: light.light_sleep_moonlight
            name: Moonlight
            icon: 'mdi:lava-lamp'
            tap_action:
              action: toggle
          - entity: switch.light_floor_up
            name: Floor OG
            icon: 'mdi:globe-light'
            tap_action:
              action: toggle
          - entity: switch.star
            name: Star
            icon: 'mdi:star'
            tap_action:
              action: toggle
          - entity: light.phone
            name: Phone
            icon: 'mdi:lamp'
            tap_action:
              action: toggle
          - entity: light.stripe_eat
            name: Eat
            icon: 'mdi:led-strip'
            tap_action:
              action: toggle
          - entity: light.stripe_mario
            name: Mario
            icon: 'mdi:led-strip'
            tap_action:
              action: toggle
          - entity: light.stripe_tv
            name: TV
            icon: 'mdi:led-strip'
            tap_action:
              action: toggle
          - entity: switch.light_entrance
            name: Floor EG
            icon: 'mdi:track-light'
            tap_action:
              action: toggle
          - entity: light.read_m
            name: Maila
            icon: 'mdi:lamp'
            tap_action:
              action: toggle
          - entity: light.ceiling_guestroom
            name: Guestroom
            icon: 'mdi:wall-sconce-round'
            tap_action:
              action: toggle
          - entity: light.light_ceiling_kitchen
            name: Kitchen
            icon: 'mdi:wall-sconce-round'
            tap_action:
              action: toggle
          - entity: light.ceiling_linus_room
            name: Linus Main
            icon: 'mdi:wall-sconce-round'
            tap_action:
              action: toggle
          - entity: light.ceiling_linus_room_ambilight
            name: Linus Ambi
            icon: 'mdi:wall-sconce-flat'
            tap_action:
              action: toggle
          - entity: switch.light_driveway
            name: Driveway
            icon: 'mdi:light-switch'
            tap_action:
              action: toggle
        show_state: false
        type: glance
  - path: alarm
    title: Alarm
    icon: 'mdi:alarm-light'
    badges: []
    cards:
      - type: glance
        entities:
          - entity: binary_sensor.motion_entrance_ias_zone
            name: Entrance
          - entity: binary_sensor.motion_stairs_ias_zone
            name: Stairs
          - entity: binary_sensor.motion_living_room_ias_zone
            name: Living Room
          - entity: binary_sensor.motion_garage_ias_zone
            name: Garage
          - entity: binary_sensor.motion_hwr_ias_zone
            name: HWR
          - entity: binary_sensor.magnet_stairs
            name: Stairs
          - entity: binary_sensor.magnet_entrance
            name: Entrance
          - entity: binary_sensor.vibration_stairs_ias_zone
          - entity: binary_sensor.lumi_lumi_vibration_aq1_ias_zone
      - entity: alarm_control_panel.home_alarm
        type: alarm-panel
  - path: debug
    title: Debug
    icon: 'mdi:android-debug-bridge'
    badges: []
    cards:
      - type: button
        tap_action:
          action: toggle
        entity: input_boolean.testbuttontriggered
      - entity: media_player.living_room
        type: media-control
      - entity: weather.home
        type: weather-forecast
      - type: media-control
        entity: media_player.living_room_tv
      - type: entities
        entities:
          - input_boolean.alarmdetected
      - type: sensor
        entity: sensor.lk_rhein_kreis_neuss_weekincidence
        graph: line
        hours_to_show: 168
      - type: entities
        entities:
          - entity: sensor.lk_rhein_kreis_neuss_weekincidence
          - entity: sensor.lk_rhein_kreis_neuss_newcases
          - entity: sensor.lk_rhein_kreis_neuss_recovered
```

### Javascript errors shown in your browser console/inspector

Log of Android app
```
04-09 20:35:42.333 12698 14436 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"disconnected"},"id":3}
04-09 20:35:42.344 12698 14439 D SensorWorker: Updating all Sensors.
04-09 20:35:42.345 12698 14420 I WM-Processor: Moving WorkSpec (dacb3342-b466-409a-940a-c01e49d91abf) to the foreground
04-09 20:35:42.348 12698 12698 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-09 20:35:42.348 12698 12698 D UrlRepository: Using external URL
04-09 20:35:42.369 12698 12698 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
04-09 20:35:42.431 12698 21468 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-09 20:35:42.431 12698 21468 D UrlRepository: Using external URL
04-09 20:35:42.552 12698 14439 D UrlRepository: localUrl is: false and usesInternalSsid is: false
04-09 20:35:52.916 12698 14421 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=dacb3342-b466-409a-940a-c01e49d91abf, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
04-09 20:35:52.920 12698 12698 I WM-SystemFgDispatcher: Stopping foreground service
04-09 20:35:52.988 12698 14436 D WebviewActivity: External bus {"type":"connection-status","payload":{"event":"connected"},"id":4}
04-09 20:35:52.991 12698 12698 D UrlRepository: localUrl is: false and usesInternalSsid is: false
```

Home Assitant log:
```
2021-04-09 20:35:43 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547233181856] Connected from 79.195.76.244
2021-04-09 20:35:43 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547233181856] Sending {"type": "auth_required", "ha_version": "2021.4.1"}
...
2021-04-09 20:35:52 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547233181856] Received {'type': 'auth', 'access_token':
```
