### ISSUE TITLE
Automation UI broken when Condition Time contains both before and after

### ISSUE THREAD

**Issue by wigster** [home-assistant/frontend#8899]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an automation which contain in a choose action a time condition with both an after and before constraint.

```yaml
  - choose:
      - alias: Turn it on
        conditions:
          - condition: and
            conditions:
              - condition: time
                after: input_datetime.plug_coffee_on
                before: input_datetime.plug_coffee_off
              - condition: state
                entity_id: group.inhabitants
                state: 'on'
```

The before constraint does not appear in the Automation UI:

![image](https://user-images.githubusercontent.com/10956987/114348351-b1fc3f00-9b66-11eb-9ae0-73a3516ab26c.png)

### Describe the behavior you expected

The UI should reflect the conditions are they are defined in the YAML

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.4.3

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Edge v 91, Firefox 87

### Which operating system are you using to run this browser?

Windows 10 21H1

### State of relevant entities

```yaml
# Paste your state here.
input_datetime.plug_coffee_off
editable: true
has_date: false
has_time: true
hour: 16
minute: 0
second: 0
timestamp: 57600
friendly_name: Plug Coffee Off Evening
icon: 'mdi:coffee-maker'


input_datetime.plug_coffee_on
editable: true
has_date: false
has_time: true
hour: 6
minute: 0
second: 0
timestamp: 21600
friendly_name: Plug Coffee On Morning
icon: 'mdi:coffee-maker'
```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.
alias: 'Plug: coffee machine'
description: Switches on coffee machine if during day and someone home
trigger:
  - platform: state
    entity_id: group.inhabitants
  - platform: time
    at: input_datetime.plug_coffee_on
  - platform: time
    at: input_datetime.plug_coffee_off
action:
  - choose:
      - alias: Turn it on
        conditions:
          - condition: and
            conditions:
              - condition: time
                after: input_datetime.plug_coffee_on
                before: input_datetime.plug_coffee_off
              - condition: state
                entity_id: group.inhabitants
                state: 'on'
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.plug_salon_coffee
          - service: notify.persistent_notification
            data:
              title: Coffee switched on
              message: Indeed
  - choose:
      - alias: Turn it off
        conditions:
          - condition: or
            conditions:
              - condition: not
                conditions:
                  - condition: time
                    after: input_datetime.plug_coffee_on
                    before: input_datetime.plug_coffee_off
              - condition: state
                entity_id: group.inhabitants
                state: 'off'
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.plug_salon_coffee
          - service: notify.persistent_notification
            data:
              title: Coffee switched off
              message: Indeed
mode: single

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```
