### ISSUE TITLE
Iframe Panel order

### ISSUE THREAD

**Issue by clemalex824** [home-assistant/frontend#8941]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

[panel_iframe
](https://www.home-assistant.io/integrations/panel_iframe/)

the arrangement, the order is made on the title instead of the name.

### Describe the behavior you expected

the name is not visible and therefore allows to add a prefix to define a command.

The title is displayed in Lovelace and should not contain a prefix to be as simple as possible.

Currently I have several iframe_panel:

```yaml
panel_iframe:
  01_deconz:
    title: "ZigBee"
    url: "https://XXXX"
    require_admin: true
  02_pilight:
    title: "Pilight"
    url: "https://XXXX"
    require_admin: true
  03_configurator:
    title: "Configurator"
    url: "https://XXXX"
    require_admin: true
```

and i got order in sidebar : 
```yaml
configurator
hacs #because title is HACS by default
pilight
deconz
```

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.4.5

### What was the last working version of Home Assistant Core?

never ?

### In which browser are you experiencing the issue with?

chrome, firefox (lastest)

### Which operating system are you using to run this browser?

win10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```
