### ISSUE TITLE
Stop button on cover still actionable when stationary

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8960]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Seems odd we can always see the Stop button as active and even operate is visually, even when the cover is stationary, and state correctly represented as Open/Closed, as seen in the custom slider-entity-row below

Unlike the Up/Down buttons, which are correctly greyed out if applicable.

### Describe the behavior you expected

have the stop button grey out if cover is stationary 

### Steps to reproduce the issue

1. simply add a cover to the card
2. that't it
3.
...

### What version of Home Assistant Core has the issue?

2021.4.6

### What was the last working version of Home Assistant Core?

never?

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### State of relevant entities

```yaml
# Paste your state here.
current_position: 100
entity_id:
  - cover.rolluik_name
  - cover.rolluik_studenten
friendly_name: Dorm
supported_features: 15
device_class: shutter
```
<img width="652" alt="Schermafbeelding 2021-04-21 om 11 40 56" src="https://user-images.githubusercontent.com/33354141/115533069-aca1a180-a296-11eb-8571-bc6e14cc32a1.png">

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.
      - entity: cover.dorm
        secondary_info: last-changed
      - type: custom:slider-entity-row
        entity: cover.dorm
        step: 1
        full_row: true
        hide_state: false
```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

### Additional information
<img width="435" alt="Schermafbeelding 2021-04-21 om 11 34 33" src="https://user-images.githubusercontent.com/33354141/115532280-f1790880-a295-11eb-8740-57ab174e4afb.png">

even showing the circle on hover, indicating it is active:

<img width="438" alt="Schermafbeelding 2021-04-21 om 11 38 25" src="https://user-images.githubusercontent.com/33354141/115532526-2be2a580-a296-11eb-9f85-33694fe055e6.png">
