### ISSUE TITLE
Slow automation editing via web UI

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#8962]
### The problem

Editing automations is now incredibly slow through the web interface / slow to respond to anything, like clicking on the "..." to view the yaml for an action (I suspect since the visual editors were added).
Using the latest version of Chrome

### What is version of Home Assistant Core has the issue?

2021.4.5

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Not Sure

### Example YAML snippet

```yaml
- id: '1576151838601'
  alias: Alert - Doorbell
  description: ''
  trigger:
  - event_data:
      entity_id: binary_sensor.switch_158d0004280083
    event_type: xiaomi_aqara.click
    platform: event
  - event_data:
      entity_id: binary_sensor.switch_158d00044cf7fe
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      gw_mac: 04cf8cf6a54d
      ringtone_id: 11
      ringtone_vol: 100
    service: xiaomi_aqara.play_ringtone
  - data:
      gw_mac: 7811dcb20cae
      ringtone_id: 11
      ringtone_vol: 100
    service: xiaomi_aqara.play_ringtone
  - data:
      brightness_pct: 100
      entity_id: light.gateway_light_04cf8cf6a54d
      rgb_color:
      - 0
      - 0
      - 255
    entity_id: light.gateway_light_04cf8cf6a54d
    service: light.turn_on
  - data:
      brightness_pct: 100
      entity_id: light.gateway_light_7811dcb20cae
      rgb_color:
      - 0
      - 0
      - 255
    entity_id: light.gateway_light_7811dcb20cae
    service: light.turn_on
  - data_template:
      message: '{% if states.sensor.home_members_at_home_count.state|int == 0 %}Someone
        is at the door{% else %}{% endif %}'
    service: notify.notifications_on_synology12_chat
  - delay: 0:0:15
  - data: {}
    entity_id: light.gateway_light_04cf8cf6a54d
    service: light.turn_off
  - data: {}
    entity_id: light.gateway_light_7811dcb20cae
    service: light.turn_off
```
