### ISSUE TITLE
When forcasted templow/temperature is 0 - it only shows ° [card:weather-forecast]

### ISSUE THREAD

**Issue by migo-dev** [home-assistant/frontend#8969]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the forecasted templow/temperature is at exactly 0, the card does not show the 0 - just °

![IMG_0310](https://user-images.githubusercontent.com/57773976/115705454-d7f6c000-a36c-11eb-9292-152b6a047f4d.JPEG)

### Describe the behavior you expected

It should show "0 °" instead of "°".

### Steps to reproduce the issue

1. Developer-tools / states
2. Change forecasted templow/temperature to exactly 0
3. The card should now only show °

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Microsoft Edge (90.0.818.42) & Companion App (2021.4.1/2021.115)

### Which operating system are you using to run this browser?

Windows 10 Pro (20H2) & iOS (14.4.2)

### State of relevant entities

```yaml
temperature: 9.7
humidity: 47
pressure: 1020
wind_bearing: 0
wind_speed: 7.42
attribution: Data provided by OpenWeatherMap
forecast:
  - datetime: '2021-04-22T11:00:00+00:00'
    precipitation: 1.99
    precipitation_probability: 80
    pressure: 1019
    wind_speed: 4.26
    wind_bearing: 35
    condition: rainy
    temperature: 14.7
    templow: 2.6
  - datetime: '2021-04-23T11:00:00+00:00'
    precipitation: 0
    precipitation_probability: 0
    pressure: 1023
    wind_speed: 4.85
    wind_bearing: 49
    condition: sunny
    temperature: 15.2
    templow: -0.7
  - datetime: '2021-04-24T11:00:00+00:00'
    precipitation: 0
    precipitation_probability: 0
    pressure: 1022
    wind_speed: 93
    wind_bearing: 60
    condition: sunny
    temperature: 17.4
    templow: 0
```

### Problem-relevant frontend configuration

```yaml
type: weather-forecast
entity: weather.openweathermap
```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```
