### ISSUE TITLE
Min/Max sensor round_digits - not rounded (reopen)

### ISSUE THREAD

**Issue by Atalonica** [home-assistant/frontend#8972]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the documentation of "min_max" sensor it says:
"round_digits (Optional): Round mean value to specified number of digits. Defaults to 2."
Although mean value (as an attribute) is rounded, the value shown in UI is not.

### Describe the behavior you expected

If round_digits is set to 0, the displayed state (mean) on the lovelace UI should be an integer without any decimal places.

### Steps to reproduce the issue

Add "min_max" sensor with `type: mean` and set `round_digits: 0` (zero)

### What version of Home Assistant Core has the issue?

core-2021.4.6

### What was the last working version of Home Assistant Core?

core-2021.4.6

### In which browser are you experiencing the issue with?

Google Chrome 90.0.4430.85

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```yaml
count_sensors: 4
max_value: 88
max_entity_id: sensor.rfmain3_69cw_9_humi
mean: 76
median: 78
min_value: 61
min_entity_id: sensor.ataene_8_humi
last: 61
last_entity_id: sensor.ataene_8_humi
unit_of_measurement: '%'
friendly_name: casa_bcn_avg_humi
icon: 'mdi:calculator'

```

**Entity state is is 76.0 (not 76)**

### Problem-relevant frontend configuration

```yaml
- platform: min_max
  name: casa_bcn_avg_humi
  type: mean
  round_digits: 0
  entity_ids:
    - sensor.atamult_2_humi
    - sensor.atamult_5_humi
    - sensor.ataene_8_humi
    - sensor.rfmain3_69cw_9_humi
```

### Additional information

Re-opened from [issue 17463](https://github.com/home-assistant/core/issues/17463) since the "error" still persists.

**Comment by spacegaier** [comment]
That rounding parameter only affects the value in the backend. The frontend is not aware of it and is attempting to have a consistent look for all numeric values.

Can you please show your relevant Lovelace config YAML that you use to display the value and also what number format have you selected in your user profile?

**Comment by Atalonica** [comment]
The Lovelace card config is:
```yaml
type: sensor
entity: sensor.casa_bcn_avg_humi
icon: 'hass:water-percent'
name: Pis
```

My number format (auto) is: `1.234.567,89` (but it does display the .0 with other ones)

However with other sensor entities whose state does not have decimals, it appears correct (with same Lovelace card).

In fact, I think, it is the sensor card that does not round to an integer if the state happens have .0 ("123.0"), like min_max state with `round_digits: 0`.
It could be fixed with a feature request of "Sensor card" to be able to round to zero decimal digits.
However the min_max entity state value could actually report an integer if there are no decimal places ".0" at any moment and sensor round to 0 feature wouldn't be necessary for this.
