### ISSUE TITLE
Panel setup lost after browser cache / cookies cleared

### ISSUE THREAD

**Issue by GerdBlomb** [home-assistant/frontend#8975]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I added a few Entries to my docker / core setup in the sidebar panel. When i use a different browser or when i clear the browser savings (cache, cookies etc.) my settings for the panel are gone.

Disabled panel entries are back und the sequence of the list of entries falls back to default.

This setup should be stored internal to so user who is logged in.

### Describe the behavior you expected

No changes to a modfied panel until the user does change it.

### Steps to reproduce the issue

1. Add Panel entires in configuration.yaml (panel_custom and panel_iframe)
2. Arrange the setup in a sequence you like (User settings / edit panel)
3. disable some internal entries from the list. Store.
4. Clear all data from browser (shift-ctrl+del in firefox e.g.) 
5. Close and reopen browser and go to ha frontpage

### What version of Home Assistant Core has the issue?

2021.4.4 on docker

### What was the last working version of Home Assistant Core?

none as far as i know

### Which operating system are you using to run this browser?

firefox 88.0 on Win10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```
includefile panel_custom.yaml

# Server Control
- name: ha_server_con
  sidebar_title: ServerControl
  sidebar_icon: mdi:cog-transfer
  js_url: /api/hassio/app/entrypoint.js
  url_path: 'config/server_control'
  embed_iframe: true
  require_admin: true
  config:
    ingress: core_configurator   

# Integrations
- name: ha_integ
  sidebar_title: Integrations
  sidebar_icon: mdi:chip
  js_url: /api/hassio/app/entrypoint.js
  url_path: 'config/integrations'
  embed_iframe: true
  require_admin: true
  config:
    ingress: core_configurator  

# Automations
- name: ha_auto
  sidebar_title: Automations
  sidebar_icon: mdi:cog-outline
  js_url: /api/hassio/app/entrypoint.js
  url_path: 'config/automation'
  embed_iframe: true
  require_admin: true
  config:
    ingress: core_configurator  



include file iframe_panel.yaml

node_red:
  icon: mdi:resistor-nodes
  title: node RED
  url: 'http://192.168.x.x:1880'
  require_admin: true

daapd:
  icon: mdi:music-box-outline
  title: daapd Server
  url: 'http://192.168.x.x:3689'
  require_admin: true

grafana:
  icon: mdi:graphql
  title: grafana
  url: 'http://192.168.x.x:3000'
  require_admin: true

zigbee:
  icon: mdi:zigbee
  title: Zigbee
  url: 'http://192.168.x.x:1881'
  require_admin: true

influxchrono:
  icon: mdi:database-clock-outline
  title: Influx Admin
  url: 'http://192.168.x.x:8888'
  require_admin: true

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

### Additional information

All user related setup (theme, panel etc. pp.) should be saved in the user entry. This makes sure that the config is available regardless of the browser or device in question.

I fear that some information is stored in cookies or other storage local to / in the browser.

Thanks for your attention and keep up the great work!
