### ISSUE TITLE
Error Rendering automation graph

### ISSUE THREAD

**Issue by Thomas55555** [home-assistant/frontend#9012]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an working automation, but the automation graph renderer says: Error rendering graph. Please download trace and share with the developers. 

### Describe the behavior you expected

Showing a graph

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.4.6

### In which browser are you experiencing the issue with?

Firefox 87.0 and Konqueror 20.08.1

### Which operating system are you using to run this browser?

ubuntu (20.10)

### State of relevant entities

```txt
see trace
```

### Problem-relevant frontend configuration

```yaml
alias: Anwensenheit_nach_oben
id: 2q55t
description: 'Wenn Bewegung Oben, Anwesenheit aktivieren'
trigger:
  platform: state
  entity_id: binary_sensor.bewegungsmelder_treppe_unten
  to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.bewegungsmelder_oben
    state: 'off'
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.presence_oben
      option: anwesend
  - choose:
      conditions:
        - condition: or
          conditions:
            - condition: numeric_state
              entity_id: sensor.lux_oben
              below: 25
            - condition: numeric_state
              entity_id: sun.sun
              value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
              below: '0.0'
      sequence:
        - service: light.turn_on
          data_template:
            entity_id:
              - light.treppe2
            kelvin: >-
              {{ state_attr('switch.adaptive_lighting_treppe',
              'color_temp_kelvin') | int }}
            brightness_pct: >-
              {{ state_attr('switch.adaptive_lighting_treppe', 'brightness_pct')
              | int }}
  - wait_template: '{{ is_state(''binary_sensor.bewegungsmelder_treppe_unten'', ''off'') }}'
  - service: light.turn_off
    data_template:
      entity_id:
        - light.treppe2
  - choose:
      - conditions: '{{ is_state(''binary_sensor.bewegungsmelder_oben'', ''off'') }}'
        sequence:
          - service: input_select.select_option
            data_template:
              entity_id: input_select.presence_oben
              option: abwesend
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

```
{
  "trace": {
    "last_step": "action/4/choose/0/conditions/0",
    "run_id": "242",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2021-04-27T21:58:03.932784+00:00",
      "finish": "2021-04-27T21:59:14.008705+00:00"
    },
    "domain": "automation",
    "item_id": "2q55t",
    "trigger": "state of binary_sensor.bewegungsmelder_treppe_unten",
    "trace": {
      "trigger/0": [
        {
          "path": "trigger/0",
          "timestamp": "2021-04-27T21:58:03.932846+00:00",
          "changed_variables": {
            "trigger": {
              "platform": "state",
              "entity_id": "binary_sensor.bewegungsmelder_treppe_unten",
              "from_state": {
                "entity_id": "binary_sensor.bewegungsmelder_treppe_unten",
                "state": "off",
                "attributes": {
                  "friendly_name": "Bewegungsmelder Treppe unten",
                  "device_class": "motion"
                },
                "last_changed": "2021-04-27T21:55:25.455885+00:00",
                "last_updated": "2021-04-27T21:55:25.455885+00:00",
                "context": {
                  "id": "da40cb438b335f5e7920e9debc55cb2d",
                  "parent_id": null,
                  "user_id": null
                }
              },
              "to_state": {
                "entity_id": "binary_sensor.bewegungsmelder_treppe_unten",
                "state": "on",
                "attributes": {
                  "friendly_name": "Bewegungsmelder Treppe unten",
                  "device_class": "motion"
                },
                "last_changed": "2021-04-27T21:58:03.930282+00:00",
                "last_updated": "2021-04-27T21:58:03.930282+00:00",
                "context": {
                  "id": "e030afeb1b94c800c6ac9a5c444b8b9a",
                  "parent_id": null,
                  "user_id": null
                }
              },
              "for": null,
              "attribute": null,
              "description": "state of binary_sensor.bewegungsmelder_treppe_unten",
              "id": "0"
            }
          }
        }
      ],
      "condition/0": [
        {
          "path": "condition/0",
          "timestamp": "2021-04-27T21:58:03.932875+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "condition/0/entity_id/0": [
        {
          "path": "condition/0/entity_id/0",
          "timestamp": "2021-04-27T21:58:03.932890+00:00",
          "result": {
            "result": true,
            "state": "off",
            "wanted_state": "off"
          }
        }
      ],
      "action/0": [
        {
          "path": "action/0",
          "timestamp": "2021-04-27T21:58:03.934135+00:00",
          "changed_variables": {
            "context": {
              "id": "d32b96602a7e573af4407e1fbe5eaacd",
              "parent_id": "e030afeb1b94c800c6ac9a5c444b8b9a",
              "user_id": null
            }
          },
          "result": {
            "params": {
              "domain": "input_select",
              "service": "select_option",
              "service_data": {
                "entity_id": "input_select.presence_oben",
                "option": "anwesend"
              },
              "target": {}
            },
            "running_script": false,
            "limit": 10
          }
        }
      ],
      "action/1": [
        {
          "path": "action/1",
          "timestamp": "2021-04-27T21:58:03.937488+00:00",
          "result": {
            "choice": 0
          }
        }
      ],
      "action/1/choose/0": [
        {
          "path": "action/1/choose/0",
          "timestamp": "2021-04-27T21:58:03.937622+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "action/1/choose/0/conditions/0": [
        {
          "path": "action/1/choose/0/conditions/0",
          "timestamp": "2021-04-27T21:58:03.937651+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "action/1/choose/0/conditions/0/conditions/0": [
        {
          "path": "action/1/choose/0/conditions/0/conditions/0",
          "timestamp": "2021-04-27T21:58:03.937667+00:00",
          "result": {
            "result": true
          }
        }
      ],
      "action/1/choose/0/conditions/0/conditions/0/entity_id/0": [
        {
          "path": "action/1/choose/0/conditions/0/conditions/0/entity_id/0",
          "timestamp": "2021-04-27T21:58:03.937682+00:00",
          "result": {
            "result": true,
            "state": 17
          }
        }
      ],
      "action/1/choose/0/sequence/0": [
        {
          "path": "action/1/choose/0/sequence/0",
          "timestamp": "2021-04-27T21:58:03.938173+00:00",
          "result": {
            "params": {
              "domain": "light",
              "service": "turn_on",
              "service_data": {
                "entity_id": [
                  "light.treppe2"
                ],
                "kelvin": 2202,
                "brightness_pct": 8
              },
              "target": {}
            },
            "running_script": false,
            "limit": 10
          }
        }
      ],
      "action/2": [
        {
          "path": "action/2",
          "timestamp": "2021-04-27T21:58:04.101120+00:00",
          "result": {
            "wait": {
              "remaining": null,
              "completed": true
            }
          }
        }
      ],
      "action/3": [
        {
          "path": "action/3",
          "timestamp": "2021-04-27T21:59:13.935203+00:00",
          "changed_variables": {
            "wait": {
              "remaining": null,
              "completed": true
            }
          },
          "result": {
            "params": {
              "domain": "light",
              "service": "turn_off",
              "service_data": {
                "entity_id": [
                  "light.treppe2"
                ]
              },
              "target": {}
            },
            "running_script": false,
            "limit": 10
          }
        }
      ],
      "action/4": [
        {
          "path": "action/4",
          "timestamp": "2021-04-27T21:59:14.006719+00:00"
        }
      ],
      "action/4/choose/0": [
        {
          "path": "action/4/choose/0",
          "timestamp": "2021-04-27T21:59:14.006823+00:00",
          "result": {
            "result": false
          }
        }
      ],
      "action/4/choose/0/conditions/0": [
        {
          "path": "action/4/choose/0/conditions/0",
          "timestamp": "2021-04-27T21:59:14.006841+00:00",
          "result": {
            "result": false
          }
        }
      ]
    },
    "config": {
      "alias": "Anwensenheit_nach_oben",
      "id": "2q55t",
      "description": "Wenn Bewegung Oben, Anwesenheit aktivieren",
      "trigger": {
        "platform": "state",
        "entity_id": "binary_sensor.bewegungsmelder_treppe_unten",
        "to": "on"
      },
      "condition": [
        {
          "condition": "state",
          "entity_id": "binary_sensor.bewegungsmelder_oben",
          "state": "off"
        }
      ],
      "action": [
        {
          "service": "input_select.select_option",
          "data_template": {
            "entity_id": "input_select.presence_oben",
            "option": "anwesend"
          }
        },
        {
          "choose": {
            "conditions": [
              {
                "condition": "or",
                "conditions": [
                  {
                    "condition": "numeric_state",
                    "entity_id": "sensor.lux_oben",
                    "below": 25
                  },
                  {
                    "condition": "numeric_state",
                    "entity_id": "sun.sun",
                    "value_template": "{{ state_attr('sun.sun', 'elevation') }}",
                    "below": "0.0"
                  }
                ]
              }
            ],
            "sequence": [
              {
                "service": "light.turn_on",
                "data_template": {
                  "entity_id": [
                    "light.treppe2"
                  ],
                  "kelvin": "{{ state_attr('switch.adaptive_lighting_treppe', 'color_temp_kelvin') | int }}",
                  "brightness_pct": "{{ state_attr('switch.adaptive_lighting_treppe', 'brightness_pct') | int }}"
                }
              }
            ]
          }
        },
        {
          "wait_template": "{{ is_state('binary_sensor.bewegungsmelder_treppe_unten', 'off') }}"
        },
        {
          "service": "light.turn_off",
          "data_template": {
            "entity_id": [
              "light.treppe2"
            ]
          }
        },
        {
          "choose": [
            {
              "conditions": "{{ is_state('binary_sensor.bewegungsmelder_oben', 'off') }}",
              "sequence": [
                {
                  "service": "input_select.select_option",
                  "data_template": {
                    "entity_id": "input_select.presence_oben",
                    "option": "abwesend"
                  }
                }
              ]
            }
          ]
        }
      ]
    },
    "blueprint_inputs": null,
    "context": {
      "id": "d32b96602a7e573af4407e1fbe5eaacd",
      "parent_id": "e030afeb1b94c800c6ac9a5c444b8b9a",
      "user_id": null
    }
  },
  "logbookEntries": [
    {
      "name": "Anwensenheit_nach_oben",
      "message": "has been triggered by state of binary_sensor.bewegungsmelder_treppe_unten",
      "source": "state of binary_sensor.bewegungsmelder_treppe_unten",
      "entity_id": "automation.anwensenheit_nach_oben",
      "context_id": "d32b96602a7e573af4407e1fbe5eaacd",
      "when": "2021-04-27T21:58:03.932991+00:00",
      "domain": "automation"
    },
    {
      "when": "2021-04-27T21:58:04.050694+00:00",
      "name": "Licht Treppe 2",
      "state": "on",
      "entity_id": "light.treppe2",
      "context_entity_id": "automation.anwensenheit_nach_oben",
      "context_entity_id_name": "Anwensenheit_nach_oben",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Anwensenheit_nach_oben",
      "message": "turned on"
    },
    {
      "when": "2021-04-27T21:59:14.003738+00:00",
      "name": "Licht Treppe 2",
      "state": "off",
      "entity_id": "light.treppe2",
      "context_entity_id": "automation.anwensenheit_nach_oben",
      "context_entity_id_name": "Anwensenheit_nach_oben",
      "context_event_type": "automation_triggered",
      "context_domain": "automation",
      "context_name": "Anwensenheit_nach_oben",
      "message": "turned off"
    }
  ]
}
```
