### ISSUE TITLE
Bad management of Flex with Vertical Stacks

### ISSUE THREAD

**Issue by kKen94** [home-assistant/frontend#9048]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,

I have a view in a dashboard with 3 vertical stacks.

Inspecting code i see html uses flex (great).

But inside the `<div id="columns">` instead of 3 `<div class="column">` at the same level i have only two div of this type. Inside the first I have first vertical stack, and inside the second  the others. 

In this way I haven't satisfactory view aligned elements but scattered elements.

Entire panel width is 1656px, each column measures 500px, so elements leave 656px unused.

### Describe the behavior you expected

If there is available space, the stacks must be at the same level

### Steps to reproduce the issue

1. Create new view
2. Insert a customization of this snippet:

```
- title: Lights
    path: lights
    panel: false
    icon: 'hass:lightbulb'
    badges: []
    cards:
      - type: vertical-stack
        title: Bedroom 1
        cards:
          - type: light
            entity: light.mi_bedside_lamp
            hold_action:
              action: none
            double_tap_action:
              action: none
          - type: entities
            entities:
              - switch.main_bedroom1_light
      - type: vertical-stack
        title: Bedroom 2
        cards:
          - type: entities
            entities:
              - switch.main_bedroom2_light
      - type: vertical-stack
        title: Sala
        cards:
          - type: light
            entity: light.yeelight_color_bulb
            double_tap_action:
              action: none
            hold_action:
              action: none
```

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Google Chrome 90.0.4430.93; Firefox 88.0

### Which operating system are you using to run this browser?

Windows 20H2 - Build 19042.964
