### ISSUE TITLE
Cover Icon for STOPPED State

### ISSUE THREAD

**Issue by uspass** [home-assistant/frontend#9102]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When STOP is done during OPENING or CLOSING, the cover icon shows "hass:garage-open" or "hass:garage" respectively.
As far as I can tell there is no way (beside actually seeing the garage door) to distinguish between this state and OPEN state (or CLOSED state respectively) on the front end screen.
I reckon this comes from frontend/src/common/entity/cover_icon.ts file.
.....
  switch (stateObj?.attributes.device_class) {
    case "garage":
      switch (state) {
        case "opening":
          return "hass:arrow-up-box";
        case "closing":
          return "hass:arrow-down-box";
        case "closed":
          return "hass:garage";
        default:
          return "hass:garage-open";
      }
....
I reckon the problem might be solve by adding:
        case "stopped":
          return "hass:garage-alert";

### Describe the behavior you expected

When STOP is done during OPENING or CLOSING, the cover icon should show "hass:garage-alert", or any other relevant icon, different from "hass:garage-open", "hass:garage"

### Steps to reproduce the issue

1. Garage door is OPEN. The icon shows "hass:garage-open"
2. Press CLOSE. The state is CLOSING. The icon shows "hass:arrow-down-box"
3. Press STOP. The state is STOPPED. The icon shows "hass:garage" as in step 4,  which doesn't reflect the real status. The door is partially closed.

4. Garage door is CLOSED. The icon shows "hass:garage"
5. Press OPEN. The state is OPENING. The icon shows "hass:arrow-up-box"
6. Press STOP. The state is STOPPED. The icon shows "hass:garage-open"as in step 1, which doesn't reflect the real status. The door is partially open.

### What version of Home Assistant Core has the issue?

core-2021.4.6

### Problem-relevant frontend configuration

```yaml
Cover.yaml
- platform: mqtt
  name: "Usa Garaj"
  unique_id: 'Cover-25-25-F3'
  device_class: garage
  state_topic: 'stat/GarageDoor/STATE'
  state_open: 'OPEN'
  state_closed: 'CLOSED'
  state_opening: 'OPENING'
  state_closing: 'CLOSING'
  state_stopped: 'STOPPED'
  command_topic: 'cmnd/GarageDoor/EVENT'
  payload_open: 'OPEN'
  payload_close: 'CLOSE'
  payload_stop: 'STOP'
  availability_topic: 'tele/GarageDoor/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  optimistic: false
```
