### ISSUE TITLE
Script Editor UI treats boolean state test conditions as strings 

### ISSUE THREAD

**Issue by boybert** [home-assistant/frontend#9144]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When specifying a boolean (true/false) as a state test condition in the Script Editor UI, that state is saved with single quotes, thus as a string, in the script YAML. Editing and saving in YAML mode makes the script work as expected, but if I switch back to Visual mode, I'm prompted to save the script. Whether or not I save, booleans have again been enquoted and do not produce the expected outcome when the script is run. 

Example Visual Editor input:
![Screenshot_20210509-160538](https://user-images.githubusercontent.com/763567/117585490-a9a11080-b0e0-11eb-98cc-779d835af195.png)

Corresponding block in script YAML:
![Screenshot_20210509-160610](https://user-images.githubusercontent.com/763567/117585491-b0c81e80-b0e0-11eb-8540-ad2b357588e9.png)

### Describe the behavior you expected

Entering `true` or `false` in the Visual Script Editor for a `state` condition should store the value as a boolean (or maybe allow user to specify it is a boolean if my expected behavior interferes with other functionality)

### Steps to reproduce the issue

1. Create a new script in the UI
2. Create a `Choose` action
3. Create a first `Condition` of type `state`
4. Specify an entity (and in my case an attribute) to test
5. Specify a state of `true` or `false`
6. Save and switch to YAML mode; a state of `false` will be stored as `state: 'false'` which would not pass the test if the entity's state is the boolean value `false`. 
7. Remove the single quotes in YAML and save. The script will now test that condition based on boolean values. 
8. Switch back to Visual Mode; the Save Script button appears. 
9. With or without saving, switch to YAML mode and the single quotes will have been added again to the boolean value(s). 

### What version of Home Assistant Core has the issue?

core-2021.5.1

### In which browser are you experiencing the issue with?

Android App, Firefox

### Which operating system are you using to run this browser?

Latest Firefox on macOS 10.15x

### Problem-relevant frontend configuration

```yaml
Full script as generated by Visual Editor:

alias: dash_button_5
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.hot_tub_maintenance
            state: 'false'
            attribute: shock_ok
        sequence:
          - service: script.update_hot_tub_data
            data:
              entity: input_datetime.hot_tub_shock_date
    default: []
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.hot_tub_maintenance
            state: 'false'
            attribute: filter_ok
        sequence:
          - service: script.update_hot_tub_data
            data:
              entity: input_datetime.hot_tub_filter_check_date
    default: []
mode: single
icon: 'mdi:gesture-tap-button'
```
