### ISSUE TITLE
Service call to notify fails to show an error if YAML provided is invalid

### ISSUE THREAD

**Issue by zacwest** [home-assistant/frontend#9188]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When issuing a service call in the developer tools, not all of the fields are sent up in the issued WebSocket request if a YAML parse error occurs in the document.

### Describe the behavior you expected

If a parse error occurs, it should show an error message rather than sending up what was valid up to that point.

### Steps to reproduce the issue

1. Change service to `notify.mobile_app_something`
2. Enter values for `message` and `data`
3. Include something invalid in data, like a tab character instead of spaces for indentation.

![image](https://user-images.githubusercontent.com/74188/118373474-e1d6a200-b56b-11eb-8c24-1c589df6c800.png)

This also happens in YAML mode.

### What version of Home Assistant Core has the issue?

2021.5.4

### In which browser are you experiencing the issue with?

Edge 90.0.818.62, Safari Version 14.1 (16611.1.21.161.6)

### Which operating system are you using to run this browser?

macOS Big Sur 11.3.1 (20E241)

### Additional information

The WS message up is:

```
{type: "execute_script",…}
id: 22
sequence: [{service: "notify.mobile_app_zac_iphone", data: {message: "ummm3"}}]
0: {service: "notify.mobile_app_zac_iphone", data: {message: "ummm3"}}
data: {message: "ummm3"}
service: "notify.mobile_app_zac_iphone"
type: "execute_script"
```

The full YAML content of my service call is:

```yaml
service: notify.mobile_app_zac_iphone
data:
  message: ummm3
  data:
    actions:
      - action: one
      	title: one
      - action: two
      	title: two
      - action: three
      	title: three
      - action: four
      	title: four
      - action: five
      	title: five
      - action: six
      	title: six
      - action: seven
      	title: seven
      - action: eight
      	title: eight
      - action: nine
      	title: nine
      - action: ten
      	title: ten
      - action: eleven
      	title: eleven
      - action: twelve
      	title: twelve
```

There are tabs just before the 'title' parts of these actions.

**Comment by zacwest** [comment]
Interestingly enough, changing the data to something like…

```yaml
service: notify.mobile_app_zac_iphone
data:
  message: ummm3
  data:
    actions: [{"action": "one", "title": "one"},{"action": "two", "title": "two"},{"action": "three", "title": "three"},{"action": "four", "title": "four"},{"action": "five", "title": "five"},{"action": "six", "title": "six"},{"action": "seven", "title": "seven"},{"action": "eight", "title": "eight"},{"action": "nine", "title": "nine"},{"action": "ten", "title": "ten"}]
```

doesn't have any issues.
