### ISSUE TITLE
Calendard card : not possible to have more than 2 weeks in 'week list'. Whereas possible in month list and day list

### ISSUE THREAD

**Issue by jugla** [home-assistant/frontend#9193]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When display in lovelace a calendar
````yaml
type: calendar
entities:
  - calendar.garbage_collection
initial_view: dayGridMonth
title: Poubelle
````
In week list only current week and next week is available.
If you go in month list or day list you can go backward and forward. If you go back to "week list" , then you can go further ....

### Describe the behavior you expected

Get the same behaviour for prev and next button for month, day, week : not limited to current and next week

### Steps to reproduce the issue

1. create a calendar card in lovelace
2. select "week view"
3. press next button or previous button
4. issue : you can only select current and the following week
...

### What version of Home Assistant Core has the issue?

2021.5.4

### In which browser are you experiencing the issue with?

Microsoft Edge Version 90.0.818.62 (Version officielle) (64 bits) and Firefox 88.0.1 (64 bits)

### Which operating system are you using to run this browser?

window 10

### Problem-relevant frontend configuration

```yaml
type: calendar
entities:
  - calendar.garbage_collection
initial_view: dayGridMonth
title: Poubelle
```

### Additional information

Hereafter screenshot
Month list :  
![image](https://user-images.githubusercontent.com/59493499/118521872-b6a2ad00-b73b-11eb-85cd-b86db336b33d.png)
You can go backward/foward

In Week list, the arrow button let you go to current and next week
![image](https://user-images.githubusercontent.com/59493499/118522042-e782e200-b73b-11eb-9f24-8eeb1098dea9.png)

Nevertheless, if you go through month or day lists, you can go beyond this limit
![image](https://user-images.githubusercontent.com/59493499/118522221-1b5e0780-b73c-11eb-9562-ef8cf99c2f1f.png)
