### ISSUE TITLE
pychromecast not connecting - cast device endpoint not found

### ISSUE THREAD

**Issue by Yonny24** [home-assistant/frontend#9212]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am trying to play music through my google cast device but it is not finding the device. I have a sony SRS-X77 with chromecast.
It was working fine up until yesterday and now refuses to connect to the pychromecast. I have reinstalled Google Cast and rebooted several times.
My sony is available on the LAN and all looks fine thought the app Music center (chromecast built-in device).

Settings are all set to wake up on LAN (network standby on) and I can play directly through it but not using this chromecast.

### Describe the behavior you expected

The media player to send audio output through google cast

### Steps to reproduce the issue

1. Connect a media player with chomecast built-in
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2021.5.5

### What was the last working version of Home Assistant Core?

Home Assistant 2021.5.3

### In which browser are you experiencing the issue with?

Chrome, FireFox and Edge

### Which operating system are you using to run this browser?

 Operating System Debian GNU/Linux 10 (buster) Docker version 20.10.6 

### State of relevant entities

```txt
entity:
media_player.piria (google cast device)

state: (even though it is on)
off

friendly_name: piria
supported_features: 152461
```

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: 'custom:mini-media-player'
    artwork: cover
    hide:
      shuffle: false
      icon_state: false
    shortcuts:
      columns: 9
      buttons:
        - name: U2
          type: playlist
          id: PLBGKi73v8aO0_rii9kE3Qs9_df1In3Tte
     group: false
    source: icon
    sound_mode: full
    entity: media_player.ytube_music_player
```

### Javascript errors shown in your browser console/inspector

```txt
Logger: pychromecast.controllers
Source: /usr/local/lib/python3.8/site-packages/pychromecast/controllers/media.py:364
First occurred: May 19, 2021, 11:31:27 PM (8 occurrences)
Last logged: 8:13:49 AM

STOP command requested but no session is active.
PAUSE command requested but no session is active.

Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py:652
First occurred: May 19, 2021, 11:28:23 PM (7 occurrences)
Last logged: 8:14:04 AM

[piria(192.168.1.138):8009] Error communicating with socket, resetting connection
[piria(192.168.1.139):8009] Error communicating with socket, resetting connection


Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.8/site-packages/pychromecast/socket_client.py:395
First occurred: May 19, 2021, 11:28:23 PM (7 occurrences)
Last logged: 8:14:04 AM

[piria(192.168.1.138):8009] Failed to connect to service ServiceInfo(type='mdns', data='SRS-X77-3a18b3491a310c486393155976ba5bfa._googlecast._tcp.local.'), retrying in 5.0s
[piri
```
