### ISSUE TITLE
The colors on some binary_sensors are inverted/misrepresented (red/green)

### ISSUE THREAD

**Issue by crixionz** [home-assistant/frontend#9239]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When looking at an entity's _**history**_, some binary sensors are visually represented with the wrong or inverted color. 
For example with device class 'sound' or 'vibration', the state 'clear' shows red, while 'detected' shows green. (confusing)

On the other hand, device classes like 'door' and 'problem' work just like one would expect, showing green for closed/ok and red for open/problem. This is the way it should be.

![image](https://user-images.githubusercontent.com/62850893/122682211-674b1300-d1f8-11eb-83c4-9d08ae3bcd1e.png)

### Describe the behavior you expected

I think the history colors of these device classes should be inverted, so that they actually represent the state that matches the intuitive expectation (like 'door' does), 
OR
even better, (if not too complicated/bloating) let the user **pick history colors for each state** of each entity. 

If that bloats the UI too much, maybe only add a simple yaml key to `customize.yaml` like
```
customize:
  binary_sensor.doorbell:
    device_class: sound
    invert_history_color: true
``` 
for example.

until then, a workaround could be to use the device class 'door' for a sensor that, in reality, monitors vibration.
### Steps to reproduce the issue

1. Add a binary_sensor of device class 'sound'
2. Change its state at least once
3. Look at the entity's history via **History** or a **History Graph card**.

### What version of Home Assistant Core has the issue?

core-2021.5.5

### In which browser are you experiencing the issue with?

Firefox 88.0.1

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
binary_sensor.front_doorbell 	off 	
friendly_name: Front Doorbell
device_class: sound
```

### Problem-relevant frontend configuration

```yaml
(ESPHome yaml)
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    name: "Front Doorbell"
    device_class: sound
    filters:
      - delayed_off: 3s
```
