### ISSUE TITLE
HA 2021.6 causes regular entities  cards to be disturbed

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9291]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

best show a picture:

<img width="455" alt="Schermafbeelding 2021-05-27 om 15 18 55" src="https://user-images.githubusercontent.com/33354141/120042243-f86c0700-c009-11eb-81f3-13e64e8498a1.png">

using:
```
  - type: entities
    title: Home settings
    show_header_toggle: false
    entities:
      - entity: input_boolean.home_mode_vacation
        secondary_info: last-changed
      - entity: input_boolean.home_mode_party
        secondary_info: last-changed
      - entity: input_boolean.home_mode_locked
        secondary_info: last-changed
      - entity: input_boolean.dogs_free
        secondary_info: last-changed
```

same goes for eg the entities on a Zwave device in config/devices

<img width="351" alt="Schermafbeelding 2021-05-28 om 23 41 59" src="https://user-images.githubusercontent.com/33354141/120044579-6ca8a980-c00e-11eb-9e6e-ae0de00d014a.png">

### Describe the behavior you expected

show as before 2021.6

### Steps to reproduce the issue

1. see above
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.60b1

### What was the last working version of Home Assistant Core?

2021.5.4

### In which browser are you experiencing the issue with?

Any/all desktop and mobile iOS

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

### Additional information

as [discussed](https://discord.com/channels/330944238910963714/427516175237382144/847863338179493980) on Discord
