### ISSUE TITLE
Lost Icon in lovelace dashboard

### ISSUE THREAD

**Issue by mbah-dukun** [home-assistant/frontend#9294]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

lost icon after rc update

![image](https://user-images.githubusercontent.com/67048857/120094490-dfb73a80-c14a-11eb-875c-bcf3c14f4540.png)

### Describe the behavior you expected

The icon should appear, not only the Light icon disappears, but the standard Redmi4X sensor icon also disappears.
![image](https://user-images.githubusercontent.com/67048857/120094787-a97aba80-c14c-11eb-937b-090345ea37da.png)

### Steps to reproduce the issue

1. update to core-2021.6.0b1
2. update OS to Home Assistant OS 6.0.rc3
3. restart Raspberry Pi 3B+

### What version of Home Assistant Core has the issue?

core-2021.6.0b1

### What was the last working version of Home Assistant Core?

core-2021.6.0b1

### In which browser are you experiencing the issue with?

2021.6.0b0

### Which operating system are you using to run this browser?

Windows 10 - 2004

### Problem-relevant frontend configuration

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: bluetooth_tracker

#logger :
#   logs :
#     homeassistant.components.modbus : debug 
#     pymodbus.client : debug

sensor:
  - platform: systemmonitor
    scan_interval: 1
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: memory_free
      - type: memory_use
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: template
    sensors:
      date_formatted:
        friendly_name: "Tanggal"
        value_template: "{{ as_timestamp(states('sensor.date')) | timestamp_custom('%d %B %Y') }}"
        icon_template: mdi:calendar
      time_formatted:
        friendly_name: "Jam"
        value_template: "{{ as_timestamp(now()) | timestamp_custom('%H:%M') }}"
        icon_template: mdi:clock
  - platform: uptime
    name: Uptime

  - platform: template
    sensors:
        ha_uptime:
           friendly_name: "Home Assistant uptime"
           value_template: >-
             {% set up_time =  as_timestamp(now()) - as_timestamp(states('sensor.uptime')) %}

             {% if up_time == 0 %}
                Just restarted...
             {% else %}
                {% set minutes = (up_time // 60) | int %}
                {% set hours = (minutes // 60) %}
                {% set days = (hours // 24) %}
                {% set weeks = (days // 7) %}

                {% set minutes = (minutes % 60) %}
                {% set hours =  (hours % 24) %}
                {% set days = (days % 7) %}

                {% macro phrase(value, name) %}
                    {%- set value = value %}
                    {%- set end = 's' if value > 1 else '' %}
                    {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
                {%- endmacro %}

                {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
                {% set last_comma = text.rfind(',') %}
                {% if last_comma != -1 %}
                    {% set text = text[:last_comma] + ' and' + text[last_comma + 1:] %}
                {% endif %}

                {{ text }}

                {% endif %}

modbus:
  - name: plc1
    type: serial
    method: rtu
    port: /dev/ttyUSB0
    baudrate: 57600
    stopbits: 1
    bytesize: 8
    parity: N
    lights:
      - name: switch1
        slave: 1
        address: 128
        write_type: coil
      - name: switch2
        slave: 1
        address: 129
        write_type: coil
      - name: switch3
        slave: 1
        address: 130
        write_type: coil
      - name: switch4
        slave: 1
        address: 131
        write_type: coil
      - name: switch5
        slave: 1
        address: 132
        write_type: coil
      - name: switch6
        slave: 1
        address: 133
        write_type: coil
      - name: switch7
        slave: 1
        address: 134
        write_type: coil
      - name: switch8
        slave: 1
        address: 135
        write_type: coil
```
