### ISSUE TITLE
[Script editor] when adding a new wait action, the "Continue on timeout" toggle does NOT reflect behaviour

### ISSUE THREAD

**Issue by tom0334** [home-assistant/frontend#9355]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new wait action through the UI, the "Continue on timeout" is off, but the script DOES continue on timeout.

Toggling the continue on timeout option on and off again fixes it, but shouldn't be needed of course.

This is also visible in yaml:

**before toggling on and of:**

```
alias: New Script
sequence:
  - wait_template: '{{0 == 1}}'
    timeout: '00:00:03'
mode: single
```
**After toggling:**
```
alias: New Script
sequence:
  - wait_template: '{{0 == 1}}'
    timeout: '00:00:03'
    continue_on_timeout: false
```
 

### Describe the behavior you expected

The script should NOT continue after the timeout, because the toggle is off.

### Steps to reproduce the issue

1. Create a new script
2. add a wait action
3. create a template that never evaluates to true for example {{0 == 1}}
4. add a short timeout duration. Do NOT touch the continue on timeout toggle.
5. add an action below, for example turn on one of the lights.
6. run the script.

Since continue on timeout is off, the Light turn on action should NOT run. Notice that it does.

### What version of Home Assistant Core has the issue?

 core-2021.6.0 

### In which browser are you experiencing the issue with?

Firefox 88.01

### Which operating system are you using to run this browser?

Windows 10
