### ISSUE TITLE
Enabling boolean option in service UI doesn't set the value

### ISSUE THREAD

**Issue by theetron** [home-assistant/frontend#9362]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When calling a service from a button, like the sonos.set_option, I can check a box to enable / disable an option.  These options are flags. If I want to call an option to set a flag value to false, checking the box for this option isn't enough. You have to toggle the true/false 1st to true and than to false so send an actual false to the service.

### Describe the behavior you expected

If I check the box for an option and this option is a flag, the default is set to false in the gui. I expect to send the false value to the service to set the option.

### Steps to reproduce the issue

1. Create a button card
2. let is call a service with flag options
3. enable an option, but not tough the toggle button
4. It will not send a false when pressing the button
5. flip the toggle to true and back to false
6. pressing the button will now send a false to the service

### What version of Home Assistant Core has the issue?

core-2021.6.1

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
without pressing the toggle from on to off:

    tap_action:
      action: call-service
      service: sonos.set_option
      service_data: {}

With pressing the toggle from on to off:

    tap_action:
      action: call-service
      service: sonos.set_option
      service_data:
        night_sound: false
```
