### ISSUE TITLE
Lovelace continually refreshing since 2021.6 on iOS 12.5.3

### ISSUE THREAD

**Issue by Juggler00** [home-assistant/frontend#9398]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since upgrading to 2021.6, Lovelaces refreshes every 15-30s on an older iPad that is stuck on iOS 12.5.3. 

This had not been the case through 2021.5.5. To ensure it was not related to a custom component and the upgrade to Lit 2.0, I remove all in configuration.yaml and restarted HA. 

### Describe the behavior you expected

Prior to upgrading to 2021.6, my iPad would run the Lovelace front-end for days without any problems.

### What version of Home Assistant Core has the issue?

core-2021.6.3

### What was the last working version of Home Assistant Core?

2021.5.5

### In which browser are you experiencing the issue with?

Mobile Safari

### Which operating system are you using to run this browser?

iOS 12.4.3

**Comment by bramkragten** [comment]
Do you get a message that there was a problem with the website? Anything in the console?

**Comment by Juggler00** [comment]
This is the output from the console:
`The main 'lit-element' module entry point is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-elements.ts'.

This is confusing, as I have deliberately removed all custom-elements and simplified my Lovelace to troubleshoot. Below are snippets of my configuration.yaml and lovelace-test.yaml.

Is this a bug, or am I not doing something correctly?

```
# Lovelace section
lovelace:
  mode: yaml
  # resources:
    # - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    #   type: module      
    # - url: /hacsfiles/lovelace-clock-card/clock-card.js
    #   type: module
    # - url: /hacsfiles/lovelace-darksky-card/lovelace-darksky-card.js
    #   type: module
    # - url: /hacsfiles/dual-gauge-card/dual-gauge-card.js 
    #   type: module
  dashboards:
    # lovelace-iphone:
    #   mode: yaml
    #   filename: lovelace-iphone.yaml
    #   title: iPhone
    #   icon: mdi:cellphone-iphone
    #   show_in_sidebar: true
    #   require_admin: true
    # lovelace-ipad-kitchen:
    #   mode: yaml
    #   filename: lovelace-ipad-kitchen.yaml
    #   title: iPadK
    #   icon: mdi:tablet-ipad
    #   show_in_sidebar: true
    #   require_admin: false      
    lovelace-test:
      mode: yaml
      filename: lovelace-test.yaml
      title: test
      icon: mdi:tablet-ipad
      show_in_sidebar: true
      require_admin: false      
```
```
title: Home

views:
  - title: Home
    icon: mdi:home  
    path: home
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Lights
            show_header_toggle: false
            entities:
              - entity: group.upstairs_lights
                name: upstairs
              - entity: group.mainfloor_lights
                name: main floor
              - entity: group.basement_lights
                name: basement
```
