### ISSUE TITLE
input_select dropdown wont show completely or scroll down

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9416]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

the dropdown of an input_select wont scroll down in a Safari desktop window when it touches the bottom window

Chrome behaves fine

### Describe the behavior you expected

be able to scroll up/down

### Steps to reproduce the issue

1. click dropdown
2. try and scroll
3.
...

### What version of Home Assistant Core has the issue?

2021.6.4

### What was the last working version of Home Assistant Core?

Dk

### In which browser are you experiencing the issue with?

Safari desktop Mac

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### State of relevant entities

```txt
not relevant
```

### Problem-relevant frontend configuration

```yaml
- type: entities
    title: Theme settings
    entities:
      - input_select.set_sunrise_theme
      - input_select.set_sunset_theme
      - sensor.sun_based_theme
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

![Jun-14-2021 11-18-41](https://user-images.githubusercontent.com/33354141/121869702-9b0ed000-cd02-11eb-8405-52f53dd42630.gif)

this is the full list of available themes the scroll wont allow to select:

<img width="471" alt="Schermafbeelding 2021-06-14 om 11 13 59" src="https://user-images.githubusercontent.com/33354141/121869734-a235de00-cd02-11eb-8355-8fa49b6ac363.png">
