### ISSUE TITLE
input_number always shows decimal on step: 1 (or any integer)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9429]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

using input_numbers with integer steps still show the decimal '.0' which is really ugly non the frontend. Besides that it takes screen real estate forcing the unit to the nest line:

<img width="478" alt="Schermafbeelding 2021-06-16 om 10 28 08" src="https://user-images.githubusercontent.com/33354141/122185666-90347680-ce8d-11eb-89fe-d79636abfa09.png">

### Describe the behavior you expected

please add some logic that input_numbers using an integer for step size dont show the decimal '.1'

### Steps to reproduce the issue

1. create input_number with step: 1, or any integer
2. check frontend
3.
...

### What version of Home Assistant Core has the issue?

2021.6.5

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

Any really

### Which operating system are you using to run this browser?

Big sur 11.4 Safari 14.1.1

### State of relevant entities

<img width="641" alt="Schermafbeelding 2021-06-16 om 10 32 47" src="https://user-images.githubusercontent.com/33354141/122186395-4bf5a600-ce8e-11eb-9c5f-b5de6c41ddfa.png">

```
  increase_volume_delay:
    name: Increase volume delay
    min: 30
    max: 150
    step: 30
    unit_of_measurement: secs
```

### Problem-relevant frontend configuration

```
  - type: entities
    title: Wakeup radio
    show_header_toggle: false
    entities:
      - input_boolean.wakeup_radio
      - input_select.wakeup_radio
      - input_select.radio_station_wakeup
      - input_boolean.snooze
      - input_boolean.increase_volume
      - type: divider
      - input_number.snooze_delay
      - input_number.increase_volume_delay
      - input_number.increase_volume
      - input_number.wakeup_radio_volume
 ```

### Javascript errors shown in your browser console/inspector

```txt
none
```
