### ISSUE TITLE
Grid card shows empty first (conditional) card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9433]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

using a type: grid card to show conditional button cards, all squares (using `aspect_ratio: 1/1`) , it always shows the first (left) position as an empty placeholder without a card.

other than that, the grid is filled perfectly, and depending on the conditions for the individual cards, fills as should

4 'on' cards:
<img width="488" alt="Schermafbeelding 2021-06-16 om 14 04 00" src="https://user-images.githubusercontent.com/33354141/122215665-c385fe00-ceab-11eb-8da9-3b0a3a8845cc.png">

3:
<img width="487" alt="Schermafbeelding 2021-06-16 om 14 01 02" src="https://user-images.githubusercontent.com/33354141/122215464-8b7ebb00-ceab-11eb-8c81-825e47d87929.png">

2:
<img width="481" alt="Schermafbeelding 2021-06-16 om 14 02 03" src="https://user-images.githubusercontent.com/33354141/122215483-91749c00-ceab-11eb-8f8f-88d01c6f86fc.png">

1:
<img width="504" alt="Schermafbeelding 2021-06-16 om 14 15 09" src="https://user-images.githubusercontent.com/33354141/122217072-596e5880-cead-11eb-940f-a50e816be3a2.png">

### Describe the behavior you expected

use the first placeholder in the grid

### Steps to reproduce the issue

1. create the grid, with config below
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.6.5

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

Any really, both desktop an handheld 

### Which operating system are you using to run this browser?

Big sur 11.4

### Problem-relevant frontend configuration

```yaml
- type: grid
  title: Alerts
  columns: 4
  cards:
    !include /config/lovelace/buttons/buttons_alerts.yaml
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

the include files has all conditional cards, like:

```
- type: conditional
  conditions:
    - entity: binary_sensor.doors
      state: 'on'
  card: !include /config/lovelace/includes/include_button_sensor_doors.yaml

- type: conditional
  conditions:
    - entity: binary_sensor.garage_door
      state: 'on'
  card: !include /config/lovelace/includes/include_button_garage_door.yaml

- type: conditional
  conditions:
    - entity: binary_sensor.github_repo_has_update
      state: 'on'
  card: !include /config/lovelace/includes/include_button_github_repo_alert.yaml

- type: conditional
  conditions:
    - entity: binary_sensor.earthquakes_near_active
      state: 'on'
  card: !include /config/lovelace/includes/include_button_quake_alert.yaml

- type: conditional
  conditions:
    - entity: binary_sensor.trash_notification
      state: 'on'
  card: !include /config/lovelace/includes/include_button_trash_alert.yaml
```

etc etc

seems to have to do with the preceding conditional cards in the list, that are not 'on', and hence leave the empty first space. taking all out of the list until the current Meteoalarm you see I the screen shot, moves it to the correct first slot.

if several others after it are 'off' and then again 1 is 'on', it shows nicely next to the first, no empty space.
