### ISSUE TITLE
Using button(s) in entities card results in configuration errors detected

### ISSUE THREAD

**Issue by pmannk** [home-assistant/frontend#9436]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When attempting to use a button in an entities card, the editor reports configuration errors were detected and will not save the card.
This card was created previously and could be edited and saved in core_2021.4, however it cannot be saved in core_2021.6.
The card is operationally working fine, it just cannot be saved if I try and edit it.

```
Card:
type: entities
show_header_toggle: false
entities:
  - type: button
    name: Bedroom Hallway
    action_name: Trigger (30 mins)
    icon: mdi:bed-outline
    show_icon: true
    tap_action:
      action: call-service
      service: script.1622291891991
    hold_action:
      action: call-service
      service: script.1622291923367
```

Error:
```
Configuration errors detected:
Required key "entities.0.entity" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.conditions" is missing.
Required key "entities.0.url" is missing.
Required key "entities.0.entities" is missing.
Required key "entities.0.entity" is missing.
Required key "entities.0.attribute" is missing.
Required key "entities.0.service" is missing.
Required key "entities.0.text" is missing.
```

Functional card:
![image](https://user-images.githubusercontent.com/79073108/122323578-a7956180-cf6a-11eb-8b0b-c25f60749684.png)

Card in editor:
![image](https://user-images.githubusercontent.com/79073108/122323640-c136a900-cf6a-11eb-8eed-d2e1e6608af6.png)

### Describe the behavior you expected

Editor should have passed validation of the button entity

### Steps to reproduce the issue

1. Create an entities card
2. Use the type: button in the card
3. Editor will fail to validate the configuration

The example entities card with button documented here [https://www.home-assistant.io/lovelace/entities/](url) also fails validation with the same error.

### What version of Home Assistant Core has the issue?

core_2021.6

### What was the last working version of Home Assistant Core?

core_2021.4

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.106

### Which operating system are you using to run this browser?

Windows 10 10.0.19041

### Problem-relevant frontend configuration

```yaml
type: entities
show_header_toggle: false
entities:
  - type: button
    name: Bedroom Hallway
    action_name: Trigger (30 mins)
    icon: mdi:bed-outline
    show_icon: true
    tap_action:
      action: call-service
      service: script.1622291891991
    hold_action:
      action: call-service
      service: script.1622291923367
```
