### ISSUE TITLE
Entry filter card has an error in documentation

### ISSUE THREAD

**Issue by Dycelll** [home-assistant/frontend#9440]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There is a error in the documentation for the entry filter card or there is a bug in the card itself.
The home assistant documentation has the bad examples displayed here:
https://www.home-assistant.io/lovelace/entity-filter/

```
state_filter:
  - operator: "!="
    value: home
  - operator: "!="
    value: work
```
This is incorrect. It should state:

```
state_filter:
  - value: home
    operator: "!="
  -  value: work
    operator: "!="
```

There was someone else that probably ran into the same problem:
https://community.home-assistant.io/t/operator-in-entity-filter-includes-wrong-entities/271167

### Describe the behavior you expected

The behavior as described in the documentation. 

### Steps to reproduce the issue

1. Add filter entry card
2. Try both filters I described. 
...

### What version of Home Assistant Core has the issue?

2021.6.5

### What was the last working version of Home Assistant Core?

Unknown

### In which browser are you experiencing the issue with?

Every

### Which operating system are you using to run this browser?

iPad, macOS. 

### Problem-relevant frontend configuration

```yaml
type: entity-filter
entities:
  - entity: person.Me
    name: Me
  - entity: person.NotMe
    name: Not me
state_filter:
  - value: unknown
    operator: '!='
card:
  type: glance
  title: People in the office
  show_icon: true
  show_state: true
```
