### ISSUE TITLE
Entity Filter Card ignores 'Section' Entity

### ISSUE THREAD

**Issue by AmeerGaafar** [home-assistant/frontend#9447]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The following would not render the section entity. It get ignored, probably filtered out..
```
          - type: entity-filter
            card:
              type: entities
              title: Open Shutters
            state_filter:
              - operator: '>'
                value: 10
                attribute: current_position
            entities:
              - entity: blah1
                type: section
              - entity: cover.xxxxxxxxx
                icon: mdi:window-shutter
                secondary_info: position
                name: Living Room - Main
```

### Describe the behavior you expected

A section Entity is only a visual aid. It should always render in an entity-filter card.

### Steps to reproduce the issue

1. Create an entity filter card
2. Include a section entity
3. Include normal etities.

The normal entities will render according to associated conditions. The section entity will never render.

### What version of Home Assistant Core has the issue?

core-2021.6.5

### In which browser are you experiencing the issue with?

Version 91.0.4472.77 

### Which operating system are you using to run this browser?

macOS BigSur 11.4
