### ISSUE TITLE
template sensor with device_class: battery doesn't show up in overview

### ISSUE THREAD

**Issue by erkr** [home-assistant/frontend#9454]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created  a template sensor for observing the battery level attribute of a HUE motion sensor. 
This new sensor is accessible in development tools and in manual created lovelace dashboards, BUT not in the automatically generated overview dashboard. 
This is the same for Chrome, Edge or the iOS app.

### Describe the behavior you expected

I expected this sensor to show up in the sensor group of the automatically generated overview dashboard. 
It doesn't, Unless I either:
- comment out the line: "device_class: battery" 
- change the type into e.g.: "device_class: humidity"

One of these changes will make the sensor to show up in the overview!

### Steps to reproduce the issue

1. Create a template sensor as described
2. just comment out the line: "device_class: battery" and restart HA
3. OR change it into "device_class: humidity" and restart HA
...

### What version of Home Assistant Core has the issue?

core-2021.6.6

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Chrome Version 91.0.4472.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10, iOS 14

### Problem-relevant frontend configuration

```yaml
# configuration.YAML
sensor:
  - platform: template
    sensors:
      serre_motion_battery:
        friendly_name: Serre sensor battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('binary_sensor.serre_sensor_motion','battery_level') }}"
        device_class: battery
```

### Additional information

Not browser or OS specific 
It seems to happen only for the specific combination of defining "device_class" with the value "battery" 
I attached two small screenshots of the sensor group of the overview dashboard.

OK.png is with humidity, in stead of battery as device class:
![ok](https://user-images.githubusercontent.com/4363599/122785483-f3b21000-d2a2-11eb-95f0-85ec18d72a6d.png)
NOK.png is with the value battery:
![nok](https://user-images.githubusercontent.com/4363599/122785636-104e4800-d2a3-11eb-904e-11d529417184.png)
