### ISSUE TITLE
Entities card schema failing

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#9461]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to add an entities card with attribute rows I get the following errors that prevent the card from being saved:

```
Configuration errors detected:

    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.view" is missing.
    Required key "entities.1.view" is missing.
    Required key "entities.1.view" is missing.
    Required key "entities.1.conditions" is missing.
    Required key "entities.1.url" is missing.
    Required key "entities.1.entities" is missing.
    Required key "entities.1.service" is missing.
    Required key "entities.1.text" is missing.
    Required key "entities.2.tap_action" is missing.
    Required key "entities.2.tap_action" is missing.
    Required key "entities.2.tap_action" is missing.
    Required key "entities.2.tap_action" is missing.
    Required key "entities.2.tap_action" is missing.
    Required key "entities.2.view" is missing.
    Required key "entities.2.view" is missing.
    Required key "entities.2.view" is missing.
    Required key "entities.2.conditions" is missing.
    Required key "entities.2.url" is missing.
    Required key "entities.2.entities" is missing.
    Required key "entities.2.service" is missing.
    Required key "entities.2.text" is missing.
    Required key "entities.3.tap_action" is missing.
    Required key "entities.3.tap_action" is missing.
    Required key "entities.3.tap_action" is missing.
    Required key "entities.3.tap_action" is missing.
    Required key "entities.3.tap_action" is missing.
    Required key "entities.3.view" is missing.
    Required key "entities.3.view" is missing.
    Required key "entities.3.view" is missing.
    Required key "entities.3.conditions" is missing.
    Required key "entities.3.url" is missing.
    Required key "entities.3.entities" is missing.
    Required key "entities.3.service" is missing.
    Required key "entities.3.text" is missing.
    Required key "entities.4.tap_action" is missing.
    Required key "entities.4.tap_action" is missing.
    Required key "entities.4.tap_action" is missing.
    Required key "entities.4.tap_action" is missing.
    Required key "entities.4.tap_action" is missing.
    Required key "entities.4.view" is missing.
    Required key "entities.4.view" is missing.
    Required key "entities.4.view" is missing.
    Required key "entities.4.conditions" is missing.
    Required key "entities.4.url" is missing.
    Required key "entities.4.entities" is missing.
    Required key "entities.4.service" is missing.
    Required key "entities.4.text" is missing.
    Required key "entities.5.tap_action" is missing.
    Required key "entities.5.tap_action" is missing.
    Required key "entities.5.tap_action" is missing.
    Required key "entities.5.tap_action" is missing.
    Required key "entities.5.tap_action" is missing.
    Required key "entities.5.view" is missing.
    Required key "entities.5.view" is missing.
    Required key "entities.5.view" is missing.
    Required key "entities.5.conditions" is missing.
    Required key "entities.5.url" is missing.
    Required key "entities.5.entities" is missing.
    Required key "entities.5.service" is missing.
    Required key "entities.5.text" is missing.
```

### Describe the behavior you expected

To be able to save the card.

### Steps to reproduce the issue

1. add config listed below to a manual card
2. attempt to save
3.
...

### What version of Home Assistant Core has the issue?

core-2021.6.6

### What was the last working version of Home Assistant Core?

2021.5?

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.114, Firefox 89.0.2

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration
```
entities:
  - entity: sensor.samba_backup
    icon: mdi:file-replace-outline
    name: Backup Status
  - attribute: backups_local
    entity: sensor.samba_backup
    icon: mdi:file-outline
    name: Local Backups
    type: attribute
  - attribute: backups_remote
    entity: sensor.samba_backup
    icon: mdi:file-move-outline
    name: Remote Backups
    type: attribute
  - attribute: total_backups_succeeded
    entity: sensor.samba_backup
    icon: mdi:file-check-outline
    name: Succeded Backups
    type: attribute
  - attribute: total_backups_failed
    entity: sensor.samba_backup
    icon: mdi:file-cancel-outline
    name: Failed Backups
    type: attribute
  - attribute: last_backup
    entity: sensor.samba_backup
    icon: mdi:file-clock-outline
    name: Last Backup
    type: attribute
show_header_toggle: false
title: Samba Backup
type: entities
```
_No response_

### Additional information

Removing the `icon:` option from the attribute type rows allows the card to be saved.
