### ISSUE TITLE
Inconsistent temp conversion across cards

### ISSUE THREAD

**Issue by jeeftor** [home-assistant/frontend#9463]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I recently picked up an Aquara temp sensor. I'm displaying it in two different cards (Entity & History). In the entity card its displaying in Fahrenheit and in the history card its in Celsius

<img width="540" alt="image" src="https://user-images.githubusercontent.com/6491743/123318312-4fbba500-d4ec-11eb-8c5f-060abf7223a3.png">

### Describe the behavior you expected

I expect it to auto convert to Fahrenheit in both cards

### Steps to reproduce the issue

1. Buy Aquara Temp Sensor
2. Add to HA instance
3. Add to an Entity Card
4. Add to a History card
...

### What version of Home Assistant Core has the issue?

core-2021.6.6

### In which browser are you experiencing the issue with?

Safari on Mac + HA Client on IOS

### Which operating system are you using to run this browser?

Supervisor mode (so docker images?)

**Comment by spacegaier** [comment]
Steps to reproduce: "Buy Aquara Temp Sensor" 🤣. That is unlikely to happen. Therefore please fill in the state of the relevant entities and the frontend configuration in the issue template so we can try to reproduce without buying new hardware 😉.

What unit system have you set your HA instance to? Metric or imperial?

**Comment by jeeftor** [comment]
Sorry.

**Entity:** `sensor.lumi_lumi_weather_18ecc506_temperature`
**State:** `68.0`

```
state_class: measurement
unit_of_measurement: °F
friendly_name: LUMI lumi.weather 18ecc506 temperature
device_class: temperature
```


# Panel #1 - **Entites Card Configuration**

```
type: entities
entities:
  - entity: sensor.downstairs_temperature
  - entity: sensor.upstairs_temperature
  - entity: sensor.laundry_room_motion_sensor_temperature
  - entity: sensor.stairs_motion_sensor_temperature
  - entity: sensor.philips_sml002_0fbe4406_temperature
    name: Outside
  - entity: sensor.lumi_lumi_weather_18ecc506_temperature
```

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/6491743/123340969-67098b00-d50a-11eb-87a4-ad31dd7e20f8.png">


# Panel #2 - **History Card**

```
type: history-graph
entities:
  - entity: sensor.downstairs_temperature
  - entity: sensor.laundry_room_motion_sensor_temperature
  - entity: sensor.stairs_motion_sensor_temperature
  - entity: sensor.upstairs_temperature
  - entity: sensor.philips_sml002_0fbe4406_temperature
  - entity: sensor.lumi_lumi_weather_18ecc506_temperature
hours_to_show: 24
refresh_interval: 0
title: Temperature Graph
```

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/6491743/123340935-53f6bb00-d50a-11eb-8b35-1fd7d854cc9e.png">
