### ISSUE TITLE
Shopping list doesn't update when item added SERVICE SHOPPING_LIST.ADD_ITEM

### ISSUE THREAD

**Issue by Rep-Hueman** [home-assistant/frontend#9521]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using a service call (eg in a script or automation) to add an item to the shopping list, it doesn't update until you refresh the shopping list.

### Describe the behavior you expected

Service calls to shopping_list.add_item and other shopping_list services should update the front end in realtime like all other services do.

### Steps to reproduce the issue

1.Open two browser windows, one on the shopping list or a page with the shopping list card, 
 the browser window on the Developer Tools services
2.choose the Shopping List: Add Item (shopping_list.add_item) service and enter "Eggs" as the product
3. Click "Call Service"
4. Note the Browser window with the shopping list on it doesn't change
5. Refresh the shopping list page and "Eggs" will appear

### What version of Home Assistant Core has the issue?

Home Assistant 2021.6.6

### In which browser are you experiencing the issue with?

Edge and Google Chrome

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
alias: Boodschappen toevoegen
sequence:
  - service: shopping_list.add_item
    data_template:
      name: '{{ states(''input_select.boodschappenlijst'') }}'
mode: single
```
