### ISSUE TITLE
Sensor not rendering humidity sensor graph line correctly

### ISSUE THREAD

**Issue by pedrolamas** [home-assistant/frontend#9522]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a few zigbee2mqtt climate sensors and I've noticed that since a few releases of Home Assistant Core, the graph lines for the humidity sensor just shows a flat line instead of the correct line.

### Describe the behavior you expected

Graph line should be similar to the graph in the sensor detail

### Steps to reproduce the issue

1. Add a temperature + humidity sensor to zigbee2mqtt
2. Ensure that it shows up in Home Assistant (via MQTT discovery)
3. Add the temperature and humidity sensors to a horizontal stack and set `graph: line` on both sensor entries

### What version of Home Assistant Core has the issue?

core-2021.7.0

### What was the last working version of Home Assistant Core?

Can't say for sure, but I know it this problem was also happening on 2021.6 (and possibly 2021.5)

### In which browser are you experiencing the issue with?

Microsoft Edge Version 93.0.933.1 (Official build) dev (64-bit)

### Which operating system are you using to run this browser?

Microsoft Windows [Version 10.0.19043.1081]

### Problem-relevant frontend configuration

```yaml
title: Climate
path: climate
icon: mdi:thermometer
cards:
  - type: vertical-stack
    title: Living Room
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Temperature
            entity: sensor.living_room_climate_temperature
            graph: line
          - type: sensor
            name: Humidity
            entity: sensor.living_room_climate_humidity
            graph: line
```

### Additional information

On the below image, compare the line graph on the Living Room humidity (on the top, 2nd graph) with the graph shown on the popup detail.

![image](https://user-images.githubusercontent.com/85504/124771495-13983380-df33-11eb-9c54-c472fddf1b84.png)
