### ISSUE TITLE
Invalid timestamp on 2021.7 Forecast Solar

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9526]
### The problem

out of the box, the new 2021.7 integration Forecast Solar creates entities that throw an error (in Front-end) because of wrong timestamp

### What is version of Home Assistant Core has the issue?

2021.7.0

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Forecast solar

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/forecast_solar/

### Example YAML snippet

all UI config.
this is lovelace:
```yaml



  - type: entities
    title: Solar production forecast
    entities:
      - sensor.energy_next_hour
      - sensor.energy_current_hour
      - sensor.energy_production_today
      - sensor.energy_production_tomorrow
      - sensor.power_production_next_12hours
      - sensor.power_production_next_24hours
      - sensor.power_production_next_hour
      - sensor.power_production_now
      - sensor.power_highest_peak_time_today
      - sensor.power_highest_peak_time_tomorrow
```

### Additional information

<img width="491" alt="Schermafbeelding 2021-07-07 om 17 20 59" src="https://user-images.githubusercontent.com/33354141/124802674-8536a880-df58-11eb-852a-5cc88d95605c.png">

and states shows:

<img width="1034" alt="Schermafbeelding 2021-07-07 om 17 24 05" src="https://user-images.githubusercontent.com/33354141/124802703-8c5db680-df58-11eb-8c7f-0a31431ad114.png">

so no T in the timestamp, causing the incorrect frontend?

comment by Petro in community:

> It could be 2 things, missing microseconds or the T. I would bet it’s the microseconds because I’ve used timestamps with or without T before. It’s also possible that something in the frontend changed with timestamps.
