### ISSUE TITLE
tap action 'fire-dom-event' not supported in visual editor

### ISSUE THREAD

**Issue by mneuron** [home-assistant/frontend#9528]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I want to generate a browser-mod popup using 'fire-dom-event' tap_action in the visual editor. 
The visual editor only supports "none","toggle","more-info","call-service","url","navigate".
Also in the yaml editor it is not possible to save the yaml because of errors:
```
Configuration errors detected:
Required key "tap_action.url_path" is missing.
Required key "tap_action.navigation_path" is missing.
Required key "tap_action.service" is missing.
```

### Describe the behavior you expected

Also accept in the visual editor
```
tap_action:
  action: fire-dom-event
    browser_mod:
      command: toast
      message: Hello, world!

```
or at least be _allowed to save the yaml in the editor_ by accepting the fire-dom-event as a valid tap_action value.

### Steps to reproduce the issue

```
type: button
entity: light.lamp_li
tap_action:
  action: fire-dom-event
  browser_mod:
    command: toast
    message: Hello, world!
```
...

### What version of Home Assistant Core has the issue?

core-2021.7.0

### Which operating system are you using to run this browser?

Windows 10.

**Comment by spacegaier** [comment]
I would not consider that a bug. You are using a 3rd party custom plugin, that HA does not know anything about, so it is not something the HA frontend can verify and handle.

**Comment by bramkragten** [comment]
`fire-dom-event` is actually an supported action, it will however never be supported by our editors as it is aimed at custom card developers.

**Comment by spacegaier** [comment]
Then we should add it to the docs because it is not mentioned there currently.

That's also why I wasn't aware and never tested that when I changed the action validation logic a couple of releases ago.

**Comment by mneuron** [comment]
It is currently not possible to save  after editing in the YAML editor.  Perhaps the fire-dom-event can be added as a valid option without the consecutive fields and not triggering missing keys
I agree that support in the visual editor is not necessary.

**Comment by gadgetchnnel** [comment]
I've had the same issue. It looks like the schema validation gets confused when the `action` isn't one of the expected values, and this causes it to treat **url_path**, **navigation_path**, and **service** as all being required even though these should only be required for the **url**, **navigate**, and **call-service** actions respectively.

This results in the error:

 ```
Configuration errors detected:
    Required key "tap_action.url_path" is missing.
    Required key "tap_action.navigation_path" is missing.
    Required key "tap_action.service" is missing.
```
A workaround for this appears to be to add values for these "missing" options:

```
type: button
entity: light.my_light
tap_action:
  action: fire-dom-event
  url_path: ''
  navigation_path: ''
  service: ''
  browser_mod:
    command: toast
    message: Hello, world!
```
This actually seems similar to issue https://github.com/home-assistant/frontend/issues/9436 regarding using a button in an entities card.
