### ISSUE TITLE
Script trace has a third stub for state condition

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#9536]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When tracing a script with a state condition as the first item in the sequence the trace is drawn with a third stub:

![Screenshot 2021-07-10 at 00-37-31 Configuration - Home Assistant](https://user-images.githubusercontent.com/10679300/125100332-50734e80-e11c-11eb-8839-2d7ae509678c.png)

### Describe the behavior you expected

Two options, the condition passes to the next item in the sequence or not (X).

### Steps to reproduce the issue

1. Trace a script with a state condition as the first step in the sequence
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.7.1

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.124, Firefox 89.0.2

### Which operating system are you using to run this browser?

Windows 10

### Additional information

Script config:

```
lounge_tv_on:
  sequence:
  - condition: state
    entity_id: media_player.viera_st50_series
    state: 'off'
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.lounge_av_rx
        state: 'off'
      sequence:
      - service: media_player.turn_on
        entity_id: media_player.lounge_av_rx
      - delay: 3
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.lounge_av_rx
        attribute: source
        state: 'Kodi'
      sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.lounge_av_rx
          source: "Lounge PC"
      - delay: 3
  - service: media_player.select_source
    data:
      entity_id: media_player.lounge_av_rx
      source: "Kodi"
  - repeat:
      sequence:
      - service: homeassistant.update_entity
        entity_id: media_player.viera_st50_series
      - delay: 2
      until:
      - condition: or
        conditions:
        - "{{ repeat.index >= 30 }}"
        - "{{ is_state('media_player.viera_st50_series', 'on') }}"
```
