### ISSUE TITLE
a hold action shows the iPhone Share, Add to photos, Copy pop up.

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9549]
> A Safari browser on the same iPhone does execute the action.

I am not able to reproduce this -- but no matter what, the fix needs to be in the frontend (using the CSS mentioned above). Feel free to re-open over there, if it's the base picture entity and nothing custom.

_Originally posted by @zacwest in https://github.com/home-assistant/iOS/issues/1698#issuecomment-877732770_

recap:

```
  - type: entities
    entities: []
    header:
      type: picture
      image: /local/weather/weatherbit.png
      tap_action:
        action: url
        url_path: !secret weatherio_api_url
      hold_action:
        action: call-service
        service: homeassistant.reload_config_entry
        service_data:
          entry_id: 79ae77f927714985b1046191c05f2b5c
```

performs Ok when in a regular safari browser window on the iPhone. In the App however, a hold action shows the Share, Add to photos, Copy pop up.

according to Zac, this should be done:

> needs to disable this via webkit-touch-callout, see [lovelace version](https://sourcegraph.com/github.com/home-assistant/frontend@df1ca1fd96e3f9b1aa8c2429b396fac82f2cc767/-/blob/src/panels/lovelace/elements/hui-image-element.ts?L66:23).

**Comment by smart-ctrl** [comment]
Got the same problem with hold action when using a picture-entity card and the Home Assistant iOS app.

**Comment by Mariusthvdb** [comment]
would it be possible to have somebody have a look at this? it really is an annoying bug and takes away from the frontend functionality. P{lease let me know if I can help to fix

**Comment by Mariusthvdb** [comment]
Don't close please, nothing changed ...

**Comment by Mariusthvdb** [comment]
Still happening in 2022.5 dev

**Comment by Mariusthvdb** [comment]
Still happening in 2022.8 dev

**Comment by Mariusthvdb** [comment]
Still happening

**Comment by Mariusthvdb** [comment]
and still on 2022.11

just now, I realized its not only happening on posted service above, but also eg on this navigate within the Ha frontend:
```
    type: picture-entity
    entity: input_boolean.ventilate
    name: Ventilate
    image: /local/images/ventilate.png
    state_filter:
      'off': grayscale(72%)
    tap_action:
      action: toggle
    hold_action:
      action: navigate
      navigation_path: /ui-data/climate
```

Holding brings up the identical IOS popup, instead of executing the service..

**Comment by Mosher23** [comment]
Why os this „closed“?!
I have same issue since I can remember using HA.
Example to reproduce:
Muschroom Template card picture instead of icon. Long press set to toggle. 
long pressing on iphone opens system Preview/share menu on iphone.

**Comment by Mariusthvdb** [comment]
please only comment with core elements, otherwise the devs tend to state its the custom element causing the issue.


this btw hasn't been closed, it is wide open for more than a year now, without as much as a blink of a Frontend dev's eye, not a single response. as if this just doesn't exist.

iOS app Zac even pointed to the solution https://github.com/home-assistant/iOS/issues/1698#issuecomment-877684390 . I don't understand that, but the Frontend devs would I suppose....

**Comment by JGKarlin** [comment]
The hold tap action doesn't work on iOS devices if that entity is displayed in lovelace with an image. It's hard to believe that this issue is not being addressed.

**Comment by Mariusthvdb** [comment]
yes, really peculiar.


moed away from the opening config, but this is a fine example too:
```
  - type: picture-entity
    show_state: false
    show_name: false
    entity: camera.weer_roosendaal
    hold_action:
      action: url
      url_path: https://www.yr.no/en/forecast/graph/2-2747930/Netherlands/North%20Brabant/Roosendaal/Roosendaal
```

no url opening, just the mentioned share dialog. iOS app only

**Comment by Mariusthvdb** [comment]
keep

**Comment by Mariusthvdb** [comment]
Keep

**Comment by Mariusthvdb** [comment]
Keep

**Comment by Mariusthvdb** [comment]
Keep

**Comment by Mariusthvdb** [comment]
well, keep

**Comment by Mariusthvdb** [comment]
keep

**Comment by Mariusthvdb** [comment]
.... keep

**Comment by Mariusthvdb** [comment]
2025.12
still happening

**Comment by Mariusthvdb** [comment]
2026.3….

**Comment by ellegamee** [comment]
@Mariusthvdb 

Hello hello, I am looking at older issues and found this issue and wanted to clear things up as I was confused for the first 5 minutes.

What you mean is that the "hold_action" stated inside of your yaml config is not overriding iOS own functions for holding on an image. What needs to be done is to override that functionality and let HA own action take over?

**Comment by Mariusthvdb** [comment]
HI
thanks for looking into this.

yes, that would be what is happening. Zac has written what he thought needs to be done, and I copied that in the opening post.

HA action would need to be leading, not iOS native if that is that is happening.

**Comment by ellegamee** [comment]
I've identified that picture-header-footer.ts requires updated CSS to prevent the iOS native "hold action" (context menu) from interfering with the custom functionality. I am currently working on a fix to ensure the hold action fires correctly on iOS.

CSS Changes:
I have implemented the following styles in my local environment to suppress native iOS behaviors:

```
TypeScript
static styles = css`
  div.clickable {
    -webkit-touch-callout: none !important;
    -webkit-user-select: none !important;
    user-select: none !important;
    display: block;
    width: 100%;
    touch-action: none !important;
    cursor: pointer;
  }

  img {
    display: block;
    width: 100%;
    pointer-events: none; 
    -webkit-touch-callout: none !important;
    -webkit-user-drag: none;
  }
`;
```

Current Issue:
The primary challenge right now is that iOS blocks navigation triggered by a hold action. Since the navigation occurs after a delay (wait), the OS does not register it as a direct user-initiated event, causing the browser to block the action. I am looking into a workaround for this.

**Comment by ellegamee** [comment]
@Mariusthvdb sat with the issue for the last hour and got my head around the issue. The PR is on the way but may take time before being merged if all looks good.

**Comment by Mariusthvdb** [comment]
> [@Mariusthvdb](https://github.com/Mariusthvdb) sat with the issue for the last hour and got my head around the issue. The PR is on the way but may take time before being merged if all looks good.

that would be truly great, thank you very much! Imagine how long we havent been able to use a hold action in iPhone!

**Comment by Mariusthvdb** [comment]
this seems to be not fixed at all yet, a simple card still shows the same issue
```
type: vertical-stack
cards:
  - type: picture
    image: /local/images/balloons.png
```

of course this is a extremely abridged card, but it shows the iOS menu still shows when holding a picture.

even setting all actions to none does not prevent that from happening (it does work on Desktop, hiding the change of the pointer completely)
```
  - type: picture
    image: /local/images/balloons.png
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
```

please re-open and inspect
