### ISSUE TITLE
History-Graph timeline sometimes not showing different colors for unique states

### ISSUE THREAD

**Issue by tylerpieper** [home-assistant/frontend#9554]
I have a template sensor that is gathering the current state of each thermostat (idle, heating, cooling). Up until now, each state would show a different color on the history graph card, but now each state shows the same color, making it very hard to read. 

The card in question:
![image](https://user-images.githubusercontent.com/54639597/125359219-d1019d00-e31e-11eb-85e8-ef8bd3826db6.png)

The YAML for the card:
```
type: history-graph
entities:
  - entity: sensor.upstairs_hvac_status
    name: Upstairs
  - entity: sensor.downstairs_hvac_status
    name: Downstairs
  - entity: sensor.hvac_duty
    name: Combined
hours_to_show: 2
refresh_interval: 0
```

The two sensors in question (within Sensors.yaml) (I know I should be using state_attr):
```
- platform: template
  sensors: 
    downstairs_hvac_status:
      friendly_name: "Downstairs HVAC Status"
      value_template: '{{ states.climate.downstairs.attributes.hvac_action }}'
- platform: template
  sensors: 
    upstairs_hvac_status:
      friendly_name: "Upstairs HVAC Status"
      value_template: '{{ states.climate.Upstairs.attributes.hvac_action }}'
```

And the state attributes of one of the thermostats (climate.downstairs) (they are both identical):
```
hvac_modes:
  - 'off'
  - heat
  - cool
  - heat_cool
min_temp: 50
max_temp: 90
current_temperature: 77
temperature: 77
hvac_action: idle
friendly_name: Downstairs Thermostat
supported_features: 1
```
The thermostats are Honeywell Lyrics controlled via Homekit Controller. The hvac_action can be idle, cool, or heat (at least with my HVAC configuration).

_Originally posted by @tylerpieper in https://github.com/home-assistant/frontend/issues/9495#issuecomment-875826241_

Since I submitted via my comment on another issue, it appears I have bypassed the form. I will complete it below:
**I have updated to the latest available Home Assistant version. 
I have cleared the cache of my browser. 
I have tried a different browser to see if it is related to my browser.** 

**Describe the issue you are experiencing:** The history graph card sometimes does not use a different color for each state in a timeline. For example, monitoring my HVAC status, I'll see states of "cool" and "idle" throughout the day, but the graph will show the same light blue for both.

**Describe the behavior you expected:** I would expect the card will be rendered with a unique color for each unique state, so they can be easily differentiated.

**Steps to reproduce the issue:** 
1. Log into Home Assistant (I'm using the Nabu Casa cloud access)
2. View a dashboard with a history-graph card that shows a timeline
3. Sometimes you get different colors for each state, sometimes they are all blue

**What version of Home Assistant Core has the issue?** Previously 2021.7.0 but I just updated to 2021.7.1 and will close if it resolves this. 

**What was the last working version of Home Assistant Core?** 2021.6.x, before the overhaul of the history-graph card

**In which browser are you experiencing the issue with?** Google Chrome 91.0.4472.124

**Which operating system are you using to run this browser?** Windows 10 21H1
