### ISSUE TITLE
Rows on entities control no longer display correctly

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#9580]
### The problem

The Image, text and state should be on the same line, instead it shows like this:
![image](https://user-images.githubusercontent.com/1435262/126135588-9c630cbb-1c7e-4e38-a50b-d10c47eededc.png)

### What is version of Home Assistant Core has the issue?

2021.7.3

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

entities

### Example YAML snippet

```yaml
type: entities
entities:
  - entity: binary_sensor.door_window_sensor_158d0003e79fbc
```
