### ISSUE TITLE
Entities Card show different icon for the same entity under condition

### ISSUE THREAD

**Issue by DariusLapinskas** [home-assistant/frontend#9585]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Entities Card the same entity under conditional row display different icon than the same entity as usual row.
![image](https://user-images.githubusercontent.com/29358431/126220905-9b98495e-7a0f-49e4-b0bb-8da0e2fdd2f1.png)

### Describe the behavior you expected

I expect entity icon to be the same in both cases.

### Steps to reproduce the issue

1. Use Android app to get phone changing status
2. Use "Problem-relevant frontend configuration"

### What version of Home Assistant Core has the issue?

core-2021.7.3

### In which browser are you experiencing the issue with?

Firefox, HA Android app

### Which operating system are you using to run this browser?

Windows 7, Android 10

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - type: section
  - entity: sensor.nokia_7_2_battery_level
    name: Battery Level
  - entity: binary_sensor.nokia_7_2_is_charging
    name: Power Status
  - type: section
  - type: conditional
    conditions:
      - entity: binary_sensor.nokia_7_2_is_charging
        state_not: 'off'
    row:
      entity: binary_sensor.nokia_7_2_is_charging
      name: Power Status
title: Nokia Zona
state_color: true
```

**Comment by spacegaier** [comment]
I think everything behaves as designed, even if perhaps not expected.

Below `row` of the conditional element, you define a completely new element, to which you can also add `state_color` which then enables the coloring for that. The `state_color` from the entities card itself is not "forwarded". This allows for some additional flexibility.

```
type: entities
entities:
  - entity: binary_sensor.car_windows_closed
    name: Power Status
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state_not: 'off'
    row:
      entity: binary_sensor.car_windows_closed
      name: Power Status
      state_color: true
title: Nokia Zona
state_color: true
```

![image](https://user-images.githubusercontent.com/114137/132258003-d8930e62-067d-4959-a361-81c046b0ed71.png)
