### ISSUE TITLE
Onboarding broken when using Firefox 90.0.2

### ISSUE THREAD

**Issue by akuma6099** [home-assistant/frontend#9646]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

New user to HA. Created a new VMware instance and attached the OS version (haos_ova-6.1.vmdk). Adjusted to UEFI and booted up fully. Navigated to the Web UI on 8123 and upon entering name, username, and password clicking next I receive an "Awe snap" alert telling me something went wrong and to refresh the page. Console message states:

```
Uncaught TypeError: this.listeners.onopen is not a function
    onOpen onboarding.html:55
    value onboarding.4d22a1c9.js:36353
```

I cannot get onboarding.html to load cleanly. I refresh, login, then awe snap again. I then decided to try Docker instead and received the same console message and behavior.

:composer.yaml:
```
version: "3"
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
          ip_range: 192.168.3.15/28
          gateway: 192.168.3.254

services:
  hass:
    container_name: hass
    restart: unless-stopped
    privileged: true
    image: homeassistant/home-assistant
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
    networks:
      backend:
        ipv4_address: 192.168.3.1
```

Using Firefox 90.0.2. Switched to Chrome (92.0.4515.107) and had no problems at all. I tried disabling enhanced tracking as well as cookie restrictions and a few other settings but FF doesn't work correctly.

### Describe the behavior you expected

After providing the inital HA setup info name, username, and password I expected to be brought to onboarding.html to enter location info and TZ. This page fails to load and produces a JS console error within the browsers developer tools.

### Steps to reproduce the issue

1. Create new VMWare VM using recommended settings (2 Cores, 4GB RAM)
2. Attached VMWare OS disk image provided by home assistant: haos_ova-6.1.vmdk
3. Adjust VMWare BIOS type to UEFI.
4. Boot VMware instance
5. After fully loading, navigate to Web UI for initial setup on port 8123 using Firefox's latest version 90.0.2
6. Fill out initial form providing name, username, and password and click next.
7. Error dialog appears and JS console message is logged.

### What version of Home Assistant Core has the issue?

core-2021.7.4

### In which browser are you experiencing the issue with?

Firefox 90.0.2

### Which operating system are you using to run this browser?

Windows 10 Pro 21H1

### Problem-relevant frontend configuration

```yaml
None. This is a fresh install.
```

### Javascript errors shown in your browser console/inspector

```txt
Uncaught TypeError: this.listeners.onopen is not a function
    onOpen onboarding.html:55
    value onboarding.4d22a1c9.js:36353
```
