### ISSUE TITLE
Gauge card doesn't allow to control height

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#9730]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If text length for the cards in the grid is has different rows due to the length, then there is no way to align the  graphics.
See screenshot above.

### Describe the behavior you expected

Allow a way to align cards either manually or, preferred, automatically.

### Steps to reproduce the issue

1. Create a grid card with 4 gauge
2. Name those with different text, at least one of which should wrap on a second row
3. Check graphics as it's not aligned.

### What version of Home Assistant Core has the issue?

2021.8.1

### In which browser are you experiencing the issue with?

Microsoft Edge - Version 92.0.902.62 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 build 21H1

### Problem-relevant frontend configuration

```yaml
cards:
  - type: gauge
    entity: sensor.custom_indice_di_thom_salotto
    name: Salotto
    needle: true
    unit: ' '
    min: 18
    max: 42
    severity:
      green: 18
      yellow: 23
      red: 33
  - type: gauge
    entity: sensor.custom_indice_di_thom_studio
    name: Studio
    needle: true
    unit: ' '
    min: 18
    max: 42
    severity:
      green: 18
      yellow: 23
      red: 33
  - type: gauge
    entity: sensor.custom_indice_di_thom_camera_da_letto
    name: Camera da letto
    needle: true
    unit: ' '
    min: 18
    max: 42
    severity:
      green: 18
      yellow: 23
      red: 33
  - type: gauge
    entity: sensor.custom_indice_di_thom_camera_degli_ospiti
    name: Camera degli ospiti
    needle: true
    unit: ' '
    min: 18
    max: 42
    severity:
      green: 18
      yellow: 23
      red: 33
title: Indice di Thom
type: grid
columns: 4
```

### Additional information

![image](https://user-images.githubusercontent.com/57354320/128434604-b9ba94b3-3bf1-4e23-abf3-42536aedf5aa.png)
