### ISSUE TITLE
Kubernetes. rotating cluster IP, static IP for trusted_proxies unavailable 

### ISSUE THREAD

**Issue by GoingOffRoading** [home-assistant/frontend#9749]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have HASS deployed via Docker in Kubernetes cluster instead of the usual single host Docker, VM, RPi, or etc.  HASS sits behind Traefik for reverse proxy and letsencrypt.  In Kuberentes, the cluster IP changes on startup, even if the host machine has a static IP (these things are not related in Kubernetes).  On cluster startup, a new cluster IP is generated for each of the pod (container) networks and the IP address required for trusted_proxies changes.  So on each startup, the HASS logs have to be reviewed to get the new network IP, and then HASS configuration.yaml has to be edited for the new trusted_proxies IP.  

This would also apply for the user_x_forward_for outlined in the documentation: https://www.home-assistant.io/integrations/http/#reverse-proxies  

### Describe the behavior you expected

That on Kuberentes startup, that I do not need to edit the trusted_proxies in configuration.yaml for the UI to be accessible from the reverse proxy.

### Steps to reproduce the issue

1.Deploy HASS in Docker to Kubernetes
2.Deploy NGINX, Trafeik, or any other reverse proxy solution for HASS
3.Change the Configuration.yaml trusted_proxies field to reflect the cluster IP of the reverse proxy, as provided by the server logs when the UI gives the HTTP 400 error
...

### What version of Home Assistant Core has the issue?

core-2021.8.4

### What was the last working version of Home Assistant Core?

core-2021.7.4 

### In which browser are you experiencing the issue with?

Chrome, Firefox, Edge - Latest Builds

### Which operating system are you using to run this browser?

Windows 10 Pro- Version	10.0.19043 Build 19043

### Problem-relevant frontend configuration

```yaml
http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 10.32.0.21
```
