### ISSUE TITLE
Since the august update "reload resources" no longer reloads correctly.

### ISSUE THREAD

**Issue by dogmatic69** [home-assistant/frontend#9793]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

lovelace is split into multiple files. Before the august update I could simply make a change to one of my views and then hit "reload resources". Sometimes I would have to `shift + F5` (iirc it used to reload the page when clicking reload). 

Now it does absolutely nothing. No errors in console or the logs, no changes to the page

I've tried clearing the cache, forcing edits to ui-lovelace.yaml etc 

The only reliable way to make it update now is to restart HA

### Describe the behavior you expected

UI should be updated to reflect the changes made to the lovelace config

### Steps to reproduce the issue

1. update lovelace config
2. click reload resources
3. UI is not updated

### What version of Home Assistant Core has the issue?

core-2021.8.6

### What was the last working version of Home Assistant Core?

core-2021.7.x

### In which browser are you experiencing the issue with?

Google chrome 92.0.4515.131 (Official Build) (64-bit) 

### Which operating system are you using to run this browser?

Windows 10 / Ubuntu 21

### Problem-relevant frontend configuration

```yaml
# ui-lovelace.yaml
title: Home Automation
kiosk_mode:
  user_settings:
    - users:
      kiosk: true
        - home
      hide_sidebar: true

views: !include_dir_list lovelace_ui/
```

and

```
# example from lovelace_ui/
title: Media
icon: mdi:television
path: media
cards:
  - type: vertical-stack
    cards:
      - type: media-control
        entity: media_player.lg55
      ....
  ....
```
```


### Javascript errors shown in your browser console/inspector

```txt
None
```
