### ISSUE TITLE
Guage card doesn't show negative background with needle:true  configured

### ISSUE THREAD

**Issue by fancygaphtrn** [home-assistant/frontend#9807]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Guage card would previously show the arc with negative values configured.   It now sizes based on the negative but arc (color) stops at 0, when needle is true

This is for the net energy from my solar.   It sometimes produces and sometimes consumes.
            cards:
              - type: gauge
                entity: sensor.trimetric_watts
                needle: true
                min: -2000
                max: 2000
                severity:
                  green: 0
                  yellow: -125
                  red: -1400

### Describe the behavior you expected

Render negative values 

### Steps to reproduce the issue

Add needle: true to a guage card with negative values

### What version of Home Assistant Core has the issue?

Home Assistant 2021.8.6

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Chrome Version 92.0.4515.131

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
na
```

### Problem-relevant frontend configuration

```yaml
cards:
              - type: gauge
                entity: sensor.trimetric_watts
                needle: true
                min: -2000
                max: 2000
                severity:
                  green: 0
                  yellow: -125
                  red: -1400
```

### Javascript errors shown in your browser console/inspector

```txt
na
```

### Additional information

na
