### ISSUE TITLE
Data of statistics-graph not visible to non-administrator user

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/frontend#9818]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My wife is having a non-administrator account inside our Home Assistant installation.
Since changing the Lovelace cards from type: sensor to type: statistics-graph. She’s not able to view the data anymore (both live and history are not visible), while I am able to view the data on the Lovelace dashboard.

### Describe the behavior you expected

Both administrator and non-administrator users being able to see the statistics-graph.

### Steps to reproduce the issue

1. Create a Lovelace card with type: statistics-graph
2. Login to Home Assistant as a non-administrator user
3. Don't see this statistics-graph

### What version of Home Assistant Core has the issue?

core-2021.8.6

### What was the last working version of Home Assistant Core?

Never, as this is introduced in 2021.8

### In which browser are you experiencing the issue with?

Brave Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit) & Also not working in Home Assistant app iOS

### Which operating system are you using to run this browser?

Windows 10 21H1 & iOS 2021.8

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
title: Logeerkamer
cards:
  - type: sensor
    entity: sensor.logeerkamer_temperatuur
    graph: line
    detail: 2
    name: Temperatuur
  - type: statistics-graph
    days_to_show: 1
    entities:
      - sensor.logeerkamer_luchtvochtigheid
    chart_type: line
    title: Luchtvochtigheid
    stat_types:
      - min
      - max
      - sum
      - mean
```
