### ISSUE TITLE
Total Costs Entity list shows only kWh sensors

### ISSUE THREAD

**Issue by mikesmitty** [home-assistant/frontend#9844]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the grid consumption setup, selecting "Use an entity tracking the total costs" shows a list of only sensors with `unit_of_measurement: kWh`.

### Describe the behavior you expected

The "Total Costs Entity" list should at least include sensors that have `unit_of_measurement` set to a currency.

### Steps to reproduce the issue

1. Add Grid Consumption sensor
2. Select "Use an entity tracking the total costs"
3. Try to find sensor in list that is not `unit_of_measurement: kWh`

### What version of Home Assistant Core has the issue?

core-2021.8.8

### In which browser are you experiencing the issue with?

Google Chrome 92.0.4515.159

### Which operating system are you using to run this browser?

Ubuntu 20.04

### Problem-relevant frontend configuration

```yaml
Template sensor yaml:

template: !include_dir_merge_list template
```

```
- unique_id: electric
  sensor:
  # Take power usage this month so far and estimate the current bill
  - name: Electric Bill
    state_class: measurement
    unit_of_measurement: '$'
    state: "{{ 23.75 + (states('sensor.energy')|float * (0.10336 + 0.07003)) |round(2) }}"
          # Dist Chg + ( kWh usage * (Delivery Fees + Supply Charge))
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

**Comment by bramkragten** [comment]
Make sure the total cost entity is enabled for long term statistics <https://developers.home-assistant.io/docs/core/entity/sensor#entities-tracking-a-total-amount> (this is documentation for the next HA version)

**Comment by mikesmitty** [comment]
Hey @bramkragten, I appreciate the link, though I've read (the current release version of) it a few times already, as it's linked in the list. I pasted my template sensor config up top that shows it using `state_class: measurement`, which seems to be what's required to opt-in?

The reason I think it's a bug is because under the "Use an entity with current price" option my template sensor does show up, among a variety of other sensors, but under "Total Costs Entity", absolutely nothing but the kWh sensors show up.

**Comment by mikesmitty** [comment]
Am I just missing that there's some way of telling if a sensor has opted into long term statistics? I see that the docs say that "entities opt-in based on their device class", but setting the device class to energy (like all the others in the list) also doesn't allow it to show up. Are there specific device classes that do/don't opt in?

**Comment by bramkragten** [comment]
It needs device class monetary

**Comment by mikesmitty** [comment]
If anyone sees this in the future, you need state_class, device_class, and a dummy last_reset attribute.
```
- sensor:
  # Take power usage this month so far and estimate the current bill
  - name: Electric Bill
    state_class: measurement
    device_class: monetary
    unit_of_measurement: '$'
    state: "{{ 23.75 + (states('sensor.energy')|float * (0.10336 + 0.07003)) |round(2) }}"
          # Dist Chg + ( kWh usage * (Delivery Fees + Supply Charge))
    attributes:
          last_reset: '1970-01-01T00:00:00+00:00'
```
