### ISSUE TITLE
Growatt integration does not show up for diplay in HA Energy

### ISSUE THREAD

**Issue by TSD858** [home-assistant/frontend#9848]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I want to add my solar panels to HA Energy. I have a Growatt inverter, so I use the Growatt integration. 

However, the Growatt entities do not show up in the list of sources, see below

![HA_growatt](https://user-images.githubusercontent.com/48689582/130110129-917e4b9a-0f1f-4787-9135-55173dc17271.jpg)

### Describe the behavior you expected

I would have expected to add the energy generated by my solar panels to HA Energy

### Steps to reproduce the issue

1. Go to Setting -> Energy
2. Add Solar panels
3. Find Growatt in the list ;-)
...

### What version of Home Assistant Core has the issue?

core-2021.8.7

### What was the last working version of Home Assistant Core?

core-2021.8.7

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: dsmr
    port: /dev/ttyUSB0
    dsmr_version: 5
    precision: 4

group:
  meter_readings:
    name: Meter readings
    entities:
      - sensor.energy_consumption_tarif_1
      - sensor.energy_consumption_tarif_2
      - sensor.energy_production_tarif_1
      - sensor.energy_production_tarif_2
  meter_power:
    name: Vermogen per fase
    entities:
      - sensor.power_consumption_phase_l1
      - sensor.power_consumption_phase_l2
      - sensor.power_consumption_phase_l3
  meter_current:
    name: Stroom per fase
    entities:
      - sensor.current_phase_l1
      - sensor.current_phase_l2
      - sensor.current_phase_l3
  meter_voltage:
    name: Spanning per fase
    entities:
      - sensor.voltage_phase_l1
      - sensor.voltage_phase_l2
      - sensor.voltage_phase_l3
```
