### ISSUE TITLE
Call_Service config validation issue

### ISSUE THREAD

**Issue by dcs8** [home-assistant/frontend#9854]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an entities card with the following config that is throwing many "Required key "entities.0.entity" is missing" errors

```type: entities
show_header_toggle: false
state_color: true
entities:
  - type: buttons
    entities:
      - entity: sensor.thermostat_boost
        name: Heating Boost
        tap_action:
          action: call-service
          service: hive.boost_heating
          service_data:
            entity_id: climate.thermostat
            time_period: '00:45:00'
            temperature: 23
```
If I remove the tap_action: line and everything below it, the error goes away. The card itself displays ok on my frontend and if I click the button, it calls the service as expected. But as it's throwing errors, I can't click 'Close' in the card editor - I have to use the raw config editor to edit the card

I am using the hive custom component but the same issue happens when calling any service. I asked about this on discord and was asked to raise an issue as it may be that the config validation is set too strict

The full error I receive is:

Configuration errors detected:
Required key "entities.0.entity" is missing.
Required key "entities.0.name" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.conditions" is missing.
Required key "entities.0.url" is missing.
Required key "entities.0.entity" is missing.
Required key "entities.0.attribute" is missing.
Required key "entities.0.name" is missing.
Required key "entities.0.service" is missing.
Required key "entities.0.name" is missing.
Required key "entities.0.text" is missing.

### Describe the behavior you expected

No "Required key "entities.0.entity" is missing" errors, meaning I am able to click 'Close' from card editor

### Steps to reproduce the issue

1 Create a new card with this config (it's fairly nonsensical but should be possible on any home assistant installation)

```type: entities
show_header_toggle: false
state_color: true
entities:
  - type: buttons
    entities:
      - entity: sun.sun
        name: Heating Boost
        tap_action:
          action: call-service
          service: input_boolean.reload
```
### What version of Home Assistant Core has the issue?

2021.8.8

### In which browser are you experiencing the issue with?

Version 92.0.4515.131

### Which operating system are you using to run this browser?

Windows 10 Pro 21H1

### Problem-relevant frontend configuration

```yaml
type: entities
show_header_toggle: false
state_color: true
entities:
  - type: buttons
    entities:
      - entity: sensor.thermostat_boost
        name: Heating Boost
        tap_action:
          action: call-service
          service: hive.boost_heating
          service_data:
            entity_id: climate.thermostat
            time_period: '00:45:00'
            temperature: 23
```
