### ISSUE TITLE
Users unable to call service cast/show_lovelace_view

### ISSUE THREAD

**Issue by DataBitz** [home-assistant/frontend#9884]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a user is logged into Home Assistant and tries to use a lovelace panel button which is configured to cast.show_lovelace_view. The message is returned that this is Unauthorized and the action is not completed.

### Describe the behavior you expected

Lovelace view to be cast to device selected.
Users can already access this button so should be able to use the buttons which are available to them.

### Steps to reproduce the issue

1. Create a add a button card containing the following to a view.
tap_action:
  action: call-service
  service: cast.show_lovelace_view
  service_data:
    entity_id: media_player.android_tv
    dashboard_path: lovelace-home
    view_path: holly-cam
  target: {}
2. Create a User in Home Assistant
3. Login as the User to Home Assistant, access the view and press the button card.
4. Observe error displayed "Failed to call service cast/show_lovelace_view. Unauthorized"

### What version of Home Assistant Core has the issue?

core-2021.8.8

### In which browser are you experiencing the issue with?

Various

### Which operating system are you using to run this browser?

Various

### Problem-relevant frontend configuration

```yaml
tap_action:
  action: call-service
  service: cast.show_lovelace_view
  service_data:
    entity_id: media_player.android_tv
    dashboard_path: lovelace-home
    view_path: holly-cam
  target: {}
```
