### ISSUE TITLE
Markdown: No display with content from template returning int / float

### ISSUE THREAD

**Issue by koying** [home-assistant/frontend#9891]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Ref: https://community.home-assistant.io/t/markdown-card-is-acting-up/331718?u=koying

Nothing is displayed in a markdown card if the content resulting from a template is an in or float

### Describe the behavior you expected

Numbers are displayed

### Steps to reproduce the issue

Test card:

1. Displays nothing

```yaml
type: markdown
content: '{{ 23.75 }}'
title: Test numbers
````

2. Displays as expected:

```yaml
type: markdown
content: '{{ 23.75 }} eur'
title: Test numbers
```

### What version of Home Assistant Core has the issue?

2021.8.7

### In which browser are you experiencing the issue with?

Firefox 91.0.1

### Which operating system are you using to run this browser?

Windows 10
