### ISSUE TITLE
Error rendering automation graph with empty sequence

### ISSUE THREAD

**Issue by dadler** [home-assistant/frontend#9901]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a working automation but the automation trace graph renderer shows "Error rendering graph. Please download trace and share with the developers. ".

This seems to happen when I have an action with an empty sequence (which is that way since I've temporarily removed the action during testing, but am keeping the enclosing choice since I still want the 'default' which follows).

A workaround is to add a 'delay: 00:00:00' as a no-op in the sequence.

### Describe the behavior you expected

I expected the Automation to show its trace successfully.

### Steps to reproduce the issue

1. Add this automation (you do NOT need to create helper input_boolean.dummy_switch):
```
- id: '999999'
  alias: automation bug demo
  trigger:
  - platform: state
    entity_id: input_boolean.dummy_switch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.dummy_switch
        state: 'on'
      sequence:
```
2. reload automations
3. In Automations config, click "RUN ACTIONS" on this automation ("automation bug demo")
4. In Automations conflg, click the "trace" button for "automation bug demo".
5. Notice error message in left panel, "Error rendering graph. Please download trace and share with the developers." 

### What version of Home Assistant Core has the issue?

2021.8.8

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Google Chrome 92.0.4515.159, Firefox

### Which operating system are you using to run this browser?

MacOS Big Sur 11.5

### Javascript errors shown in your browser console/inspector

```txt
none
```
