### ISSUE TITLE
Regression for attribute's format in entities card

### ISSUE THREAD

**Issue by mbo18** [home-assistant/frontend#9961]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

`format` for `type:attribute` seems to be no more supported by the visual editor for entities card.

`format` is in the documentation for attribute, see: https://www.home-assistant.io/lovelace/entities/#attribute

### Describe the behavior you expected

`format` should be valid and should not raise an error in the editor (works fine when editing raw config)

### Steps to reproduce the issue

1. edit or add an entities card
2. add an attribute:
```yaml
entities:
  - type: attribute
    entity: sun.sun
    attribute: next_rising
    name: Levé du soleil
```
3. add format to it:
```yaml
entities:
  - type: attribute
    entity: sun.sun
    attribute: next_rising
    name: Levé du soleil
    format: datetime
```

editor then display a lot of errors:

Configuration errors detected:

    Required key "entities.0.tap_action" is missing.
    Required key "entities.0.tap_action" is missing.
    Required key "entities.0.tap_action" is missing.
    Required key "entities.0.tap_action" is missing.
    Required key "entities.0.tap_action" is missing.
    Required key "entities.0.tap_action" is missing.
    Required key "entities.0.view" is missing.
    Required key "entities.0.view" is missing.
    Required key "entities.0.view" is missing.
    Required key "entities.0.conditions" is missing.
    Required key "entities.0.url" is missing.
    Required key "entities.0.entities" is missing.
    Required key "entities.0.service" is missing.
    Required key "entities.0.text" is missing.
    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.tap_action" is missing.
    Required key "entities.1.tap_action" is missing.
    ...

### What version of Home Assistant Core has the issue?

core-2021.9.3

### In which browser are you experiencing the issue with?

Firefox and Safari latest release

### Which operating system are you using to run this browser?

macOS Catalina

### Problem-relevant frontend configuration

```yaml
entities:
  - type: attribute
    entity: sun.sun
    attribute: next_rising
    name: Levé du soleil
    format: datetime
```

### Additional information

Could you also add support for `icon:` for `type:attribute`?

It works when editing raw config but is not supported by the visual editor. See: https://github.com/home-assistant/frontend/issues/9959 or https://github.com/home-assistant/frontend/issues/9586
