### ISSUE TITLE
Dashboard not loading - Problems with Picture-Elements

### ISSUE THREAD

**Issue by MaxxKra** [home-assistant/frontend#9968]
### The problem

My default dashboard keeps reloading the individual images after the update. A permanent function is no longer possible since then.
![Dashboard_good](https://user-images.githubusercontent.com/83531755/132136394-fdc6519f-db1c-457f-b601-445049b69049.PNG)
![Dashboard_broken](https://user-images.githubusercontent.com/83531755/132136514-509f6c71-228b-40ab-ad07-73dc68e21ecb.PNG)
Narrowing down the error has shown that it is due to the "Picture-Elements" and the "custom:config-template-card".
However, a template is necessary to display the LED colours as an image on the dashboard.

### What is version of Home Assistant Core has the issue?

core-2021.9.x

### What was the last working version of Home Assistant Core?

core-2021.8.8

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Lovelace Dahboard

### Link to integration documentation on our website

https://www.home-assistant.io/lovelace/picture-elements/

### Example YAML snippet

```yaml
type: custom:config-template-card  
card:
  type: picture-elements
  image: /local/lovelace/touchpc/_0031_background.png
```
