### ISSUE TITLE
Problems with Picture-Elements

### ISSUE THREAD

**Issue by holdestmade** [home-assistant/frontend#9988]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Have an issue with `picture_elements `taking a long time to load, using only HA picture elements cards and 100x100px icons on a background image, all in www folder.
It is only since updating to 2021.9. Blue spinning circles and takes anything up to 20 seconds to load all the icons (before it was instant, never saw any loading)

Issue is on Chrome and Android HA app.

![1](https://user-images.githubusercontent.com/13977244/132487741-07df9a3d-e551-45b8-98ef-050027028e8d.png)

### Describe the behavior you expected

Not seeing the blue spinning circles as in 2021.8

### Steps to reproduce the issue

1. Picture elements cards with 100x100px icons
2.
3.
...
s=

### What version of Home Assistant Core has the issue?

2021.9

### What was the last working version of Home Assistant Core?

2021.8

### In which browser are you experiencing the issue with?

Chrome Version 93.0.4577.63 (Official Build) (64-bit)
Android HA App

### Which operating system are you using to run this browser?

Windows

### Problem-relevant frontend configuration

```
type: picture-elements
image: /local/images/BG_BINStrans.png
elements:
  - type: image
    entity: sensor.green_bin_days
    image: /local/images/green_bin2.png
    title: null
    state_filter:
      "unavailable": grayscale(100%) drop-shadow(0px 0px 2px Red)
      "Today": drop-shadow(0px 0px 3px Green) saturate(200%)
      "Tomorrow": drop-shadow(0px 0px 3px Green) saturate(150%)
    style:
      top: 65%
      left: 15%
      width: 15%
  - type: state-label
    entity: sensor.green_bin_days
    tap_action:
      action: none
    hold_action:
      action: none
    style:
      top: 35%
      left: 15%

  - type: image
    entity: sensor.brown_bin_days
    image: /local/images/brown_bin2.png
    title: null
    state_filter:
      "unavailable": grayscale(100%) drop-shadow(0px 0px 2px Red)
      "Today": drop-shadow(0px 0px 3px Brown) saturate(200%)
      "Tomorrow": drop-shadow(0px 0px 3px Brown) saturate(150%)
    style:
      top: 65%
      left: 50%
      width: 15%
  - type: state-label
    entity: sensor.brown_bin_days
    tap_action:
      action: none
    hold_action:
      action: none
    style:
      top: 35%
      left: 50%

  - type: image
    entity: sensor.blue_bin_days
    image: /local/images/blue_bin2.png
    title: null
    state_filter:
      "unavailable": grayscale(100%) drop-shadow(0px 0px 2px Red)
      "Today": drop-shadow(0px 0px 3px Blue) saturate(200%)
      "Tomorrow": drop-shadow(0px 0px 3px Blue) saturate(150%)
    style:
      top: 65%
      left: 85%
      width: 15%
  - type: state-label
    entity: sensor.blue_bin_days
    tap_action:
      action: none
    hold_action:
      action: none
    style:
      top: 35%
      left: 85%
```

### Additional information

Similar issue (Closed)
https://github.com/home-assistant/frontend/issues/9968
